INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H40.001', 'Preglaucoma, no especificado, ojo derecho', 'Sin especificar', '["riesgo de glaucoma", "ojo derecho", "presión ocular alta", "sospecha de glaucoma", "chequeo visual", "visión borrosa", "tensión ocular", "ojo rojo", "dolor ocular", "revisión oftalmológica", "posible glaucoma", "prevenir ceguera"]'),
('H40.002', 'Preglaucoma, no especificado, ojo izquierdo', 'Sin especificar', '["riesgo de glaucoma", "ojo izquierdo", "presión ocular alta", "sospecha de glaucoma", "chequeo visual", "visión borrosa", "tensión ocular", "ojo rojo", "dolor ocular", "revisión oftalmológica", "posible glaucoma", "prevenir ceguera"]'),
('H40.003', 'Preglaucoma, no especificado, bilateral', 'Sin especificar', '["riesgo de glaucoma", "ambos ojos", "presión ocular alta", "sospecha de glaucoma", "chequeo visual", "visión borrosa", "tensión ocular", "ojo rojo", "dolor ocular", "revisión oftalmológica", "posible glaucoma", "prevenir ceguera"]'),
('H40.009', 'Preglaucoma, no especificado, ojo no especificado', 'Sin especificar', '["riesgo de glaucoma", "sospecha de ceguera", "tensión en el ojo", "presión alta", "visión que se pierde", "ojo con problemas", "dolor en los ojos", "halos de luz", "chequeo de vista", "examen de presión ocular"]'),
('H40.011', 'Ángulo abierto con resultados dudosos, bajo riesgo, ojo derecho', 'Sin especificar', '["ojo derecho", "glaucoma inicial", "presión del ojo", "duda diagnóstica", "ojo abierto", "revisión del nervio óptico", "control ocular", "visión borrosa", "ceguera silenciosa", "tamizaje glaucoma"]'),
('H40.012', 'Ángulo abierto con resultados dudosos, bajo riesgo, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "glaucoma inicial", "presión del ojo", "duda diagnóstica", "ojo abierto", "revisión del nervio óptico", "control ocular", "visión borrosa", "ceguera silenciosa", "tamizaje glaucoma"]'),
('H40.013', 'Ángulo abierto con resultados dudosos, bajo riesgo, bilateral', 'Sin especificar', '["ambos ojos", "glaucoma inicial", "presión del ojo", "duda diagnóstica", "ojo abierto", "revisión del nervio óptico", "control ocular", "visión borrosa", "ceguera silenciosa", "tamizaje glaucoma"]'),
('H40.019', 'Ángulo abierto con resultados dudosos, bajo riesgo, ojo no especificado', 'Sin especificar', '["duda diagnóstica", "bajo riesgo de glaucoma", "tensión ocular", "nervio óptico dañado", "revisión de la vista", "chequeo oftalmológico", "posible glaucoma abierto"]'),
('H40.021', 'Ángulo abierto con resultados dudosos, alto riesgo, ojo derecho', 'Sin especificar', '["ojo derecho", "alto riesgo de glaucoma", "presión ocular alta", "daño en el ojo", "sospecha de ceguera", "visión borrosa", "pérdida de campo visual", "nervio óptico en peligro"]'),
('H40.022', 'Ángulo abierto con resultados dudosos, alto riesgo, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "alto riesgo de glaucoma", "presión ocular alta", "daño en el ojo", "sospecha de ceguera", "visión borrosa", "pérdida de campo visual", "nervio óptico en peligro"]'),
('H40.023', 'Ángulo abierto con resultados dudosos, alto riesgo, bilateral', 'Sin especificar', '["ambos ojos", "alto riesgo de glaucoma", "presión ocular alta", "daño en el ojo", "sospecha de ceguera", "visión borrosa", "pérdida de campo visual", "nervio óptico en peligro"]'),
('H40.029', 'Ángulo abierto con resultados dudosos, alto riesgo, ojo no especificado', 'Sin especificar', '["urgencia oftalmológica", "riesgo alto de glaucoma", "presión ocular", "nervio óptico", "problemas de vista", "chequeo urgente", "posible daño ocular"]'),
('H40.031', 'Ángulo anatómico estrecho, ojo derecho', 'Sin especificar', '["ojo derecho", "ángulo estrecho", "glaucoma de ángulo cerrado", "ojo cerrado", "dolor en el ojo", "visión de halos", "presión ocular", "riesgo de ataque de glaucoma"]'),
('H40.032', 'Ángulo anatómico estrecho, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "ángulo estrecho", "glaucoma de ángulo cerrado", "ojo cerrado", "dolor en el ojo", "visión de halos", "presión ocular", "riesgo de ataque de glaucoma"]'),
('H40.033', 'Ángulo anatómico estrecho, bilateral', 'Sin especificar', '["ambos ojos", "ángulo estrecho", "glaucoma de ángulo cerrado", "ojo cerrado", "dolor en el ojo", "visión de halos", "presión ocular", "riesgo de ataque de glaucoma"]'),
('H40.039', 'Ángulo anatómico estrecho, ojo no especificado', 'Sin especificar', '["ángulo cerrado", "presión alta", "dolor ocular", "ceguera potencial", "halos", "ojos estrechos", "revisión de ángulo", "gonioscopia"]'),
('H40.041', 'Que responde a los esteroides, ojo derecho', 'Sin especificar', '["ojo derecho", "glaucoma por cortisona", "presión por esteroides", "reacción a gotas", "presión ocular alta por medicamentos", "glaucoma medicamentoso"]'),
('H40.042', 'Que responde a los esteroides, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "glaucoma por cortisona", "presión por esteroides", "reacción a gotas", "presión ocular alta por medicamentos", "glaucoma medicamentoso"]'),
('H40.043', 'Que responde a los esteroides, bilateral', 'Sin especificar', '["ambos ojos", "glaucoma por cortisona", "presión por esteroides", "reacción a gotas", "presión ocular alta por medicamentos", "glaucoma medicamentoso"]'),
('H40.049', 'Que responde a los esteroides, ojo no especificado', 'Sin especificar', '["glaucoma por gotas", "esteroides y ojos", "presión subió por medicación", "problemas de ojos por corticoides", "reacción adversa a gotas"]'),
('H40.051', 'Hipertensión ocular, ojo derecho', 'Sin especificar', '["ojo derecho", "presión alta en el ojo", "tensión ocular alta", "ojo tenso", "ojo duro", "riesgo de glaucoma", "control de presión del ojo"]'),
('H40.052', 'Hipertensión ocular, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "presión alta en el ojo", "tensión ocular alta", "ojo tenso", "ojo duro", "riesgo de glaucoma", "control de presión del ojo"]'),
('H40.053', 'Hipertensión ocular, bilateral', 'Sin especificar', '["ambos ojos", "presión alta en el ojo", "tensión ocular alta", "ojo tenso", "ojo duro", "riesgo de glaucoma", "control de presión del ojo"]'),
('H40.059', 'Hipertensión ocular, ojo no especificado', 'Sin especificar', '["hipertensión del ojo", "ojo tenso", "presión ocular elevada", "tensión alta en la vista", "peligro de glaucoma", "chequeo de presión"]'),
('H40.061', 'Ángulo cerrado primario sin daño por glaucoma, ojo derecho', 'Sin especificar', '["ojo derecho", "ángulo cerrado", "sospecha de glaucoma", "ojo en peligro", "bloqueo de drenaje ocular", "sin daño", "revisión oftalmológica"]'),
('H40.062', 'Ángulo cerrado primario sin daño por glaucoma, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "ángulo cerrado", "sospecha de glaucoma", "ojo en peligro", "bloqueo de drenaje ocular", "sin daño", "revisión oftalmológica"]'),
('H40.063', 'Ángulo cerrado primario sin daño por glaucoma, bilateral', 'Sin especificar', '["ambos ojos", "ángulo cerrado", "sospecha de glaucoma", "ojo en peligro", "bloqueo de drenaje ocular", "sin daño", "revisión oftalmológica"]'),
('H40.069', 'Ángulo cerrado primario sin daño por glaucoma, ojo no especificado', 'Sin especificar', '["ángulo cerrado primario", "presión ocular alta", "bloqueo ocular", "drenaje del ojo", "gonioscopia", "revisión de ángulo", "prevención de glaucoma"]'),
('H40.10X0', 'Glaucoma de ángulo abierto no especificado, estadio no especificado', 'Sin especificar', '["glaucoma", "ojo que pierde vista", "presión alta en el ojo", "nervio óptico afectado", "ceguera silenciosa", "visión túnel", "pérdida de vista", "glaucoma primario"]'),
('H40.10X1', 'Glaucoma de ángulo abierto no especificado, estadio leve', 'Sin especificar', '["glaucoma leve", "principio de glaucoma", "pérdida de visión inicial", "tensión ocular", "chequeo de vista", "glaucoma ángulo abierto", "revisión", "seguimiento"]'),
('H40.10X2', 'Glaucoma de ángulo abierto no especificado, estadio moderado', 'Sin especificar', '["glaucoma moderado", "problemas de visión", "pérdida de campo visual", "presión en el ojo", "glaucoma en progreso", "seguimiento de glaucoma"]'),
('H40.10X3', 'Glaucoma de ángulo abierto no especificado, estadio grave', 'Sin especificar', '["glaucoma avanzado", "glaucoma grave", "pérdida severa de vista", "casi ceguera", "daño irreversible", "nervio óptico destruido", "pérdida de visión periférica"]'),
('H40.10X4', 'Glaucoma de ángulo abierto no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma en estudio", "problema visual", "daño ocular no claro", "glaucoma sin especificar", "revisión oftalmológica"]'),
('H40.1110', 'Glaucoma primario de ángulo abierto, ojo derecho, estadio no especificado', 'Sin especificar', '["ojo derecho", "glaucoma primario", "ángulo abierto", "tensión ocular", "daño al nervio", "pérdida de visión", "glaucoma", "ceguera"]'),
('H40.1111', 'Glaucoma primario de ángulo abierto, ojo derecho, estadio leve', 'Sin especificar', '["ojo derecho", "glaucoma inicial", "pérdida de vista leve", "tensión ocular", "control", "seguimiento de glaucoma"]'),
('H40.1112', 'Glaucoma primario de ángulo abierto, ojo derecho, estadio moderado', 'Sin especificar', '["ojo derecho", "glaucoma avanzado", "visión con pérdida", "presión en el ojo", "daño moderado", "campo visual"]'),
('H40.1113', 'Glaucoma primario de ángulo abierto, ojo derecho, estadio grave', 'Sin especificar', '["ojo derecho", "glaucoma grave", "pérdida severa", "visión túnel", "daño al nervio óptico", "glaucoma severo"]'),
('H40.1114', 'Glaucoma primario de ángulo abierto, ojo derecho, estadio indeterminado', 'Sin especificar', '["ojo derecho", "glaucoma", "estadio incierto", "revisión oftalmológica", "daño ocular"]'),
('H40.1120', 'Glaucoma primario de ángulo abierto, ojo izquierdo, estadio no especificado', 'Sin especificar', '["ojo izquierdo", "glaucoma primario", "ángulo abierto", "tensión ocular", "daño al nervio", "pérdida de visión", "glaucoma", "ceguera"]'),
('H40.1121', 'Glaucoma primario de ángulo abierto, ojo izquierdo, estadio leve', 'Sin especificar', '["ojo izquierdo", "glaucoma inicial", "pérdida de vista leve", "tensión ocular", "control", "seguimiento de glaucoma"]'),
('H40.1122', 'Glaucoma primario de ángulo abierto, ojo izquierdo, estadio moderado', 'Sin especificar', '["ojo izquierdo", "glaucoma avanzado", "visión con pérdida", "presión en el ojo", "daño moderado", "campo visual"]'),
('H40.1123', 'Glaucoma primario de ángulo abierto, ojo izquierdo, estadio grave', 'Sin especificar', '["ojo izquierdo", "glaucoma grave", "pérdida severa", "visión túnel", "daño al nervio óptico", "glaucoma severo"]'),
('H40.1124', 'Glaucoma primario de ángulo abierto, ojo izquierdo, estadio indeterminado', 'Sin especificar', '["ojo izquierdo", "glaucoma", "estadio incierto", "revisión oftalmológica", "daño ocular"]'),
('H40.1130', 'Glaucoma primario de ángulo abierto, bilateral, estadio no especificado', 'Sin especificar', '["ambos ojos", "glaucoma primario", "ceguera progresiva", "presión en los ojos", "daño visual", "nervio óptico", "glaucoma"]'),
('H40.1131', 'Glaucoma primario de ángulo abierto, bilateral, estadio leve', 'Sin especificar', '["ambos ojos", "glaucoma leve", "inicio de ceguera", "revisión ocular", "tensión ocular alta"]'),
('H40.1132', 'Glaucoma primario de ángulo abierto, bilateral, estadio moderado', 'Sin especificar', '["ambos ojos", "glaucoma moderado", "pérdida de vista", "presión alta", "campo visual reducido"]'),
('H40.1133', 'Glaucoma primario de ángulo abierto, bilateral, estadio grave', 'Sin especificar', '["ambos ojos", "glaucoma grave", "pérdida severa de visión", "ceguera", "daño avanzado", "visión túnel"]'),
('H40.1134', 'Glaucoma primario de ángulo abierto, bilateral, estadio indeterminado', 'Sin especificar', '["ambos ojos", "glaucoma", "estadio no definido", "revisión de vista", "problemas de nervio óptico"]'),
('H40.1190', 'Glaucoma primario de ángulo abierto, ojo no especificado, estadio no especificado', 'Sin especificar', '["glaucoma", "problema de visión", "tensión del ojo", "revisión de glaucoma", "nervio óptico afectado"]'),
('H40.1191', 'Glaucoma primario de ángulo abierto, ojo no especificado, estadio leve', 'Sin especificar', '["glaucoma inicial", "pérdida visual mínima", "chequeo de presión", "revisión de vista", "glaucoma leve"]'),
('H40.1192', 'Glaucoma primario de ángulo abierto, ojo no especificado, estadio moderado', 'Sin especificar', '["glaucoma moderado", "pérdida visual", "tensión en el ojo", "daño al nervio", "problemas de campo visual"]'),
('H40.1193', 'Glaucoma primario de ángulo abierto, ojo no especificado, estadio grave', 'Sin especificar', '["glaucoma grave", "pérdida severa de vista", "ceguera", "daño avanzado", "visión muy reducida"]'),
('H40.1194', 'Glaucoma primario de ángulo abierto, ojo no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma", "estadio desconocido", "problema ocular", "revisión oftalmológica", "nervio óptico en estudio"]'),
('H40.1210', 'Glaucoma de baja tensión, ojo derecho, estadio no especificado', 'Sin especificar', '["ojo derecho", "glaucoma de presión normal", "glaucoma de baja presión", "problemas visuales sin presión alta", "daño nervio óptico"]'),
('H40.1211', 'Glaucoma de baja tensión, ojo derecho, estadio leve', 'Sin especificar', '["ojo derecho", "glaucoma presión baja", "daño inicial", "revisión oftalmológica", "control de nervio óptico"]'),
('H40.1212', 'Glaucoma de baja tensión, ojo derecho, estadio moderado', 'Sin especificar', '["ojo derecho", "glaucoma presión baja", "daño moderado", "pérdida de campo visual", "nervio óptico afectado"]'),
('H40.1213', 'Glaucoma de baja tensión, ojo derecho, estadio grave', 'Sin especificar', '["ojo derecho", "glaucoma presión baja", "daño severo", "pérdida de visión importante", "nervio óptico dañado"]'),
('H40.1214', 'Glaucoma de baja tensión, ojo derecho, estadio indeterminado', 'Sin especificar', '["ojo derecho", "glaucoma presión baja", "estadio no claro", "revisión de vista", "problemas visuales"]'),
('H40.1220', 'Glaucoma de baja tensión, ojo izquierdo, estadio no especificado', 'Sin especificar', '["ojo izquierdo", "glaucoma de presión normal", "glaucoma de baja presión", "problemas visuales sin presión alta", "daño nervio óptico"]'),
('H40.1221', 'Glaucoma de baja tensión, ojo izquierdo, estadio leve', 'Sin especificar', '["ojo izquierdo", "glaucoma presión baja", "daño inicial", "revisión oftalmológica", "control de nervio óptico"]'),
('H40.1222', 'Glaucoma de baja tensión, ojo izquierdo, estadio moderado', 'Sin especificar', '["ojo izquierdo", "glaucoma presión baja", "daño moderado", "pérdida de campo visual", "nervio óptico afectado"]'),
('H40.1223', 'Glaucoma de baja tensión, ojo izquierdo, estadio grave', 'Sin especificar', '["ojo izquierdo", "glaucoma presión baja", "daño severo", "pérdida de visión importante", "nervio óptico dañado"]'),
('H40.1224', 'Glaucoma de baja tensión, ojo izquierdo, estadio indeterminado', 'Sin especificar', '["ojo izquierdo", "glaucoma presión baja", "estadio no claro", "revisión de vista", "problemas visuales"]'),
('H40.1230', 'Glaucoma de baja tensión, bilateral, estadio no especificado', 'Sin especificar', '["ambos ojos", "glaucoma baja presión", "glaucoma presión normal", "problemas nervio óptico", "pérdida de visión"]'),
('H40.1231', 'Glaucoma de baja tensión, bilateral, estadio leve', 'Sin especificar', '["ambos ojos", "glaucoma presión baja", "etapa leve", "control visual", "revisión"]'),
('H40.1232', 'Glaucoma de baja tensión, bilateral, estadio moderado', 'Sin especificar', '["ambos ojos", "glaucoma presión baja", "daño moderado", "campo visual reducido", "nervio óptico"]'),
('H40.1233', 'Glaucoma de baja tensión, bilateral, estadio grave', 'Sin especificar', '["ambos ojos", "glaucoma presión baja", "daño severo", "ceguera", "pérdida de vista profunda"]'),
('H40.1234', 'Glaucoma de baja tensión, bilateral, estadio indeterminado', 'Sin especificar', '["ambos ojos", "glaucoma presión baja", "estadio incierto", "estudios oftalmológicos"]'),
('H40.1290', 'Glaucoma de baja tensión, ojo no especificado, estadio no especificado', 'Sin especificar', '["glaucoma presión baja", "problema visual", "revisión oftalmológica", "glaucoma normotensivo"]'),
('H40.1291', 'Glaucoma de baja tensión, ojo no especificado, estadio leve', 'Sin especificar', '["glaucoma presión baja", "daño leve", "seguimiento oftalmológico"]'),
('H40.1292', 'Glaucoma de baja tensión, ojo no especificado, estadio moderado', 'Sin especificar', '["glaucoma presión baja", "daño moderado", "pérdida visual"]'),
('H40.1293', 'Glaucoma de baja tensión, ojo no especificado, estadio grave', 'Sin especificar', '["glaucoma presión baja", "daño avanzado", "pérdida de vista"]'),
('H40.1294', 'Glaucoma de baja tensión, ojo no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma presión baja", "estadio en estudio", "problema ocular"]'),
('H40.1310', 'Glaucoma pigmentario, ojo derecho, estadio no especificado', 'Sin especificar', '["ojo derecho", "glaucoma por pigmento", "síndrome de dispersión pigmentaria", "problema de drenaje", "presión alta", "pérdida de vista"]'),
('H40.1311', 'Glaucoma pigmentario, ojo derecho, estadio leve', 'Sin especificar', '["ojo derecho", "glaucoma pigmentario", "etapa leve", "dispersión de pigmento", "revisión de vista"]'),
('H40.1312', 'Glaucoma pigmentario, ojo derecho, estadio moderado', 'Sin especificar', '["ojo derecho", "glaucoma pigmentario", "daño moderado", "presión ocular", "nervio óptico"]'),
('H40.1313', 'Glaucoma pigmentario, ojo derecho, estadio grave', 'Sin especificar', '["ojo derecho", "glaucoma pigmentario", "daño grave", "pérdida severa de visión", "glaucoma avanzado"]'),
('H40.1314', 'Glaucoma pigmentario, ojo derecho, estadio indeterminado', 'Sin especificar', '["ojo derecho", "glaucoma pigmentario", "estadio no claro", "estudios del ojo"]'),
('H40.1320', 'Glaucoma pigmentario, ojo izquierdo, estadio no especificado', 'Sin especificar', '["ojo izquierdo", "glaucoma por pigmento", "síndrome de dispersión pigmentaria", "problema de drenaje", "presión alta", "pérdida de vista"]'),
('H40.1321', 'Glaucoma pigmentario, ojo izquierdo, estadio leve', 'Sin especificar', '["ojo izquierdo", "glaucoma pigmentario", "etapa leve", "dispersión de pigmento", "revisión de vista"]'),
('H40.1322', 'Glaucoma pigmentario, ojo izquierdo, estadio moderado', 'Sin especificar', '["ojo izquierdo", "glaucoma pigmentario", "daño moderado", "presión ocular", "nervio óptico"]'),
('H40.1323', 'Glaucoma pigmentario, ojo izquierdo, estadio grave', 'Sin especificar', '["ojo izquierdo", "glaucoma pigmentario", "daño grave", "pérdida severa de visión", "glaucoma avanzado"]'),
('H40.1324', 'Glaucoma pigmentario, ojo izquierdo, estadio indeterminado', 'Sin especificar', '["ojo izquierdo", "glaucoma pigmentario", "estadio no claro", "estudios del ojo"]'),
('H40.1330', 'Glaucoma pigmentario, bilateral, estadio no especificado', 'Sin especificar', '["ambos ojos", "dispersión de pigmento", "glaucoma", "presión alta", "daño en ojos"]'),
('H40.1331', 'Glaucoma pigmentario, bilateral, estadio leve', 'Sin especificar', '["ambos ojos", "glaucoma pigmentario", "estadio leve", "control", "ojos"]'),
('H40.1332', 'Glaucoma pigmentario, bilateral, estadio moderado', 'Sin especificar', '["ambos ojos", "glaucoma pigmentario", "daño moderado", "pérdida visión", "nervio óptico"]'),
('H40.1333', 'Glaucoma pigmentario, bilateral, estadio grave', 'Sin especificar', '["ambos ojos", "glaucoma pigmentario", "daño grave", "pérdida severa", "ceguera"]'),
('H40.1334', 'Glaucoma pigmentario, bilateral, estadio indeterminado', 'Sin especificar', '["ambos ojos", "glaucoma pigmentario", "estadio indefinido", "revisión"]'),
('H40.1390', 'Glaucoma pigmentario, ojo no especificado, estadio no especificado', 'Sin especificar', '["glaucoma pigmentario", "problema ocular", "presión", "drenaje del ojo"]'),
('H40.1391', 'Glaucoma pigmentario, ojo no especificado, estadio leve', 'Sin especificar', '["glaucoma pigmentario", "leve", "revisión oftalmológica"]'),
('H40.1392', 'Glaucoma pigmentario, ojo no especificado, estadio moderado', 'Sin especificar', '["glaucoma pigmentario", "moderado", "pérdida de visión"]'),
('H40.1393', 'Glaucoma pigmentario, ojo no especificado, estadio grave', 'Sin especificar', '["glaucoma pigmentario", "grave", "daño severo"]'),
('H40.1394', 'Glaucoma pigmentario, ojo no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma pigmentario", "estudio", "ojo"]'),
('H40.1410', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo derecho, estadio no especificado', 'Sin especificar', '["ojo derecho", "pseudoexfoliación", "glaucoma capsular", "cristalino", "problema de ojo", "presión"]'),
('H40.1411', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo derecho, estadio leve', 'Sin especificar', '["ojo derecho", "pseudoexfoliación", "glaucoma leve", "estadio inicial"]'),
('H40.1412', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo derecho, estadio moderado', 'Sin especificar', '["ojo derecho", "pseudoexfoliación", "glaucoma moderado", "daño visual"]'),
('H40.1413', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo derecho, estadio grave', 'Sin especificar', '["ojo derecho", "pseudoexfoliación", "glaucoma grave", "daño avanzado"]'),
('H40.1414', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo derecho, estadio indeterminado', 'Sin especificar', '["ojo derecho", "pseudoexfoliación", "estadio en estudio"]'),
('H40.1420', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo izquierdo, estadio no especificado', 'Sin especificar', '["ojo izquierdo", "pseudoexfoliación", "glaucoma capsular", "cristalino", "problema de ojo", "presión"]'),
('H40.1421', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo izquierdo, estadio leve', 'Sin especificar', '["ojo izquierdo", "pseudoexfoliación", "glaucoma leve", "estadio inicial"]'),
('H40.1422', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo izquierdo, estadio moderado', 'Sin especificar', '["ojo izquierdo", "pseudoexfoliación", "glaucoma moderado", "daño visual"]'),
('H40.1423', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo izquierdo, estadio grave', 'Sin especificar', '["ojo izquierdo", "pseudoexfoliación", "glaucoma grave", "daño avanzado"]'),
('H40.1424', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo izquierdo, estadio indeterminado', 'Sin especificar', '["ojo izquierdo", "pseudoexfoliación", "estadio en estudio"]'),
('H40.1430', 'Glaucoma capsular con seudoexfoliación de cristalino, bilateral, estadio no especificado', 'Sin especificar', '["ambos ojos", "pseudoexfoliación", "glaucoma capsular", "problema del cristalino"]'),
('H40.1431', 'Glaucoma capsular con seudoexfoliación de cristalino, bilateral, estadio leve', 'Sin especificar', '["ambos ojos", "pseudoexfoliación", "glaucoma leve", "revisión"]'),
('H40.1432', 'Glaucoma capsular con seudoexfoliación de cristalino, bilateral, estadio moderado', 'Sin especificar', '["ambos ojos", "pseudoexfoliación", "glaucoma moderado", "campo visual"]'),
('H40.1433', 'Glaucoma capsular con seudoexfoliación de cristalino, bilateral, estadio grave', 'Sin especificar', '["ambos ojos", "pseudoexfoliación", "glaucoma grave", "ceguera"]'),
('H40.1434', 'Glaucoma capsular con seudoexfoliación de cristalino, bilateral, estadio indeterminado', 'Sin especificar', '["ambos ojos", "pseudoexfoliación", "revisión oftalmológica"]'),
('H40.1490', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo no especificado, estadio no especificado', 'Sin especificar', '["glaucoma", "seudoexfoliación", "cristalino", "problema visual"]'),
('H40.1491', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo no especificado, estadio leve', 'Sin especificar', '["glaucoma", "seudoexfoliación", "leve", "seguimiento"]'),
('H40.1492', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo no especificado, estadio moderado', 'Sin especificar', '["glaucoma", "seudoexfoliación", "moderado", "daño visual"]'),
('H40.1493', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo no especificado, estadio grave', 'Sin especificar', '["glaucoma", "seudoexfoliación", "grave", "pérdida de visión"]'),
('H40.1494', 'Glaucoma capsular con seudoexfoliación de cristalino, ojo no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma", "seudoexfoliación", "estadio desconocido"]'),
('H40.151', 'Fase residual de glaucoma de ángulo abierto, ojo derecho', 'Sin especificar', '["ojo derecho", "glaucoma residual", "secuela de glaucoma", "ojo afectado por glaucoma pasado", "revisión"]'),
('H40.152', 'Fase residual de glaucoma de ángulo abierto, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "glaucoma residual", "secuela de glaucoma", "ojo afectado por glaucoma pasado", "revisión"]'),
('H40.153', 'Fase residual de glaucoma de ángulo abierto, bilateral', 'Sin especificar', '["ambos ojos", "glaucoma residual", "daño previo por glaucoma", "control"]'),
('H40.159', 'Fase residual de glaucoma de ángulo abierto, ojo no especificado', 'Sin especificar', '["glaucoma residual", "secuela", "ojo", "daño crónico"]'),
('H40.20X0', 'Glaucoma primario de ángulo cerrado no especificado, estadio no especificado', 'Sin especificar', '["glaucoma ángulo cerrado", "ataque de glaucoma", "ojo peligro", "presión ocular alta", "dolor ojo", "urgencia"]'),
('H40.20X1', 'Glaucoma primario de ángulo cerrado no especificado, estadio leve', 'Sin especificar', '["glaucoma ángulo cerrado", "estadio inicial", "revisión urgente"]'),
('H40.20X2', 'Glaucoma primario de ángulo cerrado no especificado, estadio moderado', 'Sin especificar', '["glaucoma ángulo cerrado", "moderado", "daño nervio"]'),
('H40.20X3', 'Glaucoma primario de ángulo cerrado no especificado, estadio grave', 'Sin especificar', '["glaucoma ángulo cerrado", "grave", "pérdida severa vista"]'),
('H40.20X4', 'Glaucoma primario de ángulo cerrado no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma ángulo cerrado", "estudio", "revisión"]'),
('H40.211', 'Glaucoma agudo de ángulo cerrado, ojo derecho', 'Sin especificar', '["ojo derecho", "glaucoma agudo", "dolor intenso ojo", "urgencia oftálmica", "náuseas por ojo", "ojo rojo", "visión borrosa"]'),
('H40.212', 'Glaucoma agudo de ángulo cerrado, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "glaucoma agudo", "dolor intenso ojo", "urgencia oftálmica", "náuseas por ojo", "ojo rojo", "visión borrosa"]'),
('H40.213', 'Glaucoma agudo de ángulo cerrado, bilateral', 'Sin especificar', '["ambos ojos", "glaucoma agudo", "dolor intenso", "urgencia", "ceguera inmediata", "presión altísima"]'),
('H40.219', 'Glaucoma agudo de ángulo cerrado, ojo no especificado', 'Sin especificar', '["glaucoma agudo", "urgencia ocular", "dolor de cabeza por ojo", "ceguera súbita"]'),
('H40.2210', 'Glaucoma crónico de ángulo cerrado, ojo derecho, estadio no especificado', 'Sin especificar', '["ojo derecho", "glaucoma crónico", "ángulo cerrado", "presión ocular alta", "ceguera silenciosa"]'),
('H40.2211', 'Glaucoma crónico de ángulo cerrado, ojo derecho, estadio leve', 'Sin especificar', '["ojo derecho", "glaucoma crónico", "leve", "revisión"]'),
('H40.2212', 'Glaucoma crónico de ángulo cerrado, ojo derecho, estadio moderado', 'Sin especificar', '["ojo derecho", "glaucoma crónico", "moderado", "daño visual"]'),
('H40.2213', 'Glaucoma crónico de ángulo cerrado, ojo derecho, estadio grave', 'Sin especificar', '["ojo derecho", "glaucoma crónico", "grave", "pérdida vista"]'),
('H40.2214', 'Glaucoma crónico de ángulo cerrado, ojo derecho, estadio indeterminado', 'Sin especificar', '["ojo derecho", "glaucoma crónico", "estudio"]'),
('H40.2220', 'Glaucoma crónico de ángulo cerrado, ojo izquierdo, estadio no especificado', 'Sin especificar', '["ojo izquierdo", "glaucoma crónico", "ángulo cerrado", "presión ocular alta", "ceguera silenciosa"]'),
('H40.2221', 'Glaucoma crónico de ángulo cerrado, ojo izquierdo, estadio leve', 'Sin especificar', '["ojo izquierdo", "glaucoma crónico", "leve", "revisión"]'),
('H40.2222', 'Glaucoma crónico de ángulo cerrado, ojo izquierdo, estadio moderado', 'Sin especificar', '["ojo izquierdo", "glaucoma crónico", "moderado", "daño visual"]'),
('H40.2223', 'Glaucoma crónico de ángulo cerrado, ojo izquierdo, estadio grave', 'Sin especificar', '["ojo izquierdo", "glaucoma crónico", "grave", "pérdida vista"]'),
('H40.2224', 'Glaucoma crónico de ángulo cerrado, ojo izquierdo, estadio indeterminado', 'Sin especificar', '["ojo izquierdo", "glaucoma crónico", "estudio"]'),
('H40.2230', 'Glaucoma crónico de ángulo cerrado, bilateral, estadio no especificado', 'Sin especificar', '["ambos ojos", "glaucoma crónico", "ángulo cerrado", "problema persistente"]'),
('H40.2231', 'Glaucoma crónico de ángulo cerrado, bilateral, estadio leve', 'Sin especificar', '["ambos ojos", "glaucoma crónico", "leve", "control"]'),
('H40.2232', 'Glaucoma crónico de ángulo cerrado, bilateral, estadio moderado', 'Sin especificar', '["ambos ojos", "glaucoma crónico", "moderado", "daño nervio"]'),
('H40.2233', 'Glaucoma crónico de ángulo cerrado, bilateral, estadio grave', 'Sin especificar', '["ambos ojos", "glaucoma crónico", "grave", "ceguera"]'),
('H40.2234', 'Glaucoma crónico de ángulo cerrado, bilateral, estadio indeterminado', 'Sin especificar', '["ambos ojos", "glaucoma crónico", "estudio"]'),
('H40.2290', 'Glaucoma crónico de ángulo cerrado, ojo no especificado, estadio no especificado', 'Sin especificar', '["glaucoma crónico", "ángulo cerrado", "revisión"]'),
('H40.2291', 'Glaucoma crónico de ángulo cerrado, ojo no especificado, estadio leve', 'Sin especificar', '["glaucoma crónico", "leve", "seguimiento"]'),
('H40.2292', 'Glaucoma crónico de ángulo cerrado, ojo no especificado, estadio moderado', 'Sin especificar', '["glaucoma crónico", "moderado", "pérdida campo"]'),
('H40.2293', 'Glaucoma crónico de ángulo cerrado, ojo no especificado, estadio grave', 'Sin especificar', '["glaucoma crónico", "grave", "daño avanzado"]'),
('H40.2294', 'Glaucoma crónico de ángulo cerrado, ojo no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma crónico", "estudio", "ojo"]'),
('H40.231', 'Glaucoma intermitente de ángulo cerrado, ojo derecho', 'Sin especificar', '["ojo derecho", "glaucoma de ángulos intermitentes", "dolor ojo por ratos", "visión borrosa pasajera"]'),
('H40.232', 'Glaucoma intermitente de ángulo cerrado, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "glaucoma de ángulos intermitentes", "dolor ojo por ratos", "visión borrosa pasajera"]'),
('H40.233', 'Glaucoma intermitente de ángulo cerrado, bilateral', 'Sin especificar', '["ambos ojos", "glaucoma intermitente", "dolor ocular que viene y va"]'),
('H40.239', 'Glaucoma intermitente de ángulo cerrado, ojo no especificado', 'Sin especificar', '["glaucoma intermitente", "problema ángulo", "revisión"]'),
('H40.241', 'Fase residual de glaucoma de ángulo cerrado, ojo derecho', 'Sin especificar', '["ojo derecho", "secuela glaucoma ángulo cerrado", "fase residual"]'),
('H40.242', 'Fase residual de glaucoma de ángulo cerrado, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "secuela glaucoma ángulo cerrado", "fase residual"]'),
('H40.243', 'Fase residual de glaucoma de ángulo cerrado, bilateral', 'Sin especificar', '["ambos ojos", "secuela glaucoma", "fase residual"]'),
('H40.249', 'Fase residual de glaucoma de ángulo cerrado, ojo no especificado', 'Sin especificar', '["glaucoma", "fase residual", "ojo"]'),
('H40.30X0', 'Glaucoma secundario a traumatismo ocular, ojo no especificado, estadio no especificado', 'Sin especificar', '["glaucoma por golpe", "trauma ocular", "glaucoma traumático", "golpe en el ojo"]'),
('H40.30X1', 'Glaucoma secundario a traumatismo ocular, ojo no especificado, estadio leve', 'Sin especificar', '["glaucoma por golpe", "leve", "trauma"]'),
('H40.30X2', 'Glaucoma secundario a traumatismo ocular, ojo no especificado, estadio moderado', 'Sin especificar', '["glaucoma por golpe", "moderado", "trauma"]'),
('H40.30X3', 'Glaucoma secundario a traumatismo ocular, ojo no especificado, estadio grave', 'Sin especificar', '["glaucoma por golpe", "grave", "trauma"]'),
('H40.30X4', 'Glaucoma secundario a traumatismo ocular, ojo no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma por golpe", "indeterminado", "trauma"]'),
('H40.31X0', 'Glaucoma secundario a traumatismo ocular, ojo derecho, estadio no especificado', 'Sin especificar', '["ojo derecho", "glaucoma por trauma", "golpe", "presión"]'),
('H40.31X1', 'Glaucoma secundario a traumatismo ocular, ojo derecho, estadio leve', 'Sin especificar', '["ojo derecho", "trauma ocular", "leve"]'),
('H40.31X2', 'Glaucoma secundario a traumatismo ocular, ojo derecho, estadio moderado', 'Sin especificar', '["ojo derecho", "trauma ocular", "moderado"]'),
('H40.31X3', 'Glaucoma secundario a traumatismo ocular, ojo derecho, estadio grave', 'Sin especificar', '["ojo derecho", "trauma ocular", "grave"]'),
('H40.31X4', 'Glaucoma secundario a traumatismo ocular, ojo derecho, estadio indeterminado', 'Sin especificar', '["ojo derecho", "trauma ocular", "estudio"]'),
('H40.32X0', 'Glaucoma secundario a traumatismo ocular, ojo izquierdo, estadio no especificado', 'Sin especificar', '["ojo izquierdo", "glaucoma por trauma", "golpe", "presión"]'),
('H40.32X1', 'Glaucoma secundario a traumatismo ocular, ojo izquierdo, estadio leve', 'Sin especificar', '["ojo izquierdo", "trauma ocular", "leve"]'),
('H40.32X2', 'Glaucoma secundario a traumatismo ocular, ojo izquierdo, estadio moderado', 'Sin especificar', '["ojo izquierdo", "trauma ocular", "moderado"]'),
('H40.32X3', 'Glaucoma secundario a traumatismo ocular, ojo izquierdo, estadio grave', 'Sin especificar', '["ojo izquierdo", "trauma ocular", "grave"]'),
('H40.32X4', 'Glaucoma secundario a traumatismo ocular, ojo izquierdo, estadio indeterminado', 'Sin especificar', '["ojo izquierdo", "trauma ocular", "estudio"]'),
('H40.33X0', 'Glaucoma secundario a traumatismo ocular, bilateral, estadio no especificado', 'Sin especificar', '["ambos ojos", "golpe en ojos", "traumatismo", "glaucoma"]'),
('H40.33X1', 'Glaucoma secundario a traumatismo ocular, bilateral, estadio leve', 'Sin especificar', '["ambos ojos", "traumatismo", "glaucoma", "leve"]'),
('H40.33X2', 'Glaucoma secundario a traumatismo ocular, bilateral, estadio moderado', 'Sin especificar', '["ambos ojos", "traumatismo", "glaucoma", "moderado"]'),
('H40.33X3', 'Glaucoma secundario a traumatismo ocular, bilateral, estadio grave', 'Sin especificar', '["ambos ojos", "traumatismo", "glaucoma", "grave"]'),
('H40.40X0', 'Glaucoma secundario a inflamación ocular, ojo no especificado, estadio no especificado', 'Sin especificar', '["glaucoma por inflamación", "uveitis", "ojo rojo e inflamado", "presión alta"]'),
('H40.40X1', 'Glaucoma secundario a inflamación ocular, ojo no especificado, estadio leve', 'Sin especificar', '["inflamación ojo", "glaucoma leve"]'),
('H40.40X2', 'Glaucoma secundario a inflamación ocular, ojo no especificado, estadio moderado', 'Sin especificar', '["inflamación ojo", "glaucoma moderado"]'),
('H40.40X3', 'Glaucoma secundario a inflamación ocular, ojo no especificado, estadio grave', 'Sin especificar', '["inflamación ojo", "glaucoma grave"]'),
('H40.40X4', 'Glaucoma secundario a inflamación ocular, ojo no especificado, estadio indeterminado', 'Sin especificar', '["inflamación ojo", "glaucoma"]'),
('H40.41X0', 'Glaucoma secundario a inflamación ocular, ojo derecho, estadio no especificado', 'Sin especificar', '["ojo derecho", "uveitis", "inflamación ojo", "presión alta"]'),
('H40.41X1', 'Glaucoma secundario a inflamación ocular, ojo derecho, estadio leve', 'Sin especificar', '["ojo derecho", "inflamación", "glaucoma leve"]'),
('H40.41X2', 'Glaucoma secundario a inflamación ocular, ojo derecho, estadio moderado', 'Sin especificar', '["ojo derecho", "inflamación", "glaucoma moderado"]'),
('H40.41X3', 'Glaucoma secundario a inflamación ocular, ojo derecho, estadio grave', 'Sin especificar', '["ojo derecho", "inflamación", "glaucoma grave"]'),
('H40.41X4', 'Glaucoma secundario a inflamación ocular, ojo derecho, estadio indeterminado', 'Sin especificar', '["ojo derecho", "inflamación", "glaucoma"]'),
('H40.42X0', 'Glaucoma secundario a inflamación ocular, ojo izquierdo, estadio no especificado', 'Sin especificar', '["ojo izquierdo", "uveitis", "inflamación ojo", "presión alta"]'),
('H40.42X1', 'Glaucoma secundario a inflamación ocular, ojo izquierdo, estadio leve', 'Sin especificar', '["ojo izquierdo", "inflamación", "glaucoma leve"]'),
('H40.42X2', 'Glaucoma secundario a inflamación ocular, ojo izquierdo, estadio moderado', 'Sin especificar', '["ojo izquierdo", "inflamación", "glaucoma moderado"]'),
('H40.42X3', 'Glaucoma secundario a inflamación ocular, ojo izquierdo, estadio grave', 'Sin especificar', '["ojo izquierdo", "inflamación", "glaucoma grave"]'),
('H40.42X4', 'Glaucoma secundario a inflamación ocular, ojo izquierdo, estadio indeterminado', 'Sin especificar', '["ojo izquierdo", "inflamación", "glaucoma"]'),
('H40.43X0', 'Glaucoma secundario a inflamación ocular, bilateral, estadio no especificado', 'Sin especificar', '["ambos ojos", "inflamación", "glaucoma"]'),
('H40.43X1', 'Glaucoma secundario a inflamación ocular, bilateral, estadio leve', 'Sin especificar', '["ambos ojos", "inflamación", "glaucoma leve"]'),
('H40.43X2', 'Glaucoma secundario a inflamación ocular, bilateral, estadio moderado', 'Sin especificar', '["ambos ojos", "inflamación", "glaucoma moderado"]'),
('H40.43X3', 'Glaucoma secundario a inflamación ocular, bilateral, estadio grave', 'Sin especificar', '["ambos ojos", "inflamación", "glaucoma grave"]'),
('H40.50X0', 'Glaucoma secundario a otros trastornos del ojo, ojo no especificado, estadio no especificado', 'Sin especificar', '["glaucoma por enfermedad ocular", "problema en ojo", "presión alta"]'),
('H40.50X1', 'Glaucoma secundario a otros trastornos del ojo, ojo no especificado, estadio leve', 'Sin especificar', '["glaucoma secundario", "leve"]'),
('H40.50X2', 'Glaucoma secundario a otros trastornos del ojo, ojo no especificado, estadio moderado', 'Sin especificar', '["glaucoma secundario", "moderado"]'),
('H40.50X3', 'Glaucoma secundario a otros trastornos del ojo, ojo no especificado, estadio grave', 'Sin especificar', '["glaucoma secundario", "grave"]'),
('H40.50X4', 'Glaucoma secundario a otros trastornos del ojo, ojo no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma secundario", "indeterminado"]'),
('H40.51X0', 'Glaucoma secundario a otros trastornos del ojo, ojo derecho, estadio no especificado', 'Sin especificar', '["ojo derecho", "glaucoma por enfermedad ocular"]'),
('H40.51X1', 'Glaucoma secundario a otros trastornos del ojo, ojo derecho, estadio leve', 'Sin especificar', '["ojo derecho", "glaucoma", "leve"]'),
('H40.51X2', 'Glaucoma secundario a otros trastornos del ojo, ojo derecho, estadio moderado', 'Sin especificar', '["ojo derecho", "glaucoma", "moderado"]'),
('H40.51X3', 'Glaucoma secundario a otros trastornos del ojo, ojo derecho, estadio grave', 'Sin especificar', '["ojo derecho", "glaucoma", "grave"]'),
('H40.51X4', 'Glaucoma secundario a otros trastornos del ojo, ojo derecho, estadio indeterminado', 'Sin especificar', '["ojo derecho", "glaucoma", "estudio"]'),
('H40.52X0', 'Glaucoma secundario a otros trastornos del ojo, ojo izquierdo, estadio no especificado', 'Sin especificar', '["ojo izquierdo", "glaucoma por enfermedad ocular"]'),
('H40.52X1', 'Glaucoma secundario a otros trastornos del ojo, ojo izquierdo, estadio leve', 'Sin especificar', '["ojo izquierdo", "glaucoma", "leve"]'),
('H40.52X2', 'Glaucoma secundario a otros trastornos del ojo, ojo izquierdo, estadio moderado', 'Sin especificar', '["ojo izquierdo", "glaucoma", "moderado"]'),
('H40.52X3', 'Glaucoma secundario a otros trastornos del ojo, ojo izquierdo, estadio grave', 'Sin especificar', '["ojo izquierdo", "glaucoma", "grave"]'),
('H40.52X4', 'Glaucoma secundario a otros trastornos del ojo, ojo izquierdo, estadio indeterminado', 'Sin especificar', '["ojo izquierdo", "glaucoma", "estudio"]'),
('H40.53X0', 'Glaucoma secundario a otros trastornos del ojo, bilateral, estadio no especificado', 'Sin especificar', '["ambos ojos", "glaucoma", "enfermedad ocular"]'),
('H40.53X1', 'Glaucoma secundario a otros trastornos del ojo, bilateral, estadio leve', 'Sin especificar', '["ambos ojos", "glaucoma", "leve"]'),
('H40.53X2', 'Glaucoma secundario a otros trastornos del ojo, bilateral, estadio moderado', 'Sin especificar', '["ambos ojos", "glaucoma", "moderado"]'),
('H40.53X3', 'Glaucoma secundario a otros trastornos del ojo, bilateral, estadio grave', 'Sin especificar', '["ambos ojos", "glaucoma", "grave"]'),
('H40.60X0', 'Glaucoma secundario a fármacos, ojo no especificado, estadio no especificado', 'Sin especificar', '["glaucoma por medicina", "gotas para ojos", "corticoides", "glaucoma por medicamentos"]'),
('H40.60X1', 'Glaucoma secundario a fármacos, ojo no especificado, estadio leve', 'Sin especificar', '["glaucoma medicamentoso", "leve"]'),
('H40.60X2', 'Glaucoma secundario a fármacos, ojo no especificado, estadio moderado', 'Sin especificar', '["glaucoma medicamentoso", "moderado"]'),
('H40.60X3', 'Glaucoma secundario a fármacos, ojo no especificado, estadio grave', 'Sin especificar', '["glaucoma medicamentoso", "grave"]'),
('H40.60X4', 'Glaucoma secundario a fármacos, ojo no especificado, estadio indeterminado', 'Sin especificar', '["glaucoma medicamentoso", "estudio"]'),
('H40.61X0', 'Glaucoma secundario a fármacos, ojo derecho, estadio no especificado', 'Sin especificar', '["ojo derecho", "glaucoma por gotas", "medicamentos"]'),
('H40.61X1', 'Glaucoma secundario a fármacos, ojo derecho, estadio leve', 'Sin especificar', '["ojo derecho", "glaucoma por gotas", "leve"]'),
('H40.61X2', 'Glaucoma secundario a fármacos, ojo derecho, estadio moderado', 'Sin especificar', '["ojo derecho", "glaucoma por gotas", "moderado"]'),
('H40.61X3', 'Glaucoma secundario a fármacos, ojo derecho, estadio grave', 'Sin especificar', '["ojo derecho", "glaucoma por gotas", "grave"]'),
('H40.61X4', 'Glaucoma secundario a fármacos, ojo derecho, estadio indeterminado', 'Sin especificar', '["ojo derecho", "glaucoma por gotas", "estudio"]'),
('H40.62X0', 'Glaucoma secundario a fármacos, ojo izquierdo, estadio no especificado', 'Sin especificar', '["ojo izquierdo", "glaucoma por gotas", "medicamentos"]'),
('H40.62X1', 'Glaucoma secundario a fármacos, ojo izquierdo, estadio leve', 'Sin especificar', '["ojo izquierdo", "glaucoma por gotas", "leve"]'),
('H40.62X2', 'Glaucoma secundario a fármacos, ojo izquierdo, estadio moderado', 'Sin especificar', '["ojo izquierdo", "glaucoma por gotas", "moderado"]'),
('H40.62X3', 'Glaucoma secundario a fármacos, ojo izquierdo, estadio grave', 'Sin especificar', '["ojo izquierdo", "glaucoma por gotas", "grave"]'),
('H40.62X4', 'Glaucoma secundario a fármacos, ojo izquierdo, estadio indeterminado', 'Sin especificar', '["ojo izquierdo", "glaucoma por gotas", "estudio"]'),
('H40.63X0', 'Glaucoma secundario a fármacos, bilateral, estadio no especificado', 'Sin especificar', '["ambos ojos", "glaucoma por gotas", "medicación"]'),
('H40.63X1', 'Glaucoma secundario a fármacos, bilateral, estadio leve', 'Sin especificar', '["ambos ojos", "glaucoma por gotas", "leve"]'),
('H40.63X2', 'Glaucoma secundario a fármacos, bilateral, estadio moderado', 'Sin especificar', '["ambos ojos", "glaucoma por gotas", "moderado"]'),
('H40.63X3', 'Glaucoma secundario a fármacos, bilateral, estadio grave', 'Sin especificar', '["ambos ojos", "glaucoma por gotas", "grave"]'),
('H40.811', 'Glaucoma con aumento de presión venosa epiescleral, ojo derecho', 'Sin especificar', '["ojo derecho", "presión venosa alta", "ojo rojo", "venas ojo", "glaucoma"]'),
('H40.812', 'Glaucoma con aumento de presión venosa epiescleral, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "presión venosa alta", "ojo rojo", "venas ojo", "glaucoma"]'),
('H40.813', 'Glaucoma con aumento de presión venosa epiescleral, bilateral', 'Sin especificar', '["ambos ojos", "presión venosa alta", "ojo rojo", "glaucoma"]'),
('H40.819', 'Glaucoma con aumento de presión venosa epiescleral, ojo no especificado', 'Sin especificar', '["glaucoma", "presión venosa", "ojo"]'),
('H40.821', 'Glaucoma por hipersecreción, ojo derecho', 'Sin especificar', '["ojo derecho", "producción exceso líquido", "presión alta ojo", "glaucoma"]'),
('H40.822', 'Glaucoma por hipersecreción, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "producción exceso líquido", "presión alta ojo", "glaucoma"]'),
('H40.823', 'Glaucoma por hipersecreción, bilateral', 'Sin especificar', '["ambos ojos", "exceso humor acuoso", "glaucoma"]'),
('H40.829', 'Glaucoma por hipersecreción, ojo no especificado', 'Sin especificar', '["glaucoma", "exceso líquido ojo"]'),
('H40.831', 'Trastorno en la dirección del humor acuoso, ojo derecho', 'Sin especificar', '["ojo derecho", "bloqueo pupilar", "glaucoma maligno", "problema líquido ojo"]'),
('H40.832', 'Trastorno en la dirección del humor acuoso, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "bloqueo pupilar", "glaucoma maligno", "problema líquido ojo"]'),
('H40.833', 'Trastorno en la dirección del humor acuoso, bilateral', 'Sin especificar', '["ambos ojos", "glaucoma maligno", "bloqueo pupilar"]'),
('H40.839', 'Trastorno en la dirección del humor acuoso, ojo no especificado', 'Sin especificar', '["glaucoma maligno", "problema ojo"]'),
('H40.89', 'Otros tipos de glaucoma especificados', 'Sin especificar', '["glaucoma", "problema de presión ocular", "otros", "revisión oftálmica"]'),
('H40.9', 'Glaucoma no especificado', 'Sin especificar', '["glaucoma", "ojo que no ve bien", "presión alta", "ceguera", "ojo", "revisión vista"]');
