INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('R06.00', 'Disnea no especificada', 'Sin especificar', '["falta de aire", "ahogo", "asfixia", "no me entra el aire", "sofoco", "fatiga al respirar", "pecho cerrado", "pulmones cansados", "falta de aliento", "ahoguío", "pesadez al respirar", "dificultad respiratoria", "aire cortado", "me falta el aire", "hambre de aire"]'),
('R06.01', 'Ortopnea', 'Sin especificar', '["ahogo al acostarse", "no puedo dormir acostado", "tengo que dormir sentado", "me ahogo si me acuesto", "necesito almohadas para dormir", "falta de aire al tumbarse", "sueño erguido", "sofoco al recostarme", "falta de aliento en cama", "me asfixio al echarme"]'),
('R06.02', 'Dificultad para respirar', 'Sin especificar', '["me cuesta respirar", "respiro mal", "problemas para respirar", "no puedo tomar aire", "respiración difícil", "se me corta la respiración", "falta de aire", "asfixia", "me ahogo", "aire insuficiente", "respiración pesada", "esfuerzo al respirar", "pulmones pesados", "ahoguío"]'),
('R06.03', 'Distrés respiratorio agudo', 'Sin especificar', '["insuficiencia respiratoria", "fallo pulmonar", "crisis respiratoria", "pulmones bloqueados", "emergencia respiratoria", "no entra nada de aire", "ahogo severo", "colapso respiratorio", "se me cierran los pulmones", "pánico por no poder respirar", "hipoxia"]'),
('R06.09', 'Otras formas de disnea', 'Sin especificar', '["respiración rara", "cambios al respirar", "ritmo respiratorio extraño", "problemas de pulmón", "aire corto", "suspiros constantes", "respiración fatigosa", "opresión torácica", "incomodidad al respirar"]'),
('R06.1', 'Estridor', 'Sin especificar', '["silbido en la garganta", "ruido al respirar", "garganta que pita", "respiración ruidosa", "sonido agudo al inhalar", "chillido al respirar", "garganta cerrada", "ronquido en la garganta", "estridencia al respirar"]'),
('R06.2', 'Roncus y sibilancias', 'Sin especificar', '["pecho que pita", "silbidos en el pecho", "pulmones con flema", "pecho ronco", "ruido de pecho", "sibilancia", "ronquera pulmonar", "pecho que suena", "gorgoteo en el pecho", "pulmones silbadores", "pecho con sonido"]'),
('R06.3', 'Respiración periódica', 'Sin especificar', '["respiración irregular", "pausas al respirar", "ritmo extraño de respiración", "respiración que sube y baja", "respiración entrecortada", "cambio en el ritmo de aire", "respiración intermitente"]'),
('R06.4', 'Hiperventilación', 'Sin especificar', '["respirar muy rápido", "taquipnea emocional", "respiración agitada", "exceso de aire", "hiperventilar", "mareo por respirar mucho", "respiración rápida", "sofocón", "aire de más", "me falta el aire por respirar mucho"]'),
('R06.5', 'Respiración por la boca', 'Sin especificar', '["respirar con la boca abierta", "boca seca al dormir", "roncar con la boca", "respiración bucal", "no respiro por la nariz", "nariz tapada", "tengo que abrir la boca para respirar", "garganta seca por respirar así"]'),
('R06.6', 'Hipo', 'Sin especificar', '["hipo", "tengo hipo", "me dio el hipo", "espasmo en el diafragma", "hipido", "sacudidas del pecho", "contracciones del diafragma", "hipar"]'),
('R06.7', 'Estornudo', 'Sin especificar', '["estornudar", "estornudo", "alergia", "picazón en la nariz", "chis", "achís", "resfriado", "nariz irritada", "estornudadera", "constipado"]'),
('R06.81', 'Apnea, no clasificada bajo otro concepto', 'Sin especificar', '["pausas respiratorias", "dejar de respirar al dormir", "se me corta la respiración", "ahogo nocturno", "dejar de respirar", "falla al respirar", "interrupción de la respiración", "silencio respiratorio"]'),
('R06.82', 'Taquipnea, no clasificada bajo otro concepto', 'Sin especificar', '["respiración acelerada", "respiración rápida", "agitación al respirar", "pulmones veloces", "respirar muy seguido", "ritmo respiratorio alto", "jadeo", "aire rápido"]'),
('R06.83', 'Ronquido', 'Sin especificar', '["roncar", "ronquidos", "hacer ruido al dormir", "ronquido nocturno", "sonido al dormir", "ruido de garganta dormido", "roncador", "ruido de nariz al dormir"]'),
('R06.89', 'Otras alteraciones de la respiración', 'Sin especificar', '["problemas para aire", "raro al respirar", "molestia en la respiración", "alteración al aire", "ritmo respiratorio raro", "incomodidad al inhalar", "fallo al tomar aire"]'),
('R06.9', 'Alteraciones de la respiración no especificadas', 'Sin especificar', '["respiro raro", "problemas con el aire", "algo anda mal con mi respiración", "no respiro bien", "sensación extraña al respirar", "malestar respiratorio", "asuntos de respiración"]');
