INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L40.0', 'Psoriasis vulgar', 'Sin especificar', '["psoriasis", "placas en la piel", "escamas rojas", "cueros secos", "descamación", "manchas rojas", "piel irritada", "picazón en la piel", "codos escamosos", "psoriasis en placas", "manchas con escamas", "piel engrosada", "eccema seco", "brotes en la piel", "dermatitis descamativa"]'),
('L40.1', 'Psoriasis pustulosa generalizada', 'Sin especificar', '["psoriasis con granos", "pústulas en el cuerpo", "ampollas con pus", "psoriasis grave", "manchas con pus", "piel inflamada con granos", "brote cutáneo severo", "erupción con pústulas", "psoriasis eruptiva", "infección en la piel", "pústulas generalizadas", "psoriasis de von zumbusch", "piel irritada con pus", "puntos blancos en la piel", "brotes rojos con pus"]'),
('L40.2', 'Acrodermatitis continua', 'Sin especificar', '["acrodermatitis", "pústulas en dedos", "psoriasis en las uñas", "inflamación de los dedos", "uñas con pus", "pústulas en manos y pies", "acrodermatitis de hallopeau", "dolor en los dedos", "desprendimiento de uñas", "piel roja en dedos", "psoriasis acral", "dedos hinchados", "pus bajo la uña", "uñas dañadas", "infección ungueal crónica"]'),
('L40.3', 'Pustulosis palmar y plantar', 'Sin especificar', '["pústulas en palmas", "pústulas en plantas de los pies", "granitos en las manos", "manos descamadas", "plantas de los pies con pus", "psoriasis de manos y pies", "ampollas en la planta", "manos y pies irritados", "psoriasis palmoplantar", "piel seca en palmas", "pústulas estériles", "picor en pies y manos", "piel que se pela en las manos", "lesiones en planta del pie", "dolor al caminar por pústulas"]'),
('L40.4', 'Psoriasis guttata', 'Sin especificar', '["psoriasis en gotas", "manchas pequeñas en la piel", "brotes en forma de gota", "psoriasis eruptiva", "manchas rojas pequeñas", "puntos rojos en el torso", "psoriasis post-estreptocócica", "erupción de gotas", "piel con puntitos rojos", "psoriasis juvenil", "manchas tras faringitis", "descamación pequeña", "brotes rápidos en la piel", "manchas diseminadas", "exantema escamoso"]'),
('L40.50', 'Artropatia psoriásica, no especificada', 'Sin especificar', '["dolor articular por psoriasis", "artritis psoriásica", "articulaciones inflamadas", "dolor de huesos psoriasis", "reuma y psoriasis", "hinchazón articular", "rigidez al despertar", "dolor en las articulaciones", "psoriasis en articulaciones", "artritis asociada a piel", "articulaciones rígidas", "problemas de huesos", "dolor corporal", "artropatía inflamatoria", "hinchazón de coyunturas"]'),
('L40.51', 'Artropatía psoriásica interfalángica distal', 'Sin especificar', '["dolor en puntas de los dedos", "inflamación de falanges distales", "uñas deformes y dolor", "artritis de los dedos", "dolor en articulaciones finales", "dedos con psoriasis", "artritis distal", "hinchazón en puntas de dedos", "uñas con surcos", "dolor en las falanges", "dedos en salchicha", "deformación de uñas", "inflamación de articulaciones distales", "artritis interfalángica", "molestias al mover los dedos"]'),
('L40.52', 'Artritis psoriásica mutilante', 'Sin especificar', '["artritis severa", "deformidad articular", "dedos acortados", "artritis destructiva", "psoriasis grave en huesos", "manos deformadas", "pérdida de función articular", "artritis severa y crónica", "osteolisis psoriásica", "artritis mutilante", "dedos en telescopio", "deterioro de articulaciones", "daño articular irreversible", "dolor articular extremo", "deformidad ósea"]'),
('L40.53', 'Espondilitis psoriásica', 'Sin especificar', '["dolor de espalda", "columna rígida", "dolor lumbar psoriásico", "espondilitis", "inflamación de la columna", "dolor de cuello", "espalda tiesa", "rigidez lumbar", "psoriasis en la columna", "dolor de rabadilla", "espondiloartritis", "dificultad al agacharse", "dolor vertebral", "psoriasis espinal", "limitación de movimiento de espalda"]'),
('L40.54', 'Artropatía psoriásica juvenil', 'Sin especificar', '["artritis en niños", "psoriasis infantil con dolor", "dolor articular en adolescentes", "artritis en jóvenes", "psoriasis de aparición temprana", "dolor de crecimiento falso", "hinchazón de rodillas niños", "artritis juvenil", "problemas óseos en niños", "rigidez articular infantil", "dolor de huesos en menores", "reuma infantil", "cojera por psoriasis", "psoriasis juvenil", "inflamación de articulaciones jóvenes"]'),
('L40.59', 'Otros tipos de artropatía psoriásica', 'Sin especificar', '["artritis mixta psoriásica", "otras formas de artritis psoriásica", "dolor articular atípico", "inflamación articular psoriasis", "reumatismo psoriásico", "afectación de articulaciones", "artropatía inflamatoria crónica", "psoriasis articular", "molestias en coyunturas", "dolor articular crónico", "inflamación de tendones psoriasis", "entesitis psoriásica", "problemas articulares", "dolor en los huesos", "rigidez articular"]'),
('L40.8', 'Otros tipos de psoriasis', 'Sin especificar', '["psoriasis rara", "psoriasis invertida", "psoriasis del cuero cabelludo", "psoriasis de pliegues", "psoriasis eritrodérmica", "piel roja en pliegues", "psoriasis en zonas húmedas", "psoriasis en axilas", "psoriasis en ingles", "psoriasis en la cabeza", "caspa gruesa", "psoriasis intertriginosa", "placas rojas en el cuerpo", "enfermedad de la piel", "psoriasis no clasificada"]'),
('L40.9', 'Psoriasis, no especificada', 'Sin especificar', '["psoriasis", "manchas en la piel", "piel escamosa", "brotes cutáneos", "problemas de piel", "eccema persistente", "piel roja", "picazón de piel", "escamas blancas", "psoriasis sin definir", "dermatosis inflamatoria", "enfermedad cutánea", "placas cutáneas", "erupción crónica", "descamación de la piel"]');
