INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('I31.0', 'Pericarditis crónica adhesiva', 'Sin especificar', '["pericarditis", "dolor en el pecho", "corazón pegado", "inflamación del corazón", "membrana del corazón inflamada", "dolor al respirar", "pinchazos en el pecho", "opresión cardíaca", "cicatrices en el corazón", "adherencias pericárdicas", "pericardio duro", "dolor torácico crónico", "pesadez en el pecho", "falta de aire", "molestia al acostarse"]'),
('I31.1', 'Pericarditis constrictiva crónica', 'Sin especificar', '["pericardio rígido", "corazón apretado", "pericarditis restrictiva", "dificultad para respirar", "hinchazón de piernas", "edema por corazón", "cansancio extremo", "insuficiencia cardíaca", "presión en el pecho", "corazón que no se expande", "pericarditis fibrosa", "calcinación del pericardio", "pericardio endurecido", "fatiga crónica", "falta de aliento"]'),
('I31.2', 'Hemopericardio, no clasificado bajo otro concepto', 'Sin especificar', '["sangre alrededor del corazón", "hemorragia pericárdica", "derrame de sangre en el corazón", "choque cardíaco", "trauma cardíaco", "pericardio lleno de sangre", "sangre en la bolsa del corazón", "emergencia cardíaca", "dolor súbito en el pecho", "taponamiento hemorrágico", "rotura de vaso cardíaco", "dolor agudo pecho", "colapso circulatorio", "sangrado interno cardíaco", "desvanecimiento"]'),
('I31.31', 'Derrame pericárdico maligno en enfermedades clasificadas bajo otro concepto', 'Sin especificar', '["líquido en el corazón por cáncer", "derrame oncológico", "agua en el corazón", "cáncer y corazón", "pericarditis por tumor", "metástasis cardíaca", "acúmulo de líquido pericárdico", "derrame tumoral", "hinchan los pies y pecho", "dificultad para respirar por cáncer", "presión cardíaca maligna", "líquido en la bolsa del corazón", "enfermedad terminal corazón", "opresión torácica grave", "fatiga por derrame"]'),
('I31.39', 'Otro derrame pericárdico (no inflamatorio)', 'Sin especificar', '["líquido en el pericardio", "agua en el corazón", "derrame del corazón", "hinchazón de pecho", "edema pericárdico", "corazón encharcado", "sensación de pesadez en el pecho", "dificultad respiratoria", "acumulación de líquido cardíaco", "pericardio distendido", "exceso de líquido en el corazón", "corazón con agua", "presión en el pecho al respirar", "palpitaciones por líquido", "cansancio al caminar"]'),
('I31.4', 'Taponamiento cardiaco', 'Sin especificar', '["taponamiento del corazón", "corazón ahorcado", "infarto pericárdico", "colapso cardíaco", "emergencia al corazón", "corazón que no late bien", "presión fatal en el corazón", "choque obstructivo", "ahogo repentino", "incapacidad de bombear sangre", "presión arterial baja súbita", "pulso débil", "venas del cuello hinchadas", "taponamiento pericárdico", "urgencia cardiológica"]'),
('I31.8', 'Otras enfermedades especificadas del pericardio', 'Sin especificar', '["problemas del pericardio", "dolor en la membrana del corazón", "molestia cardíaca extraña", "infección en el corazón", "quistes pericárdicos", "tumor en el pericardio", "fibrosis pericárdica", "dolor agudo al toser", "pinchazo en la caja torácica", "sensación de presión cardíaca", "inflamación persistente pecho", "dolor intermitente corazón", "revisión cardiológica", "pericardio sensible", "dolor al mover el tórax"]'),
('I31.9', 'Enfermedades del pericardio, no especificadas', 'Sin especificar', '["dolor en el pecho de origen desconocido", "problema del corazón", "molestia en la bolsa del corazón", "dolor torácico", "no sé qué tengo en el pecho", "pinchazos en el corazón", "dolor al respirar profundo", "opresión cardíaca", "pericardio enfermo", "indefinido corazón", "síntomas cardíacos vagos", "dolor punzante pecho", "molestia en el medio del pecho", "corazón adolorido", "revisión por dolor cardíaco"]');
