INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('O66.0', 'Trabajo de parto obstruido debido a distocia del hombro', 'Sin especificar', '["hombro atascado", "bebé trabado", "parto complicado", "hombros del feto atorados", "distocia de hombros", "bebé no sale", "parto difícil", "emergencia obstétrica", "atrapado en el canal de parto", "hombrito trabado", "parto encajado", "problemas para parir", "bloqueo de hombro"]'),
('O66.1', 'Trabajo de parto obstruido debido a gemelos abrazados', 'Sin especificar', '["gemelos enganchados", "parto de mellizos complicado", "gemelos unidos", "mellizos enredados", "parto de gemelos trabado", "gemelos abrazados en el parto", "bebes entrelazados", "embarazo múltiple obstruido", "problema al nacer gemelos", "gemelos atascados", "parto doble difícil"]'),
('O66.2', 'Trabajo de parto obstruido debido a feto inusualmente grande', 'Sin especificar', '["bebé muy grande", "bebé pesado", "macrosomía fetal", "bebé enorme", "parto de guagua grande", "bebé cabezón", "parto difícil por tamaño", "bebé no pasa", "parto complicado por peso", "bebé gordito en el parto", "feto grande", "parto obstruido por tamaño", "problemas de peso al nacer"]'),
('O66.3', 'Trabajo de parto obstruido debido a otras anomalías del feto', 'Sin especificar', '["problemas fetales en parto", "malformación fetal durante parto", "parto obstruido por feto", "feto con anomalía", "parto no avanza por el bebé", "dificultad al parir feto", "anomalía fetal al nacer", "parto complicado feto", "problemas mecánicos en parto", "feto con posición rara", "obstáculos en el parto fetal"]'),
('O66.40', 'Intento de trabajo de parto fallido, no especificado', 'Sin especificar', '["parto fallido", "intentar parto natural sin éxito", "el parto no progresa", "se detuvo el parto", "no pude tener parto normal", "trabajo de parto que no avanza", "parto bloqueado", "intento de parto frustrado", "parto largo sin éxito", "dilatación detenida", "no se pudo parir naturalmente"]'),
('O66.41', 'Intento de parto vaginal fallido después de parto previo por cesárea', 'Sin especificar', '["parto después de cesárea fallido", "PVDC sin éxito", "intentar parto normal tras cesárea", "cesárea previa y parto vaginal fallido", "no pude tener parto vaginal tras cesárea", "intento de parto natural post cesárea", "parto vaginal después de cesárea bloqueado", "problemas tras cesárea anterior", "parto que no pudo ser", "reintento de parto tras cirugía"]'),
('O66.5', 'Intento de utilización de ventosa y fórceps', 'Sin especificar', '["parto con fórceps", "parto con ventosa", "uso de fierros en parto", "parto instrumental fallido", "ayuda de fórceps", "parto con succionador", "parto con instrumentos", "uso de ventosa obstétrica", "intentaron sacarlo con fórceps", "parto asistido que no funcionó", "fórceps y ventosa en el parto"]'),
('O66.6', 'Trabajo de parto obstruido debido a múltiples fetos', 'Sin especificar', '["parto de trillizos difícil", "parto múltiple trabado", "problemas con varios bebés al nacer", "parto de embarazos múltiples obstruido", "se atascó el parto múltiple", "dificultad para parir varios bebés", "parto de fetos múltiples detenido", "complicaciones en parto múltiple"]'),
('O66.8', 'Otras obstrucciones especificadas del trabajo de parto', 'Sin especificar', '["parto atorado", "parto bloqueado por causas raras", "obstáculos en el canal de parto", "dificultad extraña en el parto", "parto que no progresa por otras causas", "problemas mecánicos en el nacimiento", "parto trabado", "complicación en la expulsión", "parto atascado"]'),
('O66.9', 'Trabajo de parto obstruido, no especificado', 'Sin especificar', '["parto detenido", "parto que no avanza", "parto parado", "no sale el bebé", "trabajo de parto obstruido", "problemas al momento de parir", "parto complicado", "parto trabado sin motivo", "el parto se estancó", "no hay progreso en el parto", "atascada en el parto"]');
