INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K13.0', 'Enfermedades de los labios', 'Sin especificar', '["boqueras", "fuegos labiales", "labios partidos", "heridas en los labios", "labios resecos", "llagas en la boca", "calenturas", "dermatitis labial", "labios agrietados", "corte en el labio", "cheilitis", "inflamación de labios", "pellejos en los labios", "ampollas labiales", "boca seca"]'),
('K13.1', 'Mordedura de labio y de mejilla', 'Sin especificar', '["mordida en el cachete", "me mordí la boca", "herida por mordedura", "mordida en la cara interna", "me mordí el carrillo", "mordida en el labio", "llaga por mordida", "trauma por mordedura", "me mordí adentro", "herida en la mejilla", "lesión por mordida", "dolor en el cachete", "mordedura accidental", "herida en el bigote"]'),
('K13.21', 'Leucoplasia de mucosa oral, incluyendo la lengua', 'Sin especificar', '["mancha blanca en la boca", "parche blanco en la lengua", "placa blanca en la mucosa", "lengua con manchas blancas", "mancha que no se quita", "leucoplasia", "lesiones blanquecinas", "manchas en el paladar", "parches en la boca", "mancha precursora de cáncer", "engrosamiento blanco", "mancha en la mejilla", "lengua blanquecina", "placas en la boca"]'),
('K13.22', 'Queratinización mínima de mucosa de reborde residual', 'Sin especificar', '["piel dura en las encías", "engrosamiento de la encía", "reborde con callosidad", "mucosa endurecida", "queratinización leve", "encía blanca", "cambio en el tejido de la encía", "piel endurecida en la boca", "reborde alveolar duro", "placa blanquecina leve", "mucosa bucal áspera"]'),
('K13.23', 'Queratinización excesiva de mucosa de reborde residual', 'Sin especificar', '["encía muy dura", "callo en la encía", "reborde con callosidad gruesa", "hiperqueratosis gingival", "tejido bucal endurecido", "placa blanca gruesa", "encía acartonada", "reborde que molesta", "queratosis severa", "mucosa oral rígida", "engrosamiento epitelial", "piel muerta en la encía"]'),
('K13.24', 'Leucoqueratosis nicotínica de paladar', 'Sin especificar', '["paladar del fumador", "manchas blancas por fumar", "paladar blanco", "quemadura de paladar", "estomatitis nicotínica", "paladar con puntitos rojos", "daño por cigarrillo", "leucoplasia del paladar", "paladar áspero", "lesión por tabaco", "paladar quemado por humo", "manchas de fumador"]'),
('K13.29', 'Otras alteraciones de epitelio oral, incluyendo lengua', 'Sin especificar', '["problemas en la lengua", "alteración mucosa oral", "cambios en la piel de la boca", "lengua rara", "lesión oral extraña", "epitelio bucal alterado", "lengua con textura rara", "manchas en la mucosa", "células bucales", "tejido oral irregular", "dolor de mucosa", "lesión de la lengua"]'),
('K13.3', 'Leucoplasia pilosa', 'Sin especificar', '["lengua con pelitos", "lengua vellosa", "mancha blanca en lengua lateral", "lengua peluda", "leucoplasia vellosa", "lesión lateral de lengua", "placas blanquecinas en lengua", "lengua con aspecto de pelo", "infección en la lengua", "manchas blancas en los bordes de la lengua"]'),
('K13.4', 'Granuloma y lesiones similares a granuloma de mucosa oral', 'Sin especificar', '["bolita en la boca", "bulto en la encía", "granuloma bucal", "tumor benigno en boca", "bolita de carne", "crecimiento en la encía", "lesión carnosa en la boca", "bulto en el labio", "quiste en la boca", "carne crecida", "abultamiento oral", "granuloma piógeno", "lesión sangrante en boca"]'),
('K13.5', 'Fibrosis submucosa oral', 'Sin especificar', '["boca rígida", "dificultad para abrir la boca", "trismo", "mucosa endurecida", "fibrosis en la boca", "tejido bucal rígido", "no puedo abrir bien la boca", "rigidez de la mucosa", "boca tiesa", "cicatrices internas en boca", "fibrosis oral"]'),
('K13.6', 'Hiperplasia irritativa de mucosa oral', 'Sin especificar', '["crecimiento por roce", "hiperplasia por prótesis", "bolita por aparato", "irritación crónica en la boca", "fibroma por roce", "carne crecida por brackets", "bulto por prótesis mal ajustada", "lesión por fricción", "engrosamiento por roce", "carne que crece por el aparato", "irritación constante"]'),
('K13.70', 'Lesiones de mucosa oral no especificadas', 'Sin especificar', '["lesión en la boca", "herida en la boca", "llaga en la boca", "mancha en la mejilla", "dolor de boca", "problema en el cachete", "alguna cosa en la mucosa", "lesión sin identificar", "boca irritada", "úlcera bucal", "mancha extraña", "molestia oral"]'),
('K13.79', 'Otras lesiones de mucosa oral', 'Sin especificar', '["otras heridas bucales", "manchas en la mucosa oral", "lesiones diversas de boca", "problemas de carrillos", "aftas rebeldes", "laceración en la boca", "irritación de la mucosa", "cambios en el tejido oral", "lesiones bucales persistentes", "anomalía en la mucosa", "dolor en la mejilla interna"]');
