INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('M71.00', 'Absceso de bolsa sinovial, localización no especificada', 'Sin especificar', '["bursitis infectada", "bolsa con pus", "inflamación de la bursa", "bursa infectada", "dolor articular intenso", "hinchazón roja y caliente", "infección en la articulación", "absceso articular", "bursitis purulenta", "líquido en la articulación", "articulación con pus"]'),
('M71.011', 'Absceso de bolsa sinovial, hombro derecho', 'Sin especificar', '["absceso en hombro derecho", "bursitis infectada hombro", "hombro con pus", "dolor insoportable hombro derecho", "hombro hinchado y caliente", "infección en el hombro", "flemón en el hombro", "hombro bloqueado por pus", "bursitis séptica hombro"]'),
('M71.012', 'Absceso de bolsa sinovial, hombro izquierdo', 'Sin especificar', '["absceso en hombro izquierdo", "bursitis infectada hombro izquierdo", "hombro con pus", "dolor hombro izquierdo", "hombro inflamado por infección", "flemón en hombro izquierdo", "infección articular hombro izquierdo"]'),
('M71.019', 'Absceso de bolsa sinovial, hombro no especificado', 'Sin especificar', '["absceso en el hombro", "bursitis séptica hombro", "hombro con infección", "dolor hombro", "hinchazón en hombro", "pus en la bursa del hombro", "inflamación severa de hombro"]'),
('M71.021', 'Absceso de bolsa sinovial, codo derecho', 'Sin especificar', '["codo derecho con pus", "absceso en el codo", "bursitis olecraniana infectada", "codo inflamado y caliente", "infección en la punta del codo", "codo rojo y dolorido", "golpe en el codo con infección", "flemón codo derecho"]'),
('M71.022', 'Absceso de bolsa sinovial, codo izquierdo', 'Sin especificar', '["codo izquierdo con pus", "absceso en el codo izquierdo", "bursitis séptica codo", "codo hinchado infección", "punta del codo caliente", "infección del codo", "bursitis codo izquierdo"]'),
('M71.029', 'Absceso de bolsa sinovial, codo no especificado', 'Sin especificar', '["absceso en el codo", "codo infectado", "pus en la bursa del codo", "bursitis con infección", "codo muy hinchado y rojo", "dolor de codo severo", "infección olecraniana"]'),
('M71.031', 'Absceso de bolsa sinovial, muñeca derecha', 'Sin especificar', '["absceso en la muñeca derecha", "infección de la muñeca", "bursitis muñeca derecha", "muñeca con pus", "muñeca hinchada y roja", "dolor agudo muñeca derecha", "inflamación por infección en muñeca"]'),
('M71.032', 'Absceso de bolsa sinovial, muñeca izquierda', 'Sin especificar', '["absceso en la muñeca izquierda", "infección de la muñeca izquierda", "muñeca con pus", "bursitis muñeca izquierda", "dolor en muñeca izquierda", "muñeca roja y caliente"]'),
('M71.039', 'Absceso de bolsa sinovial, muñeca no especificada', 'Sin especificar', '["absceso en la muñeca", "infección de la bursa de la muñeca", "muñeca con pus", "dolor de muñeca severo", "bursitis séptica de muñeca", "inflamación de muñeca"]'),
('M71.041', 'Absceso de bolsa sinovial, mano derecha', 'Sin especificar', '["absceso en la mano derecha", "infección bursa mano", "mano con pus", "inflamación mano derecha", "bursitis mano derecha", "mano caliente e hinchada"]'),
('M71.042', 'Absceso de bolsa sinovial, mano izquierda', 'Sin especificar', '["absceso en la mano izquierda", "infección bursa mano izquierda", "mano con pus", "inflamación mano izquierda", "bursitis mano izquierda"]'),
('M71.049', 'Absceso de bolsa sinovial, mano no especificada', 'Sin especificar', '["absceso en la mano", "infección en la bursa de la mano", "mano con pus", "bursitis infectada mano", "hinchazón mano", "dolor mano"]'),
('M71.051', 'Absceso de bolsa sinovial, cadera derecha', 'Sin especificar', '["absceso en cadera derecha", "bursitis trocantérica infectada", "infección cadera derecha", "dolor en la cadera derecha", "cadera con pus", "bursitis séptica cadera"]'),
('M71.052', 'Absceso de bolsa sinovial, cadera izquierda', 'Sin especificar', '["absceso en cadera izquierda", "bursitis cadera izquierda", "infección de cadera", "cadera con pus", "dolor intenso cadera", "bursitis trocantérica"]'),
('M71.059', 'Absceso de bolsa sinovial, cadera no especificada', 'Sin especificar', '["absceso en la cadera", "bursitis infectada cadera", "dolor de cadera", "pus en la cadera", "infección bursa cadera", "inflamación cadera"]'),
('M71.061', 'Absceso de bolsa sinovial, rodilla derecha', 'Sin especificar', '["absceso en rodilla derecha", "bursitis prepatelar infectada", "rodilla con pus", "rodilla hinchada y roja", "infección en la rodilla", "agua en la rodilla con pus", "rodilla caliente derecha"]'),
('M71.062', 'Absceso de bolsa sinovial, rodilla izquierda', 'Sin especificar', '["absceso en rodilla izquierda", "bursitis prepatelar izquierda", "rodilla izquierda con pus", "rodilla hinchada infección", "infección rodilla izquierda"]'),
('M71.069', 'Absceso de bolsa sinovial, rodilla no especificada', 'Sin especificar', '["absceso en rodilla", "bursitis rodilla infectada", "rodilla con pus", "infección bursa rodilla", "rodilla inflamada severa", "agua en la rodilla purulenta"]'),
('M71.071', 'Absceso de bolsa sinovial, tobillo y pie derechos', 'Sin especificar', '["absceso en tobillo derecho", "bursitis pie derecho", "infección tobillo", "pie derecho con pus", "inflamación tobillo derecho", "bursitis infectada pie"]'),
('M71.072', 'Absceso de bolsa sinovial, tobillo y pie izquierdos', 'Sin especificar', '["absceso en tobillo izquierdo", "bursitis pie izquierdo", "pie izquierdo con pus", "infección tobillo izquierdo", "inflamación pie izquierdo"]'),
('M71.079', 'Absceso de bolsa sinovial, tobillo y pie no especificados', 'Sin especificar', '["absceso en tobillo", "absceso en pie", "bursitis pie infectada", "pie con pus", "infección tobillo", "dolor de pie"]'),
('M71.08', 'Absceso de bolsa sinovial, otras localizaciones', 'Sin especificar', '["absceso bursa otras partes", "infección de bursa", "bursitis con pus", "bursitis séptica", "acumulación de pus en articulación"]'),
('M71.09', 'Absceso de bolsa sinovial, localizaciones múltiples', 'Sin especificar', '["abscesos en varias articulaciones", "bursitis infectada múltiple", "varias bursas con pus", "infecciones articulares múltiples", "bursitis séptica generalizada"]'),
('M71.10', 'Otras bursitis infecciosas, localización no especificada', 'Sin especificar', '["bursitis infecciosa", "bursa infectada", "infección articular", "bursitis séptica", "dolor y pus en articulación", "inflamación bursa por bacterias"]'),
('M71.111', 'Otras bursitis infecciosas, hombro derecho', 'Sin especificar', '["infección bursa hombro derecho", "bursitis séptica hombro", "hombro infectado", "bursitis aguda hombro derecho", "inflamación purulenta hombro"]'),
('M71.112', 'Otras bursitis infecciosas, hombro izquierdo', 'Sin especificar', '["infección bursa hombro izquierdo", "bursitis séptica hombro izquierdo", "hombro infectado", "bursitis aguda hombro", "hinchazón hombro izquierdo"]'),
('M71.119', 'Otras bursitis infecciosas, hombro no especificado', 'Sin especificar', '["infección bursa hombro", "bursitis hombro infectada", "hombro con inflamación bacteriana", "bursitis séptica", "dolor de hombro severo"]'),
('M71.121', 'Otras bursitis infecciosas, codo derecho', 'Sin especificar', '["infección bursa codo derecho", "bursitis codo derecho", "codo infectado", "bursitis olecraniana séptica", "codo rojo y caliente"]'),
('M71.122', 'Otras bursitis infecciosas, codo izquierdo', 'Sin especificar', '["infección bursa codo izquierdo", "bursitis codo izquierdo", "codo infectado", "bursitis séptica codo", "codo con pus"]'),
('M71.129', 'Otras bursitis infecciosas, codo no especificado', 'Sin especificar', '["infección bursa codo", "bursitis codo", "codo infectado", "inflamación codo", "bursitis séptica"]'),
('M71.131', 'Otras bursitis infecciosas, muñeca derecha', 'Sin especificar', '["infección bursa muñeca derecha", "bursitis muñeca derecha", "muñeca infectada", "muñeca con inflamación severa", "bursitis séptica"]'),
('M71.132', 'Otras bursitis infecciosas, muñeca izquierda', 'Sin especificar', '["infección bursa muñeca izquierda", "bursitis muñeca izquierda", "muñeca infectada", "bursitis séptica muñeca"]'),
('M71.139', 'Otras bursitis infecciosas, muñeca no especificada', 'Sin especificar', '["infección bursa muñeca", "bursitis muñeca", "muñeca infectada", "dolor muñeca", "bursitis séptica"]'),
('M71.141', 'Otras bursitis infecciosas, mano derecha', 'Sin especificar', '["infección bursa mano derecha", "bursitis mano derecha", "mano infectada", "bursitis séptica mano"]'),
('M71.142', 'Otras bursitis infecciosas, mano izquierda', 'Sin especificar', '["infección bursa mano izquierda", "bursitis mano izquierda", "mano infectada", "bursitis séptica"]'),
('M71.149', 'Otras bursitis infecciosas, mano no especificada', 'Sin especificar', '["infección bursa mano", "bursitis mano", "mano infectada", "bursitis séptica"]'),
('M71.151', 'Otras bursitis infecciosas, cadera derecha', 'Sin especificar', '["infección bursa cadera derecha", "bursitis cadera derecha", "cadera infectada", "bursitis trocantérica séptica", "dolor cadera derecha"]'),
('M71.152', 'Otras bursitis infecciosas, cadera izquierda', 'Sin especificar', '["infección bursa cadera izquierda", "bursitis cadera izquierda", "cadera infectada", "bursitis séptica"]'),
('M71.159', 'Otras bursitis infecciosas, cadera no especificada', 'Sin especificar', '["infección bursa cadera", "bursitis cadera", "cadera infectada", "bursitis séptica"]'),
('M71.161', 'Otras bursitis infecciosas, rodilla derecha', 'Sin especificar', '["infección bursa rodilla derecha", "bursitis rodilla derecha", "rodilla infectada", "bursitis prepatelar séptica", "rodilla roja y caliente"]'),
('M71.162', 'Otras bursitis infecciosas, rodilla izquierda', 'Sin especificar', '["infección bursa rodilla izquierda", "bursitis rodilla izquierda", "rodilla infectada", "bursitis séptica"]'),
('M71.169', 'Otras bursitis infecciosas, rodilla no especificada', 'Sin especificar', '["infección bursa rodilla", "bursitis rodilla", "rodilla infectada", "bursitis séptica"]'),
('M71.171', 'Otras bursitis infecciosas, tobillo y pie derechos', 'Sin especificar', '["infección bursa tobillo derecho", "bursitis pie derecho", "tobillo infectado", "bursitis séptica"]'),
('M71.172', 'Otras bursitis infecciosas, tobillo y pie izquierdos', 'Sin especificar', '["infección bursa tobillo izquierdo", "bursitis pie izquierdo", "tobillo infectado", "bursitis séptica"]'),
('M71.179', 'Otras bursitis infecciosas, tobillo y pie no especificados', 'Sin especificar', '["infección bursa tobillo", "bursitis pie", "tobillo infectado", "bursitis séptica"]'),
('M71.18', 'Otras bursitis infecciosas, otra localización', 'Sin especificar', '["bursitis infecciosa otra", "infección de bursa rara", "bursitis séptica cuerpo"]'),
('M71.19', 'Otras bursitis infecciosas, localizaciones múltiples', 'Sin especificar', '["bursitis infecciosa múltiple", "múltiples bursas infectadas", "bursitis séptica generalizada"]'),
('M71.20', 'Quiste sinovial de espacio poplíteo [Baker], rodilla no especificada', 'Sin especificar', '["quiste de baker", "bolita detrás de la rodilla", "quiste en el hueco poplíteo", "quiste de rodilla", "bulto detrás de la rodilla", "quiste sinovial rodilla", "hinchazón poplítea"]'),
('M71.21', 'Quiste sinovial de espacio poplíteo [Baker], rodilla derecha', 'Sin especificar', '["quiste de baker rodilla derecha", "bolita en rodilla derecha", "quiste hueco poplíteo derecho", "bulto detrás rodilla derecha"]'),
('M71.22', 'Quiste sinovial de espacio poplíteo [Baker], rodilla izquierda', 'Sin especificar', '["quiste de baker rodilla izquierda", "bolita en rodilla izquierda", "quiste hueco poplíteo izquierdo", "bulto detrás rodilla izquierda"]'),
('M71.30', 'Otro tipo de quiste de bolsa sinovial, localización no especificada', 'Sin especificar', '["quiste sinovial", "ganglión", "bulto en la articulación", "bolita en la piel", "quiste articular", "bolsa sinovial inflamada", "quiste de líquido"]'),
('M71.311', 'Otro tipo de quiste de bolsa sinovial, hombro derecho', 'Sin especificar', '["quiste sinovial hombro derecho", "bulto en el hombro derecho", "quiste en el hombro", "bolita hombro"]'),
('M71.312', 'Otro tipo de quiste de bolsa sinovial, hombro izquierdo', 'Sin especificar', '["quiste sinovial hombro izquierdo", "bulto en el hombro izquierdo", "quiste en el hombro", "bolita hombro"]'),
('M71.319', 'Otro tipo de quiste de bolsa sinovial, hombro no especificado', 'Sin especificar', '["quiste sinovial hombro", "bulto en el hombro", "quiste en bursa del hombro"]'),
('M71.321', 'Otro tipo de quiste de bolsa sinovial, codo derecho', 'Sin especificar', '["quiste sinovial codo derecho", "bulto en el codo derecho", "quiste codo", "bolita codo"]'),
('M71.322', 'Otro tipo de quiste de bolsa sinovial, codo izquierdo', 'Sin especificar', '["quiste sinovial codo izquierdo", "bulto en el codo izquierdo", "quiste codo", "bolita codo"]'),
('M71.329', 'Otro tipo de quiste de bolsa sinovial, codo no especificado', 'Sin especificar', '["quiste sinovial codo", "bulto en el codo", "quiste codo"]'),
('M71.331', 'Otro tipo de quiste de bolsa sinovial, muñeca derecha', 'Sin especificar', '["quiste sinovial muñeca derecha", "ganglión muñeca derecha", "bulto en la muñeca derecha", "bolita muñeca"]'),
('M71.332', 'Otro tipo de quiste de bolsa sinovial, muñeca izquierda', 'Sin especificar', '["quiste sinovial muñeca izquierda", "ganglión muñeca izquierda", "bulto en la muñeca izquierda", "bolita muñeca"]'),
('M71.339', 'Otro tipo de quiste de bolsa sinovial, muñeca no especificada', 'Sin especificar', '["quiste sinovial muñeca", "ganglión muñeca", "bulto en la muñeca"]'),
('M71.341', 'Otro tipo de quiste de bolsa sinovial, mano derecha', 'Sin especificar', '["quiste sinovial mano derecha", "bulto mano derecha", "bolita en la mano"]'),
('M71.342', 'Otro tipo de quiste de bolsa sinovial, mano izquierda', 'Sin especificar', '["quiste sinovial mano izquierda", "bulto mano izquierda", "bolita en la mano"]'),
('M71.349', 'Otro tipo de quiste de bolsa sinovial, mano no especificada', 'Sin especificar', '["quiste sinovial mano", "bulto en la mano"]'),
('M71.351', 'Otro tipo de quiste de bolsa sinovial, cadera derecha', 'Sin especificar', '["quiste sinovial cadera derecha", "bulto en la cadera derecha"]'),
('M71.352', 'Otro tipo de quiste de bolsa sinovial, cadera izquierda', 'Sin especificar', '["quiste sinovial cadera izquierda", "bulto en la cadera izquierda"]'),
('M71.359', 'Otro tipo de quiste de bolsa sinovial, cadera no especificada', 'Sin especificar', '["quiste sinovial cadera", "bulto en la cadera"]'),
('M71.371', 'Otro tipo de quiste de bolsa sinovial, tobillo y pie derechos', 'Sin especificar', '["quiste sinovial tobillo derecho", "bulto tobillo derecho"]'),
('M71.372', 'Otro tipo de quiste de bolsa sinovial, tobillo y pie izquierdos', 'Sin especificar', '["quiste sinovial tobillo izquierdo", "bulto tobillo izquierdo"]'),
('M71.379', 'Otro tipo de quiste de bolsa sinovial, tobillo y pie no especificados', 'Sin especificar', '["quiste sinovial tobillo", "bulto en el tobillo"]'),
('M71.38', 'Otro tipo de quiste de bolsa sinovial, otra localización', 'Sin especificar', '["quiste bursa", "bulto articular"]'),
('M71.39', 'Otro tipo de quiste de bolsa sinovial, localizaciones múltiples', 'Sin especificar', '["quistes sinoviales múltiples", "varios bultos articulares"]'),
('M71.40', 'Depósito de calcio en bolsa sinovial, localización no especificada', 'Sin especificar', '["calcio en la bursa", "bursitis calcificante", "calcificación en el hombro", "calcio en articulación", "dolor por calcificación"]'),
('M71.421', 'Depósito de calcio en bolsa sinovial, codo derecho', 'Sin especificar', '["calcio bursa codo derecho", "bursitis calcificante codo", "calcificación codo derecho"]'),
('M71.422', 'Depósito de calcio en bolsa sinovial, codo izquierdo', 'Sin especificar', '["calcio bursa codo izquierdo", "bursitis calcificante codo", "calcificación codo izquierdo"]'),
('M71.429', 'Depósito de calcio en bolsa sinovial, codo no especificado', 'Sin especificar', '["calcio bursa codo", "bursitis calcificante codo"]'),
('M71.431', 'Depósito de calcio en bolsa sinovial, muñeca derecha', 'Sin especificar', '["calcio bursa muñeca derecha", "bursitis calcificante muñeca"]'),
('M71.432', 'Depósito de calcio en bolsa sinovial, muñeca izquierda', 'Sin especificar', '["calcio bursa muñeca izquierda", "bursitis calcificante muñeca"]'),
('M71.439', 'Depósito de calcio en bolsa sinovial, muñeca no especificada', 'Sin especificar', '["calcio bursa muñeca", "bursitis calcificante muñeca"]'),
('M71.441', 'Depósito de calcio en bolsa sinovial, mano derecha', 'Sin especificar', '["calcio bursa mano derecha", "bursitis calcificante mano"]'),
('M71.442', 'Depósito de calcio en bolsa sinovial, mano izquierda', 'Sin especificar', '["calcio bursa mano izquierda", "bursitis calcificante mano"]'),
('M71.449', 'Depósito de calcio en bolsa sinovial, mano no especificada', 'Sin especificar', '["calcio bursa mano", "bursitis calcificante mano"]'),
('M71.451', 'Depósito de calcio en bolsa sinovial, cadera derecha', 'Sin especificar', '["calcio bursa cadera derecha", "bursitis calcificante cadera"]'),
('M71.452', 'Depósito de calcio en bolsa sinovial, cadera izquierda', 'Sin especificar', '["calcio bursa cadera izquierda", "bursitis calcificante cadera"]'),
('M71.459', 'Depósito de calcio en bolsa sinovial, cadera no especificada', 'Sin especificar', '["calcio bursa cadera", "bursitis calcificante cadera"]'),
('M71.461', 'Depósito de calcio en bolsa sinovial, rodilla derecha', 'Sin especificar', '["calcio bursa rodilla derecha", "bursitis calcificante rodilla"]'),
('M71.462', 'Depósito de calcio en bolsa sinovial, rodilla izquierda', 'Sin especificar', '["calcio bursa rodilla izquierda", "bursitis calcificante rodilla"]'),
('M71.469', 'Depósito de calcio en bolsa sinovial, rodilla no especificada', 'Sin especificar', '["calcio bursa rodilla", "bursitis calcificante rodilla"]'),
('M71.471', 'Depósito de calcio en bolsa sinovial, tobillo y pie derechos', 'Sin especificar', '["calcio bursa tobillo derecho", "bursitis calcificante tobillo"]'),
('M71.472', 'Depósito de calcio en bolsa sinovial, tobillo y pie izquierdos', 'Sin especificar', '["calcio bursa tobillo izquierdo", "bursitis calcificante tobillo"]'),
('M71.479', 'Depósito de calcio en bolsa sinovial, tobillo y pie no especificados', 'Sin especificar', '["calcio bursa tobillo", "bursitis calcificante tobillo"]'),
('M71.48', 'Depósito de calcio en bolsa sinovial, otro sitio', 'Sin especificar', '["calcio bursa", "bursitis calcificante"]'),
('M71.49', 'Depósito de calcio en bolsa sinovial, lesiones múltiples', 'Sin especificar', '["bursitis calcificante múltiple", "varias calcificaciones"]'),
('M71.50', 'Otro tipo de bursitis, no clasificada bajo otro concepto, localización no especificada', 'Sin especificar', '["bursitis", "inflamación de la bursa", "dolor articular", "bolsa sinovial inflamada", "hinchazón articular"]'),
('M71.521', 'Otro tipo de bursitis, no clasificada bajo otro concepto, codo derecho', 'Sin especificar', '["bursitis codo derecho", "codo inflamado"]'),
('M71.522', 'Otro tipo de bursitis, no clasificada bajo otro concepto, codo izquierdo', 'Sin especificar', '["bursitis codo izquierdo", "codo inflamado"]'),
('M71.529', 'Otro tipo de bursitis, no clasificada bajo otro concepto, codo no especificado', 'Sin especificar', '["bursitis codo", "codo inflamado"]'),
('M71.531', 'Otro tipo de bursitis, no clasificada bajo otro concepto, muñeca derecha', 'Sin especificar', '["bursitis muñeca derecha", "muñeca inflamada"]'),
('M71.532', 'Otro tipo de bursitis, no clasificada bajo otro concepto, muñeca izquierda', 'Sin especificar', '["bursitis muñeca izquierda", "muñeca inflamada"]'),
('M71.539', 'Otro tipo de bursitis, no clasificada bajo otro concepto, muñeca no especificada', 'Sin especificar', '["bursitis muñeca", "muñeca inflamada"]'),
('M71.541', 'Otro tipo de bursitis, no clasificada bajo otro concepto, mano derecha', 'Sin especificar', '["bursitis mano derecha", "mano inflamada"]'),
('M71.542', 'Otro tipo de bursitis, no clasificada bajo otro concepto, mano izquierda', 'Sin especificar', '["bursitis mano izquierda", "mano inflamada"]'),
('M71.549', 'Otro tipo de bursitis, no clasificada bajo otro concepto, mano no especificada', 'Sin especificar', '["bursitis mano", "mano inflamada"]'),
('M71.551', 'Otro tipo de bursitis, no clasificada bajo otro concepto, cadera derecha', 'Sin especificar', '["bursitis cadera derecha", "cadera inflamada"]'),
('M71.552', 'Otro tipo de bursitis, no clasificada bajo otro concepto, cadera izquierda', 'Sin especificar', '["bursitis cadera izquierda", "cadera inflamada"]'),
('M71.559', 'Otro tipo de bursitis, no clasificada bajo otro concepto, cadera no especificada', 'Sin especificar', '["bursitis cadera", "cadera inflamada"]'),
('M71.561', 'Otro tipo de bursitis, no clasificada bajo otro concepto, rodilla derecha', 'Sin especificar', '["bursitis rodilla derecha", "rodilla inflamada"]'),
('M71.562', 'Otro tipo de bursitis, no clasificada bajo otro concepto, rodilla izquierda', 'Sin especificar', '["bursitis rodilla izquierda", "rodilla inflamada"]'),
('M71.569', 'Otro tipo de bursitis, no clasificada bajo otro concepto, rodilla no especificada', 'Sin especificar', '["bursitis rodilla", "rodilla inflamada"]'),
('M71.571', 'Otro tipo de bursitis, no clasificada bajo otro concepto, tobillo y pie derechos', 'Sin especificar', '["bursitis tobillo derecho", "pie inflamado"]'),
('M71.572', 'Otro tipo de bursitis, no clasificada bajo otro concepto, tobillo y pie izquierdos', 'Sin especificar', '["bursitis tobillo izquierdo", "pie inflamado"]'),
('M71.579', 'Otro tipo de bursitis, no clasificada bajo otro concepto, tobillo y pie no especificados', 'Sin especificar', '["bursitis tobillo", "pie inflamado"]'),
('M71.58', 'Otro tipo de bursitis, no clasificada bajo otro concepto, otra localización', 'Sin especificar', '["bursitis", "inflamación articular"]'),
('M71.80', 'Otras bursopatías especificadas, localización no especificada', 'Sin especificar', '["problema de bursa", "bursopatía", "dolor articular crónico"]'),
('M71.811', 'Otras bursopatías especificadas, hombro derecho', 'Sin especificar', '["problema de bursa hombro", "bursopatía hombro derecho"]'),
('M71.812', 'Otras bursopatías especificadas, hombro izquierdo', 'Sin especificar', '["problema de bursa hombro", "bursopatía hombro izquierdo"]'),
('M71.819', 'Otras bursopatías especificadas, hombro no especificado', 'Sin especificar', '["problema de bursa hombro", "bursopatía hombro"]'),
('M71.821', 'Otras bursopatías especificadas, codo derecho', 'Sin especificar', '["problema de bursa codo", "bursopatía codo derecho"]'),
('M71.822', 'Otras bursopatías especificadas, codo izquierdo', 'Sin especificar', '["problema de bursa codo", "bursopatía codo izquierdo"]'),
('M71.829', 'Otras bursopatías especificadas, codo no especificado', 'Sin especificar', '["problema de bursa codo", "bursopatía codo"]'),
('M71.831', 'Otras bursopatías especificadas, muñeca derecha', 'Sin especificar', '["problema de bursa muñeca", "bursopatía muñeca derecha"]'),
('M71.832', 'Otras bursopatías especificadas, muñeca izquierda', 'Sin especificar', '["problema de bursa muñeca", "bursopatía muñeca izquierda"]'),
('M71.839', 'Otras bursopatías especificadas, muñeca no especificada', 'Sin especificar', '["problema de bursa muñeca", "bursopatía muñeca"]'),
('M71.841', 'Otras bursopatías especificadas, mano derecha', 'Sin especificar', '["problema de bursa mano", "bursopatía mano derecho"]'),
('M71.842', 'Otras bursopatías especificadas, mano izquierda', 'Sin especificar', '["problema de bursa mano", "bursopatía mano izquierda"]'),
('M71.849', 'Otras bursopatías especificadas, mano no especificada', 'Sin especificar', '["problema de bursa mano", "bursopatía mano"]'),
('M71.851', 'Otras bursopatías especificadas, cadera derecha', 'Sin especificar', '["problema de bursa cadera", "bursopatía cadera derecha"]'),
('M71.852', 'Otras bursopatías especificadas, cadera izquierda', 'Sin especificar', '["problema de bursa cadera", "bursopatía cadera izquierda"]'),
('M71.859', 'Otras bursopatías especificadas, cadera no especificada', 'Sin especificar', '["problema de bursa cadera", "bursopatía cadera"]'),
('M71.861', 'Otras bursopatías especificadas, rodilla derecha', 'Sin especificar', '["problema de bursa rodilla", "bursopatía rodilla derecha"]'),
('M71.862', 'Otras bursopatías especificadas, rodilla izquierda', 'Sin especificar', '["problema de bursa rodilla", "bursopatía rodilla izquierda"]'),
('M71.869', 'Otras bursopatías especificadas, rodilla no especificada', 'Sin especificar', '["problema de bursa rodilla", "bursopatía rodilla"]'),
('M71.871', 'Otras bursopatías especificadas, tobillo y pie derechos', 'Sin especificar', '["problema de bursa tobillo", "bursopatía tobillo derecho"]'),
('M71.872', 'Otras bursopatías especificadas, tobillo y pie izquierdos', 'Sin especificar', '["problema de bursa tobillo", "bursopatía tobillo izquierdo"]'),
('M71.879', 'Otras bursopatías especificadas, tobillo y pie no especificados', 'Sin especificar', '["problema de bursa tobillo", "bursopatía tobillo"]'),
('M71.88', 'Otras bursopatías especificadas, otra localización', 'Sin especificar', '["problema de bursa", "bursopatía"]'),
('M71.89', 'Otras bursopatías especificadas, localizaciones múltiples', 'Sin especificar', '["bursopatías múltiples", "problemas en varias bursas"]'),
('M71.9', 'Bursopatía, no especificada', 'Sin especificar', '["bursopatía", "dolor en la bolsa sinovial", "enfermedad de la bursa", "problemas en articulaciones", "inflamación articular desconocida"]');
