INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('T25.011A', 'Quemadura de grado no especificado de tobillo derecho, contacto inicial', 'Sin especificar', '["quemada", "ampolla en tobillo", "dolor en tobillo", "piel quemada", "accidente tobillo", "herida en el pie", "escaldadura tobillo", "quemadura reciente", "urgencia tobillo", "tobillo hinchado por quemadura", "quemazón pie", "curación quemadura", "primeros auxilios tobillo"]'),
('T25.011D', 'Quemadura de grado no especificado de tobillo derecho, contacto sucesivo', 'Sin especificar', '["control quemadura", "seguimiento herida", "curación infectada", "seguimiento quemada tobillo", "cambio de vendaje", "revisión tobillo", "costra tobillo", "piel cicatrizando", "consulta posterior quemadura", "seguimiento médico"]'),
('T25.011S', 'Quemadura de grado no especificado de tobillo derecho, secuela', 'Sin especificar', '["cicatriz en el tobillo", "mancha por quemadura", "queloide tobillo", "piel tirante", "secuela de quemadura", "cicatriz queloide", "dolor crónico tobillo", "marca de quemada", "retracción de piel", "piel quemada antigua"]'),
('T25.012A', 'Quemadura de grado no especificado de tobillo izquierdo, contacto inicial', 'Sin especificar', '["quemada pie izquierdo", "ampolla tobillo izquierdo", "accidente pie", "urgencia quemadura", "tobillo izquierdo ardiendo", "piel dañada tobillo", "escaldadura", "quemadura nueva", "dolor tobillo izquierdo"]'),
('T25.012D', 'Quemadura de grado no especificado de tobillo izquierdo, contacto sucesivo', 'Sin especificar', '["curación sucesiva tobillo", "control médico quemada", "revisión herida", "vendaje tobillo izquierdo", "seguimiento cicatrización", "observación quemadura", "limpieza herida"]'),
('T25.012S', 'Quemadura de grado no especificado de tobillo izquierdo, secuela', 'Sin especificar', '["cicatriz tobillo izquierdo", "piel dañada permanente", "marca de quemadura", "queloides", "piel rígida", "secuela antigua", "quemadura curada mal", "mancha en la piel"]'),
('T25.019A', 'Quemadura de grado no especificado de tobillo no especificado, contacto inicial', 'Sin especificar', '["quemada tobillo", "quemadura en el hueso del pie", "accidente en el tobillo", "dolor en tobillo quemado", "piel roja tobillo", "urgencia pie", "quemazón", "herida en la articulación"]'),
('T25.019D', 'Quemadura de grado no especificado de tobillo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento médico tobillo", "cambio de vendas", "curación quemada", "revisión tobillo", "consulta control", "observación quemadura", "herida en proceso"]'),
('T25.019S', 'Quemadura de grado no especificado de tobillo no especificado, secuela', 'Sin especificar', '["cicatriz tobillo", "marcas en la piel", "lesión antigua", "queloides", "piel con secuelas", "mancha oscura", "piel rígida post quemadura"]'),
('T25.021A', 'Quemadura de grado no especificado del pie derecho, contacto inicial', 'Sin especificar', '["quemada en el pie", "pie ardiendo", "ampolla en el pie", "quemadura empeine", "accidente pie derecho", "dolor en el pie", "piel quemada", "urgencia médica", "escaldado pie"]'),
('T25.021D', 'Quemadura de grado no especificado del pie derecho, contacto sucesivo', 'Sin especificar', '["curación pie", "seguimiento quemada pie", "cambio de cura", "revisión herida", "control médico", "herida en recuperación"]'),
('T25.021S', 'Quemadura de grado no especificado del pie derecho, secuela', 'Sin especificar', '["cicatriz pie", "piel retraída", "marcas de quemada", "queloide", "piel dura", "cicatrización deficiente"]'),
('T25.022A', 'Quemadura de grado no especificado del pie izquierdo, contacto inicial', 'Sin especificar', '["quemada pie izquierdo", "pie ardiendo", "ampollas en el pie", "quemadura por calor", "accidente en pie izquierdo", "dolor agudo pie", "urgencia quemadura"]'),
('T25.022D', 'Quemadura de grado no especificado del pie izquierdo, contacto sucesivo', 'Sin especificar', '["curación pie izquierdo", "seguimiento quemadura", "revisión herida pie", "cambio de venda", "control médico herida"]'),
('T25.022S', 'Quemadura de grado no especificado del pie izquierdo, secuela', 'Sin especificar', '["cicatriz pie izquierdo", "mancha quemada", "secuela piel", "queloide", "piel tirante pie", "cicatriz antigua"]'),
('T25.029A', 'Quemadura de grado no especificado de pie no especificado, contacto inicial', 'Sin especificar', '["quemada en el pie", "quemadura planta", "quemadura empeine", "ampollas", "dolor quemante pie", "accidente piel pie", "urgencia quemadura"]'),
('T25.029D', 'Quemadura de grado no especificado de pie no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento pie", "curación herida", "revisión médica", "control de quemadura", "cambio de apósito"]'),
('T25.029S', 'Quemadura de grado no especificado de pie no especificado, secuela', 'Sin especificar', '["cicatriz en el pie", "marcas en la piel", "lesión post quemadura", "queloide", "piel endurecida", "secuelas de quemada"]'),
('T25.031A', 'Quemadura de grado no especificado de dedo(s) del pie derecho (uña), contacto inicial', 'Sin especificar', '["quemada dedo pie", "quemadura uña", "dedo del pie ardiendo", "dolor dedo pie", "ampolla uña", "quemazón dedo pie", "accidente uña pie"]'),
('T25.031D', 'Quemadura de grado no especificado de dedo(s) del pie derecho (uña), contacto sucesivo', 'Sin especificar', '["curación dedo pie", "seguimiento uña", "control herida dedo", "revisión uña", "cambio de venda dedo"]'),
('T25.031S', 'Quemadura de grado no especificado de dedo(s) del pie derecho (uña), secuela', 'Sin especificar', '["cicatriz dedo pie", "uña deformada", "secuela dedo", "cicatriz uña", "piel rígida dedo"]'),
('T25.032A', 'Quemadura de grado no especificado de dedo(s) del pie izquierdo (uña), contacto inicial', 'Sin especificar', '["quemada dedo pie izquierdo", "quemadura uña", "dolor dedo pie", "ampolla dedo", "accidente dedo", "dedo ardiendo"]'),
('T25.032D', 'Quemadura de grado no especificado de dedo(s) del pie izquierdo (uña), contacto sucesivo', 'Sin especificar', '["curación dedo izquierdo", "seguimiento uña pie", "control médico", "revisión dedo", "cura herida"]'),
('T25.032S', 'Quemadura de grado no especificado de dedo(s) del pie izquierdo (uña), secuela', 'Sin especificar', '["secuela dedo pie", "cicatriz en el dedo", "uña dañada", "piel con marcas", "cicatriz permanente"]'),
('T25.039A', 'Quemadura de grado no especificados de dedo(s) (uñas) de pie no especificados, contacto inicial', 'Sin especificar', '["quemada dedos", "quemadura uñas", "dedos del pie quemados", "dolor dedos pie", "ampollas dedos", "urgencia dedos"]'),
('T25.039D', 'Quemadura de grado no especificados de dedo(s) (uñas) de pie no especificados, contacto sucesivo', 'Sin especificar', '["seguimiento dedos pie", "curación dedos", "revisión uñas", "control médico", "cambio vendaje dedos"]'),
('T25.039S', 'Quemadura de grado no especificados de dedo(s) (uñas) de pie no especificados, secuela', 'Sin especificar', '["cicatriz dedos", "secuela quemada", "marcas en uñas", "piel endurecida dedos", "cicatriz permanente"]'),
('T25.091A', 'Quemadura de grado no especificado de localizaciones múltiples de tobillo y pie derechos, contacto inicial', 'Sin especificar', '["quemada en pie y tobillo", "quemadura múltiple pie", "pie derecho ardiendo", "dolor pie tobillo", "urgencia quemadura", "accidente pie derecho"]'),
('T25.091D', 'Quemadura de grado no especificado de localizaciones múltiples de tobillo y pie derechos, contacto sucesivo', 'Sin especificar', '["curación pie y tobillo", "seguimiento quemada", "revisión múltiple", "control médico", "limpieza heridas"]'),
('T25.091S', 'Quemadura de grado no especificado de localizaciones múltiples de tobillo y pie derechos, secuela', 'Sin especificar', '["cicatriz pie tobillo", "secuelas múltiples", "marcas de quemadura", "piel dañada", "queloide"]'),
('T25.092A', 'Quemadura de grado no especificado de localizaciones múltiples de tobillo y pie izquierdos, contacto inicial', 'Sin especificar', '["quemada pie izquierdo y tobillo", "quemadura extensa pie", "dolor pie y tobillo", "ampollas", "urgencia"]'),
('T25.092D', 'Quemadura de grado no especificado de localizaciones múltiples de tobillo y pie izquierdos, contacto sucesivo', 'Sin especificar', '["curación pie izquierdo", "seguimiento herida", "revisión médica", "control quemadura", "cuidado de heridas"]'),
('T25.092S', 'Quemadura de grado no especificado de localizaciones múltiples de tobillo y pie izquierdos, secuela', 'Sin especificar', '["cicatriz pie izquierdo", "marcas en la piel", "secuela quemadura", "queloide", "piel con cicatrices"]'),
('T25.099A', 'Quemadura de grado no especificados de localizaciones múltiples de tobillo y pie no especificados, contacto inicial', 'Sin especificar', '["quemadura pie y tobillo", "quemada múltiples zonas", "dolor pie tobillo", "ampollas extensas", "urgencia"]'),
('T25.099D', 'Quemadura de grado no especificados de localizaciones múltiples de tobillo y pie no especificados, contacto sucesivo', 'Sin especificar', '["curación pie tobillo", "seguimiento médico", "control quemadura", "revisión heridas"]'),
('T25.099S', 'Quemadura de grado no especificados de localizaciones múltiples de tobillo y pie no especificados, secuela', 'Sin especificar', '["cicatriz tobillo pie", "secuela quemadura", "marcas piel", "piel endurecida", "queloide"]'),
('T25.111A', 'Quemadura de primer grado de tobillo derecho, contacto inicial', 'Sin especificar', '["quemada leve tobillo", "piel roja tobillo", "quemadura primer grado", "ardor tobillo", "insolación tobillo", "tobillo quemado"]'),
('T25.111D', 'Quemadura de primer grado de tobillo derecho, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura leve", "revisión tobillo", "curación ardor", "control médico", "cuidado piel"]'),
('T25.111S', 'Quemadura de primer grado de tobillo derecho, secuela', 'Sin especificar', '["mancha quemadura", "piel sensible tobillo", "secuela leve", "marcas solares", "piel dañada"]'),
('T25.112A', 'Quemadura de primer grado de tobillo izquierdo, contacto inicial', 'Sin especificar', '["quemada leve tobillo izquierdo", "ardor tobillo", "piel enrojecida", "quemadura primer grado", "tobillo quemado"]'),
('T25.112D', 'Quemadura de primer grado de tobillo izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura", "revisión tobillo", "control médico", "curación piel"]'),
('T25.112S', 'Quemadura de primer grado de tobillo izquierdo, secuela', 'Sin especificar', '["mancha piel", "piel sensible", "secuela leve", "quemadura curada"]'),
('T25.119A', 'Quemadura de primer grado de tobillo no especificado, contacto inicial', 'Sin especificar', '["quemada leve tobillo", "ardor", "piel roja", "quemadura grado 1", "tobillo quemado"]'),
('T25.119D', 'Quemadura de primer grado de tobillo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura", "revisión tobillo", "control curación", "cuidado piel"]'),
('T25.119S', 'Quemadura de primer grado de tobillo no especificado, secuela', 'Sin especificar', '["mancha tobillo", "piel sensible", "secuela leve", "quemadura pasada"]'),
('T25.121A', 'Quemadura de primer grado del pie derecho, contacto inicial', 'Sin especificar', '["quemada leve pie", "pie rojo", "ardor pie", "quemadura 1er grado", "insolación pie"]'),
('T25.121D', 'Quemadura de primer grado del pie derecho, contacto sucesivo', 'Sin especificar', '["seguimiento pie", "revisión quemadura", "control curación", "cuidado piel pie"]'),
('T25.121S', 'Quemadura de primer grado del pie derecho, secuela', 'Sin especificar', '["mancha pie", "piel sensible", "secuela leve", "piel descamada"]'),
('T25.122A', 'Quemadura de primer grado del pie izquierdo, contacto inicial', 'Sin especificar', '["quemada leve pie izquierdo", "pie rojo", "ardor", "quemadura 1er grado", "quemadura solar"]'),
('T25.122D', 'Quemadura de primer grado del pie izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento pie izquierdo", "revisión quemadura", "control piel"]'),
('T25.122S', 'Quemadura de primer grado del pie izquierdo, secuela', 'Sin especificar', '["mancha pie", "piel sensible", "secuela leve", "quemadura curada"]'),
('T25.129A', 'Quemadura de primer grado de pie no especificado, contacto inicial', 'Sin especificar', '["quemada leve pie", "enrojecimiento", "ardor", "quemadura primer grado", "quemadura sol"]'),
('T25.129D', 'Quemadura de primer grado de pie no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento pie", "revisión piel", "control quemadura", "cuidado"]'),
('T25.129S', 'Quemadura de primer grado de pie no especificado, secuela', 'Sin especificar', '["mancha piel", "piel sensible", "secuela leve", "quemadura vieja"]'),
('T25.131A', 'Quemadura de primer grado de dedo(s) del pie derecho (uña), contacto inicial', 'Sin especificar', '["quemada leve dedos", "ardor dedos", "uña roja", "quemadura primer grado dedos"]'),
('T25.131D', 'Quemadura de primer grado de dedo(s) del pie derecho (uña), contacto sucesivo', 'Sin especificar', '["seguimiento dedos pie", "revisión uñas", "control quemadura"]'),
('T25.131S', 'Quemadura de primer grado de dedo(s) del pie derecho (uña), secuela', 'Sin especificar', '["piel sensible dedos", "secuela leve", "mancha uña"]'),
('T25.132A', 'Quemadura de primer grado de dedo(s) del pie izquierdo (uña), contacto inicial', 'Sin especificar', '["quemada leve dedo izquierdo", "ardor dedos", "piel roja", "quemadura primer grado"]'),
('T25.132D', 'Quemadura de primer grado de dedo(s) del pie izquierdo (uña), contacto sucesivo', 'Sin especificar', '["seguimiento dedos", "revisión uña", "control curación"]'),
('T25.132S', 'Quemadura de primer grado de dedo(s) del pie izquierdo (uña), secuela', 'Sin especificar', '["piel sensible", "secuela leve", "mancha uña"]'),
('T25.139A', 'Quemadura de primer grado de dedo(s) (uñas) de pie no especificados, contacto inicial', 'Sin especificar', '["quemada leve dedos", "quemadura uñas", "ardor dedos", "piel roja"]'),
('T25.139D', 'Quemadura de primer grado de dedo(s) (uñas) de pie no especificados, contacto sucesivo', 'Sin especificar', '["seguimiento dedos", "revisión uñas", "control quemadura"]'),
('T25.139S', 'Quemadura de primer grado de dedo(s) (uñas) de pie no especificados, secuela', 'Sin especificar', '["piel sensible", "secuela leve", "marcas en uñas"]'),
('T25.191A', 'Quemadura de primer grado de localizaciones múltiples de tobillo y pie derechos, contacto inicial', 'Sin especificar', '["quemada leve pie y tobillo", "ardor piel", "enrojecimiento", "quemadura grado 1"]'),
('T25.191D', 'Quemadura de primer grado de localizaciones múltiples de tobillo y pie derechos, contacto sucesivo', 'Sin especificar', '["seguimiento pie tobillo", "revisión piel", "control quemadura"]'),
('T25.191S', 'Quemadura de primer grado de localizaciones múltiples de tobillo y pie derechos, secuela', 'Sin especificar', '["piel sensible", "secuela leve", "mancha piel"]'),
('T25.192A', 'Quemadura de primer grado de localizaciones múltiples de tobillo y pie izquierdos, contacto inicial', 'Sin especificar', '["quemada leve pie izquierdo", "enrojecimiento", "ardor", "quemadura grado 1"]'),
('T25.192D', 'Quemadura de primer grado de localizaciones múltiples de tobillo y pie izquierdos, contacto sucesivo', 'Sin especificar', '["seguimiento pie tobillo", "revisión piel", "control quemadura"]'),
('T25.192S', 'Quemadura de primer grado de localizaciones múltiples de tobillo y pie izquierdos, secuela', 'Sin especificar', '["piel sensible", "secuela leve", "mancha piel"]'),
('T25.199A', 'Quemadura de primer grado de localizaciones múltiples de tobillo y pie no especificados, contacto inicial', 'Sin especificar', '["quemada leve pie tobillo", "enrojecimiento", "ardor", "quemadura grado 1"]'),
('T25.199D', 'Quemadura de primer grado de localizaciones múltiples de tobillo y pie no especificados, contacto sucesivo', 'Sin especificar', '["seguimiento pie tobillo", "revisión piel", "control quemadura"]'),
('T25.199S', 'Quemadura de primer grado de localizaciones múltiples de tobillo y pie no especificados, secuela', 'Sin especificar', '["piel sensible", "secuela leve", "mancha piel"]'),
('T25.211A', 'Quemadura de segundo grado de tobillo derecho, contacto inicial', 'Sin especificar', '["quemada grave tobillo", "ampollas tobillo", "quemadura con ampolla", "piel levantada tobillo", "quemadura 2do grado"]'),
('T25.211D', 'Quemadura de segundo grado de tobillo derecho, contacto sucesivo', 'Sin especificar', '["curación quemada", "seguimiento ampollas", "revisión piel tobillo", "control infección"]'),
('T25.211S', 'Quemadura de segundo grado de tobillo derecho, secuela', 'Sin especificar', '["cicatriz tobillo", "piel retraída", "marcas profundas", "queloide"]'),
('T25.212A', 'Quemadura de segundo grado de tobillo izquierdo, contacto inicial', 'Sin especificar', '["quemada con ampollas tobillo", "quemadura grave", "piel dañada tobillo", "quemadura 2do grado"]'),
('T25.212D', 'Quemadura de segundo grado de tobillo izquierdo, contacto sucesivo', 'Sin especificar', '["curación tobillo", "seguimiento ampolla", "revisión herida", "control médico"]'),
('T25.212S', 'Quemadura de segundo grado de tobillo izquierdo, secuela', 'Sin especificar', '["cicatriz pie", "piel endurecida", "marcas", "secuela quemadura"]'),
('T25.219A', 'Quemadura de segundo grado de tobillo no especificado, contacto inicial', 'Sin especificar', '["quemada ampolla tobillo", "quemadura profunda", "piel levantada", "quemadura 2do grado"]'),
('T25.219D', 'Quemadura de segundo grado de tobillo no especificado, contacto sucesivo', 'Sin especificar', '["curación tobillo", "seguimiento herida", "revisión ampollas"]'),
('T25.219S', 'Quemadura de segundo grado de tobillo no especificado, secuela', 'Sin especificar', '["cicatriz", "piel dañada", "secuela", "queloide"]'),
('T25.221A', 'Quemadura de segundo grado del pie derecho, contacto inicial', 'Sin especificar', '["quemada pie ampollas", "quemadura con llaga", "piel levantada pie", "quemadura 2do grado"]'),
('T25.221D', 'Quemadura de segundo grado del pie derecho, contacto sucesivo', 'Sin especificar', '["curación pie", "seguimiento quemada", "control infección"]'),
('T25.221S', 'Quemadura de segundo grado del pie derecho, secuela', 'Sin especificar', '["cicatriz pie", "piel dañada", "marcas", "queloide"]'),
('T25.222A', 'Quemadura de segundo grado del pie izquierdo, contacto inicial', 'Sin especificar', '["quemada pie ampolla", "quemadura 2do grado", "piel abierta pie", "quemadura profunda"]'),
('T25.222D', 'Quemadura de segundo grado del pie izquierdo, contacto sucesivo', 'Sin especificar', '["curación pie izquierdo", "seguimiento ampollas", "revisión piel"]'),
('T25.222S', 'Quemadura de segundo grado del pie izquierdo, secuela', 'Sin especificar', '["cicatriz", "piel dura", "secuela profunda", "queloide"]'),
('T25.229A', 'Quemadura de segundo grado de pie no especificado, contacto inicial', 'Sin especificar', '["quemada ampollas pie", "quemadura profunda", "piel levantada", "quemadura grado 2"]'),
('T25.229D', 'Quemadura de segundo grado de pie no especificado, contacto sucesivo', 'Sin especificar', '["curación pie", "seguimiento herida", "revisión ampollas"]'),
('T25.229S', 'Quemadura de segundo grado de pie no especificado, secuela', 'Sin especificar', '["cicatriz pie", "piel endurecida", "marcas", "secuela"]'),
('T25.231A', 'Quemadura de segundo grado de dedo(s) del pie derecho (uña), contacto inicial', 'Sin especificar', '["quemada dedos ampollas", "quemadura uña", "dedo pie ardiendo", "quemadura grado 2"]'),
('T25.231D', 'Quemadura de segundo grado de dedo(s) del pie derecho (uña), contacto sucesivo', 'Sin especificar', '["curación dedo", "seguimiento uñas", "control herida"]'),
('T25.231S', 'Quemadura de segundo grado de dedo(s) del pie derecho (uña), secuela', 'Sin especificar', '["cicatriz dedos", "uña dañada", "marcas dedo"]'),
('T25.232A', 'Quemadura de segundo grado de dedo(s) del pie izquierdo (uña), contacto inicial', 'Sin especificar', '["quemada dedos ampolla", "quemadura grado 2", "dedo pie dañado"]'),
('T25.232D', 'Quemadura de segundo grado de dedo(s) del pie izquierdo (uña), contacto sucesivo', 'Sin especificar', '["curación dedos", "seguimiento uña", "revisión"]'),
('T25.232S', 'Quemadura de segundo grado de dedo(s) del pie izquierdo (uña), secuela', 'Sin especificar', '["cicatriz dedo", "uña deforme", "secuela quemada"]'),
('T25.239A', 'Quemadura de segundo grado de dedo(s) (uñas) de pie no especificados, contacto inicial', 'Sin especificar', '["quemada dedos ampollas", "quemadura uñas", "quemadura grado 2"]'),
('T25.239D', 'Quemadura de segundo grado de dedo(s) (uñas) de pie no especificados, contacto sucesivo', 'Sin especificar', '["curación dedos", "seguimiento uñas", "control"]'),
('T25.239S', 'Quemadura de segundo grado de dedo(s) (uñas) de pie no especificados, secuela', 'Sin especificar', '["cicatriz dedos", "marcas", "uñas dañadas"]'),
('T25.291A', 'Quemadura de segundo grado de localizaciones múltiples de tobillo y pie derechos, contacto inicial', 'Sin especificar', '["quemada pie tobillo ampollas", "quemadura grave pie", "quemadura grado 2"]'),
('T25.291D', 'Quemadura de segundo grado de localizaciones múltiples de tobillo y pie derechos, contacto sucesivo', 'Sin especificar', '["curación pie tobillo", "seguimiento heridas", "revisión"]'),
('T25.291S', 'Quemadura de segundo grado de localizaciones múltiples de tobillo y pie derechos, secuela', 'Sin especificar', '["cicatriz pie", "marcas", "queloide"]'),
('T25.292A', 'Quemadura de segundo grado de localizaciones múltiples de tobillo y pie izquierdos, contacto inicial', 'Sin especificar', '["quemada pie izquierdo", "ampollas tobillo", "quemadura grado 2"]'),
('T25.292D', 'Quemadura de segundo grado de localizaciones múltiples de tobillo y pie izquierdos, contacto sucesivo', 'Sin especificar', '["curación pie tobillo", "seguimiento herida", "revisión"]'),
('T25.292S', 'Quemadura de segundo grado de localizaciones múltiples de tobillo y pie izquierdos, secuela', 'Sin especificar', '["cicatriz pie", "marcas", "queloide"]'),
('T25.299A', 'Quemadura de segundo grado de localizaciones múltiples de tobillo y pie no especificados, contacto inicial', 'Sin especificar', '["quemada pie tobillo", "ampollas", "quemadura grado 2"]'),
('T25.299D', 'Quemadura de segundo grado de localizaciones múltiples de tobillo y pie no especificados, contacto sucesivo', 'Sin especificar', '["curación pie", "seguimiento", "revisión"]'),
('T25.299S', 'Quemadura de segundo grado de localizaciones múltiples de tobillo y pie no especificados, secuela', 'Sin especificar', '["cicatriz", "marcas", "queloide"]'),
('T25.311A', 'Quemadura de tercer grado de tobillo derecho, contacto inicial', 'Sin especificar', '["quemada profunda tobillo", "piel carbonizada", "quemadura grado 3", "daño piel tobillo", "urgencia extrema"]'),
('T25.311D', 'Quemadura de tercer grado de tobillo derecho, contacto sucesivo', 'Sin especificar', '["curación profunda", "reconstrucción piel", "seguimiento cirugía", "control hospitalario"]'),
('T25.311S', 'Quemadura de tercer grado de tobillo derecho, secuela', 'Sin especificar', '["cicatriz severa", "pérdida piel", "queloide", "retracción cicatriz"]'),
('T25.312A', 'Quemadura de tercer grado de tobillo izquierdo, contacto inicial', 'Sin especificar', '["quemada grave tobillo", "piel destruida", "quemadura severa", "urgencia médica"]'),
('T25.312D', 'Quemadura de tercer grado de tobillo izquierdo, contacto sucesivo', 'Sin especificar', '["curación piel", "reconstrucción", "seguimiento", "control"]'),
('T25.312S', 'Quemadura de tercer grado de tobillo izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela profunda", "pérdida tejido"]'),
('T25.319A', 'Quemadura de tercer grado de tobillo no especificado, contacto inicial', 'Sin especificar', '["quemada profunda tobillo", "piel quemada severa", "quemadura 3er grado"]'),
('T25.319D', 'Quemadura de tercer grado de tobillo no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción piel"]'),
('T25.319S', 'Quemadura de tercer grado de tobillo no especificado, secuela', 'Sin especificar', '["cicatriz", "queloide", "tejido perdido"]'),
('T25.321A', 'Quemadura de tercer grado del pie derecho, contacto inicial', 'Sin especificar', '["quemada grave pie", "piel carbonizada", "quemadura profunda", "urgencia"]'),
('T25.321D', 'Quemadura de tercer grado del pie derecho, contacto sucesivo', 'Sin especificar', '["curación pie", "seguimiento cirugía", "reconstrucción"]'),
('T25.321S', 'Quemadura de tercer grado del pie derecho, secuela', 'Sin especificar', '["cicatriz severa", "queloide", "piel deformada"]'),
('T25.322A', 'Quemadura de tercer grado del pie izquierdo, contacto inicial', 'Sin especificar', '["quemada profunda pie", "quemadura severa", "piel dañada", "urgencia"]'),
('T25.322D', 'Quemadura de tercer grado del pie izquierdo, contacto sucesivo', 'Sin especificar', '["curación pie", "reconstrucción", "seguimiento"]'),
('T25.322S', 'Quemadura de tercer grado del pie izquierdo, secuela', 'Sin especificar', '["cicatriz", "queloide", "tejido afectado"]'),
('T25.329A', 'Quemadura de tercer grado de pie no especificado, contacto inicial', 'Sin especificar', '["quemada grave pie", "quemadura severa", "piel quemada", "urgencia"]'),
('T25.329D', 'Quemadura de tercer grado de pie no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.329S', 'Quemadura de tercer grado de pie no especificado, secuela', 'Sin especificar', '["cicatriz", "queloide", "piel perdida"]'),
('T25.331A', 'Quemadura de tercer grado de dedo(s) del pie derecho (uña), contacto inicial', 'Sin especificar', '["quemada dedos", "quemadura severa", "uñas quemadas", "daño profundo"]'),
('T25.331D', 'Quemadura de tercer grado de dedo(s) del pie derecho (uña), contacto sucesivo', 'Sin especificar', '["curación dedos", "reconstrucción uña", "seguimiento"]'),
('T25.331S', 'Quemadura de tercer grado de dedo(s) del pie derecho (uña), secuela', 'Sin especificar', '["cicatriz dedos", "uñas dañadas", "pérdida dedo"]'),
('T25.332A', 'Quemadura de tercer grado de dedo(s) del pie izquierdo (uña), contacto inicial', 'Sin especificar', '["quemada profunda dedos", "quemadura severa", "uñas destruidas"]'),
('T25.332D', 'Quemadura de tercer grado de dedo(s) del pie izquierdo (uña), contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.332S', 'Quemadura de tercer grado de dedo(s) del pie izquierdo (uña), secuela', 'Sin especificar', '["cicatriz", "deformidad dedo", "uñas perdidas"]'),
('T25.339A', 'Quemadura de tercer grado de dedo(s) (uñas) de pie no especificados, contacto inicial', 'Sin especificar', '["quemada profunda dedos", "quemadura severa", "uñas afectadas"]'),
('T25.339D', 'Quemadura de tercer grado de dedo(s) (uñas) de pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.339S', 'Quemadura de tercer grado de dedo(s) (uñas) de pie no especificados, secuela', 'Sin especificar', '["cicatriz", "uñas deformes", "secuela severa"]'),
('T25.391A', 'Quemadura de tercer grado de localizaciones múltiples de tobillo y pie derechos, contacto inicial', 'Sin especificar', '["quemada grave extensa", "quemadura profunda pie", "urgencia"]'),
('T25.391D', 'Quemadura de tercer grado de localizaciones múltiples de tobillo y pie derechos, contacto sucesivo', 'Sin especificar', '["curación extensa", "seguimiento", "reconstrucción piel"]'),
('T25.391S', 'Quemadura de tercer grado de localizaciones múltiples de tobillo y pie derechos, secuela', 'Sin especificar', '["cicatriz extensa", "queloide", "daño permanente"]'),
('T25.392A', 'Quemadura de tercer grado de localizaciones múltiples de tobillo y pie izquierdos, contacto inicial', 'Sin especificar', '["quemada grave", "quemadura profunda", "urgencia pie izquierdo"]'),
('T25.392D', 'Quemadura de tercer grado de localizaciones múltiples de tobillo y pie izquierdos, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.392S', 'Quemadura de tercer grado de localizaciones múltiples de tobillo y pie izquierdos, secuela', 'Sin especificar', '["cicatriz", "daño tisular", "queloide"]'),
('T25.399A', 'Quemadura de tercer grado de localizaciones múltiples de tobillo y pie no especificados, contacto inicial', 'Sin especificar', '["quemada profunda", "quemadura severa", "daño pie tobillo"]'),
('T25.399D', 'Quemadura de tercer grado de localizaciones múltiples de tobillo y pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.399S', 'Quemadura de tercer grado de localizaciones múltiples de tobillo y pie no especificados, secuela', 'Sin especificar', '["cicatriz", "queloide", "secuela"]'),
('T25.411A', 'Corrosión de grado no especificado de tobillo derecho, contacto inicial', 'Sin especificar', '["quemadura química", "corrosión tobillo", "ácido pie", "piel quemada producto", "accidente químico"]'),
('T25.411D', 'Corrosión de grado no especificado de tobillo derecho, contacto sucesivo', 'Sin especificar', '["cura corrosión", "limpieza producto", "seguimiento químico", "revisión piel"]'),
('T25.411S', 'Corrosión de grado no especificado de tobillo derecho, secuela', 'Sin especificar', '["mancha química", "cicatriz corrosión", "secuela piel", "queloide"]'),
('T25.412A', 'Corrosión de grado no especificado de tobillo izquierdo, contacto inicial', 'Sin especificar', '["corrosión química", "quemadura ácido", "daño pie", "urgencia química"]'),
('T25.412D', 'Corrosión de grado no especificado de tobillo izquierdo, contacto sucesivo', 'Sin especificar', '["curación ácido", "revisión", "seguimiento"]'),
('T25.412S', 'Corrosión de grado no especificado de tobillo izquierdo, secuela', 'Sin especificar', '["cicatriz", "mancha", "daño"]'),
('T25.419A', 'Corrosión de grado no especificado de tobillo no especificado, contacto inicial', 'Sin especificar', '["corrosión química", "daño ácido", "quemada producto"]'),
('T25.419D', 'Corrosión de grado no especificado de tobillo no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "limpieza"]'),
('T25.419S', 'Corrosión de grado no especificado de tobillo no especificado, secuela', 'Sin especificar', '["cicatriz", "mancha", "secuela"]'),
('T25.421A', 'Corrosión de grado no especificado del pie derecho, contacto inicial', 'Sin especificar', '["corrosión pie", "quemadura ácida pie", "producto químico"]'),
('T25.421D', 'Corrosión de grado no especificado del pie derecho, contacto sucesivo', 'Sin especificar', '["curación", "revisión", "seguimiento"]'),
('T25.421S', 'Corrosión de grado no especificado del pie derecho, secuela', 'Sin especificar', '["cicatriz", "mancha", "daño"]'),
('T25.422A', 'Corrosión de grado no especificado del pie izquierdo, contacto inicial', 'Sin especificar', '["corrosión pie", "quemadura química", "ácido en pie"]'),
('T25.422D', 'Corrosión de grado no especificado del pie izquierdo, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.422S', 'Corrosión de grado no especificado del pie izquierdo, secuela', 'Sin especificar', '["cicatriz", "mancha", "secuela"]'),
('T25.429A', 'Corrosión de grado no especificado de pie no especificado, contacto inicial', 'Sin especificar', '["corrosión pie", "quemadura producto", "daño piel"]'),
('T25.429D', 'Corrosión de grado no especificado de pie no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.429S', 'Corrosión de grado no especificado de pie no especificado, secuela', 'Sin especificar', '["cicatriz", "mancha", "daño"]'),
('T25.431A', 'Corrosión de grado no especificado de dedo(s) del pie derecho (uña), contacto inicial', 'Sin especificar', '["corrosión dedos", "quemadura uñas", "ácido dedos"]'),
('T25.431D', 'Corrosión de grado no especificado de dedo(s) del pie derecho (uña), contacto sucesivo', 'Sin especificar', '["curación dedos", "revisión uñas", "seguimiento"]'),
('T25.431S', 'Corrosión de grado no especificado de dedo(s) del pie derecho (uña), secuela', 'Sin especificar', '["cicatriz", "uña dañada", "secuela"]'),
('T25.432A', 'Corrosión de grado no especificado de dedo(s) del pie izquierdo (uña), contacto inicial', 'Sin especificar', '["corrosión dedos", "ácido pie", "quemadura uñas"]'),
('T25.432D', 'Corrosión de grado no especificado de dedo(s) del pie izquierdo (uña), contacto sucesivo', 'Sin especificar', '["curación", "revisión", "seguimiento"]'),
('T25.432S', 'Corrosión de grado no especificado de dedo(s) del pie izquierdo (uña), secuela', 'Sin especificar', '["cicatriz", "uñas", "secuela"]'),
('T25.439A', 'Corrosión de grado no especificados de dedo(s) (uñas) de pie no especificados, contacto inicial', 'Sin especificar', '["corrosión dedos", "ácido", "quemadura uñas"]'),
('T25.439D', 'Corrosión de grado no especificados de dedo(s) (uñas) de pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "revisión", "seguimiento"]'),
('T25.439S', 'Corrosión de grado no especificados de dedo(s) (uñas) de pie no especificados, secuela', 'Sin especificar', '["cicatriz", "uñas", "secuela"]'),
('T25.491A', 'Corrosión de grado no especificado de localizaciones múltiples de tobillo y pie derechos, contacto inicial', 'Sin especificar', '["corrosión extensa", "daño químico", "quemadura pie"]'),
('T25.491D', 'Corrosión de grado no especificado de localizaciones múltiples de tobillo y pie derechos, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.491S', 'Corrosión de grado no especificado de localizaciones múltiples de tobillo y pie derechos, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.492A', 'Corrosión de grado no especificado de localizaciones múltiples de tobillo y pie izquierdos, contacto inicial', 'Sin especificar', '["corrosión extensa", "daño ácido", "quemadura"]'),
('T25.492D', 'Corrosión de grado no especificado de localizaciones múltiples de tobillo y pie izquierdos, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.492S', 'Corrosión de grado no especificado de localizaciones múltiples de tobillo y pie izquierdos, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.499A', 'Corrosión de grado no especificados de localizaciones múltiples de tobillo y pie no especificados, contacto inicial', 'Sin especificar', '["corrosión múltiple", "daño químico", "quemadura"]'),
('T25.499D', 'Corrosión de grado no especificados de localizaciones múltiples de tobillo y pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.499S', 'Corrosión de grado no especificados de localizaciones múltiples de tobillo y pie no especificados, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.511A', 'Corrosión de primer grado de tobillo derecho, contacto inicial', 'Sin especificar', '["irritación química", "rojez química", "corrosión leve", "quemadura grado 1"]'),
('T25.511D', 'Corrosión de primer grado de tobillo derecho, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.511S', 'Corrosión de primer grado de tobillo derecho, secuela', 'Sin especificar', '["mancha", "piel sensible", "secuela"]'),
('T25.512A', 'Corrosión de primer grado de tobillo izquierdo, contacto inicial', 'Sin especificar', '["irritación química", "quemadura leve", "corrosión grado 1"]'),
('T25.512D', 'Corrosión de primer grado de tobillo izquierdo, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.512S', 'Corrosión de primer grado de tobillo izquierdo, secuela', 'Sin especificar', '["mancha", "piel sensible", "secuela"]'),
('T25.519A', 'Corrosión de primer grado de tobillo no especificado, contacto inicial', 'Sin especificar', '["irritación química", "quemadura leve", "corrosión grado 1"]'),
('T25.519D', 'Corrosión de primer grado de tobillo no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.519S', 'Corrosión de primer grado de tobillo no especificado, secuela', 'Sin especificar', '["mancha", "piel sensible", "secuela"]'),
('T25.521A', 'Corrosión de primer grado del pie derecho, contacto inicial', 'Sin especificar', '["irritación pie", "quemadura ácida leve", "corrosión grado 1"]'),
('T25.521D', 'Corrosión de primer grado del pie derecho, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.521S', 'Corrosión de primer grado del pie derecho, secuela', 'Sin especificar', '["mancha", "piel sensible", "secuela"]'),
('T25.522A', 'Corrosión de primer grado del pie izquierdo, contacto inicial', 'Sin especificar', '["irritación pie", "quemadura leve", "corrosión"]'),
('T25.522D', 'Corrosión de primer grado del pie izquierdo, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.522S', 'Corrosión de primer grado del pie izquierdo, secuela', 'Sin especificar', '["mancha", "piel sensible", "secuela"]'),
('T25.529A', 'Corrosión de primer grado de pie no especificado, contacto inicial', 'Sin especificar', '["irritación piel", "quemadura leve", "corrosión"]'),
('T25.529D', 'Corrosión de primer grado de pie no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.529S', 'Corrosión de primer grado de pie no especificado, secuela', 'Sin especificar', '["mancha", "piel sensible", "secuela"]'),
('T25.531A', 'Corrosión de primer grado de dedo(s) (uñas) del pie derecho, contacto inicial', 'Sin especificar', '["irritación dedos", "uñas quemadas", "corrosión"]'),
('T25.531D', 'Corrosión de primer grado de dedo(s) (uñas) del pie derecho, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.531S', 'Corrosión de primer grado de dedo(s) (uñas) del pie derecho, secuela', 'Sin especificar', '["mancha", "uñas", "secuela"]'),
('T25.532A', 'Corrosión de primer grado de dedo(s) (uñas) del pie izquierdo, contacto inicial', 'Sin especificar', '["irritación dedos", "quemadura", "corrosión"]'),
('T25.532D', 'Corrosión de primer grado de dedo(s) (uñas) del pie izquierdo, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.532S', 'Corrosión de primer grado de dedo(s) (uñas) del pie izquierdo, secuela', 'Sin especificar', '["mancha", "uñas", "secuela"]'),
('T25.539A', 'Corrosión de primer grado de dedo(s) (uñas) de pie no especificados, contacto inicial', 'Sin especificar', '["irritación dedos", "quemadura", "corrosión"]'),
('T25.539D', 'Corrosión de primer grado de dedo(s) (uñas) de pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.539S', 'Corrosión de primer grado de dedo(s) (uñas) de pie no especificados, secuela', 'Sin especificar', '["mancha", "uñas", "secuela"]'),
('T25.591A', 'Corrosión de primer grado de localizaciones múltiples de tobillo y pie derechos, contacto inicial', 'Sin especificar', '["irritación", "quemadura leve", "corrosión"]'),
('T25.591D', 'Corrosión de primer grado de localizaciones múltiples de tobillo y pie derechos, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.591S', 'Corrosión de primer grado de localizaciones múltiples de tobillo y pie derechos, secuela', 'Sin especificar', '["mancha", "piel", "secuela"]'),
('T25.592A', 'Corrosión de primer grado de localizaciones múltiples de tobillo y pie izquierdos, contacto inicial', 'Sin especificar', '["irritación", "quemadura leve", "corrosión"]'),
('T25.592D', 'Corrosión de primer grado de localizaciones múltiples de tobillo y pie izquierdos, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.592S', 'Corrosión de primer grado de localizaciones múltiples de tobillo y pie izquierdos, secuela', 'Sin especificar', '["mancha", "piel", "secuela"]'),
('T25.599A', 'Corrosión de primer grado de localizaciones múltiples de tobillo y pie no especificados, contacto inicial', 'Sin especificar', '["irritación", "quemadura leve", "corrosión"]'),
('T25.599D', 'Corrosión de primer grado de localizaciones múltiples de tobillo y pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.599S', 'Corrosión de primer grado de localizaciones múltiples de tobillo y pie no especificados, secuela', 'Sin especificar', '["mancha", "piel", "secuela"]'),
('T25.611A', 'Corrosión de segundo grado de tobillo derecho, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura química", "piel dañada"]'),
('T25.611D', 'Corrosión de segundo grado de tobillo derecho, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.611S', 'Corrosión de segundo grado de tobillo derecho, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.612A', 'Corrosión de segundo grado de tobillo izquierdo, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura química", "daño piel"]'),
('T25.612D', 'Corrosión de segundo grado de tobillo izquierdo, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.612S', 'Corrosión de segundo grado de tobillo izquierdo, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.619A', 'Corrosión de segundo grado de tobillo no especificado, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura química", "daño piel"]'),
('T25.619D', 'Corrosión de segundo grado de tobillo no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.619S', 'Corrosión de segundo grado de tobillo no especificado, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.621A', 'Corrosión de segundo grado del pie derecho, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura química", "daño piel"]'),
('T25.621D', 'Corrosión de segundo grado del pie derecho, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.621S', 'Corrosión de segundo grado del pie derecho, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.622A', 'Corrosión de segundo grado del pie izquierdo, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura química", "daño piel"]'),
('T25.622D', 'Corrosión de segundo grado del pie izquierdo, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.622S', 'Corrosión de segundo grado del pie izquierdo, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.629A', 'Corrosión de segundo grado de pie no especificado, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura química", "daño piel"]'),
('T25.629D', 'Corrosión de segundo grado de pie no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.629S', 'Corrosión de segundo grado de pie no especificado, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.631A', 'Corrosión de segundo grado de dedo(s) del pie derecho (uña), contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura uñas", "daño dedos"]'),
('T25.631D', 'Corrosión de segundo grado de dedo(s) del pie derecho (uña), contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.631S', 'Corrosión de segundo grado de dedo(s) del pie derecho (uña), secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.632A', 'Corrosión de segundo grado de dedo(s) del pie izquierdo (uña), contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura uñas", "daño dedos"]'),
('T25.632D', 'Corrosión de segundo grado de dedo(s) del pie izquierdo (uña), contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.632S', 'Corrosión de segundo grado de dedo(s) del pie izquierdo (uña), secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.639A', 'Corrosión de segundo grado de dedo(s) (uñas) de pie no especificados, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura uñas", "daño dedos"]'),
('T25.639D', 'Corrosión de segundo grado de dedo(s) (uñas) de pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.639S', 'Corrosión de segundo grado de dedo(s) (uñas) de pie no especificados, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.691A', 'Corrosión de segundo grado de tobillo y pie derechos, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura química", "daño extenso"]'),
('T25.691D', 'Corrosión de segundo grado de tobillo y pie derechos, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.691S', 'Corrosión de segundo grado de tobillo y pie derechos, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.692A', 'Corrosión de segundo grado de tobillo y pie izquierdos, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura química", "daño extenso"]'),
('T25.692D', 'Corrosión de segundo grado de tobillo y pie izquierdos, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.692S', 'Corrosión de segundo grado de tobillo y pie izquierdos, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.699A', 'Corrosión de segundo grado de tobillo y pie no especificados, contacto inicial', 'Sin especificar', '["corrosión ampollas", "quemadura química", "daño extenso"]'),
('T25.699D', 'Corrosión de segundo grado de tobillo y pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "revisión"]'),
('T25.699S', 'Corrosión de segundo grado de tobillo y pie no especificados, secuela', 'Sin especificar', '["cicatriz", "mancha", "queloide"]'),
('T25.711A', 'Corrosión de tercer grado de tobillo derecho, contacto inicial', 'Sin especificar', '["corrosión grave", "piel destruida", "ácido profundo"]'),
('T25.711D', 'Corrosión de tercer grado de tobillo derecho, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.711S', 'Corrosión de tercer grado de tobillo derecho, secuela', 'Sin especificar', '["cicatriz severa", "pérdida piel", "queloide"]'),
('T25.712A', 'Corrosión de tercer grado de tobillo izquierdo, contacto inicial', 'Sin especificar', '["corrosión grave", "piel destruida", "ácido profundo"]'),
('T25.712D', 'Corrosión de tercer grado de tobillo izquierdo, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.712S', 'Corrosión de tercer grado de tobillo izquierdo, secuela', 'Sin especificar', '["cicatriz severa", "pérdida piel", "queloide"]'),
('T25.719A', 'Corrosión de tercer grado de tobillo no especificado, contacto inicial', 'Sin especificar', '["corrosión grave", "piel destruida", "ácido profundo"]'),
('T25.719D', 'Corrosión de tercer grado de tobillo no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.719S', 'Corrosión de tercer grado de tobillo no especificado, secuela', 'Sin especificar', '["cicatriz severa", "pérdida piel", "queloide"]'),
('T25.721A', 'Corrosión de tercer grado del pie derecho, contacto inicial', 'Sin especificar', '["corrosión grave", "piel destruida", "daño profundo"]'),
('T25.721D', 'Corrosión de tercer grado del pie derecho, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.721S', 'Corrosión de tercer grado del pie derecho, secuela', 'Sin especificar', '["cicatriz severa", "pérdida piel", "queloide"]'),
('T25.722A', 'Corrosión de tercer grado del pie izquierdo, contacto inicial', 'Sin especificar', '["corrosión grave", "piel destruida", "daño profundo"]'),
('T25.722D', 'Corrosión de tercer grado del pie izquierdo, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.722S', 'Corrosión de tercer grado del pie izquierdo, secuela', 'Sin especificar', '["cicatriz severa", "pérdida piel", "queloide"]'),
('T25.729A', 'Corrosión de tercer grado de pie no especificado, contacto inicial', 'Sin especificar', '["corrosión grave", "piel destruida", "daño profundo"]'),
('T25.729D', 'Corrosión de tercer grado de pie no especificado, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.729S', 'Corrosión de tercer grado de pie no especificado, secuela', 'Sin especificar', '["cicatriz severa", "pérdida piel", "queloide"]'),
('T25.731A', 'Corrosión de tercer grado de dedo(s) del pie derecho (uña), contacto inicial', 'Sin especificar', '["corrosión grave", "uñas destruidas", "dedos dañados"]'),
('T25.731D', 'Corrosión de tercer grado de dedo(s) del pie derecho (uña), contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.731S', 'Corrosión de tercer grado de dedo(s) del pie derecho (uña), secuela', 'Sin especificar', '["cicatriz", "uñas dañadas", "daño"]'),
('T25.732A', 'Corrosión de tercer grado de dedo(s) del pie izquierdo (uña), contacto inicial', 'Sin especificar', '["corrosión grave", "uñas destruidas", "dedos dañados"]'),
('T25.732D', 'Corrosión de tercer grado de dedo(s) del pie izquierdo (uña), contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.732S', 'Corrosión de tercer grado de dedo(s) del pie izquierdo (uña), secuela', 'Sin especificar', '["cicatriz", "uñas dañadas", "daño"]'),
('T25.739A', 'Corrosión de tercer grado de dedo(s) (uñas) de pie no especificados, contacto inicial', 'Sin especificar', '["corrosión grave", "uñas destruidas", "dedos dañados"]'),
('T25.739D', 'Corrosión de tercer grado de dedo(s) (uñas) de pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.739S', 'Corrosión de tercer grado de dedo(s) (uñas) de pie no especificados, secuela', 'Sin especificar', '["cicatriz", "uñas dañadas", "daño"]'),
('T25.791A', 'Corrosión de tercer grado de localizaciones múltiples de tobillo y pie derechos, contacto inicial', 'Sin especificar', '["corrosión grave", "daño profundo", "urgencia"]'),
('T25.791D', 'Corrosión de tercer grado de localizaciones múltiples de tobillo y pie derechos, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.791S', 'Corrosión de tercer grado de localizaciones múltiples de tobillo y pie derechos, secuela', 'Sin especificar', '["cicatriz", "queloide", "daño"]'),
('T25.792A', 'Corrosión de tercer grado de localizaciones múltiples de tobillo y pie izquierdos, contacto inicial', 'Sin especificar', '["corrosión grave", "daño profundo", "urgencia"]'),
('T25.792D', 'Corrosión de tercer grado de localizaciones múltiples de tobillo y pie izquierdos, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.792S', 'Corrosión de tercer grado de localizaciones múltiples de tobillo y pie izquierdos, secuela', 'Sin especificar', '["cicatriz", "queloide", "daño"]'),
('T25.799A', 'Corrosión de tercer grado de localizaciones múltiples de tobillo y pie no especificados, contacto inicial', 'Sin especificar', '["corrosión grave", "daño profundo", "urgencia"]'),
('T25.799D', 'Corrosión de tercer grado de localizaciones múltiples de tobillo y pie no especificados, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "reconstrucción"]'),
('T25.799S', 'Corrosión de tercer grado de localizaciones múltiples de tobillo y pie no especificados, secuela', 'Sin especificar', '["cicatriz", "queloide", "daño"]');
