INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Y84.0', 'Cateterismo cardiaco como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["cateterismo", "estudio del corazón", "catéter en el corazón", "problemas tras cateterismo", "dolor tras cateterismo", "reacción al cateterismo", "complicaciones cardíacas", "pinchazo en el pecho", "intervención al corazón", "cateterismo cardíaco", "malestar tras estudio corazón", "post cateterismo", "dolor en el pecho post procedimiento", "efectos secundarios cateterismo", "estudio invasivo cardiaco"]'),
('Y84.1', 'Diálisis renal como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["diálisis", "tratamiento de riñones", "máquina de diálisis", "malestar post diálisis", "complicaciones de diálisis", "hemodiálisis", "problemas con los riñones", "insuficiencia renal tratamiento", "efectos de la diálisis", "dolor después de diálisis", "reacción tras limpiar la sangre", "lavado de riñones", "fatiga post diálisis", "baja presión tras diálisis", "acceso vascular complicaciones"]'),
('Y84.2', 'Procedimiento radiológico y de radioterapia como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["radioterapia", "rayos X", "efectos de radiación", "quemaduras por radiación", "malestar tras radiografía", "complicaciones tras radioterapia", "efectos secundarios rayos", "reacción cutánea radioterapia", "dolor tras radioterapia", "tratamiento de radiación", "secuelas de rayos", "radiología", "daño por radiación", "sensibilidad post radiación", "quemazón tras tratamiento"]'),
('Y84.3', 'Terapia de choque como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["terapia de choque", "electroshock", "terapia electroconvulsiva", "TEC", "efectos del electroshock", "reacción tras choque eléctrico", "complicaciones tras terapia", "confusión tras shock", "malestar por electroconvulsión", "efectos psiquiátricos", "dolor tras sesión de choque", "memoria después de shock", "tratamiento eléctrico", "efectos de la terapia", "reacción post TEC"]'),
('Y84.4', 'Aspiración de líquido como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["aspiración de líquido", "punción", "drenaje", "sacar líquido", "complicación tras drenaje", "dolor tras punción", "reacción tras extraer líquido", "aspiración", "pinchazo para sacar líquido", "post drenaje", "malestar tras extracción", "inflamación post aspiración", "infección tras punción", "punción abdominal", "extracción de fluidos"]'),
('Y84.5', 'Inserción de sonda gástrica o duodenal como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["sonda gástrica", "sonda nasogástrica", "manguera al estómago", "sonda duodenal", "problemas con la sonda", "dolor de garganta por sonda", "reacción tras poner sonda", "sonda para comer", "molestias en la nariz por sonda", "complicaciones con la sonda", "tubo al estómago", "malestar gástrico por sonda", "irritación por sonda", "post inserción de sonda", "sonda de alimentación"]'),
('Y84.6', 'Cateterismo urinario como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["cateterismo urinario", "sonda urinaria", "sonda vesical", "sonda en la vejiga", "dolor al orinar tras sonda", "infección por sonda", "molestias en la uretra", "reacción post sonda urinaria", "complicaciones urinarias", "malestar con la sonda", "dolor tras catéter urinario", "espasmos vesicales", "ardor al orinar post sonda", "tubo en la vejiga", "problemas para orinar tras sonda"]'),
('Y84.7', 'Toma de muestra sanguínea como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["toma de muestra", "extracción de sangre", "pinchazo para análisis", "hematoma tras sacar sangre", "dolor tras extracción", "reacción en el brazo", "moratón por análisis", "complicaciones tras muestra sanguínea", "pinchazo doloroso", "se me hizo bola en el brazo", "sangrado tras extracción", "mareo post extracción", "inflamación tras pinchar", "punción sanguínea", "analítica de sangre"]'),
('Y84.8', 'Otros procedimientos médicos como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["complicación médica", "reacción tras procedimiento", "malestar tras cirugía", "efectos secundarios médicos", "problemas post hospitalarios", "malestar después del médico", "reacción adversa no especificada", "complicaciones tras tratamiento", "post operatorio complicaciones", "dolor tras intervención", "efectos tras procedimiento", "no me siento bien tras el médico", "reacción post tratamiento", "secuelas de procedimiento", "infección post procedimiento"]'),
('Y84.9', 'Procedimiento médico no especificado como causa de reacción anormal del paciente o de complicación posterior, sin mención de evento adverso en el momento del procedimiento', 'Sin especificar', '["procedimiento médico", "complicación desconocida", "reacción tras tratamiento médico", "malestar post médico", "problemas tras ir al hospital", "complicaciones post intervención", "efectos de cirugía no especificada", "reacción extraña tras médico", "problema tras procedimiento", "malestar tras estudio", "dolor tras tratamiento", "efectos secundarios desconocidos", "post intervención", "reacción tardía", "complicaciones tras revisión"]');
