INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J98.01', 'Broncoespasmo agudo', 'Sin especificar', '["pecho cerrado", "ataque de asma", "ahogo", "sibilancias", "pecho apretado", "falta de aire", "bronquios cerrados", "asfixia", "dificultad para respirar", "pitos en el pecho", "silbido al respirar", "opresión torácica", "crisis asmática", "ahoguío", "broncoespasmo", "aire trabado"]'),
('J98.09', 'Otras enfermedades de los bronquios, no clasificables bajo otro concepto', 'Sin especificar', '["problemas de bronquios", "bronquitis crónica", "tos persistente", "inflamación bronquial", "pecho cargado", "catarro bronquial", "flemas", "bronquiectasias", "obstrucción bronquial", "mal de bronquios", "dolor bronquial", "bronquios irritados", "tos con moco", "bronquitis mal curada"]'),
('J98.11', 'Atelectasia', 'Sin especificar', '["pulmón colapsado", "pulmón contraído", "colapso pulmonar", "pulmón que no expande", "incapacidad de inflar el pulmón", "atelectasia pulmonar", "alvéolos cerrados", "insuficiencia respiratoria focal", "se me pegó el pulmón", "pulmón colapsado parcial", "dificultad para expandir pulmón"]'),
('J98.19', 'Otros tipos de colapso pulmonar', 'Sin especificar', '["colapso de pulmón", "pulmón arrugado", "neumotórax parcial", "aire en el pulmón", "fallo pulmonar", "pulmón comprimido", "problema en el pulmón", "pleura colapsada", "desinflado del pulmón", "dificultad respiratoria aguda", "pulmón cerrado"]'),
('J98.2', 'Enfisema intersticial', 'Sin especificar', '["aire en el tejido pulmonar", "burbujas de aire en pulmón", "enfisema", "daño intersticial", "inflamación del tejido pulmonar", "aire atrapado en el pulmón", "fibrosis inicial", "dolor profundo en el pecho", "pulmón con aire irregular", "enfisema pulmonar"]'),
('J98.3', 'Enfisema compensador', 'Sin especificar', '["pulmón hiperinsuflado", "sobrecarga pulmonar", "enfisema parcial", "ajuste pulmonar", "hiperinflación compensatoria", "pulmón trabajando de más", "daño pulmonar", "adaptación pulmonar", "sobredistensión alveolar", "enfisema no generalizado"]'),
('J98.4', 'Otros trastornos del pulmón', 'Sin especificar', '["enfermedad pulmonar", "problema pulmonar", "dolor de pulmón", "infección pulmonar", "mancha en el pulmón", "pulmones débiles", "mal del pulmón", "tos crónica", "irritación pulmonar", "daño en el tejido pulmonar", "pulmón enfermo"]'),
('J98.51', 'Mediastinitis', 'Sin especificar', '["inflamación del mediastino", "infección en el centro del pecho", "dolor retroesternal", "mediastino inflamado", "infección del tórax", "dolor detrás del esternón", "inflamación mediastínica", "infección profunda del pecho", "absceso mediastínico", "dolor agudo en el pecho"]'),
('J98.59', 'Otras enfermedades del mediastino, no clasificables bajo otro concepto', 'Sin especificar', '["masa en el tórax", "tumor mediastínico", "quiste en el pecho", "problemas en el centro del pecho", "crecimiento en el mediastino", "mediastino", "dolor mediastino", "afección del centro del pecho", "nódulo mediastínico"]'),
('J98.6', 'Trastornos del diafragma', 'Sin especificar', '["dolor de diafragma", "parálisis diafragmática", "diafragma atascado", "dolor en la boca del estómago", "espasmo diafragmático", "problemas para respirar por el diafragma", "hipo crónico", "debilidad del diafragma", "diafragma bloqueado", "dolor bajo las costillas", "hernia diafragmática"]'),
('J98.8', 'Otros trastornos respiratorios especificados', 'Sin especificar', '["problemas de respiración", "insuficiencia respiratoria", "dificultad para respirar", "cansancio al respirar", "fatiga respiratoria", "aire pesado", "ahogos frecuentes", "mal aliento (respiratorio)", "obstrucción de vías aéreas", "trastorno al respirar"]'),
('J98.9', 'Trastorno respiratorio, no especificado', 'Sin especificar', '["no puedo respirar", "problema de los pulmones", "falta de aire", "me ahogo", "ahoguío", "mal de los pulmones", "afección respiratoria", "enfermedad del pecho", "no entra bien el aire", "sensación de ahogo", "problema en las vías respiratorias"]');
