INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P09.1', 'Hallazgos anormales en el cribado neonatal de metabolopatías congénitas', 'Sin especificar', '["tamiz metabólico alterado", "prueba del talón mal", "error innato del metabolismo", "problemas de metabolismo bebé", "fallo en tamizaje", "problema en la sangre del recién nacido", "metabolopatía congénita", "falsos positivos tamiz", "bebé con metabolismo raro", "enfermedad metabólica hereditaria", "chequeo metabólico anormal", "resultados de tamiz fuera de rango", "pesquisa neonatal alterada"]'),
('P09.2', 'Hallazgos anormales en el cribado neonatal de enfermedad endocrina congénita', 'Sin especificar', '["problemas de tiroides bebé", "tamiz endocrino alterado", "hipotiroidismo congénito tamiz", "falla en hormonas recién nacido", "desorden endocrino bebé", "tamizaje tiroideo", "problema en las glándulas bebé", "anomalía endocrina en el talón", "cribado endocrino fallido", "bocio congénito", "problemas de crecimiento bebé tamiz", "análisis de hormonas bebé", "tamizaje positivo endocrino"]'),
('P09.3', 'Hallazgos anormales en el cribado neonatal de enfermedades hematológicas congénitas', 'Sin especificar', '["problemas de sangre bebé", "anemia falciforme tamiz", "talasemia recién nacido", "tamiz hematológico alterado", "glóbulos rojos anormales bebé", "enfermedad de la sangre congénita", "prueba del talón anemia", "trastornos hemáticos neonatales", "hemoglobina anormal", "cribado de sangre del recién nacido", "anomalía en la serie roja", "resultado raro en tamiz hematológico"]'),
('P09.4', 'Hallazgos anormales en el cribado neonatal de fibrosis quística', 'Sin especificar', '["fibrosis quística bebé", "tamiz fibrosis quística positivo", "prueba del talón fibrosis", "problemas pulmonares recién nacido", "sudor salado bebé", "problemas de páncreas bebé", "mucoviscidosis neonatal", "cribado fibrosis quística", "falla en prueba de fibrosis", "sospecha de fibrosis quística", "problemas respiratorios congénitos", "anomalía en test de tripsina"]'),
('P09.5', 'Hallazgos anormales en el cribado neonatal de cardiopatía congénita crítica', 'Sin especificar', '["problemas de corazón bebé", "cardiopatía congénita tamiz", "oximetría de pulso anormal", "soplos en el corazón recién nacido", "bebé azul tamizaje", "fallo cardíaco congénito", "cribado de corazón neonatal", "tamizaje de cardiopatía", "anomalía cardíaca al nacer", "problemas de circulación bebé", "tamiz cardíaco fallido", "cardiopatía crítica sospecha"]'),
('P09.6', 'Hallazgos anormales en el cribado neonatal de pérdida de audición neonatal', 'Sin especificar', '["bebé no escucha bien", "tamiz auditivo alterado", "prueba de audición bebé mal", "hipoacusia congénita", "sordera neonatal sospecha", "cribado auditivo fallido", "potenciales evocados auditivos bebé", "problemas de oído al nacer", "tamizaje auditivo fuera de rango", "bebé sordo tamiz", "fallo en audiometría neonatal", "revisión auditiva recién nacido"]'),
('P09.8', 'Otros hallazgos anormales en el cribado neonatal', 'Sin especificar', '["resultados raros tamiz", "tamizaje neonatal extraño", "anomalía en prueba del talón", "hallazgos raros recién nacido", "chequeo neonatal anormal", "otros problemas tamiz", "incertidumbre resultados bebé", "tamiz con datos no claros", "anormalidad en recién nacido tamizaje", "estudios neonatales raros", "reporte de laboratorio anormal", "seguimiento tras tamiz"]'),
('P09.9', 'Hallazgos anormales en el cribado neonatal, no especificados', 'Sin especificar', '["tamiz alterado sin especificar", "problema en tamizaje bebé", "resultado confuso prueba del talón", "estudio neonatal con problemas", "anomalía en la pesquisa", "tamizaje mal", "alerta en tamiz neonatal", "resultado pendiente de aclarar bebé", "posible enfermedad recién nacido", "anomalía no definida en tamiz", "cribado con dudas", "hallazgo inespecífico neonatal"]');
