INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B87.0', 'Miasis cutánea', 'Sin especificar', '["gusanos en la piel", "larvas en la piel", "bichos en la piel", "tupe", "berne", "ura", "colmoyote", "moyocuil", "chiclero", "mosca en la piel", "infección por larvas", "parásitos cutáneos", "picadura de mosca", "dermatobia hominis", "gusano barrenador", "agujeros en la piel", "bulto con gusano"]'),
('B87.1', 'Miasis en heridas', 'Sin especificar', '["gusanos en herida", "bichos en una cortada", "llaga con gusanos", "herida infectada por larvas", "gusanera", "miasis traumática", "podredumbre en herida", "larvas en úlceras", "infección purulenta", "necrosis con larvas", "cucarrones en la herida", "ataque de mosca en lesión", "herida sucia", "curación de herida con gusanos"]'),
('B87.2', 'Miasis ocular', 'Sin especificar', '["gusano en el ojo", "larvas en los ojos", "bicho en el ojo", "miasis del ojo", "infección ocular por larvas", "dolor de ojos", "visión borrosa por parásitos", "parásito ocular", "mosca en el ojo", "conjuntivitis por larvas", "picazón en el ojo", "inflamación ocular", "secreción en el ojo"]'),
('B87.3', 'Miasis nasofaríngea', 'Sin especificar', '["gusanos en la nariz", "larvas en la garganta", "bichos en la nariz", "miasis nasal", "obstrucción nasal por larvas", "dolor de nariz", "mal aliento por gusanos", "parásitos en senos paranasales", "cosquilleo en la nariz", "inflamación de nariz", "mosca en la nariz", "secreción nasal con larvas", "picazón en la garganta"]'),
('B87.4', 'Miasis aural', 'Sin especificar', '["gusanos en el oído", "larvas en el oído", "bicho en el oído", "miasis del oído", "dolor de oído", "zumbido en el oído", "secreción del oído", "infección de oído", "parásito en el canal auditivo", "mosca en el oído", "picazón en el conducto auditivo", "obstrucción de oído", "pérdida de audición por parásitos"]'),
('B87.81', 'Miasis genitourinaria', 'Sin especificar', '["gusanos en zona íntima", "larvas en genitales", "bichos en la entrepierna", "miasis urogenital", "infección genital", "dolor al orinar", "picazón en genitales", "parásitos en uretra", "infección urinaria por larvas", "inflamación genital", "secreción genital", "molestias en zona pélvica"]'),
('B87.82', 'Miasis intestinal', 'Sin especificar', '["gusanos en la panza", "larvas en el intestino", "parásitos intestinales", "bichos en el estómago", "lombrices", "diarrea con larvas", "dolor de guata", "malestar estomacal", "miasis digestiva", "náuseas por parásitos", "infección gástrica", "gusanos en heces", "dolor abdominal", "retortijones"]'),
('B87.89', 'Miasis de otras localizaciones', 'Sin especificar', '["bichos en el cuerpo", "larvas en lugares raros", "gusanos en otras partes", "parásitos subcutáneos", "infestación por larvas", "miasis ectópica", "larva migrans", "bultos con movimiento", "infección por picadura", "presencia de gusanos", "ataque de moscas"]'),
('B87.9', 'Miasis, no especificada', 'Sin especificar', '["tengo gusanos", "infección por larvas", "tengo bichos", "miasis", "infestación parasitaria", "moscas ponedoras", "enfermedad de gusanos", "ataque de larva", "parásitos en la carne", "me entró un bicho", "bichera", "cura de gusanera", "estoy lleno de larvas"]');
