INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D70.0', 'Agranulocitosis congénita', 'Sin especificar', '["defensas bajas de nacimiento", "falta de glóbulos blancos", "enfermedad de Kostmann", "bajos neutrófilos congénitos", "inmunodeficiencia hereditaria", "problema de sangre hereditario", "sin defensas", "médula ósea que no produce", "neutropenia severa congénita", "infecciones recurrentes bebé", "sangre débil", "anomalía sanguínea hereditaria", "baja respuesta inmune", "defecto congénito granulocitos"]'),
('D70.1', 'Agranulocitosis secundaria a quimioterapia antineoplásica', 'Sin especificar', '["bajas defensas por quimio", "neutropenia post-quimio", "efecto secundario quimioterapia", "quimio y defensas bajas", "leucocitos bajos por cáncer", "bajada de plaquetas y glóbulos", "fiebre post-quimio", "inmunosupresión por quimioterapia", "médula ósea afectada por quimio", "sin defensas tras tratamiento", "bajón de defensas", "efectos tóxicos quimio", "riesgo de infección quimioterapia", "quimio me dejó sin defensas"]'),
('D70.2', 'Agranulocitosis inducidas por fármacos', 'Sin especificar', '["defensas bajas por medicamentos", "neutropenia inducida por fármacos", "reacción a pastillas en la sangre", "medicinas que bajan defensas", "alergia a fármacos sangre", "toxicidad por medicamentos", "bajón de glóbulos blancos por fármacos", "efecto secundario antibióticos", "médula dañada por pastillas", "neutropenia farmacológica", "reacción adversa hematológica", "cambios en sangre por medicina", "fármacos que quitan las defensas"]'),
('D70.3', 'Neutropenia debida a infección', 'Sin especificar', '["defensas bajas por infección", "glóbulos blancos bajos por virus", "infección me bajó las defensas", "neutropenia infecciosa", "fiebre y neutrófilos bajos", "la infección se comió mis defensas", "sangre débil por gripe fuerte", "bajón inmune tras enfermedad", "bajos glóbulos por bacteria", "se me bajaron las defensas por enfermar", "neutropenia reactiva", "virus que baja los neutrófilos", "defensas agotadas por infección"]'),
('D70.4', 'Neutropenia cíclica', 'Sin especificar', '["defensas que suben y bajan", "neutropenia recurrente", "ciclos de defensas bajas", "bajada de defensas cada cierto tiempo", "neutrófilos inestables", "problema de defensas crónico", "sube y baja de glóbulos", "enfermedad cíclica de la sangre", "bajones frecuentes de defensas", "neutropenia periódica", "patrón de defensas bajas", "mis defensas se caen y vuelven", "trastorno hematológico periódico"]'),
('D70.8', 'Otras neutropenias', 'Sin especificar', '["neutropenia poco común", "otras causas de glóbulos bajos", "baja cantidad de neutrófilos", "problema extraño de glóbulos", "bajas defensas raras", "deficiencia de glóbulos blancos inespecífica", "neutropenia idiopática", "falta de defensas sin causa clara", "valores bajos de neutrófilos", "mis defensas están raras", "sangre con pocos glóbulos", "bajo recuento leucocitario"]'),
('D70.9', 'Neutropenia, no especificada', 'Sin especificar', '["bajas defensas", "glóbulos blancos bajos", "defensas bajas", "poca sangre", "neutrófilos bajos", "inmunodeficiencia leve", "se me bajaron los glóbulos", "tengo pocas defensas", "defensas por los suelos", "análisis de sangre con bajos glóbulos", "neutropenia genérica", "falta de glóbulos", "bajón de sangre", "me siento sin defensas", "recuento de neutrófilos bajo"]');
