INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L94.0', 'Esclerodermia localizada [morfea]', 'Sin especificar', '["morfea", "piel endurecida", "placas duras en la piel", "esclerodermia en parches", "piel acartonada", "lesión cutánea endurecida", "manchas brillantes en la piel", "piel como cera", "esclerosis cutánea focal", "piel tirante", "fibrosis cutánea", "mancha morfea", "atrofia dérmica", "endurecimiento de la piel", "parche endurecido"]'),
('L94.1', 'Esclerodermia lineal', 'Sin especificar', '["esclerodermia en banda", "línea de piel dura", "piel retraída en línea", "lesión lineal en extremidad", "esclerodermia en golpe de sable", "golpe de sable", "surco en la piel", "fibrosis lineal", "piel hundida", "atrofia lineal", "esclerodermia pediátrica", "cicatriz lineal profunda", "retracción cutánea", "línea blanca en la piel", "banda de piel tensa"]'),
('L94.2', 'Calcinosis de piel', 'Sin especificar', '["depósitos de calcio en piel", "bolitas de calcio", "piedras bajo la piel", "piel con nódulos duros", "calcio en los dedos", "nódulos calcificados", "piel granulosa", "depósitos cálcicos", "bultos duros bajo la piel", "calcinosis cutis", "piel que suelta piedritas", "calcificación cutánea", "bultos blanquecinos en piel", "dolor por calcio en piel", "nódulos subcutáneos"]'),
('L94.3', 'Esclerodactilia', 'Sin especificar', '["dedos duros", "dedos rígidos", "piel de dedos acartonada", "dedos en garra", "dedos afilados", "piel tirante en dedos", "engrosamiento dedos", "esclerodermia en manos", "dedos sin flexibilidad", "piel brillante en dedos", "atrofia de las yemas", "dedos engarrotados", "piel tensa en falanges", "dificultad para cerrar la mano", "piel pegada al hueso"]'),
('L94.4', 'Pápulas de Gottron', 'Sin especificar', '["pápulas en nudillos", "manchas en nudillos", "nódulos en articulaciones", "erupción en nudillos", "dermatomiositis pápulas", "lesiones rojas en dedos", "manchas violáceas nudillos", "engrosamiento en nudillos", "pápulas eritematosas", "nudos en los dedos", "lesiones tipo gottron", "parches en nudillos", "signo de gottron", "piel escamosa en nudillos", "manchas en dorso de dedos"]'),
('L94.5', 'Poiquilodermia vascular atrófica', 'Sin especificar', '["piel moteada", "piel con manchas rojas y blancas", "adelgazamiento de la piel", "piel fina como papel", "arañitas vasculares", "telangiectasias", "piel reticulada", "atrofia cutánea", "piel con cambios de color", "piel jaspeada", "piel frágil", "pigmentación irregular piel", "piel con venitas visibles", "daño solar crónico piel", "poiquilodermia"]'),
('L94.6', 'Ainhum', 'Sin especificar', '["dactilólisis espontánea", "constricción dedo del pie", "surco en dedo", "amputación espontánea", "anillo en el dedo del pie", "dedo apretado", "estrangulamiento de dedo", "surco profundo en pie", "deformidad en dedo", "pérdida de dedo pie", "banda constrictiva", "ainhum podálico", "anillo cutáneo", "dedo con surco", "constricción anular"]'),
('L94.8', 'Otros tipos de trastornos localizados especificados del tejido conjuntivo', 'Sin especificar', '["problemas tejido conectivo", "enfermedad colágeno", "inflamación tejido blando", "trastorno conectivo localizado", "fibrosis localizada", "nódulos tejido conectivo", "endurecimiento subcutáneo", "problema de dermis", "anomalía tejido conjuntivo", "lesión conectiva rara", "patología del colágeno", "induración cutánea", "lesión subcutánea especificada", "esclerosis dérmica", "fibroesclerosis"]'),
('L94.9', 'Trastorno localizado del tejido conjuntivo, no especificado', 'Sin especificar', '["problema de piel raro", "dolor en piel y tejido", "nódulo cutáneo sin nombre", "endurecimiento de piel desconocido", "trastorno tejido blando", "lesión cutánea no identificada", "inflamación bajo la piel", "fibrosis inespecífica", "daño en tejido conjuntivo", "piel rara", "patología de la dermis", "bulto en la piel", "trastorno del colágeno no especificado", "induración inespecífica", "afectación cutánea"]');
