INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A42.0', 'Actinomicosis pulmonar', 'Sin especificar', '["infección pulmonar bacteriana", "pulmones infectados", "actinomicosis en los pulmones", "bacteria en el pecho", "infección crónica de pulmón", "absceso pulmonar", "flema con pus", "tos persistente", "dolor al respirar", "infección por actinomyces", "pulmonía bacteriana rara", "mal del pulmón", "neumonía actinomicótica", "infección profunda de pecho"]'),
('A42.1', 'Actinomicosis abdominal', 'Sin especificar', '["infección en la panza", "dolor de barriga persistente", "actinomicosis intestinal", "guata infectada", "infección abdominal", "absceso en el abdomen", "dolor de guata", "bacteria en el estómago", "inflamación abdominal", "infección de las vísceras", "dolor de panza crónico", "infección postquirúrgica abdominal", "tumor abdominal infeccioso", "infección de la tripa"]'),
('A42.2', 'Actinomicosis cervicofacial', 'Sin especificar', '["infección de mandíbula", "quijada hinchada", "cara hinchada por infección", "absceso en el cuello", "infección de muelas", "actinomicosis en la cara", "infección bucal crónica", "bulto en el cuello", "mandíbula trabada", "infección de cuello y cara", "fístula en la mejilla", "infección maxilofacial", "dolor de cara", "hinchazón de cara"]'),
('A42.7', 'Sepsis actinomicótica', 'Sin especificar', '["infección generalizada", "sepsis por bacterias", "sangre infectada", "infección en todo el cuerpo", "septicemia", "choque séptico bacteriano", "infección sistémica", "bacteria en la sangre", "actinomicosis diseminada", "peligro de infección", "infección fatal", "fiebre alta por infección", "bacteriemia grave", "infección de la sangre"]'),
('A42.81', 'Meningitis actinomicótica', 'Sin especificar', '["infección en el cerebro", "meningitis bacteriana", "inflamación de las meninges", "infección de la cabeza", "dolor de cabeza extremo", "fiebre y rigidez de nuca", "actinomicosis cerebral", "infección en la nuca", "bacteria en el líquido cefalorraquídeo", "meningitis grave", "dolor de coco", "inflamación del cerebro", "infección del sistema nervioso central", "rigidez en el cuello"]'),
('A42.82', 'Encefalitis actinomicótica', 'Sin especificar', '["inflamación del cerebro", "encefalitis bacteriana", "infección cerebral", "actinomicosis del encéfalo", "daño cerebral por bacteria", "infección del sistema nervioso", "convulsiones por infección", "confusión mental por infección", "dolor de cabeza intenso", "infección del seso", "encefalitis aguda", "meningoencefalitis", "absceso cerebral", "infección intracraneal"]'),
('A42.89', 'Otras formas de actinomicosis', 'Sin especificar', '["actinomicosis atípica", "infección rara por bacterias", "actinomicosis cutánea", "actinomicosis pélvica", "infección bacteriana oculta", "actinomicosis extraña", "bacteriosis crónica", "infección de tejidos blandos", "actinomicosis diseminada", "actinomicosis localizada", "infección poco común", "malestar por actinomyces", "actinomicosis extra", "infección no clasificada"]'),
('A42.9', 'Actinomicosis, no especificada', 'Sin especificar', '["infección por actinomyces", "actinomicosis general", "enfermedad bacteriana", "infección de bacterias", "infección crónica", "actinomicosis sin especificar", "bacteria rara", "infección desconocida", "dolencia por actinomiceto", "actinomicosis diagnosticada", "infección bacteriana profunda", "bacteriosis", "enfermedad infecciosa rara", "actinomicosis de origen incierto"]');
