INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S30.0XXA', 'Contusión de parte inferior de espalda y pelvis, contacto inicial', 'Sin especificar', '["golpe en la rabadilla", "moretón en la cintura", "chichón en la cadera", "traumatismo sacro", "golpe en el coxis", "espalda baja lastimada", "dolor de pelvis por caída", "hematoma lumbar", "golpe en los riñones", "contusión lumbosacra", "golpe en las nalgas", "dolor de cintura"]'),
('S30.0XXD', 'Contusión de parte inferior de espalda y pelvis, contacto sucesivo', 'Sin especificar', '["control por golpe en la espalda baja", "seguimiento de contusión sacra", "revisión por traumatismo en cadera", "dolor persistente en coxis", "revisión de hematoma lumbar", "segunda consulta por golpe en pelvis", "evolución de moretón lumbar", "dolor de cintura crónico", "seguimiento de golpe en riñones"]'),
('S30.0XXS', 'Contusión de parte inferior de espalda y pelvis, secuela', 'Sin especificar', '["secuela de golpe en la cadera", "dolor crónico tras caída en coxis", "molestia vieja en la rabadilla", "cicatriz interna por golpe lumbar", "complicación post-contusión sacra", "dolor persistente en cintura post-golpe", "secuelas de traumatismo en pelvis"]'),
('S30.1XXA', 'Contusión de pared abdominal, contacto inicial', 'Sin especificar', '["golpe en la panza", "moretón en el estómago", "trancazo en la barriga", "dolor en la guata", "golpe en el abdomen", "traumatismo abdominal", "hematoma en la panza", "dolor de tripa por golpe", "trompada en el vientre"]'),
('S30.1XXD', 'Contusión de pared abdominal, contacto sucesivo', 'Sin especificar', '["seguimiento golpe en el abdomen", "revisión moretón en la panza", "control de traumatismo abdominal", "dolor abdominal persistente tras golpe", "evaluación de hematoma en vientre"]'),
('S30.1XXS', 'Contusión de pared abdominal, secuela', 'Sin especificar', '["secuela de golpe en la panza", "dolor persistente en la barriga", "molestia post-traumatismo abdominal", "cicatriz interna tras golpe en el vientre"]'),
('S30.201A', 'Contusión de órgano genital externo masculino, no especificado, contacto inicial', 'Sin especificar', '["golpe en los bajos", "golpe en los genitales", "traumatismo en las partes íntimas", "golpe en la entrepierna", "lastimadura en los bajos", "dolor en los aparatos", "golpe en el paquete"]'),
('S30.201D', 'Contusión de órgano genital externo masculino, no especificado, contacto sucesivo', 'Sin especificar', '["revisión golpe genitales", "control dolor en los bajos", "seguimiento traumatismo entrepierna", "evolución de golpe en las partes íntimas"]'),
('S30.201S', 'Contusión de órgano genital externo masculino, no especificado, secuela', 'Sin especificar', '["secuela de golpe en los bajos", "dolor persistente en genitales", "complicación post-golpe en partes íntimas"]'),
('S30.202A', 'Contusión de órgano genital externo femenino, no especificado, contacto inicial', 'Sin especificar', '["golpe en la vulva", "golpe en la zona íntima", "traumatismo genital femenino", "dolor en la entrepierna", "lesión en partes íntimas"]'),
('S30.202D', 'Contusión de órgano genital externo femenino, no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento golpe zona íntima", "revisión traumatismo vulvar", "control dolor genital femenino"]'),
('S30.202S', 'Contusión de órgano genital externo femenino, no especificado, secuela', 'Sin especificar', '["secuelas golpe zona genital", "molestia persistente en vulva", "dolor crónico post-traumatismo íntimo"]'),
('S30.21XA', 'Contusión de pene, contacto inicial', 'Sin especificar', '["golpe en el miembro", "traumatismo en el pene", "golpe en la vergüenza", "lastimada la parte", "golpe en el pito"]'),
('S30.21XD', 'Contusión de pene, contacto sucesivo', 'Sin especificar', '["control golpe en el pene", "seguimiento traumatismo miembro", "revisión lesión en el pito"]'),
('S30.21XS', 'Contusión de pene, secuela', 'Sin especificar', '["secuela golpe en el pene", "dolor crónico en el miembro", "molestia persistente tras golpe genital"]'),
('S30.22XA', 'Contusión de escroto y testículos, contacto inicial', 'Sin especificar', '["golpe en los huevos", "patada en los testículos", "golpe en las bolas", "traumatismo escrotal", "dolor de testículos por golpe", "golpe en los tanates"]'),
('S30.22XD', 'Contusión de escroto y testículos, contacto sucesivo', 'Sin especificar', '["revisión golpe testículos", "control dolor en las bolas", "seguimiento traumatismo escrotal", "evolución de golpe en los huevos"]'),
('S30.22XS', 'Contusión de escroto y testículos, secuela', 'Sin especificar', '["secuela patada en los huevos", "dolor crónico testicular", "molestia persistente en escroto"]'),
('S30.23XA', 'Contusión de vagina y vulva, contacto inicial', 'Sin especificar', '["golpe en la vagina", "traumatismo vulvar", "lesión en la zona externa", "golpe fuerte entre piernas"]'),
('S30.23XD', 'Contusión de vagina y vulva, contacto sucesivo', 'Sin especificar', '["seguimiento contusión vulvar", "revisión golpe vaginal", "control dolor zona íntima"]'),
('S30.23XS', 'Contusión de vagina y vulva, secuela', 'Sin especificar', '["secuela contusión genital", "dolor persistente vulvar", "molestia post-traumatismo vaginal"]'),
('S30.3XXA', 'Contusión de ano, contacto inicial', 'Sin especificar', '["golpe en el esfínter", "traumatismo anal", "dolor de culo por golpe", "golpe en el trasero", "lesión rectal externa"]'),
('S30.3XXD', 'Contusión de ano, contacto sucesivo', 'Sin especificar', '["control golpe ano", "revisión traumatismo rectal", "seguimiento dolor anal"]'),
('S30.3XXS', 'Contusión de ano, secuela', 'Sin especificar', '["secuela golpe anal", "dolor crónico en esfínter", "molestia rectal post-golpe"]'),
('S30.810A', 'Abrasión de parte inferior de espalda y pelvis, contacto inicial', 'Sin especificar', '["raspón en la espalda baja", "raspadura en la cadera", "piel quemada por caída en coxis", "raspón en las nalgas", "pelada la piel en la cintura"]'),
('S30.810D', 'Abrasión de parte inferior de espalda y pelvis, contacto sucesivo', 'Sin especificar', '["revisión raspón espalda", "control curación raspadura cadera", "seguimiento herida superficial lumbar"]'),
('S30.810S', 'Abrasión de parte inferior de espalda y pelvis, secuela', 'Sin especificar', '["cicatriz por raspón espalda", "secuela de raspadura en cadera", "mancha por abrasión lumbar"]'),
('S30.811A', 'Abrasión de pared abdominal, contacto inicial', 'Sin especificar', '["raspón en la panza", "raspadura en el abdomen", "piel pelada en la barriga", "quemadura por fricción en estómago"]'),
('S30.811D', 'Abrasión de pared abdominal, contacto sucesivo', 'Sin especificar', '["seguimiento raspón panza", "control curación herida abdominal", "revisión raspadura vientre"]'),
('S30.811S', 'Abrasión de pared abdominal, secuela', 'Sin especificar', '["cicatriz por raspón panza", "secuela herida superficial abdomen", "mancha post-abrasión abdominal"]'),
('S30.812A', 'Abrasión del pene, contacto inicial', 'Sin especificar', '["raspón en el pene", "piel irritada en el miembro", "raspadura parte íntima", "quemadura por fricción genital"]'),
('S30.812D', 'Abrasión del pene, contacto sucesivo', 'Sin especificar', '["control raspón pene", "seguimiento herida superficial genital", "revisión raspadura miembro"]'),
('S30.812S', 'Abrasión del pene, secuela', 'Sin especificar', '["cicatriz raspón pene", "secuela abrasión genital", "molestia post-raspadura"]'),
('S30.813A', 'Abrasión de escroto y testículos, contacto inicial', 'Sin especificar', '["raspón en los huevos", "raspadura escrotal", "piel irritada en los testículos", "quemadura en las bolas"]'),
('S30.813D', 'Abrasión de escroto y testículos, contacto sucesivo', 'Sin especificar', '["revisión raspón escroto", "control raspadura testículos", "seguimiento quemadura genital"]'),
('S30.813S', 'Abrasión de escroto y testículos, secuela', 'Sin especificar', '["secuela abrasión escrotal", "cicatriz raspón testículos", "molestia post-raspadura"]'),
('S30.814A', 'Abrasión de vagina y vulva, contacto inicial', 'Sin especificar', '["raspón zona íntima femenina", "raspadura vulvar", "quemadura por fricción en vagina", "piel irritada vulva"]'),
('S30.814D', 'Abrasión de vagina y vulva, contacto sucesivo', 'Sin especificar', '["seguimiento raspón vulvar", "control curación herida genital", "revisión raspadura femenina"]'),
('S30.814S', 'Abrasión de vagina y vulva, secuela', 'Sin especificar', '["cicatriz raspón vulvar", "secuela abrasión genital femenina", "molestia persistente post-abrasión"]'),
('S30.815A', 'Abrasión de órganos genitales externos masculinos, no especificados, contacto inicial', 'Sin especificar', '["raspón en los bajos", "raspadura en el área genital", "piel irritada en la entrepierna", "quemadura en los genitales"]'),
('S30.815D', 'Abrasión de órganos genitales externos masculinos, no especificados, contacto sucesivo', 'Sin especificar', '["control raspón zona genital", "revisión raspadura bajos", "seguimiento herida superficial genital"]'),
('S30.815S', 'Abrasión de órganos genitales externos masculinos, no especificados, secuela', 'Sin especificar', '["cicatriz en genitales", "secuela abrasión zona baja", "molestia post-raspadura"]'),
('S30.816A', 'Abrasión de órganos genitales externos femeninos, no especificados, contacto inicial', 'Sin especificar', '["raspón en la vulva", "raspadura zona genital femenina", "piel irritada parte íntima", "quemadura en zona vulvar"]'),
('S30.816D', 'Abrasión de órganos genitales externos femeninos, no especificados, contacto sucesivo', 'Sin especificar', '["revisión raspón zona íntima", "control raspadura vulva", "seguimiento herida femenina"]'),
('S30.816S', 'Abrasión de órganos genitales externos femeninos, no especificados, secuela', 'Sin especificar', '["cicatriz zona genital", "secuela raspadura vulvar", "molestia post-abrasión"]'),
('S30.817A', 'Abrasión de ano, contacto inicial', 'Sin especificar', '["raspón en el ano", "raspadura anal", "piel irritada en el recto", "quemadura zona anal"]'),
('S30.817D', 'Abrasión de ano, contacto sucesivo', 'Sin especificar', '["seguimiento raspón anal", "control herida rectal", "revisión raspadura zona anal"]'),
('S30.817S', 'Abrasión de ano, secuela', 'Sin especificar', '["cicatriz zona anal", "secuela raspadura rectal", "molestia post-abrasión anal"]'),
('S30.820A', 'Ampolla (no térmica) de parte inferior de espalda y pelvis, contacto inicial', 'Sin especificar', '["burbuja de agua en la espalda", "ampolla en la cadera", "burbuja por roce en coxis", "flictena en la espalda baja", "vejiga en la cintura"]'),
('S30.820D', 'Ampolla (no térmica) de parte inferior de espalda y pelvis, contacto sucesivo', 'Sin especificar', '["control ampolla espalda", "seguimiento burbuja cadera", "revisión vejiga lumbosacra"]'),
('S30.820S', 'Ampolla (no térmica) de parte inferior de espalda y pelvis, secuela', 'Sin especificar', '["secuela ampolla espalda", "cicatriz por ampolla", "mancha post-vejiga"]'),
('S30.821A', 'Ampolla (no térmica) de pared abdominal, contacto inicial', 'Sin especificar', '["ampolla en la panza", "burbuja en el abdomen", "flictena en la barriga", "vejiga en el vientre"]'),
('S30.821D', 'Ampolla (no térmica) de pared abdominal, contacto sucesivo', 'Sin especificar', '["revisión ampolla abdomen", "control burbuja panza", "seguimiento vejiga vientre"]'),
('S30.821S', 'Ampolla (no térmica) de pared abdominal, secuela', 'Sin especificar', '["cicatriz ampolla abdomen", "secuela vejiga panza", "mancha post-ampolla"]'),
('S30.822A', 'Ampolla (no térmica) de pene, contacto inicial', 'Sin especificar', '["ampolla en el pene", "burbuja en el miembro", "vejiga genital", "flictena en el pene"]'),
('S30.822D', 'Ampolla (no térmica) de pene, contacto sucesivo', 'Sin especificar', '["control ampolla pene", "revisión burbuja genital", "seguimiento vejiga miembro"]'),
('S30.822S', 'Ampolla (no térmica) de pene, secuela', 'Sin especificar', '["cicatriz ampolla pene", "secuela vejiga genital", "mancha post-ampolla"]'),
('S30.823A', 'Ampolla (no térmica) de escroto y testículos, contacto inicial', 'Sin especificar', '["ampolla en los huevos", "burbuja en los testículos", "vejiga escrotal", "flictena en las bolas"]'),
('S30.823D', 'Ampolla (no térmica) de escroto y testículos, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla testículos", "revisión burbuja escrotal", "control vejiga genital"]'),
('S30.823S', 'Ampolla (no térmica) de escroto y testículos, secuela', 'Sin especificar', '["cicatriz ampolla escroto", "secuela vejiga testículos", "mancha post-burbuja"]'),
('S30.824A', 'Ampolla (no térmica) de vagina y vulva, contacto inicial', 'Sin especificar', '["ampolla zona íntima femenina", "burbuja en vulva", "vejiga vaginal", "flictena zona femenina"]'),
('S30.824D', 'Ampolla (no térmica) de vagina y vulva, contacto sucesivo', 'Sin especificar', '["control ampolla vulvar", "revisión burbuja vaginal", "seguimiento vejiga zona íntima"]'),
('S30.824S', 'Ampolla (no térmica) de vagina y vulva, secuela', 'Sin especificar', '["cicatriz ampolla zona íntima", "secuela vejiga vulvar", "mancha post-ampolla"]'),
('S30.825A', 'Ampolla (no térmica) de órganos genitales externos masculinos, no especificados, contacto inicial', 'Sin especificar', '["ampolla en los bajos", "burbuja zona genital masculina", "vejiga en entrepierna"]'),
('S30.825D', 'Ampolla (no térmica) de órganos genitales externos masculinos, no especificados, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla bajos", "control burbuja genital", "revisión vejiga masculina"]'),
('S30.825S', 'Ampolla (no térmica) de órganos genitales externos masculinos, no especificados, secuela', 'Sin especificar', '["cicatriz ampolla bajos", "secuela vejiga genital", "mancha post-ampolla"]'),
('S30.826A', 'Ampolla (no térmica) de órganos genitales externos femeninos, no especificados, contacto inicial', 'Sin especificar', '["ampolla zona íntima femenina", "burbuja parte baja mujer", "vejiga genital externa"]'),
('S30.826D', 'Ampolla (no térmica) de órganos genitales externos femeninos, no especificados, contacto sucesivo', 'Sin especificar', '["control ampolla genital femenina", "revisión burbuja zona íntima", "seguimiento vejiga mujer"]'),
('S30.826S', 'Ampolla (no térmica) de órganos genitales externos femeninos, no especificados, secuela', 'Sin especificar', '["cicatriz ampolla genital", "secuela vejiga femenina", "mancha post-ampolla"]'),
('S30.827A', 'Ampolla (no térmica) de ano, contacto inicial', 'Sin especificar', '["ampolla anal", "burbuja en el esfínter", "vejiga zona rectal", "flictena anal"]'),
('S30.827D', 'Ampolla (no térmica) de ano, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla anal", "revisión burbuja recto", "control vejiga anal"]'),
('S30.827S', 'Ampolla (no térmica) de ano, secuela', 'Sin especificar', '["cicatriz ampolla anal", "secuela vejiga rectal", "mancha post-ampolla"]'),
('S30.840A', 'Constricción externa de parte inferior de espalda y pelvis, contacto inicial', 'Sin especificar', '["estrangulamiento en la espalda", "presión fuerte en la cintura", "cinturón muy apretado en cadera", "compresión externa lumbar"]'),
('S30.840D', 'Constricción externa de parte inferior de espalda y pelvis, contacto sucesivo', 'Sin especificar', '["revisión presión espalda", "control compresión lumbar", "seguimiento marca por presión"]'),
('S30.840S', 'Constricción externa de parte inferior de espalda y pelvis, secuela', 'Sin especificar', '["secuela presión lumbar", "cicatriz por estrangulamiento", "daño post-compresión"]'),
('S30.841A', 'Constricción externa de pared abdominal, contacto inicial', 'Sin especificar', '["faja muy apretada", "presión en la panza", "compresión abdominal", "cinturón apretando el vientre"]'),
('S30.841D', 'Constricción externa de pared abdominal, contacto sucesivo', 'Sin especificar', '["seguimiento presión abdomen", "control marca por faja", "revisión compresión vientre"]'),
('S30.841S', 'Constricción externa de pared abdominal, secuela', 'Sin especificar', '["secuela presión abdominal", "daño por faja, cicatriz en piel"]'),
('S30.842A', 'Constricción externa de pene, contacto inicial', 'Sin especificar', '["anillo en el pene", "presión en el miembro", "compresión peneana", "estrangulamiento en el pene"]'),
('S30.842D', 'Constricción externa de pene, contacto sucesivo', 'Sin especificar', '["revisión constricción pene", "control presión miembro", "seguimiento daño por anillo"]'),
('S30.842S', 'Constricción externa de pene, secuela', 'Sin especificar', '["secuela daño peneano", "cicatriz por constricción", "daño crónico en pene"]'),
('S30.843A', 'Constricción externa de escroto y testículos, contacto inicial', 'Sin especificar', '["presión en los huevos", "estrangulamiento testicular", "compresión en las bolas", "anillo en el escroto"]'),
('S30.843D', 'Constricción externa de escroto y testículos, contacto sucesivo', 'Sin especificar', '["control presión escrotal", "seguimiento daño testicular", "revisión compresión genital"]'),
('S30.843S', 'Constricción externa de escroto y testículos, secuela', 'Sin especificar', '["secuela estrangulamiento testicular", "daño permanente en escroto", "cicatriz post-presión"]'),
('S30.844A', 'Constricción externa de vagina y vulva, contacto inicial', 'Sin especificar', '["presión en zona íntima", "estrangulamiento vulvar", "compresión vaginal"]'),
('S30.844D', 'Constricción externa de vagina y vulva, contacto sucesivo', 'Sin especificar', '["seguimiento compresión vulvar", "revisión presión genital", "control daño íntimo"]'),
('S30.844S', 'Constricción externa de vagina y vulva, secuela', 'Sin especificar', '["secuela constricción íntima", "daño post-compresión vulvar"]'),
('S30.845A', 'Constricción externa de órganos genitales externos masculinos no especificados, contacto inicial', 'Sin especificar', '["presión genital masculina", "estrangulamiento bajos", "compresión en la entrepierna"]'),
('S30.845D', 'Constricción externa de órganos genitales externos masculinos no especificados, contacto sucesivo', 'Sin especificar', '["control presión genitales", "seguimiento daño bajos", "revisión compresión externa"]'),
('S30.845S', 'Constricción externa de órganos genitales externos masculinos no especificados, secuela', 'Sin especificar', '["secuela presión genital", "daño crónico bajos"]'),
('S30.846A', 'Constricción externa de órganos genitales externos femeninos no especificados, contacto inicial', 'Sin especificar', '["presión zona genital femenina", "estrangulamiento externo", "compresión en la parte íntima"]'),
('S30.846D', 'Constricción externa de órganos genitales externos femeninos no especificados, contacto sucesivo', 'Sin especificar', '["revisión presión genital femenina", "control daño externo", "seguimiento compresión"]'),
('S30.846S', 'Constricción externa de órganos genitales externos femeninos no especificados, secuela', 'Sin especificar', '["secuela constricción externa", "daño post-compresión"]'),
('S30.850A', 'Cuerpo extraño superficial de parte inferior de espalda y pelvis, contacto inicial', 'Sin especificar', '["astilla en la espalda", "vidrio en la piel baja", "objeto clavado en cadera", "punzón en la nalgas"]'),
('S30.850D', 'Cuerpo extraño superficial de parte inferior de espalda y pelvis, contacto sucesivo', 'Sin especificar', '["revisión cuerpo extraño espalda", "control herida astilla", "seguimiento objeto clavado"]'),
('S30.850S', 'Cuerpo extraño superficial de parte inferior de espalda y pelvis, secuela', 'Sin especificar', '["secuela objeto en espalda", "cicatriz por astilla", "infección post-objeto"]'),
('S30.851A', 'Cuerpo extraño superficial de pared abdominal, contacto inicial', 'Sin especificar', '["astilla en la panza", "vidrio en la barriga", "objeto clavado en abdomen", "pincho en el vientre"]'),
('S30.851D', 'Cuerpo extraño superficial de pared abdominal, contacto sucesivo', 'Sin especificar', '["seguimiento astilla abdomen", "revisión objeto panza", "control herida superficial"]'),
('S30.851S', 'Cuerpo extraño superficial de pared abdominal, secuela', 'Sin especificar', '["secuela objeto abdomen", "cicatriz por astilla", "infección en panza"]'),
('S30.852A', 'Cuerpo extraño superficial de pene, contacto inicial', 'Sin especificar', '["astilla en el pene", "vidrio en el miembro", "objeto clavado en el pito"]'),
('S30.852D', 'Cuerpo extraño superficial de pene, contacto sucesivo', 'Sin especificar', '["revisión cuerpo extraño pene", "control objeto miembro", "seguimiento herida genital"]'),
('S30.852S', 'Cuerpo extraño superficial de pene, secuela', 'Sin especificar', '["secuela objeto pene", "cicatriz post-astilla", "infección genital"]'),
('S30.853A', 'Cuerpo extraño superficial de escroto y testículos, contacto inicial', 'Sin especificar', '["astilla en los huevos", "vidrio en los testículos", "objeto clavado escroto", "pincho en bolas"]'),
('S30.853D', 'Cuerpo extraño superficial de escroto y testículos, contacto sucesivo', 'Sin especificar', '["control objeto escroto", "seguimiento astilla testículos", "revisión herida genital"]'),
('S30.853S', 'Cuerpo extraño superficial de escroto y testículos, secuela', 'Sin especificar', '["secuela objeto escroto", "cicatriz post-pincho", "infección testículos"]'),
('S30.854A', 'Cuerpo extraño superficial de vagina y vulva, contacto inicial', 'Sin especificar', '["astilla zona íntima", "objeto clavado vagina", "vidrio en vulva"]'),
('S30.854D', 'Cuerpo extraño superficial de vagina y vulva, contacto sucesivo', 'Sin especificar', '["revisión cuerpo extraño vaginal", "seguimiento objeto zona íntima", "control herida"]'),
('S30.854S', 'Cuerpo extraño superficial de vagina y vulva, secuela', 'Sin especificar', '["secuela objeto zona íntima", "cicatriz post-astilla", "infección vaginal"]'),
('S30.855A', 'Cuerpo extraño superficial de órganos genitales externos masculinos no especificados, contacto inicial', 'Sin especificar', '["objeto clavado genitales masculinos", "astilla en los bajos"]'),
('S30.855D', 'Cuerpo extraño superficial de órganos genitales externos masculinos no especificados, contacto sucesivo', 'Sin especificar', '["control objeto genitales", "revisión astilla bajos", "seguimiento herida"]'),
('S30.855S', 'Cuerpo extraño superficial de órganos genitales externos masculinos no especificados, secuela', 'Sin especificar', '["secuela cuerpo extraño", "cicatriz en genitales"]'),
('S30.856A', 'Cuerpo extraño superficial de órganos genitales externos femeninos no especificados, contacto inicial', 'Sin especificar', '["objeto clavado genitales femeninos", "astilla zona vulvar"]'),
('S30.856D', 'Cuerpo extraño superficial de órganos genitales externos femeninos no especificados, contacto sucesivo', 'Sin especificar', '["seguimiento objeto genital", "control astilla vulva", "revisión herida"]'),
('S30.856S', 'Cuerpo extraño superficial de órganos genitales externos femeninos no especificados, secuela', 'Sin especificar', '["secuela cuerpo extraño genital", "cicatriz en zona íntima"]'),
('S30.857A', 'Cuerpo extraño superficial de ano, contacto inicial', 'Sin especificar', '["objeto clavado ano", "astilla en el culo", "vidrio en recto"]'),
('S30.857D', 'Cuerpo extraño superficial de ano, contacto sucesivo', 'Sin especificar', '["control objeto anal", "revisión astilla ano", "seguimiento herida"]'),
('S30.857S', 'Cuerpo extraño superficial de ano, secuela', 'Sin especificar', '["secuela objeto anal", "cicatriz zona rectal", "infección anal"]'),
('S30.860A', 'Picadura de insecto (no venenoso) en parte inferior de espalda y pelvis, contacto inicial', 'Sin especificar', '["picadura de mosquito espalda", "bicho en la cadera", "roncha en la espalda baja", "picadura de pulga en coxis"]'),
('S30.860D', 'Picadura de insecto (no venenoso) en parte inferior de espalda y pelvis, contacto sucesivo', 'Sin especificar', '["seguimiento picadura espalda", "revisión roncha cadera", "control bicho lumbosacro"]'),
('S30.860S', 'Picadura de insecto (no venenoso) en parte inferior de espalda y pelvis, secuela', 'Sin especificar', '["secuela picadura insecto", "mancha por picadura", "infección de roncha"]'),
('S30.861A', 'Picadura de insecto (no venenoso) en pared abdominal, contacto inicial', 'Sin especificar', '["picadura en la panza", "roncha en el abdomen", "picadura bicho barriga", "picada vientre"]'),
('S30.861D', 'Picadura de insecto (no venenoso) en pared abdominal, contacto sucesivo', 'Sin especificar', '["revisión picadura panza", "control roncha abdomen", "seguimiento picada vientre"]'),
('S30.861S', 'Picadura de insecto (no venenoso) en pared abdominal, secuela', 'Sin especificar', '["secuela picadura insecto", "mancha post-roncha"]'),
('S30.862A', 'Picadura de insecto (no venenoso) en pene, contacto inicial', 'Sin especificar', '["picadura en el pene", "bicho en el miembro", "roncha en la vergüenza", "picada pito"]'),
('S30.862D', 'Picadura de insecto (no venenoso) en pene, contacto sucesivo', 'Sin especificar', '["control picadura pene", "seguimiento roncha miembro", "revisión bicho genital"]'),
('S30.862S', 'Picadura de insecto (no venenoso) en pene, secuela', 'Sin especificar', '["secuela picadura pene", "mancha en el miembro"]'),
('S30.863A', 'Picadura de insecto (no venenoso) en escroto y testículos, contacto inicial', 'Sin especificar', '["picadura en los huevos", "roncha testículos", "picada bolas", "bicho en el escroto"]'),
('S30.863D', 'Picadura de insecto (no venenoso) en escroto y testículos, contacto sucesivo', 'Sin especificar', '["revisión picadura testículos", "seguimiento roncha escroto", "control picada genital"]'),
('S30.863S', 'Picadura de insecto (no venenoso) en escroto y testículos, secuela', 'Sin especificar', '["secuela picadura escroto", "mancha post-roncha"]'),
('S30.864A', 'Picadura de insecto (no venenoso) en vagina y vulva, contacto inicial', 'Sin especificar', '["picadura en zona íntima", "roncha vulva", "picada zona femenina"]'),
('S30.864D', 'Picadura de insecto (no venenoso) en vagina y vulva, contacto sucesivo', 'Sin especificar', '["control picadura vagina", "seguimiento roncha vulvar", "revisión picada íntima"]'),
('S30.864S', 'Picadura de insecto (no venenoso) en vagina y vulva, secuela', 'Sin especificar', '["secuela picadura íntima", "mancha zona genital"]'),
('S30.865A', 'Picadura de insecto (no venenoso) en órganos genitales externos masculinos no especificados, contacto inicial', 'Sin especificar', '["picadura zona genital masculina", "roncha bajos"]'),
('S30.865D', 'Picadura de insecto (no venenoso) en órganos genitales externos masculinos no especificados, contacto sucesivo', 'Sin especificar', '["seguimiento picadura genitales", "revisión roncha bajos"]'),
('S30.865S', 'Picadura de insecto (no venenoso) en órganos genitales externos masculinos no especificados, secuela', 'Sin especificar', '["secuela picadura genital", "mancha bajos"]'),
('S30.866A', 'Picadura de insecto (no venenoso) en órganos genitales externos femeninos no especificados, contacto inicial', 'Sin especificar', '["picadura genitales femeninos", "roncha zona íntima"]'),
('S30.866D', 'Picadura de insecto (no venenoso) en órganos genitales externos femeninos no especificados, contacto sucesivo', 'Sin especificar', '["revisión picadura genital femenina", "control roncha zona íntima"]'),
('S30.866S', 'Picadura de insecto (no venenoso) en órganos genitales externos femeninos no especificados, secuela', 'Sin especificar', '["secuela picadura zona íntima", "mancha genital"]'),
('S30.867A', 'Picadura de insecto (no venenoso) en ano, contacto inicial', 'Sin especificar', '["picadura anal", "roncha en el culo"]'),
('S30.867D', 'Picadura de insecto (no venenoso) en ano, contacto sucesivo', 'Sin especificar', '["seguimiento picadura ano", "control roncha rectal"]'),
('S30.867S', 'Picadura de insecto (no venenoso) en ano, secuela', 'Sin especificar', '["secuela picadura ano", "cicatriz zona rectal"]'),
('S30.870A', 'Otra mordedura superficial de parte inferior de espalda y pelvis, contacto inicial', 'Sin especificar', '["mordida en la espalda", "mordida en cadera", "rasguño por animal espalda baja"]'),
('S30.870D', 'Otra mordedura superficial de parte inferior de espalda y pelvis, contacto sucesivo', 'Sin especificar', '["control mordida espalda", "revisión herida cadera"]'),
('S30.870S', 'Otra mordedura superficial de parte inferior de espalda y pelvis, secuela', 'Sin especificar', '["secuela mordedura espalda", "cicatriz por mordida"]'),
('S30.871A', 'Otra mordedura superficial de pared abdominal, contacto inicial', 'Sin especificar', '["mordida en la panza", "mordida en abdomen", "rasguño animal barriga"]'),
('S30.871D', 'Otra mordedura superficial de pared abdominal, contacto sucesivo', 'Sin especificar', '["seguimiento mordida panza", "control herida abdomen"]'),
('S30.871S', 'Otra mordedura superficial de pared abdominal, secuela', 'Sin especificar', '["secuela mordedura abdomen", "cicatriz panza"]'),
('S30.872A', 'Otra mordedura superficial de pene, contacto inicial', 'Sin especificar', '["mordida en el pene", "mordida en el miembro"]'),
('S30.872D', 'Otra mordedura superficial de pene, contacto sucesivo', 'Sin especificar', '["revisión mordida pene", "control herida genital"]'),
('S30.872S', 'Otra mordedura superficial de pene, secuela', 'Sin especificar', '["secuela mordedura miembro", "cicatriz pene"]'),
('S30.873A', 'Otra mordedura superficial de escroto y testículos, contacto inicial', 'Sin especificar', '["mordida en los huevos", "mordida escroto"]'),
('S30.873D', 'Otra mordedura superficial de escroto y testículos, contacto sucesivo', 'Sin especificar', '["control mordida testículos", "seguimiento escroto"]'),
('S30.873S', 'Otra mordedura superficial de escroto y testículos, secuela', 'Sin especificar', '["secuela mordida genital", "cicatriz testículos"]'),
('S30.874A', 'Otra mordedura superficial de vagina y vulva, contacto inicial', 'Sin especificar', '["mordida zona íntima", "mordida vulva"]'),
('S30.874D', 'Otra mordedura superficial de vagina y vulva, contacto sucesivo', 'Sin especificar', '["revisión mordida vaginal", "control herida vulvar"]'),
('S30.874S', 'Otra mordedura superficial de vagina y vulva, secuela', 'Sin especificar', '["secuela mordida íntima", "cicatriz vulva"]'),
('S30.875A', 'Otra mordedura superficial de órganos genitales externos masculinos no especificados, contacto inicial', 'Sin especificar', '["mordida genitales masculinos", "mordida zona bajos"]'),
('S30.875D', 'Otra mordedura superficial de órganos genitales externos masculinos no especificados, contacto sucesivo', 'Sin especificar', '["seguimiento mordida genital", "control bajos"]'),
('S30.875S', 'Otra mordedura superficial de órganos genitales externos masculinos no especificados, secuela', 'Sin especificar', '["secuela mordida bajos", "cicatriz genital"]'),
('S30.876A', 'Otra mordedura superficial de órganos genitales externos femeninos no especificados, contacto inicial', 'Sin especificar', '["mordida genitales femeninos", "mordida zona íntima"]'),
('S30.876D', 'Otra mordedura superficial de órganos genitales externos femeninos no especificados, contacto sucesivo', 'Sin especificar', '["revisión mordida genital femenina", "control zona íntima"]'),
('S30.876S', 'Otra mordedura superficial de órganos genitales externos femeninos no especificados, secuela', 'Sin especificar', '["secuela mordida zona genital", "cicatriz"]'),
('S30.877A', 'Otra mordedura superficial de ano, contacto inicial', 'Sin especificar', '["mordida anal", "mordida en el culo"]'),
('S30.877D', 'Otra mordedura superficial de ano, contacto sucesivo', 'Sin especificar', '["control mordida anal", "seguimiento herida rectal"]'),
('S30.877S', 'Otra mordedura superficial de ano, secuela', 'Sin especificar', '["secuela mordida ano", "cicatriz rectal"]'),
('S30.91XA', 'Traumatismo superficial no especificado de parte inferior de espalda y pelvis, contacto inicial', 'Sin especificar', '["golpe indefinido espalda baja", "herida en la cintura", "trauma en cadera"]'),
('S30.91XD', 'Traumatismo superficial no especificado de parte inferior de espalda y pelvis, contacto sucesivo', 'Sin especificar', '["control trauma espalda", "seguimiento herida lumbar"]'),
('S30.91XS', 'Traumatismo superficial no especificado de parte inferior de espalda y pelvis, secuela', 'Sin especificar', '["secuela trauma espalda", "cicatriz lumbosacra"]'),
('S30.92XA', 'Traumatismo superficial no especificado de pared abdominal, contacto inicial', 'Sin especificar', '["golpe indefinido panza", "herida abdomen", "trauma vientre"]'),
('S30.92XD', 'Traumatismo superficial no especificado de pared abdominal, contacto sucesivo', 'Sin especificar', '["seguimiento trauma panza", "control herida abdomen"]'),
('S30.92XS', 'Traumatismo superficial no especificado de pared abdominal, secuela', 'Sin especificar', '["secuela trauma abdomen", "cicatriz panza"]'),
('S30.93XA', 'Traumatismo superficial no especificado de pene, contacto inicial', 'Sin especificar', '["trauma en el pene", "herida miembro"]'),
('S30.93XD', 'Traumatismo superficial no especificado de pene, contacto sucesivo', 'Sin especificar', '["revisión trauma pene", "control herida"]'),
('S30.93XS', 'Traumatismo superficial no especificado de pene, secuela', 'Sin especificar', '["secuela trauma pene", "cicatriz genital"]'),
('S30.94XA', 'Traumatismo superficial no especificado de escroto y testículos, contacto inicial', 'Sin especificar', '["trauma en los huevos", "trauma testículos"]'),
('S30.94XD', 'Traumatismo superficial no especificado de escroto y testículos, contacto sucesivo', 'Sin especificar', '["control trauma testículos", "seguimiento escroto"]'),
('S30.94XS', 'Traumatismo superficial no especificado de escroto y testículos, secuela', 'Sin especificar', '["secuela trauma testículos", "cicatriz genital"]'),
('S30.95XA', 'Traumatismo superficial no especificado de vagina y vulva, contacto inicial', 'Sin especificar', '["trauma zona íntima", "herida vulva"]'),
('S30.95XD', 'Traumatismo superficial no especificado de vagina y vulva, contacto sucesivo', 'Sin especificar', '["revisión trauma vulvar", "control herida íntima"]'),
('S30.95XS', 'Traumatismo superficial no especificado de vagina y vulva, secuela', 'Sin especificar', '["secuela trauma íntimo", "cicatriz vulva"]'),
('S30.96XA', 'Traumatismo superficial no especificado de órganos genitales externos masculinos, no especificados, contacto inicial', 'Sin especificar', '["trauma genitales masculinos", "herida bajos"]'),
('S30.96XD', 'Traumatismo superficial no especificado de órganos genitales externos masculinos, no especificados, contacto sucesivo', 'Sin especificar', '["seguimiento trauma genital", "control bajos"]'),
('S30.96XS', 'Traumatismo superficial no especificado de órganos genitales externos masculinos, no especificados, secuela', 'Sin especificar', '["secuela trauma genital", "cicatriz bajos"]'),
('S30.97XA', 'Traumatismo superficial no especificado de órganos genitales externos femeninos, no especificados, contacto inicial', 'Sin especificar', '["trauma genitales femeninos", "herida zona íntima"]'),
('S30.97XD', 'Traumatismo superficial no especificado de órganos genitales externos femeninos, no especificados, contacto sucesivo', 'Sin especificar', '["revisión trauma genital", "control zona íntima"]'),
('S30.97XS', 'Traumatismo superficial no especificado de órganos genitales externos femeninos, no especificados, secuela', 'Sin especificar', '["secuela trauma zona íntima", "cicatriz genital"]'),
('S30.98XA', 'Traumatismo superficial no especificado de ano, contacto inicial', 'Sin especificar', '["trauma anal", "herida en el culo"]'),
('S30.98XD', 'Traumatismo superficial no especificado de ano, contacto sucesivo', 'Sin especificar', '["control trauma anal", "seguimiento herida rectal"]'),
('S30.98XS', 'Traumatismo superficial no especificado de ano, secuela', 'Sin especificar', '["secuela trauma anal", "cicatriz rectal"]');
