INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S17.0XXA', 'Lesión por aplastamiento de laringe y tráquea, contacto inicial', 'Sin especificar', '["golpe en el cuello", "traumatismo laringe", "tráquea aplastada", "asfixia mecánica", "ahorcamiento", "falta de aire", "dolor en la garganta", "no puedo tragar", "garganta cerrada", "lesión vía aérea", "trauma cervical", "aplastamiento cuello", "hematoma cuello", "afonía por golpe", "dificultad al respirar"]'),
('S17.0XXD', 'Lesión por aplastamiento de laringe y tráquea, contacto sucesivo', 'Sin especificar', '["seguimiento golpe laringe", "revisión tráquea", "control trauma cervical", "secuela golpe garganta", "evaluación posterior laringe", "dolor persistente garganta", "problemas para respirar tras golpe", "curación tráquea", "tratamiento continuo garganta", "revisión médica post trauma", "dolor al tragar persistente", "seguimiento médico cuello"]'),
('S17.0XXS', 'Lesión por aplastamiento de laringe y tráquea, secuela', 'Sin especificar', '["cicatriz traqueal", "estenosis laringe", "voz ronca crónica", "secuela trauma cuello", "consecuencia aplastamiento garganta", "problemas respiratorios crónicos", "dificultad al hablar", "tejido cicatricial garganta", "daño permanente tráquea", "traqueostomía secuela", "afonía permanente", "consecuencia golpe cuello"]'),
('S17.8XXA', 'Lesión por aplastamiento de otras partes especificadas del cuello, contacto inicial', 'Sin especificar', '["golpe fuerte cuello", "traumatismo cervical", "aplastamiento de cuello", "lesión tejido blando cuello", "dolor cervical intenso", "pescuezo lastimado", "golpe en la nuca", "trauma por compresión", "cuello prensado", "lesión yugular", "dolor en el gañote", "traumatismo vasos cuello", "hinchazón cuello"]'),
('S17.8XXD', 'Lesión por aplastamiento de otras partes especificadas del cuello, contacto sucesivo', 'Sin especificar', '["seguimiento traumatismo cuello", "control lesión cervical", "evolución golpe cuello", "revisión trauma cuello", "dolor cervical recurrente", "rehabilitación cervical", "tratamiento aplastamiento cuello", "consulta control cuello", "terapia por golpe cuello", "seguimiento médico cervical", "dolor persistente nuca", "chequeo vasos cuello"]'),
('S17.8XXS', 'Lesión por aplastamiento de otras partes especificadas del cuello, secuela', 'Sin especificar', '["dolor crónico cervical", "secuela golpe cuello", "rigidez cuello permanente", "daño permanente cervical", "cicatriz interna cuello", "consecuencia trauma nuca", "limitación movimiento cuello", "fibrosis cervical", "dolor al mover la cabeza", "lesión crónica cuello", "consecuencia aplastamiento", "daño muscular crónico cuello"]'),
('S17.9XXA', 'Lesión por aplastamiento del cuello, parte no especificada, contacto inicial', 'Sin especificar', '["accidente cuello", "golpe en el pescuezo", "aplastamiento zona cervical", "lesión traumática cuello", "traumatismo zona del cuello", "emergencia cuello", "dolor cuello por accidente", "cuello prensado", "golpe severo cuello", "trauma compresivo cuello", "urgencia cuello", "daño cervical general"]'),
('S17.9XXD', 'Lesión por aplastamiento del cuello, parte no especificada, contacto sucesivo', 'Sin especificar', '["control accidente cuello", "seguimiento lesión cervical", "evaluación golpe cuello", "revisión trauma cuello", "tratamiento continuo zona cervical", "terapia por aplastamiento cuello", "evolución lesión cuello", "consulta médica cuello", "seguimiento post traumatismo cervical", "rehabilitación zona del cuello", "valoración médica cuello"]'),
('S17.9XXS', 'Lesión por aplastamiento del cuello, parte no especificada, secuela', 'Sin especificar', '["secuela accidente cuello", "consecuencia lesión cuello", "dolor crónico en la zona del cuello", "daño residual cuello", "limitación funcional cuello", "secuelas por aplastamiento", "rigidez residual cervical", "dolor crónico pescuezo", "cicatrices internas cervicales", "problemas crónicos cuello", "consecuencia trauma general cuello"]');
