INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L02.01', 'Absceso cutáneo en la cara', 'Sin especificar', '["absceso facial", "postemilla en la cara", "flemón en la cara", "bulto con pus en la cara", "grano infectado cara", "infección de piel cara", "inflamación con pus cara", "nódulo doloroso cara", "bolita de pus en la cara", "abceso en el cachete", "infección en la mejilla", "masa purulenta facial", "colección de pus en la cara", "flemón facial"]'),
('L02.02', 'Forúnculo en la cara', 'Sin especificar', '["forúnculo", "grano enterrado", "nacido en la cara", "grano con pus", "golondrino en la cara", "infección folículo piloso", "chichón con pus", "grano gigante", "espinilla infectada", "nacido doloroso", "flemón", "bulto doloroso cara", "grano inflamado", "infección piel cara"]'),
('L02.03', 'Ántrax en la cara', 'Sin especificar', '["ántrax facial", "infección múltiple folículos", "forúnculos agrupados", "carbunco en la cara", "agrupación de nacidos", "infección severa piel cara", "bultos con pus cara", "flemón severo", "absceso múltiple cara", "infección cutánea grave", "granos agrupados cara", "úlcera con pus cara"]'),
('L02.11', 'Absceso cutáneo en el cuello', 'Sin especificar', '["absceso en el cuello", "flemón en el cuello", "bulto con pus cuello", "postemilla en el cuello", "infección en el cuello", "masa dolorosa cuello", "colección pus cuello", "abceso en el pescuezo", "inflamación purulenta cuello", "nódulo infectado cuello", "bulto cuello con pus"]'),
('L02.12', 'Forúnculo en el cuello', 'Sin especificar', '["nacido en el cuello", "grano en el cuello", "golondrino cuello", "forúnculo en el cuello", "grano enterrado cuello", "chichón infectado", "infección vello cuello", "grano con pus cuello", "bolita infectada cuello", "nacido doloroso cuello"]'),
('L02.13', 'Ántrax en el cuello', 'Sin especificar', '["ántrax en cuello", "carbunco cuello", "agrupación forúnculos cuello", "infección severa cuello", "nidos de granos cuello", "ántrax cutáneo", "forunculosis agrupada", "infección piel profunda cuello", "masas con pus cuello"]'),
('L02.211', 'Absceso cutáneo en pared abdominal', 'Sin especificar', '["absceso en la panza", "bulto pus abdomen", "flemón en la barriga", "infección abdominal cutánea", "postemilla abdomen", "colección pus panza", "abceso pared abdominal", "masa dolorosa panza", "bola con pus abdomen", "abceso en la guata"]'),
('L02.212', 'Absceso cutáneo en la espalda', 'Sin especificar', '["absceso en la espalda", "flemón en la espalda", "bulto con pus espalda", "postemilla espalda", "infección piel espalda", "masa dolorosa espalda", "colección pus espalda", "abceso espalda", "bolita infectada espalda"]'),
('L02.213', 'Absceso cutáneo en pared torácica', 'Sin especificar', '["absceso en el pecho", "abceso tórax", "flemón en el pecho", "bulto con pus pecho", "infección piel pecho", "postemilla pecho", "masa dolorosa tórax", "bola infectada pecho"]'),
('L02.214', 'Absceso cutáneo en la ingle', 'Sin especificar', '["absceso en la ingle", "golondrino ingle", "flemón en la ingle", "bulto con pus ingle", "infección zona inguinal", "postemilla ingle", "masa dolorosa ingle", "bola infectada ingle"]'),
('L02.215', 'Absceso cutáneo en periné o perineo', 'Sin especificar', '["absceso en el perineo", "absceso zona genital", "flemón periné", "bulto con pus zona íntima", "infección perineal", "postemilla periné", "masa dolorosa periné", "abceso entre piernas"]'),
('L02.216', 'Absceso cutáneo en ombligo', 'Sin especificar', '["absceso en el ombligo", "infección ombligo", "flemón en el ombligo", "bulto con pus ombligo", "postemilla ombligo", "masa dolorosa ombligo", "bola infectada ombligo"]'),
('L02.219', 'Absceso cutáneo en tronco, sitio no especificado', 'Sin especificar', '["absceso en el tronco", "bulto con pus cuerpo", "infección cutánea cuerpo", "flemón tronco", "postemilla tronco", "masa dolorosa cuerpo"]'),
('L02.221', 'Forúnculo en pared abdominal', 'Sin especificar', '["nacido en la panza", "grano en la panza", "forúnculo abdomen", "grano enterrado abdomen", "golondrino panza", "chichón con pus panza"]'),
('L02.222', 'Forúnculo en la espalda', 'Sin especificar', '["nacido en la espalda", "grano en la espalda", "forúnculo espalda", "grano enterrado espalda", "golondrino espalda", "chichón con pus espalda"]'),
('L02.223', 'Forúnculo de pared torácica', 'Sin especificar', '["nacido en el pecho", "grano en el pecho", "forúnculo pecho", "grano enterrado pecho", "golondrino pecho"]'),
('L02.224', 'Forúnculo de ingle', 'Sin especificar', '["nacido en la ingle", "grano en la ingle", "forúnculo ingle", "golondrino en la ingle", "grano enterrado ingle"]'),
('L02.225', 'Forúnculo de periné o perineo', 'Sin especificar', '["nacido en el perineo", "grano en zona genital", "forúnculo zona íntima", "grano enterrado periné"]'),
('L02.226', 'Forúnculo de ombligo', 'Sin especificar', '["nacido en el ombligo", "grano en el ombligo", "forúnculo ombligo", "grano enterrado ombligo"]'),
('L02.229', 'Forúnculo de tronco, no especificado', 'Sin especificar', '["nacido en el cuerpo", "grano en el tronco", "forúnculo cuerpo", "grano enterrado tronco"]'),
('L02.231', 'Ántrax de pared abdominal', 'Sin especificar', '["ántrax en la panza", "carbunco abdominal", "infección profunda abdomen", "granos agrupados panza"]'),
('L02.232', 'Ántrax de espalda', 'Sin especificar', '["ántrax en la espalda", "carbunco espalda", "infección profunda espalda", "granos agrupados espalda"]'),
('L02.233', 'Ántrax de pared torácica', 'Sin especificar', '["ántrax en el pecho", "carbunco pecho", "infección profunda pecho", "granos agrupados pecho"]'),
('L02.234', 'Ántrax de ingle', 'Sin especificar', '["ántrax en la ingle", "carbunco ingle", "infección profunda ingle", "granos agrupados ingle"]'),
('L02.235', 'Ántrax de periné', 'Sin especificar', '["ántrax en el perineo", "carbunco periné", "infección profunda zona íntima"]'),
('L02.236', 'Ántrax de ombligo', 'Sin especificar', '["ántrax en el ombligo", "carbunco ombligo", "infección profunda ombligo"]'),
('L02.239', 'Ántrax de tronco, no especificado', 'Sin especificar', '["ántrax en el cuerpo", "carbunco cuerpo", "infección profunda piel"]'),
('L02.31', 'Absceso cutáneo de nalga', 'Sin especificar', '["absceso en la nalga", "absceso en el glúteo", "flemón en la pompa", "bulto con pus trasero", "infección nalga", "postemilla trasero", "abceso en el cachete del trasero"]'),
('L02.32', 'Forúnculo de nalga', 'Sin especificar', '["nacido en la nalga", "grano en la pompa", "golondrino en el glúteo", "forúnculo trasero", "grano enterrado glúteo"]'),
('L02.33', 'Ántrax de nalga', 'Sin especificar', '["ántrax en la nalga", "carbunco glúteo", "infección profunda nalga", "granos agrupados trasero"]'),
('L02.411', 'Absceso cutáneo de axila derecha', 'Sin especificar', '["absceso en la axila", "flemón axilar", "bulto con pus axila", "golondrino axila", "postemilla axila"]'),
('L02.412', 'Absceso cutáneo de axila izquierda', 'Sin especificar', '["absceso en la axila", "flemón axilar", "bulto con pus axila", "golondrino axila", "postemilla axila"]'),
('L02.413', 'Absceso cutáneo de extremidad superior derecha', 'Sin especificar', '["absceso brazo", "absceso antebrazo", "bulto brazo con pus", "infección brazo"]'),
('L02.414', 'Absceso cutáneo de extremidad superior izquierda', 'Sin especificar', '["absceso brazo", "absceso antebrazo", "bulto brazo con pus", "infección brazo"]'),
('L02.415', 'Absceso cutáneo de extremidad inferior derecha', 'Sin especificar', '["absceso pierna", "absceso muslo", "bulto pierna con pus", "infección pierna"]'),
('L02.416', 'Absceso cutáneo de extremidad inferior izquierda', 'Sin especificar', '["absceso pierna", "absceso muslo", "bulto pierna con pus", "infección pierna"]'),
('L02.419', 'Absceso cutáneo de extremidad, no especificada', 'Sin especificar', '["absceso extremidad", "infección brazo o pierna", "bulto con pus extremidad"]'),
('L02.421', 'Forúnculo de axila derecha', 'Sin especificar', '["golondrino axila", "nacido axila", "grano axila", "forúnculo axila"]'),
('L02.422', 'Forúnculo de axila izquierda', 'Sin especificar', '["golondrino axila", "nacido axila", "grano axila", "forúnculo axila"]'),
('L02.423', 'Forúnculo de extremidad superior derecha', 'Sin especificar', '["nacido brazo", "grano brazo", "forúnculo brazo"]'),
('L02.424', 'Forúnculo de extremidad superior izquierda', 'Sin especificar', '["nacido brazo", "grano brazo", "forúnculo brazo"]'),
('L02.425', 'Forúnculo de extremidad inferior derecha', 'Sin especificar', '["nacido pierna", "grano pierna", "forúnculo pierna"]'),
('L02.426', 'Forúnculo de extremidad inferior izquierda', 'Sin especificar', '["nacido pierna", "grano pierna", "forúnculo pierna"]'),
('L02.429', 'Forúnculo de extremidad, no especificada', 'Sin especificar', '["nacido extremidad", "grano extremidad", "forúnculo extremidad"]'),
('L02.431', 'Ántrax de axila derecha', 'Sin especificar', '["ántrax axila", "carbunco axila", "granos agrupados axila"]'),
('L02.432', 'Ántrax de axila izquierda', 'Sin especificar', '["ántrax axila", "carbunco axila", "granos agrupados axila"]'),
('L02.433', 'Ántrax de extremidad superior derecha', 'Sin especificar', '["ántrax brazo", "carbunco brazo", "infección profunda brazo"]'),
('L02.434', 'Ántrax de extremidad superior izquierda', 'Sin especificar', '["ántrax brazo", "carbunco brazo", "infección profunda brazo"]'),
('L02.435', 'Ántrax de extremidad inferior derecha', 'Sin especificar', '["ántrax pierna", "carbunco pierna", "infección profunda pierna"]'),
('L02.436', 'Ántrax de extremidad inferior izquierda', 'Sin especificar', '["ántrax pierna", "carbunco pierna", "infección profunda pierna"]'),
('L02.439', 'Ántrax de extremidad, no especificada', 'Sin especificar', '["ántrax extremidad", "carbunco extremidad"]'),
('L02.511', 'Absceso cutáneo de mano derecha', 'Sin especificar', '["absceso mano", "flemón mano", "bulto con pus mano", "infección dedo", "postemilla mano"]'),
('L02.512', 'Absceso cutáneo de mano izquierda', 'Sin especificar', '["absceso mano", "flemón mano", "bulto con pus mano", "infección dedo", "postemilla mano"]'),
('L02.519', 'Absceso cutáneo de mano, lado no especificado', 'Sin especificar', '["absceso mano", "flemón mano", "bulto con pus mano", "infección dedo"]'),
('L02.521', 'Forúnculo de mano derecha', 'Sin especificar', '["nacido mano", "grano mano", "forúnculo mano"]'),
('L02.522', 'Forúnculo de mano izquierda', 'Sin especificar', '["nacido mano", "grano mano", "forúnculo mano"]'),
('L02.529', 'Forúnculo de mano no especificada', 'Sin especificar', '["nacido mano", "grano mano", "forúnculo mano"]'),
('L02.531', 'Ántrax de mano derecha', 'Sin especificar', '["ántrax mano", "carbunco mano", "infección profunda mano"]'),
('L02.532', 'Ántrax de mano izquierda', 'Sin especificar', '["ántrax mano", "carbunco mano", "infección profunda mano"]'),
('L02.539', 'Ántrax de mano, lado no especificado', 'Sin especificar', '["ántrax mano", "carbunco mano", "infección profunda mano"]'),
('L02.611', 'Absceso cutáneo de pie derecho', 'Sin especificar', '["absceso pie", "flemón pie", "bulto con pus pie", "postemilla pie", "infección dedo pie"]'),
('L02.612', 'Absceso cutáneo de pie izquierdo', 'Sin especificar', '["absceso pie", "flemón pie", "bulto con pus pie", "postemilla pie", "infección dedo pie"]'),
('L02.619', 'Absceso cutáneo de pie, lado no especificado', 'Sin especificar', '["absceso pie", "flemón pie", "bulto con pus pie", "infección pie"]'),
('L02.621', 'Forúnculo de pie derecho', 'Sin especificar', '["nacido pie", "grano pie", "forúnculo pie"]'),
('L02.622', 'Forúnculo de pie izquierdo', 'Sin especificar', '["nacido pie", "grano pie", "forúnculo pie"]'),
('L02.629', 'Forúnculo de pie, lado no especificado', 'Sin especificar', '["nacido pie", "grano pie", "forúnculo pie"]'),
('L02.631', 'Ántrax de pie derecho', 'Sin especificar', '["ántrax pie", "carbunco pie", "infección profunda pie"]'),
('L02.632', 'Ántrax de pie izquierdo', 'Sin especificar', '["ántrax pie", "carbunco pie", "infección profunda pie"]'),
('L02.639', 'Ántrax de pie no especificado', 'Sin especificar', '["ántrax pie", "carbunco pie", "infección profunda pie"]'),
('L02.811', 'Absceso cutáneo de cabeza [cualquier parte, excepto de cara]', 'Sin especificar', '["absceso cuero cabelludo", "bulto con pus cabeza", "postemilla cabeza", "infección cabeza"]'),
('L02.818', 'Absceso cutáneo de otros sitios', 'Sin especificar', '["absceso cutáneo", "bulto con pus en la piel", "infección de piel"]'),
('L02.821', 'Forúnculo de cabeza [cualquier parte, excepto de cara]', 'Sin especificar', '["nacido en la cabeza", "grano cuero cabelludo", "forúnculo cabeza"]'),
('L02.828', 'Forúnculo de otros sitios', 'Sin especificar', '["forúnculo", "grano con pus", "nacido en la piel"]'),
('L02.831', 'Ántrax de cabeza [cualquier parte, excepto de cara]', 'Sin especificar', '["ántrax en la cabeza", "carbunco cabeza", "infección profunda cuero cabelludo"]'),
('L02.838', 'Ántrax de otros sitios', 'Sin especificar', '["ántrax", "carbunco", "infección profunda piel"]'),
('L02.91', 'Absceso cutáneo, no especificado', 'Sin especificar', '["absceso", "bulto con pus", "flemón", "postemilla", "infección con pus"]'),
('L02.92', 'Forúnculo, no especificado', 'Sin especificar', '["forúnculo", "nacido", "grano con pus", "golondrino", "grano enterrado"]'),
('L02.93', 'Ántrax, no especificado', 'Sin especificar', '["ántrax", "carbunco", "infección piel severa", "granos agrupados"]');
