INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N50.0', 'Atrofia testicular', 'Sin especificar', '["testículos pequeños", "encogimiento de huevos", "testículos que se achican", "atrofia de testículo", "bolas pequeñas", "testículos sin tamaño", "problemas de tamaño en testículos", "atrofia escrotal", "testículos atrofiados", "testículos que no crecen", "disminución de testículos", "testículos marchitos", "huevas chicas", "falta de desarrollo testicular", "testículos flácidos"]'),
('N50.1', 'Trastornos vasculares de los órganos genitales masculinos', 'Sin especificar', '["varicocele", "venas hinchadas en testículos", "venas inflamadas en el escroto", "problemas de circulación en los huevos", "dolor de venas en el aparato reproductor", "bolsa de gusanos en escroto", "venas dilatadas en testículos", "dolor vascular escrotal", "problemas de riego sanguíneo genital", "hinchazón de venas escrotales", "varices en testículos", "problemas de venas en el escroto", "dolor en venas genitales", "circulación testicular lenta", "venas retorcidas en el escroto"]'),
('N50.3', 'Quiste de epidídimo', 'Sin especificar', '["bolita en el testículo", "bulto en el epidídimo", "quiste en los huevos", "bolita detrás del testículo", "espermatocele", "masa en el escroto", "quiste escrotal", "bulto indoloro en testículo", "quiste en el aparato genital masculino", "bolita dura en el escroto", "inflamación epididimaria", "bolita movible en testículo", "quiste en conductos testiculares", "bulto al tacto en el escroto", "protuberancia en el epidídimo"]'),
('N50.811', 'Dolor testicular derecho', 'Sin especificar', '["dolor en testículo derecho", "dolor de huevo derecho", "pinchazos en el testículo derecho", "testículo derecho adolorido", "dolor en la bola derecha", "dolor de testículo del lado derecho", "molestia en el escroto derecho", "dolor en huevo de la derecha", "punzadas en el testículo derecho", "testículo derecho inflamado", "tensión en testículo derecho", "golpe en testículo derecho", "dolor agudo en el derecho", "dolor testicular derecho persistente", "molestia al caminar lado derecho"]'),
('N50.812', 'Dolor testicular izquierdo', 'Sin especificar', '["dolor en testículo izquierdo", "dolor de huevo izquierdo", "pinchazos en el testículo izquierdo", "testículo izquierdo adolorido", "dolor en la bola izquierda", "dolor de testículo del lado izquierdo", "molestia en el escroto izquierdo", "dolor en huevo de la izquierda", "punzadas en el testículo izquierdo", "testículo izquierdo inflamado", "tensión en testículo izquierdo", "golpe en testículo izquierdo", "dolor agudo en el izquierdo", "dolor testicular izquierdo persistente", "molestia al caminar lado izquierdo"]'),
('N50.819', 'Dolor testicular, no especificado', 'Sin especificar', '["dolor en los huevos", "dolor en los testículos", "dolor testicular", "dolor escrotal", "me duelen las bolas", "molestia en los testículos", "testículos adoloridos", "dolor genital masculino", "punzadas en los huevos", "dolor en la bolsa escrotal", "dolor testicular difuso", "testículos sensibles", "dolor al tacto en testículos", "molestia constante en los huevos", "dolor de testículos sin causa"]'),
('N50.82', 'Dolor escrotal', 'Sin especificar', '["dolor en la bolsa", "dolor de escroto", "me duele la bolsa de los huevos", "dolor en la entrepierna", "inflamación dolorosa escrotal", "dolor en la piel del escroto", "dolor testicular general", "pesadez en el escroto", "dolor en la zona genital", "escroto adolorido", "dolor al rozar el escroto", "hinchazón escrotal con dolor", "molestia en la bolsa testicular", "dolor agudo en el escroto", "dolor insoportable en los huevos"]'),
('N50.89', 'Otros trastornos especificados de los órganos genitales masculinos', 'Sin especificar', '["problemas genitales masculinos", "molestias en el aparato reproductor masculino", "enfermedades escrotales", "trastornos del pene y testículos", "dolencias genitales del hombre", "problemas en las partes íntimas", "anomalías genitales masculinas", "afecciones del escroto", "infecciones genitales masculinas", "dolor genital", "hinchazón en partes íntimas", "problemas de piel escrotal", "irritación genital masculina", "trastornos testiculares no clasificados", "incomodidad genital"]'),
('N50.9', 'Trastorno de órganos genitales masculinos, no especificados', 'Sin especificar', '["problema en el aparato reproductor", "molestia en las partes íntimas", "algo raro en los testículos", "problemas de los huevos", "dolencia genital masculina no definida", "enfermedad en el área genital", "tengo algo en mis partes", "problema genital", "afección en el aparato genital", "trastorno del escroto", "incomodidad en los genitales", "anomalía en los genitales masculinos", "dolor inexplicable en la zona genital", "cambios en los testículos", "síntomas en los genitales"]');
