INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('I48.0', 'Fibrilación paroxística auricular', 'Sin especificar', '["arritmia", "palpitaciones", "taquicardia", "corazón acelerado", "latidos irregulares", "corazón loco", "se me sale el corazón", "taquicardia paroxística", "vuelco al corazón", "taquicardia episódica", "arritmia intermitente", "pecho agitado", "palpitadera", "taquicardias ocasionales"]'),
('I48.11', 'Fibrilación auricular persistente de larga duración', 'Sin especificar', '["arritmia crónica", "problemas del corazón", "latidos descontrolados", "taquicardia constante", "fibrilación de larga data", "corazón no descansa", "arritmia persistente", "palpitaciones seguidas", "taquicardia crónica", "ritmo cardiaco alterado", "corazón cansado", "falla en el ritmo cardiaco", "latidos rápidos todo el tiempo"]'),
('I48.19', 'Otro tipo de fibrilación auricular persistente', 'Sin especificar', '["arritmia persistente", "corazón desritmado", "palpitaciones continuas", "falla eléctrica del corazón", "taquicardia persistente", "ritmo cardiaco irregular constante", "problemas de ritmo", "fibrilación prolongada", "corazón agitado", "latidos que no se normalizan", "arritmia recalcitrante"]'),
('I48.20', 'Fibrilación auricular crónica, no especificada', 'Sin especificar', '["arritmia de siempre", "corazón con ritmo raro", "fibrilación vieja", "problema cardiaco permanente", "taquicardia crónica", "arritmia antigua", "latidos irregulares crónicos", "corazón con arritmia", "siempre tengo taquicardia", "problemas constantes en el pulso"]'),
('I48.21', 'Fibrilación auricular permanente', 'Sin especificar', '["arritmia permanente", "corazón que no marca bien", "fibrilación de base", "taquicardia de por vida", "arritmia inalterable", "fallo cardiaco constante", "pulso irregular definitivo", "corazón descompasado", "siempre el corazón acelerado", "ritmo cardiaco nunca normal", "arritmia estable"]'),
('I48.3', 'Flutter auricular típico', 'Sin especificar', '["flutter", "aleteo auricular", "taquicardia rápida", "arritmia rápida", "golpeteo en el pecho", "latidos muy rápidos", "corazón galopante", "taquicardia de flutter", "palpitaciones intensas", "ritmo cardiaco acelerado", "taquicardia regular", " flutter de aurícula"]'),
('I48.4', 'Flutter auricular atípico', 'Sin especificar', '["flutter raro", "arritmia atípica", "taquicardia extraña", "aleteo auricular inusual", "flutter auricular complejo", "problema de ritmo cardiaco", "latidos fuera de lugar", "taquicardia atípica", "ritmo cardiaco desordenado", "flutter de origen raro", "palpitaciones anormales"]'),
('I48.91', 'Fibrilación auricular no especificada', 'Sin especificar', '["arritmia cardiaca", "tengo el corazón loco", "palpitaciones", "taquicardia", "problema de ritmo", "corazón acelerado", "latidos mal", "taquicardia sin nombre", "me palpita el pecho", "pulso raro", "arritmia sin especificar", "enfermedad del corazón"]'),
('I48.92', 'Flutter auricular no especificado', 'Sin especificar', '["flutter cardiaco", "aleteo del corazón", "taquicardia por flutter", "ritmo cardiaco rápido", "palpitaciones por flutter", "corazón que aletea", "taquicardia sin clasificar", "problema de flutter", "taquicardia de aleteo", "latidos rápidos y constantes", "flutter"]');
