INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N53.11', 'Eyaculación tardía', 'Sin especificar', '["eyaculación tardía", "no puedo acabar", "tardo mucho en venirme", "eyaculación retardada", "no llego al orgasmo", "problemas para correrse", "tardar demasiado en el acto", "eyaculación demorada", "impotencia eyaculatoria", "dificultad para eyacular", "demora en el clímax", "me cuesta terminar", "poca sensibilidad al eyacular", "eyaculación inhibida"]'),
('N53.12', 'Eyaculación dolorosa', 'Sin especificar', '["eyaculación dolorosa", "dolor al eyacular", "me arde al correrne", "pinchazos al terminar", "dolor después del orgasmo", "espasmos dolorosos", "ardor en la uretra al acabar", "molestias al llegar al clímax", "dolor pélvico al eyacular", "diseyaculación", "dolor en el pene al acabar", "se siente feo al terminar", "dolor post-orgásmico", "quemazón al expulsar semen"]'),
('N53.13', 'Orgasmo aneyaculatorio', 'Sin especificar', '["orgasmo aneyaculatorio", "orgasmo seco", "no sale nada al acabar", "eyaculación seca", "acabo sin líquido", "orgasmo sin eyaculación", "no expulso semen", "clímax sin expulsión", "problemas de salida de semen", "eyaculación ausente", "sin fluido al terminar", "eyaculación vacía", "eyaculación impedida", "orgasmo sin esperma"]'),
('N53.14', 'Eyaculación retrógrada', 'Sin especificar', '["eyaculación retrógrada", "el semen se va para adentro", "eyaculación hacia la vejiga", "orinar turbio después del sexo", "el semen no sale hacia afuera", "flujo seminal inverso", "se me va para atrás el semen", "semen en la vejiga", "ausencia de eyaculación externa", "orgasmo seco interno", "eyaculación fallida", "problema de salida de semen", "eyaculación invertida", "esperma en la orina"]'),
('N53.19', 'Otros tipos de disfunción eyaculatoria', 'Sin especificar', '["disfunción eyaculatoria", "problemas para correrse", "eyaculación prematura", "eyaculación precoz", "fallas al terminar", "eyaculación incontrolable", "no puedo terminar", "problemas de semen", "trastornos del orgasmo masculino", "eyaculación rápida", "eyaculación bloqueada", "anorgasmia masculina", "problemas de salida de esperma", "disfunción del clímax"]'),
('N53.8', 'Otros tipos de disfunción sexual masculina', 'Sin especificar', '["disfunción sexual masculina", "problemas de erección", "impotencia", "baja libido", "deseo sexual bajo", "problemas en la cama", "disfunción eréctil", "falta de erección", "problemas de desempeño sexual", "no se me para", "eyaculación rápida", "poca potencia sexual", "problemas de intimidad", "no respondo sexualmente"]'),
('N53.9', 'Disfunción sexual masculina no especificados', 'Sin especificar', '["disfunción sexual", "problemas sexuales", "falla sexual", "dificultades en el sexo", "no funciona mi aparato reproductor", "problemas con el pene", "trastorno sexual masculino", "no puedo tener relaciones", "me falla el cuerpo en el sexo", "problemas viriles", "dificultad sexual", "trastorno del deseo", "problemas de potencia", "disfunción indefinida"]');
