INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('E20.0', 'Hipoparatiroidismo idiopático', 'Sin especificar', '["falta de calcio", "hormona paratiroidea baja", "problema de glándulas", "calambres constantes", "hormigueo en manos", "parestesia", "tetania", "calcio en sangre bajo", "hipocalcemia", "entumecimiento facial", "espasmos musculares", "tiroides mal", "problema de hormonas", "debilidad muscular", "convulsiones"]'),
('E20.1', 'Seudohipoparatiroidismo', 'Sin especificar', '["resistencia a la hormona paratiroidea", "falta de respuesta al calcio", "calcio bajo y fósforo alto", "genética de calcio", "síndrome de Albright", "baja estatura", "calcificaciones", "problemas óseos", "trastorno hormonal", "huesos débiles", "huesos cortos", "hormona que no funciona", "calcio desregulado", "anomalía metabólica", "endocrinopatía"]'),
('E20.810', 'Hipocalcemia autosómica dominante', 'Sin especificar', '["calcio bajo hereditario", "problema familiar de calcio", "hipercalciuria", "calcio en orina alto", "calcio sanguíneo bajo", "genético de glándulas", "herencia dominante de calcio", "problema de riñón por calcio", "hormona paratiroidea suprimida", "heredado de los padres", "parestesias familiares", "espasmos por herencia", "metabolismo del calcio alterado", "sensor de calcio defectuoso", "hipocalcemia familiar"]'),
('E20.811', 'Hipoparatiroidismo secundario en enfermedades clasificadas bajo otro concepto', 'Sin especificar', '["paratiroides dañada", "daño post quirúrgico", "secuelas de cirugía", "después de operación de tiroides", "calcio bajo por cirugía", "paratiroides extirpada", "daño por radiación", "hipocalcemia secundaria", "efecto colateral de cirugía", "hipoparatiroidismo quirúrgico", "falla de paratiroides", "bajada de calcio post operatoria", "complicación quirúrgica", "problema por tratamiento previo", "calcio bajo por enfermedad"]'),
('E20.812', 'Hipoparatiroidismo autoinmune', 'Sin especificar', '["sistema inmune atacando glándulas", "defensas contra paratiroides", "autoanticuerpos", "enfermedad autoinmune", "paratiroides inflamada", "destrucción glandular", "cuerpo atacándose solo", "calcio bajo autoinmune", "hormonas bajas", "falla glandular inmunitaria", "problema de defensas", "hipocalcemia crónica", "tiroiditis asociada", "poliendocrinopatía", "autoinmunidad hormonal"]'),
('E20.818', 'Hipoparatiroidismo debido a alteración de la secreción de hormona paratiroidea', 'Sin especificar', '["la glándula no secreta hormona", "falta de producción hormonal", "falla de secreción paratiroidea", "PTH baja", "hormona paratiroidea insuficiente", "incapacidad de secretar", "problema de fabricación hormonal", "calcio en sangre insuficiente", "glándula paratiroides en reposo", "baja producción de PTH", "trastorno endocrino específico", "fallo en el eje hormonal", "hipocalcemia por falta de PTH", "secreción hormonal alterada", "insuficiencia paratiroidea"]'),
('E20.819', 'Hipoparatiroidismo debido a alteración de la secreción de hormona paratiroidea, no especificado', 'Sin especificar', '["no sé por qué no produzco hormona", "PTH baja inexplicada", "falla glandular desconocida", "calcio bajo por causa no clara", "problema de paratiroides sin causa", "hipocalcemia no diagnosticada", "bajada de calcio misteriosa", "problema de hormona indeterminado", "secreción de PTH fallida", "disfunción hormonal genérica", "hipoparatiroidismo vago", "alteración hormonal sin definir", "desequilibrio de calcio y hormonas", "falla funcional paratiroidea", "problema hormonal sin especificar"]'),
('E20.89', 'Otro tipo especificado de hipoparatiroidismo', 'Sin especificar', '["otro hipoparatiroidismo", "causa rara de calcio bajo", "problema paratiroideo especial", "hipocalcemia por otras causas", "disfunción glandular menos común", "trastorno específico del calcio", "falla hormonal rara", "afección de la paratiroides", "hipocalcemia inusual", "baja PTH específica", "problema endocrino raro", "alteración de paratiroides", "variante de hipoparatiroidismo", "causa externa de hipoparatiroidismo", "síndrome paratiroideo"]'),
('E20.9', 'Hipoparatiroidismo, no especificado', 'Sin especificar', '["tengo calcio bajo", "problema de glándulas en el cuello", "calcio en sangre bajo", "hormonas de los huesos bajas", "tengo las paratiroides mal", "hipocalcemia", "me faltan hormonas paratiroideas", "problema endocrino general", "desorden de calcio", "tengo tetania", "espasmos en las manos", "hormigueo", "problema de glándulas no especificado", "calcio descompensado", "hipoparatiroidismo"]');
