INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K35.200', 'Apendicitis aguda con peritonitis generalizada, sin perforación ni absceso', 'Sin especificar', '["apendicitis", "dolor de panza", "dolor de guata", "dolor de barriga", "apéndice inflamado", "infección en el abdomen", "dolor fuerte lado derecho", "fiebre y dolor abdominal", "peritonitis", "emergencia abdominal", "apendicitis aguda", "dolor agudo en el vientre", "vientre duro", "abdomen en tabla", "inflamación abdominal grave"]'),
('K35.201', 'Apendicitis aguda con peritonitis generalizada, con perforación, sin absceso', 'Sin especificar', '["apéndice reventado", "apendicitis perforada", "peritonitis grave", "dolor abdominal intenso", "infección generalizada", "vientre hinchado", "dolor súbito de abdomen", "sepsis abdominal", "apendicitis complicada", "abdomen muy doloroso", "fiebre alta", "náuseas y vómitos", "urgencia quirúrgica", "dolor en fosa ilíaca derecha", "shock séptico abdominal"]'),
('K35.209', 'Apendicitis aguda con peritonitis generalizada, sin absceso, sin especificación de perforación', 'Sin especificar', '["apendicitis severa", "inflamación total del peritoneo", "dolor abdominal difuso", "apéndice grave", "infección del vientre", "abdomen rígido", "peritonitis aguda", "dolor punzante de estómago", "malestar general intenso", "necesito cirugía urgente", "apendicitis con infección", "dolor constante de panza", "fiebre por apendicitis", "abdomen sensible", "cuadro abdominal agudo"]'),
('K35.210', 'Apendicitis aguda con peritonitis generalizada, sin perforación, con absceso', 'Sin especificar', '["apendicitis con infección localizada", "absceso abdominal", "bola de pus en el abdomen", "apendicitis complicada", "dolor de vientre con fiebre", "peritonitis con absceso", "infección interna", "dolor persistente lado derecho", "inflamación del peritoneo con pus", "colección purulenta abdominal", "masa dolorosa en el abdomen", "apéndice enfermo", "dolor abdominal profundo", "úlcera interna", "foco infeccioso abdominal"]'),
('K35.211', 'Apendicitis aguda con peritonitis generalizada, con perforación y absceso', 'Sin especificar', '["apéndice estallado", "apendicitis reventada con pus", "peritonitis por perforación", "infección abdominal grave", "absceso tras perforación", "dolor insoportable de panza", "urgencia máxima", "sepsis por apendicitis", "vómitos y dolor fuerte", "pus en el abdomen", "apendicitis avanzada", "abdomen muy hinchado", "dolor agudo abdominal", "emergencia hospitalaria", "estado crítico abdominal"]'),
('K35.219', 'Apendicitis aguda con peritonitis generalizada, con absceso, sin especificación de perforación', 'Sin especificar', '["apendicitis con pus", "absceso abdominal por apéndice", "peritonitis infecciosa", "dolor de guata con infección", "dolor de barriga persistente", "masa inflamatoria en abdomen", "apendicitis severa con complicación", "fiebre por absceso", "malestar abdominal profundo", "infección del peritoneo", "foco de pus en el vientre", "dolor que no cede", "apéndice afectado", "abdomen doloroso a la palpación", "urgencia médica abdominal"]'),
('K35.30', 'Apendicitis aguda con peritonitis localizada, sin perforación ni gangrena', 'Sin especificar', '["apendicitis temprana", "dolor bajo lado derecho", "inflamación de apéndice", "apendicitis inicial", "dolor de estómago localizado", "puntada en el costado", "apéndice irritado", "dolor abdominal", "peritonitis focal", "molestia en la ingle derecha", "dolor al caminar", "apendicitis leve", "dolor tipo cólico", "inflamación abdominal", "sensibilidad en fosa ilíaca"]'),
('K35.31', 'Apendicitis aguda con peritonitis y gangrena localizadas, sin perforación', 'Sin especificar', '["apéndice gangrenado", "apendicitis avanzada", "tejido del apéndice muriendo", "infección del apéndice", "dolor intenso de abdomen", "apendicitis con necrosis", "dolor localizado muy fuerte", "peritonitis localizada", "inflamación purulenta", "necrosis apendicular", "dolor que aumenta", "vientre sensible", "apendicitis severa sin perforar", "dolor punzante", "urgencia quirúrgica apendicitis"]'),
('K35.32', 'Apendicitis aguda con perforación, peritonitis localizada y gangrena, sin absceso', 'Sin especificar', '["apéndice reventado", "apéndice necrosado", "perforación de apéndice", "peritonitis localizada", "dolor abdominal agudo", "tejido muerto en el apéndice", "apendicitis grave", "dolor intenso lado derecho", "urgencia por apendicitis", "estallido de apéndice", "infección del abdomen", "dolor súbito y fuerte", "abdomen rígido localizado", "necrosis por apendicitis", "cirugía de emergencia apéndice"]'),
('K35.33', 'Apendicitis aguda con perforación, peritonitis localizada y gangrena, con absceso', 'Sin especificar', '["apendicitis grave con complicaciones", "apéndice con pus y gangrena", "absceso por apendicitis", "perforación de apéndice complicada", "infección grave del abdomen", "apendicitis con necrosis y pus", "dolor de panza insoportable", "urgencia quirúrgica mayor", "peritonitis localizada con pus", "tejido apendicular gangrenado", "dolor abdominal intenso", "masa infecciosa abdominal", "fiebre alta por apendicitis", "dolor punzante en la guata", "emergencia médica"]'),
('K35.80', 'Apendicitis aguda no especificada', 'Sin especificar', '["apendicitis", "dolor de apéndice", "dolor en la boca del estómago y baja", "dolor de guata", "dolor de panza", "dolor de lado derecho", "inflamación abdominal", "apendicitis aguda", "dolor abdominal agudo", "me duele la barriga", "malestar abdominal", "síntomas de apendicitis", "dolor punzante abdominal", "urgencia de panza", "apéndice inflamado"]'),
('K35.890', 'Otros tipos de apendicitis aguda sin perforación ni gangrena', 'Sin especificar', '["apendicitis simple", "inflamación del apéndice", "dolor abdominal", "apendicitis inicial", "dolor en el vientre", "malestar en la ingle", "dolor de panza", "apéndice irritado", "dolor de apéndice", "apendicitis común", "dolor sordo abdominal", "molestia abdominal derecha", "apendicitis no complicada", "fiebre y dolor de barriga", "dolor localizado"]'),
('K35.891', 'Otros tipos de apendicitis aguda sin perforación, con gangrena', 'Sin especificar', '["apendicitis gangrenosa", "tejido apendicular muerto", "apendicitis complicada", "infección de apéndice", "dolor abdominal intenso", "necrosis del apéndice", "apendicitis severa", "inflamación aguda con gangrena", "dolor fuerte lado derecho", "apendicitis crítica", "dolor abdominal persistente", "dolor que no para", "urgencia por apendicitis", "tejido apendicular necrosado", "dolor punzante de estómago"]');
