INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S61.001A', 'Herida abierta no especificada de pulgar derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["corte en el dedo gordo", "tajo en el pulgar", "tajada", "herida en la mano", "sangrado", "cortada", "raspón profundo", "abertura en la piel", "primeros auxilios", "emergencia mano", "sangre", "dedo gordo derecho"]'),
('S61.001D', 'Herida abierta no especificada de pulgar derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["curación de herida", "revisión de corte", "seguimiento médico", "cambio de vendaje", "inflamación", "infección", "pulgar derecho curación", "revisión herida", "seguimiento"]'),
('S61.001S', 'Herida abierta no especificada de pulgar derecho, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz", "queloide", "falta de sensibilidad", "rigidez en el dedo", "dolor crónico", "secuelas de corte", "cicatrización", "molestias en el pulgar"]'),
('S61.002A', 'Herida abierta no especificada de pulgar izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["corte en pulgar izquierdo", "herida en la mano izquierda", "sangrada dedo gordo", "tajada mano", "emergencia mano", "accidente doméstico"]'),
('S61.002D', 'Herida abierta no especificada de pulgar izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento médico", "curación", "cambio de gasas", "revisión de pulgar izquierdo", "control herida"]'),
('S61.002S', 'Herida abierta no especificada de pulgar izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz", "secuela de lesión", "dolor postraumático", "pérdida de fuerza en pulgar izquierdo"]'),
('S61.009A', 'Herida abierta no especificada de pulgar no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["corte en el pulgar", "me corté el dedo gordo", "sangrado en el dedo", "tajada en la mano", "herida de emergencia"]'),
('S61.009D', 'Herida abierta no especificada de pulgar no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["revisión médica", "curación de dedo", "seguimiento de herida", "limpieza de herida"]'),
('S61.009S', 'Herida abierta no especificada de pulgar no especificado, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz en el pulgar", "secuela de cortada", "dolor residual en dedo"]'),
('S61.011A', 'Desgarro sin cuerpo extraño de pulgar derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["piel levantada", "desgarro en la piel", "herida irregular", "corte profundo", "pulgar derecho lastimado", "sangre", "accidente"]'),
('S61.011D', 'Desgarro sin cuerpo extraño de pulgar derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "control de desgarro", "revisión de piel"]'),
('S61.011S', 'Desgarro sin cuerpo extraño de pulgar derecho, sin daños en la uña, secuela', 'Sin especificar', '["cicatrización irregular", "marca en el dedo", "fibrosis"]'),
('S61.012A', 'Desgarro sin cuerpo extraño de pulgar izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["desgarro pulgar izquierdo", "piel desgarrada", "herida abierta", "accidente mano izquierda"]'),
('S61.012D', 'Desgarro sin cuerpo extraño de pulgar izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["limpieza de herida", "curación", "control médico pulgar izquierdo"]'),
('S61.012S', 'Desgarro sin cuerpo extraño de pulgar izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz", "sensibilidad alterada", "rigidez"]'),
('S61.019A', 'Desgarro sin cuerpo extraño de pulgar no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["desgarro en dedo", "piel desgarrada", "herida", "sangrado"]'),
('S61.019D', 'Desgarro sin cuerpo extraño de pulgar no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento de desgarro", "revisión", "curación"]'),
('S61.019S', 'Desgarro sin cuerpo extraño de pulgar no especificado, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz en dedo", "secuelas de desgarro", "dolor"]'),
('S61.021A', 'Desgarro con cuerpo extraño de pulgar derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["astilla en el dedo", "tierra en la herida", "vidrio en el dedo", "cuerpo extraño en pulgar", "desgarro sucio", "infección riesgo"]'),
('S61.021D', 'Desgarro con cuerpo extraño de pulgar derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["retiro de restos", "limpieza profunda", "control de infección", "revisión"]'),
('S61.021S', 'Desgarro con cuerpo extraño de pulgar derecho, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz profunda", "infección persistente", "dolor crónico"]'),
('S61.022A', 'Desgarro con cuerpo extraño de pulgar izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["cuerpo extraño en pulgar izquierdo", "basura en el corte", "desgarro con residuos"]'),
('S61.022D', 'Desgarro con cuerpo extraño de pulgar izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["curación", "revisión de cuerpo extraño", "control"]'),
('S61.022S', 'Desgarro con cuerpo extraño de pulgar izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz", "dolor"]'),
('S61.029A', 'Desgarro con cuerpo extraño de pulgar no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["cuerpo extraño en dedo", "herida con suciedad", "desgarro en el pulgar"]'),
('S61.029D', 'Desgarro con cuerpo extraño de pulgar no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["limpieza", "seguimiento"]'),
('S61.029S', 'Desgarro con cuerpo extraño de pulgar no especificado, sin daños en la uña, secuela', 'Sin especificar', '["secuela", "cicatriz"]'),
('S61.031A', 'Herida punzante sin cuerpo extraño de pulgar derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["pinchazo en el dedo", "aguja en el dedo", "clavo en el pulgar", "herida punzante", "sangre", "dolor"]'),
('S61.031D', 'Herida punzante sin cuerpo extraño de pulgar derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["curación", "revisión de pinchazo", "control de infección"]'),
('S61.031S', 'Herida punzante sin cuerpo extraño de pulgar derecho, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz interna", "dolor al tacto", "sensibilidad"]'),
('S61.032A', 'Herida punzante sin cuerpo extraño de pulgar izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["pinchazo pulgar izquierdo", "aguja", "punzada en la mano"]'),
('S61.032D', 'Herida punzante sin cuerpo extraño de pulgar izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["curación", "control"]'),
('S61.032S', 'Herida punzante sin cuerpo extraño de pulgar izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["dolor crónico", "sensibilidad"]'),
('S61.039A', 'Herida punzante sin cuerpo extraño de pulgar no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["pinchazo en dedo", "herida por objeto punzante"]'),
('S61.039D', 'Herida punzante sin cuerpo extraño de pulgar no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["curación", "control"]'),
('S61.039S', 'Herida punzante sin cuerpo extraño de pulgar no especificado, sin daños en la uña, secuela', 'Sin especificar', '["dolor", "cicatriz"]'),
('S61.041A', 'Herida punzante con cuerpo extraño de pulgar derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["astilla clavada", "clavo en el pulgar", "objeto clavado", "punzada con objeto", "emergencia pulgar"]'),
('S61.041D', 'Herida punzante con cuerpo extraño de pulgar derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["extracción de objeto", "limpieza", "seguimiento"]'),
('S61.041S', 'Herida punzante con cuerpo extraño de pulgar derecho, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz", "dolor", "infección tardía"]'),
('S61.042A', 'Herida punzante con cuerpo extraño de pulgar izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["pinchazo con objeto", "astilla en pulgar izquierdo"]'),
('S61.042D', 'Herida punzante con cuerpo extraño de pulgar izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["curación", "control"]'),
('S61.042S', 'Herida punzante con cuerpo extraño de pulgar izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz", "dolor"]'),
('S61.049A', 'Herida punzante con cuerpo extraño de pulgar no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["objeto clavado en dedo", "pinchazo"]'),
('S61.049D', 'Herida punzante con cuerpo extraño de pulgar no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento"]'),
('S61.049S', 'Herida punzante con cuerpo extraño de pulgar no especificado, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz", "dolor"]'),
('S61.051A', 'Mordedura abierta de pulgar derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["mordida de perro", "mordida de gato", "mordedura humana", "mordida en el dedo", "pulgar derecho mordido", "herida por dientes"]'),
('S61.051D', 'Mordedura abierta de pulgar derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["prevención de rabia", "antibióticos", "limpieza de mordida", "curación"]'),
('S61.051S', 'Mordedura abierta de pulgar derecho, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz de mordida", "infección", "pérdida de sensibilidad"]'),
('S61.052A', 'Mordedura abierta de pulgar izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["mordedura en pulgar izquierdo", "me mordió un animal", "herida por mordida"]'),
('S61.052D', 'Mordedura abierta de pulgar izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["control médico", "curación", "antibióticos"]'),
('S61.052S', 'Mordedura abierta de pulgar izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz", "dolor"]'),
('S61.059A', 'Mordedura abierta de pulgar no especificado sin daño en la uña, contacto inicial', 'Sin especificar', '["mordida en el dedo", "herida por mordida"]'),
('S61.059D', 'Mordedura abierta de pulgar no especificado sin daño en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento", "curación"]'),
('S61.059S', 'Mordedura abierta de pulgar no especificado sin daño en la uña, secuela', 'Sin especificar', '["cicatriz", "secuela"]');
