INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('E27.0', 'Otros tipos de hiperactividad corticosuprarrenal', 'Sin especificar', '["exceso de cortisol", "síndrome de cushing", "hiperactividad suprarrenal", "hinchazón de cara", "cara de luna llena", "giba de búfalo", "exceso de hormonas", "hipercortisolismo", "problemas de glándulas", "estrías rojas", "debilidad muscular", "aumento de peso abdominal", "hormonas alteradas", "fallo endocrino", "hiperfunción adrenal"]'),
('E27.1', 'Insuficiencia suprarrenal primaria', 'Sin especificar', '["enfermedad de addison", "falta de cortisol", "cansancio extremo", "fatiga crónica", "piel bronceada", "manchas en la piel", "bajada de presión", "mareos frecuentes", "desgano", "hipoadrenalismo", "falta de energía", "debilitamiento general", "hipotensión", "pérdida de peso", "desequilibrio endocrino"]'),
('E27.2', 'Crisis addisoniana', 'Sin especificar', '["crisis adrenal", "shock suprarrenal", "colapso endocrino", "emergencia addison", "descompensación adrenal", "bajón de presión severo", "desmayo", "insuficiencia aguda", "crisis de cortisol", "dolor abdominal intenso", "vómitos graves", "fiebre alta", "confusión mental", "shock hipovolémico", "falla glandular aguda"]'),
('E27.3', 'Insuficiencia corticosuprarrenal inducida por fármacos', 'Sin especificar', '["insuficiencia por esteroides", "daño por cortisona", "efecto secundario de corticoides", "supresión adrenal por fármacos", "exceso de dexametasona", "problemas por pastillas para inflamación", "síndrome de abstinencia a corticoides", "bloqueo adrenal", "efecto rebote medicamentos", "desajuste hormonal medicamentoso", "adicción a corticoides", "fallo por tratamiento", "toxicidad hormonal"]'),
('E27.40', 'Insuficiencia corticosuprarrenal no especificada', 'Sin especificar', '["fallo suprarrenal", "problemas de glándulas arriba de los riñones", "insuficiencia adrenal sin diagnosticar", "cansancio raro", "debilidad generalizada", "desequilibrio de sales", "deshidratación inexplicada", "falta de hormonas del estrés", "malestar endocrino", "bajón hormonal", "astenia", "hipofunción suprarrenal"]'),
('E27.49', 'Otros tipos de insuficiencia corticosuprarrenal', 'Sin especificar', '["fallo endocrino secundario", "déficit hormonal adrenal", "problemas en glándulas suprarrenales", "falta de aldosterona", "insuficiencia adrenal leve", "descontrol de glándulas", "anomalía suprarrenal", "problema hormonal crónico", "debilidad constante", "fatiga suprarrenal", "hiposecreción adrenal"]'),
('E27.5', 'Hiperfunción de médula suprarrenal', 'Sin especificar', '["feocromocitoma", "taquicardia inexplicable", "sudoración excesiva", "dolor de cabeza pulsátil", "presión arterial alta", "crisis hipertensivas", "nerviosismo extremo", "palpitaciones", "ansiedad súbita", "subidón de adrenalina", "exceso de catecolaminas", "ataques de pánico", "temblores", "hiperactividad hormonal", "fallo en la médula adrenal"]'),
('E27.8', 'Otros trastornos específicos de glándula suprarrenal', 'Sin especificar', '["tumor suprarrenal", "quiste en glándula", "hiperplasia suprarrenal", "nódulo adrenal", "trastorno endocrino raro", "problemas hormonales", "alteración suprarrenal", "dolor en la zona lumbar alta", "desequilibrio electrolítico", "masas adrenales", "disfunción de glándulas", "patología suprarrenal"]'),
('E27.9', 'Trastorno de glándula suprarrenal, no especificado', 'Sin especificar', '["problema en las glándulas arriba de los riñones", "enfermedad adrenal sin especificar", "mal funcionamiento glandular", "dolor abdominal difuso", "desajuste hormonal", "problemas de riñones y glándulas", "síntomas endocrinos", "chequeo de glándulas", "nódulo en la glándula", "anomalía endocrina", "desorden hormonal"]');
