INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('G51.0', 'Parálisis de Bell', 'Sin especificar', '["parálisis facial", "cara chueca", "cara torcida", "parálisis de medio lado", "se me torció la boca", "cara de lado", "parálisis periférica", "pérdida de fuerza en la cara", "parálisis facial a frigore", "cara paralizada", "se me cayó la cara", "adormecimiento facial", "parálisis del nervio facial", "asimetría facial"]'),
('G51.1', 'Ganglionitis geniculada', 'Sin especificar', '["síndrome de Ramsay Hunt", "herpes zóster facial", "dolor de oído y cara", "vesículas en el oído", "fuegos en el oído", "herpes en la cara", "infección del nervio facial", "dolor ótico severo", "parálisis facial por herpes", "ampollas en el conducto auditivo", "ganglionitis", "dolor de nervio en la cara", "zooster del ganglio geniculado"]'),
('G51.2', 'Síndrome de Melkersson', 'Sin especificar', '["síndrome de Melkersson-Rosenthal", "hinchazón de labios", "labios gruesos", "edema facial recurrente", "labios inflamados", "lengua fisurada", "lengua escrotal", "inflamación de la cara", "parálisis facial recurrente", "hinchazón de boca", "labio superior hinchado", "trastorno granulomatoso facial"]'),
('G51.31', 'Espasmo hemifacial clónico, derecho', 'Sin especificar', '["ojo derecho saltando", "tic en la cara derecha", "brinco en el ojo derecho", "contracción facial derecha", "cara derecha se mueve sola", "temblor en la mejilla derecha", "movimientos involuntarios cara derecha", "espasmo en el ojo derecho", "me salta el ojo derecho", "tic nervioso cara derecha", "espasmo facial derecho", "tembladera en el lado derecho"]'),
('G51.32', 'Espasmo hemifacial clónico, izquierdo', 'Sin especificar', '["ojo izquierdo saltando", "tic en la cara izquierda", "brinco en el ojo izquierdo", "contracción facial izquierda", "cara izquierda se mueve sola", "temblor en la mejilla izquierda", "movimientos involuntarios cara izquierda", "espasmo en el ojo izquierdo", "me salta el ojo izquierdo", "tic nervioso cara izquierda", "espasmo facial izquierdo", "tembladera en el lado izquierdo"]'),
('G51.33', 'Espasmo hemifacial clónico, bilateral', 'Sin especificar', '["tic en ambos ojos", "me saltan los ojos", "espasmos en toda la cara", "cara que se mueve sola", "tics faciales en ambos lados", "brincos en los ojos", "contracción de los dos lados de la cara", "cara saltarina", "temblor facial constante", "movimientos involuntarios en ambos lados de la cara", "espasmos faciales bilaterales", "tic nervioso bilateral"]'),
('G51.39', 'Espasmo hemifacial clónico, no especificado', 'Sin especificar', '["tic en la cara", "me salta el ojo", "temblor en la cara", "espasmo facial", "cara que brinca", "contracciones involuntarias cara", "tic nervioso", "movimientos raros en la cara", "parpadeo involuntario constante", "espasmo hemifacial", "tic de ojo", "tembladera facial"]'),
('G51.4', 'Mioquimia facial', 'Sin especificar', '["temblor en el párpado", "fasciculaciones faciales", "culebrilla en la cara", "tembladera muscular en la cara", "movimiento ondulatorio facial", "músculos de la cara vibrando", "mioquimia", "espasmo muscular sutil", "temblor bajo la piel cara", "contracciones musculares rápidas cara", "vibración muscular facial"]'),
('G51.8', 'Otros trastornos del nervio facial', 'Sin especificar', '["problemas de nervios en la cara", "dolor de nervio facial", "afectación nervio facial", "neuropatía facial", "dolor en la mejilla", "pinchazos en la cara", "molestias en la cara", "hormigueo facial", "disfunción nervio facial", "daño en nervio de la cara", "problemas de sensibilidad en la cara"]'),
('G51.9', 'Trastorno del nervio facial, no especificado', 'Sin especificar', '["enfermedad del nervio facial", "problema cara", "dolor facial raro", "disfunción nerviosa cara", "neurología facial", "siento la cara rara", "problema en nervio de la cabeza", "trastorno facial", "afectación nerviosa cara", "dolor o molestia en la cara", "síntomas en la cara", "nervio facial dañado"]');
