INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q31.0', 'Membrana laríngea', 'Sin especificar', '["membrana en la garganta", "tejido en las cuerdas vocales", "estridor al nacer", "llanto débil bebé", "dificultad para respirar neonato", "obstrucción laríngea congénita", "problemas de voz congénitos", "malformación de laringe", "cuerdas vocales pegadas", "membrana glótica", "atresia laríngea parcial", "ruido al respirar bebé", "disfonía de nacimiento", "anomalía laringea", "falta de aire bebé", "tejido extra en la laringe"]'),
('Q31.1', 'Estenosis subglótica congénita', 'Sin especificar', '["estrechez en la garganta", "vías respiratorias estrechas bebé", "subglotis estrecha", "estridor congénito", "dificultad para respirar recién nacido", "laringe pequeña", "obstrucción de la tráquea superior", "ruidos al respirar", "garganta cerrada", "problemas para tragar y respirar", "cianosis bebé", "espasmo laringeo congénito", "estrechamiento de la vía aérea", "falta de aire al llorar", "anomalía subglótica", "obstrucción al paso del aire"]'),
('Q31.2', 'Hipoplasia laríngea', 'Sin especificar', '["laringe pequeña", "laringe subdesarrollada", "garganta diminuta", "hipoplasia de cuerdas vocales", "problemas de crecimiento laringeo", "inmadurez de la laringe", "vía aérea pequeña", "llanto silencioso", "dificultad para ventilar", "laringe hipoplásica", "anomalía en la caja de voz", "desarrollo incompleto de la laringe", "problemas respiratorios neonatales", "estrechez laríngea", "falla al respirar bebé"]'),
('Q31.3', 'Laringocele', 'Sin especificar', '["quiste en la laringe", "bolsa de aire en la garganta", "inflamación del cuello", "abultamiento en la garganta", "masa en el cuello que se infla", "laringocele interno", "laringocele externo", "aire en los ventrículos laringeos", "bulto al hacer esfuerzo", "dificultad para tragar", "ronquera persistente", "sensación de cuerpo extraño en garganta", "saco lleno de aire garganta", "hernia de laringe", "masa cervical"]'),
('Q31.5', 'Laringomalacia congénita', 'Sin especificar', '["laringe blanda", "ruido al respirar bebé", "estridor inspiratorio", "colapso laríngeo al respirar", "bebé hace ruiditos al respirar", "cuerdas vocales flácidas", "laringe inmadura", "sonido de ronquido en recién nacido", "dificultad respiratoria al dormir", "techo de la laringe blando", "estridor congénito benigno", "garganta colapsable", "hipotonía laríngea", "ruido tipo silbido al respirar", "molestias respiratorias en lactantes"]'),
('Q31.8', 'Otras malformaciones congénitas de laringe', 'Sin especificar', '["defectos de nacimiento laringe", "anomalías de la garganta bebé", "problemas congénitos voz", "malformación laringe infante", "defecto estructural garganta", "quiste laringeo congénito", "fístula laringea", "hendidura laringea", "anomalía morfológica laríngea", "defecto de la caja de voz", "malformación congénita no especificada garganta", "problemas laringeos de cuna", "anormalidad al nacer en la laringe", "obstrucción congénita laringea", "deformidad laringea congénita"]'),
('Q31.9', 'Malformación congénita de la laringe, no especificada', 'Sin especificar', '["problema en la garganta al nacer", "defecto congénito desconocido garganta", "anomalía laringea congénita", "no saben qué tiene en la laringe", "problema de laringe desde el nacimiento", "malformación no especificada laringe", "dificultad respiratoria congénita", "defecto laringeo del bebé", "anormalidad laringea", "problemas para respirar o tragar bebé", "caja de voz deforme", "condición laringea de nacimiento", "estridor o llanto anormal bebé", "defecto en la formación de la garganta", "enfermedad congénita laringea"]');
