INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('F60.0', 'Trastorno de personalidad paranoide', 'Sin especificar', '["paranoia", "desconfiado", "manía persecutoria", "siempre cree que le hacen daño", "pensar que todos le quieren hacer algo", "alguien me persigue", "ataques de desconfianza", "celos extremos", "pensamientos conspirativos", "creer que todos conspiran", "desconfianza patológica", "suspicacia", "alerta constante", "creer que me vigilan", "paranoico"]'),
('F60.1', 'Trastorno esquizoide de personalidad', 'Sin especificar', '["aislamiento social", "falta de interés social", "ser solitario", "prefiero estar solo", "frialdad emocional", "indiferencia a los demás", "sin amigos", "distante", "desapego emocional", "introvertido extremo", "falta de placer en actividades", "no siento nada por los demás", "bicho raro", "ermitaño", "poco sociable"]'),
('F60.2', 'Trastorno de personalidad antisocial', 'Sin especificar', '["psicópata", "sociópata", "sin remordimientos", "no respeto las reglas", "manipulador", "mentiroso patológico", "problemas con la ley", "impulsivo", "falta de empatía", "cruel", "romper normas", "delincuencia", "no tengo conciencia", "poco empático", "violento"]'),
('F60.3', 'Trastorno límite de personalidad', 'Sin especificar', '["borderline", "inestabilidad emocional", "cambios de humor bruscos", "tengo altibajos", "miedo al abandono", "autolesiones", "vacío emocional", "crisis de llanto", "impulsividad", "picos emocionales", "personalidad inestable", "todo o nada", "relaciones tormentosas", "me siento vacío", "drama constante"]'),
('F60.4', 'Trastorno de personalidad histriónica', 'Sin especificar', '["drama queen", "llamativo", "exhibicionista", "necesito ser el centro de atención", "teatrero", "exagerado", "emociones superficiales", "coquetería constante", "seductor", "siempre quiero que me miren", "muy dramático", "siempre actuando", "insustancial", "atención excesiva", "vulgar"]'),
('F60.5', 'Trastorno de personalidad obsesivo-compulsivo', 'Sin especificar', '["perfeccionista", "orden obsesivo", "maniático", "limpieza extrema", "controlador", "rígido", "cuadrado", "todo en su sitio", "obsesión con el orden", "inflexible", "necesidad de control", "meticuloso al extremo", "reglas estrictas", "acumulador", "perfección absoluta"]'),
('F60.6', 'Trastorno de personalidad evitativa', 'Sin especificar', '["tímido patológico", "miedo al rechazo", "inseguridad extrema", "vergüenza", "complejo de inferioridad", "evitar gente", "me da miedo hablar con otros", "soy un cobarde", "evitación social", "aislamiento por miedo", "baja autoestima", "sensible a la crítica", "siempre me critican", "poco valorado", "me escondo de la gente"]'),
('F60.7', 'Trastorno de personalidad dependiente', 'Sin especificar', '["necesito a alguien", "inseguro", "no puedo decidir solo", "sumiso", "pegajoso", "miedo a estar solo", "necesito aprobación", "siempre con alguien", "dependencia emocional", "incapaz de tomar decisiones", "esclavo de otro", "ayúdame a decidir", "soy una sombra", "incapaz de cuidarme", "falta de autonomía"]'),
('F60.81', 'Trastorno de personalidad narcisista', 'Sin especificar', '["narcisista", "creído", "ego elevado", "egocéntrico", "el mejor de todos", "necesito admiración", "soberbio", "creerse superior", "fantasia de éxito", "poco empático", "falta de humildad", "altanero", "presumido", "yo primero", "arrogancia"]'),
('F60.89', 'Otros tipos de trastornos específicos de personalidad', 'Sin especificar', '["problemas de conducta", "alteraciones del carácter", "desajustes de personalidad", "mi forma de ser no es normal", "problemas de personalidad no clasificados", "trastornos atípicos", "comportamiento extraño", "cambios de personalidad", "problemas psiquiátricos", "anormalidad del carácter", "conflictos internos", "inestabilidad de carácter", "disfunción social", "rareza conductual", "inadaptación"]'),
('F60.9', 'Trastorno de personalidad, no especificado', 'Sin especificar', '["locura", "problemas mentales", "mi forma de ser me causa problemas", "trastorno psiquiátrico", "estoy raro", "no me entiendo", "problemas con mi forma de actuar", "diagnóstico de personalidad", "trastorno mental sin nombre", "conducta desadaptativa", "problemas emocionales", "crisis de identidad", "comportamiento diferente", "desorden mental", "necesito ayuda psicológica"]');
