INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B45.0', 'Criptococosis pulmonar', 'Sin especificar', '["hongos en los pulmones", "infección fúngica pulmonar", "criptococo en el pecho", "neumonía por hongos", "tos con hongos", "micosis respiratoria", "dificultad para respirar por hongos", "dolor en los pulmones por criptococo", "infección pulmonar grave", "hongos en el sistema respiratorio", "cuerpo cortado y tos", "flemas con hongos", "infección por excremento de paloma", "neumopatía fúngica", "micosis pulmonar profunda"]'),
('B45.1', 'Criptococosis cerebral', 'Sin especificar', '["hongos en el cerebro", "meningitis por criptococo", "infección cerebral por hongos", "dolor de cabeza por hongos", "inflamación de las meninges", "micosis del sistema nervioso central", "criptococo en la cabeza", "confusión mental por hongos", "fiebre y dolor de cabeza intenso", "problemas neurológicos por hongos", "meningitis fúngica", "presión en la cabeza por micosis", "infección del líquido cefalorraquídeo", "cerebritis fúngica", "dolor de cabeza que no cede"]'),
('B45.2', 'Criptococosis cutánea', 'Sin especificar', '["hongos en la piel", "granos por criptococo", "úlceras en la piel por hongos", "llagas que no curan", "micosis cutánea profunda", "lesiones en la piel por infección", "bolitas en la piel", "infección cutánea por criptococo", "heridas con pus en la piel", "manchas en la piel por hongos", "bultos debajo de la piel", "enfermedad de la piel por hongos", "infección dermatológica fúngica", "pústulas por hongos", "cáscaras en la piel por infección"]'),
('B45.3', 'Criptococosis ósea', 'Sin especificar', '["hongos en los huesos", "infección en el hueso", "dolor de huesos por hongos", "osteomielitis fúngica", "criptococo en la estructura ósea", "huesos inflamados", "dolor profundo en las articulaciones", "micosis ósea", "infección profunda en el esqueleto", "dolor en el esqueleto por hongos", "lesiones en los huesos", "inflamación de los huesos", "criptococosis de los huesos", "dolor articular crónico", "debilidad ósea por infección"]'),
('B45.7', 'Criptococosis diseminada', 'Sin especificar', '["infección por hongos en todo el cuerpo", "criptococosis generalizada", "hongos en la sangre", "sepsis por hongos", "micosis sistémica", "infección diseminada por criptococo", "hongos en varios órganos", "infección generalizada grave", "micosis grave", "el hongo se regó por todo el cuerpo", "infección sistémica severa", "compromiso multiorgánico por hongos", "enfermedad fúngica generalizada", "criptococo en el sistema sanguíneo", "fungaemia"]'),
('B45.8', 'Otras formas de criptococosis', 'Sin especificar', '["criptococosis atípica", "otras infecciones por criptococo", "micosis extraña", "infección por hongos en otros órganos", "criptococo diseminado en órganos", "complicaciones por criptococo", "manifestaciones raras de criptococosis", "infección fúngica poco común", "criptococosis de localización rara", "hongos en el cuerpo no especificados", "variantes de la criptococosis", "infección sistémica inusual", "hongos en órganos internos", "criptococosis en lugares raros", "enfermedad fúngica poco frecuente"]'),
('B45.9', 'Criptococosis, no especificada', 'Sin especificar', '["criptococosis", "infección por criptococo", "hongos", "micosis", "tengo hongos en el cuerpo", "enfermedad por hongo", "infección fúngica", "cryptococcus", "infección por levaduras", "micosis sistémica sin definir", "enfermedad por excremento de pájaro", "problemas por hongos", "infección por levadura oportunista", "hongos en el organismo", "diagnóstico de criptococosis"]');
