INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J10.00', 'Gripe debida a otros tipos de virus de la gripe identificados con neumonía de tipo no especificada', 'Sin especificar', '["gripe", "gripa", "influenza", "neumonía", "pulmonía", "pecho congestionado", "gripe fuerte", "infección respiratoria", "tos con flema", "fiebre alta", "escalofríos", "dolor de cuerpo", "catarro fuerte", "malestar general", "ahogo", "dificultad para respirar", "gripe mal curada"]'),
('J10.01', 'Gripe debida a otros tipos de virus de la gripe identificados con neumonía debida al mismo tipo de virus de la gripe identificado', 'Sin especificar', '["neumonía viral", "gripa con pulmonía", "infección en los pulmones", "gripe complicada", "pecho cerrado", "influenza grave", "tos seca persistente", "dolor al respirar", "dificultad respiratoria", "fiebre persistente", "gripe con neumonía", "estoy muy mal del pecho", "pulmones comprometidos", "fatiga extrema", "esputo", "sibilancias"]'),
('J10.08', 'Gripe debida a otros tipos de virus de la gripe identificados con otro tipo de neumonía especificado', 'Sin especificar', '["neumonía bacteriana post-gripe", "complicación pulmonar", "gripe severa", "influenza complicada", "tos con sangre", "dolor torácico", "dificultad para tomar aire", "fiebre que no baja", "infección pulmonar secundaria", "debilitamiento pulmonar", "pulmonía infecciosa", "flemas verdes", "silbido al respirar", "opresión en el pecho", "cansancio extremo"]'),
('J10.1', 'Gripe debida a otros tipos de virus de la gripe identificados con otras manifestaciones respiratorias', 'Sin especificar', '["gripe común", "gripa fuerte", "catarro", "moquera", "nariz tapada", "tos constante", "dolor de garganta", "influenza estacional", "rinitis viral", "faringitis por gripe", "voz ronca", "picazón en la garganta", "estornudos", "congestión nasal", "dolor al tragar", "inflamación de vías aéreas"]'),
('J10.2', 'Gripe debida a otros tipos de virus de la gripe identificados con manifestaciones gastrointestinales', 'Sin especificar', '["gripe estomacal", "gripa con diarrea", "gripe intestinal", "vómito y gripe", "dolor de panza", "dolor de guata", "cagadera", "diarrea por influenza", "náuseas", "malestar estomacal", "cólicos", "barriga suelta", "descomposición estomacal", "pujido", "deshidratación por gripe", "gripe del estómago"]'),
('J10.81', 'Gripe debida a otros tipos de virus de la gripe con encefalopatía', 'Sin especificar', '["gripe con complicaciones cerebrales", "confusión por gripe", "influenza con encefalitis", "desorientación", "gripe severa con delirio", "convulsiones por gripe", "cefalea intensa por gripe", "somnolencia extrema", "fiebre y desvarío", "afectación neurológica", "gripe grave", "inflamación cerebral", "alteración del estado mental", "mareos fuertes", "letargo"]'),
('J10.82', 'Gripe debida a otros tipos de virus de la gripe con miocarditis', 'Sin especificar', '["gripe con problemas al corazón", "dolor en el pecho", "palpitaciones por gripe", "taquicardia por infección", "inflamación del corazón", "gripe con falla cardíaca", "arritmia", "influenza y corazón", "opresión cardíaca", "fatiga al caminar", "falta de aire al esfuerzo", "dolor precordial", "latidos irregulares", "debilitamiento cardíaco", "complicación al corazón"]'),
('J10.83', 'Gripe debida a otros tipos de virus de la gripe con otitis media', 'Sin especificar', '["gripe con dolor de oído", "oído tapado", "infección de oído por gripe", "otitis por catarro", "dolor en el conducto auditivo", "zumbido de oídos", "inflamación de oído", "oído con pus", "gripe y dolor de oídos", "pérdida de audición momentánea", "presión en el oído", "gripe complicada con oídos", "punzadas en el oído"]'),
('J10.89', 'Gripe debida a otros virus influenza con otras manifestaciones', 'Sin especificar', '["gripe atípica", "síntomas raros de gripe", "gripe con dolores musculares", "mialgia", "fiebre por influenza", "postración", "gripe fuerte generalizada", "influenza con otras molestias", "dolor de articulaciones", "gripe sistémica", "malestar corporal", "abatimiento", "influenza extraña", "dolor de huesos por gripe"]');
