INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('G91.0', 'Hidrocefalia comunicante', 'Sin especificar', '["agua en el cerebro", "cabeza grande", "hidrocefalia", "líquido cefalorraquídeo acumulado", "presión intracraneal", "dolor de cabeza", "vómitos", "visión borrosa", "dificultad para caminar", "demencia", "incontinencia", "aumento de volumen craneal", "macrocefalia", "hipertensión intracraneal", "líquido en la cabeza"]'),
('G91.1', 'Hidrocefalia obstructiva', 'Sin especificar', '["hidrocefalia obstructiva", "obstrucción líquido cerebral", "agua en la cabeza", "bloqueo de líquido cefalorraquídeo", "ventrículos dilatados", "hidrocefalia no comunicante", "dolor de cabeza intenso", "náuseas", "somnolencia", "letargo", "pérdida de equilibrio", "convulsiones", "presión en el cráneo", "cabeza pesada", "hidrocefalia mecánica"]'),
('G91.2', 'Hidrocefalia normotensiva (idiopática)', 'Sin especificar', '["hidrocefalia del adulto mayor", "tríada de hakim", "pérdida de memoria", "dificultad para caminar", "incontinencia urinaria", "deterioro cognitivo", "paso errático", "lentitud mental", "hidrocefalia de presión normal", "demencia reversible", "problemas de marcha", "torpeza motora", "olvidos", "hidrocefalia idiopática", "problemas al orinar"]'),
('G91.3', 'Hidrocefalia postraumática, no especificada', 'Sin especificar', '["hidrocefalia por golpe", "líquido tras accidente", "secuela de traumatismo craneal", "agua en el cerebro por golpe", "trauma craneoencefálico", "secuelas de TCe", "dolor tras el choque", "mareos tras golpe", "presión post-accidente", "hidrocefalia adquirida", "edema cerebral crónico", "drenaje de líquido post-trauma", "complicación post-accidente", "daño cerebral postraumático"]'),
('G91.4', 'Hidrocefalia en enfermedades clasificadas bajo otro concepto', 'Sin especificar', '["hidrocefalia secundaria", "líquido cerebral por infección", "complicación de meningitis", "tumor cerebral", "secuela de infección", "hidrocefalia por enfermedad base", "problema neurológico asociado", "acumulación de líquido", "inflamación cerebral", "complicación de enfermedad crónica", "hidrocefalia parasitaria", "hidrocefalia tumoral", "causa externa de hidrocefalia", "hidrocefalia por proceso sistémico"]'),
('G91.8', 'Otros tipos de hidrocefalia', 'Sin especificar', '["hidrocefalia mixta", "hidrocefalia ex vacuo", "dilatación ventricular", "líquido acumulado en cráneo", "otros trastornos del LCR", "hidrocefalia externa", "hidrocefalia interna", "problemas de reabsorción LCR", "aumento de líquido cerebroespinal", "presión excesiva cabeza", "hidrocefalia poco común", "desequilibrio de LCR", "trastorno neurológico", "hidrocefalia atípica"]'),
('G91.9', 'Hidrocefalia, no especificada', 'Sin especificar', '["hidrocefalia", "agua en la cabeza", "exceso de líquido cerebral", "cabeza gigante", "presión en el cerebro", "macrocefalia", "dolor de cabeza crónico", "líquido cefalorraquídeo", "ventrículos grandes", "problema de cabeza", "hidropesía cerebral", "edema cerebral", "líquido en el cráneo", "malformación cerebral", "hidrocefalia inespecífica"]');
