INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J96.00', 'Insuficiencia respiratoria aguda no especificada si con hipoxia o con hipercapnia', 'Sin especificar', '["falta de aire súbita", "no me entra el aire", "ahogo repentino", "asfixia aguda", "dificultad para respirar de pronto", "hambre de aire", "pecho cerrado", "pulmones no funcionan", "fatiga respiratoria", "aire trabado", "disnea súbita", "insuficiencia pulmonar rápida", "pecho apretado", "falta de oxígeno", "crisis respiratoria"]'),
('J96.01', 'Insuficiencia respiratoria aguda con hipoxia', 'Sin especificar', '["falta de oxígeno en sangre", "ahogo por falta de aire", "labios morados", "cianosis", "saturación baja", "no oxigena bien", "asfixia", "hipoxemia aguda", "se me va el aire", "hambre de aire", "poca oxigenación", "desaturación", "pecho cerrado urgente", "oxígeno bajo", "falla pulmonar por hipoxia"]'),
('J96.02', 'Insuficiencia respiratoria aguda con hipercapnia', 'Sin especificar', '["exceso de dióxido de carbono", "acidosis respiratoria", "retención de gas", "dificultad respiratoria con confusión", "ahogo con malestar", "pulmones tapados", "hipercapnia aguda", "fallo al soltar aire", "fatiga de músculos respiratorios", "dificultad para exhalar", "sed de aire aguda", "intoxicación por CO2", "pulmón sin ventilación"]'),
('J96.10', 'Insuficiencia respiratoria crónica no especificada si con hipoxia o con hipercapnia', 'Sin especificar', '["problema respiratorio de largo tiempo", "falta de aire constante", "EPOC", "pulmones cansados", "siempre cansado al respirar", "respiración crónica difícil", "ahogo permanente", "falta de aire al caminar", "enfermedad pulmonar vieja", "pecho siempre cerrado", "hambre de aire crónica", "no lleno los pulmones", "disnea de esfuerzo prolongada"]'),
('J96.11', 'Insuficiencia respiratoria crónica con hipoxia', 'Sin especificar', '["oxígeno crónicamente bajo", "necesito tanque de oxígeno", "hipoxemia de largo plazo", "saturación baja constante", "labios azulados crónicos", "pulmón insuficiente", "falta de aire crónica", "disnea hipóxica", "cansancio al menor esfuerzo", "falla respiratoria continua", "oxigenación deficiente", "insuficiencia pulmonar crónica"]'),
('J96.12', 'Insuficiencia respiratoria crónica con hipercapnia', 'Sin especificar', '["retención de CO2 crónica", "pulmones que no limpian el aire", "hipercapnia estable", "respiración difícil y constante", "falla de ventilación", "tos crónica con ahogo", "cuerpo saturado de gas", "insuficiencia pulmonar por retención", "dificultad para respirar prolongada", "acidosis crónica", "ventilación deficiente crónica"]'),
('J96.20', 'Insuficiencia respiratoria aguda y crónica no especificada si con hipoxia o con hipercapnia', 'Sin especificar', '["descompensación respiratoria", "crisis en enfermedad pulmonar", "empeoramiento del asma o EPOC", "pulmón colapsado crónico", "ahogo sobreañadido", "falla pulmonar mixta", "agudización de insuficiencia crónica", "crisis de asfixia", "problemas respiratorios acumulados", "pulmones muy dañados", "no puedo respirar de repente siendo enfermo crónico"]'),
('J96.21', 'Insuficiencia respiratoria aguda y crónica con hipoxia', 'Sin especificar', '["descompensación por falta de oxígeno", "crisis de hipoxemia", "bajada drástica de oxígeno", "paciente crónico sin aire", "falla pulmonar grave", "oxigenación crítica", "ahogo repentino en paciente con EPOC", "falta de aire aguda y crónica", "crisis de desaturación", "pecho colapsado", "necesito urgencias por falta de oxígeno"]'),
('J96.22', 'Insuficiencia respiratoria aguda y crónica con hipercapnia', 'Sin especificar', '["crisis de retención de gas", "agudización con CO2 alto", "descompensación respiratoria grave", "falla pulmonar con confusión", "hipercapnia descompensada", "emergencia respiratoria en crónico", "pulmón sin capacidad de ventilación", "retención de gas aguda", "falla respiratoria tipo 2", "crisis de hipercapnia"]'),
('J96.90', 'Insuficiencia respiratoria no especificada, sin especificar si con hipoxia o con hipercapnia', 'Sin especificar', '["problema pulmonar", "no puedo respirar", "ahogo", "falta de aire", "dificultad para respirar", "pecho cerrado", "pulmones fallando", "tengo que respirar con esfuerzo", "fatiga al respirar", "disnea", "falta de aliento", "ahogos", "se me cierra el pecho", "aire corto", "me falta el aire", "hambre de aire"]'),
('J96.91', 'Insuficiencia respiratoria no especificada, con hipoxia', 'Sin especificar', '["me falta oxígeno", "no me llega oxígeno", "saturación baja", "ahogo con desoxigenación", "cianosis", "dedos morados por falta de aire", "asfixia leve", "sangre sin oxígeno", "problema respiratorio con hipoxia", "pulmones no oxigenan", "necesito oxígeno", "hipoxemia"]'),
('J96.92', 'Insuficiencia respiratoria no especificada, con hipercapnia', 'Sin especificar', '["tengo exceso de CO2", "pulmones que no ventilan", "ahogo por retención de gas", "hipercapnia", "problema respiratorio con retención de aire", "dificultad respiratoria con somnolencia", "falla ventilatoria", "gases arteriales alterados", "pulmón bloqueado", "mala salida de aire"]');
