INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C93.00', 'Leucemia monoblástica/monocítica aguda, sin haber alcanzado remisión', 'Sin especificar', '["leucemia aguda", "cáncer en la sangre", "leucemia activa", "sangre enferma", "leucemia sin controlar", "cáncer de médula", "leucemia monoblástica", "problemas de glóbulos blancos", "leucemia no remitida", "leucemia grave", "enfermedad hematológica", "cáncer hematológico", "leucemia agresiva", "leucemia inicial", "cáncer de los monocitos"]'),
('C93.01', 'Leucemia monoblástica/monocítica aguda, en remisión', 'Sin especificar', '["leucemia en control", "leucemia en remisión", "leucemia superada", "cáncer en pausa", "leucemia controlada", "en remisión de leucemia", "cáncer de sangre bajo control", "leucemia que no avanza", "recuperación de leucemia", "leucemia asintomática", "leucemia no activa", "sangre limpia", "leucemia en tratamiento efectivo"]'),
('C93.02', 'Leucemia monoblástica/monocítica aguda, en recidiva', 'Sin especificar', '["recaída de leucemia", "leucemia que regresó", "leucemia de nuevo", "cáncer que volvió", "recidiva de leucemia", "leucemia reactivada", "leucemia reaparecida", "leucemia nuevamente activa", "segunda batalla contra leucemia", "leucemia otra vez", "leucemia resistente"]'),
('C93.10', 'Leucemia mielomonocítica crónica, sin haber alcanzado remisión', 'Sin especificar', '["leucemia crónica", "cáncer de sangre crónico", "leucemia mielomonocítica", "leucemia de larga duración", "leucemia no remitida", "problemas de médula crónica", "sangre enferma crónica", "leucemia sin mejorar", "leucemia persistente", "leucemia indolente activa", "cáncer crónico de glóbulos"]'),
('C93.11', 'Leucemia mielomonocítica crónica, en remisión', 'Sin especificar', '["leucemia crónica en control", "cáncer crónico bajo control", "leucemia mielomonocítica en remisión", "leucemia crónica estable", "leucemia crónica en pausa", "leucemia controlada", "remisión de cáncer crónico", "leucemia que no progresa"]'),
('C93.12', 'Leucemia mielomonocítica crónica, en recidiva', 'Sin especificar', '["leucemia crónica que volvió", "recaída de leucemia crónica", "leucemia crónica reaparecida", "regreso de leucemia mielomonocítica", "cáncer crónico reactivado", "otra vez leucemia crónica", "recidiva hematológica crónica"]'),
('C93.30', 'Leucemia mielomonocítica juvenil, sin haber alcanzado remisión', 'Sin especificar', '["leucemia infantil", "leucemia en niños", "cáncer de sangre infantil", "leucemia juvenil", "leucemia de los niños", "niño con leucemia", "cáncer pediátrico", "leucemia agresiva infantil", "leucemia sin remisión infantil"]'),
('C93.31', 'Leucemia mielomonocítica juvenil, en remisión', 'Sin especificar', '["leucemia infantil en control", "leucemia juvenil en remisión", "niño en remisión de leucemia", "leucemia infantil bajo control", "recuperación de leucemia en niños", "leucemia pediátrica estable"]'),
('C93.32', 'Leucemia mielomonocítica juvenil, en recidiva', 'Sin especificar', '["recaída de leucemia infantil", "cáncer infantil que volvió", "leucemia juvenil que regresó", "reaparición de leucemia en niños", "niño con leucemia de nuevo", "recidiva de cáncer pediátrico"]'),
('C93.Z0', 'Otros tipos de leucemia monocítica, sin haber alcanzado remisión', 'Sin especificar', '["otros tipos de leucemia", "leucemia rara", "tipo de leucemia sin controlar", "cáncer de monocitos", "leucemia no especificada", "enfermedad de la sangre activa", "leucemia sin mejorar"]'),
('C93.Z1', 'Otros tipos de leucemia monocítica, en remisión', 'Sin especificar', '["leucemia bajo control", "cáncer de monocitos en remisión", "leucemia controlada", "leucemia en fase estable", "leucemia rara en remisión"]'),
('C93.Z2', 'Otros tipos de leucemia monocítica, en recidiva', 'Sin especificar', '["recaída de leucemia", "leucemia que volvió", "retorno de leucemia monocítica", "leucemia reaparecida", "cáncer reactivado"]'),
('C93.90', 'Leucemia monocítica, no especificada, sin haber alcanzado remisión', 'Sin especificar', '["leucemia general", "leucemia no especificada", "cáncer de la sangre", "leucemia sin clasificar", "leucemia sin controlar", "problemas de glóbulos", "cáncer activo", "leucemia sin mejoría"]'),
('C93.91', 'Leucemia monocítica, no especificada, en remisión', 'Sin especificar', '["leucemia en remisión", "cáncer en control", "leucemia controlada", "fase de remisión", "leucemia sin síntomas actuales", "cáncer inactivo"]'),
('C93.92', 'Leucemia monocítica, no especificada, en recidiva', 'Sin especificar', '["recaída de leucemia", "leucemia de nuevo", "el cáncer volvió", "leucemia reactivada", "reaparición del cáncer", "leucemia que ha vuelto"]');
