INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N42.0', 'Cálculo de próstata', 'Sin especificar', '["piedras en la próstata", "cálculos prostáticos", "dolor al orinar", "litiasis prostática", "orinar sangre", "dolor bajo vientre", "obstrucción al orinar", "chorro de orina débil", "infección urinaria recurrente", "ardor al miccionar", "prostatis", "molestia en la ingle", "problemas para hacer pipí", "arenilla en la próstata", "taponamiento prostático"]'),
('N42.1', 'Congestión y hemorragia de próstata', 'Sin especificar', '["próstata inflamada", "sangre en el semen", "hematospermia", "sangrado al eyacular", "hinchazón de próstata", "dolor al eyacular", "prostatorragia", "espermatorrea con sangre", "dolor perineal", "próstata congestionada", "molestia en los testículos", "problemas prostáticos agudos", "inflamación de la glándula masculina", "sangre en la orina", "hematuria prostática"]'),
('N42.30', 'Displasia de próstata no especificada', 'Sin especificar', '["células anormales próstata", "lesión premaligna próstata", "crecimiento anormal próstata", "cambios en la próstata", "displasia prostática", "diagnóstico de próstata incierto", "hiperplasia prostática sospechosa", "biopsia alterada", "células raras próstata", "anomalía prostática", "problemas de próstata", "lesión prostática", "riesgo de cáncer de próstata", "proliferación celular prostática", "control prostático"]'),
('N42.31', 'Neoplasia intraepitelial prostática', 'Sin especificar', '["PIN prostático", "lesión precursora de cáncer", "células pre-cancerosas próstata", "neoplasia intraepitelial", "displasia epitelial de próstata", "grado de PIN", "riesgo alto próstata", "cambios celulares malignos", "biopsia con PIN", "lesión escamosa próstata", "anomalía de próstata grado alto", "estudio histopatológico próstata", "vigilancia prostática", "células atípicas de próstata", "neoplasia intraepitelial prostática PIN"]'),
('N42.32', 'Proliferación acinar atípica pequeña de próstata', 'Sin especificar', '["ASAP próstata", "proliferación atípica", "biopsia sospechosa próstata", "células pequeñas anormales", "anomalía acinar prostática", "riesgo de cáncer prostático", "proliferación de glándulas próstata", "lesión prostática inicial", "hallazgo patológico próstata", "atípia de próstata", "estudio de biopsia próstata", "proliferación pequeña acinar", "células sospechosas próstata", "sospecha de malignidad prostática", "seguimiento prostático"]'),
('N42.39', 'Otra displasia de próstata', 'Sin especificar', '["otra anomalía prostática", "displasia prostática diversa", "alteración epitelial próstata", "cambio celular prostático raro", "patología prostática no clasificada", "displasia atípica próstata", "células extrañas en próstata", "hallazgo inusual en biopsia próstata", "proliferación atípica próstata", "trastorno epitelial próstata", "lesión prostática inespecífica", "diagnóstico prostático", "problema de glándula prostática", "cambios tisulares próstata", "estudio histológico próstata"]'),
('N42.81', 'Síndrome de prostatodinia', 'Sin especificar', '["dolor crónico de próstata", "próstata dolorosa", "dolor pélvico masculino", "síndrome de dolor prostático", "dolor perineal crónico", "ardor pélvico", "molestia en la uretra", "dolor al sentarse próstata", "prostatitis sin infección", "dolor testicular y rectal", "síndrome de dolor pélvico crónico", "dolor al orinar sin infección", "tensión pélvica", "dolor en la zona de la bragueta", "espasmos de próstata"]'),
('N42.82', 'Síndrome de prostatosis', 'Sin especificar', '["próstata sintomática", "irritación de próstata", "molestias urinarias inespecíficas", "próstata irritable", "síntomas de prostatitis", "dolor prostático persistente", "próstata sensible", "problemas de próstata funcional", "incomodidad prostática", "prostatorrea", "sensación de pesadez en el bajo vientre", "dolor vago en la zona prostática", "disconfort prostático", "inflamación prostática asintomática", "trastornos de la glándula"]'),
('N42.83', 'Quiste de próstata', 'Sin especificar', '["bolita en la próstata", "quiste prostático", "tumor benigno de próstata", "obstrucción por quiste", "próstata con quistes", "hidrocele prostático", "masa en la próstata", "retención urinaria por quiste", "bulto en la próstata", "quiste de conducto eyaculador", "obstrucción al orinar por quiste", "quiste utricular", "quiste prostático benigno", "ecografía próstata quiste", "dolor por quiste de próstata"]'),
('N42.89', 'Otros trastornos especificados de próstata', 'Sin especificar', '["problemas varios de próstata", "afección prostática", "enfermedad de la glándula prostática", "trastorno de la glándula masculina", "daño prostático", "anomalía de próstata", "patología de próstata", "problemas para orinar próstata", "inflamación de próstata no especificada", "molestias urinarias del hombre", "obstrucción de la salida de la vejiga", "próstata grande", "hipertrofia", "dolor de la próstata", "diagnóstico prostático especial"]'),
('N42.9', 'Trastorno de próstata, no especificado', 'Sin especificar', '["problema de próstata", "mal de la próstata", "enfermedad de la próstata", "problemas de la próstata", "dolor de próstata", "prostata dañada", "no sé qué tengo en la próstata", "molestia en la glándula masculina", "revisión de próstata", "chequeo prostático", "trastorno prostático", "hinchazón de la glándula", "problemas al hacer pipí", "urgencia urinaria", "chorro de orina cortado"]');
