INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P35.0', 'Síndrome de rubéola congénita', 'Sin especificar', '["rubéola en el embarazo", "sarpullido bebé", "manchas rojas recién nacido", "sordera congénita", "cataratas bebé", "problemas corazón bebé", "rubéola al nacer", "infección viral embarazo", "síndrome rubéola", "manchitas bebé", "virus durante gestación", "daño ocular bebé", "defectos nacimiento rubéola", "fiebre y ronchas embarazo"]'),
('P35.1', 'Infección congénita por Citomegalovirus', 'Sin especificar', '["citomegalovirus", "CMV congénito", "virus en el embarazo", "infección por CMV", "bebé con CMV", "retraso desarrollo bebé", "problemas audición bebé", "microcefalia", "calcificaciones cerebrales bebé", "ictericia recién nacido", "hígado grande bebé", "manchas moradas bebé", "infección intrauterina", "CMV recién nacido"]'),
('P35.2', 'Infecciones congénitas por virus del herpes simple', 'Sin especificar', '["herpes neonatal", "herpes recién nacido", "llagas bebé", "ampollas piel bebé", "herpes al nacer", "infección herpes gestación", "conjuntivitis recién nacido", "fiebre bebé", "lesiones piel recién nacido", "meningitis viral bebé", "herpes simple congénito", "virus herpes embarazo", "bebé con herpes", "sepsis neonatal herpes"]'),
('P35.3', 'Hepatitis vírica congénita', 'Sin especificar', '["hepatitis bebé", "ictericia recién nacido", "bebé amarillo", "hígado inflamado bebé", "hepatitis congénita", "virus hígado embarazo", "piel amarilla bebé", "ojos amarillos recién nacido", "problemas hígado gestación", "infección hepática bebé", "hígado agrandado", "ictericia neonatal persistente", "colestasis bebé", "hepatitis por virus al nacer"]'),
('P35.4', 'Enfermedad congénita por virus del Zika', 'Sin especificar', '["zika", "virus zika embarazo", "cabeza pequeña", "microcefalia zika", "picadura mosquito embarazo", "zika congénito", "daño cerebral bebé", "bebé con zika", "problemas desarrollo neurológico", "zika en recién nacidos", "cabeza bebé muy pequeña", "infección mosquito zika", "malformaciones cerebrales zika", "zika virus bebé"]'),
('P35.8', 'Otras enfermedades víricas congénitas', 'Sin especificar', '["virus en el útero", "infección viral bebé", "infección congénita rara", "problemas virales nacimiento", "virus paso placenta", "enfermedad viral recién nacido", "contagio viral gestación", "infección intrauterina rara", "complicaciones virales bebé", "virus embarazo no especificado", "bebés con infecciones congénitas", "patología viral prenatal"]'),
('P35.9', 'Enfermedad vírica congénita no especificada', 'Sin especificar', '["infección congénita desconocida", "virus desconocido embarazo", "enfermedad rara recién nacido", "infección no identificada bebé", "bebé con infección", "problemas nacimiento virus", "enfermedad viral sin nombre", "infección prenatal", "virus gestación", "complicación vírica bebé", "bebé enfermo al nacer", "infección inespecífica bebé"]');
