INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('M10.00', 'Gota idiopática, localización no especificada', 'Sin especificar', '["gota", "ácido úrico alto", "artritis gotosa", "dolor de articulaciones", "cristales en la sangre", "ataque de gota", "inflamación de coyunturas", "podagra", "dolor articular severo", "hiperuricemia", "hinchazón articular", "gota idiopática", "inflamación por ácido úrico", "dolor repentino en articulación", "gota crónica"]'),
('M10.011', 'Gota idiopática, hombro derecho', 'Sin especificar', '["gota en el hombro derecho", "dolor de hombro derecho", "inflamación hombro derecho", "artritis por ácido úrico hombro", "hombro derecho hinchado", "cristales en hombro derecho", "ataque de gota hombro derecho", "pinchazos en el hombro", "rigidez hombro derecho", "dolor agudo hombro", "gota hombro", "artritis gotosa hombro"]'),
('M10.012', 'Gota idiopática, hombro izquierdo', 'Sin especificar', '["gota en el hombro izquierdo", "dolor de hombro izquierdo", "inflamación hombro izquierdo", "artritis por ácido úrico hombro", "hombro izquierdo hinchado", "cristales en hombro izquierdo", "ataque de gota hombro izquierdo", "pinchazos en el hombro", "rigidez hombro izquierdo", "dolor agudo hombro izquierdo", "gota hombro", "artritis gotosa hombro"]'),
('M10.019', 'Gota idiopática, hombro no especificado', 'Sin especificar', '["gota en el hombro", "dolor de hombro", "inflamación del hombro", "ataque de gota en hombro", "molestia en hombro por ácido úrico", "artritis gotosa hombro", "hombro inflamado", "cristales ácido úrico", "hombro doloroso", "gota articulación hombro"]'),
('M10.021', 'Gota idiopática, codo derecho', 'Sin especificar', '["gota en el codo derecho", "dolor de codo derecho", "codo derecho hinchado", "inflamación codo derecho", "artritis por ácido úrico codo", "ataque de gota codo", "codo inflamado", "pinchazos en el codo", "codo rojo y caliente", "gota en el codo"]'),
('M10.022', 'Gota idiopática, codo izquierdo', 'Sin especificar', '["gota en el codo izquierdo", "dolor de codo izquierdo", "codo izquierdo hinchado", "inflamación codo izquierdo", "artritis por ácido úrico codo", "ataque de gota codo", "codo inflamado", "pinchazos en el codo", "codo rojo y caliente", "gota en el codo"]'),
('M10.029', 'Gota idiopática, codo no especificado', 'Sin especificar', '["gota en el codo", "dolor de codo", "codo inflamado", "inflamación de codo", "artritis gotosa codo", "ataque de gota en el codo", "ácido úrico en el codo", "codo rojo", "codo caliente", "molestias en el codo"]'),
('M10.031', 'Gota idiopática, muñeca derecha', 'Sin especificar', '["gota en la muñeca derecha", "dolor de muñeca derecha", "muñeca derecha hinchada", "inflamación muñeca", "ataque de gota muñeca", "artritis por ácido úrico muñeca", "muñeca caliente", "dolor fuerte muñeca", "cristales en la muñeca", "muñeca rígida"]'),
('M10.032', 'Gota idiopática, muñeca izquierda', 'Sin especificar', '["gota en la muñeca izquierda", "dolor de muñeca izquierda", "muñeca izquierda hinchada", "inflamación muñeca", "ataque de gota muñeca", "artritis por ácido úrico muñeca", "muñeca caliente", "dolor fuerte muñeca", "cristales en la muñeca", "muñeca rígida"]'),
('M10.039', 'Gota idiopática, muñeca no especificada', 'Sin especificar', '["gota en la muñeca", "dolor de muñeca", "muñeca hinchada", "artritis gotosa muñeca", "inflamación de la articulación de la muñeca", "ataque de gota en mano", "ácido úrico muñeca", "muñeca roja", "muñeca que duele al moverla"]'),
('M10.041', 'Gota idiopática, mano derecha', 'Sin especificar', '["gota en la mano derecha", "dolor de mano derecha", "mano derecha hinchada", "dedos de la mano hinchados", "artritis gotosa mano", "gota en los dedos", "inflamación mano derecha", "nudos en los dedos", "tofos gotosos mano"]'),
('M10.042', 'Gota idiopática, mano izquierda', 'Sin especificar', '["gota en la mano izquierda", "dolor de mano izquierda", "mano izquierda hinchada", "dedos de la mano hinchados", "artritis gotosa mano", "gota en los dedos", "inflamación mano izquierda", "nudos en los dedos", "tofos gotosos mano"]'),
('M10.049', 'Gota idiopática, mano no especificada', 'Sin especificar', '["gota en la mano", "dolor en las manos", "manos hinchadas", "artritis por gota", "dedos de las manos rojos", "hinchazón en dedos", "ácido úrico en las manos", "gota articular mano"]'),
('M10.051', 'Gota idiopática, cadera derecha', 'Sin especificar', '["gota en la cadera derecha", "dolor de cadera derecha", "inflamación cadera derecha", "artritis cadera", "dolor inguinal por gota", "ataque de gota cadera", "artritis gotosa cadera", "cadera trabada", "dolor al caminar cadera"]'),
('M10.052', 'Gota idiopática, cadera izquierda', 'Sin especificar', '["gota en la cadera izquierda", "dolor de cadera izquierda", "inflamación cadera izquierda", "artritis cadera", "dolor inguinal por gota", "ataque de gota cadera", "artritis gotosa cadera", "cadera trabada", "dolor al caminar cadera"]'),
('M10.059', 'Gota idiopática, cadera no especificada', 'Sin especificar', '["gota en la cadera", "dolor de cadera", "artritis en la cadera", "inflamación articulación cadera", "ácido úrico en la cadera", "ataque agudo en la cadera", "cadera que duele"]'),
('M10.061', 'Gota idiopática, rodilla derecha', 'Sin especificar', '["gota en la rodilla derecha", "rodilla derecha hinchada", "dolor de rodilla derecha", "líquido en la rodilla por gota", "rodilla roja", "rodilla caliente", "inflamación rodilla", "artritis gotosa rodilla", "ataque de gota rodilla", "me duele la rodilla derecha"]'),
('M10.062', 'Gota idiopática, rodilla izquierda', 'Sin especificar', '["gota en la rodilla izquierda", "rodilla izquierda hinchada", "dolor de rodilla izquierda", "líquido en la rodilla por gota", "rodilla roja", "rodilla caliente", "inflamación rodilla", "artritis gotosa rodilla", "ataque de gota rodilla", "me duele la rodilla izquierda"]'),
('M10.069', 'Gota idiopática, rodilla no especificada', 'Sin especificar', '["gota en la rodilla", "rodilla hinchada", "dolor de rodilla", "rodilla roja y caliente", "artritis por ácido úrico", "inflamación de articulación de la rodilla", "gota articular rodilla", "ataque de gota rodilla"]'),
('M10.071', 'Gota idiopática, tobillo y pie derechos', 'Sin especificar', '["gota en el tobillo derecho", "gota en el pie derecho", "tobillo derecho hinchado", "dolor de pie derecho", "pie rojo por gota", "tobillo caliente", "inflamación tobillo", "dolor al pisar", "ataque de gota pie", "artritis gotosa pie"]'),
('M10.072', 'Gota idiopática, tobillo y pie izquierdo', 'Sin especificar', '["gota en el tobillo izquierdo", "gota en el pie izquierdo", "tobillo izquierdo hinchado", "dolor de pie izquierdo", "pie rojo por gota", "tobillo caliente", "inflamación tobillo", "dolor al pisar", "ataque de gota pie", "artritis gotosa pie"]'),
('M10.079', 'Gota idiopática, tobillo y pie no especificados', 'Sin especificar', '["gota en el pie", "podagra", "dolor en el dedo gordo", "tobillo hinchado", "pie inflamado", "dolor al caminar gota", "gota en el tobillo", "ácido úrico en los pies", "pie rojo y caliente", "ataque de gota pie"]'),
('M10.08', 'Gota idiopática, vértebras', 'Sin especificar', '["gota en la columna", "gota en la espalda", "dolor de espalda por gota", "inflamación vértebras", "artritis gotosa columna", "dolor vertebral", "ácido úrico en la espalda", "dolor lumbar gota"]'),
('M10.09', 'Gota idiopática, localizaciones múltiples', 'Sin especificar', '["gota generalizada", "gota en varias articulaciones", "muchas articulaciones con gota", "dolor poliarticular por gota", "ataques de gota recurrentes", "ácido úrico en todo el cuerpo", "gota múltiple", "artritis gotosa sistémica"]'),
('M10.10', 'Gota inducida por plomo, localización no especificada', 'Sin especificar', '["gota por plomo", "intoxicación por plomo y gota", "saturnismo y gota", "gota saturnina", "ácido úrico y plomo", "gota por exposición a plomo", "artritis por plomo"]'),
('M10.111', 'Gota inducida por plomo, hombro derecho', 'Sin especificar', '["gota saturnina hombro derecho", "gota por plomo hombro derecho", "dolor de hombro por plomo", "artritis por plomo hombro"]'),
('M10.112', 'Gota inducida por plomo, hombro izquierdo', 'Sin especificar', '["gota saturnina hombro izquierdo", "gota por plomo hombro izquierdo", "dolor de hombro por plomo", "artritis por plomo hombro"]'),
('M10.119', 'Gota inducida por plomo, hombro no especificado', 'Sin especificar', '["gota por plomo en el hombro", "gota saturnina en el hombro", "artritis por intoxicación de plomo"]'),
('M10.121', 'Gota inducida por plomo, codo derecho', 'Sin especificar', '["gota por plomo codo derecho", "gota saturnina codo derecho", "dolor de codo por plomo"]'),
('M10.122', 'Gota inducida por plomo, codo izquierdo', 'Sin especificar', '["gota por plomo codo izquierdo", "gota saturnina codo izquierdo", "dolor de codo por plomo"]'),
('M10.129', 'Gota inducida por plomo, codo no especificado', 'Sin especificar', '["gota por plomo codo", "gota saturnina codo", "artritis codo plomo"]'),
('M10.131', 'Gota inducida por plomo, muñeca derecha', 'Sin especificar', '["gota por plomo muñeca derecha", "gota saturnina muñeca derecha"]'),
('M10.132', 'Gota inducida por plomo, muñeca izquierda', 'Sin especificar', '["gota por plomo muñeca izquierda", "gota saturnina muñeca izquierda"]'),
('M10.139', 'Gota inducida por plomo, muñeca no especificada', 'Sin especificar', '["gota por plomo muñeca", "gota saturnina muñeca"]'),
('M10.141', 'Gota inducida por plomo, mano derecha', 'Sin especificar', '["gota por plomo mano derecha", "gota saturnina mano derecha"]'),
('M10.142', 'Gota inducida por plomo, mano izquierda', 'Sin especificar', '["gota por plomo mano izquierda", "gota saturnina mano izquierda"]'),
('M10.149', 'Gota inducida por plomo, mano no especificada', 'Sin especificar', '["gota por plomo en la mano", "gota saturnina mano"]'),
('M10.151', 'Gota inducida por plomo, cadera derecha', 'Sin especificar', '["gota por plomo cadera derecha", "gota saturnina cadera derecha"]'),
('M10.152', 'Gota inducida por plomo, cadera izquierda', 'Sin especificar', '["gota por plomo cadera izquierda", "gota saturnina cadera izquierda"]'),
('M10.159', 'Gota inducida por plomo, cadera no especificada', 'Sin especificar', '["gota por plomo cadera", "gota saturnina cadera"]'),
('M10.161', 'Gota inducida por plomo, rodilla derecha', 'Sin especificar', '["gota por plomo rodilla derecha", "gota saturnina rodilla derecha"]'),
('M10.162', 'Gota inducida por plomo, rodilla izquierda', 'Sin especificar', '["gota por plomo rodilla izquierda", "gota saturnina rodilla izquierda"]'),
('M10.169', 'Gota inducida por plomo, rodilla no especificada', 'Sin especificar', '["gota por plomo rodilla", "gota saturnina rodilla"]'),
('M10.171', 'Gota inducida por plomo, tobillo y pie derechos', 'Sin especificar', '["gota por plomo pie derecho", "gota saturnina pie derecho"]'),
('M10.172', 'Gota inducida por plomo, tobillo y pie izquierdo', 'Sin especificar', '["gota por plomo pie izquierdo", "gota saturnina pie izquierdo"]'),
('M10.179', 'Gota inducida por plomo, tobillo y pie no especificados', 'Sin especificar', '["gota por plomo pie", "gota saturnina pie"]'),
('M10.18', 'Gota inducida por plomo, vértebras', 'Sin especificar', '["gota por plomo vértebras", "gota saturnina columna"]'),
('M10.19', 'Gota inducida por plomo, localizaciones múltiples', 'Sin especificar', '["gota por plomo generalizada", "gota saturnina múltiple"]'),
('M10.20', 'Gota inducida por medicamentos, localización no especificada', 'Sin especificar', '["gota por fármacos", "gota por medicinas", "gota inducida por diuréticos", "ácido úrico por medicamentos", "gota secundaria a medicamentos", "dolor articular por pastillas", "artritis por medicación"]'),
('M10.211', 'Gota inducida por medicamentos, hombro derecho', 'Sin especificar', '["gota por medicamentos hombro derecho", "dolor hombro derecho por fármacos"]'),
('M10.212', 'Gota inducida por medicamentos, hombro izquierdo', 'Sin especificar', '["gota por medicamentos hombro izquierdo", "dolor hombro izquierdo por fármacos"]'),
('M10.219', 'Gota inducida por medicamentos, hombro no especificado', 'Sin especificar', '["gota por medicamentos en hombro", "dolor articular hombro fármacos"]'),
('M10.221', 'Gota inducida por medicamentos, codo derecho', 'Sin especificar', '["gota por medicamentos codo derecho", "artritis codo fármacos"]'),
('M10.222', 'Gota inducida por medicamentos, codo izquierdo', 'Sin especificar', '["gota por medicamentos codo izquierdo", "artritis codo fármacos"]'),
('M10.229', 'Gota inducida por medicamentos, codo no especificado', 'Sin especificar', '["gota por medicamentos codo", "dolor codo fármacos"]'),
('M10.231', 'Gota inducida por medicamentos, muñeca derecha', 'Sin especificar', '["gota por medicamentos muñeca derecha", "muñeca derecha inflamada fármacos"]'),
('M10.232', 'Gota inducida por medicamentos, muñeca izquierda', 'Sin especificar', '["gota por medicamentos muñeca izquierda", "muñeca izquierda inflamada fármacos"]'),
('M10.239', 'Gota inducida por medicamentos, muñeca no especificada', 'Sin especificar', '["gota por medicamentos muñeca", "dolor muñeca por fármacos"]'),
('M10.241', 'Gota inducida por medicamentos, mano derecha', 'Sin especificar', '["gota por medicamentos mano derecha", "mano derecha hinchada fármacos"]'),
('M10.242', 'Gota inducida por medicamentos, mano izquierda', 'Sin especificar', '["gota por medicamentos mano izquierda", "mano izquierda hinchada fármacos"]'),
('M10.249', 'Gota inducida por medicamentos, mano no especificada', 'Sin especificar', '["gota por medicamentos mano", "dedos hinchados por fármacos"]'),
('M10.251', 'Gota inducida por medicamentos, cadera derecha', 'Sin especificar', '["gota por medicamentos cadera derecha", "dolor cadera fármacos"]'),
('M10.252', 'Gota inducida por medicamentos, cadera izquierda', 'Sin especificar', '["gota por medicamentos cadera izquierda", "dolor cadera fármacos"]'),
('M10.259', 'Gota inducida por medicamentos, cadera no especificada', 'Sin especificar', '["gota por medicamentos cadera", "dolor de cadera por medicinas"]'),
('M10.261', 'Gota inducida por medicamentos, rodilla derecha', 'Sin especificar', '["gota por medicamentos rodilla derecha", "rodilla derecha inflamada fármacos"]'),
('M10.262', 'Gota inducida por medicamentos, rodilla izquierda', 'Sin especificar', '["gota por medicamentos rodilla izquierda", "rodilla izquierda inflamada fármacos"]'),
('M10.269', 'Gota inducida por medicamentos, rodilla no especificada', 'Sin especificar', '["gota por medicamentos rodilla", "rodilla hinchada por medicinas"]'),
('M10.271', 'Gota inducida por medicamentos, tobillo y pie derechos', 'Sin especificar', '["gota por medicamentos pie derecho", "dolor pie derecho fármacos"]'),
('M10.272', 'Gota inducida por medicamentos, tobillo y pie izquierdos', 'Sin especificar', '["gota por medicamentos pie izquierdo", "dolor pie izquierdo fármacos"]'),
('M10.279', 'Gota inducida por medicamentos, tobillo y pie no especificados', 'Sin especificar', '["gota por medicamentos pie", "dolor de pies por fármacos"]'),
('M10.28', 'Gota inducida por medicamentos, vértebras', 'Sin especificar', '["gota por medicamentos columna", "dolor espalda fármacos"]'),
('M10.29', 'Gota inducida por medicamentos, localizaciones múltiples', 'Sin especificar', '["gota múltiple por fármacos", "ataque sistémico por medicamentos"]'),
('M10.30', 'Gota debida a insuficiencia renal, localización no especificada', 'Sin especificar', '["gota por insuficiencia renal", "gota y riñones", "ácido úrico alto por riñones", "gota renal", "dolor articular por fallo renal"]'),
('M10.311', 'Gota debida a insuficiencia renal, hombro derecho', 'Sin especificar', '["gota renal hombro derecho", "dolor hombro derecho insuficiencia renal"]'),
('M10.312', 'Gota debida a insuficiencia renal, hombro izquierdo', 'Sin especificar', '["gota renal hombro izquierdo", "dolor hombro izquierdo insuficiencia renal"]'),
('M10.319', 'Gota debida a insuficiencia renal, hombro no especificado', 'Sin especificar', '["gota renal hombro", "dolor hombro riñones"]'),
('M10.321', 'Gota debida a insuficiencia renal, codo derecho', 'Sin especificar', '["gota renal codo derecho"]'),
('M10.322', 'Gota debida a insuficiencia renal, codo izquierdo', 'Sin especificar', '["gota renal codo izquierdo"]'),
('M10.329', 'Gota debida a insuficiencia renal, codo no especificado', 'Sin especificar', '["gota renal codo"]'),
('M10.331', 'Gota debida a insuficiencia renal, muñeca derecha', 'Sin especificar', '["gota renal muñeca derecha"]'),
('M10.332', 'Gota debida a insuficiencia renal, muñeca izquierda', 'Sin especificar', '["gota renal muñeca izquierda"]'),
('M10.339', 'Gota debida a insuficiencia renal, muñeca no especificada', 'Sin especificar', '["gota renal muñeca"]'),
('M10.341', 'Gota debida a insuficiencia renal, mano derecha', 'Sin especificar', '["gota renal mano derecha"]'),
('M10.342', 'Gota debida a insuficiencia renal, mano izquierda', 'Sin especificar', '["gota renal mano izquierda"]'),
('M10.349', 'Gota debida a insuficiencia renal, mano no especificada', 'Sin especificar', '["gota renal mano"]'),
('M10.351', 'Gota debida a insuficiencia renal, cadera derecha', 'Sin especificar', '["gota renal cadera derecha"]'),
('M10.352', 'Gota debida a insuficiencia renal, cadera izquierda', 'Sin especificar', '["gota renal cadera izquierda"]'),
('M10.359', 'Gota debida a insuficiencia renal, cadera no especificada', 'Sin especificar', '["gota renal cadera"]'),
('M10.361', 'Gota debida a insuficiencia renal, rodilla derecha', 'Sin especificar', '["gota renal rodilla derecha"]'),
('M10.362', 'Gota debida a insuficiencia renal, rodilla izquierda', 'Sin especificar', '["gota renal rodilla izquierda"]'),
('M10.369', 'Gota debida a insuficiencia renal, rodilla no especificada', 'Sin especificar', '["gota renal rodilla"]'),
('M10.371', 'Gota debida a insuficiencia renal, tobillo y pie derechos', 'Sin especificar', '["gota renal pie derecho"]'),
('M10.372', 'Gota debida a insuficiencia renal, tobillo y pie izquierdos', 'Sin especificar', '["gota renal pie izquierdo"]'),
('M10.379', 'Gota debida a insuficiencia renal, tobillo y pie no especificados', 'Sin especificar', '["gota renal pie"]'),
('M10.38', 'Gota debida a insuficiencia renal, vértebras', 'Sin especificar', '["gota renal vértebras"]'),
('M10.39', 'Gota debida a insuficiencia renal, localizaciones múltiples', 'Sin especificar', '["gota renal múltiple"]'),
('M10.40', 'Otros tipos de gota secundaria, localización no especificada', 'Sin especificar', '["gota secundaria", "gota por otras causas", "ácido úrico secundario"]'),
('M10.411', 'Otros tipos de gota secundaria, hombro derecho', 'Sin especificar', '["gota secundaria hombro derecho"]'),
('M10.412', 'Otros tipos de gota secundaria, hombro izquierdo', 'Sin especificar', '["gota secundaria hombro izquierdo"]'),
('M10.419', 'Otros tipos de gota secundaria, hombro no especificado', 'Sin especificar', '["gota secundaria hombro"]'),
('M10.421', 'Otros tipos de gota secundaria, codo derecho', 'Sin especificar', '["gota secundaria codo derecho"]'),
('M10.422', 'Otros tipos de gota secundaria, codo izquierdo', 'Sin especificar', '["gota secundaria codo izquierdo"]'),
('M10.429', 'Otros tipos de gota secundaria, codo no especificado', 'Sin especificar', '["gota secundaria codo"]'),
('M10.431', 'Otros tipos de gota secundaria, muñeca derecha', 'Sin especificar', '["gota secundaria muñeca derecha"]'),
('M10.432', 'Otros tipos de gota secundaria, muñeca izquierda', 'Sin especificar', '["gota secundaria muñeca izquierda"]'),
('M10.439', 'Otros tipos de gota secundaria, muñeca no especificada', 'Sin especificar', '["gota secundaria muñeca"]'),
('M10.441', 'Otros tipos de gota secundaria, mano derecha', 'Sin especificar', '["gota secundaria mano derecha"]'),
('M10.442', 'Otros tipos de gota secundaria, mano izquierda', 'Sin especificar', '["gota secundaria mano izquierda"]'),
('M10.449', 'Otros tipos de gota secundaria, mano no especificada', 'Sin especificar', '["gota secundaria mano"]'),
('M10.451', 'Otros tipos de gota secundaria, cadera derecha', 'Sin especificar', '["gota secundaria cadera derecha"]'),
('M10.452', 'Otros tipos de gota secundaria, cadera izquierda', 'Sin especificar', '["gota secundaria cadera izquierda"]'),
('M10.459', 'Otros tipos de gota secundaria, cadera no especificada', 'Sin especificar', '["gota secundaria cadera"]'),
('M10.461', 'Otros tipos de gota secundaria, rodilla derecha', 'Sin especificar', '["gota secundaria rodilla derecha"]'),
('M10.462', 'Otros tipos de gota secundaria, rodilla izquierda', 'Sin especificar', '["gota secundaria rodilla izquierda"]'),
('M10.469', 'Otros tipos de gota secundaria, rodilla no especificada', 'Sin especificar', '["gota secundaria rodilla"]'),
('M10.471', 'Otros tipos de gota secundaria, tobillo y pie derechos', 'Sin especificar', '["gota secundaria pie derecho"]'),
('M10.472', 'Otros tipos de gota secundaria, tobillo y pie izquierdos', 'Sin especificar', '["gota secundaria pie izquierdo"]'),
('M10.479', 'Otros tipos de gota secundaria, tobillo y pie no especificados', 'Sin especificar', '["gota secundaria pie"]'),
('M10.48', 'Otros tipos de gota secundaria, vértebras', 'Sin especificar', '["gota secundaria vértebras"]'),
('M10.49', 'Otros tipos de gota secundaria, localizaciones múltiples', 'Sin especificar', '["gota secundaria múltiple"]'),
('M10.9', 'Gota, no especificada', 'Sin especificar', '["gota", "tengo gota", "ataque de gota", "dolor por ácido úrico", "podagra", "artritis", "enfermedad de los reyes"]');
