INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N94.0', 'Dolor intermenstrual', 'Sin especificar', '["dolor en la ovulacion", "molestia entre periodos", "pinchazo en el ovario", "dolor a mitad de ciclo", "mittelschmerz", "dolor de ovarios a mitad de mes", "colico de ovulacion", "dolor pelvico intermenstrual", "dolor en la panza en dias fertiles", "dolor en la guata en la mitad del ciclo", "dolor bajito a mitad de mes"]'),
('N94.10', 'Dispareunia no especificada', 'Sin especificar', '["dolor al tener relaciones", "coito doloroso", "me duele al penetrar", "dolor en el acto sexual", "ardor en la relacion sexual", "molestias al coito", "dolor vaginal durante el sexo", "pinchazos al tener relaciones", "incomodidad sexual", "dolor durante la penetracion", "no puedo tener relaciones por dolor"]'),
('N94.11', 'Dispareunia superficial (introital)', 'Sin especificar', '["dolor en la entrada de la vagina", "ardor al inicio de la penetracion", "dolor en la vulva al tener sexo", "irritacion en la entrada vaginal", "me duele la entrada al tener relaciones", "picazon y dolor al coito", "dolor en el introito", "sensacion de desgarro al inicio del coito", "ardor en los labios vaginales durante el sexo"]'),
('N94.12', 'Dispareunia profunda', 'Sin especificar', '["dolor profundo al tener relaciones", "me duele el fondo al tener sexo", "pinchazos en el fondo de la vagina", "dolor en el bajo vientre durante el coito", "dolor en el abdomen profundo al penetrar", "molestia al final de la vagina en el acto", "dolor de ovarios al tener sexo", "impacto doloroso en el fondo", "dolor pelvico durante el coito"]'),
('N94.19', 'Otro tipo de dispareunia', 'Sin especificar', '["dolor al sexo poco comun", "molestias raras al tener relaciones", "dolor ginecologico en el acto", "problemas para tener relaciones por dolor", "dolor coital persistente", "incomodidad en la zona intima al sexo", "dolor psicogenico al coito", "dolor mixto al tener relaciones"]'),
('N94.2', 'Vaginismo', 'Sin especificar', '["no puedo penetrar", "se me cierra todo al intentar tener sexo", "espasmos vaginales", "miedo a la penetracion", "dolor al intentar el coito", "no entra nada", "imposibilidad de penetracion", "cierre involuntario de la vagina", "dolor insoportable al intentar sexo", "musculos vaginales contraidos"]'),
('N94.3', 'Síndrome de tensión premenstrual', 'Sin especificar', '["sindrome premenstrual", "cambios de humor antes de la regla", "dolor de pechos antes de menstruar", "irritabilidad premenstrual", "hinchazon antes de la regla", "ansiedad por menstruar", "depresion premenstrual", "me siento mal antes de que me baje", "tension antes de la regla", "inflamacion antes del periodo", "SPM"]'),
('N94.4', 'Dismenorrea primaria', 'Sin especificar', '["dolores menstruales fuertes", "colicos menstruales", "dolor de regla", "dolor al bajarme", "me duele la panza con la regla", "dolor de ovarios por regla", "calambres menstruales", "dolor de guata con la regla", "dolor en la pelvis al menstruar", "discopatía menstrual", "dolor intenso en el periodo"]'),
('N94.5', 'Dismenorrea secundaria', 'Sin especificar', '["dolor menstrual constante", "dolor de regla anormal", "colicos por endometriosis", "dolor menstrual por miomas", "dolor de periodo que no se quita", "regla muy dolorosa y rara", "dolor pelvico cronico con la regla", "menstruacion dolorosa patologica", "dolor uterino fuerte durante el periodo"]'),
('N94.6', 'Dismenorrea, no especificada', 'Sin especificar', '["dolor de regla", "colicos", "me duele mucho la regla", "regla dolorosa", "dolores de abdomen por el periodo", "discopatía", "malestar por menstruacion", "dolor menstrual no identificado", "dolor bajito por la regla"]'),
('N94.810', 'Vestibulitis vulvar', 'Sin especificar', '["ardor en la entrada de la vagina", "inflamacion del vestibulo vulvar", "dolor al roce en la vulva", "ardor en la zona genital", "sensacion de fuego en la entrada de la vagina", "dolor con la ropa interior", "dolor al andar en bicicleta", "irritacion cronica en la vulva", "sensibilidad extrema en la zona genital"]'),
('N94.818', 'Otros tipos de vulvodinia', 'Sin especificar', '["dolor vulvar cronico", "ardor en la vulva", "picazon y ardor genital", "dolor en los labios vaginales", "vulva irritada siempre", "dolor de la zona intima", "sensacion de quemazon en la vulva", "dolor al tacto en la zona genital"]'),
('N94.819', 'Vulvodinia, no especificada', 'Sin especificar', '["dolor de vulva", "ardor genital", "dolor cronico en la zona intima", "quemazon vaginal", "dolor en la parte externa de la vagina", "incomodidad constante en la vulva", "dolor neuropatico vulvar", "me arde toda la zona genital"]'),
('N94.89', 'Otras afecciones especificadas asociadas a órganos genitales femeninos y al ciclo menstrual', 'Sin especificar', '["molestias ginecologicas", "problemas del ciclo menstrual", "dolor pelvico atipico", "trastornos genitales femeninos", "dolor en los ovarios", "inflamacion uterina", "problemas en la matriz", "dolor en la zona baja por regla"]'),
('N94.9', 'Afecciones no especificadas asociadas a órganos genitales femeninos y al ciclo menstrual', 'Sin especificar', '["dolor genital", "problemas de ovarios", "problemas de regla", "molestias en la matriz", "dolor en la zona baja", "dolor ginecologico", "malestar en el aparato reproductor", "problemas con el periodo"]');
