INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B46.0', 'Mucormicosis pulmonar', 'Sin especificar', '["hongo en los pulmones", "infección fúngica pulmonar", "neumonía por hongos", "moho en los pulmones", "micosis pulmonar", "dificultad para respirar por hongos", "tos con sangre fúngica", "hongo negro pulmonar", "infección respiratoria grave", "necrosis pulmonar por hongos", "pulmón con moho", "tos seca persistente", "dolor de pecho por micosis", "infección oportunista pulmonar"]'),
('B46.1', 'Mucormicosis rinocerebral', 'Sin especificar', '["hongo negro", "hongo en la cara", "micosis facial", "infección en senos paranasales", "necrosis de nariz", "hongo que come tejido", "infección ocular por hongos", "sinusitis fúngica grave", "mancha negra en la nariz", "hongo en el cerebro", "hongo en el paladar", "inflamación de la cara", "dolor facial intenso", "infección invasiva cara y ojos"]'),
('B46.2', 'Mucormicosis gastrointestinal', 'Sin especificar', '["hongo en el estómago", "micosis intestinal", "infección fúngica del tracto digestivo", "dolor de panza fuerte", "dolor de guata", "úlcera gástrica por hongos", "infección en el intestino", "dolor abdominal por moho", "vómito con sangre por hongos", "necrosis intestinal", "hongo en el tracto digestivo", "diarrea persistente por hongos", "inflamación del colon por micosis", "dolor de tripa grave"]'),
('B46.3', 'Mucormicosis cutánea', 'Sin especificar', '["hongo en la piel", "micosis en la piel", "mancha negra en la piel", "necrosis cutánea", "infección fúngica de la piel", "llaga que no sana", "herida con moho", "hongo invasivo piel", "piel negra por infección", "úlcera fúngica", "inflamación de la dermis por hongos", "lesión cutánea necrótica", "infección de la piel por moho", "tejido muerto en piel"]'),
('B46.4', 'Mucormicosis diseminada', 'Sin especificar', '["hongo generalizado", "micosis en todo el cuerpo", "infección fúngica sistémica", "sepsis por hongos", "hongo en la sangre", "infección invasiva general", "micosis que se extiende", "hongo negro diseminado", "fallo multiorgánico por hongos", "micosis grave extendida", "infección oportunista sistémica", "hongo en órganos vitales", "micosis diseminada rápida", "infección fúngica fatal"]'),
('B46.5', 'Mucormicosis, no especificada', 'Sin especificar', '["infección por hongos desconocida", "hongo invasivo", "micosis rara", "moho en el cuerpo", "infección micótica grave", "hongo negro sin especificar", "enfermedad por zigomicetos", "hongo oportunista", "infección peligrosa por hongos", "micosis de origen incierto", "hongo que necrosa tejido", "infección por mohos ambientales", "hongo en tejidos", "micosis no clasificada"]'),
('B46.8', 'Otras cigomicosis', 'Sin especificar', '["infección por zigomicetos", "otras infecciones fúngicas", "mohos raros", "micosis diversas", "hongo invasivo raro", "infección por phycomycetes", "zigomicosis general", "moho en tejidos blandos", "infección fúngica infrecuente", "hongo ambiental peligroso", "micosis profunda", "infección oportunista rara", "enfermedad fúngica invasora", "zigomicosis no común"]'),
('B46.9', 'Cigomicosis, no especificada', 'Sin especificar', '["infección por zigomicetos no especificada", "hongo tipo moho", "infección micótica invasora", "micosis sistémica", "enfermedad por hongos mucorales", "zigomicosis indefinida", "hongo oportunista grave", "micosis profunda sin especificar", "infección invasiva por mohos", "hongo en tejidos profundos", "micosis de los zigomicetos", "infección por mohos", "enfermedad por hongo no determinada", "micosis invasiva general"]');
