INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P78.0', 'Perforación intestinal perinatal', 'Sin especificar', '["perforación intestinal bebé", "agujero en el intestino recién nacido", "ruptura de panza bebé", "intestino roto neonato", "peritonitis neonatal", "tripa perforada", "abdomen agudo en bebé", "dolor de guata grave neonato", "emergencia intestinal infantil", "cirugía de panza recién nacido", "fuga intestinal bebé"]'),
('P78.1', 'Otras peritonitis neonatales', 'Sin especificar', '["inflamación de la panza bebé", "peritonitis del recién nacido", "infección en el peritoneo neonato", "panza hinchada bebé", "guata inflamada recién nacido", "abdomen duro bebé", "infección abdominal infantil", "dolor abdominal severo neonato", "peritonitis infantil", "vientre inflamado recién nacido", "cuerpo sensible abdomen bebé"]'),
('P78.2', 'Hematemesis y melena neonatales por ingestión de sangre materna', 'Sin especificar', '["vómito con sangre bebé", "caca negra recién nacido", "sangre en el vómito del bebé", "heces negras neonato", "bebé escupe sangre", "sangre materna en bebé", "melena neonatal", "hematemesis del recién nacido", "bebé con popó negro", "vómito rojo recién nacido", "sangre en pañal bebé"]'),
('P78.3', 'Diarrea neonatal no infecciosa', 'Sin especificar', '["diarrea bebé no por virus", "caca suelta recién nacido", "evacuaciones líquidas neonato", "bebé hace popó aguado", "diarrea persistente recién nacido", "cagadera bebé", "churretera bebé", "diarrea por leche", "intolerancia alimentaria bebé", "bebé descompuesto", "diarrea inespecífica neonato"]'),
('P78.81', 'Cirrosis congénita (de hígado)', 'Sin especificar', '["hígado dañado bebé", "cirrosis desde nacimiento", "hígado duro recién nacido", "problema hepático bebé", "hígado que no funciona neonato", "ictericia grave recién nacido", "hígado cirrótico infantil", "daño hepático congénito", "fallo hepático neonatal", "hígado agrandado bebé"]'),
('P78.82', 'Úlcera péptica del recién nacido', 'Sin especificar', '["úlcera en el estómago bebé", "herida en el estómago neonato", "dolor de guata bebé", "ardor de estómago recién nacido", "úlcera gástrica infantil", "úlcera duodenal bebé", "sangre en vómito bebé", "bebé llora al comer", "gastritis severa bebé", "úlceras en neonatos"]'),
('P78.83', 'Reflujo gastroesofágico del recién nacido', 'Sin especificar', '["reflujo bebé", "bebé devuelve la leche", "ardor en el pecho bebé", "bebé con acidez", "regurgitación constante", "bebé escupe mucho", "reflujo gástrico recién nacido", "esofagitis bebé", "reflujo silencioso", "bebé con malestar después de comer", "vomitón bebé"]'),
('P78.84', 'Enfermedad hepática gestacional aloinmune', 'Sin especificar', '["enfermedad del hígado aloinmune", "problema hepático por embarazo", "daño hepático neonatal aloinmune", "hígado afectado bebé aloinmune", "fallo hepático aloinmune", "hepatopatía gestacional", "hígado atacado por anticuerpos", "ictericia neonatal severa", "problemas de hígado congénitos"]'),
('P78.89', 'Otros trastornos perinatales especificados del aparato digestivo', 'Sin especificar', '["problemas digestivos bebé", "molestias de panza recién nacido", "trastornos intestinales neonato", "dolor de guata bebé", "digestión lenta bebé", "malestar gastrointestinal recién nacido", "problemas para digerir neonato", "cólicos persistentes", "anomalías digestivas bebé"]'),
('P78.9', 'Trastorno perinatal del aparato digestivo, no especificado', 'Sin especificar', '["problemas digestivos neonato", "indigestión bebé", "dolor de panza bebé desconocido", "enfermedad intestinal recién nacido", "molestia estomacal bebé", "trastorno del sistema digestivo neonato", "problemas de pancita", "no puede digerir bien bebé", "malestar intestinal bebé"]');
