INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C82.00', 'Linfoma folicular grado I, localización no especificada', 'Sin especificar', '["cáncer de ganglios", "bolitas en el cuerpo", "ganglios inflamados", "linfoma grado 1", "linfoma folicular", "cáncer linfático", "hinchazón de ganglios", "bolitas en el cuello", "bultos sospechosos", "ganglios crecidos", "dolor en ganglios", "linfoma indolente"]'),
('C82.01', 'Linfoma folicular grado I, ganglios linfáticos de cabeza, cara y cuello', 'Sin especificar', '["bolitas en el cuello", "ganglios inflamados en la cara", "bultos bajo la mandíbula", "ganglios del cuello hinchados", "cáncer en el cuello", "linfoma en el cuello", "bolitas detrás de la oreja", "hinchazón en la garganta", "ganglios del cuello", "linfadenopatía cervical", "bolitas en la nuca"]'),
('C82.02', 'Linfoma folicular grado I, ganglios linfáticos intratorácicos', 'Sin especificar', '["ganglios en el pecho", "linfoma en el tórax", "dolor en el pecho", "falta de aire", "ganglios en los pulmones", "opresión en el pecho", "tos persistente", "linfadenopatía mediastínica", "masa en el tórax", "cáncer pulmonar linfático"]'),
('C82.03', 'Linfoma folicular grado I, ganglios linfáticos intraabdominales', 'Sin especificar', '["bolitas en la panza", "dolor de guata", "hinchazón abdominal", "linfoma en el abdomen", "ganglios inflamados en el estómago", "dolor de barriga", "masa abdominal", "ganglios intraabdominales", "dolor en el vientre", "panza hinchada"]'),
('C82.04', 'Linfoma folicular grado I, ganglios linfáticos de axila y extremidad superior', 'Sin especificar', '["bolitas en la axila", "ganglios bajo el brazo", "bultos en la axila", "linfoma axilar", "ganglios inflamados en el brazo", "hinchazón en la axila", "bolita en el sobaco", "linfadenopatía axilar", "cáncer de axila"]'),
('C82.05', 'Linfoma folicular grado I, ganglios linfáticos de región inguinal y miembro inferior', 'Sin especificar', '["bolitas en la ingle", "ganglios inflamados en la entrepierna", "bultos en la ingle", "linfoma inguinal", "hinchazón en la ingle", "bolitas en la pierna", "ganglios de la ingle", "ganglios inflamados en la parte baja", "dolor en la ingle"]'),
('C82.06', 'Linfoma folicular grado I, ganglios linfáticos intrapélvicos', 'Sin especificar', '["ganglios en la pelvis", "linfoma pélvico", "dolor en la pelvis", "bultos internos en la pelvis", "ganglios inflamados en la zona pélvica", "dolor en la parte baja de la espalda", "masa pélvica", "linfadenopatía pélvica"]'),
('C82.07', 'Linfoma folicular grado I, bazo', 'Sin especificar', '["bazo inflamado", "esplenomegalia", "dolor en el costado izquierdo", "bazo grande", "dolor de bazo", "linfoma en el bazo", "hinchazón bajo las costillas", "dolor abdominal alto", "esplenomegalia linfomatosa"]'),
('C82.08', 'Linfoma folicular grado I, ganglios linfáticos de localizaciones múltiples', 'Sin especificar', '["linfoma generalizado", "ganglios inflamados por todo el cuerpo", "muchas bolitas en el cuerpo", "linfadenopatía múltiple", "cáncer linfático avanzado", "ganglios por todas partes", "bolitas en cuello axilas e ingle", "linfoma sistémico"]'),
('C82.09', 'Linfoma folicular grado I, localizaciones extraganglionares y de órganos sólidos', 'Sin especificar', '["linfoma fuera de los ganglios", "cáncer en órganos", "linfoma extraganglionar", "masa en órganos", "afectación a órganos sólidos", "cáncer diseminado", "linfoma en tejidos"]'),
('C82.0A', 'Linfoma folicular grado I, en remisión', 'Sin especificar', '["linfoma curado", "remisión de cáncer", "linfoma bajo control", "cáncer en remisión", "ya no tengo linfoma", "linfoma controlado", "sin síntomas de linfoma", "seguimiento oncológico"]'),
('C82.10', 'Linfoma folicular grado II, localización no especificada', 'Sin especificar', '["linfoma grado 2", "cáncer de ganglios nivel 2", "linfoma folicular moderado", "ganglios inflamados", "bolitas en el cuerpo", "cáncer linfático", "linfoma folicular grado II"]'),
('C82.11', 'Linfoma folicular grado II, ganglios linfáticos de cabeza, cara y cuello', 'Sin especificar', '["bolitas en el cuello grado 2", "ganglios cuello linfoma", "hinchazón cara y cuello", "linfoma grado 2 cuello", "bultos cervicales"]'),
('C82.12', 'Linfoma folicular grado II, ganglios linfáticos intratorácicos', 'Sin especificar', '["linfoma tórax grado 2", "ganglios pecho inflamados", "masa mediastino", "linfoma grado 2 pulmones", "opresión torácica"]'),
('C82.13', 'Linfoma folicular grado II, ganglios linfáticos intraabdominales', 'Sin especificar', '["linfoma abdominal grado 2", "ganglios panza inflamados", "dolor abdominal linfoma", "bultos en el abdomen", "linfoma grado 2 estómago"]'),
('C82.14', 'Linfoma folicular grado II, ganglios linfáticos de axila y extremidad superior', 'Sin especificar', '["linfoma axilar grado 2", "bolitas axila nivel 2", "ganglios brazo inflamados", "cáncer axilar nivel 2", "inflamación axilar"]'),
('C82.15', 'Linfoma folicular grado II, ganglios linfáticos de región inguinal y miembro inferior', 'Sin especificar', '["linfoma inguinal grado 2", "bolitas en la ingle nivel 2", "ganglios pierna inflamados", "bultos ingle grado 2", "linfadenopatía inguinal"]'),
('C82.16', 'Linfoma folicular grado II, ganglios linfáticos intrapélvicos', 'Sin especificar', '["linfoma pélvico grado 2", "ganglios pelvis nivel 2", "dolor pélvico linfoma", "cáncer pélvico grado 2"]'),
('C82.17', 'Linfoma folicular grado II, bazo', 'Sin especificar', '["linfoma en el bazo grado 2", "esplenomegalia grado 2", "dolor costado izquierdo grado 2", "bazo hinchado"]'),
('C82.18', 'Linfoma folicular grado II, ganglios linfáticos de localizaciones múltiples', 'Sin especificar', '["linfoma grado 2 diseminado", "ganglios múltiples grado 2", "linfoma sistémico nivel 2", "muchos ganglios inflamados"]'),
('C82.19', 'Linfoma folicular grado II, localizaciones extraganglionares y de órganos sólidos', 'Sin especificar', '["linfoma grado 2 órganos", "afectación visceral grado 2", "linfoma extraganglionar nivel 2"]'),
('C82.1A', 'Linfoma folicular grado II, en remisión', 'Sin especificar', '["linfoma grado 2 en remisión", "cáncer nivel 2 controlado", "remisión completa", "sin rastro de linfoma grado 2"]'),
('C82.20', 'Linfoma folicular grado III, no especificado, localización no especificada', 'Sin especificar', '["linfoma grado 3", "linfoma folicular avanzado", "cáncer de ganglios grado 3", "linfoma agresivo folicular", "bolitas por todo el cuerpo"]'),
('C82.21', 'Linfoma folicular grado III, no especificado, ganglios linfáticos de cabeza, cara y cuello', 'Sin especificar', '["linfoma cuello grado 3", "bolitas grandes en cuello", "bultos cuello grado 3", "linfadenopatía cervical avanzada"]'),
('C82.22', 'Linfoma folicular grado III, no especificado, ganglios linfáticos intratorácicos', 'Sin especificar', '["linfoma tórax grado 3", "masa torácica grado 3", "cáncer tórax avanzado", "ganglios pecho grandes"]'),
('C82.23', 'Linfoma folicular grado III, no especificado, ganglios linfáticos intraabdominales', 'Sin especificar', '["linfoma abdominal grado 3", "bultos abdominales grandes", "ganglios barriga grado 3", "dolor abdominal intenso"]'),
('C82.24', 'Linfoma folicular grado III, no especificado, ganglios linfáticos de axila y extremidad superior', 'Sin especificar', '["linfoma axilar grado 3", "bolitas axila grandes", "bultos axilares grado 3", "ganglios axila inflamados"]'),
('C82.25', 'Linfoma folicular grado III, no especificado, ganglios linfáticos de región inguinal y extremidad inferior', 'Sin especificar', '["linfoma inguinal grado 3", "bultos ingle grandes", "bolitas entrepierna grado 3", "ganglios ingle avanzados"]'),
('C82.26', 'Linfoma folicular grado III, no especificado, ganglios intrapélvicos', 'Sin especificar', '["linfoma pélvico grado 3", "ganglios pelvis grandes", "cáncer pélvico avanzado", "dolor pelvis grado 3"]'),
('C82.27', 'Linfoma folicular grado III, no especificado, bazo', 'Sin especificar', '["linfoma en el bazo grado 3", "esplenomegalia severa", "bazo muy grande", "dolor bazo grado 3"]'),
('C82.28', 'Linfoma folicular grado III, no especificado, ganglios linfáticos de localizaciones múltiples', 'Sin especificar', '["linfoma grado 3 avanzado", "ganglios por todo el cuerpo grado 3", "linfoma sistémico agresivo"]'),
('C82.29', 'Linfoma folicular grado III, no especificado, localizaciones extraganglionares y de órganos sólidos', 'Sin especificar', '["linfoma grado 3 órganos", "linfoma extraganglionar avanzado", "cáncer órganos sólidos", "metástasis linfática"]'),
('C82.2A', 'Linfoma folicular grado III, no especificado, en remisión', 'Sin especificar', '["linfoma grado 3 en remisión", "remisión de cáncer agresivo", "superviviente de linfoma grado 3"]'),
('C82.30', 'Linfoma folicular grado IIIa, localización no especificada', 'Sin especificar', '["linfoma folicular 3a", "cáncer linfático 3a", "linfoma 3a", "grado 3a linfoma"]'),
('C82.31', 'Linfoma folicular grado IIIa, ganglios linfáticos de cabeza, cara y cuello', 'Sin especificar', '["linfoma 3a cuello", "ganglios cara 3a", "bultos cervicales 3a"]'),
('C82.32', 'Linfoma folicular grado IIIa, ganglios linfáticos intratorácicos', 'Sin especificar', '["linfoma tórax 3a", "ganglios mediastino 3a", "bultos pecho 3a"]'),
('C82.33', 'Linfoma folicular grado IIIa, ganglios linfáticos intraabdominales', 'Sin especificar', '["linfoma abdomen 3a", "ganglios panza 3a", "dolor abdominal 3a"]'),
('C82.34', 'Linfoma folicular grado IIIa, ganglios linfáticos de axila y extremidad superior', 'Sin especificar', '["linfoma axilar 3a", "bultos axila 3a", "ganglios axilares 3a"]'),
('C82.35', 'Linfoma folicular grado IIIa, ganglios linfáticos de región inguinal y extremidad inferior', 'Sin especificar', '["linfoma inguinal 3a", "ganglios ingle 3a", "bultos ingle 3a"]'),
('C82.36', 'Linfoma folicular grado IIIa, ganglios linfáticos intrapélvicos', 'Sin especificar', '["linfoma pélvico 3a", "ganglios pelvis 3a", "bultos pélvicos 3a"]'),
('C82.37', 'Linfoma folicular grado IIIa, bazo', 'Sin especificar', '["linfoma bazo 3a", "esplenomegalia 3a", "dolor bazo 3a"]'),
('C82.38', 'Linfoma folicular grado IIIa, ganglios linfáticos de localizaciones múltiples', 'Sin especificar', '["linfoma 3a generalizado", "ganglios múltiples 3a"]'),
('C82.39', 'Linfoma folicular grado IIIa, localizaciones extraganglionares y de órganos sólidos', 'Sin especificar', '["linfoma 3a órganos", "linfoma extraganglionar 3a"]'),
('C82.3A', 'Linfoma folicular grado IIIa, en remisión', 'Sin especificar', '["linfoma 3a en remisión", "remisión 3a", "controlado 3a"]'),
('C82.40', 'Linfoma folicular grado IIIb, localización no especificada', 'Sin especificar', '["linfoma folicular 3b", "cáncer linfático 3b", "linfoma 3b agresivo", "linfoma folicular grado IIIb"]'),
('C82.41', 'Linfoma folicular grado IIIb, ganglios linfáticos de cabeza, cara y cuello', 'Sin especificar', '["linfoma cuello 3b", "bultos cervicales 3b", "ganglios cara 3b"]'),
('C82.42', 'Linfoma folicular grado IIIb, ganglios linfáticos intratorácicos', 'Sin especificar', '["linfoma tórax 3b", "ganglios mediastino 3b", "masa pecho 3b"]'),
('C82.43', 'Linfoma folicular grado IIIb, ganglios linfáticos intraabdominales', 'Sin especificar', '["linfoma abdomen 3b", "ganglios barriga 3b", "dolor abdomen 3b"]'),
('C82.44', 'Linfoma folicular grado IIIb, ganglios linfáticos de axila y extremidad superior', 'Sin especificar', '["linfoma axilar 3b", "bultos axila 3b", "ganglios axilares 3b"]'),
('C82.45', 'Linfoma folicular grado IIIb, ganglios linfáticos de región inguinal y extremidad inferior', 'Sin especificar', '["linfoma inguinal 3b", "bultos ingle 3b", "ganglios ingle 3b"]'),
('C82.46', 'Linfoma folicular grado IIIb, ganglios linfáticos intrapélvicos', 'Sin especificar', '["linfoma pélvico 3b", "ganglios pelvis 3b", "bultos pelvis 3b"]'),
('C82.47', 'Linfoma folicular grado IIIb, bazo', 'Sin especificar', '["linfoma bazo 3b", "esplenomegalia 3b", "dolor bazo 3b"]'),
('C82.48', 'Linfoma folicular grado IIIb, ganglios linfáticos de localizaciones múltiples', 'Sin especificar', '["linfoma 3b diseminado", "ganglios múltiples 3b"]'),
('C82.49', 'Linfoma folicular grado IIIb, localizaciones extraganglionares y de órganos sólidos', 'Sin especificar', '["linfoma 3b órganos", "linfoma extraganglionar 3b"]'),
('C82.4A', 'Linfoma folicular grado IIIb, en remisión', 'Sin especificar', '["linfoma 3b en remisión", "remisión 3b"]'),
('C82.50', 'Linfoma difuso centrofolicular, localización no especificada', 'Sin especificar', '["linfoma centrofolicular", "cáncer linfático difuso", "linfoma difuso", "linfoma no folicular clásico"]'),
('C82.51', 'Linfoma difuso centrofolicular, ganglios linfáticos de cabeza, cara y cuello', 'Sin especificar', '["linfoma difuso cuello", "bolitas cuello difuso", "ganglios cara difuso"]'),
('C82.52', 'Linfoma difuso centrofolicular, ganglios linfáticos intratorácicos', 'Sin especificar', '["linfoma difuso tórax", "ganglios pecho difuso"]'),
('C82.53', 'Linfoma difuso centrofolicular, ganglios linfáticos intraabdominales', 'Sin especificar', '["linfoma difuso abdomen", "dolor abdomen difuso"]'),
('C82.54', 'Linfoma difuso centrofolicular, ganglios linfáticos de axila y extremidad superior', 'Sin especificar', '["linfoma difuso axila", "bolitas axila difuso"]'),
('C82.55', 'Linfoma difuso centrofolicular, ganglios linfáticos de región inguinal y extremidad inferior', 'Sin especificar', '["linfoma difuso ingle", "ganglios ingle difuso"]'),
('C82.56', 'Linfoma difuso centrofolicular, ganglios linfáticos intrapélvicos', 'Sin especificar', '["linfoma difuso pelvis", "ganglios pelvis difuso"]'),
('C82.57', 'Linfoma difuso centrofolicular, bazo', 'Sin especificar', '["linfoma difuso bazo", "esplenomegalia difusa"]'),
('C82.58', 'Linfoma difuso centrofolicular, ganglios linfáticos de localizaciones múltiples', 'Sin especificar', '["linfoma difuso generalizado", "ganglios múltiples difuso"]'),
('C82.59', 'Linfoma difuso centrofolicular, localizaciones extraganglionares y de órganos sólidos', 'Sin especificar', '["linfoma difuso órganos", "linfoma difuso extraganglionar"]'),
('C82.5A', 'Linfoma difuso centrofolicular, en remisión', 'Sin especificar', '["linfoma difuso en remisión", "remisión difuso"]'),
('C82.60', 'Linfoma centrofolicular cutáneo, localización no especificada', 'Sin especificar', '["linfoma en la piel", "cáncer de piel linfático", "bultos en la piel", "linfoma cutáneo", "lesiones en la piel", "manchas en la piel linfoma"]'),
('C82.61', 'Linfoma centrofolicular cutáneo, ganglios linfáticos de cabeza, cara y cuello', 'Sin especificar', '["linfoma cutáneo cuello", "bolitas cuello piel", "ganglios cara piel"]'),
('C82.62', 'Linfoma centrofolicular cutáneo, ganglios linfáticos intratorácicos', 'Sin especificar', '["linfoma cutáneo tórax", "ganglios pecho cutáneo"]'),
('C82.63', 'Linfoma centrofolicular cutáneo, ganglios linfáticos intraabdominales', 'Sin especificar', '["linfoma cutáneo abdomen", "dolor abdomen cutáneo"]'),
('C82.64', 'Linfoma centrofolicular cutáneo, ganglios linfáticos de axila y extremidad superior', 'Sin especificar', '["linfoma cutáneo axila", "bolitas axila piel"]'),
('C82.65', 'Linfoma centrofolicular cutáneo, ganglios linfáticos de región inguinal y extremidad inferior', 'Sin especificar', '["linfoma cutáneo ingle", "ganglios ingle piel"]'),
('C82.66', 'Linfoma centrofolicular cutáneo, ganglios linfáticos intrapélvicos', 'Sin especificar', '["linfoma cutáneo pelvis", "ganglios pelvis piel"]'),
('C82.67', 'Linfoma centrofolicular cutáneo, bazo', 'Sin especificar', '["linfoma cutáneo bazo", "esplenomegalia cutánea"]'),
('C82.68', 'Linfoma centrofolicular cutáneo, ganglios linfáticos de localizaciones múltiples', 'Sin especificar', '["linfoma cutáneo generalizado", "ganglios múltiples piel"]'),
('C82.69', 'Linfoma centrofolicular cutáneo, localizaciones extraganglionares y de órganos sólidos', 'Sin especificar', '["linfoma cutáneo órganos", "linfoma extraganglionar piel"]'),
('C82.6A', 'Linfoma centrofolicular cutáneo, en remisión', 'Sin especificar', '["linfoma cutáneo en remisión", "remisión piel"]'),
('C82.80', 'Otros tipos de linfoma folicular, localización no especificada', 'Sin especificar', '["otro linfoma folicular", "linfoma folicular raro", "cáncer ganglios otros"]'),
('C82.81', 'Otros tipos de linfoma folicular, ganglios linfáticos de cabeza, cara y cuello', 'Sin especificar', '["linfoma folicular cuello", "bolitas cuello otros"]'),
('C82.82', 'Otros tipos de linfoma folicular, ganglios linfáticos intratorácicos', 'Sin especificar', '["linfoma folicular tórax", "ganglios pecho otros"]'),
('C82.83', 'Otros tipos de linfoma folicular, ganglios linfáticos intraabdominales', 'Sin especificar', '["linfoma folicular abdomen", "dolor abdomen otros"]'),
('C82.84', 'Otros tipos de linfoma folicular, ganglios linfáticos de axila y extremidad superior', 'Sin especificar', '["linfoma folicular axila", "bolitas axila otros"]'),
('C82.85', 'Otros tipos de linfoma folicular, ganglios linfáticos de región inguinal y extremidad inferior', 'Sin especificar', '["linfoma folicular ingle", "ganglios ingle otros"]'),
('C82.86', 'Otros tipos de linfoma folicular, ganglios linfáticos intrapélvicos', 'Sin especificar', '["linfoma folicular pelvis", "ganglios pelvis otros"]'),
('C82.87', 'Otros tipos de linfoma folicular, bazo', 'Sin especificar', '["linfoma folicular bazo", "esplenomegalia otros"]'),
('C82.88', 'Otros tipos de linfoma folicular, ganglios linfáticos de localizaciones múltiples', 'Sin especificar', '["linfoma folicular generalizado", "ganglios múltiples otros"]'),
('C82.89', 'Otros tipos de linfoma folicular, localizaciones extraganglionares y de órganos sólidos', 'Sin especificar', '["linfoma folicular órganos", "linfoma folicular extraganglionar"]'),
('C82.8A', 'Otros tipos de linfoma folicular, en remisión', 'Sin especificar', '["linfoma folicular en remisión", "remisión folicular otros"]'),
('C82.90', 'Linfoma folicular, no especificado, localización no especificada', 'Sin especificar', '["linfoma folicular sin especificar", "cáncer linfoma folicular", "ganglios folicular"]'),
('C82.91', 'Linfoma folicular, no especificado, ganglios linfáticos de cabeza, cara y cuello', 'Sin especificar', '["linfoma folicular cuello", "bolitas cuello no especificado"]'),
('C82.92', 'Linfoma folicular, no especificado, ganglios linfáticos intratorácicos', 'Sin especificar', '["linfoma folicular tórax", "ganglios pecho no especificado"]'),
('C82.93', 'Linfoma folicular, no especificado, ganglios linfáticos intraabdominales', 'Sin especificar', '["linfoma folicular abdomen", "dolor abdomen no especificado"]'),
('C82.94', 'Linfoma folicular, no especificado, ganglios linfáticos de axila y extremidad superior', 'Sin especificar', '["linfoma folicular axila", "bolitas axila no especificado"]'),
('C82.95', 'Linfoma folicular, no especificado, ganglios linfáticos de región inguinal y extremidad inferior', 'Sin especificar', '["linfoma folicular ingle", "ganglios ingle no especificado"]'),
('C82.96', 'Linfoma folicular, no especificado, ganglios linfáticos intrapélvicos', 'Sin especificar', '["linfoma folicular pelvis", "ganglios pelvis no especificado"]'),
('C82.97', 'Linfoma folicular, no especificado, bazo', 'Sin especificar', '["linfoma folicular bazo", "esplenomegalia no especificada"]'),
('C82.98', 'Linfoma folicular, no especificado, ganglios linfáticos de localizaciones múltiples', 'Sin especificar', '["linfoma folicular generalizado", "ganglios múltiples no especificado"]'),
('C82.99', 'Linfoma folicular, no especificado, localizaciones extraganglionares y de órganos sólidos', 'Sin especificar', '["linfoma folicular órganos", "linfoma folicular extraganglionar"]'),
('C82.9A', 'Linfoma folicular, no especificado, en remisión', 'Sin especificar', '["linfoma folicular en remisión", "remisión folicular no especificada"]');
