INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N07.0', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con anomalía glomerular mínima', 'Sin especificar', '["fallo renal genético", "problemas de riñón hereditarios", "orina con espuma", "orina espumosa", "hinchazón en la cara", "edema renal", "proteínas en la orina", "proteinuria hereditaria", "daño en glomérulos", "insuficiencia renal familiar", "dolor de riñones", "enfermedad renal de nacimiento", "nefritis hereditaria", "síndrome nefrótico familiar", "glomérulos dañados"]'),
('N07.1', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con lesiones glomerulares focales y segmentarias', 'Sin especificar', '["esclerosis focal y segmentaria", "daño segmentario riñón", "cicatrices en los riñones", "orina oscura", "hinchazón de piernas", "edema en pies", "insuficiencia renal genética", "problemas filtrado renal", "mal funcionamiento renal", "proteína alta en orina", "nefropatía familiar", "glomérulos con cicatrices", "enfermedad renal hereditaria", "retención de líquidos", "dolor lumbar renal"]'),
('N07.2', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con glomerulonefritis membranosa difusa', 'Sin especificar', '["nefritis membranosa", "riñones inflamados", "filtro renal grueso", "proteína en orina", "orina turbia", "hinchazón generalizada", "síndrome nefrótico", "daño renal hereditario", "inflamación de glomérulos", "problemas autoinmunes riñón", "fallo de riñón crónico", "orinar poco", "cansancio por riñón", "orina espumosa", "enfermedad glomerular"]'),
('N07.3', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con glomerulonefritis proliferativa mesangial difusa', 'Sin especificar', '["nefritis mesangial", "inflamación mesangio", "riñones enfermos", "sangre en la orina", "hematuria hereditaria", "dolor de espalda bajo", "proteínas en orina", "daño glomerular difuso", "problema renal genético", "orina rojiza", "hinchazón matutina", "insuficiencia de riñones", "glomerulonefritis familiar", "edema palpebral", "fallo en el filtrado"]'),
('N07.4', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con glomerulonefritis proliferativa endocapilar difusa', 'Sin especificar', '["nefritis endocapilar", "riñón inflamado agudo", "post-infección renal", "hematuria", "orina color coca-cola", "orina oscura", "hipertensión renal", "presión alta por riñón", "hinchazón cara", "edema en ojos", "riñones que no filtran", "enfermedad renal heredada", "inflamación glomérulos", "problema genético riñón", "dolor al orinar"]'),
('N07.5', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con glomerulonefritis mesangiocapilar difusa', 'Sin especificar', '["nefritis membranoproliferativa", "problema riñón genético", "orina con sangre", "orina espumosa", "edemas en el cuerpo", "presión arterial alta", "insuficiencia renal heredada", "daño glomerular severo", "riñones dañados", "proteínas orina", "fatiga renal", "inflamación renal difusa", "falla en los filtros renales", "dolor riñones", "problemas de riñón crónicos"]'),
('N07.6', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con enfermedad por depósitos densos', 'Sin especificar', '["enfermedad depósitos densos", "nefropatía C3", "depósitos en riñón", "riñón con depósitos", "daño glomerular hereditario", "orina con proteínas", "orina turbia", "hinchazón pies y piernas", "insuficiencia renal", "fallo en la filtración", "enfermedad genética riñón", "problemas de riñones", "orinar con espuma", "inflamación glomérulos", "dolor renal"]'),
('N07.7', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con glomerulonefritis semilunar difusa', 'Sin especificar', '["nefritis rápidamente progresiva", "creciente renal", "nefritis semilunar", "fallo renal rápido", "pérdida de función renal", "orina escasa", "oliguria", "orina con sangre", "dolor de riñones intenso", "hinchazón severa", "edemas", "presión alta", "problema riñón genético", "inflamación severa riñón", "insuficiencia renal grave"]'),
('N07.8', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con otras lesiones morfológicas', 'Sin especificar', '["lesión renal hereditaria", "daño glomerular específico", "riñones afectados", "problema genético renal", "proteína en orina", "sangre en la orina", "edema", "hinchazón", "orina anormal", "fallo de riñón", "nefropatía familiar rara", "insuficiencia renal", "cambios en los glomérulos", "dolor lumbar", "filtración renal baja"]'),
('N07.9', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con lesiones morfológicas no especificados', 'Sin especificar', '["nefropatía hereditaria no especificada", "enfermedad renal genética", "problema de riñón desconocido", "orina rara", "proteínas elevadas", "insuficiencia de riñones", "dolor en el costado", "hinchazón corporal", "fallo renal familiar", "riñones sin especificar", "daño en los riñones", "orina espumosa", "edema inexplicable", "problemas de filtrado", "mal renal hereditario"]'),
('N07.A', 'Nefropatía hereditaria, no clasificada bajo otro concepto, con glomerulonefritis C3', 'Sin especificar', '["nefritis C3", "glomerulopatía C3", "problema complemento riñón", "depósitos de C3", "riñón inflamado C3", "enfermedad hereditaria riñón", "daño glomerular", "orina con proteínas", "hinchazón por riñón", "fallo renal hereditario", "edemas", "orinar con espuma", "insuficiencia renal", "problemas autoinmunes genéticos", "dolor riñones"]');
