INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('R68.0', 'Hipotermia, no asociada a temperatura ambiental baja', 'Sin especificar', '["cuerpo helado", "tener frío constante", "temperatura corporal baja", "enfriamiento interno", "manos y pies congelados", "tiritar sin frío", "bajada de calor corporal", "pálido y frío", "hipotermia primaria", "escalofrío interno", "falta de calor en el cuerpo", "cuerpo frío", "sensor térmico bajo", "síndrome de enfriamiento", "baja temperatura sin causa ambiental"]'),
('R68.11', 'Llanto excesivo del lactante (bebé)', 'Sin especificar', '["bebé llorón", "llanto inconsolable", "bebé que no para de llorar", "berrinche de bebé", "llanto por cólicos", "bebé no se calma", "chillar constante", "bebé llora mucho", "gritos de bebé", "llanto persistente", "bebé irritable", "llanto de angustia", "bebé malcriado por llanto", "llanto desmedido", "griterío de recién nacido"]'),
('R68.12', 'Bebé irritable', 'Sin especificar', '["bebé fastidiado", "bebé molesto", "bebé inquieto", "bebé que no se deja consolar", "guagua mañosa", "bebé enojado", "niño alterado", "mal humor de bebé", "bebé insoportable", "bebé que se arquea", "bebé que pelea el pecho", "bebé inconforme", "bebé que no descansa", "llanto por molestia", "bebé de genio difícil"]'),
('R68.13', 'Suceso que aparentemente amenaza la vida del lactante [ALTE]', 'Sin especificar', '["bebé dejó de respirar", "apnea de bebé", "susto respiratorio", "bebé se puso azul", "episodio de asfixia", "bebé pálido y flácido", "emergencia respiratoria lactante", "cambio de color bebé", "desmayo de bebé", "episodio súbito de riesgo", "bebé que se queda tieso", "crisis de color", "paro respiratorio transitorio", "evento crítico lactante", "bebé se puso morado"]'),
('R68.19', 'Otros síntomas inespecíficos propios del lactante', 'Sin especificar', '["bebé raro", "bebé decaído", "malestar general bebé", "bebé sin energía", "síntomas raros en bebés", "bebé no actúa normal", "cambio de comportamiento bebé", "bebé sin causa aparente", "bebé con síntomas vagos", "bebé raro hoy", "problemas inespecíficos lactante", "no es el mismo bebé", "anormalidad en recién nacido", "signos de alarma bebé", "bebito indispuesto"]'),
('R68.2', 'Sequedad de boca, no especificada', 'Sin especificar', '["boca seca", "xerostomía", "lengua pastosa", "boca pastosa", "sed constante", "falta de saliva", "boca pegajosa", "boca de trapo", "sentir la boca arenosa", "deshidratación oral", "boca reseca", "lengua seca", "labios partidos", "boca deshidratada", "falta de humedad en la boca"]'),
('R68.3', 'Dedos en palillo de tambor', 'Sin especificar', '["dedos hipocráticos", "dedos hinchados en las puntas", "uñas en vidrio de reloj", "deformidad en dedos", "dedos gordos en las yemas", "acropaquia", "uñas curvas", "falanges inflamadas", "dedos con forma de palillo", "uñas que se doblan", "cambio en la forma de los dedos", "dedos bulbosos", "engrosamiento de las puntas de los dedos", "dedos en baqueta", "deformación de los dedos de la mano"]'),
('R68.81', 'Saciedad precoz', 'Sin especificar', '["llenura rápida", "me lleno con poco", "poca hambre", "no puedo terminar de comer", "sentirse lleno enseguida", "estómago cerrado", "empacho rápido", "inapetencia", "sentir que la comida no baja", "saciedad al empezar a comer", "estómago inflamado al comer", "falta de apetito", "sensación de plenitud gástrica", "no tengo hambre", "estómago lleno con dos bocados"]'),
('R68.82', 'Disminución de la libido', 'Sin especificar', '["falta de deseo sexual", "no tengo ganas", "bajón de líbido", "pérdida de ganas", "poca chispa", "sin apetito sexual", "ausencia de deseo", "frialdad sexual", "poca libido", "disminución del deseo", "no tengo ganas de nada", "impotencia sexual", "bajo deseo sexual", "indiferencia sexual", "desgano sexual"]'),
('R68.83', 'Escalofríos (sin fiebre)', 'Sin especificar', '["chuchos de frío", "tembladera", "tiritones", "escalofríos sin temperatura", "cuerpo con temblor", "tener un soponcio frío", "me sacude el frío", "tiritar sin estar enfermo", "frío que recorre el cuerpo", "escalofrío repentino", "tener la carne de gallina", "temblor corporal", "sensación de frío extremo", "escalofríos pasajeros", "entrar en chucho"]'),
('R68.84', 'Dolor de mandíbula', 'Sin especificar', '["dolor de quijada", "dolor en los huesos de la cara", "mandíbula trabada", "dolor al masticar", "tensión en la mandíbula", "dolor de oído y mandíbula", "bruxismo", "crujido de mandíbula", "dolor de dientes y cara", "mandíbula cansada", "molestia al abrir la boca", "dolor facial", "inflamación de mandíbula", "dolor articular mandibular", "mandíbula que hace clic"]'),
('R68.89', 'Otros síntomas y signos generales', 'Sin especificar', '["sentirse mal", "cuerpo cortado", "malestar general", "decaimiento", "sentirse raro", "bajón", "sin fuerzas", "apatía", "sentirse de mal cuerpo", "estar indispuesto", "cansancio general", "me siento flojo", "sentirse enfermo sin saber qué es", "postración", "debilidad corporal"]');
