INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S91.001A', 'Herida abierta no especificada de tobillo derecho, contacto inicial', 'Sin especificar', '["corte en el tobillo", "tajo en el tobillo", "rajadura", "sangrando el tobillo", "herida profunda tobillo derecho", "abertura en la piel", "desolladura tobillo", "me corté el tobillo", "tengo una cortada en el tobillo", "herida mal hecha", "lesión abierta tobillo", "tajo en la articulación del pie", "urgencia tobillo", "sangre en el tobillo", "traumatismo abierto"]'),
('S91.001D', 'Herida abierta no especificada de tobillo derecho, contacto sucesivo', 'Sin especificar', '["curación de herida en tobillo", "seguimiento corte tobillo", "la herida del tobillo sigue abierta", "revisión de tajo en tobillo", "limpieza de herida tobillo derecho", "cambio de vendas tobillo", "infección en corte de tobillo", "herida que no cierra tobillo", "cuidado posterior herida tobillo", "control de sutura tobillo", "seguimiento médico tobillo derecho", "aún me duele el corte del tobillo", "cita de control herida", "evolución de herida tobillo"]'),
('S91.001S', 'Herida abierta no especificada de tobillo derecho, secuela', 'Sin especificar', '["cicatriz en el tobillo", "secuela de corte tobillo", "queloide tobillo", "dolor crónico tras herida tobillo", "rigidez tobillo por vieja cicatriz", "complicación herida antigua tobillo", "problemas al caminar por herida vieja", "marca de corte en tobillo", "atrofia por cicatriz", "molestias en tobillo antiguo", "secuela de traumatismo derecho", "pérdida de sensibilidad tobillo", "cicatriz queloide tobillo"]'),
('S91.002A', 'Herida abierta no especificada de tobillo izquierdo, contacto inicial', 'Sin especificar', '["corte en el tobillo izquierdo", "tajo en tobillo izquierdo", "herida sangrante tobillo izquierdo", "golpe con corte en tobillo", "abertura piel tobillo izquierdo", "me rajé el tobillo", "desolladura tobillo izquierdo", "lesión abierta", "accidente en el tobillo", "urgencia tobillo izquierdo", "tajo profundo tobillo", "sangre saliendo del tobillo", "herida reciente", "traumatismo en pie izquierdo"]'),
('S91.002D', 'Herida abierta no especificada de tobillo izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento herida tobillo izquierdo", "curación de tajo izquierdo", "revisión de puntos tobillo izquierdo", "limpieza herida tobillo", "la cortada no cierra", "control de infección tobillo", "cambio de gasas tobillo", "me duele el tobillo después del corte", "cita de revisión", "progreso de cicatrización tobillo", "seguimiento de herida abierta", "dolor en tobillo izquierdo tras curación", "control médico tobillo", "evolución de la herida"]'),
('S91.002S', 'Herida abierta no especificada de tobillo izquierdo, secuela', 'Sin especificar', '["cicatriz tobillo izquierdo", "secuela de corte en tobillo", "molestias crónicas tobillo", "queloide tobillo izquierdo", "cicatrización defectuosa", "dolor post-traumático tobillo", "rigidez por cicatriz", "problemas de movilidad tobillo", "marca de herida antigua", "secuelas de accidente", "fibrosis en tobillo", "adherencias de tejido tobillo", "cicatriz abultada"]'),
('S91.011A', 'Desgarro sin cuerpo extraño de tobillo derecho, contacto inicial', 'Sin especificar', '["desgarro piel tobillo", "piel rasgada tobillo derecho", "desollón tobillo", "herida por roce fuerte", "piel desprendida tobillo", "raspón profundo tobillo", "desgarre en el pie", "lesión de tejidos blandos tobillo", "abertura sin objeto clavado", "desgarro cutáneo", "me desgarré el tobillo", "traumatismo tobillo sin objeto", "herida de piel tobillo", "raspadura profunda tobillo"]'),
('S91.011D', 'Desgarro sin cuerpo extraño de tobillo derecho, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro tobillo", "curación de piel rasgada", "control de desgarro tobillo derecho", "revisión de piel en tobillo", "cicatrización de desgarro", "cambio de vendaje", "limpieza de herida por desgarro", "seguimiento evolución de herida", "dolor por piel desgarrosa", "cita de control piel", "observación de desgarro", "tratamiento de herida desgarro", "revisión de curación", "progreso del desgarro"]'),
('S91.011S', 'Desgarro sin cuerpo extraño de tobillo derecho, secuela', 'Sin especificar', '["cicatriz de desgarro tobillo", "piel marcada en tobillo", "secuela de desgarro", "fibrosis de la piel", "cicatrización queloide tobillo", "atrofia cutánea tobillo", "molestias en la zona del desgarro", "piel sensible tras desgarro", "problemas de piel tobillo", "secuelas de lesión cutánea", "marca permanente", "remodelación de tejido", "cicatriz antigua tobillo"]'),
('S91.101A', 'Herida abierta no especificada de dedo gordo del pie derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["corte en el dedo gordo", "herida dedo gordo pie", "tajo en el primer dedo del pie", "me corté el dedo del pie", "herida abierta dedo pie derecho", "urgencia dedo del pie", "corte en el ortejo mayor", "lesión en dedo gordo pie", "abertura piel dedo pie", "sangre en el dedo gordo", "herida sin daño en uña", "traumatismo dedo gordo", "me hice una herida en el dedo gordo", "corte superficial o profundo dedo"]'),
('S91.101D', 'Herida abierta no especificada de dedo gordo del pie derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["curación dedo gordo", "seguimiento herida dedo del pie", "revisión de puntos dedo gordo", "limpieza herida ortejo mayor", "control de herida pie", "el dedo no cierra bien", "cambio de curas dedo del pie", "infección en dedo gordo", "seguimiento médico dedo pie", "cita de revisión dedo", "observación herida abierta", "evolución corte dedo", "dolor en dedo tras curación", "control de sutura pie"]'),
('S91.101S', 'Herida abierta no especificada de dedo gordo del pie derecho, sin daños en la uña, secuela', 'Sin especificar', '["cicatriz dedo gordo pie", "secuela de corte dedo del pie", "problemas dedo gordo por herida antigua", "queloide en el dedo del pie", "dolor al caminar por cicatriz", "rigidez dedo gordo", "cicatrización dolorosa", "marca en el dedo gordo", "secuela de traumatismo pie", "fibrosis en ortejo mayor", "pérdida de sensibilidad dedo", "cicatriz queloide pie", "secuelas post-herida"]'),
('S91.351A', 'Mordedura abierta del pie derecho, contacto inicial', 'Sin especificar', '["mordida en el pie", "me mordió un perro el pie", "herida por mordedura pie", "mordisco en pie derecho", "lesión por animal en el pie", "herida abierta por mordida", "sangre por mordida", "urgencia mordedura pie", "ataque de animal en pie", "limpieza de mordida", "traumatismo por mordedura", "herida profunda pie", "me mordieron el pie", "desgarro por mordida"]'),
('S91.351D', 'Mordedura abierta del pie derecho, contacto sucesivo', 'Sin especificar', '["seguimiento mordida pie", "curación mordedura pie", "revisión herida por mordida", "infección por mordida de perro", "control de mordisco pie", "limpieza herida animal", "cambio de vendas mordida", "observación de la herida", "me duele la mordida del pie", "cita de control tras mordida", "evolución de mordedura", "tratamiento de mordedura abierta", "seguimiento de curación", "revisión de lesiones por mordedura"]'),
('S91.351S', 'Mordedura abierta del pie derecho, secuela', 'Sin especificar', '["cicatriz por mordida en pie", "secuela de mordedura animal", "marca de mordedura pie", "dolor crónico por mordida", "cicatriz deformante pie", "problemas de piel por mordida", "secuelas de ataque animal", "fibrosis tras mordedura", "cicatriz queloide mordida", "adherencias en pie", "pérdida de tejido por mordida", "cicatriz profunda pie", "molestias en zona de mordida antigua"]');
