INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C25.0', 'Neoplasia maligna de cabeza de páncreas', 'Sin especificar', '["cáncer de páncreas", "tumor en la cabeza del páncreas", "cáncer pancreático", "dolor en la boca del estómago", "ictericia", "piel amarilla", "ojos amarillos", "pérdida de peso inexplicable", "dolor de espalda irradiado", "tumor maligno", "cáncer digestivo", "problemas de páncreas", "bulto en el páncreas", "malestar abdominal", "heces pálidas", "orina oscura"]'),
('C25.1', 'Neoplasia maligna de cuerpo de páncreas', 'Sin especificar', '["cáncer en el cuerpo del páncreas", "tumor en el páncreas", "dolor de panza persistente", "cáncer abdominal", "masa abdominal", "dolor de guata", "dolor de barriga", "pérdida de apetito", "indigestión severa", "cansancio extremo", "pérdida de peso repentina", "diarrea persistente", "dolor que se va a la espalda", "carcinoma pancreático", "neoplasia"]'),
('C25.2', 'Neoplasia maligna de cola de páncreas', 'Sin especificar', '["tumor en la cola del páncreas", "cáncer de cola de páncreas", "dolor intenso en el abdomen", "dolor bajo las costillas", "molestias en el costado", "pérdida de peso", "diabetes de aparición repentina", "asco a la comida", "vómitos", "tumor maligno", "cáncer de órganos digestivos", "dolor que no se quita", "problemas digestivos graves", "masa en la parte superior del abdomen", "fatiga crónica"]'),
('C25.3', 'Neoplasia maligna de conducto pancreático', 'Sin especificar', '["tumor en el conducto del páncreas", "obstrucción del conducto pancreático", "cáncer de conductos", "ictericia obstructiva", "dolor abdominal alto", "problemas de digestión", "pérdida de peso", "piel amarillenta", "orina como té", "heces color arcilla", "dolor punzante en la panza", "cáncer agresivo", "tumor en el páncreas", "malestar estomacal"]'),
('C25.4', 'Neoplasia maligna de páncreas endocrino', 'Sin especificar', '["tumor endocrino del páncreas", "insulinoma", "gastrinoma", "cáncer de las células del páncreas", "problemas de azúcar", "subidas de azúcar", "bajones de azúcar", "hipoglucemia", "niveles de glucosa inestables", "tumor productor de hormonas", "cáncer poco común de páncreas", "problemas hormonales", "pancreático endocrino", "nódulos en el páncreas"]'),
('C25.7', 'Neoplasia maligna de otras partes de páncreas', 'Sin especificar', '["tumor en el páncreas", "cáncer en páncreas", "masa en páncreas", "dolor de guata constante", "dolor en el epigastrio", "pérdida de peso sin dieta", "cáncer de órganos", "tumor maligno", "malestar abdominal", "pérdida de fuerza", "problemas digestivos", "dolor sordo en la barriga", "neoplasia pancreática", "cáncer raro de páncreas"]'),
('C25.8', 'Neoplasia maligna de localizaciones contiguas de páncreas', 'Sin especificar', '["cáncer de páncreas extendido", "tumor avanzado de páncreas", "cáncer en zonas vecinas al páncreas", "afectación pancreática", "masa abdominal", "dolor intenso en la panza", "dolor que atraviesa la espalda", "pérdida de peso severa", "cáncer gastrointestinal", "tumor maligno", "neoplasia extendida", "malestar general", "problemas serios de páncreas"]'),
('C25.9', 'Neoplasia maligna de páncreas, no especificada', 'Sin especificar', '["cáncer de páncreas", "tumor en el páncreas", "cáncer en la panza", "enfermedad del páncreas", "bolita en el páncreas", "masa maligna", "dolor abdominal crónico", "pérdida de peso", "cáncer en el estómago", "malestar de panza", "dolor de barriga", "problemas graves de páncreas", "tumor maligno", "cáncer detectado en páncreas", "neoplasia"]');
