INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('I44.0', 'Bloqueo auriculoventricular, primer grado', 'Sin especificar', '["bloqueo AV", "falla eléctrica corazón", "ritmo cardiaco lento", "bradicardia leve", "corazón lento", "problema conducción eléctrica", "latidos lentos", "retraso conducción corazón", "bloqueo primer grado", "síncope", "mareos", "fatiga", "palpitaciones", "electrocardiograma alterado", "conducción AV retrasada"]'),
('I44.1', 'Bloqueo auriculoventricular, segundo grado', 'Sin especificar', '["bloqueo AV segundo grado", "Mobitz tipo I", "Mobitz tipo II", "latidos saltados", "pulso irregular", "bloqueo intermitente", "corazón descompassado", "arritmia", "bloqueo segundo grado", "pausas en el pulso", "desmayos", "pre-síncope", "ritmo inestable", "fallo conducción cardíaca", "falta de latido"]'),
('I44.2', 'Bloqueo auriculoventricular, completo', 'Sin especificar', '["bloqueo AV completo", "bloqueo tercer grado", "bloqueo cardiaco total", "corazón bloqueado", "ritmo de escape", "disociación AV", "desmayo súbito", "braquicardia severa", "riesgo de paro", "marcapasos necesario", "fallo eléctrico corazón", "bloqueo total", "sincope", "mareo intenso", "pérdida de consciencia"]'),
('I44.30', 'Bloqueo auriculoventricular no especificado', 'Sin especificar', '["bloqueo AV", "problema en el pulso", "latidos raros", "alteración eléctrica corazón", "conducción cardíaca alterada", "bloqueo indeterminado", "arritmia cardíaca", "problemas de ritmo", "electrocardiograma raro", "falla en el sistema eléctrico", "irregularidad al latir", "corazón raro", "palpitaciones raras", "chequeo cardíaco anormal"]'),
('I44.39', 'Otros tipos de bloqueo auriculoventricular', 'Sin especificar', '["otros bloqueos AV", "bloqueo de conducción", "alteración conducción cardíaca", "anomalía eléctrica", "ritmo raro", "bloqueo cardíaco específico", "defecto conducción", "ritmo cardiaco extraño", "bloqueo de rama", "arritmia específica", "pulso irregular", "latido desigual", "problemas de conexión cardíaca", "electrocardiograma inusual"]'),
('I44.4', 'Bloqueo fascicular anterior izquierdo', 'Sin especificar', '["bloqueo fascicular anterior", "hemibloqueo anterior izquierdo", "bloqueo rama anterior", "problema eléctrico ventrículo", "eje desviado corazón", "alteración conducción ventrículo", "bloqueo de hemirrama", "electrocardiograma con desvío", "bloqueo hemifascicular", "problemas de conducción intraventricular", "arritmia focal", "desviación del eje izquierdo", "bloqueo específico izquierdo", "defecto rama izquierda"]'),
('I44.5', 'Bloqueo fascicular posterior izquierdo', 'Sin especificar', '["bloqueo fascicular posterior", "hemibloqueo posterior izquierdo", "bloqueo rama posterior", "eje desviado a la derecha", "bloqueo hemifascicular posterior", "problemas conducción posterior", "alteración intraventricular", "defecto rama posterior", "arritmia intraventricular", "bloqueo ventrículo izquierdo", "electrocardiograma alterado", "conducción eléctrica ventrículo", "bloqueo posterior", "falla de rama izquierda"]'),
('I44.60', 'Bloqueo fascicular no especificado', 'Sin especificar', '["bloqueo fascicular", "bloqueo de rama parcial", "alteración fascicular", "problema eléctrico en ventrículo", "arritmia fascicular", "defecto conducción intraventricular", "bloqueo de conducción inespecífico", "electrocardiograma anormal", "bloqueo ventrículo", "anomalía eléctrica ventricular", "latidos desiguales", "problemas de haz de his", "bloqueo de rama no definido"]'),
('I44.69', 'Otros tipos de bloqueo fascicular', 'Sin especificar', '["otros bloqueos fasciculares", "bloqueos de rama menores", "alteración de haz de his", "problemas eléctricos específicos", "defecto fascicular", "conducción ventricular alterada", "bloqueo intraventricular", "arritmia ventricular específica", "electrocardiograma con cambios", "anomalía de conducción", "bloqueo fascicular raro", "falla conducción ventrículo", "irregularidad eléctrica intraventricular"]'),
('I44.7', 'Bloqueo de rama izquierda, no especificado', 'Sin especificar', '["bloqueo de rama izquierda", "BRI", "BLO", "bloqueo rama izquierda", "problema eléctrico izquierdo", "corazón lado izquierdo", "fallo conducción ventrículo izquierdo", "arritmia bloqueo rama", "bloqueo de conducción izquierda", "electrocardiograma con bloqueo", "latido bloqueado", "problema haz de his izquierdo", "alteración ventrículo izquierdo", "defecto eléctrico severo"]');
