INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C78.00', 'Neoplasia maligna secundaria de pulmón no especificado', 'Sin especificar', '["cáncer de pulmón", "metástasis pulmonar", "tumores en los pulmones", "mancha en el pulmón", "bolitas en los pulmones", "cáncer secundario de pulmón", "cáncer que se fue al pulmón", "nódulos pulmonares malignos", "falla pulmonar por cáncer", "adenocarcinoma pulmonar metastásico", "cáncer avanzado pulmón", "carcinomatosis pulmonar", "dolor al respirar", "tos con sangre", "dificultad para respirar", "falta de aire", "cáncer pulmonar diseminado"]'),
('C78.01', 'Neoplasia maligna secundaria de pulmón derecho', 'Sin especificar', '["metástasis pulmón derecho", "tumor en pulmón derecho", "cáncer lado derecho pulmón", "nódulo maligno pulmón derecho", "masa en pulmón derecho", "cáncer secundario pulmón derecho", "adenocarcinoma pulmón derecho", "afectación pulmón derecho", "falla pulmón derecho", "cáncer avanzado pulmón derecho", "diseminación pulmón derecho", "cáncer de pulmón derecho", "lesión pulmonar derecha", "tumoración derecha pulmón", "cáncer que se pasó al pulmón derecho"]'),
('C78.02', 'Neoplasia maligna secundaria de pulmón izquierdo', 'Sin especificar', '["metástasis pulmón izquierdo", "tumor en pulmón izquierdo", "cáncer lado izquierdo pulmón", "nódulo maligno pulmón izquierdo", "masa en pulmón izquierdo", "cáncer secundario pulmón izquierdo", "adenocarcinoma pulmón izquierdo", "afectación pulmón izquierdo", "falla pulmón izquierdo", "cáncer avanzado pulmón izquierdo", "diseminación pulmón izquierdo", "cáncer de pulmón izquierdo", "lesión pulmonar izquierda", "tumoración izquierda pulmón", "cáncer que se pasó al pulmón izquierdo"]'),
('C78.1', 'Neoplasia maligna secundaria de mediastino', 'Sin especificar', '["cáncer en el mediastino", "tumor en medio del pecho", "masa mediastínica", "metástasis en el mediastino", "cáncer de tórax", "adenopatías mediastínicas malignas", "ganglios en el pecho", "tumor central del tórax", "linfoma mediastínico", "cáncer secundario tórax", "dolor de pecho por tumor", "opresión en el pecho", "masa retroesternal", "cáncer mediastínico metastásico", "diseminación al mediastino"]'),
('C78.2', 'Neoplasia maligna secundaria de pleura', 'Sin especificar', '["cáncer en la pleura", "tumor en la membrana del pulmón", "metástasis pleural", "derrame pleural maligno", "líquido en los pulmones por cáncer", "mesotelioma secundario", "cáncer de la pleura", "cáncer que afecta la capa del pulmón", "carcinomatosis pleural", "dolor costal", "dolor en los pulmones", "inflamación pleural por cáncer", "cáncer secundario pleura", "nódulos en la pleura", "agua en el pulmón por cáncer"]'),
('C78.30', 'Neoplasia maligna secundaria de órgano respiratorio no especificado', 'Sin especificar', '["cáncer respiratorio metastásico", "tumor en sistema respiratorio", "metástasis sistema respiratorio", "cáncer avanzado de vías respiratorias", "tumor de vías aéreas", "cáncer diseminado pulmones y vías", "lesión maligna respiratoria", "diseminación a órganos respiratorios", "tumor de pulmón o vía aérea", "problemas respiratorios por cáncer", "cáncer secundario aparato respiratorio", "masa en vías respiratorias", "cáncer terminal respiratorio"]'),
('C78.39', 'Neoplasia maligna secundaria de otros órganos respiratorios', 'Sin especificar', '["cáncer de tráquea metastásico", "tumor en bronquios", "cáncer laringe secundario", "metástasis en tráquea", "tumor vías respiratorias altas", "diseminación a vías aéreas", "cáncer de faringe secundario", "masa en tráquea", "cáncer secundario bronquial", "lesión bronquial maligna", "tumor traqueobronquial", "cáncer de vías respiratorias", "metástasis de otros órganos a tráquea"]'),
('C78.4', 'Neoplasia maligna secundaria de intestino delgado', 'Sin especificar', '["cáncer en las tripas", "metástasis en intestino delgado", "tumor en el intestino", "cáncer secundario intestino", "masa en el abdomen", "dolor de panza por cáncer", "cáncer avanzado de intestinos", "obstrucción intestinal por tumor", "cáncer en el vientre", "diseminación a intestinos", "tumor en el duodeno", "tumor en yeyuno", "tumor en íleon", "cáncer que se fue a las tripas", "cáncer de barriga metastásico"]'),
('C78.5', 'Neoplasia maligna secundaria de intestino grueso y recto', 'Sin especificar', '["cáncer de colon metastásico", "tumor en el recto", "metástasis en el colon", "cáncer de colon y recto secundario", "tumor en el intestino grueso", "sangre en la caca por cáncer", "cáncer colorrectal secundario", "masa en el recto", "cáncer de ano metastásico", "dolor de panza bajo", "tumor en la guata", "cáncer diseminado al colon", "obstrucción rectal", "cáncer que se fue al colon", "cáncer de tripa gorda"]'),
('C78.6', 'Neoplasia maligna secundaria de retroperitoneo y peritoneo', 'Sin especificar', '["cáncer en el peritoneo", "metástasis peritoneal", "carcinomatosis peritoneal", "agua en la panza por cáncer", "ascitis maligna", "tumor en el abdomen", "cáncer en la cavidad abdominal", "tumor retroperitoneal", "cáncer secundario de abdomen", "masa abdominal", "hinchazón de la panza por cáncer", "cáncer diseminado al vientre", "tumor en las membranas del abdomen", "cáncer de guata", "líquido en el abdomen maligno"]'),
('C78.7', 'Neoplasia maligna secundaria de hígado y vías biliares intrahepáticas', 'Sin especificar', '["metástasis en el hígado", "cáncer de hígado secundario", "hígado con tumores", "bolitas en el hígado", "cáncer que se fue al hígado", "metástasis hepática", "cáncer de vías biliares secundario", "hígado inflamado por cáncer", "ictericia por cáncer", "piel amarilla por cáncer", "dolor debajo de las costillas derecha", "cáncer avanzado de hígado", "tumor en hígado", "diseminación al hígado", "cáncer hepático metastásico"]'),
('C78.80', 'Neoplasia maligna secundaria de órganos digestivos no especificados', 'Sin especificar', '["cáncer digestivo metastásico", "tumor en el sistema digestivo", "cáncer en la panza", "metástasis en el aparato digestivo", "cáncer avanzado de estómago o intestinos", "diseminación a órganos digestivos", "tumor abdominal no especificado", "cáncer secundario de sistema digestivo", "problemas digestivos por cáncer", "dolor de panza por metástasis", "masa abdominal maligna", "cáncer en las entrañas", "cáncer de guata avanzado"]'),
('C78.89', 'Neoplasia maligna secundaria de otros órganos del aparato digestivo', 'Sin especificar', '["cáncer de páncreas metastásico", "metástasis en el páncreas", "tumor en el esófago", "cáncer de esófago secundario", "tumor en la vesícula", "cáncer de vesícula metastásico", "cáncer de bazo", "metástasis en el bazo", "tumor en el estómago", "cáncer gástrico secundario", "cáncer de órganos digestivos secundarios", "metástasis a órganos del aparato digestivo", "masa en páncreas", "cáncer que se pasó al esófago", "tumor en la boca del estómago"]');
