INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('G52.0', 'Trastornos del nervio olfatorio', 'Sin especificar', '["pérdida de olfato", "anosmia", "no huelo nada", "olfato atrofiado", "nariz tapada sin moco", "distorsión de olores", "fantosmia", "parosmia", "pérdida de gusto y olfato", "nariz no siente", "problemas para oler", "olfato alterado", "anosmia postviral", "hiposmia"]'),
('G52.1', 'Trastornos del nervio glosofaríngeo', 'Sin especificar', '["neuralgia glosofaríngea", "dolor en la garganta", "pinchazo en la lengua", "dolor al tragar", "dolor en la base de la lengua", "dolor en el oído profundo", "dolor punzante en la faringe", "molestia en la garganta", "dolor de garganta crónico", "espasmos en la garganta", "dolor mandibular", "neuralgia facial", "dolor al pasar saliva"]'),
('G52.2', 'Trastornos del nervio vago', 'Sin especificar', '["problemas del nervio vago", "disfunción vagal", "mareos", "desmayos frecuentes", "taquicardia", "nauseas constantes", "dificultad para tragar", "disfonía", "voz ronca", "problemas digestivos nerviosos", "desvanecimientos", "vértigo", "bradicardia", "nudo en el estómago", "vagal"]'),
('G52.3', 'Trastornos del nervio hipogloso', 'Sin especificar', '["lengua dormida", "problemas para mover la lengua", "atrofia lingual", "lengua trabada", "dificultad al hablar", "lengua desviada", "parálisis de lengua", "debilidad en la lengua", "problemas de masticación", "lengua pesada", "trastorno del habla", "dificultad para deglutir", "lengua torcida", "atrofia de la lengua"]'),
('G52.7', 'Trastornos de múltiples nervios craneales', 'Sin especificar', '["polineuropatía craneal", "parálisis facial múltiple", "dolor facial", "problemas de los pares craneales", "debilidad en la cara", "adormecimiento facial", "problemas de vista y habla", "síndrome de pares craneales", "daño nervioso en la cabeza", "entumecimiento de la cara", "pérdida de sensibilidad facial", "complicaciones neurológicas faciales", "parálisis de varios nervios"]'),
('G52.8', 'Trastornos de otros nervios craneales especificados', 'Sin especificar', '["daño nervioso craneal", "neuropatía craneal", "problemas en nervios de la cara", "dolor en la cabeza por nervios", "nervio atrapado en la cara", "dolor neuropático craneal", "parestesia facial", "desórdenes neurológicos de cabeza", "dolor nervioso de cráneo", "problemas sensoriales faciales", "neuropatía de cabeza", "molestias nerviosas faciales"]'),
('G52.9', 'Trastorno de nervio craneal, no especificado', 'Sin especificar', '["dolor facial extraño", "hormigueo en la cara", "dolor de nervio en la cabeza", "parálisis facial sin causa", "cara dormida", "dolor de cara", "neuropatía desconocida", "problema neurológico indefinido", "punzadas en la cabeza", "adormecimiento de mejilla", "dolor tipo eléctrico en cara", "molestia neurológica", "entumecimiento facial", "nervio de la cabeza mal"]');
