INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A77.0', 'Fiebre maculosa por Rickettsia rickettsii', 'Sin especificar', '["fiebre de las montañas rocosas", "fiebre manchada", "picadura de garrapata", "manchas en la piel", "rash cutáneo", "fiebre alta", "dolor muscular", "exantema", "infección por garrapatas", "erupción febril", "malestar general", "dolor de cabeza intenso", "fiebre con puntos rojos", "rickettsiosis", "síntomas de mordedura de bicho", "enfermedad de la garrapata"]'),
('A77.1', 'Fiebre maculosa por Rickettsia conorii', 'Sin especificar', '["fiebre botonosa mediterránea", "mancha negra", "tache noire", "picadura de garrapata marrón", "fiebre con erupción", "rash por rickettsia", "infección del mediterráneo", "manchas en el cuerpo", "ganglios inflamados", "dolor articular", "fiebre repentina", "exantema papuloso", "enfermedad por garrapatas", "picaduras de insectos con fiebre", "infección tropical", "síndrome febril eruptivo"]'),
('A77.2', 'Fiebre maculosa por Rickettsia siberica', 'Sin especificar', '["fiebre manchada del norte de asia", "fiebre siberiana", "erupción por garrapatas", "manchas en la piel con fiebre", "picadura de bicho en siberia", "síndrome rickettsial", "rash cutáneo febril", "dolor de cuerpo", "fiebre con exantema", "infección zoonótica", "malestar por garrapatas", "inflamación de ganglios", "puntos rojos en la piel", "enfermedad de la taiga", "fiebre exantemática"]'),
('A77.3', 'Fiebre maculosa por Rickettsia australis', 'Sin especificar', '["fiebre manchada de queensland", "fiebre por rickettsia australiana", "picadura de garrapata austral", "erupción febril", "rash cutáneo", "fiebre y manchas", "infección por garrapata", "dolor de cabeza", "malestar generalizado", "manchas rojas en el cuerpo", "dolor muscular", "inflamación local por picadura", "enfermedad febril", "síndrome eruptivo", "rickettsiosis australiana"]'),
('A77.40', 'Erliquiosis, no especificada', 'Sin especificar', '["erliquiosis", "infección por garrapatas", "fiebre por picadura", "dolor muscular intenso", "dolor de huesos", "dolor de cabeza", "fiebre alta sin causa", "malestar general", "infección bacteriana por garrapata", "dolor de articulaciones", "fatiga extrema", "náuseas", "síntomas de gripe por garrapata", "infección zoonótica", "mal de la garrapata", "fiebre inespecífica"]'),
('A77.41', 'Erliquiosis chaffeensis [E. chaffeensis]', 'Sin especificar', '["erliquiosis monocítica humana", "infección por garrapata estrella solitaria", "fiebre con dolor muscular", "dolor en las articulaciones", "dolor detrás de los ojos", "fiebre alta", "cansancio extremo", "malestar de cuerpo", "picadura de garrapata", "erliquia", "bacteria transmitida por garrapatas", "dolor de cabeza fuerte", "escalofríos", "vómitos y dolor abdominal", "infección por mordedura de bicho", "síntomas tipo gripe"]'),
('A77.49', 'Otras erliquiosis', 'Sin especificar', '["erliquiosis granulocítica", "infección bacteriana", "enfermedad por picadura", "fiebre y malestar", "dolor corporal", "fiebre de origen oscuro", "picadura de garrapata", "dolor articular", "inflamación de ganglios", "cansancio inusual", "náuseas", "dolor de cabeza", "infección por garrapatas poco común", "síndrome febril", "mal de picadura", "rickettsiosis relacionada"]'),
('A77.8', 'Otras fiebres maculosas', 'Sin especificar', '["fiebre con manchas", "rash febril", "manchas rojas en la piel con fiebre", "infección por picadura", "enfermedad por garrapatas", "exantema febril", "fiebre manchada inespecífica", "puntos en la piel", "ronchas con fiebre", "erupción cutánea", "dolor muscular por picadura", "malestar y manchas", "rickettsiosis", "fiebre por insectos", "síndrome exantemático"]'),
('A77.9', 'Fiebre maculosa, no especificada', 'Sin especificar', '["fiebre manchada", "manchas rojas en el cuerpo", "erupción febril", "fiebre con rash", "picadura de garrapata", "fiebre misteriosa", "enfermedad eruptiva", "manchitas en la piel", "fiebre y ronchas", "dolor de cuerpo y manchas", "fiebre de garrapata", "infección por mordedura", "erupción en la piel", "síndrome de fiebre y manchas", "rash en el cuerpo", "malestar generalizado con manchas"]');
