INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H75.00', 'Mastoiditis en enfermedades infecciosas y parasitarias clasificadas bajo otro concepto, oído no especificado', 'Sin especificar', '["mastoiditis", "dolor detrás de la oreja", "infección en el hueso del oído", "hinchazón detrás de la oreja", "oido inflamado", "otitis complicada", "infección ósea oído", "dolor de mastoides", "pus en el oído", "fiebre por dolor de oido", "hueso mastoides inflamado", "infección profunda del oído", "dolor de cabeza por oido", "enrojecimiento detrás de la oreja", "secreción del oído", "flemón auricular"]'),
('H75.01', 'Mastoiditis en enfermedades infecciosas y parasitarias clasificadas bajo otro concepto, oído derecho', 'Sin especificar', '["mastoiditis derecha", "infección hueso oído derecho", "dolor detrás de la oreja derecha", "hinchazón lado derecho cabeza", "otitis derecha grave", "inflamación mastoides derecha", "pus en oído derecho", "infección mastoidea derecha", "dolor fuerte oído derecho", "fiebre e infección oído derecho", "rojez detrás oreja derecha", "problema hueso oído derecho", "dolor punzante oído derecho", "secreción oído derecho", "oido derecho tapado y adolorido"]'),
('H75.02', 'Mastoiditis en enfermedades infecciosas y parasitarias clasificadas bajo otro concepto, oído izquierdo', 'Sin especificar', '["mastoiditis izquierda", "infección hueso oído izquierdo", "dolor detrás de la oreja izquierda", "hinchazón lado izquierdo cabeza", "otitis izquierda grave", "inflamación mastoides izquierda", "pus en oído izquierdo", "infección mastoidea izquierda", "dolor fuerte oído izquierdo", "fiebre e infección oído izquierdo", "rojez detrás oreja izquierda", "problema hueso oído izquierdo", "dolor punzante oído izquierdo", "secreción oído izquierdo", "oido izquierdo tapado y adolorido"]'),
('H75.03', 'Mastoiditis en enfermedades infecciosas y parasitarias clasificadas bajo otro concepto, bilateral', 'Sin especificar', '["mastoiditis bilateral", "infección en ambos oídos", "dolor detrás de ambas orejas", "inflamación mastoides doble", "infección ósea ambos oídos", "otitis severa bilateral", "dolor de cabeza intenso oído", "pus en ambos oídos", "hinchazón detrás de las dos orejas", "infección mastoidea en ambos lados", "fiebre alta por infección oídos", "rojez detrás de las orejas", "problema en huesos de los oídos", "dolor punzante en ambos lados", "infección de oídos complicada"]'),
('H75.80', 'Otros trastornos especificados del oído medio y mastoides en enfermedades clasificadas bajo otro concepto, oído no especificado', 'Sin especificar', '["problemas oido medio", "trastorno mastoides", "infección oído medio", "dolor de oído persistente", "oido tapado", "secreción oído", "zumbido en el oido", "tinnitus", "presión en el oído", "dolor de oido sordo", "malestar en el hueso mastoides", "infección recurrente oído", "oido inflamado", "problema de oido no especificado", "sensación de oído lleno"]'),
('H75.81', 'Otros trastornos especificados del oído medio y mastoides en enfermedades clasificadas bajo otro concepto, oído derecho', 'Sin especificar', '["trastorno oido medio derecho", "dolor oido derecho", "infección oido derecho", "mastoides derecha inflamada", "oido derecho tapado", "zumbido oido derecho", "presión oido derecho", "molestia hueso oido derecho", "problema auditivo derecho", "secreción oido derecho", "dolor sordo derecho", "oido derecho congestionado", "inflamación oído medio derecho", "infección crónica oído derecho", "problemas de mastoides lado derecho"]'),
('H75.82', 'Otros trastornos especificados del oído medio y mastoides en enfermedades clasificadas bajo otro concepto, oído izquierdo', 'Sin especificar', '["trastorno oido medio izquierdo", "dolor oido izquierdo", "infección oido izquierdo", "mastoides izquierda inflamada", "oido izquierdo tapado", "zumbido oido izquierdo", "presión oido izquierdo", "molestia hueso oido izquierdo", "problema auditivo izquierdo", "secreción oido izquierdo", "dolor sordo izquierdo", "oido izquierdo congestionado", "inflamación oído medio izquierdo", "infección crónica oído izquierdo", "problemas de mastoides lado izquierdo"]'),
('H75.83', 'Otros trastornos especificados del oído medio y mastoides en enfermedades clasificadas bajo otro concepto, bilateral', 'Sin especificar', '["trastorno oido medio bilateral", "dolor en ambos oídos", "infección en los dos oídos", "mastoides inflamadas bilateral", "oídos tapados", "zumbido en los oídos", "presión en ambos oídos", "molestia huesos de los oídos", "problema auditivo doble", "secreción en ambos oídos", "dolor sordo en ambos lados", "oídos congestionados", "inflamación oídos medio bilateral", "infección crónica oídos", "problemas de mastoides ambos lados"]');
