INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H46.00', 'Papilitis óptica, ojo no especificado', 'Sin especificar', '["inflamación del nervio óptico", "papilitis", "disco óptico hinchado", "ojo inflamado", "dolor de ojo", "visión borrosa", "pérdida de visión repentina", "dolor al mover el ojo", "inflamación ocular", "problemas de visión", "ceguera repentina", "manchas en la vista", "ojo rojo", "dolor detrás del ojo", "doctor de ojos", "oftalmólogo", "edema papilar"]'),
('H46.01', 'Papilitis óptica, ojo derecho', 'Sin especificar', '["papilitis ojo derecho", "inflamación nervio óptico derecho", "dolor ojo derecho", "visión borrosa ojo derecho", "pérdida de visión ojo derecho", "ojo derecho hinchado", "dolor al mover el ojo derecho", "ceguera ojo derecho", "problema visual derecho", "punzadas ojo derecho", "doctor ojos", "oftalmólogo", "neuritis óptica derecha", "disco óptico derecho inflamado"]'),
('H46.02', 'Papilitis óptica, ojo izquierdo', 'Sin especificar', '["papilitis ojo izquierdo", "inflamación nervio óptico izquierdo", "dolor ojo izquierdo", "visión borrosa ojo izquierdo", "pérdida de visión ojo izquierdo", "ojo izquierdo hinchado", "dolor al mover el ojo izquierdo", "ceguera ojo izquierdo", "problema visual izquierdo", "punzadas ojo izquierdo", "doctor ojos", "oftalmólogo", "neuritis óptica izquierda", "disco óptico izquierdo inflamado"]'),
('H46.03', 'Papilitis óptica, bilateral', 'Sin especificar', '["papilitis en ambos ojos", "inflamación de los dos nervios ópticos", "visión borrosa en ambos ojos", "pérdida de visión total", "dolor en los dos ojos", "ojos hinchados", "problemas de visión bilateral", "no veo bien de ninguno", "ceguera bilateral", "dolor ocular ambos ojos", "edema papilar bilateral", "neuritis óptica bilateral", "doctor especialista en ojos"]'),
('H46.10', 'Neuritis retrobulbar, ojo no especificado', 'Sin especificar', '["neuritis retrobulbar", "dolor detrás del globo ocular", "dolor al mover los ojos", "pérdida de visión central", "visión nublada", "problema en el nervio del ojo", "inflamación nervio óptico", "visión opaca", "dolor profundo en el ojo", "doctor de la vista", "oftalmólogo", "visión con manchas", "pérdida de color en la visión", "neuro-oftalmología"]'),
('H46.11', 'Neuritis retrobulbar, ojo derecho', 'Sin especificar', '["neuritis retrobulbar ojo derecho", "dolor detrás del ojo derecho", "dolor al mover el ojo derecho", "visión nublada ojo derecho", "pérdida de visión ojo derecho", "inflamación nervio ojo derecho", "visión borrosa derecha", "dolor profundo ocular derecho", "problema de nervio derecho", "no veo bien con el derecho", "especialista en ojos"]'),
('H46.12', 'Neuritis retrobulbar, ojo izquierdo', 'Sin especificar', '["neuritis retrobulbar ojo izquierdo", "dolor detrás del ojo izquierdo", "dolor al mover el ojo izquierdo", "visión nublada ojo izquierdo", "pérdida de visión ojo izquierdo", "inflamación nervio ojo izquierdo", "visión borrosa izquierda", "dolor profundo ocular izquierdo", "problema de nervio izquierdo", "no veo bien con el izquierdo", "especialista en ojos"]'),
('H46.13', 'Neuritis retrobulbar, bilateral', 'Sin especificar', '["neuritis retrobulbar en ambos ojos", "dolor detrás de los ojos", "dolor al mover ambos ojos", "visión nublada en los dos ojos", "pérdida de visión bilateral", "inflamación nervios ópticos", "visión borrosa total", "dolor profundo ocular bilateral", "problemas nerviosos en ojos", "no veo bien de ningún lado", "especialista en neuro-oftalmología"]'),
('H46.2', 'Neuropatía óptica nutricional', 'Sin especificar', '["pérdida de visión por mala alimentación", "ceguera por desnutrición", "daño al nervio óptico por dieta", "visión borrosa por falta de vitaminas", "neuropatía por falta de B12", "ojos y nutrición", "deficiencia vitamínica y vista", "pérdida visual progresiva", "problemas visuales por mala dieta", "doctor nutrición ojos", "pérdida de visión por alcoholismo"]'),
('H46.3', 'Neuropatía óptica tóxica', 'Sin especificar', '["daño al nervio óptico por tóxicos", "visión dañada por químicos", "ceguera por metanol", "pérdida de vista por venenos", "toxicidad en los ojos", "pérdida de visión por medicamentos", "daño al nervio por alcohol", "visión dañada por drogas", "doctor toxicología", "efectos tóxicos en la vista", "ceguera química", "problemas nerviosos oculares"]'),
('H46.8', 'Otros tipos de neuritis óptica', 'Sin especificar', '["otros tipos de inflamación del nervio óptico", "dolor en los ojos inusual", "problemas raros de visión", "inflamación del nervio de la vista", "neuritis óptica rara", "daño nervioso en ojo", "problemas oculares crónicos", "especialista en retina y nervio", "ojos inflamados", "pérdida visual inespecífica"]'),
('H46.9', 'Neuritis óptica no especificada', 'Sin especificar', '["neuritis óptica", "inflamación del nervio del ojo", "ojo inflamado y no veo bien", "dolor de nervio ocular", "problemas con el nervio del ojo", "pérdida repentina de visión", "visión borrosa de repente", "dolor detrás del ojo", "especialista en ojos", "oftalmólogo urgente", "no veo bien", "visión nublada", "ceguera temporal"]');
