INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L49.0', 'Exfoliación por afección eritematosa que afecta a menos del 10 por ciento de la superficie corporal', 'Sin especificar', '["despellejamiento", "piel roja", "descamación", "pellejos", "irritación cutánea", "eritema leve", "piel descamada", "pica la piel", "ardor en la piel", "ronchas con escamas", "piel levantada", "exfoliación cutánea", "eccema descamativo", "dermatitis descamativa", "inflamación de la piel"]'),
('L49.1', 'Exfoliación por afección eritematosa que afecta al 10-19 por ciento de la superficie corporal', 'Sin especificar', '["despellejo", "piel pelada", "erupción roja", "descamación moderada", "parches rojos", "pellejitos", "piel irritada", "quemazón cutánea", "dermatitis extensa", "piel seca y agrietada", "inflamación roja", "eritema corporal", "exfoliación de la dermis", "brotes en la piel", "piel sensible y roja"]'),
('L49.2', 'Exfoliación por afección eritematosa que afecta al 20-29 por ciento de la superficie corporal', 'Sin especificar', '["gran parte de la piel roja", "descamación mayor", "piel se cae a pedazos", "eritema generalizado", "dermatitis severa", "despellejamiento corporal", "piel inflamada y roja", "irritación en gran parte del cuerpo", "brotes cutáneos", "picazón intensa", "piel irritada y seca", "parches rojos que se descaman", "lesiones cutáneas rojas", "exfoliación por eritrodermia", "piel que se desprende"]'),
('L49.3', 'Exfoliación por afección eritematosa que afecta al 30-39 por ciento de la superficie corporal', 'Sin especificar', '["mucha piel pelada", "eritema extenso", "despelleje corporal", "cuerpo rojo y descamado", "dermatitis difusa", "inflamación grave de la piel", "piel se desprende en grandes zonas", "descamación importante", "erupción roja generalizada", "piel caliente y roja", "ardor en la piel del cuerpo", "pellejos en la ropa", "exfoliación por enfermedad eritematosa", "piel que se cae", "reacción cutánea severa"]'),
('L49.4', 'Exfoliación por afección eritematosa que afecta al 40-49 por ciento de la superficie corporal', 'Sin especificar', '["piel roja en casi la mitad del cuerpo", "descamación severa", "casi medio cuerpo pelado", "eritrodermia parcial", "dermatitis aguda", "irritación cutánea grave", "piel se descascara", "rojez extrema", "inflamación general", "piel que se desprende masivamente", "lesiones eritematosas", "exfoliación corporal extensa", "picor insoportable", "piel viva", "quemazón en la dermis"]'),
('L49.5', 'Exfoliación por afección eritematosa que afecta al 50-59 por ciento de la superficie corporal', 'Sin especificar', '["más de la mitad del cuerpo pelado", "eritrodermia", "piel en carne viva", "descamación generalizada", "eritema severo", "inflamación de la piel del cuerpo", "piel roja y descamada casi completa", "despellejamiento masivo", "reacción inflamatoria cutánea", "piel seca que se cae", "erupción roja extendida", "malestar cutáneo severo", "piel sensible al tacto", "exfoliación profunda", "problema grave de la piel"]'),
('L49.6', 'Exfoliación por afección eritematosa que afecta al 60-69 por ciento de superficie corporal', 'Sin especificar', '["gran parte de la piel descamada", "eritrodermia grave", "cuerpo casi totalmente rojo", "despelleje intenso", "inflamación cutánea masiva", "piel descamada en gran porcentaje", "eritema difuso", "picor generalizado", "piel que se cae a tiras", "ardor en todo el cuerpo", "descamación crítica", "dermatitis eritrodérmica", "piel roja e irritada", "erupción que cubre el cuerpo", "piel muy dañada"]'),
('L49.7', 'Exfoliación por afección eritematosa que afecta al 70-79 por ciento de la superficie corporal', 'Sin especificar', '["cuerpo casi entero pelado", "eritrodermia crítica", "descamación muy extensa", "casi todo el cuerpo descamado", "piel roja por todas partes", "inflamación de casi toda la dermis", "despellejamiento casi total", "dermatitis severa generalizada", "piel viva y roja", "ardor y dolor en la piel", "exfoliación casi completa", "eritema en gran escala", "piel que se desprende constantemente", "pérdida de piel a gran escala", "cuadro cutáneo grave"]'),
('L49.8', 'Exfoliación por afección eritematosa que afecta al 80-89 por ciento de la superficie corporal', 'Sin especificar', '["casi todo el cuerpo sin piel", "eritrodermia extrema", "descamación casi total", "cuerpo en rojo intenso", "piel casi totalmente descamada", "inflamación cutánea severa", "despelleje casi completo", "piel que se desprende casi en su totalidad", "exfoliación casi absoluta", "daño cutáneo masivo", "rojez casi total", "piel muy sensible y roja", "erupción generalizada crítica", "dermatitis eritrodérmica severa", "piel descamada en casi toda la superficie"]'),
('L49.9', 'Exfoliación por afección eritematosa que afecta al 90 por ciento o más de la superficie corporal', 'Sin especificar', '["cuerpo completamente pelado", "eritrodermia total", "descamación total", "piel roja en todo el cuerpo", "despellejamiento absoluto", "eritema generalizado total", "dermatitis exfoliativa", "piel que se cae completa", "cuerpo en carne viva", "inflamación de toda la piel", "exfoliación del 90 por ciento", "cuadro crítico de piel", "emergencia cutánea", "piel roja y escamosa en todo el cuerpo", "todo el cuerpo despellejado"]');
