INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q95.0', 'Inserción y translocación balanceada en un individuo normal', 'Sin especificar', '["translocación cromosómica", "problemas genéticos", "alteración en los cromosomas", "mutación genética", "anomalía del ADN", "intercambio de segmentos cromosómicos", "falla en los genes", "estudio citogenético", "cariotipo alterado", "trastorno hereditario", "inserción cromosómica", "reordenamiento del material genético", "problemas de fertilidad", "riesgo genético", "defectos cromosómicos"]'),
('Q95.1', 'Inversión cromosómica en individuo normal', 'Sin especificar', '["cromosoma invertido", "inversión pericéntrica", "inversión paracéntrica", "error en el orden del ADN", "alteración cromosómica silenciosa", "cariotipo con inversión", "anomalía estructural", "fallas genéticas", "mutación equilibrada", "genética del desarrollo", "problemas reproductivos", "cambio en la secuencia del cromosoma", "desorden de los genes", "análisis de ADN", "herencia cromosómica"]'),
('Q95.2', 'Reordenamiento autosómico balanceado en individuo anormal', 'Sin especificar', '["reordenamiento genético", "anomalía autosómica", "problema genético grave", "síndrome genético", "fallas en el desarrollo", "mutación autosómica", "reordenamiento cromosómico", "anomalías congénitas", "cariotipo anormal", "discapacidad genética", "defecto del cromosoma", "reordenamiento equilibrado", "retraso en el desarrollo", "malformaciones genéticas", "diagnóstico de ADN"]'),
('Q95.3', 'Reordenamiento balanceado sexual / autosómico en individuo anormal', 'Sin especificar', '["reordenamiento cromosoma sexual", "anomalía de cromosomas sexuales", "problemas de fertilidad", "desorden del desarrollo sexual", "mutación equilibrada sexual", "alteración cromosómica", "trastorno de los cromosomas", "anomalía genética X o Y", "reordenamiento complejo", "cariotipo alterado", "fallas genéticas congénitas", "anomalía estructural", "síndromes cromosómicos", "pruebas genéticas", "inconsistencia genética"]'),
('Q95.5', 'Individuo con loci autosómico frágil', 'Sin especificar', '["sitio frágil", "fragilidad cromosómica", "cromosoma frágil", "inestabilidad genética", "locus frágil", "problemas de ADN", "mutación autosómica", "riesgo de ruptura cromosómica", "trastorno genético", "estudio de fragilidad", "anomalía cromosómica", "cariotipo con inestabilidad", "defecto congénito", "diagnóstico citogenético", "fragilidad en los genes"]'),
('Q95.8', 'Otros reordenamientos balanceados y marcadores estructurales', 'Sin especificar', '["cromosoma marcador", "anomalías estructurales", "reordenamiento cromosómico inusual", "marcador supernumerario", "anomalía del cariotipo", "mutación rara", "defecto estructural del ADN", "problema genético desconocido", "cariotipo con marcador", "variación cromosómica", "anomalía no especificada", "error en los cromosomas", "estudios genéticos avanzados", "trastorno cromosómico", "marcador genético balanceado"]'),
('Q95.9', 'Reordenamiento balanceado y marcador estructural, no especificado', 'Sin especificar', '["alteración cromosómica inespecífica", "reordenamiento genético sin especificar", "problema cromosómico", "cariotipo alterado no definido", "anomalía de los cromosomas", "falla genética detectada", "estudio citogenético anormal", "reordenamiento estructural", "marcador genético", "problemas en el ADN", "mutación no clasificada", "trastorno del material genético", "desorden cromosómico desconocido", "anomalía balanceada", "hallazgo citogenético"]');
