INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z3A.00', 'Semanas de gestación no especificadas', 'Sin especificar', '["embarazo sin fecha", "cuántas semanas tengo", "tiempo de gestación", "embarazada", "duda tiempo embarazo", "cálculo fecha parto", "gestación", "estado de buena esperanza", "embarazo actual", "control prenatal"]'),
('Z3A.01', 'Menos de 8 semanas de gestación', 'Sin especificar', '["primer mes embarazo", "recién embarazada", "principio de embarazo", "dos meses", "fecundación reciente", "anuncio embarazo", "prueba positiva", "antelación", "gestación temprana", "primeras semanas", "test embarazo positivo"]'),
('Z3A.08', '8 semanas de gestación', 'Sin especificar', '["dos meses embarazo", "ocho semanas", "gestación segundo mes", "inicio segundo trimestre", "embarazo", "bebé en camino", "control prenatal 8 semanas", "esperando bebé", "desarrollo fetal 8 semanas"]'),
('Z3A.09', '9 semanas de gestación', 'Sin especificar', '["nueve semanas embarazo", "segundo mes gestación", "embarazo", "bebé creciendo", "nauseas embarazo", "desarrollo 9 semanas", "antojos", "gestación"]'),
('Z3A.10', '10 semanas de gestación', 'Sin especificar', '["diez semanas embarazo", "tercer mes inicio", "gestación 10 semanas", "embarazada", "bebé", "crecimiento fetal", "control médico", "primer trimestre"]'),
('Z3A.11', '11 semanas de gestación', 'Sin especificar', '["once semanas embarazo", "gestación", "tercer mes", "embarazo", "bebé", "feto 11 semanas", "control de embarazo"]'),
('Z3A.12', '12 semanas de gestación', 'Sin especificar', '["doce semanas embarazo", "cierre primer trimestre", "tres meses", "embarazada", "gestación 12 semanas", "ecografía 12 semanas", "bebé", "riesgo bajo primer trimestre"]'),
('Z3A.13', '13 semanas de gestación', 'Sin especificar', '["trece semanas embarazo", "inicio segundo trimestre", "gestación", "embarazo", "cuarto mes", "bebé", "desarrollo fetal", "embarazada"]'),
('Z3A.14', '14 semanas de gestación', 'Sin especificar', '["catorce semanas embarazo", "segundo trimestre", "gestación", "embarazo", "bebé", "cuarto mes", "embarazada", "crecimiento"]'),
('Z3A.15', '15 semanas de gestación', 'Sin especificar', '["quince semanas embarazo", "gestación", "embarazo", "segundo trimestre", "cuarto mes", "bebé", "embarazada", "desarrollo"]'),
('Z3A.16', '16 semanas de gestación', 'Sin especificar', '["dieciséis semanas embarazo", "gestación", "cuarto mes", "embarazo", "segundo trimestre", "bebé", "embarazada", "movimientos fetales"]'),
('Z3A.17', '17 semanas de gestación', 'Sin especificar', '["diecisiete semanas embarazo", "gestación", "quinto mes", "embarazo", "segundo trimestre", "bebé", "embarazada", "crecimiento"]'),
('Z3A.18', '18 semanas de gestación', 'Sin especificar', '["dieciocho semanas embarazo", "gestación", "quinto mes", "embarazo", "segundo trimestre", "bebé", "embarazada", "ecografía estructural"]'),
('Z3A.19', '19 semanas de gestación', 'Sin especificar', '["diecinueve semanas embarazo", "gestación", "quinto mes", "embarazo", "segundo trimestre", "bebé", "embarazada", "pataditas"]'),
('Z3A.20', '20 semanas de gestación', 'Sin especificar', '["veinte semanas embarazo", "mitad de embarazo", "quinto mes", "gestación", "embarazo", "segundo trimestre", "bebé", "embarazada", "ecografía morfológica"]'),
('Z3A.21', '21 semanas de gestación', 'Sin especificar', '["veintiuna semanas embarazo", "gestación", "sexto mes", "embarazo", "segundo trimestre", "bebé", "embarazada", "crecimiento fetal"]'),
('Z3A.22', '22 semanas de gestación', 'Sin especificar', '["veintidós semanas embarazo", "gestación", "sexto mes", "embarazo", "segundo trimestre", "bebé", "embarazada", "viabilidad fetal"]'),
('Z3A.23', '23 semanas de gestación', 'Sin especificar', '["veintitrés semanas embarazo", "gestación", "sexto mes", "embarazo", "segundo trimestre", "bebé", "embarazada", "desarrollo"]'),
('Z3A.24', '24 semanas de gestación', 'Sin especificar', '["veinticuatro semanas embarazo", "gestación", "sexto mes", "embarazo", "segundo trimestre", "bebé", "embarazada", "curva glucosa"]'),
('Z3A.25', '25 semanas de gestación', 'Sin especificar', '["veinticinco semanas embarazo", "gestación", "séptimo mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "crecimiento"]'),
('Z3A.26', '26 semanas de gestación', 'Sin especificar', '["veintiséis semanas embarazo", "gestación", "séptimo mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "desarrollo"]'),
('Z3A.27', '27 semanas de gestación', 'Sin especificar', '["veintisiete semanas embarazo", "gestación", "séptimo mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "último trimestre"]'),
('Z3A.28', '28 semanas de gestación', 'Sin especificar', '["veintiocho semanas embarazo", "gestación", "séptimo mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "prematuridad"]'),
('Z3A.29', '29 semanas de gestación', 'Sin especificar', '["veintinueve semanas embarazo", "gestación", "octavo mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "crecimiento"]'),
('Z3A.30', '30 semanas de gestación', 'Sin especificar', '["treinta semanas embarazo", "gestación", "octavo mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "pesadez"]'),
('Z3A.31', '31 semanas de gestación', 'Sin especificar', '["treinta y una semanas embarazo", "gestación", "octavo mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "hinchazón"]'),
('Z3A.32', '32 semanas de gestación', 'Sin especificar', '["treinta y dos semanas embarazo", "gestación", "octavo mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "preparación parto"]'),
('Z3A.33', '33 semanas de gestación', 'Sin especificar', '["treinta y tres semanas embarazo", "gestación", "noveno mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "cansancio"]'),
('Z3A.34', '34 semanas de gestación', 'Sin especificar', '["treinta y cuatro semanas embarazo", "gestación", "noveno mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "pulmones maduros"]'),
('Z3A.35', '35 semanas de gestación', 'Sin especificar', '["treinta y cinco semanas embarazo", "gestación", "noveno mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "recta final"]'),
('Z3A.36', '36 semanas de gestación', 'Sin especificar', '["treinta y seis semanas embarazo", "gestación", "noveno mes", "embarazo", "tercer trimestre", "bebé", "embarazada", "pre-parto"]'),
('Z3A.37', '37 semanas de gestación', 'Sin especificar', '["treinta y siete semanas embarazo", "embarazo a término", "casi nace", "gestación", "noveno mes", "bebé", "embarazada", "término temprano"]'),
('Z3A.38', '38 semanas de gestación', 'Sin especificar', '["treinta y ocho semanas embarazo", "embarazo a término", "a punto de nacer", "gestación", "noveno mes", "bebé", "embarazada", "esperando contracciones"]'),
('Z3A.39', '39 semanas de gestación', 'Sin especificar', '["treinta y nueve semanas embarazo", "embarazo a término", "cuenta regresiva", "gestación", "noveno mes", "bebé", "embarazada", "esperando el parto"]'),
('Z3A.40', '40 semanas de gestación', 'Sin especificar', '["fecha de parto", "ya debe nacer", "parto"]'),
('Z3A.41', '41 semanas de gestación', 'Sin especificar', '["cuarenta y una semanas embarazo", "post-término", "se pasó la fecha", "gestación", "bebé pasado", "embarazada", "necesito parto", "atención médica urgente"]'),
('Z3A.42', '42 semanas de gestación', 'Sin especificar', '["cuarenta y dos semanas embarazo", "gestación prolongada", "embarazo prolongado", "bebé que no nace", "urgencia obstétrica", "sobretiempo", "parto inducido"]'),
('Z3A.49', 'Más de 42 semanas de gestación', 'Sin especificar', '["embarazo prolongado", "más de 42 semanas", "embarazo cronológicamente prolongado", "gestación extra larga", "riesgo fetal", "inducción necesaria", "necesito cesárea", "parto vencido"]');
