INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C10.0', 'Neoplasia maligna de valécula', 'Sin especificar', '["cáncer de valécula", "tumor en la garganta", "bolita en la base de la lengua", "dolor al tragar", "cáncer de garganta", "bulto en la boca", "carcinoma de valécula", "disfagia", "inflamación en la faringe", "neoplasia orofaríngea", "cáncer en la base de la lengua", "molestias al pasar saliva", "tumor maligno en la garganta", "afección en la valécula", "dolor de cuello persistente"]'),
('C10.1', 'Neoplasia maligna de superficie anterior de epiglotis', 'Sin especificar', '["cáncer de epiglotis", "tumor en la laringe", "cáncer de garganta", "dolor al tragar", "disfagia", "carraspera constante", "bulto en la garganta", "carcinoma epiglótico", "dificultad para respirar", "sensación de cuerpo extraño", "neoplasia laríngea", "dolor en la manzana de adán", "tumor maligno anterior", "cáncer de cuello", "inflamación de la epiglotis"]'),
('C10.2', 'Neoplasia maligna de pared lateral de orofaringe', 'Sin especificar', '["cáncer de faringe", "tumor lateral de garganta", "cáncer de amígdala", "carcinoma de orofaringe", "bolita en el cuello", "dolor de garganta crónico", "disfagia", "inflamación de la pared faríngea", "tumor maligno lateral", "dolor al comer", "ganglios inflamados", "cáncer de boca", "molestia al tragar", "neoplasia lateral", "dolor persistente en la faringe"]'),
('C10.3', 'Neoplasia maligna de pared posterior de orofaringe', 'Sin especificar', '["cáncer de faringe", "tumor en la parte de atrás de la garganta", "cáncer de garganta", "carcinoma de pared posterior", "neoplasia orofaríngea posterior", "dolor de garganta al tragar", "disfagia", "bulto en la garganta", "tumor maligno de faringe", "molestia faríngea persistente", "carraspera", "inflamación de la pared posterior", "dolor de garganta sin causa", "cáncer de cuello", "afección de orofaringe"]'),
('C10.4', 'Neoplasia maligna de hendidura branquial', 'Sin especificar', '["cáncer de quiste branquial", "tumor en el cuello", "bolita en el costado del cuello", "carcinoma de hendidura branquial", "neoplasia branquial", "masa en el cuello", "bulto cervical", "cáncer de origen branquial", "tumor congénito maligno", "inflamación lateral del cuello", "dolor cervical", "quiste infectado", "neoplasia maligna de cuello", "tumor en el conducto branquial", "afección cervical"]'),
('C10.8', 'Neoplasia maligna de localizaciones contiguas de orofaringe', 'Sin especificar', '["cáncer de orofaringe", "tumor de garganta", "cáncer en múltiples sitios de la garganta", "carcinoma orofaríngeo", "neoplasia maligna extensa", "tumor contiguo en la faringe", "cáncer avanzado de garganta", "dolor severo al tragar", "disfagia severa", "inflamación general de la garganta", "masa faríngea", "tumor maligno diseminado", "cáncer de cuello y garganta", "afección compleja de orofaringe", "dolor al pasar alimentos"]'),
('C10.9', 'Neoplasia maligna de orofaringe, no especificada', 'Sin especificar', '["cáncer de garganta", "tumor en la boca y garganta", "cáncer de orofaringe", "dolor al tragar", "carcinoma no especificado de garganta", "neoplasia de faringe", "bolita en el cuello", "bulto en la garganta", "disfagia", "carraspera constante", "cáncer de cuello", "tumor maligno de garganta", "molestia al comer", "problemas para pasar saliva", "afección faríngea"]');
