INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z97.0', 'Presencia de ojo artificial', 'Sin especificar', '["ojo de vidrio", "ojo postizo", "prótesis ocular", "ojo falso", "ojo de plástico", "ojo artificial", "lente escleral", "ojo cosmético", "perdí un ojo", "reemplazo ocular", "ojo estético", "implante ocular", "prótesis de ojo", "ojo removible"]'),
('Z97.10', 'Presencia de extremidad artificial (completa) (parcial), no especificada', 'Sin especificar', '["prótesis", "miembro artificial", "muñón", "amputación", "pata de palo", "brazo ortopédico", "pierna ortopédica", "ayuda ortopédica", "miembro ortopédico", "uso de prótesis", "extremidad robótica", "reemplazo de miembro", "equipo de rehabilitación", "soporte ortopédico"]'),
('Z97.11', 'Presencia de brazo derecho artificial (completo) (parcial)', 'Sin especificar', '["brazo derecho ortopédico", "prótesis de brazo derecho", "miembro superior derecho artificial", "mano derecha artificial", "brazo mecánico derecho", "prótesis brazo derecho", "reemplazo brazo derecho", "brazo de goma", "brazo robótico derecho", "miembro derecho postizo"]'),
('Z97.12', 'Presencia de brazo izquierdo artificial (completo) (parcial)', 'Sin especificar', '["brazo izquierdo ortopédico", "prótesis de brazo izquierdo", "miembro superior izquierdo artificial", "mano izquierda artificial", "brazo mecánico izquierdo", "prótesis brazo izquierdo", "reemplazo brazo izquierdo", "brazo robótico izquierdo", "miembro izquierdo postizo", "ayuda brazo izquierdo"]'),
('Z97.13', 'Presencia de pierna derecha artificial (completa) (parcial)', 'Sin especificar', '["pierna derecha ortopédica", "prótesis de pierna derecha", "pie derecho artificial", "pierna mecánica derecha", "pata ortopédica derecha", "prótesis pierna derecha", "reemplazo pierna derecha", "pierna robótica derecha", "miembro inferior derecho postizo", "prótesis tibial derecha"]'),
('Z97.14', 'Presencia de pierna izquierda artificial (completa) (parcial)', 'Sin especificar', '["pierna izquierda ortopédica", "prótesis de pierna izquierda", "pie izquierdo artificial", "pierna mecánica izquierda", "pata ortopédica izquierda", "prótesis pierna izquierda", "reemplazo pierna izquierda", "pierna robótica izquierda", "miembro inferior izquierdo postizo", "prótesis tibial izquierda"]'),
('Z97.15', 'Presencia de brazos artificiales, bilaterales (completos) (parciales)', 'Sin especificar', '["ambos brazos artificiales", "prótesis bilaterales de brazo", "doble prótesis de brazo", "dos brazos mecánicos", "brazos postizos", "doble amputación de brazo", "prótesis superiores bilaterales", "reemplazo de ambos brazos"]'),
('Z97.16', 'Presencia de piernas artificiales, bilaterales (completos) (parciales)', 'Sin especificar', '["ambas piernas artificiales", "prótesis bilaterales de pierna", "doble prótesis de pierna", "dos piernas mecánicas", "piernas postizas", "doble amputación de pierna", "prótesis inferiores bilaterales", "reemplazo de ambas piernas", "doble prótesis de pie"]'),
('Z97.2', 'Presencia de dispositivo protésico dental (completo) (parcial)', 'Sin especificar', '["dentadura postiza", "placa dental", "dientes postizos", "puente dental", "prótesis dental", "caja de dientes", "dentadura removible", "dientes falsos", "coronas dentales", "implantes dentales", "plancha dental", "dentadura completa", "dientes de acrílico", "boquilla"]'),
('Z97.3', 'Presencia de gafas y lentes de contacto', 'Sin especificar', '["lentes", "anteojos", "gafas", "lentes de contacto", "pupilentes", "gafas graduadas", "uso de anteojos", "miopía", "astigmatismo", "lentes de aumento", "gafas de vista", "lentes de ver", "espejuelos", "gafas formuladas"]'),
('Z97.4', 'Presencia de audífono externo', 'Sin especificar', '["aparato auditivo", "audífono", "ayuda para oír", "sordera", "uso de audífonos", "amplificador auditivo", "aparato para la sordera", "auxiliar auditivo", "prótesis auditiva", "oigo mal", "dificultad auditiva", "audífono retroauricular"]'),
('Z97.5', 'Presencia de dispositivo anticonceptivo (intrauterino)', 'Sin especificar', '["DIU", "T de cobre", "dispositivo intrauterino", "anticonceptivo intrauterino", "método anticonceptivo", "anticoncepción", "implante uterino", "espiral", "dispositivo en el útero", "planificación familiar", "DIU hormonal", "DIU Mirena", "dispositivo de cobre"]'),
('Z97.8', 'Presencia de otros dispositivos especificados', 'Sin especificar', '["marcapasos", "stent", "clavo ortopédico", "tornillos quirúrgicos", "válvula cardíaca", "bomba de insulina", "catéter permanente", "placa metálica", "dispositivo médico interno", "implante metálico", "prótesis interna", "marcapasos cardíaco"]');
