INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z18.01', 'Fragmentos de uranio empobrecido retenidos', 'Sin especificar', '["uranio en el cuerpo", "partículas radioactivas", "contaminación por uranio", "esquirla radioactiva", "radiación en tejidos", "toxicidad por metales pesados", "cuerpo extraño tóxico", "partícula de uranio encarnada", "lesión por uranio", "residuo nuclear en piel", "material radioactivo incrustado", "exposición a uranio", "metales pesados retenidos"]'),
('Z18.09', 'Otros fragmentos radioactivos retenidos', 'Sin especificar', '["residuo radioactivo en el cuerpo", "objeto que emite radiación", "material radioactivo bajo la piel", "esquirla radioactiva", "partícula con radiación", "contaminación interna", "cuerpo extraño peligroso", "incrustación radioactiva", "material emisor de radiación", "residuo de laboratorio", "fuga radioactiva en tejidos", "partícula brillante", "radiación local"]'),
('Z18.10', 'Fragmentos metálicos, no especificados, retenidos', 'Sin especificar', '["pedazo de metal en la piel", "fierro encarnado", "esquirla metálica", "trozo de metal en el cuerpo", "objeto de metal clavado", "metal en la carne", "trozo de fierro", "objeto extraño metálico", "punzada por metal", "metal bajo la piel", "pedazo de acero", "punta de metal", "esquirla", "trozo metálico"]'),
('Z18.11', 'Fragmentos metálicos magnéticos retenidos', 'Sin especificar', '["metal que pega imán", "esquirla magnética", "pedazo de metal atraído por imán", "hierro en el cuerpo", "objeto ferromagnético", "metal atraído por resonancia", "esquirla de imán", "trozo de metal que se pega", "metal con magnetismo", "partícula metálica", "cuerpo extraño de fierro", "punta magnética"]'),
('Z18.12', 'Fragmentos no-magnéticos metálicos retenidos', 'Sin especificar', '["esquirla no magnética", "metal que no pega el imán", "aluminio en la piel", "plomo en la carne", "acero inoxidable encarnado", "pedazo de cobre en el cuerpo", "metal no imantado", "objeto metálico inerte", "esquirla de metal blando", "trozo de metal extraño", "residuo metálico", "metal oxidado"]'),
('Z18.2', 'Fragmentos plásticos retenidos', 'Sin especificar', '["pedazo de plástico en la piel", "plástico encarnado", "pedazo de acrílico", "trozo de PVC", "cuerpo extraño de plástico", "esquirla de plástico", "plástico clavado", "objeto plástico dentro", "fragmento de juguete", "plástico debajo de la piel", "residuo plástico", "pedazo de polímero"]'),
('Z18.31', 'Plumas o espinas de animales retenidas', 'Sin especificar', '["espina de pescado en la carne", "espina de erizo", "púa de puercoespín", "pluma clavada", "espina de animal encarnada", "punzada por animal", "pelusa de animal en la piel", "aguijón clavado", "espina de mar", "púa enterrada", "punta de pluma", "espinita de pez"]'),
('Z18.32', 'Diente retenido', 'Sin especificar', '["diente en la encía", "diente enterrado", "diente que no sale", "muela del juicio retenida", "diente impactado", "diente bajo el hueso", "diente encarnado", "problema de muelas", "diente de leche que no se cae", "diente en el paladar", "diente que no erupcionó", "dolor de muela retenida", "diente incluido"]'),
('Z18.33', 'Fragmentos de madera retenidos', 'Sin especificar', '["astilla en el dedo", "pedazo de madera enterrado", "astilla de leña", "pedacito de árbol", "esquirla de madera", "madera clavada", "astillazo", "pedazo de palo en la carne", "astilla profunda", "astilla infectada", "madera encarnada", "punzada por astilla"]'),
('Z18.39', 'Otros fragmentos orgánicos retenidos', 'Sin especificar', '["pedazo de planta en la piel", "residuo orgánico en el cuerpo", "esquirla vegetal", "tejido extraño", "hoja enterrada", "semilla en la piel", "restos orgánicos", "cuerpo extraño natural", "fibra vegetal clavada", "ramita en la herida", "partícula de tierra y planta"]'),
('Z18.81', 'Fragmento de cristal retenido', 'Sin especificar', '["vidrio en la piel", "pedazo de vidrio enterrado", "cristal en la carne", "vidrio molido", "cortada con vidrio", "vidrio encarnado", "esquirla de cristal", "vidrio profundo", "punzada de vidrio", "vidrio en el pie", "trozo de botella en la herida", "cristal transparente bajo la piel"]'),
('Z18.83', 'Fragmento cristalino o de piedra retenido', 'Sin especificar', '["piedra en la piel", "pedazo de roca", "arena en la herida", "guijarro en la carne", "esquirla de piedra", "piedrita enterrada", "trozo de roca clavado", "cristal de piedra", "cuerpo extraño mineral", "piedra incrustada", "polvo de piedra en herida", "pedazo de mármol"]'),
('Z18.89', 'Otros fragmentos de cuerpo extraño especificado retenidos', 'Sin especificar', '["objeto extraño en la piel", "algo clavado", "cuerpo extraño incrustado", "cosa enterrada", "objeto dentro del cuerpo", "residuo extraño", "partícula ajena", "punzada por objeto", "herida con algo adentro", "objeto atorado", "cuerpo extraño retenido", "objeto incrustado"]'),
('Z18.9', 'Fragmentos de cuerpo extraño, material no especificado, retenidos', 'Sin especificar', '["algo me entró en la piel", "tengo algo clavado", "objeto no identificado en el cuerpo", "cuerpo extraño", "tengo una cosa metida", "objeto misterioso en la piel", "algo adentro", "esquirla desconocida", "punzada con algo raro", "objeto sin identificar", "residuo enterrado", "cosa bajo la piel"]');
