INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P24.00', 'Aspiración de meconio sin síntomas respiratorios', 'Sin especificar', '["bebé tragó meconio", "aspiración de primera caca", "meconio en pulmones", "recién nacido tragó popó", "líquido amniótico con meconio", "parto con meconio", "bebé verde al nacer", "problemas al nacer", "aspiración de materia fecal en parto", "bebé no respira bien", "sufrimiento fetal", "riesgo neonatal", "caca en el líquido amniótico"]'),
('P24.01', 'Aspiración de meconio con síntomas respiratorios', 'Sin especificar', '["bebé ahogado con meconio", "dificultad para respirar recién nacido", "bebé azul meconio", "pulmones sucios de meconio", "bebé con oxígeno meconio", "neumonía por aspiración neonatal", "bebé no puede respirar", "bebé hace ruido al respirar", "distrés respiratorio neonatal", "bebé sibilante", "bebé con tiros intercostales", "bebé agónico al nacer", "se tragó el líquido con popó", "necesita ventilador por meconio"]'),
('P24.10', 'Aspiración neonatal de líquido amniótico (claro) y moco sin síntomas respiratorios', 'Sin especificar', '["bebé tragó líquido", "aspiración de líquido amniótico", "bebé con moco al nacer", "bebé se tragó el agua", "líquido en pulmones recién nacido", "bebé tragó su agüita", "aspiración de moco neonatal", "bebé hace ruidos de moco", "atragantamiento al nacer", "limpieza de vías respiratorias neonatal"]'),
('P24.11', 'Aspiración neonatal de líquido amniótico (claro) y moco con síntomas respiratorios', 'Sin especificar', '["bebé se ahogó con líquido", "recién nacido no respira bien líquido", "bebé con flemas al nacer", "neumonía por aspiración de líquido", "bebé hace ruiditos al pecho", "dificultad respiratoria por líquido", "bebé azulado por líquido", "se fue el agua por los pulmones", "bebé se ahoga con flema", "insuficiencia respiratoria por aspiración", "bebé que se cansa al respirar"]'),
('P24.20', 'Aspiración neonatal de sangre sin síntomas respiratorios', 'Sin especificar', '["aspiración de sangre en parto", "sangre en vía aérea bebé", "bebé tragó sangre en el parto", "aspiración de secreción hemática", "bebé con sangre en la boca", "sangrado intraparto aspiración", "bebé succionó sangre", "sangre materna en pulmones bebé"]'),
('P24.21', 'Aspiración neonatal de sangre con síntomas respiratorios', 'Sin especificar', '["sangre en los pulmones del bebé", "bebé no puede respirar sangre", "tos con sangre recién nacido", "ahogamiento con sangre neonatal", "problemas pulmonares por aspiración de sangre", "bebé se pone morado por sangre", "obstrucción por sangre neonatal", "bebé con insuficiencia por aspirar sangre"]'),
('P24.30', 'Aspiración neonatal de leche y comida regurgitada sin síntomas respiratorios', 'Sin especificar', '["bebé se ahogó con leche", "bebé regurgitó y aspiró", "leche en los pulmones bebé", "bebé se fue la leche por el lado", "aspiración de fórmula", "bebé se tragó el vómito", "bebé se atragantó con la toma", "leche en vía aérea", "bebé se pone rojo al tomar"]'),
('P24.31', 'Aspiración neonatal de leche y comida regurgitada con síntomas respiratorios', 'Sin especificar', '["neumonía por aspiración de leche", "bebé se ahoga al comer", "bebé con leche en los pulmones", "dificultad para respirar después de comer", "bebé hace gorgoteo al respirar", "bebé se pone azul tomando pecho", "tos por aspiración de leche", "bebé se cansa al tomar", "aspiración masiva de leche", "síndrome de aspiración láctea"]'),
('P24.80', 'Otra aspiración neonatal, sin síntomas respiratorios', 'Sin especificar', '["bebé aspiró algo extraño", "aspiración de cuerpo extraño neonatal", "bebé se atragantó al nacer", "obstrucción vías aéreas neonato", "aspiración no especificada bebé", "bebé se tragó algo", "problema de succión al nacer"]'),
('P24.81', 'Otra aspiración neonatal con síntomas respiratorios', 'Sin especificar', '["bebé no puede respirar aspiración", "ahogo neonatal", "obstrucción pulmonar por cuerpo extraño", "bebé con falta de aire", "bebé se ahoga", "emergencia respiratoria neonatal", "bebé con obstrucción bronquial", "bebé que hace ruido al pasar aire", "insuficiencia respiratoria por atragantamiento"]'),
('P24.9', 'Aspiración neonatal, no especificada', 'Sin especificar', '["bebé se ahogó", "problemas para respirar recién nacido", "bebé aspiró algo", "atragantamiento del recién nacido", "bebé hace ruidos raros al respirar", "bebé con vía aérea obstruida", "bebé que se ahoga en el parto", "dificultad respiratoria de causa desconocida", "bebé no pudo respirar bien al nacer"]');
