INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Y65.0', 'Transfusión de sangre no compatible', 'Sin especificar', '["error de transfusión", "sangre equivocada", "transfusión fallida", "reacción hemolítica", "sangre incompatible", "me pusieron la sangre mal", "error médico en sangre", "error de grupo sanguíneo", "reacción transfusional", "accidente transfusional", "sangre cruzada mal", "complicación por transfusión", "error tipo de sangre", "shock transfusional", "mala transfusión"]'),
('Y65.1', 'Líquido erróneo usado en infusión', 'Sin especificar', '["suero equivocado", "error en goteo", "medicación intravenosa mal", "líquido IV erróneo", "error de sueroterapia", "me pusieron el suero que no era", "error en venoclisis", "contaminación de fluido", "infusión incorrecta", "error de preparación de suero", "error en vía", "solución intravenosa incorrecta", "falla en infusión", "intoxicación por suero", "error de medicación IV"]'),
('Y65.2', 'Fallo en sutura o ligadura durante operación quirúrgica', 'Sin especificar', '["puntos mal dados", "sutura abierta", "se soltó la sutura", "se abrió la herida", "falla en los puntos", "ligadura mal hecha", "hemorragia postquirúrgica", "se descosió la operación", "cierre quirúrgico fallido", "fuga de sutura", "mala cicatrización interna", "se soltaron los puntos", "dehisencia de sutura", "falla en sutura interna", "problemas con el cosido de la cirugía"]'),
('Y65.3', 'Tubo endotraqueal colocado indebidamente durante procedimiento anestésico', 'Sin especificar', '["tubo mal puesto", "problemas de intubación", "tubo en el esófago", "mala intubación", "error al entubar", "obstrucción por tubo", "dificultad respiratoria tras anestesia", "intubación esofágica accidental", "mal manejo de vía aérea", "tubo mal ubicado", "se desplazó el tubo", "trauma por intubación", "error en ventilación mecánica", "falla en el tubo de la garganta", "no me pudieron intubar bien"]'),
('Y65.4', 'Fallo en introducir o retirar otro tubo o instrumento', 'Sin especificar', '["sonda mal puesta", "error de cateterismo", "drenaje mal colocado", "se quedó instrumento adentro", "objeto extraño tras cirugía", "falla al sacar la sonda", "error con el catéter", "sonda atascada", "problemas con tubos médicos", "error en instrumental", "cuerpo extraño quirúrgico", "mala colocación de drenaje", "dolor por sonda mal puesta", "error de manipulación de instrumentos", "fallo en la sonda vesical"]'),
('Y65.51', 'Realización de un procedimiento (operación) equivocado en paciente correcto', 'Sin especificar', '["cirugía equivocada", "operación que no me tocaba", "me hicieron lo que no era", "error de intervención", "me operaron de otra cosa", "confusión de cirugía", "error de procedimiento médico", "me hicieron el procedimiento mal", "operación incorrecta", "error de diagnóstico quirúrgico", "procedimiento no programado", "mala praxis en quirófano", "me cambiaron la operación", "error en la indicación quirúrgica", "confusión en el tipo de cirugía"]'),
('Y65.52', 'Realización de procedimiento (operación) en paciente no programado para cirugía', 'Sin especificar', '["operaron a la persona equivocada", "error de identidad en quirófano", "me confundieron con otro paciente", "falla en identificación", "operación por error de nombre", "no era yo el candidato a cirugía", "confusión de expediente", "error de paciente", "operación errónea", "me llevaron a quirófano por error", "cambio de paciente en cirugía", "falla de seguridad en quirófano", "me operaron y yo no era", "error administrativo de quirófano", "identidad equivocada en cirugía"]'),
('Y65.53', 'Realización de procedimiento (operación) correcto en lado o parte del cuerpo equivocados', 'Sin especificar', '["operación del lado incorrecto", "me operaron la pierna que no era", "error de lateralidad", "cirugía en lado equivocado", "me hicieron el procedimiento en el lado mal", "error de sitio quirúrgico", "confusión de extremidad", "operación al revés", "error en el lado del cuerpo", "cirugía espejo mal hecha", "me operaron el lado sano", "confusión derecha izquierda en cirugía", "falla en marcaje quirúrgico", "operación en parte equivocada", "procedimiento en sitio incorrecto"]'),
('Y65.8', 'Otros eventos adversos especificados durante la atención quirúrgica y médica', 'Sin especificar', '["error médico", "mala praxis", "complicaciones quirúrgicas", "accidente en el hospital", "negligencia médica", "problemas durante la operación", "falla en el hospital", "evento adverso", "daño por atención médica", "mala experiencia quirúrgica", "complicación inesperada", "error en el quirófano", "atención médica fallida", "riesgo quirúrgico", "incidente hospitalario"]');
