INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D75.0', 'Eritrocitosis familiar', 'Sin especificar', '["sangre espesa hereditaria", "exceso de glóbulos rojos", "policitemia familiar", "sangre viscosa", "hematocrito alto genético", "mucha sangre", "exceso de eritrocitos", "problema genético de sangre", "sangre pesada", "eritrocitosis hereditaria", "exceso de células sanguíneas", "aumento de masa eritrocitaria"]'),
('D75.1', 'Policitemia secundaria', 'Sin especificar', '["sangre espesa", "exceso de glóbulos rojos", "hematocrito alto", "sangre concentrada", "policitemia adquirida", "glóbulos rojos elevados", "problema de viscosidad sanguínea", "sangre densa", "mucha hemoglobina", "exceso de eritrocitos", "sangre cargada", "poliglobulia"]'),
('D75.81', 'Mielofibrosis', 'Sin especificar', '["cicatrización de médula ósea", "fibrosis medular", "problema de médula", "insuficiencia medular", "médula endurecida", "anemia por fibrosis", "trastorno de la médula", "médula que no produce sangre", "mielofibrosis idiopática", "problema hematológico severo", "tejido cicatricial en la médula"]'),
('D75.821', 'Trombocitopenia no inmune inducida por heparina', 'Sin especificar', '["plaquetas bajas por heparina", "reacción a la heparina", "trombocitopenia medicamentosa", "plaquetas en descenso", "efecto secundario de anticoagulantes", "bajada de plaquetas por fármaco", "problema de coagulación por heparina", "plaquetopenia no autoinmune", "reacción adversa a la heparina", "plaquetas caídas"]'),
('D75.822', 'Trombocitopenia inmune inducida por heparina', 'Sin especificar', '["HIT", "plaquetas bajas por heparina", "reacción autoinmune por heparina", "anticuerpos contra plaquetas", "trombocitopenia inducida por fármaco", "bajada peligrosa de plaquetas", "alergia a la heparina", "defensa contra plaquetas por heparina", "trastorno inmune plaquetario", "complicación de heparina", "ataque inmune a las plaquetas"]'),
('D75.828', 'Otro síndrome de trombocitopenia inducida por heparina', 'Sin especificar', '["bajada de plaquetas por heparina", "trombocitopenia por anticoagulantes", "plaquetas bajas", "problema plaquetario por medicamento", "reacción a heparina", "síndrome plaquetario", "caída de plaquetas", "complicación por inyección de heparina", "desorden de plaquetas por heparina"]'),
('D75.829', 'Trombocitopenia inducida por heparina, no especificada', 'Sin especificar', '["plaquetas bajas por medicamento", "trombocitopenia por heparina", "bajada de plaquetas", "efecto heparina", "problema de plaquetas", "caída de conteo plaquetario", "plaquetopenia", "reacción a inyecciones de sangre", "plaquetas en 0", "sangrado por plaquetas bajas"]'),
('D75.838', 'Otra trombocitosis', 'Sin especificar', '["exceso de plaquetas", "plaquetas altas", "muchas plaquetas", "trombocitosis reactiva", "sangre muy coagulable", "coagulación acelerada", "elevación de plaquetas", "conteo plaquetario alto", "hiperplaquetosis", "sangre espesa por plaquetas"]'),
('D75.839', 'Trombocitosis, no especificada', 'Sin especificar', '["muchas plaquetas", "plaquetas elevadas", "trombocitosis", "sangre muy espesa", "demasiadas plaquetas", "conteo alto de plaquetas", "problema de coagulación", "exceso plaquetario", "sangre pegajosa", "riesgo de coágulos por plaquetas"]'),
('D75.84', 'Otros trastornos anti-PF4 que activan las plaquetas', 'Sin especificar', '["activación plaquetaria", "problema de PF4", "trastorno plaquetario", "coagulación anormal", "plaquetas hiperactivas", "síndrome anti-PF4", "activación de plaquetas", "riesgo trombótico", "trastorno inmune plaquetario", "activación plaquetaria por anticuerpos"]'),
('D75.89', 'Otras enfermedades de la sangre y órganos hematopoyéticos especificadas', 'Sin especificar', '["enfermedad de la sangre", "problemas hematológicos", "problemas de bazo", "anemia rara", "trastorno de la sangre", "afección hematopoyética", "mal de la sangre", "problemas de producción de sangre", "enfermedad de médula ósea", "problema de los órganos de la sangre"]'),
('D75.9', 'Enfermedad de la sangre y órganos hematopoyéticos, no especificada', 'Sin especificar', '["enfermedad de la sangre", "problema de sangre", "anemia", "problema hematológico", "no sé qué tengo en la sangre", "enfermedad rara de sangre", "trastorno sanguíneo", "problema de defensas", "dolencia de sangre", "sangre rara", "problema de ganglios y bazo"]'),
('D75.A', 'Deficiencia de glucosa-6-fosfato deshidrogenasa (G6PD) sin anemia', 'Sin especificar', '["déficit de G6PD", "favismo", "alergia a las habas", "intolerancia a legumbres", "enfermedad de las habas", "genética de la sangre", "deficiencia enzimática", "problema de glóbulos rojos", "anemia por habas (sin anemia aún)", "deficiencia de enzima g6pd", "sensibilidad a medicamentos y habas"]');
