INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A81.00', 'Enfermedad de Creutzfeldt-Jakob, no especificada', 'Sin especificar', '["enfermedad de las vacas locas", "demencia fulminante", "priones", "degeneración cerebral rápida", "pérdida de memoria acelerada", "enfermedad neurodegenerativa rara", "encefalopatía espongiforme", "temblores incontrolables", "mioclonías", "rigidez muscular", "deterioro cognitivo veloz", "problemas de coordinación", "ataxia", "demencia progresiva", "enfermedad priónica"]'),
('A81.01', 'Variante de enfermedad de Creutzfeldt-Jakob', 'Sin especificar', '["nueva variante vCJD", "mal de las vacas locas humano", "variante humana de la enfermedad de las vacas locas", "infección por prión bovino", "trastorno neurológico severo", "demencia juvenil", "cambios psiquiátricos", "depresión y ansiedad extrema", "dolor persistente", "sacudidas musculares", "problemas al caminar", "inestabilidad al moverse", "atrofia cerebral", "neurodegeneración", "enfermedad por consumo de carne infectada"]'),
('A81.09', 'Otra enfermedad de Creutzfeldt-Jakob', 'Sin especificar', '["variante atípica de Creutzfeldt-Jakob", "espectro de enfermedades priónicas", "degeneración del sistema nervioso", "demencia esporádica", "confusión mental severa", "desorientación", "pérdida de funciones motoras", "habla arrastrada", "dificultad para hablar", "cambios de personalidad", "trastorno neurológico degenerativo", "ceguera cortical", "alucinaciones", "rigidez de extremidades", "muerte cerebral progresiva"]'),
('A81.1', 'Panencefalitis esclerosante subaguda', 'Sin especificar', '["PEES", "complicación del sarampión", "inflamación cerebral crónica", "secuelas de sarampión", "deterioro intelectual", "crisis epilépticas", "movimientos involuntarios", "espasmos", "pérdida de memoria", "declinación neurológica", "daño cerebral post-sarampión", "encefalitis crónica", "debilidad muscular", "rigidez espástica", "problemas visuales"]'),
('A81.2', 'Leucoencefalopatía multifocal progresiva', 'Sin especificar', '["LMP", "infección por virus JC", "daño en la sustancia blanca", "deficiencia inmunológica", "problemas de visión", "debilidad en un lado del cuerpo", "hemiparesia", "torpeza motora", "cambios de carácter", "pérdida del habla", "afasia", "encefalopatía viral", "problemas de equilibrio", "confusión progresiva", "disfunción cerebral"]'),
('A81.81', 'Kuru', 'Sin especificar', '["mal de la risa", "enfermedad caníbal", "temblores corporales", "pérdida de equilibrio", "ataxia cerebelosa", "inestabilidad al andar", "sacudidas de cabeza", "dificultad para tragar", "risa incontrolable", "deterioro neurológico", "enfermedad priónica de Papúa Nueva Guinea", "muerte por inanición", "tembladera", "trastorno del movimiento", "degeneración del sistema nervioso central"]'),
('A81.82', 'Síndrome de Gerstmann-Sträussler-Scheinker', 'Sin especificar', '["GSS", "atrofia cerebelosa", "descoordinación motora", "inestabilidad al caminar", "habla dificultosa", "disartria", "pérdida de reflejos", "demencia leve", "degeneración neuronal hereditaria", "trastorno priónico hereditario", "problemas de equilibrio", "rigidez muscular", "mioclonus", "pérdida de sensibilidad", "marcha inestable"]'),
('A81.83', 'Insomnio familiar fatal', 'Sin especificar', '["IFF", "insomnio total", "imposibilidad de dormir", "falta de sueño crónica", "deterioro del ciclo sueño-vigilia", "alucinaciones por falta de sueño", "pérdida de memoria", "desorientación", "delirios", "hiperactividad del sistema nervioso", "problemas de presión arterial", "sudoración excesiva", "pérdida de peso rápida", "trastorno genético del sueño", "muerte por insomnio"]'),
('A81.89', 'Otras infecciones por virus atípico del sistema nervioso central', 'Sin especificar', '["infecciones cerebrales raras", "virus lentos del cerebro", "encefalitis atípica", "daño neurológico viral", "meningoencefalitis crónica", "inflamación del cerebro", "trastornos degenerativos del SNC", "neuroinfección", "virus neurotrópicos", "deterioro del sistema nervioso", "infecciones cerebrales persistentes", "anomalías de la sustancia blanca", "enfermedades desmielinizantes virales", "problemas cognitivos virales", "ataxia progresiva"]'),
('A81.9', 'Infección viral atípica del sistema nervioso central', 'Sin especificar', '["infección viral del cerebro", "neurovirosis", "virus cerebral", "inflamación del sistema nervioso", "encefalopatía viral", "problemas de memoria y juicio", "cambios de personalidad por virus", "debilidad progresiva", "alteraciones motoras", "trastorno cerebral viral", "inflamación de la médula", "daño neurológico difuso", "infección del sistema nervioso", "síntomas neurológicos raros", "declinación cognitiva"]');
