INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N81.0', 'Uretrocele', 'Sin especificar', '["uretrocele", "bulto en la uretra", "bolita al orinar", "prolapso uretral", "descenso de uretra", "vejiga caída", "sensación de peso vaginal", "bulto al ir al baño", "problemas al orinar", "incontinencia urinaria", "hinchazón zona íntima", "vejiga que se baja", "bulto en la entrada de la vagina", "dolor al tener relaciones", "uretra descendida"]'),
('N81.10', 'Cistocele, no especificado', 'Sin especificar', '["cistocele", "vejiga caída", "vejiga descendida", "bulto en la vagina", "bajón de vejiga", "vejiga que se sale", "sensación de bulto", "prolapso de vejiga", "presión en la pelvis", "peso en la entrepierna", "incontinencia", "escapes de orina", "vejiga fuera de lugar", "bolsa en la vagina", "pesadez vaginal"]'),
('N81.11', 'Cistocele, medial', 'Sin especificar', '["cistocele medial", "vejiga caída central", "prolapso central", "bulto vaginal anterior", "debilidad pared vaginal", "vejiga descendida al centro", "presión pélvica central", "protuberancia en la vagina", "vejiga que baja por el medio", "falta de tono muscular", "incontinencia de esfuerzo", "sensación de tener algo entre las piernas", "problemas de suelo pélvico"]'),
('N81.12', 'Cistocele, lateral', 'Sin especificar', '["cistocele lateral", "vejiga caída lado", "desprendimiento lateral vejiga", "prolapso lateral", "bulto vaginal costado", "defectos paravaginales", "vejiga descendida lateralmente", "presión pélvica lateral", "debilidad de soporte lateral", "vejiga que se sale hacia el lado", "pesadez lateral", "incontinencia lateral", "fallo soportes vejiga"]'),
('N81.2', 'Prolapso uterovaginal incompleto', 'Sin especificar', '["prolapso uterino parcial", "matriz caída", "útero descendido", "útero que baja", "útero que se descuelga", "bajón de matriz", "sensación de matriz fuera", "prolapso incompleto", "matriz que no sale del todo", "pesadez pélvica", "útero fuera de su sitio", "dolor pélvico", "útero bajo", "cérvix descendido", "molestias al caminar"]'),
('N81.3', 'Prolapso uterovaginal completo', 'Sin especificar', '["prolapso uterino total", "procidencia uterina", "matriz afuera", "matriz que se sale", "útero fuera de la vagina", "matriz caída al exterior", "útero procidente", "útero que cuelga", "bulto total en la zona íntima", "útero expuesto", "matriz que asoma", "desprendimiento de matriz", "pérdida de soporte uterino", "útero que sale por la vagina"]'),
('N81.4', 'Prolapso uterovaginal, no especificado', 'Sin especificar', '["prolapso genital", "útero caído", "matriz caída", "bajón de matriz", "útero descolgado", "problemas de matriz", "caída de órganos pélvicos", "piso pélvico debilitado", "útero bajo", "sensación de peso vaginal", "bulto vaginal", "útero fuera de posición", "debilidad pélvica", "incontinencia", "dolor de matriz"]'),
('N81.5', 'Enterocele vaginal', 'Sin especificar', '["enterocele", "hernia vaginal", "prolapso de intestino", "intestino que baja a la vagina", "bolsa de intestino", "bulto en la parte superior de la vagina", "hernia de fondo de saco", "intestino empujando la vagina", "pesadez vaginal", "presión pélvica severa", "prolapso de cúpula", "hernia en la pelvis", "intestino descendido"]'),
('N81.6', 'Rectocele', 'Sin especificar', '["rectocele", "prolapso de recto", "recto caído", "recto que se sale", "hernia rectal hacia la vagina", "bulto vaginal posterior", "dificultad para defecar", "estreñimiento por prolapso", "bulto al ir al baño", "recto que empuja la vagina", "debilidad pared posterior", "caca atrapada en la vagina", "presión en el ano y vagina"]'),
('N81.81', 'Perineocele', 'Sin especificar', '["perineocele", "hernia perineal", "bulto en el periné", "prolapso perineal", "hernia entre vagina y ano", "debilitamiento del periné", "bulto en la zona del perineo", "hernia de suelo pélvico", "dolor perineal", "debilidad del perineo", "hernia rectoperineal", "abultamiento bajo", "bolita entre ano y vagina"]'),
('N81.82', 'Incompetencia o debilitamiento del tejido pubocervical', 'Sin especificar', '["debilidad pubocervical", "tejido vaginal débil", "falta de soporte de vejiga", "fascia pubocervical debilitada", "soporte vaginal flojo", "tejido estirado", "debilidad de paredes vaginales", "pérdida de elasticidad pélvica", "tejido de soporte dañado", "vejiga sin sostén", "falta de tono en vagina", "prolapso incipiente"]'),
('N81.83', 'Incompetencia o debilitamiento del tejido rectovaginal', 'Sin especificar', '["debilidad rectovaginal", "tabique rectovaginal débil", "fascia rectal floja", "soporte del recto debilitado", "tejido rectal estirado", "debilidad pared posterior vagina", "falta de soporte de recto", "recto con poco sostén", "tejido laxo entre recto y vagina", "pared vaginal posterior floja"]'),
('N81.84', 'Atrofia de la musculatura pélvica', 'Sin especificar', '["atrofia suelo pélvico", "músculos pélvicos débiles", "pérdida de fuerza vaginal", "suelo pélvico flojo", "debilidad muscular de pelvis", "músculos vaginales relajados", "falta de tono muscular", "pelvis sin fuerza", "atrofia muscular genital", "suelo pélvico atrofiado", "músculos pélvicos cansados", "falta de firmeza vaginal"]'),
('N81.85', 'Prolapso de muñón cervical', 'Sin especificar', '["prolapso de muñón", "prolapso de cúpula", "muñón cervical caído", "prolapso tras histerectomía", "cúpula vaginal que baja", "descenso de cúpula", "muñón de cérvix que sale", "bulto de cúpula vaginal", "cúpula vaginal descendida", "muñón fuera de lugar"]'),
('N81.89', 'Otros tipos de prolapso genital femenino', 'Sin especificar', '["prolapso pélvico", "fallo de órganos genitales", "descenso de órganos", "caída pélvica rara", "otros prolapsos", "inestabilidad de órganos pélvicos", "defectos del suelo pélvico", "desplazamiento de órganos internos", "falta de soporte genital"]'),
('N81.9', 'Prolapso genital femenino, no especificado', 'Sin especificar', '["prolapso", "se me bajó todo", "órganos caídos", "bajón de órganos", "pesadez en la entrepierna", "dolor pélvico", "bulto en la vagina", "sensación de que se sale algo", "prolapso sin especificar", "problemas de piso pélvico", "suelo pélvico descolgado", "bulto genital", "presión pélvica", "incomodidad vaginal"]');
