INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P12.0', 'Cefalohematoma debido a traumatismo del nacimiento', 'Sin especificar', '["bolita en la cabeza del bebé", "chichón recién nacido", "hematoma neonatal", "hinchazón cabeza bebé parto", "sangre debajo del cuero cabelludo", "cabeza deforme recién nacido", "abultamiento cabeza bebé", "trauma al nacer", "hinchazón craneal", "chichón de parto", "colección sanguínea craneal", "bulto blando cabeza bebé", "lesión parto cráneo", "hinchazón tras parto"]'),
('P12.1', 'Moño (por ventosa) debido a traumatismo del nacimiento', 'Sin especificar', '["chichón ventosa", "marca de ventosa", "cabeza alargada recién nacido", "chichón de parto", "deformidad por vacío", "marcas de parto instrumental", "hinchazón por ventosa", "cabeza en punta recién nacido", "traumatismo ventosa", "chichón en forma de cono", "hinchazón alargada cráneo", "marca equipo extracción", "deformación cabeza ventosa", "moldeado craneal excesivo"]'),
('P12.2', 'Hemorragia subaponeurótica epicraneal por traumatismo del nacimiento', 'Sin especificar', '["sangrado bajo el cuero cabelludo", "hemorragia cabeza bebé", "colección sangre cráneo", "sangrado epicraneal", "sangre bajo la piel cabeza bebé", "complicación parto sangrado", "hinchazón grave cabeza recién nacido", "hemorragia pericraneal", "lesión vascular neonatal", "edema hemorrágico cabeza", "sangrado difuso cuero cabelludo", "hemorragia parto", "sangre atrapada cráneo", "urgencia hematoma bebé"]'),
('P12.3', 'Hematomas en cuero cabelludo debidos a traumatismo del nacimiento', 'Sin especificar', '["moratones cabeza bebé", "moretones recién nacido", "cardenales cráneo", "chichones de parto", "sangre bajo la piel recién nacido", "hematoma neonatal", "manchas moradas cabeza", "traumatismo cuero cabelludo", "lesión parto piel cabeza", "morados al nacer", "bultos con sangre cabeza", "manchas parto cabeza", "hematoma cuero cabelludo", "contusión neonatal"]'),
('P12.4', 'Lesión en cuero cabelludo del recién nacido debida a equipo de monitorización', 'Sin especificar', '["herida monitorización", "marca electrodo cabeza", "lesión electrodo recién nacido", "rasguño monitor fetal", "corte monitorización parto", "herida equipo parto", "marca dispositivo control bebé", "lesión cuero cabelludo bebé", "marcas al nacer por monitor", "electrodo cuero cabelludo", "herida cabeza neonatal", "punción monitor parto", "irritación cuero cabelludo", "trauma por sensor"]'),
('P12.81', 'Caput succedaneum', 'Sin especificar', '["cabeza ahuevada", "hinchazón cabeza bebé", "cabeza deforme parto", "chichón normal parto", "hinchazón cuero cabelludo recién nacido", "cabeza alargada", "edema cabeza recién nacido", "cabeza hinchada nacer", "deformidad craneal temporal", "chichón de canal de parto", "hinchazón blanda cráneo", "abultamiento cabeza bebé", "cabeza con forma rara", "hinchazón bajo la piel cabeza"]'),
('P12.89', 'Otro traumatismo del nacimiento en el cuero cabelludo', 'Sin especificar', '["lesión cuero cabelludo bebé", "daño piel cabeza recién nacido", "herida parto cabeza", "golpe al nacer", "traumatismo cabeza bebé", "rasguño parto", "corte cuero cabelludo recién nacido", "lesión parto", "daño cráneo recién nacido", "contusión cabeza bebé", "marca de parto", "herida por parto", "trauma nacimiento cráneo", "lesión piel neonatal"]'),
('P12.9', 'Traumatismo del nacimiento en cuero cabelludo, no especificado', 'Sin especificar', '["daño cabeza recién nacido", "problema cabeza al nacer", "lesión en la cabeza del bebé", "trauma de parto no identificado", "chichón o herida recién nacido", "dolencia cuero cabelludo bebé", "problemas cabeza post-parto", "daño cráneo recién nacido", "lesión neonatal cuero cabelludo", "traumatismo cráneo parto", "herida o marca cabeza bebé", "afectación cuero cabelludo", "golpe recién nacido parto", "traumatismo no especificado cuero cabelludo"]');
