INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('X78.0XXA', 'Lesiones autoinfligidas intencionadamente por un cristal afilado, contacto inicial', 'Sin especificar', '["corte con vidrio", "cortarse con vidrio", "vidrios rotos", "autolesión", "autoagresión", "hacerse daño", "trizas de vidrio", "cristales", "cortarse con espejo", "sangrado por vidrio", "herida por vidrio", "corte intencional", "crisis emocional", "emergencia psiquiátrica", "corte con botella"]'),
('X78.0XXD', 'Lesiones autoinfligidas intencionadamente por un cristal afilado, contacto sucesivo', 'Sin especificar', '["cura de heridas por vidrio", "seguimiento corte vidrio", "curación corte profundo", "cicatrización herida vidrio", "infección corte vidrio", "cuidado de heridas", "limpieza de corte", "puntadas por corte", "revisión herida", "curar tajos", "autolesión recurrente", "segunda visita por corte"]'),
('X78.0XXS', 'Lesiones autoinfligidas intencionadamente por un cristal afilado, secuela', 'Sin especificar', '["cicatriz de corte", "secuelas de autolesión", "marcas de cortes", "daño nervioso por corte", "queloides por vidrio", "cicatrices feas", "pérdida de sensibilidad", "secuela física autolesión", "cicatrices antiguas", "tatuaje cicatriz", "consecuencias corte", "rehabilitación tras corte"]'),
('X78.1XXA', 'Lesiones autoinfligidas intencionadamente por cuchillo, contacto inicial', 'Sin especificar', '["cortarse con cuchillo", "autoagresión con arma blanca", "hacerse tajos", "corte profundo", "intentar hacerse daño", "crisis nerviosa", "apuñalamiento autoinfligido", "herida con cuchillo", "sangrado grave", "autolesionarse", "emergencia hospitalaria", "corte en brazos", "corte en piernas", "acero", "cuchillazo"]'),
('X78.1XXD', 'Lesiones autoinfligidas intencionadamente por cuchillo, contacto sucesivo', 'Sin especificar', '["curación de cuchillazo", "seguimiento herida profunda", "puntos de sutura", "limpieza de herida", "cambio de vendajes", "revisión de cortes", "infección por cuchillo", "cura de tajos", "cicatrización dirigida", "control post-trauma", "atención hospitalaria", "curaciones sucesivas"]'),
('X78.1XXS', 'Lesiones autoinfligidas intencionadamente por cuchillo, secuela', 'Sin especificar', '["cicatriz por cuchillo", "marcas de autoagresión", "secuela física", "daño tendinoso", "pérdida de fuerza", "cicatriz queloide", "secuelas psicológicas", "cicatrices permanentes", "reparación estética", "discapacidad funcional", "marcas en la piel", "secuelas de corte profundo"]'),
('X78.2XXA', 'Lesiones autoinfligidas intencionadamente por espada o daga, contacto inicial', 'Sin especificar', '["corte con espada", "herida por daga", "autolesión con arma blanca", "autoagresión con filo", "cuchillo ceremonial", "puñal", "estoque", "arma blanca", "corte severo", "emergencia médica", "sangrado masivo", "apuñalamiento intencional", "daño autoinfligido", "hoja afilada"]'),
('X78.2XXD', 'Lesiones autoinfligidas intencionadamente por espada o daga, contacto sucesivo', 'Sin especificar', '["seguimiento de puñalada", "curación de herida por daga", "atención de secuela", "limpieza de herida profunda", "cambio de gasas", "control de hemorragia", "punzadas", "cuidado post-corte", "curas de urgencia", "cicatrización", "observación clínica"]'),
('X78.2XXS', 'Lesiones autoinfligidas intencionadamente por espada o daga, secuela', 'Sin especificar', '["cicatriz de daga", "daño tisular", "secuela de arma blanca", "cicatrices anchas", "atrofia muscular", "daño nervioso", "rehabilitación de herida", "secuelas funcionales", "cicatrización anómala", "marcas traumáticas"]'),
('X78.8XXA', 'Lesiones autoinfligidas intencionadamente por otro objeto puntiagudo, contacto inicial', 'Sin especificar', '["pincharse a propósito", "herida con objeto punzante", "autolesión con alfiler", "clavo", "punzón", "aguja", "objeto cortopunzante", "hacerse pinchazos", "corte con metal", "autoagresión", "crisis de ansiedad", "lesión cutánea", "herida sangrante", "pincharse"]'),
('X78.8XXD', 'Lesiones autoinfligidas intencionadamente por otro objeto puntiagudo, contacto sucesivo', 'Sin especificar', '["cura de pinchazo", "seguimiento herida punzante", "desinfección de herida", "limpieza de pinchazos", "control de infección", "revisión de punción", "cura de autolesión", "curaciones", "atención médica de pinchazos", "cuidado de heridas", "seguimiento médico"]'),
('X78.8XXS', 'Lesiones autoinfligidas intencionadamente por otro objeto puntiagudo, secuela', 'Sin especificar', '["cicatriz de pinchazo", "marcas de agujas", "secuelas de punción", "cicatrices pequeñas", "daño epidérmico", "marcas en la piel", "tatuaje post-lesión", "cicatrización residual", "lesión residual", "secuela autolesión"]'),
('X78.9XXA', 'Lesiones autoinfligidas intencionadamente por objeto cortante no especificado, contacto inicial', 'Sin especificar', '["corte intencional", "autolesionarse", "hacerse daño", "tajo", "cuchillada", "herida con objeto filoso", "corte en la piel", "autoagresión", "crisis emocional", "sangrado", "emergencia", "autolesión", "corte misterioso", "corte con navaja", "corte con cutter"]'),
('X78.9XXD', 'Lesiones autoinfligidas intencionadamente por objeto cortante no especificado, contacto sucesivo', 'Sin especificar', '["cura de corte", "seguimiento de autolesión", "limpieza de herida", "puntos", "suturas", "cambio de vendaje", "control de herida", "infección de corte", "curación", "atención de emergencia", "cuidado de tajos", "revisión de cortes"]'),
('X78.9XXS', 'Lesiones autoinfligidas intencionadamente por objeto cortante no especificado, secuela', 'Sin especificar', '["cicatriz", "marcas de cortes", "secuela de autolesión", "cicatrices antiguas", "tejido cicatricial", "queloides", "daño en la piel", "marcas visibles", "secuelas permanentes", "reparación de piel", "historial de autolesiones", "cicatrización"]');
