INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A56.00', 'Infección del tracto genitourinario inferior debida a clamidias, no especificada', 'Sin especificar', '["clamidia", "chlamydia", "its", "infección de transmisión sexual", "enfermedad venérea", "secreción genital", "ardor al orinar", "picazón genital", "flujo anormal", "ETS", "infección urinaria", "dolor al tener relaciones", "chequeo its", "bacterias zona íntima", "infección secreta", "contagio sexual"]'),
('A56.01', 'Cistitis y uretritis por clamidias', 'Sin especificar', '["cistitis", "uretritis", "ardor al hacer pis", "dolor al orinar", "ganas constantes de orinar", "escozor al miccionar", "orinar a cada rato", "pinchazos al orinar", "uretra inflamada", "infección en la uretra", "dolor de vejiga", "chorrito corto", "orina con mal olor", "quemazón urinaria", "clamidia en la uretra"]'),
('A56.02', 'Vulvovaginitis por clamidias', 'Sin especificar', '["vulvovaginitis", "flujo vaginal", "flujo con mal olor", "picazón en la vulva", "ardor vaginal", "infección de la vagina", "inflamación vulvar", "secreción amarillenta", "picor íntimo", "dolor en la zona genital femenina", "clamidia vaginal", "flujo raro", "irritación vulva", "vaginitis bacteriana"]'),
('A56.09', 'Otra infección por clamidias de tracto genitourinario inferior', 'Sin especificar', '["infección genital", "malestar en la zona íntima", "clamidia genital", "enfermedad de transmisión sexual", "infección de bajo vientre", "ardor genital", "escozor íntimo", "contagio genital", "bacterias en la zona baja", "dolor pélvico bajo", "síntomas de its", "infección persistente"]'),
('A56.11', 'Enfermedad pélvica inflamatoria femenina por clamidias', 'Sin especificar', '["enfermedad pélvica inflamatoria", "epi", "dolor de ovarios", "dolor de matriz", "dolor de vientre bajo", "infección pélvica", "dolor abdominal bajo", "clamidia profunda", "dolor al tener sexo", "inflamación de la pelvis", "dolor en la panza baja", "dolor en el bajo vientre", "infección en los anexos", "inflamación de órganos reproductores"]'),
('A56.19', 'Otra infección genitourinaria por clamidias', 'Sin especificar', '["infección urinaria por clamidia", "clamidia urinaria", "malestar genitourinario", "problemas para orinar", "dolor en el tracto urinario", "infección de transmisión sexual compleja", "dolor genital constante", "complicación de clamidia", "infección bacteriana urinaria", "clamidiasis urinaria"]'),
('A56.2', 'Infecciones del tracto genitourinario debidas a clamidias, no especificada', 'Sin especificar', '["clamidia", "contagio de clamidia", "its no diagnosticada", "infección venérea", "dolor al orinar", "secreción anormal", "enfermedad de pareja", "chequeo de clamidia", "bacteria de transmisión sexual", "prueba de its", "infección de vías urinarias por its"]'),
('A56.3', 'Infección del ano y del recto debida a clamidias', 'Sin especificar', '["proctitis", "dolor anal", "picazón en el ano", "dolor al defecar", "secreción anal", "infección rectal", "clamidia anal", "sangrado anal", "ardor en el recto", "dolor al ir al baño", "picazón rectal", "inflamación anal", "tenesmo rectal", "contagio anal", "infección zona posterior"]'),
('A56.4', 'Infección de faringe debida a clamidias', 'Sin especificar', '["faringitis por clamidia", "dolor de garganta", "clamidia en la garganta", "garganta irritada", "infección faríngea sexual", "ardor al tragar", "ganglios inflamados cuello", "infección bucofaríngea", "dolor al pasar saliva", "garganta roja", "contagio oral", "clamidia oral", "molestias en la garganta tras sexo oral"]'),
('A56.8', 'Infección de transmisión sexual de otras localizaciones debida a clamidias', 'Sin especificar', '["clamidia diseminada", "otra localización clamidia", "infección bacteriana its", "contagio poco común its", "problemas de clamidia", "síntomas raros its", "infección sistémica clamidia", "complicaciones por clamidiasis", "infección de transmisión sexual atípica"]');
