INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K76.0', 'Hígado graso (degeneración grasa) de hígado, no clasificado bajo otro concepto', 'Sin especificar', '["hígado graso", "esteatosis hepática", "grasa en el hígado", "hígado con grasa", "hígado inflamado", "hígado cargado", "hígado pesado", "dolor bajo las costillas", "molestias en el costado derecho", "hígado graso no alcohólico", "esteatosis", "exceso de grasa abdominal", "hígado enfermito", "dolor hepático"]'),
('K76.1', 'Congestión pasiva crónica de hígado', 'Sin especificar', '["congestión hepática", "hígado congestivo", "hígado grande", "hepatomegalia", "hinchazón abdominal", "hígado inflamado crónico", "pesadez en el abdomen", "dolor sordo en el hígado", "falla cardíaca hepática", "hígado congestionado", "dolor de panza crónico", "sensación de llenura constante", "hígado crecido"]'),
('K76.2', 'Necrosis hemorrágica central de hígado', 'Sin especificar', '["necrosis hepática", "muerte de tejido hepático", "sangrado en el hígado", "necrosis centrolobulillar", "falla hepática aguda", "daño hepático severo", "hemorragia hepática", "dolor abdominal intenso", "shock hepático", "descomposición del hígado", "ictericia severa", "hígado con necrosis", "emergencia hepática"]'),
('K76.3', 'Infarto de hígado', 'Sin especificar', '["infarto hepático", "ataque al hígado", "dolor agudo en el hígado", "muerte celular hepática", "isquemia hepática", "obstrucción arterial hepática", "necrosis por falta de sangre", "dolor en el costado derecho", "falla súbita del hígado", "dolor abdominal agudo", "infarto del tejido hepático", "complicación hepática", "dolor punzante bajo las costillas"]'),
('K76.4', 'Peliosis hepática', 'Sin especificar', '["peliosis hepática", "quistes de sangre en el hígado", "lagos sanguíneos en el hígado", "hígado con cavidades sanguíneas", "enfermedad vascular hepática", "lesión quística hepática", "sangrado hepático interno", "hígado esponjoso", "dilatación de sinusoides hepáticos", "problemas vasculares del hígado", "masas en el hígado", "peliosis"]'),
('K76.5', 'Enfermedad venooclusiva de hígado', 'Sin especificar', '["obstrucción venosa hepática", "síndrome de obstrucción sinusoidal", "taponamiento venas hígado", "venas hepáticas bloqueadas", "hígado obstruido", "ictericia y dolor abdominal", "ascitis", "hinchazón de panza por hígado", "falla del retorno venoso hepático", "venas tapadas hígado", "obstrucción sinusoidal", "daño hepático por tóxicos"]'),
('K76.6', 'Hipertensión portal', 'Sin especificar', '["presión alta en la vena porta", "hipertensión venosa portal", "venas varicosas en el esófago", "várices esofágicas", "hígado endurecido", "cirrosis y presión", "sangrado de várices", "presión en el sistema digestivo", "hinchazón abdominal grave", "ascitis por hipertensión", "venas del abdomen crecidas", "presión portal"]'),
('K76.7', 'Síndrome hepatorrenal', 'Sin especificar', '["falla del riñón por el hígado", "falla hepatorrenal", "problemas de riñón por cirrosis", "insuficiencia renal por hígado", "hígado y riñones fallando", "síndrome hígado-riñón", "orina poco por el hígado", "complicación renal hepática", "falla orgánica múltiple hepática", "ictericia y falla renal", "daño hepático que afecta riñón"]'),
('K76.81', 'Síndrome hepatopulmonar', 'Sin especificar', '["problemas de pulmón por el hígado", "falta de aire por enfermedad hepática", "hígado y pulmones", "dificultad para respirar por cirrosis", "síndrome hígado-pulmón", "oxigenación baja por hígado", "disnea hepática", "insuficiencia pulmonar hepática", "hipoxemia hepática", "cansancio al respirar hígado", "vasodilatación pulmonar por hígado"]'),
('K76.82', 'Encefalopatía hepática', 'Sin especificar', '["confusión por hígado", "hígado que afecta el cerebro", "delirio hepático", "tóxicos en el cerebro por hígado", "amoniaco alto en sangre", "cambios de humor por hígado", "adormecimiento por hígado", "coma hepático", "desorientación hepática", "pérdida de memoria por hígado", "hígado y mente", "encefalopatía por cirrosis", "babeo y desorientación"]'),
('K76.89', 'Otras enfermedades especificadas de hígado', 'Sin especificar', '["problemas hepáticos raros", "enfermedad del hígado poco común", "otras afecciones hepáticas", "molestia en el hígado", "daño hepático inespecífico", "dolor constante en la guata", "hígado enfermito", "malestar abdominal hepático", "desorden hepático específico", "chequeo de hígado", "complicaciones del hígado"]'),
('K76.9', 'Enfermedad hepática, no especificada', 'Sin especificar', '["dolor en el hígado", "problemas de hígado", "me duele la panza lado derecho", "tengo mal el hígado", "hígado inflamado", "hígado irritado", "enfermedad del hígado", "dolor bajo las costillas", "molestia abdominal derecha", "hígado graso o cirrosis", "estudios del hígado alterados", "dolor hepático general", "problema en el hígado", "hígado dañado"]');
