INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N05.0', 'Síndrome nefrítico no especificado con anomalía glomerular mínima', 'Sin especificar', '["mal funcionamiento de riñones", "orina con sangre", "orina oscura", "hinchazón de cara", "edema", "retención de líquidos", "problema en los filtros del riñón", "daño renal leve", "orina espumosa", "presión alta", "puffy eyes", "ojos hinchados", "riñones inflamados", "hematuria", "proteinuria"]'),
('N05.1', 'Síndrome nefrítico no especificado con lesiones glomerulares focales y segmentarias', 'Sin especificar', '["cicatrices en el riñón", "falla renal focal", "orina roja", "hinchazón en piernas", "edema en tobillos", "glomeruloesclerosis", "daño renal segmentario", "pérdida de proteínas por orina", "orina cargada", "dolor en la espalda baja", "inflamación renal", "problemas de filtración", "nefritis focal", "exceso de albúmina"]'),
('N05.2', 'Síndrome nefrítico no especificado con glomerulonefritis membranosa difusa', 'Sin especificar', '["daño en membrana renal", "nefritis membranosa", "orina con espuma", "pies hinchados", "retención de agua", "enfermedad de los riñones", "inflamación glomerular difusa", "orina turbia", "presión elevada", "problemas para orinar", "daño de filtros renales", "síndrome nefrótico", "hinchazón generalizada", "proteínas en la pipi"]'),
('N05.3', 'Síndrome nefrítico no especificado con glomerulonefritis proliferativa mesangial difusa', 'Sin especificar', '["proliferación mesangial", "inflamación de los riñones", "orina oscura como refresco", "hinchazón de parpados", "edema renal", "problemas glomerulares", "sangre en la orina", "proteínas en orina", "nefritis proliferativa", "daño renal crónico", "orina colúrica", "retención de líquidos", "fatiga renal", "malestar en zona renal"]'),
('N05.4', 'Síndrome nefrítico no especificados con glomerulonefritis proliferativa endocapilar difusa', 'Sin especificar', '["nefritis endocapilar", "inflamación renal aguda", "orina color coca-cola", "hinchazón de manos y cara", "edema pos-infeccioso", "problemas de filtración renal", "glomerulonefritis aguda", "sangre en el pipí", "orina espumosa", "hipertensión renal", "dolor lumbar", "filtrado renal deficiente", "daño de capilares renales"]'),
('N05.5', 'Síndrome nefrítico no especificado con glomerulonefritis mesangiocapilar difusa', 'Sin especificar', '["nefritis membranoproliferativa", "daño renal complejo", "orina con sangre", "hinchazón de pies", "edemas", "orina con proteínas", "insuficiencia renal", "inflamación de los glomérulos", "orina muy oscura", "hipertensión arterial", "daño en filtros del riñón", "fatiga por fallo renal", "exceso de líquido", "problemas renales graves"]'),
('N05.6', 'Síndrome nefrítico no especificado con enfermedad por depósitos densos', 'Sin especificar', '["enfermedad de depósitos densos", "problemas renales autoinmunes", "orina turbia", "proteínas en orina", "edema en cara y piernas", "hinchazón por riñón", "daño glomerular denso", "nefritis específica", "sangre en orina", "insuficiencia renal progresiva", "orina cargada", "problemas de filtrado", "hinchazón de guata", "retención de líquidos"]'),
('N05.7', 'Síndrome nefrítico no especificado con glomerulonefritis semilunar difusa', 'Sin especificar', '["glomerulonefritis rápidamente progresiva", "nefritis semilunar", "daño renal agresivo", "insuficiencia renal grave", "orina con sangre intensa", "anuria", "edema severo", "hinchazón de todo el cuerpo", "presión arterial alta", "pérdida rápida de función renal", "orina de color oscuro", "problemas de filtración rápida", "inflamación de semilunas renales"]'),
('N05.8', 'Síndrome nefrítico no especificado con otros cambios morfológicos', 'Sin especificar', '["nefritis inespecífica", "daño renal raro", "inflamación renal variada", "problemas en riñones", "orina anormal", "edema renal", "hinchazón por fallos de riñón", "proteínas en la pipi", "hematuria", "dolor en riñones", "filtrado renal alterado", "enfermedad glomerular inespecífica", "orina espumosa", "problemas de retención"]'),
('N05.9', 'Síndrome nefrítico no especificado con cambios morfológicos no especificados', 'Sin especificar', '["nefritis sin especificar", "problema renal desconocido", "orina con sangre", "orina espumosa", "edema", "hinchazón de cara y ojos", "problema de riñones", "inflamación renal", "proteínas en orina", "malestar renal", "orina oscura", "fallo en la filtración", "retención de líquidos", "hipertensión por riñón"]'),
('N05.A', 'Síndrome nefrítico no especificado con glomerulonefritis C3', 'Sin especificar', '["glomerulonefritis C3", "problema renal por complemento", "nefritis por C3", "orina con sangre", "hinchazón y edemas", "daño de riñón autoinmune", "proteínas en orina", "orina cargada", "fallo de filtración renal", "inflamación de los glomérulos", "orina espumosa", "problemas en la sangre y riñón", "retención de líquidos"]');
