INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N41.0', 'Prostatitis aguda', 'Sin especificar', '["prostatitis aguda", "infección de próstata", "inflamación próstata", "dolor al orinar", "ardor al orinar", "orinar a gotas", "dolor de huevos", "dolor perineal", "fiebre y escalofríos", "urgencia urinaria", "molestia al eyacular", "chorro débil", "infección urinaria hombres", "prostatitis repentina", "dolor pélvico agudo", "tenesmo vesical", "goteo posmiccional"]'),
('N41.1', 'Prostatitis crónica', 'Sin especificar', '["prostatitis crónica", "dolor de próstata persistente", "molestia en la ingle", "dolor crónico pélvico", "infección recurrente próstata", "ardor al orinar constante", "dolor al sentarse", "dolor testicular crónico", "eyaculación dolorosa", "orina turbia", "prostatitis persistente", "dolor bajo vientre", "frecuencia urinaria", "pesadez pélvica", "malestar en la próstata", "disuria crónica"]'),
('N41.2', 'Absceso de próstata', 'Sin especificar', '["absceso de próstata", "pus en la próstata", "infección grave próstata", "fuego en la próstata", "bolsa de pus próstata", "fiebre alta por próstata", "dolor intenso próstata", "obstrucción urinaria", "retención de orina", "hinchazón próstata", "inflamación severa próstata", "urgencia médica próstata", "dolor insoportable al orinar", "prostatitis complicada", "masa en próstata"]'),
('N41.3', 'Prostatocistitis', 'Sin especificar', '["prostatocistitis", "infección próstata y vejiga", "cistitis en hombres", "inflamación vejiga y próstata", "dolor al orinar hombre", "ardor vejiga", "infección urinaria combinada", "dolor pélvico y vesical", "ganas constantes de orinar", "orinar sangre", "espasmos vesicales", "infección de vías urinarias masculinas", "molestia baja espalda", "dolor suprapúbico"]'),
('N41.4', 'Prostatitis granulomatosa', 'Sin especificar', '["prostatitis granulomatosa", "inflamación crónica próstata", "nódulos en la próstata", "bultos en la próstata", "sospecha de cáncer próstata", "prostatitis específica", "inflamación granulomatosa", "dolor prostático persistente", "endurecimiento próstata", "prostatitis autoinmune", "biopsia próstata", "diagnóstico próstata", "prostatitis rara", "inflamación tejido prostático"]'),
('N41.8', 'Otras enfermedades inflamatorias de próstata', 'Sin especificar', '["otras enfermedades inflamatorias próstata", "inflamación glándula prostática", "problemas de próstata", "malestar prostático", "infección próstata", "dolor próstata", "prostatitis inflamatoria", "pesadez en la zona baja", "inflamación uretra y próstata", "irritación próstata", "molestias urinarias hombres", "complicaciones próstata", "dolor perineal", "enfermedad de la próstata"]'),
('N41.9', 'Enfermedad inflamatoria de próstata, no especificada', 'Sin especificar', '["enfermedad inflamatoria próstata", "problema próstata no diagnosticado", "dolor zona genital", "inflamación de la próstata", "molestia al orinar", "no sé qué tengo en la próstata", "infección prostática", "dolor al eyacular", "problemas al hacer pipí", "hinchazón zona pélvica", "molestia en la entrepierna", "inflamación próstata sin causa", "chequeo próstata", "dolor uretra"]');
