INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q62.0', 'Hidronefrosis congénita', 'Sin especificar', '["riñón hinchado bebé", "hidronefrosis", "orina retenida riñón", "riñón dilatado", "obstrucción urinaria congénita", "agua en el riñón", "riñón grande", "problema de riñones al nacer", "hidronefrosis neonatal", "pelvis renal dilatada", "uropatía obstructiva", "hinchazón renal", "riñones tapados congénito"]'),
('Q62.10', 'Oclusión congénita del uréter no especificada', 'Sin especificar', '["uréter tapado", "obstrucción ureteral", "bloqueo conducto orina", "uretra cerrada", "uréter obstruido", "problema para orinar congénito", "no sale orina bebé", "conducto renal tapado", "malformación conducto urinario", "estenosis ureteral", "uréter atresico", "uréter estenosado"]'),
('Q62.11', 'Oclusión congénita de la unión pieloureteral', 'Sin especificar', '["estenosis pieloureteral", "obstrucción unión riñón uréter", "bloqueo pieloureteral", "estrechez unión uréter", "obstrucción UPJ", "uréter bloqueado en el riñón", "problema salida orina riñón", "estrangulamiento uréter", "uretero-pielo obstrucción", "hidronefrosis pieloureteral", "defecto unión uréter renal"]'),
('Q62.12', 'Oclusión congénita del orificio ureterovesical', 'Sin especificar', '["obstrucción unión uréter vejiga", "uréter tapado en vejiga", "estenosis unión ureterovesical", "bloqueo entrada orina vejiga", "orificio ureteral cerrado", "problema salida uréter a vejiga", "estenosis meato ureteral", "uréter obstruido distal", "malformación unión vejiga uréter"]'),
('Q62.2', 'Megauréter congénito', 'Sin especificar', '["uréter gigante", "uréter dilatado", "megauréter", "uréter ensanchado", "ureterohidronefrosis", "conducto orina grande", "uréter muy ancho", "uréter agrandado al nacer", "megauréter congénito", "uréter redundante", "malformación uréter grande"]'),
('Q62.31', 'Ureterocele congénito ortotópico', 'Sin especificar', '["ureterocele", "quiste en el uréter", "bolsa en el uréter", "ureterocele intravesical", "inflamación final uréter", "abultamiento en vejiga", "ureterocele simple", "malformación uréter vejiga", "quiste urinario congénito", "obstrucción por ureterocele", "vejiga con quiste ureteral"]'),
('Q62.32', 'Cecoureterocele', 'Sin especificar', '["ureterocele ciego", "quiste uréter", "cecoureterocele", "ureterocele ectópico", "malformación uréter vejiga", "ureterocele complejo", "quiste en la salida de la orina", "ureterocele obstruyendo orina", "abultamiento ureteral congénito", "defecto uréter vejiga"]'),
('Q62.39', 'Otros defectos obstructivos de la pelvis renal y uréter', 'Sin especificar', '["obstrucción tracto urinario", "bloqueo pelvis renal", "defecto uréter", "problemas orina congénitos", "obstrucción vías urinarias", "malformación conductos orina", "estenosis renal", "obstrucción congénita vías urinarias", "uréter con problemas"]'),
('Q62.4', 'Agenesia del uréter', 'Sin especificar', '["falta de uréter", "uréter ausente", "agenesia ureteral", "no tiene uréter", "malformación urinaria congénita", "ausencia de conducto renal", "riñón sin conexión a vejiga", "defecto formación uréter", "uréter inexistente", "falta conducto urinario"]'),
('Q62.5', 'Duplicación ureteral', 'Sin especificar', '["uréter doble", "duplicidad ureteral", "dos uréteres en un riñón", "duplicación del conducto urinario", "uréteres extras", "sistema colector duplicado", "doble uréter", "malformación uréter doble", "uréter bífido"]'),
('Q62.60', 'Malposición del uréter no especificada', 'Sin especificar', '["uréter fuera de lugar", "posición anómala uréter", "uréter desplazado", "uréter mal posicionado", "anatomía uréter rara", "malformación posición uréter", "uréter torcido", "uréter no donde debe estar"]'),
('Q62.61', 'Desviación de uréter', 'Sin especificar', '["uréter desviado", "uréter desplazado", "uréter torcido", "uréter chueco", "uréter mal orientado", "desviación ureteral", "uréter fuera de su sitio", "problema trayecto uréter", "uréter mal alineado"]'),
('Q62.62', 'Desplazamiento del uréter', 'Sin especificar', '["uréter movido", "desplazamiento ureteral", "uréter fuera de posición", "uréter corrido", "uréter fuera de su trayecto normal", "malformación uréter posición", "uréter desplazado congénito", "problema ubicación uréter"]'),
('Q62.63', 'Implantación anómala del uréter', 'Sin especificar', '["uréter mal conectado", "implantación ureteral ectópica", "uréter que llega mal a la vejiga", "conexión uréter vejiga mal hecha", "uréter fuera de lugar vejiga", "implantación anormal uréter", "malformación conexión uréter", "uréter conectado donde no va"]'),
('Q62.69', 'Otra malposición del uréter', 'Sin especificar', '["anatomía rara uréter", "defecto posición uréter", "uréter con malformación", "posición extraña uréter", "uréter anómalo", "malformación conducto urinario", "problemas con el uréter congénitos"]'),
('Q62.7', 'Reflujo vésico-urétero-renal congénito', 'Sin especificar', '["reflujo vesicoureteral", "orina se regresa al riñón", "reflujo orina", "RVU", "infecciones de orina recurrentes niño", "reflujo renal", "orina vuelve al riñón", "problema válvulas vejiga", "reflujo vésico renal", "orina en el riñón", "malformación orina", "reflujo congénito"]'),
('Q62.8', 'Otras malformaciones congénitas del uréter', 'Sin especificar', '["defecto uréter", "uréter con malformación", "problema congénito uréter", "malformación vías urinarias", "uréter raro", "anomalía conducto urinario", "uréter mal formado", "defecto congénito conducto riñón"]');
