INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('W00.0XXA', 'Caída en el mismo nivel debida a hielo y nieve, contacto inicial', 'Sin especificar', '["resbalón", "patinada", "caída", "piso congelado", "me caí en la nieve", "resbalón en el hielo", "golpe por caída", "piso resbaloso", "accidente en la calle", "hielo en la vereda", "acera congelada", "me fui de espaldas", "porrazo", "chupón", "tortazo", "tropezón", "suelo escarchado"]'),
('W00.0XXD', 'Caída en el mismo nivel debida a hielo y nieve, contacto sucesivo', 'Sin especificar', '["seguimiento por caída", "dolor post caída", "revisión tras resbalón", "golpe por segunda vez", "complicación tras resbalar", "atención por caída previa", "dolor continuo por golpe", "cita de control por caída", "recaída por golpe", "secuelas de resbalón", "revisión de lesiones por hielo", "consulta post caída"]'),
('W00.0XXS', 'Caída en el mismo nivel debida a hielo y nieve, secuela', 'Sin especificar', '["dolor crónico por caída", "secuela de resbalón", "dolor de vieja herida", "complicación por golpe antiguo", "daño persistente por caída", "rehabilitación tras caída", "secuela por golpe en el hielo", "dolor persistente post accidente", "lesión mal curada por caída", "secuelas de piso resbaloso"]'),
('W00.1XXA', 'Caída desde las escaleras y escalones por hielo y nieve, contacto inicial', 'Sin especificar', '["caída en escalera", "escalones congelados", "resbalón en escaleras", "golpe en escalera", "caída en la nieve de la escalera", "me caí por las gradas", "resbalón en la escala", "accidente en peldaños", "caída de espaldas en escalera", "golpe bajando escaleras", "escalera con hielo", "porrazo en gradas", "guatazo en escalones", "me di un ranazo en la escalera"]'),
('W00.1XXD', 'Caída desde las escaleras y escalones por hielo y nieve, contacto sucesivo', 'Sin especificar', '["revisión por caída en escalera", "control post caída gradas", "dolor tras caída en escalones", "seguimiento por golpe en escalera", "complicación en escaleras", "atención médica tras rodar", "evaluación por caída previa en gradas", "dolor persistente tras resbalar en escalera"]'),
('W00.1XXS', 'Caída desde las escaleras y escalones por hielo y nieve, secuela', 'Sin especificar', '["secuela de caída en escalera", "dolor crónico tras rodar", "secuelas de accidente en escalones", "problema persistente tras caída", "rehabilitación por caída en escalera", "daño por caída antigua en gradas", "consecuencia de rodar por escalera"]'),
('W00.2XXA', 'Otras caídas entre distintos niveles por hielo y nieve, contacto inicial', 'Sin especificar', '["caída de altura en nieve", "caída de plataforma", "resbalón de nivel", "me caí desde una altura por hielo", "caída a distinto nivel", "accidente en nieve desde desnivel", "golpe al caer de un escalón alto", "caída de bordillo", "resbalón en pendiente", "caída desde talud"]'),
('W00.2XXD', 'Otras caídas entre distintos niveles por hielo y nieve, contacto sucesivo', 'Sin especificar', '["control tras caída de altura", "seguimiento por golpe de desnivel", "atención posterior a caída de altura", "revisión por caída en pendiente", "dolor post accidente en altura"]'),
('W00.2XXS', 'Otras caídas entre distintos niveles por hielo y nieve, secuela', 'Sin especificar', '["secuelas de caída de altura", "dolor prolongado por caída de nivel", "daño físico por accidente de desnivel", "consecuencias tras caída en nieve", "secuela de golpe por altura"]'),
('W00.9XXA', 'Caída no especificada debida a hielo o nieve, contacto inicial', 'Sin especificar', '["me caí con el hielo", "accidente en la nieve", "golpe por nieve", "resbalón inesperado", "me resbalé", "caída por piso escarchado", "accidente por resbalar", "porrazo por hielo", "chupón por nieve", "resbalón tonto", "me di un guamazo", "caída por mal clima"]'),
('W00.9XXD', 'Caída no especificada debida a hielo o nieve, contacto sucesivo', 'Sin especificar', '["revisión tras caída", "seguimiento por golpe", "dolor después de caerme", "control por resbalón", "atención médica de seguimiento", "evaluación post caída", "consulta por golpe anterior"]'),
('W00.9XXS', 'Caída no especificada debida a hielo o nieve, secuela', 'Sin especificar', '["dolor por caída antigua", "secuelas de un resbalón", "daño por caída pasada", "consecuencias de caída", "rehabilitación tras resbalón", "dolor crónico por caída en hielo"]');
