INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Y28.0XXA', 'Contacto con vidrio afilado, intención no determinada, contacto inicial', 'Sin especificar', '["cortada con vidrio", "herida por cristal", "vidrio roto", "me corté con un vidrio", "corte profundo", "vidrio tajante", "accidente con vidrio", "pedazo de vidrio", "corte en la piel", "herida abierta", "cristal filoso", "tajo por vidrio", "herida de emergencia", "primeros auxilios corte", "sangrado por vidrio"]'),
('Y28.0XXD', 'Contacto con vidrio afilado, intención no determinada, contacto sucesivo', 'Sin especificar', '["curación de herida de vidrio", "control de corte por cristal", "herida que no cierra", "seguimiento de cortada", "infección por vidrio", "limpieza de herida", "cicatrización lenta", "revisión de corte", "vidrio incrustado", "cuidado de puntos", "herida en proceso", "evolución de cortada", "revisión médica de corte", "tratamiento de herida", "curación de tajos"]'),
('Y28.0XXS', 'Contacto con vidrio afilado, intención no determinada, secuela', 'Sin especificar', '["cicatriz por vidrio", "secuela de corte", "marca de cortada", "daño nervioso por vidrio", "problemas de movilidad tras corte", "cicatriz queloide", "tejido cicatricial", "falta de sensibilidad en herida", "rigidez por cortada", "rehabilitación de herida", "problemas en tendones por vidrio", "secuela de accidente", "cicatriz antigua", "marcas permanentes", "reparación de cicatriz"]'),
('Y28.1XXA', 'Contacto con cuchillo, intención no determinada, contacto inicial', 'Sin especificar', '["cortada con cuchillo", "herida por arma blanca", "me corté cocinando", "tajo de cuchillo", "corte accidental", "accidente en la cocina", "sangrado por cuchillazo", "herida profunda", "filo de cuchillo", "cuchillo afilado", "incisión accidental", "herida sangrante", "cortadura grave", "primeros auxilios cuchillo", "corte en el dedo"]'),
('Y28.1XXD', 'Contacto con cuchillo, intención no determinada, contacto sucesivo', 'Sin especificar', '["curación de corte de cuchillo", "seguimiento de herida de cuchillo", "puntos de sutura", "control de infección de corte", "cuidado de cortada profunda", "limpieza de herida de cocina", "cicatrización de tajo", "revisión de sutura", "revisión médica", "evolución de herida", "tratamiento de cortes", "vendaje de herida", "control de inflamación", "chequeo de heridas", "cuidado de cortaduras"]'),
('Y28.1XXS', 'Contacto con cuchillo, intención no determinada, secuela', 'Sin especificar', '["cicatriz de cuchillo", "secuela de herida profunda", "daño en nervios por cuchillo", "pérdida de movilidad por corte", "cicatriz fea", "queloide de corte", "tejido con cicatriz", "dificultad para mover el dedo", "adormecimiento por corte", "rehabilitación tras corte", "marcas de cuchillazo", "secuelas funcionales", "cicatrización anormal", "problemas de agarre", "daño muscular"]'),
('Y28.2XXA', 'Contacto con espada o daga, intención no determinada, contacto inicial', 'Sin especificar', '["herida por espada", "cortada con daga", "estocada accidental", "corte con arma blanca", "herida penetrante", "accidente con espada", "tajazo", "cuchillada", "herida punzocortante", "lesión por arma", "corte profundo", "emergencia por espada", "choque con arma", "herida con filo", "accidente de esgrima"]'),
('Y28.2XXD', 'Contacto con espada o daga, intención no determinada, contacto sucesivo', 'Sin especificar', '["seguimiento de herida por espada", "curación de daga", "control de herida profunda", "revisión de suturas", "limpieza de herida por arma", "tratamiento post-herida", "cuidado de tejidos cortados", "cicatrización de estocada", "evolución de herida penetrante", "control de infección", "vendajes de larga duración", "terapia de cicatriz", "monitoreo médico", "revisión de tejidos", "chequeo de recuperación"]'),
('Y28.2XXS', 'Contacto con espada o daga, intención no determinada, secuela', 'Sin especificar', '["cicatriz de espada", "marca de daga", "secuela de herida penetrante", "daño muscular permanente", "pérdida de función", "cicatriz profunda", "adherencias cicatriciales", "dificultad motriz", "daño nervioso", "reconstrucción de cicatriz", "atrofia tras herida", "marcas en la piel", "problemas articulares", "secuelas estéticas", "daño en tendones"]'),
('Y28.8XXA', 'Contacto con otro objeto cortante, intención no determinada, contacto inicial', 'Sin especificar', '["cortada con objeto extraño", "corte con lámina", "herida por metal", "corte con herramienta", "accidente con objeto filoso", "me corté con metal", "herida accidental", "tajo con borde filoso", "corte con lata", "corte con papel", "herida con cutter", "corte con tijeras", "sangrado por objeto filoso", "herida abierta por metal", "accidente doméstico"]'),
('Y28.8XXD', 'Contacto con otro objeto cortante, intención no determinada, contacto sucesivo', 'Sin especificar', '["seguimiento de corte por objeto", "curación de herida por lata", "cuidado de corte por herramienta", "revisión de puntos", "limpieza de corte", "cicatrización de herida", "chequeo médico", "control de infección", "tratamiento de tajos", "evolución de la herida", "revisión de vendaje", "terapia de herida", "cuidado de cortes profundos", "evaluación de cicatrización", "revisión de laceraciones"]'),
('Y28.8XXS', 'Contacto con otro objeto cortante, intención no determinada, secuela', 'Sin especificar', '["cicatriz por objeto cortante", "secuela de corte accidental", "marcas de laceración", "cicatrización hipertrófica", "problemas de piel", "daño en la zona del corte", "sensibilidad en cicatriz", "tejido endurecido", "pérdida de textura", "problemas estéticos", "rehabilitación de tejido", "secuelas de cortaduras", "cicatriz permanente", "marcas de herramientas", "daño estructural"]'),
('Y28.9XXA', 'Contacto con objetos afilados no especificados, intención no determinada, contacto inicial', 'Sin especificar', '["me corté con algo", "herida por objeto filoso", "corte desconocido", "accidente con filo", "me hice una tajada", "herida punzante", "herida cortante", "sangrado inesperado", "corte en la piel", "objeto cortante", "herida de emergencia", "primeros auxilios", "cortadura", "lesión por objeto", "accidente filoso"]'),
('Y28.9XXD', 'Contacto con objetos afilados no especificados, intención no determinada, contacto sucesivo', 'Sin especificar', '["seguimiento de cortada", "curación de herida", "revisión de corte", "control de herida", "limpieza de herida", "chequeo de puntos", "revisión de sutura", "evolución de cortadura", "cuidado de la piel", "tratamiento de la herida", "monitoreo de infección", "revisión médica", "curaciones sucesivas", "vendaje de herida", "cuidado post-corte"]'),
('Y28.9XXS', 'Contacto con objetos afilados no especificados, intención no determinada, secuela', 'Sin especificar', '["cicatriz", "marca de corte", "secuela de herida", "tejido de cicatriz", "cicatrización", "problemas de cicatrización", "sensibilidad post-herida", "marca en la piel", "secuela funcional", "remodelación de cicatriz", "daño cutáneo", "problemas de regeneración", "marcas", "secuelas de accidentes", "cicatriz permanente"]');
