INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C74.00', 'Neoplasia maligna de corteza de glándula suprarrenal no especificada', 'Sin especificar', '["cáncer de glándula suprarrenal", "tumor en glándula suprarrenal", "tumor suprarrenal", "bolita en la glándula", "metástasis adrenal", "hiperplasia suprarrenal maligna", "cáncer adrenal", "tumor maligno glándula", "problemas de glándulas arriba del riñón", "cáncer endocrino", "nódulo suprarrenal maligno", "neoplasia adrenal", "masa en la glándula suprarrenal", "fallo de glándulas adrenales", "tumor maligno de corteza adrenal"]'),
('C74.01', 'Neoplasia maligna de corteza de glándula suprarrenal derecha', 'Sin especificar', '["cáncer suprarrenal derecho", "tumor adrenal derecho", "tumor en glándula del lado derecho", "cáncer de corteza adrenal derecha", "masa en glándula suprarrenal derecha", "nódulo maligno riñón derecho superior", "cáncer de la glándula sobre el riñón derecho", "tumor maligno zona derecha", "afectación suprarrenal derecha", "cáncer de glándula renal derecha", "tumor de corteza adrenal derecha", "crecimiento maligno suprarrenal derecho", "neoplasia adrenal derecha", "carcinoma suprarrenal derecho", "metástasis en glándula derecha"]'),
('C74.02', 'Neoplasia maligna de corteza de glándula suprarrenal izquierda', 'Sin especificar', '["cáncer suprarrenal izquierdo", "tumor adrenal izquierdo", "tumor en glándula del lado izquierdo", "cáncer de corteza adrenal izquierda", "masa en glándula suprarrenal izquierda", "nódulo maligno riñón izquierdo superior", "cáncer de la glándula sobre el riñón izquierdo", "tumor maligno zona izquierda", "afectación suprarrenal izquierda", "cáncer de glándula renal izquierda", "tumor de corteza adrenal izquierda", "crecimiento maligno suprarrenal izquierdo", "neoplasia adrenal izquierda", "carcinoma suprarrenal izquierdo", "metástasis en glándula izquierda"]'),
('C74.10', 'Neoplasia maligna de médula de glándula suprarrenal no especificada', 'Sin especificar', '["feocromocitoma maligno", "cáncer de médula suprarrenal", "tumor medular adrenal", "tumor de médula adrenal", "cáncer de glándula", "tumor endocrino maligno", "tumor productor de catecolaminas", "neoplasia medular", "tumor en la médula suprarrenal", "masa medular adrenal", "cáncer de las glándulas arriba de los riñones", "tumor maligno de la médula", "afección medular suprarrenal", "cáncer adrenal interno", "carcinoma medular suprarrenal"]'),
('C74.11', 'Neoplasia maligna de médula de glándula suprarrenal derecha', 'Sin especificar', '["feocromocitoma derecho", "cáncer medular suprarrenal derecho", "tumor de médula adrenal derecha", "tumor en la médula derecha", "cáncer en la parte interna de la suprarrenal derecha", "masa medular adrenal derecha", "neoplasia de médula derecha", "tumor maligno de médula derecha", "cáncer adrenal derecho central", "nódulo maligno médula derecha", "tumor de glándula superior derecha", "cáncer feocromocitoma", "tumor maligno de la médula del riñón derecho", "carcinoma de médula adrenal derecha", "tumor suprarrenal derecho profundo"]'),
('C74.12', 'Neoplasia maligna de médula de glándula suprarrenal izquierda', 'Sin especificar', '["feocromocitoma izquierdo", "cáncer medular suprarrenal izquierdo", "tumor de médula adrenal izquierda", "tumor en la médula izquierda", "cáncer en la parte interna de la suprarrenal izquierda", "masa medular adrenal izquierda", "neoplasia de médula izquierda", "tumor maligno de médula izquierda", "cáncer adrenal izquierdo central", "nódulo maligno médula izquierda", "tumor de glándula superior izquierda", "cáncer feocromocitoma izquierdo", "tumor maligno de la médula del riñón izquierdo", "carcinoma de médula adrenal izquierda", "tumor suprarrenal izquierdo profundo"]'),
('C74.90', 'Neoplasia maligna de parte no especificada de glándula suprarrenal no especificada', 'Sin especificar', '["cáncer de glándula suprarrenal", "tumor maligno adrenal", "cáncer adrenal", "masa en la suprarrenal", "tumor en glándula de riñón", "cáncer en glándula superior", "nódulo maligno suprarrenal", "neoplasia suprarrenal", "carcinoma de la glándula suprarrenal", "tumor maligno glándula suprarrenal", "problemas malignos suprarrenales", "bolita en la suprarrenal", "tumor en el riñón arriba", "enfermedad maligna suprarrenal", "tumor adrenal sin especificar"]'),
('C74.91', 'Neoplasia maligna de parte no especificada de glándula suprarrenal derecha', 'Sin especificar', '["cáncer suprarrenal derecho", "tumor en glándula derecha", "cáncer glándula renal derecha", "tumor maligno lado derecho arriba", "masa adrenal derecha", "cáncer en la parte superior del riñón derecho", "nódulo suprarrenal derecho", "neoplasia derecha", "tumor en la suprarrenal derecha", "carcinoma adrenal derecho", "tumor maligno glándula derecha", "crecimiento maligno riñón derecho", "afectación glándula derecha", "metástasis suprarrenal derecha", "cáncer de glándula de lado derecho"]'),
('C74.92', 'Neoplasia maligna de parte no especificada glándula suprarrenal izquierda', 'Sin especificar', '["cáncer suprarrenal izquierdo", "tumor en glándula izquierda", "cáncer glándula renal izquierda", "tumor maligno lado izquierdo arriba", "masa adrenal izquierda", "cáncer en la parte superior del riñón izquierdo", "nódulo suprarrenal izquierdo", "neoplasia izquierda", "tumor en la suprarrenal izquierda", "carcinoma adrenal izquierdo", "tumor maligno glándula izquierda", "crecimiento maligno riñón izquierdo", "afectación glándula izquierda", "metástasis suprarrenal izquierda", "cáncer de glándula de lado izquierdo"]');
