INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B40.0', 'Blastomicosis pulmonar aguda', 'Sin especificar', '["blastomicosis aguda", "infección por hongos en pulmón", "neumonía fúngica", "tos con sangre", "dolor al respirar", "fiebre alta y escalofríos", "dolor en el pecho", "pulmones comprometidos", "hongos en los pulmones", "infección pulmonar severa", "dificultad para respirar", "fatiga extrema", "blastomicosis fulminante", "micosis pulmonar", "inflamación de pulmones por hongos"]'),
('B40.1', 'Blastomicosis pulmonar crónica', 'Sin especificar', '["blastomicosis de larga duración", "tos persistente", "tuberculosis fúngica", "pérdida de peso inexplicable", "sudores nocturnos", "pulmones dañados", "infección crónica de pulmón", "malestar general crónico", "cansancio constante", "dolor torácico persistente", "micosis pulmonar lenta", "lesiones pulmonares", "blastomicosis persistente", "flema con sangre", "debilidad crónica"]'),
('B40.2', 'Blastomicosis pulmonar, no especificada', 'Sin especificar', '["problemas pulmonares por hongos", "infección de pecho", "dolor en la caja torácica", "blastomicosis de pulmón", "enfermedad fúngica pulmonar", "tos rara", "afección respiratoria por hongos", "dificultad para respirar por hongos", "malestar en los pulmones", "infección pulmonar sin clasificar", "síntomas respiratorios persistentes", "blastomicosis sin especificar", "micosis en el sistema respiratorio", "secreción pulmonar", "tos con flemas"]'),
('B40.3', 'Blastomicosis cutánea', 'Sin especificar', '["llagas en la piel", "heridas que no curan", "blastomicosis en la piel", "granos con pus", "úlceras cutáneas", "erupción por hongos", "ronchas infectadas", "lesiones en la cara", "costras en la piel", "infección micótica de la piel", "marcas en la piel", "bultos con pus", "piel lastimada", "micosis de piel", "heridas supurantes"]'),
('B40.7', 'Blastomicosis diseminada', 'Sin especificar', '["blastomicosis generalizada", "hongos en todo el cuerpo", "infección sistémica", "micosis avanzada", "blastomicosis sistémica", "debilitamiento general", "infección en varios órganos", "fiebre persistente", "dolor corporal", "blastomicosis que se esparció", "infección grave", "compromiso multiorgánico", "malestar generalizado", "blastomicosis terminal", "hongos en la sangre"]'),
('B40.81', 'Meningoencefalitis blastomicótica', 'Sin especificar', '["infección de cerebro por hongos", "meningitis por blastomicosis", "dolor de cabeza extremo", "cerebro inflamado", "infección de meninges", "confusión mental", "fiebre y rigidez de nuca", "problemas neurológicos", "blastomicosis cerebral", "encefalitis fúngica", "mareos severos", "convulsiones por infección", "inflamación de la cabeza", "infección fúngica del sistema nervioso", "migraña severa por hongo"]'),
('B40.89', 'Otras formas de blastomicosis', 'Sin especificar', '["blastomicosis atípica", "infección por hongos rara", "blastomicosis diseminada a huesos", "infección de articulaciones por hongos", "blastomicosis ósea", "infección de órganos internos", "blastomicosis ocular", "micosis poco comunes", "otras complicaciones de blastomicosis", "enfermedad fúngica rara", "blastomicosis extraña", "infección micótica inusual", "complicaciones por hongos", "blastomicosis diseminada en órganos", "infección fúngica sistémica adicional"]'),
('B40.9', 'Blastomicosis, no especificada', 'Sin especificar', '["hongos en el cuerpo", "infección por blastomyces", "enfermedad fúngica", "micosis general", "síntomas extraños por hongos", "infección que no sana", "blastomicosis general", "enfermedad por hongos", "dolores sin causa", "infección persistente", "blastomicosis sin especificar", "malestar por infección de hongos", "síntomas sistémicos", "problemas de salud por hongos", "infección micótica"]');
