INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('G96.00', 'Fuga de líquido cefalorraquídeo, no especificada', 'Sin especificar', '["pérdida de líquido cerebral", "fuga de licor", "líquido en la cabeza", "cefalea ortostática", "goteo de líquido cefalorraquídeo", "fuga de LCR", "dolor de cabeza por fuga", "fuga de líquido espinal", "dolor al levantarse", "filtración de líquido cerebral", "pérdida de líquido espinal", "presión baja en la cabeza", "dolor de nuca al estar de pie", "líquido que sale por la nariz o oídos"]'),
('G96.01', 'Fuga de líquido cefalorraquídeo craneal, espontánea', 'Sin especificar', '["fuga espontánea de LCR", "líquido saliendo por la nariz", "goteo por la nariz espontáneo", "fuga de líquido por el cráneo", "cefalea por baja presión espontánea", "fuga de licor sin golpe", "se me sale líquido por la nariz", "dolor de cabeza explosivo al pararme", "fuga de LCR idiopática", "líquido claro por la nariz", "fístula de líquido cefalorraquídeo craneal", "presión intracraneal baja", "dolor de cabeza que se quita al acostarse"]'),
('G96.02', 'Fuga de líquido cefalorraquídeo espinal, espontánea', 'Sin especificar', '["fuga de líquido en la espalda", "fuga espinal de LCR", "fuga espontánea de líquido espinal", "dolor de espalda baja y cabeza", "fístula de líquido espinal", "pérdida de LCR por la columna", "dolor al incorporarse", "cefalea postural espinal", "goteo de líquido espinal", "síndrome de presión baja de LCR", "fuga meníngea espinal", "dolor de cabeza persistente al estar de pie", "quiste de tarlov roto", "fuga por desgarro dural espontáneo"]'),
('G96.08', 'Otra fuga de líquido cefalorraquídeo craneal', 'Sin especificar', '["fuga de líquido cefalorraquídeo postraumática", "fuga craneal", "otolicuorrea", "rinolicuorrea", "líquido por los oídos", "fístula de LCR postquirúrgica", "goteo tras cirugía de cabeza", "fuga después de golpe en cráneo", "pérdida de líquido por oído", "salida de líquido cerebral por lesión", "fuga secundaria a procedimiento"]'),
('G96.09', 'Otra fuga de líquido cefalorraquídeo espinal', 'Sin especificar', '["fuga espinal traumática", "fuga tras punción lumbar", "líquido saliendo tras epidural", "fuga de LCR postquirúrgica", "dolor después de la raquia", "fuga tras anestesia espinal", "fístula de LCR en la columna", "dolor de cabeza después de punción", "fuga por lesión en la espalda", "goteo espinal post-procedimiento", "fuga de licor espinal"]'),
('G96.11', 'Desgarro de duramadre', 'Sin especificar', '["desgarro dural", "rotura de la duramadre", "desgarro de la meninge", "fuga tras epidural", "lesión de la membrana cerebral", "desgarro por punción", "dolor de cabeza post-punción", "herida en la duramadre", "desgarro durante cirugía espinal", "meninges rotas", "cefalea severa post-procedimiento", "desgarro de la cobertura del cerebro"]'),
('G96.12', 'Adherencias meníngeas (cerebrales) (medulares) (espinales) (raquídeas)', 'Sin especificar', '["meninges pegadas", "adherencias espinales", "fibrosis meníngea", "dolor crónico de espalda", "aracnoiditis", "meninges adheridas", "cicatriz en la columna", "nervios atrapados en la médula", "dolor por fibrosis espinal", "adherencias después de cirugía", "membranas cerebrales pegadas", "compresión medular por adherencias", "tejido cicatricial en la columna"]'),
('G96.191', 'Quiste perineural', 'Sin especificar', '["quiste de Tarlov", "quiste en la raíz nerviosa", "quiste en la columna", "quiste radicular", "dolor por quiste en el sacro", "quiste perineural espinal", "bolsa de líquido en el nervio", "dolor en el coxis por quiste", "tumor quístico en la columna", "quiste lumbar", "quiste de la vaina nerviosa", "dolor al estar sentado mucho tiempo"]'),
('G96.198', 'Otros trastornos de las meninges, no clasificados bajo otro concepto', 'Sin especificar', '["problemas de las meninges", "enfermedad de las cubiertas cerebrales", "inflamación meníngea no especificada", "trastornos de la duramadre", "engrosamiento meníngeo", "anomalía de las meninges", "dolor meningeo", "afección de las membranas del cerebro", "lesión meníngea", "fibrosis de las meninges"]'),
('G96.810', 'Hipotensión intracraneal, no especificada', 'Sin especificar', '["presión baja en el cerebro", "hipotensión de LCR", "dolor de cabeza por presión baja", "cefalea al pararse", "se me baja la presión en la cabeza", "presión intracraneal disminuida", "dolor de nuca y cabeza al levantarse", "hipotensión craneal", "pesadez de cabeza", "presión craneal baja", "dolor de cabeza postural"]'),
('G96.811', 'Hipotensión intracraneal, espontánea', 'Sin especificar', '["presión baja en la cabeza sin causa", "cefalea espontánea por baja presión", "hipotensión intracraneal idiopática", "dolor de cabeza severo que cede al acostarse", "presión baja espontánea del LCR", "dolor de cabeza postural espontáneo", "hipotensión de licor", "síndrome de presión baja espontánea", "cabeza pesada sin razón", "dolor de cuello y cabeza intenso"]'),
('G96.819', 'Otra hipotensión intracraneal', 'Sin especificar', '["baja presión craneal por fármacos", "hipotensión craneal secundaria", "presión intracraneal baja por cirugía", "dolor tras punción", "hipotensión de LCR post-traumática", "dolor de cabeza por baja presión en el cerebro", "presión baja por pérdida de LCR", "complicación de baja presión intracraneal"]'),
('G96.89', 'Otros trastornos especificados del sistema nervioso central', 'Sin especificar', '["problema neurológico", "afección del SNC", "trastorno del cerebro y columna", "enfermedad nerviosa central", "problemas de los nervios centrales", "trastornos del sistema nervioso no comunes", "daño del SNC", "patología del sistema nervioso central", "síntomas neurológicos raros"]'),
('G96.9', 'Trastorno del sistema nervioso central, no especificado', 'Sin especificar', '["problema en los nervios", "enfermedad del cerebro o columna", "dolor neurológico", "fallo del sistema nervioso", "trastorno neurológico sin nombre", "síntomas de los nervios", "problemas del SNC", "neuropatía central", "enfermedad rara del sistema nervioso", "trastorno del sistema nervioso no diagnosticado"]');
