INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D36.0', 'Neoplasia benigna de ganglios linfáticos', 'Sin especificar', '["bolita en el cuello", "ganglio inflamado", "adenopatía", "nódulo linfático", "inflamación de ganglios", "bulto en la axila", "ganglios crecidos", "adenitis benigna", "tumor benigno en ganglio", "bolitas en las ingles", "linfadenoma", "quiste linfático", "inflamación de glándulas", "crecimiento ganglionar", "bola debajo de la mandíbula"]'),
('D36.10', 'Neoplasia benigna de nervios periféricos y sistema nervioso autónomo, no especificados', 'Sin especificar', '["tumor de nervios", "neuroma benigno", "bulto en un nervio", "neurinoma", "schwannoma", "tumor nervioso", "bolita bajo la piel que duele", "dolor nervioso", "engrosamiento de un nervio", "crecimiento en nervio", "neoplasia del sistema nervioso", "neurofibroma", "masa nerviosa", "pinchazos constantes", "entumecimiento por bulto"]'),
('D36.11', 'Neoplasia benigna de nervios periféricos y sistema nervioso autónomo de cara, cabeza y cuello', 'Sin especificar', '["tumor en la cara", "bolita en el cuello", "neurinoma facial", "masa en la cabeza", "bulto en la nuca", "tumor de nervio craneal", "bolita cerca del oído", "tumor nervioso en el cuello", "bulto en la sien", "tumor benigno en la cara", "dolor de cara por bulto", "schwannoma de cabeza", "inflamación nerviosa facial", "bulto en la mandíbula", "tumor nervioso en el cuero cabelludo"]'),
('D36.12', 'Neoplasia benigna de nervios periféricos y sistema nervioso autónomo, extremidad superior, incluyendo hombro', 'Sin especificar', '["bolita en el brazo", "tumor en el hombro", "masa en la mano", "bulto en el antebrazo", "neurinoma en el brazo", "bolita en el codo", "dolor de nervio en el hombro", "bulto en la axila", "tumor nervioso en la muñeca", "crecimiento en el brazo", "hormigueo por bulto en brazo", "bulto en la articulación del hombro", "schwannoma de miembro superior", "quiste de nervio en el brazo", "masa en el bíceps"]'),
('D36.13', 'Neoplasia benigna de nervios periféricos y sistema nervioso autónomo de extremidad inferior, incluyendo cadera', 'Sin especificar', '["bolita en la pierna", "tumor en el muslo", "masa en la cadera", "bulto en el pie", "neurinoma en la pierna", "dolor nervioso en la cadera", "tumor en la rodilla", "bulto en el tobillo", "masa en el glúteo", "crecimiento nervioso en pierna", "schwannoma de miembro inferior", "bolita en la pantorrilla", "ciática por tumor", "bulto en la ingle", "dolor al caminar por bulto"]'),
('D36.14', 'Neoplasia benigna de nervios periféricos y sistema nervioso autónomo de tórax', 'Sin especificar', '["tumor en el pecho", "masa en el tórax", "bulto en la espalda alta", "tumor nervioso mediastínico", "dolor en el pecho por bulto", "masa torácica", "tumor de nervio intercostal", "bolita en la pared torácica", "opresión en el pecho por masa", "neurinoma torácico", "bulto sobre las costillas", "neoplasia intratorácica benigna", "bulto debajo de la clavícula", "tumor benigno de tórax", "molestia al respirar por bulto"]'),
('D36.15', 'Neoplasia benigna de nervios periféricos y sistema nervioso autónomo de abdomen', 'Sin especificar', '["bolita en la panza", "bulto en el abdomen", "tumor en la guata", "masa en la barriga", "dolor abdominal por bulto", "tumor nervioso abdominal", "inflamación en el estómago", "neurinoma abdominal", "bulto en el vientre", "masa en la tripa", "tumor retroperitoneal benigno", "bulto en el abdomen bajo", "masa nerviosa en el abdomen", "sensación de bulto en el abdomen", "bolita en el epigastrio"]'),
('D36.16', 'Neoplasia benigna de nervios periféricos y sistema nervioso autónomo de pelvis', 'Sin especificar', '["bulto en la pelvis", "tumor pélvico", "masa en la zona pélvica", "tumor nervioso en la pelvis", "dolor pélvico por bulto", "masa en el bajo vientre", "neurinoma pélvico", "bolita en la zona genital", "tumor benigno en la pelvis", "bulto en la zona del pubis", "presión pélvica", "masa en cavidad pélvica", "schwannoma pélvico", "bolita en la zona pélvica", "molestia interna en la pelvis"]'),
('D36.17', 'Neoplasia benigna de nervios periféricos y sistema nervioso autónomo de tronco, no especificada', 'Sin especificar', '["tumor en el tronco", "bulto en la espalda", "masa en el cuerpo", "tumor nervioso en el torso", "bolita en la columna", "masa en la cintura", "crecimiento en el tronco", "neurinoma del tronco", "tumor benigno del torso", "bulto en la espalda baja", "masa en la espalda media", "tumor de nervios en el torso", "bolita bajo la piel del torso", "masa profunda en el tronco", "schwannoma de tronco"]'),
('D36.7', 'Neoplasia benigna de otras localizaciones especificadas', 'Sin especificar', '["tumor benigno", "quiste", "bolita", "bulto", "neo", "neoplasia benigna", "masa benigna", "bolita de grasa", "nódulo benigno", "tumorcito", "crecimiento benigno", "tumor no cancerígeno", "bultito", "tumor localizado", "masa no maligna"]'),
('D36.9', 'Neoplasia benigna, localización no especificada', 'Sin especificar', '["tengo una bolita", "bulto extraño", "tumor benigno sin lugar", "tengo un bulto y no sé dónde es", "quiste o tumor benigno", "nódulo sin especificar", "masa bajo la piel", "bolita que me salió", "tengo un tumor pero es benigno", "crecimiento anormal benigno", "bulto desconocido", "neoplasia benigna no definida", "no sé qué es esta bola", "masa benigna inespecífica", "tumor no maligno en el cuerpo"]');
