INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('I65.01', 'Oclusión y estenosis de arteria vertebral derecha', 'Sin especificar', '["arteria tapada cuello", "bloqueo arteria vertebral", "isquemia vertebral derecha", "falta de riego al cerebro", "mareos por arteria cuello", "inestabilidad al caminar", "vértigo cervical", "dolor en nuca", "problemas vasculares cuello", "estrechamiento arteria derecha", "taponamiento arterial", "mala circulación cerebral", "obstrucción arterial derecha", "desmayos frecuentes", "visión borrosa por arteria"]'),
('I65.02', 'Oclusión y estenosis de arteria vertebral izquierda', 'Sin especificar', '["arteria vertebral izquierda tapada", "bloqueo arteria izquierda cuello", "estenosis vertebral izquierda", "mala irrigación cerebral", "mareos fuertes", "vértigo posicional", "entumecimiento cervical", "problemas de circulación cerebral", "arteria bloqueada lado izquierdo", "flujo sanguíneo cerebral disminuido", "insuficiencia vertebral izquierda", "arteriosclerosis vertebral", "pérdida de equilibrio", "zumbido en oídos", "náuseas por mareo"]'),
('I65.03', 'Oclusión y estenosis de arterias vertebrales bilateral', 'Sin especificar', '["arterias vertebrales tapadas", "bloqueo bilateral arterias cuello", "estenosis de ambas vertebrales", "falta de riego sanguíneo al cerebro", "riesgo de infarto cerebral", "mareo crónico severo", "inestabilidad constante", "problemas vasculares graves", "arterias del cuello obstruidas", "déficit de flujo cerebral", "mala irrigación bilateral", "taponamiento arterial doble", "dificultad para caminar por mareo", "desmayos inexplicables", "debilidad generalizada"]'),
('I65.09', 'Oclusión y estenosis de arteria vertebral no especificada', 'Sin especificar', '["arteria cuello tapada", "problemas de arterias vertebrales", "obstrucción de arteria vertebral", "mala circulación en el cuello", "mareos persistentes", "vértigo de origen cervical", "arteria vertebral cerrada", "estrechez en arterias del cuello", "falta de sangre al cerebro", "posible trombosis vertebral", "arteriosclerosis de cuello", "inestabilidad al levantarse", "dolor de cabeza tensional cervical", "desmayo súbito", "irrigación cerebral deficiente"]'),
('I65.1', 'Oclusión y estenosis de arteria basilar', 'Sin especificar', '["arteria basilar obstruida", "bloqueo de arteria basilar", "infarto de tronco cerebral", "trombosis basilar", "mareo extremo", "pérdida de conciencia", "visión doble", "dificultad para tragar", "debilidad en extremidades", "problemas de irrigación basilar", "estenosis de arteria basilar", "ataque isquémico transitorio", "vértigo severo", "parálisis facial", "dificultad para hablar"]'),
('I65.21', 'Oclusión y estenosis de arteria carótida derecha', 'Sin especificar', '["carótida derecha tapada", "bloqueo arteria carótida derecha", "estrechamiento carótida derecha", "placa en carótida derecha", "riesgo de derrame cerebral", "mala circulación hacia la cabeza", "soplos en carótida", "obstrucción arterial cuello", "falta de oxígeno al cerebro", "taponamiento arterial derecho", "entumecimiento lado izquierdo", "pérdida de fuerza brazo izquierdo", "arteriosclerosis carotídea", "problemas vasculares cerebrales", "carótida obstruida"]'),
('I65.22', 'Oclusión y estenosis de arteria carótida izquierda', 'Sin especificar', '["carótida izquierda obstruida", "bloqueo arteria cuello izquierda", "estenosis carótida izquierda", "placa de ateroma carótida", "riesgo de accidente cerebrovascular", "pérdida de sensibilidad lado derecho", "debilidad brazo derecho", "mala irrigación cerebral izquierda", "obstrucción flujo sanguíneo cabeza", "estrechez carotídea", "trombosis carótida izquierda", "mareos y desvanecimientos", "problemas de presión carotídea", "dificultad para hablar por arteria", "arteria del cuello cerrada"]'),
('I65.23', 'Oclusión y estenosis de arteria carótida bilateral', 'Sin especificar', '["carótidas tapadas", "obstrucción de ambas carótidas", "bloqueo carótida doble", "estrechamiento arterias cuello", "mala circulación cerebral severa", "riesgo alto de infarto cerebral", "desmayos por falta de riego", "arteriosclerosis severa en cuello", "déficit flujo sanguíneo cerebral", "taponamiento carotídeo bilateral", "inestabilidad y confusión", "problemas vasculares graves cuello", "estenosis carotídea crítica", "fatiga mental por mala irrigación", "vértigo constante"]'),
('I65.29', 'Oclusión y estenosis de arteria carótida, no especificada', 'Sin especificar', '["arteria carótida bloqueada", "taponamiento carótida", "estenosis de carótida", "problemas con la carótida", "mala irrigación cabeza", "obstrucción arterial cuello", "placa en la arteria del cuello", "riesgo de embolia cerebral", "arteriosclerosis de carótida", "estrechamiento de arteria cuello", "falta de riego sanguíneo", "mareos y debilidad", "dolor en la zona del cuello", "trombosis arterial cuello", "soplo carotídeo"]'),
('I65.8', 'Oclusión y estenosis de otras arterias precerebrales', 'Sin especificar', '["arterias cuello tapadas", "bloqueo arterias precerebrales", "problemas arterias cuello", "estenosis vasos sanguíneos cuello", "obstrucción arterias cabeza", "mala circulación hacia el cerebro", "falta de flujo sanguíneo cerebral", "arteriosclerosis en cuello", "taponamiento arterias cuello", "insuficiencia arterial precerebral", "problemas de riego sanguíneo al cerebro", "estrechez de vasos cervicales", "riesgo de ictus", "mareos por problemas circulatorios", "obstrucción arterial no definida"]'),
('I65.9', 'Oclusión y estenosis de arteria precerebral no especificada', 'Sin especificar', '["arteria tapada cuello", "mala circulación cuello", "obstrucción flujo cerebral", "arteria precerebral bloqueada", "falta de sangre al cerebro", "estenosis arterial cuello", "taponamiento vasos sanguíneos", "mareos constantes", "problemas arteriales cabeza", "obstrucción de vasos en el cuello", "riesgo de infarto cerebral", "arteriosclerosis cuello", "inestabilidad al caminar", "vértigo y confusión", "mala irrigación sanguínea"]');
