INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('R29.0', 'Tetania', 'Sin especificar', '["calambres musculares", "entumecimiento", "hormigueo en manos", "espasmos", "contracción involuntaria", "dedos en garra", "tirones", "rigidez muscular", "parálisis transitoria", "hormigueo facial", "calambre constante", "hormigueo boca", "temblor", "contractura", "rigidez manos"]'),
('R29.1', 'Meningismo', 'Sin especificar', '["rigidez de nuca", "dolor de cabeza fuerte", "cuello tieso", "no puedo doblar el cuello", "dolor al bajar la barbilla", "nuca rígida", "cefalea intensa", "dolor al mover la cabeza", "cuello trabado", "sensibilidad a la luz", "fotofobia", "fiebre y dolor de cabeza", "nuca dura"]'),
('R29.2', 'Reflejos anómalos', 'Sin especificar', '["reflejos raros", "falta de reflejos", "saltos incontrolables", "pierna que salta sola", "reflejos exagerados", "golpe en la rodilla sin respuesta", "reflejo ausente", "movimiento involuntario", "reacción rara", "nervios mal", "reflejos alterados", "problemas neurológicos", "respuesta muscular lenta"]'),
('R29.3', 'Postura anómala', 'Sin especificar', '["caminar raro", "cuerpo torcido", "postura extraña", "caminar chueco", "posición forzada", "rigidez al estar de pie", "postura encorvada", "inclinación del cuerpo", "problema de postura", "cuerpo rígido", "caminar de lado", "desalineación corporal", "postura antálgica"]'),
('R29.4', 'Chasquido de cadera', 'Sin especificar', '["cadera que suena", "truena la cadera", "cadera con clic", "chasquido al caminar", "cadera se traba", "crujido en la cadera", "sonido en la cadera", "cadera saltarina", "cadera que se desencaja", "dolor de cadera al mover", "chasquido al levantarse"]'),
('R29.5', 'Parálisis transitoria', 'Sin especificar', '["se me durmió el cuerpo", "pérdida de fuerza temporal", "parálisis pasajera", "debilidad que se quita", "no puedo mover el brazo un rato", "entumecimiento temporal", "cuerpo pesado", "se me fue la fuerza", "ataque isquémico transitorio", "debilidad repentina", "parálisis que desaparece"]'),
('R29.6', 'Caídas repetidas', 'Sin especificar', '["me caigo mucho", "se me doblan las piernas", "perder el equilibrio", "tropezones frecuentes", "desvanecimientos", "caerse solo", "falta de estabilidad", "inestabilidad al caminar", "mareos y caídas", "tropiezos al caminar", "débil de las piernas", "me voy de boca", "caídas frecuentes"]'),
('R29.700', 'Puntuación NIHSS 0', 'Sin especificar', '["sin déficit neurológico", "stroke cero", "ataque cerebral leve", "sin síntomas de ictus", "neurología normal", "test NIHSS cero", "evaluación ictus normal", "paciente sin ictus", "sin secuelas de derrame"]'),
('R29.701', 'Puntuación NIHSS 1', 'Sin especificar', '["ictus mínimo", "déficit neurológico muy leve", "NIHSS 1", "síntomas neurológicos mínimos", "derrame cerebral ligero", "evaluación stroke uno"]'),
('R29.702', 'Puntuación NIHSS 2', 'Sin especificar', '["ictus leve", "déficit neurológico leve", "NIHSS 2", "derrame cerebral leve", "secuelas mínimas", "problemas neurológicos leves"]'),
('R29.703', 'Puntuación NIHSS 3', 'Sin especificar', '["ictus leve", "déficit neurológico grado 3", "NIHSS 3", "derrame cerebral leve", "alteración neurológica pequeña"]'),
('R29.704', 'Puntuación NIHSS 4', 'Sin especificar', '["ictus leve", "déficit neurológico grado 4", "NIHSS 4", "derrame cerebral leve", "problema neurológico leve"]'),
('R29.705', 'Puntuación NIHSS 5', 'Sin especificar', '["ictus leve", "déficit neurológico grado 5", "NIHSS 5", "derrame cerebral moderado", "problema neurológico detectable"]'),
('R29.706', 'Puntuación NIHSS 6', 'Sin especificar', '["ictus leve a moderado", "déficit neurológico grado 6", "NIHSS 6", "derrame cerebral moderado"]'),
('R29.707', 'Puntuación NIHSS 7', 'Sin especificar', '["ictus moderado", "déficit neurológico grado 7", "NIHSS 7", "derrame cerebral moderado"]'),
('R29.708', 'Puntuación NIHSS 8', 'Sin especificar', '["ictus moderado", "déficit neurológico grado 8", "NIHSS 8", "derrame cerebral moderado"]'),
('R29.709', 'Puntuación NIHSS 9', 'Sin especificar', '["ictus moderado", "déficit neurológico grado 9", "NIHSS 9", "derrame cerebral moderado"]'),
('R29.710', 'Puntuación NIHSS 10', 'Sin especificar', '["ictus moderado", "déficit neurológico grado 10", "NIHSS 10", "derrame moderado"]'),
('R29.711', 'Puntuación NIHSS 11', 'Sin especificar', '["ictus moderado", "déficit neurológico grado 11", "NIHSS 11", "derrame moderado"]'),
('R29.712', 'Puntuación NIHSS 12', 'Sin especificar', '["ictus moderado a grave", "déficit neurológico grado 12", "NIHSS 12", "derrame moderado"]'),
('R29.713', 'Puntuación NIHSS 13', 'Sin especificar', '["ictus moderado a grave", "déficit neurológico grado 13", "NIHSS 13", "derrame moderado"]'),
('R29.714', 'Puntuación NIHSS 14', 'Sin especificar', '["ictus moderado a grave", "déficit neurológico grado 14", "NIHSS 14", "derrame moderado"]'),
('R29.715', 'Puntuación NIHSS 15', 'Sin especificar', '["ictus grave", "déficit neurológico grado 15", "NIHSS 15", "derrame cerebral grave"]'),
('R29.716', 'Puntuación NIHSS 16', 'Sin especificar', '["ictus grave", "déficit neurológico grado 16", "NIHSS 16", "derrame cerebral grave"]'),
('R29.717', 'Puntuación NIHSS 17', 'Sin especificar', '["ictus grave", "déficit neurológico grado 17", "NIHSS 17", "derrame cerebral grave"]'),
('R29.718', 'Puntuación NIHSS 18', 'Sin especificar', '["ictus grave", "déficit neurológico grado 18", "NIHSS 18", "derrame cerebral grave"]'),
('R29.719', 'Puntuación NIHSS 19', 'Sin especificar', '["ictus grave", "déficit neurológico grado 19", "NIHSS 19", "derrame cerebral grave"]'),
('R29.720', 'Puntuación NIHSS 20', 'Sin especificar', '["ictus grave", "déficit neurológico grado 20", "NIHSS 20", "derrame cerebral severo"]'),
('R29.721', 'Puntuación NIHSS 21', 'Sin especificar', '["ictus grave", "déficit neurológico grado 21", "NIHSS 21", "derrame cerebral severo"]'),
('R29.722', 'Puntuación NIHSS 22', 'Sin especificar', '["ictus grave", "déficit neurológico grado 22", "NIHSS 22", "derrame cerebral severo"]'),
('R29.723', 'Puntuación NIHSS 23', 'Sin especificar', '["ictus grave", "déficit neurológico grado 23", "NIHSS 23", "derrame cerebral severo"]'),
('R29.724', 'Puntuación NIHSS 24', 'Sin especificar', '["ictus grave", "déficit neurológico grado 24", "NIHSS 24", "derrame cerebral severo"]'),
('R29.725', 'Puntuación NIHSS 25', 'Sin especificar', '["ictus grave", "déficit neurológico grado 25", "NIHSS 25", "derrame severo"]'),
('R29.726', 'Puntuación NIHSS 26', 'Sin especificar', '["ictus grave", "déficit neurológico grado 26", "NIHSS 26", "derrame severo"]'),
('R29.727', 'Puntuación NIHSS 27', 'Sin especificar', '["ictus grave", "déficit neurológico grado 27", "NIHSS 27", "derrame severo"]'),
('R29.728', 'Puntuación NIHSS 28', 'Sin especificar', '["ictus grave", "déficit neurológico grado 28", "NIHSS 28", "derrame severo"]'),
('R29.729', 'Puntuación NIHSS 29', 'Sin especificar', '["ictus grave", "déficit neurológico grado 29", "NIHSS 29", "derrame severo"]'),
('R29.730', 'Puntuación NIHSS 30', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 30", "NIHSS 30", "derrame cerebral crítico"]'),
('R29.731', 'Puntuación NIHSS 31', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 31", "NIHSS 31", "derrame cerebral crítico"]'),
('R29.732', 'Puntuación NIHSS 32', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 32", "NIHSS 32", "derrame cerebral crítico"]'),
('R29.733', 'Puntuación NIHSS 33', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 33", "NIHSS 33", "derrame cerebral crítico"]'),
('R29.734', 'Puntuación NIHSS 34', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 34", "NIHSS 34", "derrame cerebral crítico"]'),
('R29.735', 'Puntuación NIHSS 35', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 35", "NIHSS 35", "derrame cerebral crítico"]'),
('R29.736', 'Puntuación NIHSS 36', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 36", "NIHSS 36", "derrame cerebral crítico"]'),
('R29.737', 'Puntuación NIHSS 37', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 37", "NIHSS 37", "derrame cerebral crítico"]'),
('R29.738', 'Puntuación NIHSS 38', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 38", "NIHSS 38", "derrame cerebral crítico"]'),
('R29.739', 'Puntuación NIHSS 39', 'Sin especificar', '["ictus muy grave", "déficit neurológico grado 39", "NIHSS 39", "derrame cerebral crítico"]'),
('R29.740', 'Puntuación NIHSS 40', 'Sin especificar', '["ictus máximo", "déficit neurológico grado 40", "NIHSS 40", "derrame cerebral severísimo"]'),
('R29.741', 'Puntuación NIHSS 41', 'Sin especificar', '["ictus máximo", "déficit neurológico grado 41", "NIHSS 41", "derrame cerebral severísimo"]'),
('R29.742', 'Puntuación NIHSS 42', 'Sin especificar', '["ictus máximo", "déficit neurológico grado 42", "NIHSS 42", "derrame cerebral severísimo"]'),
('R29.810', 'Debilidad facial', 'Sin especificar', '["cara torcida", "boca chueca", "se me cae la cara", "parálisis facial", "cara dormida", "párpado caído", "cara sin movimiento", "se me cae un lado de la boca", "sonrisa asimétrica", "debilidad en la cara", "cara rara"]'),
('R29.818', 'Otros síntomas y signos que afectan al sistema nervioso', 'Sin especificar', '["problemas neurológicos", "cosas raras en los nervios", "problemas de cabeza", "dolor neurológico", "sensaciones raras", "pérdida de sensibilidad", "entumecimiento raro", "fallos del sistema nervioso", "neuropatía"]'),
('R29.890', 'Pérdida de estatura', 'Sin especificar', '["me estoy haciendo más bajito", "encogimiento", "pérdida de altura", "me achico", "columna encorvada", "ser más bajo por la edad", "disminución de estatura", "encogerme"]'),
('R29.891', 'Tortícolis ocular', 'Sin especificar', '["ojo desviado", "cabeza inclinada", "mirar de lado", "ojos chuecos", "problema en la mirada", "ojo que se mueve solo", "visión doble con cabeza torcida", "tortícolis de origen visual", "mala alineación ocular"]'),
('R29.898', 'Otros síntomas y signos que afectan al aparato musculoesquelético', 'Sin especificar', '["dolor de huesos", "dolor muscular raro", "problemas de articulaciones", "molestias corporales", "dolor al moverse", "tensión muscular", "problemas esqueléticos", "rigidez corporal"]'),
('R29.90', 'Síntomas y signos no especificados que afectan al sistema nervioso', 'Sin especificar', '["problemas neurológicos no claros", "nervios mal", "mareos sin razón", "dolor extraño", "fallo neurológico", "problemas cerebrales no diagnosticados", "síntomas nerviosos raros"]'),
('R29.91', 'Síntomas y signos no especificados que afectan al aparato musculoesquelético', 'Sin especificar', '["dolor en el cuerpo no especificado", "molestia muscular no clara", "problema articular no definido", "dolor generalizado", "me duele todo el cuerpo", "dolor sin causa aparente"]');
