INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('G80.0', 'Parálisis cerebral espástica tetrapléjica', 'Sin especificar', '["parálisis cerebral total", "tetraparesia espástica", "parálisis de los cuatro miembros", "rigidez muscular generalizada", "parálisis cerebral severa", "espasmos en brazos y piernas", "tono muscular alto", "incapacidad motora total", "daño cerebral motor", "parálisis espástica general", "músculos duros", "problemas de motricidad global", "parálisis cuadripléjica", "daño neurológico infantil", "compromiso motor de las cuatro extremidades"]'),
('G80.1', 'Parálisis cerebral espástica dipléjica', 'Sin especificar', '["dipléjica espástica", "parálisis de piernas", "rigidez en miembros inferiores", "marcha en tijera", "diplejía cerebral", "espasmos en las piernas", "dificultad para caminar", "daño motor en tren inferior", "hipertonía en piernas", "parálisis cerebral de piernas", "músculos tensos en extremidades inferiores", "parálisis infantil de extremidades bajas", "problemas de marcha", "rigidez al andar"]'),
('G80.2', 'Parálisis cerebral espástica hemipléjica', 'Sin especificar', '["hemiplejia cerebral", "parálisis de un lado del cuerpo", "media parálisis", "espasmos en un lado", "rigidez de brazo y pierna", "parálisis unilateral", "daño motor de un costado", "invalidez de un hemicuerpo", "brazo y pierna rígidos", "afectación de un lado del cerebro", "parálisis cerebral de un lado", "dificultad motriz lateral", "rigidez unilateral", "postura asimétrica"]'),
('G80.3', 'Parálisis cerebral atetoide', 'Sin especificar', '["atetosis", "movimientos involuntarios", "parálisis cerebral discinética", "retorcimientos corporales", "movimientos incontrolados", "torceduras musculares", "distonía cerebral", "movimientos lentos y serpentinos", "falta de control muscular", "temblores constantes", "gestos involuntarios", "movimientos serpenteantes", "alteración del tono muscular", "inestabilidad de postura", "parálisis con movimientos extraños"]'),
('G80.4', 'Parálisis cerebral atáxica', 'Sin especificar', '["ataxia cerebral", "falta de equilibrio", "marcha inestable", "temblores al moverse", "torpeza motora", "incoordinación motriz", "problemas de equilibrio", "caídas frecuentes", "caminar tambaleante", "falta de precisión en movimientos", "parálisis cerebral con temblor", "dificultad de coordinación", "movimientos bruscos", "problemas de marcha atáxica", "descontrol de equilibrio"]'),
('G80.8', 'Otros tipos de parálisis cerebral', 'Sin especificar', '["daño neurológico infantil variado", "parálisis cerebral mixta", "trastorno motor cerebral", "problemas de desarrollo motor", "secuelas de daño cerebral", "parálisis cerebral atípica", "daño motriz no clasificado", "alteraciones motoras cerebrales", "parálisis infantil inespecífica", "trastorno neurológico infantil", "lesión cerebral del desarrollo", "complicaciones motoras cerebrales"]'),
('G80.9', 'Parálisis cerebral, no especificada', 'Sin especificar', '["parálisis cerebral", "daño cerebral infantil", "problemas de nacimiento", "retraso motor", "discapacidad motriz", "parálisis infantil", "lesión motora cerebral", "trastorno del movimiento", "invalidez infantil", "problemas neurológicos al nacer", "incapacidad motora", "daño cerebral perinatal", "problemas de desarrollo psicomotor", "parálisis del desarrollo"]');
