INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D14.0', 'Neoplasia benigna de oído medio, cavidad nasal y senos accesorios', 'Sin especificar', '["bolita en el oído", "tumor en la nariz", "bulto en la nariz", "pólipo nasal", "taponamiento nasal", "obstrucción de nariz", "se me tapa el oído", "zumbido en el oído", "dolor de senos paranasales", "crecimiento en la nariz", "masa en el oído", "sinusitis crónica", "nariz tapada", "tumor benigno de oído", "inflamación de senos accesorios"]'),
('D14.1', 'Neoplasia benigna de laringe', 'Sin especificar', '["ronquera constante", "voz tomada", "disfonía", "tumor en la garganta", "bulto en las cuerdas vocales", "me quedé sin voz", "carraspera", "nudo en la garganta", "pólipo en la laringe", "tengo algo atorado en la garganta", "dolor al hablar", "esfuerzo para hablar", "nódulo en garganta", "tumor benigno laringe", "afonía persistente"]'),
('D14.2', 'Neoplasia benigna de tráquea', 'Sin especificar', '["tumor en la tráquea", "bulto en el cuello", "obstrucción respiratoria", "dificultad para respirar", "sibilancias", "tos seca persistente", "tengo algo en la garganta", "silbido al respirar", "masa en la tráquea", "opresión en el pecho", "falta de aire", "neoplasia benigna tráquea", "crecimiento traqueal", "disnea", "tos con ruido"]'),
('D14.30', 'Neoplasia benigna de bronquio y pulmón no especificado', 'Sin especificar', '["tumor en el pulmón", "bulto en el pecho", "masa pulmonar benigna", "nódulo en el pulmón", "tengo una mancha en el pulmón", "dolor en el pecho", "tos con sangre", "dificultad para respirar", "falta de aire", "bronquios tapados", "flemas con sangre", "tumor benigno pulmón", "crecimiento pulmonar", "insuficiencia respiratoria", "tos crónica"]'),
('D14.31', 'Neoplasia benigna de bronquio y pulmón derecho', 'Sin especificar', '["tumor pulmón derecho", "dolor en el lado derecho del pecho", "bulto pulmón derecho", "masa pulmonar derecha", "nódulo en pulmón derecho", "pinchazos en el costado derecho", "molestia en el pecho derecho", "neoplasia benigna bronquio derecho", "crecimiento bronquial derecho", "dificultad para respirar lado derecho", "tengo una mancha en el pulmón derecho", "obstrucción bronquial derecha", "lesión pulmonar derecha", "tumor benigno bronquio derecho", "dolor al respirar profundo derecho"]'),
('D14.32', 'Neoplasia benigna de bronquio y pulmón izquierdo', 'Sin especificar', '["tumor pulmón izquierdo", "dolor en el lado izquierdo del pecho", "bulto pulmón izquierdo", "masa pulmonar izquierda", "nódulo en pulmón izquierdo", "pinchazos en el costado izquierdo", "molestia en el pecho izquierdo", "neoplasia benigna bronquio izquierdo", "crecimiento bronquial izquierdo", "dificultad para respirar lado izquierdo", "tengo una mancha en el pulmón izquierdo", "obstrucción bronquial izquierda", "lesión pulmonar izquierda", "tumor benigno bronquio izquierdo", "dolor al respirar profundo izquierdo"]'),
('D14.4', 'Neoplasia benigna de aparato respiratorio, no especificada', 'Sin especificar', '["tumor en las vías respiratorias", "bulto en el sistema respiratorio", "crecimiento en los pulmones", "problemas para respirar", "masa en vías aéreas", "neoplasia respiratoria benigna", "tengo algo en los pulmones", "obstrucción vías aéreas", "lesión benigna respiratoria", "dificultad respiratoria inexplicable", "tumor benigno vías respiratorias", "crecimiento en el pecho", "problemas de pecho", "afección respiratoria benigna", "bulto en el aparato respiratorio"]');
