INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('F65.0', 'Fetichismo', 'Sin especificar', '["fetiche", "obsesión con objetos", "atracción por cosas", "fetiches sexuales", "parafilia", "conducta sexual no convencional", "fijación sexual", "excitación por objetos", "fetiche pies", "fetiche ropa", "gustos sexuales particulares", "fetiche de objetos inanimados", "atracción inusual"]'),
('F65.1', 'Fetichismo travestista', 'Sin especificar', '["travestismo", "vestirse del sexo opuesto", "crossdressing", "travesti", "excitación al vestirse de mujer", "travesti fetichista", "transformismo", "cambio de ropa sexual", "placer al vestirse de otro género", "fetiche de travestismo", "ropa de mujer", "ropa de hombre", "fetiche de prendas"]'),
('F65.2', 'Exhibicionismo', 'Sin especificar', '["exhibicionista", "enseñar partes íntimas", "mostrar los genitales", "exponerse en público", "flashers", "mostrar el miembro", "exhibirse", "exhibicionismo callejero", "conducta exhibicionista", "mostrar sus partes", "desnudismo compulsivo", "enseñar el cuerpo", "exponer genitales"]'),
('F65.3', 'Voyeurismo', 'Sin especificar', '["voyeur", "mirón", "espiar", "ver a escondidas", "ver gente desnuda", "mirar por la ventana", "espiar gente", "placer al mirar", "obsesión por mirar", "mirón de baños", "mirón de alcobas", "ver actos sexuales en secreto", "cámara oculta", "fisgoneo"]'),
('F65.4', 'Pedofilia', 'Sin especificar', '["pedófilo", "abuso a menores", "atracción por niños", "abusador de menores", "depredador sexual", "pederastia", "excitación con niños", "pedofilia", "desviación sexual con menores", "abuso infantil", "pederasta", "atracción por menores", "pedofilia criminal"]'),
('F65.50', 'Sadomasoquismo, no especificado', 'Sin especificar', '["sadomasoquismo", "sado", "masoquismo", "sadismo", "juegos de dolor", "dolor y placer", "prácticas sado", "sado-maso", "dominación y sumisión", "BDSM", "amarrar a la pareja", "latigazos", "golpes por placer", "juegos de dolor y control"]'),
('F65.51', 'Masoquismo sexual', 'Sin especificar', '["masoquista", "placer al sufrir", "que me peguen", "humillación sexual", "gusto por el dolor", "atado", "placer en el dolor", "ser dominado", "sumisión", "masoquismo extremo", "dolor físico por sexo", "sufrir para excitarse", "juegos de sumisión"]'),
('F65.52', 'Sadismo sexual', 'Sin especificar', '["sádico", "hacer sufrir", "placer al lastimar", "golpear para excitarse", "dominador", "hacer daño a la pareja", "placer en el dolor ajeno", "sadismo", "controlar mediante dolor", "castigar sexualmente", "tortura sexual", "dominancia extrema", "placer en causar dolor"]'),
('F65.81', 'Froteurismo', 'Sin especificar', '["frotador", "frotarse en el transporte", "frotamiento", "apretarse contra otros", "acoso en el metro", "frotarse en lugares públicos", "contacto físico no deseado", "frotismo", "roce sexual", "frotarse con desconocidos", "tocamientos indebidos", "frotamiento compulsivo"]'),
('F65.89', 'Otros tipos de parafilia', 'Sin especificar', '["parafilias raras", "fetiches extraños", "conductas sexuales raras", "desviaciones sexuales", "gustos sexuales inusuales", "comportamiento sexual atípico", "parafilia rara", "fetiche raro", "práctica sexual extraña", "fetiche no común", "excitación inusual"]'),
('F65.9', 'Parafilia no especificada', 'Sin especificar', '["parafilia", "conducta sexual extraña", "desviación sexual", "comportamiento sexual raro", "problemas de conducta sexual", "fetiche sin nombre", "desorden de excitación", "trastorno parafílico", "gustos sexuales fuera de lo común", "parafilia sin clasificar", "comportamiento erótico extraño"]');
