INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('I21.01', 'Infarto agudo de miocardio con elevación de ST (IAMCEST) (IMEST) (STEMI) con implicación de arteria coronaria principal izquierda', 'Sin especificar', '["infarto", "ataque al corazón", "infarto masivo", "dolor en el pecho", "preinfarto", "infarto al miocardio", "paro cardíaco", "dolor opresivo en el pecho", "angustia en el pecho", "infarto coronario", "obstrucción coronaria", "apretón en el pecho", "ataque cardiaco", "dolor al brazo izquierdo", "falta de aire por infarto"]'),
('I21.02', 'Infarto agudo de miocardio con elevación de ST (IAMCEST) (IMEST) (STEMI) con implicación de arteria coronaria descendente anterior', 'Sin especificar', '["infarto coronario", "infarto en la cara anterior", "infarto de arteria principal", "dolor en el esternón", "pesadez en el pecho", "dolor irradiado al cuello", "ataque al corazón", "infarto severo", "dolor de infarto", "obstrucción arterial", "trombo coronario", "infarto anterior", "dolor punzante en el pecho", "ahogo por infarto", "sudoración fría por infarto"]'),
('I21.09', 'Infarto agudo de miocardio con elevación de ST (IAMCEST) (IMEST) (STEMI) con implicación de otra arteria coronaria de la cara anterior', 'Sin especificar', '["infarto anterior", "ataque al corazón", "dolor precordial", "opresión en el pecho", "infarto cardíaco", "dolor en la boca del estómago", "infarto de miocardio", "bloqueo coronario", "infarto cara anterior", "dolor en el pecho al esfuerzo", "pinchazos en el corazón", "dolor irradiado a la mandíbula", "infarto de cara anterior", "malestar coronario", "infarto agudo"]'),
('I21.11', 'Infarto agudo de miocardio con elevación de ST (IAMCEST) (IMEST) (STEMI) con implicación de arteria coronaria derecha', 'Sin especificar', '["infarto cara inferior", "infarto coronaria derecha", "dolor en el epigastrio", "dolor abdominal por infarto", "ataque al corazón", "infarto de miocardio", "dolor sordo en el pecho", "náuseas por infarto", "infarto de cara inferior", "obstrucción coronaria derecha", "dolor en la zona alta del abdomen", "infarto con dolor en el estómago", "malestar general intenso", "presión torácica", "infarto"]'),
('I21.19', 'Infarto agudo de miocardio con elevación de ST (IAMCEST) (IMEST) (STEMI) con implicación de otra arteria coronaria de cara inferior', 'Sin especificar', '["infarto cara inferior", "infarto cardíaco", "dolor en la parte baja del pecho", "infarto de miocardio", "dolor epigástrico", "ataque cardiaco", "molestia en el abdomen superior", "infarto de cara inferior", "obstrucción arterial menor", "dolor irradiado a la espalda", "infarto no especificado", "dolor torácico tipo infarto", "infarto con náuseas", "infarto sin síntomas típicos", "dolor de pecho sordo"]'),
('I21.21', 'Infarto agudo de miocardio con elevación de ST (IAMCEST) (IMEST) (STEMI) con implicación de la arteria coronaria circunfleja', 'Sin especificar', '["infarto circunfleja", "infarto cara lateral", "dolor en el costado izquierdo", "infarto cardíaco", "ataque al corazón", "dolor irradiado al hombro", "opresión torácica", "infarto lateral", "dolor en la espalda y pecho", "obstrucción de circunfleja", "infarto de miocardio", "dolor de infarto", "infarto con elevación ST", "dolor lateral del pecho", "infarto agudo"]'),
('I21.29', 'Infarto agudo de miocardio con elevación de ST (IAMCEST) (IMEST) (STEMI) de otra localización', 'Sin especificar', '["infarto de miocardio", "infarto atípico", "dolor en el pecho", "ataque cardiaco", "infarto con elevación ST", "infarto de cara posterior", "infarto localizado", "dolor en el tórax", "angina de pecho inestable", "infarto de arteria pequeña", "infarto no común", "dolor torácico severo", "síntomas de infarto", "infarto", "dolor de pecho inexplicable"]'),
('I21.3', 'Infarto agudo de miocardio con elevación de ST (IAMCEST) (IMEST) (STEMI) de localización no especificada', 'Sin especificar', '["infarto", "ataque al corazón", "dolor de pecho", "infarto fulminante", "infarto miocárdico", "dolor opresivo", "paro cardiaco", "infarto ST elevado", "infarto agudo", "dolor al pecho", "ataque al miocardio", "infarto al corazón", "infarto severo", "dolor punzante", "obstrucción coronaria"]'),
('I21.4', 'Infarto agudo de miocardio sin elevación de ST (IAMSEST) (IMNEST) (NSTEMI)', 'Sin especificar', '["infarto sin elevación ST", "infarto leve", "preinfarto", "angina inestable", "infarto NSTEMI", "dolor de pecho", "infarto pequeño", "ataque al corazón leve", "dolor persistente en el pecho", "infarto sin onda Q", "infarto que no se ve en EKG", "molestia en el tórax", "infarto silencioso", "infarto incompleto", "obstrucción parcial"]'),
('I21.9', 'Infarto agudo de miocardio, no especificado', 'Sin especificar', '["infarto", "ataque cardiaco", "infarto al miocardio", "dolor al corazón", "infarto del miocardio", "parada cardiaca", "dolor de pecho", "infarto coronario", "infarto agudo", "ataque al corazón", "problema cardiaco severo", "infarto no definido", "dolor en el centro del pecho", "infarto súbito", "emergencia cardiaca"]'),
('I21.A1', 'Infarto de miocardio tipo 2', 'Sin especificar', '["infarto tipo 2", "infarto por demanda", "infarto secundario", "infarto por anemia", "infarto por taquicardia", "infarto por presión alta", "infarto no coronario", "infarto por desequilibrio", "daño cardiaco por hipoxia", "infarto por falta de oxígeno", "infarto por estrés cardiaco", "infarto miocárdico tipo 2", "infarto por insuficiencia", "isquemia por demanda", "infarto por sobrecarga"]'),
('I21.A9', 'Otro tipo de infarto de miocardio', 'Sin especificar', '["infarto raro", "infarto de miocardio inespecífico", "otro tipo de infarto", "lesión cardiaca", "daño al miocardio", "infarto inusual", "infarto secundario a otra causa", "infarto post operatorio", "complicación cardiaca", "infarto multifactorial", "infarto por vasoespasmo", "infarto de otro origen", "infarto tipo 3", "infarto tipo 4", "infarto tipo 5"]'),
('I21.B', 'Infarto de miocardio con disfunción coronaria microvascular', 'Sin especificar', '["infarto microvascular", "infarto de arterias pequeñas", "infarto sin obstrucción de grandes vasos", "angina microvascular", "infarto con arterias limpias", "infarto por vasos pequeños", "disfunción coronaria", "infarto atípico", "dolor de pecho con coronarias limpias", "problemas en arterias pequeñas", "infarto de miocardio microvascular", "infarto femenino", "infarto con cateterismo normal", "isquemia microvascular", "infarto por capilares"]');
