INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H36.811', 'Retinopatía drepanocítica no proliferativa, ojo derecho', 'Sin especificar', '["ojo derecho", "vista borrosa", "anemia falciforme ojos", "drepanocitosis ocular", "sangrado ojo", "problemas retina", "daño retinal", "ojo derecho nublado", "hemorragia retiniana", "mala visión ojo derecho", "manchas en el ojo", "ceguera parcial", "retina dañada", "dolor ocular", "visión doble", "falla visual"]'),
('H36.812', 'Retinopatía drepanocítica no proliferativa, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "vista borrosa", "anemia falciforme ojos", "drepanocitosis ocular", "sangrado ojo", "problemas retina", "daño retinal", "ojo izquierdo nublado", "hemorragia retiniana", "mala visión ojo izquierdo", "manchas en el ojo", "ceguera parcial", "retina dañada", "dolor ocular", "visión doble", "falla visual"]'),
('H36.813', 'Retinopatía drepanocítica no proliferativa, bilateral', 'Sin especificar', '["ambos ojos", "vista borrosa total", "anemia falciforme ojos", "drepanocitosis ocular", "sangrado ojos", "problemas retina", "daño retinal bilateral", "ojos nublados", "hemorragia retiniana bilateral", "mala visión", "manchas en los ojos", "ceguera parcial", "retina dañada", "dolor ocular", "visión doble", "falla visual global"]'),
('H36.819', 'Retinopatía drepanocítica no proliferativa, ojo no especificado', 'Sin especificar', '["problemas de vista", "vista nublada", "anemia falciforme ojos", "drepanocitosis ocular", "sangrado ocular", "problemas retina", "daño retinal", "ojo afectado", "hemorragia retiniana", "mala visión", "manchas en la visión", "ceguera parcial", "retina dañada", "dolor de ojo", "visión borrosa", "falla visual inespecífica"]'),
('H36.821', 'Retinopatía drepanocítica proliferativa, ojo derecho', 'Sin especificar', '["ojo derecho", "visión perdida", "anemia falciforme severa", "neovascularización retiniana", "ojos con sangre", "desprendimiento retina", "daño retinal grave", "ceguera ojo derecho", "hemorragia vítrea", "vasos sanguíneos ojo", "visión distorsionada", "puntos negros en la vista", "retina dañada", "dolor ocular intenso", "visión de telarañas", "falla visual proliferativa"]'),
('H36.822', 'Retinopatía drepanocítica proliferativa, ojo izquierdo', 'Sin especificar', '["ojo izquierdo", "visión perdida", "anemia falciforme severa", "neovascularización retiniana", "ojos con sangre", "desprendimiento retina", "daño retinal grave", "ceguera ojo izquierdo", "hemorragia vítrea", "vasos sanguíneos ojo", "visión distorsionada", "puntos negros en la vista", "retina dañada", "dolor ocular intenso", "visión de telarañas", "falla visual proliferativa"]'),
('H36.823', 'Retinopatía drepanocítica proliferativa, bilateral', 'Sin especificar', '["ambos ojos", "visión muy borrosa", "anemia falciforme severa", "neovascularización", "ojos sangrantes", "desprendimiento de retina", "daño retinal severo", "ceguera", "hemorragia en el vitreo", "vasos sanguíneos anormales", "visión distorsionada", "manchas negras en la vista", "retinas dañadas", "dolor ocular", "visión de telarañas", "pérdida de vista"]'),
('H36.829', 'Retinopatía drepanocítica proliferativa, ojo no especificado', 'Sin especificar', '["problemas graves de ojo", "visión nublada", "anemia falciforme ojos", "formación vasos sanguíneos ojo", "hemorragia ocular", "problemas retina severos", "daño retinal", "ojo enfermo", "hemorragia vítrea", "mala visión", "puntos flotantes en ojo", "ceguera inminente", "retina dañada", "dolor de ojo intenso", "visión distorsionada", "falla visual proliferativa"]'),
('H36.89', 'Otros trastornos de retina en enfermedades clasificadas bajo otro concepto', 'Sin especificar', '["enfermedad en la vista", "daño en retina", "problemas visuales", "ojo enfermo", "dolor en el ojo", "vista nublada", "ceguera", "manchas al ver", "pérdida de visión", "retina enferma", "trastornos oculares sistémicos", "visión borrosa por enfermedad", "dolor ocular", "ojo irritado", "vista cansada extrema", "falla de la retina"]');
