INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P15.0', 'Traumatismo del nacimiento del hígado', 'Sin especificar', '["lesión hepática neonatal", "golpe en el hígado del bebé", "daño hepático parto", "trauma abdominal recién nacido", "ruptura hígado bebé", "sangrado hígado parto", "dolor hepático neonato", "complicación parto hígado", "lesión órganos internos bebé", "hematoma hepático parto", "traumatismo al nacer hígado", "estallido hepático parto"]'),
('P15.1', 'Traumatismo del nacimiento del bazo', 'Sin especificar', '["lesión esplénica neonatal", "daño en el bazo al nacer", "trauma del bazo bebé", "ruptura de bazo parto", "lesión abdominal recién nacido", "golpe bazo neonato", "complicación esplénica parto", "traumatismo bazo parto", "dolor bazo bebé", "hematoma esplénico neonato", "lesión órganos bazo recién nacido", "daño bazo al salir"]'),
('P15.2', 'Traumatismo del nacimiento de esternocleidomastoideo', 'Sin especificar', '["cuello torcido bebé", "lesión músculo cuello parto", "tortícolis neonatal", "trauma cuello bebé", "distensión cuello al nacer", "bola en el cuello bebé", "lesión esternocleidomastoideo", "cuello chueco recién nacido", "dolor cuello al nacer", "contractura cuello bebé parto", "traumatismo cuello neonato", "cuello tieso recién nacido"]'),
('P15.3', 'Traumatismo del nacimiento de los ojos', 'Sin especificar', '["ojo morado bebé al nacer", "lesión ocular parto", "daño en los ojos bebé", "trauma ocular recién nacido", "ojo hinchado parto", "ojo cerrado parto", "hemorragia subconjuntival bebé", "golpe en el ojo parto", "rasguño ojo bebé", "traumatismo ocular al nacer", "inflamación ojos recién nacido", "ojo rojo parto"]'),
('P15.4', 'Traumatismo del nacimiento de la cara', 'Sin especificar', '["cara golpeada bebé", "lesión facial parto", "cara hinchada recién nacido", "trauma cara al nacer", "chichón cara bebé", "moretones cara bebé", "rasguños cara al nacer", "herida cara parto", "hematoma cara bebé", "traumatismo facial recién nacido", "cara raspada parto", "daño tejido cara bebé"]'),
('P15.5', 'Traumatismo del nacimiento de genitales externos', 'Sin especificar', '["lesión genitales bebé", "hinchazón genital recién nacido", "daño genitales parto", "trauma zona íntima bebé", "golpe genitales al nacer", "hematoma escroto parto", "inflamación genital bebé", "traumatismo genitales recién nacido", "moretón genital parto", "lesión parte privada bebé", "hinchazón vulvar bebé parto", "daño área genital al nacer"]'),
('P15.6', 'Necrosis de grasa subcutánea debida a traumatismo del nacimiento', 'Sin especificar', '["grasa dura piel bebé", "bultos grasa recién nacido", "necrosis grasa parto", "lesión piel bebé parto", "nódulos grasa bebé", "endurecimiento piel bebé", "trauma grasa subcutánea", "bultitos duros bebé al nacer", "necrosis grasa neonatal", "bolitas piel recién nacido", "grasa dañada parto", "lesión tejido graso bebé"]'),
('P15.8', 'Otros traumatismos del nacimiento especificados', 'Sin especificar', '["lesión parto no clasificada", "daño por parto", "trauma al nacer", "complicaciones físicas parto", "lesiones neonatales", "traumatismo al salir", "golpes durante el parto", "daños físicos recién nacido", "lesión específica bebé", "problemas físicos nacimiento", "trauma obstétrico", "traumatismo al nacer otros"]'),
('P15.9', 'Traumatismo del nacimiento no especificado', 'Sin especificar', '["bebé lastimado parto", "lesión al nacer", "trauma parto desconocido", "golpe durante el nacimiento", "daño físico bebé parto", "problema al nacer", "lesión recién nacido", "traumatismo nacimiento", "daño no definido parto", "bebé golpeado nacimiento", "complicación parto", "lesión no especificada al nacer"]');
