INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('W23.0XXA', 'Atrapado, aplastado, atascado o comprimido entre objetos en movimiento, contacto inicial', 'Sin especificar', '["apachurrado", "prensa", "aplastamiento", "dedo machucado", "atrapado por maquinaria", "apretado", "accidentes laborales", "accidentes industriales", "aplastado por engranajes", "golpe con máquina", "atrapamiento mecánico", "apretón", "choque de objetos", "lesión por compresión", "atrapado entre piezas", "aplastado en el trabajo", "prensado"]'),
('W23.0XXD', 'Atrapado, aplastado, atascado o comprimido entre objetos en movimiento, contacto sucesivo', 'Sin especificar', '["seguimiento de aplastamiento", "cura de machucón", "control por aplastamiento", "revisión por atrapamiento", "dolor persistente por prensa", "evolución de machucón", "curación de dedo aplastado", "segunda consulta por apretón", "problemas tras accidente mecánico", "atención secundaria por compresión", "herida en recuperación por maquinaria", "dolor post accidente", "lesión recurrente por movimiento", "seguimiento de trauma mecánico"]'),
('W23.0XXS', 'Atrapado, aplastado, atascado o comprimido entre objetos en movimiento, secuela', 'Sin especificar', '["secuelas de aplastamiento", "dedo deforme por accidente", "cicatrices de prensa", "limitación de movimiento por machucón", "daño permanente mecánico", "secuelas de accidente industrial", "dedo atrofiado", "dificultad funcional tras atrapamiento", "secuelas de lesión por compresión", "dolor crónico tras accidente", "deformidad post aplastamiento", "rigidez articular por trauma", "consecuencias de atrapamiento antiguo", "invalidación por accidente"]'),
('W23.1XXA', 'Atrapado, aplastado, atascado o comprimido entre objetos inmóviles, contacto inicial', 'Sin especificar', '["apretado entre paredes", "atrapado en puertas", "dedos en la bisagra", "aplastado contra la pared", "atascado en mobiliario", "compresión por objeto fijo", "machucado con puerta", "apretón entre muebles", "atrapamiento estático", "dedo en ventana", "aplastado por estructura fija", "bloqueado entre objetos", "lesión por objeto inmóvil", "aplastamiento accidental", "atrapado entre piedras o paredes"]'),
('W23.1XXD', 'Atrapado, aplastado, atascado o comprimido entre objetos inmóviles, contacto sucesivo', 'Sin especificar', '["control por aplastamiento en puerta", "seguimiento de dedo machucado", "cura de herida por objeto fijo", "revisión por apretón", "dolor post machucón", "evolución de lesión en puerta", "control médico por compresión estática", "consulta de seguimiento por atrapamiento", "curación de trauma en bisagra", "valoración de lesión antigua", "segunda revisión por apretón", "atención por secuelas de compresión", "revisión tras accidente doméstico"]'),
('W23.1XXS', 'Atrapado, aplastado, atascado o comprimido entre objetos inmóviles, secuela', 'Sin especificar', '["secuelas de machucón", "dedo rígido por puerta", "daño permanente en dedos", "deformidad por atrapamiento", "limitación funcional post compresión", "cicatriz retráctil", "dolor crónico tras aplastamiento", "articulación dañada por puerta", "secuelas de accidente doméstico", "consecuencias de lesión estática", "pérdida de sensibilidad por apretón", "dificultad de agarre secuela", "secuelas post trauma", "daño articular antiguo"]'),
('W23.2XXA', 'Atrapado, aplastado, atascado o comprimido entre un objeto móvil y fijo, contacto inicial', 'Sin especificar', '["atrapado entre vehículo y pared", "aplastado contra el muro", "atrapamiento mixto", "apretado por máquina y pared", "dedo entre herramienta y banco", "compresión entre objeto y suelo", "atrapado por puerta eléctrica", "atrapado entre auto y poste", "machucón severo", "lesión por atrapamiento mecánico fijo", "atrapado en transporte", "aplastamiento accidental severo", "contacto inicial por compresión", "atascado en estructura móvil"]'),
('W23.2XXD', 'Atrapado, aplastado, atascado o comprimido entre un objeto móvil y fijo, contacto sucesivo', 'Sin especificar', '["seguimiento de trauma por aplastamiento", "cura de lesión por máquina y pared", "revisión post accidente de tráfico/trabajo", "evolución de compresión severa", "control médico tras atrapamiento", "curación de herida por objeto móvil-fijo", "dolor persistente post accidente", "atención secundaria por machucón complejo", "valoración de evolución de daño", "control por trauma por aplastamiento", "segunda consulta de lesiones graves"]'),
('W23.2XXS', 'Atrapado, aplastado, atascado o comprimido entre un objeto móvil y fijo, secuela', 'Sin especificar', '["secuelas de aplastamiento severo", "daño crónico por atrapamiento", "deformidad post compresión", "limitación de movimiento severa", "secuelas de accidente complejo", "dolor crónico post trauma", "pérdida de función tras aplastamiento", "cicatrices traumáticas", "secuelas de accidente laboral grave", "consecuencias de lesión por objeto móvil y fijo", "daño permanente en tejidos", "invalidación física por compresión", "secuelas de trauma mecánico", "secuelas post accidentes graves"]');
