INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S64.00XA', 'Traumatismo de nervio cubital a nivel de muñeca y mano, brazo no especificado, contacto inicial', 'Sin especificar', '["dolor en la mano", "hormigueo en el dedo meñique", "golpe en la muñeca", "adormecimiento mano", "lesión nervio cubital", "pinzamiento muñeca", "sensación de corriente en la mano", "debilidad para agarrar", "torpeza manual", "traumatismo mano", "nervio pinzado muñeca", "dedos dormidos", "dolor brazo", "lesión nerviosa muñeca", "golpe en el codo"]'),
('S64.00XD', 'Traumatismo de nervio cubital a nivel de muñeca y mano, brazo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión cubital", "dolor persistente mano", "rehabilitación mano", "terapia nervio cubital", "control traumatismo muñeca", "molestias continuas mano", "adormecimiento persistente", "evolución lesión nervio", "cita control mano", "sesión fisioterapia mano", "dolor crónico muñeca", "revisión golpe mano", "síntomas nervio cubital"]'),
('S64.00XS', 'Traumatismo de nervio cubital a nivel de muñeca y mano, brazo no especificado, secuela', 'Sin especificar', '["secuela lesión cubital", "atrofia muscular mano", "dedos en garra", "mano garra", "debilidad permanente mano", "pérdida sensibilidad mano", "dolor crónico postraumático", "cicatriz nerviosa", "discapacidad mano", "efecto secundario golpe muñeca", "daño nervioso permanente", "pérdida de fuerza mano"]'),
('S64.01XA', 'Traumatismo de nervio cubital a nivel de muñeca y mano, brazo derecho, contacto inicial', 'Sin especificar', '["golpe muñeca derecha", "nervio cubital brazo derecho", "hormigueo mano derecha", "lesión mano derecha", "traumatismo mano diestra", "dolor muñeca derecha", "adormecimiento dedos derecha", "accidente mano derecha"]'),
('S64.01XD', 'Traumatismo de nervio cubital a nivel de muñeca y mano, brazo derecho, contacto sucesivo', 'Sin especificar', '["control lesión mano derecha", "seguimiento nervio cubital derecho", "fisioterapia mano derecha", "evolución lesión derecha"]'),
('S64.01XS', 'Traumatismo de nervio cubital a nivel de muñeca y mano, brazo derecho, secuela', 'Sin especificar', '["secuela nervio cubital derecho", "daño permanente mano derecha", "pérdida fuerza mano derecha", "deformidad mano derecha"]'),
('S64.02XA', 'Traumatismo de nervio cubital a nivel de muñeca y mano, brazo izquierdo, contacto inicial', 'Sin especificar', '["golpe muñeca izquierda", "nervio cubital brazo izquierdo", "hormigueo mano izquierda", "lesión mano izquierda", "traumatismo mano zurda", "dolor muñeca izquierda", "adormecimiento dedos izquierda"]'),
('S64.02XD', 'Traumatismo de nervio cubital a nivel de muñeca y mano, brazo izquierdo, contacto sucesivo', 'Sin especificar', '["control lesión mano izquierda", "seguimiento nervio cubital izquierdo", "fisioterapia mano izquierda", "evolución lesión izquierda"]'),
('S64.02XS', 'Traumatismo de nervio cubital a nivel de muñeca y mano, brazo izquierdo, secuela', 'Sin especificar', '["secuela nervio cubital izquierdo", "daño permanente mano izquierda", "pérdida fuerza mano izquierda", "deformidad mano izquierda"]'),
('S64.10XA', 'Traumatismo de nervio mediano a nivel de muñeca y mano, brazo no especificado, contacto inicial', 'Sin especificar', '["síndrome túnel carpiano agudo", "dolor muñeca", "hormigueo pulgar e índice", "adormecimiento mano", "golpe en muñeca", "lesión nervio mediano", "pinchazos en dedos", "dolor al agarrar", "torpeza manos", "quemazón muñeca", "traumatismo mediano"]'),
('S64.10XD', 'Traumatismo de nervio mediano a nivel de muñeca y mano, brazo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento túnel carpiano", "rehabilitación nervio mediano", "control muñeca", "terapia física mano", "revisión lesión nerviosa"]'),
('S64.10XS', 'Traumatismo de nervio mediano a nivel de muñeca y mano, brazo no especificado, secuela', 'Sin especificar', '["atrofia músculo pulgar", "mano caída", "debilidad pinza", "secuela nervio mediano", "daño permanente mediano", "pérdida sensibilidad dedos"]'),
('S64.11XA', 'Traumatismo de nervio mediano a nivel de muñeca y mano, brazo derecho, contacto inicial', 'Sin especificar', '["dolor mano derecha", "túnel carpiano derecho", "golpe muñeca derecha", "lesión mediano mano derecha", "hormigueo pulgar derecho"]'),
('S64.11XD', 'Traumatismo de nervio mediano a nivel de muñeca y mano, brazo derecho, contacto sucesivo', 'Sin especificar', '["seguimiento mediano derecho", "control mano derecha", "fisioterapia derecha"]'),
('S64.11XS', 'Traumatismo de nervio mediano a nivel de muñeca y mano, brazo derecho, secuela', 'Sin especificar', '["secuela mano derecha", "daño permanente mediano derecho", "pérdida fuerza derecha"]'),
('S64.12XA', 'Traumatismo de nervio mediano a nivel de muñeca y mano, brazo izquierdo, contacto inicial', 'Sin especificar', '["dolor mano izquierda", "túnel carpiano izquierdo", "golpe muñeca izquierda", "lesión mediano mano izquierda", "hormigueo pulgar izquierdo"]'),
('S64.12XD', 'Traumatismo de nervio mediano a nivel de muñeca y mano, brazo izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento mediano izquierdo", "control mano izquierda", "fisioterapia izquierda"]'),
('S64.12XS', 'Traumatismo de nervio mediano a nivel de muñeca y mano, brazo izquierdo, secuela', 'Sin especificar', '["secuela mano izquierda", "daño permanente mediano izquierdo", "pérdida fuerza izquierda"]'),
('S64.20XA', 'Traumatismo de nervio radial a nivel de muñeca y mano, brazo no especificado, contacto inicial', 'Sin especificar', '["mano caída", "no puedo levantar la mano", "lesión nervio radial", "golpe muñeca", "debilidad muñeca", "pérdida extensión muñeca", "trauma radial", "adormecimiento dorso mano", "sensación de electricidad brazo"]'),
('S64.20XD', 'Traumatismo de nervio radial a nivel de muñeca y mano, brazo no especificado, contacto sucesivo', 'Sin especificar', '["rehabilitación mano caída", "control nervio radial", "terapia extensión muñeca", "seguimiento lesión radial"]'),
('S64.20XS', 'Traumatismo de nervio radial a nivel de muñeca y mano, brazo no especificado, secuela', 'Sin especificar', '["secuela mano caída", "parálisis radial", "debilidad permanente extensión", "daño crónico radial"]'),
('S64.21XA', 'Traumatismo de nervio radial a nivel de muñeca y mano, brazo derecho, contacto inicial', 'Sin especificar', '["mano derecha caída", "golpe muñeca derecha", "lesión radial derecha", "parálisis radial mano derecha"]'),
('S64.21XD', 'Traumatismo de nervio radial a nivel de muñeca y mano, brazo derecho, contacto sucesivo', 'Sin especificar', '["seguimiento radial derecho", "fisioterapia muñeca derecha"]'),
('S64.21XS', 'Traumatismo de nervio radial a nivel de muñeca y mano, brazo derecho, secuela', 'Sin especificar', '["secuela mano derecha caída", "daño permanente radial derecho"]'),
('S64.22XA', 'Traumatismo de nervio radial a nivel de muñeca y mano, brazo izquierdo, contacto inicial', 'Sin especificar', '["mano izquierda caída", "golpe muñeca izquierda", "lesión radial izquierda", "parálisis radial mano izquierda"]'),
('S64.22XD', 'Traumatismo de nervio radial a nivel de muñeca y mano, brazo izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento radial izquierdo", "fisioterapia muñeca izquierda"]'),
('S64.22XS', 'Traumatismo de nervio radial a nivel de muñeca y mano, brazo izquierdo, secuela', 'Sin especificar', '["secuela mano izquierda caída", "daño permanente radial izquierdo"]'),
('S64.30XA', 'Traumatismo de nervio digital de pulgar no especificado, contacto inicial', 'Sin especificar', '["golpe en el dedo gordo", "corte en el pulgar", "dedo gordo dormido", "lesión nervio pulgar", "dolor pulgar", "punzada en el dedo", "accidente pulgar", "falta de sensibilidad pulgar"]'),
('S64.30XD', 'Traumatismo de nervio digital de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["curación herida pulgar", "control nervio dedo", "seguimiento lesión pulgar"]'),
('S64.30XS', 'Traumatismo de nervio digital de pulgar no especificado, secuela', 'Sin especificar', '["cicatriz nervio pulgar", "entumecimiento crónico pulgar", "pérdida sensibilidad dedo gordo"]'),
('S64.31XA', 'Traumatismo de nervio digital de pulgar derecho, contacto inicial', 'Sin especificar', '["golpe pulgar derecho", "lesión nervio dedo gordo derecho", "corte pulgar derecho"]'),
('S64.31XD', 'Traumatismo de nervio digital de pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento pulgar derecho", "control dedo derecho"]'),
('S64.31XS', 'Traumatismo de nervio digital de pulgar derecho, secuela', 'Sin especificar', '["daño permanente pulgar derecho", "secuela dedo derecho"]'),
('S64.32XA', 'Traumatismo de nervio digital de pulgar izquierdo, contacto inicial', 'Sin especificar', '["golpe pulgar izquierdo", "lesión nervio dedo gordo izquierdo", "corte pulgar izquierdo"]'),
('S64.32XD', 'Traumatismo de nervio digital de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento pulgar izquierdo", "control dedo izquierdo"]'),
('S64.32XS', 'Traumatismo de nervio digital de pulgar izquierdo, secuela', 'Sin especificar', '["daño permanente pulgar izquierdo", "secuela dedo izquierdo"]'),
('S64.40XA', 'Traumatismo de nervio digital de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["corte en el dedo", "golpe dedo", "dedo dormido", "pinchazo dedo", "lesión nerviosa dedo", "dolor agudo dedo", "accidente dedo"]'),
('S64.40XD', 'Traumatismo de nervio digital de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento herida dedo", "control nervio dedo", "curación dedo"]'),
('S64.40XS', 'Traumatismo de nervio digital de dedo de mano no especificado, secuela', 'Sin especificar', '["pérdida sensibilidad dedo", "cicatriz dolorosa dedo", "entumecimiento dedo"]'),
('S64.490A', 'Traumatismo de nervio digital de dedo índice derecho, contacto inicial', 'Sin especificar', '["corte dedo índice derecho", "golpe índice derecho", "lesión nervio índice derecho"]'),
('S64.490D', 'Traumatismo de nervio digital de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["control índice derecho", "seguimiento herida índice"]'),
('S64.490S', 'Traumatismo de nervio digital de dedo índice derecho, secuela', 'Sin especificar', '["daño permanente índice derecho", "pérdida tacto índice"]'),
('S64.491A', 'Traumatismo de nervio digital de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["corte dedo índice izquierdo", "golpe índice izquierdo", "lesión nervio índice izquierdo"]'),
('S64.491D', 'Traumatismo de nervio digital de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["control índice izquierdo", "seguimiento herida índice"]'),
('S64.491S', 'Traumatismo de nervio digital de dedo índice izquierdo, secuela', 'Sin especificar', '["daño permanente índice izquierdo", "pérdida tacto índice"]'),
('S64.492A', 'Traumatismo de nervio digital de dedo medio derecho, contacto inicial', 'Sin especificar', '["corte dedo corazón derecho", "lesión nervio dedo medio derecho"]'),
('S64.492D', 'Traumatismo de nervio digital de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["seguimiento dedo medio derecho"]'),
('S64.492S', 'Traumatismo de nervio digital de dedo medio derecho, secuela', 'Sin especificar', '["secuela dedo medio derecho"]'),
('S64.493A', 'Traumatismo de nervio digital de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["corte dedo corazón izquierdo", "lesión nervio dedo medio izquierdo"]'),
('S64.493D', 'Traumatismo de nervio digital de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento dedo medio izquierdo"]'),
('S64.493S', 'Traumatismo de nervio digital de dedo medio izquierdo, secuela', 'Sin especificar', '["secuela dedo medio izquierdo"]'),
('S64.494A', 'Traumatismo de nervio digital de dedo anular derecho, contacto inicial', 'Sin especificar', '["corte anular derecho", "lesión nervio anular derecho"]'),
('S64.494D', 'Traumatismo de nervio digital de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["seguimiento anular derecho"]'),
('S64.494S', 'Traumatismo de nervio digital de dedo anular derecho, secuela', 'Sin especificar', '["secuela anular derecho"]'),
('S64.495A', 'Traumatismo de nervio digital de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["corte anular izquierdo", "lesión nervio anular izquierdo"]'),
('S64.495D', 'Traumatismo de nervio digital de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento anular izquierdo"]'),
('S64.495S', 'Traumatismo de nervio digital de dedo anular izquierdo, secuela', 'Sin especificar', '["secuela anular izquierdo"]'),
('S64.496A', 'Traumatismo de nervio digital de dedo meñique derecho, contacto inicial', 'Sin especificar', '["corte meñique derecho", "golpe meñique derecho"]'),
('S64.496D', 'Traumatismo de nervio digital de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["seguimiento meñique derecho"]'),
('S64.496S', 'Traumatismo de nervio digital de dedo meñique derecho, secuela', 'Sin especificar', '["secuela meñique derecho"]'),
('S64.497A', 'Traumatismo de nervio digital de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["corte meñique izquierdo", "golpe meñique izquierdo"]'),
('S64.497D', 'Traumatismo de nervio digital de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento meñique izquierdo"]'),
('S64.497S', 'Traumatismo de nervio digital de dedo meñique izquierdo, secuela', 'Sin especificar', '["secuela meñique izquierdo"]'),
('S64.498A', 'Traumatismo de nervio digital de otro dedo de la mano, contacto inicial', 'Sin especificar', '["corte dedo", "lesión nervio dedo"]'),
('S64.498D', 'Traumatismo de nervio digital de otro dedo de la mano, contacto sucesivo', 'Sin especificar', '["seguimiento dedo"]'),
('S64.498S', 'Traumatismo de nervio digital de otro dedo de la mano, secuela', 'Sin especificar', '["secuela dedo"]'),
('S64.8X1A', 'Traumatismo de otros nervios a nivel de muñeca y mano, brazo derecho, contacto inicial', 'Sin especificar', '["lesión nervios mano derecha", "trauma mano derecha"]'),
('S64.8X1D', 'Traumatismo de otros nervios a nivel de muñeca y mano, brazo derecho, contacto sucesivo', 'Sin especificar', '["control mano derecha"]'),
('S64.8X1S', 'Traumatismo de otros nervios a nivel de muñeca y mano, brazo derecho, secuela', 'Sin especificar', '["secuela mano derecha"]'),
('S64.8X2A', 'Traumatismo de otros nervios a nivel de muñeca y mano, brazo izquierdo, contacto inicial', 'Sin especificar', '["lesión nervios mano izquierda", "trauma mano izquierda"]'),
('S64.8X2D', 'Traumatismo de otros nervios a nivel de muñeca y mano, brazo izquierdo, contacto sucesivo', 'Sin especificar', '["control mano izquierda"]'),
('S64.8X2S', 'Traumatismo de otros nervios a nivel de muñeca y mano, brazo izquierdo, secuela', 'Sin especificar', '["secuela mano izquierda"]'),
('S64.8X9A', 'Traumatismo de otros nervios a nivel de muñeca y mano, brazo no especificado, contacto inicial', 'Sin especificar', '["lesión nervios muñeca", "trauma mano"]'),
('S64.8X9D', 'Traumatismo de otros nervios a nivel de muñeca y mano, brazo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento nervios mano"]'),
('S64.8X9S', 'Traumatismo de otros nervios a nivel de muñeca y mano, brazo no especificado, secuela', 'Sin especificar', '["secuela nervios mano"]'),
('S64.90XA', 'Traumatismo de nervio no especificado a nivel de muñeca y mano, brazo no especificado, contacto inicial', 'Sin especificar', '["daño nervio mano", "problema nervio muñeca"]'),
('S64.90XD', 'Traumatismo de nervio no especificado a nivel de muñeca y mano, brazo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento daño nervio"]'),
('S64.90XS', 'Traumatismo de nervio no especificado a nivel de muñeca y mano, brazo no especificado, secuela', 'Sin especificar', '["secuela daño nervio"]'),
('S64.91XA', 'Traumatismo de nervio no especificado a nivel de muñeca y mano, brazo derecho, contacto inicial', 'Sin especificar', '["daño nervio mano derecha"]'),
('S64.91XD', 'Traumatismo de nervio no especificado a nivel de muñeca y mano, brazo derecho, contacto sucesivo', 'Sin especificar', '["control nervio mano derecha"]'),
('S64.91XS', 'Traumatismo de nervio no especificado a nivel de muñeca y mano, brazo derecho, secuela', 'Sin especificar', '["secuela nervio derecha"]'),
('S64.92XA', 'Traumatismo de nervio no especificado a nivel de muñeca y mano, brazo izquierdo, contacto inicial', 'Sin especificar', '["daño nervio mano izquierda"]'),
('S64.92XD', 'Traumatismo de nervio no especificado a nivel de muñeca y mano, brazo izquierdo, contacto sucesivo', 'Sin especificar', '["control nervio mano izquierda"]'),
('S64.92XS', 'Traumatismo de nervio no especificado a nivel de muñeca y mano, brazo izquierdo, secuela', 'Sin especificar', '["secuela nervio izquierda"]');
