INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q96.0', 'Cariotipo 45, X', 'Sin especificar', '["Síndrome de Turner", "monosomía X", "falta cromosoma X", "talla baja", "ausencia de menstruación", "amenorrea primaria", "infertilidad femenina", "problemas de desarrollo sexual", "cariotipo femenino anormal", "cuello alado", "pterigium colli", "baja estatura", "disgenesia gonadal", "anomalía genética"]'),
('Q96.1', 'Cariotipo 46, X iso (Xq)', 'Sin especificar', '["Síndrome de Turner variante", "isocromosoma X", "problemas de fertilidad", "pubertad retrasada", "anomalías cromosómicas", "cariotipo Xq", "estatura corta", "problemas de crecimiento", "desarrollo gonadal incompleto", "alteración genética", "mosaicismo cromosómico", "disgenesia ovárica", "fallo ovárico precoz"]'),
('Q96.2', 'Cariotipo 46, X con cromosoma sexual anormal, excepto iso (Xq)', 'Sin especificar', '["Síndrome de Turner", "cromosoma X deletado", "anomalía del cromosoma sexual", "cariotipo alterado", "retraso en el desarrollo", "infertilidad", "problemas hormonales", "talla pequeña", "dismorfia", "fallo ovárico", "problemas de crecimiento", "cariotipo raro", "mutación cromosómica", "desarrollo sexual incompleto"]'),
('Q96.3', 'Mosaicismo 45, X/46, XX o XY', 'Sin especificar', '["Turner en mosaico", "mosaicismo genético", "mezcla de células", "dos líneas celulares", "síndrome de Turner leve", "problemas de crecimiento desigual", "infertilidad variable", "variante de Turner", "cariotipo mixto", "anomalía en la sangre", "estudio genético", "diagnóstico de Turner", "fallo ovárico parcial", "desarrollo puberal incompleto"]'),
('Q96.4', 'Mosaicismo 45, X / otra (-s) línea (-s) celular (-es) con cromosoma sexual anormal', 'Sin especificar', '["Turner complejo", "mosaicismo cromosómico complejo", "anomalía genética múltiple", "cariotipo 45 X anormal", "problemas reproductivos", "baja estatura familiar", "dificultades en la pubertad", "alteración en el número de cromosomas", "anomalías de los cromosomas sexuales", "estudio citogenético", "variante genética rara", "problemas congénitos", "desarrollo sexual anormal"]'),
('Q96.8', 'Otras variantes del síndrome de Turner', 'Sin especificar', '["síndrome de Turner atípico", "variantes de Turner", "anomalías del cromosoma X", "baja estatura", "problemas hormonales femeninos", "infertilidad femenina", "pubertad tardía", "cuello ancho", "problemas cardíacos asociados", "problemas renales Turner", "cariotipo Turner", "alteración cromosómica", "diagnóstico genético", "hipogonadismo"]'),
('Q96.9', 'Síndrome de Turner no especificado', 'Sin especificar', '["síndrome de Turner", "enfermedad de Turner", "problema de cromosomas", "falta de crecimiento", "niña pequeña", "problemas de fertilidad", "fallo de ovarios", "pubertad no llega", "anomalía genética femenina", "retraso en desarrollo", "cariotipo anormal", "enfermedad genética", "talla baja", "cuello corto y ancho", "amenorrea"]');
