INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z75.0', 'Servicios médicos no disponibles en el domicilio', 'Sin especificar', '["atención médica en casa", "doctor a domicilio", "enfermero a casa", "visita médica fallida", "no hay médico en la zona", "falta de servicio de salud residencial", "atención domiciliaria no disponible", "médico no quiere venir", "sin servicio de salud en casa", "solicitar médico a domicilio", "no hay quien vaya a casa", "desabasto de atención médica local", "médico de cabecera no atiende en domicilio", "auxilio médico en casa no disponible"]'),
('Z75.1', 'Persona en espera de admisión en servicio de salud en otro lugar', 'Sin especificar', '["esperando cama", "lista de espera hospital", "esperando traslado", "en cola para internación", "esperando cupo médico", "pendiente de ingreso hospitalario", "esperando pase a otro hospital", "trámite de traslado", "aguardando admisión clínica", "en lista para ser admitido", "esperando lugar en otro centro", "traslado de paciente pendiente", "esperando cama de hospital", "trámite de internación en otra institución"]'),
('Z75.2', 'Otro tipo de período de espera para investigación y tratamiento', 'Sin especificar', '["lista de espera cirugía", "esperando turno con especialista", "esperando resultados de exámenes", "lista de espera consulta", "tiempo de espera médicos", "esperando cita de control", "turno médico lejano", "esperando estudio médico", "demora en atención de especialista", "esperando tratamiento", "cita programada para largo plazo", "tiempo de demora en salud", "esperando orden médica", "pendiente de examen diagnóstico"]'),
('Z75.3', 'Falta de disponibilidad e inaccesibilidad a centros de salud', 'Sin especificar', '["no hay hospitales cerca", "centro de salud lejos", "inaccesibilidad médica", "falta de doctores", "no tengo clínica cerca", "zonas rurales sin salud", "ausencia de servicios sanitarios", "problemas para llegar al hospital", "lejanía de centro médico", "falta de médicos en la zona", "sin acceso a servicios de salud", "hospitales saturados", "deficiencia de atención médica local", "barreras para llegar al centro de salud"]'),
('Z75.4', 'Falta de disponibilidad e inaccesibilidad a otros tipos de instituciones de ayuda', 'Sin especificar', '["sin apoyo social", "falta de centros de rehabilitación", "no hay donde recibir ayuda", "inaccesibilidad a servicios sociales", "sin instituciones de ayuda", "falta de centros de apoyo", "ayuda comunitaria no disponible", "donde buscar ayuda social", "sin acceso a centros de asistencia", "barreras para recibir ayuda externa", "ausencia de centros de soporte", "dónde acudir por ayuda", "falta de servicios de asistencia"]'),
('Z75.5', 'Vacaciones del proveedor de cuidados', 'Sin especificar', '["médico de vacaciones", "cuidador no disponible", "reemplazo de enfermero", "doctor fuera de servicio", "quién cubre al médico", "vacaciones de mi doctor", "ausencia temporal del cuidador", "sin atención por vacaciones", "baja por vacaciones del doctor", "atención médica interrumpida", "mi terapeuta está de vacaciones", "falta de cuidador titular", "cobertura médica en vacaciones"]'),
('Z75.8', 'Otros problemas relacionados con las instalaciones médicas y otros servicios de salud', 'Sin especificar', '["problemas en el hospital", "mal servicio médico", "inconvenientes con la clínica", "quejas de atención", "problemas administrativos médicos", "fallas en servicios de salud", "gestión hospitalaria deficiente", "mala atención en centro de salud", "trabas en servicios médicos", "complicaciones con citas", "problemas de infraestructura médica", "burocracia en salud", "insuficiencias en el servicio sanitario"]'),
('Z75.9', 'Problema relacionado con las instalaciones médicas y otros servicios de salud, no especificado', 'Sin especificar', '["problemas de salud no claros", "complicación con el centro médico", "situación médica difícil", "conflicto con servicios de salud", "incidente en hospital", "problema no definido en clínica", "inconveniente médico general", "algo anda mal con el servicio", "problema de atención médica", "trámite médico raro", "dificultades con instituciones de salud", "situación irregular en centro de salud"]');
