INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A08.0', 'Enteritis debida a rotavirus', 'Sin especificar', '["rotavirus", "diarrea infantil", "cagalera", "churretera", "virus estomacal", "diarrea por virus", "deshidratación", "vómitos y diarrea", "gastroenteritis viral", "cagadera", "diarrea explosiva", "indigestión viral", "infección estomacal", "dolor de guata", "mal de panza", "dolor de barriga"]'),
('A08.11', 'Gastroenteropatía aguda debida al agente de Norwalk', 'Sin especificar', '["norovirus", "virus de norwalk", "diarrea de crucero", "vómito repentino", "gastroenteritis aguda", "infección intestinal", "náuseas intensas", "diarrea viral", "virus de la panza", "dolor abdominal", "cagantina", "cagadera", "vómitos constantes", "gastro", "malestar estomacal"]'),
('A08.19', 'Gastroenteropatía aguda por otros virus pequeños redondos', 'Sin especificar', '["virus pequeños redondos", "diarrea viral aguda", "infección intestinal viral", "cagalera", "gastroenteritis", "dolor de tripa", "retortijones", "vómito", "malestar intestinal", "diarrea acuosa", "virus estomacal", "intestinos irritados", "ataque al hígado", "dolor de guata", "descomposición estomacal"]'),
('A08.2', 'Enteritis debida a adenovirus', 'Sin especificar', '["adenovirus intestinal", "infección viral", "diarrea por adenovirus", "dolor abdominal", "fiebre y diarrea", "gastroenteritis viral", "cagadera", "vómitos", "malestar intestinal", "dolor de panza", "inflamación intestinal", "virus estomacal", "indigestión", "intestinos revueltos", "enteritis"]'),
('A08.31', 'Enteritis por calicivirus', 'Sin especificar', '["calicivirus", "infección estomacal", "diarrea viral", "gastroenteritis", "virus de la panza", "náuseas", "vómito frecuente", "retortijones", "cagantina", "dolor de guata", "malestar de barriga", "descomposición", "diarrea líquida", "ataque al estómago", "virus intestinal"]'),
('A08.32', 'Enteritis por astrovirus', 'Sin especificar', '["astrovirus", "diarrea acuosa", "infección intestinal", "virus estomacal", "gastroenteritis", "vómitos", "malestar estomacal", "dolor de barriga", "cagalera", "descomposición", "diarrea del viajero", "retortijones", "dolor de guata", "enteritis", "inflamación de tripa"]'),
('A08.39', 'Otras enteritis virales', 'Sin especificar', '["infección viral intestinal", "gastroenteritis viral", "virus estomacal", "cagadera", "diarrea", "vómitos", "dolor abdominal", "malestar de panza", "dolor de tripa", "cagalera", "descomposición intestinal", "virus de la guata", "retortijones", "indigestión viral", "malestar estomacal"]'),
('A08.4', 'Infección intestinal viral, no especificada', 'Sin especificar', '["virus estomacal", "infección de la panza", "gastro", "diarrea", "cagadera", "vómito", "dolor de tripa", "malestar intestinal", "virus de barriga", "cagalera", "dolor de guata", "indigestión", "mal de panza", "descomposición", "virus no identificado", "infección de tripa"]'),
('A08.8', 'Otras infecciones intestinales especificadas', 'Sin especificar', '["infección intestinal", "gastroenteritis", "diarrea severa", "cagadera", "vómitos constantes", "malestar estomacal", "dolor abdominal fuerte", "retortijones", "cagalera", "dolor de guata", "descomposición", "infección de tripa", "mal de barriga", "problemas estomacales", "virus intestinal"]');
