INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z46.0', 'Contacto para colocación y ajuste de gafas y lentes de contacto', 'Sin especificar', '["gafas", "lentes", "anteojos", "lentes de contacto", "pupilentes", "lentes de aumento", "graduación de vista", "examen de la vista", "anteojos nuevos", "gafas graduadas", "ajuste de armazón", "lunas", "cristales", "lentes de contacto blandos", "lentes de contacto rígidos", "optometrista", "oftalmólogo", "ver mejor", "miopía", "astigmatismo"]'),
('Z46.1', 'Contacto para colocación y ajuste de audífonos', 'Sin especificar', '["audífonos", "aparato auditivo", "sordera", "problemas de audición", "no oigo bien", "ajuste de audífono", "molde para el oído", "pérdida auditiva", "oído", "hipoacusia", "batería para audífono", "otorrino", "auxiliar auditivo", "foniatría", "problemas para escuchar", "zumbido de oídos", "revisión de aparato auditivo"]'),
('Z46.2', 'Contacto para colocación y ajuste de otros dispositivos relacionados con el sistema nervioso y los sentidos especiales', 'Sin especificar', '["dispositivos neurológicos", "estimulador nervioso", "implante coclear", "ajuste de implante", "sistema nervioso", "neurología", "sensores cerebrales", "estimulador cerebral", "control de nervios", "neuroestimulador", "dispositivo de estimulación", "revisión de implantes", "ajuste de sentidos"]'),
('Z46.3', 'Contacto para colocación y ajuste de dispositivo protésico dental', 'Sin especificar', '["dentadura postiza", "placas", "dientes postizos", "prótesis dental", "puente dental", "coronas", "funda dental", "dentadura", "ajuste de prótesis", "fijador dental", "dolor de placa", "dentista", "odontología", "revisión de dentadura", "dientes falsos", "implantología"]'),
('Z46.4', 'Contacto para colocación y ajuste de dispositivo de ortodoncia', 'Sin especificar', '["brackets", "frenillos", "frenos", "alineadores", "ortodoncia", "apretar brackets", "ajuste de frenos", "alineación dental", "bandas de ortodoncia", "hules para frenos", "tensión de brackets", "dientes chuecos", "brackets flojos", "dolor de brackets", "cera dental", "dentista"]'),
('Z46.51', 'Contacto para colocación y ajuste de banda gástrica', 'Sin especificar', '["banda gástrica", "cirugía bariátrica", "ajuste de banda", "anillo gástrico", "bajar de peso", "cirugía de estómago", "obesidad", "ajuste de cinturón gástrico", "revisión de banda", "cirujano bariatra", "adelgazar", "reducción de estómago", "dolor de banda", "problemas con la banda", "dieta bariátrica"]'),
('Z46.59', 'Contacto para colocación y ajuste de otro aparato y dispositivo gastrointestinal', 'Sin especificar', '["sonda gástrica", "dispositivo estomacal", "sonda de alimentación", "gastrostomía", "problemas estomacales", "ajuste de sonda", "tubo de alimentación", "cuidado de estoma", "gastroenterología", "revisión de sonda", "molestias intestinales", "nutrición enteral", "tubo digestivo"]'),
('Z46.6', 'Contacto para colocación y ajuste de dispositivo urinario', 'Sin especificar', '["catéter urinario", "sonda vesical", "sonda foley", "problemas de orina", "incontinencia", "dispositivo urinario", "ajuste de sonda", "bolsa de orina", "uretra", "urología", "dolor al orinar", "cuidado de sonda", "cambio de catéter", "vejiga", "infección urinaria"]'),
('Z46.81', 'Contacto para colocación y ajuste de bomba de insulina', 'Sin especificar', '["bomba de insulina", "diabetes", "ajuste de bomba", "insulina", "medidor de glucosa", "control de azúcar", "diabético", "monitoreo de glucosa", "infusión de insulina", "problemas con la bomba", "configuración de bomba", "cánula de insulina", "endocrinología", "niveles de azúcar", "glucómetro"]'),
('Z46.82', 'Contacto para colocación y ajuste de catéter no vascular', 'Sin especificar', '["catéter", "sonda", "ajuste de catéter", "catéter abdominal", "drenaje", "dispositivo médico", "cuidado de catéter", "revisión de catéter", "limpieza de catéter", "problemas con el catéter", "tubo de drenaje", "procedimiento médico", "salud pública"]'),
('Z46.89', 'Contacto para colocación y ajuste de otros dispositivos especificados', 'Sin especificar', '["dispositivo médico", "ajuste de equipo", "revisión de aparato", "ayuda técnica", "mantenimiento de dispositivo", "equipo de soporte", "asistencia médica", "ajuste de férula", "soporte externo", "dispositivo ortopédico", "cuidado técnico", "reparación de dispositivo"]'),
('Z46.9', 'Contacto para colocación y ajuste de dispositivo no especificado', 'Sin especificar', '["dispositivo médico general", "ajuste de equipo", "ayuda médica", "revisión de aparato", "soporte médico", "consultorio", "atención médica", "chequeo de dispositivo", "problemas con el equipo", "ayudas técnicas", "soporte de salud", "colocación de aparato", "mantenimiento médico"]');
