INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N43.0', 'Hidrocele enquistado', 'Sin especificar', '["hidrocele", "bolas en los huevos", "hinchazón de testículo", "líquido en el escroto", "testículo inflamado", "quiste escrotal", "hidrocele encapsulado", "bolsa de agua en el escroto", "inflamación escrotal", "testículo grande", "bulto en el escroto", "hidrocele cerrado", "hidrocele enquistado", "testículos hinchados", "edema escrotal", "acumulación de líquido testicular"]'),
('N43.1', 'Hidrocele infectado', 'Sin especificar', '["hidrocele infectado", "piocele", "infección en el escroto", "testículo con pus", "escroto rojo y caliente", "dolor de huevos", "inflamación dolorosa escroto", "hidrocele inflamado", "infección testicular", "bolas calientes", "escroto infectado", "absceso escrotal", "hidrocele con fiebre", "dolor testicular agudo", "testículo supurante"]'),
('N43.2', 'Otros tipos de hidrocele', 'Sin especificar', '["hidrocele", "acumulación de líquido testicular", "hidrocele comunicante", "hidrocele no comunicante", "testículo con líquido", "hinchazón escrotal", "escroto abultado", "bolas pesadas", "hidrocele crónico", "bolsa de líquido en los testículos", "hidrocele idiopático", "hidrocele secundario", "edema testicular"]'),
('N43.3', 'Hidrocele, no especificado', 'Sin especificar', '["hidrocele", "testículo hinchado", "escroto inflamado", "bolas con agua", "bulto en el escroto", "líquido en las bolas", "hinchazón de escroto", "testículo grande", "problema en el escroto", "acumulación de líquido", "escroto con masa", "hidrocele sin especificar", "hinchazón en la bolsa escrotal"]'),
('N43.40', 'Espermatocele de epidídimo, no especificado', 'Sin especificar', '["espermatocele", "quiste en el epidídimo", "quiste en el testículo", "bolita en el testículo", "bulto sobre el testículo", "quiste espermático", "bulto en el epidídimo", "quiste benigno en el testículo", "espermatocele epididimario", "masa en el epidídimo", "bolita indolora en los huevos", "quiste de cordón espermático"]'),
('N43.41', 'Espermatocele de epidídimo, único', 'Sin especificar', '["espermatocele único", "quiste solitario en el epidídimo", "una bolita en el testículo", "quiste espermático único", "bolita en el epidídimo", "masa única en el escroto", "bulto único en el testículo", "quiste testicular simple", "quiste epididimario único", "quiste de esperma único", "pequeña bolita en el epidídimo"]'),
('N43.42', 'Espermatocele de epidídimo, múltiple', 'Sin especificar', '["espermatoceles múltiples", "quistes en el epidídimo", "varias bolitas en el testículo", "bolitas en el escroto", "quistes espermáticos múltiples", "múltiples bultos en el epidídimo", "espermatocele poliquístico", "bolitas sobre el testículo", "nódulos en el epidídimo", "quistes epididimarios múltiples", "muchas bolitas en los testículos"]');
