INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z76.0', 'Contacto para prescripción repetida', 'Sin especificar', '["renovar receta", "pedir medicamentos", "repetición de medicamentos", "necesito mis pastillas", "receta permanente", "solicitar fármacos recurrentes", "control de medicación", "pedir orden médica", "reclamar medicamentos", "continuidad de tratamiento", "recetario habitual", "renovación de fármacos", "tramitar medicinas", "consulta solo por receta"]'),
('Z76.1', 'Contacto para supervisión y cuidado de salud de niño expósito', 'Sin especificar', '["niño abandonado", "bebé huérfano", "cuidado de menor en adopción", "niño sin tutela", "menor bajo custodia", "supervisión de niño acogido", "salud de infante expósito", "atención médica niño sin padres", "menor en sistema de protección", "cuidado de niño institucionalizado", "chequeo niño tutelado", "bienestar de niño abandonado", "expósito", "niño del DIF"]'),
('Z76.2', 'Contacto para supervisión y cuidado de salud de otro tipo de lactante y niño sano', 'Sin especificar', '["control niño sano", "chequeo de rutina bebé", "revisión pediátrica", "control de crecimiento", "consulta de niño sano", "pesaje de bebé", "seguimiento de lactante", "visita de rutina pediatra", "control de peso y talla", "ver si el niño está bien", "chequeo infantil de rutina", "revisión de rutina para niños", "control de niño pequeño", "consulta preventiva pediátrica"]'),
('Z76.3', 'Persona sana que acompaña a persona enferma', 'Sin especificar', '["acompañante", "cuidador", "quien cuida al enfermo", "persona que acompaña al paciente", "cuidador familiar", "asistente del enfermo", "quien se queda en el hospital", "apoyo al paciente", "familiar del paciente", "acompañante sano", "persona de apoyo", "vigilante del paciente", "cuidador de guardia", "acompañante en internación"]'),
('Z76.4', 'Otros usuarios de servicios sanitarios', 'Sin especificar', '["otros servicios médicos", "trámites sanitarios", "atención médica no especificada", "gestiones en salud", "otros pacientes", "uso de instalaciones sanitarias", "solicitud de servicios de salud", "consultas administrativas médicas", "trámite de salud", "gestión administrativa hospitalaria", "usuarios extra", "servicios auxiliares de salud", "persona en centro de salud"]'),
('Z76.5', 'Persona que finge enfermedad [simulación consciente]', 'Sin especificar', '["simulador", "mentir sobre enfermedad", "fingir síntomas", "mentiroso médico", "falso paciente", "simulación de dolencias", "cuento del tío médico", "se hace el enfermo", "querer sacar licencia falsa", "fingir malestar", "fraude sanitario", "exagerar síntomas", "paciente simulado", "hacerse el sordo", "fingidor"]'),
('Z76.81', 'Visita pediátrica preparto de futuro(s) padre(s)', 'Sin especificar', '["entrevista con pediatra", "primera visita pediatra", "cita antes del parto", "conocer al pediatra", "consulta prenatal pediatría", "preparación para el bebé", "consejos preparto pediatría", "cita informativa pediatra", "reunión con pediatra antes de nacer", "evaluación pre-nacimiento", "planificación de salud del recién nacido", "pre-cita con pediatra", "consulta informativa padres primerizos"]'),
('Z76.82', 'Estado de espera de trasplante de órgano', 'Sin especificar', '["lista de espera trasplante", "esperando un órgano", "paciente en espera de donante", "lista de trasplante", "esperando riñón", "esperando hígado", "esperando corazón", "paciente apto para trasplante", "en espera de trasplante", "búsqueda de donante", "esperando trasplante de órganos", "candidato a trasplante", "proceso de trasplante", "lista del INCUCAI", "donante de órganos"]'),
('Z76.89', 'Personas que entran en contacto con los servicios de salud en otras circunstancias especificadas', 'Sin especificar', '["otras consultas médicas", "contacto con servicios de salud", "atención sanitaria especial", "circunstancias médicas diversas", "consultas atípicas", "situaciones de salud", "contacto médico", "paciente en circunstancia especial", "atención de salud no catalogada", "eventos de salud", "visitas al centro de salud", "gestiones sanitarias", "consultas particulares"]');
