INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('M72.0', 'Fibromatosis de fascia palmar [de Dupuytren]', 'Sin especificar', '["contractura de Dupuytren", "mano en garra", "dedos encogidos", "bolitas en la palma", "nudos en la mano", "mano contraída", "dedos tiesos", "endurecimiento de palma", "dedo trabado", "fibrosis palmar", "mano rígida", "nódulo en la palma", "dedo doblado", "mano de alcahuete", "retracción palmar"]'),
('M72.1', 'Nódulos interfalángicos', 'Sin especificar', '["bolitas en los dedos", "nudos en las articulaciones", "bultos en los nudillos", "nódulos de Heberden", "nódulos de Bouchard", "dedos hinchados", "deformidad en dedos", "callos en las articulaciones", "artrosis de dedos", "bolitas duras en falanges", "huesos crecidos en dedos", "inflamación de nudillos", "dedos deformes", "dolor articular falange", "protuberancias en dedos"]'),
('M72.2', 'Fibromatosis de fascia plantar', 'Sin especificar', '["enfermedad de Ledderhose", "nudos en la planta del pie", "bolitas en el pie", "fasciosis plantar", "dolor al caminar", "bultos en la planta", "fibrosis plantar", "dolor en el arco del pie", "nódulos en el pie", "endurecimiento de la planta", "espolón", "planta del pie dura", "fascitis", "bultos bajo el pie", "molestia al pisar"]'),
('M72.4', 'Fibromatosis seudosarcomatosa', 'Sin especificar', '["fascitis nodular", "bulto de crecimiento rápido", "nódulo subcutáneo", "tumor benigno en piel", "bulto en el brazo", "nódulo de tejido blando", "masa subcutánea", "fibromatosis proliferativa", "pseudotumor", "bolita inflamada", "masa móvil bajo la piel", "nódulo doloroso", "crecimiento de tejido", "masa muscular", "tumor seudosarcomatoso"]'),
('M72.6', 'Fascitis necrotizante', 'Sin especificar', '["bacteria come carne", "infección necrosante", "gangrena gaseosa", "infección mortal de piel", "muerte de tejido", "piel negra", "infección rápida", "sepsis por herida", "celulitis necrotizante", "infección en la carne", "necrosis de tejidos", "herida que se pudre", "infección de la fascia", "emergencia por infección", "piel morada y podrida"]'),
('M72.8', 'Otros trastornos fibroblásticos', 'Sin especificar', '["enfermedades de tejido conectivo", "fibrosis", "trastorno de fascia", "endurecimiento de tejidos", "problemas de tejido blando", "engrosamiento de la piel", "retracción tisular", "fibromatosis", "lesión de fascia", "daño en tejido conectivo", "inflamación crónica de tejido", "cambios en el tejido subcutáneo", "contracturas", "nódulos subcutáneos", "fibroplasia"]'),
('M72.9', 'Trastorno fibroblástico no especificado', 'Sin especificar', '["problema en la fascia", "nódulo sin diagnosticar", "bolita en la piel", "dolor de tejido blando", "endurecimiento desconocido", "trastorno de la piel y fascia", "nódulo extraño", "bulto no identificado", "fibrosis no especificada", "molestia en músculos", "induración de tejido", "masa bajo la piel", "inflamación persistente", "anomalía de fascia", "problema fibroso"]');
