INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('E28.0', 'Exceso de estrógenos', 'Sin especificar', '["exceso de hormonas femeninas", "hiperestrogenismo", "desajuste hormonal", "subidón de estrógenos", "exceso de estrógeno", "cuerpo inflamado", "retención de líquidos", "dolor en los pechos", "ciclos irregulares", "regla abundante", "cambios de humor", "hormonas locas", "desbalance hormonal", "estrógeno alto", "sangrado excesivo", "sensibilidad mamaria", "periodos largos"]'),
('E28.1', 'Exceso de andrógenos', 'Sin especificar', '["exceso de hormonas masculinas", "hiperandrogenismo", "vello facial en mujeres", "hirsutismo", "acné severo", "andrógenos altos", "voz ronca", "caída de cabello", "alopecia femenina", "barba en mujeres", "grasa en la cara", "desorden hormonal", "aumento de vello", "ciclos sin regla", "exceso de testosterona", "ovarios con problemas"]'),
('E28.2', 'Síndrome de ovario poliquístico', 'Sin especificar', '["sop", "ovarios con quistes", "quistes en los ovarios", "ovarios poliquísticos", "infertilidad por ovarios", "problemas para quedar embarazada", "regla que no baja", "periodos irregulares", "engordar sin razón", "manchas en el cuello", "resistencia a la insulina", "acné hormonal", "pelitos en la cara", "dolor pélvico", "ovarios perezosos", "ciclos largos", "falta de ovulación"]'),
('E28.310', 'Menopausia prematura sintomática', 'Sin especificar', '["menopausia precoz", "climaterio temprano", "sofocos", "calores repentinos", "bochornos", "falta de regla joven", "sudores nocturnos", "cambios de humor repentinos", "sequedad vaginal", "falta de deseo sexual", "insomnio por calor", "se me fue la regla antes de tiempo", "menopausia joven", "ovarios que dejaron de funcionar", "irritabilidad", "desajuste ovárico temprano"]'),
('E28.319', 'Menopausia prematura asintomática', 'Sin especificar', '["menopausia precoz silenciosa", "falla ovárica prematura", "cese de regla joven", "infertilidad prematura", "ausencia de menstruación", "menopausia sin sofocos", "ovarios agotados", "agotamiento ovárico temprano", "no me baja la regla", "falla ovárica oculta", "insuficiencia ovárica precoz", "sin síntomas de menopausia", "menopausia sin bochornos", "diagnóstico de falla ovárica", "desaparición de periodos"]'),
('E28.39', 'Otros tipos de insuficiencia ovárica primaria', 'Sin especificar', '["falla de ovarios", "ovarios que no trabajan", "insuficiencia ovárica", "falla ovárica", "ovarios atrofiados", "menopausia temprana por causa desconocida", "ovarios perezosos", "incapacidad ovárica", "falla prematura de los ovarios", "problemas de funcionamiento ovárico", "ovarios detenidos", "disfunción de ovarios", "problemas con la ovulación", "ovarios que no ovulan", "ovarios dañados"]'),
('E28.8', 'Otros tipos de disfunción ovárica', 'Sin especificar', '["problemas de ovarios", "desajuste ovárico", "ovarios que fallan", "mal funcionamiento de ovarios", "problemas hormonales ováricos", "ovarios irregulares", "desequilibrio de ovarios", "ciclos raros", "alteración ovárica", "problemas con mis ovarios", "dolor ovárico", "cuestiones de ovarios", "dificultad para ovular", "anomalía ovárica", "desorden en la ovulación"]'),
('E28.9', 'Disfunción ovárica, no especificada', 'Sin especificar', '["problema en los ovarios", "no sé qué tienen mis ovarios", "ovarios no funcionan bien", "dolor en los ovarios", "desajuste en los ovarios", "ovarios mal", "problemas ginecológicos", "fallo ovárico", "algo pasa con mis ovarios", "dolor en la guata abajo", "dolor en el bajo vientre", "problemas con la regla", "ovarios inflamados", "duda sobre mis ovarios", "consulta ginecológica ovarios"]');
