INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P10.0', 'Hemorragia subdural debida a traumatismo del nacimiento', 'Sin especificar', '["sangrado en el cerebro recién nacido", "hematoma subdural parto", "golpe en la cabeza al nacer", "trauma obstétrico", "derrame cerebral bebé", "sangre en la cabeza bebé", "lesión craneal nacimiento", "complicaciones del parto", "fórceps lesiones", "sangrado meníngeo neonatal", "hematoma subdural infantil", "traumatismo al nacer", "daño cerebral neonatal", "hemorragia después del parto", "urgencia neonatal"]'),
('P10.1', 'Hemorragia cerebral debida a traumatismo del nacimiento', 'Sin especificar', '["sangrado cerebral neonatal", "derrame cerebral en bebé", "hemorragia intracerebral parto", "trauma al nacer", "lesión cerebral del recién nacido", "sangre en el cerebro del bebé", "complicación obstétrica", "parto traumático", "daño en el cerebro del neonato", "hemorragia interna bebé", "problemas neurológicos al nacer", "hematoma cerebral recién nacido", "urgencia recién nacido", "falla al nacer", "traumatismo cefálico neonatal"]'),
('P10.2', 'Hemorragia intraventricular debida a traumatismo del nacimiento', 'Sin especificar', '["sangrado en ventrículos bebé", "hemorragia intraventricular neonatal", "sangrado cerebral profundo", "trauma obstétrico", "complicaciones parto prematuro", "derrame en la cabeza bebé", "lesión de los ventrículos cerebrales", "sangrado al nacer", "daño cerebral por parto", "hemorragia en el cerebro del neonato", "problemas de presión intracraneal", "hematoma ventricular", "emergencia al nacer", "traumatismo neonatal", "sangre en los ventrículos recién nacido"]'),
('P10.3', 'Hemorragia subaracnoidea debida a traumatismo del nacimiento', 'Sin especificar', '["sangrado subaracnoideo neonatal", "sangre entre membranas cerebro bebé", "derrame en el cerebro al nacer", "trauma obstétrico cabeza", "lesión cerebral parto", "hemorragia meníngea recién nacido", "sangrado craneal bebé", "complicación parto", "traumatismo durante el nacimiento", "daño cerebral leve a grave neonato", "hemorragia de las meninges", "sangrado por fórceps", "hematoma subaracnoideo", "urgencia neurológica bebé", "problemas al nacer"]'),
('P10.4', 'Desgarro tentorial debido a traumatismo del nacimiento', 'Sin especificar', '["desgarro del tentorio parto", "lesión de la tienda del cerebelo", "desgarro cerebral recién nacido", "trauma obstétrico cabeza", "parto difícil", "daño cerebral por trauma", "lesión de membranas cerebrales", "herida en la cabeza del bebé", "fórceps desgarro", "desgarro craneal neonatal", "complicación grave del parto", "traumatismo de la cabeza al nacer", "emergencia obstétrica", "daño estructural cerebro recién nacido", "desgarro de estructuras intracraneales"]'),
('P10.8', 'Otras laceraciones y hemorragias intracraneales debidas a traumatismo del nacimiento', 'Sin especificar', '["laceración cerebral neonatal", "sangrado interno cabeza bebé", "herida en el cerebro recién nacido", "lesión cerebral traumática parto", "traumatismo intracraneal al nacer", "daño cerebral por parto", "sangrado por complicaciones del nacimiento", "hematoma cerebral neonato", "emergencia médica recién nacido", "trauma en la cabeza del bebé", "problemas neurológicos parto", "lesión del cerebro recién nacido", "complicaciones graves al nacer", "hemorragia no especificada parto", "daño intracraneal neonatal"]'),
('P10.9', 'Laceración y hemorragia intracraneal no especificadas debidas a traumatismo del nacimiento', 'Sin especificar', '["lesión craneal desconocida al nacer", "sangrado en la cabeza bebé", "trauma obstétrico sin especificar", "daño cerebral al nacer", "hemorragia en el recién nacido", "complicaciones neurológicas parto", "traumatismo al nacer bebé", "sangre en el cerebro neonato", "problemas de cabeza tras parto", "urgencia neonatal no definida", "lesión cerebral del neonato", "daño por nacimiento", "emergencia al nacer bebé", "trauma intracraneal recién nacido", "herida craneal parto"]');
