INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('E61.0', 'Carencia de cobre', 'Sin especificar', '["falta de cobre", "deficiencia de cobre", "hipocupremia", "anemia por cobre", "debilidad por falta de minerales", "cansancio extremo", "pérdida de pigmentación en el pelo", "pelo débil", "desnutrición mineral", "niveles bajos de cobre", "fatiga crónica", "alteraciones en la sangre", "fragilidad ósea"]'),
('E61.1', 'Carencia de hierro', 'Sin especificar', '["anemia", "falta de hierro", "anemia ferropénica", "estar anémico", "deficiencia de hierro", "cansancio", "fatiga", "palidez", "se me cae el pelo", "uñas quebradizas", "mareos", "debilidad general", "sentirse mareado", "falta de aliento", "anemia por carencia de hierro", "hierro bajo"]'),
('E61.2', 'Carencia de magnesio', 'Sin especificar', '["falta de magnesio", "deficiencia de magnesio", "calambres", "tirones", "espasmos musculares", "temblor de párpado", "me tiembla el ojo", "insomnio", "ansiedad", "fatiga muscular", "dolor de piernas", "rigidez", "falta de energía", "nerviosismo", "astenia", "hipomagnesemia"]'),
('E61.3', 'Carencia de manganeso', 'Sin especificar', '["falta de manganeso", "deficiencia de manganeso", "debilidad ósea", "problemas en las articulaciones", "dolor articular", "mala coagulación", "problemas de crecimiento", "metabolismo lento", "cansancio físico", "problemas de ligamentos", "deficiencia de oligoelementos", "anomalías esqueléticas"]'),
('E61.4', 'Carencia de cromo', 'Sin especificar', '["falta de cromo", "deficiencia de cromo", "ansiedad por el dulce", "azúcar alta", "niveles de glucosa inestables", "problemas con la insulina", "ganas de comer azúcar", "metabolismo de carbohidratos", "fatiga constante", "aumento de peso por antojos", "resistencia a la insulina"]'),
('E61.5', 'Carencia de molibdeno', 'Sin especificar', '["falta de molibdeno", "deficiencia de molibdeno", "toxicidad por sulfitos", "sensibilidad a químicos", "problemas metabólicos", "taquicardia", "dolor de cabeza", "alteraciones visuales", "problemas digestivos raros", "debilidad metabólica"]'),
('E61.6', 'Carencia de vanadio', 'Sin especificar', '["falta de vanadio", "deficiencia de vanadio", "problemas de crecimiento", "alteraciones del metabolismo lipídico", "colesterol alto", "problemas de azúcar", "desequilibrio de oligoelementos", "cansancio inexplicable"]'),
('E61.7', 'Carencia de múltiples elementos nutricionales', 'Sin especificar', '["desnutrición", "falta de vitaminas y minerales", "mala alimentación", "déficit nutricional múltiple", "cuerpo descompensado", "debilidad generalizada", "estoy débil", "se me cae el pelo y me duelen los huesos", "fatiga crónica", "mala nutrición", "carencia de oligoelementos", "cuerpo sin defensas"]'),
('E61.8', 'Carencia de otros elementos nutricionales especificados', 'Sin especificar', '["déficit mineral", "falta de minerales", "desequilibrio nutricional", "carencia específica", "mala absorción de nutrientes", "anemia nutricional", "debilidad por falta de nutrientes", "falta de oligoelementos", "carencia dietética"]'),
('E61.9', 'Carencia de nutrientes elementales, no especificada', 'Sin especificar', '["estoy débil", "me faltan vitaminas", "cansancio injustificado", "desgano", "no tengo energía", "deficiencia alimentaria", "malestar general", "desnutrición", "falta de minerales básicos", "siempre estoy cansado", "decaimiento", "debilidad física"]');
