INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('I51.0', 'Defecto del tabique cardiaco, adquirido', 'Sin especificar', '["agujero en el corazón", "comunicación interauricular", "comunicación interventricular", "soplos cardiacos", "defecto septal", "corazón agujereado", "tabique roto", "fuga en el corazón", "valvula dañada", "palpitaciones", "cansancio extremo", "cianosis", "fatiga al hacer esfuerzo", "soplo en el pecho", "problema cardiaco adquirido"]'),
('I51.1', 'Rotura de cuerdas tendinosas, no clasificada bajo otro concepto', 'Sin especificar', '["cuerdas del corazón rotas", "insuficiencia mitral aguda", "dolor en el pecho", "falta de aire", "disnea", "latidos irregulares", "desgarro valvular", "soplo repentino", "arritmia", "pecho apretado", "fallo en la válvula", "pulso acelerado", "dolor torácico agudo", "ahogo", "cuerdas tendinosas dañadas"]'),
('I51.2', 'Rotura de músculo papilar, no clasificada bajo otro concepto', 'Sin especificar', '["músculo cardiaco roto", "infarto de miocardio complicado", "dolor precordial intenso", "colapso cardiaco", "insuficiencia mitral severa", "edema pulmonar", "dolor opresivo", "fallo del músculo del corazón", "desgarro muscular cardiaco", "shock cardiogénico", "taquicardia", "dolor de pecho fuerte", "falta de aliento grave", "desmayos", "emergencia cardiaca"]'),
('I51.3', 'Trombosis intracardiaca, no clasificada bajo otro concepto', 'Sin especificar', '["coágulo en el corazón", "trombo cardiaco", "sangre espesa en el corazón", "bloqueo sanguíneo cardiaco", "embolia", "riesgo de infarto", "trombo en la aurícula", "trombo en el ventrículo", "sangre coagulada", "riesgo de derrame", "palpitaciones raras", "dolor persistente", "trombosis", "obstrucción cardiaca", "coágulo de sangre"]'),
('I51.4', 'Miocarditis, no especificada', 'Sin especificar', '["inflamación del corazón", "corazón inflamado", "infección en el músculo cardiaco", "miocardio hinchado", "dolor al respirar", "fiebre y dolor de pecho", "fatiga crónica", "palpitaciones", "dolor torácico", "latidos raros", "debilidad cardiaca", "pinchazos en el pecho", "infección cardiaca", "miocarditis viral", "dolor agudo"]'),
('I51.5', 'Degeneración miocárdica', 'Sin especificar', '["corazón débil", "músculo cardiaco desgastado", "corazón grande", "fallo cardiaco progresivo", "miocardio viejo", "debilidad del corazón", "cansancio constante", "insuficiencia cardiaca", "corazón cansado", "desgaste muscular cardiaco", "hinchazón de piernas", "falta de aire", "retención de líquidos", "arritmias", "corazón que no bombea bien"]'),
('I51.7', 'Cardiomegalia', 'Sin especificar', '["corazón grande", "corazón agrandado", "corazón crecido", "hipertrofia cardiaca", "corazón dilatado", "corazón hinchado", "corazón gordo", "cansancio al caminar", "falta de aire", "edema en piernas", "fatiga", "insuficiencia cardiaca", "corazón aumentado de tamaño", "latidos fuertes", "presión en el pecho"]'),
('I51.81', 'Síndrome takotsubo', 'Sin especificar', '["síndrome del corazón roto", "corazón roto por estrés", "infarto emocional", "miocardiopatía por estrés", "dolor de pecho por angustia", "shock emocional cardiaco", "estrés cardiaco", "debilidad del ventrículo", "angustia en el pecho", "opresión por pena", "arritmia por estrés", "falsa alarma de infarto", "takotsubo", "corazón aturdido", "dolor torácico por impacto emocional"]'),
('I51.89', 'Otras enfermedades mal definidas cardiacas', 'Sin especificar', '["problema raro del corazón", "dolor de pecho inexplicable", "molestia cardiaca", "corazón extraño", "falla cardiaca incierta", "taquicardia inexplicable", "pinchazos en el corazón", "palpitaciones raras", "soplo no diagnosticado", "enfermedad del corazón mal definida", "dolor en el pecho sin causa", "chequeo cardiaco necesario", "desmayos cardiacos", "latidos raros", "problema del corazón"]'),
('I51.9', 'Enfermedad cardiaca, no especificada', 'Sin especificar', '["problema del corazón", "mal del corazón", "enfermedad cardiaca", "fallo en el corazón", "corazón enfermo", "dolor torácico", "chequeo del corazón", "insuficiencia", "corazón débil", "molestias en el pecho", "arritmias", "cardiopatía", "ataque al corazón", "dolor en el pecho", "problema cardiaco"]');
