INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K11.0', 'Atrofia de glándula salival', 'Sin especificar', '["boca seca", "xerostomía", "falta de saliva", "glándula pequeña", "atrofia salival", "salivación escasa", "se queda la boca seca", "boca pastosa", "glándulas que no funcionan", "reducción de saliva", "síndrome de boca seca", "deshidratación oral", "escasez de saliva", "atrofia glandular"]'),
('K11.1', 'Hipertrofia de glándula salival', 'Sin especificar', '["glándula inflamada", "hinchazón de cara", "bulto en la mejilla", "glándula grande", "hipertrofia glandular", "papera", "tumor salival benigno", "glándula agrandada", "bola en el cuello", "inflamación de parótida", "sialoadenosis", "hinchazón bajo la mandíbula", "aumento de volumen glandular", "flemón en la cara"]'),
('K11.20', 'Sialoadenitis, no especificada', 'Sin especificar', '["infección de glándula salival", "inflamación de la boca", "dolor en la mandíbula", "infección bucal", "glándula adolorida", "sialoadenitis", "dolor al comer", "hinchazón salival", "molestia en parótida", "infección glandular", "glándula irritada", "flemón", "dolor en el cuello", "glándula infectada"]'),
('K11.21', 'Sialoadenitis aguda', 'Sin especificar', '["infección repentina de glándula", "hinchazón súbita", "dolor agudo en la mejilla", "flemón repentino", "fiebre por glándula salival", "sialoadenitis aguda", "inflamación rápida", "dolor fuerte al salivar", "infección fuerte de boca", "dolor bajo el oído", "glándula roja y caliente", "infección purulenta", "pinchazos en la mandíbula"]'),
('K11.22', 'Sialoadenitis aguda recidivante', 'Sin especificar', '["infección de glándula que vuelve", "sialoadenitis recurrente", "inflamación constante de glándula", "flemones frecuentes", "dolor salival intermitente", "problema crónico de glándula", "se me hincha la cara seguido", "infección persistente de saliva", "brotes de sialoadenitis", "inflamación recidivante", "otra vez con la cara hinchada", "problema recurrente de parótida"]'),
('K11.23', 'Sialoadenitis crónica', 'Sin especificar', '["infección de glándula de larga duración", "dolor sordo en mandíbula", "sialoadenitis crónica", "inflamación de años", "molestia persistente en la cara", "glándula permanentemente inflamada", "problema continuo de saliva", "dolor leve y constante", "engrosamiento de glándula", "fibrosis glandular", "infección persistente", "secreción espesa"]'),
('K11.3', 'Absceso de glándula salival', 'Sin especificar', '["pus en la glándula", "flemón con pus", "absceso bucal", "grano en la glándula", "infección con pus", "acumulación de pus en mandíbula", "hinchazón caliente y roja", "dolor pulsátil en cara", "glándula con infección severa", "drenaje de pus salival", "absceso parotídeo", "infección profunda en boca"]'),
('K11.4', 'Fístula de glándula salival', 'Sin especificar', '["agujero en la piel que sale saliva", "saliva por fuera de la boca", "drenaje de saliva", "fístula salival", "conducto salival abierto", "salida de líquido por la mejilla", "herida en la cara que segrega", "fuga de saliva", "trayecto fistuloso", "herida que no cierra en la cara", "saliva en la piel"]'),
('K11.5', 'Sialolitiasis', 'Sin especificar', '["piedra en la glándula", "cálculo salival", "piedra en la boca", "cálculos en la saliva", "dolor al comer por piedra", "obstrucción salival", "arenilla en la boca", "piedra en el conducto", "dolor debajo de la lengua", "bolita dura en la boca", "litiasis salival", "taponamiento de glándula"]'),
('K11.6', 'Mucocele de glándula salival', 'Sin especificar', '["burbuja en el labio", "quiste de moco", "bolita en la boca", "mucocele", "quiste en la lengua", "burbuja transparente en la mejilla", "bola de agua en la boca", "bolita en el labio inferior", "quiste salival", "glándula bloqueada", "burbuja que se rompe y sale", "acumulación de moco oral"]'),
('K11.7', 'Alteraciones de la secreción salival', 'Sin especificar', '["mucha saliva", "babeo excesivo", "falta de saliva", "boca seca", "hipersalivación", "sialorrea", "xerostomía", "problemas con la saliva", "se me llena la boca de agua", "salivación anormal", "exceso de baba", "poca saliva al comer", "trastornos salivales"]'),
('K11.8', 'Otras enfermedades de las glándulas salivales', 'Sin especificar', '["enfermedades de parótida", "problemas en glándulas bucales", "trastorno glandular", "patología salival", "daño en glándulas", "síndrome de Sjögren", "problemas con las glándulas de la cara", "dolor en la mandíbula inferior", "molestias cerca del oído", "enfermedad de glándula salival no común"]'),
('K11.9', 'Enfermedad de glándula salival, no especificada', 'Sin especificar', '["problema en la glándula", "dolor de glándula", "hinchazón en la cara", "dolor debajo de la oreja", "molestia salival", "glándula enferma", "problema en el cuello", "inflamación desconocida", "dolor al masticar", "infección en boca sin nombre", "dolor raro en la cara", "problema con la saliva"]');
