INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C46.0', 'Sarcoma de Kaposi de piel', 'Sin especificar', '["manchas moradas en la piel", "cáncer de piel VIH", "lesiones violáceas", "nódulos en la piel", "sarcoma cutáneo", "manchas rojas en el cuerpo", "lunares raros", "tumores en la piel", "manchas de kaposi", "bultos en la piel", "sarcoma de piel", "manchas cancerosas", "cáncer asociado a sida", "lesiones vasculares piel", "manchas que no se quitan"]'),
('C46.1', 'Sarcoma de Kaposi de tejidos blandos', 'Sin especificar', '["tumor en tejidos blandos", "bultos debajo de la piel", "sarcoma de tejidos", "masas musculares", "bolas en el cuerpo", "cáncer de tejido blando", "sarcoma kaposi profundo", "nódulos subcutáneos", "tumores de partes blandas", "crecimiento bajo la piel", "sarcoma tejidos", "lesiones profundas", "bultos sospechosos", "nódulos en la carne", "induraciones"]'),
('C46.2', 'Sarcoma de Kaposi de paladar', 'Sin especificar', '["manchas en el paladar", "cáncer de boca", "lesión en el cielo de la boca", "mancha morada en la boca", "nódulo en el paladar", "tumor bucal", "lesiones palatinas", "bulto en el cielo de la boca", "sarcoma en la boca", "mancha oscura en la encía", "problemas en el paladar", "herida que no sana en la boca", "mancha violácea paladar", "lesiones orales sida", "dolor en el paladar"]'),
('C46.3', 'Sarcoma de Kaposi de ganglios linfáticos', 'Sin especificar', '["ganglios inflamados", "bolitas en el cuello", "nódulos linfáticos hinchados", "cáncer de ganglios", "adenopatías", "sarcoma en los ganglios", "ganglios crecidos", "bolitas en la axila", "bolitas en la ingle", "inflamación de ganglios", "linfadenopatía kaposi", "ganglios duros", "bultos en el cuello", "hinchazón de ganglios", "dolor de ganglios"]'),
('C46.4', 'Sarcoma de Kaposi de localizaciones gastrointestinales', 'Sin especificar', '["dolor de panza", "sangrado intestinal", "dolor de guata", "malestar estomacal", "cáncer de estómago", "tumor intestinal", "sangre en la caca", "problemas digestivos", "dolor de barriga", "lesiones en el intestino", "cáncer gastrointestinal", "sangrado digestivo", "problemas de tripas", "nódulos en el sistema digestivo", "diarrea con sangre"]'),
('C46.50', 'Sarcoma de Kaposi de pulmón no especificado', 'Sin especificar', '["problemas para respirar", "tos persistente", "cáncer de pulmón", "dolor en el pecho", "falta de aire", "sarcoma pulmonar", "tos con sangre", "dificultad al respirar", "tumores en los pulmones", "ahogo", "manchas en los pulmones", "cáncer en el pecho", "pulmones afectados", "tos crónica", "disnea"]'),
('C46.51', 'Sarcoma de Kaposi de pulmón derecho', 'Sin especificar', '["dolor en pulmón derecho", "tumor en pulmón derecho", "lesión pulmón derecho", "cáncer pulmón lado derecho", "mancha pulmón derecho", "dificultad respiratoria derecha", "sarcoma lado derecho", "problema respiratorio derecho", "masa en pulmón derecho", "dolor en costado derecho", "afección pulmonar derecha", "nódulo pulmón derecho", "afectación pulmón derecho", "tos pulmón derecho", "diagnóstico pulmón derecho"]'),
('C46.52', 'Sarcoma de Kaposi de pulmón izquierdo', 'Sin especificar', '["dolor en pulmón izquierdo", "tumor en pulmón izquierdo", "lesión pulmón izquierdo", "cáncer pulmón lado izquierdo", "mancha pulmón izquierdo", "dificultad respiratoria izquierda", "sarcoma lado izquierdo", "problema respiratorio izquierdo", "masa en pulmón izquierdo", "dolor en costado izquierdo", "afección pulmonar izquierda", "nódulo pulmón izquierdo", "afectación pulmón izquierdo", "tos pulmón izquierdo", "diagnóstico pulmón izquierdo"]'),
('C46.7', 'Sarcoma de Kaposi de otras localizaciones especificadas', 'Sin especificar', '["sarcoma en otros órganos", "cáncer kaposi sistémico", "lesiones internas kaposi", "tumor en órganos", "sarcoma diseminado", "kaposi en órganos internos", "cáncer raro", "tumores múltiples", "localizaciones inusuales kaposi", "afecciones sistémicas", "compromiso visceral", "metástasis kaposi", "manchas internas", "crecimientos extraños", "cáncer avanzado"]'),
('C46.9', 'Sarcoma de Kaposi, no especificado', 'Sin especificar', '["cáncer de kaposi", "enfermedad de kaposi", "sarcoma kaposi", "manchas de sida", "cáncer de las manchas", "tumores en la piel y órganos", "lesiones cutáneas y sistémicas", "diagnóstico kaposi", "sarcoma asociado al VIH", "manchas que sangran", "tumor maligno vascular", "lesiones violáceas extensas", "cáncer del sistema inmunológico", "nódulos y manchas", "enfermedad oncológica"]');
