INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P29.0', 'Insuficiencia cardiaca neonatal', 'Sin especificar', '["corazón débil bebé", "falla cardiaca recién nacido", "corazón grande bebé", "soplo neonatal", "bebé cianótico", "corazón no bombea bien", "edema neonatal", "bebé cansado al comer", "falla del corazón al nacer", "insuficiencia cardiaca del infante", "corazón insuficiente", "problema cardiaco al nacer", "bebé morado", "dificultad respiratoria cardiaca"]'),
('P29.11', 'Taquicardia neonatal', 'Sin especificar', '["corazón acelerado bebé", "taquicardia del recién nacido", "latidos rápidos bebé", "corazón acelerado al nacer", "taquicardia supraventricular neonatal", "pulso acelerado recién nacido", "taquicardia sinusal bebé", "palpitaciones bebé", "corazón disparado bebé", "bebé con el corazón a mil", "latidos veloces infante", "arritmia rápida neonatal", "ritmo cardiaco alto recién nacido"]'),
('P29.12', 'Bradicardia neonatal', 'Sin especificar', '["corazón lento bebé", "bradicardia del recién nacido", "latidos pausados bebé", "pulso bajo bebé", "frecuencia cardiaca baja al nacer", "ritmo cardiaco lento recién nacido", "corazón que late poco", "bebé con frecuencia baja", "pausas en el corazón bebé", "bradicardia del neonato", "corazón lento al nacer", "pulso débil bebé", "ritmo lento al nacer"]'),
('P29.2', 'Hipertensión neonatal', 'Sin especificar', '["presión alta recién nacido", "tensión arterial elevada bebé", "hipertensión del neonato", "presión alta al nacer", "presión elevada en el bebé", "bebé hipertenso", "tensión alta bebé", "presión elevada al nacer", "problema de presión al nacer", "hipertensión arterial del recién nacido", "presión sanguínea alta bebé", "hipertensión al nacer"]'),
('P29.30', 'Hipertensión pulmonar del recién nacido', 'Sin especificar', '["hipertensión pulmonar bebé", "presión alta en pulmones bebé", "problema pulmonar cardiaco", "falta de aire al nacer", "bebé con falta de oxigeno", "hipertensión pulmonar persistente", "presión elevada pulmones recién nacido", "enfermedad vascular pulmonar bebé", "bebé se pone morado", "dificultad respiratoria severa al nacer", "presión pulmonar alta", "híper tensión en pulmones"]'),
('P29.38', 'Otra persistencia de la circulación fetal', 'Sin especificar', '["conducto arterioso persistente bebé", "persistencia de ductus", "circulación fetal que no cambia", "ductus arterioso abierto", "problema de circulación al nacer", "corazón sigue en modo fetal", "falla en cierre del conducto", "circulación de bebé no madura", "ductus arterioso", "persistencia fetal", "fallo en la transición circulatoria", "circulación persistente", "conducto abierto"]'),
('P29.4', 'Isquemia miocárdica transitoria en el recién nacido', 'Sin especificar', '["falta de riego al corazón bebé", "isquemia del corazón recién nacido", "infarto transitorio bebé", "falta de oxígeno al corazón al nacer", "isquemia miocárdica neonato", "daño cardiaco al nacer", "problema de flujo coronario bebé", "isquemia temporal corazón", "corazón sin oxígeno bebé", "isquemia al nacer", "sufrimiento cardiaco bebé", "isquemia miocárdica neonatal"]'),
('P29.81', 'Parada cardiaca del recién nacido', 'Sin especificar', '["parada cardiaca bebé", "bebé dejó de latir", "paro cardiaco al nacer", "corazón se detuvo bebé", "reanimación cardiaca neonato", "paro del corazón en recién nacido", "bebé sin pulso", "se detuvo el corazón", "paro cardiaco al nacer", "reanimación al nacer", "ausencia de latidos al nacer", "paro circulatorio neonatal"]'),
('P29.89', 'Otros trastornos cardiovasculares originados en el período perinatal', 'Sin especificar', '["problemas del corazón al nacer", "fallo circulatorio recién nacido", "trastorno cardiaco perinatal", "problemas de circulación al nacer", "cardiopatía del recién nacido", "fallas al nacer del corazón", "complicaciones cardiacas perinatales", "problemas de venas y arterias bebé", "enfermedad cardiaca al nacer", "problema circulatorio", "trastorno del sistema circulatorio", "cardiopatía neonatal"]'),
('P29.9', 'Trastorno cardiovascular no especificado, con origen en el período perinatal', 'Sin especificar', '["problema cardiaco desconocido al nacer", "fallo cardiovascular no definido", "trastorno del corazón al nacer", "problemas en la circulación bebé", "cardiopatía inespecífica neonatal", "bebé con problema al corazón", "trastorno vascular inespecífico", "daño cardiaco no especificado", "problema desconocido del corazón al nacer", "anomalía cardiaca perinatal", "inconveniente cardiaco al nacer", "trastorno del sistema cardiovascular recién nacido"]');
