INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q98.0', 'Síndrome de Klinefelter, cariotipo 47, XXY', 'Sin especificar', '["síndrome de Klinefelter", "47 XXY", "esterilidad masculina", "infertilidad hombre", "trastorno cromosómico", "ginoide", "ginecomastia", "hipogonadismo", "problemas de desarrollo sexual", "cromosomas de más", "fallo testicular", "desequilibrio hormonal", "testículos pequeños", "pubertad retrasada", "exceso de cromosoma X"]'),
('Q98.1', 'Síndrome de Klinefelter, hombre con más de dos cromosomas X', 'Sin especificar', '["XXXY", "XXXXY", "síndrome de Klinefelter severo", "variante Klinefelter", "anomalía cromosómica", "hombres con cromosomas extra", "discapacidad intelectual", "problemas de aprendizaje", "retraso en el desarrollo", "criptorquidia", "microorquidismo", "carencia de testosterona", "baja libido", "síntomas de Klinefelter", "exceso de X"]'),
('Q98.3', 'Otros hombres con cariotipo 46, XX', 'Sin especificar', '["varón XX", "síndrome de reversión sexual", "46 XX masculino", "hombre con cromosomas femeninos", "esterilidad", "trastorno del desarrollo sexual", "DSD", "anomalía genética", "falta de espermatozoides", "azoospermia", "hipogonadismo primario", "fenotipo masculino", "ambigüedad genética", "infecondidad masculina", "testículos no descendidos"]'),
('Q98.4', 'Síndrome de Klinefelter, no especificado', 'Sin especificar', '["Klinefelter no definido", "síndrome XXY genérico", "problemas de cromosomas", "esterilidad por genética", "desorden genético masculino", "infertilidad inexplicable", "trastorno de los cromosomas sexuales", "diagnóstico Klinefelter", "alteración cromosómica", "falla en la producción de esperma", "desarrollo sexual alterado", "estudio de cariotipo", "genética del varón", "testosterona baja", "dificultades de fertilidad"]'),
('Q98.5', 'Cariotipo 47, XYY', 'Sin especificar', '["síndrome XYY", "síndrome del superhombre", "47 XYY", "talla alta", "problemas de aprendizaje", "conducta agresiva", "crecimiento acelerado", "alteración genética", "cromosoma Y extra", "trastorno del comportamiento", "hipotonía muscular", "dificultad de habla", "retraso en lenguaje", "anomalía masculina", "genética del cromosoma Y"]'),
('Q98.6', 'Hombre con cromosoma sexual estructuralmente anormal', 'Sin especificar', '["anomalía en cromosomas", "deleción cromosoma sexual", "translocación sexual", "problema genético masculino", "defecto cromosómico", "falla en el desarrollo sexual", "esterilidad masculina", "infertilidad", "genética anormal", "cariotipo alterado", "malformación genética", "problemas hormonales hombres", "desorden del desarrollo", "alteración en el esperma", "disfunción testicular"]'),
('Q98.7', 'Hombre con un mosaicismo cromosómico sexual', 'Sin especificar', '["mosaicismo sexual", "mosaicismo cromosómico", "células con distinto ADN", "variante genética", "Klinefelter mosaico", "error en cromosomas", "problemas de fertilidad hombre", "desarrollo sexual incompleto", "hipogonadismo", "fallo en las gónadas", "problemas de testosterona", "genética de la infertilidad", "cariotipo mixto", "células X extra", "síntomas genéticos raros"]'),
('Q98.8', 'Otras anomalías cromosómicas sexuales especificadas, fenotipo masculino', 'Sin especificar', '["mutación genética masculina", "anomalía del cromosoma Y", "trastorno genético raro", "problema del desarrollo sexual", "infertilidad genética", "esterilidad", "hipogonadismo", "falla en testículos", "desorden cromosómico", "problemas de hormonas masculinas", "cariotipo inusual", "anormalidad sexual masculina", "anomalía gonadal", "defectos del desarrollo genético", "disfunción sexual congénita"]'),
('Q98.9', 'Anomalía cromosómica sexual, fenotipo masculino, no especificada', 'Sin especificar', '["problemas genéticos hombres", "anomalía en cromosomas sexuales", "trastorno de fertilidad", "esterilidad sin causa aparente", "problema en el cariotipo", "falla hormonal masculina", "desorden sexual", "genética del varón", "infertilidad", "testículos pequeños", "desarrollo puberal anormal", "hipogonadismo", "estudio de fertilidad", "anormalidad genética", "desequilibrio cromosómico"]');
