INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J32.0', 'Sinusitis crónica maxilar', 'Sin especificar', '["sinusitis", "dolor en los pómulos", "moco espeso", "nariz tapada", "congestión nasal", "presión en la cara", "sinusitis en los cachetes", "infección en los senos paranasales", "mocos verdes", "dolor de muelas por sinusitis", "inflamación de senos maxilares", "nariz congestionada", "goteo postnasal", "sinusitis vieja", "dolor facial", "catarro que no se quita"]'),
('J32.1', 'Sinusitis frontal crónica', 'Sin especificar', '["dolor en la frente", "sinusitis en la frente", "cabeza pesada", "dolor de cabeza por sinusitis", "presión en la frente", "infección frontal", "frente inflamada", "presión sobre los ojos", "dolor de cejas", "sinusitis persistente", "dolor de cabeza frontal", "moco en la frente", "sinusitis crónica", "jaqueca por sinusitis", "punzadas en la frente", "congestión severa"]'),
('J32.2', 'Sinusitis etmoidal crónica', 'Sin especificar', '["dolor entre los ojos", "presión en el tabique", "dolor en el puente nasal", "sinusitis entre los ojos", "infección etmoidal", "presión ocular", "dolor al tocar la nariz", "congestión profunda", "sinusitis de larga duración", "secreción nasal persistente", "dolor en la nariz", "bloqueo nasal", "inflamación de celdillas etmoidales", "molestias oculares por sinusitis", "tabique congestionado", "mocos constantes"]'),
('J32.3', 'Sinusitis esfenoidal crónica', 'Sin especificar', '["dolor en la nuca", "dolor en el fondo de la cabeza", "sinusitis profunda", "dolor de oído por sinusitis", "presión en la base del cráneo", "infección esfenoidal", "dolor de cabeza tensional", "molestia en la garganta", "presión detrás de los ojos", "dolor de coronilla", "sinusitis difícil de detectar", "presión en la nuca", "dolor profundo en el cráneo", "inflamación de senos esfenoidales", "dolor de cuello por sinusitis", "congestión interna"]'),
('J32.4', 'Pansinusitis crónica', 'Sin especificar', '["sinusitis en todos los senos", "sinusitis generalizada", "inflamación de todos los senos paranasales", "infección total de nariz y cara", "sinusitis severa", "cara llena de moco", "dolor en toda la cara", "congestión nasal total", "múltiples focos de infección", "sinusitis compleja", "dolor de cabeza constante", "presión facial total", "sinusitis rebelde", "catarro crónico", "bloqueo de senos", "toda la cara inflamada"]'),
('J32.8', 'Otros tipos de sinusitis crónica', 'Sin especificar', '["sinusitis recurrente", "sinusitis rara", "sinusitis persistente", "mocos que no salen", "dolor facial crónico", "sinusitis rebelde", "sinusitis que no cura", "infección de senos paranasales", "congestión crónica", "malestar nasal", "goteo de nariz constante", "inflamación de senos paranasales", "sinusitis mixta", "dolor crónico en la cara", "moco constante", "catarro de años"]'),
('J32.9', 'Sinusitis crónica, no especificada', 'Sin especificar', '["sinusitis", "infección de nariz", "dolor de cara", "mocos espesos", "congestión nasal", "sinusitis de mucho tiempo", "nariz tapada por meses", "dolor en los senos paranasales", "sinusitis mal curada", "catarro crónico", "inflamación de nariz", "dolor de cabeza por moco", "presión facial", "sinusitis constante", "mocos pegados", "malestar por sinusitis"]');
