INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N32.0', 'Obstrucción de cuello vesical', 'Sin especificar', '["bloqueo urinario", "no puedo orinar", "chorro débil", "esfuerzo para orinar", "vejiga obstruida", "retención de orina", "problemas al miccionar", "goteo postmiccional", "traba en la vejiga", "obstrucción al orinar", "pujo urinario", "orina cortada", "flujo débil", "estenosis cuello vesical", "problemas de próstata asociados"]'),
('N32.1', 'Fístula vesicointestinal', 'Sin especificar', '["gas al orinar", "heces en la orina", "fístula vejiga intestino", "neumaturia", "infección urinaria recurrente", "orina con materia fecal", "fecaluria", "comunicación vejiga intestino", "olor fecal en la orina", "pus en la orina", "dolor pélvico crónico", "orina turbia", "burbujas al orinar", "infección persistente", "perforación vejiga"]'),
('N32.2', 'Fístula vesical, no clasificada bajo otro concepto', 'Sin especificar', '["fuga de orina", "orina por otro lado", "fístula en la vejiga", "agujero en la vejiga", "orina vaginal", "fístula urogenital", "goteo constante", "humedad permanente", "lesión vesical", "comunicación anormal", "incontinencia por fístula", "pérdida de pipí", "escurrimiento urinario", "problema en el tracto urinario", "defecto vesical"]'),
('N32.3', 'Divertículo de vejiga', 'Sin especificar', '["bolsa en la vejiga", "saco vesical", "quiste en la vejiga", "diverticulosis vesical", "vejiga deformada", "orina estancada", "acumulación de orina", "dolor al orinar", "infección urinaria frecuente", "vejiga con hernia", "abultamiento vesical", "orinar en dos tiempos", "retención crónica", "formación sacular", "problemas para vaciar la vejiga"]'),
('N32.81', 'Vejiga hiperactiva', 'Sin especificar', '["ganas de orinar a cada rato", "vejiga sensible", "urgencia urinaria", "orino cada 5 minutos", "vejiga nerviosa", "escapes de pipí", "vejiga inquieta", "incontinencia de urgencia", "no aguanto las ganas", "despertarse a orinar mucho", "vejiga irritable", "vejiga sobreactiva", "frecuencia urinaria", "pérdidas de orina al estornudar", "vejiga loca"]'),
('N32.89', 'Otros trastornos especificados de vejiga', 'Sin especificar', '["problemas de vejiga", "malestar vesical", "dolor en la vejiga", "vejiga inflamada", "cistitis crónica", "vesicalgia", "trastornos miccionales", "vejiga dolorosa", "molestias al orinar", "ardor en la uretra", "vejiga irritada", "daño en la pared vesical", "problemas urológicos", "inflamación de la vejiga", "dolor bajo vientre"]'),
('N32.9', 'Trastorno de vejiga, no especificado', 'Sin especificar', '["enfermedad de la vejiga", "dolor en la zona baja", "problema urinario", "dolor en la panza", "dolor en la guata", "dolor en la barriga", "mal al orinar", "infección urinaria", "molestias urinarias", "no puedo aguantar la orina", "problemas de vejiga no diagnosticados", "dolor pélvico", "sintomas urinarios", "trastorno vesical", "urgencia de orinar"]');
