INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Y90.0', 'Nivel de alcoholemia menor de 20 mg/100 ml', 'Sin especificar', '["alcoholemia baja", "tomar poco", "trago suave", "aliento alcohólico leve", "copa de vino", "bebida ligera", "tasa de alcohol", "control de alcoholemia", "soplar alcohol", "alcohol en sangre mínimo", "test de aliento", "primer trago", "estado sobrio", "beber social", "poca graduación"]'),
('Y90.1', 'Nivel de alcoholemia de 20-39 mg/100 ml', 'Sin especificar', '["leve embriaguez", "tomé una cerveza", "alegría alcohólica", "bajo efecto alcohol", "alcoholemia control", "trago social", "poca caña", "ligeramente mareado", "alcohol en aliento", "test de alcohol", "beber moderado", "nivel de alcohol permisible", "tomado poco", "ligera alteración", "copas de más"]'),
('Y90.2', 'Nivel de alcoholemia de 40-59 mg/100 ml', 'Sin especificar', '["medio ebrio", "un poco entonado", "alcohol en sangre", "control de tránsito", "soplar en la pipeta", "tasa alcohol permitida", "tragos", "efectos del alcohol", "mareo leve", "poca chispa", "tomado dos cervezas", "alcoholemia en sangre", "medidor de alcohol", "aliento a alcohol", "beodo leve"]'),
('Y90.3', 'Nivel de alcoholemia de 60-79 mg/100 ml', 'Sin especificar', '["alcoholemia moderada", "pedito", "medio alegre", "tomado moderado", "alcoholizado", "embriaguez media", "puntos de alcoholemia", "test de alcoholemia positivo", "tragos encima", "con unas copas", "poca coordinación", "aliento etílico", "ligeramente borracho", "niveles de alcohol", "beber en fiesta"]'),
('Y90.4', 'Nivel de alcoholemia de 80-99 mg/100 ml', 'Sin especificar', '["borracho", "ebrio", "tomado", "alcohol en sangre alto", "nivel etílico", "tragos de más", "llevo unos tragos", "alcoholemia alta", "test positivo", "con copas", "mareado por alcohol", "borrachera", "etanol en sangre", "alcoholemia límite", "beber alcohol"]'),
('Y90.5', 'Nivel de alcoholemia de 100-119 mg/100 ml', 'Sin especificar', '["ebriedad legal", "borrachera media", "alto nivel alcohol", "alcoholemia excesiva", "pedazo de borrachera", "tomado de más", "estado etílico", "alcohol en cuerpo", "mareo fuerte", "pérdida de reflejos", "control positivo", "ebrio moderado", "con aliento", "alcoholismo agudo", "muchos tragos"]'),
('Y90.6', 'Nivel de alcoholemia de 120-199 mg/100 ml', 'Sin especificar', '["muy borracho", "embriaguez severa", "pedido mal", "tomado hasta el agua", "alcoholismo", "alcoholemia muy alta", "ebriedad profunda", "pérdida de equilibrio", "hablar trabado", "etanol elevado", "borrachera seria", "test de alcohol alto", "exceso de alcohol", "con varias copas", "intoxicación alcohólica"]'),
('Y90.7', 'Nivel de alcoholemia de 200-239 mg/100 ml', 'Sin especificar', '["borrachera fuerte", "en estado de ebriedad", "alcoholemia crítica", "intoxicación por alcohol", "muy alcoholizado", "hasta las trancas", "pedísimo", "borracho perdido", "alcohol en sangre muy elevado", "pérdida de consciencia", "mareo severo", "estado de inconsciencia", "excesivo alcohol", "coma alcohólico leve", "ciego de alcohol"]'),
('Y90.8', 'Nivel de alcoholemia de 240 mg/100 ml o más', 'Sin especificar', '["coma alcohólico", "intoxicación etílica severa", "borrachera extrema", "alcoholemia máxima", "estado inconsciente", "peligro por alcohol", "alcohol en sangre extremo", "sobrepasado de alcohol", "envenenamiento por alcohol", "emergencia alcohólica", "pedotota", "cero reflejos", "inconsciencia por trago", "niveles tóxicos de alcohol", "urgencia por alcohol"]'),
('Y90.9', 'Presencia de alcoholemia, nivel no especificado', 'Sin especificar', '["aliento etílico", "olor a alcohol", "test positivo", "presencia de alcohol", "bebí alcohol", "alcoholemia detectada", "alcohol en aliento", "sospecha de ebriedad", "tomé algo", "revisión de alcoholemia", "estado de alcoholemia", "rastro de alcohol", "beber", "positivo en alcohol", "análisis de alcohol"]');
