INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('F63.0', 'Ludopatía', 'Sin especificar', '["adicción al juego", "vicio por las apuestas", "jugador compulsivo", "ludópata", "apostar todo", "problemas con el casino", "adicto a las tragamonedas", "gastarse el dinero en apuestas", "no poder parar de jugar", "ruleta", "apuestas deportivas", "bingo", "apostar la casa", "perderlo todo en el juego", "juego patológico", "obsesión por el azar"]'),
('F63.1', 'Piromanía', 'Sin especificar', '["obsesión con el fuego", "ganas de quemar cosas", "prender fuego", "pirómano", "incendiario", "impulso de incendiar", "fuego", "quemar objetos", "fascinación por las llamas", "provocar incendios", "prender hogueras", "jugar con fuego", "placer al ver quemar", "piromanía", "incendiarismo"]'),
('F63.2', 'Cleptomanía', 'Sin especificar', '["robar por impulso", "ganas de robar cosas", "cleptómano", "robar sin necesidad", "chorizo", "caco", "ladrón compulsivo", "me llevo las cosas sin pagar", "tentación de hurtar", "robo impulsivo", "clepto", "no puedo evitar robar", "me gusta hurtar", "robar en tiendas", "hurto compulsivo"]'),
('F63.3', 'Tricotilomanía', 'Sin especificar', '["arrancarse el pelo", "arrancarse las cejas", "quitarse los vellos", "me arranco el cabello", "trastorno de arrancarse el pelo", "calvas por arrancarme el pelo", "tricotilomanía", "ansiedad por el pelo", "tirarse del pelo", "arrancarse pestañas", "alopecia por arrancamiento", "impulso de depilarse el pelo", "jalarse el cabello"]'),
('F63.81', 'Trastorno explosivo intermitente', 'Sin especificar', '["ataques de ira", "perder el control", "explosiones de rabia", "mal genio", "me descontrolo fácil", "agresividad repentina", "ataques de furia", "pronto", "iracundo", "estallidos violentos", "perder los estribos", "me pongo violento de repente", "arranques de cólera", "explosivo", "no puedo controlar mi rabia", "ira desmedida"]'),
('F63.89', 'Otros tipos de trastornos de impulsos', 'Sin especificar', '["falta de control", "impulsividad", "conducta compulsiva", "no puedo parar", "compulsión", "hacer cosas sin pensar", "actuar por impulso", "trastorno de conducta", "necesidad incontrolable", "problemas de autocontrol", "tengo impulsos raros", "descontrol emocional", "comportamiento impulsivo", "adicción conductual"]'),
('F63.9', 'Trastorno de los impulsos, no especificado', 'Sin especificar', '["no sé qué me pasa", "impulso incontrolable", "problema de conducta", "actúo sin pensar", "me dejo llevar por el momento", "compulsiones raras", "trastorno conductual", "falta de freno", "comportamiento errático", "necesito ayuda con mis impulsos", "no puedo dominar mis actos", "impulsividad desmedida", "trastorno inespecífico de impulsos"]');
