INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('R78.0', 'Hallazgo de alcohol en sangre', 'Sin especificar', '["alcoholemia", "ebriedad", "borrachera", "tomar", "beber", "positivo en alcohol", "nivel de alcohol", "intoxicación etílica", "chupa", "pedera", "copas", "alcoholímetro", "guayabo", "resaca", "cruda", "ebrio", "tomado", "borracho"]'),
('R78.1', 'Hallazgo de drogas opiáceas en sangre', 'Sin especificar', '["opiáceos", "heroína", "morfina", "codeína", "drogadicción", "positivo en opiáceos", "metadona", "estupefacientes", "fármacos fuertes", "drogas en el sistema", "abuso de drogas", "toxicología positiva", "adicción", "substancias ilícitas", "sedantes", "drogado"]'),
('R78.2', 'Hallazgo de cocaína en sangre', 'Sin especificar', '["cocaína", "coca", "perico", "nieve", "merca", "polvo blanco", "positivo en cocaína", "drogas estimulantes", "análisis de drogas", "consumo de cocaína", "estupefacientes", "drogado", "raya", "linea", "toco", "sustancias prohibidas"]'),
('R78.3', 'Hallazgo de alucinógenos en sangre', 'Sin especificar', '["alucinógenos", "ácido", "LSD", "hongos", "psicodélicos", "viaje", "alucinaciones", "drogas recreativas", "test de drogas", "estupefacientes", "sustancias alucinantes", "setas", "peyote", "tripi", "drogado", "visiones"]'),
('R78.4', 'Hallazgo de otras drogas potencialmente adictivas en sangre', 'Sin especificar', '["drogas adictivas", "abuso de sustancias", "dependencia a drogas", "anfetaminas", "meta", "cristal", "tacha", "éxtasis", "speed", "test toxicológico", "positivo en drogas", "drogadicción", "consumo problemático", "estimulantes", "sustancias controladas"]'),
('R78.5', 'Hallazgo de drogas psicotrópicas en sangre', 'Sin especificar', '["psicotrópicos", "ansiolíticos", "sedantes", "benzodiacepinas", "clonazepam", "pastillas", "tranquilizantes", "drogas psiquiátricas", "abuso de fármacos", "adicción a pastillas", "medicación psicotrópica", "test de sustancias", "drogas para los nervios", "valium", "ansiedad", "dormir"]'),
('R78.6', 'Hallazgo de andrógenos anabolizantes detectados en sangre', 'Sin especificar', '["anabólicos", "esteroides", "testosterona", "suplementos dopaje", "doping", "hormonas en sangre", "musculación", "gym", "físico culturismo", "ciclo de esteroides", "andrógenos", "sustancias para ganar músculo", "hormonas sintéticas", "uso de esteroides", "dopaje deportivo"]'),
('R78.71', 'Concentraciones anormales de plomo en sangre', 'Sin especificar', '["saturnismo", "intoxicación por plomo", "plomo en sangre", "metales pesados", "envenenamiento por plomo", "contaminación por plomo", "plumbemia", "tóxicos en sangre", "pintura con plomo", "metales en el cuerpo", "niveles de plomo altos", "intoxicación ambiental", "plomo"]'),
('R78.79', 'Hallazgo de concentraciones anormales de metales pesados en sangre', 'Sin especificar', '["metales pesados", "intoxicación por mercurio", "arsénico en sangre", "cadmio", "metales tóxicos", "contaminación metálica", "tóxicos ambientales", "envenenamiento metálico", "químicos en la sangre", "intoxicación industrial", "análisis de metales", "exposición tóxica", "metales"]'),
('R78.81', 'Bacteriemia', 'Sin especificar', '["bacterias en la sangre", "infección en la sangre", "sepsis", "septicemia", "infección generalizada", "sangre infectada", "bacterias circulantes", "fiebre alta", "infección severa", "presencia de bacterias", "infección bacteriana", "bacterias en hemocultivo", "septicemia", "infección sistémica"]'),
('R78.89', 'Hallazgo de otras sustancias especificadas, que no se encuentran normalmente en sangre', 'Sin especificar', '["sustancias extrañas", "tóxicos en sangre", "químicos en sangre", "venenos en sangre", "exposición a sustancias", "anomalías químicas", "elementos extraños en sangre", "intoxicación", "sustancias desconocidas", "análisis de sangre anormal", "sustancias industriales", "contaminantes sanguíneos", "químicos"]'),
('R78.9', 'Hallazgo de sustancia no especificada, que no se encuentra normalmente en sangre', 'Sin especificar', '["sustancia desconocida", "elemento extraño", "sangre contaminada", "algo en la sangre", "análisis alterado", "tóxico no identificado", "cuerpo extraño en sangre", "resultados anormales", "análisis clínico raro", "sustancia rara", "prueba de sangre positiva", "desconocido", "anormalidad sanguínea", "químico no identificado"]');
