INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N73.0', 'Parametritis y celulitis pélvica agudas', 'Sin especificar', '["infección en la matriz", "dolor bajo vientre agudo", "inflamación pélvica aguda", "celulitis en la pelvis", "dolor pélvico repentino", "infección uterina aguda", "dolor de caderas y matriz", "pus en la pelvis", "fiebre y dolor pélvico", "parametrítis", "inflamación de los tejidos de la matriz", "dolor punzante en el bajo vientre", "infección severa de la zona íntima"]'),
('N73.1', 'Parametritis y celulitis pélvica crónicas', 'Sin especificar', '["dolor pélvico constante", "infección pélvica persistente", "dolor recurrente bajo vientre", "inflamación crónica de matriz", "molestia persistente en la pelvis", "celulitis pélvica de larga duración", "dolor sordo en la matriz", "malestar crónico en la zona baja", "inflamación de los ligamentos del útero", "parametritis crónica", "dolor pélvico de meses", "inflamación vaginal recurrente"]'),
('N73.2', 'Parametritis y celulitis pélvica no especificadas', 'Sin especificar', '["dolor en la pelvis", "inflamación de órganos reproductores", "malestar en el bajo vientre", "infección desconocida en la matriz", "dolor en la zona de la pelvis", "problemas inflamatorios pélvicos", "dolor en la zona baja femenina", "molestias ginecológicas", "infección ginecológica sin nombre", "dolor de ovarios y matriz", "inflamación pélvica no diagnosticada"]'),
('N73.3', 'Peritonitis pélvica aguda femenina', 'Sin especificar', '["peritonitis pélvica", "dolor abdominal bajo intenso", "inflamación del peritoneo pélvico", "dolor de guata agudo", "dolor de panza fuerte", "infección en la cavidad pélvica", "peritonitis aguda femenina", "dolor al caminar bajo vientre", "fiebre pélvica", "vientre inflamado y doloroso", "dolor agudo en la zona baja", "infección del recubrimiento de la pelvis"]'),
('N73.4', 'Peritonitis pélvica crónica femenina', 'Sin especificar', '["peritonitis persistente", "dolor de bajo vientre recurrente", "inflamación de peritoneo duradera", "dolor pélvico crónico", "molestia constante en la zona baja", "inflamación pélvica de larga evolución", "dolor sordo en el vientre", "problemas de peritoneo femenino", "dolor persistente al tener relaciones", "inflamación ginecológica persistente"]'),
('N73.5', 'Peritonitis pélvica femenina no especificada', 'Sin especificar', '["dolor en la pelvis femenina", "inflamación de la zona abdominal baja", "molestia en el bajo vientre", "dolor de matriz sin causa clara", "peritonitis pélvica indefinida", "inflamación ginecológica", "dolor difuso en la pelvis", "malestar abdominal inferior", "dolor pélvico inexplicable", "infección pélvica no definida"]'),
('N73.6', 'Adherencias de peritoneo pélvico femenino (posinfecciosas)', 'Sin especificar', '["adherencias en la matriz", "cicatrices internas en la pelvis", "tejido cicatricial pélvico", "dolor por cirugías previas", "dolor por infecciones pasadas", "pegaduras internas en el vientre", "dolor pélvico crónico posinfección", "adherencias después de infección", "dolor al moverse", "molestia por adherencias pélvicas", "tejido inflamado interno", "dolor pélvico por bridas"]'),
('N73.8', 'Otros tipos especificados de enfermedades inflamatorias pélvicas femeninas', 'Sin especificar', '["EIP", "enfermedad inflamatoria pélvica", "infección de la matriz", "infección en las trompas", "dolor pélvico infeccioso", "salpingitis", "ooforitis", "infección ginecológica", "dolor de ovarios", "inflamación de la zona baja", "flujo y dolor pélvico", "infección de la zona reproductiva"]'),
('N73.9', 'Enfermedad inflamatoria pélvica femenina, no especificada', 'Sin especificar', '["EIP no especificada", "dolor pélvico", "infección pélvica", "inflamación de la matriz", "dolor de ovarios y trompas", "problemas ginecológicos", "dolor de bajo vientre", "inflamación interna femenina", "molestias en la zona pélvica", "infección de las partes íntimas", "dolor constante en la pelvis", "enfermedad pélvica ginecológica"]');
