INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J93.0', 'Neumotórax espontáneo a tensión', 'Sin especificar', '["pulmón colapsado", "aire en el pecho", "falta de aire súbita", "asfixia repentina", "dolor punzante en el tórax", "neumotórax a tensión", "emergencia respiratoria", "pulmón perforado", "ahogo", "dificultad para respirar grave", "opresión en el pecho", "aire atrapado en la pleura", "tos seca y falta de aire", "cianosis", "insuficiencia respiratoria aguda"]'),
('J93.11', 'Neumotórax espontáneo primario', 'Sin especificar', '["pulmón colapsado sin causa", "pinchazo en el pulmón", "dolor de costado repentino", "neumotórax simple", "aire en la caja torácica", "neumotórax de joven", "problema pulmonar repentino", "sentir que se escapa el aire", "dolor al respirar profundo", "burbuja de aire en el pulmón", "colapso pulmonar espontáneo", "dolor pleurítico", "punzada en el tórax", "disnea súbita", "sensación de aire atrapado"]'),
('J93.12', 'Neumotórax espontáneo secundario', 'Sin especificar', '["pulmón colapsado por enfermedad", "neumotórax por enfisema", "complicación de asma", "pulmón dañado por EPOC", "aire en pulmón enfermo", "derrame de aire pulmonar", "insuficiencia respiratoria por neumotórax", "dolor torácico crónico agudizado", "complicación pulmonar", "respiración entrecortada", "neumotórax por fibrosis", "pulmón que falla", "burbuja pulmonar rota", "agudización de enfermedad respiratoria", "neumotórax post-patología"]'),
('J93.81', 'Neumotórax crónico', 'Sin especificar', '["neumotórax persistente", "aire que no sale del pecho", "pulmón que no se expande", "fuga de aire crónica", "neumotórax recurrente", "problema pulmonar de larga duración", "aire constante en la pleura", "dificultad para respirar crónica", "fístula broncopleural", "pulmón a medio inflar", "molestia constante en el pecho", "neumotórax que no sana", "aire atrapado recidivante", "tos persistente con falta de aire", "incapacidad respiratoria prolongada"]'),
('J93.82', 'Otro escape de aire', 'Sin especificar', '["fuga de aire torácica", "enfisema mediastínico", "aire en el mediastino", "aire en cavidad pleural", "escapes de aire internos", "neumomediastino", "aire en el espacio pleural", "ruido al respirar", "crujido en el pecho", "enfisema subcutáneo", "aire bajo la piel", "fuga pleural", "aire extratorácico", "filtración de aire pulmonar", "escape de aire post-traumático"]'),
('J93.83', 'Otro neumotórax', 'Sin especificar', '["variedades de neumotórax", "neumotórax traumático", "neumotórax iatrogénico", "aire en la pleura por golpe", "aire en el pulmón por cirugía", "lesión en la pleura", "perforación pulmonar", "aire en tórax", "colapso del pulmón", "neumotórax por punción", "aire atrapado post-biopsia", "aire en cavidad torácica", "neumotórax hidroneumotórax", "aire y líquido en el pecho", "problema en el espacio pleural"]'),
('J93.9', 'Neumotórax, no especificado', 'Sin especificar', '["pulmón colapsado", "aire en el pulmón", "neumotórax", "dolor en el pecho al respirar", "falta de aire", "ahogo", "dificultad para respirar", "pinchazo en el tórax", "sensación de ahogo", "problema en el pecho", "pulmón pinchado", "aire atrapado", "tos con dolor torácico", "opresión en el pecho", "neumotorax genérico"]');
