INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B00.0', 'Eccema herpético', 'Sin especificar', '["erupción por herpes", "eccema por herpes simple", "brote herpético en piel", "herpes cutáneo", "pústulas herpéticas", "dermatitis herpética", "ampollas con pus", "fuegos en la piel", "vesículas en la cara", "eccema de Kaposi", "herpes diseminado en dermatitis", "pupa por herpes", "herpes en la piel irritada", "erupción dolorosa", "llagas de herpes"]'),
('B00.1', 'Dermatitis vesicular herpética', 'Sin especificar', '["vesículas herpéticas", "ampollas de herpes", "herpes simple en piel", "boqueras", "fuegos labiales", "calenturas", "vesículas con líquido", "herpes cutáneo", "picazón de herpes", "erupción con ampollas", "herpes en labios", "herpes en la nariz", "fuego en la boca", "herpes en dedos", "brote de vesículas"]'),
('B00.2', 'Gingivoestomatitis y faringoamigdalitis herpética', 'Sin especificar', '["herpes en la garganta", "herpes en las encías", "llagas en la boca", "fuegos en la boca", "aftas herpéticas", "dolor al tragar por herpes", "inflamación de encías por herpes", "anginas con llagas", "herpangina", "boca llena de llagas", "estomatitis herpética", "dolor de garganta con úlceras", "llagas en el paladar", "herpes oral", "fiebre y llagas en boca"]'),
('B00.3', 'Meningitis herpética', 'Sin especificar', '["meningitis por herpes", "inflamación del cerebro por herpes", "dolor de cabeza intenso", "rigidez de nuca", "fiebre y dolor de cabeza", "infección en las meninges", "herpes en el sistema nervioso", "meningitis viral", "dolor de nuca", "fotofobia por herpes", "mareos por herpes", "vómitos y rigidez", "herpes en la cabeza", "inflamación de membranas cerebrales", "meningitis por VHS"]'),
('B00.4', 'Encefalitis herpética', 'Sin especificar', '["encefalitis por herpes", "infección cerebral", "inflamación del cerebro", "convulsiones por herpes", "confusión mental", "cambios de personalidad", "fiebre alta y delirio", "herpes en el cerebro", "encefalitis viral", "dolor de cabeza insoportable", "problemas de habla por herpes", "problemas de memoria por herpes", "ataque al cerebro", "virus en el cerebro", "herpes fulminante"]'),
('B00.50', 'Afectación ocular por herpesvirus, no especificada', 'Sin especificar', '["herpes en el ojo", "ojo infectado por herpes", "virus en el ojo", "dolor de ojo", "ojo rojo por herpes", "visión borrosa por herpes", "molestias oculares", "herpes oftálmico", "ojo irritado", "sensibilidad a la luz", "lagrimeo por herpes", "infección ocular viral", "herpes en párpado", "herpes ocular", "pinchazos en el ojo"]'),
('B00.51', 'Iridociclitis por herpesvirus', 'Sin especificar', '["inflamación del iris", "uveítis herpética", "dolor ocular intenso", "ojo muy rojo", "herpes en la parte interna del ojo", "iridociclitis viral", "sensibilidad extrema a la luz", "visión nublada", "inflamación uveal", "ojo inyectado", "herpes en la coroides", "dolor detrás del ojo", "pérdida de visión temporal", "fotofobia severa", "inflamación del cuerpo ciliar"]'),
('B00.52', 'Queratitis por herpesvirus', 'Sin especificar', '["queratitis herpética", "herpes en la córnea", "herpes en la parte transparente del ojo", "úlcera corneal por herpes", "nube en el ojo", "cicatriz en la córnea", "dolor agudo en el ojo", "sensación de arenilla", "ojo lloroso", "visión opaca", "ojo con herpes", "infección de la córnea", "ojo blanco con manchas", "fotofobia por queratitis", "herpes de córnea"]'),
('B00.53', 'Conjuntivitis por herpesvirus', 'Sin especificar', '["conjuntivitis herpética", "ojo rojo con lagañas", "herpes en la conjuntiva", "infección en el párpado y ojo", "ojo irritado por herpes", "conjuntivitis viral", "picazón de ojos", "ojo que supura", "ojo pegado por la mañana", "ojo con virus", "herpes en la membrana del ojo", "conjuntivitis persistente", "ojo colorado", "hinchazón de párpados", "ojo con sensación de cuerpo extraño"]'),
('B00.59', 'Otras enfermedades oculares por herpesvirus', 'Sin especificar', '["complicaciones oculares de herpes", "herpes en la retina", "infección herpética del ojo", "herpes en el globo ocular", "coriorretinitis herpética", "neuritis óptica por herpes", "problemas de visión por herpes", "virus ocular", "daño en el ojo por herpes", "herpes zóster oftálmico (error común)", "infección profunda del ojo", "herpes en el nervio óptico", "inflamación ocular persistente", "herpes uveal", "edema ocular por herpes"]'),
('B00.7', 'Enfermedad herpética diseminada', 'Sin especificar', '["herpes generalizado", "herpes por todo el cuerpo", "infección herpética grave", "virus del herpes en la sangre", "sepsis por herpes", "brote herpético severo", "herpes diseminado", "herpes en órganos internos", "infección multisistémica por herpes", "herpes avanzado", "herpes incontrolable", "herpes fulminante", "herpes en inmunodeprimidos", "llagas en todo el cuerpo", "herpes sistémico"]'),
('B00.81', 'Hepatitis por herpesvirus', 'Sin especificar', '["hepatitis viral por herpes", "inflamación del hígado por herpes", "hígado infectado", "daño hepático por herpes", "virus del herpes en el hígado", "dolor en la panza por el hígado", "ictericia por herpes", "herpes en el hígado", "hepatitis herpética", "hígado inflamado", "dolor en el hipocondrio derecho", "infección del hígado", "herpes y problemas hepáticos", "enzimas hepáticas altas por herpes", "hígado con virus"]'),
('B00.82', 'Mielitis por herpes simple', 'Sin especificar', '["mielitis herpética", "inflamación de la médula espinal", "herpes en la columna", "debilidad en las piernas por herpes", "adormecimiento por herpes", "problemas de sensibilidad por herpes", "herpes y dolor de espalda", "inflamación de la médula", "daño medular por virus", "herpes neurológico", "mielitis viral", "herpes en la médula", "hormigueo en extremidades", "problemas para caminar por herpes", "infección en la columna"]'),
('B00.89', 'Otras infecciones por herpesvirus', 'Sin especificar', '["herpes raro", "otras formas de herpes", "infección por virus del herpes", "complicaciones por herpes simple", "herpes en zonas atípicas", "herpes visceral", "infección herpética atípica", "virus herpes", "herpes inusual", "secuelas de herpes", "herpes profundo", "herpes atípico", "afectación de órganos por herpes", "herpes que no se va", "problemas de salud por herpes"]'),
('B00.9', 'Infección debida a herpesvirus, no especificada', 'Sin especificar', '["tengo herpes", "infección por herpes", "virus del herpes", "herpes", "fuegos", "calenturas", "boqueras", "llagas de herpes", "ampollas", "herpes simple", "brotes", "picazón de herpes", "herpes labial", "herpes genital", "herpes por contacto", "infección viral", "herpes sin especificar", "tengo algo en la piel (posible herpes)"]');
