INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S70.00XA', 'Contusión de cadera no especificada, contacto inicial', 'Sin especificar', '["golpe en la cadera", "moratón en la cadera", "chichón en la cadera", "contusión cadera", "me pegué en la cadera", "traumatismo cadera", "dolor en la cadera por golpe", "cardenal en la cadera", "magulladura en la cadera", "hematoma en la cadera"]'),
('S70.00XD', 'Contusión de cadera no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento golpe cadera", "control contusión cadera", "dolor persistente cadera", "revisión traumatismo cadera", "evolución chichón cadera", "curación golpe cadera", "tratamiento contusión cadera", "molestias cadera tras golpe"]'),
('S70.00XS', 'Contusión de cadera no especificada, secuela', 'Sin especificar', '["secuela golpe cadera", "dolor crónico cadera por golpe", "problema persistente cadera", "secuelas traumatismo cadera", "molestias viejas en la cadera", "daño antiguo en cadera"]'),
('S70.01XA', 'Contusión de cadera derecha, contacto inicial', 'Sin especificar', '["golpe en la cadera derecha", "trancazo en la cadera derecha", "porrazo en la cadera derecha", "me di en la cadera derecha", "cardenal cadera derecha", "morado en la cadera derecha"]'),
('S70.01XD', 'Contusión de cadera derecha, contacto sucesivo', 'Sin especificar', '["seguimiento contusión cadera derecha", "control golpe cadera derecha", "revisión cadera derecha", "dolor que sigue en la cadera derecha"]'),
('S70.01XS', 'Contusión de cadera derecha, secuela', 'Sin especificar', '["secuela golpe cadera derecha", "molestias antiguas cadera derecha", "cicatriz interna cadera derecha", "dolor residual cadera derecha"]'),
('S70.02XA', 'Contusión de cadera izquierda, contacto inicial', 'Sin especificar', '["golpe en la cadera izquierda", "trancazo en la cadera izquierda", "cardenal en la cadera izquierda", "moratón lado izquierdo cadera", "me di un porrazo en la izquierda"]'),
('S70.02XD', 'Contusión de cadera izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento golpe cadera izquierda", "control contusión izquierda", "revisión molestia cadera izquierda", "dolor cadera izquierda post golpe"]'),
('S70.02XS', 'Contusión de cadera izquierda, secuela', 'Sin especificar', '["secuela golpe cadera izquierda", "dolor crónico cadera izquierda", "molestias después de tiempo cadera izquierda", "daño persistente cadera izquierda"]'),
('S70.10XA', 'Contusión de muslo no especificado, contacto inicial', 'Sin especificar', '["golpe en el muslo", "golpe en la pierna", "me di en el muslo", "moratón en el muslo", "contusión pierna", "hematoma muslo", "trancazo en la pata", "golpe en el cuadríceps"]'),
('S70.10XD', 'Contusión de muslo no especificado, contacto sucesivo', 'Sin especificar', '["revisión golpe muslo", "control contusión muslo", "seguimiento lesión muslo", "dolor muslo persiste", "curación golpe pierna"]'),
('S70.10XS', 'Contusión de muslo no especificado, secuela', 'Sin especificar', '["secuela golpe muslo", "dolor antiguo muslo", "molestia persistente en la pierna", "cicatriz interna muslo", "daño residual muslo"]'),
('S70.11XA', 'Contusión de muslo derecho, contacto inicial', 'Sin especificar', '["golpe muslo derecho", "cardenal muslo derecho", "me di en la pierna derecha", "trancazo en el muslo derecho", "hematoma muslo derecho"]'),
('S70.11XD', 'Contusión de muslo derecho, contacto sucesivo', 'Sin especificar', '["control contusión muslo derecho", "revisión golpe pierna derecha", "seguimiento muslo derecho"]'),
('S70.11XS', 'Contusión de muslo derecho, secuela', 'Sin especificar', '["secuela golpe muslo derecho", "dolor residual pierna derecha", "molestia vieja muslo derecho"]'),
('S70.12XA', 'Contusión de muslo izquierdo, contacto inicial', 'Sin especificar', '["golpe muslo izquierdo", "morado muslo izquierdo", "golpe pierna izquierda", "trancazo pierna izquierda", "hematoma muslo izquierdo"]'),
('S70.12XD', 'Contusión de muslo izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento contusión muslo izquierdo", "control golpe pierna izquierda", "revisión muslo izquierdo"]'),
('S70.12XS', 'Contusión de muslo izquierdo, secuela', 'Sin especificar', '["secuela golpe muslo izquierdo", "dolor antiguo muslo izquierdo", "molestia persistente pierna izquierda"]'),
('S70.211A', 'Abrasión de cadera derecha, contacto inicial', 'Sin especificar', '["rasponazo en la cadera derecha", "raspón cadera derecha", "piel pelada cadera derecha", "herida superficial cadera derecha", "me raspé la cadera", "quemadura por fricción cadera"]'),
('S70.211D', 'Abrasión de cadera derecha, contacto sucesivo', 'Sin especificar', '["curación raspón cadera", "seguimiento herida cadera", "control raspadura cadera", "revisión piel cadera"]'),
('S70.211S', 'Abrasión de cadera derecha, secuela', 'Sin especificar', '["cicatriz raspón cadera", "mancha por raspón cadera", "secuela herida cadera", "marca en la piel cadera"]'),
('S70.212A', 'Abrasión de cadera izquierda, contacto inicial', 'Sin especificar', '["rasponazo cadera izquierda", "raspón en la cadera izquierda", "peladura cadera izquierda", "herida por caída cadera", "raspada cadera"]'),
('S70.212D', 'Abrasión de cadera izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento raspón cadera izquierda", "control herida cadera", "revisión cura cadera"]'),
('S70.212S', 'Abrasión de cadera izquierda, secuela', 'Sin especificar', '["cicatriz cadera izquierda", "marca raspón cadera", "secuela piel cadera"]'),
('S70.219A', 'Abrasión de cadera no especificada, contacto inicial', 'Sin especificar', '["raspón en la cadera", "rasponazo cadera", "piel raspada cadera", "me pelé la cadera", "herida leve cadera"]'),
('S70.219D', 'Abrasión de cadera no especificada, contacto sucesivo', 'Sin especificar', '["revisión raspón cadera", "control cura cadera", "seguimiento herida cadera"]'),
('S70.219S', 'Abrasión de cadera no especificada, secuela', 'Sin especificar', '["cicatriz cadera", "marca en la piel de la cadera", "secuela de raspón"]'),
('S70.221A', 'Ampolla (no térmica) de cadera derecha, contacto inicial', 'Sin especificar', '["ampolla en la cadera", "burbuja en la piel cadera", "vejiga en la cadera", "rozadura en la cadera", "bulla cadera", "burbuja por roce"]'),
('S70.221D', 'Ampolla (no térmica) de cadera derecha, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla cadera", "control vejiga piel", "revisión roce cadera"]'),
('S70.221S', 'Ampolla (no térmica) de cadera derecha, secuela', 'Sin especificar', '["cicatriz ampolla cadera", "marca ampolla cadera", "secuela rozadura cadera"]'),
('S70.222A', 'Ampolla (no térmica) de cadera izquierda, contacto inicial', 'Sin especificar', '["ampolla cadera izquierda", "rozadura cadera izquierda", "vejiga en la piel cadera", "burbuja de agua cadera"]'),
('S70.222D', 'Ampolla (no térmica) de cadera izquierda, contacto sucesivo', 'Sin especificar', '["revisión ampolla cadera izquierda", "control ampolla", "seguimiento rozadura"]'),
('S70.222S', 'Ampolla (no térmica) de cadera izquierda, secuela', 'Sin especificar', '["cicatriz por ampolla cadera", "marca ampolla", "secuela piel cadera"]'),
('S70.229A', 'Ampolla (no térmica) de cadera no especificada, contacto inicial', 'Sin especificar', '["tengo una ampolla en la cadera", "rozadura en la cadera", "vejiga por roce", "burbuja cadera"]'),
('S70.229D', 'Ampolla (no térmica) de cadera no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control curación ampolla", "revisión roce"]'),
('S70.229S', 'Ampolla (no térmica) de cadera no especificada, secuela', 'Sin especificar', '["secuela ampolla cadera", "marca piel", "cicatriz"]'),
('S70.241A', 'Constricción externa de cadera derecha, contacto inicial', 'Sin especificar', '["apretón cadera", "marcas en la cadera", "constricción cadera", "me apretó algo la cadera", "marca de cinturón", "presión en la cadera"]'),
('S70.241D', 'Constricción externa de cadera derecha, contacto sucesivo', 'Sin especificar', '["revisión marca cadera", "seguimiento presión piel", "control marca"]'),
('S70.241S', 'Constricción externa de cadera derecha, secuela', 'Sin especificar', '["secuela marca cadera", "cicatriz por presión", "marca persistente piel"]'),
('S70.242A', 'Constricción externa de cadera izquierda, contacto inicial', 'Sin especificar', '["apretón cadera izquierda", "marca en la cadera izquierda", "constricción externa piel", "me marcó la ropa la cadera"]'),
('S70.242D', 'Constricción externa de cadera izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento marca cadera", "control constricción", "revisión piel"]'),
('S70.242S', 'Constricción externa de cadera izquierda, secuela', 'Sin especificar', '["secuela marca piel", "cicatriz constricción", "marca duradera"]'),
('S70.249A', 'Constricción externa de cadera no especificada, contacto inicial', 'Sin especificar', '["marcas de presión en la cadera", "me apretó la cadera", "constricción en piel de cadera"]'),
('S70.249D', 'Constricción externa de cadera no especificada, contacto sucesivo', 'Sin especificar', '["control marcas", "seguimiento piel", "revisión"]'),
('S70.249S', 'Constricción externa de cadera no especificada, secuela', 'Sin especificar', '["cicatriz de marca", "secuela de presión", "marca en la piel"]'),
('S70.251A', 'Cuerpo extraño superficial de cadera derecha, contacto inicial', 'Sin especificar', '["astilla en la cadera", "tengo algo clavado en la cadera", "objeto en la piel cadera", "espinita en la cadera", "tierra en la herida cadera"]'),
('S70.251D', 'Cuerpo extraño superficial de cadera derecha, contacto sucesivo', 'Sin especificar', '["revisión cuerpo extraño cadera", "control extracción objeto", "seguimiento herida"]'),
('S70.251S', 'Cuerpo extraño superficial de cadera derecha, secuela', 'Sin especificar', '["cicatriz por cuerpo extraño", "secuela objeto piel", "herida infectada por objeto"]'),
('S70.252A', 'Cuerpo extraño superficial de cadera izquierda, contacto inicial', 'Sin especificar', '["astilla cadera izquierda", "algo clavado cadera", "espinita en la piel", "tierra en la cadera"]'),
('S70.252D', 'Cuerpo extraño superficial de cadera izquierda, contacto sucesivo', 'Sin especificar', '["control cuerpo extraño", "revisión extracción", "seguimiento"]'),
('S70.252S', 'Cuerpo extraño superficial de cadera izquierda, secuela', 'Sin especificar', '["cicatriz objeto", "secuela herida", "infección por cuerpo extraño"]'),
('S70.259A', 'Cuerpo extraño superficial de cadera no especificada, contacto inicial', 'Sin especificar', '["algo clavado en la cadera", "astilla", "espinita", "cuerpo extraño en la piel"]'),
('S70.259D', 'Cuerpo extraño superficial de cadera no especificada, contacto sucesivo', 'Sin especificar', '["revisión extracción", "seguimiento piel", "control"]'),
('S70.259S', 'Cuerpo extraño superficial de cadera no especificada, secuela', 'Sin especificar', '["cicatriz por objeto", "secuela herida", "infección"]'),
('S70.261A', 'Picadura de insecto (no venenoso) en cadera derecha, contacto inicial', 'Sin especificar', '["picadura en la cadera derecha", "me picó un bicho en la cadera", "roncha en la cadera", "picazón cadera derecha", "zancudazo cadera"]'),
('S70.261D', 'Picadura de insecto (no venenoso) en cadera derecha, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "revisión roncha", "control hinchazón cadera"]'),
('S70.261S', 'Picadura de insecto (no venenoso) en cadera derecha, secuela', 'Sin especificar', '["cicatriz picadura", "secuela roncha", "mancha por picadura"]'),
('S70.262A', 'Picadura de insecto (no venenoso) en cadera izquierda, contacto inicial', 'Sin especificar', '["picadura cadera izquierda", "roncha cadera izquierda", "me picó un bicho", "picazón piel"]'),
('S70.262D', 'Picadura de insecto (no venenoso) en cadera izquierda, contacto sucesivo', 'Sin especificar', '["control picadura", "seguimiento roncha", "revisión"]'),
('S70.262S', 'Picadura de insecto (no venenoso) en cadera izquierda, secuela', 'Sin especificar', '["cicatriz picadura", "marca roncha", "secuela piel"]'),
('S70.269A', 'Picadura de insecto (no venenoso) en cadera no especificada, contacto inicial', 'Sin especificar', '["picadura en la cadera", "roncha en la cadera", "me picó un bicho", "picazón"]'),
('S70.269D', 'Picadura de insecto (no venenoso) en cadera no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control hinchazón", "revisión"]'),
('S70.269S', 'Picadura de insecto (no venenoso) en cadera no especificada, secuela', 'Sin especificar', '["cicatriz picadura", "secuela roncha", "marca"]'),
('S70.271A', 'Otra mordedura superficial de cadera de cadera derecha, contacto inicial', 'Sin especificar', '["mordida en la cadera", "me mordieron la cadera", "marca de mordida cadera derecha", "herida por mordisco"]'),
('S70.271D', 'Otra mordedura superficial de cadera de cadera derecha, contacto sucesivo', 'Sin especificar', '["revisión mordedura", "seguimiento herida mordida", "control infección"]'),
('S70.271S', 'Otra mordedura superficial de cadera de cadera derecha, secuela', 'Sin especificar', '["cicatriz mordedura", "secuela herida mordida", "marca mordida"]'),
('S70.272A', 'Otra mordedura superficial de cadera de cadera izquierda, contacto inicial', 'Sin especificar', '["mordida cadera izquierda", "marca mordisco cadera izquierda", "herida superficial mordedura"]'),
('S70.272D', 'Otra mordedura superficial de cadera de cadera izquierda, contacto sucesivo', 'Sin especificar', '["control mordida", "seguimiento herida", "revisión"]'),
('S70.272S', 'Otra mordedura superficial de cadera de cadera izquierda, secuela', 'Sin especificar', '["cicatriz mordida", "secuela marca", "marca de dientes"]'),
('S70.279A', 'Otra mordedura superficial de cadera de cadera no especificada, contacto inicial', 'Sin especificar', '["mordida en la cadera", "mordisco en la cadera", "herida por mordida"]'),
('S70.279D', 'Otra mordedura superficial de cadera de cadera no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "revisión herida", "control"]'),
('S70.279S', 'Otra mordedura superficial de cadera de cadera no especificada, secuela', 'Sin especificar', '["cicatriz mordedura", "secuela marca", "marca dientes"]'),
('S70.311A', 'Abrasión de muslo derecho, contacto inicial', 'Sin especificar', '["raspón en el muslo derecho", "piel pelada muslo", "me raspé la pierna derecha", "raspadura pierna"]'),
('S70.311D', 'Abrasión de muslo derecho, contacto sucesivo', 'Sin especificar', '["seguimiento raspón muslo", "control herida pierna", "curación raspadura"]'),
('S70.311S', 'Abrasión de muslo derecho, secuela', 'Sin especificar', '["cicatriz raspón muslo", "marca en la pierna", "secuela raspadura"]'),
('S70.312A', 'Abrasión de muslo izquierdo, contacto inicial', 'Sin especificar', '["raspón muslo izquierdo", "peladura pierna izquierda", "herida superficial muslo"]'),
('S70.312D', 'Abrasión de muslo izquierdo, contacto sucesivo', 'Sin especificar', '["control raspón muslo", "revisión herida", "seguimiento"]'),
('S70.312S', 'Abrasión de muslo izquierdo, secuela', 'Sin especificar', '["cicatriz muslo", "secuela raspón", "marca"]'),
('S70.319A', 'Abrasión de muslo no especificado, contacto inicial', 'Sin especificar', '["raspón en el muslo", "me raspé el muslo", "piel raspada pierna"]'),
('S70.319D', 'Abrasión de muslo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "control herida", "revisión"]'),
('S70.319S', 'Abrasión de muslo no especificado, secuela', 'Sin especificar', '["cicatriz muslo", "secuela raspón", "marca"]'),
('S70.321A', 'Ampolla (no térmica) de muslo derecho, contacto inicial', 'Sin especificar', '["ampolla muslo derecho", "rozadura en el muslo", "burbuja pierna derecha", "vejiga muslo"]'),
('S70.321D', 'Ampolla (no térmica) de muslo derecho, contacto sucesivo', 'Sin especificar', '["revisión ampolla", "control rozadura", "seguimiento"]'),
('S70.321S', 'Ampolla (no térmica) de muslo derecho, secuela', 'Sin especificar', '["cicatriz ampolla", "secuela roce", "marca piel"]'),
('S70.322A', 'Ampolla (no térmica) de muslo izquierdo, contacto inicial', 'Sin especificar', '["ampolla muslo izquierdo", "rozadura muslo", "burbuja de agua"]'),
('S70.322D', 'Ampolla (no térmica) de muslo izquierdo, contacto sucesivo', 'Sin especificar', '["control ampolla", "seguimiento rozadura", "revisión"]'),
('S70.322S', 'Ampolla (no térmica) de muslo izquierdo, secuela', 'Sin especificar', '["cicatriz ampolla", "secuela marca", "marca piel"]'),
('S70.329A', 'Ampolla (no térmica) de muslo no especificado, contacto inicial', 'Sin especificar', '["ampolla en el muslo", "rozadura muslo", "vejiga"]'),
('S70.329D', 'Ampolla (no térmica) de muslo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control cura", "revisión"]'),
('S70.329S', 'Ampolla (no térmica) de muslo no especificado, secuela', 'Sin especificar', '["cicatriz ampolla", "secuela marca", "marca piel"]'),
('S70.341A', 'Constricción externa de muslo derecho, contacto inicial', 'Sin especificar', '["marca de apretón muslo derecho", "constricción muslo derecho", "me apretó algo la pierna"]'),
('S70.341D', 'Constricción externa de muslo derecho, contacto sucesivo', 'Sin especificar', '["revisión marca muslo", "control presión piel", "seguimiento"]'),
('S70.341S', 'Constricción externa de muslo derecho, secuela', 'Sin especificar', '["cicatriz presión", "secuela marca", "marca persistente"]'),
('S70.342A', 'Constricción externa de muslo izquierdo, contacto inicial', 'Sin especificar', '["marca de presión muslo izquierdo", "constricción muslo", "me apretó la ropa el muslo"]'),
('S70.342D', 'Constricción externa de muslo izquierdo, contacto sucesivo', 'Sin especificar', '["control marca muslo", "seguimiento presión", "revisión"]'),
('S70.342S', 'Constricción externa de muslo izquierdo, secuela', 'Sin especificar', '["cicatriz constricción", "secuela marca", "marca"]'),
('S70.349A', 'Constricción externa de muslo no especificado, contacto inicial', 'Sin especificar', '["marca de apretón en el muslo", "constricción en piel muslo"]'),
('S70.349D', 'Constricción externa de muslo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento marca", "control piel", "revisión"]'),
('S70.349S', 'Constricción externa de muslo no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela marca", "marca"]'),
('S70.351A', 'Cuerpo extraño superficial de muslo derecho, contacto inicial', 'Sin especificar', '["astilla en el muslo derecho", "algo clavado en la pierna", "espinita muslo", "objeto en la piel"]'),
('S70.351D', 'Cuerpo extraño superficial de muslo derecho, contacto sucesivo', 'Sin especificar', '["revisión extracción muslo", "control herida", "seguimiento"]'),
('S70.351S', 'Cuerpo extraño superficial de muslo derecho, secuela', 'Sin especificar', '["cicatriz cuerpo extraño", "secuela herida", "infección"]'),
('S70.352A', 'Cuerpo extraño superficial de muslo izquierdo, contacto inicial', 'Sin especificar', '["astilla muslo izquierdo", "algo clavado en el muslo", "espinita en la pierna"]'),
('S70.352D', 'Cuerpo extraño superficial de muslo izquierdo, contacto sucesivo', 'Sin especificar', '["control objeto", "seguimiento herida", "revisión"]'),
('S70.352S', 'Cuerpo extraño superficial de muslo izquierdo, secuela', 'Sin especificar', '["cicatriz objeto", "secuela herida", "infección"]'),
('S70.359A', 'Cuerpo extraño superficial de muslo no especificado, contacto inicial', 'Sin especificar', '["algo clavado en el muslo", "astilla muslo", "espinita"]'),
('S70.359D', 'Cuerpo extraño superficial de muslo no especificado, contacto sucesivo', 'Sin especificar', '["revisión objeto", "control herida", "seguimiento"]'),
('S70.359S', 'Cuerpo extraño superficial de muslo no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela", "infección"]'),
('S70.361A', 'Picadura de insecto (no venenoso) en muslo derecho, contacto inicial', 'Sin especificar', '["picadura en el muslo derecho", "roncha pierna derecha", "picazón muslo", "me picó un mosquito en el muslo"]'),
('S70.361D', 'Picadura de insecto (no venenoso) en muslo derecho, contacto sucesivo', 'Sin especificar', '["seguimiento picadura muslo", "control roncha", "revisión piel"]'),
('S70.361S', 'Picadura de insecto (no venenoso) en muslo derecho, secuela', 'Sin especificar', '["cicatriz picadura", "secuela roncha", "marca picadura"]'),
('S70.362A', 'Picadura de insecto (no venenoso) en muslo izquierdo, contacto inicial', 'Sin especificar', '["picadura muslo izquierdo", "roncha muslo", "picazón"]'),
('S70.362D', 'Picadura de insecto (no venenoso) en muslo izquierdo, contacto sucesivo', 'Sin especificar', '["control picadura", "seguimiento roncha", "revisión"]'),
('S70.362S', 'Picadura de insecto (no venenoso) en muslo izquierdo, secuela', 'Sin especificar', '["cicatriz picadura", "secuela marca", "marca"]'),
('S70.369A', 'Picadura de insecto (no venenoso) en muslo no especificado, contacto inicial', 'Sin especificar', '["picadura en el muslo", "roncha en el muslo", "me picó un bicho"]'),
('S70.369D', 'Picadura de insecto (no venenoso) en muslo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control roncha", "revisión"]'),
('S70.369S', 'Picadura de insecto (no venenoso) en muslo no especificado, secuela', 'Sin especificar', '["cicatriz picadura", "secuela marca", "marca"]'),
('S70.371A', 'Otra mordedura superficial de muslo derecho, contacto inicial', 'Sin especificar', '["mordida en el muslo derecho", "marca de dientes muslo", "me mordió algo la pierna derecha"]'),
('S70.371D', 'Otra mordedura superficial de muslo derecho, contacto sucesivo', 'Sin especificar', '["revisión mordida muslo", "control herida", "seguimiento"]'),
('S70.371S', 'Otra mordedura superficial de muslo derecho, secuela', 'Sin especificar', '["cicatriz mordida", "secuela marca", "marca dientes"]'),
('S70.372A', 'Otra mordedura superficial de muslo izquierdo, contacto inicial', 'Sin especificar', '["mordida muslo izquierdo", "marca de mordida muslo", "herida superficial pierna"]'),
('S70.372D', 'Otra mordedura superficial de muslo izquierdo, contacto sucesivo', 'Sin especificar', '["control mordida", "seguimiento herida", "revisión"]'),
('S70.372S', 'Otra mordedura superficial de muslo izquierdo, secuela', 'Sin especificar', '["cicatriz mordida", "secuela marca", "marca dientes"]'),
('S70.379A', 'Otra mordedura superficial de muslo no especificado, contacto inicial', 'Sin especificar', '["mordida en el muslo", "mordisco en la pierna", "herida por mordida"]'),
('S70.379D', 'Otra mordedura superficial de muslo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "revisión herida", "control"]'),
('S70.379S', 'Otra mordedura superficial de muslo no especificado, secuela', 'Sin especificar', '["cicatriz mordida", "secuela marca", "marca dientes"]'),
('S70.911A', 'Traumatismo superficial no especificado de cadera derecha, contacto inicial', 'Sin especificar', '["lesión superficial cadera derecha", "golpe o roce cadera derecha", "daño en la piel cadera", "traumatismo cadera"]'),
('S70.911D', 'Traumatismo superficial no especificado de cadera derecha, contacto sucesivo', 'Sin especificar', '["seguimiento lesión cadera", "control traumatismo", "revisión piel"]'),
('S70.911S', 'Traumatismo superficial no especificado de cadera derecha, secuela', 'Sin especificar', '["secuela lesión cadera", "cicatriz traumatismo", "daño piel cadera"]'),
('S70.912A', 'Traumatismo superficial no especificado de cadera izquierda, contacto inicial', 'Sin especificar', '["lesión piel cadera izquierda", "golpe cadera izquierda", "traumatismo superficial"]'),
('S70.912D', 'Traumatismo superficial no especificado de cadera izquierda, contacto sucesivo', 'Sin especificar', '["control lesión", "seguimiento traumatismo", "revisión"]'),
('S70.912S', 'Traumatismo superficial no especificado de cadera izquierda, secuela', 'Sin especificar', '["cicatriz lesión", "secuela traumatismo", "marca piel"]'),
('S70.919A', 'Traumatismo superficial no especificado de cadera no especificada, contacto inicial', 'Sin especificar', '["traumatismo en la cadera", "lesión piel cadera", "golpe o raspón cadera"]'),
('S70.919D', 'Traumatismo superficial no especificado de cadera no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control traumatismo", "revisión"]'),
('S70.919S', 'Traumatismo superficial no especificado de cadera no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela", "marca"]'),
('S70.921A', 'Traumatismo superficial no especificado de muslo derecho, contacto inicial', 'Sin especificar', '["lesión piel muslo derecho", "golpe pierna derecha", "traumatismo muslo derecho"]'),
('S70.921D', 'Traumatismo superficial no especificado de muslo derecho, contacto sucesivo', 'Sin especificar', '["seguimiento lesión muslo", "control traumatismo", "revisión"]'),
('S70.921S', 'Traumatismo superficial no especificado de muslo derecho, secuela', 'Sin especificar', '["cicatriz muslo", "secuela traumatismo", "marca piel"]'),
('S70.922A', 'Traumatismo superficial no especificado de muslo izquierdo, contacto inicial', 'Sin especificar', '["lesión muslo izquierdo", "traumatismo pierna izquierda", "golpe muslo"]'),
('S70.922D', 'Traumatismo superficial no especificado de muslo izquierdo, contacto sucesivo', 'Sin especificar', '["control lesión", "seguimiento traumatismo", "revisión"]'),
('S70.922S', 'Traumatismo superficial no especificado de muslo izquierdo, secuela', 'Sin especificar', '["cicatriz muslo", "secuela traumatismo", "marca piel"]'),
('S70.929A', 'Traumatismo superficial no especificado de muslo no especificado, contacto inicial', 'Sin especificar', '["traumatismo en el muslo", "lesión piel pierna", "golpe o roce"]'),
('S70.929D', 'Traumatismo superficial no especificado de muslo no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control traumatismo", "revisión"]'),
('S70.929S', 'Traumatismo superficial no especificado de muslo no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela", "marca"]');
