INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z93.0', 'Estado de traqueostomía', 'Sin especificar', '["traqueostomía", "traqueo", "agujero en el cuello", "tubo en la garganta", "canula de traqueostomía", "respirar por el cuello", "traqueotomizado", "estoma respiratorio", "incisión en la tráquea", "cánula traqueal", "apoyo ventilatorio por cuello", "traqueo artificial", "abertura en la tráquea", "traqueostomizado", "orificio para respirar"]'),
('Z93.1', 'Estado de gastrostomía', 'Sin especificar', '["gastrostomía", "gastro", "tubo en el estómago", "sonda de alimentación", "sonda gástrica", "boton gástrico", "nutrición por sonda", "comer por el estómago", "alimentación artificial", "estoma gástrico", "sonda peg", "sonda de gastrostomía", "operación de estomago para comer", "sonda en la panza", "sonda en la guata"]'),
('Z93.2', 'Estado de ileostomía', 'Sin especificar', '["ileostomía", "bolsa de ileostomía", "estoma en el intestino delgado", "ileostomizado", "bolsa de recolección intestinal", "cirugía de ileon", "salida intestinal", "intestino afuera", "bolsa colectora ileal", "orificio en el abdomen para desecho", "manejo de ileostomía", "estoma de descarga", "bolsita para el intestino", "ileostomía permanente"]'),
('Z93.3', 'Estado de colostomía', 'Sin especificar', '["colostomía", "bolsa de colostomía", "bolsa para la caca", "estoma de colon", "cirugía de colon", "bolsa recolectora", "intestino grueso afuera", "colostomizado", "orificio en la panza para defecar", "bolsita para el excremento", "estoma abdominal", "caca por bolsa", "evacuación por estoma", "manejo de colostomía", "bolsa de desecho"]'),
('Z93.4', 'Estado de otros estomas artificiales del tracto gastrointestinal', 'Sin especificar', '["estoma digestivo", "yeyunostomía", "estoma intestinal", "derivación intestinal", "operación de tripas", "abertura en el abdomen", "estoma artificial", "cirugía gastrointestinal", "salida de materia fecal", "apertura abdominal", "estoma de alimentación", "estoma de drenaje", "derivación digestiva", "problemas con el estoma", "bolsa de derivación"]'),
('Z93.50', 'Estado de cistostomía no especificado', 'Sin especificar', '["cistostomía", "sonda en la vejiga", "catéter vesical suprapúbico", "orificio para orinar", "sonda de cistostomía", "orinar por la panza", "vejiga conectada a bolsa", "catéter supra púbico", "derivación urinaria", "tubo para la orina", "cistostomía suprapúbica", "estoma urinario", "orificio en la vejiga", "drenaje de orina", "bolsa de orina por el abdomen"]'),
('Z93.51', 'Estado de vesicostomía cutánea', 'Sin especificar', '["vesicostomía", "vesicostomía cutánea", "abertura de la vejiga a la piel", "vejiga al exterior", "estoma vesical", "derivación de orina a la piel", "orinar por la piel", "vesicostomía cutánea", "estoma para orina", "cirugía de vejiga", "bolsa para orina abdominal", "orificio vesical", "salida de vejiga", "vesicostomía en niños", "vejiga abierta"]'),
('Z93.52', 'Estado de apendicovesicostomía', 'Sin especificar', '["apendicovesicostomía", "procedimiento de mitrofanoff", "apéndice para orinar", "canal artificial de orina", "reconstrucción urinaria", "cateterismo vesical por apéndice", "derivación urinaria compleja", "uso de apéndice en vejiga", "estoma para cateterismo", "orinar mediante apéndice", "cirugía reconstructiva urinaria", "vía urinaria artificial", "apendico-vesicostomía", "mitrofanoff", "cateterismo limpio"]'),
('Z93.59', 'Estado de otra cistostomía', 'Sin especificar', '["cistostomía adicional", "otras vías de cistostomía", "derivación vesical", "drenaje vesical permanente", "estoma de vejiga", "orificio de salida vesical", "sonda de drenaje vesical", "cirugía de estoma urinario", "abertura vesical", "catéter suprapúbico", "manejo de cistostomía", "acceso a la vejiga", "cistostomía alternativa", "drenaje urinario por pared abdominal", "vesicostomía"]'),
('Z93.6', 'Estado de otros estomas artificiales del tracto urinario', 'Sin especificar', '["urostomía", "estoma urinario", "conducto ileal", "bolsa de urostomía", "derivación urinaria", "orinar por bolsa", "ureterostomía", "nefrostomía", "bolsa de orina", "salida de orina por el abdomen", "cirugía de vías urinarias", "estoma en la guata para orinar", "estoma de orina", "colector de orina abdominal", "ureteroileostomía"]'),
('Z93.8', 'Otro estado de estoma artificial', 'Sin especificar', '["estoma diverso", "otro tipo de estoma", "abertura quirúrgica", "estoma de drenaje", "fístula artificial", "cirugía de estoma", "orificio de salida corporal", "estoma de alimentación o excreción", "complicaciones de estoma", "cuidado de estoma", "estoma no clasificado", "derivación de fluidos", "estoma de piel", "estoma de mucosas", "manejo de estomas"]'),
('Z93.9', 'Estado de estoma artificial, no especificado', 'Sin especificar', '["estoma", "bolsa de ostomía", "tengo un estoma", "operación con bolsa", "salida artificial", "estoma abdominal", "orificio de cirugía", "bolsita para desechos", "ostomizado", "paciente ostomizado", "estoma no definido", "derivación corporal", "abertura postquirúrgica", "manejo de bolsa", "cuidado del estoma"]');
