INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('I75.011', 'Ateroembolismo de extremidad superior derecha', 'Sin especificar', '["coágulo en brazo derecho", "trombo en brazo derecho", "arteria tapada brazo derecho", "embolia brazo derecho", "dolor brazo derecho", "brazo frío derecho", "brazo morado derecho", "falta de sangre en brazo derecho", "obstrucción vascular brazo derecho", "trombosis arterial brazo derecho", "infarto en brazo derecho", "problemas de circulación brazo derecho", "entumecimiento brazo derecho", "isquemia brazo derecho", "arterioesclerosis brazo derecho"]'),
('I75.012', 'Ateroembolismo de extremidad superior izquierda', 'Sin especificar', '["coágulo en brazo izquierdo", "trombo en brazo izquierdo", "arteria tapada brazo izquierdo", "embolia brazo izquierdo", "dolor brazo izquierdo", "brazo frío izquierdo", "brazo morado izquierdo", "falta de sangre en brazo izquierdo", "obstrucción vascular brazo izquierdo", "trombosis arterial brazo izquierdo", "infarto en brazo izquierdo", "problemas de circulación brazo izquierdo", "entumecimiento brazo izquierdo", "isquemia brazo izquierdo", "arterioesclerosis brazo izquierdo"]'),
('I75.013', 'Ateroembolismo bilateral de extremidades superiores', 'Sin especificar', '["coágulos en ambos brazos", "trombos en los dos brazos", "arterias tapadas en brazos", "embolia en ambos miembros superiores", "dolor en los dos brazos", "brazos fríos", "brazos morados", "falta de circulación en brazos", "obstrucción vascular bilateral brazos", "trombosis arterial en ambos brazos", "isquemia en ambos brazos", "problemas vasculares brazos", "hormigueo en ambos brazos", "arterioesclerosis en brazos", "mala circulación en los brazos"]'),
('I75.019', 'Ateroembolismo de extremidad superior no especificada', 'Sin especificar', '["coágulo en brazo", "trombo en brazo", "arteria tapada en brazo", "embolia en el brazo", "dolor de brazo por circulación", "brazo frío", "brazo entumido", "obstrucción de arteria en brazo", "trombosis en brazo", "problemas de circulación en brazo", "isquemia de miembro superior", "arterioesclerosis de brazo", "falta de riego sanguíneo en brazo", "dolor vascular brazo", "brazo morado"]'),
('I75.021', 'Ateroembolismo de extremidad inferior derecha', 'Sin especificar', '["coágulo en pierna derecha", "trombo en pierna derecha", "arteria tapada pierna derecha", "embolia pierna derecha", "dolor de pata derecha", "pierna fría derecha", "pierna morada", "falta de circulación pierna derecha", "obstrucción vascular pierna derecha", "trombosis arterial pierna derecha", "claudicación pierna derecha", "pie derecho frío", "isquemia pierna derecha", "arterioesclerosis pierna derecha", "pie con mala sangre"]'),
('I75.022', 'Ateroembolismo de extremidad inferior izquierda', 'Sin especificar', '["coágulo en pierna izquierda", "trombo en pierna izquierda", "arteria tapada pierna izquierda", "embolia pierna izquierda", "dolor de pata izquierda", "pierna fría izquierda", "pierna morada", "falta de circulación pierna izquierda", "obstrucción vascular pierna izquierda", "trombosis arterial pierna izquierda", "claudicación pierna izquierda", "pie izquierdo frío", "isquemia pierna izquierda", "arterioesclerosis pierna izquierda", "pie con mala sangre"]'),
('I75.023', 'Ateroembolismo bilateral de extremidades inferiores', 'Sin especificar', '["coágulos en las piernas", "trombos en ambas patas", "arterias tapadas piernas", "embolia en ambas piernas", "dolor en las dos piernas", "piernas frías", "piernas moradas", "mala circulación en piernas", "obstrucción vascular bilateral piernas", "trombosis arterial en las piernas", "isquemia en las piernas", "problemas de circulación en piernas", "claudicación intermitente", "arterioesclerosis en piernas", "falta de flujo sanguíneo en piernas"]'),
('I75.029', 'Ateroembolismo de extremidad inferior no especificada', 'Sin especificar', '["coágulo en pierna", "trombo en pierna", "arteria tapada en pierna", "embolia en pierna", "dolor de pierna por circulación", "pierna fría", "pierna entumida", "obstrucción de arteria en pierna", "trombosis en pierna", "problemas de circulación en pierna", "isquemia de miembro inferior", "arterioesclerosis de pierna", "falta de riego sanguíneo en pierna", "dolor vascular pierna", "pie morado"]'),
('I75.81', 'Ateroembolismo de riñón', 'Sin especificar', '["coágulo en el riñón", "trombo renal", "embolia renal", "infarto renal", "dolor de riñones por coágulo", "obstrucción arteria riñón", "fallo renal por coágulo", "trombosis de la arteria renal", "problemas de riñón por circulación", "isquemia renal", "arterioesclerosis renal", "dolor en la espalda por riñón", "orina con sangre por coágulo", "falla de riñón repentina", "obstrucción vascular en el riñón"]'),
('I75.89', 'Ateroembolismo de otra localización', 'Sin especificar', '["coágulo en órgano", "trombo en arteria", "embolia sistémica", "obstrucción arterial", "trombo que viajó", "trombosis arterial", "placa que se soltó", "arteria tapada", "problemas vasculares", "infarto por embolia", "isquemia en órgano", "obstrucción del flujo sanguíneo", "arterioesclerosis con desprendimiento", "coágulo en el cuerpo", "desprendimiento de ateroma"]');
