INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C7B.00', 'Tumores carcinoides secundarios, localización no especificada', 'Sin especificar', '["cáncer extendido", "metástasis", "tumor diseminado", "cáncer que se movió", "tumores neuroendocrinos", "neoplasia secundaria", "cáncer con metástasis", "células malignas", "tumores regados", "cáncer avanzado", "tumor secundario", "cáncer de origen desconocido", "nódulos cancerosos", "proliferación tumoral", "cáncer diseminado"]'),
('C7B.01', 'Tumores carcinoides secundarios de ganglios linfáticos a distancia', 'Sin especificar', '["ganglios inflamados", "bolitas en el cuello", "ganglios cancerosos", "metástasis ganglionar", "ganglios duros", "cáncer en los ganglios", "linfadenopatía maligna", "tumor en los ganglios", "nódulos linfáticos", "cáncer linfático secundario", "bultos en axilas", "ganglios que no bajan", "linfoma secundario", "inflamación ganglional", "metástasis a distancia"]'),
('C7B.02', 'Tumores carcinoides secundarios de hígado', 'Sin especificar', '["metástasis hepática", "cáncer en el hígado", "tumores en el hígado", "manchas en el hígado", "hígado con tumores", "hígado dañado por cáncer", "nódulos en el hígado", "cáncer avanzado hepático", "cáncer secundario de hígado", "dolor de hígado", "hígado inflamado", "cáncer del hígado metastásico", "tumores carcinoides hepáticos", "problemas de hígado", "masa en el hígado"]'),
('C7B.03', 'Tumores carcinoides secundarios de hueso', 'Sin especificar', '["cáncer en los huesos", "metástasis ósea", "dolor de huesos", "huesos débiles", "tumores óseos secundarios", "cáncer que carcome los huesos", "dolor punzante en huesos", "cáncer avanzado de hueso", "fracturas por cáncer", "nódulos en los huesos", "cáncer metastásico al hueso", "debilidad ósea", "dolor de cuerpo profundo", "lesiones óseas", "cáncer carcinoides óseo"]'),
('C7B.04', 'Tumores carcinoides secundarios de peritoneo', 'Sin especificar', '["cáncer en la panza", "tumores en el abdomen", "metástasis peritoneal", "cáncer de peritoneo", "líquido en la panza", "dolor de barriga persistente", "cáncer en el vientre", "inflamación abdominal", "tumores en la guata", "cáncer abdominal avanzado", "carcinomatosis peritoneal", "hinchazón abdominal", "dolor de guata", "masa abdominal", "cáncer de peritoneo secundario"]'),
('C7B.09', 'Tumores carcinoides secundarios de otras localizaciones', 'Sin especificar', '["cáncer en otras partes", "metástasis en otros órganos", "tumores diseminados", "cáncer avanzado no especificado", "focos cancerosos", "cáncer secundario", "tumores en el cuerpo", "neoplasia secundaria diseminada", "cáncer con ramificaciones", "células malignas secundarias", "cáncer que se extendió", "tumor metastásico múltiple", "nódulos tumorales", "cáncer en varios sitios", "cáncer sistémico"]'),
('C7B.1', 'Carcinoma secundario de células de Merkel', 'Sin especificar', '["cáncer de piel agresivo", "tumor de Merkel", "cáncer de Merkel metastásico", "carcinoma neuroendocrino de piel", "cáncer de piel avanzado", "mancha rara en la piel", "cáncer de células de Merkel", "tumor cutáneo secundario", "bulto en la piel", "cáncer maligno de piel", "metástasis de Merkel", "carcinoma de Merkel", "tumor dérmico", "cáncer cutáneo que se movió", "cáncer de Merkel diseminado"]'),
('C7B.8', 'Otros tumores neuroendocrinos secundarios', 'Sin especificar', '["tumores neuroendocrinos avanzados", "cáncer neuroendocrino con metástasis", "tumores en glándulas", "cáncer de glándulas", "tumores endocrinos secundarios", "cáncer que produce hormonas", "metástasis neuroendocrina", "cáncer secundario de origen neuroendocrino", "tumores raros", "crecimientos hormonales malignos", "cáncer endocrino", "tumores que se movieron", "cáncer maligno neuroendocrino", "tumores secundarios del sistema endocrino", "masa endocrina"]');
