INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N36.0', 'Fístula uretral', 'Sin especificar', '["fístula en la uretra", "agujero en el conducto de la orina", "salida de orina por lugar indebido", "fuga de orina", "comunicación anormal uretra", "incontinencia por fístula", "goteo constante de orina", "fisura en la uretra", "conducto urinario abierto", "orificio urinario extraño", "infección urinaria recurrente por fístula", "problemas para orinar", "dolor al orinar"]'),
('N36.1', 'Divertículo uretral', 'Sin especificar', '["bolsa en la uretra", "quiste en el conducto urinario", "abultamiento en la uretra", "saculaciones en uretra", "acumulación de orina en la uretra", "uretra dilatada", "orina estancada en uretra", "bulto al orinar", "infección urinaria persistente", "dolor uretra mujer", "goteo post-miccional", "inflamación de uretra", "saco en la uretra"]'),
('N36.2', 'Carúncula uretral', 'Sin especificar', '["bolita roja en la uretra", "crecimiento carnoso uretra", "tumoración benigna uretra", "protuberancia roja zona íntima", "dolor al orinar mujer", "ardor al hacer pis", "sangrado al orinar", "irritación en el meato", "carúncula en mujer", "lesión roja uretra", "molestias al tener relaciones", "inflamación del conducto de la orina", "bultito en la entrada de la orina"]'),
('N36.41', 'Hipermovilidad de uretra', 'Sin especificar', '["uretra que se mueve", "incontinencia de esfuerzo", "uretra inestable", "vejiga caída", "uretra floja", "se me escapa el pipí al toser", "fuga de orina al cargar peso", "uretra hiperlaxa", "debilidad del suelo pélvico", "incontinencia femenina", "problemas de sostén uretral", "uretra descolgada", "incontinencia al estornudar"]'),
('N36.42', 'Deficiencia intrínseca del esfínter (DIE)', 'Sin especificar', '["esfínter urinario débil", "no aguanto las ganas de orinar", "incontinencia por esfínter", "cierre uretral insuficiente", "falta de tono en esfínter", "escape de orina permanente", "esfínter que no cierra", "uretra abierta", "incontinencia severa", "problemas para retener la orina", "falla del esfínter", "incontinencia por deficiencia", "goteo de orina"]'),
('N36.43', 'Hipermovilidad de uretra y deficiencia intrínseca del esfínter combinadas', 'Sin especificar', '["incontinencia mixta", "uretra floja y esfínter débil", "doble problema urinario", "incontinencia severa de esfuerzo", "fuga total de orina", "no puedo retener el pis", "caída de vejiga y esfínter", "uretra inestable y abierta", "pérdida de orina crónica", "suelo pélvico colapsado", "problemas de uretra mixtos", "incontinencia al movimiento y esfuerzo", "urgencia y escape de orina"]'),
('N36.44', 'Trastornos musculares de uretra', 'Sin especificar', '["espasmo uretral", "uretra tensa", "músculo de la uretra contraído", "dolor al orinar", "corte del chorro urinario", "dificultad para orinar", "calambre en la uretra", "problemas musculares al hacer pis", "disfunción de la uretra", "espasmo en el conducto", "uretra espástica", "dificultad para relajar al orinar", "obstrucción funcional uretra"]'),
('N36.5', 'Vía uretral falsa', 'Sin especificar', '["falsa vía urinaria", "orificio falso en uretra", "daño en la uretra por sonda", "perforación de uretra", "lesión en el conducto urinario", "sangrado por la uretra", "dolor al meter sonda", "problemas al orinar por lesión", "falsa ruta al sondar", "herida en la uretra", "cicatriz uretra", "uretra lesionada", "complicación post-sondaje"]'),
('N36.8', 'Otros trastornos especificados de uretra', 'Sin especificar', '["problemas raros de uretra", "dolor en el conducto de la orina", "inflamación uretra", "uretritis rara", "picazón en la uretra", "ardor al hacer del baño", "molestias urinarias", "sensación extraña al orinar", "uretra sensible", "infecciones de uretra recurrentes", "irritación uretra", "trastornos uretrales", "malestar en el aparato urinario"]'),
('N36.9', 'Trastorno de uretra, no especificado', 'Sin especificar', '["problema en la uretra", "dolor al orinar sin causa", "molestia al hacer pis", "ardor urinario", "sangre en la orina", "no sé qué tengo al orinar", "dolor de vejiga y uretra", "enfermedad de la uretra", "problemas para hacer pipí", "picor urinario", "urgencia por orinar", "goteo uretral", "desconocido en el conducto de orina"]');
