INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S67.00XA', 'Lesión por aplastamiento de pulgar no especificado, contacto inicial', 'Sin especificar', '["pulgar aplastado", "dedo gordo machucado", "dedo gordo prensado", "aplastamiento de dedo", "dedo morado", "dedo hinchado", "traumatismo en el pulgar", "dedo espachurrado", "dedo accidentado", "urgencia dedo gordo", "golpe fuerte en el pulgar", "dedo magullado"]'),
('S67.00XD', 'Lesión por aplastamiento de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["control lesión pulgar", "seguimiento dedo gordo", "cura de dedo machucado", "revisión aplastamiento pulgar", "curación dedo gordo", "evolución de machucón", "tratamiento continuo pulgar", "cita de seguimiento dedo", "revisión de herida en pulgar"]'),
('S67.00XS', 'Lesión por aplastamiento de pulgar no especificado, secuela', 'Sin especificar', '["secuela aplastamiento pulgar", "dolor crónico pulgar", "dedo gordo rígido", "cicatriz por aplastamiento", "deformidad de dedo gordo", "dolor postraumático pulgar", "pérdida de movilidad pulgar", "secuelas de golpe en dedo"]'),
('S67.01XA', 'Lesión por aplastamiento de pulgar derecho, contacto inicial', 'Sin especificar', '["pulgar derecho machucado", "aplastamiento dedo gordo derecho", "golpe en el pulgar derecho", "dedo derecho prensado", "emergencia pulgar derecho", "dedo derecho hinchado", "accidente mano derecha pulgar"]'),
('S67.01XD', 'Lesión por aplastamiento de pulgar derecho, contacto sucesivo', 'Sin especificar', '["control pulgar derecho", "seguimiento dedo gordo mano derecha", "cura pulgar derecho", "revisión aplastamiento mano derecha"]'),
('S67.01XS', 'Lesión por aplastamiento de pulgar derecho, secuela', 'Sin especificar', '["secuela pulgar derecho", "rigidez pulgar derecho", "dolor crónico pulgar derecho", "deformidad postraumática pulgar derecho"]'),
('S67.02XA', 'Lesión por aplastamiento de pulgar izquierdo, contacto inicial', 'Sin especificar', '["pulgar izquierdo machucado", "aplastamiento dedo gordo izquierdo", "golpe en el pulgar izquierdo", "dedo izquierdo prensado", "emergencia pulgar izquierdo"]'),
('S67.02XD', 'Lesión por aplastamiento de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["control pulgar izquierdo", "seguimiento dedo gordo mano izquierda", "cura pulgar izquierdo", "revisión aplastamiento mano izquierda"]'),
('S67.02XS', 'Lesión por aplastamiento de pulgar izquierdo, secuela', 'Sin especificar', '["secuela pulgar izquierdo", "rigidez pulgar izquierdo", "dolor crónico pulgar izquierdo", "deformidad postraumática pulgar izquierdo"]'),
('S67.10XA', 'Lesión por aplastamiento de dedo(s) de la mano no especificado, contacto inicial', 'Sin especificar', '["dedo machucado", "dedos aplastados", "dedo prensado", "dedo espachurrado", "golpe en los dedos", "accidente en la mano", "dedo morado", "dedo hinchado", "trauma en dedos", "dedos machucados"]'),
('S67.10XD', 'Lesión por aplastamiento de dedo(s) de la mano no especificado, contacto sucesivo', 'Sin especificar', '["control dedos machucados", "seguimiento lesión dedos", "cura dedos", "revisión aplastamiento", "curación mano"]'),
('S67.10XS', 'Lesión por aplastamiento de dedo(s) de la mano no especificado, secuela', 'Sin especificar', '["secuela dedos", "dedo rígido", "cicatriz mano", "deformidad dedos", "dolor crónico manos"]'),
('S67.190A', 'Lesión por aplastamiento de dedo índice derecho, contacto inicial', 'Sin especificar', '["índice derecho machucado", "aplastamiento dedo índice mano derecha", "golpe dedo índice derecho", "dedo índice prensado"]'),
('S67.190D', 'Lesión por aplastamiento de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["control índice derecho", "seguimiento índice derecho", "cura índice derecho", "revisión aplastamiento índice"]'),
('S67.190S', 'Lesión por aplastamiento de dedo índice derecho, secuela', 'Sin especificar', '["secuela índice derecho", "rigidez índice derecho", "dolor crónico índice derecho"]'),
('S67.191A', 'Lesión por aplastamiento de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["índice izquierdo machucado", "aplastamiento dedo índice mano izquierda", "golpe dedo índice izquierdo", "dedo índice prensado"]'),
('S67.191D', 'Lesión por aplastamiento de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["control índice izquierdo", "seguimiento índice izquierdo", "cura índice izquierdo", "revisión aplastamiento índice"]'),
('S67.191S', 'Lesión por aplastamiento de dedo índice izquierdo, secuela', 'Sin especificar', '["secuela índice izquierdo", "rigidez índice izquierdo", "dolor crónico índice izquierdo"]'),
('S67.192A', 'Lesión por aplastamiento de dedo medio derecho, contacto inicial', 'Sin especificar', '["dedo medio derecho machucado", "corazón derecho aplastado", "golpe dedo cordial derecho"]'),
('S67.192D', 'Lesión por aplastamiento de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["control dedo medio derecho", "seguimiento dedo cordial derecho"]'),
('S67.192S', 'Lesión por aplastamiento de dedo medio derecho, secuela', 'Sin especificar', '["secuela dedo medio derecho", "rigidez dedo corazón derecho"]'),
('S67.193A', 'Lesión por aplastamiento de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["dedo medio izquierdo machucado", "corazón izquierdo aplastado", "golpe dedo cordial izquierdo"]'),
('S67.193D', 'Lesión por aplastamiento de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["control dedo medio izquierdo", "seguimiento dedo cordial izquierdo"]'),
('S67.193S', 'Lesión por aplastamiento de dedo medio izquierdo, secuela', 'Sin especificar', '["secuela dedo medio izquierdo", "rigidez dedo corazón izquierdo"]'),
('S67.194A', 'Lesión por aplastamiento de dedo anular derecho, contacto inicial', 'Sin especificar', '["anular derecho machucado", "dedo anular derecho prensado", "golpe en el anular derecho"]'),
('S67.194D', 'Lesión por aplastamiento de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["control anular derecho", "seguimiento dedo anular derecho"]'),
('S67.194S', 'Lesión por aplastamiento de dedo anular derecho, secuela', 'Sin especificar', '["secuela anular derecho", "rigidez anular derecho"]'),
('S67.195A', 'Lesión por aplastamiento de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["anular izquierdo machucado", "dedo anular izquierdo prensado", "golpe en el anular izquierdo"]'),
('S67.195D', 'Lesión por aplastamiento de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["control anular izquierdo", "seguimiento dedo anular izquierdo"]'),
('S67.195S', 'Lesión por aplastamiento de dedo anular izquierdo, secuela', 'Sin especificar', '["secuela anular izquierdo", "rigidez anular izquierdo"]'),
('S67.196A', 'Lesión por aplastamiento de dedo meñique derecho, contacto inicial', 'Sin especificar', '["meñique derecho machucado", "dedo chiquito derecho prensado", "golpe meñique derecho"]'),
('S67.196D', 'Lesión por aplastamiento de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["control meñique derecho", "seguimiento meñique derecho"]'),
('S67.196S', 'Lesión por aplastamiento de dedo meñique derecho, secuela', 'Sin especificar', '["secuela meñique derecho", "rigidez meñique derecho"]'),
('S67.197A', 'Lesión por aplastamiento de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["meñique izquierdo machucado", "dedo chiquito izquierdo prensado", "golpe meñique izquierdo"]'),
('S67.197D', 'Lesión por aplastamiento de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["control meñique izquierdo", "seguimiento meñique izquierdo"]'),
('S67.197S', 'Lesión por aplastamiento de dedo meñique izquierdo, secuela', 'Sin especificar', '["secuela meñique izquierdo", "rigidez meñique izquierdo"]'),
('S67.198A', 'Lesión por aplastamiento de otro dedo de mano, contacto inicial', 'Sin especificar', '["dedo extraño machucado", "golpe otro dedo", "lesión dedo adicional"]'),
('S67.198D', 'Lesión por aplastamiento de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["seguimiento dedo", "control lesión dedo"]'),
('S67.198S', 'Lesión por aplastamiento de otro dedo de mano, secuela', 'Sin especificar', '["secuela dedo", "dolor postraumático dedo"]'),
('S67.20XA', 'Lesión por aplastamiento de mano no especificada, contacto inicial', 'Sin especificar', '["mano aplastada", "mano prensada", "golpe fuerte en la mano", "mano machucada", "accidente mano", "urgencia mano"]'),
('S67.20XD', 'Lesión por aplastamiento de mano no especificada, contacto sucesivo', 'Sin especificar', '["control mano machucada", "curación mano", "revisión mano"]'),
('S67.20XS', 'Lesión por aplastamiento de mano no especificada, secuela', 'Sin especificar', '["secuela mano", "dolor crónico mano", "rigidez mano"]'),
('S67.21XA', 'Lesión por aplastamiento de mano derecha, contacto inicial', 'Sin especificar', '["mano derecha machucada", "golpe mano derecha", "mano derecha prensada"]'),
('S67.21XD', 'Lesión por aplastamiento de mano derecha, contacto sucesivo', 'Sin especificar', '["control mano derecha", "revisión mano derecha"]'),
('S67.21XS', 'Lesión por aplastamiento de mano derecha, secuela', 'Sin especificar', '["secuela mano derecha", "rigidez mano derecha"]'),
('S67.22XA', 'Lesión por aplastamiento de mano izquierda, contacto inicial', 'Sin especificar', '["mano izquierda machucada", "golpe mano izquierda", "mano izquierda prensada"]'),
('S67.22XD', 'Lesión por aplastamiento de mano izquierda, contacto sucesivo', 'Sin especificar', '["control mano izquierda", "revisión mano izquierda"]'),
('S67.22XS', 'Lesión por aplastamiento de mano izquierda, secuela', 'Sin especificar', '["secuela mano izquierda", "rigidez mano izquierda"]'),
('S67.30XA', 'Lesión por aplastamiento de muñeca no especificada, contacto inicial', 'Sin especificar', '["muñeca aplastada", "muñeca machucada", "golpe fuerte muñeca", "prensado de muñeca"]'),
('S67.30XD', 'Lesión por aplastamiento de muñeca no especificada, contacto sucesivo', 'Sin especificar', '["control muñeca", "seguimiento muñeca machucada"]'),
('S67.30XS', 'Lesión por aplastamiento de muñeca no especificada, secuela', 'Sin especificar', '["secuela muñeca", "muñeca rígida", "dolor crónico muñeca"]'),
('S67.31XA', 'Lesión por aplastamiento de muñeca derecha, contacto inicial', 'Sin especificar', '["muñeca derecha machucada", "golpe muñeca derecha"]'),
('S67.31XD', 'Lesión por aplastamiento de muñeca derecha, contacto sucesivo', 'Sin especificar', '["control muñeca derecha"]'),
('S67.31XS', 'Lesión por aplastamiento de muñeca derecha, secuela', 'Sin especificar', '["secuela muñeca derecha"]'),
('S67.32XA', 'Lesión por aplastamiento de muñeca izquierda, contacto inicial', 'Sin especificar', '["muñeca izquierda machucada", "golpe muñeca izquierda"]'),
('S67.32XD', 'Lesión por aplastamiento de muñeca izquierda, contacto sucesivo', 'Sin especificar', '["control muñeca izquierda"]'),
('S67.32XS', 'Lesión por aplastamiento de muñeca izquierda, secuela', 'Sin especificar', '["secuela muñeca izquierda"]'),
('S67.40XA', 'Lesión por aplastamiento de muñeca y mano no especificadas, contacto inicial', 'Sin especificar', '["muñeca y mano aplastada", "golpe en mano y muñeca"]'),
('S67.40XD', 'Lesión por aplastamiento de muñeca y mano no especificadas, contacto sucesivo', 'Sin especificar', '["control mano y muñeca"]'),
('S67.40XS', 'Lesión por aplastamiento de muñeca y mano no especificadas, secuela', 'Sin especificar', '["secuela mano y muñeca"]'),
('S67.41XA', 'Lesión por aplastamiento de muñeca y mano derecha, contacto inicial', 'Sin especificar', '["golpe mano derecha y muñeca"]'),
('S67.41XD', 'Lesión por aplastamiento de muñeca y mano derecha, contacto sucesivo', 'Sin especificar', '["control mano derecha y muñeca"]'),
('S67.41XS', 'Lesión por aplastamiento de muñeca y mano derecha, secuela', 'Sin especificar', '["secuela mano derecha y muñeca"]'),
('S67.42XA', 'Lesión por aplastamiento de muñeca y mano izquierda, contacto inicial', 'Sin especificar', '["golpe mano izquierda y muñeca"]'),
('S67.42XD', 'Lesión por aplastamiento de muñeca y mano izquierda, contacto sucesivo', 'Sin especificar', '["control mano izquierda y muñeca"]'),
('S67.42XS', 'Lesión por aplastamiento de muñeca y mano izquierda, secuela', 'Sin especificar', '["secuela mano izquierda y muñeca"]'),
('S67.90XA', 'Lesión por aplastamiento de parte(s) no especificada de muñeca, mano y dedos de la mano no especificadas, contacto inicial', 'Sin especificar', '["aplastamiento extremidad mano", "trauma grave mano"]'),
('S67.90XD', 'Lesión por aplastamiento de parte(s) no especificada de muñeca, mano y dedos de la mano no especificadas, contacto sucesivo', 'Sin especificar', '["seguimiento trauma mano"]'),
('S67.90XS', 'Lesión por aplastamiento de parte(s) no especificada de muñeca, mano y dedos de la mano no especificadas, secuela', 'Sin especificar', '["secuelas graves mano"]'),
('S67.91XA', 'Lesión por aplastamiento de parte(s) no especificada de muñeca, mano y dedos de mano, lado derecho, contacto inicial', 'Sin especificar', '["aplastamiento mano derecha grave"]'),
('S67.91XD', 'Lesión por aplastamiento de parte(s) no especificada de muñeca, mano y dedos de mano, lado derecho, contacto sucesivo', 'Sin especificar', '["control mano derecha grave"]'),
('S67.91XS', 'Lesión por aplastamiento de parte(s) no especificada de muñeca, mano y dedos de mano, lado derecho, secuela', 'Sin especificar', '["secuelas mano derecha grave"]'),
('S67.92XA', 'Lesión por aplastamiento de parte(s) no especificada de muñeca, mano y dedos de la mano, lado izquierdo, contacto inicial', 'Sin especificar', '["aplastamiento mano izquierda grave"]'),
('S67.92XD', 'Lesión por aplastamiento de parte(s) no especificada de muñeca, mano y dedos de la mano, lado izquierdo, contacto sucesivo', 'Sin especificar', '["control mano izquierda grave"]'),
('S67.92XS', 'Lesión por aplastamiento de parte(s) no especificada de muñeca, mano y dedos de la mano, lado izquierdo, secuela', 'Sin especificar', '["secuelas mano izquierda grave"]');
