INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('I74.01', 'Émbolo en silla de montar de aorta abdominal', 'Sin especificar', '["coágulo en la panza", "taponamiento aórtico", "trombo en la barriga", "dolor abdominal intenso", "obstrucción arterial grave", "infarto de vísceras", "isquemia mesentérica", "urgencia vascular", "coágulo aórtico", "dolor de guata agudo", "obstrucción de la aorta", "trombo en silla de montar", "dolor de tripa fuerte", "crisis vascular abdominal", "trombosis aórtica"]'),
('I74.09', 'Otra embolia y trombosis arterial de aorta abdominal', 'Sin especificar', '["coágulo en la aorta", "trombosis abdominal", "bloqueo de arteria estomacal", "dolor de barriga fuerte", "isquemia abdominal", "taponamiento arterial", "mala circulación en el abdomen", "dolor en el vientre", "trombo aórtico", "arteria tapada en la panza", "insuficiencia arterial abdominal", "obstrucción de arterias del abdomen", "dolor constante en la guata"]'),
('I74.10', 'Embolia y trombosis de partes no especificadas de aorta', 'Sin especificar', '["coágulo en la aorta", "trombo aórtico", "arteria tapada", "bloqueo de la aorta", "trombosis de la arteria principal", "obstrucción de la arteria mayor", "mala circulación arterial", "problema en la arteria aorta", "taponamiento aórtico", "infarto aórtico", "urgencia vascular", "arteria bloqueada", "embolia aórtica"]'),
('I74.11', 'Embolia y trombosis de aorta torácica', 'Sin especificar', '["dolor en el pecho", "coágulo en el tórax", "trombo en la aorta del pecho", "opresión en el pecho", "arteria torácica tapada", "obstrucción aórtica en el pecho", "trombosis de pecho", "pinchazos en el pecho", "infarto torácico", "dolor retroesternal", "urgencia cardiaca", "obstrucción en la caja torácica", "isquemia torácica"]'),
('I74.19', 'Embolia y trombosis de otras partes de aorta', 'Sin especificar', '["trombo en la aorta", "coágulo en la arteria principal", "bloqueo arterial", "taponamiento aórtico", "arteria tapada", "problemas vasculares", "obstrucción de arterias mayores", "mala circulación", "embolia de aorta", "trombosis arterial", "obstrucción de vaso principal", "isquemia sistémica", "coágulo sanguíneo"]'),
('I74.2', 'Embolia y trombosis de arterias de los miembros superiores', 'Sin especificar', '["brazo dormido", "mano fría", "dolor en el brazo", "coágulo en el brazo", "arteria del brazo tapada", "hormigueo en la mano", "trombosis en miembros superiores", "mala circulación en los brazos", "mano amoratada", "falta de pulso en el brazo", "brazo hinchado", "obstrucción arterial del brazo", "dolor en la extremidad superior", "isquemia del brazo"]'),
('I74.3', 'Embolia y trombosis de arterias de los miembros inferiores', 'Sin especificar', '["pierna dormida", "pie frío", "dolor en la pantorrilla", "claudicación", "trombo en la pierna", "obstrucción arterial de la pierna", "mala circulación en los pies", "dolor al caminar", "pierna hinchada", "pie morado", "trombosis en miembros inferiores", "falta de pulso en el pie", "isquemia de pierna", "pierna pesada", "calambre constante en la pierna"]'),
('I74.4', 'Embolia y trombosis de arterias de extremidades, no especificada', 'Sin especificar', '["arteria tapada en la extremidad", "coágulo en la pierna o brazo", "problema circulatorio grave", "trombosis arterial", "obstrucción vascular", "falta de riego sanguíneo", "dolor en el miembro", "isquemia periférica", "trombo en extremidades", "extremidad fría", "mala circulación general", "urgencia vascular", "arteria obstruida", "bloqueo sanguíneo"]'),
('I74.5', 'Embolia y trombosis de arteria ilíaca', 'Sin especificar', '["dolor en la ingle", "trombo en la pelvis", "coágulo en la arteria ilíaca", "dolor en la cadera", "mala circulación en la pelvis", "obstrucción arterial ilíaca", "dolor en la zona baja del abdomen", "isquemia de la arteria ilíaca", "problemas de riego en la pelvis", "dolor inguinal", "taponamiento arterial pélvico", "arteria tapada en la pelvis"]'),
('I74.8', 'Embolia y trombosis de otras arterias', 'Sin especificar', '["coágulo en arterias", "trombosis arterial", "arteria tapada", "bloqueo de vaso sanguíneo", "obstrucción arterial", "problema de circulación", "trombo vascular", "obstrucción de flujo sanguíneo", "isquemia arterial", "embolia de arteria", "arteria bloqueada", "taponamiento arterial", "enfermedad vascular"]'),
('I74.9', 'Embolia y trombosis de arteria no especificada', 'Sin especificar', '["arteria tapada", "coágulo sanguíneo", "trombosis", "problemas de circulación", "obstrucción arterial", "trombo", "bloqueo vascular", "embolia", "mala circulación", "infarto arterial", "isquemia", "taponamiento arterial", "obstrucción de un vaso", "dolor por falta de riego"]');
