INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q17.0', 'Oreja supernumeraria', 'Sin especificar', '["oreja extra", "oreja de más", "doble oreja", "apéndice preauricular", "tag en la oreja", "bolita en la oreja", "cartílago extra", "oreja accesoria", "oreja pequeña extra", "malformación en la oreja", "bulto frente a la oreja", "tercera oreja", "oreja duplicada", "politia"]'),
('Q17.1', 'Macrotia', 'Sin especificar', '["orejas grandes", "orejas muy grandes", "orejas gigantes", "orejas de soplillo", "orejas desproporcionadas", "orejas enormes", "crecimiento excesivo de orejas", "orejas muy anchas", "orejas muy largas", "macroorejas", "orejas de abanico", "orejas de Dumbo", "desarrollo excesivo del pabellón"]'),
('Q17.2', 'Microtia', 'Sin especificar', '["oreja pequeña", "oreja sin desarrollar", "oreja atrofiada", "oreja muy chiquita", "falta de oreja", "malformación de oreja", "oreja deforme", "oreja incompleta", "hipoplasia auricular", "oreja apenas formada", "oreja arrugada", "oreja diminuta", "problemas al oír", "ausencia parcial de oreja"]'),
('Q17.3', 'Otras deformidades del oído', 'Sin especificar', '["oreja rara", "deformidad auricular", "oreja torcida", "oreja plegada", "oreja puntiaguda", "oreja de elfo", "forma extraña en la oreja", "oreja malformada", "problemas congénitos en la oreja", "oreja hundida", "oreja rara congénita", "anomalía del pabellón", "oreja deformada"]'),
('Q17.4', 'Anomalía de posición de oído', 'Sin especificar', '["orejas bajas", "orejas caídas", "orejas fuera de lugar", "orejas mal posicionadas", "orejas asimétricas", "implantación baja de orejas", "orejas chuecas", "orejas a distinta altura", "posición rara de las orejas", "orejas muy arriba", "orejas muy abajo", "malformación de posición", "orejas desalineadas"]'),
('Q17.5', 'Oreja prominente', 'Sin especificar', '["orejas de soplillo", "orejas despegadas", "orejas separadas", "orejas paradas", "orejas hacia afuera", "orejas en abanico", "orejas de Dumbo", "orejas grandes y abiertas", "orejas proyectadas", "orejas que sobresalen", "orejas de pantalla", "orejas muy separadas de la cabeza", "orejas abiertas"]'),
('Q17.8', 'Otras malformaciones congénitas especificadas del oído', 'Sin especificar', '["defecto congénito en el oído", "problema de nacimiento en el oído", "malformación auditiva", "oreja extraña congénita", "anomalía en la oreja desde nacimiento", "deformidad específica del pabellón", "falta de conducto auditivo", "oreja cerrada", "atresia auditiva", "problema estructural del oído", "malformación de oído medio", "anomalía congénita auditiva"]'),
('Q17.9', 'Malformación congénita del oído, no especificada', 'Sin especificar', '["problema en la oreja al nacer", "anomalía de nacimiento en oído", "defecto en la oreja", "oreja rara", "malformación auditiva de nacimiento", "problema de orejas del bebé", "oreja que no se formó bien", "deformidad de oído no diagnosticada", "defecto auditivo congénito", "oreja diferente", "problema al oír congénito", "anomalía en el pabellón auricular"]');
