INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('R41.0', 'Desorientación, no especificada', 'Sin especificar', '["desubicado", "andar perdido", "no saber dónde estoy", "confusión mental", "estar desorientado", "despiste", "despistado", "atontado", "fuera de onda", "desubicación", "falta de orientación", "no saber qué día es", "desorientación", "estar perdido", "embotamiento"]'),
('R41.1', 'Amnesia anterógrada', 'Sin especificar', '["no poder crear recuerdos nuevos", "olvidar lo que acaba de pasar", "memoria a corto plazo fallando", "amnesia de fijación", "pérdida de memoria reciente", "olvido de hechos recientes", "no retener información nueva", "olvidos frecuentes", "lagunas mentales", "bloqueo de memoria", "falla en la memoria", "incapacidad de recordar eventos nuevos", "mente en blanco", "amnesia"]'),
('R41.2', 'Amnesia retrógrada', 'Sin especificar', '["olvidar el pasado", "pérdida de memoria antigua", "borrón del pasado", "no recordar quién soy", "amnesia de hechos pasados", "olvido de vivencias", "pérdida de recuerdos", "amnesia de evocación", "lagunas de memoria", "olvidar la vida anterior", "olvido de recuerdos lejanos", "bloqueo de recuerdos", "amnesia total", "no recordar nada de antes"]'),
('R41.3', 'Otra amnesia', 'Sin especificar', '["problemas de memoria", "olvidadizo", "pérdida de memoria", "lagunas mentales", "olvidar cosas", "mala memoria", "cabeza de chorlito", "se me va la onda", "se me va el avión", "falta de retentiva", "olvidos", "memoria frágil", "lapsos de memoria", "amnesia", "desmemoriado"]'),
('R41.4', 'Síndrome neurológico de inatención', 'Sin especificar', '["falta de atención", "no prestar atención", "desatención", "ignorar estímulos", "no ver de un lado", "síndrome de heminegligencia", "inconsciencia de un lado", "negligencia visual", "falta de foco", "distraído", "inconsciencia espacial", "falta de respuesta", "desconexión", "falta de atención selectiva", "inatención"]'),
('R41.81', 'Deterioro cognitivo relacionado con la edad', 'Sin especificar', '["vejez", "mala memoria por viejo", "se me olvidan las cosas por la edad", "deterioro senil", "mente cansada", "lapsos mentales propios de la edad", "pérdida de memoria senil", "envejecimiento cerebral", "despistes de viejo", "mente lenta", "falta de agilidad mental", "deterioro cognitivo leve", "olvidos seniles", "demencia incipiente", "memoria desgastada"]'),
('R41.82', 'Estado mental alterado, no especificado', 'Sin especificar', '["andar raro", "estado mental raro", "confusión", "comportamiento extraño", "mente alterada", "desvariar", "estar delirando", "locura temporal", "incoherencias", "hablar tonteras", "pérdida de conciencia", "estar fuera de sí", "obnubilación", "trastorno mental", "mente confundida"]'),
('R41.83', 'Capacidad intelectual límite', 'Sin especificar', '["inteligencia baja", "lento de aprendizaje", "dificultad para aprender", "lento para captar", "limítrofe", "déficit intelectual leve", "capacidad cognitiva disminuida", "bajo rendimiento mental", "poca agilidad mental", "dificultad cognitiva", "mente lenta", "retraso leve", "no entender rápido", "problemas de aprendizaje", "intelecto reducido"]'),
('R41.840', 'Déficit de atención y concentración', 'Sin especificar', '["falta de concentración", "no me puedo concentrar", "distraído", "mente dispersa", "dispersión", "no mantener la atención", "desatención", "cabeza en las nubes", "mente volada", "poca concentración", "no enfocar", "problemas de foco", "falta de atención", "disperso", "se me va el hilo"]'),
('R41.841', 'Déficit cognitivo de comunicación', 'Sin especificar', '["dificultad para hablar", "no poder expresarme", "problemas para comunicarse", "trabarse al hablar", "no me salen las palabras", "afasia leve", "dificultad de lenguaje", "trastorno del habla", "incoherencia verbal", "no encontrar las palabras", "dificultad comunicativa", "problemas para entender lo que me dicen", "disfasia", "barreras de comunicación", "no poder explicarme"]'),
('R41.842', 'Déficit visoespacial', 'Sin especificar', '["problemas para orientarse", "dificultad para calcular distancias", "chocarse con las cosas", "problemas de percepción espacial", "no calcular bien el espacio", "desorientación espacial", "confusión de derecha e izquierda", "torpeza espacial", "dificultad de ubicación", "no poder dibujar", "problemas para armar objetos", "dificultad visoespacial", "fallas de percepción", "perderse en lugares conocidos", "mala coordinación visual"]'),
('R41.843', 'Déficit psicomotor', 'Sin especificar', '["torpeza motriz", "movimientos lentos", "lentitud física", "falta de coordinación", "problemas motores", "descoordinación", "movimientos raros", "cuerpo lento", "reacción lenta", "lentitud psicomotora", "dificultad de movimiento", "torpeza", "falta de agilidad", "movimientos pesados", "descontrol motor"]'),
('R41.844', 'Déficit del lóbulo frontal y de las funciones ejecutivas', 'Sin especificar', '["problemas de juicio", "no poder planificar", "falta de control de impulsos", "dificultad para organizar", "conducta desinhibida", "mala toma de decisiones", "incapacidad de organizar ideas", "pérdida de iniciativa", "problemas de conducta", "falta de razonamiento", "dificultad para resolver problemas", "fallas en la planificación", "descontrol", "falta de criterio", "disfunción ejecutiva"]'),
('R41.85', 'Anosognosia', 'Sin especificar', '["no saber que estoy enfermo", "negar la enfermedad", "no darse cuenta del problema", "falta de conciencia de enfermedad", "no reconocer el déficit", "creer que estoy bien cuando no es así", "ceguera a la enfermedad", "negar los síntomas", "no ver mis errores", "falta de percepción de salud", "ignorancia de la dolencia", "no reconocer mis fallas", "inconsciencia del problema", "autonegar la enfermedad", "desconocimiento de la enfermedad"]'),
('R41.89', 'Otros síntomas y signos que afectan a las funciones cognitivas y la conciencia', 'Sin especificar', '["problemas mentales", "cosas raras en la cabeza", "cambios de personalidad", "fallas mentales", "trastornos cognitivos", "alteraciones del pensamiento", "confusión", "embotamiento mental", "niebla mental", "mente pesada", "mareo mental", "desconexión mental", "trastorno de la conciencia", "síntomas cognitivos", "cambios en la mente"]'),
('R41.9', 'Síntomas y signos no especificados que afectan a las funciones cognitivas y la conciencia', 'Sin especificar', '["no sé qué tengo", "problemas de mente", "andar extraño", "confusión general", "alteración desconocida", "síntomas mentales", "mente rara", "problema de conciencia", "no estar lúcido", "desorientación", "algo me pasa en la cabeza", "trastorno no definido", "falla cognitiva", "alteración cerebral", "problema mental indeterminado"]');
