INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('T16.1XXA', 'Cuerpo extraño en oído derecho, contacto inicial', 'Sin especificar', '["objeto en el oído", "algo metido en el oído", "tengo algo en la oreja", "tapón en el oído", "cuerpo extraño", "objeto extraño", "audición bloqueada", "oído derecho tapado", "insecto en el oído", "algodón atorado", "arena en el oído", "piedra en el oído", "dolor de oído por objeto", "cera obstruyendo", "obstrucción auditiva", "oído derecho", "urgencia otorrino"]'),
('T16.1XXD', 'Cuerpo extraño en oído derecho, contacto sucesivo', 'Sin especificar', '["seguimiento objeto en oído", "revisión oído derecho", "control cuerpo extraño oído", "todavía tengo algo en la oreja", "limpieza oído después de objeto", "dolor persistente oído derecho", "evaluación otorrino seguimiento", "curación oído", "oido no destapa", "molestia persistente oído", "cita control oído", "monitoreo oreja", "post extracción objeto"]'),
('T16.1XXS', 'Cuerpo extraño en oído derecho, secuela', 'Sin especificar', '["daño por cuerpo extraño", "secuela auditiva", "oído zumbando", "pérdida de audición", "cicatriz en el oído", "infección residual", "dolor post extracción", "oído sensible", "problemas de oído crónicos", "daño en tímpano", "oído tapado crónico", "rehabilitación auditiva", "molestia antigua en oído"]'),
('T16.2XXA', 'Cuerpo extraño en oído izquierdo, contacto inicial', 'Sin especificar', '["objeto en oído izquierdo", "algo en mi oreja izquierda", "oreja tapada", "tengo algo atorado", "cuerpo extraño izquierdo", "objeto raro en el oído", "oído bloqueado", "limpieza de oídos urgente", "bicho en el oído", "juguete en el oído", "cuenta en el oído", "taponamiento auditivo", "dolor agudo oído izquierdo", "sensación de cuerpo extraño"]'),
('T16.2XXD', 'Cuerpo extraño en oído izquierdo, contacto sucesivo', 'Sin especificar', '["revisión oído izquierdo", "seguimiento objeto oreja", "control médico oído", "segunda visita oído", "dolor continúa", "oído izquierdo inflamado", "monitoreo post obstrucción", "seguimiento otorrino", "limpieza de restos", "evaluación conducto auditivo", "revisión tras accidente"]'),
('T16.2XXS', 'Cuerpo extraño en oído izquierdo, secuela', 'Sin especificar', '["problema auditivo crónico", "secuela oído izquierdo", "oído sordo", "pitido en el oído", "acúfenos", "daño canal auditivo", "cicatrización oído", "molestias auditivas", "hipoacusia post traumática", "inflamación crónica", "oído delicado"]'),
('T16.9XXA', 'Cuerpo extraño en oído, oído no especificado, contacto inicial', 'Sin especificar', '["objeto en el oído", "cuerpo extraño auditivo", "tengo algo en la oreja", "oído tapado", "urgencia oído", "cuerpo extraño", "objeto atorado", "qué hacer si tengo algo en el oído", "bichos en el oído", "limpieza de oído profesional", "me entró algo a la oreja", "obstrucción de oído", "dolor de oreja"]'),
('T16.9XXD', 'Cuerpo extraño en oído, oído no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento oído", "cita control oído", "revisión oreja", "monitoreo médico", "dolor después de extracción", "curaciones otorrino", "inspección conducto", "chequeo auditivo", "evaluación de restos", "post tratamiento oído", "continuación atención otorrino"]'),
('T16.9XXS', 'Cuerpo extraño en oído, oído no especificado, secuela', 'Sin especificar', '["secuela auditiva", "daños en el oído", "problemas de audición", "acúfeno", "zumbido permanente", "disminución auditiva", "cicatriz canal auditivo", "oído zumbando", "pérdida parcial oído", "dolor crónico de oreja", "sensibilidad auditiva", "rehabilitación oído"]');
