INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S60.00XA', 'Contusión de dedo de mano no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe en el dedo", "dedo machucado", "dedo morado", "dedo hinchado", "traumatismo en el dedo", "me di un golpe", "dedo aplastado", "dolor en el dedo", "dedo negro", "dedo inflamado", "hematoma en el dedo", "dedo abollado", "dedo contuso", "golpe fuerte", "dedo lastimado"]'),
('S60.00XD', 'Contusión de dedo de mano no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["revisión de golpe en dedo", "seguimiento de dedo machucado", "control de dedo lastimado", "dedo todavía duele", "golpe en dedo evolución", "dolor persistente en dedo", "revisión médica de dedo", "evolución de contusión", "curación de dedo golpeado", "dolor en dedo tras golpe"]'),
('S60.00XS', 'Contusión de dedo de mano no especificado, sin daños en la uña, secuela', 'Sin especificar', '["dolor crónico en dedo", "dedo quedó mal tras golpe", "secuela de dedo machucado", "dedo rígido tras golpe", "problema en dedo por accidente", "complicación en dedo", "dolor después de contusión", "dedo sensible tras golpe", "cicatriz interna en dedo"]'),
('S60.011A', 'Contusión de pulgar derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe en el dedo gordo derecho", "pulgar machucado", "golpe en el pulgar", "pulgar hinchado", "dedo pulgar derecho lastimado", "pulgar adolorido", "me pegué en el dedo gordo"]'),
('S60.011D', 'Contusión de pulgar derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["control pulgar derecho", "seguimiento golpe pulgar", "revisión dedo gordo derecho", "evolución contusión pulgar", "dolor continuo pulgar derecho"]'),
('S60.011S', 'Contusión de pulgar derecho, sin daños en la uña, secuela', 'Sin especificar', '["secuela golpe pulgar", "dolor persistente pulgar", "pulgar rígido", "molestia vieja en el pulgar", "complicación pulgar derecho"]'),
('S60.012A', 'Contusión de pulgar izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe en el dedo gordo izquierdo", "pulgar izquierdo machucado", "pulgar adolorido mano izquierda", "me pegué en el pulgar izquierdo", "hinchazón dedo gordo izquierdo"]'),
('S60.012D', 'Contusión de pulgar izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["control pulgar izquierdo", "seguimiento golpe pulgar mano izquierda", "evolución de la contusión en pulgar izquierdo"]'),
('S60.012S', 'Contusión de pulgar izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["dolor crónico pulgar izquierdo", "secuela contusión pulgar izquierdo", "pulgar izquierdo entumecido por golpe viejo"]'),
('S60.019A', 'Contusión de pulgar no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe en el pulgar", "dedo gordo machucado", "traumatismo en el pulgar", "me golpeé el dedo gordo", "pulgar hinchado y morado"]'),
('S60.019D', 'Contusión de pulgar no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["revisión de pulgar", "seguimiento golpe dedo gordo", "control de contusión de pulgar", "dolor residual en pulgar"]'),
('S60.019S', 'Contusión de pulgar no especificado, sin daños en la uña, secuela', 'Sin especificar', '["molestias post-traumáticas pulgar", "dolor crónico en el dedo gordo", "secuela de machucón en pulgar"]'),
('S60.021A', 'Contusión de dedo índice derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe en el dedo índice derecho", "dedo señalador derecho machucado", "dedo índice hinchado", "golpe en dedo de apuntar"]'),
('S60.021D', 'Contusión de dedo índice derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["control dedo índice derecho", "seguimiento contusión índice derecho", "evolución de golpe en índice"]'),
('S60.021S', 'Contusión de dedo índice derecho, sin daños en la uña, secuela', 'Sin especificar', '["secuela golpe dedo índice", "dolor persistente índice derecho", "dedo índice rígido"]'),
('S60.022A', 'Contusión de dedo índice izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe en el índice izquierdo", "dedo índice mano izquierda lastimado", "índice izquierdo machucado"]'),
('S60.022D', 'Contusión de dedo índice izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento dedo índice izquierdo", "control de golpe en índice izquierdo", "evolución contusión mano izquierda"]'),
('S60.022S', 'Contusión de dedo índice izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["secuela dedo índice izquierdo", "dolor crónico índice izquierdo", "complicación golpe dedo izquierdo"]'),
('S60.029A', 'Contusión de dedo índice no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe en el dedo índice", "dedo índice machucado", "dedo índice inflamado", "traumatismo índice"]'),
('S60.029D', 'Contusión de dedo índice no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento dedo índice", "control contusión índice", "dolor al mover el dedo índice"]'),
('S60.029S', 'Contusión de dedo índice no especificado, sin daños en la uña, secuela', 'Sin especificar', '["dolor persistente índice", "secuela de golpe en índice", "dedo índice sensible tras golpe"]'),
('S60.031A', 'Contusión de dedo medio derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe en el dedo medio derecho", "dedo corazón derecho machucado", "golpe en el dedo mayor derecho"]'),
('S60.031D', 'Contusión de dedo medio derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["control dedo medio derecho", "seguimiento golpe dedo corazón derecho"]'),
('S60.031S', 'Contusión de dedo medio derecho, sin daños en la uña, secuela', 'Sin especificar', '["secuela dedo medio derecho", "dolor crónico en el dedo corazón"]'),
('S60.032A', 'Contusión de dedo medio izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe en dedo medio izquierdo", "dedo corazón izquierdo machucado", "golpe en dedo mayor izquierdo"]'),
('S60.032D', 'Contusión de dedo medio izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento dedo medio izquierdo", "revisión contusión dedo corazón"]'),
('S60.032S', 'Contusión de dedo medio izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["dolor persistente dedo medio izquierdo", "secuela golpe dedo mayor"]'),
('S60.039A', 'Contusión de dedo medio no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo medio", "dedo corazón machucado", "dedo mayor lastimado"]'),
('S60.039D', 'Contusión de dedo medio no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["control contusión dedo medio", "seguimiento dedo corazón"]'),
('S60.039S', 'Contusión de dedo medio no especificado, sin daños en la uña, secuela', 'Sin especificar', '["secuela dedo medio", "molestia crónica dedo mayor"]'),
('S60.041A', 'Contusión de dedo anular derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo anular derecho", "dedo del anillo derecho golpeado", "machucón dedo anular"]'),
('S60.041D', 'Contusión de dedo anular derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento dedo anular derecho", "revisión contusión anular"]'),
('S60.041S', 'Contusión de dedo anular derecho, sin daños en la uña, secuela', 'Sin especificar', '["secuela golpe anular", "dolor persistente anular derecho"]'),
('S60.042A', 'Contusión de dedo anular izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo anular izquierdo", "dedo del anillo izquierdo machucado"]'),
('S60.042D', 'Contusión de dedo anular izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["control anular izquierdo", "seguimiento golpe anular"]'),
('S60.042S', 'Contusión de dedo anular izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["secuela golpe dedo anular izquierdo", "dolor crónico anular"]'),
('S60.049A', 'Contusión de dedo anular no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo anular", "machucón dedo del anillo", "traumatismo anular"]'),
('S60.049D', 'Contusión de dedo anular no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento dedo anular", "evolución contusión anular"]'),
('S60.049S', 'Contusión de dedo anular no especificado, sin daños en la uña, secuela', 'Sin especificar', '["dolor persistente dedo anular", "secuela de contusión"]'),
('S60.051A', 'Contusión de dedo meñique derecho, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo meñique derecho", "dedo chiquito derecho machucado"]'),
('S60.051D', 'Contusión de dedo meñique derecho, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento meñique derecho", "revisión contusión meñique"]'),
('S60.051S', 'Contusión de dedo meñique derecho, sin daños en la uña, secuela', 'Sin especificar', '["secuela golpe meñique derecho", "dolor crónico meñique"]'),
('S60.052A', 'Contusión de dedo meñique izquierdo, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo meñique izquierdo", "dedo chiquito izquierdo lastimado"]'),
('S60.052D', 'Contusión de dedo meñique izquierdo, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["control meñique izquierdo", "seguimiento golpe meñique"]'),
('S60.052S', 'Contusión de dedo meñique izquierdo, sin daños en la uña, secuela', 'Sin especificar', '["secuela golpe dedo chiquito", "dolor persistente meñique"]'),
('S60.059A', 'Contusión de dedo meñique no especificado, sin daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo meñique", "machucón dedo chiquito"]'),
('S60.059D', 'Contusión de dedo meñique no especificado, sin daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento contusión meñique", "revisión golpe dedo"]'),
('S60.059S', 'Contusión de dedo meñique no especificado, sin daños en la uña, secuela', 'Sin especificar', '["secuela dedo meñique", "dolor crónico meñique"]'),
('S60.10XA', 'Contusión de dedo de mano no especificado, con daños en la uña, contacto inicial', 'Sin especificar', '["dedo machucado con uña rota", "uñero por golpe", "uña negra", "golpe en uña", "contusión con uña dañada", "uña herida por golpe"]'),
('S60.10XD', 'Contusión de dedo de mano no especificado, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento dedo con uña dañada", "revisión uña negra", "control evolución dedo y uña", "dolor de uña tras golpe"]'),
('S60.10XS', 'Contusión de dedo de mano no especificado, con daños en la uña, secuela', 'Sin especificar', '["deformidad de uña por golpe", "secuela uña dañada", "uña que no crece bien por golpe", "dolor crónico bajo uña"]'),
('S60.111A', 'Contusión de pulgar derecho, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe en pulgar derecho con uña rota", "uña pulgar derecho morada", "machucón pulgar con daño en uña"]'),
('S60.111D', 'Contusión de pulgar derecho, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña pulgar derecho", "control golpe pulgar con uña dañada"]'),
('S60.111S', 'Contusión de pulgar derecho, con daños en la uña, secuela', 'Sin especificar', '["secuela golpe uña pulgar derecho", "deformidad uña gorda derecha"]'),
('S60.112A', 'Contusión de pulgar izquierdo, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe pulgar izquierdo con uña dañada", "uña pulgar izquierdo negra", "machucón dedo gordo izquierdo"]'),
('S60.112D', 'Contusión de pulgar izquierdo, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña pulgar izquierdo", "revisión golpe pulgar izquierdo"]'),
('S60.112S', 'Contusión de pulgar izquierdo, con daños en la uña, secuela', 'Sin especificar', '["secuela uña pulgar izquierdo", "uña estropeada por golpe"]'),
('S60.119A', 'Contusión de pulgar no especificado, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe pulgar con uña dañada", "uña negra dedo gordo", "machucón pulgar"]'),
('S60.119D', 'Contusión de pulgar no especificado, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña pulgar", "revisión contusión dedo gordo"]'),
('S60.119S', 'Contusión de pulgar no especificado, con daños en la uña, secuela', 'Sin especificar', '["secuela uña pulgar", "problema uña gorda por trauma"]'),
('S60.121A', 'Contusión de dedo índice derecho, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe índice derecho con uña rota", "uña índice derecho negra"]'),
('S60.121D', 'Contusión de dedo índice derecho, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña índice derecho", "revisión golpe índice"]'),
('S60.121S', 'Contusión de dedo índice derecho, con daños en la uña, secuela', 'Sin especificar', '["secuela uña índice derecho", "daño crónico uña índice"]'),
('S60.122A', 'Contusión de dedo índice izquierdo, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe índice izquierdo con uña dañada", "uña índice izquierdo morada"]'),
('S60.122D', 'Contusión de dedo índice izquierdo, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña índice izquierdo", "control golpe índice izquierdo"]'),
('S60.122S', 'Contusión de dedo índice izquierdo, con daños en la uña, secuela', 'Sin especificar', '["secuela uña índice izquierdo", "deformidad uña índice"]'),
('S60.129A', 'Contusión de dedo índice no especificado, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo índice con uña dañada", "uña negra índice"]'),
('S60.129D', 'Contusión de dedo índice no especificado, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña índice", "control contusión uña"]'),
('S60.129S', 'Contusión de dedo índice no especificado, con daños en la uña, secuela', 'Sin especificar', '["secuela uña índice", "daño crónico uña"]'),
('S60.131A', 'Contusión de dedo medio derecho, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo medio derecho con uña rota", "uña corazón derecho negra"]'),
('S60.131D', 'Contusión de dedo medio derecho, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña dedo medio derecho", "revisión golpe dedo"]'),
('S60.131S', 'Contusión de dedo medio derecho, con daños en la uña, secuela', 'Sin especificar', '["secuela uña dedo medio derecho", "daño persistente uña"]'),
('S60.132A', 'Contusión de dedo medio izquierdo, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo medio izquierdo con uña dañada", "uña corazón izquierdo negra"]'),
('S60.132D', 'Contusión de dedo medio izquierdo, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña dedo medio izquierdo", "control golpe uña"]'),
('S60.132S', 'Contusión de dedo medio izquierdo, con daños en la uña, secuela', 'Sin especificar', '["secuela uña dedo medio izquierdo", "problema uña corazón"]'),
('S60.139A', 'Contusión de dedo medio no especificado, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo medio con uña dañada", "uña negra medio"]'),
('S60.139D', 'Contusión de dedo medio no especificado, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña dedo medio", "control golpe medio"]'),
('S60.139S', 'Contusión de dedo medio no especificado, con daños en la uña, secuela', 'Sin especificar', '["secuela uña dedo medio", "daño crónico uña"]'),
('S60.141A', 'Contusión de dedo anular derecho, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo anular derecho con uña rota", "uña anular derecho negra"]'),
('S60.141D', 'Contusión de dedo anular derecho, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña anular derecho", "control golpe uña"]'),
('S60.141S', 'Contusión de dedo anular derecho, con daños en la uña, secuela', 'Sin especificar', '["secuela uña anular derecho", "daño uña"]'),
('S60.142A', 'Contusión de dedo anular izquierdo, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo anular izquierdo con uña dañada", "uña anular izquierdo negra"]'),
('S60.142D', 'Contusión de dedo anular izquierdo, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña anular izquierdo", "control golpe uña"]'),
('S60.142S', 'Contusión de dedo anular izquierdo, con daños en la uña, secuela', 'Sin especificar', '["secuela uña anular izquierdo", "daño persistente uña"]'),
('S60.149A', 'Contusión de dedo anular no especificado, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo anular con uña dañada", "uña anular negra"]'),
('S60.149D', 'Contusión de dedo anular no especificado, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña anular", "control golpe"]'),
('S60.149S', 'Contusión de dedo anular no especificado, con daños en la uña, secuela', 'Sin especificar', '["secuela uña anular", "daño uña"]'),
('S60.151A', 'Contusión de dedo meñique derecho, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo meñique derecho con uña rota", "uña meñique derecho negra"]'),
('S60.151D', 'Contusión de dedo meñique derecho, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña meñique derecho", "control golpe uña"]'),
('S60.151S', 'Contusión de dedo meñique derecho, con daños en la uña, secuela', 'Sin especificar', '["secuela uña meñique derecho", "daño crónico"]'),
('S60.152A', 'Contusión de dedo meñique izquierdo, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo meñique izquierdo con uña dañada", "uña meñique izquierdo negra"]'),
('S60.152D', 'Contusión de dedo meñique izquierdo, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña meñique izquierdo", "control golpe uña"]'),
('S60.152S', 'Contusión de dedo meñique izquierdo, con daños en la uña, secuela', 'Sin especificar', '["secuela uña meñique izquierdo", "daño uña"]'),
('S60.159A', 'Contusión de dedo meñique no especificado, con daños en la uña, contacto inicial', 'Sin especificar', '["golpe dedo meñique con uña dañada", "uña meñique negra"]'),
('S60.159D', 'Contusión de dedo meñique no especificado, con daños en la uña, contacto sucesivo', 'Sin especificar', '["seguimiento uña meñique", "control golpe uña"]'),
('S60.159S', 'Contusión de dedo meñique no especificado, con daños en la uña, secuela', 'Sin especificar', '["secuela uña meñique", "daño uña"]'),
('S60.211A', 'Contusión de muñeca derecha, contacto inicial', 'Sin especificar', '["golpe en la muñeca derecha", "muñeca hinchada", "traumatismo muñeca derecha", "me golpeé la muñeca"]'),
('S60.211D', 'Contusión de muñeca derecha, contacto sucesivo', 'Sin especificar', '["control muñeca derecha", "seguimiento golpe muñeca", "dolor muñeca derecha"]'),
('S60.211S', 'Contusión de muñeca derecha, secuela', 'Sin especificar', '["secuela golpe muñeca", "dolor crónico muñeca"]'),
('S60.212A', 'Contusión de muñeca izquierda, contacto inicial', 'Sin especificar', '["golpe muñeca izquierda", "traumatismo muñeca izquierda", "muñeca morada"]'),
('S60.212D', 'Contusión de muñeca izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento muñeca izquierda", "control golpe muñeca"]'),
('S60.212S', 'Contusión de muñeca izquierda, secuela', 'Sin especificar', '["secuela golpe muñeca", "dolor persistente muñeca"]'),
('S60.219A', 'Contusión de muñeca no especificada, contacto inicial', 'Sin especificar', '["golpe muñeca", "traumatismo muñeca", "muñeca lastimada"]'),
('S60.219D', 'Contusión de muñeca no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento muñeca", "control contusión"]'),
('S60.219S', 'Contusión de muñeca no especificada, secuela', 'Sin especificar', '["secuela contusión muñeca", "dolor crónico muñeca"]'),
('S60.221A', 'Contusión de mano derecha, contacto inicial', 'Sin especificar', '["golpe mano derecha", "mano hinchada", "traumatismo mano derecha"]'),
('S60.221D', 'Contusión de mano derecha, contacto sucesivo', 'Sin especificar', '["seguimiento mano derecha", "control golpe mano"]'),
('S60.221S', 'Contusión de mano derecha, secuela', 'Sin especificar', '["secuela golpe mano derecha", "dolor crónico mano"]'),
('S60.222A', 'Contusión de mano izquierda, contacto inicial', 'Sin especificar', '["golpe mano izquierda", "traumatismo mano izquierda"]'),
('S60.222D', 'Contusión de mano izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento mano izquierda", "control contusión"]'),
('S60.222S', 'Contusión de mano izquierda, secuela', 'Sin especificar', '["secuela golpe mano izquierda", "dolor crónico"]'),
('S60.229A', 'Contusión de mano no especificada, contacto inicial', 'Sin especificar', '["golpe mano", "traumatismo mano", "mano lastimada"]'),
('S60.229D', 'Contusión de mano no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento mano", "control contusión mano"]'),
('S60.229S', 'Contusión de mano no especificada, secuela', 'Sin especificar', '["secuela golpe mano", "dolor persistente"]'),
('S60.311A', 'Abrasión de pulgar derecho, contacto inicial', 'Sin especificar', '["raspón pulgar derecho", "pulgar pelado", "rasguño dedo gordo", "me raspé el pulgar"]'),
('S60.311D', 'Abrasión de pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento raspón pulgar", "curación pulgar", "revisión rasguño"]'),
('S60.311S', 'Abrasión de pulgar derecho, secuela', 'Sin especificar', '["cicatriz raspón pulgar", "secuela rasguño"]'),
('S60.312A', 'Abrasión de pulgar izquierdo, contacto inicial', 'Sin especificar', '["raspón pulgar izquierdo", "rasguño dedo gordo izquierdo"]'),
('S60.312D', 'Abrasión de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento raspón pulgar izquierdo", "curación"]'),
('S60.312S', 'Abrasión de pulgar izquierdo, secuela', 'Sin especificar', '["cicatriz pulgar izquierdo", "secuela"]'),
('S60.319A', 'Abrasión de pulgar no especificado, contacto inicial', 'Sin especificar', '["raspón pulgar", "rasguño pulgar"]'),
('S60.319D', 'Abrasión de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.319S', 'Abrasión de pulgar no especificado, secuela', 'Sin especificar', '["cicatriz pulgar", "secuela"]'),
('S60.321A', 'Ampolla (no térmica) de pulgar derecho, contacto inicial', 'Sin especificar', '["burbuja pulgar", "ampolla pulgar", "rozadura pulgar derecho"]'),
('S60.321D', 'Ampolla (no térmica) de pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla pulgar", "revisión"]'),
('S60.321S', 'Ampolla (no térmica) de pulgar derecho, secuela', 'Sin especificar', '["cicatriz ampolla pulgar", "secuela"]'),
('S60.322A', 'Ampolla (no térmica) de pulgar izquierdo, contacto inicial', 'Sin especificar', '["ampolla pulgar izquierdo", "rozadura"]'),
('S60.322D', 'Ampolla (no térmica) de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla pulgar izquierdo", "revisión"]'),
('S60.322S', 'Ampolla (no térmica) de pulgar izquierdo, secuela', 'Sin especificar', '["cicatriz ampolla", "secuela"]'),
('S60.329A', 'Ampolla (no térmica) de pulgar no especificado, contacto inicial', 'Sin especificar', '["ampolla en el pulgar", "burbuja por roce"]'),
('S60.329D', 'Ampolla (no térmica) de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.329S', 'Ampolla (no térmica) de pulgar no especificado, secuela', 'Sin especificar', '["cicatriz ampolla", "secuela"]'),
('S60.341A', 'Constricción externa de pulgar derecho, contacto inicial', 'Sin especificar', '["pulgar apretado", "anillo apretado pulgar", "algo ajustado en pulgar"]'),
('S60.341D', 'Constricción externa de pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento constricción pulgar", "revisión"]'),
('S60.341S', 'Constricción externa de pulgar derecho, secuela', 'Sin especificar', '["secuela constricción pulgar", "daño por presión"]'),
('S60.342A', 'Constricción externa de pulgar izquierdo, contacto inicial', 'Sin especificar', '["pulgar izquierdo apretado", "anillo constriñendo pulgar"]'),
('S60.342D', 'Constricción externa de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento constricción pulgar izquierdo", "control"]'),
('S60.342S', 'Constricción externa de pulgar izquierdo, secuela', 'Sin especificar', '["secuela constricción", "daño"]'),
('S60.349A', 'Constricción externa de pulgar no especificado, contacto inicial', 'Sin especificar', '["pulgar constreñido", "presión en pulgar"]'),
('S60.349D', 'Constricción externa de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.349S', 'Constricción externa de pulgar no especificado, secuela', 'Sin especificar', '["secuela constricción", "lesión"]'),
('S60.351A', 'Cuerpo extraño superficial de pulgar derecho, contacto inicial', 'Sin especificar', '["espina en pulgar", "astilla pulgar derecho", "vidrio en el dedo", "tengo algo clavado en el pulgar"]'),
('S60.351D', 'Cuerpo extraño superficial de pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento astilla pulgar", "revisión cuerpo extraño"]'),
('S60.351S', 'Cuerpo extraño superficial de pulgar derecho, secuela', 'Sin especificar', '["secuela cuerpo extraño", "cicatriz por astilla"]'),
('S60.352A', 'Cuerpo extraño superficial de pulgar izquierdo, contacto inicial', 'Sin especificar', '["espina pulgar izquierdo", "astilla en pulgar izquierdo"]'),
('S60.352D', 'Cuerpo extraño superficial de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.352S', 'Cuerpo extraño superficial de pulgar izquierdo, secuela', 'Sin especificar', '["cicatriz por astilla", "secuela"]'),
('S60.359A', 'Cuerpo extraño superficial de pulgar no especificado, contacto inicial', 'Sin especificar', '["espina en el pulgar", "astilla en el dedo"]'),
('S60.359D', 'Cuerpo extraño superficial de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "control"]'),
('S60.359S', 'Cuerpo extraño superficial de pulgar no especificado, secuela', 'Sin especificar', '["cicatriz por astilla", "secuela"]'),
('S60.361A', 'Picadura de insecto (no venenoso) en pulgar derecho, contacto inicial', 'Sin especificar', '["picadura en el pulgar", "roncha en pulgar derecho", "me picó un bicho en el dedo"]'),
('S60.361D', 'Picadura de insecto (no venenoso) en pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "revisión roncha"]'),
('S60.361S', 'Picadura de insecto (no venenoso) en pulgar derecho, secuela', 'Sin especificar', '["cicatriz picadura", "secuela"]'),
('S60.362A', 'Picadura de insecto (no venenoso) en pulgar izquierdo, contacto inicial', 'Sin especificar', '["picadura pulgar izquierdo", "bichito en pulgar"]'),
('S60.362D', 'Picadura de insecto (no venenoso) en pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.362S', 'Picadura de insecto (no venenoso) en pulgar izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.369A', 'Picadura de insecto (no venenoso) en pulgar no especificado, contacto inicial', 'Sin especificar', '["picadura en pulgar", "bicho en el dedo"]'),
('S60.369D', 'Picadura de insecto (no venenoso) en pulgar no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.369S', 'Picadura de insecto (no venenoso) en pulgar no especificado, secuela', 'Sin especificar', '["secuela", "cicatriz"]'),
('S60.371A', 'Otra mordedura superficial de pulgar derecho, contacto inicial', 'Sin especificar', '["mordida en pulgar derecho", "me mordió un animal el dedo"]'),
('S60.371D', 'Otra mordedura superficial de pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "curación"]'),
('S60.371S', 'Otra mordedura superficial de pulgar derecho, secuela', 'Sin especificar', '["cicatriz mordedura", "secuela"]'),
('S60.372A', 'Otra mordedura superficial de pulgar izquierdo, contacto inicial', 'Sin especificar', '["mordida pulgar izquierdo", "me mordió algo"]'),
('S60.372D', 'Otra mordedura superficial de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento mordida", "curación"]'),
('S60.372S', 'Otra mordedura superficial de pulgar izquierdo, secuela', 'Sin especificar', '["cicatriz mordedura", "secuela"]'),
('S60.379A', 'Otra mordedura superficial de pulgar no especificado, contacto inicial', 'Sin especificar', '["mordedura en pulgar", "mordisco en dedo"]'),
('S60.379D', 'Otra mordedura superficial de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "curación"]'),
('S60.379S', 'Otra mordedura superficial de pulgar no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.391A', 'Otros traumatismos superficiales de pulgar derecho, contacto inicial', 'Sin especificar', '["herida superficial pulgar derecho", "corte pequeño pulgar"]'),
('S60.391D', 'Otros traumatismos superficiales de pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento herida", "curación"]'),
('S60.391S', 'Otros traumatismos superficiales de pulgar derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.392A', 'Otros traumatismos superficiales de pulgar izquierdo, contacto inicial', 'Sin especificar', '["herida superficial pulgar izquierdo", "corte"]'),
('S60.392D', 'Otros traumatismos superficiales de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento herida", "curación"]'),
('S60.392S', 'Otros traumatismos superficiales de pulgar izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.399A', 'Otros traumatismos superficiales de pulgar no especificado, contacto inicial', 'Sin especificar', '["herida superficial pulgar", "corte en dedo"]'),
('S60.399D', 'Otros traumatismos superficiales de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento herida", "curación"]'),
('S60.399S', 'Otros traumatismos superficiales de pulgar no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.410A', 'Abrasión de dedo índice derecho, contacto inicial', 'Sin especificar', '["raspón índice derecho", "rasguño índice"]'),
('S60.410D', 'Abrasión de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["seguimiento raspón índice", "curación"]'),
('S60.410S', 'Abrasión de dedo índice derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.411A', 'Abrasión de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["raspón índice izquierdo", "rasguño"]'),
('S60.411D', 'Abrasión de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.411S', 'Abrasión de dedo índice izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.412A', 'Abrasión de dedo medio derecho, contacto inicial', 'Sin especificar', '["raspón dedo medio derecho", "rasguño dedo corazón"]'),
('S60.412D', 'Abrasión de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.412S', 'Abrasión de dedo medio derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.413A', 'Abrasión de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["raspón dedo medio izquierdo", "rasguño"]'),
('S60.413D', 'Abrasión de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.413S', 'Abrasión de dedo medio izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.414A', 'Abrasión de dedo anular derecho, contacto inicial', 'Sin especificar', '["raspón anular derecho", "rasguño dedo anular"]'),
('S60.414D', 'Abrasión de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.414S', 'Abrasión de dedo anular derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.415A', 'Abrasión de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["raspón anular izquierdo", "rasguño"]'),
('S60.415D', 'Abrasión de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.415S', 'Abrasión de dedo anular izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.416A', 'Abrasión de dedo meñique derecho, contacto inicial', 'Sin especificar', '["raspón meñique derecho", "rasguño chiquito"]'),
('S60.416D', 'Abrasión de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.416S', 'Abrasión de dedo meñique derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.417A', 'Abrasión de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["raspón meñique izquierdo", "rasguño"]'),
('S60.417D', 'Abrasión de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.417S', 'Abrasión de dedo meñique izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.418A', 'Abrasión de dedo de mano (salvo pulgar), contacto inicial', 'Sin especificar', '["raspón en dedo", "rasguño en mano"]'),
('S60.418D', 'Abrasión de dedo de mano (salvo pulgar), contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.418S', 'Abrasión de dedo de mano (salvo pulgar), secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.419A', 'Abrasión de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["raspón en dedo", "rasguño"]'),
('S60.419D', 'Abrasión de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.419S', 'Abrasión de dedo de mano no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.420A', 'Ampolla (no térmica) de dedo índice derecho, contacto inicial', 'Sin especificar', '["ampolla dedo índice derecho", "burbuja mano"]'),
('S60.420D', 'Ampolla (no térmica) de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.420S', 'Ampolla (no térmica) de dedo índice derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.421A', 'Ampolla (no térmica) de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["ampolla dedo índice izquierdo", "rozadura"]'),
('S60.421D', 'Ampolla (no térmica) de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.421S', 'Ampolla (no térmica) de dedo índice izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.422A', 'Ampolla (no térmica) de dedo medio derecho, contacto inicial', 'Sin especificar', '["ampolla dedo medio derecho", "ampolla dedo corazón"]'),
('S60.422D', 'Ampolla (no térmica) de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.422S', 'Ampolla (no térmica) de dedo medio derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.423A', 'Ampolla (no térmica) de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["ampolla dedo medio izquierdo", "ampolla corazón"]'),
('S60.423D', 'Ampolla (no térmica) de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.423S', 'Ampolla (no térmica) de dedo medio izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.424A', 'Ampolla (no térmica) de dedo anular derecho, contacto inicial', 'Sin especificar', '["ampolla anular derecho", "rozadura"]'),
('S60.424D', 'Ampolla (no térmica) de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.424S', 'Ampolla (no térmica) de dedo anular derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.425A', 'Ampolla (no térmica) de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["ampolla anular izquierdo", "rozadura"]'),
('S60.425D', 'Ampolla (no térmica) de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.425S', 'Ampolla (no térmica) de dedo anular izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.426A', 'Ampolla (no térmica) de dedo meñique derecho, contacto inicial', 'Sin especificar', '["ampolla meñique derecho", "rozadura"]'),
('S60.426D', 'Ampolla (no térmica) de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.426S', 'Ampolla (no térmica) de dedo meñique derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.427A', 'Ampolla (no térmica) de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["ampolla meñique izquierdo", "rozadura"]'),
('S60.427D', 'Ampolla (no térmica) de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.427S', 'Ampolla (no térmica) de dedo meñique izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.428A', 'Ampolla (no térmica) de otro dedo de mano, contacto inicial', 'Sin especificar', '["ampolla en el dedo", "rozadura"]'),
('S60.428D', 'Ampolla (no térmica) de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.428S', 'Ampolla (no térmica) de otro dedo de mano, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.429A', 'Ampolla (no térmica) de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["ampolla en el dedo", "burbuja"]'),
('S60.429D', 'Ampolla (no térmica) de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.429S', 'Ampolla (no térmica) de dedo de mano no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.440A', 'Constricción externa de dedo índice derecho, contacto inicial', 'Sin especificar', '["dedo índice apretado", "anillo constriñendo índice"]'),
('S60.440D', 'Constricción externa de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.440S', 'Constricción externa de dedo índice derecho, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.441A', 'Constricción externa de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["dedo índice apretado", "anillo"]'),
('S60.441D', 'Constricción externa de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.441S', 'Constricción externa de dedo índice izquierdo, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.442A', 'Constricción externa de dedo medio derecho, contacto inicial', 'Sin especificar', '["dedo medio apretado", "anillo"]'),
('S60.442D', 'Constricción externa de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.442S', 'Constricción externa de dedo medio derecho, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.443A', 'Constricción externa de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["dedo medio apretado", "anillo"]'),
('S60.443D', 'Constricción externa de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.443S', 'Constricción externa de dedo medio izquierdo, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.444A', 'Constricción externa de dedo anular derecho, contacto inicial', 'Sin especificar', '["anillo en anular apretado", "dedo constreñido"]'),
('S60.444D', 'Constricción externa de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.444S', 'Constricción externa de dedo anular derecho, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.445A', 'Constricción externa de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["anillo en anular apretado", "dedo constreñido"]'),
('S60.445D', 'Constricción externa de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.445S', 'Constricción externa de dedo anular izquierdo, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.446A', 'Constricción externa de dedo meñique derecho, contacto inicial', 'Sin especificar', '["meñique apretado", "constricción"]'),
('S60.446D', 'Constricción externa de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.446S', 'Constricción externa de dedo meñique derecho, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.447A', 'Constricción externa de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["meñique apretado", "constricción"]'),
('S60.447D', 'Constricción externa de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.447S', 'Constricción externa de dedo meñique izquierdo, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.448A', 'Constricción externa de otro dedo de mano, contacto inicial', 'Sin especificar', '["dedo apretado", "constricción"]'),
('S60.448D', 'Constricción externa de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.448S', 'Constricción externa de otro dedo de mano, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.449A', 'Constricción externa de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["dedo apretado", "constricción"]'),
('S60.449D', 'Constricción externa de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.449S', 'Constricción externa de dedo de mano no especificado, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.450A', 'Cuerpo extraño superficial de dedo índice derecho, contacto inicial', 'Sin especificar', '["astilla en índice derecho", "espina"]'),
('S60.450D', 'Cuerpo extraño superficial de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.450S', 'Cuerpo extraño superficial de dedo índice derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.451A', 'Cuerpo extraño superficial de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["astilla en índice izquierdo", "espina"]'),
('S60.451D', 'Cuerpo extraño superficial de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.451S', 'Cuerpo extraño superficial de dedo índice izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.452A', 'Cuerpo extraño superficial de dedo medio derecho, contacto inicial', 'Sin especificar', '["astilla en medio derecho", "espina"]'),
('S60.452D', 'Cuerpo extraño superficial de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.452S', 'Cuerpo extraño superficial de dedo medio derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.453A', 'Cuerpo extraño superficial de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["astilla en medio izquierdo", "espina"]'),
('S60.453D', 'Cuerpo extraño superficial de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.453S', 'Cuerpo extraño superficial de dedo medio izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.454A', 'Cuerpo extraño superficial de dedo anular derecho, contacto inicial', 'Sin especificar', '["astilla en anular derecho", "espina"]'),
('S60.454D', 'Cuerpo extraño superficial de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.454S', 'Cuerpo extraño superficial de dedo anular derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.455A', 'Cuerpo extraño superficial de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["astilla en anular izquierdo", "espina"]'),
('S60.455D', 'Cuerpo extraño superficial de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.455S', 'Cuerpo extraño superficial de dedo anular izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.456A', 'Cuerpo extraño superficial de dedo meñique derecho, contacto inicial', 'Sin especificar', '["astilla en meñique derecho", "espina"]'),
('S60.456D', 'Cuerpo extraño superficial de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.456S', 'Cuerpo extraño superficial de dedo meñique derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.457A', 'Cuerpo extraño superficial de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["astilla en meñique izquierdo", "espina"]'),
('S60.457D', 'Cuerpo extraño superficial de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.457S', 'Cuerpo extraño superficial de dedo meñique izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.458A', 'Cuerpo extraño superficial de otro dedo de mano, contacto inicial', 'Sin especificar', '["astilla", "espina"]'),
('S60.458D', 'Cuerpo extraño superficial de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.458S', 'Cuerpo extraño superficial de otro dedo de mano, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.459A', 'Cuerpo extraño superficial de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["astilla", "espina"]'),
('S60.459D', 'Cuerpo extraño superficial de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.459S', 'Cuerpo extraño superficial de dedo de mano no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.460A', 'Picadura de insecto (no venenoso) en dedo índice derecho, contacto inicial', 'Sin especificar', '["picadura índice derecho", "bicho"]'),
('S60.460D', 'Picadura de insecto (no venenoso) en dedo índice derecho, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.460S', 'Picadura de insecto (no venenoso) en dedo índice derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.461A', 'Picadura de insecto (no venenoso) en dedo índice izquierdo, contacto inicial', 'Sin especificar', '["picadura índice izquierdo", "bicho"]'),
('S60.461D', 'Picadura de insecto (no venenoso) en dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.461S', 'Picadura de insecto (no venenoso) en dedo índice izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.462A', 'Picadura de insecto (no venenoso) en dedo medio derecho, contacto inicial', 'Sin especificar', '["picadura medio derecho", "bicho"]'),
('S60.462D', 'Picadura de insecto (no venenoso) en dedo medio derecho, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.462S', 'Picadura de insecto (no venenoso) en dedo medio derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.463A', 'Picadura de insecto (no venenoso) en dedo medio izquierdo, contacto inicial', 'Sin especificar', '["picadura medio izquierdo", "bicho"]'),
('S60.463D', 'Picadura de insecto (no venenoso) en dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.463S', 'Picadura de insecto (no venenoso) en dedo medio izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.464A', 'Picadura de insecto (no venenoso) en dedo anular derecho, contacto inicial', 'Sin especificar', '["picadura anular derecho", "bicho"]'),
('S60.464D', 'Picadura de insecto (no venenoso) en dedo anular derecho, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.464S', 'Picadura de insecto (no venenoso) en dedo anular derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.465A', 'Picadura de insecto (no venenoso) en dedo anular izquierdo, contacto inicial', 'Sin especificar', '["picadura anular izquierdo", "bicho"]'),
('S60.465D', 'Picadura de insecto (no venenoso) en dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.465S', 'Picadura de insecto (no venenoso) en dedo anular izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.466A', 'Picadura de insecto (no venenoso) en dedo meñique derecho, contacto inicial', 'Sin especificar', '["picadura meñique derecho", "bicho"]'),
('S60.466D', 'Picadura de insecto (no venenoso) en dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.466S', 'Picadura de insecto (no venenoso) en dedo meñique derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.467A', 'Picadura de insecto (no venenoso) en dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["picadura meñique izquierdo", "bicho"]'),
('S60.467D', 'Picadura de insecto (no venenoso) en dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.467S', 'Picadura de insecto (no venenoso) en dedo meñique izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.468A', 'Picadura de insecto (no venenoso) en otro dedo de mano, contacto inicial', 'Sin especificar', '["picadura", "bicho"]'),
('S60.468D', 'Picadura de insecto (no venenoso) en otro dedo de mano, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.468S', 'Picadura de insecto (no venenoso) en otro dedo de mano, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.469A', 'Picadura de insecto (no venenoso) en dedo de mano no especificado, contacto inicial', 'Sin especificar', '["picadura", "bicho"]'),
('S60.469D', 'Picadura de insecto (no venenoso) en dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.469S', 'Picadura de insecto (no venenoso) en dedo de mano no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.470A', 'Otra mordedura superficial de dedo índice derecho, contacto inicial', 'Sin especificar', '["mordida índice derecho", "herida"]'),
('S60.470D', 'Otra mordedura superficial de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.470S', 'Otra mordedura superficial de dedo índice derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.471A', 'Otra mordedura superficial de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["mordida índice izquierdo", "herida"]'),
('S60.471D', 'Otra mordedura superficial de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.471S', 'Otra mordedura superficial de dedo índice izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.472A', 'Otra mordedura superficial de dedo medio derecho, contacto inicial', 'Sin especificar', '["mordida medio derecho", "herida"]'),
('S60.472D', 'Otra mordedura superficial de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.472S', 'Otra mordedura superficial de dedo medio derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.473A', 'Otra mordedura superficial de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["mordida medio izquierdo", "herida"]'),
('S60.473D', 'Otra mordedura superficial de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.473S', 'Otra mordedura superficial de dedo medio izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.474A', 'Otra mordedura superficial de dedo anular derecho, contacto inicial', 'Sin especificar', '["mordida anular derecho", "herida"]'),
('S60.474D', 'Otra mordedura superficial de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.474S', 'Otra mordedura superficial de dedo anular derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.475A', 'Otra mordedura superficial de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["mordida anular izquierdo", "herida"]'),
('S60.475D', 'Otra mordedura superficial de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.475S', 'Otra mordedura superficial de dedo anular izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.476A', 'Otra mordedura superficial de dedo meñique derecho, contacto inicial', 'Sin especificar', '["mordida meñique derecho", "herida"]'),
('S60.476D', 'Otra mordedura superficial de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.476S', 'Otra mordedura superficial de dedo meñique derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.477A', 'Otra mordedura superficial de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["mordida meñique izquierdo", "herida"]'),
('S60.477D', 'Otra mordedura superficial de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.477S', 'Otra mordedura superficial de dedo meñique izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.478A', 'Otra mordedura superficial de otro dedo de mano, contacto inicial', 'Sin especificar', '["mordedura", "herida"]'),
('S60.478D', 'Otra mordedura superficial de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.478S', 'Otra mordedura superficial de otro dedo de mano, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.479A', 'Otra mordedura superficial de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["mordedura", "herida"]'),
('S60.479D', 'Otra mordedura superficial de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.479S', 'Otra mordedura superficial de dedo de mano no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.511A', 'Abrasión de mano derecha, contacto inicial', 'Sin especificar', '["raspón mano derecha", "rasguño"]'),
('S60.511D', 'Abrasión de mano derecha, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.511S', 'Abrasión de mano derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.512A', 'Abrasión de mano izquierda, contacto inicial', 'Sin especificar', '["raspón mano izquierda", "rasguño"]'),
('S60.512D', 'Abrasión de mano izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.512S', 'Abrasión de mano izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.519A', 'Abrasión de mano no especificada, contacto inicial', 'Sin especificar', '["raspón mano", "rasguño"]'),
('S60.519D', 'Abrasión de mano no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.519S', 'Abrasión de mano no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.521A', 'Ampolla (no térmica) de mano derecha, contacto inicial', 'Sin especificar', '["ampolla mano derecha", "burbuja"]'),
('S60.521D', 'Ampolla (no térmica) de mano derecha, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.521S', 'Ampolla (no térmica) de mano derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.522A', 'Ampolla (no térmica) de mano izquierda, contacto inicial', 'Sin especificar', '["ampolla mano izquierda", "burbuja"]'),
('S60.522D', 'Ampolla (no térmica) de mano izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.522S', 'Ampolla (no térmica) de mano izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.529A', 'Ampolla (no térmica) de mano no especificada, contacto inicial', 'Sin especificar', '["ampolla mano", "burbuja"]'),
('S60.529D', 'Ampolla (no térmica) de mano no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.529S', 'Ampolla (no térmica) de mano no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.541A', 'Constricción externa de mano derecha, contacto inicial', 'Sin especificar', '["mano apretada", "constricción"]'),
('S60.541D', 'Constricción externa de mano derecha, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.541S', 'Constricción externa de mano derecha, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.542A', 'Constricción externa de mano izquierda, contacto inicial', 'Sin especificar', '["mano apretada", "constricción"]'),
('S60.542D', 'Constricción externa de mano izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.542S', 'Constricción externa de mano izquierda, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.549A', 'Constricción externa de mano no especificada, contacto inicial', 'Sin especificar', '["mano apretada", "constricción"]'),
('S60.549D', 'Constricción externa de mano no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.549S', 'Constricción externa de mano no especificada, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.551A', 'Cuerpo extraño superficial de mano derecha, contacto inicial', 'Sin especificar', '["astilla mano derecha", "espina"]'),
('S60.551D', 'Cuerpo extraño superficial de mano derecha, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.551S', 'Cuerpo extraño superficial de mano derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.552A', 'Cuerpo extraño superficial de mano izquierda, contacto inicial', 'Sin especificar', '["astilla mano izquierda", "espina"]'),
('S60.552D', 'Cuerpo extraño superficial de mano izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.552S', 'Cuerpo extraño superficial de mano izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.559A', 'Cuerpo extraño superficial de mano no especificada, contacto inicial', 'Sin especificar', '["astilla mano", "espina"]'),
('S60.559D', 'Cuerpo extraño superficial de mano no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.559S', 'Cuerpo extraño superficial de mano no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.561A', 'Picadura de insecto (no venenoso) en mano derecha, contacto inicial', 'Sin especificar', '["picadura mano derecha", "bicho"]'),
('S60.561D', 'Picadura de insecto (no venenoso) en mano derecha, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.561S', 'Picadura de insecto (no venenoso) en mano derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.562A', 'Picadura de insecto (no venenoso) en mano izquierda, contacto inicial', 'Sin especificar', '["picadura mano izquierda", "bicho"]'),
('S60.562D', 'Picadura de insecto (no venenoso) en mano izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.562S', 'Picadura de insecto (no venenoso) en mano izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.569A', 'Picadura de insecto (no venenoso) en mano no especificada, contacto inicial', 'Sin especificar', '["picadura mano", "bicho"]'),
('S60.569D', 'Picadura de insecto (no venenoso) en mano no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.569S', 'Picadura de insecto (no venenoso) en mano no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.571A', 'Otra mordedura superficial de mano derecha, contacto inicial', 'Sin especificar', '["mordida mano derecha", "herida"]'),
('S60.571D', 'Otra mordedura superficial de mano derecha, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.571S', 'Otra mordedura superficial de mano derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.572A', 'Otra mordedura superficial de mano izquierda, contacto inicial', 'Sin especificar', '["mordida mano izquierda", "herida"]'),
('S60.572D', 'Otra mordedura superficial de mano izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.572S', 'Otra mordedura superficial de mano izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.579A', 'Otra mordedura superficial de mano no especificada, contacto inicial', 'Sin especificar', '["mordida mano", "herida"]'),
('S60.579D', 'Otra mordedura superficial de mano no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.579S', 'Otra mordedura superficial de mano no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.811A', 'Abrasión de muñeca derecha, contacto inicial', 'Sin especificar', '["raspón muñeca derecha", "rasguño"]'),
('S60.811D', 'Abrasión de muñeca derecha, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.811S', 'Abrasión de muñeca derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.812A', 'Abrasión de muñeca izquierda, contacto inicial', 'Sin especificar', '["raspón muñeca izquierda", "rasguño"]'),
('S60.812D', 'Abrasión de muñeca izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.812S', 'Abrasión de muñeca izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.819A', 'Abrasión de muñeca no especificada, contacto inicial', 'Sin especificar', '["raspón muñeca", "rasguño"]'),
('S60.819D', 'Abrasión de muñeca no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento raspón", "curación"]'),
('S60.819S', 'Abrasión de muñeca no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.821A', 'Ampolla (no térmica) de muñeca derecha, contacto inicial', 'Sin especificar', '["ampolla muñeca derecha", "burbuja"]'),
('S60.821D', 'Ampolla (no térmica) de muñeca derecha, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.821S', 'Ampolla (no térmica) de muñeca derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.822A', 'Ampolla (no térmica) de muñeca izquierda, contacto inicial', 'Sin especificar', '["ampolla muñeca izquierda", "burbuja"]'),
('S60.822D', 'Ampolla (no térmica) de muñeca izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.822S', 'Ampolla (no térmica) de muñeca izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.829A', 'Ampolla (no térmica) de muñeca no especificada, contacto inicial', 'Sin especificar', '["ampolla muñeca", "burbuja"]'),
('S60.829D', 'Ampolla (no térmica) de muñeca no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento ampolla", "control"]'),
('S60.829S', 'Ampolla (no térmica) de muñeca no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.841A', 'Constricción externa de muñeca derecha, contacto inicial', 'Sin especificar', '["muñeca apretada", "constricción"]'),
('S60.841D', 'Constricción externa de muñeca derecha, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.841S', 'Constricción externa de muñeca derecha, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.842A', 'Constricción externa de muñeca izquierda, contacto inicial', 'Sin especificar', '["muñeca apretada", "constricción"]'),
('S60.842D', 'Constricción externa de muñeca izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.842S', 'Constricción externa de muñeca izquierda, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.849A', 'Constricción externa de muñeca no especificada, contacto inicial', 'Sin especificar', '["muñeca apretada", "constricción"]'),
('S60.849D', 'Constricción externa de muñeca no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento constricción", "revisión"]'),
('S60.849S', 'Constricción externa de muñeca no especificada, secuela', 'Sin especificar', '["secuela", "daño"]'),
('S60.851A', 'Cuerpo extraño superficial de muñeca derecha, contacto inicial', 'Sin especificar', '["astilla muñeca derecha", "espina"]'),
('S60.851D', 'Cuerpo extraño superficial de muñeca derecha, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.851S', 'Cuerpo extraño superficial de muñeca derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.852A', 'Cuerpo extraño superficial de muñeca izquierda, contacto inicial', 'Sin especificar', '["astilla muñeca izquierda", "espina"]'),
('S60.852D', 'Cuerpo extraño superficial de muñeca izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.852S', 'Cuerpo extraño superficial de muñeca izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.859A', 'Cuerpo extraño superficial de muñeca no especificada, contacto inicial', 'Sin especificar', '["astilla muñeca", "espina"]'),
('S60.859D', 'Cuerpo extraño superficial de muñeca no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento astilla", "revisión"]'),
('S60.859S', 'Cuerpo extraño superficial de muñeca no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.861A', 'Picadura de insecto (no venenoso) en muñeca derecha, contacto inicial', 'Sin especificar', '["picadura muñeca derecha", "bicho"]'),
('S60.861D', 'Picadura de insecto (no venenoso) en muñeca derecha, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.861S', 'Picadura de insecto (no venenoso) en muñeca derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.862A', 'Picadura de insecto (no venenoso) en muñeca izquierda, contacto inicial', 'Sin especificar', '["picadura muñeca izquierda", "bicho"]'),
('S60.862D', 'Picadura de insecto (no venenoso) en muñeca izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.862S', 'Picadura de insecto (no venenoso) en muñeca izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.869A', 'Picadura de insecto (no venenoso) en muñeca no especificada, contacto inicial', 'Sin especificar', '["picadura muñeca", "bicho"]'),
('S60.869D', 'Picadura de insecto (no venenoso) en muñeca no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento picadura", "control"]'),
('S60.869S', 'Picadura de insecto (no venenoso) en muñeca no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.871A', 'Otra mordedura superficial de muñeca derecha, contacto inicial', 'Sin especificar', '["mordida muñeca derecha", "herida"]'),
('S60.871D', 'Otra mordedura superficial de muñeca derecha, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.871S', 'Otra mordedura superficial de muñeca derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.872A', 'Otra mordedura superficial de muñeca izquierda, contacto inicial', 'Sin especificar', '["mordida muñeca izquierda", "herida"]'),
('S60.872D', 'Otra mordedura superficial de muñeca izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.872S', 'Otra mordedura superficial de muñeca izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.879A', 'Otra mordedura superficial de muñeca no especificada, contacto inicial', 'Sin especificar', '["mordida muñeca", "herida"]'),
('S60.879D', 'Otra mordedura superficial de muñeca no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento mordedura", "control"]'),
('S60.879S', 'Otra mordedura superficial de muñeca no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.911A', 'Traumatismo superficial no especificado de muñeca derecha, contacto inicial', 'Sin especificar', '["golpe muñeca derecha", "daño"]'),
('S60.911D', 'Traumatismo superficial no especificado de muñeca derecha, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.911S', 'Traumatismo superficial no especificado de muñeca derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.912A', 'Traumatismo superficial no especificado de muñeca izquierda, contacto inicial', 'Sin especificar', '["golpe muñeca izquierda", "daño"]'),
('S60.912D', 'Traumatismo superficial no especificado de muñeca izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.912S', 'Traumatismo superficial no especificado de muñeca izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.919A', 'Traumatismo superficial no especificado de muñeca no especificada, contacto inicial', 'Sin especificar', '["golpe muñeca", "daño"]'),
('S60.919D', 'Traumatismo superficial no especificado de muñeca no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.919S', 'Traumatismo superficial no especificado de muñeca no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.921A', 'Traumatismo superficial no especificado de mano derecha, contacto inicial', 'Sin especificar', '["golpe mano derecha", "daño"]'),
('S60.921D', 'Traumatismo superficial no especificado de mano derecha, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.921S', 'Traumatismo superficial no especificado de mano derecha, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.922A', 'Traumatismo superficial no especificado de mano izquierda, contacto inicial', 'Sin especificar', '["golpe mano izquierda", "daño"]'),
('S60.922D', 'Traumatismo superficial no especificado de mano izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.922S', 'Traumatismo superficial no especificado de mano izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.929A', 'Traumatismo superficial no especificado de mano no especificada, contacto inicial', 'Sin especificar', '["golpe mano", "daño"]'),
('S60.929D', 'Traumatismo superficial no especificado de mano no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.929S', 'Traumatismo superficial no especificado de mano no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.931A', 'Traumatismo superficial no especificado de pulgar derecho, contacto inicial', 'Sin especificar', '["golpe pulgar derecho", "daño"]'),
('S60.931D', 'Traumatismo superficial no especificado de pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.931S', 'Traumatismo superficial no especificado de pulgar derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.932A', 'Traumatismo superficial no especificado de pulgar izquierdo, contacto inicial', 'Sin especificar', '["golpe pulgar izquierdo", "daño"]'),
('S60.932D', 'Traumatismo superficial no especificado de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.932S', 'Traumatismo superficial no especificado de pulgar izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.939A', 'Traumatismo superficial no especificado de pulgar no especificado, contacto inicial', 'Sin especificar', '["golpe pulgar", "daño"]'),
('S60.939D', 'Traumatismo superficial no especificado de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.939S', 'Traumatismo superficial no especificado de pulgar no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.940A', 'Traumatismo superficial no especificado de dedo índice derecho, contacto inicial', 'Sin especificar', '["golpe índice derecho", "daño"]'),
('S60.940D', 'Traumatismo superficial no especificado de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.940S', 'Traumatismo superficial no especificado de dedo índice derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.941A', 'Traumatismo superficial no especificado de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["golpe índice izquierdo", "daño"]'),
('S60.941D', 'Traumatismo superficial no especificado de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.941S', 'Traumatismo superficial no especificado de dedo índice izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.942A', 'Traumatismo superficial no especificado de dedo medio derecho, contacto inicial', 'Sin especificar', '["golpe dedo medio derecho", "daño"]'),
('S60.942D', 'Traumatismo superficial no especificado de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.942S', 'Traumatismo superficial no especificado de dedo medio derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.943A', 'Traumatismo superficial no especificado de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["golpe dedo medio izquierdo", "daño"]'),
('S60.943D', 'Traumatismo superficial no especificado de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.943S', 'Traumatismo superficial no especificado de dedo medio izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.944A', 'Traumatismo superficial no especificado de dedo anular derecho, contacto inicial', 'Sin especificar', '["golpe dedo anular derecho", "daño"]'),
('S60.944D', 'Traumatismo superficial no especificado de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.944S', 'Traumatismo superficial no especificado de dedo anular derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.945A', 'Traumatismo superficial no especificado de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["golpe dedo anular izquierdo", "daño"]'),
('S60.945D', 'Traumatismo superficial no especificado de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.945S', 'Traumatismo superficial no especificado de dedo anular izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.946A', 'Traumatismo superficial no especificado de dedo meñique derecho, contacto inicial', 'Sin especificar', '["golpe dedo meñique derecho", "daño"]'),
('S60.946D', 'Traumatismo superficial no especificado de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.946S', 'Traumatismo superficial no especificado de dedo meñique derecho, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.947A', 'Traumatismo superficial no especificado de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["golpe dedo meñique izquierdo", "daño"]'),
('S60.947D', 'Traumatismo superficial no especificado de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.947S', 'Traumatismo superficial no especificado de dedo meñique izquierdo, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.948A', 'Traumatismo superficial no especificado de otro dedo de mano, contacto inicial', 'Sin especificar', '["golpe en dedo", "daño"]'),
('S60.948D', 'Traumatismo superficial no especificado de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.948S', 'Traumatismo superficial no especificado de otro dedo de mano, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S60.949A', 'Traumatismo superficial no especificado de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["golpe en dedo", "daño"]'),
('S60.949D', 'Traumatismo superficial no especificado de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control"]'),
('S60.949S', 'Traumatismo superficial no especificado de dedo de mano no especificado, secuela', 'Sin especificar', '["cicatriz", "secuela"]');
