INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D01.0', 'Carcinoma in situ de colon', 'Sin especificar', '["cáncer de colon", "tumor en el intestino", "cáncer de tripa", "cáncer de colón", "lesión precancerosa colon", "masa en el colon", "pólipos malignos", "sangre en la caca", "sangre en las heces", "dolor de panza", "dolor de barriga", "dolor de guata", "cambios al ir al baño", "estreñimiento severo", "diarrea persistente", "neoplasia in situ colon"]'),
('D01.1', 'Carcinoma in situ de unión rectosigmoidea', 'Sin especificar', '["cáncer recto-sigmoide", "tumor unión rectosigmoidea", "cáncer en la última parte del intestino", "dolor anal", "tenesmo", "sangrado rectal", "caca con sangre", "dolor de panza bajo", "tumor digestivo inicial", "neoplasia rectosigmoidea", "lesión en el sigmoides", "ardor en el recto", "urgencia al ir al baño"]'),
('D01.2', 'Carcinoma in situ de recto', 'Sin especificar', '["cáncer de recto", "tumor en el recto", "sangrado anal", "bolitas en el ano", "dolor al defecar", "caca con sangre fresca", "neoplasia rectal", "picazón en el ano", "sensación de peso en el recto", "tenesmo rectal", "cáncer de colón bajo", "lesión precancerosa recto", "sangre en el papel higiénico"]'),
('D01.3', 'Carcinoma in situ de ano y canal anal', 'Sin especificar', '["cáncer de ano", "tumor en el ano", "herida en el ano", "picazón anal intensa", "sangre al limpiar", "dolor anal persistente", "masa en el orificio anal", "carcinoma canal anal", "lesión anal maligna", "bulto en el poto", "bulto en el traste", "dolor en el culo", "sangrado anal post defecación"]'),
('D01.40', 'Carcinoma in situ de parte no especificada de intestino', 'Sin especificar', '["tumor intestinal", "cáncer de tripas", "cáncer intestinal", "dolor abdominal difuso", "masa abdominal", "cáncer de panza", "neoplasia intestinal", "problemas digestivos graves", "lesión en el intestino", "cáncer de vísceras", "dolor de guata", "inflamación abdominal persistente", "pérdida de peso inexplicable"]'),
('D01.49', 'Carcinoma in situ de otras partes de intestino', 'Sin especificar', '["cáncer intestino delgado", "tumor en el íleon", "cáncer duodeno", "neoplasia intestinal", "dolor de panza", "obstrucción intestinal", "problemas para digerir", "lesión precancerosa intestino", "tumor del aparato digestivo", "cáncer de tripa", "cáncer intestinal localizado"]'),
('D01.5', 'Carcinoma in situ de hígado, vesícula biliar y conductos biliares', 'Sin especificar', '["cáncer de hígado", "tumor en la vesícula", "piedras en la vesícula malignas", "cáncer conductos biliares", "ictericia", "piel amarilla", "ojos amarillos", "dolor debajo de las costillas", "dolor en el hipocondrio derecho", "dolor en la boca del estómago", "tumor hepático", "neoplasia de vías biliares", "cáncer de hiel"]'),
('D01.7', 'Carcinoma in situ de otros órganos digestivos especificados', 'Sin especificar', '["tumor sistema digestivo", "cáncer órganos digestivos", "lesión digestiva", "neoplasia tracto gastrointestinal", "problemas digestivos severos", "masa abdominal", "dolor estomacal", "carcinoma digestivo in situ", "tumor de glándulas digestivas", "cáncer esofágico inicial", "cáncer gástrico in situ"]'),
('D01.9', 'Carcinoma in situ de órganos digestivos, localización no especificada', 'Sin especificar', '["cáncer digestivo", "tumor en la panza", "tumor en el aparato digestivo", "problemas graves de digestión", "neoplasia digestiva no especificada", "cáncer de vísceras abdominales", "masa en el abdomen", "dolor abdominal de origen desconocido", "lesión precancerosa digestiva", "cáncer de órganos internos", "cáncer de estómago no especificado"]');
