INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L74.0', 'Miliaria rubra', 'Sin especificar', '["sarpullido", "salpullido", "sudamina", "granitos por calor", "ronchas de calor", "erupción por calor", "picazón en la piel", "ardor en la piel", "granitos rojos", "dermatitis por sudor", "calorina", "sudorina", "salpullido rojo", "irritación por sudor"]'),
('L74.1', 'Miliaria cristalina', 'Sin especificar', '["vesículas en la piel", "ampollitas transparentes", "gotitas de sudor en la piel", "sudamina cristalina", "sarpullido blanco", "granitos de agua", "erupción vesicular", "piel de cristal", "sudor atrapado", "micropápulas", "lesiones transparentes", "erupción superficial", "ampollas pequeñas"]'),
('L74.2', 'Miliaria profunda', 'Sin especificar', '["miliaria profunda", "bultos bajo la piel", "pápulas profundas", "sudamina severa", "sarpullido interno", "granitos dolorosos", "inflamación de glándulas sudoríparas", "lesiones cutáneas profundas", "obstrucción de sudor", "nódulos por sudor", "erupción dérmica", "bultitos bajo la piel"]'),
('L74.3', 'Miliaria, no especificada', 'Sin especificar', '["erupción por sudor", "granitos del calor", "sudamina general", "sarpullido generalizado", "piel irritada por calor", "problemas de sudor", "dermatitis por calor", "picazón de verano", "manchas rojas por calor", "irritación dérmica"]'),
('L74.4', 'Anhidrosis', 'Sin especificar', '["falta de sudor", "no puedo sudar", "piel seca excesiva", "incapacidad para sudar", "ausencia de transpiración", "cuerpo no transpira", "hipohidrosis", "sobrecalentamiento corporal", "piel que no suda", "trastorno de la transpiración", "intolerancia al calor"]'),
('L74.510', 'Hiperhidrosis primaria focal de la axila', 'Sin especificar', '["sudor excesivo axilas", "axilas mojadas", "manchas en la ropa", "sudoración en las axilas", "sudor de sobaco", "exceso de sudor axilar", "transpiración excesiva", "humedad en las axilas", "chupacos mojados", "axila empapada", "sudoración axilar crónica"]'),
('L74.511', 'Hiperhidrosis primaria focal de la cara', 'Sin especificar', '["sudor excesivo en la cara", "cara mojada", "sudor en la frente", "sudoración facial", "exceso de transpiración en la cara", "goteo de sudor en cara", "sudor constante en el rostro", "sudor de cabeza", "cara empapada", "sudoración cefálica"]'),
('L74.512', 'Hiperhidrosis primaria focal de las palmas de las manos', 'Sin especificar', '["manos sudorosas", "manos mojadas", "exceso de sudor en palmas", "manos empapadas", "hiperhidrosis palmar", "sudor de manos", "manos que gotean", "sudoración al tocar cosas", "manos resbaladizas", "sudor excesivo en las palmas"]'),
('L74.513', 'Hiperhidrosis primaria focal de las plantas de los pies', 'Sin especificar', '["pies sudorosos", "pies mojados", "sudor en los pies", "hiperhidrosis plantar", "sudoración excesiva en pies", "pies empapados", "olor en los pies por sudor", "sudor constante en plantas", "pies resbalosos", "humedad en zapatos"]'),
('L74.519', 'Hiperhidrosis primaria focal, no especificada', 'Sin especificar', '["sudor excesivo", "hiperhidrosis", "mucha sudoración", "exceso de transpiración", "sudoración corporal alta", "transpirar demasiado", "sudor profuso", "sudor constante", "transpiración crónica", "sudar mucho"]'),
('L74.52', 'Hiperhidrosis secundaria focal', 'Sin especificar', '["sudor excesivo por otra enfermedad", "sudoración por medicamentos", "sudor excesivo repentino", "causa de sudoración excesiva", "sudoración secundaria", "exceso de sudor localizado", "sudor patológico", "transpiración aumentada por enfermedad", "sudoración provocada"]'),
('L74.8', 'Otros tipos de trastornos sudoríparos ecrinos', 'Sin especificar', '["trastornos del sudor", "sudor con olor", "problemas con el sudor", "alteración de glándulas sudoríparas", "sudor coloreado", "cromhidrosis", "sudoración anormal", "disfunción de glándulas ecrinas", "problemas de transpiración"]'),
('L74.9', 'Trastorno sudoríparo ecrino, no especificado', 'Sin especificar', '["problema con la transpiración", "enfermedad de las glándulas sudoríparas", "trastorno del sudor sin nombre", "sudoración rara", "alteración de la piel y sudor", "problemas de sudoración", "trastorno glandular cutáneo", "sudoración inusual"]');
