INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('M48.00', 'Estenosis vertebral, localización no especificada', 'Sin especificar', '["estrechamiento de columna", "canal estrecho", "dolor de espalda", "columna cerrada", "nervio pinzado", "dificultad para caminar", "hormigueo en piernas", "debilidad muscular", "espalda trabada", "rigidez vertebral", "dolor crónico de espalda", "pinzamiento vertebral", "compresión nerviosa", "columna comprimida"]'),
('M48.01', 'Estenosis vertebral, región occipitoatloaxoidea', 'Sin especificar', '["dolor en la nuca", "estrechamiento cervical alto", "cuello trabado", "dolor base del cráneo", "rigidez cervical alta", "presión en el cuello", "dolor al girar el cuello", "pinzamiento cervical superior", "vértigo cervical", "hormigueo en cuello", "tensión cervical", "molestia en la nuca"]'),
('M48.02', 'Estenosis vertebral, región cervical', 'Sin especificar', '["dolor de cuello", "cuello tieso", "cervicalgia", "estrechamiento cervical", "dolor que baja al brazo", "hormigueo en manos", "adormecimiento de brazos", "cuello trabado", "rigidez en el cuello", "tortícolis crónica", "pesadez de hombros", "pinzamiento cervical"]'),
('M48.03', 'Estenosis vertebral, región cervicotorácica', 'Sin especificar', '["dolor entre la espalda y el cuello", "nudo en la espalda", "dolor en los hombros", "estrechamiento unión cuello espalda", "molestia en la zona alta de la espalda", "rigidez en la espalda alta", "tensión cervicodorsal", "dolor al respirar profundo", "cargazón en la espalda"]'),
('M48.04', 'Estenosis vertebral, región torácica', 'Sin especificar', '["dolor de espalda alta", "dolor dorsales", "espalda cerrada", "pinchazos en la espalda", "dolor en el tórax por espalda", "rigidez dorsal", "molestia entre las paletas", "dolor al mover el tronco", "estrechamiento dorsal"]'),
('M48.05', 'Estenosis vertebral, región dorsolumbar', 'Sin especificar', '["dolor en la cintura y espalda", "dolor de riñones", "cintura trabada", "dolor de espalda media-baja", "rigidez dorsolumbar", "lumbago", "molestia al agacharse", "espalda media dolorida"]'),
('M48.061', 'Estenosis vertebral, región lumbar sin claudicación neurógena', 'Sin especificar', '["dolor lumbar", "lumbago", "ciática", "dolor de cintura", "espalda baja dolorida", "dolor al estar parado", "pinchazos en la cintura", "columna lumbar estrecha", "dolor de riñones", "tensión lumbar"]'),
('M48.062', 'Estenosis vertebral, región lumbar con claudicación neurógena', 'Sin especificar', '["dolor al caminar", "piernas cansadas", "debilidad en las piernas al andar", "pesadez en las piernas", "necesidad de sentarse para descansar", "calambres en las piernas", "espalda baja con dolor", "cojera por dolor", "estancamiento al caminar", "hormigueo en las piernas"]'),
('M48.07', 'Estenosis vertebral, región lumbosacra', 'Sin especificar', '["dolor en el bajo vientre y cintura", "dolor de cadera", "dolor en el huesito dulce", "dolor de rabadilla", "ciática", "dolor en la base de la columna", "lumbosacralgia", "dolor al sentarse", "tirón en la cintura"]'),
('M48.08', 'Estenosis vertebral, regiones sacra y sacrococcígea', 'Sin especificar', '["dolor de rabadilla", "dolor en el coxis", "molestia al sentarse", "dolor en la base de la espalda", "dolor sacro", "pinchazos en la rabadilla", "inflamación de la base de la columna"]'),
('M48.10', 'Hiperostosis anquilosante [Forestier], localización no especificada', 'Sin especificar', '["columna rígida", "huesos pegados", "espalda tiesa", "calcificación de columna", "enfermedad de Forestier", "picos de loro en columna", "columna ósea", "rigidez de espalda", "columna que no se mueve"]'),
('M48.11', 'Hiperostosis anquilosante [Forestier], región occipitoatloaxoidea', 'Sin especificar', '["cuello de piedra", "rigidez extrema del cuello", "no puedo girar la cabeza", "calcificación del cuello", "Forestier en el cuello", "nuca rígida"]'),
('M48.12', 'Hiperostosis anquilosante [Forestier], región cervical', 'Sin especificar', '["cervicales calcificadas", "cuello tieso", "imposible mover el cuello", "huesos de la nuca pegados", "dolor cervical intenso", "rigidez de cuello"]'),
('M48.13', 'Hiperostosis anquilosante [Forestier], región cervicotorácica', 'Sin especificar', '["rigidez en la espalda alta", "espalda de piedra", "espalda bloqueada", "calcificación de vértebras altas", "nudos de hueso en espalda"]'),
('M48.14', 'Hiperostosis anquilosante [Forestier], región torácica', 'Sin especificar', '["torso rígido", "espalda encorvada y dura", "calcificación dorsal", "pecho tieso", "dificultad para respirar por rigidez", "espalda bloqueada"]'),
('M48.15', 'Hiperostosis anquilosante [Forestier], región dorsolumbar', 'Sin especificar', '["rigidez de cintura y espalda", "espalda bloqueada", "columna soldada", "dolor crónico de espalda media y baja"]'),
('M48.16', 'Hiperostosis anquilosante [Forestier], región lumbar', 'Sin especificar', '["cintura de piedra", "cintura bloqueada", "no puedo agacharme", "lumbar rígida", "calcificación lumbar", "huesos soldados en la cintura"]'),
('M48.17', 'Hiperostosis anquilosante [Forestier], región lumbosacra', 'Sin especificar', '["rigidez en la base de la columna", "sacro pegado", "dolor al caminar", "dificultad para pararse", "espalda baja rígida"]'),
('M48.18', 'Hiperostosis anquilosante [Forestier], regiones sacra y sacrococcígea', 'Sin especificar', '["coxis rígido", "rabadilla calcificada", "dolor al estar sentado", "base de la espalda dura"]'),
('M48.19', 'Hiperostosis anquilosante [Forestier], localizaciones múltiples de columna vertebral', 'Sin especificar', '["columna de bambú", "espalda rígida completa", "columna calcificada", "enfermedad de los huesos pegados", "toda la espalda tiesa"]'),
('M48.20', 'Espondilopatía interespinosa, localización no especificada', 'Sin especificar', '["dolor entre las vértebras", "enfermedad de Baastrup", "beso de las apófisis", "dolor espinoso", "roce de vértebras", "espalda dolorida"]'),
('M48.21', 'Espondilopatía interespinosa, región occipitoatloaxoidea', 'Sin especificar', '["dolor entre vértebras del cuello", "roce óseo en nuca", "molestia en la base del cráneo"]'),
('M48.22', 'Espondilopatía interespinosa, región cervical', 'Sin especificar', '["dolor al inclinar la cabeza", "pinchazo en la nuca", "roce de vértebras cervicales", "dolor cervical central"]'),
('M48.23', 'Espondilopatía interespinosa, región cervicotorácica', 'Sin especificar', '["dolor en la base del cuello", "pinchazo en espalda alta", "roce vertebral en zona de unión"]'),
('M48.24', 'Espondilopatía interespinosa, región torácica', 'Sin especificar', '["dolor entre los huesos de la espalda", "pinchazos dorsales", "roce de paletas", "dolor al estirarse"]'),
('M48.25', 'Espondilopatía interespinosa, región dorsolumbar', 'Sin especificar', '["dolor en la unión lumbar", "roce de huesos en espalda media", "pinchazo en la cintura alta"]'),
('M48.26', 'Espondilopatía interespinosa, región lumbar', 'Sin especificar', '["dolor de cintura por roce", "beso vertebral lumbar", "pinchazo al arquear la espalda", "dolor en vértebras lumbares"]'),
('M48.27', 'Espondilopatía interespinosa, región lumbosacra', 'Sin especificar', '["dolor lumbar bajo", "pinchazo en la base de la columna", "roce óseo sacro", "molestia al enderezarse"]'),
('M48.30', 'Espondilopatía traumática, localización no especificada', 'Sin especificar', '["dolor de espalda por golpe", "columna lesionada", "trauma vertebral", "dolor post accidente", "espalda golpeada"]'),
('M48.31', 'Espondilopatía traumática, región occipitoatloaxoidea', 'Sin especificar', '["latigazo cervical", "golpe en el cuello", "nuca golpeada", "lesión base cráneo", "dolor post golpe en cabeza"]'),
('M48.32', 'Espondilopatía traumática, región cervical', 'Sin especificar', '["dolor cervical por accidente", "golpe en cuello", "latigazo", "traumatismo cervical", "cuello trabado por choque"]'),
('M48.33', 'Espondilopatía traumática, región cervicotorácica', 'Sin especificar', '["golpe entre espalda y cuello", "trauma espalda alta", "dolor por caída en espalda", "lesión dorsal alta"]'),
('M48.34', 'Espondilopatía traumática, región torácica', 'Sin especificar', '["golpe en la espalda", "trauma dorsal", "dolor en la caja torácica por golpe", "espalda golpeada fuerte"]'),
('M48.35', 'Espondilopatía traumática, región dorsolumbar', 'Sin especificar', '["golpe en la espalda media-baja", "traumatismo en cintura", "caída de espaldas", "lesión en la cintura"]'),
('M48.36', 'Espondilopatía traumática, región lumbar', 'Sin especificar', '["golpe en la cintura", "trauma lumbar", "dolor lumbar por caída", "espalda baja lesionada", "esguince lumbar"]'),
('M48.37', 'Espondilopatía traumática, región lumbosacra', 'Sin especificar', '["golpe en el sacro", "caída de sentón", "lesión en la rabadilla", "trauma lumbosacro"]'),
('M48.38', 'Espondilopatía traumática, regiones sacra y sacrococcígea', 'Sin especificar', '["fractura de coxis", "golpe en el huesito dulce", "dolor de rabadilla por caída", "trauma en el coxis"]'),
('M48.40XA', 'Fractura vertebral por fatiga, localización no especificada, contacto inicial por fractura', 'Sin especificar', '["fractura por esfuerzo", "vértebra quebrada por cargar peso", "hueso de la espalda roto", "fisura vertebral", "dolor súbito en espalda"]'),
('M48.40XD', 'Fractura vertebral por fatiga, localización no especificada, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["seguimiento fractura vertebral", "control vértebra rota", "curación fractura espalda", "revisión fractura"]'),
('M48.40XG', 'Fractura vertebral por fatiga, localización no especificada, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["hueso que no pega", "fractura vertebral no sana", "retraso en consolidación ósea", "hueso sin soldar"]'),
('M48.40XS', 'Fractura vertebral por fatiga, localización no especificada, secuela', 'Sin especificar', '["secuelas de fractura", "dolor crónico tras fractura", "espalda deformada por fractura antigua"]'),
('M48.41XA', 'Fractura vertebral por fatiga, región occipitoatloaxoidea, contacto inicial por fractura', 'Sin especificar', '["fractura en la nuca", "hueso de la base del cráneo roto", "lesión cervical alta"]'),
('M48.41XD', 'Fractura vertebral por fatiga, región occipitoatloaxoidea, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["control fractura cervical alta", "seguimiento lesión nuca"]'),
('M48.41XG', 'Fractura vertebral por fatiga, región occipitoatloaxoidea, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["hueso del cuello sin pegar", "falta de unión fractura alta"]'),
('M48.41XS', 'Fractura vertebral por fatiga, región occipitoatloaxoidea, secuela', 'Sin especificar', '["secuela de fractura en nuca", "dolor persistente cervical"]'),
('M48.42XA', 'Fractura vertebral por fatiga, región cervical, contacto inicial por fractura', 'Sin especificar', '["fractura de cuello", "vértebra cervical rota", "cuello quebrado por esfuerzo"]'),
('M48.42XD', 'Fractura vertebral por fatiga, región cervical, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["control fractura cervical", "revisión cuello roto"]'),
('M48.42XG', 'Fractura vertebral por fatiga, región cervical, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["fractura de cuello sin consolidar", "huesos del cuello sin soldar"]'),
('M48.42XS', 'Fractura vertebral por fatiga, región cervical, secuela', 'Sin especificar', '["secuela tras fractura de cuello", "dolor cervical crónico"]'),
('M48.43XA', 'Fractura vertebral por fatiga, región cervicotorácica, contacto inicial por fractura', 'Sin especificar', '["fractura en la base del cuello", "lesión espalda alta", "vértebra rota espalda alta"]'),
('M48.43XD', 'Fractura vertebral por fatiga, región cervicotorácica, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["seguimiento fractura cervicodorsal"]'),
('M48.43XG', 'Fractura vertebral por fatiga, región cervicotorácica, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["huesos sin pegar espalda alta"]'),
('M48.43XS', 'Fractura vertebral por fatiga, región cervicotorácica, secuela', 'Sin especificar', '["dolor crónico cervicodorsal"]'),
('M48.44XA', 'Fractura vertebral por fatiga, región torácica, contacto inicial por fractura', 'Sin especificar', '["fractura dorsal", "vértebra rota espalda alta", "espalda rota"]'),
('M48.44XD', 'Fractura vertebral por fatiga, región torácica, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["control fractura torácica"]'),
('M48.44XG', 'Fractura vertebral por fatiga, región torácica, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["fractura dorsal sin soldar"]'),
('M48.44XS', 'Fractura vertebral por fatiga, región torácica, secuela', 'Sin especificar', '["espalda encorvada post fractura", "dolor crónico dorsal"]'),
('M48.45XA', 'Fractura vertebral por fatiga, región dorsolumbar, contacto inicial por fractura', 'Sin especificar', '["fractura dorsolumbar", "vértebra rota espalda media"]'),
('M48.45XD', 'Fractura vertebral por fatiga, región dorsolumbar, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["revisión fractura dorsolumbar"]'),
('M48.45XG', 'Fractura vertebral por fatiga, región dorsolumbar, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["hueso sin pegar dorsolumbar"]'),
('M48.45XS', 'Fractura vertebral por fatiga, región dorsolumbar, secuela', 'Sin especificar', '["secuela fractura dorsolumbar"]'),
('M48.46XA', 'Fractura vertebral por fatiga, región lumbar, contacto inicial por fractura', 'Sin especificar', '["fractura de cintura", "vértebra lumbar rota", "fractura lumbar"]'),
('M48.46XD', 'Fractura vertebral por fatiga, región lumbar, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["control fractura lumbar"]'),
('M48.46XG', 'Fractura vertebral por fatiga, región lumbar, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["fractura lumbar no consolida"]'),
('M48.46XS', 'Fractura vertebral por fatiga, región lumbar, secuela', 'Sin especificar', '["dolor lumbar post fractura"]'),
('M48.47XA', 'Fractura vertebral por fatiga, región lumbosacra, contacto inicial por fractura', 'Sin especificar', '["fractura base de columna", "hueso de la cintura rota"]'),
('M48.47XD', 'Fractura vertebral por fatiga, región lumbosacra, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["control lesión sacra"]'),
('M48.47XG', 'Fractura vertebral por fatiga, región lumbosacra, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["falta de pegado en sacro"]'),
('M48.47XS', 'Fractura vertebral por fatiga, región lumbosacra, secuela', 'Sin especificar', '["dolor base columna permanente"]'),
('M48.48XA', 'Fractura vertebral por fatiga, regiones sacra y sacrococcígea, contacto inicial por fractura', 'Sin especificar', '["fractura de rabadilla", "coxis roto por esfuerzo"]'),
('M48.48XD', 'Fractura vertebral por fatiga, regiones sacra y sacrococcígea, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["revisión fractura coxis"]'),
('M48.48XG', 'Fractura vertebral por fatiga, regiones sacra y sacrococcígea, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["coxis que no suelda"]'),
('M48.48XS', 'Fractura vertebral por fatiga, regiones sacra y sacrococcígea, secuela', 'Sin especificar', '["dolor al sentarse permanente"]'),
('M48.50XA', 'Vértebra colapsada, no clasificada bajo otro concepto, localización no especificada, contacto inicial por fractura', 'Sin especificar', '["vértebra aplastada", "colapso vertebral", "hueso de la columna hundido"]'),
('M48.50XD', 'Vértebra colapsada, no clasificada bajo otro concepto, localización no especificada, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["seguimiento vértebra hundida"]'),
('M48.50XG', 'Vértebra colapsada, no clasificada bajo otro concepto, localización no especificada, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["vértebra sin recuperar forma"]'),
('M48.50XS', 'Vértebra colapsada, no clasificada bajo otro concepto, localización no especificada, secuela', 'Sin especificar', '["espalda encorvada", "deformidad vertebral"]'),
('M48.51XA', 'Vértebra colapsada, no clasificada bajo otro concepto, región occipitoatloaxoidea, contacto inicial por fractura', 'Sin especificar', '["colapso vértebra alta", "hundimiento vértebra nuca"]'),
('M48.51XD', 'Vértebra colapsada, no clasificada bajo otro concepto, región occipitoatloaxoidea, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["control vértebra nuca hundida"]'),
('M48.51XG', 'Vértebra colapsada, no clasificada bajo otro concepto, región occipitoatloaxoidea, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["falta de consolidación cervical alta"]'),
('M48.51XS', 'Vértebra colapsada, no clasificada bajo otro concepto, región occipitoatloaxoidea, secuela', 'Sin especificar', '["dolor persistente cabeza-cuello"]'),
('M48.52XA', 'Vértebra colapsada, no clasificada bajo otro concepto, región cervical, contacto inicial por fractura', 'Sin especificar', '["cuello aplastado", "vértebra cervical hundida"]'),
('M48.52XD', 'Vértebra colapsada, no clasificada bajo otro concepto, región cervical, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["control vértebra cervical"]'),
('M48.52XG', 'Vértebra colapsada, no clasificada bajo otro concepto, región cervical, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["vértebra cervical no pega"]'),
('M48.52XS', 'Vértebra colapsada, no clasificada bajo otro concepto, región cervical, secuela', 'Sin especificar', '["secuela cuello aplastado"]'),
('M48.53XA', 'Vértebra colapsada, no clasificada bajo otro concepto, región cervicodorsal, contacto inicial por fractura', 'Sin especificar', '["hundimiento espalda alta", "colapso transición espalda"]'),
('M48.53XD', 'Vértebra colapsada, no clasificada bajo otro concepto, región cervicodorsal, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["control vértebra transición"]'),
('M48.53XG', 'Vértebra colapsada, no clasificada bajo otro concepto, región cervicodorsal, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["vértebra unión sin consolidar"]'),
('M48.53XS', 'Vértebra colapsada, no clasificada bajo otro concepto, región cervicodorsal, secuela', 'Sin especificar', '["deformidad espalda alta"]'),
('M48.54XA', 'Vértebra colapsada, no clasificada bajo otro concepto, región torácica, contacto inicial por fractura', 'Sin especificar', '["colapso dorsal", "espalda encorvada hundida"]'),
('M48.54XD', 'Vértebra colapsada, no clasificada bajo otro concepto, región torácica, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["seguimiento colapso dorsal"]'),
('M48.54XG', 'Vértebra colapsada, no clasificada bajo otro concepto, región torácica, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["vértebra dorsal sin pegar"]'),
('M48.54XS', 'Vértebra colapsada, no clasificada bajo otro concepto, región torácica, secuela', 'Sin especificar', '["joroba post colapso"]'),
('M48.55XA', 'Vértebra colapsada, no clasificada bajo otro concepto, región dorsolumbar, contacto inicial por fractura', 'Sin especificar', '["hundimiento dorsolumbar", "aplastamiento zona media"]'),
('M48.55XD', 'Vértebra colapsada, no clasificada bajo otro concepto, región dorsolumbar, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["control vértebra media"]'),
('M48.55XG', 'Vértebra colapsada, no clasificada bajo otro concepto, región dorsolumbar, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["vértebra dorsolumbar no soldada"]'),
('M48.55XS', 'Vértebra colapsada, no clasificada bajo otro concepto, región dorsolumbar, secuela', 'Sin especificar', '["dolor espalda media permanente"]'),
('M48.56XA', 'Vértebra colapsada, no clasificada bajo otro concepto, región lumbar, contacto inicial por fractura', 'Sin especificar', '["colapso lumbar", "vértebra cintura aplastada"]'),
('M48.56XD', 'Vértebra colapsada, no clasificada bajo otro concepto, región lumbar, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["seguimiento colapso lumbar"]'),
('M48.56XG', 'Vértebra colapsada, no clasificada bajo otro concepto, región lumbar, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["colapso lumbar sin consolidar"]'),
('M48.56XS', 'Vértebra colapsada, no clasificada bajo otro concepto, región lumbar, secuela', 'Sin especificar', '["debilidad espalda baja"]'),
('M48.57XA', 'Vértebra colapsada, no clasificada bajo otro concepto, región lumbosacra, contacto inicial por fractura', 'Sin especificar', '["hundimiento base columna", "aplastamiento sacro"]'),
('M48.57XD', 'Vértebra colapsada, no clasificada bajo otro concepto, región lumbosacra, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["revisión base de columna"]'),
('M48.57XG', 'Vértebra colapsada, no clasificada bajo otro concepto, región lumbosacra, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["vértebra base no pega"]'),
('M48.57XS', 'Vértebra colapsada, no clasificada bajo otro concepto, región lumbosacra, secuela', 'Sin especificar', '["dolor sacro crónico"]'),
('M48.58XA', 'Vértebra colapsada, no clasificada bajo otro concepto, región sacra y sacrococcígea, contacto inicial por fractura', 'Sin especificar', '["coxis aplastado", "hundimiento sacro"]'),
('M48.58XD', 'Vértebra colapsada, no clasificada bajo otro concepto, región sacra y sacrococcígea, contacto sucesivo por fractura con curas rutinarias', 'Sin especificar', '["seguimiento coxis"]'),
('M48.58XG', 'Vértebra colapsada, no clasificada bajo otro concepto, región sacra y sacrococcígea, contacto sucesivo por fractura con retardo de consolidación', 'Sin especificar', '["coxis sin pegar"]'),
('M48.58XS', 'Vértebra colapsada, no clasificada bajo otro concepto, región sacra y sacrococcígea, secuela', 'Sin especificar', '["molestia al sentarse crónica"]'),
('M48.8X1', 'Otras espondilopatías especificadas, región occipitoatloaxoidea', 'Sin especificar', '["problema cervical alto", "lesión nuca", "molestia columna craneal"]'),
('M48.8X2', 'Otras espondilopatías especificadas, región cervical', 'Sin especificar', '["problema cuello", "enfermedad cervical", "cervicales mal"]'),
('M48.8X3', 'Otras espondilopatías especificadas, región cervicotorácica', 'Sin especificar', '["problema unión espalda-cuello", "dolor cervicodorsal"]'),
('M48.8X4', 'Otras espondilopatías especificadas, región torácica', 'Sin especificar', '["problema espalda", "enfermedad dorsal"]'),
('M48.8X5', 'Otras espondilopatías especificadas, región dorsolumbar', 'Sin especificar', '["problema espalda media", "dolor cintura alta"]'),
('M48.8X6', 'Otras espondilopatías especificadas, región lumbar', 'Sin especificar', '["problema cintura", "dolor lumbar", "enfermedad lumbar"]'),
('M48.8X7', 'Otras espondilopatías especificadas, región lumbosacra', 'Sin especificar', '["problema base espalda", "dolor sacro"]'),
('M48.8X8', 'Otras espondilopatías especificadas, regiones sacra y sacrococcígea', 'Sin especificar', '["problema coxis", "dolor rabadilla"]'),
('M48.8X9', 'Otras espondilopatías especificadas, localización no especificada', 'Sin especificar', '["problema de columna", "dolor de espalda raro", "enfermedad de columna"]'),
('M48.9', 'Espondilopatía, no especificada', 'Sin especificar', '["problema de espina dorsal", "dolor de espalda", "columna mal", "desgaste de columna"]');
