INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H92.01', 'Otalgia, oído derecho', 'Sin especificar', '["dolor de oído", "me duele el oído", "punzadas en el oído", "oído tapado", "pinchazos oído", "infección oído", "otitis", "dolor de oreja", "oído derecho adolorido", "tengo algo en el oído", "dolor profundo oído", "oído inflamado"]'),
('H92.02', 'Otalgia, oído izquierdo', 'Sin especificar', '["dolor de oído", "me duele el oído izquierdo", "punzadas en el oído", "oído tapado", "pinchazos oído", "infección oído", "otitis", "dolor de oreja", "oído izquierdo adolorido", "tengo algo en el oído", "dolor profundo oído", "oído inflamado"]'),
('H92.03', 'Otalgia, bilateral', 'Sin especificar', '["dolor en ambos oídos", "duelen los dos oídos", "dolor de oídos", "otitis bilateral", "infección en ambos oídos", "oídos tapados", "dolor de orejas", "pinchazos en los oídos", "siento presión en los oídos", "oídos inflamados", "tengo los oídos tapados"]'),
('H92.09', 'Otalgia, oído no especificado', 'Sin especificar', '["dolor de oído", "me duele el oído", "punzadas oído", "dolor agudo oído", "otitis", "oído lastimado", "oído hinchado", "tengo un dolor en la oreja", "molestia en el oído", "oído enfermo", "dolor intenso oído"]'),
('H92.10', 'Otorrea, oído no especificado', 'Sin especificar', '["supuración oído", "oído que suelta líquido", "oído supurando", "líquido en el oído", "oído que bota pus", "oído mojado", "infección con supuración", "oído que rezuma", "oído supurante", "oído supurativo", "secreción en el oído"]'),
('H92.11', 'Otorrea, oído derecho', 'Sin especificar', '["supuración oído derecho", "oído derecho supurando", "líquido en el oído derecho", "oído derecho que bota pus", "oído derecho mojado", "infección supurativa oído derecho", "rezuma el oído derecho", "secreción oído derecho", "oído derecho que suelta pus"]'),
('H92.12', 'Otorrea, oído izquierdo', 'Sin especificar', '["supuración oído izquierdo", "oído izquierdo supurando", "líquido en el oído izquierdo", "oído izquierdo que bota pus", "oído izquierdo mojado", "infección supurativa oído izquierdo", "rezuma el oído izquierdo", "secreción oído izquierdo", "oído izquierdo que suelta pus"]'),
('H92.13', 'Otorrea, bilateral', 'Sin especificar', '["supuración en ambos oídos", "oídos supurando", "líquido en los dos oídos", "oídos que botan pus", "oídos mojados", "infección supurativa bilateral", "rezuman los oídos", "secreción en ambos oídos", "pus en los oídos"]'),
('H92.20', 'Otorragia, oído no especificado', 'Sin especificar', '["sangre en el oído", "oído sangrando", "hemorragia oído", "oído sangrante", "sangre saliendo del oído", "oído lesionado con sangre", "sangrado de oído", "tengo sangre en la oreja", "oído herido sangrando"]'),
('H92.21', 'Otorragia, oído derecho', 'Sin especificar', '["sangre en el oído derecho", "oído derecho sangrando", "hemorragia oído derecho", "oído derecho sangrante", "sangre saliendo del oído derecho", "oído derecho herido", "sangrado de oído derecho", "oído derecho con sangre"]'),
('H92.22', 'Otorragia, oído izquierdo', 'Sin especificar', '["sangre en el oído izquierdo", "oído izquierdo sangrando", "hemorragia oído izquierdo", "oído izquierdo sangrante", "sangre saliendo del oído izquierdo", "oído izquierdo herido", "sangrado de oído izquierdo", "oído izquierdo con sangre"]'),
('H92.23', 'Otorragia, bilateral', 'Sin especificar', '["sangre en ambos oídos", "oídos sangrando", "hemorragia en ambos oídos", "sangre saliendo de los dos oídos", "sangrado bilateral de oídos", "oídos sangrantes", "tengo los oídos con sangre"]');
