INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('E03.0', 'Hipotiroidismo congénito con bocio difuso', 'Sin especificar', '["tiroides inflamada de nacimiento", "bocio al nacer", "cuello hinchado bebé", "problemas de tiroides congénitos", "tiroides agrandada neonatal", "bocio difuso congénito", "bocio neonatal", "garganta inflamada recién nacido", "hipotiroidismo de bebé", "tiroides lenta nacimiento", "hinchazón en el cuello bebé", "bocio simple", "hiperplasia tiroidea congénita", "bocio congénito", "fallo tiroideo congénito"]'),
('E03.1', 'Hipotiroidismo congénito sin bocio', 'Sin especificar', '["bebé con hipotiroidismo", "tiroides que no funciona al nacer", "hipotiroidismo neonatal", "falla tiroidea congénita", "bebé sin hormona tiroidea", "problemas tiroideos sin bocio", "déficit de hormona tiroidea al nacer", "tamiz neonatal alterado", "tiroides hipoactiva congénita", "hipotiroidismo primario congénito", "retraso crecimiento bebé", "desarrollo lento bebé", "fallo de glándula tiroides", "tiroides ausente al nacer"]'),
('E03.2', 'Hipotiroidismo debido a medicamentos y otras sustancias exógenas', 'Sin especificar', '["tiroides dañada por medicinas", "hipotiroidismo por fármacos", "tiroides lenta por pastillas", "efecto secundario tiroides", "medicamentos que afectan tiroides", "problemas tiroides por químicos", "hipotiroidismo inducido por fármacos", "litio y tiroides", "amiodarona tiroides", "tiroides por suplementos", "hipotiroidismo por medicación", "tiroides alterada por medicinas", "toxicidad tiroidea medicamentosa", "iatrogenia tiroidea"]'),
('E03.3', 'Hipotiroidismo posinfeccioso', 'Sin especificar', '["tiroides lenta tras infección", "hipotiroidismo después de virus", "tiroiditis post infecciosa", "problemas de tiroides después de enfermar", "tiroides inflamada por virus", "hipotiroidismo postviral", "tiroides tras enfermedad infecciosa", "daño tiroideo por infección", "tiroiditis subaguda", "baja tiroides post infección", "infección y tiroides", "secuela de tiroiditis"]'),
('E03.4', 'Atrofia de tiroides (adquirida)', 'Sin especificar', '["tiroides pequeña", "tiroides que se encogió", "atrofia tiroidea", "tiroides atrofiada", "tiroides seca", "desaparición de tiroides", "reducción de tamaño tiroides", "insuficiencia tiroidea", "tiroides inactiva", "tiroides que ya no trabaja", "tiroides pequeña por autoinmunidad", "encogimiento tiroides", "tiroides sin función", "hipotiroidismo atrófico"]'),
('E03.5', 'Coma mixedematoso', 'Sin especificar', '["coma por hipotiroidismo", "crisis tiroidea grave", "emergencia tiroidea", "mixedema grave", "hipotiroidismo severo", "pérdida de conciencia tiroides", "desmayo por tiroides", "mixedema comatoso", "insuficiencia tiroidea aguda", "baja extrema de hormona tiroidea", "choque hipotiroideo", "coma metabólico", "hipotiroidismo profundo", "emergencia endocrina", "crisis mixedematosa"]'),
('E03.8', 'Otros tipos de hipotiroidismo especificados', 'Sin especificar', '["tiroides lenta rara", "otros problemas de tiroides", "hipotiroidismo específico", "tiroides hipoactiva", "falta de hormona tiroidea", "trastornos tiroideos", "problemas glandulares", "metabolismo lento por tiroides", "tiroides sin diagnosticar", "hipotiroidismo no común", "disfunción tiroidea", "tiroides cansada", "anomalía tiroidea"]'),
('E03.9', 'Hipotiroidismo, no especificado', 'Sin especificar', '["tiroides lenta", "tiroides floja", "tiroides hipoactiva", "tengo la tiroides baja", "metabolismo lento", "hipotiroidismo", "tiroides cansada", "problemas de peso por tiroides", "hormona tiroidea baja", "siempre cansado tiroides", "hipotiroidismo primario", "deficiencia de tiroides", "baja producción de hormona", "la tiroides no me funciona", "nódulos o tiroides lenta"]');
