INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N44.00', 'Torsión de testículo, no especificado', 'Sin especificar', '["torsión testicular", "dolor de bolas", "dolor en los huevos", "testículo torcido", "dolor escrotal agudo", "emergencia testicular", "dolor de testículos", "pelotas hinchadas", "torsión de testículo", "dolor de gónadas", "dolor en el escroto", "urgencia urológica", "testículo girado", "dolor en la zona genital", "nudo en el testículo"]'),
('N44.01', 'Torsión extravaginal de cordón espermático', 'Sin especificar', '["torsión extravaginal", "torsión neonatal testicular", "cordón espermático torcido", "torsión testicular del recién nacido", "torsión escrotal extratesticular", "emergencia testicular neonatal", "testículo inflamado recién nacido", "problema de cordón espermático", "torsión testicular infantil", "dolor genital pediátrico", "torsión de cordón", "patología escrotal infantil"]'),
('N44.02', 'Torsión intravaginal de cordón espermático', 'Sin especificar', '["torsión intravaginal", "torsión de cordón espermático", "dolor súbito testicular", "torsión testicular adolescente", "torsión de testículo aguda", "torsión de pedículo testicular", "testículo que gira", "dolor agudo en bolsa escrotal", "emergencia urológica", "torsión intraescrotal", "torsión de testículo mayor", "dolor intenso de huevos", "torsión de cordón espermático", "obstrucción flujo testículo"]'),
('N44.03', 'Torsión de apéndice testicular', 'Sin especificar', '["torsión de la hidátide de Morgagni", "torsión de apéndice testicular", "dolor testicular localizado", "hidátide torcida", "dolor en el polo superior del testículo", "puntada en el testículo", "dolor de escroto leve", "torsión de apéndice", "punzadas en los huevos", "dolor genital", "inflamación de apéndice testicular", "signo del punto azul"]'),
('N44.04', 'Torsión de apéndice de epidídimo', 'Sin especificar', '["torsión de apéndice epididimario", "torsión del epidídimo", "dolor epididimario", "dolor escrotal", "torsión apéndice epididimario", "molestia en epidídimo", "dolor detrás del testículo", "inflamación de epidídimo", "dolor en la bolsa", "torsión de apéndice", "dolor genital inespecífico", "dolor al caminar testículo"]'),
('N44.1', 'Quiste de túnica albugínea de testículo', 'Sin especificar', '["quiste en el testículo", "bolita en el testículo", "tumor benigno testículo", "quiste de la túnica albugínea", "bulto en el escroto", "masa testicular benigna", "quiste escrotal", "bolita en la bolsa", "quiste albugíneo", "nódulo testicular", "bolita en el huevo", "quiste simple testículo"]'),
('N44.2', 'Quiste benigno de testículo', 'Sin especificar', '["quiste testicular", "bola en el testículo", "bulto benigno en el testículo", "quiste simple en gónada", "masa en la bolsa", "bolita en escroto", "quiste en los huevos", "tumor no canceroso testículo", "quiste epididimario", "nódulo benigno testicular", "quiste en el escroto", "bolita dura en el testículo"]'),
('N44.8', 'Otros trastornos no inflamatorios de testículo', 'Sin especificar', '["dolor crónico testicular", "problemas de testículos", "molestias en las bolas", "dolor en el escroto no inflamatorio", "atrofia testicular", "trastornos testiculares", "molestia en la zona genital", "dolor de gónadas", "problemas escrotales", "dolor de testículo crónico", "pesadez en los testículos", "dolor inguinal y testicular"]');
