INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D73.0', 'Hipoesplenismo', 'Sin especificar', '["bazo lento", "bazo vago", "bazo que no trabaja", "bazo atrofiado", "defensa baja", "inmunodeficiencia bazo", "bazo pequeño", "hipofunción esplénica", "bazo poco activo", "bazo inactivo", "bazo hipoactivo", "problemas de defensas", "bazo ausente funcionalmente", "bazo flojo"]'),
('D73.1', 'Hiperesplenismo', 'Sin especificar', '["bazo hiperactivo", "bazo loco", "bazo grande que destruye células", "bazo acelerado", "bazo que se come la sangre", "destrucción de plaquetas bazo", "anemia por bazo grande", "bazo sobreactivo", "hiperfunción esplénica", "bazo que trabaja de más", "bazo agrandado", "bazo destructor", "citopenia por bazo"]'),
('D73.2', 'Esplenomegalia congestiva crónica', 'Sin especificar', '["bazo hinchado", "bazo inflamado", "bazo grande", "hinchazón bajo las costillas", "dolor en el costado izquierdo", "bazo crecido", "bazo inflamado crónico", "bazo pesado", "hinchazón abdominal izquierda", "bazo congestionado", "esplenomegalia", "bazo inflamado por cirrosis", "bazo agrandado crónico"]'),
('D73.3', 'Absceso del bazo', 'Sin especificar', '["infección en el bazo", "pus en el bazo", "bazo con infección", "bazo infectado", "bolsa de pus en el bazo", "dolor fuerte en el bazo", "absceso esplénico", "infección esplénica", "bazo caliente", "fiebre y dolor de bazo", "inflamación con pus en el costado", "bazo purulento"]'),
('D73.4', 'Quiste del bazo', 'Sin especificar', '["bolita en el bazo", "bazo con quistes", "tumor de agua en el bazo", "quiste esplénico", "bolsa de líquido en el bazo", "bazo con masa", "bazo quístico", "bazo con bultos", "quiste en el costado izquierdo", "bazo raro", "quiste en el bazo", "masa en el bazo"]'),
('D73.5', 'Infarto de bazo', 'Sin especificar', '["infarto esplénico", "dolor repentino en el bazo", "bazo infartado", "muerte de tejido del bazo", "isquemia esplénica", "bazo bloqueado", "dolor agudo en el costado", "infarto en el costado", "ataque al bazo", "bazo que se muere", "necrosis del bazo", "dolor punzante bazo"]'),
('D73.81', 'Esplenomegalia neutropénica', 'Sin especificar', '["bazo grande y defensas bajas", "neutropenia y bazo crecido", "defensas bajas por bazo", "bazo y glóbulos blancos bajos", "bazo que baja las defensas", "síndrome esplenomegalia neutropénica", "bazo y neutrófilos bajos", "bazo inflamado con infección", "problema de bazo y sangre"]'),
('D73.89', 'Otras enfermedades del bazo', 'Sin especificar', '["problemas del bazo", "dolor de bazo", "mal de bazo", "enfermedad en el costado izquierdo", "problemas esplénicos", "dolor bajo las costillas", "molestias en el bazo", "bazo enfermo", "patología del bazo", "trastorno esplénico", "bazo raro", "cosas del bazo"]'),
('D73.9', 'Enfermedad del bazo, no especificada', 'Sin especificar', '["dolor en el bazo sin nombre", "problema de bazo", "molestia en el costado izquierdo", "no sé qué tengo en el bazo", "enfermedad de bazo sin diagnosticar", "dolor raro en el costado", "bazo extraño", "sospecha de bazo", "indefinido bazo", "molestia abdominal izquierda", "problema en el bazo", "dolor de costado indefinido"]');
