INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q13.0', 'Coloboma del iris', 'Sin especificar', '["ojo de gato", "pupila alargada", "fisura en el iris", "ojo deforme", "pupila rasgada", "defecto congénito del iris", "ojo con muesca", "malformación ocular", "pupila con forma de cerradura", "iris incompleto", "coloboma iridiano", "agujero en el iris", "mancha rara en el ojo", "ojo de felino"]'),
('Q13.1', 'Ausencia del iris', 'Sin especificar', '["aniridia", "sin iris", "ojo sin color", "ojo todo negro", "falta de iris", "pupila gigante", "ojo sin diafragma", "defecto ocular grave", "ojo ciego de nacimiento", "ausencia total de iris", "problemas de luz en el ojo", "ceguera al nacer", "malformación visual", "ojo despigmentado"]'),
('Q13.2', 'Otras malformaciones congénitas del iris', 'Sin especificar', '["iris raro", "deformidad en el iris", "ojos diferentes", "anomalía iridiana", "iris mal formado", "pupila extraña", "defecto de nacimiento en el ojo", "iris pequeño", "iris descentrado", "quiste en el iris", "iris con huecos", "problemas de iris", "malformación del color del ojo"]'),
('Q13.3', 'Opacidad corneal congénita', 'Sin especificar', '["ojo nublado al nacer", "mancha blanca en el ojo", "córnea opaca", "ojo lechoso", "nube en el ojo", "ojo blanco congénito", "córnea borrosa", "córnea turbia", "ojo con telilla", "defecto corneal", "problema de visión de nacimiento", "ojo con mancha blanca", "ceguera por opacidad"]'),
('Q13.4', 'Otras malformaciones corneales congénitas', 'Sin especificar', '["ojo deformado", "córnea pequeña", "córnea muy curva", "problemas de la parte frontal del ojo", "anomalía corneal", "córnea puntiaguda", "ojo con forma rara", "desarrollo incompleto del ojo", "córnea plana", "deformidad del ojo", "ojo de nacimiento", "malformación del segmento anterior"]'),
('Q13.5', 'Esclerótica azul', 'Sin especificar', '["ojos azules claros", "esclerótica tintada", "ojo azuloso", "esclera de color azul", "ojos de cristal", "esclerótica fina", "ojo con tinte azul", "enfermedad de los huesos de cristal ojo", "esclera delgada", "ojo pálido", "color raro en el blanco del ojo", "anomalía del blanco del ojo"]'),
('Q13.81', 'Anomalía de Rieger', 'Sin especificar', '["síndrome de Rieger", "glaucoma congénito", "ojo con fallas", "problemas de iris y córnea", "ojos con anomalías múltiples", "defectos oculares genéticos", "malformación del ángulo del ojo", "desarrollo ocular anormal", "ojos con malformaciones", "problema visual hereditario", "alteración del iris y la córnea"]'),
('Q13.89', 'Otras malformaciones congénitas del segmento anterior del ojo', 'Sin especificar', '["defecto en la parte delantera del ojo", "malformación frontal del ojo", "problema ocular al nacer", "anomalía del segmento anterior", "ojo mal desarrollado", "defectos oculares complejos", "problemas de córnea e iris", "fallas en la estructura ocular", "desarrollo anormal del ojo", "ojo con malformación", "defecto de nacimiento visual"]'),
('Q13.9', 'Malformación congénita del segmento anterior del ojo, no especificada', 'Sin especificar', '["ojo mal formado desde el nacimiento", "defecto visual congénito", "anomalía ocular de nacimiento", "problema en el frente del ojo", "malformación del ojo", "ojo con falla genética", "defecto al nacer en el ojo", "problema ocular", "malformación sin especificar", "anomalía en la parte frontal del ojo", "ojo raro"]');
