INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N04.0', 'Síndrome nefrótico con anomalía glomerular mínima', 'Sin especificar', '["síndrome nefrótico", "hinchazón de cara", "pies hinchados", "orina espumosa", "edema", "proteínas en la orina", "daño renal", "fallo renal", "retención de líquidos", "párpados hinchados", "niño con edema", "mal funcionamiento del riñón", "anomalía renal mínima", "problemas de filtración"]'),
('N04.1', 'Síndrome nefrótico con lesiones glomerulares focales y segmentarias', 'Sin especificar', '["glomeruloesclerosis focal y segmentaria", "nefropatía", "insuficiencia renal", "hinchazón generalizada", "orina con burbujas", "lesión en el riñón", "nefrosis", "pérdida de albúmina", "riñones que no filtran", "edema crónico", "inflamación renal", "proteinuria", "daño segmentario del glomérulo"]'),
('N04.20', 'Síndrome nefrótico con glomerulonefritis membranosa difusa, no especificada', 'Sin especificar', '["glomerulonefritis membranosa", "riñones enfermos", "exceso de proteína en orina", "hinchazón de tobillos", "edema grave", "enfermedad de los riñones", "filtro renal dañado", "nefritis", "síndrome nefrótico inespecífico", "acumulación de líquidos", "orina turbia"]'),
('N04.21', 'Nefropatía membranosa primaria con síndrome nefrótico', 'Sin especificar', '["nefropatía membranosa primaria", "autoanticuerpos renales", "orina espumosa", "edema idiopático", "daño en glomérulos", "insuficiencia renal progresiva", "proteína en la meada", "hinchazón de piernas", "riñones fallando", "nefritis membranosa", "problemas de riñón primarios"]'),
('N04.22', 'Nefropatía membranosa secundaria con síndrome nefrótico', 'Sin especificar', '["nefropatía secundaria", "daño renal por otra enfermedad", "hinchazón por nefritis", "edema secundario", "proteinuria severa", "orina con espuma", "riñones con lesiones", "complicación renal", "filtro del riñón roto", "hinchazón de cuerpo entero", "nefritis por otras causas"]'),
('N04.29', 'Otro síndrome nefrótico con glomerulonefritis membranosa difusa', 'Sin especificar', '["glomerulonefritis membranosa variante", "edema persistente", "orina espumante", "pérdida de proteínas por el riñón", "nefritis difusa", "falla de filtración renal", "hinchazón abdominal", "hinchazón en ojos", "insuficiencia del riñón", "nefrosis membranosa", "riñones inflamados"]'),
('N04.3', 'Síndrome nefrótico con glomerulonefritis proliferativa mesangial difusa', 'Sin especificar', '["glomerulonefritis mesangial", "proliferación mesangial", "orina con mucha espuma", "hinchazón de párpados", "edema en miembros inferiores", "riñón que pierde albúmina", "proteinuria masiva", "daño por proliferación renal", "enfermedad renal proliferativa", "hinchazón por retención", "fallo renal crónico"]'),
('N04.4', 'Síndrome nefrótico con glomerulonefritis proliferativa endocapilar difusa', 'Sin especificar', '["glomerulonefritis endocapilar", "nefritis postinfecciosa", "hinchazón repentina", "orina color oscuro", "orina con burbujas", "edema marcado", "riñones inflamados por proliferación", "daño capilar renal", "proteinuria elevada", "problemas graves de riñón", "inflamación de los glomérulos"]'),
('N04.5', 'Síndrome nefrótico con glomerulonefritis mesangiocapilar difusa', 'Sin especificar', '["glomerulonefritis membranoproliferativa", "nefritis mesangiocapilar", "riñones que no filtran bien", "edema grave y constante", "orina muy espumosa", "hinchazón de cara y cuerpo", "daño renal severo", "pérdida de proteínas", "nefritis crónica", "inflamación de los filtros renales", "insuficiencia renal"]'),
('N04.6', 'Síndrome nefrótico con enfermedad por depósitos densos', 'Sin especificar', '["enfermedad por depósitos densos", "nefritis por depósitos", "daño renal por C3", "edema por enfermedad renal", "orina espumosa crónica", "hinchazón de pies y manos", "proteínas perdidas en la orina", "lesión glomerular densa", "riñones fallando por depósitos", "fallo del filtro renal", "nefropatía severa"]'),
('N04.7', 'Síndrome nefrótico con glomerulonefritis semilunar difusa', 'Sin especificar', '["glomerulonefritis rápidamente progresiva", "glomerulonefritis extracapilar", "daño renal agudo", "edema severo", "orina con espuma", "fallo renal rápido", "pérdida de función renal", "inflamación grave del riñón", "crecimiento semilunar", "hinchazón corporal rápida", "nefropatía urgente"]'),
('N04.8', 'Síndrome nefrótico con otros cambios morfológicos', 'Sin especificar', '["nefritis atípica", "edema inespecífico", "orina con proteínas", "hinchazón general", "daño renal raro", "nefrosis", "riñones con cambios", "problemas de filtrado de orina", "edema por nefropatía", "inflamación renal difusa", "proteinuria persistente"]'),
('N04.9', 'Síndrome nefrótico con cambios morfológicos no especificados', 'Sin especificar', '["síndrome nefrótico inespecífico", "hinchazón general", "orina con espuma", "riñones que pierden proteína", "edema desconocido", "fallo renal sin causa clara", "hinchazón de cara", "hinchazón de pies", "daño en el riñón", "nefrosis sin especificar", "orina rara"]'),
('N04.A', 'Síndrome nefrótico con glomerulonefritis C3', 'Sin especificar', '["glomerulonefritis C3", "nefritis por complemento C3", "edema renal", "orina con espuma", "daño renal por C3", "hinchazón por nefritis", "proteinuria por C3", "riñones con depósitos C3", "enfermedad renal por complemento", "fallo renal por C3", "edema por nefropatía C3"]');
