INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('O08.0', 'Infección pélvica y del tracto genital después de un embarazo ectópico y molar', 'Sin especificar', '["infección matriz", "pus en la matriz", "fiebre después de aborto", "dolor bajo vientre post embarazo", "inflamación pélvica", "infección genital", "supuración vaginal", "mal olor vaginal post parto", "dolor de guata bajo", "infección post molar", "secreción vaginal infecciosa", "dolor en la bajovientre", "pelviperitonitis", "endometritis post embarazo", "fiebre puerperal", "infección en la zona íntima"]'),
('O08.1', 'Hemorragia tardía o excesiva después de un embarazo ectópico y molar', 'Sin especificar', '["sangrado excesivo", "hemorragia posparto", "pérdida de sangre post aborto", "sangrado abundante", "chorro de sangre", "sangrar mucho después de embarazo", "metrorragia", "sangrado tardío", "desangramiento", "flujo de sangre incontrolable", "sangrado anormal", "hemorragia uterina", "sangrado tipo regla fuerte", "pérdida hemática", "manchado post embarazo", "emergencia por sangrado"]'),
('O08.2', 'Embolia después de un embarazo ectópico y molar', 'Sin especificar', '["coágulo de sangre", "trombo", "embolia", "coágulos en la sangre", "obstrucción vascular", "embolismo", "tromboembolismo", "trombosis post embarazo", "dolor de pierna y pecho", "falta de aire por coágulo", "tapón en las venas", "embolia pulmonar post molar", "coágulo post operatorio", "riesgo de coágulo", "infarto por embolia", "problemas de circulación post aborto"]'),
('O08.3', 'Shock después de un embarazo ectópico y molar', 'Sin especificar', '["shock", "desmayo", "colapso", "shock hipovolémico", "shock séptico", "caída de presión", "desvanecimiento", "desmayarse", "estado de shock", "tensión muy baja", "descompensación", "shock post parto", "shock por pérdida de sangre", "desmayo súbito", "presión arterial baja", "pulso débil"]'),
('O08.4', 'Insuficiencia renal después de un embarazo ectópico y molar', 'Sin especificar', '["fallo renal", "riñones dejaron de funcionar", "insuficiencia renal", "dejar de orinar", "orina con sangre", "dolor de riñones", "problemas de riñón post embarazo", "fallo en los riñones", "edema renal", "orinar poco", "anuria", "creatinina alta", "riñones afectados post molar", "dolor lumbar post embarazo", "insuficiencia del riñón", "retención de líquidos por riñón"]'),
('O08.5', 'Trastornos metabólicos después de embarazo ectópico y molar', 'Sin especificar', '["desajuste metabólico", "desequilibrio electrolítico", "trastorno del metabolismo", "alteración química en sangre", "deshidratación severa", "desbalance mineral", "problemas metabólicos", "alteración de electrolitos", "acidosis post embarazo", "cambios en la sangre", "desequilibrio post molar", "cuerpo descompensado", "problemas de azúcar post embarazo", "descontrol metabólico", "alteración química", "anomalía metabólica"]'),
('O08.6', 'Lesión de órganos y tejidos pélvicos después de embarazo ectópico y molar', 'Sin especificar', '["daño en órganos internos", "perforación uterina", "lesión interna", "desgarro pélvico", "daño en la matriz", "lesión de tejidos", "herida interna", "complicación quirúrgica", "perforación de útero", "daño en ovarios", "dolor pélvico persistente", "tejido dañado post cirugía", "lesión vesical", "lesión ureteral", "trauma pélvico", "dolor abdominal intenso post embarazo"]'),
('O08.7', 'Otras complicaciones venosas después de un embarazo ectópico y molar', 'Sin especificar', '["problemas de venas", "flebitis", "venas inflamadas", "trombosis venosa", "inflamación de venas", "problemas circulatorios post embarazo", "varices post embarazo", "complicación venosa", "insuficiencia venosa", "dolor de venas", "venas tapadas", "formación de trombos", "afección vascular", "venas hinchadas", "problemas de circulación", "complicación de vasos sanguíneos"]'),
('O08.81', 'Paro cardiaco después de un embarazo ectópico y molar', 'Sin especificar', '["paro cardíaco", "corazón se detuvo", "infarto al corazón", "ataque al corazón", "parada cardiorrespiratoria", "corazón dejó de latir", "colapso cardíaco", "muerte súbita", "insuficiencia cardíaca", "problemas del corazón post embarazo", "paro del corazón", "desmayo cardiaco", "emergencia cardiaca", "falla cardiaca", "arritmia grave", "shock cardiaco"]'),
('O08.82', 'Sepsis después de un embarazo ectópico y molar', 'Sin especificar', '["sepsis", "infección generalizada", "septicemia", "infección en la sangre", "infección sistémica", "bacterias en la sangre", "shock séptico", "fiebre alta por infección", "infección grave post embarazo", "envenenamiento de la sangre", "infección general", "estado séptico", "fiebre por infección", "sepsis post molar", "infección peligrosa", "infección que se expandió"]'),
('O08.83', 'Infección del tracto urinario después de un embarazo ectópico y molar', 'Sin especificar', '["infección de orina", "cistitis", "ardor al orinar", "dolor al orinar", "orina turbia", "infección urinaria", "infección de vejiga", "ganas de orinar a cada rato", "orinar sangre", "ITU", "infección urinaria post embarazo", "dolor bajo vientre al orinar", "orina con mal olor", "ardor vaginal", "infección de conductos urinarios", "pujo urinario"]'),
('O08.89', 'Otras complicaciones después de un embarazo ectópico y molar', 'Sin especificar', '["problemas post embarazo", "complicaciones del embarazo molar", "efectos secundarios post molar", "complicaciones después de cirugía", "problemas de salud post ectópico", "mala evolución post quirúrgica", "dolencias después del embarazo", "complicaciones ginecológicas", "secuelas post embarazo", "reacciones post operación", "problemas imprevistos", "complicación postoperatoria", "después del embarazo ectópico", "problemas de salud", "complicación no especificada", "eventos adversos"]'),
('O08.9', 'Complicación no especificada después de un embarazo ectópico y molar', 'Sin especificar', '["complicación extraña", "problema no definido", "algo salió mal post embarazo", "complicación general", "problema sin nombre", "dolor post embarazo", "problemas después de molar", "complicación inespecífica", "síntomas post embarazo", "malestar después de ectópico", "complicación desconocida", "situación médica post embarazo", "problema post-quirúrgico", "complicación médica", "malestar persistente", "problema de salud tras embarazo"]');
