INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z11.0', 'Contacto para cribado de enfermedades infecciosas intestinales', 'Sin especificar', '["diarrea", "infección estomacal", "dolor de guata", "dolor de panza", "gastroenteritis", "bacterias intestinales", "parásitos", "cagalera", "chorrillo", "descomposición estomacal", "dolor de barriga", "intoxicación alimentaria", "análisis de heces", "coprocultivo", "infección gastrointestinal"]'),
('Z11.1', 'Contacto para cribado de tuberculosis respiratoria', 'Sin especificar', '["tuberculosis", "tisis", "tos con sangre", "tos crónica", "bacilo de koch", "prueba de tuberculosis", "esputo", "flema con sangre", "dolor al respirar", "tuberculosis pulmonar", "examen de flema", "tuberculosis activa", "prueba de Mantoux", "baciloscopia", "tos persistente"]'),
('Z11.2', 'Contacto para cribado de otras enfermedades bacterianas', 'Sin especificar', '["bacterias", "infección bacteriana", "análisis de sangre", "cultivo de bacterias", "foco infeccioso", "pus", "inflamación", "fiebre por bacterias", "infección generalizada", "antibióticos", "examen bacteriológico", "bacteriemia", "enfermedad bacteriana", "frotis", "infección oculta"]'),
('Z11.3', 'Contacto para cribado de infecciones de transmisión predominantemente de tipo sexual', 'Sin especificar', '["ETS", "ITS", "enfermedades venéreas", "chancro", "flujo vaginal anormal", "picazón genital", "ardor al orinar", "gonorrea", "sífilis", "clamidia", "infección de transmisión sexual", "prueba de ETS", "chequeo sexual", "dolor pélvico", "verrugas genitales"]'),
('Z11.4', 'Contacto para cribado del virus de inmunodeficiencia humana [VIH]', 'Sin especificar', '["VIH", "SIDA", "prueba de VIH", "test de Elisa", "cargas virales", "examen de sangre VIH", "defensas bajas", "inmunodeficiencia", "virus del sida", "chequeo de VIH", "diagnóstico temprano VIH", "test rápido VIH", "posible contagio VIH", "ventana inmunológica", "prevención VIH"]'),
('Z11.51', 'Contacto para cribado del virus del papiloma humano (VPH)', 'Sin especificar', '["VPH", "papiloma humano", "verrugas", "condilomas", "papanicolaou", "citología", "cáncer de cuello uterino", "virus de verrugas", "chequeo ginecológico VPH", "infección por VPH", "lesiones genitales", "prueba de ADN VPH", "colposcopia", "verrugas venéreas", "prevención papiloma"]'),
('Z11.52', 'Contacto para cribado de COVID-19', 'Sin especificar', '["coronavirus", "COVID", "test de COVID", "prueba de antígenos", "PCR", "fiebre", "pérdida de olfato", "pérdida de gusto", "tos seca", "dolor de cuerpo", "contagio de coronavirus", "hisopado", "chequeo COVID", "virus chino", "dolor de garganta"]'),
('Z11.59', 'Contacto para cribado de otras enfermedades víricas', 'Sin especificar', '["virus", "infección viral", "chequeo de virus", "virosis", "enfermedad por virus", "detección viral", "examen de sangre viral", "fiebre viral", "dolores virales", "contagio vírico", "perfil viral", "rastreo de virus", "diagnóstico de virosis", "prueba de anticuerpos", "síntomas virales"]'),
('Z11.6', 'Contacto para cribado de otras enfermedades por protozoos y helmintiasis', 'Sin especificar', '["parásitos", "lombrices", "gusanos", "amibas", "amebiasis", "bichos", "infección parasitaria", "examen de heces", "parásitos intestinales", "giardia", "helmintos", "lombrices intestinales", "picazón anal", "dolor abdominal por parásitos", "desparasitación"]'),
('Z11.7', 'Contacto para prueba de infección tuberculosa latente', 'Sin especificar', '["tuberculosis dormida", "tuberculosis latente", "prueba de Mantoux", "PPD", "tuberculosis oculta", "chequeo de tuberculosis", "infección de TB", "examen de tuberculosis", "rastreo de bacilo", "tuberculosis asintomática", "riesgo de tuberculosis", "prueba cutánea de tuberculina", "tuberculosis no activa", "diagnóstico de TB", "prevención de tuberculosis"]'),
('Z11.8', 'Contacto para cribado de otras enfermedades infecciosas y parasitarias', 'Sin especificar', '["infección", "contagio", "enfermedad infecciosa", "chequeo de infecciones", "diagnóstico de parásitos", "enfermedad contagiosa", "examen de enfermedades", "rastreo de bichos", "chequeo general de infecciones", "bacterias y virus", "rastreo epidemiológico", "perfil infeccioso", "sospecha de infección", "prueba de enfermedades", "estudio infeccioso"]'),
('Z11.9', 'Contacto para cribado de enfermedades infecciosas y parasitarias, no especificado', 'Sin especificar', '["chequeo médico", "prevención de enfermedades", "análisis general", "diagnóstico preventivo", "chequeo de salud", "prueba de tamizaje", "examen de rutina", "rastreo de enfermedades", "cribado de salud", "estudio de síntomas", "consulta de prevención", "chequeo de malestares", "detección temprana", "evaluación infecciosa", "chequeo general"]');
