INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('W88.0XXA', 'Exposición a rayos X, contacto inicial', 'Sin especificar', '["rayos x", "radiografía", "placa", "tomarme una placa", "chequeo con rayos", "accidente con rayos x", "radiación médica", "quemadura por rayos x", "exposición a radiación", "radioscopia", "radiólogo", "sobreexposición a radiación", "problema con rayos x", "choque radiológico", "daño por rayos x"]'),
('W88.0XXD', 'Exposición a rayos X, contacto sucesivo', 'Sin especificar', '["seguimiento radiografía", "control por radiación", "exposición repetida rayos x", "terapia radiológica", "segunda exposición rayos x", "chequeo post radiación", "consecuencias de rayos x", "efectos de radiación continua", "seguimiento médico radiación", "acumulación de radiación", "protocolo radiológico", "rayos x recurrentes", "continuación de radiación", "evaluación radiológica", "manejo tras exposición"]'),
('W88.0XXS', 'Exposición a rayos X, secuela', 'Sin especificar', '["efectos secundarios rayos x", "daños por radiación a largo plazo", "secuelas de radiografía", "complicaciones por rayos x", "enfermedad post radiación", "secuela radiológica", "cicatrices por radiación", "problemas de salud por rayos x", "efectos tardíos de radiación", "daño tisular por radiación", "cáncer por radiación", "reacción tardía a rayos x", "secuelas de exposición médica", "marcas de radiación", "dolor post radiografía"]'),
('W88.1XXA', 'Exposición a isótopos radiactivos, contacto inicial', 'Sin especificar', '["radiación nuclear", "accidente radiactivo", "contacto con isótopos", "material radiactivo", "contaminación radiactiva", "exposición a uranio", "radiación ionizante", "envenenamiento por radiación", "fuga radiactiva", "quemadura radiactiva", "material peligroso", "isótopos radiactivos", "accidente nuclear", "contacto con radiación", "exposición súbita a isótopos"]'),
('W88.1XXD', 'Exposición a isótopos radiactivos, contacto sucesivo', 'Sin especificar', '["tratamiento por radiación", "seguimiento contaminación radiactiva", "exposición continuada a isótopos", "manejo de materiales radiactivos", "protocolo de descontaminación", "terapia con isótopos", "exposición recurrente", "control de radioactividad", "observación tras contacto radiactivo", "seguimiento de isótopos", "tratamiento médico nuclear", "atención post radiación", "exposición laboral radiactiva", "monitoreo de isótopos", "proceso de radioterapia"]'),
('W88.1XXS', 'Exposición a isótopos radiactivos, secuela', 'Sin especificar', '["secuelas de radiación nuclear", "daño crónico por isótopos", "efectos a largo plazo de material radiactivo", "enfermedad post radiación", "secuelas por contacto con isótopos", "cáncer radiactivo", "problemas genéticos por radiación", "daño sistémico por isótopos", "tardíos efectos radiactivos", "complicaciones por contaminación", "secuela nuclear", "secuelas de exposición crónica", "daño tisular radiactivo", "efectos degenerativos por radiación", "síndrome de irradiación"]'),
('W88.8XXA', 'Exposición a otras radiaciones ionizantes, contacto inicial', 'Sin especificar', '["radiación ionizante", "exposición a rayos gamma", "contacto con radiación", "quemadura por radiación", "accidente con equipo emisor", "exposición a partículas", "radiación de alta energía", "accidente en laboratorio", "radiación industrial", "choque de radiación", "daño por radiación", "exposición accidental", "fuga de partículas", "fuente radiactiva", "contacto con radiación ionizante"]'),
('W88.8XXD', 'Exposición a otras radiaciones ionizantes, contacto sucesivo', 'Sin especificar', '["seguimiento por radiación ionizante", "manejo post exposición", "control de efectos de radiación", "continuación del tratamiento", "seguimiento médico tras radiación", "monitoreo post exposición", "atención por exposición accidental", "evaluación de radiación continuada", "procedimientos de descontaminación", "protocolo post radiación", "atención médica especializada", "manejo crónico de radiación", "revisión por exposición", "seguimiento de radiación ionizante", "terapia de soporte tras radiación"]'),
('W88.8XXS', 'Exposición a otras radiaciones ionizantes, secuela', 'Sin especificar', '["secuelas de radiación ionizante", "daños permanentes por radiación", "efectos secundarios de ionización", "complicaciones a largo plazo", "daño celular por radiación", "enfermedad tardía por exposición", "consecuencias de radiación", "secuela post ionización", "efectos crónicos de la radiación", "problemas de salud tardíos", "alteraciones post radiación", "secuelas de accidente radioactivo", "daños radioinducidos", "efectos en el cuerpo por radiación", "toxicidad por radiación"]');
