INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z57.0', 'Exposición ocupacional al ruido', 'Sin especificar', '["ruido en el trabajo", "zumbido en los oídos", "pitidos", "sordera profesional", "hipoacusia laboral", "daño auditivo", "ruido industrial", "no escucho bien", "tinitus", "fábrica ruidosa", "acúfenos", "pérdida de audición", "ruido excesivo", "tapones para oídos", "sordera por ruido"]'),
('Z57.1', 'Exposición ocupacional a radiación', 'Sin especificar', '["radiación en el trabajo", "rayos x", "material radiactivo", "peligro radiológico", "exposición nuclear", "quemaduras por radiación", "riesgo de cáncer por radiación", "radioactividad", "contaminación radiactiva", "blindaje radiológico", "trabajo con rayos", "efectos de radiación", "ionización", "exposición a radiación ionizante"]'),
('Z57.2', 'Exposición ocupacional al polvo', 'Sin especificar', '["polvo en el trabajo", "respirar polvo", "tos con polvo", "neumoconiosis", "pulmón de minero", "polvillo", "trabajo en cantera", "alergia al polvo industrial", "asma ocupacional", "tierra en los pulmones", "sílice", "partículas en el aire", "picazón por polvo", "tos seca"]'),
('Z57.31', 'Exposición ocupacional al humo de tabaco ambiental', 'Sin especificar', '["humo de cigarro", "fumador pasivo", "humo de tabaco", "aire viciado", "ambiente con humo", "olor a cigarro", "humo de segunda mano", "tos por humo", "irritación por tabaco", "trabajar entre fumadores", "humo ambiental", "asfixia por tabaco", "humo en la oficina"]'),
('Z57.39', 'Exposición ocupacional a otros contaminantes atmosféricos', 'Sin especificar', '["gases tóxicos", "aire contaminado", "vapores químicos", "humos industriales", "polución en el trabajo", "emanaciones", "respirar químicos", "falta de aire", "vaho tóxico", "contaminantes en el ambiente laboral", "olores fuertes", "solventes", "vapores irritantes"]'),
('Z57.4', 'Exposición ocupacional a agentes tóxicos en agricultura', 'Sin especificar', '["pesticidas", "insecticidas", "agroquímicos", "venenos agrícolas", "fumigación", "plaguicidas", "tóxicos en el campo", "contacto con herbicidas", "intoxicación por químicos", "trabajo en el agro", "veneno en cultivos", "fertilizantes tóxicos", "efectos de pesticidas"]'),
('Z57.5', 'Exposición ocupacional a agentes tóxicos en otras industrias', 'Sin especificar', '["químicos industriales", "solventes peligrosos", "ácidos", "metales pesados", "productos químicos", "intoxicación laboral", "contacto con sustancias tóxicas", "peligro químico", "manipulación de químicos", "vapores tóxicos", "quemaduras químicas", "exposición a químicos"]'),
('Z57.6', 'Exposición ocupacional a temperaturas extremas', 'Sin especificar', '["mucho calor", "mucho frío", "golpe de calor", "hipotermia", "trabajo al sol", "congelamiento", "estrés térmico", "cámaras frigoríficas", "trabajo en fundición", "deshidratación laboral", "trabajo extremo", "quemaduras por sol", "congelación"]'),
('Z57.7', 'Exposición ocupacional a vibración', 'Sin especificar', '["vibración en el cuerpo", "martillo neumático", "hormigueo en las manos", "manos dormidas", "síndrome de vibración", "daño por máquinas", "vibración de herramientas", "entumecimiento", "daño en los nervios", "vibración mano-brazo", "herramientas vibratorias", "temblor por trabajo"]'),
('Z57.8', 'Exposición ocupacional a otros factores de riesgo', 'Sin especificar', '["riesgo laboral", "peligro en el trabajo", "accidentes de trabajo", "exposición a riesgos", "trabajo peligroso", "seguridad industrial", "condiciones inseguras", "riesgo ocupacional", "peligro no especificado", "daño por trabajo", "entorno de riesgo"]'),
('Z57.9', 'Exposición ocupacional a factor de riesgo no especificado', 'Sin especificar', '["peligro desconocido", "no sé qué me causa daño", "riesgo de trabajo", "problema en el trabajo", "algo me afecta en el empleo", "factor desconocido", "exposición no clara", "peligro laboral", "enfermedad de trabajo", "riesgo sin especificar"]');
