INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B74.0', 'Filariasis debida a Wuchereria bancrofti', 'Sin especificar', '["elefantiasis", "filariasis linfática", "pie de elefante", "hinchazón de piernas", "edema linfático", "gusanos en la sangre", "parásitos tropicales", "inflamación de ganglios", "hidrocele", "linfedema", "picadura de mosquito", "enfermedad de los trópicos", "filarias", "filaria de bancroft", "piernas hinchadas"]'),
('B74.1', 'Filariasis debida a Brugia malayi', 'Sin especificar', '["filariasis malaya", "elefantiasis asiática", "parásitos en linfa", "hinchazón de extremidades", "gusano brugia", "edema por parásitos", "filaria tropical", "enfermedad de transmisión por mosquito", "inflamación linfática", "nódulos subcutáneos", "linfadenitis", "infección parasitaria", "hinchazón de pies", "fiebre filarial", "obstrucción de vasos linfáticos"]'),
('B74.2', 'Filariasis debida a Brugia timori', 'Sin especificar', '["filariasis de timor", "elefantiasis de la isla de timor", "parásitos de indonesia", "hinchazón severa", "filaria timori", "infección por nematodos", "inflamación de los vasos linfáticos", "edema crónico", "enfermedad parasitaria tropical", "gusanos en el sistema linfático", "linfedema severo", "hinchazón de piernas y pies", "picadura de insecto infectado", "dolor linfático", "filaria transmitida por mosquitos"]'),
('B74.3', 'Loasis', 'Sin especificar', '["gusano del ojo", "loa loa", "gusano africano del ojo", "hinchazón de calabar", "edema de calabar", "parásito que se mueve en la piel", "gusano debajo de la piel", "picazón en el ojo", "gusano en la conjuntiva", "hinchazón transitoria", "filaria de áfrica occidental", "infección por moscas", "parásito ocular", "movimiento bajo la piel", "picazón severa"]'),
('B74.4', 'Mansoneliasis', 'Sin especificar', '["infección por mansonella", "filaria de sangre", "parásito de américa latina", "gusanos mansonella", "infección por jejenes", "picadura de mosca negra", "dolor articular por parásitos", "fiebre mansoneliasis", "problemas cutáneos por filarias", "hinchazón moderada", "edema leve", "parásitos tropicales no especificados", "infección parasitaria endémica", "picazón generalizada", "filaria de la piel"]'),
('B74.8', 'Otras filariasis', 'Sin especificar', '["otras infecciones por filarias", "gusanos parásitos", "enfermedades parasitarias de la linfa", "infección por nematodos filariales", "enfermedades tropicales desatendidas", "infestación por gusanos", "parásitos en la piel y sangre", "filaria exótica", "linfedema tropical", "infecciones raras por parásitos", "picadura de vectores", "inflamación parasitaria", "hinchazón inexplicable", "parásitos transmitidos por picaduras", "diagnóstico de filariasis"]'),
('B74.9', 'Filariasis, no especificada', 'Sin especificar', '["infección por filaria", "tengo parásitos", "filaria sin especificar", "hinchazón de piernas", "edema de causa parasitaria", "gusanos en el cuerpo", "problema de vasos linfáticos", "infección por mosquito tropical", "hinchazón rara", "enfermedad parasitaria no identificada", "linfedema crónico", "presencia de gusanos microscópicos", "picazón y ronchas por parásitos", "hinchazón de escroto", "filaria desconocida"]');
