INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B57.0', 'Enfermedad de Chagas aguda con compromiso cardiaco', 'Sin especificar', '["mal de chagas", "chagas agudo", "picadura vinchuca", "bicho de monte", "barbeiro", "corazón inflamado", "miocarditis chagasica", "dolor en el pecho", "taquicardia", "fiebre por chagas", "picadura de chinche", "chupona", "infarto de chagas", "insuficiencia cardiaca chagásica"]'),
('B57.1', 'Enfermedad de Chagas aguda que no afecta al corazón', 'Sin especificar', '["chagas sin daños al corazón", "fase inicial de chagas", "picadura de vinchuca", "mal de chagas", "hinchazón en párpado", "signo de romaña", "chagoma de inoculación", "fiebre", "malestar general", "ganglios inflamados", "bicho que pica", "enfermedad de la chinche"]'),
('B57.2', 'Enfermedad de Chagas (crónica) que afecta al corazón', 'Sin especificar', '["chagas crónico", "miocardiopatía chagásica", "arritmias por chagas", "corazón grande", "cardiomegalia chagásica", "insuficiencia cardiaca", "palpitaciones", "dolor torácico", "desmayos", "mareos", "fallo del corazón", "daño cardiaco crónico", "mal de chagas avanzado"]'),
('B57.30', 'Enfermedad de Chagas con afectación del aparato digestivo, no especificada', 'Sin especificar', '["chagas digestivo", "problemas estomacales chagas", "mala digestión", "dificultad para tragar", "estreñimiento severo", "intestino inflamado", "dolor de guata", "dolor de panza", "dolor de barriga", "chagas crónico digestivo", "problemas intestinales", "bloqueo intestinal"]'),
('B57.31', 'Megaesófago en enfermedad de Chagas', 'Sin especificar', '["esófago grande", "dificultad al tragar", "comida se queda atorada", "disfagia", "no puedo pasar la comida", "esófago dilatado", "chagas esofágico", "regurgitación", "alimento atorado en el pecho", "esofagitis chagásica", "megaesófago"]'),
('B57.32', 'Megacolon en enfermedad de Chagas', 'Sin especificar', '["colon dilatado", "estreñimiento crónico", "intestino grande", "no puedo ir al baño", "impactación fecal", "megacolon", "barriga hinchada", "panza dura", "dolor abdominal crónico", "estreñimiento severo por chagas", "obstrucción intestinal"]'),
('B57.39', 'Otros tipos de afectación del aparato digestivo en la enfermedad de Chagas', 'Sin especificar', '["trastornos digestivos chagas", "gastritis chagásica", "problemas en el tubo digestivo", "malestar abdominal", "pesadez estomacal", "problemas para evacuar", "digestión lenta", "dolor de vientre", "afectación visceral chagas"]'),
('B57.40', 'Enfermedad de Chagas con afectación del sistema nervioso, no especificada', 'Sin especificar', '["chagas neurológico", "problemas cerebrales chagas", "daño en el sistema nervioso", "dolor de cabeza fuerte", "mareos", "confusión mental", "problemas motores", "chagas crónico sistema nervioso"]'),
('B57.41', 'Meningitis en enfermedad de Chagas', 'Sin especificar', '["meningitis chagasica", "inflamación de meninges", "dolor de cabeza intenso", "rigidez de nuca", "fiebre alta por chagas", "chagas en el cerebro", "infección de las meninges", "fotofobia", "náuseas por chagas"]'),
('B57.42', 'Meningoencefalitis en enfermedad de Chagas', 'Sin especificar', '["meningoencefalitis chagásica", "inflamación cerebral", "encefalitis", "convulsiones por chagas", "alteración del estado mental", "chagas agudo neurológico", "infección cerebral", "problemas de conciencia", "chagas grave"]'),
('B57.49', 'Otros tipos de afectación del sistema nervioso en la enfermedad de Chagas', 'Sin especificar', '["daño neurológico crónico chagas", "neuropatía chagásica", "hormigueo", "debilidad muscular", "alteraciones nerviosas", "fallo del sistema nervioso central", "problemas de coordinación", "daño en los nervios"]'),
('B57.5', 'Enfermedad de Chagas (crónica) que afecta otros órganos', 'Sin especificar', '["chagas sistémico", "chagas crónico multiorgánico", "afectación visceral", "chagas en otros órganos", "complicaciones por mal de chagas", "daño a órganos internos", "enfermedad multisistémica por chagas", "fase final de chagas"]');
