INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N52.01', 'Disfunción eréctil debida a insuficiencia arterial', 'Sin especificar', '["impotencia", "no se me para", "problemas de erección", "falla el miembro", "falta de riego", "problemas circulatorios pene", "pene flácido", "disfunción sexual masculina", "no levanta", "pene dormido", "falla vascular", "erección débil", "problemas de virilidad", "insuficiencia de sangre en el pene", "pene sin fuerza"]'),
('N52.02', 'Disfunción eréctil debida a enfermedad corpórea venooclusiva', 'Sin especificar', '["fuga venosa", "impotencia venosa", "se escapa la sangre", "no mantiene la erección", "pene pierde rigidez rápido", "problemas de retorno venoso", "erección que se desinfla", "falla en el mecanismo venooclusivo", "impotencia por escape de sangre", "dificultad para mantener el palo firme", "problemas de vena en el pene", "disfunción eréctil venosa"]'),
('N52.03', 'Disfunción eréctil por insuficiencia arterial y enfermedad corpórea venooclusiva combinadas', 'Sin especificar', '["impotencia mixta", "falla circulatoria y de retorno", "problemas vasculares combinados", "no me funciona el equipo", "erección insuficiente y breve", "pene que no rinde", "falla arterial y venosa", "impotencia severa", "problemas de irrigación y retención", "disfunción eréctil compleja", "el miembro no se mantiene duro", "circulación fallida en el pene"]'),
('N52.1', 'Disfunción eréctil debida a otras enfermedades clasificadas bajo otro concepto', 'Sin especificar', '["impotencia por diabetes", "falla eréctil por enfermedad", "erección afectada por salud", "impotencia secundaria", "problemas de erección por salud general", "no se levanta por enfermedad", "disfunción eréctil por causas orgánicas", "el miembro no responde por enfermedad", "problemas de virilidad por otras causas", "erección fallida", "impotencia sistémica"]'),
('N52.2', 'Disfunción eréctil inducida por fármacos', 'Sin especificar', '["impotencia por pastillas", "erección floja por medicamentos", "los remedios me bajan el líbido", "falla del miembro por fármacos", "efecto secundario sexual", "erección débil por antidepresivos", "no se para por la medicación", "problemas sexuales por fármacos", "la pastilla me deja el pene blando", "impotencia medicamentosa", "el tratamiento me quita la erección"]'),
('N52.31', 'Disfunción eréctil tras prostatectomía radical', 'Sin especificar', '["impotencia post operación de próstata", "no se me para después de quitar la próstata", "falla de erección tras cirugía radical", "problemas sexuales post prostatectomía", "miembro sin fuerza tras cirugía", "erección perdida por cáncer de próstata", "efectos post operatorios en el sexo", "quedé impotente tras la operación", "dificultad para erección tras prostatectomía", "problemas de erección postquirúrgicos"]'),
('N52.32', 'Disfunción eréctil tras cistectomía radical', 'Sin especificar', '["impotencia tras cirugía de vejiga", "no tengo erección después de cistectomía", "falla sexual por operación de vejiga", "problemas de virilidad tras cistectomía", "el miembro no se levanta post cirugía", "secuelas sexuales cistectomía", "erección afectada por cirugía pélvica", "impotencia postoperatoria", "problemas de función sexual tras cirugía"]'),
('N52.33', 'Disfunción eréctil tras cirugía uretral', 'Sin especificar', '["impotencia post cirugía uretra", "no se me para después de operar la uretra", "falla eréctil tras uretroplastia", "problemas de erección por cirugía uretral", "el pene no responde tras operación", "secuelas de cirugía en uretra", "impotencia tras corrección uretral", "erección débil por cirugía", "falla sexual post intervención uretral"]'),
('N52.34', 'Disfunción eréctil tras prostatectomía simple', 'Sin especificar', '["impotencia tras operación de próstata simple", "no tengo erecciones normales tras cirugía", "falla del miembro post próstata", "problemas sexuales después de quitar próstata", "el pene está flácido tras la cirugía", "impotencia post prostatectomía simple", "erección afectada tras operación", "falla de virilidad postoperatoria"]'),
('N52.35', 'Disfunción eréctil tras radioterapia', 'Sin especificar', '["impotencia por radiación", "no se me levanta tras la radioterapia", "falla de erección por rayos", "problemas de pene tras radioterapia", "erección dañada por radiación pélvica", "quedé impotente después de los rayos", "el miembro ya no funciona por radioterapia", "efectos sexuales de la radioterapia", "impotencia radioterápica"]'),
('N52.36', 'Disfunción eréctil tras tratamiento con semillas intersticiales', 'Sin especificar', '["impotencia tras braquiterapia", "no tengo erecciones por semillas de próstata", "falla sexual post semillas radiactivas", "problemas de virilidad post braquiterapia", "erección débil tras tratamiento con semillas", "el miembro no funciona post semillas", "impotencia post tratamiento prostático", "secuelas sexuales semillas intersticiales"]'),
('N52.37', 'Disfunción eréctil tras tratamiento por ablación de próstata', 'Sin especificar', '["impotencia tras ablación de próstata", "no se me para después de quemar la próstata", "falla sexual post ablación", "erección afectada por ablación prostática", "problemas de erección después de láser en próstata", "impotencia tras HIFU", "el miembro está blando tras ablación", "falla de erección por tratamiento prostático"]'),
('N52.39', 'Disfunción eréctil tras otro tipo de procedimiento y los no especificados', 'Sin especificar', '["impotencia post cirugía", "no me funciona tras la operación", "falla sexual después de procedimiento", "problemas de erección tras cirugía en la zona", "pene que no levanta tras intervención", "impotencia quirúrgica", "falla de virilidad tras tratamiento médico", "el equipo no responde tras cirugía"]'),
('N52.8', 'Otros tipos de disfunción eréctil masculina', 'Sin especificar', '["otros problemas de erección", "impotencia psicógena", "falla eréctil de causa mixta", "no se me para y no sé por qué", "problemas de erección poco comunes", "pene que no rinde", "disfunción eréctil inespecífica", "falla de erección", "impotencia no clasificada", "dificultad para mantener el miembro tieso"]'),
('N52.9', 'Disfunción eréctil masculina, no especificados', 'Sin especificar', '["impotencia", "no se me para", "problemas de erección", "disfunción sexual", "no levanta", "pene flácido", "problemas de virilidad", "falla en el sexo", "el miembro no funciona", "erección fallida", "impotencia sexual masculina", "pene dormido", "falla eréctil"]');
