INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B01.0', 'Meningitis debida a varicela', 'Sin especificar', '["meningitis por varicela", "inflamación cerebro varicela", "fiebre y rigidez de nuca", "complicación varicela", "dolor de cabeza intenso varicela", "fiebre alta y varicela", "meninges inflamadas", "infección del sistema nervioso central", "varicela grave", "dolor de cuello y granos", "fotofobia y varicela", "meningitis viral", "inflamación de las meninges"]'),
('B01.11', 'Encefalitis y encefalomielitis debidas a varicela', 'Sin especificar', '["encefalitis por varicela", "inflamación cerebral", "confusión mental varicela", "ataques o convulsiones", "somnolencia extrema", "alteración del estado mental", "daño cerebral por varicela", "complicación neurológica varicela", "encefalomielitis viral", "fiebre y delirio", "problemas de coordinación varicela", "vómitos y desorientación", "varicela complicada"]'),
('B01.12', 'Mielitis por varicela', 'Sin especificar', '["mielitis transversa", "inflamación de la médula espinal", "debilidad en las piernas", "pérdida de sensibilidad", "dolor de espalda y varicela", "hormigueo en extremidades", "problemas para caminar", "mielitis viral", "complicación de la varicela", "daño medular varicela", "pérdida de control de esfínteres", "parálisis parcial varicela", "entumecimiento varicela"]'),
('B01.2', 'Neumonía debida a varicela', 'Sin especificar', '["neumonía por varicela", "varicela en los pulmones", "falta de aire", "tos persistente", "dificultad para respirar", "dolor en el pecho al respirar", "fiebre alta y tos", "infección pulmonar", "complicación respiratoria", "pulmonía por varicela", "fatiga respiratoria", "asfixia varicela", "flemas y varicela"]'),
('B01.81', 'Queratitis por varicela', 'Sin especificar', '["queratitis varicela", "inflamación de la córnea", "ojo rojo y varicela", "dolor ocular", "visión borrosa", "sensibilidad a la luz", "lagrimeo constante", "infección en el ojo", "úlcera corneal varicela", "fotofobia ocular", "molestia en el globo ocular", "secreción ocular varicela", "ojos irritados varicela"]'),
('B01.89', 'Otras complicaciones de varicela', 'Sin especificar', '["varicela complicada", "infección de la piel varicela", "celulitis por varicela", "varicela grave", "sepsis varicela", "problemas secundarios varicela", "varicela difícil", "pústulas infectadas", "sobreinfección bacteriana", "manchas negras varicela", "fiebre persistente varicela", "varicela que no cura", "riesgos de la varicela"]'),
('B01.9', 'Varicela sin complicaciones', 'Sin especificar', '["varicela", "lechosa", "viruela loca", "china", "pica-pica", "granitos de agua", "ampollas en la piel", "fiebre y granos", "exantema variceloso", "picazón intensa", "ronchas con agua", "varicela común", "brote de varicela", "manchitas en el cuerpo"]');
