INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N28.0', 'Isquemia e infarto del riñón', 'Sin especificar', '["infarto renal", "dolor de riñones", "isquemia renal", "falla en el riego del riñón", "dolor en la espalda baja", "dolor lumbar intenso", "cólico renal", "problemas de circulación en riñón", "muerte de tejido renal", "dolor punzante en la cintura", "riñón que no recibe sangre", "dolor de costado", "inflamación lumbar", "dolor en los riñones", "obstrucción renal"]'),
('N28.1', 'Quiste de riñón, adquirido', 'Sin especificar', '["quiste en el riñón", "bolitas en el riñón", "quistes renales", "bolsa de líquido en el riñón", "dolor en la zona lumbar", "masa en el riñón", "dolor de costado", "problemas renales", "quiste simple", "hallazgo en ultrasonido", "dolor al orinar", "sensación de pesadez en la espalda", "dolor en la guata", "dolor en el flanco", "revisión de riñón"]'),
('N28.81', 'Hipertrofia de riñón', 'Sin especificar', '["riñón crecido", "riñón grande", "hipertrofia renal", "aumento de tamaño del riñón", "riñón inflamado", "crecimiento renal", "dolor en el riñón", "pesadez en la cintura", "malestar lumbar", "dolor al costado", "problemas de riñones", "riñón dilatado", "riñón hinchado", "dolor en el costado", "revisión de función renal"]'),
('N28.82', 'Megauréter', 'Sin especificar', '["uréter grande", "conducto de orina dilatado", "uréter dilatado", "ureter agrandado", "problema de orina", "dolor al orinar", "obstrucción de orina", "dolor en la vejiga", "flujo de orina lento", "malformación del uréter", "dolor en el vientre bajo", "infección urinaria recurrente", "dolor al evacuar orina", "ureteritis", "problemas de conductos urinarios"]'),
('N28.83', 'Nefroptosis', 'Sin especificar', '["riñón caído", "riñón desplazado", "caída de riñón", "riñón móvil", "dolor lumbar al estar de pie", "dolor de cintura", "dolor en la espalda baja", "dolor al moverse", "riñón fuera de lugar", "sensación de órgano suelto", "dolor en el costado", "bajón de riñón", "malestar abdominal", "dolor crónico de espalda", "desplazamiento renal"]'),
('N28.84', 'Pielitis quística', 'Sin especificar', '["quistes en la pelvis renal", "infección con quistes", "inflamación de la pelvis renal", "pielitis crónica", "dolor al orinar", "ardor al orinar", "dolor lumbar", "infecciones urinarias a repetición", "cistitis constante", "quistes en conductos", "dolor en el bajo vientre", "picazón urinaria", "orina con mal olor", "problemas en la pelvis renal", "inflamación de vías urinarias"]'),
('N28.85', 'Pieloureteritis quística', 'Sin especificar', '["quistes en uréter y riñón", "inflamación de pelvis y uréter", "quistes urinarios", "dolor al orinar", "ardor en la uretra", "dolor lumbar punzante", "orinar seguido", "infección de vías urinarias", "obstrucción de uréter", "quistes en el tracto urinario", "dolor en la guata", "malestar en la espalda baja", "dolor al costado", "problemas para orinar", "inflamación de conductos"]'),
('N28.86', 'Ureteritis quística', 'Sin especificar', '["quistes en el conducto urinario", "ureteritis con quistes", "dolor al orinar", "ardor al orinar", "dolor punzante en la pelvis", "obstrucción urinaria", "infecciones de orina frecuentes", "dolor en el bajo vientre", "orina con sangre", "dolor de uretra", "sensación de ardor genital", "dolor al vaciar vejiga", "molestia al orinar", "inflamación ureteral", "quistes en el uréter"]'),
('N28.89', 'Otros trastornos especificados de riñón y uréter', 'Sin especificar', '["problemas de riñones", "dolor de riñones", "dolor en los conductos de orina", "malestar renal", "dolor de cintura", "dolor de costado", "dificultad para orinar", "enfermedad renal", "dolor lumbar", "dolor al orinar", "molestia en el abdomen bajo", "problemas urinarios", "dolor de guata", "inflamación renal", "trastornos de las vías urinarias"]'),
('N28.9', 'Trastorno del riñón y del uréter, no especificado', 'Sin especificar', '["dolor de riñones", "problema en riñón", "dolor de espalda baja", "malestar de orina", "dolor al costado", "problemas de vías urinarias", "riñón que duele", "dolor en la cintura", "dolor en el vientre bajo", "molestia al orinar", "dolor lumbar", "problema urinario desconocido", "dolor en el flanco", "malestar renal", "dolor de guata"]');
