INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P61.0', 'Trombocitopenia neonatal transitoria', 'Sin especificar', '["plaquetas bajas en bebé", "sangrado neonatal", "petequias en recién nacido", "moretones en el recién nacido", "hematomas en bebé", "purpura neonatal", "plaquetopenia transitoria", "problemas de coagulación bebé", "sangrado de cordón umbilical", "trombocitopenia transitoria del lactante", "plaquetas bajas por anticuerpos maternos", "manchitas rojas en la piel bebé", "desorden plaquetario del recién nacido"]'),
('P61.1', 'Policitemia neonatal', 'Sin especificar', '["exceso de glóbulos rojos", "sangre espesa bebé", "bebé muy colorado", "bebé rojo", "poliglobulia del recién nacido", "hematocrito alto neonatal", "sangre viscosa", "bebé rubicundo", "hiperviscosidad sanguínea", "sangre cargada", "problemas de circulación neonatal", "exceso de eritrocitos bebé"]'),
('P61.2', 'Anemia de la prematuridad', 'Sin especificar', '["anemia del bebé prematuro", "bajo hierro bebé prematuro", "bebé pálido", "falta de sangre prematuro", "anemia del recién nacido prematuro", "bajo nivel de glóbulos rojos", "fatiga del prematuro", "cansancio del bebé", "anemia fisiológica del prematuro", "bebé bajito de defensas", "anemia por falta de madurez", "sangre del prematuro"]'),
('P61.3', 'Anemia congénita por hemorragia fetal', 'Sin especificar', '["pérdida de sangre antes de nacer", "hemorragia feto-materna", "bebé nace anémico", "sangrado antes del parto", "anemia por pérdida fetal", "anemia fetal grave", "pérdida de glóbulos rojos intrauterina", "bebé muy pálido al nacer", "hemorragia del feto", "choque hipovolémico neonatal", "anemia por desangramiento del feto"]'),
('P61.4', 'Otras anemias congénitas, no clasificadas bajo otro concepto', 'Sin especificar', '["anemia hereditaria bebé", "sangre pobre al nacer", "bebé con anemia desde el nacimiento", "anemia de origen desconocido recién nacido", "problemas de formación de sangre", "anemia neonatal rara", "bajo conteo sanguíneo", "bebé sin color", "anemia genética", "anemia del recién nacido no especificada"]'),
('P61.5', 'Neutropenia neonatal transitoria', 'Sin especificar', '["defensas bajas recién nacido", "neutrófilos bajos bebé", "infecciones en recién nacido", "leucocitos bajos bebé", "baja de defensas temporal", "neutropenia autoinmune neonatal", "problemas con glóbulos blancos", "defensas inmaduras", "bebés propensos a infecciones", "neutropenia benigna", "baja de glóbulos blancos"]'),
('P61.6', 'Otros trastornos neonatales transitorios de la coagulación', 'Sin especificar', '["problemas para coagular bebé", "sangrado del ombligo", "bebé que sangra mucho", "sangrado fácil recién nacido", "fallo en la coagulación", "trastorno de hemostasia", "hematomas injustificados", "sangrado después de la circuncisión", "problemas de sangrado neonatal", "coagulación lenta", "hemorragia neonatal"]'),
('P61.8', 'Otros trastornos hematológicos perinatales especificados', 'Sin especificar', '["problemas de sangre al nacer", "alteración de la sangre recién nacido", "trastornos de las células sanguíneas", "anomalía hematológica", "enfermedad de la sangre perinatal", "problemas sanguíneos del recién nacido", "complicación sanguínea al nacer", "desorden hematológico bebé", "sangre fuera de lo normal"]'),
('P61.9', 'Trastornos hematológicos perinatales, no especificados', 'Sin especificar', '["problema sanguíneo bebé", "enfermedad de la sangre recién nacido", "alteración analítica sangre", "estudio sanguíneo alterado", "problemas hematológicos del neonato", "trastorno de la sangre inespecífico", "anomalía en la sangre del bebé", "diagnóstico hematológico neonatal", "problemas de recién nacido", "sangre anormal en neonato"]');
