INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K74.00', 'Fibrosis hepática, no especificada', 'Sin especificar', '["hígado endurecido", "cicatrices en el hígado", "daño hepático", "hígado graso cicatrizado", "problemas de hígado", "hígado enfermo", "fibrosis del hígado", "dolor en el cuadrante superior derecho", "hinchazón abdominal", "hígado dañado", "fibrosis", "ictericia", "fatiga crónica", "transaminasas altas", "enfermedad hepática"]'),
('K74.01', 'Fibrosis hepática, fibrosis temprana', 'Sin especificar', '["principio de fibrosis", "daño hepático inicial", "cicatrices leves en el hígado", "etapa inicial de fibrosis", "hígado empezando a endurecerse", "grados iniciales de daño hepático", "fibrosis grado 1", "fibrosis grado 2", "hígado con marcas", "estrés hepático", "hígado graso no alcohólico", "fatiga", "molestia en la panza", "dolor bajo las costillas", "chequeo hígado"]'),
('K74.02', 'Fibrosis hepática, fibrosis avanzada', 'Sin especificar', '["fibrosis severa", "daño hepático severo", "hígado muy dañado", "cicatrización extensa del hígado", "fibrosis grado 3", "fibrosis grado 4", "pre-cirrosis", "hígado endurecido gravemente", "hígado tieso", "panza hinchada", "retención de líquidos", "ascitis", "piel amarilla", "ictérico", "insuficiencia hepática"]'),
('K74.1', 'Esclerosis hepática', 'Sin especificar', '["hígado esclerótico", "endurecimiento del hígado", "hígado rígido", "tejido cicatricial en hígado", "esclerosis del hígado", "cirrosis incipiente", "degeneración hepática", "hígado bloqueado", "mala función hepática", "hinchazón de guata", "dolor de hígado", "abdomen inflamado", "ictericia", "malestar general", "hígado enfermo"]'),
('K74.2', 'Fibrosis hepática con esclerosis hepática', 'Sin especificar', '["fibrosis y esclerosis hepática", "hígado cicatrizado y endurecido", "daño hepático crónico", "hígado rígido y dañado", "enfermedad esclerótica del hígado", "hígado muy mal", "complicación hepática", "hígado endurecido", "cicatrices profundas", "fallo hepático", "dolor abdominal", "hinchazón", "malestar en la panza", "cuerpo amarillo", "análisis hepáticos alterados"]'),
('K74.3', 'Cirrosis biliar primaria', 'Sin especificar', '["cirrosis biliar", "daño en conductos biliares", "colangitis destructiva", "picazón en la piel", "prurito por hígado", "cansa excesivo", "cirrosis autoinmune", "hígado biliar", "ojos amarillos", "ictericia obstructiva", "dolor bajo la costilla derecha", "orina oscura", "heces claras", "problemas de vesícula y hígado", "cirrosis CBP"]'),
('K74.4', 'Cirrosis biliar secundaria', 'Sin especificar', '["cirrosis por obstrucción biliar", "obstrucción de vías biliares", "cirrosis por piedras en la vesícula", "daño hepático por cálculos", "hígado con obstrucción", "problemas de conductos biliares", "ictericia biliar", "dolor de vesícula crónico", "hinchazón de vientre", "hígado inflamado", "infección biliar", "dolor agudo en la guata", "cirrosis post-obstructiva", "problemas de drenaje biliar", "hígado biliar secundario"]'),
('K74.5', 'Cirrosis biliar, no especificada', 'Sin especificar', '["problema biliar en el hígado", "daño biliar hepático", "cirrosis de origen biliar", "obstrucción biliar", "hígado con mala bilis", "ictericia", "dolor hepático biliar", "cirrosis", "hígado enfermo por bilis", "picazón de piel", "hinchazón abdominal", "molestias en el abdomen", "problemas de conductos", "fallo del hígado", "hígado graso o biliar"]'),
('K74.60', 'Cirrosis de hígado no especificada', 'Sin especificar', '["cirrosis", "hígado cirrótico", "hígado destruido", "hígado con cicatrices irreversibles", "panza llena de líquido", "ascitis", "hígado encogido", "hígado dañado por alcohol", "cirrosis hepática", "piel amarilla", "ojos amarillos", "hinchazón de guata", "hinchazón de barriga", "cansancio extremo", "hígado enfermo terminal"]'),
('K74.69', 'Otras cirrosis de hígado', 'Sin especificar', '["cirrosis alcohólica", "cirrosis post-hepatitis", "hígado dañado por virus", "cirrosis autoinmune", "hígado cirrótico severo", "daño hepático crónico", "enfermedad del hígado", "hígado descompensado", "insuficiencia hepática", "fallo de hígado", "cirrosis criptogénica", "ictericia severa", "hinchazón de piernas y panza", "dolor abdominal constante", "complicación hepática crónica"]');
