INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A39.0', 'Meningitis meningocócica', 'Sin especificar', '["meningitis", "inflamación de las meninges", "fiebre con rigidez de nuca", "dolor de cabeza fuerte", "nuca tiesa", "infección en el cerebro", "meningococo", "bacteria en la cabeza", "fiebre y manchas en la piel", "meningitis bacteriana", "fuerte dolor de cuello", "fotofobia", "rigidez cervical", "meningitis aguda", "infección por neisseria"]'),
('A39.1', 'Síndrome de Waterhouse-Friderichsen', 'Sin especificar', '["fallo suprarrenal por meningococo", "shock por meningococo", "hemorragia adrenal", "manchas moradas en la piel", "púrpura fulminante", "insuficiencia suprarrenal aguda", "colapso circulatorio rápido", "sepsis grave", "síndrome hemorrágico por bacteria", "necrosis de glándulas suprarrenales", "shock séptico fulminante", "manchas negras en el cuerpo", "fallo multiorgánico rápido"]'),
('A39.2', 'Meningococemia aguda', 'Sin especificar', '["infección generalizada por meningococo", "sepsis por meningococo", "sangre infectada con bacterias", "manchas rojas en el cuerpo", "erupción petequial", "fiebre alta repentina", "bacteriemia por meningococo", "meningococemia fulminante", "infección de la sangre", "choque séptico", "fiebre y manchas moradas", "septicemia aguda", "meningococo en la sangre"]'),
('A39.3', 'Meningococemia crónica', 'Sin especificar', '["meningococemia persistente", "fiebre recurrente por meningococo", "articulaciones doloridas por infección", "erupciones cutáneas crónicas", "bacteriemia prolongada", "infección meningocócica latente", "fiebre que va y viene", "dolor de huesos por bacteria", "meningococo recurrente", "infección de larga duración", "nódulos en la piel", "fiebre y dolor articular"]'),
('A39.4', 'Meningococemia, no especificada', 'Sin especificar', '["infección por meningococo", "bacterias en la sangre", "sepsis meningocócica", "fiebre por bacteria", "septicemia por neisseria", "infección sistémica bacteriana", "presencia de meningococo en el cuerpo", "infección bacteriana grave", "bacteriemia no clasificada", "fiebre, escalofríos y manchas"]'),
('A39.50', 'Carditis meningocócica, no especificada', 'Sin especificar', '["corazón inflamado por meningococo", "infección del corazón", "daño cardíaco por bacteria", "dolor en el pecho por infección", "inflamación cardíaca bacteriana", "carditis bacteriana", "meningococo en el corazón", "miocardio afectado por infección", "problemas cardíacos por sepsis", "dolor precordial por bacteria"]'),
('A39.51', 'Endocarditis meningocócica', 'Sin especificar', '["infección en las válvulas del corazón", "endocarditis bacteriana", "soplo cardíaco por infección", "fiebre y dolor de pecho", "bacterias en el endocardio", "meningococo en válvulas cardíacas", "infección de la capa interna del corazón", "fiebre prolongada y soplos", "daño valvular por bacteria", "endocarditis subaguda"]'),
('A39.52', 'Miocarditis meningocócica', 'Sin especificar', '["inflamación del músculo cardíaco", "miocardio inflamado", "insuficiencia cardíaca por infección", "dolor en el pecho", "latidos irregulares por bacteria", "meningococo en el músculo del corazón", "fatiga y falta de aire", "inflamación cardíaca por meningococo", "daño muscular en el corazón", "arritmias por infección"]'),
('A39.53', 'Pericarditis meningocócica', 'Sin especificar', '["inflamación de la capa que cubre el corazón", "pericardio inflamado", "dolor punzante en el pecho", "pinchazos en el pecho", "dolor al respirar profundo", "infección del pericardio", "frote pericárdico", "derrame pericárdico", "dolor cardíaco que alivia al inclinarse", "meningococo en la bolsa del corazón"]'),
('A39.81', 'Encefalitis meningocócicas', 'Sin especificar', '["inflamación del cerebro por meningococo", "meningoencefalitis", "confusión mental por infección", "alteración del estado de conciencia", "meningitis con encefalitis", "convulsiones por bacteria", "daño cerebral por meningococo", "delirio por infección", "infección del sistema nervioso central", "fiebre y alteración mental"]'),
('A39.82', 'Neuritis retrobulbar meningocócica', 'Sin especificar', '["inflamación del nervio óptico", "dolor detrás del ojo", "pérdida de visión por infección", "visión borrosa por meningococo", "neuritis óptica bacteriana", "dolor al mover el ojo", "ceguera repentina por infección", "nervio del ojo inflamado", "dolor ocular profundo", "meningococo y visión"]'),
('A39.83', 'Artritis meningocócica', 'Sin especificar', '["dolor en articulaciones por meningococo", "inflamación de rodillas o codos", "articulaciones hinchadas por bacteria", "reumatismo por infección", "artritis infecciosa", "articulación con pus", "meningococo en las articulaciones", "dolor articular severo", "artritis aguda", "hinchazón de manos y pies"]'),
('A39.84', 'Artritis posmeningocócica', 'Sin especificar', '["dolor articular después de meningitis", "secuelas de meningitis en articulaciones", "inflamación articular tras infección", "artritis reactiva meningocócica", "rigidez articular post-infección", "dolor en coyunturas después de estar enfermo", "secuela de infección por meningococo", "articulaciones tiesas después de la fiebre", "inflamación crónica post-bacteriana"]'),
('A39.89', 'Otras infecciones meningocócicas', 'Sin especificar', '["complicaciones por meningococo", "infección rara por neisseria", "neumonía meningocócica", "sinusitis por meningococo", "infección generalizada", "afectación por bacteria meningocócica", "complicación bacteriana inespecífica", "foco infeccioso por meningococo", "meningococo en otras partes del cuerpo"]'),
('A39.9', 'Infección meningocócica, no especificada', 'Sin especificar', '["enfermedad por meningococo", "contagio por bacteria", "infección bacteriana", "meningococo en el cuerpo", "cuadro infeccioso por meningococo", "sospecha de infección", "fiebre por bacteria no especificada", "bacterias en sangre o tejidos", "meningococemia sin especificar", "infección grave por neisseria meningitidis"]');
