INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D09.0', 'Carcinoma in situ de vejiga', 'Sin especificar', '["cáncer de vejiga", "tumor en la vejiga", "cáncer in situ", "sangre en la orina", "dolor al orinar", "ardor al hacer pipí", "cáncer precoz de vejiga", "lesión vesical", "neoplasia vesical", "tumor maligno incipiente", "cáncer de orina", "bulto en vejiga", "carcinoma vesical", "cáncer localizado", "tumor no invasivo"]'),
('D09.10', 'Carcinoma in situ de órgano urinario no especificado', 'Sin especificar', '["cáncer vías urinarias", "tumor tracto urinario", "cáncer en los riñones o vejiga", "lesión vías urinarias", "carcinoma urinario", "cáncer incipiente urinario", "tumor en el aparato urinario", "sangrado urinario", "dolor de orines", "neoplasia urinaria", "cáncer primario de vías urinarias", "lesión maligna localizada", "problemas de orina", "tumor in situ", "cáncer vías bajas"]'),
('D09.19', 'Carcinoma in situ de otros órganos urinarios', 'Sin especificar', '["cáncer uréter", "tumor en la uretra", "carcinoma de uréter", "lesión en vías urinarias", "tumor incipiente de uretra", "cáncer de conducto urinario", "carcinoma in situ uretral", "neoplasia de uretra", "tumor primario uréter", "lesión maligna uretra", "cáncer de las vías de salida", "masa en la uretra", "carcinoma de pelvis renal", "tumor en pelvis renal", "lesión ureteral"]'),
('D09.20', 'Carcinoma in situ de ojo no especificado', 'Sin especificar', '["cáncer en el ojo", "tumor en el ojo", "lesión ocular", "mancha en el ojo", "cáncer ocular", "neoplasia de ojo", "tumor del globo ocular", "carcinoma de ojo", "bulto en el ojo", "cáncer párpado", "lesión maligna en ojo", "tumor in situ ocular", "melanoma ocular in situ", "cáncer de córnea", "carcinoma conjuntival"]'),
('D09.21', 'Carcinoma in situ de ojo derecho', 'Sin especificar', '["cáncer ojo derecho", "tumor ojo derecho", "lesión ojo derecho", "cáncer del ojo diestro", "ojo derecho con cáncer", "carcinoma in situ ocular derecho", "masa en ojo derecho", "tumor maligno localizado ojo derecho", "carcinoma de párpado derecho", "cáncer de retina ojo derecho", "neoplasia ocular derecha", "cáncer ocular dextro", "ojo derecho afectado", "lesión en el ojo derecho", "tumor ocular derecho"]'),
('D09.22', 'Carcinoma in situ de ojo izquierdo', 'Sin especificar', '["cáncer ojo izquierdo", "tumor ojo izquierdo", "lesión ojo izquierdo", "cáncer del ojo siniestro", "ojo izquierdo con cáncer", "carcinoma in situ ocular izquierdo", "masa en ojo izquierdo", "tumor maligno localizado ojo izquierdo", "carcinoma de párpado izquierdo", "cáncer de retina ojo izquierdo", "neoplasia ocular izquierda", "cáncer ocular zurdo", "ojo izquierdo afectado", "lesión en el ojo izquierdo", "tumor ocular izquierdo"]'),
('D09.3', 'Carcinoma in situ de tiroides y otras glándulas endocrinas', 'Sin especificar', '["cáncer de tiroides", "nódulo tiroideo", "tumor en la tiroides", "cáncer de glándulas", "cáncer endocrino", "nudo en la garganta", "hinchazón de tiroides", "bocio maligno", "carcinoma tiroideo", "cáncer glándula paratiroides", "neoplasia endocrina in situ", "bulto en el cuello", "cáncer hormonal", "tumor de tiroides", "lesión tiroidea"]'),
('D09.8', 'Carcinoma in situ de otras localizaciones especificadas', 'Sin especificar', '["cáncer en otras partes", "tumor localizado", "carcinoma in situ raro", "cáncer en sitio específico", "tumor en sitio no común", "cáncer primario localizado", "lesión maligna en órgano", "tumor in situ no habitual", "neoplasia localizada en otro sitio", "cáncer en zona especificada", "tumor en ubicación extraña", "carcinoma de localización específica", "masa cancerosa in situ", "lesión precancerosa localizada", "cáncer de sitio desconocido"]'),
('D09.9', 'Carcinoma in situ, localización no especificada', 'Sin especificar', '["cáncer in situ", "tumor de origen desconocido", "cáncer sin especificar", "tumor maligno localizado", "cáncer sin sitio", "carcinoma de ubicación incierta", "tumor sin localizar", "masa cancerosa in situ", "neoplasia in situ", "cáncer primario oculto", "cáncer inespecífico", "tumor en parte no definida", "carcinoma localizado", "cáncer oculto", "tumor incipiente sin especificar"]');
