INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z15.01', 'Susceptibilidad genética a neoplasia maligna de mama', 'Sin especificar', '["cáncer de seno", "herencia cáncer mama", "gen BRCA", "bolita en el pecho", "tumor mamario hereditario", "riesgo genético pecho", "mutación cáncer seno", "cáncer de teta", "antecedentes familiares mama", "cáncer de pechuga", "prevención cáncer seno", "test genético cáncer mama", "familia con cáncer de mama", "predisposición genética teta"]'),
('Z15.02', 'Susceptibilidad genética a neoplasia maligna de ovario', 'Sin especificar', '["cáncer de ovarios hereditario", "riesgo genético ovarios", "tumor en ovarios familiar", "cáncer ginecológico hereditario", "herencia cáncer ovario", "predisposición genética ovarios", "dolor en ovarios constante", "mutación genética ovario", "historial familiar cáncer ovario", "detección precoz cáncer ovarios", "genética ginecológica", "cáncer de ovarios joven"]'),
('Z15.03', 'Susceptibilidad genética a neoplasia maligna de próstata', 'Sin especificar', '["cáncer de próstata familiar", "herencia cáncer próstata", "riesgo genético próstata", "predisposición cáncer próstata", "problemas de próstata hereditarios", "tumor próstata genético", "antecedentes familiares próstata", "cáncer de la próstata", "genética cáncer masculino", "examen próstata hereditario", "padre con cáncer próstata", "riesgo de cáncer prostático"]'),
('Z15.04', 'Susceptibilidad genética a neoplasia maligna de endometrio', 'Sin especificar', '["cáncer de útero hereditario", "predisposición cáncer endometrio", "cáncer de matriz genético", "herencia cáncer de útero", "riesgo genético endometrio", "tumor endometrio familiar", "antecedentes matriz", "cáncer endometrial hereditario", "problemas de útero genéticos", "genética cáncer ginecológico", "cáncer en la matriz", "detección hereditaria útero"]'),
('Z15.09', 'Susceptibilidad genética a otra neoplasia maligna', 'Sin especificar', '["cáncer hereditario", "genética del cáncer", "riesgo genético tumores", "predisposición familiar cáncer", "historia familiar de cáncer", "mutaciones cancerígenas", "síndromes de cáncer familiar", "herencia de tumores", "gen oncogénico", "riesgo de neoplasia", "predisposición genética neoplasias", "cáncer en la familia", "asesoramiento genético cáncer"]'),
('Z15.1', 'Susceptibilidad genética a epilepsia y trastornos del desarrollo neurológico', 'Sin especificar', '["epilepsia hereditaria", "convulsiones genéticas", "ataques epilépticos familiares", "problemas de desarrollo neurológico", "genética de la epilepsia", "desarrollo cerebral genético", "predisposición a convulsiones", "trastorno neurológico hereditario", "atraso en el desarrollo genético", "ataques de la enfermedad sagrada", "herencia de trastornos del sistema nervioso", "genética y retraso madurativo", "epilepsia familiar"]'),
('Z15.2', 'Susceptibilidad genética a la obesidad', 'Sin especificar', '["tendencia genética a engordar", "obesidad hereditaria", "gen de la obesidad", "familia con obesidad", "predisposición a ser gordo", "genética del sobrepeso", "por qué no bajo de peso", "herencia de la gordura", "metabolismo lento hereditario", "obesidad familiar", "problema genético de peso", "predisposición a la obesidad", "genética y sobrepeso"]'),
('Z15.81', 'Susceptibilidad genética a neoplasia endocrina múltiple [NEM]', 'Sin especificar', '["neoplasia endocrina múltiple", "NEM", "tumores en glándulas", "genética endocrina", "síndrome endocrino hereditario", "cáncer de glándulas familiar", "problemas hormonales genéticos", "predisposición a tumores endocrinos", "herencia glándulas endócrinas", "trastorno endocrino múltiple", "adenomas múltiples", "genética de tumores múltiples"]'),
('Z15.89', 'Susceptibilidad genética a otra enfermedad', 'Sin especificar', '["predisposición genética a enfermedades", "enfermedades de familia", "carga genética", "herencia genética enfermedades", "genes enfermos", "antecedentes familiares de salud", "riesgo genético", "tendencia a enfermarse", "mapa genético de enfermedades", "problemas genéticos ocultos", "susceptibilidad hereditaria", "genética médica", "historial genético"]');
