INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q12.0', 'Catarata congénita', 'Sin especificar', '["cataratas de nacimiento", "ojos nublados recién nacido", "bebé no ve bien", "mancha blanca en el ojo del bebé", "cristalino opaco congénito", "visión borrosa infantil", "pupila blanca bebé", "leucoma congénito", "ojos lechosos", "nube en el ojo", "problemas de visión al nacer", "ceguera infantil", "opacidad del lente", "catarata hereditaria", "bebé con ojos raros"]'),
('Q12.1', 'Luxación congénita del cristalino', 'Sin especificar', '["lente del ojo movido", "cristalino fuera de lugar", "ectopia lentis", "cristalino desplazado al nacer", "ojo con lente suelto", "visión inestable bebé", "movimiento del lente ocular", "luxación del cristalino", "subluxación congénita", "problemas de enfoque congénitos", "cristalino descentrado", "ojo tembloroso", "falla visual del niño", "anomalía de posición del cristalino", "defecto del lente ocular"]'),
('Q12.2', 'Coloboma del cristalino', 'Sin especificar', '["ojo con muesca", "falta de tejido ocular", "cristalino con hendidura", "pupila con forma de cerradura", "coloboma ocular", "defecto del cristalino", "agujero en el ojo", "falta un trozo de iris o cristalino", "malformación del cristalino", "ojo incompleto", "anomalía congénita ocular", "falla en el desarrollo del ojo", "ojo en forma de lágrima", "coloboma del lente", "desarrollo ocular incompleto"]'),
('Q12.3', 'Afaquia congénita', 'Sin especificar', '["nacido sin cristalino", "ojo sin lente", "falta el cristalino al nacer", "ausencia de lente intraocular", "afaquia infantil", "ojo sin foco", "defecto visual grave al nacer", "problema del desarrollo ocular", "ausencia congénita del lente", "ojo sin capacidad de enfoque", "anomalía ocular de nacimiento", "falta lente interno", "problema estructural del ojo", "ceguera por falta de cristalino", "ausencia de lente ocular"]'),
('Q12.4', 'Esferofaquia', 'Sin especificar', '["lente redondo", "cristalino esférico", "lente del ojo muy pequeño y redondo", "deformidad del cristalino", "anomalía de forma del cristalino", "cristalino abombado", "ojo con lente esférico", "defecto congénito del lente", "esferofaquia congénita", "problema de refracción bebé", "miopía severa por forma del lente", "cristalino hipermetrópico", "alteración del lente ocular", "forma anormal del lente", "cristalino como esfera"]'),
('Q12.8', 'Otras malformaciones congénitas del cristalino', 'Sin especificar', '["problemas raros del cristalino", "anomalía del lente del ojo", "malformación ocular congénita", "defecto raro en el lente", "problema de visión de nacimiento", "alteración del cristalino bebé", "ojo deforme", "problemas oculares del niño", "defecto congénito del cristalino", "malformación ocular", "problema de nacimiento en el ojo", "falla del cristalino", "anomalía inespecífica del lente", "problema visual congénito", "defecto estructural del ojo"]'),
('Q12.9', 'Malformación congénita del cristalino, no especificada', 'Sin especificar', '["problema del cristalino no identificado", "defecto de nacimiento en el ojo", "malformación del ojo sin definir", "anomalía ocular de nacimiento", "problema visual del bebé", "daño congénito en el cristalino", "enfermedad del ojo al nacer", "defecto de lente ocular no especificado", "falla del ojo congénita", "problema en el cristalino", "bebé con problema ocular", "diagnóstico ocular confuso", "malformación no clasificada del lente", "anomalía de nacimiento del cristalino", "problema ocular del recién nacido"]');
