INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('G31.01', 'Enfermedad de Pick', 'Sin especificar', '["demencia de Pick", "atrofia lobular", "demencia frontotemporal", "problemas de personalidad", "cambios de conducta", "pérdida de memoria", "trastornos del lenguaje", "afasia", "atrofia cerebral", "desinhibición social", "deterioro cognitivo", "enfermedad degenerativa", "demencia presenil", "alteración del juicio", "pérdida de funciones ejecutivas"]'),
('G31.09', 'Otro trastorno neurocognitivo frontotemporal', 'Sin especificar', '["demencia frontotemporal", "atrofia del lóbulo frontal", "degeneración frontotemporal", "trastorno de la conducta", "cambios de personalidad", "demencia progresiva", "pérdida de inhibición", "problemas de lenguaje", "afasia progresiva", "deterioro mental", "fallas de memoria", "desorientación", "déficit cognitivo", "problemas ejecutivos", "atrofia cerebral focal"]'),
('G31.1', 'Degeneración cerebral senil no clasificada bajo otro concepto', 'Sin especificar', '["vejez cerebral", "atrofia cerebral senil", "demencia senil", "senilidad", "pérdida de memoria en ancianos", "degeneración del cerebro", "deterioro cognitivo senil", "envejecimiento cerebral", "atrofia del cerebro", "demencia por edad", "olvidos frecuentes", "desgaste cerebral", "pérdida de facultades mentales", "demencia no especificada"]'),
('G31.2', 'Degeneración del sistema nervioso debida al alcohol', 'Sin especificar', '["daño cerebral por alcohol", "alcoholismo y cerebro", "encefalopatía alcohólica", "neurodegeneración alcohólica", "problemas neurológicos por trago", "daño neuronal por alcohol", "cerebro quemado por alcohol", "demencia alcohólica", "deterioro cognitivo por alcohol", "ataxia alcohólica", "efectos del alcohol en el sistema nervioso", "neuropatía alcohólica", "atrofia cerebral alcohólica"]'),
('G31.80', 'Leucodistrofia, no especificada', 'Sin especificar', '["enfermedad de la sustancia blanca", "daño en la mielina", "desmielinización", "enfermedad desmielinizante", "problemas de la materia blanca", "trastorno de la mielina", "degradación de la sustancia blanca", "leucodistrofias", "enfermedad neurológica degenerativa", "daño en las fibras nerviosas", "fallo neurológico genético"]'),
('G31.81', 'Enfermedad de Alpers', 'Sin especificar', '["síndrome de Alpers", "poliodistrofia esclerosante progresiva", "epilepsia infantil", "degradación neurológica infantil", "daño hepático y cerebral", "encefalopatía epiléptica", "trastorno mitocondrial", "enfermedad neurodegenerativa infantil", "fallo orgánico multisistémico", "crisis convulsivas severas", "retraso en el desarrollo infantil"]'),
('G31.82', 'Enfermedad de Leigh', 'Sin especificar', '["encefalomiopatía necrotizante subaguda", "síndrome de Leigh", "trastorno mitocondrial", "daño cerebral infantil", "debilidad muscular", "problemas respiratorios infantiles", "trastorno metabólico cerebral", "pérdida de habilidades motoras", "problemas de equilibrio", "encefalopatía degenerativa", "atrofia del tronco encefálico"]'),
('G31.83', 'Trastorno neurocognitivo por cuerpos de Lewy', 'Sin especificar', '["demencia por cuerpos de Lewy", "alucinaciones visuales", "parkinsonismo", "rigidez muscular", "problemas de atención", "demencia con alucinaciones", "fluctuaciones cognitivas", "desmayos frecuentes", "temblores", "trastorno del sueño REM", "confusión mental", "pérdida de agudeza mental", "enfermedad degenerativa tipo Parkinson"]'),
('G31.84', 'Deterioro cognitivo leve de etiología incierta o desconocida', 'Sin especificar', '["despistes frecuentes", "problemas de memoria leves", "olvidos constantes", "niebla mental", "pérdida de agilidad mental", "dificultad para concentrarse", "problemas de memoria a corto plazo", "deterioro mental incipiente", "falla de memoria leve", "pre-demencia", "problemas cognitivos sin causa clara", "cabeza nublada"]'),
('G31.85', 'Degeneración corticobasal', 'Sin especificar', '["síndrome corticobasal", "rigidez asimétrica", "dificultad para usar las manos", "apraxia", "problemas de movimiento", "parkinsonismo atípico", "torpeza motora", "pérdida de control muscular", "dificultad para hablar", "atrofia de la corteza cerebral", "trastorno motor progresivo", "problemas de equilibrio"]'),
('G31.86', 'Enfermedad de Alexander', 'Sin especificar', '["leucodistrofia de Alexander", "problemas de la sustancia blanca", "macrocefalia", "cabeza grande", "trastorno astrocitario", "enfermedad degenerativa infantil", "atraso psicomotor", "espasticidad", "trastorno neurológico genético", "problemas motores en niños", "acumulación de fibra de Rosenthal"]'),
('G31.89', 'Otras enfermedades degenerativas especificadas del sistema nervioso', 'Sin especificar', '["enfermedades neurodegenerativas raras", "daño progresivo del sistema nervioso", "trastorno del sistema nervioso", "pérdida de función neurológica", "atrofia del sistema nervioso", "degeneración nerviosa", "enfermedad del cerebro", "problemas progresivos de nervios", "neuropatía degenerativa", "desgaste neurológico"]'),
('G31.9', 'Enfermedad degenerativa del sistema nervioso, no especificada', 'Sin especificar', '["enfermedad degenerativa del cerebro", "deterioro neurológico", "problemas de nervios progresivos", "desgaste cerebral", "daño al sistema nervioso", "enfermedad del sistema nervioso sin nombre", "pérdida de funciones cerebrales", "trastorno degenerativo nervioso", "atrofia neurológica", "problemas de salud mental y nervios"]');
