INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H55.00', 'Nistagmo no especificado', 'Sin especificar', '["ojos que se mueven solos", "temblor en los ojos", "ojos que bailan", "movimiento involuntario de ojos", "ojos inquietos", "oscilopsia", "ojos que vibran", "movimiento rápido de ojos", "ojos descontrolados", "nistagmus", "ojos que dan saltitos", "mareo por movimiento ocular"]'),
('H55.01', 'Nistagmo congénito', 'Sin especificar', '["ojos que se mueven desde que nací", "nistagmo de nacimiento", "ojos inquietos de bebé", "temblor ocular hereditario", "ojos que bailan desde chico", "nistagmo infantil", "ojos con movimiento constante desde el nacimiento", "movimiento involuntario ocular congénito", "problema visual de nacimiento", "ojos que vibran desde la infancia"]'),
('H55.02', 'Nistagmo latente', 'Sin especificar', '["nistagmo al tapar un ojo", "ojos que bailan al cubrir uno", "nistagmo oculto", "temblor ocular ante oclusión", "movimiento ocular al tapar", "ojos inquietos al tapar un ojo", "nistagmo inducido por oclusión", "ojos que se descontrolan al tapar", "nistagmo provocado por taparse", "problema visual al cubrir un ojo"]'),
('H55.03', 'Nistagmo de deprivación visual', 'Sin especificar', '["nistagmo por no ver bien", "ojos que bailan por mala visión", "nistagmo sensorial", "temblor ocular por baja visión", "nistagmo por catarata congénita", "ojos inquietos por ceguera parcial", "movimiento ocular por privación visual", "ojos que vibran por visión borrosa", "pérdida de fijación visual", "nistagmo por falta de estímulo visual"]'),
('H55.04', 'Nistagmo disociado', 'Sin especificar', '["ojos que se mueven diferente", "movimiento ocular no sincronizado", "cada ojo se mueve por su lado", "nistagmo asimétrico", "temblor ocular desfasado", "ojos que bailan de forma distinta", "nistagmo en un solo ojo", "movimiento de ojos descoordinado", "ojos con movimientos independientes", "nistagmo bilateral asimétrico"]'),
('H55.09', 'Otras formas de nistagmo', 'Sin especificar', '["nistagmo adquirido", "movimiento raro de ojos", "ojos que se tuercen", "nistagmo vertical", "nistagmo rotatorio", "ojos que vibran de lado a lado", "temblor ocular inusual", "nistagmo pendular", "nistagmo a sacudidas", "movimientos oculares erráticos"]'),
('H55.81', 'Deficiencia de movimientos sacádicos de los ojos', 'Sin especificar', '["dificultad para mover los ojos rápido", "ojos lentos para fijar", "fallo en movimientos sacádicos", "ojos que no siguen bien", "falta de velocidad ocular", "problema de fijación visual", "ojos que no brincan de un punto a otro", "dificultad para mirar de reojo", "ojos perezosos al saltar de objetivo", "insuficiencia sacádica"]'),
('H55.82', 'Movimientos oculares deficientes de persecución lenta', 'Sin especificar', '["dificultad para seguir objetos", "ojos que no persiguen bien", "problema al seguir con la mirada", "vista que se pierde al seguir", "ojos que no acompañan el movimiento", "fallo en seguimiento ocular", "dificultad para seguir un dedo con los ojos", "ojos que saltan al seguir algo", "seguimiento visual deficiente", "incapacidad de seguir objetos suavemente"]'),
('H55.89', 'Otros tipos de movimientos oculares irregulares', 'Sin especificar', '["ojos que se mueven raro", "movimientos oculares anormales", "ojos que se van por su cuenta", "tics oculares", "movimientos erráticos de los ojos", "inestabilidad ocular", "falta de fijación de la mirada", "ojos que saltan", "movimientos oculares espasmódicos", "ojos que no se quedan quietos"]');
