INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('G46.0', 'Síndrome de la arteria cerebral media', 'Sin especificar', '["derrame cerebral", "ACV", "ictus", "ataque al cerebro", "embolia", "parálisis de medio cuerpo", "hemiplejia", "debilidad facial", "boca chueca", "afasia", "no puedo hablar", "infarto cerebral", "coágulo en la cabeza", "trombosis", "isquemia cerebral"]'),
('G46.1', 'Síndrome de la arteria cerebral anterior', 'Sin especificar', '["infarto cerebral anterior", "cambios de personalidad por derrame", "dificultad para caminar", "incontinencia urinaria", "ACV anterior", "desorientación", "falta de juicio", "apatía", "problemas motrices piernas", "ictus frontal", "lóbulo frontal dañado", "coágulo en arteria anterior", "embolia cerebral", "isquemia frontal"]'),
('G46.2', 'Síndrome de la arteria cerebral posterior', 'Sin especificar', '["problemas de visión por ACV", "ceguera repentina", "vértigo", "mareos fuertes", "pérdida de campo visual", "ictus posterior", "infarto occipital", "confusión mental", "problemas de memoria", "alucinaciones visuales", "ataque cerebral visual", "trombosis posterior", "embolia visual", "isquemia posterior"]'),
('G46.3', 'Síndrome cerebrovascular troncoencefálico', 'Sin especificar', '["infarto de tronco encefálico", "problemas para tragar", "dificultad al hablar", "disfagia", "voz ronca", "parálisis facial bilateral", "doble visión", "diplopía", "ataxia", "inestabilidad al caminar", "mareo intenso", "ACV de tallo cerebral", "ictus del tronco", "vómitos por derrame", "problemas respiratorios"]'),
('G46.4', 'Síndrome cerebrovascular cerebeloso', 'Sin especificar', '["infarto cerebeloso", "desequilibrio", "caminar borracho", "falta de coordinación", "problemas de equilibrio", "ataxia cerebelosa", "vómitos explosivos", "cefalea intensa", "inestabilidad", "temblor al moverse", "mareo constante", "ictus del cerebelo", "trombosis cerebelosa", "problemas de motricidad fina"]'),
('G46.5', 'Síndrome lacunar motor puro', 'Sin especificar', '["infarto lacunar", "debilidad motora", "parálisis brazo y pierna", "pérdida de fuerza", "ictus pequeño", "isquemia lacunar", "problemas de movimiento unilateral", "derrame leve", "claudicación de extremidades", "falta de fuerza repentina", "coágulo en vasos pequeños", "lesión lacunar", "parálisis parcial"]'),
('G46.6', 'Síndrome lacunar sensitivo puro', 'Sin especificar', '["pérdida de sensibilidad", "hormigueo en medio cuerpo", "entumecimiento facial", "adormecimiento brazo y pierna", "parestesia", "falta de tacto", "sensación de acorchamiento", "ictus sensitivo", "lesión sensitiva pura", "daño nervioso central", "infarto de vasos pequeños", "anestesia unilateral", "quemazón en la piel"]'),
('G46.7', 'Otros síndromes lacunares', 'Sin especificar', '["ataxia hemiparética", "disartria-mano torpe", "síndrome de mala dicción", "infarto lacunar atípico", "ictus lacunar complejo", "problemas de lenguaje y movimiento", "coágulos pequeños", "microinfartos cerebrales", "lesiones vasculares profundas", "mini-ictus", "enfermedad de vasos pequeños", "daño lacunar crónico"]'),
('G46.8', 'Otros síndromes vasculares cerebrales en enfermedades cerebrovasculares', 'Sin especificar', '["vasculitis cerebral", "disección arterial", "aneurisma cerebral", "trombosis venosa cerebral", "malformación arteriovenosa", "infarto cerebral complejo", "problemas de circulación cerebral", "choque vascular", "daño por presión alta", "enfermedad de los vasos sanguíneos del cerebro", "estenosis carotídea", "placa en la carótida", "sangrado cerebral"]');
