INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A98.0', 'Fiebre hemorrágica de Crimea-Congo', 'Sin especificar', '["fiebre hemorrágica", "virus Crimea-Congo", "fiebre por garrapatas", "sangrado interno", "hemorragias", "manchas en la piel", "fiebre alta", "virus transmitido por garrapatas", "dolor articular", "fiebre viral", "petequias", "fiebre con sangrado", "síndrome febril hemorrágico", "infección por garrapatas"]'),
('A98.1', 'Fiebre hemorrágica de Omsk', 'Sin especificar', '["fiebre de Omsk", "fiebre hemorrágica", "virus de Omsk", "enfermedad por roedores", "fiebre viral", "sangrado", "hemorragia", "fiebre alta", "malestar general", "dolor de cuerpo", "fiebre con hemorragia", "infección viral de Omsk", "síndrome febril"]'),
('A98.2', 'Enfermedad de la selva de Kyasanur', 'Sin especificar', '["fiebre de Kyasanur", "enfermedad de la selva", "fiebre hemorrágica", "virus de Kyasanur", "fiebre de la selva", "mordedura de garrapata", "sangrado", "fiebre alta", "dolor de cabeza", "vómito", "hemorragias", "infección viral selvática", "fiebre tropical hemorrágica"]'),
('A98.3', 'Enfermedad por el virus de Marburg', 'Sin especificar', '["virus de Marburg", "fiebre hemorrágica de Marburg", "fiebre viral grave", "hemorragia interna", "sangrado por orificios", "fiebre alta", "dolor abdominal", "dolor de barriga", "malestar general", "diarrea", "vómitos con sangre", "fiebre mortal", "virus hemorrágico", "enfermedad de Marburg"]'),
('A98.4', 'Enfermedad por el virus de Ébola', 'Sin especificar', '["ébola", "virus ébola", "fiebre hemorrágica del ébola", "fiebre con sangrado", "sangrado interno", "sangrar por los ojos", "virus africano", "epidemia de ébola", "fiebre alta", "dolor de guata", "vómitos", "diarrea sanguinolenta", "dolor de cuerpo", "virus mortal", "infección por ébola"]'),
('A98.5', 'Fiebres hemorrágicas con síndrome renal', 'Sin especificar', '["fiebre hemorrágica renal", "problemas de riñón", "fiebre con fallo renal", "virus Hanta", "insuficiencia renal", "sangrado y riñones", "dolor en la espalda baja", "dolor en los riñones", "fiebre alta", "orinar sangre", "infección viral renal", "fiebre hemorrágica", "síndrome renal"]'),
('A98.8', 'Otras fiebres hemorrágicas virales especificadas', 'Sin especificar', '["fiebre hemorrágica", "virus con sangrado", "fiebre viral rara", "infección hemorrágica", "fiebre alta y manchas", "sangrado repentino", "virus desconocidos", "fiebre con hemorragias", "síndrome febril grave", "malestar hemorrágico", "enfermedad viral por sangrado"]');
