INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('G95.0', 'Siringomielia y siringobulbia', 'Sin especificar', '["quiste en la médula", "cavidad en la médula", "médula espinal hueca", "siringe medular", "dolor neuropático", "debilidad muscular", "pérdida de sensibilidad", "entumecimiento", "atrofia muscular", "problemas de temperatura", "falta de fuerza en brazos", "sensación de hormigueo", "parálisis parcial", "mielopatía quística", "tensión medular"]'),
('G95.11', 'Infarto agudo de médula espinal (embólico) (no embólico)', 'Sin especificar', '["derrame en la médula", "ataque a la médula", "embolia medular", "parálisis súbita", "pérdida de movilidad repentina", "infarto espinal", "trombosis medular", "fallo circulatorio medular", "isquemia medular", "dejar de sentir las piernas", "infarto de la columna", "emergencia medular", "necrosis medular", "coágulo en la médula"]'),
('G95.19', 'Otras mielopatías vasculares', 'Sin especificar', '["problemas circulatorios médula", "mal riego médula", "mielopatía vascular", "daño por falta de sangre en columna", "enfermedad vascular medular", "angiopatía medular", "edema medular vascular", "inflamación vascular médula", "daño espinal por circulación", "déficit motor vascular", "compresión vascular medular"]'),
('G95.20', 'Compresión medular no especificada', 'Sin especificar', '["médula apretada", "nervios pinzados médula", "columna comprimida", "dolor de espalda fuerte", "presión en la médula", "bloqueo medular", "disminución de movilidad", "hormigueo en extremidades", "debilidad de piernas", "columna bloqueada", "pinzamiento medular", "aplastamiento medular", "dificultad para caminar", "daño por presión espinal"]'),
('G95.29', 'Otros tipos de compresión medular', 'Sin especificar', '["presión externa en médula", "tumor medular", "absceso epidural", "compresión por hernia", "estrechamiento canal medular", "estenosis espinal", "daño por golpe en columna", "presión sobre los nervios", "mielopatía compresiva", "espasmos musculares", "entumecimiento crónico", "pérdida de reflejos", "pesadez en las piernas", "dolor radicular"]'),
('G95.81', 'Síndrome de cono medular', 'Sin especificar', '["pérdida control esfínteres", "incontinencia urinaria", "incontinencia fecal", "anestesia en silla de montar", "dolor lumbar bajo", "problemas sexuales neurológicos", "disfunción eréctil neurológica", "debilidad en esfínteres", "lesión final de médula", "pérdida sensibilidad perineal", "fallo medular bajo", "hormigueo en genitales", "pérdida de fuerza en pies"]'),
('G95.89', 'Otras enfermedades especificadas de médula espinal', 'Sin especificar', '["lesión médula espinal", "problemas de columna", "enfermedad rara de médula", "daño nervioso columna", "inflamación médula", "mielitis", "debilidad progresiva", "trastornos medulares", "dolor neuropático crónico", "pérdida de sensibilidad", "problemas de coordinación", "marcha inestable", "atrofia de nervios espinales"]'),
('G95.9', 'Enfermedades de la médula espinal, no especificadas', 'Sin especificar', '["problema en la espalda", "dolor de columna", "no siento las piernas", "problemas al caminar", "daño nervioso", "enfermedad de la columna", "debilidad en el cuerpo", "fallo medular", "problemas motores", "hormigueo persistente", "tensión en la espalda", "desgaste de médula", "problemas de nervios", "enfermedad medular desconocida"]');
