INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('O89.01', 'Neumonitis por aspiración debida a la anestesia durante el puerperio', 'Sin especificar', '["neumonía por anestesia", "aspiración pulmonar postparto", "pulmones después de la cesárea", "tos tras anestesia", "aspiración durante el parto", "se me fue la anestesia a los pulmones", "ahogo postparto", "infección pulmonar por vomitar anestesiada", "problemas de respiración postparto", "broncoaspiración por parto", "dificultad para respirar después de dar a luz", "líquido en los pulmones por anestesia", "neumonitis puerperal", "tos con flema postparto"]'),
('O89.09', 'Otras complicaciones pulmonares de la anestesia durante el puerperio', 'Sin especificar', '["problemas respiratorios postparto", "pulmones después de la cirugía de parto", "fatiga al respirar tras cesárea", "dolor al respirar después de tener al bebé", "anestesia y pulmones", "oxígeno bajo postparto", "sensación de falta de aire post cesárea", "complicaciones del pecho después del parto", "tos seca persistente postparto", "se me cerró el pecho en la operación", "dificultad para respirar después de la anestesia", "afección pulmonar tras el parto"]'),
('O89.1', 'Complicaciones cardiacas de la anestesia durante el puerperio', 'Sin especificar', '["taquicardia después de cesárea", "corazón acelerado tras anestesia", "problemas del corazón postparto", "arritmia después de parir", "dolor en el pecho por anestesia", "palpitaciones post parto", "corazón raro después de la operación", "taquicardia puerperal", "desmayos después de la anestesia", "presión alta tras anestesia", "susto del corazón tras parto", "complicaciones cardiovasculares en puerperio"]'),
('O89.2', 'Complicaciones del sistema nervioso central de la anestesia durante el puerperio', 'Sin especificar', '["convulsiones tras anestesia", "temblores post parto", "mareos después de la cesárea", "confusión mental post anestesia", "hormigueo en la cabeza tras el parto", "problemas neurológicos después de la epidural", "desorientación postquirúrgica", "daño nervioso por anestesia", "nervios alterados post parto", "pérdida de sensibilidad post anestesia", "entumecimiento postparto", "ataque nervioso post cesárea"]'),
('O89.3', 'Reacción tóxica a la anestesia local durante el puerperio', 'Sin especificar', '["intoxicación por anestesia", "alergia a la anestesia del parto", "reacción adversa a la lidocaína", "mareos por anestesia", "hormigueo en la cara por anestesia", "mal sabor de boca por anestesia", "taquicardia por anestesia local", "reacción alérgica tras cesárea", "toxicidad por anestésicos", "me cayó mal la anestesia", "erupción por anestesia", "picazón tras anestesia"]'),
('O89.4', 'Cefalea inducida por la anestesia espinal y epidural durante el puerperio', 'Sin especificar', '["dolor de cabeza por epidural", "jaqueca postparto", "dolor de cabeza por la raquia", "cefalea post punción", "punzadas en la cabeza después del parto", "dolor de nuca post parto", "migraña tras cesárea", "se me parte la cabeza tras el parto", "dolor de cabeza al levantarme post parto", "cefalea por anestesia", "dolor de espalda y cabeza epidural", "la epidural me dejó dolor de cabeza", "dolor punzante de cabeza post cesárea"]'),
('O89.5', 'Otras complicaciones de la anestesia espinal y epidural durante el puerperio', 'Sin especificar', '["dolor de espalda por la epidural", "entumecimiento de piernas postparto", "dolor en el sitio de la punción", "espalda adolorida post cesárea", "hormigueo en las piernas por la anestesia", "problemas de movilidad postparto", "pinchazo en la columna", "dificultad para caminar después de la epidural", "infección en la zona de la epidural", "dolor lumbar post parto", "efectos secundarios de la raquia", "mala colocación de la epidural"]'),
('O89.6', 'Intubación difícil o fallida para la anestesia durante el puerperio', 'Sin especificar', '["dolor de garganta después de la cesárea", "trauma en la garganta por anestesia", "problemas para intubar en el parto", "tos con sangre después de intubación", "dificultad para tragar post parto", "voz ronca después de la anestesia", "se me irritó la garganta en el parto", "tubo en la garganta durante cesárea", "lesión en la tráquea por anestesia", "molestia al tragar post cesárea", "intubación complicada", "dolor al pasar saliva tras la cirugía"]'),
('O89.8', 'Otras complicaciones de la anestesia durante el puerperio', 'Sin especificar', '["efectos secundarios de la anestesia", "malestar tras la anestesia", "vomitos tras cesárea", "náuseas post anestesia", "fiebre después de la anestesia", "escalofríos post parto", "temblorina después de la cirugía", "mareos al levantarse post parto", "sensación de pesadez post anestesia", "después de la anestesia me siento rara", "complicaciones postquirúrgicas parto", "reacción alérgica post parto"]'),
('O89.9', 'Complicación de la anestesia durante el puerperio, no especificada', 'Sin especificar', '["problemas con la anestesia", "efectos raros tras el parto", "anestesia y complicaciones", "me fue mal con la anestesia", "qué pasó con mi anestesia", "reacciones raras post cesárea", "efectos de la raquia", "dolores post parto por anestesia", "anestesia mal puesta", "consecuencias de la anestesia", "malestar general post anestesia"]');
