INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L10.0', 'Pénfigo vulgar', 'Sin especificar', '["ampollas en la piel", "llagas en la boca", "enfermedad autoinmune piel", "burbujas en la piel", "desprendimiento de piel", "erosiones bucales", "piel escamada", "lesiones ampollosas", "quemaduras en la boca", "ampollas que se rompen", "enfermedad de las ampollas", "boqueras graves", "piel en carne viva", "flictenas", "despellejamiento", "pénfigo común"]'),
('L10.1', 'Pénfigo vegetante', 'Sin especificar', '["crecimientos en la piel", "verrugas ampollosas", "placas vegetantes", "piel con abultamientos", "lesiones con costra", "pénfigo granulomatoso", "ampollas con tejido", "bultos en pliegues cutáneos", "enfermedad ampollosa proliferativa", "piel rugosa con ampollas", "lesiones exudativas", "vegetaciones cutáneas", "pénfigo con crecimientos", "ampollas infectadas", "lesiones que no curan"]'),
('L10.2', 'Pénfigo foliáceo', 'Sin especificar', '["piel descamada", "costras en la piel", "piel reseca con escamas", "ampollas superficiales", "pénfigo sin llagas bucales", "piel como papel de fumar", "descamación generalizada", "piel irritada", "costras doradas en piel", "dermatitis ampollosa", "piel descamativa", "enfermedad de la piel escamosa", "ampollas que se descaman", "piel que se pela sola", "lesiones eritematosas"]'),
('L10.3', 'Pénfigo de Brasil [fogo salvagem]', 'Sin especificar', '["fogo salvagem", "fuego salvaje", "pénfigo endémico", "ampollas tropicales", "enfermedad de la piel brasilera", "picazón intensa", "piel con fuego", "manchas ampollosas", "pénfigo sudamericano", "quemazón en la piel", "pénfigo de los trópicos", "escoriaciones", "enfermedad ampollosa endémica", "piel ardiente", "costras extensas"]'),
('L10.4', 'Pénfigo eritematoso', 'Sin especificar', '["pénfigo de Senear-Usher", "piel roja con costras", "manchas rojas en cara", "ampollas en rostro", "eritema con ampollas", "lesiones tipo lupus", "costras seborreicas", "piel enrojecida", "inflamación cutánea con burbujas", "pénfigo facial", "piel con parches rojos", "erupción con ampollas", "piel irritada en nariz y mejillas", "costras escamosas", "enfermedad autoinmune cutánea"]'),
('L10.5', 'Pénfigo inducido por fármacos', 'Sin especificar', '["ampollas por medicamentos", "reacción alérgica grave a medicinas", "pénfigo por pastillas", "piel ampollada por fármacos", "efecto secundario en piel", "dermatitis medicamentosa", "reacción cutánea a fármacos", "pénfigo iatrogénico", "lesiones por tomar medicinas", "erupción medicamentosa", "piel que reacciona a medicación", "burbujas por fármacos", "tóxico cutáneo", "pénfigo por antibióticos", "reacción a drogas farmacológicas"]'),
('L10.81', 'Pénfigo paraneoplásico', 'Sin especificar', '["ampollas por cáncer", "pénfigo asociado a tumor", "enfermedad autoinmune oncológica", "llagas en boca por cáncer", "pénfigo y neoplasia", "lesiones cutáneas graves", "ampollas en labios y piel", "dolor oral severo", "pénfigo maligno", "enfermedad ampollosa sistémica", "lesiones eritematosas severas", "síndrome paraneoplásico cutáneo", "llagas que no cierran", "pénfigo por linfoma", "enfermedad de la piel grave"]'),
('L10.89', 'Otros tipos de pénfigo', 'Sin especificar', '["enfermedad ampollosa rara", "otra forma de pénfigo", "pénfigo atípico", "ampollas extrañas en piel", "problemas cutáneos autoinmunes", "piel con ampollas persistentes", "trastorno de la unión dermoepidérmica", "lesiones ampollosas raras", "dermatosis ampollosa", "burbujas en la piel sin explicación", "enfermedad de piel poco común", "pénfigo no clasificado", "lesiones cutáneas autoinmunes", "ampollas inexplicables"]'),
('L10.9', 'Pénfigo, no especificado', 'Sin especificar', '["tengo ampollas en la piel", "enfermedad de las ampollas", "piel con burbujas de agua", "llagas en el cuerpo", "enfermedad autoinmune desconocida", "piel que se despega", "problema de piel tipo pénfigo", "ampollas recurrentes", "dermatosis con ampollas", "llagas bucales", "piel en carne viva", "burbujas en la piel que revientan", "enfermedad de la piel no diagnosticada", "pénfigo general"]');
