INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D10.0', 'Neoplasia benigna de labio', 'Sin especificar', '["bulto en el labio", "bolita en la boca", "tumor labial", "herida en el labio que no sana", "crecimiento en el labio", "papiloma labial", "fibroma en labio", "chichón en el labio", "verruga en el labio", "masa en la boca", "nódulo labial", "lesión en el labio", "bultito en la comisura", "tumor benigno labio", "bolita en la trompa"]'),
('D10.1', 'Neoplasia benigna de la lengua', 'Sin especificar', '["bolita en la lengua", "bulto debajo de la lengua", "tumor en la lengua", "fibroma lingual", "crecimiento en la lengua", "lengua inflamada", "bolita en el costado de la lengua", "papiloma en la lengua", "nódulo en la lengua", "masa lingual", "verruga en la lengua", "lesión en la lengua", "carnosidad en la lengua", "tumor benigno lengua", "ulcerita que no se quita"]'),
('D10.2', 'Neoplasia benigna de suelo de la boca', 'Sin especificar', '["bolita debajo de la lengua", "bulto en el piso de la boca", "ranula", "tumor en el suelo de la boca", "hinchazón bajo la lengua", "masa en el piso de la boca", "crecimiento en la base de la lengua", "nódulo sublingual", "carnosidad en la boca", "tumor benigno piso boca", "bolita en la base de la lengua", "inflamación bajo la lengua", "bulto en el paladar inferior"]'),
('D10.30', 'Neoplasia benigna de parte no especificada de la boca', 'Sin especificar', '["tumor en la boca", "bulto en la boca", "bolita en la mejilla", "masa en la cavidad oral", "carnosidad en la boca", "crecimiento extraño en la boca", "lesión oral", "nódulo en la mejilla", "papiloma bucal", "chichón en la boca", "tumor benigno oral", "bulto en las encías", "bolita en el carrillo"]'),
('D10.39', 'Neoplasia benigna de otras partes de la boca', 'Sin especificar', '["bulto en el paladar", "bolita en la encía", "tumor en la mejilla", "crecimiento en las mejillas", "tumor palatino", "fibroma bucal", "masa en la encía", "epulis", "lesión en el paladar", "bolita en el paladar duro", "papiloma en la mejilla", "bulto en la parte interna de la mejilla", "tumor benigno encía"]'),
('D10.4', 'Neoplasia benigna de amígdala', 'Sin especificar', '["bulto en la amígdala", "amígdala grande", "tumor en la garganta", "bolita en la campanilla", "crecimiento en las anginas", "masa en la amígdala", "nódulo amigdalino", "inflamación de una sola amígdala", "bulto en la garganta", "tumor benigno amígdala", "papiloma en la garganta", "angina inflamada", "piedras en las amígdalas", "tonsilolito"]'),
('D10.5', 'Neoplasia benigna de otras partes de orofaringe', 'Sin especificar', '["bulto en la garganta", "tumor en la faringe", "masa en la garganta", "crecimiento en el fondo de la boca", "nódulo orofaríngeo", "dolor al tragar bulto", "tumor benigno orofaringe", "lesión en la parte posterior de la boca", "carnosidad en la garganta", "bulto atrás de la lengua", "sensación de cuerpo extraño en garganta"]'),
('D10.6', 'Neoplasia benigna de nasofaringe', 'Sin especificar', '["tumor en la nariz y garganta", "bulto detrás de la nariz", "masa en la nasofaringe", "crecimiento en el cavum", "tumor benigno nasofaríngeo", "angiofibroma", "bulto en la parte alta de la garganta", "obstrucción nasal persistente", "nódulo en la nasofaringe", "lesión en la parte alta de la faringe"]'),
('D10.7', 'Neoplasia benigna de hipofaringe', 'Sin especificar', '["bulto en la parte baja de la garganta", "tumor en la hipofaringe", "masa en la laringe", "crecimiento en la parte inferior de la faringe", "nódulo hipofaríngeo", "dificultad para pasar comida", "tumor benigno hipofaringe", "lesión en la faringe baja", "bulto en la base de la garganta", "sensación de nudo en la garganta"]'),
('D10.9', 'Neoplasia benigna de faringe, no especificada', 'Sin especificar', '["tumor en la garganta", "bulto en la faringe", "masa en la garganta", "crecimiento faríngeo", "nódulo en la garganta", "carnosidad en la faringe", "tumor benigno de garganta", "lesión faríngea", "bulto en la garganta desconocido", "obstrucción al tragar", "tumor en la vía aérea alta"]');
