INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('W20.0XXA', 'Golpeado por objeto que cae en un derrumbamiento, contacto inicial', 'Sin especificar', '["derrumbamiento", "escombros", "sepultado", "derrumbe", "aplastado por piedras", "piedras cayendo", "golpe en obra", "accidente de construcción", "derrumbe de cerro", "escombros encima", "accidente en excavación", "sepultado por tierra", "traumatismo por derrumbe", "piedrazos", "emergencia derrumbe"]'),
('W20.0XXD', 'Golpeado por objeto que cae en un derrumbamiento, contacto sucesivo', 'Sin especificar', '["seguimiento derrumbe", "control por golpe de escombros", "curación tras derrumbe", "revisión por aplastamiento", "golpe recurrente escombros", "atención secundaria derrumbe", "seguimiento por trauma de construcción", "evolución tras sepultamiento", "segunda revisión escombros", "control médico post-derrumbamiento", "atención médica tras desastre", "lesión residual derrumbe"]'),
('W20.0XXS', 'Golpeado por objeto que cae en un derrumbamiento, secuela', 'Sin especificar', '["secuelas de derrumbe", "dolores post-derrumbe", "cicatrices de escombros", "daño crónico por aplastamiento", "secuela de sepultamiento", "problemas por accidente de obra", "dolor crónico por golpe de escombros", "limitación tras derrumbamiento", "secuelas de desastre natural", "rehabilitación por trauma de construcción", "secuelas físicas por escombros"]'),
('W20.1XXA', 'Golpeado por objeto debido a derrumbamiento de edificio, contacto inicial', 'Sin especificar', '["derrumbe de casa", "edificio cayendo", "escombros de concreto", "techo caído", "golpe por pared que se cae", "accidente estructural", "derrumbe de construcción", "bloques cayendo", "derrumbado", "techo desplomado", "escombros de edificio", "golpe por desplome", "accidente inmobiliario", "paredes cayendo", "emergencia estructural"]'),
('W20.1XXD', 'Golpeado por objeto debido a derrumbamiento de edificio, contacto sucesivo', 'Sin especificar', '["control por derrumbe de edificio", "seguimiento accidente estructural", "curación tras caída de edificio", "revisión por golpe de construcción", "atención secundaria por desplome", "seguimiento desplome de techo", "evolución post-derrumbe edilicio", "control por escombros de concreto", "segunda atención accidente casa", "revisión médica tras colapso"]'),
('W20.1XXS', 'Golpeado por objeto debido a derrumbamiento de edificio, secuela', 'Sin especificar', '["secuelas de desplome edificio", "dolor crónico tras colapso", "secuela de derrumbe de casa", "daños por accidente estructural", "rehabilitación por desplome", "limitaciones físicas post-derrumbe", "secuelas de escombros de concreto", "dolor por caída de techo", "consecuencias de colapso edilicio", "problemas persistentes por derrumbe"]'),
('W20.8XXA', 'Otra causa de golpe por objeto lanzado, proyectado o que cae, contacto inicial', 'Sin especificar', '["golpeado por objeto", "cosas que caen", "objeto lanzado", "golpe de refilón", "me cayó algo encima", "objeto proyectado", "objeto volador", "golpe por caída de objeto", "accidentes con cosas", "me golpearon con algo", "objeto contundente cayendo", "golpe repentino", "accidente con objeto pesado"]'),
('W20.8XXD', 'Otra causa de golpe por objeto lanzado, proyectado o que cae, contacto sucesivo', 'Sin especificar', '["control por golpe de objeto", "seguimiento de impacto", "revisión por objeto caído", "curación de golpe", "atención secundaria por proyectil", "seguimiento de contusión", "evolución tras golpe de objeto", "control médico por impacto", "revisión de herida por objeto", "seguimiento por trauma contuso"]'),
('W20.8XXS', 'Otra causa de golpe por objeto lanzado, proyectado o que cae, secuela', 'Sin especificar', '["secuelas de golpe por objeto", "dolor persistente por impacto", "secuela de contusión", "daño crónico por golpe", "secuela de objeto proyectado", "limitación por golpe", "cicatriz por objeto caído", "molestia post-golpe", "dolor crónico por impacto", "secuelas de traumatismo contuso", "rehabilitación tras golpe"]');
