INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H50.00', 'Esotropía no especificada', 'Sin especificar', '["ojo desviado hacia adentro", "ojos bizcos", "estrabismo convergente", "ojo metido", "bizquera", "ojos cruzados", "desviación ocular interna", "ojos que se juntan", "estrabismo hacia adentro", "ojos encontrados", "mirada bizca", "problema de alineación ocular", "ojo metido hacia la nariz", "estrabismo infantil"]'),
('H50.011', 'Esotropía monocular, ojo derecho', 'Sin especificar', '["ojo derecho bizco", "ojo derecho hacia adentro", "estrabismo ojo derecho", "desviación ojo derecho al centro", "ojo derecho metido", "ojo derecho cruzado", "bizquera ojo derecho", "ojo derecho desalineado", "ojos chuecos derecho", "ojo derecho que apunta a la nariz", "ojo derecho torcido al centro"]'),
('H50.012', 'Esotropía monocular, ojo izquierdo', 'Sin especificar', '["ojo izquierdo bizco", "ojo izquierdo hacia adentro", "estrabismo ojo izquierdo", "desviación ojo izquierdo al centro", "ojo izquierdo metido", "ojo izquierdo cruzado", "bizquera ojo izquierdo", "ojo izquierdo desalineado", "ojos chuecos izquierdo", "ojo izquierdo que apunta a la nariz", "ojo izquierdo torcido al centro"]'),
('H50.021', 'Esotropía monocular con patrón A, ojo derecho', 'Sin especificar', '["esotropía ojo derecho patrón A", "estrabismo patrón A ojo derecho", "desviación ocular tipo A derecho", "estrabismo al mirar hacia arriba o abajo", "ojo derecho desviado hacia adentro con patrón A"]'),
('H50.022', 'Esotropía monocular con patrón A, ojo izquierdo', 'Sin especificar', '["esotropía ojo izquierdo patrón A", "estrabismo patrón A ojo izquierdo", "desviación ocular tipo A izquierdo", "estrabismo al mirar hacia arriba o abajo", "ojo izquierdo desviado hacia adentro con patrón A"]'),
('H50.031', 'Esotropía monocular con patrón V, ojo derecho', 'Sin especificar', '["esotropía ojo derecho patrón V", "estrabismo patrón V ojo derecho", "desviación ocular tipo V derecho", "ojo derecho desviado hacia adentro con patrón V"]'),
('H50.032', 'Esotropía monocular con patrón V, ojo izquierdo', 'Sin especificar', '["esotropía ojo izquierdo patrón V", "estrabismo patrón V ojo izquierdo", "desviación ocular tipo V izquierdo", "ojo izquierdo desviado hacia adentro con patrón V"]'),
('H50.041', 'Esotropía monocular con otros defectos de concomitancia, ojo derecho', 'Sin especificar', '["esotropía concomitante derecho", "desviación ocular derecha", "estrabismo derecho", "ojo derecho se va hacia adentro"]'),
('H50.042', 'Esotropía monocular con otros defectos de concomitancia, ojo izquierdo', 'Sin especificar', '["esotropía concomitante izquierdo", "desviación ocular izquierda", "estrabismo izquierdo", "ojo izquierdo se va hacia adentro"]'),
('H50.05', 'Esotropía alternante', 'Sin especificar', '["estrabismo alternante", "bizquera que cambia de ojo", "ojos que se desvían alternadamente", "esotropía que pasa de un ojo a otro", "ojos bizcos intermitentes"]'),
('H50.06', 'Esotropía alternante con patrón A', 'Sin especificar', '["esotropía alternante patrón A", "bizquera alternante tipo A", "estrabismo que cambia ojo con patrón A"]'),
('H50.07', 'Esotropía alternante con patrón V', 'Sin especificar', '["esotropía alternante patrón V", "bizquera alternante tipo V", "estrabismo que cambia ojo con patrón V"]'),
('H50.08', 'Esotropía alternante con otros defectos de concomitancia', 'Sin especificar', '["esotropía alternante concomitante", "bizquera variable", "estrabismo que se mueve"]'),
('H50.10', 'Exotropía no especificada', 'Sin especificar', '["ojo desviado hacia afuera", "ojos bizcos hacia fuera", "estrabismo divergente", "ojo que se va hacia la oreja", "ojo salido", "desviación ocular externa", "estrabismo divergente", "ojos hacia afuera", "bizco hacia afuera"]'),
('H50.111', 'Exotropía monocular, ojo derecho', 'Sin especificar', '["exotropía ojo derecho", "ojo derecho hacia afuera", "ojo derecho divergente", "ojo derecho se desvía a la oreja", "bizco ojo derecho afuera"]'),
('H50.112', 'Exotropía monocular, ojo izquierdo', 'Sin especificar', '["exotropía ojo izquierdo", "ojo izquierdo hacia afuera", "ojo izquierdo divergente", "ojo izquierdo se desvía a la oreja", "bizco ojo izquierdo afuera"]'),
('H50.121', 'Exotropía monocular con patrón A, ojo derecho', 'Sin especificar', '["exotropía ojo derecho patrón A", "ojo derecho divergente patrón A", "desviación externa ojo derecho tipo A"]'),
('H50.122', 'Exotropía monocular con patrón A, ojo izquierdo', 'Sin especificar', '["exotropía ojo izquierdo patrón A", "ojo izquierdo divergente patrón A", "desviación externa ojo izquierdo tipo A"]'),
('H50.131', 'Exotropía monocular con patrón V, ojo derecho', 'Sin especificar', '["exotropía ojo derecho patrón V", "ojo derecho divergente patrón V", "desviación externa ojo derecho tipo V"]'),
('H50.132', 'Exotropía monocular con patrón V, ojo izquierdo', 'Sin especificar', '["exotropía ojo izquierdo patrón V", "ojo izquierdo divergente patrón V", "desviación externa ojo izquierdo tipo V"]'),
('H50.141', 'Exotropía monocular con otros defectos de concomitancia, ojo derecho', 'Sin especificar', '["exotropía ojo derecho concomitante", "estrabismo divergente derecho"]'),
('H50.142', 'Exotropía monocular con otros defectos de concomitancia, ojo izquierdo', 'Sin especificar', '["exotropía ojo izquierdo concomitante", "estrabismo divergente izquierdo"]'),
('H50.15', 'Exotropía alternante', 'Sin especificar', '["exotropía que alterna ojos", "estrabismo divergente alternante", "ojos que se desvían hacia afuera alternadamente"]'),
('H50.16', 'Exotropía alternante con patrón A', 'Sin especificar', '["exotropía alternante patrón A", "divergencia alternante A"]'),
('H50.17', 'Exotropía alternante con patrón V', 'Sin especificar', '["exotropía alternante patrón V", "divergencia alternante V"]'),
('H50.18', 'Exotropía alternante con otros defectos de concomitancia', 'Sin especificar', '["exotropía alternante concomitante", "problemas de alineación externa"]'),
('H50.21', 'Estrabismo vertical, ojo derecho', 'Sin especificar', '["ojo derecho más arriba que el otro", "ojo derecho más abajo", "estrabismo vertical derecho", "hipertropía derecho", "hipotropía derecho"]'),
('H50.22', 'Estrabismo vertical, ojo izquierdo', 'Sin especificar', '["ojo izquierdo más arriba que el otro", "ojo izquierdo más abajo", "estrabismo vertical izquierdo", "hipertropía izquierdo", "hipotropía izquierdo"]'),
('H50.30', 'Heterotropía intermitente no especificada', 'Sin especificar', '["estrabismo que aparece y desaparece", "ojo que se desvía a veces", "ojos a veces desviados", "desviación ocular intermitente"]'),
('H50.311', 'Esotropía monocular intermitente, ojo derecho', 'Sin especificar', '["ojo derecho se desvía a veces al centro", "esotropía intermitente derecho"]'),
('H50.312', 'Esotropía monocular intermitente, ojo izquierdo', 'Sin especificar', '["ojo izquierdo se desvía a veces al centro", "esotropía intermitente izquierdo"]'),
('H50.32', 'Esotropía alternante intermitente', 'Sin especificar', '["bizquera que aparece a ratos y cambia de ojo"]'),
('H50.331', 'Exotropía monocular intermitente, ojo derecho', 'Sin especificar', '["ojo derecho se va a veces hacia afuera"]'),
('H50.332', 'Exotropía monocular intermitente, ojo izquierdo', 'Sin especificar', '["ojo izquierdo se va a veces hacia afuera"]'),
('H50.34', 'Exotropía alternante intermitente', 'Sin especificar', '["divergencia que aparece a ratos alternando ojos"]'),
('H50.40', 'Heterotropía no especificada', 'Sin especificar', '["desviación de ojos", "estrabismo no clasificado", "ojos desalineados"]'),
('H50.411', 'Ciclotropía, ojo derecho', 'Sin especificar', '["ojo derecho rotado", "torsión ocular derecho", "problemas de rotación ocular derecho"]'),
('H50.412', 'Ciclotropía, ojo izquierdo', 'Sin especificar', '["ojo izquierdo rotado", "torsión ocular izquierdo", "problemas de rotación ocular izquierdo"]'),
('H50.42', 'Síndrome de monofijación', 'Sin especificar', '["ojo dominante", "falta de visión binocular", "visión de un solo ojo", "problemas de enfoque binocular"]'),
('H50.43', 'Componente acomodativo en esotropía', 'Sin especificar', '["esotropía por esfuerzo visual", "esotropía acomodativa", "bizquera al esforzar la vista"]'),
('H50.50', 'Heteroforia no especificada', 'Sin especificar', '["ojo oculto", "estrabismo latente", "cansancio ocular por desalineación"]'),
('H50.51', 'Esoforia', 'Sin especificar', '["tendencia a bizquera interna", "esoforia", "ojo que quiere irse hacia adentro"]'),
('H50.52', 'Exoforia', 'Sin especificar', '["tendencia a bizquera externa", "exoforia", "ojo que quiere irse hacia afuera"]'),
('H50.53', 'Heteroforia vertical', 'Sin especificar', '["tendencia a ojo arriba abajo", "desalineación vertical latente"]'),
('H50.54', 'Cicloforia', 'Sin especificar', '["tendencia a rotación ocular", "torsión ocular latente"]'),
('H50.55', 'Heteroforia alternante', 'Sin especificar', '["heteroforia que cambia de ojo"]'),
('H50.60', 'Estrabismo mecánico no especificado', 'Sin especificar', '["estrabismo por músculo bloqueado", "ojo trabado", "estrabismo restrictivo"]'),
('H50.611', 'Síndrome de la vaina de Brown, ojo derecho', 'Sin especificar', '["síndrome de Brown ojo derecho", "ojo derecho no sube bien"]'),
('H50.612', 'Síndrome de la vaina de Brown, ojo izquierdo', 'Sin especificar', '["síndrome de Brown ojo izquierdo", "ojo izquierdo no sube bien"]'),
('H50.621', 'Atrapamiento del músculo oblicuo inferior, ojo derecho', 'Sin especificar', '["músculo del ojo derecho trabado", "no puedo mover el ojo derecho"]'),
('H50.622', 'Atrapamiento del músculo oblicuo inferior, ojo izquierdo', 'Sin especificar', '["músculo del ojo izquierdo trabado", "no puedo mover el ojo izquierdo"]'),
('H50.629', 'Atrapamiento del músculo oblicuo inferior, ojo no especificado', 'Sin especificar', '["atrapamiento músculo oblicuo"]'),
('H50.631', 'Atrapamiento del músculo recto inferior, ojo derecho', 'Sin especificar', '["ojo derecho atrapado recto inferior"]'),
('H50.632', 'Atrapamiento del músculo recto inferior, ojo izquierdo', 'Sin especificar', '["ojo izquierdo atrapado recto inferior"]'),
('H50.639', 'Atrapamiento del músculo recto inferior, ojo no especificado', 'Sin especificar', '["atrapamiento recto inferior"]'),
('H50.641', 'Atrapamiento del músculo recto lateral, ojo derecho', 'Sin especificar', '["ojo derecho no mueve a los lados"]'),
('H50.642', 'Atrapamiento del músculo recto lateral, ojo izquierdo', 'Sin especificar', '["ojo izquierdo no mueve a los lados"]'),
('H50.649', 'Atrapamiento del músculo recto lateral, ojo no especificado', 'Sin especificar', '["atrapamiento recto lateral"]'),
('H50.651', 'Atrapamiento del músculo recto medial, ojo derecho', 'Sin especificar', '["ojo derecho bloqueado recto medial"]'),
('H50.652', 'Atrapamiento del músculo recto medial, ojo izquierdo', 'Sin especificar', '["ojo izquierdo bloqueado recto medial"]'),
('H50.659', 'Atrapamiento del músculo recto medial, ojo no especificado', 'Sin especificar', '["atrapamiento recto medial"]'),
('H50.661', 'Atrapamiento del músculo oblicuo superior, ojo derecho', 'Sin especificar', '["ojo derecho bloqueado oblicuo superior"]'),
('H50.662', 'Atrapamiento del músculo oblicuo superior, ojo izquierdo', 'Sin especificar', '["ojo izquierdo bloqueado oblicuo superior"]'),
('H50.669', 'Atrapamiento del músculo oblicuo superior, ojo no especificado', 'Sin especificar', '["atrapamiento oblicuo superior"]'),
('H50.671', 'Atrapamiento del músculo recto superior, ojo derecho', 'Sin especificar', '["ojo derecho no sube recto superior"]'),
('H50.672', 'Atrapamiento del músculo recto superior, ojo izquierdo', 'Sin especificar', '["ojo izquierdo no sube recto superior"]'),
('H50.679', 'Atrapamiento del músculo recto superior, ojo no especificado', 'Sin especificar', '["atrapamiento recto superior"]'),
('H50.681', 'Atrapamiento de músculo extraocular, no especificado, ojo derecho', 'Sin especificar', '["músculo ojo derecho trabado"]'),
('H50.682', 'Atrapamiento de músculo extraocular, no especificado, ojo izquierdo', 'Sin especificar', '["músculo ojo izquierdo trabado"]'),
('H50.689', 'Atrapamiento de músculo extraocular, no especificado, ojo no especificado', 'Sin especificar', '["músculo extraocular bloqueado"]'),
('H50.69', 'Otros estrabismos mecánicos', 'Sin especificar', '["estrabismo mecánico raro", "ojo trabado por cirugía o trauma"]'),
('H50.811', 'Síndrome de Duane, ojo derecho', 'Sin especificar', '["síndrome de Duane ojo derecho", "limitación movimiento ojo derecho"]'),
('H50.812', 'Síndrome de Duane, ojo izquierdo', 'Sin especificar', '["síndrome de Duane ojo izquierdo", "limitación movimiento ojo izquierdo"]'),
('H50.89', 'Otros tipos de estrabismo especificados', 'Sin especificar', '["estrabismo mixto", "estrabismo complejo"]'),
('H50.9', 'Estrabismo no especificado', 'Sin especificar', '["ojo bizco", "bizquera", "ojos chuecos", "ojos desalineados", "problema de desviación de ojos", "estrabismo", "ojos que no miran al mismo lugar", "ojos que se cruzan", "ojo virado"]');
