INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A17.0', 'Meningitis tuberculosa', 'Sin especificar', '["meningitis por tuberculosis", "inflamación de las meninges tuberculosa", "fiebre tifoidea cerebral", "dolor de cabeza intenso", "rigidez de nuca", "fotofobia", "vómitos en proyectil", "fiebre alta", "infección en la cabeza", "tuberculosis del cerebro", "meningitis bacteriana TB", "rigidez en el cuello", "dolor de coco", "malestar en la sesera", "tisis meníngea"]'),
('A17.1', 'Tuberculoma meníngeo', 'Sin especificar', '["tumor tuberculoso en meninges", "masa por tuberculosis cerebral", "bolita en el cerebro por TB", "nódulo tuberculoso meníngeo", "lesión en las meninges", "absceso cerebral tuberculoso", "tumor en la cabeza", "tuberculoma en las membranas del cerebro", "masa infecciosa craneal", "tuberculosis del sistema nervioso central", "quiste tuberculoso", "masa en la sesera", "bulto en la cabeza", "cabeza pesada", "nódulo de koch"]'),
('A17.81', 'Tuberculoma de cerebro y médula espinal', 'Sin especificar', '["tuberculoma cerebral", "tuberculoma en la médula", "lesiones tuberculosas en el sistema nervioso", "tumor en la columna por tuberculosis", "masa en el cerebro y espina", "tuberculosis del cerebro y médula", "bolas tuberculosas en el sistema nervioso", "nódulos en la columna", "infección tuberculosa del SNC", "tumor medular TB", "masa en la sesera y espalda", "tuberculosis espinal", "lesión ocupante de espacio cerebral", "bultos en el sistema nervioso", "afectación del sistema nervioso central por koch"]'),
('A17.82', 'Meningoencefalitis tuberculosa', 'Sin especificar', '["inflamación de cerebro y meninges TB", "meningitis y encefalitis tuberculosa", "infección del cerebro y membranas", "encefalitis por koch", "fiebre y confusión mental TB", "infección severa del sistema nervioso", "tuberculosis cerebral grave", "meningoencefalitis por TBC", "dolor de cabeza y fiebre alta", "alteración del estado mental tuberculosa", "infección de las capas del cerebro", "tisis cerebral", "inflamación en la azotea", "mal del cerebro", "fiebre cerebral"]'),
('A17.83', 'Neuritis tuberculosa', 'Sin especificar', '["inflamación de los nervios por tuberculosis", "dolor en los nervios TB", "neuritis por TBC", "daño a los nervios por koch", "dolor punzante por tuberculosis", "entumecimiento por tuberculosis", "hormigueo en los nervios", "infección nerviosa tuberculosa", "dolor neuropático por TB", "problemas en los nervios tuberculosos", "inflamación nerviosa", "pinchazos en el cuerpo TB", "dolor en los miembros por koch", "neuritis de koch", "calambres por tuberculosis"]'),
('A17.89', 'Otras tuberculosis del sistema nervioso', 'Sin especificar', '["tuberculosis del sistema nervioso central", "otras formas de TBC nerviosa", "infección tuberculosa craneal", "afectación neurológica por tuberculosis", "tuberculosis de los nervios", "tuberculosis del encéfalo", "complicaciones neurológicas de la TB", "tuberculosis del canal espinal", "infección por bacilo de koch en nervios", "tuberculosis encéfalo-raquídea", "lesión del sistema nervioso por koch", "tuberculosis oculta del sistema nervioso", "daño cerebral por tuberculosis", "problemas del sistema nervioso por koch", "tisis del sistema nervioso"]'),
('A17.9', 'Tuberculosis del sistema nervioso, no especificada', 'Sin especificar', '["tuberculosis nerviosa", "infección por tuberculosis en la cabeza o médula", "TBC del sistema nervioso", "tuberculosis en el cerebro", "mal de koch en el sistema nervioso", "enfermedad tuberculosa del sistema nervioso", "infección por bacilo de koch", "tuberculosis del SNC", "problemas nerviosos por tuberculosis", "infección de la sesera", "tuberculosis del sistema nervioso central", "sospecha de tuberculosis nerviosa", "tuberculosis desconocida en el sistema nervioso", "tuberculosis craneal o espinal", "afectación tuberculosa nerviosa"]');
