INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K00.0', 'Anodoncia', 'Sin especificar', '["falta de dientes", "no me salen los dientes", "dientes ausentes", "sin piezas dentales", "anodoncia parcial", "agenesia dental", "diente de leche que nunca salió", "hueco en la encía", "falta de muelas", "anodoncia total", "edentulismo", "dientes que no bajaron", "ausencia congénita de dientes"]'),
('K00.1', 'Dientes supernumerarios', 'Sin especificar', '["dientes de más", "diente extra", "dientes encimados", "poliodoncia", "hiperdoncia", "diente doble", "me está saliendo otro diente", "dientes amontonados", "diente de tiburón", "dientes extra en el paladar", "dientes adicionales", "dientes de más en la encía"]'),
('K00.2', 'Anomalías de tamaño y de forma de los dientes', 'Sin especificar', '["dientes deformes", "dientes muy grandes", "dientes muy pequeños", "microdoncia", "macrodoncia", "dientes con forma rara", "dientes de conejo", "dientes en forma de clavo", "dientes fusionados", "dientes pegados", "dientes raros", "geminación dental", "dientes con puntas extrañas"]'),
('K00.3', 'Dientes manchados', 'Sin especificar', '["dientes amarillos", "dientes con manchas blancas", "manchas negras en los dientes", "dientes oscurecidos", "fluorosis", "dientes con líneas marrones", "dientes percudidos", "manchas en el esmalte", "dientes manchados por café", "dientes con sarro", "dientes con caries incipientes", "hipoplasia", "esmalte decolorado"]'),
('K00.4', 'Alteraciones en la formación de los dientes', 'Sin especificar', '["dientes mal formados", "esmalte débil", "dientes con huecos", "dientes que se desgastan", "hipoplasia del esmalte", "dientes con surcos", "dientes frágiles", "formación incompleta de dientes", "dientes deformados", "esmalte rugoso", "dientes delgados", "problemas en la calcificación"]'),
('K00.5', 'Alteraciones hereditarias en la estructura dental, no clasificadas bajo otro concepto', 'Sin especificar', '["dientes genéticos", "dentinogénesis imperfecta", "amelogénesis imperfecta", "dientes que se rompen fácil", "dientes de color raro genético", "mala estructura dental", "dientes hereditarios", "esmalte que se cae solo", "dientes débiles de familia", "trastornos dentales congénitos", "dientes transparentes", "dientes quebradizos"]'),
('K00.6', 'Alteraciones en erupción de diente', 'Sin especificar', '["diente que no sale", "diente enterrado", "diente impactado", "diente retenido", "diente chueco", "erupción tardía", "diente que no baja", "dolor al salir diente", "diente atrapado en la encía", "diente inclinado", "me duele cuando sale la muela", "diente de leche que no se cae"]'),
('K00.7', 'Síndrome de la erupción dentaria', 'Sin especificar', '["dolor de encías por dientes", "salida de dientes en bebés", "me están saliendo las muelas del juicio", "dolor de muela del juicio", "encía inflamada por diente", "dientes picando la encía", "fiebre por salida de dientes", "molestia al brotar diente", "encía roja y dolorosa", "diente rompiendo encía", "malestar por dentición", "babeo por dientes"]'),
('K00.8', 'Otros trastornos del desarrollo de los dientes', 'Sin especificar', '["problemas con mis dientes", "dientes raros", "desarrollo dental anormal", "dientes que no crecen bien", "problemas de crecimiento dental", "alteraciones dentarias no especificadas", "dientes chuecos por desarrollo", "dientes flojos desde niños", "dientes con malformación interna", "defectos en el crecimiento dental"]'),
('K00.9', 'Trastorno del desarrollo del diente, no especificado', 'Sin especificar', '["problema en los dientes", "dolor dental raro", "dientes que no se ven bien", "algo pasa con mis dientes", "anomalía dental", "dientes raros y con dolor", "problema en la dentadura", "dientes que no están bien formados", "defecto en el diente", "diente con apariencia extraña"]');
