INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('V91.00XA', 'Quemadura debida a fuego en barco mercante, contacto inicial', 'Sin especificar', '["quemadura en barco", "fuego en alta mar", "incendio en navío", "quemado en barco mercante", "accidente por incendio en buque", "fuego en el mar", "herida por fuego en barco", "accidente laboral marítimo", "quemaduras en carga", "incendio naval", "emergencia en buque mercante"]'),
('V91.00XD', 'Quemadura debida a fuego en barco mercante, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura barco", "control quemadura incendio barco", "cura quemadura en buque", "quemadura por incendio náutico recurrente", "tratamiento tras quemadura en barco", "evolución quemadura en altamar", "segunda revisión quemadura por fuego en navío"]'),
('V91.00XS', 'Quemadura debida a fuego en barco mercante, secuela', 'Sin especificar', '["cicatriz por quemadura en barco", "secuela incendio buque", "marcas por fuego en el mar", "quemadura vieja de barco", "secuelas de incendio mercante", "deformidad por quemadura en navío", "cicatrices tras accidente náutico"]'),
('V91.01XA', 'Quemadura debida a fuego en barco de pasajeros, contacto inicial', 'Sin especificar', '["incendio en crucero", "fuego en barco de pasajeros", "quemadura en vacaciones en barco", "accidente en barco de turistas", "fuego a bordo con pasajeros", "quemado en ferry", "incendio en transatlántico", "quemaduras por fuego en viaje en barco"]'),
('V91.01XD', 'Quemadura debida a fuego en barco de pasajeros, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura crucero", "cura por fuego en ferry", "revisión herida quemadura buque pasajeros", "tratamiento quemadura tras incendio en navío"]'),
('V91.01XS', 'Quemadura debida a fuego en barco de pasajeros, secuela', 'Sin especificar', '["secuela incendio crucero", "cicatriz quemadura ferry", "marcas por fuego en barco de turistas", "huella de accidente en crucero"]'),
('V91.02XA', 'Quemadura debida a fuego en barco de pesca, contacto inicial', 'Sin especificar', '["incendio en barquito de pesca", "fuego en lancha pesquera", "quemado en faena de pesca", "fuego en pesquero", "quemadura en trabajo de mar", "incendio en barca de pescadores"]'),
('V91.02XD', 'Quemadura debida a fuego en barco de pesca, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura pesquero", "cura incendio embarcación pesca", "control quemadura pescador"]'),
('V91.02XS', 'Quemadura debida a fuego en barco de pesca, secuela', 'Sin especificar', '["cicatriz por fuego en lancha", "secuela incendio pesquero", "marcas de quemadura por trabajo pesquero"]'),
('V91.03XA', 'Quemadura debida a fuego en otra embarcación motorizada, contacto inicial', 'Sin especificar', '["quemado en lancha motor", "incendio en yate", "fuego en lancha rápida", "quemadura en moto de agua", "fuego en barco a motor"]'),
('V91.03XD', 'Quemadura debida a fuego en otra embarcación motorizada, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura yate", "cura quemadura lancha", "revisión incendio vehículo acuático"]'),
('V91.03XS', 'Quemadura debida a fuego en otra embarcación motorizada, secuela', 'Sin especificar', '["secuela quemadura yate", "cicatrices por fuego en lancha motor", "marcas accidente acuático motorizado"]'),
('V91.04XA', 'Quemadura debida a fuego en velero, contacto inicial', 'Sin especificar', '["fuego en velero", "quemadura en barco de vela", "incendio en velero", "quemado en velero", "accidente con fuego en embarcación de vela"]'),
('V91.04XD', 'Quemadura debida a fuego en velero, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura velero", "cura por incendio en barco de vela"]'),
('V91.04XS', 'Quemadura debida a fuego en velero, secuela', 'Sin especificar', '["secuela quemadura velero", "cicatrices en barco de vela"]'),
('V91.05XA', 'Quemadura debida a fuego en canoa o kayak, contacto inicial', 'Sin especificar', '["quemadura en kayak", "incendio en canoa", "fuego en piragua", "quemado en kayak"]'),
('V91.05XD', 'Quemadura debida a fuego en canoa o kayak, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura kayak", "revisión quemadura canoa"]'),
('V91.05XS', 'Quemadura debida a fuego en canoa o kayak, secuela', 'Sin especificar', '["secuela quemadura canoa", "marcas por fuego en kayak"]'),
('V91.06XA', 'Quemadura debida a fuego en embarcación inflable sin motor, contacto inicial', 'Sin especificar', '["fuego en balsa inflable", "quemadura en inflable", "incendio en bote de goma", "quemado en gomón"]'),
('V91.06XD', 'Quemadura debida a fuego en embarcación inflable sin motor, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura balsa", "cura quemadura bote inflable"]'),
('V91.06XS', 'Quemadura debida a fuego en embarcación inflable sin motor, secuela', 'Sin especificar', '["cicatriz quemadura inflable", "secuela incendio balsa de goma"]'),
('V91.07XA', 'Quemadura debida a fuego en esquí acuático, contacto inicial', 'Sin especificar', '["quemadura esquiando", "incendio equipo esquí acuático", "fuego en esquí acuático"]'),
('V91.07XD', 'Quemadura debida a fuego en esquí acuático, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura esquí", "cura herida quemadura acuática"]'),
('V91.07XS', 'Quemadura debida a fuego en esquí acuático, secuela', 'Sin especificar', '["secuela quemadura esquí", "cicatriz esquí acuático"]'),
('V91.08XA', 'Quemadura debida a fuego en otra embarcación no motorizada, contacto inicial', 'Sin especificar', '["quemadura en remo", "fuego en bote de remos", "incendio en barca"]'),
('V91.08XD', 'Quemadura debida a fuego en otra embarcación no motorizada, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura barca", "revisión quemadura remo"]'),
('V91.08XS', 'Quemadura debida a fuego en otra embarcación no motorizada, secuela', 'Sin especificar', '["secuela quemadura barca", "cicatrices remo"]'),
('V91.09XA', 'Quemadura debida a fuego en embarcación no especificada, contacto inicial', 'Sin especificar', '["quemadura en el mar", "quemado en barco", "incendio embarcación"]'),
('V91.09XD', 'Quemadura debida a fuego en embarcación no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura embarcación", "cura quemadura barco"]'),
('V91.09XS', 'Quemadura debida a fuego en embarcación no especificada, secuela', 'Sin especificar', '["secuela quemadura barco", "cicatrices fuego mar"]'),
('V91.10XA', 'Aplastamiento entre barco mercante y otra embarcación u otro objeto debido a colisión, contacto inicial', 'Sin especificar', '["aplastado en barco", "choque barcos", "colisión marítima", "atrapado en colisión mercante", "aplastamiento en puerto"]'),
('V91.10XD', 'Aplastamiento entre barco mercante y otra embarcación u otro objeto debido a colisión, contacto sucesivo', 'Sin especificar', '["rehabilitación por choque barco", "seguimiento lesión aplastamiento"]'),
('V91.10XS', 'Aplastamiento entre barco mercante y otra embarcación u otro objeto debido a colisión, secuela', 'Sin especificar', '["secuela choque barcos", "deformidad por aplastamiento", "secuelas accidente marítimo"]'),
('V91.11XA', 'Aplastamiento entre barco de pasajeros y otra embarcación u otro objeto debido a colisión, contacto inicial', 'Sin especificar', '["choque ferry", "aplastado en crucero", "colisión barco pasajeros", "atrapado en choque turístico"]'),
('V91.11XD', 'Aplastamiento entre barco de pasajeros y otra embarcación u otro objeto debido a colisión, contacto sucesivo', 'Sin especificar', '["recuperación tras colisión crucero", "seguimiento lesión ferry"]'),
('V91.11XS', 'Aplastamiento entre barco de pasajeros y otra embarcación u otro objeto debido a colisión, secuela', 'Sin especificar', '["secuela aplastamiento ferry", "consecuencia choque crucero"]'),
('V91.12XA', 'Aplastamiento entre barco de pesca y otra embarcación u otro objeto debido a colisión, contacto inicial', 'Sin especificar', '["choque pesquero", "atrapado entre barcos pesca", "colisión barco pescador"]'),
('V91.12XD', 'Aplastamiento entre barco de pesca y otra embarcación u otro objeto debido a colisión, contacto sucesivo', 'Sin especificar', '["seguimiento lesión pesquero", "cura choque pesquero"]'),
('V91.12XS', 'Aplastamiento entre barco de pesca y otra embarcación u otro objeto debido a colisión, secuela', 'Sin especificar', '["secuela aplastamiento pesquero", "lesión crónica pesquero"]'),
('V91.13XA', 'Aplastamiento entre otro vehículo acuático a motor y otra embarcación u otro objeto debido a colisión, contacto inicial', 'Sin especificar', '["choque yate", "atrapado en lancha", "colisión moto agua", "aplastamiento lancha motor"]'),
('V91.13XD', 'Aplastamiento entre otro vehículo acuático a motor y otra embarcación u otro objeto debido a colisión, contacto sucesivo', 'Sin especificar', '["seguimiento choque lancha", "cura aplastamiento yate"]'),
('V91.13XS', 'Aplastamiento entre otro vehículo acuático a motor y otra embarcación u otro objeto debido a colisión, secuela', 'Sin especificar', '["secuela choque yate", "lesión persistente lancha"]'),
('V91.14XA', 'Aplastamiento entre velero y otra embarcación u otro objeto debido a colisión, contacto inicial', 'Sin especificar', '["choque velero", "aplastado en barco de vela", "atrapado en velero"]'),
('V91.14XD', 'Aplastamiento entre velero y otra embarcación u otro objeto debido a colisión, contacto sucesivo', 'Sin especificar', '["seguimiento aplastamiento velero", "rehabilitación accidente vela"]'),
('V91.14XS', 'Aplastamiento entre velero y otra embarcación u otro objeto debido a colisión, secuela', 'Sin especificar', '["secuelas velero", "daños tras colisión vela"]'),
('V91.15XA', 'Aplastamiento entre canoa o kayak y otra embarcación u otro objeto debido a colisión, contacto inicial', 'Sin especificar', '["choque kayak", "aplastado en canoa", "atrapado con kayak"]'),
('V91.15XD', 'Aplastamiento entre canoa o kayak y otra embarcación u otro objeto debido a colisión, contacto sucesivo', 'Sin especificar', '["seguimiento golpe kayak", "recuperación accidente canoa"]'),
('V91.15XS', 'Aplastamiento entre canoa o kayak y otra embarcación u otro objeto debido a colisión, secuela', 'Sin especificar', '["secuela choque kayak", "secuela canoa"]'),
('V91.16XA', 'Aplastamiento entre embarcación inflable (sin motor) y otra embarcación u otro objeto debido a colisión, contacto inicial', 'Sin especificar', '["choque balsa inflable", "aplastado en bote de goma", "atrapado en inflable"]'),
('V91.16XD', 'Aplastamiento entre embarcación inflable (sin motor) y otra embarcación u otro objeto debido a colisión, contacto sucesivo', 'Sin especificar', '["rehabilitación tras choque inflable", "seguimiento lesión balsa"]'),
('V91.16XS', 'Aplastamiento entre embarcación inflable (sin motor) y otra embarcación u otro objeto debido a colisión, secuela', 'Sin especificar', '["secuela aplastamiento balsa", "lesión permanente inflable"]'),
('V91.18XA', 'Aplastamiento entre otra embarcación sin motor y otra embarcación u otro objeto debido a colisión, contacto inicial', 'Sin especificar', '["choque barca remo", "aplastamiento embarcación pequeña"]'),
('V91.18XD', 'Aplastamiento entre otra embarcación sin motor y otra embarcación u otro objeto debido a colisión, contacto sucesivo', 'Sin especificar', '["seguimiento choque barca", "cura aplastamiento"]'),
('V91.18XS', 'Aplastamiento entre otra embarcación sin motor y otra embarcación u otro objeto debido a colisión, secuela', 'Sin especificar', '["secuela accidente remo", "daños tras colisión"]'),
('V91.19XA', 'Aplastamiento entre vehículo acuático no especificado y otra embarcación no especificada u otro objeto debido a colisión, contacto inicial', 'Sin especificar', '["choque barco", "aplastamiento en el mar", "atrapado en accidente acuático"]'),
('V91.19XD', 'Aplastamiento entre vehículo acuático no especificado y otra embarcación no especificada u otro objeto debido a colisión, contacto sucesivo', 'Sin especificar', '["seguimiento choque acuático", "recuperación tras colisión"]'),
('V91.19XS', 'Aplastamiento entre vehículo acuático no especificado y otra embarcación no especificada u otro objeto debido a colisión, secuela', 'Sin especificar', '["secuela choque", "lesión persistente"]'),
('V91.20XA', 'Caída debida a colisión entre barco mercante y otra embarcación u otro objeto, contacto inicial', 'Sin especificar', '["caída en barco", "tropiezo barco mercante", "accidente en cubierta mercante", "caída al chocar barco"]'),
('V91.20XD', 'Caída debida a colisión entre barco mercante y otra embarcación u otro objeto, contacto sucesivo', 'Sin especificar', '["seguimiento caída en buque", "rehabilitación tras caída mercante"]'),
('V91.20XS', 'Caída debida a colisión entre barco mercante y otra embarcación u otro objeto, secuela', 'Sin especificar', '["secuela caída barco mercante", "consecuencia tropiezo marítimo"]'),
('V91.21XA', 'Caída debida a colisión entre barco de pasajeros y otra embarcación u otro objeto, contacto inicial', 'Sin especificar', '["caída en crucero", "resbalón en ferry", "accidente en buque de pasajeros"]'),
('V91.21XD', 'Caída debida a colisión entre barco de pasajeros y otra embarcación u otro objeto, contacto sucesivo', 'Sin especificar', '["seguimiento caída crucero", "cura tras caída ferry"]'),
('V91.21XS', 'Caída debida a colisión entre barco de pasajeros y otra embarcación u otro objeto, secuela', 'Sin especificar', '["secuela caída crucero", "lesión persistente ferry"]'),
('V91.22XA', 'Caída debida a colisión entre barco pesquero y otra embarcación u otro objeto, contacto inicial', 'Sin especificar', '["caída en pesquero", "resbalón en lancha pesca", "accidente faena pesca"]'),
('V91.22XD', 'Caída debida a colisión entre barco pesquero y otra embarcación u otro objeto, contacto sucesivo', 'Sin especificar', '["seguimiento caída pesquero", "rehabilitación tras golpe"]'),
('V91.22XS', 'Caída debida a colisión entre barco pesquero y otra embarcación u otro objeto, secuela', 'Sin especificar', '["secuela caída pesquero", "dolor crónico accidente"]'),
('V91.23XA', 'Caída debida a colisión entre otro vehículo acuático con motor y otra embarcación u otro objeto, contacto inicial', 'Sin especificar', '["caída de yate", "caída de lancha motor", "golpe en moto agua"]'),
('V91.23XD', 'Caída debida a colisión entre otro vehículo acuático con motor y otra embarcación u otro objeto, contacto sucesivo', 'Sin especificar', '["seguimiento caída lancha", "cura tras golpe en yate"]'),
('V91.23XS', 'Caída debida a colisión entre otro vehículo acuático con motor y otra embarcación u otro objeto, secuela', 'Sin especificar', '["secuela caída yate", "consecuencia choque lancha"]'),
('V91.24XA', 'Caída debida a colisión entre barco de vela y otra embarcación u otro objeto, contacto inicial', 'Sin especificar', '["caída en velero", "resbalón en barco vela", "golpe en velero"]'),
('V91.24XD', 'Caída debida a colisión entre barco de vela y otra embarcación u otro objeto, contacto sucesivo', 'Sin especificar', '["seguimiento caída velero", "rehabilitación tras tropiezo"]'),
('V91.24XS', 'Caída debida a colisión entre barco de vela y otra embarcación u otro objeto, secuela', 'Sin especificar', '["secuela caída velero", "lesión post accidente vela"]'),
('V91.25XA', 'Caída debida a colisión entre canoa o kayak y otra embarcación u otro objeto, contacto inicial', 'Sin especificar', '["caída de kayak", "caída de canoa", "golpe en piragua"]'),
('V91.25XD', 'Caída debida a colisión entre canoa o kayak y otra embarcación u otro objeto, contacto sucesivo', 'Sin especificar', '["seguimiento caída kayak", "cura tras caída canoa"]'),
('V91.25XS', 'Caída debida a colisión entre canoa o kayak y otra embarcación u otro objeto, secuela', 'Sin especificar', '["secuela caída kayak", "secuela caída canoa"]'),
('V91.26XA', 'Caída debida a colisión entre embarcación inflable (sin motor) y otro vehículo acuático u otro objeto, contacto inicial', 'Sin especificar', '["caída de balsa inflable", "golpe en inflable"]'),
('V91.26XD', 'Caída debida a colisión entre embarcación inflable (sin motor) y otro vehículo acuático u otro objeto, contacto sucesivo', 'Sin especificar', '["seguimiento caída balsa", "recuperación tras caída"]'),
('V91.26XS', 'Caída debida a colisión entre embarcación inflable (sin motor) y otro vehículo acuático u otro objeto, secuela', 'Sin especificar', '["secuela caída inflable", "daños tras golpe balsa"]'),
('V91.29XA', 'Caída debida a colisión entre vehículo acuático no especificado y otra embarcación u otro objeto, contacto inicial', 'Sin especificar', '["caída en el mar", "resbalón barco", "tropiezo embarcación"]'),
('V91.29XD', 'Caída debida a colisión entre vehículo acuático no especificado y otra embarcación u otro objeto, contacto sucesivo', 'Sin especificar', '["seguimiento caída barco", "rehabilitación tras caída"]'),
('V91.29XS', 'Caída debida a colisión entre vehículo acuático no especificado y otra embarcación u otro objeto, secuela', 'Sin especificar', '["secuela caída barco", "daños persistentes caída"]'),
('V91.30XA', 'Golpe por caída de objeto debido a accidente con barco mercante, contacto inicial', 'Sin especificar', '["golpeado por objeto barco", "objeto caído mercante", "accidente carga buque", "golpe en cubierta"]'),
('V91.30XD', 'Golpe por caída de objeto debido a accidente con barco mercante, contacto sucesivo', 'Sin especificar', '["seguimiento traumatismo barco", "rehabilitación golpe objeto"]'),
('V91.30XS', 'Golpe por caída de objeto debido a accidente con barco mercante, secuela', 'Sin especificar', '["secuela golpe objeto mercante", "daño crónico accidente"]'),
('V91.31XA', 'Golpe por caída de objeto debido a accidente con barco de pasajeros, contacto inicial', 'Sin especificar', '["objeto caído crucero", "golpe en barco pasajeros", "accidente objetos ferry"]'),
('V91.31XD', 'Golpe por caída de objeto debido a accidente con barco de pasajeros, contacto sucesivo', 'Sin especificar', '["seguimiento golpe crucero", "recuperación traumatismo"]'),
('V91.31XS', 'Golpe por caída de objeto debido a accidente con barco de pasajeros, secuela', 'Sin especificar', '["secuela golpe crucero", "daños post accidente ferry"]'),
('V91.32XA', 'Golpe por caída de objeto debido a accidente a pesca en barco, contacto inicial', 'Sin especificar', '["golpeado pesca", "objeto cae en pesquero", "accidente equipos pesca"]'),
('V91.32XD', 'Golpe por caída de objeto debido a accidente a pesca en barco, contacto sucesivo', 'Sin especificar', '["seguimiento golpe pesquero", "cura traumatismo"]'),
('V91.32XS', 'Golpe por caída de objeto debido a accidente a pesca en barco, secuela', 'Sin especificar', '["secuela golpe pesquero", "lesión crónica pesca"]'),
('V91.33XA', 'Golpe por caída de objeto debido a accidente con otra embarcación motorizada, contacto inicial', 'Sin especificar', '["golpe objeto yate", "objeto cae en lancha"]'),
('V91.33XD', 'Golpe por caída de objeto debido a accidente con otra embarcación motorizada, contacto sucesivo', 'Sin especificar', '["seguimiento golpe yate", "rehabilitación lancha"]'),
('V91.33XS', 'Golpe por caída de objeto debido a accidente con otra embarcación motorizada, secuela', 'Sin especificar', '["secuela golpe yate", "daños lancha"]'),
('V91.34XA', 'Golpe por caída de objeto debido a accidente con barco de vela, contacto inicial', 'Sin especificar', '["golpeado objeto velero", "caída mástil", "accidente vela"]'),
('V91.34XD', 'Golpe por caída de objeto debido a accidente con barco de vela, contacto sucesivo', 'Sin especificar', '["seguimiento golpe velero", "cura traumatismo vela"]'),
('V91.34XS', 'Golpe por caída de objeto debido a accidente con barco de vela, secuela', 'Sin especificar', '["secuela golpe velero", "daños mástil"]'),
('V91.35XA', 'Golpe por caída de objeto debido a accidente con canoa o kayak, contacto inicial', 'Sin especificar', '["golpe objeto kayak", "caída remo kayak"]'),
('V91.35XD', 'Golpe por caída de objeto debido a accidente con canoa o kayak, contacto sucesivo', 'Sin especificar', '["seguimiento golpe kayak", "rehabilitación remo"]'),
('V91.35XS', 'Golpe por caída de objeto debido a accidente con canoa o kayak, secuela', 'Sin especificar', '["secuela golpe kayak", "lesión post canoa"]'),
('V91.36XA', 'Golpe por caída de objeto debido a accidente con embarcación inflable sin motor, contacto inicial', 'Sin especificar', '["golpe objeto inflable", "caída bomba aire"]'),
('V91.36XD', 'Golpe por caída de objeto debido a accidente con embarcación inflable sin motor, contacto sucesivo', 'Sin especificar', '["seguimiento golpe inflable", "cura objeto balsa"]'),
('V91.36XS', 'Golpe por caída de objeto debido a accidente con embarcación inflable sin motor, secuela', 'Sin especificar', '["secuela golpe balsa", "lesión post inflable"]'),
('V91.37XA', 'Golpe por caída de objeto debido a accidente a esquíes acuáticos, contacto inicial', 'Sin especificar', '["golpe objeto esquí", "caída equipo acuático"]'),
('V91.37XD', 'Golpe por caída de objeto debido a accidente a esquíes acuáticos, contacto sucesivo', 'Sin especificar', '["seguimiento golpe esquí", "recuperación golpe"]'),
('V91.37XS', 'Golpe por caída de objeto debido a accidente a esquíes acuáticos, secuela', 'Sin especificar', '["secuela golpe esquí", "daño post esquí"]'),
('V91.38XA', 'Golpe por caída de objeto debido a accidente con otra embarcación sin motor, contacto inicial', 'Sin especificar', '["golpe objeto remo", "caída objeto barca"]'),
('V91.38XD', 'Golpe por caída de objeto debido a accidente con otra embarcación sin motor, contacto sucesivo', 'Sin especificar', '["seguimiento golpe barca", "cura barca"]'),
('V91.38XS', 'Golpe por caída de objeto debido a accidente con otra embarcación sin motor, secuela', 'Sin especificar', '["secuela golpe barca", "lesión post remo"]'),
('V91.39XA', 'Golpe por caída de objeto debido a accidente con embarcación no especificada, contacto inicial', 'Sin especificar', '["golpe objeto barco", "caída equipo mar"]'),
('V91.39XD', 'Golpe por caída de objeto debido a accidente con embarcación no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento golpe barco", "cura equipo"]'),
('V91.39XS', 'Golpe por caída de objeto debido a accidente con embarcación no especificada, secuela', 'Sin especificar', '["secuela golpe barco", "lesión barco"]'),
('V91.80XA', 'Otro tipo de lesión por otro tipo de accidente con barco mercante, contacto inicial', 'Sin especificar', '["accidente buque mercante", "lesión marítima mercante"]'),
('V91.80XD', 'Otro tipo de lesión por otro tipo de accidente con barco mercante, contacto sucesivo', 'Sin especificar', '["seguimiento lesión mercante", "cura accidente buque"]'),
('V91.80XS', 'Otro tipo de lesión por otro tipo de accidente con barco mercante, secuela', 'Sin especificar', '["secuela lesión mercante", "daño permanente buque"]'),
('V91.81XA', 'Otro tipo de lesión por otro tipo de accidente con barco de pasajeros, contacto inicial', 'Sin especificar', '["lesión crucero", "accidente barco pasajeros"]'),
('V91.81XD', 'Otro tipo de lesión por otro tipo de accidente con barco de pasajeros, contacto sucesivo', 'Sin especificar', '["seguimiento lesión crucero", "recuperación accidente"]'),
('V91.81XS', 'Otro tipo de lesión por otro tipo de accidente con barco de pasajeros, secuela', 'Sin especificar', '["secuela lesión crucero", "secuela barco pasajeros"]'),
('V91.82XA', 'Otro tipo de lesión por otro tipo de accidente con barco de pesca, contacto inicial', 'Sin especificar', '["lesión pesquero", "accidente faena"]'),
('V91.82XD', 'Otro tipo de lesión por otro tipo de accidente con barco de pesca, contacto sucesivo', 'Sin especificar', '["seguimiento lesión pesquero", "cura pesquero"]'),
('V91.82XS', 'Otro tipo de lesión por otro tipo de accidente con barco de pesca, secuela', 'Sin especificar', '["secuela lesión pesquero", "secuela accidente pesca"]'),
('V91.83XA', 'Otro tipo de lesión por otro tipo de accidente con otra embarcación motorizada, contacto inicial', 'Sin especificar', '["lesión yate", "accidente lancha"]'),
('V91.83XD', 'Otro tipo de lesión por otro tipo de accidente con otra embarcación motorizada, contacto sucesivo', 'Sin especificar', '["seguimiento lesión yate", "cura lancha"]'),
('V91.83XS', 'Otro tipo de lesión por otro tipo de accidente con otra embarcación motorizada, secuela', 'Sin especificar', '["secuela lesión yate", "secuela lancha"]'),
('V91.84XA', 'Otro tipo de lesión por otro tipo de accidente con barco de vela, contacto inicial', 'Sin especificar', '["lesión velero", "accidente vela"]'),
('V91.84XD', 'Otro tipo de lesión por otro tipo de accidente con barco de vela, contacto sucesivo', 'Sin especificar', '["seguimiento lesión velero", "cura vela"]'),
('V91.84XS', 'Otro tipo de lesión por otro tipo de accidente con barco de vela, secuela', 'Sin especificar', '["secuela lesión velero", "secuela vela"]'),
('V91.85XA', 'Otra lesión por otro tipo de accidente con canoa o kayak, contacto inicial', 'Sin especificar', '["lesión kayak", "accidente canoa"]'),
('V91.85XD', 'Otra lesión por otro tipo de accidente con canoa o kayak, contacto sucesivo', 'Sin especificar', '["seguimiento lesión kayak", "cura canoa"]'),
('V91.85XS', 'Otra lesión por otro tipo de accidente con canoa o kayak, secuela', 'Sin especificar', '["secuela lesión kayak", "secuela canoa"]'),
('V91.86XA', 'Otro tipo de lesión por otro tipo de accidente con embarcación inflable (sin motor), contacto inicial', 'Sin especificar', '["lesión balsa", "accidente inflable"]'),
('V91.86XD', 'Otro tipo de lesión por otro tipo de accidente con embarcación inflable (sin motor), contacto sucesivo', 'Sin especificar', '["seguimiento lesión balsa", "cura inflable"]'),
('V91.86XS', 'Otro tipo de lesión por otro tipo de accidente con embarcación inflable (sin motor), secuela', 'Sin especificar', '["secuela lesión balsa", "secuela inflable"]'),
('V91.87XA', 'Otra lesión por otro tipo de accidente con esquí náutico, contacto inicial', 'Sin especificar', '["lesión esquí", "accidente acuático"]'),
('V91.87XD', 'Otra lesión por otro tipo de accidente con esquí náutico, contacto sucesivo', 'Sin especificar', '["seguimiento lesión esquí", "cura esquí"]'),
('V91.87XS', 'Otra lesión por otro tipo de accidente con esquí náutico, secuela', 'Sin especificar', '["secuela lesión esquí", "secuela accidente"]'),
('V91.88XA', 'Otra lesión por otro tipo de accidente con embarcación no motorizada, contacto inicial', 'Sin especificar', '["lesión remo", "accidente bote"]'),
('V91.88XD', 'Otra lesión por otro tipo de accidente con embarcación no motorizada, contacto sucesivo', 'Sin especificar', '["seguimiento lesión remo", "cura bote"]'),
('V91.88XS', 'Otra lesión por otro tipo de accidente con embarcación no motorizada, secuela', 'Sin especificar', '["secuela lesión remo", "secuela bote"]'),
('V91.89XA', 'Otro tipo de lesión por otro tipo de accidente con embarcación no especificada, contacto inicial', 'Sin especificar', '["lesión barco", "accidente mar"]'),
('V91.89XD', 'Otro tipo de lesión por otro tipo de accidente con embarcación no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento lesión barco", "cura mar"]'),
('V91.89XS', 'Otro tipo de lesión por otro tipo de accidente con embarcación no especificada, secuela', 'Sin especificar', '["secuela lesión barco", "secuela mar"]');
