INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A60.00', 'Infección por herpesvirus del sistema urogenital, no especificada', 'Sin especificar', '["herpes genital", "infección sexual", "llagas en la zona íntima", "ampollas genitales", "ETS", "herpes en mis partes", "picazón genital", "herpes simple", "brotes en la zona pélvica", "infección urinaria por herpes", "herpesvirus urogenital", "dolor al orinar", "ardor en partes íntimas", "herpes infeccioso", "enfermedad de transmisión sexual"]'),
('A60.01', 'Infección por herpesvirus del pene', 'Sin especificar', '["herpes en el pene", "llagas en el miembro", "ampollas en el pito", "herpes en el nepe", "herpes en la verga", "granitos en el pene", "lesiones en el glande", "herpes viril", "herpes en la pichula", "herpes en el choto", "herpes en el pingo", "infección genital masculina", "brotes en el miembro", "herpes en el falo", "ardor en el pene"]'),
('A60.02', 'Infección por herpesvirus de otros órganos genitales masculinos', 'Sin especificar', '["herpes en los testículos", "herpes en el escroto", "herpes en la bolsa", "herpes en los huevos", "herpes en el perineo masculino", "lesiones genitales masculinas", "ampollas en el escroto", "infección herpética escrotal", "herpes en la zona genital hombre", "brotes en los testículos", "llagas en la zona íntima masculina", "herpes en el área del perineo", "infección en órganos reproductores masculinos", "dolor en los testículos por herpes", "picazón escrotal"]'),
('A60.03', 'Cervicitis por herpesvirus', 'Sin especificar', '["herpes en el cuello uterino", "herpes en la matriz", "cervicitis herpética", "inflamación del cuello uterino por herpes", "herpes interno mujer", "flujo por herpes", "herpes en el cérvix", "herpes vaginal profundo", "dolor pélvico por herpes", "infección herpética en la matriz", "herpes ginecológico", "cervicitis infecciosa", "lesiones internas vagina", "ardor en el cuello uterino", "herpes cervical"]'),
('A60.04', 'Vulvovaginitis por herpesvirus', 'Sin especificar', '["herpes en la vulva", "herpes vaginal", "vulvovaginitis herpética", "llagas en la vagina", "ampollas en los labios vaginales", "herpes en la panocha", "herpes en la concha", "herpes en el choro", "herpes en la vayaina", "picazón en la vulva", "ardor vaginal", "infección en la parte de afuera", "herpes en el toti", "lesiones en la zona íntima femenina", "herpes vulvar"]'),
('A60.09', 'Otras infecciones por herpesvirus del tracto urogenital', 'Sin especificar', '["herpes en las partes bajas", "infección urogenital herpética", "herpes en la zona baja", "brotes genitales", "herpes recurrente", "herpes en la zona pélvica", "llagas zona íntima", "herpesvirus tracto urogenital", "infección por virus del herpes", "molestias genitales por herpes", "lesiones por herpes", "picazón en zona baja", "herpes no especificado", "herpes sexual", "herpes genitourinario"]'),
('A60.1', 'Infección de la piel perianal y recto por virus del herpes simple', 'Sin especificar', '["herpes anal", "herpes en el culo", "herpes en el ano", "herpes perianal", "herpes en el recto", "llagas en el ano", "ampollas cerca del ano", "picazón anal por herpes", "herpes en la cola", "herpes en el asterisco", "herpes en el traserito", "dolor al defecar por herpes", "herpes en el ano", "lesiones anales", "infección rectal herpética"]'),
('A60.9', 'Infección anogenital por virus del herpes simple, no especificada', 'Sin especificar', '["herpes anogenital", "herpes en zona genital y anal", "infección por herpes simple", "tengo herpes", "herpes", "brotes de herpes", "virus del herpes simple", "herpes en mis partes íntimas", "llagas genitales", "ampollas genitales", "contagio de herpes", "herpes en la zona íntima", "infección por herpes sin especificar", "herpesvirus anogenital", "herpes de transmisión sexual"]');
