INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A36.0', 'Difteria faríngea', 'Sin especificar', '["difteria de garganta", "anginas con placa gris", "membrana en la garganta", "faringitis diftérica", "infección bacteriana garganta", "dolor de garganta severo", "inflamación faríngea", "asfixia por difteria", "placas en las amígdalas", "dificultad para tragar", "garganta cerrada", "tos perruna", "crup", "fiebre y dolor de garganta", "bacterias en la garganta"]'),
('A36.1', 'Difteria nasofaríngea', 'Sin especificar', '["difteria de nariz y garganta", "infección nasofaríngea", "nariz tapada con secreción", "secreción nasal sanguinolenta", "infección de vías respiratorias altas", "obstrucción nasal", "membranas en nariz", "faringitis con rinitis", "infección grave nariz garganta", "fiebre alta y mucosidad", "difteria respiratoria", "bacterias en vías aéreas", "inflamación de adenoides", "ganglios del cuello inflamados", "cuello de toro"]'),
('A36.2', 'Difteria laríngea', 'Sin especificar', '["difteria en la laringe", "crup diftérico", "obstrucción de la vía aérea", "falta de aire", "ronquera severa", "estridor", "dificultad para respirar", "pérdida de la voz", "laringitis severa", "garganta bloqueada", "asfixia", "tos metálica", "cierre de glotis", "emergencia respiratoria", "inflamación laríngea"]'),
('A36.3', 'Difteria cutánea', 'Sin especificar', '["difteria en la piel", "llagas infectadas", "úlceras diftéricas", "heridas que no curan", "infección cutánea", "costras en la piel", "lesiones cutáneas purulentas", "piel con llagas", "infección bacteriana cutánea", "úlcera de piel", "herida con membrana", "difteria en heridas", "manchas infectadas", "enfermedad de la piel", "dermatitis infecciosa"]'),
('A36.81', 'Cardiomiopatía diftérica', 'Sin especificar', '["corazón dañado por difteria", "miocarditis diftérica", "falla cardiaca por infección", "corazón inflamado", "arritmia por difteria", "daño al músculo cardiaco", "complicación cardiaca", "dolor en el pecho", "palpitaciones", "debilidad cardiaca", "insuficiencia del corazón", "ataque cardiaco por bacteria", "anomalía en electrocardiograma", "miocardio infectado", "corazón débil"]'),
('A36.82', 'Radiculomielitis diftérica', 'Sin especificar', '["daño a los nervios", "problemas de médula espinal", "difteria neurológica", "inflamación de raíces nerviosas", "parálisis por difteria", "debilidad muscular", "dolor de espalda por nervios", "pérdida de sensibilidad", "hormigueo en extremidades", "problemas motrices", "ataque al sistema nervioso", "radiculopatía infecciosa", "mielitis post-infecciosa", "daño nervioso", "pérdida de reflejos"]'),
('A36.83', 'Polineuritis diftérica', 'Sin especificar', '["inflamación de varios nervios", "hormigueo en pies y manos", "entumecimiento", "debilidad de músculos", "parálisis diftérica", "neuropatía por bacterias", "daño a los nervios periféricos", "pérdida de fuerza", "dolor nervioso", "calambres", "pérdida de sensibilidad", "problemas al caminar", "alteración nerviosa", "debilidad progresiva", "polineuropatía"]'),
('A36.84', 'Nefropatía túbulo-intersticial diftérica', 'Sin especificar', '["daño al riñón por difteria", "infección renal", "problemas urinarios", "insuficiencia renal", "dolor en la espalda baja", "riñones inflamados", "nefritis", "alteración de la orina", "proteínas en la orina", "daño tubular", "problemas para orinar", "nefropatía tóxica", "afectación de riñones", "inflamación renal", "fallo de riñón"]'),
('A36.85', 'Cistitis diftérica', 'Sin especificar', '["infección de vejiga", "cistitis infecciosa", "ardor al orinar", "dolor en la vejiga", "ganas constantes de orinar", "orinar sangre", "orina turbia", "dolor en el vientre", "inflamación de vejiga", "infección urinaria baja", "molestias al orinar", "difteria urinaria", "espasmos en vejiga", "mal de orín", "cistitis bacteriana"]'),
('A36.86', 'Conjuntivitis diftérica', 'Sin especificar', '["ojo rojo", "infección en el ojo", "conjuntivitis con pus", "ojo pegado", "secreción ocular", "membranas en el ojo", "ojos inflamados", "ojo con costras", "infección ocular", "picor de ojos", "difteria ocular", "ojos llorosos y con pus", "irritación ocular severa", "conjuntivitis bacteriana", "ojos pegados al despertar"]'),
('A36.89', 'Otras complicaciones de la difteria', 'Sin especificar', '["secuelas de difteria", "complicaciones por bacteria", "problemas sistémicos", "daño multiorgánico", "toxicidad por difteria", "efectos secundarios difteria", "infección generalizada", "afectaciones post-difteria", "problemas de salud tras difteria", "complicaciones severas", "reacciones por bacteria", "efectos de la toxina", "secuelas de la enfermedad", "problemas de órganos", "complicaciones infecciosas"]'),
('A36.9', 'Difteria, no especificada', 'Sin especificar', '["difteria", "infección bacteriana", "enfermedad de la garganta", "placas en la garganta", "bacteria de la difteria", "crup", "garganta con membrana", "enfermedad contagiosa", "infección grave de garganta", "mal de garganta severo", "bacilo de Klebs-Löffler", "fiebre y dolor de cuello", "inflamación de amígdalas", "enfermedad por bacterias", "infección de vías respiratorias"]');
