INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S37.001A', 'Traumatismo no especificado de riñón derecho, contacto inicial', 'Sin especificar', '["golpe en el riñón", "dolor de riñones", "trancazo en la cintura", "riñón lastimado", "trauma renal", "sangre en la orina", "hematuria por golpe", "dolor lumbar agudo", "lesión en el riñón", "contusión renal", "golpe en la espalda baja", "dolor al orinar post golpe", "espalda golpeada", "traumatismo renal", "emergencia renal"]'),
('S37.001D', 'Traumatismo no especificado de riñón derecho, contacto sucesivo', 'Sin especificar', '["seguimiento golpe riñón", "control por trauma renal", "dolor persistente riñón", "revisión golpe riñón", "evolución lesión renal", "dolor post golpe riñón", "seguimiento médico riñón", "dolor lumbar continuo", "revisión de riñón", "checkup renal", "control de hematuria", "seguimiento post trauma"]'),
('S37.001S', 'Traumatismo no especificado de riñón derecho, secuela', 'Sin especificar', '["secuelas golpe riñón", "complicación riñón golpeado", "problema renal crónico post golpe", "daño permanente riñón", "cicatriz renal", "dolor crónico de riñones", "problema de riñón antiguo", "secuela de trauma lumbar", "falla renal post golpe", "dolor lumbar crónico", "riñón que no funciona bien"]'),
('S37.002A', 'Traumatismo no especificado de riñón izquierdo, contacto inicial', 'Sin especificar', '["golpe riñón izquierdo", "dolor riñón izquierdo", "trancazo lado izquierdo espalda", "golpe en la costilla izquierda baja", "lesión renal izquierda", "hematuria", "orinar sangre", "trauma riñón izquierdo", "dolor punzante riñón", "golpe fuerte espalda"]'),
('S37.002D', 'Traumatismo no especificado de riñón izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento riñón izquierdo", "control lesión riñón izquierdo", "revisión trauma renal izquierdo", "evolución golpe riñón", "chequeo riñón izquierdo", "dolor persistente espalda izquierda", "seguimiento hematuria"]'),
('S37.002S', 'Traumatismo no especificado de riñón izquierdo, secuela', 'Sin especificar', '["secuela golpe riñón izquierdo", "daño crónico riñón izquierdo", "dolor de riñón izquierdo viejo", "complicaciones golpe riñón izquierdo", "cicatriz riñón izquierdo", "insuficiencia renal post golpe"]'),
('S37.009A', 'Traumatismo no especificado de riñón no especificado, contacto inicial', 'Sin especificar', '["golpe en la espalda", "dolor intenso riñones", "golpe en la cintura", "lesión lumbar interna", "trauma renal", "orinar sangre", "dolor fuerte espalda baja", "golpe en los costados"]'),
('S37.009D', 'Traumatismo no especificado de riñón no especificado, contacto sucesivo', 'Sin especificar', '["control riñones", "seguimiento golpe espalda", "revisión trauma renal", "evolución dolor lumbar", "chequeo riñones", "revisión orina con sangre"]'),
('S37.009S', 'Traumatismo no especificado de riñón no especificado, secuela', 'Sin especificar', '["secuela dolor de espalda", "daño renal crónico", "dolor constante riñones", "cicatriz renal antigua", "complicación post golpe riñones"]'),
('S37.011A', 'Contusión leve de riñón derecho, contacto inicial', 'Sin especificar', '["moretón en el riñón", "golpe suave riñón derecho", "dolor leve cintura derecha", "trauma renal leve", "golpe en la rabadilla", "dolor de espalda al moverse"]'),
('S37.011D', 'Contusión leve de riñón derecho, contacto sucesivo', 'Sin especificar', '["control moretón riñón", "revisión golpe riñón derecho", "seguimiento contusión renal", "revisión dolor lumbar derecho"]'),
('S37.011S', 'Contusión leve de riñón derecho, secuela', 'Sin especificar', '["molestia riñón derecho antigua", "dolor residual golpe riñón", "secuela contusión renal", "dolor leve espalda derecha permanente"]'),
('S37.012A', 'Contusión leve de riñón izquierdo, contacto inicial', 'Sin especificar', '["moretón riñón izquierdo", "golpe suave lado izquierdo", "dolor leve cintura izquierda", "trauma renal leve izquierdo", "golpe en el costado"]'),
('S37.012D', 'Contusión leve de riñón izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento contusión riñón izquierdo", "revisión golpe riñón izquierdo", "control dolor costado izquierdo"]'),
('S37.012S', 'Contusión leve de riñón izquierdo, secuela', 'Sin especificar', '["dolor residual costado izquierdo", "secuela golpe riñón izquierdo", "molestia renal antigua"]'),
('S37.019A', 'Contusión leve de riñón no especificado, contacto inicial', 'Sin especificar', '["moretón en la espalda", "golpe en los riñones", "dolor sordo espalda baja", "trauma leve riñones", "contusión renal"]'),
('S37.019D', 'Contusión leve de riñón no especificado, contacto sucesivo', 'Sin especificar', '["control moretón riñones", "seguimiento golpe espalda", "revisión contusión renal"]'),
('S37.019S', 'Contusión leve de riñón no especificado, secuela', 'Sin especificar', '["secuela golpe riñones", "molestia residual espalda", "dolor leve crónico riñones"]'),
('S37.021A', 'Contusión grave de riñón derecho, contacto inicial', 'Sin especificar', '["golpe fuerte riñón derecho", "traumatismo renal severo", "dolor intenso riñón derecho", "sangre abundante al orinar", "hematoma riñón derecho", "urgencia por golpe riñón"]'),
('S37.021D', 'Contusión grave de riñón derecho, contacto sucesivo', 'Sin especificar', '["control hematoma riñón", "seguimiento contusión grave", "revisión trauma renal derecho", "chequeo riñón post golpe fuerte"]'),
('S37.021S', 'Contusión grave de riñón derecho, secuela', 'Sin especificar', '["daño permanente riñón derecho", "secuela trauma grave riñón", "cicatriz renal severa", "problemas renales post golpe fuerte"]'),
('S37.022A', 'Contusión grave de riñón izquierdo, contacto inicial', 'Sin especificar', '["golpe severo riñón izquierdo", "trauma renal grave izquierdo", "dolor agudo riñón izquierdo", "hematoma riñón izquierdo", "sangre en orina por golpe"]'),
('S37.022D', 'Contusión grave de riñón izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento contusión grave riñón", "revisión hematoma riñón izquierdo", "control trauma renal", "chequeo riñón izquierdo"]'),
('S37.022S', 'Contusión grave de riñón izquierdo, secuela', 'Sin especificar', '["secuela trauma severo riñón izquierdo", "daño riñón izquierdo", "problema renal crónico izquierdo", "cicatriz renal"]'),
('S37.029A', 'Contusión grave de riñón no especificado, contacto inicial', 'Sin especificar', '["golpe fuerte en la espalda", "trauma riñón severo", "dolor insoportable riñones", "hematoma interno riñón", "sangre en la orina urgente"]'),
('S37.029D', 'Contusión grave de riñón no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento trauma renal grave", "control hematoma renal", "revisión riñones golpeados", "chequeo médico riñones"]'),
('S37.029S', 'Contusión grave de riñón no especificado, secuela', 'Sin especificar', '["secuela trauma grave riñones", "daño crónico riñones", "cicatriz renal importante", "falla renal post golpe"]'),
('S37.031A', 'Desgarro de riñón derecho de grado no especificado, contacto inicial', 'Sin especificar', '["riñón roto", "desgarro renal", "ruptura riñón derecho", "golpe fatal riñón", "trauma riñón con hemorragia", "emergencia riñón roto"]'),
('S37.031D', 'Desgarro de riñón derecho de grado no especificado, contacto sucesivo', 'Sin especificar', '["control desgarro riñón", "seguimiento ruptura renal", "revisión riñón derecho", "chequeo desgarro interno"]'),
('S37.031S', 'Desgarro de riñón derecho de grado no especificado, secuela', 'Sin especificar', '["secuela desgarro renal", "daño permanente riñón derecho", "cicatriz post desgarro", "insuficiencia renal cicatricial"]'),
('S37.032A', 'Desgarro de riñón izquierdo de grado no especificado, contacto inicial', 'Sin especificar', '["desgarro riñón izquierdo", "ruptura renal izquierda", "riñón izquierdo roto", "hemorragia renal", "trauma severo riñón"]'),
('S37.032D', 'Desgarro de riñón izquierdo de grado no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro riñón izquierdo", "revisión ruptura riñón", "control post desgarro renal"]'),
('S37.032S', 'Desgarro de riñón izquierdo de grado no especificado, secuela', 'Sin especificar', '["secuela desgarro riñón izquierdo", "daño crónico riñón izquierdo", "cicatriz interna riñón"]'),
('S37.039A', 'Desgarro de riñón no especificado de grado no especificado, contacto inicial', 'Sin especificar', '["riñón roto", "ruptura renal", "desgarro en el riñón", "golpe interno riñón", "trauma con sangrado renal"]'),
('S37.039D', 'Desgarro de riñón no especificado de grado no especificado, contacto sucesivo', 'Sin especificar', '["control ruptura renal", "seguimiento desgarro riñón", "revisión sangrado interno renal"]'),
('S37.039S', 'Desgarro de riñón no especificado de grado no especificado, secuela', 'Sin especificar', '["secuela ruptura renal", "daño crónico riñones", "cicatriz renal interna"]'),
('S37.041A', 'Desgarro leve de riñón derecho, contacto inicial', 'Sin especificar', '["pequeño desgarro riñón derecho", "fisura riñón derecho", "golpe con pequeña ruptura", "lesión renal derecha"]'),
('S37.041D', 'Desgarro leve de riñón derecho, contacto sucesivo', 'Sin especificar', '["seguimiento fisura renal", "control desgarro leve", "revisión riñón derecho"]'),
('S37.041S', 'Desgarro leve de riñón derecho, secuela', 'Sin especificar', '["secuela pequeña fisura renal", "cicatriz pequeña riñón", "molestia renal leve"]'),
('S37.042A', 'Desgarro leve de riñón izquierdo, contacto inicial', 'Sin especificar', '["pequeño desgarro riñón izquierdo", "fisura riñón izquierdo", "lesión interna riñón izquierdo", "golpe riñón izquierdo"]'),
('S37.042D', 'Desgarro leve de riñón izquierdo, contacto sucesivo', 'Sin especificar', '["seguimiento fisura renal izquierda", "control desgarro leve", "revisión riñón izquierdo"]'),
('S37.042S', 'Desgarro leve de riñón izquierdo, secuela', 'Sin especificar', '["secuela desgarro leve riñón", "cicatriz renal leve", "molestia renal crónica"]'),
('S37.049A', 'Desgarro leve de riñón no especificado, contacto inicial', 'Sin especificar', '["fisura en el riñón", "pequeño desgarro riñón", "lesión renal menor", "trauma interno riñón"]'),
('S37.049D', 'Desgarro leve de riñón no especificado, contacto sucesivo', 'Sin especificar', '["control fisura renal", "seguimiento desgarro leve", "revisión riñón"]'),
('S37.049S', 'Desgarro leve de riñón no especificado, secuela', 'Sin especificar', '["secuela fisura renal", "cicatriz renal", "dolor leve crónico"]'),
('S37.051A', 'Desgarro moderado de riñón derecho, contacto inicial', 'Sin especificar', '["desgarro mediano riñón derecho", "lesión renal moderada", "ruptura parcial riñón", "dolor riñón derecho golpe"]'),
('S37.051D', 'Desgarro moderado de riñón derecho, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro moderado", "control ruptura parcial renal", "revisión riñón derecho"]'),
('S37.051S', 'Desgarro moderado de riñón derecho, secuela', 'Sin especificar', '["secuela desgarro renal moderado", "daño renal moderado", "cicatriz renal cicatrizante"]'),
('S37.052A', 'Desgarro moderado de riñón izquierdo, contacto inicial', 'Sin especificar', '["desgarro moderado riñón izquierdo", "lesión parcial riñón izquierdo", "ruptura renal media", "trauma renal izquierdo"]'),
('S37.052D', 'Desgarro moderado de riñón izquierdo, contacto sucesivo', 'Sin especificar', '["control desgarro moderado riñón", "seguimiento lesión parcial", "revisión riñón izquierdo"]'),
('S37.052S', 'Desgarro moderado de riñón izquierdo, secuela', 'Sin especificar', '["secuela desgarro moderado", "daño renal medio izquierdo", "cicatriz cicatrizada"]'),
('S37.059A', 'Desgarro moderado de riñón no especificado, contacto inicial', 'Sin especificar', '["desgarro moderado riñón", "ruptura renal media", "lesión moderada interna", "trauma renal"]'),
('S37.059D', 'Desgarro moderado de riñón no especificado, contacto sucesivo', 'Sin especificar', '["control ruptura parcial", "seguimiento desgarro moderado", "revisión riñones"]'),
('S37.059S', 'Desgarro moderado de riñón no especificado, secuela', 'Sin especificar', '["secuela desgarro moderado", "daño renal moderado", "cicatriz renal"]'),
('S37.061A', 'Desgarro grave de riñón derecho, contacto inicial', 'Sin especificar', '["desgarro serio riñón derecho", "ruptura grave riñón", "daño renal mayor derecho", "urgencia renal grave"]'),
('S37.061D', 'Desgarro grave de riñón derecho, contacto sucesivo', 'Sin especificar', '["seguimiento ruptura grave riñón", "control desgarro serio", "revisión riñón derecho"]'),
('S37.061S', 'Desgarro grave de riñón derecho, secuela', 'Sin especificar', '["secuela desgarro grave", "daño renal mayor", "cicatriz renal severa", "falla renal cicatriz"]'),
('S37.062A', 'Desgarro grave de riñón izquierdo, contacto inicial', 'Sin especificar', '["desgarro serio riñón izquierdo", "ruptura grave riñón izquierdo", "daño mayor renal izquierdo", "urgencia por trauma"]'),
('S37.062D', 'Desgarro grave de riñón izquierdo, contacto sucesivo', 'Sin especificar', '["control ruptura grave riñón", "seguimiento desgarro severo", "revisión riñón izquierdo"]'),
('S37.062S', 'Desgarro grave de riñón izquierdo, secuela', 'Sin especificar', '["secuela desgarro serio", "daño renal mayor", "cicatriz renal importante"]'),
('S37.069A', 'Desgarro grave de riñón no especificado, contacto inicial', 'Sin especificar', '["ruptura severa riñón", "desgarro grave riñón", "trauma renal mayor", "sangrado severo renal"]'),
('S37.069D', 'Desgarro grave de riñón no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento ruptura severa", "control desgarro grave", "revisión riñones"]'),
('S37.069S', 'Desgarro grave de riñón no especificado, secuela', 'Sin especificar', '["secuela desgarro grave", "daño renal severo", "cicatriz importante renal"]'),
('S37.091A', 'Otro traumatismo de riñón derecho, contacto inicial', 'Sin especificar', '["golpe extraño riñón derecho", "lesión interna riñón derecho", "trauma atípico riñón derecho", "problema renal post golpe"]'),
('S37.091D', 'Otro traumatismo de riñón derecho, contacto sucesivo', 'Sin especificar', '["seguimiento trauma renal", "control lesión riñón derecho", "revisión riñón"]'),
('S37.091S', 'Otro traumatismo de riñón derecho, secuela', 'Sin especificar', '["secuela trauma renal", "molestia renal derecho", "cicatriz interna derecha"]'),
('S37.092A', 'Otro traumatismo de riñón izquierdo, contacto inicial', 'Sin especificar', '["golpe extraño riñón izquierdo", "lesión interna riñón izquierdo", "trauma inespecífico riñón", "daño renal izquierdo"]'),
('S37.092D', 'Otro traumatismo de riñón izquierdo, contacto sucesivo', 'Sin especificar', '["control lesión renal izquierda", "seguimiento trauma atípico", "revisión riñón"]'),
('S37.092S', 'Otro traumatismo de riñón izquierdo, secuela', 'Sin especificar', '["secuela trauma renal izquierdo", "molestia crónica riñón", "cicatriz interna"]'),
('S37.099A', 'Otro traumatismo de riñón no especificado, contacto inicial', 'Sin especificar', '["lesión interna riñones", "trauma riñón raro", "golpe inespecífico riñón", "daño renal"]'),
('S37.099D', 'Otro traumatismo de riñón no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento trauma renal", "control lesión riñones", "revisión médica riñones"]'),
('S37.099S', 'Otro traumatismo de riñón no especificado, secuela', 'Sin especificar', '["secuela trauma riñones", "daño renal crónico", "cicatriz interna riñones"]'),
('S37.10XA', 'Traumatismo no especificado de uréter, contacto inicial', 'Sin especificar', '["golpe uréter", "trauma vías urinarias", "lesión en el tubo de la orina", "dolor al orinar por golpe", "problema uréter", "obstrucción uréter por golpe"]'),
('S37.10XD', 'Traumatismo no especificado de uréter, contacto sucesivo', 'Sin especificar', '["seguimiento trauma uréter", "control lesión vía urinaria", "revisión uréter"]'),
('S37.10XS', 'Traumatismo no especificado de uréter, secuela', 'Sin especificar', '["secuela lesión uréter", "cicatriz uréter", "dolor crónico vías urinarias"]'),
('S37.12XA', 'Contusión de uréter, contacto inicial', 'Sin especificar', '["moretón en el uréter", "golpe uréter", "trauma leve vías urinarias", "dolor bajo vientre por golpe"]'),
('S37.12XD', 'Contusión de uréter, contacto sucesivo', 'Sin especificar', '["control moretón uréter", "seguimiento golpe vías", "revisión uréter"]'),
('S37.12XS', 'Contusión de uréter, secuela', 'Sin especificar', '["secuela golpe uréter", "cicatriz uréter", "dolor persistente orinar"]'),
('S37.13XA', 'Desgarro de uréter, contacto inicial', 'Sin especificar', '["uréter roto", "desgarro conducto urinario", "ruptura uréter", "sangrado al orinar", "emergencia uréter"]'),
('S37.13XD', 'Desgarro de uréter, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro uréter", "control ruptura conducto", "revisión vía urinaria"]'),
('S37.13XS', 'Desgarro de uréter, secuela', 'Sin especificar', '["secuela ruptura uréter", "cicatriz conducto urinario", "problema crónico uréter"]'),
('S37.19XA', 'Otro traumatismo de uréter, contacto inicial', 'Sin especificar', '["lesión interna uréter", "trauma inespecífico vías", "golpe uréter"]'),
('S37.19XD', 'Otro traumatismo de uréter, contacto sucesivo', 'Sin especificar', '["control trauma uréter", "seguimiento vía urinaria", "revisión uréter"]'),
('S37.19XS', 'Otro traumatismo de uréter, secuela', 'Sin especificar', '["secuela trauma uréter", "cicatriz vía urinaria", "molestia persistente"]'),
('S37.20XA', 'Traumatismo no especificado de vejiga, contacto inicial', 'Sin especificar', '["golpe en la vejiga", "trauma vejiga", "dolor bajo vientre", "sangre al orinar", "problema vejiga por golpe", "golpe en la panza baja"]'),
('S37.20XD', 'Traumatismo no especificado de vejiga, contacto sucesivo', 'Sin especificar', '["seguimiento vejiga golpeada", "control trauma vejiga", "revisión orinar sangre"]'),
('S37.20XS', 'Traumatismo no especificado de vejiga, secuela', 'Sin especificar', '["secuela golpe vejiga", "cicatriz vejiga", "incontinencia post golpe", "dolor pélvico crónico"]'),
('S37.22XA', 'Contusión de vejiga, contacto inicial', 'Sin especificar', '["moretón en la vejiga", "golpe leve vejiga", "dolor pélvico", "trauma vejiga leve"]'),
('S37.22XD', 'Contusión de vejiga, contacto sucesivo', 'Sin especificar', '["seguimiento moretón vejiga", "control golpe pélvico", "revisión vejiga"]'),
('S37.22XS', 'Contusión de vejiga, secuela', 'Sin especificar', '["secuela golpe vejiga", "molestia pélvica", "cicatriz vejiga"]'),
('S37.23XA', 'Desgarro de vejiga, contacto inicial', 'Sin especificar', '["vejiga rota", "ruptura vejiga", "desgarro vejiga", "sangrado severo vejiga", "emergencia vejiga"]'),
('S37.23XD', 'Desgarro de vejiga, contacto sucesivo', 'Sin especificar', '["control ruptura vejiga", "seguimiento desgarro", "revisión vejiga post cirugía"]'),
('S37.23XS', 'Desgarro de vejiga, secuela', 'Sin especificar', '["secuela ruptura vejiga", "cicatriz vejiga", "problemas urinarios crónicos"]'),
('S37.29XA', 'Otro traumatismo de vejiga, contacto inicial', 'Sin especificar', '["lesión interna vejiga", "trauma inespecífico vejiga", "golpe vejiga"]'),
('S37.29XD', 'Otro traumatismo de vejiga, contacto sucesivo', 'Sin especificar', '["seguimiento trauma vejiga", "control lesión", "revisión vejiga"]'),
('S37.29XS', 'Otro traumatismo de vejiga, secuela', 'Sin especificar', '["secuela trauma vejiga", "molestia pélvica crónica", "cicatriz interna"]'),
('S37.30XA', 'Traumatismo no especificado de uretra, contacto inicial', 'Sin especificar', '["golpe uretra", "trauma zona genital", "dolor al orinar", "sangre uretra", "lesión uretral"]'),
('S37.30XD', 'Traumatismo no especificado de uretra, contacto sucesivo', 'Sin especificar', '["seguimiento lesión uretra", "control trauma uretral", "revisión dolor orinar"]'),
('S37.30XS', 'Traumatismo no especificado de uretra, secuela', 'Sin especificar', '["secuela trauma uretra", "cicatriz uretra", "dolor crónico al orinar"]'),
('S37.32XA', 'Contusión de uretra, contacto inicial', 'Sin especificar', '["moretón uretra", "golpe leve uretra", "molestia genital", "dolor leve uretral"]'),
('S37.32XD', 'Contusión de uretra, contacto sucesivo', 'Sin especificar', '["seguimiento golpe uretra", "control moretón", "revisión uretra"]'),
('S37.32XS', 'Contusión de uretra, secuela', 'Sin especificar', '["secuela golpe uretra", "cicatriz uretra", "molestia persistente"]'),
('S37.33XA', 'Desgarro de uretra, contacto inicial', 'Sin especificar', '["uretra rota", "ruptura uretra", "desgarro uretra", "sangrado genital", "emergencia uretra"]'),
('S37.33XD', 'Desgarro de uretra, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro uretra", "control ruptura", "revisión uretra"]'),
('S37.33XS', 'Desgarro de uretra, secuela', 'Sin especificar', '["secuela ruptura uretra", "cicatriz uretra", "problema crónico al orinar"]'),
('S37.39XA', 'Otro traumatismo de uretra, contacto inicial', 'Sin especificar', '["lesión uretra", "trauma inespecífico", "golpe zona uretra"]'),
('S37.39XD', 'Otro traumatismo de uretra, contacto sucesivo', 'Sin especificar', '["seguimiento trauma uretra", "control lesión", "revisión genital"]'),
('S37.39XS', 'Otro traumatismo de uretra, secuela', 'Sin especificar', '["secuela trauma uretra", "molestia persistente", "cicatriz"]'),
('S37.401A', 'Traumatismo no especificado de ovario, unilateral, contacto inicial', 'Sin especificar', '["golpe en el ovario", "dolor ovario derecho o izquierdo", "trauma pélvico", "lesión interna ovario", "dolor abdominal bajo fuerte"]'),
('S37.401D', 'Traumatismo no especificado de ovario, unilateral, contacto sucesivo', 'Sin especificar', '["seguimiento golpe ovario", "control trauma pélvico", "revisión ovario"]'),
('S37.401S', 'Traumatismo no especificado de ovario, unilateral, secuela', 'Sin especificar', '["secuela golpe ovario", "cicatriz ovario", "dolor pélvico crónico"]'),
('S37.402A', 'Traumatismo no especificado de ovario, bilateral, contacto inicial', 'Sin especificar', '["golpe ovarios", "trauma ambos ovarios", "dolor pélvico bilateral", "lesión interna ovarios"]'),
('S37.402D', 'Traumatismo no especificado de ovario, bilateral, contacto sucesivo', 'Sin especificar', '["seguimiento golpe ovarios", "control trauma bilateral", "revisión médica"]'),
('S37.402S', 'Traumatismo no especificado de ovario, bilateral, secuela', 'Sin especificar', '["secuela trauma ovarios", "dolor pélvico persistente", "cicatriz interna"]'),
('S37.409A', 'Traumatismo no especificado de ovario no especificado, contacto inicial', 'Sin especificar', '["golpe bajo vientre", "trauma ovárico", "dolor pélvico intenso"]'),
('S37.409D', 'Traumatismo no especificado de ovario no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento trauma ovárico", "control dolor pélvico", "revisión"]'),
('S37.409S', 'Traumatismo no especificado de ovario no especificado, secuela', 'Sin especificar', '["secuela trauma ovárico", "dolor persistente", "cicatriz"]'),
('S37.421A', 'Contusión de ovario, unilateral, contacto inicial', 'Sin especificar', '["moretón ovario", "golpe suave ovario", "molestia pélvica leve"]'),
('S37.421D', 'Contusión de ovario, unilateral, contacto sucesivo', 'Sin especificar', '["seguimiento golpe ovario", "control moretón", "revisión"]'),
('S37.421S', 'Contusión de ovario, unilateral, secuela', 'Sin especificar', '["secuela golpe ovario", "molestia residual", "cicatriz"]'),
('S37.422A', 'Contusión de ovario, bilateral, contacto inicial', 'Sin especificar', '["moretón ovarios", "golpe leve ambos ovarios", "molestia baja vientre"]'),
('S37.422D', 'Contusión de ovario, bilateral, contacto sucesivo', 'Sin especificar', '["seguimiento golpe ovarios", "control moretón", "revisión"]'),
('S37.422S', 'Contusión de ovario, bilateral, secuela', 'Sin especificar', '["secuela golpe ovarios", "molestia pélvica", "cicatriz"]'),
('S37.429A', 'Contusión de ovario no especificado, contacto inicial', 'Sin especificar', '["moretón en ovarios", "golpe bajo", "molestia pelviana"]'),
('S37.429D', 'Contusión de ovario no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control moretón", "revisión"]'),
('S37.429S', 'Contusión de ovario no especificado, secuela', 'Sin especificar', '["secuela golpe ovarios", "cicatriz interna", "molestia persistente"]'),
('S37.431A', 'Desgarro de ovario, unilateral, contacto inicial', 'Sin especificar', '["ovario roto", "ruptura ovario", "desgarro ovario", "dolor abdominal agudo", "emergencia ginecológica"]'),
('S37.431D', 'Desgarro de ovario, unilateral, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro ovario", "control ruptura", "revisión post quirúrgica"]'),
('S37.431S', 'Desgarro de ovario, unilateral, secuela', 'Sin especificar', '["secuela ruptura ovario", "cicatriz ovario", "problema pélvico"]'),
('S37.432A', 'Desgarro de ovario, bilateral, contacto inicial', 'Sin especificar', '["ovarios rotos", "ruptura ambos ovarios", "desgarro bilateral", "dolor pélvico severo"]'),
('S37.432D', 'Desgarro de ovario, bilateral, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro bilateral", "control ruptura", "revisión médica"]'),
('S37.432S', 'Desgarro de ovario, bilateral, secuela', 'Sin especificar', '["secuela ruptura bilateral", "cicatriz ovarios", "dolor persistente"]'),
('S37.439A', 'Desgarro de ovario no especificado, contacto inicial', 'Sin especificar', '["desgarro ovárico", "ruptura ovario", "emergencia pélvica"]'),
('S37.439D', 'Desgarro de ovario no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro ovárico", "control ruptura", "revisión"]'),
('S37.439S', 'Desgarro de ovario no especificado, secuela', 'Sin especificar', '["secuela desgarro ovárico", "cicatriz interna", "dolor pélvico"]'),
('S37.491A', 'Otro traumatismo de ovario, unilateral, contacto inicial', 'Sin especificar', '["trauma ovario", "lesión interna ovario", "golpe pelviano"]'),
('S37.491D', 'Otro traumatismo de ovario, unilateral, contacto sucesivo', 'Sin especificar', '["seguimiento trauma", "control lesión", "revisión"]'),
('S37.491S', 'Otro traumatismo de ovario, unilateral, secuela', 'Sin especificar', '["secuela trauma ovario", "cicatriz interna", "molestia"]'),
('S37.492A', 'Otro traumatismo de ovario, bilateral, contacto inicial', 'Sin especificar', '["trauma ovarios", "lesión ambos ovarios", "golpe bajo"]'),
('S37.492D', 'Otro traumatismo de ovario, bilateral, contacto sucesivo', 'Sin especificar', '["seguimiento trauma", "control lesión", "revisión"]'),
('S37.492S', 'Otro traumatismo de ovario, bilateral, secuela', 'Sin especificar', '["secuela trauma ovarios", "cicatriz interna", "dolor persistente"]'),
('S37.499A', 'Otro traumatismo de ovario no especificado, contacto inicial', 'Sin especificar', '["lesión ovario", "trauma inespecífico"]'),
('S37.499D', 'Otro traumatismo de ovario no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control trauma", "revisión"]'),
('S37.499S', 'Otro traumatismo de ovario no especificado, secuela', 'Sin especificar', '["secuela trauma ovario", "cicatriz", "molestia"]'),
('S37.501A', 'Traumatismo no especificado de trompa de Falopio, unilateral, contacto inicial', 'Sin especificar', '["golpe trompa falopio", "lesión trompa útero", "dolor bajo vientre", "trauma trompas"]'),
('S37.501D', 'Traumatismo no especificado de trompa de Falopio, unilateral, contacto sucesivo', 'Sin especificar', '["seguimiento trauma trompa", "control lesión", "revisión"]'),
('S37.501S', 'Traumatismo no especificado de trompa de Falopio, unilateral, secuela', 'Sin especificar', '["secuela trauma trompa", "cicatriz trompa", "dolor pélvico"]'),
('S37.502A', 'Traumatismo no especificado de trompas de Falopio, bilateral, contacto inicial', 'Sin especificar', '["golpe trompas", "trauma ambas trompas", "dolor pélvico severo"]'),
('S37.502D', 'Traumatismo no especificado de trompas de Falopio, bilateral, contacto sucesivo', 'Sin especificar', '["seguimiento trauma trompas", "control lesión", "revisión"]'),
('S37.502S', 'Traumatismo no especificado de trompas de Falopio, bilateral, secuela', 'Sin especificar', '["secuela trauma trompas", "cicatriz interna", "molestia persistente"]'),
('S37.509A', 'Traumatismo no especificado de trompa de Falopio no especificada, contacto inicial', 'Sin especificar', '["lesión trompa", "golpe bajo", "dolor interno"]'),
('S37.509D', 'Traumatismo no especificado de trompa de Falopio no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control trauma", "revisión"]'),
('S37.509S', 'Traumatismo no especificado de trompa de Falopio no especificada, secuela', 'Sin especificar', '["secuela trauma trompa", "cicatriz", "molestia"]'),
('S37.511A', 'Lesión primaria por onda expansiva de trompa de Falopio, unilateral, contacto inicial', 'Sin especificar', '["explosión trompa", "daño por onda expansiva", "trauma trompa", "emergencia interna"]'),
('S37.511D', 'Lesión primaria por onda expansiva de trompa de Falopio, unilateral, contacto sucesivo', 'Sin especificar', '["seguimiento explosión", "control daño", "revisión"]'),
('S37.511S', 'Lesión primaria por onda expansiva de trompa de Falopio, unilateral, secuela', 'Sin especificar', '["secuela onda explosiva", "cicatriz trompa", "molestia"]'),
('S37.512A', 'Lesión primaria por onda expansiva en trompa de Falopio, bilateral, contacto inicial', 'Sin especificar', '["explosión ambas trompas", "daño por onda expansiva trompas", "trauma grave pélvico"]'),
('S37.512D', 'Lesión primaria por onda expansiva en trompa de Falopio, bilateral, contacto sucesivo', 'Sin especificar', '["seguimiento daño bilateral", "control explosión", "revisión"]'),
('S37.512S', 'Lesión primaria por onda expansiva en trompa de Falopio, bilateral, secuela', 'Sin especificar', '["secuela daño bilateral", "cicatriz trompas", "dolor persistente"]'),
('S37.519A', 'Lesión primaria por onda expansiva de trompa de Falopio no especificada, contacto inicial', 'Sin especificar', '["daño trompa por onda", "emergencia explosiva"]'),
('S37.519D', 'Lesión primaria por onda expansiva de trompa de Falopio no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento daño trompa", "control onda", "revisión"]'),
('S37.519S', 'Lesión primaria por onda expansiva de trompa de Falopio no especificada, secuela', 'Sin especificar', '["secuela daño onda", "cicatriz", "molestia"]'),
('S37.521A', 'Contusión de trompa de Falopio, unilateral, contacto inicial', 'Sin especificar', '["moretón trompa", "golpe trompa", "lesión interna"]'),
('S37.521D', 'Contusión de trompa de Falopio, unilateral, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control moretón", "revisión"]'),
('S37.521S', 'Contusión de trompa de Falopio, unilateral, secuela', 'Sin especificar', '["secuela golpe trompa", "cicatriz interna", "molestia"]'),
('S37.522A', 'Contusión de trompas de Falopio, bilateral, contacto inicial', 'Sin especificar', '["moretón ambas trompas", "golpe trompas", "lesión interna pélvica"]'),
('S37.522D', 'Contusión de trompas de Falopio, bilateral, contacto sucesivo', 'Sin especificar', '["seguimiento golpe trompas", "control moretón", "revisión"]'),
('S37.522S', 'Contusión de trompas de Falopio, bilateral, secuela', 'Sin especificar', '["secuela golpe trompas", "cicatriz interna", "molestia"]'),
('S37.529A', 'Contusión de trompa de Falopio no especificada, contacto inicial', 'Sin especificar', '["moretón en trompa", "golpe pélvico"]'),
('S37.529D', 'Contusión de trompa de Falopio no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control moretón", "revisión"]'),
('S37.529S', 'Contusión de trompa de Falopio no especificada, secuela', 'Sin especificar', '["secuela golpe trompa", "cicatriz", "molestia"]'),
('S37.531A', 'Desgarro de trompa de Falopio, unilateral, contacto inicial', 'Sin especificar', '["trompa rota", "desgarro trompa", "dolor agudo"]'),
('S37.531D', 'Desgarro de trompa de Falopio, unilateral, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro", "control ruptura", "revisión"]'),
('S37.531S', 'Desgarro de trompa de Falopio, unilateral, secuela', 'Sin especificar', '["secuela trompa rota", "cicatriz interna", "molestia"]'),
('S37.532A', 'Desgarro de trompa de Falopio, bilateral, contacto inicial', 'Sin especificar', '["trompas rotas", "desgarro bilateral trompas", "dolor pélvico grave"]'),
('S37.532D', 'Desgarro de trompa de Falopio, bilateral, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro", "control ruptura", "revisión"]'),
('S37.532S', 'Desgarro de trompa de Falopio, bilateral, secuela', 'Sin especificar', '["secuela trompas rotas", "cicatriz interna", "molestia persistente"]'),
('S37.539A', 'Desgarro de trompa de Falopio no especificada, contacto inicial', 'Sin especificar', '["desgarro trompa", "trompa rota", "emergencia"]'),
('S37.539D', 'Desgarro de trompa de Falopio no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro", "control ruptura", "revisión"]'),
('S37.539S', 'Desgarro de trompa de Falopio no especificada, secuela', 'Sin especificar', '["secuela desgarro trompa", "cicatriz", "molestia"]'),
('S37.591A', 'Otro traumatismo de trompa de Falopio, unilateral, contacto inicial', 'Sin especificar', '["lesión trompa", "trauma inespecífico", "golpe"]'),
('S37.591D', 'Otro traumatismo de trompa de Falopio, unilateral, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control trauma", "revisión"]'),
('S37.591S', 'Otro traumatismo de trompa de Falopio, unilateral, secuela', 'Sin especificar', '["secuela trauma trompa", "cicatriz", "molestia"]'),
('S37.592A', 'Otro traumatismo de trompas de Falopio, bilateral, contacto inicial', 'Sin especificar', '["lesión trompas", "trauma ambas trompas", "golpe pélvico"]'),
('S37.592D', 'Otro traumatismo de trompas de Falopio, bilateral, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control trauma", "revisión"]'),
('S37.592S', 'Otro traumatismo de trompas de Falopio, bilateral, secuela', 'Sin especificar', '["secuela trauma trompas", "cicatriz interna", "molestia"]'),
('S37.599A', 'Otro traumatismo de trompa de Falopio, no especificada, contacto inicial', 'Sin especificar', '["lesión trompa", "trauma interno"]'),
('S37.599D', 'Otro traumatismo de trompa de Falopio, no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control trauma", "revisión"]'),
('S37.599S', 'Otro traumatismo de trompa de Falopio, no especificado, secuela', 'Sin especificar', '["secuela trauma trompa", "cicatriz", "molestia"]'),
('S37.60XA', 'Traumatismo no especificado de útero, contacto inicial', 'Sin especificar', '["golpe en la matriz", "trauma uterino", "lesión útero", "dolor bajo vientre intenso", "emergencia obstétrica"]'),
('S37.60XD', 'Traumatismo no especificado de útero, contacto sucesivo', 'Sin especificar', '["seguimiento golpe matriz", "control trauma", "revisión ginecológica"]'),
('S37.60XS', 'Traumatismo no especificado de útero, secuela', 'Sin especificar', '["secuela golpe matriz", "cicatriz útero", "dolor persistente"]'),
('S37.62XA', 'Contusión de útero, contacto inicial', 'Sin especificar', '["moretón matriz", "golpe matriz", "lesión leve útero"]'),
('S37.62XD', 'Contusión de útero, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control moretón", "revisión"]'),
('S37.62XS', 'Contusión de útero, secuela', 'Sin especificar', '["secuela golpe matriz", "cicatriz", "molestia"]'),
('S37.63XA', 'Desgarro de útero, contacto inicial', 'Sin especificar', '["matriz rota", "desgarro matriz", "emergencia útero", "ruptura uterina"]'),
('S37.63XD', 'Desgarro de útero, contacto sucesivo', 'Sin especificar', '["seguimiento ruptura", "control desgarro", "revisión"]'),
('S37.63XS', 'Desgarro de útero, secuela', 'Sin especificar', '["secuela matriz rota", "cicatriz interna", "molestia"]'),
('S37.69XA', 'Otro traumatismo de útero, contacto inicial', 'Sin especificar', '["lesión matriz", "trauma inespecífico", "golpe"]'),
('S37.69XD', 'Otro traumatismo de útero, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control trauma", "revisión"]'),
('S37.69XS', 'Otro traumatismo de útero, secuela', 'Sin especificar', '["secuela trauma útero", "cicatriz", "molestia"]'),
('S37.812A', 'Contusión de glándula suprarrenal, contacto inicial', 'Sin especificar', '["golpe glándula", "moretón suprarrenal", "dolor espalda", "trauma interno"]'),
('S37.812D', 'Contusión de glándula suprarrenal, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control moretón", "revisión"]'),
('S37.812S', 'Contusión de glándula suprarrenal, secuela', 'Sin especificar', '["secuela golpe glándula", "cicatriz", "molestia"]'),
('S37.813A', 'Desgarro de glándula suprarrenal, contacto inicial', 'Sin especificar', '["glándula rota", "desgarro glándula", "emergencia interna"]'),
('S37.813D', 'Desgarro de glándula suprarrenal, contacto sucesivo', 'Sin especificar', '["seguimiento ruptura", "control desgarro", "revisión"]'),
('S37.813S', 'Desgarro de glándula suprarrenal, secuela', 'Sin especificar', '["secuela glándula rota", "cicatriz", "molestia"]'),
('S37.818A', 'Otro traumatismo de glándula suprarrenal, contacto inicial', 'Sin especificar', '["lesión glándula", "trauma", "golpe interno"]'),
('S37.818D', 'Otro traumatismo de glándula suprarrenal, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control trauma", "revisión"]'),
('S37.818S', 'Otro traumatismo de glándula suprarrenal, secuela', 'Sin especificar', '["secuela trauma glándula", "cicatriz", "molestia"]'),
('S37.819A', 'Traumatismo no especificado de glándula suprarrenal, contacto inicial', 'Sin especificar', '["golpe suprarrenal", "trauma interno"]'),
('S37.819D', 'Traumatismo no especificado de glándula suprarrenal, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control trauma", "revisión"]'),
('S37.819S', 'Traumatismo no especificado de glándula suprarrenal, secuela', 'Sin especificar', '["secuela trauma suprarrenal", "cicatriz", "molestia"]'),
('S37.822A', 'Contusión de próstata, contacto inicial', 'Sin especificar', '["golpe próstata", "moretón genital", "molestia al orinar"]'),
('S37.822D', 'Contusión de próstata, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control moretón", "revisión"]'),
('S37.822S', 'Contusión de próstata, secuela', 'Sin especificar', '["secuela golpe próstata", "cicatriz", "dolor persistente"]'),
('S37.823A', 'Desgarro de próstata, contacto inicial', 'Sin especificar', '["próstata rota", "desgarro próstata", "sangrado"]'),
('S37.823D', 'Desgarro de próstata, contacto sucesivo', 'Sin especificar', '["seguimiento ruptura", "control desgarro", "revisión"]'),
('S37.823S', 'Desgarro de próstata, secuela', 'Sin especificar', '["secuela próstata rota", "cicatriz", "molestia"]'),
('S37.828A', 'Otro traumatismo de próstata, contacto inicial', 'Sin especificar', '["lesión próstata", "trauma", "golpe"]'),
('S37.828D', 'Otro traumatismo de próstata, contacto sucesivo', 'Sin especificar', '["seguimiento lesión", "control trauma", "revisión"]'),
('S37.828S', 'Otro traumatismo de próstata, secuela', 'Sin especificar', '["secuela trauma próstata", "cicatriz", "molestia"]'),
('S37.829A', 'Traumatismo no especificado de próstata, contacto inicial', 'Sin especificar', '["golpe próstata", "trauma"]'),
('S37.829D', 'Traumatismo no especificado de próstata, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control trauma", "revisión"]'),
('S37.829S', 'Traumatismo no especificado de próstata, secuela', 'Sin especificar', '["secuela trauma próstata", "cicatriz", "molestia"]'),
('S37.892A', 'Contusión de otro órgano urinario o pélvico, contacto inicial', 'Sin especificar', '["golpe zona pélvica", "moretón pélvico", "molestia interna"]'),
('S37.892D', 'Contusión de otro órgano urinario o pélvico, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control moretón", "revisión"]'),
('S37.892S', 'Contusión de otro órgano urinario o pélvico, secuela', 'Sin especificar', '["secuela golpe pélvico", "cicatriz", "molestia"]'),
('S37.893A', 'Desgarro de otro órgano urinario o pélvico, contacto inicial', 'Sin especificar', '["ruptura pélvica", "desgarro interno", "emergencia"]'),
('S37.893D', 'Desgarro de otro órgano urinario o pélvico, contacto sucesivo', 'Sin especificar', '["seguimiento ruptura", "control desgarro", "revisión"]'),
('S37.893S', 'Desgarro de otro órgano urinario o pélvico, secuela', 'Sin especificar', '["secuela ruptura pélvica", "cicatriz", "molestia"]'),
('S37.898A', 'Otro traumatismo de otro órgano urinario o pélvico, contacto inicial', 'Sin especificar', '["trauma pélvico", "lesión interna"]'),
('S37.898D', 'Otro traumatismo de otro órgano urinario o pélvico, contacto sucesivo', 'Sin especificar', '["seguimiento trauma", "control lesión", "revisión"]'),
('S37.898S', 'Otro traumatismo de otro órgano urinario o pélvico, secuela', 'Sin especificar', '["secuela trauma pélvico", "cicatriz", "molestia"]'),
('S37.899A', 'Traumatismo no especificado de otro órgano urinario o pélvico, contacto inicial', 'Sin especificar', '["golpe pelvis", "trauma"]'),
('S37.899D', 'Traumatismo no especificado de otro órgano urinario o pélvico, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control trauma", "revisión"]'),
('S37.899S', 'Traumatismo no especificado de otro órgano urinario o pélvico, secuela', 'Sin especificar', '["secuela trauma pelvis", "cicatriz", "molestia"]'),
('S37.90XA', 'Traumatismo no especificado de órgano urinario y pélvico no especificado, contacto inicial', 'Sin especificar', '["golpe bajo", "trauma pélvico"]'),
('S37.90XD', 'Traumatismo no especificado de órgano urinario y pélvico no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control trauma", "revisión"]'),
('S37.90XS', 'Traumatismo no especificado de órgano urinario y pélvico no especificado, secuela', 'Sin especificar', '["secuela trauma pélvico", "cicatriz", "molestia"]'),
('S37.92XA', 'Contusión de órgano urinario y pélvico no especificado, contacto inicial', 'Sin especificar', '["moretón bajo vientre", "golpe pélvico"]'),
('S37.92XD', 'Contusión de órgano urinario y pélvico no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento golpe", "control moretón", "revisión"]'),
('S37.92XS', 'Contusión de órgano urinario y pélvico no especificado, secuela', 'Sin especificar', '["secuela golpe pélvico", "cicatriz", "molestia"]'),
('S37.93XA', 'Desgarro de órgano urinario y pélvico no especificado, contacto inicial', 'Sin especificar', '["ruptura pélvica", "desgarro interno"]'),
('S37.93XD', 'Desgarro de órgano urinario y pélvico no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento ruptura", "control desgarro", "revisión"]'),
('S37.93XS', 'Desgarro de órgano urinario y pélvico no especificado, secuela', 'Sin especificar', '["secuela ruptura pélvica", "cicatriz", "molestia"]'),
('S37.99XA', 'Otro traumatismo de órgano urinario y pélvico no especificado, contacto inicial', 'Sin especificar', '["trauma pelvis", "lesión"]'),
('S37.99XD', 'Otro traumatismo de órgano urinario y pélvico no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento trauma", "control lesión", "revisión"]'),
('S37.99XS', 'Otro traumatismo de órgano urinario y pélvico no especificado, secuela', 'Sin especificar', '["secuela trauma pelvis", "cicatriz", "molestia"]');
