INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S36.00XA', 'Traumatismo no especificado de bazo, contacto inicial', 'Sin especificar', '["golpe en el bazo", "lesión esplénica", "dolor bajo las costillas", "traumatismo abdominal", "dolor en el costado izquierdo", "accidente en el bazo", "urgencia por golpe", "trauma esplénico", "hematoma en bazo", "dolor en el bazo", "pinchazo en el costado"]'),
('S36.00XD', 'Traumatismo no especificado de bazo, contacto sucesivo', 'Sin especificar', '["seguimiento golpe bazo", "control lesión esplénica", "revisión trauma bazo", "dolor persistente bazo", "control post-accidente bazo", "consulta por bazo", "seguimiento médico bazo", "evolución lesión esplénica"]'),
('S36.00XS', 'Traumatismo no especificado de bazo, secuela', 'Sin especificar', '["secuela de golpe en bazo", "cicatriz esplénica", "complicaciones por trauma bazo", "dolor crónico tras golpe bazo", "daño a largo plazo bazo", "posibles efectos golpe esplénico", "problemas después de lesionar bazo"]'),
('S36.020A', 'Contusión leve de bazo, contacto inicial', 'Sin especificar', '["golpe suave en el bazo", "moretón en el bazo", "traumatismo leve bazo", "dolor leve costado izquierdo", "esplenocontusión leve", "susto por golpe en el bazo"]'),
('S36.020D', 'Contusión leve de bazo, contacto sucesivo', 'Sin especificar', '["control contusión bazo", "seguimiento moretón bazo", "revisión golpe leve bazo", "mejora de golpe bazo", "seguimiento médico bazo leve"]'),
('S36.020S', 'Contusión leve de bazo, secuela', 'Sin especificar', '["secuela contusión bazo", "efectos post-contusión esplénica", "dolor residual golpe bazo", "revisión secuelas bazo"]'),
('S36.021A', 'Contusión grave de bazo, contacto inicial', 'Sin especificar', '["golpe fuerte bazo", "trauma grave bazo", "lesión severa esplénica", "emergencia golpe bazo", "dolor intenso bajo costillas", "riesgo ruptura bazo", "golpazo en la zona del bazo"]'),
('S36.021D', 'Contusión grave de bazo, contacto sucesivo', 'Sin especificar', '["seguimiento contusión grave bazo", "revisión hospitalaria bazo", "control trauma esplénico severo", "evolución golpe bazo", "vigilancia bazo lesionado"]'),
('S36.021S', 'Contusión grave de bazo, secuela', 'Sin especificar', '["secuelas de trauma esplénico grave", "problemas persistentes bazo", "complicaciones bazo después de golpe", "dolor crónico post-trauma"]'),
('S36.029A', 'Contusión no especificada de bazo, contacto inicial', 'Sin especificar', '["golpe en el bazo", "traumatismo bazo", "me di un golpe en la panza y me duele el costado", "dolor en la zona del bazo", "lesión esplénica desconocida"]'),
('S36.029D', 'Contusión no especificada de bazo, contacto sucesivo', 'Sin especificar', '["seguimiento golpe en el bazo", "control médico por dolor esplénico", "revisión bazo después de golpe", "evolución de trauma bazo"]'),
('S36.029S', 'Contusión no especificada de bazo, secuela', 'Sin especificar', '["secuela de golpe bazo", "dolor que persiste en bazo", "problemas post-trauma bazo", "efectos largo plazo bazo"]'),
('S36.030A', 'Desgarro superficial (capsular) de bazo, contacto inicial', 'Sin especificar', '["bazo rasgado", "pequeña fisura bazo", "lesión capsular bazo", "desgarro bazo", "emergencia bazo", "dolor punzante costado"]'),
('S36.030D', 'Desgarro superficial (capsular) de bazo, contacto sucesivo', 'Sin especificar', '["control bazo rasgado", "seguimiento fisura bazo", "revisión desgarro esplénico", "curación bazo", "monitoreo bazo"]'),
('S36.030S', 'Desgarro superficial (capsular) de bazo, secuela', 'Sin especificar', '["secuela desgarro bazo", "complicaciones cicatriz bazo", "problemas por rotura capsular bazo"]'),
('S36.031A', 'Desgarro moderado de bazo, contacto inicial', 'Sin especificar', '["bazo dañado", "desgarro bazo urgencia", "sangrado bazo moderado", "lesión seria esplénica", "dolor fuerte costado"]'),
('S36.031D', 'Desgarro moderado de bazo, contacto sucesivo', 'Sin especificar', '["control desgarro moderado bazo", "seguimiento bazo moderado", "revisión médica bazo", "evolución bazo"]'),
('S36.031S', 'Desgarro moderado de bazo, secuela', 'Sin especificar', '["secuela desgarro bazo moderado", "dolor residual bazo", "daño esplénico crónico"]'),
('S36.032A', 'Desgarro grave de bazo, contacto inicial', 'Sin especificar', '["ruptura de bazo", "desgarro grave bazo", "emergencia médica bazo", "bazo partido", "sangrado interno bazo", "choque por bazo", "dolor abdominal intenso bazo"]'),
('S36.032D', 'Desgarro grave de bazo, contacto sucesivo', 'Sin especificar', '["seguimiento ruptura bazo", "revisión bazo grave", "control posoperatorio bazo", "curación bazo roto"]'),
('S36.032S', 'Desgarro grave de bazo, secuela', 'Sin especificar', '["secuelas ruptura bazo", "problemas post-cirugía bazo", "consecuencias bazo grave"]'),
('S36.039A', 'Desgarro no especificado de bazo, contacto inicial', 'Sin especificar', '["bazo lesionado", "desgarro en bazo", "dolor en la guata costado", "trauma bazo", "urgencia esplénica"]'),
('S36.039D', 'Desgarro no especificado de bazo, contacto sucesivo', 'Sin especificar', '["seguimiento lesión bazo", "control desgarro bazo", "revisión médica", "evolución de bazo"]'),
('S36.039S', 'Desgarro no especificado de bazo, secuela', 'Sin especificar', '["secuela bazo", "problemas bazo", "efectos largo plazo bazo"]'),
('S36.09XA', 'Otro traumatismo de bazo, contacto inicial', 'Sin especificar', '["lesión bazo", "trauma esplénico otro", "daño bazo", "urgencia bazo", "golpe costillas"]'),
('S36.09XD', 'Otro traumatismo de bazo, contacto sucesivo', 'Sin especificar', '["control traumatismo bazo", "seguimiento lesión esplénica", "revisión médica bazo"]'),
('S36.09XS', 'Otro traumatismo de bazo, secuela', 'Sin especificar', '["secuela trauma bazo", "problemas residuales bazo"]'),
('S36.112A', 'Contusión de hígado, contacto inicial', 'Sin especificar', '["golpe en el hígado", "moretón en el hígado", "traumatismo hepático", "dolor bajo costillas derechas", "dolor de hígado por golpe", "hepatocontusión"]'),
('S36.112D', 'Contusión de hígado, contacto sucesivo', 'Sin especificar', '["seguimiento contusión hígado", "revisión golpe hígado", "control médico hígado", "evolución trauma hepático"]'),
('S36.112S', 'Contusión de hígado, secuela', 'Sin especificar', '["secuela contusión hígado", "dolor crónico hígado", "cicatriz hepática"]'),
('S36.113A', 'Desgarro de hígado de grado no especificado, contacto inicial', 'Sin especificar', '["hígado rasgado", "desgarro hepático", "lesión hígado", "golpe fuerte abdomen superior", "urgencia hígado"]'),
('S36.113D', 'Desgarro de hígado de grado no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro hígado", "revisión lesión hepática", "control hígado", "evolución desgarro hepático"]'),
('S36.113S', 'Desgarro de hígado de grado no especificado, secuela', 'Sin especificar', '["secuela desgarro hígado", "efectos post-lesión hígado", "complicaciones hepáticas"]'),
('S36.114A', 'Desgarro leve de hígado, contacto inicial', 'Sin especificar', '["fisura hígado leve", "desgarro hepático pequeño", "lesión hígado leve", "golpe en la panza lado derecho"]'),
('S36.114D', 'Desgarro leve de hígado, contacto sucesivo', 'Sin especificar', '["control desgarro leve hígado", "seguimiento hígado", "revisión médica hepática"]'),
('S36.114S', 'Desgarro leve de hígado, secuela', 'Sin especificar', '["secuelas desgarro leve hígado", "dolor residual hígado"]'),
('S36.115A', 'Desgarro moderado de hígado, contacto inicial', 'Sin especificar', '["desgarro moderado hígado", "lesión seria hígado", "trauma hepático moderado", "golpe fuerte hígado"]'),
('S36.115D', 'Desgarro moderado de hígado, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro moderado hígado", "control hepático", "evolución lesión moderada"]'),
('S36.115S', 'Desgarro moderado de hígado, secuela', 'Sin especificar', '["secuela desgarro moderado hígado", "problemas hepáticos", "dolor crónico hepático"]'),
('S36.116A', 'Desgarro grave de hígado, contacto inicial', 'Sin especificar', '["ruptura hígado", "desgarro severo hígado", "lesión hepática grave", "hemorragia hepática", "urgencia extrema hígado"]'),
('S36.116D', 'Desgarro grave de hígado, contacto sucesivo', 'Sin especificar', '["seguimiento ruptura hígado", "revisión desgarro grave hígado", "control post-trauma hepático"]'),
('S36.116S', 'Desgarro grave de hígado, secuela', 'Sin especificar', '["secuelas desgarro grave hígado", "efectos largo plazo hepático", "complicaciones graves hígado"]'),
('S36.118A', 'Otro traumatismo de hígado, contacto inicial', 'Sin especificar', '["trauma hígado", "golpe hígado", "daño hepático", "urgencia hígado"]'),
('S36.118D', 'Otro traumatismo de hígado, contacto sucesivo', 'Sin especificar', '["seguimiento trauma hígado", "control médico hepático", "revisión hígado"]'),
('S36.118S', 'Otro traumatismo de hígado, secuela', 'Sin especificar', '["secuela trauma hígado", "daño crónico hígado"]'),
('S36.119A', 'Traumatismo no especificado de hígado, contacto inicial', 'Sin especificar', '["lesión en el hígado", "golpe en la panza", "dolor lado derecho", "trauma hepático"]'),
('S36.119D', 'Traumatismo no especificado de hígado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión hígado", "control médico", "revisión hepática"]'),
('S36.119S', 'Traumatismo no especificado de hígado, secuela', 'Sin especificar', '["secuelas hígado", "problemas hepáticos"]'),
('S36.122A', 'Contusión de vesícula biliar, contacto inicial', 'Sin especificar', '["golpe en la vesícula", "dolor bajo las costillas derechas", "traumatismo vesícula", "dolor biliar por golpe"]'),
('S36.122D', 'Contusión de vesícula biliar, contacto sucesivo', 'Sin especificar', '["seguimiento golpe vesícula", "control vesícula", "revisión médica biliar"]'),
('S36.122S', 'Contusión de vesícula biliar, secuela', 'Sin especificar', '["secuela contusión vesícula", "dolor crónico vesícula"]'),
('S36.123A', 'Desgarro de vesícula biliar, contacto inicial', 'Sin especificar', '["vesícula rota", "desgarro vesícula", "lesión vesícula biliar", "urgencia biliar"]'),
('S36.123D', 'Desgarro de vesícula biliar, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro vesícula", "control médico biliar", "revisión post-lesión"]'),
('S36.123S', 'Desgarro de vesícula biliar, secuela', 'Sin especificar', '["secuelas desgarro vesícula", "problemas biliares post-golpe"]'),
('S36.128A', 'Otro traumatismo de vesícula biliar, contacto inicial', 'Sin especificar', '["daño vesícula", "trauma vesícula biliar", "golpe vesícula"]'),
('S36.128D', 'Otro traumatismo de vesícula biliar, contacto sucesivo', 'Sin especificar', '["seguimiento vesícula", "control médico vesícula"]'),
('S36.128S', 'Otro traumatismo de vesícula biliar, secuela', 'Sin especificar', '["secuelas vesícula", "problemas vesícula"]'),
('S36.129A', 'Traumatismo no especificado de vesícula biliar, contacto inicial', 'Sin especificar', '["lesión vesícula", "golpe en el costado derecho", "urgencia vesícula"]'),
('S36.129D', 'Traumatismo no especificado de vesícula biliar, contacto sucesivo', 'Sin especificar', '["seguimiento lesión vesícula", "control médico"]'),
('S36.129S', 'Traumatismo no especificado de vesícula biliar, secuela', 'Sin especificar', '["secuelas vesícula", "problemas vesícula"]'),
('S36.13XA', 'Traumatismo de conducto biliar, contacto inicial', 'Sin especificar', '["lesión conducto biliar", "daño vías biliares", "golpe abdomen", "urgencia biliar"]'),
('S36.13XD', 'Traumatismo de conducto biliar, contacto sucesivo', 'Sin especificar', '["seguimiento lesión conducto biliar", "revisión vías biliares"]'),
('S36.13XS', 'Traumatismo de conducto biliar, secuela', 'Sin especificar', '["secuelas conducto biliar", "problemas biliares crónicos"]'),
('S36.200A', 'Traumatismo no especificado de cabeza del páncreas, contacto inicial', 'Sin especificar', '["golpe páncreas cabeza", "lesión cabeza páncreas", "dolor boca del estómago", "trauma pancreático"]'),
('S36.200D', 'Traumatismo no especificado de cabeza del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento cabeza páncreas", "control páncreas", "revisión médica"]'),
('S36.200S', 'Traumatismo no especificado de cabeza del páncreas, secuela', 'Sin especificar', '["secuela cabeza páncreas", "problemas pancreáticos"]'),
('S36.201A', 'Traumatismo no especificado de cuerpo del páncreas, contacto inicial', 'Sin especificar', '["golpe cuerpo páncreas", "lesión páncreas", "dolor abdominal alto", "trauma páncreas"]'),
('S36.201D', 'Traumatismo no especificado de cuerpo del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento cuerpo páncreas", "control páncreas", "revisión médica"]'),
('S36.201S', 'Traumatismo no especificado de cuerpo del páncreas, secuela', 'Sin especificar', '["secuela cuerpo páncreas", "problemas pancreáticos"]'),
('S36.202A', 'Traumatismo no especificado de cola del páncreas, contacto inicial', 'Sin especificar', '["golpe cola páncreas", "lesión cola páncreas", "dolor costado izquierdo", "trauma páncreas"]'),
('S36.202D', 'Traumatismo no especificado de cola del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento cola páncreas", "control páncreas", "revisión médica"]'),
('S36.202S', 'Traumatismo no especificado de cola del páncreas, secuela', 'Sin especificar', '["secuela cola páncreas", "problemas pancreáticos"]'),
('S36.209A', 'Traumatismo no especificad de parte no especificada del páncreas, contacto inicial', 'Sin especificar', '["lesión páncreas", "golpe abdomen", "dolor páncreas", "urgencia páncreas"]'),
('S36.209D', 'Traumatismo no especificad de parte no especificada del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento páncreas", "control médico páncreas"]'),
('S36.209S', 'Traumatismo no especificad de parte no especificada del páncreas, secuela', 'Sin especificar', '["secuelas páncreas", "problemas páncreas"]'),
('S36.220A', 'Contusión de cabeza del páncreas, contacto inicial', 'Sin especificar', '["golpe cabeza páncreas", "trauma cabeza páncreas", "contusión pancreática"]'),
('S36.220D', 'Contusión de cabeza del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento contusión cabeza páncreas", "control médico"]'),
('S36.220S', 'Contusión de cabeza del páncreas, secuela', 'Sin especificar', '["secuela contusión cabeza páncreas", "problemas pancreáticos"]'),
('S36.221A', 'Contusión de cuerpo del páncreas, contacto inicial', 'Sin especificar', '["golpe cuerpo páncreas", "trauma cuerpo páncreas", "contusión páncreas"]'),
('S36.221D', 'Contusión de cuerpo del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento contusión cuerpo páncreas", "control médico"]'),
('S36.221S', 'Contusión de cuerpo del páncreas, secuela', 'Sin especificar', '["secuela contusión cuerpo páncreas", "problemas pancreáticos"]'),
('S36.222A', 'Contusión de cola del páncreas, contacto inicial', 'Sin especificar', '["golpe cola páncreas", "trauma cola páncreas", "contusión cola páncreas"]'),
('S36.222D', 'Contusión de cola del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento contusión cola páncreas", "control médico"]'),
('S36.222S', 'Contusión de cola del páncreas, secuela', 'Sin especificar', '["secuela contusión cola páncreas", "problemas pancreáticos"]'),
('S36.229A', 'Contusión de parte no especificada del páncreas, contacto inicial', 'Sin especificar', '["golpe páncreas", "contusión páncreas", "trauma páncreas"]'),
('S36.229D', 'Contusión de parte no especificada del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento contusión páncreas", "control médico"]'),
('S36.229S', 'Contusión de parte no especificada del páncreas, secuela', 'Sin especificar', '["secuela contusión páncreas", "problemas páncreas"]'),
('S36.230A', 'Desgarro de cabeza del páncreas de grado no especificado, contacto inicial', 'Sin especificar', '["desgarro cabeza páncreas", "lesión cabeza páncreas", "urgencia páncreas"]'),
('S36.230D', 'Desgarro de cabeza del páncreas de grado no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro cabeza páncreas", "revisión médica"]'),
('S36.230S', 'Desgarro de cabeza del páncreas de grado no especificado, secuela', 'Sin especificar', '["secuela desgarro cabeza páncreas", "problemas pancreáticos"]'),
('S36.231A', 'Desgarro de cuerpo del páncreas de grado no especificado, contacto inicial', 'Sin especificar', '["desgarro cuerpo páncreas", "lesión cuerpo páncreas", "urgencia páncreas"]'),
('S36.231D', 'Desgarro de cuerpo del páncreas de grado no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro cuerpo páncreas", "revisión médica"]'),
('S36.231S', 'Desgarro de cuerpo del páncreas de grado no especificado, secuela', 'Sin especificar', '["secuela desgarro cuerpo páncreas", "problemas pancreáticos"]'),
('S36.232A', 'Desgarro de cola del páncreas de grado no especificado, contacto inicial', 'Sin especificar', '["desgarro cola páncreas", "lesión cola páncreas", "urgencia páncreas"]'),
('S36.232D', 'Desgarro de cola del páncreas de grado no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro cola páncreas", "revisión médica"]'),
('S36.232S', 'Desgarro de cola del páncreas de grado no especificado, secuela', 'Sin especificar', '["secuela desgarro cola páncreas", "problemas pancreáticos"]'),
('S36.239A', 'Desgarro de parte no especificado del páncreas de grado no especificada, contacto inicial', 'Sin especificar', '["desgarro páncreas", "lesión páncreas", "urgencia páncreas"]'),
('S36.239D', 'Desgarro de parte no especificado del páncreas de grado no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro páncreas", "revisión médica"]'),
('S36.239S', 'Desgarro de parte no especificado del páncreas de grado no especificada, secuela', 'Sin especificar', '["secuela desgarro páncreas", "problemas pancreáticos"]'),
('S36.240A', 'Desgarro leve de cabeza del páncreas, contacto inicial', 'Sin especificar', '["desgarro leve cabeza páncreas", "lesión páncreas leve"]'),
('S36.240D', 'Desgarro leve de cabeza del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro leve páncreas", "revisión médica"]'),
('S36.240S', 'Desgarro leve de cabeza del páncreas, secuela', 'Sin especificar', '["secuela desgarro leve cabeza páncreas"]'),
('S36.241A', 'Desgarro leve de cuerpo del páncreas, contacto inicial', 'Sin especificar', '["desgarro leve cuerpo páncreas", "lesión páncreas leve"]'),
('S36.241D', 'Desgarro leve de cuerpo del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro leve cuerpo páncreas", "revisión médica"]'),
('S36.241S', 'Desgarro leve de cuerpo del páncreas, secuela', 'Sin especificar', '["secuela desgarro leve cuerpo páncreas"]'),
('S36.242A', 'Desgarro leve de cola del páncreas, contacto inicial', 'Sin especificar', '["desgarro leve cola páncreas", "lesión páncreas leve"]'),
('S36.242D', 'Desgarro leve de cola del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro leve cola páncreas", "revisión médica"]'),
('S36.242S', 'Desgarro leve de cola del páncreas, secuela', 'Sin especificar', '["secuela desgarro leve cola páncreas"]'),
('S36.249A', 'Desgarro leve de parte no especificada del páncreas, contacto inicial', 'Sin especificar', '["desgarro leve páncreas", "lesión páncreas leve"]'),
('S36.249D', 'Desgarro leve de parte no especificada del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro leve páncreas", "revisión médica"]'),
('S36.249S', 'Desgarro leve de parte no especificada del páncreas, secuela', 'Sin especificar', '["secuela desgarro leve páncreas"]'),
('S36.250A', 'Desgarro moderado de cabeza del páncreas, contacto inicial', 'Sin especificar', '["desgarro moderado cabeza páncreas", "lesión páncreas moderada"]'),
('S36.250D', 'Desgarro moderado de cabeza del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro moderado cabeza páncreas", "revisión médica"]'),
('S36.250S', 'Desgarro moderado de cabeza del páncreas, secuela', 'Sin especificar', '["secuela desgarro moderado cabeza páncreas"]'),
('S36.251A', 'Desgarro moderado de cuerpo del páncreas, contacto inicial', 'Sin especificar', '["desgarro moderado cuerpo páncreas", "lesión páncreas moderada"]'),
('S36.251D', 'Desgarro moderado de cuerpo del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro moderado cuerpo páncreas", "revisión médica"]'),
('S36.251S', 'Desgarro moderado de cuerpo del páncreas, secuela', 'Sin especificar', '["secuela desgarro moderado cuerpo páncreas"]'),
('S36.252A', 'Desgarro moderado de cola del páncreas, contacto inicial', 'Sin especificar', '["desgarro moderado cola páncreas", "lesión páncreas moderada"]'),
('S36.252D', 'Desgarro moderado de cola del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro moderado cola páncreas", "revisión médica"]'),
('S36.252S', 'Desgarro moderado de cola del páncreas, secuela', 'Sin especificar', '["secuela desgarro moderado cola páncreas"]'),
('S36.259A', 'Desgarro moderado de parte no especificada del páncreas, contacto inicial', 'Sin especificar', '["desgarro moderado páncreas", "lesión páncreas moderada"]'),
('S36.259D', 'Desgarro moderado de parte no especificada del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro moderado páncreas", "revisión médica"]'),
('S36.259S', 'Desgarro moderado de parte no especificada del páncreas, secuela', 'Sin especificar', '["secuela desgarro moderado páncreas"]'),
('S36.260A', 'Desgarro grave de cabeza del páncreas, contacto inicial', 'Sin especificar', '["desgarro grave cabeza páncreas", "ruptura cabeza páncreas", "urgencia páncreas"]'),
('S36.260D', 'Desgarro grave de cabeza del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro grave cabeza páncreas", "revisión médica"]'),
('S36.260S', 'Desgarro grave de cabeza del páncreas, secuela', 'Sin especificar', '["secuela desgarro grave cabeza páncreas"]'),
('S36.261A', 'Desgarro grave de cuerpo del páncreas, contacto inicial', 'Sin especificar', '["desgarro grave cuerpo páncreas", "ruptura cuerpo páncreas", "urgencia páncreas"]'),
('S36.261D', 'Desgarro grave de cuerpo del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro grave cuerpo páncreas", "revisión médica"]'),
('S36.261S', 'Desgarro grave de cuerpo del páncreas, secuela', 'Sin especificar', '["secuela desgarro grave cuerpo páncreas"]'),
('S36.262A', 'Desgarro grave de cola del páncreas, contacto inicial', 'Sin especificar', '["desgarro grave cola páncreas", "ruptura cola páncreas", "urgencia páncreas"]'),
('S36.262D', 'Desgarro grave de cola del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro grave cola páncreas", "revisión médica"]'),
('S36.262S', 'Desgarro grave de cola del páncreas, secuela', 'Sin especificar', '["secuela desgarro grave cola páncreas"]'),
('S36.269A', 'Desgarro grave de parte no especificada del páncreas, contacto inicial', 'Sin especificar', '["desgarro grave páncreas", "ruptura páncreas", "urgencia páncreas"]'),
('S36.269D', 'Desgarro grave de parte no especificada del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro grave páncreas", "revisión médica"]'),
('S36.269S', 'Desgarro grave de parte no especificada del páncreas, secuela', 'Sin especificar', '["secuela desgarro grave páncreas"]'),
('S36.290A', 'Otro traumatismo de cabeza del páncreas, contacto inicial', 'Sin especificar', '["lesión cabeza páncreas", "trauma cabeza páncreas"]'),
('S36.290D', 'Otro traumatismo de cabeza del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento lesión cabeza páncreas", "revisión médica"]'),
('S36.290S', 'Otro traumatismo de cabeza del páncreas, secuela', 'Sin especificar', '["secuela lesión cabeza páncreas"]'),
('S36.291A', 'Otro traumatismo de cuerpo del páncreas, contacto inicial', 'Sin especificar', '["lesión cuerpo páncreas", "trauma cuerpo páncreas"]'),
('S36.291D', 'Otro traumatismo de cuerpo del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento lesión cuerpo páncreas", "revisión médica"]'),
('S36.291S', 'Otro traumatismo de cuerpo del páncreas, secuela', 'Sin especificar', '["secuela lesión cuerpo páncreas"]'),
('S36.292A', 'Otro traumatismo de cola del páncreas, contacto inicial', 'Sin especificar', '["lesión cola páncreas", "trauma cola páncreas"]'),
('S36.292D', 'Otro traumatismo de cola del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento lesión cola páncreas", "revisión médica"]'),
('S36.292S', 'Otro traumatismo de cola del páncreas, secuela', 'Sin especificar', '["secuela lesión cola páncreas"]'),
('S36.299A', 'Otro traumatismo de parte no especificada del páncreas, contacto inicial', 'Sin especificar', '["lesión páncreas", "trauma páncreas"]'),
('S36.299D', 'Otro traumatismo de parte no especificada del páncreas, contacto sucesivo', 'Sin especificar', '["seguimiento lesión páncreas", "revisión médica"]'),
('S36.299S', 'Otro traumatismo de parte no especificada del páncreas, secuela', 'Sin especificar', '["secuela lesión páncreas"]'),
('S36.30XA', 'Traumatismo no especificado de estómago, contacto inicial', 'Sin especificar', '["golpe en la panza", "dolor de estómago por golpe", "trauma gástrico", "me pegaron en el estómago"]'),
('S36.30XD', 'Traumatismo no especificado de estómago, contacto sucesivo', 'Sin especificar', '["seguimiento golpe estómago", "revisión estómago", "control dolor abdominal"]'),
('S36.30XS', 'Traumatismo no especificado de estómago, secuela', 'Sin especificar', '["secuelas golpe estómago", "dolor crónico estómago"]'),
('S36.32XA', 'Contusión de estómago, contacto inicial', 'Sin especificar', '["golpe estómago", "moretón estomacal", "dolor estomacal", "trauma gástrico"]'),
('S36.32XD', 'Contusión de estómago, contacto sucesivo', 'Sin especificar', '["seguimiento contusión estómago", "revisión estómago"]'),
('S36.32XS', 'Contusión de estómago, secuela', 'Sin especificar', '["secuela contusión estómago", "problemas estomacales"]'),
('S36.33XA', 'Desgarro de estómago, contacto inicial', 'Sin especificar', '["estómago rasgado", "perforación estómago por golpe", "desgarro gástrico", "urgencia estomacal"]'),
('S36.33XD', 'Desgarro de estómago, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro estómago", "revisión estomacal"]'),
('S36.33XS', 'Desgarro de estómago, secuela', 'Sin especificar', '["secuela desgarro estómago", "problemas digestivos post-trauma"]'),
('S36.39XA', 'Otro traumatismo del estómago, contacto inicial', 'Sin especificar', '["lesión estómago", "golpe abdomen", "trauma gástrico"]'),
('S36.39XD', 'Otro traumatismo del estómago, contacto sucesivo', 'Sin especificar', '["seguimiento lesión estómago", "revisión médica"]'),
('S36.39XS', 'Otro traumatismo del estómago, secuela', 'Sin especificar', '["secuela lesión estómago", "problemas estomacales"]'),
('S36.400A', 'Traumatismo no especificado de duodeno, contacto inicial', 'Sin especificar', '["golpe intestino", "lesión duodeno", "dolor abdominal"]'),
('S36.400D', 'Traumatismo no especificado de duodeno, contacto sucesivo', 'Sin especificar', '["seguimiento lesión duodeno", "revisión intestinal"]'),
('S36.400S', 'Traumatismo no especificado de duodeno, secuela', 'Sin especificar', '["secuela lesión duodeno", "problemas intestinales"]'),
('S36.408A', 'Traumatismo no especificado de otra parte de intestino delgado, contacto inicial', 'Sin especificar', '["golpe intestino delgado", "lesión intestinal"]'),
('S36.408D', 'Traumatismo no especificado de otra parte de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión intestino", "revisión médica"]'),
('S36.408S', 'Traumatismo no especificado de otra parte de intestino delgado, secuela', 'Sin especificar', '["secuela lesión intestino", "problemas digestivos"]'),
('S36.409A', 'Traumatismo no especificado de parte no especificada de intestino delgado, contacto inicial', 'Sin especificar', '["lesión intestino", "golpe abdomen", "dolor abdominal"]'),
('S36.409D', 'Traumatismo no especificado de parte no especificada de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión intestino", "revisión médica"]'),
('S36.409S', 'Traumatismo no especificado de parte no especificada de intestino delgado, secuela', 'Sin especificar', '["secuela lesión intestino", "problemas digestivos"]'),
('S36.410A', 'Lesión primaria por onda expansiva de duodeno, contacto inicial', 'Sin especificar', '["lesión duodeno explosión", "onda expansiva abdomen", "trauma duodeno"]'),
('S36.410D', 'Lesión primaria por onda expansiva de duodeno, contacto sucesivo', 'Sin especificar', '["seguimiento lesión duodeno", "revisión intestinal"]'),
('S36.410S', 'Lesión primaria por onda expansiva de duodeno, secuela', 'Sin especificar', '["secuela lesión duodeno", "problemas digestivos"]'),
('S36.418A', 'Lesión primaria por onda expansiva de otra parte de intestino delgado, contacto inicial', 'Sin especificar', '["lesión intestino explosión", "onda expansiva abdomen"]'),
('S36.418D', 'Lesión primaria por onda expansiva de otra parte de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión intestino", "revisión médica"]'),
('S36.418S', 'Lesión primaria por onda expansiva de otra parte de intestino delgado, secuela', 'Sin especificar', '["secuela lesión intestino", "problemas digestivos"]'),
('S36.419A', 'Lesión primaria por onda expansiva de parte no especificada de intestino delgado, contacto inicial', 'Sin especificar', '["lesión intestino explosión", "onda expansiva"]'),
('S36.419D', 'Lesión primaria por onda expansiva de parte no especificada de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión intestino", "revisión médica"]'),
('S36.419S', 'Lesión primaria por onda expansiva de parte no especificada de intestino delgado, secuela', 'Sin especificar', '["secuela lesión intestino", "problemas digestivos"]'),
('S36.420A', 'Contusión de duodeno, contacto inicial', 'Sin especificar', '["golpe duodeno", "contusión intestinal"]'),
('S36.420D', 'Contusión de duodeno, contacto sucesivo', 'Sin especificar', '["seguimiento contusión duodeno", "revisión médica"]'),
('S36.420S', 'Contusión de duodeno, secuela', 'Sin especificar', '["secuela contusión duodeno", "problemas digestivos"]'),
('S36.428A', 'Contusión de otra parte de intestino delgado, contacto inicial', 'Sin especificar', '["golpe intestino", "contusión intestinal"]'),
('S36.428D', 'Contusión de otra parte de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento contusión intestino", "revisión médica"]'),
('S36.428S', 'Contusión de otra parte de intestino delgado, secuela', 'Sin especificar', '["secuela contusión intestino", "problemas digestivos"]'),
('S36.429A', 'Contusión de parte no especificada de intestino delgado, contacto inicial', 'Sin especificar', '["golpe intestino", "contusión intestinal"]'),
('S36.429D', 'Contusión de parte no especificada de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento contusión intestino", "revisión médica"]'),
('S36.429S', 'Contusión de parte no especificada de intestino delgado, secuela', 'Sin especificar', '["secuela contusión intestino", "problemas digestivos"]'),
('S36.430A', 'Desgarro de duodeno, contacto inicial', 'Sin especificar', '["desgarro duodeno", "ruptura intestino", "urgencia abdominal"]'),
('S36.430D', 'Desgarro de duodeno, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro duodeno", "revisión médica"]'),
('S36.430S', 'Desgarro de duodeno, secuela', 'Sin especificar', '["secuela desgarro duodeno", "problemas digestivos"]'),
('S36.438A', 'Desgarro de otra parte de intestino delgado, contacto inicial', 'Sin especificar', '["desgarro intestino", "ruptura intestinal"]'),
('S36.438D', 'Desgarro de otra parte de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro intestino", "revisión médica"]'),
('S36.438S', 'Desgarro de otra parte de intestino delgado, secuela', 'Sin especificar', '["secuela desgarro intestino", "problemas digestivos"]'),
('S36.439A', 'Desgarro de parte no especificada de intestino delgado, contacto inicial', 'Sin especificar', '["desgarro intestino", "ruptura intestinal"]'),
('S36.439D', 'Desgarro de parte no especificada de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro intestino", "revisión médica"]'),
('S36.439S', 'Desgarro de parte no especificada de intestino delgado, secuela', 'Sin especificar', '["secuela desgarro intestino", "problemas digestivos"]'),
('S36.490A', 'Otro traumatismo de duodeno, contacto inicial', 'Sin especificar', '["lesión duodeno", "trauma intestinal"]'),
('S36.490D', 'Otro traumatismo de duodeno, contacto sucesivo', 'Sin especificar', '["seguimiento lesión duodeno", "revisión médica"]'),
('S36.490S', 'Otro traumatismo de duodeno, secuela', 'Sin especificar', '["secuela lesión duodeno", "problemas digestivos"]'),
('S36.498A', 'Otro traumatismo de otra parte de intestino delgado, contacto inicial', 'Sin especificar', '["lesión intestino", "trauma intestinal"]'),
('S36.498D', 'Otro traumatismo de otra parte de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión intestino", "revisión médica"]'),
('S36.498S', 'Otro traumatismo de otra parte de intestino delgado, secuela', 'Sin especificar', '["secuela lesión intestino", "problemas digestivos"]'),
('S36.499A', 'Otro traumatismo de parte no especificada de intestino delgado, contacto inicial', 'Sin especificar', '["lesión intestino", "trauma intestinal"]'),
('S36.499D', 'Otro traumatismo de parte no especificada de intestino delgado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión intestino", "revisión médica"]'),
('S36.499S', 'Otro traumatismo de parte no especificada de intestino delgado, secuela', 'Sin especificar', '["secuela lesión intestino", "problemas digestivos"]'),
('S36.500A', 'Traumatismo no especificado de colon ascendente [derecho], contacto inicial', 'Sin especificar', '["golpe colon", "lesión colon derecho", "trauma colon"]'),
('S36.500D', 'Traumatismo no especificado de colon ascendente [derecho], contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.500S', 'Traumatismo no especificado de colon ascendente [derecho], secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.501A', 'Traumatismo no especificado de colon transverso, contacto inicial', 'Sin especificar', '["golpe colon transverso", "lesión colon", "trauma colon"]'),
('S36.501D', 'Traumatismo no especificado de colon transverso, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.501S', 'Traumatismo no especificado de colon transverso, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.502A', 'Traumatismo no especificado de colon descendente [izquierdo], contacto inicial', 'Sin especificar', '["golpe colon izquierdo", "lesión colon", "trauma colon"]'),
('S36.502D', 'Traumatismo no especificado de colon descendente [izquierdo], contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.502S', 'Traumatismo no especificado de colon descendente [izquierdo], secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.503A', 'Traumatismo no especificado de colon sigmoide, contacto inicial', 'Sin especificar', '["golpe colon sigmoide", "lesión colon", "trauma colon"]'),
('S36.503D', 'Traumatismo no especificado de colon sigmoide, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.503S', 'Traumatismo no especificado de colon sigmoide, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.508A', 'Traumatismo no especificado de otra parte de colon, contacto inicial', 'Sin especificar', '["golpe colon", "lesión colon"]'),
('S36.508D', 'Traumatismo no especificado de otra parte de colon, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.508S', 'Traumatismo no especificado de otra parte de colon, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.509A', 'Traumatismo no especificado de parte no especificada de colon, contacto inicial', 'Sin especificar', '["golpe colon", "lesión colon"]'),
('S36.509D', 'Traumatismo no especificado de parte no especificada de colon, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.509S', 'Traumatismo no especificado de parte no especificada de colon, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.510A', 'Lesión primaria por onda expansiva de colon ascendente [derecho], contacto inicial', 'Sin especificar', '["lesión colon explosión", "onda expansiva colon"]'),
('S36.510D', 'Lesión primaria por onda expansiva de colon ascendente [derecho], contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.510S', 'Lesión primaria por onda expansiva de colon ascendente [derecho], secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.511A', 'Lesión primaria por onda expansiva de colon transverso, contacto inicial', 'Sin especificar', '["lesión colon explosión", "onda expansiva colon"]'),
('S36.511D', 'Lesión primaria por onda expansiva de colon transverso, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.511S', 'Lesión primaria por onda expansiva de colon transverso, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.512A', 'Lesión primaria por onda expansiva de colon descendente [izquierdo], contacto inicial', 'Sin especificar', '["lesión colon explosión", "onda expansiva colon"]'),
('S36.512D', 'Lesión primaria por onda expansiva de colon descendente [izquierdo], contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.512S', 'Lesión primaria por onda expansiva de colon descendente [izquierdo], secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.513A', 'Lesión primaria por onda expansiva de colon sigmoide, contacto inicial', 'Sin especificar', '["lesión colon explosión", "onda expansiva colon"]'),
('S36.513D', 'Lesión primaria por onda expansiva de colon sigmoide, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.513S', 'Lesión primaria por onda expansiva de colon sigmoide, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.518A', 'Lesión primaria por onda expansiva de otra parte de colon, contacto inicial', 'Sin especificar', '["lesión colon explosión", "onda expansiva"]'),
('S36.518D', 'Lesión primaria por onda expansiva de otra parte de colon, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.518S', 'Lesión primaria por onda expansiva de otra parte de colon, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.519A', 'Lesión primaria por onda expansiva de parte no especificada de colon, contacto inicial', 'Sin especificar', '["lesión colon explosión", "onda expansiva"]'),
('S36.519D', 'Lesión primaria por onda expansiva de parte no especificada de colon, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.519S', 'Lesión primaria por onda expansiva de parte no especificada de colon, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.520A', 'Contusión de colon ascendente [derecho], contacto inicial', 'Sin especificar', '["golpe colon", "contusión colon derecho"]'),
('S36.520D', 'Contusión de colon ascendente [derecho], contacto sucesivo', 'Sin especificar', '["seguimiento contusión colon", "revisión colon"]'),
('S36.520S', 'Contusión de colon ascendente [derecho], secuela', 'Sin especificar', '["secuela contusión colon", "problemas intestinales"]'),
('S36.521A', 'Contusión de colon transverso, contacto inicial', 'Sin especificar', '["golpe colon", "contusión colon transverso"]'),
('S36.521D', 'Contusión de colon transverso, contacto sucesivo', 'Sin especificar', '["seguimiento contusión colon", "revisión colon"]'),
('S36.521S', 'Contusión de colon transverso, secuela', 'Sin especificar', '["secuela contusión colon", "problemas intestinales"]'),
('S36.522A', 'Contusión de colon descendente [izquierdo], contacto inicial', 'Sin especificar', '["golpe colon", "contusión colon izquierdo"]'),
('S36.522D', 'Contusión de colon descendente [izquierdo], contacto sucesivo', 'Sin especificar', '["seguimiento contusión colon", "revisión colon"]'),
('S36.522S', 'Contusión de colon descendente [izquierdo], secuela', 'Sin especificar', '["secuela contusión colon", "problemas intestinales"]'),
('S36.523A', 'Contusión de colon sigmoide, contacto inicial', 'Sin especificar', '["golpe colon", "contusión colon sigmoide"]'),
('S36.523D', 'Contusión de colon sigmoide, contacto sucesivo', 'Sin especificar', '["seguimiento contusión colon", "revisión colon"]'),
('S36.523S', 'Contusión de colon sigmoide, secuela', 'Sin especificar', '["secuela contusión colon", "problemas intestinales"]'),
('S36.528A', 'Contusión de otra parte de colon, contacto inicial', 'Sin especificar', '["golpe colon", "contusión colon"]'),
('S36.528D', 'Contusión de otra parte de colon, contacto sucesivo', 'Sin especificar', '["seguimiento contusión colon", "revisión colon"]'),
('S36.528S', 'Contusión de otra parte de colon, secuela', 'Sin especificar', '["secuela contusión colon", "problemas intestinales"]'),
('S36.529A', 'Contusión de parte no especificada de colon, contacto inicial', 'Sin especificar', '["golpe colon", "contusión colon"]'),
('S36.529D', 'Contusión de parte no especificada de colon, contacto sucesivo', 'Sin especificar', '["seguimiento contusión colon", "revisión colon"]'),
('S36.529S', 'Contusión de parte no especificada de colon, secuela', 'Sin especificar', '["secuela contusión colon", "problemas intestinales"]'),
('S36.530A', 'Desgarro de colon ascendente [derecho], contacto inicial', 'Sin especificar', '["desgarro colon derecho", "ruptura colon"]'),
('S36.530D', 'Desgarro de colon ascendente [derecho], contacto sucesivo', 'Sin especificar', '["seguimiento desgarro colon", "revisión colon"]'),
('S36.530S', 'Desgarro de colon ascendente [derecho], secuela', 'Sin especificar', '["secuela desgarro colon", "problemas intestinales"]'),
('S36.531A', 'Desgarro de colon transverso, contacto inicial', 'Sin especificar', '["desgarro colon transverso", "ruptura colon"]'),
('S36.531D', 'Desgarro de colon transverso, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro colon", "revisión colon"]'),
('S36.531S', 'Desgarro de colon transverso, secuela', 'Sin especificar', '["secuela desgarro colon", "problemas intestinales"]'),
('S36.532A', 'Desgarro de colon descendente [izquierdo], contacto inicial', 'Sin especificar', '["desgarro colon izquierdo", "ruptura colon"]'),
('S36.532D', 'Desgarro de colon descendente [izquierdo], contacto sucesivo', 'Sin especificar', '["seguimiento desgarro colon", "revisión colon"]'),
('S36.532S', 'Desgarro de colon descendente [izquierdo], secuela', 'Sin especificar', '["secuela desgarro colon", "problemas intestinales"]'),
('S36.533A', 'Desgarro de colon sigmoide, contacto inicial', 'Sin especificar', '["desgarro colon sigmoide", "ruptura colon"]'),
('S36.533D', 'Desgarro de colon sigmoide, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro colon", "revisión colon"]'),
('S36.533S', 'Desgarro de colon sigmoide, secuela', 'Sin especificar', '["secuela desgarro colon", "problemas intestinales"]'),
('S36.538A', 'Desgarro de otra parte de colon, contacto inicial', 'Sin especificar', '["desgarro colon", "ruptura colon"]'),
('S36.538D', 'Desgarro de otra parte de colon, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro colon", "revisión colon"]'),
('S36.538S', 'Desgarro de otra parte de colon, secuela', 'Sin especificar', '["secuela desgarro colon", "problemas intestinales"]'),
('S36.539A', 'Desgarro de parte no especificada de colon, contacto inicial', 'Sin especificar', '["desgarro colon", "ruptura colon"]'),
('S36.539D', 'Desgarro de parte no especificada de colon, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro colon", "revisión colon"]'),
('S36.539S', 'Desgarro de parte no especificada de colon, secuela', 'Sin especificar', '["secuela desgarro colon", "problemas intestinales"]'),
('S36.590A', 'Otro traumatismo de colon ascendente [derecho], contacto inicial', 'Sin especificar', '["lesión colon derecho", "trauma colon"]'),
('S36.590D', 'Otro traumatismo de colon ascendente [derecho], contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.590S', 'Otro traumatismo de colon ascendente [derecho], secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.591A', 'Otro traumatismo de colon transverso, contacto inicial', 'Sin especificar', '["lesión colon transverso", "trauma colon"]'),
('S36.591D', 'Otro traumatismo de colon transverso, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.591S', 'Otro traumatismo de colon transverso, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.592A', 'Otro traumatismo de colon descendente [izquierdo], contacto inicial', 'Sin especificar', '["lesión colon izquierdo", "trauma colon"]'),
('S36.592D', 'Otro traumatismo de colon descendente [izquierdo], contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.592S', 'Otro traumatismo de colon descendente [izquierdo], secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.593A', 'Otro traumatismo de colon sigmoide, contacto inicial', 'Sin especificar', '["lesión colon sigmoide", "trauma colon"]'),
('S36.593D', 'Otro traumatismo de colon sigmoide, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.593S', 'Otro traumatismo de colon sigmoide, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.598A', 'Otro traumatismo de otra parte de colon, contacto inicial', 'Sin especificar', '["lesión colon", "trauma colon"]'),
('S36.598D', 'Otro traumatismo de otra parte de colon, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.598S', 'Otro traumatismo de otra parte de colon, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.599A', 'Otro traumatismo de parte no especificada de colon, contacto inicial', 'Sin especificar', '["lesión colon", "trauma colon"]'),
('S36.599D', 'Otro traumatismo de parte no especificada de colon, contacto sucesivo', 'Sin especificar', '["seguimiento lesión colon", "revisión colon"]'),
('S36.599S', 'Otro traumatismo de parte no especificada de colon, secuela', 'Sin especificar', '["secuela lesión colon", "problemas intestinales"]'),
('S36.60XA', 'Traumatismo no especificado de recto, contacto inicial', 'Sin especificar', '["golpe recto", "lesión rectal", "trauma recto"]'),
('S36.60XD', 'Traumatismo no especificado de recto, contacto sucesivo', 'Sin especificar', '["seguimiento lesión rectal", "revisión médica"]'),
('S36.60XS', 'Traumatismo no especificado de recto, secuela', 'Sin especificar', '["secuela lesión rectal", "problemas rectales"]'),
('S36.61XA', 'Lesión primaria por onda expansiva de recto, contacto inicial', 'Sin especificar', '["lesión recto explosión", "trauma rectal"]'),
('S36.61XD', 'Lesión primaria por onda expansiva de recto, contacto sucesivo', 'Sin especificar', '["seguimiento lesión rectal", "revisión médica"]'),
('S36.61XS', 'Lesión primaria por onda expansiva de recto, secuela', 'Sin especificar', '["secuela lesión rectal", "problemas rectales"]'),
('S36.62XA', 'Contusión de recto, contacto inicial', 'Sin especificar', '["golpe recto", "contusión rectal"]'),
('S36.62XD', 'Contusión de recto, contacto sucesivo', 'Sin especificar', '["seguimiento contusión rectal", "revisión médica"]'),
('S36.62XS', 'Contusión de recto, secuela', 'Sin especificar', '["secuela contusión rectal", "problemas rectales"]'),
('S36.63XA', 'Desgarro de recto, contacto inicial', 'Sin especificar', '["desgarro recto", "ruptura rectal"]'),
('S36.63XD', 'Desgarro de recto, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro rectal", "revisión médica"]'),
('S36.63XS', 'Desgarro de recto, secuela', 'Sin especificar', '["secuela desgarro rectal", "problemas rectales"]'),
('S36.69XA', 'Otro traumatismo de recto, contacto inicial', 'Sin especificar', '["lesión recto", "trauma rectal"]'),
('S36.69XD', 'Otro traumatismo de recto, contacto sucesivo', 'Sin especificar', '["seguimiento lesión rectal", "revisión médica"]'),
('S36.69XS', 'Otro traumatismo de recto, secuela', 'Sin especificar', '["secuela lesión rectal", "problemas rectales"]'),
('S36.81XA', 'Traumatismo de peritoneo, contacto inicial', 'Sin especificar', '["lesión peritoneo", "daño cavidad abdominal"]'),
('S36.81XD', 'Traumatismo de peritoneo, contacto sucesivo', 'Sin especificar', '["seguimiento lesión peritoneo", "revisión médica"]'),
('S36.81XS', 'Traumatismo de peritoneo, secuela', 'Sin especificar', '["secuela lesión peritoneo", "problemas abdominales"]'),
('S36.892A', 'Contusión de otros órganos intraabdominales, contacto inicial', 'Sin especificar', '["golpe órganos internos", "contusión abdominal"]'),
('S36.892D', 'Contusión de otros órganos intraabdominales, contacto sucesivo', 'Sin especificar', '["seguimiento contusión abdominal", "revisión médica"]'),
('S36.892S', 'Contusión de otros órganos intraabdominales, secuela', 'Sin especificar', '["secuela contusión órganos abdominales"]'),
('S36.893A', 'Desgarro de otros órganos intraabdominales, contacto inicial', 'Sin especificar', '["lesión órganos internos", "ruptura órganos abdominales"]'),
('S36.893D', 'Desgarro de otros órganos intraabdominales, contacto sucesivo', 'Sin especificar', '["seguimiento lesión órganos abdominales", "revisión médica"]'),
('S36.893S', 'Desgarro de otros órganos intraabdominales, secuela', 'Sin especificar', '["secuela lesión órganos abdominales"]'),
('S36.898A', 'Otro traumatismo de otros órganos intraabdominales, contacto inicial', 'Sin especificar', '["lesión órganos internos", "trauma abdominal"]'),
('S36.898D', 'Otro traumatismo de otros órganos intraabdominales, contacto sucesivo', 'Sin especificar', '["seguimiento lesión órganos abdominales", "revisión médica"]'),
('S36.898S', 'Otro traumatismo de otros órganos intraabdominales, secuela', 'Sin especificar', '["secuela lesión órganos abdominales"]'),
('S36.899A', 'Traumatismo no especificado de otros órganos intraabdominales, contacto inicial', 'Sin especificar', '["lesión órganos internos", "trauma abdominal"]'),
('S36.899D', 'Traumatismo no especificado de otros órganos intraabdominales, contacto sucesivo', 'Sin especificar', '["seguimiento lesión órganos abdominales", "revisión médica"]'),
('S36.899S', 'Traumatismo no especificado de otros órganos intraabdominales, secuela', 'Sin especificar', '["secuela lesión órganos abdominales"]'),
('S36.90XA', 'Traumatismo no especificado de órgano intraabdominal no especificado, contacto inicial', 'Sin especificar', '["lesión interna abdomen", "golpe abdomen", "urgencia abdominal"]'),
('S36.90XD', 'Traumatismo no especificado de órgano intraabdominal no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión abdominal", "revisión médica"]'),
('S36.90XS', 'Traumatismo no especificado de órgano intraabdominal no especificado, secuela', 'Sin especificar', '["secuela lesión abdominal"]'),
('S36.92XA', 'Contusión de órgano intraabdominal no especificado, contacto inicial', 'Sin especificar', '["golpe abdomen", "contusión abdominal"]'),
('S36.92XD', 'Contusión de órgano intraabdominal no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento contusión abdominal", "revisión médica"]'),
('S36.92XS', 'Contusión de órgano intraabdominal no especificado, secuela', 'Sin especificar', '["secuela contusión abdominal"]'),
('S36.93XA', 'Desgarro de órgano intraabdominal no especificado, contacto inicial', 'Sin especificar', '["lesión interna abdomen", "ruptura interna"]'),
('S36.93XD', 'Desgarro de órgano intraabdominal no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión interna abdomen", "revisión médica"]'),
('S36.93XS', 'Desgarro de órgano intraabdominal no especificado, secuela', 'Sin especificar', '["secuela lesión interna abdomen"]'),
('S36.99XA', 'Otro traumatismo de órgano intraabdominal no especificado, contacto inicial', 'Sin especificar', '["lesión interna abdomen", "trauma abdominal"]'),
('S36.99XD', 'Otro traumatismo de órgano intraabdominal no especificado, contacto sucesivo', 'Sin especificar', '["seguimiento lesión interna abdominal", "revisión médica"]'),
('S36.99XS', 'Otro traumatismo de órgano intraabdominal no especificado, secuela', 'Sin especificar', '["secuela lesión interna abdominal"]');
