INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q16.0', 'Ausencia congénita de oído (oreja)', 'Sin especificar', '["oreja ausente", "anotia", "falta de oreja al nacer", "oreja malformada", "microtia", "no tengo oreja", "problemas de pabellón auricular", "deformidad de oreja congénita", "oreja chiquita", "sin oreja", "problema auditivo externo", "malformación en la oreja", "problema en el pabellón", "oreja subdesarrollada", "oreja plana"]'),
('Q16.1', 'Ausencia, atresia y estenosis congénita del conducto auditivo (externo)', 'Sin especificar', '["conducto auditivo cerrado", "atresia de conducto", "no tengo hueco en el oído", "conducto estrecho", "estenosis auditiva", "oído tapado de nacimiento", "canal auditivo bloqueado", "conducto auditivo imperforado", "no puedo meter nada al oído", "problema de entrada al oído", "atresia conducto auditivo", "conducto auditivo obstruido", "canal estrechito", "falta de canal auditivo"]'),
('Q16.2', 'Ausencia de la trompa de Eustaquio', 'Sin especificar', '["problemas en la trompa de Eustaquio", "trompa de Eustaquio inexistente", "falta de conexión oído y garganta", "oído se siente tapado siempre", "trompa de eustaquio mal formada", "problemas de presión en el oído", "tuba auditiva ausente", "oído sordo de nacimiento", "malformación conducto oído medio", "aire en el oído", "problemas de drenaje de oido"]'),
('Q16.3', 'Malformación congénita de los huesecillos del oído', 'Sin especificar', '["huesos del oído mal formados", "estribo martillo yunque mal", "problema en los huesecillos", "sordera de nacimiento", "problema en el oído medio", "huesos del oído sin desarrollar", "malformación osicular", "no escucho bien por los huesitos", "fallo en cadena de huesecillos", "hipoacusia congénita", "problemas auditivos estructurales", "malformación del martillo", "malformación del yunque", "malformación del estribo"]'),
('Q16.4', 'Otras malformaciones congénitas del oído medio', 'Sin especificar', '["problemas oido medio", "malformación oído medio", "oído medio deforme", "problema caja del tímpano", "caja del tímpano mal formada", "anomalía del oído medio", "problemas auditivos estructurales internos", "malformaciones congénitas oido", "oído medio defectuoso", "sordera conductiva", "problema de ventilación oído", "oído que no escucha bien de nacimiento"]'),
('Q16.5', 'Malformación congénita del oído interno', 'Sin especificar', '["problemas oido interno", "cóclea mal formada", "malformación laberinto", "problema en caracol del oído", "sordera profunda", "oído interno defectuoso", "malformación congénita coclear", "sordera de nacimiento nervio auditivo", "problema en nervio del oído", "no escucho por malformación interna", "hipoacusia severa", "anomalía laberíntica", "problema de equilibrio y oído"]'),
('Q16.9', 'Malformación congénita del oído que causa alteración en la audición, no especificada', 'Sin especificar', '["sordo de nacimiento", "bebé no escucha", "problemas auditivos congénitos", "oído deforme y no oigo", "malformación congénita auditiva", "hipoacusia", "sordera", "no oigo bien desde bebé", "problema de nacimiento en el oído", "anomalía del sistema auditivo", "defecto auditivo de nacimiento", "oído que no funciona", "sordera hereditaria", "problemas para oír de bebé", "discapacidad auditiva congénita"]');
