INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H51.0', 'Parálisis (espasmo) de mirada conjugada', 'Sin especificar', '["ojos trabados", "parálisis ocular", "ojos bloqueados", "espasmo de mirada", "no puedo mover los ojos", "ojos desviados", "desviación ocular", "mirada fija", "parálisis de mirada", "ojos paralizados", "ojo vago", "bloqueo de movimiento ocular", "dificultad para mover los ojos", "espasmo ocular"]'),
('H51.11', 'Convergencia insuficiente', 'Sin especificar', '["ojo flojo al leer", "dificultad para enfocar de cerca", "cansancio visual", "fatiga ocular", "visión doble al leer", "se me juntan las letras", "mala convergencia", "dolor de ojos al estudiar", "esfuerzo visual", "debilidad ocular", "vista cansada", "problemas de enfoque", "esotropia divergente", "falta de enfoque"]'),
('H51.12', 'Exceso de convergencia', 'Sin especificar', '["exceso de enfoque", "ojos demasiado cruzados", "sobreesfuerzo visual", "ojos bizcos", "estrabismo convergente", "tensión ocular", "vista forzada", "dolor de cabeza por enfocar", "espasmo de convergencia", "exceso de cruce ocular", "fatiga al leer", "ojo metido", "hiperconvergencia"]'),
('H51.20', 'Oftalmoplejia internuclear, ojo no especificado', 'Sin especificar', '["ojo desincronizado", "movimiento ocular lento", "fallo de coordinación ocular", "parálisis de mirada lateral", "diplopía", "visión doble", "lesión ocular", "oftalmoplejia", "problemas de conexión ocular", "descoordinación de ojos", "ojos que no van juntos", "trastorno de mirada"]'),
('H51.21', 'Oftalmoplejia internuclear, ojo derecho', 'Sin especificar', '["ojo derecho trabado", "ojo derecho no gira", "fallo en ojo derecho", "descoordinación ojo derecho", "oftalmoplejia ojo derecho", "visión doble ojo derecho", "el ojo derecho se queda atrás", "parálisis internuclear derecha", "ojo derecho lento", "falla de movimiento ojo derecho"]'),
('H51.22', 'Oftalmoplejia internuclear, ojo izquierdo', 'Sin especificar', '["ojo izquierdo trabado", "ojo izquierdo no gira", "fallo en ojo izquierdo", "descoordinación ojo izquierdo", "oftalmoplejia ojo izquierdo", "visión doble ojo izquierdo", "el ojo izquierdo se queda atrás", "parálisis internuclear izquierda", "ojo izquierdo lento", "falla de movimiento ojo izquierdo"]'),
('H51.23', 'Oftalmoplejia internuclear, bilateral', 'Sin especificar', '["ojos desincronizados", "ambos ojos no giran", "falla de coordinación en ambos ojos", "oftalmoplejia bilateral", "parálisis de mirada doble", "ojos que no siguen el movimiento", "bloqueo de movimiento en ambos ojos", "visión doble constante", "descoordinación severa de ojos"]'),
('H51.8', 'Otros trastornos especificados del movimiento binocular', 'Sin especificar', '["problemas de coordinación ocular", "ojos que no trabajan juntos", "estrabismo", "trastornos binoculares", "mala visión de conjunto", "dificultad para mover los ojos", "incoordinación ocular", "ojos disociados", "fallo en el trabajo en equipo de los ojos", "problemas de movimiento ocular"]'),
('H51.9', 'Trastorno del movimiento binocular no especificado', 'Sin especificar', '["problemas de ojos", "no puedo mover bien los ojos", "ojos raros", "falla ocular", "dolor al mover los ojos", "descontrol ocular", "visión extraña", "ojos que no coordinan", "problema en el movimiento de los ojos", "me saltan los ojos", "ojos descoordinados"]');
