INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('I42.0', 'Miocardiopatía dilatada', 'Sin especificar', '["corazón grande", "cardiomegalia", "corazón dilatado", "insuficiencia cardíaca", "músculo cardíaco débil", "corazón estirado", "fallo cardíaco", "cansancio extremo", "fatiga crónica", "falta de aire", "corazón ancho", "edema", "hinchazón de piernas", "corazón agrandado", "cardiomiopatía", "debilidad del corazón"]'),
('I42.1', 'Miocardiopatía hipertrófica obstructiva', 'Sin especificar', '["músculo cardíaco grueso", "corazón hipertrófico", "hipertrofia septal", "obstrucción al flujo cardíaco", "desmayos al hacer ejercicio", "síncope", "dolor en el pecho", "angina", "palpitaciones", "taquicardia", "corazón muy fuerte", "obstrucción ventricular", "riesgo de muerte súbita", "insuficiencia cardíaca obstructiva", "soplo cardíaco"]'),
('I42.2', 'Otras Miocardiopatías hipertróficas', 'Sin especificar', '["engrosamiento del corazón", "músculo cardíaco hipertrofiado", "hipertrofia del ventrículo", "corazón con paredes gruesas", "corazón rígido", "insuficiencia diastólica", "disfunción cardíaca", "problemas en el músculo del corazón", "cardiomiopatía hipertrófica", "dolor torácico", "falta de aliento", "fatiga física", "miocardiopatía idiopática"]'),
('I42.3', 'Enfermedad endomiocárdica (eosinofílica)', 'Sin especificar', '["fibrosis endomiocárdica", "síndrome hipereosinofílico", "corazón con tejido cicatricial", "inflamación del endocardio", "endocarditis eosinofílica", "corazón rígido", "falla cardíaca restrictiva", "aumento de eosinófilos en sangre", "daño al revestimiento del corazón", "fibrosis cardíaca", "insuficiencia cardíaca derecha"]'),
('I42.4', 'Fibroelastosis endocárdica', 'Sin especificar', '["corazón engrosado en niños", "endocardio endurecido", "fibrosis del corazón", "fibroelastosis", "corazón rígido congénito", "falla cardíaca infantil", "engrosamiento fibroso del corazón", "daño al corazón bebé", "cardiomiopatía restrictiva infantil", "corazón con elastina excesiva"]'),
('I42.5', 'Otras miocardiopatías restrictivas', 'Sin especificar', '["corazón rígido", "dificultad para relajarse el corazón", "llenado cardíaco pobre", "miocardiopatía infiltrativa", "músculo cardíaco inflexible", "insuficiencia cardíaca diastólica", "cardiomiopatía restrictiva", "edema generalizado", "fatiga al esfuerzo", "corazón tieso", "problemas de relajación cardíaca"]'),
('I42.6', 'Miocardiopatía alcohólica', 'Sin especificar', '["corazón por alcohol", "corazón de borracho", "daño cardíaco por alcoholismo", "corazón alcohólico", "miocardiopatía tóxica", "insuficiencia cardíaca por alcohol", "debilidad cardíaca por alcohol", "corazón grande por trago", "tomadera y corazón", "cardiomiopatía etílica", "falla del corazón por licor"]'),
('I42.7', 'Miocardiopatía debida a drogas y otros agentes externos', 'Sin especificar', '["corazón dañado por drogas", "cardiotoxicidad por medicamentos", "corazón por cocaína", "daño cardíaco por quimioterapia", "miocardiopatía tóxica", "corazón intoxicado", "falla cardíaca por fármacos", "corazón débil por sustancias", "cardiomiopatía por venenos", "daño cardíaco por metanfetaminas"]'),
('I42.8', 'Otras miocardiopatías', 'Sin especificar', '["enfermedad del músculo cardíaco", "cardiomiopatía inespecífica", "falla del corazón", "corazón débil", "miocardiopatía rara", "problema en el ventrículo", "corazón que no bombea bien", "debilidad miocárdica", "falla ventricular", "corazón con anomalías", "problemas crónicos del corazón"]'),
('I42.9', 'Miocardiopatía, no especificada', 'Sin especificar', '["problemas del corazón", "enfermedad del corazón", "corazón débil", "falla cardíaca", "cardiomiopatía", "tengo algo en el corazón", "corazón no funciona bien", "insuficiencia del corazón", "problemas de bombeo", "músculo cardíaco enfermo", "cardiopatía", "mal del corazón"]');
