INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A48.0', 'Gangrena gaseosa', 'Sin especificar', '["gangrena", "necrosis", "infección por clostridium", "podredumbre", "carne podrida", "infección en herida", "herida con gas", "burbujas en la piel", "olor a podrido en herida", "crepitación", "muerte de tejido", "infección fulminante", "septicemia por gas", "gangrena necrotizante", "infección grave", "herida negra"]'),
('A48.1', 'Enfermedad de los legionarios', 'Sin especificar', '["legionelosis", "neumonía de los legionarios", "fiebre del legionario", "bacteria del aire acondicionado", "infección pulmonar por agua", "neumonía bacteriana", "tos con legionella", "brotes de neumonía", "infección por torres de enfriamiento", "tos seca y fiebre", "neumonía atípica", "fiebre alta y tos", "enfermedad del aire", "legionella pneumophila"]'),
('A48.2', 'Enfermedad de los legionarios no neumónica [fiebre de Pontiac]', 'Sin especificar', '["fiebre de pontiac", "gripe de pontiac", "legionelosis sin neumonía", "tos sin pulmón afectado", "fiebre leve y escalofríos", "dolor muscular por legionella", "malestar general por agua", "infección por aire acondicionado", "fiebre pasajera", "síndrome pseudogripal", "dolor de cuerpo y fiebre", "infección leve por bacterias", "gripe atípica"]'),
('A48.3', 'Síndrome de shock tóxico', 'Sin especificar', '["shock tóxico", "síndrome de shock", "infección por estafilococo", "fiebre alta repentina", "bajada de tensión brusca", "desmayo por infección", "shock por tampones", "infección por heridas", "colapso circulatorio", "sepsis severa", "erupción cutánea", "bajada de presión arterial", "insuficiencia multiorgánica", "infección fulminante", "intoxicación bacteriana"]'),
('A48.4', 'Fiebre purpúrica brasileña', 'Sin especificar', '["fiebre purpúrica", "manchas moradas en la piel", "púrpura brasileña", "infección por haemophilus", "fiebre con manchas", "sepsis hemorrágica", "manchas en el cuerpo", "shock por bacteria", "fiebre y sangrado", "petequias", "infección tropical", "fiebre fulminante", "manchas rojas en la piel", "septicemia brasileña"]'),
('A48.51', 'Botulismo infantil', 'Sin especificar', '["botulismo en bebés", "bebé flojo", "estreñimiento en bebés", "parálisis infantil", "dificultad para succionar", "infección por miel", "bacteria en miel", "bebé sin fuerza", "debilidad muscular en bebés", "intoxicación botulínica", "párpados caídos en bebé", "llanto débil", "bebé que no sostiene la cabeza", "botulismo del lactante"]'),
('A48.52', 'Botulismo por herida', 'Sin especificar', '["botulismo en una herida", "infección de herida por botulismo", "herida infectada por toxina", "parálisis por herida", "toxina de clostridium", "herida profunda", "músculos sin fuerza por herida", "herida sucia", "debilidad tras lesión", "visión borrosa por herida", "infección bacteriana en corte", "intoxicación por herida"]'),
('A48.8', 'Otras enfermedades bacterianas especificadas', 'Sin especificar', '["infección bacteriana rara", "bacterias atípicas", "infección bacteriana no común", "bicho bacteriano", "infección interna", "fiebre de origen bacteriano", "enfermedad por bacterias", "infección inusual", "cuadro bacteriano", "bacteremia", "malestar por infección", "infección bacteriana no clasificada"]');
