INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('M89.00', 'Algoneurodistrofia, localización no especificada', 'Sin especificar', '["Sudeck", "distrofia simpática refleja", "dolor crónico óseo", "quemazón en huesos", "inflamación ósea crónica", "dolor ardiente", "hipersensibilidad ósea", "problemas nerviosos en huesos", "cambios de color en la piel", "atrofia ósea", "dolor neuropático localizado", "frialdad en la zona", "rigidez articular inexplicable"]'),
('M89.011', 'Algoneurodistrofia, hombro derecho', 'Sin especificar', '["hombro doloroso", "Sudeck en hombro", "dolor en el hombro derecho", "hombro congelado doloroso", "pinzamiento crónico", "ardor en el hombro", "inflamación en el hombro derecho", "rigidez del hombro", "dolor nervioso hombro derecho", "trastorno óseo hombro derecho", "dificultad para mover el hombro"]'),
('M89.012', 'Algoneurodistrofia, hombro izquierdo', 'Sin especificar', '["hombro izquierdo doloroso", "distrofia ósea hombro izquierdo", "dolor crónico en hombro izquierdo", "ardor en el hombro izquierdo", "inflamación de hombro izquierdo", "problema nervioso hombro izquierdo", "rigidez hombro izquierdo", "Sudeck hombro izquierdo"]'),
('M89.019', 'Algoneurodistrofia, hombro no especificado', 'Sin especificar', '["dolor en hombro", "Sudeck en hombro", "inflamación ósea hombro", "ardor en el hombro", "problema óseo en hombro", "dolor crónico en hombro", "rigidez de hombro"]'),
('M89.021', 'Algoneurodistrofia, brazo derecho', 'Sin especificar', '["dolor en el brazo derecho", "brazo ardiendo", "Sudeck brazo derecho", "dolor óseo brazo derecho", "brazo rígido y doloroso", "pinchazos en el brazo", "inflamación del brazo", "problemas de circulación y huesos brazo derecho"]'),
('M89.022', 'Algoneurodistrofia, brazo izquierdo', 'Sin especificar', '["dolor en el brazo izquierdo", "brazo izquierdo adolorido", "Sudeck brazo izquierdo", "ardor en brazo izquierdo", "inflamación brazo izquierdo", "brazo rígido izquierdo", "dolor profundo brazo izquierdo"]'),
('M89.029', 'Algoneurodistrofia, brazo, no especificada', 'Sin especificar', '["dolor en brazo", "brazo adolorido", "ardor en brazo", "inflamación de hueso en el brazo", "Sudeck en el brazo", "dolor crónico en brazo"]'),
('M89.031', 'Algoneurodistrofia, antebrazo derecho', 'Sin especificar', '["dolor antebrazo derecho", "ardor antebrazo derecho", "Sudeck antebrazo derecho", "inflamación ósea antebrazo", "rigidez antebrazo derecho"]'),
('M89.032', 'Algoneurodistrofia, antebrazo izquierdo', 'Sin especificar', '["dolor antebrazo izquierdo", "ardor antebrazo izquierdo", "Sudeck antebrazo izquierdo", "inflamación ósea antebrazo izquierdo", "rigidez antebrazo izquierdo"]'),
('M89.039', 'Algoneurodistrofia, antebrazo no especificado', 'Sin especificar', '["dolor antebrazo", "ardor antebrazo", "Sudeck antebrazo", "inflamación ósea antebrazo", "rigidez antebrazo"]'),
('M89.041', 'Algoneurodistrofia, mano derecha', 'Sin especificar', '["mano dolorosa", "Sudeck en la mano", "ardor en la mano derecha", "mano derecha hinchada", "rigidez de mano derecha", "dolor crónico mano derecha", "huesos de la mano doloridos", "mano derecha sensible"]'),
('M89.042', 'Algoneurodistrofia, mano izquierda', 'Sin especificar', '["mano izquierda dolorosa", "Sudeck mano izquierda", "ardor en la mano izquierda", "mano izquierda hinchada", "rigidez de mano izquierda", "dolor crónico mano izquierda", "huesos de la mano izquierda doloridos"]'),
('M89.049', 'Algoneurodistrofia, mano no especificada', 'Sin especificar', '["dolor en la mano", "Sudeck en mano", "ardor en la mano", "mano hinchada", "rigidez de manos", "dolor crónico en los huesos de la mano"]'),
('M89.051', 'Algoneurodistrofia, muslo derecho', 'Sin especificar', '["dolor muslo derecho", "Sudeck en la pierna", "ardor en el muslo derecho", "pierna derecha adolorida", "dolor de fémur", "molestia muslo derecho"]'),
('M89.052', 'Algoneurodistrofia, muslo izquierdo', 'Sin especificar', '["dolor muslo izquierdo", "Sudeck en muslo izquierdo", "ardor en el muslo izquierdo", "pierna izquierda adolorida", "dolor de hueso muslo"]'),
('M89.059', 'Algoneurodistrofia, muslo no especificado', 'Sin especificar', '["dolor en el muslo", "ardor en el muslo", "dolor de pierna", "molestia ósea en el muslo", "Sudeck en muslo"]'),
('M89.061', 'Algoneurodistrofia, pierna derecha', 'Sin especificar', '["pierna derecha adolorida", "dolor de canilla", "Sudeck en pierna derecha", "ardor en la pierna derecha", "huesos de la pierna duelen", "pierna derecha hinchada y dolorosa"]'),
('M89.062', 'Algoneurodistrofia, pierna izquierda', 'Sin especificar', '["pierna izquierda adolorida", "dolor pierna izquierda", "Sudeck en pierna izquierda", "ardor en la pierna izquierda", "huesos de la pierna izquierda duelen"]'),
('M89.069', 'Algoneurodistrofia, pierna, no especificada', 'Sin especificar', '["dolor de pierna", "pierna ardiendo", "huesos de la pierna duelen", "Sudeck en la pierna", "pierna adolorida"]'),
('M89.071', 'Algoneurodistrofia, tobillo y pie derechos', 'Sin especificar', '["pie derecho adolorido", "tobillo derecho doloroso", "Sudeck en el pie", "ardor en el pie derecho", "dolor en el empeine", "pie derecho hinchado", "huesos del pie derecho duelen"]'),
('M89.072', 'Algoneurodistrofia, tobillo y pie izquierdos', 'Sin especificar', '["pie izquierdo adolorido", "tobillo izquierdo doloroso", "Sudeck en pie izquierdo", "ardor en el pie izquierdo", "dolor en el empeine izquierdo", "pie izquierdo hinchado", "huesos del pie izquierdo duelen"]'),
('M89.079', 'Algoneurodistrofia, tobillo y pie no especificados', 'Sin especificar', '["dolor de pie", "dolor de tobillo", "ardor en el pie", "Sudeck en el pie", "pie hinchado", "dolor al caminar", "molestia ósea en el pie"]'),
('M89.08', 'Algoneurodistrofia, otro sitio', 'Sin especificar', '["dolor óseo en otro sitio", "Sudeck en otras partes", "ardor óseo", "dolor raro en huesos"]'),
('M89.09', 'Algoneurodistrofia, lesiones múltiples', 'Sin especificar', '["dolor generalizado en huesos", "Sudeck múltiple", "varias zonas adoloridas", "ardor en varios huesos", "dolor óseo difuso"]'),
('M89.121', 'Detención epifisaria completa, húmero proximal derecho', 'Sin especificar', '["hueso que no crece", "detención de crecimiento óseo", "brazo corto", "problema de crecimiento en hombro", "falta de desarrollo óseo húmero", "hueso húmero detenido"]'),
('M89.122', 'Detención epifisaria completa, húmero proximal izquierdo', 'Sin especificar', '["hueso que no crece izquierdo", "detención crecimiento hombro", "falta de crecimiento brazo", "hueso húmero izquierdo detenido"]'),
('M89.123', 'Detención epifisaria parcial, húmero proximal derecho', 'Sin especificar', '["crecimiento óseo lento", "hueso húmero derecho con poco crecimiento", "deformidad en brazo derecho", "problema placa crecimiento"]'),
('M89.124', 'Detención epifisaria parcial, húmero proximal izquierdo', 'Sin especificar', '["crecimiento lento brazo izquierdo", "placa de crecimiento cerrada", "hueso húmero izquierdo con poco crecimiento"]'),
('M89.125', 'Detención epifisaria completa, húmero distal derecho', 'Sin especificar', '["codo que no crece bien", "detención crecimiento brazo derecho", "hueso de codo detenido"]'),
('M89.126', 'Detención epifisaria completa, húmero distal izquierdo', 'Sin especificar', '["codo izquierdo que no crece", "detención crecimiento húmero izquierdo", "hueso brazo izquierdo corto"]'),
('M89.127', 'Detención epifisaria parcial, húmero distal derecho', 'Sin especificar', '["desarrollo lento del brazo", "problema codo derecho", "crecimiento parcial húmero distal"]'),
('M89.128', 'Detención epifisaria parcial, húmero distal izquierdo', 'Sin especificar', '["desarrollo lento codo izquierdo", "problema húmero izquierdo", "crecimiento incompleto"]'),
('M89.129', 'Detención epifisaria, húmero, no especificado', 'Sin especificar', '["hueso del brazo no crece", "problema de crecimiento en húmero", "crecimiento detenido en brazo"]'),
('M89.131', 'Detención epifisaria completa, radio distal derecho', 'Sin especificar', '["muñeca que no crece", "detención crecimiento antebrazo", "radio derecho no crece", "hueso corto en brazo"]'),
('M89.132', 'Detención epifisaria completa, radio distal izquierdo', 'Sin especificar', '["muñeca izquierda que no crece", "radio izquierdo no crece", "brazo corto", "detención ósea"]'),
('M89.133', 'Detención epifisaria parcial, radio distal derecho', 'Sin especificar', '["crecimiento lento radio", "muñeca derecha poco desarrollo", "problema de crecimiento antebrazo"]'),
('M89.134', 'Detención epifisaria parcial, radio distal izquierdo', 'Sin especificar', '["crecimiento lento radio izquierdo", "muñeca izquierda poco desarrollo", "problema óseo antebrazo"]'),
('M89.138', 'Otros tipos de detención del crecimiento epifisario, antebrazo', 'Sin especificar', '["antebrazo corto", "hueso antebrazo no desarrolla", "problemas de crecimiento brazo", "detención crecimiento cúbito radio"]'),
('M89.139', 'Detención epifisaria, antebrazo, no especificado', 'Sin especificar', '["hueso antebrazo no crece", "problema desarrollo antebrazo", "detención crecimiento óseo"]'),
('M89.151', 'Detención epifisaria completa, fémur proximal derecho', 'Sin especificar', '["fémur derecho no crece", "pierna más corta", "problema cadera", "falta de crecimiento en fémur"]'),
('M89.152', 'Detención epifisaria completa, fémur proximal izquierdo', 'Sin especificar', '["fémur izquierdo no crece", "pierna izquierda corta", "problema de crecimiento cadera"]'),
('M89.153', 'Detención epifisaria parcial, fémur proximal derecho', 'Sin especificar', '["desarrollo lento fémur", "fémur derecho acortado", "placa de crecimiento cadera"]'),
('M89.154', 'Detención epifisaria parcial, fémur proximal izquierdo', 'Sin especificar', '["desarrollo lento fémur izquierdo", "fémur corto", "crecimiento óseo parcial"]'),
('M89.155', 'Detención epifisaria completa, fémur distal derecho', 'Sin especificar', '["rodilla derecha no crece", "pierna derecha corta", "fémur no crece hasta la rodilla"]'),
('M89.156', 'Detención epifisaria completa, fémur distal izquierdo', 'Sin especificar', '["rodilla izquierda no crece", "pierna izquierda corta", "fémur no desarrolla"]'),
('M89.157', 'Detención epifisaria parcial, fémur distal derecho', 'Sin especificar', '["crecimiento irregular rodilla", "fémur derecho lento", "deformidad rodilla"]'),
('M89.158', 'Detención epifisaria parcial, fémur distal izquierdo', 'Sin especificar', '["crecimiento irregular rodilla izquierda", "fémur izquierdo lento", "desarrollo hueso rodilla"]'),
('M89.159', 'Detención epifisaria, fémur, no especificado', 'Sin especificar', '["fémur que no crece", "pierna corta", "problema crecimiento hueso muslo"]'),
('M89.160', 'Detención epifisaria completa, tibia proximal derecha', 'Sin especificar', '["tibia derecha no crece", "pierna derecha corta", "problema rodilla", "hueso no desarrolla"]'),
('M89.161', 'Detención epifisaria completa, tibia proximal izquierda', 'Sin especificar', '["tibia izquierda no crece", "pierna izquierda corta", "hueso pierna parado"]'),
('M89.162', 'Detención epifisaria parcial, tibia proximal derecha', 'Sin especificar', '["tibia derecha poco crecimiento", "crecimiento irregular tibia", "deformidad pierna derecha"]'),
('M89.163', 'Detención epifisaria parcial, tibia proximal izquierda', 'Sin especificar', '["tibia izquierda poco crecimiento", "crecimiento irregular tibia", "problema óseo pierna"]'),
('M89.164', 'Detención epifisaria completa, tibia distal derecha', 'Sin especificar', '["tobillo derecho no crece", "pierna derecha corta", "hueso tobillo detenido"]'),
('M89.165', 'Detención epifisaria completa, tibia distal izquierda', 'Sin especificar', '["tobillo izquierdo no crece", "pierna izquierda corta", "hueso detenido"]'),
('M89.166', 'Detención epifisaria parcial, tibia distal derecha', 'Sin especificar', '["crecimiento lento tobillo", "tibia derecha deforme", "problema crecimiento óseo"]'),
('M89.167', 'Detención epifisaria parcial, tibia distal izquierda', 'Sin especificar', '["crecimiento lento tobillo izquierdo", "tibia izquierda poco desarrollo", "problema óseo"]'),
('M89.168', 'Otros tipos de detención del crecimiento epifisario, pierna', 'Sin especificar', '["pierna corta", "hueso pierna no desarrolla", "problemas crecimiento extremidades"]'),
('M89.169', 'Detención epifisaria, pierna, no especificada', 'Sin especificar', '["hueso de la pierna no crece", "detención crecimiento pierna", "problema desarrollo óseo"]'),
('M89.18', 'Detención epifisaria, otra localización', 'Sin especificar', '["hueso no crece", "problemas de crecimiento óseo", "detención crecimiento", "hueso detenido"]'),
('M89.20', 'Otros trastornos de desarrollo y crecimiento de hueso, localización no especificada', 'Sin especificar', '["huesos deformes", "problemas óseos de crecimiento", "hueso raro", "crecimiento óseo extraño"]'),
('M89.211', 'Otros trastornos de desarrollo y crecimiento de hueso, hombro derecho', 'Sin especificar', '["hombro derecho deforme", "desarrollo raro hombro", "hueso hombro derecho raro"]'),
('M89.212', 'Otros trastornos de desarrollo y crecimiento de hueso, hombro izquierdo', 'Sin especificar', '["hombro izquierdo deforme", "hueso raro hombro izquierdo", "desarrollo raro hueso"]'),
('M89.219', 'Otros trastornos de desarrollo y crecimiento de hueso, hombro no especificado', 'Sin especificar', '["trastorno hombro", "hueso hombro raro", "desarrollo óseo extraño"]'),
('M89.221', 'Otros trastornos de desarrollo y crecimiento de hueso, húmero derecho', 'Sin especificar', '["húmero derecho raro", "hueso del brazo deforme", "desarrollo húmero anormal"]'),
('M89.222', 'Otros trastornos de desarrollo y crecimiento de hueso, húmero izquierdo', 'Sin especificar', '["húmero izquierdo raro", "desarrollo brazo anormal", "hueso húmero extraño"]'),
('M89.229', 'Otros trastornos de desarrollo y crecimiento de hueso, húmero no especificado', 'Sin especificar', '["problema óseo húmero", "hueso brazo deforme", "húmero raro"]'),
('M89.231', 'Otros trastornos de desarrollo y crecimiento de hueso, cúbito derecho', 'Sin especificar', '["cúbito derecho deforme", "brazo raro", "desarrollo anormal cúbito"]'),
('M89.232', 'Otros trastornos de desarrollo y crecimiento de hueso, cúbito izquierdo', 'Sin especificar', '["cúbito izquierdo deforme", "brazo raro", "desarrollo anormal cúbito izquierdo"]'),
('M89.233', 'Otros trastornos de desarrollo y crecimiento de hueso, radio derecho', 'Sin especificar', '["radio derecho raro", "muñeca deforme", "hueso antebrazo anormal"]'),
('M89.234', 'Otros trastornos de desarrollo y crecimiento de hueso, radio izquierdo', 'Sin especificar', '["radio izquierdo raro", "muñeca deforme", "hueso antebrazo anormal"]'),
('M89.239', 'Otros trastornos de desarrollo y crecimiento de hueso, cúbito y radio no especificados', 'Sin especificar', '["huesos antebrazo raros", "brazo deforme", "desarrollo óseo raro"]'),
('M89.241', 'Otros trastornos de desarrollo y crecimiento de hueso, mano derecha', 'Sin especificar', '["mano derecha deforme", "huesos mano derecha raros", "desarrollo mano anormal"]'),
('M89.242', 'Otros trastornos de desarrollo y crecimiento de hueso, mano izquierda', 'Sin especificar', '["mano izquierda deforme", "huesos mano izquierda raros", "desarrollo mano anormal"]'),
('M89.249', 'Otros trastornos de desarrollo y crecimiento de hueso, mano no especificada', 'Sin especificar', '["huesos mano raros", "mano deforme", "problema desarrollo mano"]'),
('M89.251', 'Otros trastornos de desarrollo y crecimiento de hueso, fémur derecho', 'Sin especificar', '["fémur derecho raro", "fémur deforme", "hueso muslo anormal"]'),
('M89.252', 'Otros trastornos de desarrollo y crecimiento de hueso, fémur izquierdo', 'Sin especificar', '["fémur izquierdo raro", "fémur izquierdo deforme", "hueso muslo raro"]'),
('M89.259', 'Otros trastornos de desarrollo y crecimiento de hueso, fémur no especificado', 'Sin especificar', '["hueso del muslo raro", "fémur deforme", "problema fémur"]'),
('M89.261', 'Otros trastornos de desarrollo y crecimiento de hueso, tibia derecha', 'Sin especificar', '["tibia derecha rara", "tibia derecha deforme", "hueso pierna raro"]'),
('M89.262', 'Otros trastornos de desarrollo y crecimiento de hueso, tibia izquierda', 'Sin especificar', '["tibia izquierda rara", "tibia izquierda deforme", "hueso pierna raro"]'),
('M89.263', 'Otros trastornos de desarrollo y crecimiento de hueso, peroné derecho', 'Sin especificar', '["peroné derecho raro", "hueso pierna raro", "deformidad ósea pierna"]'),
('M89.264', 'Otros trastornos de desarrollo y crecimiento de hueso, peroné izquierdo', 'Sin especificar', '["peroné izquierdo raro", "hueso pierna raro", "deformidad ósea pierna"]'),
('M89.269', 'Otros trastornos de desarrollo y crecimiento de hueso, pierna no especificada', 'Sin especificar', '["huesos pierna raros", "pierna deforme", "desarrollo óseo pierna"]'),
('M89.271', 'Otros trastornos de desarrollo y crecimiento de hueso, tobillo y pie derechos', 'Sin especificar', '["pie derecho deforme", "huesos pie raro", "desarrollo pie anormal"]'),
('M89.272', 'Otros trastornos de desarrollo y crecimiento de hueso, tobillo y pie izquierdos', 'Sin especificar', '["pie izquierdo deforme", "huesos pie izquierdo raro", "desarrollo pie izquierdo"]'),
('M89.279', 'Otros trastornos de desarrollo y crecimiento de hueso, tobillo y pie no especificados', 'Sin especificar', '["huesos pie raros", "pie deforme", "problema óseo pie"]'),
('M89.28', 'Otros trastornos de desarrollo y crecimiento de hueso, otra localización', 'Sin especificar', '["hueso raro", "problema óseo crecimiento", "deformidad ósea"]'),
('M89.29', 'Otros trastornos de desarrollo y crecimiento de hueso, localizaciones múltiples', 'Sin especificar', '["huesos deformes", "problemas desarrollo óseo general", "huesos raros en varias partes"]'),
('M89.30', 'Hipertrofia de hueso, localización no especificada', 'Sin especificar', '["hueso muy grande", "hueso crecido", "hipertrofia ósea", "hueso grueso", "aumento de tamaño hueso"]'),
('M89.311', 'Hipertrofia de hueso, hombro derecho', 'Sin especificar', '["hueso hombro derecho grande", "hombro derecho abultado", "hipertrofia ósea hombro"]'),
('M89.312', 'Hipertrofia de hueso, hombro izquierdo', 'Sin especificar', '["hueso hombro izquierdo grande", "hombro izquierdo abultado", "hipertrofia ósea hombro"]'),
('M89.319', 'Hipertrofia de hueso, hombro no especificado', 'Sin especificar', '["hueso hombro grande", "hombro abultado", "crecimiento anormal hueso"]'),
('M89.321', 'Hipertrofia de hueso, húmero derecho', 'Sin especificar', '["húmero derecho grande", "hueso brazo grueso", "crecimiento óseo húmero"]'),
('M89.322', 'Hipertrofia de hueso, húmero izquierdo', 'Sin especificar', '["húmero izquierdo grande", "hueso brazo grueso", "hipertrofia hueso húmero"]'),
('M89.329', 'Hipertrofia de hueso, húmero no especificado', 'Sin especificar', '["hueso húmero crecido", "brazo grueso", "hipertrofia ósea"]'),
('M89.331', 'Hipertrofia de hueso, cúbito derecho', 'Sin especificar', '["cúbito derecho grande", "hueso antebrazo grueso", "hipertrofia ósea"]'),
('M89.332', 'Hipertrofia de hueso, cúbito izquierdo', 'Sin especificar', '["cúbito izquierdo grande", "hueso antebrazo grueso", "hipertrofia ósea"]'),
('M89.333', 'Hipertrofia de hueso, radio derecho', 'Sin especificar', '["radio derecho grande", "hueso antebrazo abultado", "hipertrofia ósea"]'),
('M89.334', 'Hipertrofia de hueso, radio izquierdo', 'Sin especificar', '["radio izquierdo grande", "hueso antebrazo abultado", "hipertrofia ósea"]'),
('M89.339', 'Hipertrofia de hueso, cúbito y radio no especificado', 'Sin especificar', '["huesos antebrazo grandes", "antebrazo grueso", "hipertrofia ósea"]'),
('M89.341', 'Hipertrofia de hueso, mano derecha', 'Sin especificar', '["huesos mano derecha grandes", "mano derecha abultada", "hipertrofia ósea mano"]'),
('M89.342', 'Hipertrofia de hueso, mano izquierda', 'Sin especificar', '["huesos mano izquierda grandes", "mano izquierda abultada", "hipertrofia ósea mano"]'),
('M89.349', 'Hipertrofia de hueso, mano no especificada', 'Sin especificar', '["huesos mano grandes", "mano abultada", "hipertrofia ósea"]'),
('M89.351', 'Hipertrofia de hueso, fémur derecho', 'Sin especificar', '["fémur derecho grande", "hueso muslo grueso", "hipertrofia fémur"]'),
('M89.352', 'Hipertrofia de hueso, fémur izquierdo', 'Sin especificar', '["fémur izquierdo grande", "hueso muslo grueso", "hipertrofia fémur"]'),
('M89.359', 'Hipertrofia de hueso, fémur no especificado', 'Sin especificar', '["hueso muslo grande", "fémur grueso", "hipertrofia ósea"]'),
('M89.361', 'Hipertrofia de hueso, tibia derecha', 'Sin especificar', '["tibia derecha grande", "hueso pierna grueso", "hipertrofia tibia"]'),
('M89.362', 'Hipertrofia de hueso, tibia izquierda', 'Sin especificar', '["tibia izquierda grande", "hueso pierna grueso", "hipertrofia tibia"]'),
('M89.363', 'Hipertrofia de hueso, peroné derecho', 'Sin especificar', '["peroné derecho grande", "hueso pierna grueso", "hipertrofia peroné"]'),
('M89.364', 'Hipertrofia de hueso, peroné izquierdo', 'Sin especificar', '["peroné izquierdo grande", "hueso pierna grueso", "hipertrofia peroné"]'),
('M89.369', 'Hipertrofia de hueso, tibia y peroné no especificados', 'Sin especificar', '["huesos pierna grandes", "pierna gruesa", "hipertrofia ósea"]'),
('M89.371', 'Hipertrofia de hueso, tobillo y pie derechos', 'Sin especificar', '["huesos pie derecho grandes", "pie derecho grande", "hipertrofia ósea pie"]'),
('M89.372', 'Hipertrofia de hueso, tobillo y pie izquierdos', 'Sin especificar', '["huesos pie izquierdo grandes", "pie izquierdo grande", "hipertrofia ósea pie"]'),
('M89.379', 'Hipertrofia de hueso, tobillo y pie no especificados', 'Sin especificar', '["huesos pie grandes", "pie grande", "hipertrofia ósea"]'),
('M89.38', 'Hipertrofia de hueso, otra localización', 'Sin especificar', '["hueso grande", "hueso crecido", "hipertrofia ósea"]'),
('M89.39', 'Hipertrofia de hueso, localizaciones múltiples', 'Sin especificar', '["huesos grandes", "crecimiento óseo múltiple", "hipertrofia ósea generalizada"]'),
('M89.40', 'Otra osteoartropatía hipertrófica, localización no especificada', 'Sin especificar', '["problema óseo y articular", "crecimiento óseo anormal", "osteoartropatía", "inflamación articular y ósea"]'),
('M89.411', 'Otra osteoartropatía hipertrófica, hombro derecho', 'Sin especificar', '["hombro derecho adolorido", "osteoartropatía hombro", "hombro grueso y doloroso"]'),
('M89.412', 'Otra osteoartropatía hipertrófica, hombro izquierdo', 'Sin especificar', '["hombro izquierdo adolorido", "osteoartropatía hombro", "hombro grueso y doloroso"]'),
('M89.419', 'Otra osteoartropatía hipertrófica, hombro no especificado', 'Sin especificar', '["problema hombro", "osteoartropatía hombro", "hombro grande"]'),
('M89.421', 'Otra osteoartropatía hipertrófica, brazo derecho', 'Sin especificar', '["brazo derecho adolorido", "osteoartropatía brazo", "brazo grueso"]'),
('M89.422', 'Otra osteoartropatía hipertrófica, brazo izquierdo', 'Sin especificar', '["brazo izquierdo adolorido", "osteoartropatía brazo", "brazo grueso"]'),
('M89.429', 'Otra osteoartropatía hipertrófica, brazo no especificado', 'Sin especificar', '["problema brazo", "osteoartropatía brazo", "huesos brazo grandes"]'),
('M89.431', 'Otra osteoartropatía hipertrófica, antebrazo derecho', 'Sin especificar', '["antebrazo derecho adolorido", "osteoartropatía antebrazo", "antebrazo grueso"]'),
('M89.432', 'Otra osteoartropatía hipertrófica, antebrazo izquierdo', 'Sin especificar', '["antebrazo izquierdo adolorido", "osteoartropatía antebrazo", "antebrazo grueso"]'),
('M89.439', 'Otra osteoartropatía hipertrófica, antebrazo no especificado', 'Sin especificar', '["problema antebrazo", "osteoartropatía antebrazo"]'),
('M89.441', 'Otra osteoartropatía hipertrófica, mano derecha', 'Sin especificar', '["mano derecha adolorida", "osteoartropatía mano", "dedos gruesos"]'),
('M89.442', 'Otra osteoartropatía hipertrófica, mano izquierda', 'Sin especificar', '["mano izquierda adolorida", "osteoartropatía mano", "dedos gruesos"]'),
('M89.449', 'Otra osteoartropatía hipertrófica, mano no especificada', 'Sin especificar', '["problema mano", "osteoartropatía mano", "dedos hinchados"]'),
('M89.451', 'Otra osteoartropatía hipertrófica, muslo derecho', 'Sin especificar', '["muslo derecho adolorido", "osteoartropatía muslo", "muslo grande"]'),
('M89.452', 'Otra osteoartropatía hipertrófica, muslo izquierdo', 'Sin especificar', '["muslo izquierdo adolorido", "osteoartropatía muslo", "muslo grande"]'),
('M89.459', 'Otra osteoartropatía hipertrófica, muslo, no especificado', 'Sin especificar', '["problema muslo", "osteoartropatía muslo"]'),
('M89.461', 'Otra osteoartropatía hipertrófica, pierna derecha', 'Sin especificar', '["pierna derecha adolorida", "osteoartropatía pierna", "pierna grande"]'),
('M89.462', 'Otra osteoartropatía hipertrófica, pierna izquierda', 'Sin especificar', '["pierna izquierda adolorida", "osteoartropatía pierna", "pierna grande"]'),
('M89.469', 'Otra osteoartropatía hipertrófica, pierna no especificada', 'Sin especificar', '["problema pierna", "osteoartropatía pierna"]'),
('M89.471', 'Otra osteoartropatía hipertrófica, tobillo y pie derechos', 'Sin especificar', '["pie derecho adolorido", "osteoartropatía pie", "pie grande"]'),
('M89.472', 'Otra osteoartropatía hipertrófica, tobillo y pie izquierdos', 'Sin especificar', '["pie izquierdo adolorido", "osteoartropatía pie", "pie grande"]'),
('M89.479', 'Otra osteoartropatía hipertrófica, tobillo y pie no especificados', 'Sin especificar', '["problema pie", "osteoartropatía pie"]'),
('M89.48', 'Otra osteoartropatía hipertrófica, otra localización', 'Sin especificar', '["problema óseo articular", "osteoartropatía"]'),
('M89.49', 'Otra osteoartropatía hipertrófica, localizaciones múltiples', 'Sin especificar', '["osteoartropatía generalizada", "problemas en varios huesos y articulaciones"]'),
('M89.50', 'Osteolisis, localización no especificada', 'Sin especificar', '["desgaste óseo", "hueso que se deshace", "pérdida de hueso", "osteolisis", "hueso débil"]'),
('M89.511', 'Osteolisis, hombro derecho', 'Sin especificar', '["desgaste hueso hombro derecho", "hueso hombro derecho se debilita"]'),
('M89.512', 'Osteolisis, hombro izquierdo', 'Sin especificar', '["desgaste hueso hombro izquierdo", "hueso hombro izquierdo se debilita"]'),
('M89.519', 'Osteolisis, hombro no especificado', 'Sin especificar', '["desgaste óseo hombro", "pérdida de hueso hombro"]'),
('M89.521', 'Osteolisis, brazo derecho', 'Sin especificar', '["desgaste hueso brazo derecho", "brazo débil", "osteolisis brazo"]'),
('M89.522', 'Osteolisis, brazo izquierdo', 'Sin especificar', '["desgaste hueso brazo izquierdo", "brazo débil", "osteolisis brazo"]'),
('M89.529', 'Osteolisis, brazo no especificado', 'Sin especificar', '["desgaste óseo brazo", "pérdida de hueso brazo"]'),
('M89.531', 'Osteolisis, antebrazo derecho', 'Sin especificar', '["desgaste hueso antebrazo derecho", "osteolisis antebrazo"]'),
('M89.532', 'Osteolisis, antebrazo izquierdo', 'Sin especificar', '["desgaste hueso antebrazo izquierdo", "osteolisis antebrazo"]'),
('M89.539', 'Osteolisis, antebrazo no especificado', 'Sin especificar', '["desgaste hueso antebrazo", "pérdida de hueso antebrazo"]'),
('M89.541', 'Osteolisis, mano derecha', 'Sin especificar', '["desgaste huesos mano derecha", "huesos mano derecha debilitados"]'),
('M89.542', 'Osteolisis, mano izquierda', 'Sin especificar', '["desgaste huesos mano izquierda", "huesos mano izquierda debilitados"]'),
('M89.549', 'Osteolisis, mano no especificada', 'Sin especificar', '["desgaste huesos mano", "pérdida de hueso mano"]'),
('M89.551', 'Osteolisis, muslo derecho', 'Sin especificar', '["desgaste hueso muslo derecho", "osteolisis fémur"]'),
('M89.552', 'Osteolisis, muslo izquierdo', 'Sin especificar', '["desgaste hueso muslo izquierdo", "osteolisis fémur"]'),
('M89.559', 'Osteolisis, muslo no especificado', 'Sin especificar', '["desgaste hueso muslo", "pérdida de hueso muslo"]'),
('M89.561', 'Osteolisis, pierna derecha', 'Sin especificar', '["desgaste hueso pierna derecha", "osteolisis pierna"]'),
('M89.562', 'Osteolisis, pierna izquierda', 'Sin especificar', '["desgaste hueso pierna izquierda", "osteolisis pierna"]'),
('M89.569', 'Osteolisis, pierna no especificada', 'Sin especificar', '["desgaste hueso pierna", "pérdida de hueso pierna"]'),
('M89.571', 'Osteolisis, tobillo y pie derechos', 'Sin especificar', '["desgaste huesos pie derecho", "osteolisis pie derecho"]'),
('M89.572', 'Osteolisis, tobillo y pie izquierdos', 'Sin especificar', '["desgaste huesos pie izquierdo", "osteolisis pie izquierdo"]'),
('M89.579', 'Osteolisis, tobillo y pie no especificados', 'Sin especificar', '["desgaste huesos pie", "pérdida de hueso pie"]'),
('M89.58', 'Osteolisis, otra localización', 'Sin especificar', '["desgaste óseo", "pérdida de hueso"]'),
('M89.59', 'Osteolisis, localizaciones múltiples', 'Sin especificar', '["desgaste de varios huesos", "pérdida de hueso generalizada"]'),
('M89.60', 'Osteopatía tras poliomielitis, localización no especificada', 'Sin especificar', '["hueso débil post polio", "osteopatía polio", "problema hueso después de polio"]'),
('M89.611', 'Osteopatía tras poliomielitis, hombro derecho', 'Sin especificar', '["osteopatía post polio hombro", "hueso hombro derecho débil por polio"]'),
('M89.612', 'Osteopatía tras poliomielitis, hombro izquierdo', 'Sin especificar', '["osteopatía post polio hombro", "hueso hombro izquierdo débil por polio"]'),
('M89.619', 'Osteopatía tras poliomielitis, hombro no especificado', 'Sin especificar', '["osteopatía polio hombro", "hueso débil hombro"]'),
('M89.621', 'Osteopatía tras poliomielitis, brazo derecho', 'Sin especificar', '["osteopatía polio brazo", "brazo débil por polio"]'),
('M89.622', 'Osteopatía tras poliomielitis, brazo izquierdo', 'Sin especificar', '["osteopatía polio brazo", "brazo débil por polio"]'),
('M89.629', 'Osteopatía tras poliomielitis, brazo no especificado', 'Sin especificar', '["osteopatía polio brazo", "brazo débil"]'),
('M89.631', 'Osteopatía tras poliomielitis, antebrazo derecho', 'Sin especificar', '["osteopatía polio antebrazo", "antebrazo débil por polio"]'),
('M89.632', 'Osteopatía tras poliomielitis, antebrazo izquierdo', 'Sin especificar', '["osteopatía polio antebrazo", "antebrazo débil por polio"]'),
('M89.639', 'Osteopatía tras poliomielitis, antebrazo no especificado', 'Sin especificar', '["osteopatía polio antebrazo", "antebrazo débil"]'),
('M89.641', 'Osteopatía tras poliomielitis, mano derecha', 'Sin especificar', '["osteopatía polio mano", "mano débil por polio"]'),
('M89.642', 'Osteopatía tras poliomielitis, mano izquierda', 'Sin especificar', '["osteopatía polio mano", "mano débil por polio"]'),
('M89.649', 'Osteopatía tras poliomielitis, mano no especificada', 'Sin especificar', '["osteopatía polio mano", "mano débil"]'),
('M89.651', 'Osteopatía tras poliomielitis, muslo derecho', 'Sin especificar', '["osteopatía polio muslo", "pierna débil por polio"]'),
('M89.652', 'Osteopatía tras poliomielitis, muslo izquierdo', 'Sin especificar', '["osteopatía polio muslo", "pierna débil por polio"]'),
('M89.659', 'Osteopatía tras poliomielitis, muslo no especificado', 'Sin especificar', '["osteopatía polio muslo", "pierna débil"]'),
('M89.661', 'Osteopatía tras poliomielitis, pierna derecha', 'Sin especificar', '["osteopatía polio pierna", "pierna débil por polio"]'),
('M89.662', 'Osteopatía tras poliomielitis, pierna izquierda', 'Sin especificar', '["osteopatía polio pierna", "pierna débil por polio"]'),
('M89.669', 'Osteopatía tras poliomielitis, pierna no especificada', 'Sin especificar', '["osteopatía polio pierna", "pierna débil"]'),
('M89.671', 'Osteopatía tras poliomielitis, tobillo y pie derechos', 'Sin especificar', '["osteopatía polio pie", "pie débil por polio"]'),
('M89.672', 'Osteopatía tras poliomielitis, tobillo y pie izquierdos', 'Sin especificar', '["osteopatía polio pie", "pie débil por polio"]'),
('M89.679', 'Osteopatía tras poliomielitis, tobillo y pie no especificados', 'Sin especificar', '["osteopatía polio pie", "pie débil"]'),
('M89.68', 'Osteopatía tras poliomielitis, otra localización', 'Sin especificar', '["osteopatía post polio", "hueso débil"]'),
('M89.69', 'Osteopatía tras poliomielitis, localizaciones múltiples', 'Sin especificar', '["osteopatía polio múltiple", "huesos débiles post polio"]'),
('M89.70', 'Defecto óseo mayor, localización no especificada', 'Sin especificar', '["hueso con hueco", "defecto óseo", "falta de hueso", "hueso dañado", "hueso roto"]'),
('M89.711', 'Defecto óseo mayor, región del hombro, lado derecho', 'Sin especificar', '["defecto hueso hombro derecho", "hueso dañado hombro derecho"]'),
('M89.712', 'Defecto óseo mayor, región del hombro, lado izquierdo', 'Sin especificar', '["defecto hueso hombro izquierdo", "hueso dañado hombro izquierdo"]'),
('M89.719', 'Defecto óseo mayor, región del hombro, lado no especificado', 'Sin especificar', '["defecto hueso hombro", "daño en hueso hombro"]'),
('M89.721', 'Defecto óseo mayor, húmero derecho', 'Sin especificar', '["defecto húmero derecho", "hueso húmero roto"]'),
('M89.722', 'Defecto óseo mayor, húmero izquierdo', 'Sin especificar', '["defecto húmero izquierdo", "hueso húmero roto"]'),
('M89.729', 'Defecto óseo mayor, húmero no especificado', 'Sin especificar', '["defecto húmero", "daño hueso brazo"]'),
('M89.731', 'Defecto óseo mayor, antebrazo derecho', 'Sin especificar', '["defecto antebrazo derecho", "hueso antebrazo roto"]'),
('M89.732', 'Defecto óseo mayor, antebrazo izquierdo', 'Sin especificar', '["defecto antebrazo izquierdo", "hueso antebrazo roto"]'),
('M89.739', 'Defecto óseo mayor, antebrazo no especificado', 'Sin especificar', '["defecto antebrazo", "daño hueso antebrazo"]'),
('M89.741', 'Defecto óseo mayor, mano derecha', 'Sin especificar', '["defecto hueso mano derecha", "huesos mano derecha dañados"]'),
('M89.742', 'Defecto óseo mayor, mano izquierda', 'Sin especificar', '["defecto hueso mano izquierda", "huesos mano izquierda dañados"]'),
('M89.749', 'Defecto óseo mayor, mano no especificada', 'Sin especificar', '["defecto mano", "daño huesos mano"]'),
('M89.751', 'Defecto óseo mayor, región pélvica y muslo derechos', 'Sin especificar', '["defecto fémur derecho", "daño hueso pelvis"]'),
('M89.752', 'Defecto óseo mayor, región pélvica y muslo izquierdos', 'Sin especificar', '["defecto fémur izquierdo", "daño hueso pelvis"]'),
('M89.759', 'Defecto óseo mayor, región pélvica y muslo no especificados', 'Sin especificar', '["defecto fémur", "daño hueso muslo"]'),
('M89.761', 'Defecto óseo mayor, pierna derecha', 'Sin especificar', '["defecto hueso pierna derecha", "daño pierna"]'),
('M89.762', 'Defecto óseo mayor, pierna izquierda', 'Sin especificar', '["defecto hueso pierna izquierda", "daño pierna"]'),
('M89.769', 'Defecto óseo mayor, pierna no especificada', 'Sin especificar', '["defecto hueso pierna", "daño pierna"]'),
('M89.771', 'Defecto óseo mayor, tobillo y pie derechos', 'Sin especificar', '["defecto hueso pie derecho", "hueso pie roto"]'),
('M89.772', 'Defecto óseo mayor, tobillo y pie izquierdos', 'Sin especificar', '["defecto hueso pie izquierdo", "hueso pie roto"]'),
('M89.779', 'Defecto óseo mayor, tobillo y pie no especificados', 'Sin especificar', '["defecto hueso pie", "daño pie"]'),
('M89.78', 'Defecto óseo mayor, otra localización', 'Sin especificar', '["defecto hueso", "hueso con daño"]'),
('M89.79', 'Defecto óseo mayor, localizaciones múltiples', 'Sin especificar', '["defectos óseos múltiples", "huesos dañados"]'),
('M89.8X0', 'Otros trastornos de hueso especificados, localizaciones múltiples', 'Sin especificar', '["problemas óseos varios", "enfermedad hueso generalizada"]'),
('M89.8X1', 'Otros trastornos de hueso especificados, hombro', 'Sin especificar', '["problema óseo hombro", "enfermedad hueso hombro"]'),
('M89.8X2', 'Otros trastornos de hueso especificados, brazo', 'Sin especificar', '["problema óseo brazo", "enfermedad hueso brazo"]'),
('M89.8X3', 'Otros trastornos de hueso especificados, antebrazo', 'Sin especificar', '["problema óseo antebrazo", "enfermedad hueso antebrazo"]'),
('M89.8X4', 'Otros trastornos de hueso especificados, mano', 'Sin especificar', '["problema óseo mano", "enfermedad hueso mano"]'),
('M89.8X5', 'Otros trastornos de hueso especificados, muslo', 'Sin especificar', '["problema óseo muslo", "enfermedad hueso muslo"]'),
('M89.8X6', 'Otros trastornos de hueso especificados, pierna', 'Sin especificar', '["problema óseo pierna", "enfermedad hueso pierna"]'),
('M89.8X7', 'Otros trastornos de hueso especificados, tobillo y pie', 'Sin especificar', '["problema óseo pie", "enfermedad hueso pie"]'),
('M89.8X8', 'Otros trastornos de hueso especificados, otra localización', 'Sin especificar', '["trastorno óseo", "enfermedad ósea"]'),
('M89.8X9', 'Otros trastornos de hueso especificados, localización no especificada', 'Sin especificar', '["problema óseo raro", "enfermedad ósea no identificada"]'),
('M89.9', 'Trastorno del hueso no especificado', 'Sin especificar', '["dolor de huesos", "enfermedad de los huesos", "huesos enfermos", "problema en los huesos", "molestia ósea", "hueso que duele", "trastorno óseo", "dolor general en huesos", "no sé qué tengo en los huesos"]');
