INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K65.0', 'Peritonitis (aguda) generalizada', 'Sin especificar', '["dolor abdominal severo", "panza dura", "vientre rígido", "abdomen en tabla", "infección del peritoneo", "barriga hinchada", "guata inflamada", "dolor de guata agudo", "peritonitis aguda", "pus en el abdomen", "inflamación de la cavidad abdominal", "dolor insoportable en la panza", "abdomen agudo", "fiebre y dolor abdominal", "vientre duro como piedra"]'),
('K65.1', 'Absceso peritoneal', 'Sin especificar', '["bolsa de pus", "infección abdominal localizada", "absceso en la panza", "colección de pus", "infección interna", "absceso intraabdominal", "tumor infectado", "masa dolorosa en el vientre", "fiebre por infección interna", "dolor punzante abdominal", "absceso en el abdomen", "infección después de cirugía", "flemón abdominal", "bulto infectado en la guata", "infección focal abdominal"]'),
('K65.2', 'Peritonitis bacteriana espontánea', 'Sin especificar', '["infección abdominal sin causa", "peritonitis en cirróticos", "infección de líquido ascítico", "líquido infectado en la panza", "ascitis infectada", "dolor abdominal por cirrosis", "infección espontánea", "peritonitis primaria", "fiebre en pacientes con cirrosis", "dolor de guata repentino", "infección bacteriana en la barriga", "sepsis abdominal", "inflamación del peritoneo por bacterias", "dolor difuso abdominal", "peritonitis bacteriana"]'),
('K65.3', 'Coleperitonitis', 'Sin especificar', '["bilis en el abdomen", "peritonitis biliar", "fuga de bilis", "derrame biliar", "abdomen irritado por bilis", "dolor abdominal por vesícula", "inflamación peritoneal biliar", "secreción biliar en el vientre", "peritonitis química", "dolor intenso en la parte superior de la panza", "bilis en la cavidad abdominal", "complicación de vesícula", "dolor de guata por bilis", "inflamación por fuga biliar", "abdomen agudo biliar"]'),
('K65.4', 'Mesenteritis esclerosante', 'Sin especificar', '["mesenteritis retráctil", "inflamación del mesenterio", "panza dura crónica", "fibrosis abdominal", "dolor de barriga crónico", "mesenteritis crónica", "inflamación de la grasa abdominal", "endurecimiento del tejido abdominal", "dolor abdominal persistente", "mesenteritis esclerosante idiopática", "engrosamiento abdominal", "problemas en las tripas", "dolor intestinal crónico", "panza inflamada y dura", "enfermedad del mesenterio"]'),
('K65.8', 'Otras peritonitis', 'Sin especificar', '["infección peritoneal rara", "peritonitis secundaria", "peritonitis crónica", "dolor abdominal persistente", "irritación del revestimiento abdominal", "infección abdominal inusual", "dolor en la cavidad peritoneal", "problemas de peritoneo", "inflamación de las membranas abdominales", "dolor agudo de panza", "peritonitis no especificada", "afección de la membrana abdominal", "dolor de barriga severo", "infección de la guata", "complicación abdominal"]'),
('K65.9', 'Peritonitis, no especificada', 'Sin especificar', '["dolor abdominal fuerte", "inflamación del abdomen", "peritonitis", "dolor de panza intenso", "vientre muy adolorido", "infección en la barriga", "dolor de guata severo", "panza inflamada", "ataque de dolor abdominal", "abdomen agudo", "dolor abdominal generalizado", "infección en las tripas", "dolor en la cavidad del estómago", "fiebre y dolor de barriga", "abdomen en tabla"]');
