INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q60.0', 'Agenesia renal unilateral', 'Sin especificar', '["falta de un riñón", "nacer con un solo riñón", "riñón único", "riñón solitario", "agenesia de riñón", "riñón que no se formó", "mono riñón", "problemas en riñones al nacer", "malformación renal", "ausencia de riñón", "riñón de nacimiento", "falla renal congénita", "un solo riñón funcionando", "anomalía renal", "riñón ausente"]'),
('Q60.1', 'Agenesia renal bilateral', 'Sin especificar', '["nacer sin riñones", "ausencia de ambos riñones", "falla total de riñones de nacimiento", "sin riñones desde que nací", "agenesia renal grave", "ausencia bilateral de riñones", "riñones que no se desarrollaron", "malformación congénita grave", "anomalía de riñones", "problema de riñones al nacer", "sin forma de orinar desde bebé", "ausencia de órganos renales", "desarrollo renal inexistente", "insuficiencia renal neonatal"]'),
('Q60.2', 'Agenesia renal no especificada', 'Sin especificar', '["problemas con la formación de riñones", "riñón que no se desarrolló", "malformación de nacimiento en riñón", "defectos congénitos renales", "anomalía al nacer riñón", "desarrollo incompleto riñón", "problema urinario de nacimiento", "riñones mal formados", "enfermedad renal congénita", "ausencia renal", "desconocimiento de formación renal", "riñones inmaduros al nacer"]'),
('Q60.3', 'Hipoplasia renal unilateral', 'Sin especificar', '["riñón pequeño de nacimiento", "riñón poco desarrollado", "un riñón más chiquito que el otro", "desarrollo insuficiente de un riñón", "hipoplasia de riñón", "riñón que no creció", "riñón enano", "riñón chiquitito", "problema renal unilateral", "riñón poco funcional desde el nacimiento", "anomalía de tamaño renal", "riñón subdesarrollado", "insuficiencia renal de un lado", "riñón pequeño congénito"]'),
('Q60.4', 'Hipoplasia renal bilateral', 'Sin especificar', '["ambos riñones pequeños", "riñones que no crecieron", "falta de desarrollo de riñones", "insuficiencia renal congénita", "riñones chiquitos", "problemas de riñones pequeños al nacer", "riñones subdesarrollados", "riñones enanos", "desarrollo incompleto renal", "riñones poco funcionales", "anomalía renal doble", "riñones pequeños en recién nacido", "fallo de crecimiento renal"]'),
('Q60.5', 'Hipoplasia renal no especificada', 'Sin especificar', '["riñón con tamaño anormal", "problemas de crecimiento renal", "riñón pequeño no diagnosticado", "anomalía en tamaño de riñón", "malformación en riñones", "riñón que no terminó de formarse", "defecto renal", "insuficiencia por tamaño renal", "problemas renales congénitos", "riñón inmaduro", "crecimiento renal deficiente", "anomalía en riñones al nacer"]'),
('Q60.6', 'Síndrome de Potter', 'Sin especificar', '["síndrome de Potter", "secuencia de Potter", "falta de líquido amniótico por riñones", "problemas de riñones y pulmones al nacer", "anomalía renal severa", "caras de Potter", "deformidades por falta de riñones", "ausencia de riñones y deformidad facial", "problemas respiratorios al nacer por riñones", "síndrome de falta de líquido", "falla renal neonatal", "malformación congénita múltiple", "problemas en el bebé al nacer", "defectos por agenesia renal"]');
