INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J68.0', 'Bronquitis y neumonitis por productos químicos, gases, humos y vapores', 'Sin especificar', '["bronquitis química", "inflamación pulmonar por gases", "tos por humo", "pulmones irritados", "intoxicación por inhalación", "bronquios cerrados", "pecho apretado", "neumonitis tóxica", "inhalé químicos", "ahogo por vapor", "falta de aire", "tos seca por humos", "irritación bronquial", "daño pulmonar por químicos", "respiré gases tóxicos", "pulmón inflamado"]'),
('J68.1', 'Edema pulmonar debido a productos químicos, gases, humos y vapores', 'Sin especificar', '["agua en los pulmones", "líquido en el pulmón", "edema pulmonar tóxico", "ahogo severo", "pulmón encharcado", "no puedo respirar", "asfixia por gases", "edema por químicos", "se me llenaron los pulmones de líquido", "insuficiencia respiratoria por humos", "pecho pesado", "silbido al respirar", "fatiga respiratoria", "urgencia respiratoria", "pulmones congestionados"]'),
('J68.2', 'Inflamación del tracto respiratorio superior debida a productos químicos, gases, humos, y vapores, no clasificados bajo otro concepto', 'Sin especificar', '["irritación de garganta", "nariz quemada", "garganta irritada por gases", "inflamación de vías aéreas altas", "picazón en la garganta", "nariz tapada por químicos", "faringitis química", "ronquera por humo", "quemazón en la nariz", "laringitis por vapores", "dolor al tragar", "tracto respiratorio irritado", "nariz roja y picante", "molestia en vías superiores", "tos por irritación"]'),
('J68.3', 'Otras afecciones respiratorias agudas y subagudas, debidas a productos químicos, gases, humos y vapores', 'Sin especificar', '["problemas respiratorios por gases", "ataque respiratorio agudo", "reacción alérgica a gases", "broncoespasmo químico", "crisis respiratoria", "malestar en el pecho", "tos repentina", "dificultad para respirar", "espasmos en el pulmón", "infección pulmonar por tóxicos", "inflamación súbita", "aire contaminado", "bronquios contraídos", "problemas para inhalar"]'),
('J68.4', 'Afecciones respiratorias crónicas debidas a productos químicos, gases, humos y vapores', 'Sin especificar', '["daño pulmonar crónico", "EPOC por químicos", "fibrosis pulmonar por trabajo", "tos crónica por humos", "pulmones dañados por gases", "enfermedad de los pulmones por vapores", "problemas respiratorios de larga duración", "tos constante", "falta de aliento crónica", "bronquitis crónica profesional", "pecho débil", "secuelas de inhalación", "pulmones gastados", "tos del trabajador"]'),
('J68.8', 'Otras afecciones respiratorias debidas a productos químicos, gases, humos y vapores', 'Sin especificar', '["molestias pulmonares por químicos", "enfermedad respiratoria por tóxicos", "daño en las vías respiratorias", "dolor en los pulmones", "afectación por humos industriales", "sensibilidad a químicos", "inflamación bronquial por vapores", "problemas en el pecho", "respiración molesta", "secuelas de gases", "tos persistente por químicos", "irritación persistente"]'),
('J68.9', 'Afección respiratoria no especificada debida a productos químicos, gases, humos y vapores', 'Sin especificar', '["problema en los pulmones por químicos", "raro aliento", "no puedo respirar bien", "malo del pecho por humos", "síntomas pulmonares extraños", "malestar al respirar por gases", "algo raro en el pulmón", "intoxicación respiratoria", "sospecha de daño por químicos", "problema respiratorio sin diagnosticar", "ahogo inexplicable", "pecho raro", "tos por causa desconocida", "inhalé algo y me siento mal"]');
