INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J70.0', 'Manifestaciones pulmonares agudas debidas a radiación', 'Sin especificar', '["neumonitis por radiación", "daño pulmonar por radioterapia", "quemadura de pulmón", "inflamación pulmonar aguda", "pulmón radiado", "pecho irritado por radiación", "tos seca tras radiación", "dificultad para respirar por radiación", "toxicidad pulmonar aguda", "edema pulmonar por radiación", "daño radiactivo en pulmones", "pulmones quemados por rayos", "ahogo repentino por radioterapia"]'),
('J70.1', 'Manifestaciones pulmonares crónicas y de otros tipos debidas a radiación', 'Sin especificar', '["fibrosis pulmonar por radiación", "cicatrices en el pulmón por radioterapia", "daño pulmonar crónico", "pulmón duro por radiación", "dureza en el pulmón", "falta de aire crónica", "tos persistente por radiación", "daño tardío por radioterapia", "insuficiencia respiratoria por radiación", "fibrosis posradiación", "pulmón encogido", "dificultad respiratoria prolongada", "cambios pulmonares crónicos"]'),
('J70.2', 'Enfermedades pulmonares intersticiales agudas inducidas por fármacos', 'Sin especificar', '["neumonitis medicamentosa", "daño pulmonar por pastillas", "inflamación de pulmón por medicina", "reacción pulmonar a fármacos", "pulmón irritado por medicamentos", "tos por fármacos", "toxicidad pulmonar aguda", "daño intersticial rápido", "ahogo por fármacos", "reacción adversa respiratoria", "pulmón inflamado por drogas", "edema por fármacos"]'),
('J70.3', 'Enfermedades pulmonares intersticiales crónicas inducidas por fármacos', 'Sin especificar', '["fibrosis pulmonar por medicamentos", "cicatriz pulmonar por fármacos", "daño pulmonar crónico por pastillas", "pulmón endurecido por medicación", "tos crónica por fármacos", "enfermedad intersticial crónica", "daño pulmonar de largo plazo", "toxicidad pulmonar crónica", "pulmón rígido", "falta de aire persistente", "cambios fibróticos pulmonares", "pulmón cicatrizado por químicos"]'),
('J70.4', 'Enfermedades pulmonares intersticiales no especificadas inducidas por fármacos', 'Sin especificar', '["problemas pulmonares por fármacos", "daño en el tejido pulmonar", "reacción respiratoria a medicamentos", "pulmón afectado por pastillas", "tos por efecto secundario", "enfermedad pulmonar no especificada", "indefinido pulmonar por fármacos", "dolor de pecho por medicina", "fatiga respiratoria por fármacos", "problemas en los pulmones por drogas", "daño intersticial por fármacos", "afección pulmonar rara por medicamentos"]'),
('J70.5', 'Enfermedades respiratorias debidas a inhalación de humo', 'Sin especificar', '["inhalación de humo", "pulmones quemados por fuego", "aspirar humo", "ahogarse con humo", "daño pulmonar por incendio", "intoxicación por humo", "pulmones negros", "tos con hollín", "asma por humo", "quemaduras en la vía aérea", "irritación pulmonar por humareda", "dificultad al respirar por humo", "traqueítis por humo", "bronquitis química"]'),
('J70.8', 'Enfermedades respiratorias debidas a otros agentes externos especificados', 'Sin especificar', '["daño pulmonar por químicos", "inhalación de gases tóxicos", "pulmón irritado por vapores", "neumonitis química", "aspirar tóxicos", "lesión pulmonar por agentes externos", "problemas de pecho por polución", "daño por humos industriales", "irritación bronquial por químicos", "asma ocupacional", "intoxicación pulmonar por gases", "problemas para respirar por ambiente tóxico"]'),
('J70.9', 'Afecciones respiratorias debidas a agentes externos no especificados', 'Sin especificar', '["problemas pulmonares desconocidos", "daño pulmonar ambiental", "pecho cerrado por agentes externos", "tos por causas ambientales", "ahogo por factores externos", "pulmón irritado por algo externo", "afección respiratoria inespecífica", "dificultad al respirar por entorno", "daño respiratorio no aclarado", "problema en el pecho por sustancias", "pulmón afectado por el aire", "molestias pulmonares raras"]');
