INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D05.00', 'Carcinoma lobular in situ de mama no especificada', 'Sin especificar', '["cáncer de mama", "bolita en el seno", "tumor en el pecho", "nódulo mamario", "carcinoma lobulillar", "masa en la teta", "dolor en el busto", "cáncer de seno", "prevención de mama", "chequeo de pechos", "carcinoma in situ", "biopsia mamaria", "quiste mamario", "detección precoz", "salud de la mujer", "mastología"]'),
('D05.01', 'Carcinoma lobular in situ de mama derecha', 'Sin especificar', '["cáncer de mama derecha", "tumor seno derecho", "bolita en teta derecha", "nódulo mama derecha", "carcinoma lobulillar mama derecha", "masa en pecho derecho", "dolor busto derecho", "chequeo seno derecho", "afección mamaria derecha", "diagnóstico de mama derecha", "cáncer seno lado derecho", "biopsia seno derecho", "mastología derecha", "salud mamaria derecha"]'),
('D05.02', 'Carcinoma lobular in situ de mama izquierda', 'Sin especificar', '["cáncer de mama izquierda", "tumor seno izquierdo", "bolita en teta izquierda", "nódulo mama izquierda", "carcinoma lobulillar mama izquierda", "masa en pecho izquierdo", "dolor busto izquierdo", "chequeo seno izquierdo", "afección mamaria izquierda", "diagnóstico de mama izquierda", "cáncer seno lado izquierdo", "biopsia seno izquierdo", "mastología izquierda", "salud mamaria izquierda"]'),
('D05.10', 'Carcinoma intraductal in situ de mama no especificada', 'Sin especificar', '["cáncer de conductos mamarios", "carcinoma ductal", "tumor en los conductos", "células anormales mama", "cáncer de seno inicial", "lesión mamaria", "carcinoma in situ", "ductal in situ", "chequeo ductal", "masa en el seno", "dureza en el pecho", "pre-cáncer de mama", "detección de tumores", "salud mamaria", "mastología"]'),
('D05.11', 'Carcinoma intraductal in situ de mama derecha', 'Sin especificar', '["carcinoma ductal mama derecha", "tumor conductos mama derecha", "cáncer ductal in situ derecha", "bolita conducto seno derecho", "lesión conductos pecho derecho", "células precancerosas seno derecho", "diagnóstico ductal derecha", "nódulo conducto derecha", "detección precoz seno derecho", "mastología derecha", "biopsia ductal derecha"]'),
('D05.12', 'Carcinoma intraductal in situ de mama izquierda', 'Sin especificar', '["carcinoma ductal mama izquierda", "tumor conductos mama izquierda", "cáncer ductal in situ izquierda", "bolita conducto seno izquierdo", "lesión conductos pecho izquierdo", "células precancerosas seno izquierdo", "diagnóstico ductal izquierda", "nódulo conducto izquierda", "detección precoz seno izquierdo", "mastología izquierda", "biopsia ductal izquierda"]'),
('D05.80', 'Otro tipo especificado de carcinoma in situ de mama no especificada', 'Sin especificar', '["cáncer de seno no invasivo", "tumor mamario localizado", "carcinoma localizado", "neoplasia in situ", "lesión premaligna de mama", "células malignas seno", "anomalía en el pecho", "chequeo de masa mamaria", "enfermedad de la mama", "diagnóstico mamario", "detección de carcinomas", "salud de la mujer", "mastología", "cáncer encapsulado"]'),
('D05.81', 'Otro tipo especificado de carcinoma in situ de mama derecha', 'Sin especificar', '["carcinoma in situ mama derecha", "tumor localizado seno derecho", "lesión mamaria derecha", "neoplasia seno derecho", "cáncer no invasivo derecha", "anomalía en teta derecha", "chequeo mama derecha", "diagnóstico seno derecho", "biopsia mama derecha", "mastología derecha", "células malignas pecho derecho"]'),
('D05.82', 'Otro tipo especificado de carcinoma in situ de mama izquierda', 'Sin especificar', '["carcinoma in situ mama izquierda", "tumor localizado seno izquierdo", "lesión mamaria izquierda", "neoplasia seno izquierdo", "cáncer no invasivo izquierda", "anomalía en teta izquierda", "chequeo mama izquierda", "diagnóstico seno izquierdo", "biopsia mama izquierda", "mastología izquierda", "células malignas pecho izquierdo"]'),
('D05.90', 'Carcinoma in situ de tipo no especificado de mama no especificada', 'Sin especificar', '["cáncer de mama", "tumor in situ", "nódulo en el seno", "masa en la mama", "células anormales en el pecho", "pre-cáncer de seno", "problema en el busto", "chequeo mamario", "diagnóstico de cáncer", "detección de nódulos", "salud mamaria general", "mastología", "anomalía en el tejido mamario"]'),
('D05.91', 'Carcinoma in situ de mama derecha tipo no especificado', 'Sin especificar', '["tumor en seno derecho", "bolita en pecho derecho", "cáncer de mama derecha", "nódulo seno derecho", "masa en teta derecha", "anomalía pecho derecho", "chequeo seno derecho", "diagnóstico de mama derecha", "mastología derecha", "biopsia de seno derecho", "salud mamaria derecha"]'),
('D05.92', 'Carcinoma in situ de mama izquierda tipo no especificado', 'Sin especificar', '["tumor en seno izquierdo", "bolita en pecho izquierdo", "cáncer de mama izquierda", "nódulo seno izquierdo", "masa en teta izquierda", "anomalía pecho izquierdo", "chequeo seno izquierdo", "diagnóstico de mama izquierda", "mastología izquierda", "biopsia de seno izquierdo", "salud mamaria izquierda"]');
