INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('F80.0', 'Trastorno fonológico', 'Sin especificar', '["trastorno del habla", "problemas para pronunciar", "no se le entiende al hablar", "ceceo", "habla infantil", "traba la lengua", "dislalia", "articula mal", "habla mal", "pronunciación incorrecta", "no dice bien las letras", "defecto de dicción", "fonemas", "tartajear", "habla enredada"]'),
('F80.1', 'Trastornos del lenguaje expresivo', 'Sin especificar', '["no sabe expresarse", "se le dificulta hablar", "pobre vocabulario", "habla poco", "no arma oraciones", "dificultad para comunicarse", "se explica mal", "no le salen las palabras", "retraso en el habla", "se le traba la lengua", "habla bloqueada", "poco léxico", "le cuesta decir lo que piensa", "problemas de expresión"]'),
('F80.2', 'Trastorno del lenguaje mixto receptivo-expresivo', 'Sin especificar', '["no entiende lo que le dicen", "no sigue instrucciones", "no comprende", "problemas para entender y hablar", "no procesa el lenguaje", "habla raro y no entiende", "deficiencia en comunicación", "no se comunica bien", "dificultad lingüística", "atraso en el lenguaje", "no capta lo que le digo", "problemas de comprensión oral", "trastorno del lenguaje"]'),
('F80.4', 'Retraso del desarrollo del habla y del lenguaje debido a pérdida de audición', 'Sin especificar', '["no habla por no oír", "sordera y habla", "no escucha bien", "problemas de oído y habla", "hipoacusia infantil", "no oye y no aprende a hablar", "oído tapado y no habla", "retraso por sordera", "problemas auditivos", "no responde a sonidos", "pérdida de audición", "niño que no escucha", "sordo y mudo", "no desarrolla el lenguaje por sordera"]'),
('F80.81', 'Trastorno de la fluidez del habla de inicio en la infancia', 'Sin especificar', '["tartamudez", "tartajear", "se traba al hablar", "bloqueos al hablar", "repetición de sílabas", "habla entrecortada", "se queda pegado al hablar", "tartamudo", "dificultad para hablar fluido", "se le van las palabras", "tartamudeo infantil", "dificultad para terminar la frase", "ansiedad al hablar", "no puede hablar de corrido"]'),
('F80.82', 'Trastorno de comunicación social pragmática', 'Sin especificar', '["no entiende el doble sentido", "problemas sociales", "no sabe conversar", "dificultad en normas sociales", "habla fuera de contexto", "no capta las indirectas", "problemas de socialización", "no sabe dialogar", "falla en pragmática", "no entiende las reglas del habla", "habilidades sociales bajas", "se expresa inadecuadamente", "no sabe mantener una charla", "le falta picardía al hablar"]'),
('F80.89', 'Otros trastornos del desarrollo del habla y del lenguaje', 'Sin especificar', '["problemas raros del habla", "fallas al hablar", "trastorno del lenguaje no especificado", "no desarrolla bien el habla", "dificultad comunicativa extraña", "lenguaje confuso", "problemas de comunicación infantil", "habla poco clara", "retraso comunicativo", "desarrollo lingüístico lento", "trastorno del habla atípico"]'),
('F80.9', 'Trastorno del desarrollo del habla y del lenguaje, no especificado', 'Sin especificar', '["retraso en el habla", "mi hijo no habla", "no se le entiende nada", "problemas de lenguaje", "niño que no desarrolla el habla", "atraso en comunicación", "no se comunica como sus pares", "trastorno del lenguaje genérico", "dificultad para el habla", "problemas de expresión y comprensión", "habla infantil prolongada", "desarrollo tardío del habla"]');
