INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B35.0', 'Tiña de la barba y del cuero cabelludo', 'Sin especificar', '["hongos en la cabeza", "tiña en el pelo", "caspa con parches", "calvas por hongos", "micosis capilar", "tiña capitis", "hongos en la barba", "picazón en el cuero cabelludo", "parches escamosos", "pelado por hongos", "tinea barbae", "tiña de la cabeza", "infección por hongos en el vello facial", "erupción en el cuero cabelludo"]'),
('B35.1', 'Tiña de las uñas', 'Sin especificar', '["hongos en las uñas", "onicomicosis", "uñas amarillas", "uñas negras", "uñas gruesas", "uñas feas", "uñas quebradizas", "infección de uñas", "uñas con hongos", "desmoronamiento de uñas", "uñas encarnadas por hongo", "micosis ungueal", "hongos en las patas", "uña con mal olor"]'),
('B35.2', 'Tiña de la mano', 'Sin especificar', '["hongos en las manos", "manos escamosas", "micosis en las manos", "dermatitis por hongos", "tiña palmar", "picazón en las palmas", "manos descascaradas", "infección fúngica en manos", "manos con costras", "manos rojas", "hongos en los dedos", "tinea manuum", "eccema por hongos"]'),
('B35.3', 'Tiña del pie [Tinea pedis]', 'Sin especificar', '["pie de atleta", "hongos en los pies", "mal olor en los pies", "picazón entre los dedos", "patas hediondas", "hongos en la planta", "pie descamado", "micosis en el pie", "ampollas en los pies", "sudoración y hongos", "uña de atleta", "tinea pedis", "pie con mal olor", "ardor en los pies"]'),
('B35.4', 'Tiña del cuerpo [Tinea corporis]', 'Sin especificar', '["tiña en la piel", "manchas rojas en forma de aro", "hongos en el tronco", "tinea corporis", "anillos en la piel", "micosis corporal", "hongos en el cuerpo", "manchas circulares rojas", "picazón en la piel", "dermatofitosis corporal", "erupción cutánea", "parches rojos con bordes", "hongos por contagio"]'),
('B35.5', 'Tiña imbricada [Tinea imbricata]', 'Sin especificar', '["tiña imbricada", "micosis en escamas", "infección fúngica con anillos", "tinea imbricata", "escamas en círculos concéntricos", "hongos tropicales", "dermatofitosis por Tokelau", "manchas en forma de encaje", "hongos en la piel con escamas", "erupción escamosa persistente"]'),
('B35.6', 'Tiña inguinal [Tinea cruris]', 'Sin especificar', '["hongos en la ingle", "tiña de la entrepierna", "picazón en la zona genital", "rojez en la ingle", "jock itch", "hongos por humedad", "micosis inguinal", "escozor en la entrepierna", "tinea cruris", "infección por hongos en los pliegues", "dermatofitosis en la entrepierna", "hongos por sudor"]'),
('B35.8', 'Otras dermatofitosis', 'Sin especificar', '["otras infecciones por hongos", "dermatofitosis rara", "hongos en áreas poco comunes", "micosis cutáneas", "infecciones fúngicas de la piel", "dermatofitosis atípica", "hongos en la piel general", "problemas de hongos cutáneos", "lesiones por hongos", "tiñas diversas"]'),
('B35.9', 'Dermatofitosis, no especificada', 'Sin especificar', '["hongos en la piel", "micosis cutánea", "infección de la piel por hongos", "dermatofitosis", "tiña general", "tengo algo en la piel", "parches por hongos", "picazón persistente", "erupción por hongos", "dermatitis fúngica", "tiña sin diagnosticar", "hongos de origen desconocido"]');
