INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z67.10', 'Grupo sanguíneo A, Rh positivo', 'Sin especificar', '["sangre tipo A+", "grupo A positivo", "sangre A positivo", "soy A positivo", "tipo de sangre A mas", "A positivo", "fenotipo A Rh positivo", "compatibilidad sangre A+", "donante A positivo", "factor Rh positivo grupo A", "sangre tipo A plus"]'),
('Z67.11', 'Grupo sanguíneo A, Rh negativo', 'Sin especificar', '["sangre tipo A-", "grupo A negativo", "sangre A negativo", "soy A negativo", "tipo de sangre A menos", "A negativo", "fenotipo A Rh negativo", "compatibilidad sangre A-", "donante A negativo", "factor Rh negativo grupo A", "sangre tipo A minus"]'),
('Z67.20', 'Grupo sanguíneo B, Rh positivo', 'Sin especificar', '["sangre tipo B+", "grupo B positivo", "sangre B positivo", "soy B positivo", "tipo de sangre B mas", "B positivo", "fenotipo B Rh positivo", "compatibilidad sangre B+", "donante B positivo", "factor Rh positivo grupo B", "sangre tipo B plus"]'),
('Z67.21', 'Grupo sanguíneo B, Rh negativo', 'Sin especificar', '["sangre tipo B-", "grupo B negativo", "sangre B negativo", "soy B negativo", "tipo de sangre B menos", "B negativo", "fenotipo B Rh negativo", "compatibilidad sangre B-", "donante B negativo", "factor Rh negativo grupo B", "sangre tipo B minus"]'),
('Z67.30', 'Grupo sanguíneo AB, Rh positivo', 'Sin especificar', '["sangre tipo AB+", "grupo AB positivo", "sangre AB positivo", "soy AB positivo", "tipo de sangre AB mas", "AB positivo", "fenotipo AB Rh positivo", "compatibilidad sangre AB+", "donante AB positivo", "factor Rh positivo grupo AB", "sangre tipo AB plus"]'),
('Z67.31', 'Grupo sanguíneo AB, Rh negativo', 'Sin especificar', '["sangre tipo AB-", "grupo AB negativo", "sangre AB negativo", "soy AB negativo", "tipo de sangre AB menos", "AB negativo", "fenotipo AB Rh negativo", "compatibilidad sangre AB-", "donante AB negativo", "factor Rh negativo grupo AB", "sangre tipo AB minus"]'),
('Z67.40', 'Grupo sanguíneo O, Rh positivo', 'Sin especificar', '["sangre tipo O+", "grupo O positivo", "sangre O positivo", "soy O positivo", "tipo de sangre O mas", "O positivo", "donante universal positivo", "fenotipo O Rh positivo", "compatibilidad sangre O+", "donante O positivo", "factor Rh positivo grupo O", "sangre tipo O plus"]'),
('Z67.41', 'Grupo sanguíneo O, Rh negativo', 'Sin especificar', '["sangre tipo O-", "grupo O negativo", "sangre O negativo", "soy O negativo", "tipo de sangre O menos", "O negativo", "donante universal negativo", "donante universal puro", "fenotipo O Rh negativo", "compatibilidad sangre O-", "donante O negativo", "factor Rh negativo grupo O", "sangre tipo O minus"]'),
('Z67.90', 'Grupo sanguíneo no especificado, Rh positivo', 'Sin especificar', '["sangre Rh positivo", "desconocido positivo", "grupo sanguíneo incierto Rh+", "factor positivo desconocido", "tipo de sangre no determinado", "RH positivo sin grupo", "análisis de sangre pendiente", "estudio sanguíneo RH+", "sangre desconocida RH positivo"]'),
('Z67.91', 'Grupo sanguíneo no especificado, Rh negativo', 'Sin especificar', '["sangre Rh negativo", "desconocido negativo", "grupo sanguíneo incierto Rh-", "factor negativo desconocido", "tipo de sangre no determinado", "RH negativo sin grupo", "análisis de sangre pendiente", "estudio sanguíneo RH-", "sangre desconocida RH negativo"]'),
('Z67.A1', 'Duffy nulo', 'Sin especificar', '["sistema duffy nulo", "fy a-b-", "ausencia de antigeno duffy", "genotipo duffy nulo", "resistencia malaria vivax", "fenotipo duffy negativo", "deficiencia factor duffy", "duffy nulo prueba sangre"]'),
('Z67.A2', 'Duffy a positivo', 'Sin especificar', '["sistema duffy a", "fya positivo", "antigeno duffy a", "factor duffy a+", "genotipo fy a", "presencia fy a", "analisis grupo duffy a"]'),
('Z67.A3', 'Duffy b positivo', 'Sin especificar', '["sistema duffy b", "fyb positivo", "antigeno duffy b", "factor duffy b+", "genotipo fy b", "presencia fy b", "analisis grupo duffy b"]'),
('Z67.A4', 'Duffy a y b positivos', 'Sin especificar', '["sistema duffy a y b", "fya y fyb positivo", "antigeno duffy ab", "factor duffy doble positivo", "genotipo fy a-b", "fenotipo duffy a b", "compatibilidad grupo duffy a y b"]');
