INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('O87.0', 'Tromboflebitis superficial en el puerperio', 'Sin especificar', '["vena hinchada postparto", "inflamación de venas después de dar a luz", "cordón duro en la pierna", "enrojecimiento venoso puerperio", "tromboflebitis superficial", "dolor en venas post-parto", "flebitis al parir", "calor en la piel después del parto", "venas rojas en las piernas", "inflamación venosa superficial", "bulto en la pierna postparto", "trombosis superficial puerperio", "venas calientes", "dolor venoso al tener al bebé"]'),
('O87.1', 'Flebotrombosis profunda en el puerperio', 'Sin especificar', '["trombosis venosa profunda", "coágulo en la pierna postparto", "TVP puerperio", "pierna hinchada y morada", "trombo después de parir", "dolor profundo en la pantorrilla", "embolia postparto", "pierna pesada y caliente", "coágulo sanguíneo post-parto", "flebotrombosis", "peligro de coágulo tras el parto", "hinchazón severa de pierna", "trombosis en la cuarentena", "dolor al caminar postparto"]'),
('O87.2', 'Hemorroides en el puerperio', 'Sin especificar', '["almorranas", "hemorroides después del parto", "bolitas en el ano", "dolor al evacuar postparto", "inflamación anal tras el parto", "venas inflamadas en el recto", "almorranas por el esfuerzo del parto", "picazón anal postparto", "sangrado rectal post-parto", "prolapso hemorroidal", "dolor de poto al parir", "hemorroides de la cuarentena", "bultos en el culo postparto", "molestias rectales post-parto"]'),
('O87.3', 'Trombosis venosa cerebral en el puerperio', 'Sin especificar', '["coágulo en el cerebro postparto", "trombosis cerebral puerperal", "dolor de cabeza fuerte postparto", "cefalea grave tras el parto", "trombosis de senos venosos", "accidente cerebrovascular postparto", "infarto cerebral tras parir", "dolor de cabeza insoportable", "convulsiones postparto", "problemas neurológicos tras el parto", "coágulo intracraneal", "dolor de cabeza tipo migraña", "trombosis venosa cerebral", "pérdida de visión postparto"]'),
('O87.4', 'Venas varicosas de las extremidades inferiores en el puerperio', 'Sin especificar', '["várices después del parto", "venas brotadas en las piernas", "venas moradas postparto", "arañitas en las piernas", "varices post-parto", "piernas hinchadas y varicosas", "venas dilatadas en la cuarentena", "insuficiencia venosa postparto", "dolor de piernas tras el embarazo", "venas marcadas en el embarazo", "varices que salen al parir", "venas varicosas puerperio", "pesadez de piernas tras el parto", "venas hinchadas y tortuosas"]'),
('O87.8', 'Otras complicaciones venosas en el puerperio', 'Sin especificar', '["problemas de circulación postparto", "complicaciones venosas raras", "trastornos de las venas tras el parto", "inflamación vascular postparto", "problemas vasculares en la cuarentena", "flebitis generalizada", "complicaciones del sistema venoso", "problemas de coagulación postparto", "venas irritadas post-parto", "infección venosa puerperio", "trastornos venosos del postparto", "vasculitis postparto", "embolia venosa", "problemas de retorno venoso"]'),
('O87.9', 'Complicaciones venosas en el puerperio, no especificadas', 'Sin especificar', '["problema de venas después de parir", "complicación vascular desconocida", "dolor en las venas postparto", "malestar venoso inespecífico", "problemas de sangre y venas tras el parto", "síntomas venosos post-parto", "afectación venosa puerperal", "complicación de las venas", "indefinido venoso postparto", "dolor y venas tras el parto", "sospecha de trombosis postparto", "problemas de circulación puerperio", "complicación circulatoria tras el parto", "venas que duelen postparto"]');
