INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('X11.0XXA', 'Contacto con agua caliente en baño o tina, contacto inicial', 'Sin especificar', '["quemadura tina", "quemado baño", "agua hirviendo", "escaldadura", "quemarse en la ducha", "accidente baño", "quemadura primer contacto", "quemado con agua caliente", "pellejo quemado", "ampollas por agua", "dermatitis por calor", "accidente doméstico agua", "quemazón tina"]'),
('X11.0XXD', 'Contacto con agua caliente en baño o tina, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura", "cura quemadura baño", "quemadura en evolución", "control quemadura agua", "tratamiento herida tina", "curación escaldadura", "revisión quemado", "herida sin cerrar", "quemadura que no sana", "consulta quemadura recurrente", "cuidado quemadura"]'),
('X11.0XXS', 'Contacto con agua caliente en baño o tina, secuela', 'Sin especificar', '["cicatriz quemadura", "mancha por quemadura", "piel dañada tina", "secuela agua hirviendo", "queloides por quemadura", "pellejo estirado", "cicatriz escaldadura", "piel acartonada", "marca de quemada", "secuela de accidente doméstico", "problemas de piel por quemadura"]'),
('X11.1XXA', 'Contacto con agua caliente, contacto inicial', 'Sin especificar', '["quemado con agua", "escaldado", "quemadura reciente", "chorro de agua caliente", "agua que quema", "accidente agua caliente", "primeros auxilios quemadura", "piel roja por agua", "quemadura inmediata", "quemazón", "lesión térmica inicial"]'),
('X11.1XXD', 'Contacto con agua caliente, contacto sucesivo', 'Sin especificar', '["curación quemadura", "seguimiento quemado", "revisión de piel", "herida de agua caliente", "cura de escaldadura", "tratamiento quemazón", "control de herida", "curar piel quemada", "atención médica quemadura", "cuidado post-quemadura"]'),
('X11.1XXS', 'Contacto con agua caliente, secuela', 'Sin especificar', '["cicatriz por agua", "marca de quemadura", "piel con secuelas", "mancha de quemado", "cicatriz queloide", "piel quemada vieja", "daño térmico secuela", "secuela de escaldadura", "piel manchada por calor", "cicatrización deficiente"]'),
('X11.8XXA', 'Contacto con otra agua caliente de grifo, contacto inicial', 'Sin especificar', '["quemado en el grifo", "quemadura con la canilla", "agua de la llave caliente", "quemarse la mano con agua", "quemadura por chorro", "quemadura llave de paso", "lesión por agua hirviente", "accidente grifo", "quemazón inmediata", "agua caliente plomería"]'),
('X11.8XXD', 'Contacto con otra agua caliente de grifo, contacto sucesivo', 'Sin especificar', '["revisión quemadura grifo", "curar quemadura canilla", "seguimiento lesión agua", "tratamiento piel quemada", "control médico quemadura", "curación de grifo", "herida en recuperación", "consulta post quemadura", "cuidado herida agua"]'),
('X11.8XXS', 'Contacto con otra agua caliente de grifo, secuela', 'Sin especificar', '["cicatriz grifo", "mancha quemadura canilla", "piel cicatrizada", "secuela quemadura llave", "daño térmico crónico", "piel marcada", "cicatriz quemazón", "secuela por agua de grifo", "tejido con cicatriz", "problema estético quemadura"]');
