INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('X01.0XXA', 'Exposición a las llamas en un incendio incontrolado, no en un edificio o estructura, contacto inicial', 'Sin especificar', '["quemadura por fuego", "queme", "incendio forestal", "fuego en campo", "quemado por llama", "fuego descontrolado", "quema de pastizales", "fogata descontrolada", "accidente con fuego", "quemaduras", "llamas", "accidente de quemadura", "fuego en la intemperie", "fuego al aire libre"]'),
('X01.0XXD', 'Exposición a las llamas en un incendio incontrolado, no en un edificio o estructura, contacto sucesivo', 'Sin especificar', '["tratamiento por quemaduras", "curación de quemaduras", "seguimiento de incendio", "segunda exposición a fuego", "quemadura crónica", "cuidado de heridas por incendio", "reincidencia en incendio", "atención médica por fuego", "proceso de quemadura", "cicatrices de incendio", "control de quemadura"]'),
('X01.0XXS', 'Exposición a las llamas en un incendio incontrolado, no en un edificio o estructura, secuela', 'Sin especificar', '["secuelas de quemadura", "cicatrices por fuego", "marcas de quemadura", "queloides por incendio", "contracturas por fuego", "daño crónico por llama", "pérdida de movilidad por quemadura", "secuela de accidente", "quemadura vieja", "marcas de incendio", "daño cutáneo permanente"]'),
('X01.1XXA', 'Exposición al humo de un incendio no controlado, no en un edificio o estructura, contacto inicial', 'Sin especificar', '["inhalación de humo", "intoxicación por humo", "ahogo por fuego", "humo de incendio", "tos por humo", "respirar humo", "asfixia por incendio", "gases de incendio", "humo de monte", "humo tóxico", "dificultad al respirar por humo", "vías respiratorias irritadas"]'),
('X01.1XXD', 'Exposición al humo de un incendio no controlado, no en un edificio o estructura, contacto sucesivo', 'Sin especificar', '["seguimiento por inhalación de humo", "problemas respiratorios por humo", "tos crónica por incendio", "daño pulmonar por gases", "atención por humo", "revisión respiratoria", "inflamación de vías aéreas", "exposición recurrente a humo", "tratamiento neumológico"]'),
('X01.1XXS', 'Exposición al humo de un incendio no controlado, no en un edificio o estructura, secuela', 'Sin especificar', '["daño pulmonar por humo", "fibrosis por inhalación", "secuelas respiratorias", "problemas de pulmón por fuego", "tos persistente por incendio", "asma por humo", "EPOC por inhalación", "cicatrices en vías respiratorias", "daño bronquial", "incapacidad respiratoria"]'),
('X01.3XXA', 'Caída por incendios incontrolados, no en un edificio o estructura, contacto inicial', 'Sin especificar', '["caída en incendio", "tropezón en incendio", "caer por huir del fuego", "accidente huyendo del fuego", "caída al correr por incendio", "golpe al caer en incendio", "fractura por incendio", "caída en zona de fuego", "escapar del fuego y caer"]'),
('X01.3XXD', 'Caída por incendios incontrolados, no en un edificio o estructura, contacto sucesivo', 'Sin especificar', '["seguimiento de fractura por incendio", "curación de caída", "rehabilitación tras caída en incendio", "atención de golpes por fuego", "tratamiento post-caída", "seguimiento de traumatismo", "fisioterapia post-incendio"]'),
('X01.3XXS', 'Caída por incendios incontrolados, no en un edificio o estructura, secuela', 'Sin especificar', '["secuela de fractura", "dolor post-traumático", "discapacidad tras caída", "problemas articulares por caída", "dolor crónico de caída", "limitación física tras incendio", "consecuencia de accidente", "lesión residual"]'),
('X01.4XXA', 'Golpe por objeto debido al fuego no controlado, no en un edificio o estructura, contacto inicial', 'Sin especificar', '["golpe por caída de rama", "árbol caído por fuego", "objeto proyectado por incendio", "atropello por escombros", "impacto por objeto en incendio", "golpeado por fuego", "accidente con escombros", "escombros en llamas", "golpe al huir del incendio"]'),
('X01.4XXD', 'Golpe por objeto debido al fuego no controlado, no en un edificio o estructura, contacto sucesivo', 'Sin especificar', '["seguimiento de contusión", "curación de golpe", "tratamiento de traumatismo", "revisión por impacto", "atención médica tras golpe", "cuidado de heridas por objeto", "rehabilitación de contusión"]'),
('X01.4XXS', 'Golpe por objeto debido al fuego no controlado, no en un edificio o estructura, secuela', 'Sin especificar', '["secuela de golpe", "dolor persistente por impacto", "daño interno por objeto", "cicatrices de golpe", "problemas post-traumáticos", "consecuencias de traumatismo", "lesión antigua por incendio"]'),
('X01.8XXA', 'Otras exposiciones a fuego sin control, no en un edificio o estructura, contacto inicial', 'Sin especificar', '["accidente con fuego", "incidente de quemado", "lesión por fuego", "fuego salvaje", "fuego en campo abierto", "exposición a brasas", "quemadura química por incendio", "daño por cenizas", "accidente de campo"]'),
('X01.8XXD', 'Otras exposiciones a fuego sin control, no en un edificio o estructura, contacto sucesivo', 'Sin especificar', '["seguimiento de quemadura", "evolución de lesión por fuego", "control médico post-incendio", "tratamiento de heridas", "cuidado de quemaduras abiertas", "revisión de lesiones", "proceso de curación de fuego"]'),
('X01.8XXS', 'Otras exposiciones a fuego sin control, no en un edificio o estructura, secuela', 'Sin especificar', '["secuela de quemaduras", "cicatrices permanentes", "daño tisular post-fuego", "discapacidad por incendio", "consecuencias de exposición al fuego", "dolor crónico", "marcas cutáneas de incendio"]');
