INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L25.0', 'Dermatitis de contacto no especificada debida a cosméticos', 'Sin especificar', '["alergia a cremas", "irritación por maquillaje", "reacción a cosméticos", "piel roja por labial", "picazón por perfume", "sarpullido por base", "dermatitis por labial", "alergia a sombras", "cara irritada por maquillaje", "eccema por cremas", "piel escamada por cosméticos", "erupción facial cosmética", "reacción alérgica cutánea", "picor en la cara", "brote por crema", "irritación cutánea cosmética"]'),
('L25.1', 'Dermatitis de contacto no especificada debida a medicamentos en contacto con la piel', 'Sin especificar', '["alergia a pomadas", "irritación por ungüentos", "reacción a cremas medicinales", "sarpullido por medicamentos", "quemazón por crema medicada", "dermatitis por antibiótico tópico", "piel irritada por bálsamo", "reacción a gotas dermatológicas", "alergia a linimentos", "picor por parche medicado", "erupción por medicación", "eccema por pomada", "efecto adverso cutáneo", "irritación por gel medicado", "dermatitis medicamentosa"]'),
('L25.2', 'Dermatitis de contacto no especificada debida a tintes', 'Sin especificar', '["alergia al tinte de pelo", "picazón en el cuero cabelludo", "irritación por tinte", "reacción alérgica al tinte", "orejas rojas por tinte", "sarpullido por teñirse", "dermatitis por tinte", "cuero cabelludo irritado", "piel quemada por tinte", "alergia a la henna", "picor tras teñirse", "reacción a químicos del tinte", "eccema por tinte capilar", "erupción en la nuca", "irritación química por tinte"]'),
('L25.3', 'Dermatitis de contacto no especificada debida a otros productos químicos', 'Sin especificar', '["alergia a químicos", "quemadura química leve", "irritación por detergente", "dermatitis por cloro", "piel irritada por solventes", "reacción a productos de limpieza", "alergia a ácidos", "sarpullido por químicos", "manos irritadas por jabón", "eccema industrial", "dermatitis de contacto irritativa", "picazón por detergentes", "erupción por sustancias químicas", "piel agrietada por químicos", "reacción a lejía"]'),
('L25.4', 'Dermatitis de contacto no especificada debida a alimentos en contacto con la piel', 'Sin especificar', '["alergia al tocar comida", "irritación al picar vegetales", "reacción cutánea a cítricos", "sarpullido por contacto alimentario", "picor al pelar frutas", "dermatitis por alimentos", "manos rojas por manipular comida", "reacción a la piña", "alergia cutánea a condimentos", "irritación por ajo", "erupción por manipular alimentos", "piel sensible a la comida", "picazón tras cocinar", "eccema por contacto alimenticio", "quemazón por chiles"]'),
('L25.5', 'Dermatitis de contacto no especificada debida a plantas, excepto las alimenticias', 'Sin especificar', '["alergia a plantas", "erupción por maleza", "picazón por pasto", "reacción al contacto con hojas", "sarpullido por flores", "hiedra venenosa", "dermatitis por plantas", "piel irritada por el campo", "picor por plantas de jardín", "erupción por contacto con plantas", "alergia a polen en la piel", "reacción a espinas", "eccema botánico", "irritación por arbustos", "picazón por hiedra"]'),
('L25.8', 'Dermatitis de contacto no especificada debida a otros agentes', 'Sin especificar', '["alergia a la bisutería", "reacción al níquel", "dermatitis por metales", "picazón por reloj", "irritación por tela", "sarpullido por contacto", "alergia a tejidos sintéticos", "eccema de contacto", "reacción a correas", "picor por materiales desconocidos", "erupción alérgica", "dermatitis por contacto externo", "piel roja sin causa clara", "alergia a accesorios", "irritación dérmica"]'),
('L25.9', 'Dermatitis de contacto no especificada, causa no especificada', 'Sin especificar', '["dermatitis no especificada", "eccema de origen desconocido", "sarpullido inexplicable", "alergia cutánea rara", "piel irritada sin causa", "manchas rojas en la piel", "picazón persistente", "erupción cutánea misteriosa", "picor de piel", "dermatitis aguda", "reacción alérgica en piel", "irritación dermatológica", "alergia de la piel", "eccema inespecífico", "brotes en la piel"]');
