INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q61.00', 'Quiste renal congénito, no especificado', 'Sin especificar', '["quiste en el riñón", "bolita en el riñón", "quiste de nacimiento", "dolor de riñones", "infección urinaria recurrente", "punzada en la espalda", "problema renal", "riñón afectado", "quiste congénito", "dolor en el costado", "masa en el riñón", "piedra o quiste", "insuficiencia renal", "chequeo de riñones", "orina con sangre"]'),
('Q61.01', 'Quiste renal congénito simple', 'Sin especificar', '["quiste simple", "quiste solitario", "bolita de agua en el riñón", "quiste benigno", "quiste sin importancia", "quiste de nacimiento", "dolor lumbar", "flanco dolorido", "examen de riñones", "ecografía renal", "hallazgo incidental", "quiste único", "problema de riñón", "cólico renal", "orina turbia"]'),
('Q61.02', 'Quistes renales múltiples congénitos', 'Sin especificar', '["muchos quistes", "riñón con burbujas", "quistes por todos lados", "bolitas en los riñones", "riñón multiquístico", "displasia renal", "problema genético de riñones", "dolor en la espalda baja", "orinar mucho", "presión alta renal", "insuficiencia renal", "herencia familiar", "riñón poliquístico", "dolor constante en la guata", "malestar renal"]'),
('Q61.11', 'Dilatación quística de los túbulos colectores', 'Sin especificar', '["riñón esponja", "dilatación de túbulos", "riñón con huequitos", "problema renal congénito", "fallo en los riñones", "piedras en el riñón frecuentes", "cálculos renales", "dolor renal", "infección urinaria", "orina cargada", "dolor al orinar", "dolor en la zona lumbar", "malformación renal", "nefrología", "túbulos dilatados"]'),
('Q61.19', 'Otro riñón poliquístico tipo infantil', 'Sin especificar', '["riñón poliquístico de bebé", "riñón con muchos quistes infantil", "problema renal de nacimiento", "enfermedad hereditaria renal", "riñón grande", "hinchazón abdominal", "insuficiencia renal infantil", "riñón que no filtra", "orina con sangre", "anomalía de nacimiento", "problema de riñones en niños", "genética renal", "diálisis infantil", "fallo renal congénito", "masa abdominal"]'),
('Q61.2', 'Riñón poliquístico tipo adulto', 'Sin especificar', '["riñón poliquístico", "riñones con quistes", "enfermedad hereditaria de riñones", "quistes en riñones", "presión arterial alta", "insuficiencia renal crónica", "dolor de costado", "riñones agrandados", "cálculos renales", "orinar sangre", "dolor de espalda baja", "punzadas en los riñones", "quistes en el hígado y riñones", "fallo de riñón", "nefropatía"]'),
('Q61.3', 'Riñón poliquístico no especificado', 'Sin especificar', '["riñones con bolas", "riñones con quistes", "poliquistosis renal", "problemas de riñón crónicos", "dolor de riñones", "herencia familiar de riñones", "hipertensión por riñones", "mal funcionamiento renal", "quistes en ambos riñones", "riñón grande y con quistes", "dolor abdominal crónico", "orina oscura", "hinchazón renal", "insuficiencia de riñón", "chequeo nefrológico"]'),
('Q61.4', 'Displasia renal', 'Sin especificar', '["riñón mal formado", "riñón que no creció", "riñón atrofiado", "displasia de riñón", "riñón hipoplásico", "falla renal de nacimiento", "riñón pequeño", "problema de riñones", "dolor en la panza", "dolor en la guata", "insuficiencia renal crónica", "malformación urinaria", "orina anormal", "retraso en el crecimiento renal", "reflujo renal"]'),
('Q61.5', 'Riñón quístico medular', 'Sin especificar', '["enfermedad quística medular", "quistes en la médula renal", "riñón nefronoftisis", "problema hereditario de riñón", "insuficiencia renal", "orinar mucho", "sed excesiva", "dolor en la espalda", "orina diluida", "problemas para filtrar", "deshidratación crónica", "fallo renal", "anemia renal", "dolor lumbar", "chequeo con nefrólogo"]'),
('Q61.8', 'Otras enfermedades renales quísticas', 'Sin especificar', '["otros quistes renales", "quiste complejo", "bolitas en el riñón", "problema de riñones", "dolor en la zona renal", "masa quística", "examen de riñones", "quistes renales atípicos", "dolor en el flanco", "orina con sangre", "malestar renal", "hidronefrosis", "quiste hidatídico renal", "cálculos y quistes", "nefrología"]'),
('Q61.9', 'Enfermedad quística del riñón, no especificada', 'Sin especificar', '["problema en los riñones", "quistes en el riñón", "dolor de riñones", "mal de riñones", "punzada en la espalda", "dolor en el costado", "orina turbia", "examen de orina alterado", "insuficiencia renal", "cálculos renales", "dolor de riñón", "hinchazón en la barriga", "problema para orinar", "nefropatía", "chequeo renal"]');
