INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J12.0', 'Neumonía por adenovirus', 'Sin especificar', '["neumonía", "infección pulmonar", "pulmonía", "virus respiratorio", "adenovirus", "fiebre alta", "tos seca", "dolor de pecho", "dificultad para respirar", "infección en los pulmones", "mal del pulmón", "pecho cargado", "catarro fuerte", "falta de aire", "pulmones inflamados", "flemas", "cansancio extremo"]'),
('J12.1', 'Neumonía por virus sincitial respiratorio', 'Sin especificar', '["virus sincitial", "neumonía infantil", "bronquiolitis", "infección respiratoria", "tos con flema", "dificultad para respirar", "silbidos al respirar", "pecho cerrado", "pulmonía por virus", "faringitis", "moco en los pulmones", "fiebre", "bebé ahogado", "pulmón infectado", "dificultad al succionar", "malestar respiratorio"]'),
('J12.2', 'Neumonía por virus parainfluenza', 'Sin especificar', '["neumonía viral", "parainfluenza", "tos perruna", "crup", "pulmonía", "inflamación de vías respiratorias", "fiebre", "ronquera", "dificultad al tragar", "dolor de garganta", "pecho congestionado", "infección viral", "mal del pecho", "pulmones inflamados", "falta de aire", "catarro persistente"]'),
('J12.3', 'Neumonía por metaneumovirus humano', 'Sin especificar', '["metaneumovirus", "neumonía viral", "tos intensa", "dificultad respiratoria", "congestión pulmonar", "fiebre alta", "infección bronquial", "pulmonía", "bronquitis fuerte", "pecho apretado", "flemas verdes", "falta de aliento", "malestar general", "cansancio respiratorio", "infección pulmonar aguda"]'),
('J12.81', 'Neumonía por coronavirus asociado al SARS', 'Sin especificar', '["SARS", "neumonía por SARS", "coronavirus severo", "síndrome respiratorio agudo", "pulmonía grave", "dificultad respiratoria severa", "tos seca", "fiebre alta", "insuficiencia respiratoria", "pulmones dañados", "infección por coronavirus", "falta de oxígeno", "dolor torácico", "neumonía atípica", "emergencia pulmonar"]'),
('J12.82', 'Neumonía por enfermedad de coronavirus 2019', 'Sin especificar', '["COVID-19", "neumonía por covid", "bicho", "coronavirus", "infección pulmonar covid", "pulmonía covid", "tos seca", "pérdida de olfato", "falta de aire", "oxígeno bajo", "pecho pesado", "fiebre covid", "infección viral respiratoria", "neumonía atípica covid", "fatiga extrema", "complicación respiratoria"]'),
('J12.89', 'Otros tipos de neumonía vírica', 'Sin especificar', '["neumonía viral", "infección pulmonar por virus", "pulmonía contagiosa", "tos persistente", "fiebre y dolor de pecho", "pulmones inflamados", "catarro de pecho", "bronquitis viral", "malestar de pulmones", "dificultad para respirar", "infección de vías bajas", "pecho congestionado", "flemas", "dolor al respirar", "mal del pulmón"]'),
('J12.9', 'Neumonía vírica, no especificada', 'Sin especificar', '["neumonía", "pulmonía", "infección en los pulmones", "pulmón tomado", "pecho inflamado", "tos persistente", "fiebre", "dificultad respiratoria", "flemas", "bronquitis mal curada", "dolor en el pecho", "falta de aire", "catarro fuerte", "malestar general", "pecho cargado", "pulmonía viral"]');
