INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A21.0', 'Tularemia ulceroglandular', 'Sin especificar', '["fiebre de los conejos", "úlceras en la piel", "ganglios inflamados", "bultos en el cuello", "infección por conejos", "tularemia cutánea", "llagas infectadas", "linfadenitis regional", "picadura de garrapata", "fiebre del ciervo", "infección de roedores", "dolor glandular", "inflamación axilar", "bacteria de la fiebre", "úlcera glandular"]'),
('A21.1', 'Tularemia oculoglandular', 'Sin especificar', '["infección en el ojo", "ojo rojo", "conjuntivitis infecciosa", "dolor ocular", "párpados inflamados", "secreción ocular", "fiebre de los conejos ojos", "ganglios cerca del ojo", "linfadenopatía ocular", "tularemia ocular", "infección ocular por roedores", "ojo pegajoso", "ardor en ojos", "ojo hinchado", "bacteria en el ojo"]'),
('A21.2', 'Tularemia pulmonar', 'Sin especificar', '["neumonía por tularemia", "tos con sangre", "dolor en el pecho", "falta de aire", "dificultad para respirar", "infección respiratoria grave", "fiebre del conejo pulmones", "disnea", "pulmones inflamados", "tos seca persistente", "tuberculosis falsa", "problemas para respirar", "infección de vías respiratorias", "neumonía atípica", "fiebre alta y tos"]'),
('A21.3', 'Tularemia gastrointestinal', 'Sin especificar', '["dolor de panza", "dolor de guata", "dolor de barriga", "diarrea severa", "vómitos y fiebre", "infección estomacal", "dolor abdominal intenso", "nauseas por tularemia", "malestar intestinal", "fiebre de los conejos estómago", "cólicos fuertes", "infección por ingerir bacterias", "gastroenteritis bacteriana", "inflamación intestinal", "descomposición estomacal"]'),
('A21.7', 'Tularemia generalizada', 'Sin especificar', '["tularemia sistémica", "sepsis por tularemia", "fiebre muy alta", "infección en todo el cuerpo", "shock séptico", "enfermedad de los conejos grave", "malestar general extremo", "infección en la sangre", "fallo multiorgánico", "fiebre tifoidea de los roedores", "tularemia grave", "postración", "infección diseminada", "riesgo vital por tularemia", "bacteriemia"]'),
('A21.8', 'Otras formas de tularemia', 'Sin especificar', '["tularemia atípica", "variantes de tularemia", "formas raras de fiebre de los conejos", "tularemia no especificada", "infección inusual por Francisella", "manifestaciones raras de tularemia", "complicaciones por tularemia", "síntomas extraños de tularemia", "otras presentaciones de fiebre del ciervo", "tularemia oculta", "focos atípicos de tularemia"]'),
('A21.9', 'Tularemia, no especificada', 'Sin especificar', '["fiebre de los conejos", "fiebre del conejo", "enfermedad de los roedores", "infección por liebres", "mal del conejo", "fiebre del ciervo", "infección por garrapatas", "bacteria de la fiebre", "tularemia sin clasificar", "sospecha de tularemia", "fiebre de origen desconocido por conejos", "análisis de tularemia", "brotes de tularemia", "Francisella tularensis"]');
