INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P03.0', 'Recién nacido afectado por parto de nalgas y extracción de nalgas', 'Sin especificar', '["bebé de nalgas", "parto de nalgas", "venía sentado", "parto pélvico", "presentación de nalgas", "bebé al revés", "nació de nalgas", "extracción podálica", "parto difícil de nalgas", "complicaciones parto nalgas", "bebé nalgón", "nació sentado", "presentación de nalgas al nacer", "problemas parto de nalgas", "parto de nalgas asistido"]'),
('P03.1', 'Recién nacido afectado por otros tipos de mala presentación, malposición y desproporción durante el trabajo del parto y parto', 'Sin especificar', '["bebé mal acomodado", "parto complicado", "mala posición al nacer", "desproporción céfalo-pélvica", "no encajó", "bebé torcido", "parto obstruido", "mala presentación fetal", "distocia de presentación", "bebé grande no cabe", "parto estancado", "presentación de cara", "presentación de frente", "mala posición en el útero", "dificultad para encajar"]'),
('P03.2', 'Recién nacido afectado por parto con fórceps', 'Sin especificar', '["parto con fórceps", "le pusieron fórceps", "parto instrumentado", "nacido con pinzas", "marcas de fórceps", "uso de fórceps en el parto", "bebé con fórceps", "parto asistido con instrumentos", "pinzas al nacer", "fórceps en la cabeza del bebé", "ayuda con fórceps", "lesiones por fórceps", "fórceps obstétricos", "parto forzado con pinzas", "nacimiento instrumentado"]'),
('P03.3', 'Recién nacido afectado por parto con ventosa', 'Sin especificar', '["parto con ventosa", "parto con vacuo", "bebé con chichón", "vacum extractor", "ventosa obstétrica", "chichón en la cabeza del bebé", "nació con ventosa", "extracción por succión", "parto asistido con vacío", "bebé succionado", "marca de ventosa", "succión en la cabeza al nacer", "extracción al vacío", "parto con succión", "complicaciones por ventosa"]'),
('P03.4', 'Recién nacido afectado por parto por cesárea', 'Sin especificar', '["bebé de cesárea", "nació por cesárea", "le hicieron cesárea", "operación para nacer", "parto quirúrgico", "nació por raje", "cesárea de urgencia", "corte en la panza para nacer", "nació por la panza", "operado al nacer", "nacimiento por cirugía", "cesárea programada", "recuperación de cesárea del bebé", "parto por bisturí", "nació por cesárea complicaciones"]'),
('P03.5', 'Recién nacido afectado por parto precipitado', 'Sin especificar', '["parto rápido", "nació muy rápido", "parto relámpago", "nació de sorpresa", "parto precipitado", "nació antes de llegar al hospital", "parto súbito", "nació en el auto", "parto veloz", "bebé que salió de golpe", "nació sin tiempo", "parto en casa involuntario", "nacimiento explosivo", "nació en un pispás", "parto sin anestesia rápido"]'),
('P03.6', 'Recién nacido afectado por contracciones uterinas anormales', 'Sin especificar', '["contracciones raras", "parto detenido", "contracciones ineficientes", "útero no dilataba", "contracciones que no servían", "parto distócico", "contracciones anormales", "dinámica uterina alterada", "parto que no avanza", "contracciones débiles", "contracciones muy fuertes", "útero espástico", "fallo en las contracciones", "parto lento", "problemas con las contracciones"]'),
('P03.810', 'Recién nacido afectado por alteraciones en el ritmo o la frecuencia cardiaca fetal (intrauterinas) antes del inicio del trabajo de parto', 'Sin especificar', '["corazón del bebé lento", "frecuencia cardiaca fetal baja", "sufrimiento fetal antes de nacer", "taquicardia fetal", "bradicardia fetal", "ritmo cardiaco del bebé raro", "problemas de corazón del feto", "latido del bebé débil", "sufrimiento fetal crónico", "monitorización cardiaca fetal", "corazón fetal alterado", "arritmia del feto", "latido inestable del bebé", "problemas cardiacos en el útero", "auscultación fetal anormal"]'),
('P03.811', 'Recién nacido afectado por alteraciones en el ritmo o la frecuencia cardiaca fetal (intrauterinas) durante el parto', 'Sin especificar', '["sufrimiento fetal agudo", "frecuencia cardiaca bajó en el parto", "el corazón del bebé se cansó", "desaceleraciones fetales", "pérdida de bienestar fetal", "taquicardia durante el parto", "bradicardia intraparto", "corazón del bebé se aceleró", "monitoreo fetal con problemas", "sufrimiento en el expulsivo", "arritmia durante el nacimiento", "latido fetal crítico", "estrés fetal en el parto", "el bebé se estaba asfixiando", "cambios en latido fetal durante parto"]'),
('P03.819', 'Recién nacido afectado por alteraciones en el ritmo o la frecuencia cardiaca fetal (intrauterinas), no especificadas en cuanto al momento de inicio', 'Sin especificar', '["problemas ritmo cardiaco bebé", "arritmia fetal", "frecuencia cardiaca fetal alterada", "latidos fetales irregulares", "corazón del feto no suena bien", "alteración cardiaca fetal", "sufrimiento fetal sin especificar", "anomalía cardiaca en el útero", "ritmo fetal fuera de rango", "problemas de monitoreo del bebé", "fetal heart rate abnormal", "latido del bebé preocupante", "alteración del pulso fetal", "cardiología fetal alterada", "sospecha de sufrimiento fetal"]'),
('P03.82', 'Expulsión de meconio durante el parto', 'Sin especificar', '["bebé hizo caca adentro", "líquido amniótico teñido", "meconio en el líquido", "aspiración de meconio", "líquido verde", "bebé sucio de meconio", "expulsión de caca fetal", "sufrimiento fetal por meconio", "líquido amniótico meconial", "parto con líquido verde", "el bebé se hizo popó", "aspiró meconio al nacer", "riesgo por meconio", "líquido espeso y verde", "bebé manchado de meconio"]'),
('P03.89', 'Recién nacido afectado por otras complicaciones especificadas del trabajo de parto y parto', 'Sin especificar', '["complicaciones al nacer", "parto difícil", "problemas en el nacimiento", "parto traumático", "emergencia obstétrica", "bebé afectado por el parto", "complicaciones del parto no especificadas", "trabajo de parto complicado", "daño por el parto", "dificultades durante el nacimiento", "parto con imprevistos", "bebé con secuelas del parto", "eventos adversos en el parto", "problemas inesperados al nacer", "parto de riesgo"]'),
('P03.9', 'Recién nacido afectado por complicaciones del trabajo de parto y parto, no especificadas', 'Sin especificar', '["problemas al nacer", "parto complicado no especificado", "complicaciones obstétricas", "recién nacido con problemas del parto", "parto que salió mal", "bebé con complicaciones al nacer", "qué pasó en el parto", "nació con complicaciones", "parto con historia difícil", "dificultad al nacer", "no saben por qué fue difícil el parto", "problemas post-parto inmediato", "evento obstétrico", "bebé afectado por parto", "complicaciones médicas al nacer"]');
