INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('R46.0', 'Muy bajo nivel de higiene personal', 'Sin especificar', '["desaseado", "sucio", "cochino", "descuidado", "falta de baño", "mal olor", "andrajoso", "marrano", "chambón", "facha", "desaliñado", "abandono personal", "roñoso", "mugriento", "dejado"]'),
('R46.1', 'Apariencia personal extraña', 'Sin especificar', '["aspecto raro", "look extravagante", "se ve raro", "facha rara", "pinta extraña", "vestimenta bizarra", "aspecto descabellado", "estrafalario", "desentonado", "parece loco", "look inusual", "impresión extraña", "indumentaria rara", "aspecto estrafalario", "excéntrico"]'),
('R46.2', 'Conducta extraña e inexplicable', 'Sin especificar', '["comportamiento raro", "actúa raro", "raro", "loco", "actitud incomprensible", "comportamiento errático", "hace cosas raras", "rarito", "fuera de lugar", "conducta desubicada", "actuar sin sentido", "comportamiento extraño", "maneras raras", "actitud misteriosa", "comportamiento desconcertante"]'),
('R46.3', 'Exceso de actividad', 'Sin especificar', '["hiperactivo", "inquieto", "acelerado", "no para de moverse", "nervioso", "con mucha pila", "alterado", "excitado", "maníaco", "agitado", "batería alta", "inquietud motora", "impaciente", "acelerado", "hiperkinesia"]'),
('R46.4', 'Lentitud y poca capacidad de respuesta', 'Sin especificar', '["lento", "atontado", "adormilado", "lento de reflejos", "apático", "aletargado", "colgado", "empanado", "lenteja", "con poca chispa", "reacciona lento", "desconectado", "le cuesta responder", "modorra", "somnoliento"]'),
('R46.5', 'Suspicacia y evasividad notable', 'Sin especificar', '["desconfiado", "sospechoso", "paranoico", "evasivo", "se esconde", "no quiere hablar", "esquivo", "con miedo", "oculta algo", "alerta", "receloso", "no mira a los ojos", "misterioso", "cauteloso", "huye de la charla"]'),
('R46.6', 'Preocupación desproporcionada por sucesos que causan tensión', 'Sin especificar', '["estresado", "obsesivo", "se ahoga en un vaso de agua", "agobiado", "nervios a mil", "angustiado", "ansioso", "preocupado de más", "se estresa por todo", "drama", "siempre alerta", "tensión constante", "agobio", "tensión nerviosa", "sufre por anticipado"]'),
('R46.7', 'Verborrea y prolijidad que enmascaran el motivo del contacto', 'Sin especificar', '["habla mucho", "se va por las ramas", "mareador", "cháchara", "parlanchín", "hablador", "no va al punto", "da mil vueltas", "verborrágico", "habla hasta por los codos", "cantinflear", "largo de lengua", "marear la perdiz", "hablar de más", "círculos en el discurso"]'),
('R46.81', 'Comportamiento obsesivo-compulsivo', 'Sin especificar', '["obsesivo", "manías", "ritualista", "toc", "repetitivo", "muy ordenado", "maníaco con el orden", "necesidad de control", "revisa todo muchas veces", "ideas fijas", "obsesión", "compulsivo", "manía", "neuras", "comportamiento ritual"]'),
('R46.89', 'Otros síntomas y signos que afectan a la apariencia y al comportamiento', 'Sin especificar', '["actitud inusual", "cambio de forma de ser", "actitud rara", "comportamiento alterado", "apariencia cambiante", "otros síntomas conductuales", "rareza", "comportamiento atípico", "cambio de carácter", "conducta fuera de lo común", "signos de comportamiento", "variaciones en la apariencia", "desorden conductual", "problemas de conducta", "manifestaciones extrañas"]');
