INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('T59.0X1A', 'Efecto tóxico de óxidos de nitrógeno, accidental (no intencionado), contacto inicial', 'Sin especificar', '["intoxicación por gases", "envenenamiento por vapores", "inhalar óxidos de nitrógeno", "quemazón en pulmones", "tos por vapores químicos", "accidente industrial", "exposición a gases tóxicos", "falta de aire por químicos", "irritación pulmonar aguda", "emergencia ambiental", "inhalación de humos industriales"]'),
('T59.0X1D', 'Efecto tóxico de óxidos de nitrógeno, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["seguimiento por intoxicación", "control por inhalación de gases", "daño crónico por nitrógeno", "secuelas de inhalación", "tratamiento posterior a intoxicación", "revisión médica por vapores", "efectos persistentes de gases", "reexposición a químicos", "síntomas continuos por nitrógeno"]'),
('T59.0X1S', 'Efecto tóxico de óxidos de nitrógeno, accidental (no intencionado), secuela', 'Sin especificar', '["daño pulmonar crónico", "secuelas por envenenamiento", "fibrosis pulmonar por gases", "problemas respiratorios a largo plazo", "daño permanente por inhalación", "secuelas post-tóxicas", "discapacidad respiratoria", "consecuencias de exposición química"]'),
('T59.0X2A', 'Efecto tóxico de óxidos de nitrógeno, autolesión intencionada, contacto inicial', 'Sin especificar', '["intento de autoenvenenamiento", "inhalación voluntaria", "quitarse la vida con gases", "toxicidad provocada", "intento suicida por químicos", "inhalación deliberada de vapores"]'),
('T59.0X2D', 'Efecto tóxico de óxidos de nitrógeno, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["seguimiento médico post-intento", "control por intento suicida", "recuperación tras intoxicación voluntaria", "cuidado post-exposición"]'),
('T59.0X2S', 'Efecto tóxico de óxidos de nitrógeno, autolesión intencionada, secuela', 'Sin especificar', '["secuelas crónicas de intento de suicidio", "daños permanentes por gases", "cicatrices internas por inhalación deliberada"]'),
('T59.0X3A', 'Efecto tóxico de óxidos de nitrógeno, agresión, contacto inicial', 'Sin especificar', '["ataque con gases químicos", "envenenamiento provocado por terceros", "intoxicación criminal", "agresión con vapores", "ataque con óxidos de nitrógeno", "ataque químico"]'),
('T59.0X3D', 'Efecto tóxico de óxidos de nitrógeno, agresión, contacto sucesivo', 'Sin especificar', '["control médico post-ataque", "seguimiento tras agresión química", "recuperación de daño pulmonar por agresión"]'),
('T59.0X3S', 'Efecto tóxico de óxidos de nitrógeno, agresión, secuela', 'Sin especificar', '["secuelas tras ataque químico", "daño crónico tras agresión", "problemas de salud por ataque con gases"]'),
('T59.0X4A', 'Efecto tóxico de óxidos de nitrógeno, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["intoxicación de causa desconocida", "sospecha de envenenamiento", "inhalación de origen incierto", "exposición química inexplicable"]'),
('T59.0X4D', 'Efecto tóxico de óxidos de nitrógeno, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["seguimiento por intoxicación dudosa", "control de caso sospechoso", "evaluación posterior a exposición incierta"]'),
('T59.0X4S', 'Efecto tóxico de óxidos de nitrógeno, intencionalidad sin determinar, secuela', 'Sin especificar', '["secuelas post-exposición incierta", "complicaciones a largo plazo de origen desconocido"]'),
('T59.1X1A', 'Efecto tóxico de dióxido de azufre, accidental (no intencionado), contacto inicial', 'Sin especificar', '["inhalación de azufre", "gas de azufre", "irritación por vapores de azufre", "ahogo por gases", "quemazón en la garganta", "picazón de ojos por químicos", "accidente por dióxido de azufre"]'),
('T59.1X1D', 'Efecto tóxico de dióxido de azufre, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["revisión por inhalación de azufre", "control por vapores químicos", "seguimiento de irritación pulmonar"]'),
('T59.1X1S', 'Efecto tóxico de dióxido de azufre, accidental (no intencionado), secuela', 'Sin especificar', '["secuelas respiratorias del azufre", "bronquitis crónica química", "daño permanente en mucosas"]'),
('T59.1X2A', 'Efecto tóxico de dióxido de azufre, autolesión intencionada, contacto inicial', 'Sin especificar', '["intento suicida con azufre", "inhalación voluntaria de dióxido de azufre"]'),
('T59.1X2D', 'Efecto tóxico de dióxido de azufre, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["seguimiento post-intento de autoenvenenamiento"]'),
('T59.1X2S', 'Efecto tóxico de dióxido de azufre, autolesión intencionada, secuela', 'Sin especificar', '["consecuencias a largo plazo de inhalación de azufre"]'),
('T59.1X3A', 'Efecto tóxico de dióxido de azufre, agresión, contacto inicial', 'Sin especificar', '["ataque con gas de azufre", "agresión con químicos tóxicos"]'),
('T59.1X3D', 'Efecto tóxico de dióxido de azufre, agresión, contacto sucesivo', 'Sin especificar', '["evaluación de daños por agresión química"]'),
('T59.1X3S', 'Efecto tóxico de dióxido de azufre, agresión, secuela', 'Sin especificar', '["secuelas crónicas tras agresión con azufre"]'),
('T59.1X4A', 'Efecto tóxico de dióxido de azufre, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["sospecha de envenenamiento por azufre", "exposición inexplicable a azufre"]'),
('T59.1X4D', 'Efecto tóxico de dióxido de azufre, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["seguimiento de caso incierto por azufre"]'),
('T59.1X4S', 'Efecto tóxico de dióxido de azufre, intencionalidad sin determinar, secuela', 'Sin especificar', '["daño persistente de causa incierta (azufre)"]'),
('T59.2X1A', 'Efecto tóxico de formaldehído, accidental (no intencionado), contacto inicial', 'Sin especificar', '["intoxicación por formol", "inhalación de formaldehído", "vapores de formol", "irritación química por formol", "accidente en laboratorio con formol", "olores fuertes químicos"]'),
('T59.2X1D', 'Efecto tóxico de formaldehído, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["seguimiento por exposición a formol", "control de toxicidad por formaldehído"]'),
('T59.2X1S', 'Efecto tóxico de formaldehído, accidental (no intencionado), secuela', 'Sin especificar', '["secuelas por formol", "cáncer por formol (sospecha)", "daño crónico vías respiratorias por formol"]'),
('T59.2X2A', 'Efecto tóxico de formaldehído, autolesión intencionada, contacto inicial', 'Sin especificar', '["ingesta de formol", "intento suicida con formaldehído"]'),
('T59.2X2D', 'Efecto tóxico de formaldehído, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["revisión post-ingesta de formaldehído"]'),
('T59.2X2S', 'Efecto tóxico de formaldehído, autolesión intencionada, secuela', 'Sin especificar', '["secuelas orgánicas por ingesta de formol"]'),
('T59.2X3A', 'Efecto tóxico de formaldehído, agresión, contacto inicial', 'Sin especificar', '["ataque con formaldehído", "agresión con formol"]'),
('T59.2X3D', 'Efecto tóxico de formaldehído, agresión, contacto sucesivo', 'Sin especificar', '["seguimiento médico por ataque con formol"]'),
('T59.2X3S', 'Efecto tóxico de formaldehído, agresión, secuela', 'Sin especificar', '["daño permanente tras ataque con formol"]'),
('T59.2X4A', 'Efecto tóxico de formaldehído, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["intoxicación por formol de origen dudoso"]'),
('T59.2X4D', 'Efecto tóxico de formaldehído, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["revisión de caso de intoxicación por formaldehído"]'),
('T59.2X4S', 'Efecto tóxico de formaldehído, intencionalidad sin determinar, secuela', 'Sin especificar', '["secuelas post-exposición indeterminada a formol"]'),
('T59.3X1A', 'Efecto tóxico de gas lacrimógeno, accidental (no intencionado), contacto inicial', 'Sin especificar', '["gas pimienta", "gas lacrimógeno", "picor en los ojos por gas", "gases de protesta", "llanto incontrolable por gas", "quemazón en la piel por gas", "inhalar gas de policía", "ojos rojos y llorosos por gas"]'),
('T59.3X1D', 'Efecto tóxico de gas lacrimógeno, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["revisión ocular post-gas", "control por irritación persistente por gas"]'),
('T59.3X1S', 'Efecto tóxico de gas lacrimógeno, accidental (no intencionado), secuela', 'Sin especificar', '["conjuntivitis crónica por gas", "irritación persistente de vías aéreas"]'),
('T59.3X2A', 'Efecto tóxico de gas lacrimógeno, autolesión intencionada, contacto inicial', 'Sin especificar', '["exposición voluntaria a gas lacrimógeno", "autolesión con gas pimienta"]'),
('T59.3X2D', 'Efecto tóxico de gas lacrimógeno, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["control post-exposición voluntaria"]'),
('T59.3X2S', 'Efecto tóxico de gas lacrimógeno, autolesión intencionada, secuela', 'Sin especificar', '["secuelas tras uso deliberado de gas"]'),
('T59.3X3A', 'Efecto tóxico de gas lacrimógeno, agresión, contacto inicial', 'Sin especificar', '["ataque con gas pimienta", "agresión con gas lacrimógeno"]'),
('T59.3X3D', 'Efecto tóxico de gas lacrimógeno, agresión, contacto sucesivo', 'Sin especificar', '["seguimiento tras ataque con gas"]'),
('T59.3X3S', 'Efecto tóxico de gas lacrimógeno, agresión, secuela', 'Sin especificar', '["daño persistente tras agresión con gases"]'),
('T59.3X4A', 'Efecto tóxico de gas lacrimógeno, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["exposición a gas de origen desconocido", "intoxicación por gas dudosa"]'),
('T59.3X4D', 'Efecto tóxico de gas lacrimógeno, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["evaluación de síntomas post-gas"]'),
('T59.3X4S', 'Efecto tóxico de gas lacrimógeno, intencionalidad sin determinar, secuela', 'Sin especificar', '["secuelas respiratorias de origen incierto"]'),
('T59.4X1A', 'Efecto tóxico de gas de cloro, accidental (no intencionado), contacto inicial', 'Sin especificar', '["intoxicación por cloro", "gas de cloro en alberca", "inhalación de lejía", "vapores de cloro", "quemazón en la garganta por cloro", "accidente en piscina con cloro", "asfixia por cloro"]'),
('T59.4X1D', 'Efecto tóxico de gas de cloro, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["control médico por cloro", "seguimiento de daño pulmonar por cloro"]'),
('T59.4X1S', 'Efecto tóxico de gas de cloro, accidental (no intencionado), secuela', 'Sin especificar', '["daño pulmonar crónico por cloro", "secuelas respiratorias por lejía"]'),
('T59.4X2A', 'Efecto tóxico de gas de cloro, autolesión intencionada, contacto inicial', 'Sin especificar', '["intento de suicidio con cloro", "inhalación deliberada de cloro"]'),
('T59.4X2D', 'Efecto tóxico de gas de cloro, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["seguimiento tras intento de autoenvenenamiento"]'),
('T59.4X2S', 'Efecto tóxico de gas de cloro, autolesión intencionada, secuela', 'Sin especificar', '["daño permanente tras intento de cloro"]'),
('T59.4X3A', 'Efecto tóxico de gas de cloro, agresión, contacto inicial', 'Sin especificar', '["ataque con cloro", "agresión con gas tóxico"]'),
('T59.4X3D', 'Efecto tóxico de gas de cloro, agresión, contacto sucesivo', 'Sin especificar', '["revisión médica post-ataque con cloro"]'),
('T59.4X3S', 'Efecto tóxico de gas de cloro, agresión, secuela', 'Sin especificar', '["secuelas tras agresión con gas de cloro"]'),
('T59.4X4A', 'Efecto tóxico de gas de cloro, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["envenenamiento por cloro dudoso", "exposición incierta a gas"]'),
('T59.4X4D', 'Efecto tóxico de gas de cloro, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["control de intoxicación por cloro"]'),
('T59.4X4S', 'Efecto tóxico de gas de cloro, intencionalidad sin determinar, secuela', 'Sin especificar', '["daños post-cloro de origen incierto"]'),
('T59.5X1A', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, accidental (no intencionado), contacto inicial', 'Sin especificar', '["intoxicación por fluoruro", "quemadura química por fluoruro", "inhalación de gas flúor", "accidente industrial con flúor", "vapores tóxicos de ácido fluorhídrico"]'),
('T59.5X1D', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["seguimiento por exposición a fluoruro", "control de quemaduras químicas"]'),
('T59.5X1S', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, accidental (no intencionado), secuela', 'Sin especificar', '["daño tisular crónico por fluoruro", "secuelas óseas o pulmonares por flúor"]'),
('T59.5X2A', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, autolesión intencionada, contacto inicial', 'Sin especificar', '["inhalación deliberada de fluoruro", "intento suicida con ácido"]'),
('T59.5X2D', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["seguimiento tras intento de autoenvenenamiento"]'),
('T59.5X2S', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, autolesión intencionada, secuela', 'Sin especificar', '["daño permanente tras intento con fluoruro"]'),
('T59.5X3A', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, agresión, contacto inicial', 'Sin especificar', '["ataque con ácido fluorhídrico", "agresión con flúor"]'),
('T59.5X3D', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, agresión, contacto sucesivo', 'Sin especificar', '["revisión médica por agresión con flúor"]'),
('T59.5X3S', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, agresión, secuela', 'Sin especificar', '["secuelas por ataque con químicos"]'),
('T59.5X4A', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["intoxicación por flúor dudosa", "exposición incierta a fluoruros"]'),
('T59.5X4D', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["seguimiento por intoxicación por flúor"]'),
('T59.5X4S', 'Efecto tóxico de gas de flúor y fluoruro de hidrógeno, intencionalidad sin determinar, secuela', 'Sin especificar', '["secuelas post-fluoruro indeterminadas"]'),
('T59.6X1A', 'Efecto tóxico de sulfuro de hidrógeno, accidental (no intencionado), contacto inicial', 'Sin especificar', '["intoxicación por ácido sulfhídrico", "gas de alcantarilla", "inhalación de sulfuro de hidrógeno", "olor a huevo podrido", "asfixia por gases de drenaje", "accidente por gases tóxicos"]'),
('T59.6X1D', 'Efecto tóxico de sulfuro de hidrógeno, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["control por inhalación de gas de drenaje", "seguimiento neurológico tras gas"]'),
('T59.6X1S', 'Efecto tóxico de sulfuro de hidrógeno, accidental (no intencionado), secuela', 'Sin especificar', '["secuelas cerebrales por gas", "daño cognitivo post-asfixia"]'),
('T59.6X2A', 'Efecto tóxico de sulfuro de hidrógeno, autolesión intencionada, contacto inicial', 'Sin especificar', '["suicidio con gas de alcantarilla", "inhalación deliberada de sulfuro"]'),
('T59.6X2D', 'Efecto tóxico de sulfuro de hidrógeno, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["seguimiento post-intento suicida"]'),
('T59.6X2S', 'Efecto tóxico de sulfuro de hidrógeno, autolesión intencionada, secuela', 'Sin especificar', '["daño permanente tras intento suicida"]'),
('T59.6X3A', 'Efecto tóxico de sulfuro de hidrógeno, agresión, contacto inicial', 'Sin especificar', '["ataque con gases de drenaje", "envenenamiento provocado"]'),
('T59.6X3D', 'Efecto tóxico de sulfuro de hidrógeno, agresión, contacto sucesivo', 'Sin especificar', '["revisión médica por agresión con gases"]'),
('T59.6X3S', 'Efecto tóxico de sulfuro de hidrógeno, agresión, secuela', 'Sin especificar', '["secuelas tras ataque químico"]'),
('T59.6X4A', 'Efecto tóxico de sulfuro de hidrógeno, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["intoxicación por sulfuro dudosa", "exposición incierta a gases"]'),
('T59.6X4D', 'Efecto tóxico de sulfuro de hidrógeno, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["seguimiento de intoxicación incierta"]'),
('T59.6X4S', 'Efecto tóxico de sulfuro de hidrógeno, intencionalidad sin determinar, secuela', 'Sin especificar', '["daño post-gases de origen incierto"]'),
('T59.7X1A', 'Efecto tóxico de dióxido de carbono, accidental (no intencionado), contacto inicial', 'Sin especificar', '["intoxicación por CO2", "asfixia por falta de oxígeno", "inhalación de dióxido de carbono", "accidente en espacio confinado", "ahogo por gas", "hipoxia"]'),
('T59.7X1D', 'Efecto tóxico de dióxido de carbono, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["seguimiento tras asfixia", "control por hipoxia", "recuperación tras falta de aire"]'),
('T59.7X1S', 'Efecto tóxico de dióxido de carbono, accidental (no intencionado), secuela', 'Sin especificar', '["daño cerebral por hipoxia", "secuelas de asfixia", "problemas neurológicos crónicos"]'),
('T59.7X2A', 'Efecto tóxico de dióxido de carbono, autolesión intencionada, contacto inicial', 'Sin especificar', '["suicidio con CO2", "asfixia deliberada"]'),
('T59.7X2D', 'Efecto tóxico de dióxido de carbono, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["cuidado posterior a intento suicida"]'),
('T59.7X2S', 'Efecto tóxico de dióxido de carbono, autolesión intencionada, secuela', 'Sin especificar', '["secuelas post-intento suicida"]'),
('T59.7X3A', 'Efecto tóxico de dióxido de carbono, agresión, contacto inicial', 'Sin especificar', '["ataque con CO2", "intento de asfixia"]'),
('T59.7X3D', 'Efecto tóxico de dióxido de carbono, agresión, contacto sucesivo', 'Sin especificar', '["revisión post-ataque por asfixia"]'),
('T59.7X3S', 'Efecto tóxico de dióxido de carbono, agresión, secuela', 'Sin especificar', '["secuelas físicas tras intento de asfixia"]'),
('T59.7X4A', 'Efecto tóxico de dióxido de carbono, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["asfixia inexplicable", "intoxicación por gas dudosa"]'),
('T59.7X4D', 'Efecto tóxico de dióxido de carbono, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["seguimiento por intoxicación por CO2"]'),
('T59.7X4S', 'Efecto tóxico de dióxido de carbono, intencionalidad sin determinar, secuela', 'Sin especificar', '["secuelas de hipoxia indeterminada"]'),
('T59.811A', 'Efecto tóxico de humo, accidental (no intencionado), contacto inicial', 'Sin especificar', '["inhalación de humo", "intoxicación por fuego", "inhalar hollín", "quemaduras en vías respiratorias por humo", "ahogarse con el humo", "emergencia por incendio"]'),
('T59.811D', 'Efecto tóxico de humo, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["control pulmonar tras incendio", "seguimiento por inhalación de humo"]'),
('T59.811S', 'Efecto tóxico de humo, accidental (no intencionado), secuela', 'Sin especificar', '["daño pulmonar tras incendio", "fibrosis por inhalación de humo", "tos crónica post-incendio"]'),
('T59.812A', 'Efecto tóxico de humo, autolesión intencionada, contacto inicial', 'Sin especificar', '["intentar quemarse con humo", "inhalación deliberada de humo de incendio"]'),
('T59.812D', 'Efecto tóxico de humo, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["revisión médica post-incendio provocado"]'),
('T59.812S', 'Efecto tóxico de humo, autolesión intencionada, secuela', 'Sin especificar', '["secuelas de daño pulmonar deliberado"]'),
('T59.813A', 'Efecto tóxico de humo, agresión, contacto inicial', 'Sin especificar', '["ataque con humo", "provocar incendio para dañar"]'),
('T59.813D', 'Efecto tóxico de humo, agresión, contacto sucesivo', 'Sin especificar', '["seguimiento tras ataque con humo"]'),
('T59.813S', 'Efecto tóxico de humo, agresión, secuela', 'Sin especificar', '["secuelas pulmonares tras ataque"]'),
('T59.814A', 'Efecto tóxico de humo, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["inhalación de humo dudosa", "intoxicación por humo incierta"]'),
('T59.814D', 'Efecto tóxico de humo, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["evaluación de pulmones tras humo"]'),
('T59.814S', 'Efecto tóxico de humo, intencionalidad sin determinar, secuela', 'Sin especificar', '["secuelas pulmonares indeterminadas"]'),
('T59.891A', 'Efecto tóxico de otros gases, humos y vapores especificados, accidental (no intencionado), contacto inicial', 'Sin especificar', '["intoxicación por químicos industriales", "exposición accidental a vapores", "inhalación de químicos tóxicos", "accidente de laboratorio", "vapores tóxicos"]'),
('T59.891D', 'Efecto tóxico de otros gases, humos y vapores especificados, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["seguimiento por exposición química", "control de toxicidad"]'),
('T59.891S', 'Efecto tóxico de otros gases, humos y vapores especificados, accidental (no intencionado), secuela', 'Sin especificar', '["secuelas de inhalación química", "daño crónico por tóxicos"]'),
('T59.892A', 'Efecto tóxico de otros gases, humos y vapores especificados, autolesión intencionada, contacto inicial', 'Sin especificar', '["autoenvenenamiento con químicos", "intento suicida con gases"]'),
('T59.892D', 'Efecto tóxico de otros gases, humos y vapores especificados, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["seguimiento psiquiátrico-médico"]'),
('T59.892S', 'Efecto tóxico de otros gases, humos y vapores especificados, autolesión intencionada, secuela', 'Sin especificar', '["secuelas post-intento de suicidio"]'),
('T59.893A', 'Efecto tóxico de otros gases, humos y vapores especificados, agresión, contacto inicial', 'Sin especificar', '["ataque químico", "agresión con vapores tóxicos"]'),
('T59.893D', 'Efecto tóxico de otros gases, humos y vapores especificados, agresión, contacto sucesivo', 'Sin especificar', '["revisión médica post-ataque"]'),
('T59.893S', 'Efecto tóxico de otros gases, humos y vapores especificados, agresión, secuela', 'Sin especificar', '["daño permanente tras ataque"]'),
('T59.894A', 'Efecto tóxico de otros gases, humos y vapores especificados, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["exposición química inexplicable", "intoxicación dudosa"]'),
('T59.894D', 'Efecto tóxico de otros gases, humos y vapores especificados, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["seguimiento por intoxicación"]'),
('T59.894S', 'Efecto tóxico de otros gases, humos y vapores especificados, intencionalidad sin determinar, secuela', 'Sin especificar', '["secuelas de exposición incierta"]'),
('T59.91XA', 'Efecto tóxico de gases, humos y vapores no especificados, accidental (no intencionado), contacto inicial', 'Sin especificar', '["intoxicación por gas desconocido", "inhalación de vapores", "emergencia química", "no sé qué gas inhalé"]'),
('T59.91XD', 'Efecto tóxico de gases, humos y vapores no especificados, accidental (no intencionado), contacto sucesivo', 'Sin especificar', '["seguimiento médico por gas desconocido"]'),
('T59.91XS', 'Efecto tóxico de gases, humos y vapores no especificados, accidental (no intencionado), secuela', 'Sin especificar', '["secuelas de inhalación desconocida"]'),
('T59.92XA', 'Efecto tóxico de gases, humos y vapores no especificados, autolesión intencionada, contacto inicial', 'Sin especificar', '["intento de suicidio con gas", "autolesión por inhalación"]'),
('T59.92XD', 'Efecto tóxico de gases, humos y vapores no especificados, autolesión intencionada, contacto sucesivo', 'Sin especificar', '["seguimiento tras intento suicida"]'),
('T59.92XS', 'Efecto tóxico de gases, humos y vapores no especificados, autolesión intencionada, secuela', 'Sin especificar', '["secuelas post-intento suicida"]'),
('T59.93XA', 'Efecto tóxico de gases, humos y vapores no especificados, agresión, contacto inicial', 'Sin especificar', '["agresión con gas", "ataque con vapores"]'),
('T59.93XD', 'Efecto tóxico de gases, humos y vapores no especificados, agresión, contacto sucesivo', 'Sin especificar', '["revisión médica post-ataque"]'),
('T59.93XS', 'Efecto tóxico de gases, humos y vapores no especificados, agresión, secuela', 'Sin especificar', '["secuelas tras agresión"]'),
('T59.94XA', 'Efecto tóxico de gases, humos y vapores no especificados, intencionalidad sin determinar, contacto inicial', 'Sin especificar', '["exposición a vapores dudosa", "intoxicación inexplicable"]'),
('T59.94XD', 'Efecto tóxico de gases, humos y vapores no especificados, intencionalidad sin determinar, contacto sucesivo', 'Sin especificar', '["seguimiento de intoxicación incierta"]'),
('T59.94XS', 'Efecto tóxico de gases, humos y vapores no especificados, intencionalidad sin determinar, secuela', 'Sin especificar', '["secuelas de origen desconocido"]');
