INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('N46.01', 'Azoospermia orgánica', 'Sin especificar', '["ausencia de espermatozoides", "esterilidad masculina", "infertilidad congénita", "no produce esperma", "problemas para concebir", "esperma vacío", "eyaculación sin espermatozoides", "falla en la producción de esperma", "infertilidad primaria", "conteo de esperma cero", "problema en testículos", "infertilidad permanente", "azoospermia", "falla testicular"]'),
('N46.021', 'Azoospermia debida a tratamiento con fármacos', 'Sin especificar', '["infertilidad por medicamentos", "esperma bajo por pastillas", "esterilidad secundaria a fármacos", "efectos secundarios medicamentos fertilidad", "daño espermático por medicinas", "quimioterapia y fertilidad", "azoospermia inducida", "medicamentos que matan el esperma", "esterilidad por tratamiento médico", "fármacos afectan esperma", "infertilidad provocada por drogas", "conteo cero por fármacos"]'),
('N46.022', 'Azoospermia debida a infección', 'Sin especificar', '["azoospermia por infección", "esterilidad tras infección", "orquitis e infertilidad", "infección testicular", "inflamación de testículos y esperma", "daño espermático por enfermedad", "secuelas de ETS en fertilidad", "falla espermática por bacteria", "inflamación gónadas", "infertilidad post-infección", "esperma afectado por inflamación", "epididimitis crónica"]'),
('N46.023', 'Azoospermia debida a obstrucción de conductos deferentes', 'Sin especificar', '["conductos bloqueados", "vasos deferentes obstruidos", "azoospermia obstructiva", "obstrucción espermática", "tubos tapados", "conductos cerrados", "vasectomía natural", "infertilidad por bloqueo", "eyaculación seca", "problemas de paso de esperma", "espermatozoides atrapados", "conductos deferentes tapados"]'),
('N46.024', 'Azoospermia debida a radiación', 'Sin especificar', '["radioterapia e infertilidad", "esperma dañado por radiación", "esterilidad por rayos", "efectos de radioterapia en testículos", "conteo cero por radiación", "daño testicular radioinducido", "esterilidad por rayos X", "azoospermia post-radiación", "incapacidad de producir esperma por radiación", "falla testicular por exposición radiactiva"]'),
('N46.025', 'Azoospermia debida a enfermedad sistémica', 'Sin especificar', '["infertilidad por diabetes", "falla de órganos y esperma", "enfermedad crónica e infertilidad", "azoospermia por desorden sistémico", "problemas de salud general y esperma", "insuficiencia orgánica e infertilidad", "esperma bajo por enfermedades graves", "metabolismo y fertilidad", "infertilidad secundaria a enfermedad", "baja calidad espermática por salud general"]'),
('N46.029', 'Azoospermia debida a otras causas extratesticulares', 'Sin especificar', '["azoospermia no testicular", "causas hormonales infertilidad", "problemas extratesticulares", "falla en producción hormonal esperma", "trastornos endocrinos fertilidad", "azoospermia hormonal", "desequilibrio de hormonas y esperma", "infertilidad por causas externas", "problemas en glándulas sexuales", "causas ajenas al testículo"]'),
('N46.11', 'Oligospermia orgánica', 'Sin especificar', '["pocos espermatozoides", "conteo espermático bajo", "bajo conteo de esperma", "oligospermia", "poca cantidad de semen", "esperma pobre", "infertilidad masculina leve", "espermatozoides insuficientes", "baja densidad espermática", "problemas de fertilidad hombre", "pocos bichitos", "espermograma bajo"]'),
('N46.121', 'Oligospermia debida a tratamiento con fármacos', 'Sin especificar', '["conteo bajo por medicamentos", "poca cantidad de esperma por fármacos", "efecto de medicinas en conteo", "esterilidad farmacológica", "menos espermatozoides por drogas", "fármacos afectan producción esperma", "baja densidad por tratamiento", "reducción espermática medicamentosa", "efectos secundarios en el esperma", "pastillas bajan conteo de esperma"]'),
('N46.122', 'Oligospermia debida a infección', 'Sin especificar', '["conteo bajo por infección", "infección y baja cantidad de esperma", "oligospermia infecciosa", "inflamación testicular y poco esperma", "orquitis y baja fertilidad", "infección de vías seminales", "daño infeccioso conteo espermático", "baja cantidad por bacterias", "secuelas de infecciones en el semen", "reducción de espermatozoides por inflamación"]'),
('N46.123', 'Oligospermia debida a obstrucción de conductos deferentes', 'Sin especificar', '["obstrucción parcial de conductos", "bloqueo parcial deferentes", "oligospermia obstructiva", "dificultad paso de espermatozoides", "conductos parcialmente tapados", "baja cantidad eyaculación por obstrucción", "problema de paso de esperma", "espermatozoides lentos por bloqueo", "flujo espermático reducido", "conductos estrechos y poco esperma"]'),
('N46.124', 'Oligospermia debida a radiación', 'Sin especificar', '["conteo bajo por radiación", "poca cantidad de esperma por rayos", "daño por radioterapia en conteo", "reducción espermática radioinducida", "esterilidad parcial por radiación", "baja densidad espermática por rayos", "efecto acumulativo radiación fertilidad", "menos esperma por exposición rayos", "oligospermia post-radiación"]'),
('N46.125', 'Oligospermia debida a enfermedad sistémica', 'Sin especificar', '["bajo conteo por enfermedades", "oligospermia por diabetes", "salud general y conteo de esperma", "enfermedades crónicas e infertilidad", "baja producción por enfermedad", "desgaste físico y poco esperma", "insuficiencia sistémica y esperma", "conteo bajo por salud", "daño metabólico fertilidad", "impacto enfermedades en el semen"]'),
('N46.129', 'Oligospermia debida a otras causas extratesticulares', 'Sin especificar', '["conteo bajo por hormonas", "problemas hormonales y esperma", "oligospermia hormonal", "causas externas bajo esperma", "falta de hormonas espermáticas", "problema endocrino fertilidad", "baja cantidad por factores extratesticulares", "desorden glandular y poco esperma", "infertilidad hormonal hombre", "conteo espermático reducido por causas externas"]'),
('N46.8', 'Otros tipos de infertilidad masculina', 'Sin especificar', '["problemas esperma movilidad", "esperma lento", "astenozoospermia", "teratozoospermia", "esperma con formas anormales", "mala calidad de esperma", "eyaculación retrógrada", "problemas de erección e infertilidad", "eyaculación precoz e infertilidad", "problemas de concepción hombre", "infertilidad idiopática", "no puede tener hijos", "descartar infertilidad"]'),
('N46.9', 'Infertilidad masculina, no especificada', 'Sin especificar', '["problemas para tener hijos", "no puedo embarazar a mi mujer", "infertilidad hombre", "problema de fertilidad", "esterilidad masculina", "dificultad para concebir", "no sale el embarazo", "estéril", "no soy fértil", "estudio de fertilidad hombre", "problemas del varón para ser padre", "infertilidad causas desconocidas"]');
