INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L72.0', 'Quiste epidérmico', 'Sin especificar', '["bolita en la piel", "quiste bajo la piel", "grano duro", "quiste de queratina", "tumor benigno piel", "bulto encapsulado", "bola de grasa", "quiste epidermoide", "quiste cutáneo", "protuberancia piel", "quiste con mal olor", "bulto que drena", "absceso pequeño", "nódulo en la piel", "bolita de carne"]'),
('L72.11', 'Quiste piloso', 'Sin especificar', '["quiste triquilemal", "bolita en el cuero cabelludo", "bulto en la cabeza", "quiste en la nuca", "bola de grasa en el pelo", "quiste del folículo", "quiste piloso cabeza", "bulto duro en el cráneo", "quiste de queratina capilar", "bolita que no duele", "quiste en el cuero cabelludo", "tumorcito en el pelo", "quiste sebáceo cabeza"]'),
('L72.12', 'Quiste tricodérmico', 'Sin especificar', '["quiste proliferante", "quiste triquilemal proliferante", "bulto cutáneo", "nódulo dérmico", "quiste folicular", "bolita en la espalda", "crecimiento bajo la piel", "tumor anexial", "masa subcutánea", "quiste con pus", "bulto inflamado", "quiste que crece", "quiste piloso complicado"]'),
('L72.2', 'Esteatocistoma múltiple', 'Sin especificar', '["quistes múltiples", "bolitas por todo el cuerpo", "quistes en el pecho", "muchas bolitas de grasa", "enfermedad de los quistes", "quistes foliculares diseminados", "pápulas amarillentas", "bultitos en el torso", "quistes de sebo múltiples", "bolitas en los brazos", "problema de piel con quistes", "quistes benignos generalizados"]'),
('L72.3', 'Quiste sebáceo', 'Sin especificar', '["bola de grasa", "grano de grasa", "quiste de sebo", "bulto con pus", "bolita en la cara", "bolita en la espalda", "quiste infectado", "barro enterrado", "quiste que se revienta", "mal olor del quiste", "bulto en la axila", "bolita en la oreja", "quiste que drena", "absceso de grasa", "punto de grasa"]'),
('L72.8', 'Otros tipos de quistes foliculares de la piel y del tejido subcutáneo', 'Sin especificar', '["bolita rara en la piel", "bulto subcutáneo", "quiste folicular inespecífico", "nódulo de piel", "tumor benigno subcutáneo", "bolita de tejido", "bulto que no desaparece", "quiste complejo", "protuberancia bajo la piel", "masa de grasa", "quiste inflamado", "bolita que duele"]'),
('L72.9', 'Quiste folicular de la piel y del tejido subcutáneo, no especificado', 'Sin especificar', '["bulto en la piel", "bolita bajo la piel", "quiste cutáneo", "bola de grasa", "quiste", "protuberancia dérmica", "nódulo subcutáneo", "bolita", "quiste sin nombre", "bulto en el cuerpo", "bolita de carne", "masa en la piel", "quiste que sale de la nada", "bolita que ha crecido"]');
