INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('X99.0XXA', 'Agresión con vidrio filoso, contacto inicial', 'Sin especificar', '["corte con vidrio", "cristalazo", "herida de vidrio", "vidrio enterrado", "cortada con botella", "vidrio en la piel", "ataque con vidrio", "lesión por vidrio", "tajo con vidrio", "cristal en la herida", "emergencia corte vidrio", "sangrado por vidrio", "vidrio roto", "agresión con cristal", "vidrio filoso"]'),
('X99.0XXD', 'Agresión con vidrio filoso, contacto sucesivo', 'Sin especificar', '["curación corte vidrio", "seguimiento herida cristal", "revisión herida vidrio", "infección por vidrio", "retirada de vidrios", "lavado de herida vidrio", "evolución corte vidrio", "tratamiento corte cristal", "cuidado herida por vidrio", "control de sutura vidrio", "revisión de tajo", "herida infectada por vidrio", "limpieza de cristal", "curar herida profunda", "seguimiento médico vidrio"]'),
('X99.0XXS', 'Agresión con vidrio filoso, secuela', 'Sin especificar', '["cicatriz de vidrio", "queloide por corte", "daño nervioso vidrio", "secuelas de corte", "cicatriz queloide", "mala cicatrización", "discapacidad por vidrio", "herida antigua vidrio", "fibrosis cicatrizal", "cicatriz queloide brazo", "adherencias por corte", "pérdida de sensibilidad", "cicatriz hipertrófica", "dolor post corte", "deformidad por vidrio"]'),
('X99.1XXA', 'Agresión con un cuchillo, contacto inicial', 'Sin especificar', '["apuñalamiento", "ataque con cuchillo", "navajazo", "picazón con cuchillo", "herida de arma blanca", "cortada con cuchillo", "tajo", "cuchillada", "agresión con navaja", "herida abierta", "sangrado por arma blanca", "filo", "fierrazo", "puñalada", "herida cortante"]'),
('X99.1XXD', 'Agresión con un cuchillo, contacto sucesivo', 'Sin especificar', '["cura de puñalada", "seguimiento herida cuchillo", "limpieza de herida profunda", "control de sutura", "revisión de navajazo", "infección de herida", "evolución de arma blanca", "curación de tajo", "manejo de herida abierta", "cuidado de puntos", "tratamiento post apuñalamiento", "revisión de drenaje", "seguimiento hospitalario", "curar herida profunda", "cuidado de cicatriz inicial"]'),
('X99.1XXS', 'Agresión con un cuchillo, secuela', 'Sin especificar', '["cicatriz de arma blanca", "cicatriz de puñalada", "daño interno por cuchillo", "secuelas de apuñalamiento", "cicatriz grande", "queloide", "pérdida de función", "lesión muscular permanente", "dolor crónico por herida", "mala cicatrización", "fibrosis", "daño en nervios", "cicatriz queloide", "deformidad por corte", "cicatriz de navajazo"]'),
('X99.2XXA', 'Agresión con espada o daga, contacto inicial', 'Sin especificar', '["estocada", "ataque con daga", "herida por espada", "tajo de sable", "agresión con arma blanca larga", "pinche", "espadazo", "herida penetrante", "daga en el cuerpo", "ataque con acero", "traumatismo por arma blanca", "lesión por sable", "corte profundo", "herida de daga", "acero en el cuerpo"]'),
('X99.2XXD', 'Agresión con espada o daga, contacto sucesivo', 'Sin especificar', '["tratamiento herida por espada", "cura de estocada", "seguimiento daga", "limpieza herida profunda", "infección por arma larga", "control de puntos", "revisión de tajo", "cuidado de herida penetrante", "evolución de herida", "curar espadazo", "seguimiento post agresión", "revisión de drenaje", "tratamiento médico de herida", "manejo de cicatriz", "curación post quirúrgica"]'),
('X99.2XXS', 'Agresión con espada o daga, secuela', 'Sin especificar', '["cicatriz de estocada", "daño tisular permanente", "cicatriz de daga", "pérdida de movilidad", "secuela de arma blanca", "fibrosis muscular", "cicatriz hipertrófica", "daño nervioso", "atrofia post herida", "cicatriz profunda", "adherencias internas", "dolor crónico", "deformidad cicatrizal", "cicatriz queloide", "limitación funcional"]'),
('X99.8XXA', 'Agresión con otro objeto puntiagudo, contacto inicial', 'Sin especificar', '["pinchazo", "picadura", "ataque con objeto punzante", "herida por punzón", "herida con alambre", "agresión con destornillador", "estocada con objeto", "objeto enterrado", "punzada", "herida perforante", "lesión por punta", "ataque con metal", "herida con clavos", "objeto puntiagudo", "lesión por punción"]'),
('X99.8XXD', 'Agresión con otro objeto puntiagudo, contacto sucesivo', 'Sin especificar', '["cura de pinchazo", "infección de herida punzante", "seguimiento de punzada", "limpieza de herida", "revisión de lesión por punta", "cura de herida", "control de infección", "tratamiento de herida pequeña", "revisión de sutura", "cuidado de punción", "evolución de herida perforante", "cuidado de orificio", "revisión médica", "curar herida profunda", "manejo de punzada"]'),
('X99.8XXS', 'Agresión con otro objeto puntiagudo, secuela', 'Sin especificar', '["cicatriz por punción", "cicatriz de pinchazo", "fibrosis local", "adherencia en piel", "cicatriz queloide", "daño residual", "dolor local post herida", "cicatriz interna", "deformidad puntual", "pérdida de sensibilidad", "tejido cicatrizal", "cicatriz pequeña", "fibrosis cicatrizal", "molestia en la cicatriz", "secuela de punción"]'),
('X99.9XXA', 'Agresión con objeto punzante no especificado, contacto inicial', 'Sin especificar', '["herida por objeto desconocido", "ataque con punta", "herida extraña", "objeto enterrado en la piel", "picotazo", "agresión con algo afilado", "punzada no especificada", "herida punzocortante", "lesión por objeto extraño", "corte desconocido", "pinchazo profundo", "ataque con instrumento", "agresión con punta", "herida de arma desconocida", "punzón"]'),
('X99.9XXD', 'Agresión con objeto punzante no especificado, contacto sucesivo', 'Sin especificar', '["cura de herida punzante", "seguimiento de objeto desconocido", "infección de herida", "limpieza de herida punzocortante", "revisión de herida", "control de evolución", "curación de lesión", "cuidado de puntos", "seguimiento post ataque", "revisión de drenaje", "tratamiento de herida punzante", "cura de punzada", "limpieza profunda", "manejo médico de herida", "control de cicatriz"]'),
('X99.9XXS', 'Agresión con objeto punzante no especificado, secuela', 'Sin especificar', '["cicatriz punzocortante", "secuelas de herida", "cicatriz de objeto", "fibrosis por herida", "cicatriz queloide", "dolor crónico en la zona", "daño tisular residual", "cicatriz hipertrófica", "deformidad en piel", "adherencias cicatrizales", "pérdida de sensibilidad", "cicatriz por ataque", "tejido fibroso", "secuela funcional", "cicatriz de punzada"]');
