INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q89.01', 'Asplenia (congénita)', 'Sin especificar', '["falta de bazo", "nacido sin bazo", "ausencia de bazo", "bazo ausente", "agenesia esplénica", "defecto del bazo al nacer", "bazo inexistente", "problemas de bazo congénitos", "sin bazo", "malformación esplénica", "bazo atrofiado", "bazo no desarrollado", "hipoplasia esplénica", "defecto congénito bazo"]'),
('Q89.09', 'Malformaciones congénitas del bazo', 'Sin especificar', '["bazo deforme", "bazo anormal", "problemas en el bazo al nacer", "bazo pequeño", "bazo grande congénito", "poliesplenia", "bazo supernumerario", "bazo accesorio", "malformación de bazo", "bazo raro", "defectos esplénicos", "bazo de forma extraña", "anomalía del bazo", "bazo congénito", "bazo desplazado"]'),
('Q89.1', 'Malformaciones congénitas de las glándulas suprarrenales', 'Sin especificar', '["problemas de glándulas suprarrenales", "fallo en las suprarrenales al nacer", "defecto en glándulas arriba de los riñones", "glándulas suprarrenales anormales", "displasia suprarrenal", "malformación glándulas adrenal", "hiperplasia adrenal congénita", "problemas hormonales congénitos", "glándulas renales mal formadas", "defecto en hormonas suprarrenales", "anomalía glándula adrenal", "suprarrenales deformes", "desarrollo anormal de suprarrenales", "enfermedad de glándulas de riñón", "problema en adrenales"]'),
('Q89.2', 'Malformaciones congénitas de otras glándulas endocrinas', 'Sin especificar', '["problema de hormonas congénito", "glándulas mal formadas", "problema de tiroides congénito", "anomalía glandular", "fallo en glándulas endocrinas", "desarrollo anormal glandular", "problema hormonal de nacimiento", "defecto sistema endocrino", "glándula defectuosa al nacer", "displasia glandular", "malformación de hipófisis", "malformación de paratiroides", "problema en el sistema de hormonas", "glándulas atrofiadas al nacer", "anomalía congénita de glándulas"]'),
('Q89.3', 'Situs inversus', 'Sin especificar', '["órganos al revés", "corazón en el lado derecho", "órganos cambiados de lugar", "transposición de órganos", "espejo visceral", "órganos invertidos", "hígado a la izquierda", "dextrocardia", "cuerpo invertido", "situs invertido", "anomalía de posición de órganos", "órganos en espejo", "visceras al revés", "ubicación invertida de órganos", "corazón a la derecha"]'),
('Q89.4', 'Hermanos siameses o unidos', 'Sin especificar', '["gemelos unidos", "siameses", "gemelos pegados", "hermanos unidos", "gemelos conectados", "gemelos fusionados", "gemelos que comparten cuerpo", "bebés unidos", "gemelos pegaditos", "hermanitos unidos", "embarazo de gemelos unidos", "gemelos nacidos juntos", "hermanos gemelos conectados", "bebés gemelos pegados", "gemelos siameses unidos"]'),
('Q89.7', 'Malformaciones congénitas múltiples no clasificados bajo otro concepto', 'Sin especificar', '["muchas malformaciones", "varios defectos al nacer", "deformidades múltiples", "problemas congénitos raros", "anomalías congénitas diversas", "síndrome con muchos defectos", "problemas múltiples desde nacimiento", "malformaciones congénitas complejas", "defecto de nacimiento múltiple", "varios problemas físicos al nacer", "anomalías múltiples no especificadas", "malformaciones de nacimiento variadas", "problemas congénitos combinados", "defectos múltiples congénitos", "varias malformaciones al nacer"]'),
('Q89.8', 'Otras malformaciones congénitas especificadas', 'Sin especificar', '["defectos de nacimiento raros", "otras deformidades congénitas", "malformaciones raras", "anomalías congénitas específicas", "defectos congénitos extraños", "problemas de nacimiento no comunes", "malformación congénita especial", "anomalía de nacimiento poco frecuente", "problemas físicos desde el nacimiento", "deformación de nacimiento especificada", "malformación extraña", "problemas de nacimiento clasificados", "anomalía congénita puntual", "deformidad de nacimiento rara", "defectos congénitos específicos"]'),
('Q89.9', 'Malformación congénita, no especificada', 'Sin especificar', '["defecto de nacimiento", "problema al nacer", "deformidad congénita", "problema de nacimiento", "anomalía congénita", "bebé con malformación", "defecto físico de nacimiento", "anomalía de nacimiento", "problema físico al nacer", "defecto de nacimiento general", "deformación desde nacimiento", "malformación de nacimiento", "problema al nacer no definido", "defecto congénito sin especificar", "anomalía al nacer"]');
