INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q39.0', 'Atresia esofágica sin fístula', 'Sin especificar', '["esófago cerrado", "no puede tragar el bebé", "bebé no pasa leche", "esófago obstruido congénito", "atresia del tubo digestivo", "problema al nacer esófago", "baba constante bebé", "bebé babea mucho al nacer", "esófago que no conecta", "fallo desarrollo esófago", "no pasa el alimento", "obstrucción esofágica recién nacido", "malformación del esófago", "bebé escupe todo", "atresia sin comunicación"]'),
('Q39.1', 'Atresia del esófago con fístula traqueoesofágica', 'Sin especificar', '["conexión esófago tráquea", "bebé se ahoga al comer", "fístula al nacer", "malformación traqueoesofágica", "bebé cianótico al comer", "problemas respiratorios al succionar", "esófago conectado a pulmones", "tos al amamantar bebé", "atresia con fístula", "paso de leche a pulmones", "se le mete la leche al pulmón", "bebé con burbujas de baba", "obstrucción esófago con comunicación", "dificultad tragar y respirar", "bebé con atragantamiento congénito"]'),
('Q39.2', 'Fístula traqueoesofágica congénita sin atresia', 'Sin especificar', '["fístula en H", "comunicación esófago tráquea", "bebé tose al tomar leche", "se le va la comida al pulmón", "problema de conexión esofágica", "neumonía por aspiración bebé", "toses raras al comer", "fístula traqueoesofágica tipo H", "esófago comunica con vía aérea", "paso de aire al estómago", "bebé se pone morado al comer", "deglución difícil congénita", "aire en la guata del bebé", "molestias al pasar leche", "anomalía esófago congénita"]'),
('Q39.3', 'Estenosis congénita y estrechez del esófago', 'Sin especificar', '["esófago estrecho", "dificultad para tragar sólido", "comida se queda atascada", "esófago muy fino", "obstrucción parcial esófago", "estenosis de nacimiento", "bebé devuelve la comida", "problemas para pasar comida", "esófago estrechado", "cuello apretado", "dolor al tragar niño", "atresia esofágica parcial", "estrechez esofágica congénita", "comida se devuelve", "bebé no tolera sólidos"]'),
('Q39.4', 'Membrana esofágica', 'Sin especificar', '["telita en el esófago", "membrana en la garganta", "comida se atora en el pecho", "obstrucción por membrana", "esófago con banda", "dificultad tragar membrana", "tejido extra en esófago", "sensación de cuerpo extraño garganta", "anillo esofágico", "red en el esófago", "problemas de deglución", "obstrucción esofágica benigna", "membrana congénita", "disfagia por membrana", "se me atora la comida"]'),
('Q39.5', 'Dilatación congénita del esófago', 'Sin especificar', '["esófago grande", "esófago dilatado congénito", "megaesófago", "esófago ensanchado", "problemas de movimiento del esófago", "esófago que no cierra", "esófago con bolsa", "mala motilidad esofágica", "esófago muy ancho", "deglución lenta", "regurgitación congénita", "esófago relajado", "esófago con forma extraña", "obstrucción distal", "megaesófago primario"]'),
('Q39.6', 'Divertículo congénito del esófago', 'Sin especificar', '["bolsa en el esófago", "esófago con hueco", "divertículo en la garganta", "comida se guarda en el cuello", "aliento feo por comida estancada", "bulto en el esófago", "esófago con saco", "divertículo de nacimiento", "problemas de tragar alimentos", "acumulación de comida esófago", "bolsa esofágica", "esófago malformado", "regurgitación de comida vieja", "bulto al tragar", "divertículo esofágico congénito"]'),
('Q39.8', 'Otras malformaciones congénitas del esófago', 'Sin especificar', '["malformación del tubo del comer", "defecto congénito esófago", "problema en el esófago al nacer", "variación anatómica esófago", "esófago corto", "esófago duplicado", "anomalía esofágica rara", "defecto desarrollo esófago", "esófago raro", "problemas digestivos neonatales", "complicación esofágica congénita", "esófago de forma anormal", "malformación del tracto superior", "alteración congénita esófago", "esófago con tejido ectópico"]'),
('Q39.9', 'Malformación congénita del esófago, no especificada', 'Sin especificar', '["problemas al nacer para tragar", "defecto en el esófago", "bebé no puede comer bien", "malformación esofágica", "enfermedad del esófago recién nacido", "problema digestivo al nacer", "desarrollo anormal esófago", "esófago con falla", "falla en el sistema digestivo superior", "bebé con problemas para succionar", "anomalía esófago no definida", "problemas de garganta congénitos", "condición esofágica congénita", "defecto del tracto digestivo", "bebé con malformación interna"]');
