INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('F52.0', 'Trastorno de deseo sexual hipoactivo', 'Sin especificar', '["falta de ganas", "no tengo libido", "bajo deseo sexual", "frigidez", "desgano sexual", "cero ganas de sexo", "apetito sexual bajo", "poca líbido", "aburrimiento sexual", "no se me antoja", "no tengo ganas", "frialdad sexual", "desinterés sexual", "apagón sexual", "sin ganas de nada"]'),
('F52.1', 'Trastorno de aversión sexual', 'Sin especificar', '["asco al sexo", "rechazo al acto sexual", "fobia al sexo", "miedo al sexo", "repulsión sexual", "no me gusta que me toquen", "evitación sexual", "horror al sexo", "sentirse sucio tras sexo", "angustia al tener relaciones", "repulsión al contacto físico", "bloqueo sexual", "aversión al acto íntimo"]'),
('F52.21', 'Trastorno eréctil masculino', 'Sin especificar', '["impotencia", "no se me levanta", "se me baja", "disfunción eréctil", "miembro flácido", "no me responde el aparato", "pene blando", "no tengo erección", "problemas de erección", "la tengo muerta", "falla el sistema", "no se pone dura", "se me apaga", "impotencia sexual"]'),
('F52.22', 'Trastorno de excitación sexual femenino', 'Sin especificar', '["falta de lubricación", "se me seca", "no me excito", "poca humedad", "no me lubrico", "sequedad íntima", "frialdad", "falta de respuesta sexual", "no me prendo", "no siento nada al tocarme", "problemas de excitación", "anestesia sexual", "cuerpo no responde", "sequedad vaginal"]'),
('F52.31', 'Trastorno del orgasmo femenino', 'Sin especificar', '["anorgasmia", "no llego al clímax", "no puedo terminar", "no tengo orgasmos", "me quedo a medias", "no alcanzo el pico", "dificultad para correrse", "no veo estrellas", "mi pareja no termina", "se me corta el orgasmo", "incapacidad de llegar al final", "nunca termino", "no siento el orgasmo"]'),
('F52.32', 'Trastorno del orgasmo masculino', 'Sin especificar', '["eyaculación retardada", "no puedo eyacular", "me cuesta correrse", "no llego al final", "no eyaculo", "tardo demasiado", "pene sin sensibilidad", "no termino", "bloqueo al eyacular", "inorgasmia masculina", "no alcanzo el clímax", "eyaculación ausente", "poca sensibilidad al final"]'),
('F52.4', 'Eyaculación precoz', 'Sin especificar', '["me vengo rápido", "se me sale rápido", "eyaculación veloz", "no aguanto nada", "termino enseguida", "soy un rapidín", "acabo muy rápido", "eyaculación antes de tiempo", "no duro nada", "soy de gatillo fácil", "me vine muy rápido", "descontrol eyaculatorio", "prematurez al eyacular"]'),
('F52.5', 'Vaginismo no debido a sustancia ni afección fisiológica conocida', 'Sin especificar', '["dolor al penetrar", "se me cierra todo", "dolor al tener sexo", "no puedo tener relaciones", "me duele la entrada", "contracción vaginal", "no entra nada", "dolor al intentar penetración", "imposibilidad de penetrar", "espasmo vaginal", "cierre involuntario", "dolor vaginal insoportable"]'),
('F52.6', 'Dispareunia no debida a sustancia ni afección fisiológica conocida', 'Sin especificar', '["coito doloroso", "me duele al hacerlo", "dolor al intimar", "penetracion dolorosa", "ardor durante el sexo", "pinchazos al tener relaciones", "dolor en el fondo", "sentir dolor al tener sexo", "sexo doloroso", "dolor en el coito", "punzadas durante la penetración"]'),
('F52.8', 'Otras disfunciones sexuales no debidas a sustancia ni afección fisiológica conocida', 'Sin especificar', '["problemas sexuales", "fallas en la intimidad", "dificultad sexual", "cosas raras en el sexo", "alteración sexual", "no va bien mi vida sexual", "malestar en el acto sexual", "incapacidad sexual", "problemas con mi pareja sexual", "desorden sexual", "trastornos de la vida sexual"]'),
('F52.9', 'Disfunción sexual no especificada no debida a sustancia ni afección fisiológica conocida', 'Sin especificar', '["problemas de cama", "no sé qué me pasa", "algo falla en mi sexo", "no disfruto el sexo", "dificultades con mi pareja", "trastorno sexual", "no me siento bien teniendo sexo", "problemas en el catre", "mal funcionamiento sexual", "dificultad al tener encuentros"]');
