INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D56.0', 'Alfa talasemia', 'Sin especificar', '["anemia hereditaria", "anemia mediterránea", "problema de sangre", "sangre débil", "anemia genética", "anemia crónica", "hemoglobina baja", "cansancio extremo", "palidez", "falta de hierro", "anemia severa", "trastorno sanguíneo", "anemia congénita", "fatiga crónica", "anemia de herencia"]'),
('D56.1', 'Beta talasemia', 'Sin especificar', '["anemia de Cooley", "anemia mediterránea", "anemia grave", "sangre que no oxigena", "anemia heredada", "anemia de los niños", "hemoglobina defectuosa", "anemia falciforme", "palidez extrema", "ictericia", "anemia severa", "cansancio constante", "dolor de huesos", "anemia crónica", "defecto genético de sangre"]'),
('D56.2', 'Talasemia delta-beta', 'Sin especificar', '["anemia mixta", "anemia hereditaria", "anemia mediterránea", "trastorno de hemoglobina", "sangre pobre", "fatiga", "palidez", "anemia persistente", "problema genético de sangre", "anemia rara", "anemia crónica", "desgaste físico", "anemia leve", "anemia moderada", "anemia familiar"]'),
('D56.3', 'Talasemia menor', 'Sin especificar', '["anemia leve", "anemia asintomática", "rasgo talasémico", "anemia moderada", "sangre floja", "anemia de los abuelos", "anemia genética leve", "hemoglobina baja", "cansancio ligero", "anemia silenciosa", "anemia sin síntomas", "anemia común", "anemia del mediterráneo", "anemia no grave", "anemia controlada"]'),
('D56.4', 'Persistencia hereditaria de hemoglobina fetal [PHHF]', 'Sin especificar', '["hemoglobina de bebé", "anemia hereditaria", "condición sanguínea", "sangre fetal", "anemia genética", "trastorno sanguíneo raro", "hemoglobina persistente", "problema de sangre familiar", "anemia sin causa", "condición de la sangre", "hemoglobina elevada", "anemia crónica", "anemia heredada", "anemia benigna", "enfermedad de la sangre"]'),
('D56.5', 'Hemoglobina E-beta talasemia', 'Sin especificar', '["anemia severa", "anemia hereditaria", "hemoglobina anormal", "anemia grave", "sangre debilitada", "anemia de origen genético", "trastorno de hemoglobina", "palidez", "fatiga extrema", "anemia mediterránea", "anemia de hemoglobina E", "problema crónico de sangre", "anemia del sureste asiático", "anemia de la sangre", "anemia severa congénita"]'),
('D56.8', 'Otras talasemias', 'Sin especificar', '["anemia rara", "anemia hereditaria", "sangre débil", "anemia mediterránea", "otras anemias genéticas", "problemas de hemoglobina", "anemia familiar", "anemia crónica", "anemia sin especificar", "fatiga", "palidez", "desgaste físico", "anemia moderada", "trastorno sanguíneo", "sangre rara"]'),
('D56.9', 'Talasemia, no especificada', 'Sin especificar', '["anemia", "sangre débil", "anemia hereditaria", "anemia mediterránea", "anemia genética", "anemia crónica", "problema de la sangre", "cansancio por anemia", "palidez crónica", "anemia mal diagnosticada", "anemia sin nombre", "problema de hemoglobina", "anemia de familia", "fatiga persistente", "anemia desconocida"]');
