INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z60.0', 'Problemas de adaptación a las transiciones de los ciclos de vida', 'Sin especificar', '["crisis vital", "etapa de cambios", "no me hallo", "crisis de los 40", "nido vacío", "transición de vida", "estrés por cambios", "ajuste a nuevas etapas", "no saber qué hacer con mi vida", "desubicado", "cambio de etapa", "crisis existencial", "adaptación difícil", "problemas de madurez", "estoy en otra onda", "inestabilidad vital"]'),
('Z60.2', 'Problemas relacionados con vivir solo', 'Sin especificar', '["vivir solo", "soledad no deseada", "aislamiento", "depresión por vivir solo", "me siento solo", "no tengo con quien hablar", "sentirse abandonado", "soledad en casa", "vivir sin compañía", "falta de apoyo social", "tristeza por soledad", "estar solo en la vida", "vivienda solitaria", "aislamiento social", "encerrado en casa", "necesito compañía"]'),
('Z60.3', 'Dificultades por aculturación', 'Sin especificar', '["choque cultural", "no me adapto al país", "extraño mi tierra", "adaptación al extranjero", "problemas de inmigrante", "no entiendo las costumbres", "me siento un extraño", "inmigración difícil", "choque de culturas", "sentirse fuera de lugar", "adaptación social en el exterior", "dificultad de integración", "rechazo del entorno", "vivir lejos de casa", "barrera cultural"]'),
('Z60.4', 'Problemas relacionados con la exclusión y el rechazo social', 'Sin especificar', '["marginación", "exclusión social", "hacer el vacío", "rechazo", "discriminación", "ser ignorado", "sentirse marginado", "desprecio social", "invisibilización", "me hacen el feo", "excluido del grupo", "ser un paria", "soledad impuesta", "no me integran", "aislamiento forzado", "ser desplazado"]'),
('Z60.5', 'Objeto de (aparente) discriminación negativa y persecución', 'Sin especificar', '["perseguido", "me tienen ganas", "me discriminan", "odio", "hostigamiento", "bullying", "acoso grupal", "me tienen en la mira", "prejuicios", "ser chivo expiatorio", "xenofobia", "racismo", "me hacen la vida imposible", "persecución social", "ser objeto de odio", "maltrato social"]'),
('Z60.8', 'Otros problemas relacionados con el entorno social', 'Sin especificar', '["problemas con vecinos", "conflicto social", "mala racha social", "entorno tóxico", "problemas con el vecindario", "presión social", "dificultades de convivencia", "ambiente hostil", "estrés social", "conflictos comunitarios", "inadaptación al medio", "relaciones tensas", "entorno complicado", "problemas de barrio", "convivencia difícil"]'),
('Z60.9', 'Problema relacionado con el ambiente social, no especificado', 'Sin especificar', '["problema de entorno", "cuestiones sociales", "no me llevo bien con nadie", "situación social difícil", "malestar social", "problemas en mi círculo", "cuestiones de vida social", "inestabilidad social", "desadaptación social", "incógnita social", "conflicto del entorno", "mala vibra en mi entorno", "ajuste social", "dificultades del medio", "me siento desubicado"]');
