INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('E16.0', 'Hipoglucemia inducida por fármaco, sin coma', 'Sin especificar', '["bajón de azúcar", "azúcar baja", "hipoglucemia medicamentosa", "bajón por insulina", "mareo por pastillas azúcar", "temblorina por medicamento", "bajón glucémico", "desvanecimiento por fármaco", "sudor frío por insulina", "bajón de glucosa", "debilidad por medicación", "bajón de azúcar sin pérdida de conocimiento", "crisis hipoglucémica", "bajón"]'),
('E16.1', 'Otros tipos de hipoglucemia', 'Sin especificar', '["bajón de azúcar", "azúcar baja", "glucosa baja en sangre", "hipoglucemia reactiva", "desmayo por hambre", "bajón de azúcar espontáneo", "mareos por falta de azúcar", "debilidad por falta de comida", "hipoglucemia postprandial", "sudoración fría", "tiritona", "cuerpo cortado por azúcar", "desvanecimiento", "hambre intensa con mareo", "bajón glucémico"]'),
('E16.2', 'Hipoglucemia, no especificada', 'Sin especificar', '["azúcar baja", "bajón de azúcar", "hipoglucemia", "mareos por azúcar", "bajón", "me dio el bajón", "se me bajó el azúcar", "pálida por glucosa", "desmayo por azúcar", "temblorina", "sudor frío", "debilidad repentina", "bajón de energías", "sentirse flojo", "malestar por azúcar"]'),
('E16.3', 'Aumento de secreción de glucagón', 'Sin especificar', '["exceso de glucagón", "hiperglucagonemia", "problemas de páncreas", "descontrol pancreático", "hormona glucagón elevada", "desajuste de glucosa", "exceso de hormona pancreática", "problema de azúcar en sangre", "desbalance hormonal", "alteración del páncreas", "glucosa inestable", "hiperglucemia secundaria", "mal funcionamiento glandular"]'),
('E16.4', 'Aumento de secreción de gastrina', 'Sin especificar', '["exceso de gastrina", "hipergastrinemia", "ardor de estómago", "gastritis severa", "gastrinoma", "ácido estomacal excesivo", "quemazón en la panza", "acidez extrema", "problemas digestivos", "ardor de guata", "dolor en la boca del estómago", "úlceras estomacales", "reflujo ácido", "exceso de jugo gástrico", "ardor de barriga"]'),
('E16.8', 'Otros trastornos especificados de secreción interna del páncreas', 'Sin especificar', '["problema del páncreas", "disfunción pancreática", "trastorno hormonal pancreático", "desajuste del páncreas", "secreción pancreática anormal", "descontrol de insulina", "fallo en la regulación pancreática", "problemas de islotes pancreáticos", "insuficiencia endocrina pancreática", "desorden glandular", "enfermedad del páncreas", "fallo endocrino", "hormonas pancreáticas alteradas"]'),
('E16.9', 'Trastornos de secreción interna del páncreas, no especificados', 'Sin especificar', '["fallo del páncreas", "problemas del páncreas", "desajuste hormonal", "pancreas enfermo", "descontrol endocrino", "problema de glándulas internas", "alteración pancreática", "mal funcionamiento pancreático", "desorden del sistema endocrino", "dolor de páncreas", "problemas de azúcar y hormonas", "disfunción de secreción"]'),
('E16.A1', 'Nivel 1 de hipoglucemia', 'Sin especificar', '["bajón de azúcar leve", "azúcar un poco baja", "hipoglucemia leve", "primer nivel de bajón", "azúcar en rango bajo", "mareo leve", "hambre excesiva con mareo", "temblorina leve", "bajón de azúcar inicial", "alerta de azúcar baja", "bajón de glucosa nivel 1", "ligeros síntomas de bajón", "bajón controlable"]'),
('E16.A2', 'Nivel 2 de hipoglucemia', 'Sin especificar', '["bajón de azúcar moderado", "hipoglucemia moderada", "azúcar bastante baja", "bajón de azúcar nivel 2", "mareo intenso", "desvanecimiento inminente", "temblorina fuerte", "sudoración fría profusa", "confusión por azúcar baja", "debilidad extrema", "bajón glucémico preocupante", "necesidad urgente de azúcar", "crisis de azúcar moderada"]'),
('E16.A3', 'Nivel 3 de hipoglucemia', 'Sin especificar', '["bajón de azúcar severo", "hipoglucemia grave", "azúcar muy baja", "choque hipoglucémico", "desmayo por bajón", "coma hipoglucémico", "crisis severa de azúcar", "pérdida de conciencia por azúcar", "emergencia por azúcar baja", "bajón crítico", "convulsiones por bajón", "peligro por falta de azúcar", "hipoglucemia nivel 3", "estado crítico por glucosa"]');
