INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z73.0', 'Síndrome de burn-out', 'Sin especificar', '["burnout", "quemado", "agotamiento laboral", "estrés crónico", "jartura laboral", "hastío", "fundido", "desgaste profesional", "cansancio extremo", "fatiga laboral", "no poder más", "estoy quemado", "sobrecarga", "estrés laboral", "colapso mental", "desbordado", "estrés severo"]'),
('Z73.1', 'Patrón de conducta tipo A', 'Sin especificar', '["personalidad tipo A", "impaciente", "competitivo", "perfeccionista", "ansiedad por logro", "hiperactivo", "correveidile", "siempre de prisa", "tensión constante", "obsesivo por el trabajo", "perfil estresado", "agresividad competitiva", "acelerado", "controlador", "autoexigente"]'),
('Z73.2', 'Falta de descanso y ocio', 'Sin especificar', '["sin tiempo libre", "vida sin ocio", "no paro de trabajar", "descanso insuficiente", "saturado", "no tengo tiempo para nada", "ahogado", "estrés por exceso de trabajo", "sin vacaciones", "sin vida social", "siempre ocupado", "desequilibrio vida-trabajo", "falta de relax", "agotado", "necesito parar"]'),
('Z73.3', 'Estrés, no clasificado bajo otro concepto', 'Sin especificar', '["estrés", "nervios", "angustia", "agobio", "tensión", "mal de nervios", "alterado", "estresado", "crisis de nervios", "presión", "estar de los nervios", "quemado", "desesperación", "intranquilidad", "tensión nerviosa", "ataque de nervios"]'),
('Z73.4', 'Habilidades sociales inadecuadas, no clasificadas bajo otro concepto', 'Sin especificar', '["torpeza social", "dificultad para relacionarse", "introversión extrema", "miedo a la gente", "timidez patológica", "aislamiento social", "problemas de conducta", "falta de tacto", "inadaptación social", "problemas para hacer amigos", "miedo escénico", "no sé cómo hablar con otros", "antipatía", "habilidades sociales bajas", "aislado"]'),
('Z73.5', 'Conflicto de rol social, no clasificado bajo otro concepto', 'Sin especificar', '["crisis de identidad", "no sé mi lugar", "conflicto con mi papel", "estrés de rol", "presión social", "no encajo", "expectativas sociales", "rol equivocado", "confusión de identidad", "presión de grupo", "no me hallo", "sentirse fuera de lugar", "problemas de identidad", "conflicto familiar o laboral", "desorientado"]'),
('Z73.6', 'Limitación de las actividades debido a discapacidad', 'Sin especificar', '["discapacidad", "limitación física", "no puedo moverme bien", "restricción de actividad", "impedimento", "minusvalía", "dependencia", "dificultad para hacer cosas", "barreras físicas", "inmovilidad", "incapacidad", "necesito ayuda para todo", "dependiente", "limitado físicamente", "problemas de movilidad"]'),
('Z73.810', 'Comportamiento insomne en la niñez, de tipo asociación al inicio del sueño', 'Sin especificar', '["hijo no duerme solo", "insomnio infantil", "bebé no duerme sin mí", "necesita compañía para dormir", "mal dormir", "problemas de sueño", "se despierta y llora", "no concilia el sueño solo", "necesita brazos para dormir", "hábito de sueño", "insomnio por dependencia", "miedo a dormir solo", "noche en vela", "desvelo"]'),
('Z73.811', 'Comportamiento insomne en la niñez, de tipo de falta de rutinas (o límites mal establecidos)', 'Sin especificar', '["niño sin horario", "sin rutina de sueño", "malos hábitos de sueño", "niño trasnochador", "falta de disciplina de sueño", "horarios caóticos", "hijo no se quiere dormir", "descontrol de sueño", "duerme cuando quiere", "falta de límites", "insomnio por falta de orden", "niño rebelde al dormir", "ritmo circadiano desordenado", "no tiene hora de acostarse"]'),
('Z73.812', 'Comportamiento insomne en la niñez, tipo combinado', 'Sin especificar', '["insomnio mixto", "problemas complejos de sueño", "mi hijo no duerme", "descontrol total de sueño", "insomnio crónico infantil", "hijo no duerme ni de día ni de noche", "múltiples problemas de sueño", "desvelo frecuente", "trastorno del sueño infantil", "noche difícil", "llanto nocturno", "insomnio severo", "sin descanso", "agotamiento del niño"]'),
('Z73.819', 'Comportamiento insomne en la niñez, tipo no especificado', 'Sin especificar', '["hijo no duerme bien", "insomnio inexplicable", "problema de sueño niño", "por qué no duerme mi hijo", "desorden al dormir", "dificultad para dormir niño", "sueño intranquilo", "no pega el ojo", "dormir mal", "noche mala", "hijo inquieto", "insomnio infantil", "ayuda para dormir niño", "niño que no descansa"]'),
('Z73.82', 'Discapacidad sensorial dual', 'Sin especificar', '["sordoceguera", "problemas de vista y oído", "pérdida auditiva y visual", "sordo y ciego", "discapacidad combinada", "dificultad de percepción", "limitación sensorial", "ceguera y sordera", "problemas sensoriales", "discapacidad múltiple", "déficit sensorial", "sin ver ni oír bien", "invalidez sensorial", "desconexión sensorial"]'),
('Z73.89', 'Otros problemas relacionados con la dificultad de gestión de vida', 'Sin especificar', '["mala organización", "desorden vital", "no puedo con mi vida", "caos en mi vida", "desorientación", "dificultad para organizar", "vida desastrosa", "incapaz de gestionar", "problemas diarios", "falta de control personal", "sobrepasado", "crisis de vida", "me supera el día a día", "desorganización"]'),
('Z73.9', 'Problema relacionado con la dificultad de gestión de vida, no especificado', 'Sin especificar', '["problemas personales", "no sé qué me pasa", "me va mal la vida", "crisis existencial", "estoy perdido", "no puedo organizar mi día", "problemas de estilo de vida", "descontrol", "necesito ayuda con mi vida", "desorden", "dificultades personales", "insatisfacción vital", "bloqueo", "problemas cotidianos"]');
