INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P36.0', 'Sepsis del recién nacido por estreptococo del grupo B', 'Sin especificar', '["sepsis neonatal", "infección en la sangre bebé", "fiebre recién nacido", "bebé con sepsis", "estreptococo grupo B bebé", "septicemia neonatal", "bebé muy enfermo", "infección grave recién nacido", "bebé decaído", "sepsis EGB", "infección bacteriana bebé", "shock séptico recién nacido", "bebé no quiere comer", "recién nacido con fiebre", "infección generalizada bebé"]'),
('P36.10', 'Sepsis del recién nacido por estreptococos no especificados', 'Sin especificar', '["sepsis bebé", "infección sangre neonato", "septicemia por estreptococo", "bebé malito", "fiebre en neonatos", "infección generalizada neonato", "bebé con sepsis no especificada", "bacterias en sangre bebé", "recién nacido con infección", "bebé somnoliento", "letargo recién nacido", "sepsis bacteriana bebé", "cuadro séptico neonato", "bebé no se mueve bien", "infección grave neonato"]'),
('P36.19', 'Sepsis del recién nacido por otros estreptococos', 'Sin especificar', '["sepsis neonatal estreptococo", "infección sangre bebé", "sepsis bacteriana específica", "neonato infectado", "septicemia bebé", "estreptococo en sangre", "bebé con fiebre alta", "bebé pálido", "rechazo al pecho", "infección generalizada en bebés", "bacterias en recién nacido", "sepsis temprana", "sepsis tardía bebé", "recién nacido muy delicado", "infección bacteriana inespecífica"]'),
('P36.2', 'Sepsis del recién nacido por Staphylococcus aureus', 'Sin especificar', '["sepsis por estafilococo", "infección sangre staphylococcus", "septicemia estafilococo", "infección aureus bebé", "bebé con estafilococo", "sepsis estafilocócica", "infección piel y sangre bebé", "bebé con sepsis grave", "bacteriemia recién nacido", "bebé irritable", "fiebre estafilococo", "sepsis nosocomial bebé", "infección por estafilococo dorado", "bebé enfermo estafilo", "cuidados intensivos sepsis"]'),
('P36.30', 'Sepsis del recién nacido por estafilococo no especificado', 'Sin especificar', '["sepsis estafilococo bebé", "infección sangre estafilococo", "septicemia recién nacido", "bebé con estafilo", "bacterias estafilococos bebé", "infección generalizada estafilocócica", "recién nacido septicemia", "bebé con fiebre estafilo", "sepsis bacteriana estafilocócica", "bebé inactivo", "infección neonatal severa", "estafilococo en sangre bebé", "problema de sangre bebé", "bebé con sepsis", "infección de origen bacteriano"]'),
('P36.39', 'Sepsis del recién nacido por otros estafilococos', 'Sin especificar', '["sepsis otros estafilococos", "infección neonatal bacteriana", "septicemia por estafilococos", "estafilococo coagulasa negativo bebé", "sepsis hospitalaria recién nacido", "bebé con estafilococo epidermidis", "bacteriemia estafilocócica", "bebé muy enfermo sepsis", "infección sangre neonatos", "sepsis severa recién nacido", "fiebre y letargo bebé", "bebé con sepsis por bacteria", "tratamiento sepsis bebé", "recién nacido con infección grave", "estafilococos en neonatos"]'),
('P36.4', 'Sepsis del recién nacido por Escherichia coli', 'Sin especificar', '["sepsis por e. coli", "infección sangre e. coli bebé", "septicemia e. coli", "e. coli en recién nacido", "infección intestinal bebé sepsis", "sepsis gramnegativa bebé", "escherichia coli en sangre", "bebé con infección e. coli", "sepsis neonatal por coli", "bebé con fiebre e. coli", "infección bacteriana severa bebé", "shock séptico e. coli", "bacterias en sangre e. coli", "recién nacido enfermo coli", "infección generalizada coli"]'),
('P36.5', 'Sepsis del recién nacido por anaerobios', 'Sin especificar', '["sepsis bacterias anaerobias", "septicemia anaerobia bebé", "infección sangre bacterias anaerobias", "anaerobios en recién nacido", "infección severa neonato", "sepsis por bacterias sin aire", "bebé sepsis grave", "infección profunda bebé", "bacteriemia anaerobia", "bebé con infección por anaerobios", "sepsis bacteriana anaerobia", "fiebre y sepsis recién nacido", "bebé muy malito", "infección rara bebé", "sepsis sistémica anaeróbica"]'),
('P36.8', 'Otras sepsis bacterianas del recién nacido', 'Sin especificar', '["otras infecciones sangre bebé", "sepsis bacteriana neonatal", "septicemia recién nacido rara", "infección generalizada bebé", "bacterias en sangre neonatal", "bebé con infección bacteriana", "sepsis neonatal inespecífica", "recién nacido con sepsis", "bebé en peligro infección", "fiebre, decaimiento bebé", "infección grave neonato", "sepsis sistémica bebé", "bacteriemia en neonatos", "cuadro infeccioso recién nacido", "sepsis bacteriana general"]'),
('P36.9', 'Sepsis bacteriana del recién nacido, no especificada', 'Sin especificar', '["sepsis neonatal", "infección en sangre bebé", "septicemia recién nacido", "bebé con sepsis", "infección grave recién nacido", "bebé con fiebre y sepsis", "bacterias en la sangre bebé", "sepsis sin especificar", "recién nacido muy grave", "sepsis bacteriana", "cuadro séptico bebé", "bebé decaído e infeccioso", "sepsis del recién nacido", "infección sistémica bebé", "sepsis del neonato"]');
