INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q22.0', 'Atresia de la válvula pulmonar', 'Sin especificar', '["atresia pulmonar", "corazón azul", "cianosis neonatal", "bebé azul", "defecto cardíaco congénito", "soplo en el corazón", "falta de válvula pulmonar", "obstrucción al flujo pulmonar", "cardiopatía severa", "problemas cardíacos al nacer", "malformación del corazón", "cianosis", "dificultad respiratoria en bebés", "hipoxemia neonatal", "defectos del tabique"]'),
('Q22.1', 'Estenosis congénita de la válvula pulmonar', 'Sin especificar', '["estenosis pulmonar", "válvula pulmonar estrecha", "soplo cardíaco", "corazón estrecho", "dificultad para respirar", "fatiga rápida", "valvulopatía pulmonar", "estrechez valvular", "dolor en el pecho", "desmayos", "cianosis leve", "problemas de válvula", "cardiopatía", "soplo funcional", "obstrucción pulmonar"]'),
('Q22.2', 'Insuficiencia congénita de la válvula pulmonar', 'Sin especificar', '["insuficiencia pulmonar", "regurgitación pulmonar", "fuga en la válvula pulmonar", "soplo", "corazón que no cierra bien", "valvulopatía", "cansancio extremo", "edema en piernas", "hinchazón", "falta de aire", "corazón grande", "cardiomegalia", "defecto de nacimiento", "soplo diastólico", "insuficiencia valvular"]'),
('Q22.3', 'Otras malformaciones congénitas de la válvula pulmonar', 'Sin especificar', '["malformación pulmonar", "defecto de válvula", "valvulopatía congénita", "problemas de corazón al nacer", "displasia pulmonar", "anatomía anormal del corazón", "soplo cardíaco", "problemas circulatorios", "anomalía en la válvula", "corazón mal formado", "cardiopatía congénita", "estenosis o insuficiencia", "detectar soplo", "malformación", "defecto valvular"]'),
('Q22.4', 'Estenosis congénita tricuspídea', 'Sin especificar', '["estenosis tricúspide", "tricúspide estrecha", "problema en válvula derecha", "soplo cardíaco", "obstrucción válvula tricúspide", "cansancio", "hinchazón abdominal", "edema", "falta de oxígeno", "taquicardia", "problema de nacimiento", "cardiopatía valvular", "obstrucción tricuspídea", "valvulopatía", "dolor de pecho"]'),
('Q22.5', 'Anomalía de Ebstein', 'Sin especificar', '["anomalía de ebstein", "corazón con malformación", "enfermedad de ebstein", "tricúspide desplazada", "soplo muy fuerte", "insuficiencia tricúspide", "bebé azul", "cianosis", "fatiga extrema", "arritmias cardíacas", "palpitaciones", "cardiomegalia", "defecto de nacimiento", "problema en el ventrículo derecho", "cardiopatía compleja"]'),
('Q22.6', 'Síndrome del corazón derecho hipoplásico', 'Sin especificar', '["corazón derecho pequeño", "hipoplasia ventrículo derecho", "corazón hipoplásico", "falla cardíaca neonatal", "cianosis", "bebé con corazón pequeño", "defecto cardíaco grave", "hipoplasia", "cardiopatía cianótica", "problema de desarrollo cardíaco", "baja oxigenación", "insuficiencia derecha", "malformación severa", "problemas de circulación", "corazón izquierdo dominante"]'),
('Q22.8', 'Otras malformaciones congénitas de válvula tricúspide', 'Sin especificar', '["malformación tricúspide", "problemas válvula derecha", "defecto en válvula", "insuficiencia de la tricúspide", "soplo de nacimiento", "anomalía valvular", "tricúspide pequeña", "valvulopatía tricúspide", "falla en la válvula", "cardiopatía", "dificultad para respirar", "fatiga infantil", "desarrollo anormal del corazón", "soplo", "defecto congénito"]'),
('Q22.9', 'Malformación congénita de la válvula tricúspide, no especificada', 'Sin especificar', '["problema en la válvula tricúspide", "defecto cardíaco congénito", "soplo", "falla de válvula", "valvulopatía no especificada", "anomalía cardíaca", "problemas al nacer", "malformación del corazón", "cardiología pediátrica", "insuficiencia de válvula", "estenosis de válvula", "soplo funcional", "corazón que falla", "defecto de nacimiento", "cardiopatía"]');
