INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J67.0', 'Pulmón del granjero', 'Sin especificar', '["pulmón de granjero", "tos de campo", "alergia al heno", "neumonitis por moho", "tos por paja", "pulmón de agricultor", "dificultad para respirar campo", "fiebre del cosechador", "disnea por polvo agrícola", "pulmón inflamado granja", "tos seca persistente campo", "enfermedad del trabajador rural", "alergia a hongos granja", "exposición a heno con moho", "problemas respiratorios rurales"]'),
('J67.1', 'Bagazosis', 'Sin especificar', '["bagazosis", "pulmón por caña de azúcar", "alergia al bagazo", "tos por fibra de caña", "neumonitis por caña", "enfermedad azucarera", "tos de ingenio", "pulmón de cañero", "dificultad respiratoria azucarera", "inflamación pulmonar fibra vegetal", "reacción alérgica caña", "polvo de caña de azúcar", "tos seca industrial caña", "daño pulmonar por bagazo", "exposición a residuo de caña"]'),
('J67.2', 'Pulmón del criador de aves', 'Sin especificar', '["pulmón de criador de aves", "tos de palomero", "alergia a las plumas", "neumonitis por aves", "fiebre de criadero", "tos por excremento de ave", "pulmón de avicultor", "asma de gallinero", "tos seca por aves", "alergia a periquitos", "reacción a plumas de aves", "pulmón de cuidador de aves", "inflamación por caspa de ave", "tos crónica por palomas", "dificultad para respirar avícola"]'),
('J67.3', 'Suberosis', 'Sin especificar', '["suberosis", "pulmón de corchero", "alergia al corcho", "tos por polvo de corcho", "neumonitis por corcho", "enfermedad de la industria del corcho", "tos de fábrica de corchos", "pulmón inflamado corcho", "daño pulmonar corteza árbol", "problemas de pecho industria corcho", "reacción alérgica polvo de corcho", "tos seca industrial corcho", "exposición a polvo de corcho", "molestias respiratorias corcheras", "asma por polvillo de corcho"]'),
('J67.4', 'Pulmón de los manipuladores de la malta', 'Sin especificar', '["pulmón de maltero", "alergia a la malta", "tos por malta", "neumonitis por malta", "enfermedad de la cerveza", "tos de fábrica de cerveza", "pulmón de trabajador cervecero", "alergia a granos malteados", "tos seca por polvillo de malta", "problemas respiratorios maltería", "inflamación pulmonar cereales", "reacción a esporas de malta", "exposición a polvo de grano malteado", "tos persistente cervecera", "dificultad para respirar maltería"]'),
('J67.5', 'Pulmón del cultivador de setas', 'Sin especificar', '["pulmón de cultivador de setas", "alergia a hongos", "tos de champiñonero", "neumonitis por setas", "tos por sustrato de hongos", "pulmón de micocultor", "alergia a esporas de setas", "tos de invernadero de hongos", "inflamación pulmonar cultivo setas", "dificultad para respirar hongos", "reacción alérgica cultivo champiñón", "problemas de pecho por setas", "tos seca persistente micología", "exposición a polvo de esporas", "tos de trabajador de hongos"]'),
('J67.6', 'Pulmón de los descortezadores de arce', 'Sin especificar', '["pulmón de descortezador", "alergia a corteza de árbol", "tos por corteza de arce", "neumonitis por arce", "tos de maderero", "pulmón de industria maderera", "alergia a esporas de corteza", "tos seca polvo madera arce", "inflamación pulmonar descortezado", "reacción alérgica corteza", "dificultad respiratoria maderera", "tos persistente carpintero", "problemas pulmón por arce", "polvo de corteza", "exposición a descortezado"]'),
('J67.7', 'Pulmón de humidificador y acondicionador de aire', 'Sin especificar', '["tos del aire acondicionado", "alergia al humidificador", "neumonitis por aire acondicionado", "tos de oficina", "pulmón de aire viciado", "tos por moho en aire", "alergia al aire sucio", "fiebre del humidificador", "tos por ventilación", "problemas respiratorios por clima", "aire contaminado pulmones", "infección por aire acondicionado", "tos crónica oficina", "dificultad respiratoria ventilación", "exposición a hongos aire"]'),
('J67.8', 'Neumonitis por hipersensibilidad debida a otros tipos de polvo orgánico', 'Sin especificar', '["alergia a polvos orgánicos", "neumonitis por polvo", "tos por material orgánico", "pulmón inflamado por polvo", "reacción alérgica inhalación", "tos seca industrial", "daño pulmonar por partículas", "alergia respiratoria laboral", "tos por polvillo", "hipersensibilidad pulmonar", "irritación pulmonar polvo", "tos persistente por inhalación", "asma ocupacional orgánica", "dificultad respiratoria por polvo", "enfermedad pulmonar por ambiente"]'),
('J67.9', 'Neumonitis por hipersensibilidad debido a polvo orgánico no especificado', 'Sin especificar', '["neumonitis desconocida", "tos por causa ambiental", "alergia pulmonar sin especificar", "pulmón sensible al polvo", "tos crónica por ambiente", "problemas de pecho por polvillo", "reacción alérgica desconocida pulmón", "hipersensibilidad no diagnosticada", "tos seca sin causa clara", "irritación bronquial ambiental", "daño pulmonar por inhalación polvo", "problemas respiratorios ocupacionales", "alergia por entorno laboral", "dificultad para respirar polvos", "tos persistente por exposición"]');
