INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L81.0', 'Hiperpigmentación posinflamatoria', 'Sin especificar', '["manchas oscuras", "manchas tras el acné", "manchas por cicatrices", "pigmentación postinflamatoria", "marcas en la piel", "manchas después de granos", "piel manchada", "hiperpigmentación", "manchas por irritación", "oscurecimiento de la piel", "marcas negras", "manchas de sol", "pigmentación residual", "manchas inflamatorias", "manchitas en la cara"]'),
('L81.1', 'Cloasma', 'Sin especificar', '["paño", "melasma", "máscara del embarazo", "manchas en el embarazo", "manchas hormonales", "manchas en la cara", "manchas solares", "paño en la frente", "paño en el bozo", "hiperpigmentación hormonal", "manchas café", "melasma facial", "piel manchada por embarazo", "manchas gestacionales", "manchas de la edad"]'),
('L81.2', 'Pecas (efélides) (L)', 'Sin especificar', '["pecas", "efélides", "manchitas en la piel", "puntos en la cara", "pecas de sol", "manchas de sol", "pequitas", "piel con pecas", "manchitas marrones", "puntos cafés", "pigmentación cutánea", "manchas pequeñas", "manchas de nacimiento", "pequeñas manchitas", "piel pecosa"]'),
('L81.3', 'Manchas café con leche', 'Sin especificar', '["manchas café con leche", "manchas color café", "manchas de nacimiento", "manchas grandes en la piel", "manchas planas marrones", "manchas claras", "manchas en el cuerpo", "manchas congénitas", "manchas dérmicas", "manchas cutáneas", "pigmentación café", "manchas pálidas", "marcas en la piel al nacer", "manchas circulares", "hiperpigmentación café"]'),
('L81.4', 'Otros tipos de hiperpigmentación por melanina', 'Sin especificar', '["exceso de melanina", "manchas oscuras en la piel", "hiperpigmentación cutánea", "manchas solares", "manchas por sol", "manchas de la vejez", "lentigos", "manchas de hígado", "hiperpigmentación focalizada", "manchas hiperpigmentadas", "pigmentación excesiva", "piel oscura en zonas", "manchas marrones", "manchas de sol en manos", "manchas seniles"]'),
('L81.5', 'Leucoderma, no clasificada bajo otro concepto', 'Sin especificar', '["manchas blancas", "piel despigmentada", "manchas sin color", "leucoderma", "piel clara por parches", "manchas pálidas", "pérdida de color en la piel", "piel descolorida", "manchas blancas en el cuerpo", "despigmentación", "manchas tipo vitiligo", "piel blanca localizada", "manchas por quemaduras", "parches blancos", "falta de pigmento"]'),
('L81.6', 'Otros trastornos con disminución de la formación de melanina', 'Sin especificar', '["falta de melanina", "hipopigmentación", "piel clara", "manchas claras", "decoloración de la piel", "baja pigmentación", "manchas blancas dispersas", "piel sin color", "hipomelanosis", "pérdida de tono de piel", "manchas claras en el cuerpo", "disminución de pigmento", "piel manchada de blanco", "zonas claras en la piel", "trastorno del pigmento"]'),
('L81.7', 'Dermatosis purpúrica pigmentada', 'Sin especificar', '["manchas de sangre", "manchas rojizas", "petequias", "manchas de color óxido", "manchas tipo moretón", "dermatosis pigmentaria", "manchas en las piernas", "manchas purpúreas", "pigmentación en las piernas", "manchas por extravasación", "manchas color café rojizo", "dermatitis pigmentada", "manchas vasculares", "lesiones purpúricas", "manchas en forma de pimienta"]'),
('L81.8', 'Otros tipos de trastornos especificados de la pigmentación', 'Sin especificar', '["trastornos del color de piel", "pigmentación alterada", "cambios en el tono de piel", "manchas extrañas", "piel con color irregular", "pigmentación inusual", "manchas por medicamentos", "manchas por químicos", "problemas de pigmentación", "discromía", "manchas amarillentas", "manchas grisáceas", "oscurecimiento cutáneo", "aclaramiento cutáneo", "irregularidad en la piel"]'),
('L81.9', 'Trastorno de la pigmentación, no especificado', 'Sin especificar', '["problema en la piel", "manchas en la piel", "color raro en la piel", "cambio de color de piel", "alteración en el pigmento", "mancha", "manchas raras", "piel descolorida", "problemas de color", "pigmentación anormal", "manchas cutáneas sin causa", "manchas en la cara o cuerpo", "piel con manchas", "alteración cutánea", "daño en la pigmentación"]');
