INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B06.00', 'Rubeola con complicación neurológica, no especificada', 'Sin especificar', '["rubeola", "rubéola", "sarampión alemán", "manchitas rojas", "salpullido", "fiebre y ronchas", "complicación en el cerebro", "daño neurológico", "rubeola grave", "rubeola rara", "problemas mentales rubeola", "convulsiones por rubeola", "mareos rubeola", "confusion rubeola"]'),
('B06.01', 'Encefalitis por rubeola', 'Sin especificar', '["encefalitis", "inflamación del cerebro", "cerebro inflamado", "rubeola en la cabeza", "fiebre alta y delirio", "rubeola con convulsiones", "desorientación por rubeola", "dolor de cabeza intenso rubeola", "rubeola con sopor", "coma por rubeola", "meningoencefalitis rubeola", "infección cerebral por virus"]'),
('B06.02', 'Meningitis por rubeola', 'Sin especificar', '["meningitis", "inflamación de meninges", "rubeola con rigidez de nuca", "cuello tieso rubeola", "fiebre alta y rigidez", "dolor de cabeza extremo", "fotofobia rubeola", "rubeola con vomitos", "dolor de nuca rubeola", "infección de las meninges por rubeola", "rubeola grave del sistema nervioso"]'),
('B06.09', 'Otras complicaciones neurológicas de la rubeola', 'Sin especificar', '["problemas neurológicos rubeola", "daño nervioso rubeola", "neuropatía post rubeola", "hormigueo rubeola", "debilidad muscular rubeola", "rubeola con problemas de movimiento", "ataxia por rubeola", "rubeola con temblores", "afectación del sistema nervioso rubeola", "problemas de coordinación rubeola"]'),
('B06.81', 'Neumonía por rubeola', 'Sin especificar', '["neumonía", "pulmonía", "rubeola con tos", "pecho cargado rubeola", "flemas rubeola", "dificultad para respirar rubeola", "rubeola con asfixia", "dolor al respirar rubeola", "pulmones inflamados por rubeola", "infección pulmonar rubeola", "tos persistente rubeola"]'),
('B06.82', 'Artritis por rubeola', 'Sin especificar', '["artritis", "dolor de articulaciones", "articulaciones inflamadas", "rubeola con dolor de huesos", "reumas por rubeola", "dolor de manos y pies rubeola", "rigidez articular rubeola", "hinchazón de rodillas rubeola", "dolor de coyunturas rubeola", "rubeola con inflamación de muñecas", "ataque articular rubeola"]'),
('B06.89', 'Otras complicaciones de la rubeola', 'Sin especificar', '["complicaciones rubeola", "rubeola grave", "rubeola complicada", "problemas después de la rubeola", "secuelas rubeola", "rubeola que no cura", "rubeola con otros síntomas", "fiebre persistente rubeola", "rubeola en adultos", "rubeola peligrosa", "malestar general intenso rubeola"]'),
('B06.9', 'Rubeola sin complicaciones', 'Sin especificar', '["rubeola", "rubéola", "sarampión alemán", "manchitas rojas", "salpullido", "ronchas", "fiebre leve", "ganglios inflamados", "rubeola común", "manchas en la cara", "ronchitas", "fiebre de tres días", "rubeola leve", "puntitos rojos"]');
