INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C34.00', 'Neoplasia maligna de bronquio principal, no especificado', 'Sin especificar', '["cáncer de pulmón", "tumor en el bronquio", "bulto en el pulmón", "carcinoma bronquial", "tos con sangre", "dolor en el pecho", "falta de aire", "masa pulmonar", "cáncer pulmonar", "dificultad para respirar", "escupir sangre", "neoplasia bronquial", "mancha en el pulmón", "cáncer", "malignidad bronquial", "afección pulmonar grave", "oncología pulmonar"]'),
('C34.01', 'Neoplasia maligna de bronquio principal derecho', 'Sin especificar', '["cáncer pulmón derecho", "tumor bronquio derecho", "masa pulmón derecho", "carcinoma derecho", "problemas para respirar derecho", "dolor torácico derecho", "tos persistente derecha", "cáncer en el bronquio derecho", "tumor bronquial derecho", "neoplasia derecha", "tejido maligno pulmón derecho", "lesión pulmonar derecha", "tumoración derecha", "cáncer de tórax derecho", "escupir sangre pulmón derecho"]'),
('C34.02', 'Neoplasia maligna de bronquio principal izquierdo', 'Sin especificar', '["cáncer pulmón izquierdo", "tumor bronquio izquierdo", "masa pulmón izquierdo", "carcinoma izquierdo", "problemas para respirar izquierdo", "dolor torácico izquierdo", "tos persistente izquierda", "cáncer en el bronquio izquierdo", "tumor bronquial izquierdo", "neoplasia izquierda", "tejido maligno pulmón izquierdo", "lesión pulmonar izquierda", "tumoración izquierda", "cáncer de tórax izquierdo", "escupir sangre pulmón izquierdo"]'),
('C34.10', 'Neoplasia maligna de lóbulo superior, bronquio y pulmón no especificados', 'Sin especificar', '["tumor lóbulo superior", "cáncer en la parte alta del pulmón", "masa en la parte superior pulmonar", "carcinoma lóbulo superior", "cáncer pulmonar superior", "tumor en el vértice pulmonar", "dolor en la parte alta del pecho", "neoplasia de lóbulo superior", "lesión en el ápex pulmonar", "nódulo pulmonar superior", "cáncer broncopulmonar superior", "tumor maligno superior", "afección del lóbulo superior"]'),
('C34.11', 'Neoplasia maligna de lóbulo superior, bronquio o pulmón derecho', 'Sin especificar', '["tumor lóbulo superior derecho", "cáncer pulmón derecho arriba", "carcinoma lóbulo superior derecho", "masa en pulmón derecho superior", "cáncer bronquial superior derecho", "nódulo lóbulo derecho", "dolor parte alta pulmón derecho", "neoplasia lóbulo superior derecho", "lesión apical derecha", "tumor maligno lóbulo superior derecho", "problemas pulmón derecho superior"]'),
('C34.12', 'Neoplasia maligna de lóbulo superior, bronquio o pulmón izquierdo', 'Sin especificar', '["tumor lóbulo superior izquierdo", "cáncer pulmón izquierdo arriba", "carcinoma lóbulo superior izquierdo", "masa en pulmón izquierdo superior", "cáncer bronquial superior izquierdo", "nódulo lóbulo izquierdo", "dolor parte alta pulmón izquierdo", "neoplasia lóbulo superior izquierdo", "lesión apical izquierda", "tumor maligno lóbulo superior izquierdo", "problemas pulmón izquierdo superior"]'),
('C34.2', 'Neoplasia maligna de lóbulo medio, bronquio o pulmón', 'Sin especificar', '["tumor lóbulo medio", "cáncer pulmón medio", "carcinoma lóbulo medio", "masa pulmonar media", "cáncer bronquial medio", "neoplasia lóbulo medio", "lesión lóbulo medio", "tumoración pulmón medio", "problemas en el centro del pulmón", "tumor bronquial lóbulo medio"]'),
('C34.30', 'Neoplasia maligna de lóbulo inferior, bronquio o pulmón no especificados', 'Sin especificar', '["tumor lóbulo inferior", "cáncer en la base del pulmón", "masa en la parte baja del pulmón", "carcinoma lóbulo inferior", "cáncer pulmonar base", "dolor base pulmonar", "neoplasia lóbulo inferior", "lesión basal pulmonar", "nódulo pulmonar base", "cáncer broncopulmonar inferior", "tumor maligno inferior"]'),
('C34.31', 'Neoplasia maligna de lóbulo inferior, bronquio o pulmón derecho', 'Sin especificar', '["tumor lóbulo inferior derecho", "cáncer base pulmón derecho", "carcinoma base derecha", "masa base pulmón derecho", "cáncer bronquial inferior derecho", "nódulo basal derecho", "dolor base pulmón derecho", "neoplasia lóbulo inferior derecho", "lesión basal derecha", "tumor maligno lóbulo inferior derecho"]'),
('C34.32', 'Neoplasia maligna de lóbulo inferior, bronquio o pulmón izquierdo', 'Sin especificar', '["tumor lóbulo inferior izquierdo", "cáncer base pulmón izquierdo", "carcinoma base izquierda", "masa base pulmón izquierdo", "cáncer bronquial inferior izquierdo", "nódulo basal izquierdo", "dolor base pulmón izquierdo", "neoplasia lóbulo inferior izquierdo", "lesión basal izquierda", "tumor maligno lóbulo inferior izquierdo"]'),
('C34.80', 'Neoplasia maligna de localizaciones contiguas de bronquio y pulmón no especificados', 'Sin especificar', '["cáncer pulmón extendido", "tumor con múltiples focos pulmonares", "neoplasia difusa broncopulmonar", "cáncer bronquial contiguo", "tumor diseminado en pulmón", "afectación pulmonar combinada", "carcinoma broncopulmonar extenso", "tumor pulmonar múltiple", "neoplasia maligna extendida"]'),
('C34.81', 'Neoplasia maligna de localizaciones contiguas de bronquio y pulmón derecho', 'Sin especificar', '["cáncer pulmón derecho extendido", "tumor pulmón derecho múltiple", "afectación pulmón derecho contigua", "neoplasia maligna pulmón derecho múltiple", "carcinoma bronquial derecho extendido", "tumor derecho difuso"]'),
('C34.82', 'Neoplasia maligna de localizaciones contiguas de bronquio y pulmón izquierdo', 'Sin especificar', '["cáncer pulmón izquierdo extendido", "tumor pulmón izquierdo múltiple", "afectación pulmón izquierdo contigua", "neoplasia maligna pulmón izquierdo múltiple", "carcinoma bronquial izquierdo extendido", "tumor izquierdo difuso"]'),
('C34.90', 'Neoplasia maligna de parte no especificada, bronquio o pulmón no especificados', 'Sin especificar', '["cáncer de pulmón sin especificar", "tumor pulmonar no definido", "cáncer respiratorio", "problema maligno en el pecho", "masa en el tórax", "neoplasia pulmonar no especificada", "tumor en bronquios", "bulto en el pecho", "carcinoma pulmonar", "oncología pulmonar inespecífica"]'),
('C34.91', 'Neoplasia maligna de parte no especificada de pulmón o bronquio derecho', 'Sin especificar', '["cáncer pulmón derecho", "tumor derecho no especificado", "cáncer bronquio derecho", "masa lado derecho pecho", "carcinoma pulmón derecho", "neoplasia bronquial derecha", "problema en el pulmón derecho", "tumoración derecha tórax"]'),
('C34.92', 'Neoplasia maligna de parte no especificada de pulmón o bronquio izquierdo', 'Sin especificar', '["cáncer pulmón izquierdo", "tumor izquierdo no especificado", "cáncer bronquio izquierdo", "masa lado izquierdo pecho", "carcinoma pulmón izquierdo", "neoplasia bronquial izquierda", "problema en el pulmón izquierdo", "tumoración izquierda tórax"]');
