INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q50.01', 'Ausencia congénita de ovario unilateral', 'Sin especificar', '["falta de un ovario", "ovario único", "agenesia ovárica unilateral", "nacer sin un ovario", "ovario ausente", "hipoplasia ovárica", "problemas de nacimiento ovarios", "infertilidad congénita", "falla ovárica", "malformación genital", "desarrollo incompleto ovarios", "ovario faltante", "dolor bajo vientre", "revisión ginecológica", "falta de ovulación", "dificultad para embarazar"]'),
('Q50.02', 'Ausencia bilateral congénita de los ovarios', 'Sin especificar', '["no tengo ovarios", "agenesia ovárica total", "síndrome de ovarios ausentes", "nacer sin ovarios", "falta de desarrollo ovárico", "amenorrea primaria", "esterilidad primaria", "problemas hormonales congénitos", "fallo ovárico prematuro", "desarrollo sexual incompleto", "malformación útero ovarios", "ausencia de ovarios", "no ovulo", "menopausia precoz", "disgenesia gonadal", "falta de estrógenos"]'),
('Q50.1', 'Quiste ovárico del desarrollo', 'Sin especificar', '["quiste en el ovario", "bolita en el ovario", "dolor de ovarios", "ovarios poliquísticos", "dolor en la panza", "pinchazos en la guata", "dolor de ovarios", "punzadas bajo vientre", "hinchazón abdominal", "quiste funcional", "folículo persistente", "dolor al tener relaciones", "menstruación irregular", "bulto en el abdomen", "quiste de nacimiento", "dolor en el bajo vientre"]'),
('Q50.2', 'Torsión ovárica congénita', 'Sin especificar', '["ovario torcido", "dolor agudo en el vientre", "dolor de guata fuerte", "torsión de ovario", "emergencia ginecológica", "dolor abdominal súbito", "retorcijón en el ovario", "dolor de ovarios intenso", "ovario enrollado", "dolor tipo cólico", "dolor de panza insoportable", "isquemia ovárica", "dolor pélvico agudo", "torsión anexial", "dolor bajo vientre urgente", "vómitos y dolor pélvico"]'),
('Q50.31', 'Ovario accesorio', 'Sin especificar', '["ovario extra", "ovario supernumerario", "tener tres ovarios", "malformación ovárica", "ovario adicional", "tejido ovárico extra", "hallazgo ecográfico", "duplicidad ovárica", "problemas hormonales", "dolor pélvico inexplicable", "masa en la pelvis", "anomalía de ovarios", "crecimiento anormal ovarios", "ecografía pélvica", "variante anatómica ovarios", "ovarios múltiples"]'),
('Q50.32', 'Cintilla ovárica', 'Sin especificar', '["ovario en cintilla", "disgenesia gonadal", "ovario rudimentario", "cintilla gonadal", "ovario pequeño", "problemas de desarrollo ovárico", "agenesia parcial", "fallo ovárico", "ausencia de ovulación", "desarrollo sexual retrasado", "falta de estrógenos", "hipogonadismo", "anomalía cromosómica", "examen de ovarios", "desarrollo genital anómalo", "ovarios no desarrollados"]'),
('Q50.39', 'Otras malformaciones congénitas del ovario', 'Sin especificar', '["anomalía congénita ovarios", "malformación ovárica", "defecto de nacimiento ovarios", "problema en el desarrollo de ovarios", "ovario deforme", "ovarios malformados", "displasia ovárica", "alteración ginecológica congénita", "ovario dismórfico", "estudios por infertilidad", "malformaciones genitales internas", "ovario ectópico", "problemas estructurales ovarios", "desarrollo anormal ginecológico", "anomalía pélvica"]'),
('Q50.4', 'Quiste embrionario de la trompa de Falopio', 'Sin especificar', '["quiste en la trompa", "quiste paratubárico", "quiste de hidátide de morgagni", "bolita en la trompa", "dolor en los anexos", "dolor abdominal bajo", "dolor en la panza", "dolor en la guata", "inflamación de trompas", "molestia en la pelvis", "quiste benigno trompa", "masa en la pelvis", "quiste en los anexos", "dolor durante el ciclo", "obstrucción tubárica", "quiste congénito"]'),
('Q50.5', 'Quiste embrionario del ligamento ancho', 'Sin especificar', '["quiste ligamento ancho", "quiste paraovárico", "dolor pélvico", "quiste cerca del ovario", "masa pélvica", "dolor bajo vientre", "dolor de panza", "dolor de guata", "pinchazos en la pelvis", "quiste de desarrollo", "dolor en los anexos", "quiste benigno", "molestia abdominal", "hallazgo en ecografía", "quiste embrionario", "presión en la pelvis"]'),
('Q50.6', 'Otras malformaciones congénitas de la trompa de Falopio y del ligamento ancho', 'Sin especificar', '["anomalía de trompas de falopio", "malformación de trompas", "trompa de falopio ausente", "trompas dobles", "problemas congénitos en trompas", "agenesia de trompas", "defecto congénito ligamento ancho", "obstrucción congénita de trompas", "anomalía anatómica trompas", "problemas de fertilidad", "infección o malformación trompas", "desarrollo incompleto trompas", "anomalía en los anexos", "disgenesia tubárica", "trompas malformadas", "problemas ginecológicos de nacimiento"]');
