INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A01.00', 'Fiebre tifoidea, no especificada', 'Sin especificar', '["fiebre tifoidea", "tifus", "fiebre intestinal", "infección por salmonella", "calentura constante", "dolor de panza fuerte", "fiebre alta y persistente", "tifoidea", "malestar general por salmonella", "diarrea por tifoidea", "fiebre tífica", "dolor de guata", "fiebre prolongada", "infección estomacal severa", "fiebre tifoidea clásica"]'),
('A01.01', 'Meningitis tifoidea', 'Sin especificar', '["meningitis tifoidea", "inflamación de las meninges por tifoidea", "tifoidea con dolor de cabeza extremo", "rigidez de nuca por tifoidea", "infección cerebral por salmonella", "cefalea intensa por tifoidea", "fiebre tifoidea en la cabeza", "meningitis por fiebre tífica", "tifoidea con delirios", "inflamación cerebral por tifoidea", "dolor de cabeza insoportable por fiebre", "tifoidea complicada con meningitis"]'),
('A01.02', 'Fiebre tifoidea con afectación cardiaca', 'Sin especificar', '["tifoidea en el corazón", "miocarditis por tifoidea", "tifoidea con taquicardia", "problemas cardiacos por tifoidea", "dolor en el pecho por tifoidea", "complicación cardiaca de la tifoidea", "tifoidea con arritmia", "inflamación del corazón por fiebre tifoidea", "tifoidea con palpitaciones", "infección cardiaca tífica", "debilidad cardiaca por fiebre prolongada"]'),
('A01.03', 'Neumonía tifoidea', 'Sin especificar', '["neumonía por tifoidea", "tifoidea en los pulmones", "fiebre tifoidea con tos", "infección pulmonar por salmonella", "tifoidea con dificultad para respirar", "neumonía tífica", "pecho congestionado por tifoidea", "tifoidea con falta de aire", "complicación respiratoria de tifoidea", "fiebre y tos por tifoidea", "pulmonía tífica"]'),
('A01.04', 'Artritis tifoidea', 'Sin especificar', '["artritis por tifoidea", "dolor de articulaciones por tifoidea", "tifoidea con inflamación articular", "tifoidea con dolor de huesos", "artritis tífica", "inflamación de coyunturas por tifoidea", "dolor en las articulaciones por fiebre tifoidea", "tifoidea que afecta las rodillas", "articulaciones tiesas por tifoidea", "tifoidea con reumatismo infeccioso"]'),
('A01.05', 'Osteomielitis tifoidea', 'Sin especificar', '["infección ósea por tifoidea", "osteomielitis por salmonella", "tifoidea en los huesos", "infección en la médula ósea por tifoidea", "tifoidea que pudre el hueso", "dolor profundo en los huesos por tifoidea", "osteomielitis tífica", "tifoidea con daño óseo", "infección tífica de los huesos", "tifoidea que afecta la estructura ósea"]'),
('A01.09', 'Fiebre tifoidea con otras complicaciones', 'Sin especificar', '["tifoidea complicada", "tifoidea severa", "tifoidea con malestares extra", "fiebre tifoidea grave", "tifoidea con secuelas", "complicaciones por salmonella", "tifoidea con fallos orgánicos", "fiebre tífica grave", "tifoidea con crisis", "urgencia por tifoidea", "tifoidea que no cede"]'),
('A01.1', 'Fiebre paratifoidea A', 'Sin especificar', '["paratifoidea A", "fiebre paratifoidea tipo A", "salmonelosis paratifoidea", "paratifus A", "fiebre similar a la tifoidea A", "infección paratifoidea", "fiebre por paratifoidea A", "tifoidea leve A", "brote paratifoideo A", "malestar estomacal por paratifoidea A"]'),
('A01.2', 'Fiebre paratifoidea B', 'Sin especificar', '["paratifoidea B", "fiebre paratifoidea tipo B", "paratifus B", "infección bacteriana paratifoidea B", "fiebre entérica B", "salmonella paratyphi B", "fiebre paratifoidea tipo B", "malestar abdominal por paratifoidea B", "paratifoidea tipo B", "diarrea por paratifoidea B"]'),
('A01.3', 'Fiebre paratifoidea C', 'Sin especificar', '["paratifoidea C", "fiebre paratifoidea tipo C", "paratifus C", "infección por salmonella tipo C", "fiebre entérica C", "paratifoidea tipo C", "fiebre tropical paratifoidea", "complicación paratifoidea C", "cuadro de paratifoidea C", "salmonella paratyphi C"]'),
('A01.4', 'Fiebre paratifoidea, no especificada', 'Sin especificar', '["paratifoidea no especificada", "fiebre paratifoidea sin especificar", "paratifus", "infección paratifoidea sin definir", "fiebre similar a tifoidea", "sospecha de paratifoidea", "cuadro de fiebre paratifoidea", "salmonelosis general", "fiebre entérica no clasificada", "malestar por paratifoidea"]');
