INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z80.0', 'Historia familiar de neoplasia maligna de órganos digestivos', 'Sin especificar', '["cáncer estomacal", "cáncer de colon", "antecedentes cáncer gástrico", "tumor digestivo", "cáncer en la panza", "cáncer intestinal", "cáncer en la guata", "cáncer en el estómago", "adenocarcinoma digestivo", "herencia cáncer estomacal", "cáncer del aparato digestivo", "cáncer de guata", "cáncer en la barriga", "antecedentes familiares tumores digestivos"]'),
('Z80.1', 'Historia familiar de neoplasia maligna de tráquea, bronquios y pulmón', 'Sin especificar', '["cáncer de pulmón", "cáncer pulmonar", "cáncer de pecho", "antecedentes cáncer bronquial", "tumor en los pulmones", "herencia cáncer de pulmón", "cáncer de fumador", "mancha en el pulmón", "cáncer respiratorio", "historial familiar de cáncer pulmón", "cáncer de tráquea", "tumor bronquial"]'),
('Z80.2', 'Historia familiar de neoplasia maligna de otros órganos respiratorios e intratorácicos', 'Sin especificar', '["cáncer de pleura", "mesotelioma", "cáncer de mediastino", "tumor torácico", "antecedentes cáncer respiratorio", "cáncer en el pecho", "tumor en el tórax", "neoplasia intratorácica", "cáncer de vías aéreas", "historia familiar tumores tórax"]'),
('Z80.3', 'Historia familiar de neoplasia maligna de mama', 'Sin especificar', '["cáncer de mama", "cáncer de seno", "antecedentes cáncer de pecho", "tumor en el seno", "bolita en el seno", "historial cáncer de mama", "herencia cáncer de seno", "mastología", "cáncer de teta", "cáncer de chiche", "antecedentes familiares cáncer mama"]'),
('Z80.41', 'Historia familiar de neoplasia maligna de ovario', 'Sin especificar', '["cáncer de ovario", "tumor en los ovarios", "cáncer ovárico", "antecedentes cáncer de matriz", "quistes malignos ovario", "historial cáncer ovarios", "herencia cáncer ginecológico", "cáncer de ovarios", "masa en los ovarios"]'),
('Z80.42', 'Historia familiar de neoplasia maligna de próstata', 'Sin especificar', '["cáncer de próstata", "cáncer prostático", "tumor en la próstata", "antecedentes cáncer de próstata", "problemas de orina cáncer", "PSA elevado cáncer", "historia familiar cáncer próstata", "herencia cáncer de próstata", "cáncer del varón"]'),
('Z80.43', 'Historia familiar de neoplasia maligna de testículo', 'Sin especificar', '["cáncer de testículo", "tumor testicular", "antecedentes cáncer testicular", "bolita en el testículo", "cáncer en los huevos", "herencia cáncer testicular", "tumor en las bolas", "historial cáncer de testículo", "cáncer escrotal"]'),
('Z80.49', 'Historia familiar de neoplasia maligna de otros órganos genitales', 'Sin especificar', '["cáncer genital", "cáncer de útero", "cáncer de matriz", "cáncer de cuello uterino", "cáncer cervical", "cáncer de cérvix", "cáncer de vulva", "cáncer de pene", "antecedentes cáncer genital", "tumor aparato reproductor"]'),
('Z80.51', 'Historia familiar de neoplasia maligna de riñón', 'Sin especificar', '["cáncer de riñón", "tumor renal", "cáncer renal", "antecedentes cáncer riñón", "dolor en la espalda baja cáncer", "historial cáncer de riñón", "herencia tumor renal", "masa en el riñón"]'),
('Z80.52', 'Historia familiar de neoplasia maligna de vejiga', 'Sin especificar', '["cáncer de vejiga", "sangre en la orina cáncer", "tumor en la vejiga", "antecedentes cáncer de vejiga", "cáncer urinario", "historia familiar tumores vejiga", "cáncer de la orina"]'),
('Z80.59', 'Historia familiar de neoplasia maligna de otros órganos del tracto urinario', 'Sin especificar', '["cáncer vías urinarias", "cáncer uréter", "tumor tracto urinario", "antecedentes cáncer urinario", "cáncer urotelial", "historial cáncer sistema urinario"]'),
('Z80.6', 'Historia familiar de leucemia', 'Sin especificar', '["leucemia", "cáncer en la sangre", "antecedentes leucemia", "cáncer sanguíneo", "cáncer de médula", "historial leucemia familiar", "herencia leucemia", "leucemia infantil familiar", "enfermedad de la sangre"]'),
('Z80.7', 'Historia familiar de otras neoplasias malignas de los tejidos linfáticos, hemopoyéticos y otros tejidos relacionados', 'Sin especificar', '["linfoma", "cáncer linfático", "ganglios inflamados cáncer", "linfoma de hodgkin", "linfoma no hodgkin", "cáncer sistema linfático", "antecedentes linfoma", "tumor en los ganglios", "historia familiar cáncer sangre"]'),
('Z80.8', 'Historia familiar de neoplasia maligna de otros órganos o sistemas', 'Sin especificar', '["otros tipos de cáncer", "antecedentes cáncer familiar", "tumor hereditario", "historial cáncer otros órganos", "cáncer raro familiar", "historia familiar tumores", "neoplasia familiar no especificada"]'),
('Z80.9', 'Historia familiar de neoplasia maligna, no especificada', 'Sin especificar', '["antecedentes cáncer en la familia", "cáncer hereditario", "historia de cáncer", "familia con cáncer", "herencia de tumores", "historial de neoplasias", "mi familia tuvo cáncer", "antecedentes malignos familiares"]');
