INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q10.0', 'Ptosis congénita', 'Sin especificar', '["párpado caído", "ojo cerrado", "párpado perezoso", "ojo dormido", "caída del párpado", "ptosis palpebral", "párpado que no abre", "párpado pesado", "ojo entrecerrado", "párpado caído al nacer", "ptosis desde nacimiento", "descolgamiento de párpado", "ojito cerrado", "párpado flácido", "debilidad del elevador del párpado"]'),
('Q10.1', 'Ectropión congénito', 'Sin especificar', '["párpado hacia afuera", "ojo volteado", "párpado evertido", "ojo lloroso congénito", "borde del párpado separado", "párpado suelto", "ojo irritado por párpado", "párpado caído hacia afuera", "malformación de párpado", "párpado que no cierra bien", "ojo expuesto", "ectropion al nacer", "párpado despegado del ojo"]'),
('Q10.2', 'Entropión congénito', 'Sin especificar', '["párpado hacia adentro", "pestañas contra el ojo", "párpado invertido", "párpado que raspa el ojo", "ojo irritado por pestañas", "entropion al nacer", "pestañas adentro", "ojo rojo por roce", "malformación de borde palpebral", "párpado metido", "párpado que choca con el globo ocular", "dolor ocular congénito", "ojo lagrimoso por roce"]'),
('Q10.3', 'Otras malformaciones congénitas de los párpados', 'Sin especificar', '["deformidad de párpado", "párpado raro", "ojos diferentes", "anomalía de párpados", "coloboma palpebral", "fisura en el párpado", "párpado incompleto", "falta de párpado", "párpado unido", "anomalías congénitas oculares", "defecto en los ojos", "párpados pequeños", "párpados mal formados"]'),
('Q10.4', 'Agenesia y ausencia del aparato lagrimal', 'Sin especificar', '["ojo seco congénito", "falta de lagrimal", "ojo que no llora", "sin lagrimales", "ausencia de glándula lagrimal", "problemas de lagrimeo", "ojo siempre seco", "falta de producción de lágrimas", "malformación del sistema lagrimal", "no le salen lágrimas", "agenesia lagrimal", "ojos sin lubricación natural"]'),
('Q10.5', 'Estenosis o estrechez congénita del conducto lagrimal', 'Sin especificar', '["conducto lagrimal tapado", "lagrimal obstruido", "ojo lloroso", "lagrimeo constante", "conducto lagrimal cerrado", "ojo con lagañas", "lagrimeo del bebé", "conducto bloqueado", "ojo que lagrimea siempre", "obstrucción congénita", "lagrimal obstruido al nacer", "lagañas constantes en el ojo", "drenaje lagrimal cerrado"]'),
('Q10.6', 'Otras malformaciones congénitas del aparato lacrimal', 'Sin especificar', '["quiste lagrimal", "bulto en el lagrimal", "problema en los ojos", "malformación en vías lagrimales", "anomalía de la glándula lagrimal", "tumor lagrimal congénito", "fístula lagrimal", "drenaje lagrimal anormal", "problema de los lagrimales", "anomalías congénitas oculares", "inflamación lagrimal crónica"]'),
('Q10.7', 'Malformación congénita de la órbita', 'Sin especificar', '["ojo hundido", "ojo saltón", "deformidad del hueso del ojo", "órbita pequeña", "ojo fuera de lugar", "asimetría de la cara", "problema de cuenca del ojo", "anomalía órbito-facial", "ojo desalineado congénito", "hueso del ojo mal formado", "órbita poco profunda", "malformación facial congénita", "ojo muy metido o muy salido"]');
