INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H16.001', 'Úlcera corneal no especificada, ojo derecho', 'Sin especificar', '["herida en el ojo", "ojo derecho irritado", "dolor de ojo", "rasguño en la córnea", "ojo rojo", "visión borrosa", "sensación de arenilla", "fotofobia", "clavo en el ojo", "ulcera ocular", "ojo lagrimeante", "infección en el ojo derecho", "picor en el ojo", "pinchazos en el ojo"]'),
('H16.002', 'Úlcera corneal no especificada, ojo izquierdo', 'Sin especificar', '["herida en el ojo", "ojo izquierdo irritado", "dolor de ojo", "rasguño en la córnea", "ojo rojo", "visión borrosa", "sensación de arenilla", "fotofobia", "clavo en el ojo", "ulcera ocular", "ojo lagrimeante", "infección en el ojo izquierdo", "picor en el ojo", "pinchazos en el ojo"]'),
('H16.003', 'Úlcera corneal no especificada, bilateral', 'Sin especificar', '["herida en ambos ojos", "dolor de ojos", "ojos rojos", "visión borrosa en ambos ojos", "sensación de arena en los ojos", "fotofobia severa", "ulceras en los ojos", "ojos llorosos", "infección ocular bilateral", "picor intenso en los ojos"]'),
('H16.009', 'Úlcera corneal no especificada, ojo no especificado', 'Sin especificar', '["herida en el ojo", "dolor ocular", "ojo irritado", "rasguño corneal", "visión nublada", "arenilla en el ojo", "luz molesta", "ulcera en la córnea", "ojo inflamado", "pinchazos oculares"]'),
('H16.011', 'Úlcera corneal central, ojo derecho', 'Sin especificar', '["mancha en el centro del ojo", "punto blanco en el ojo", "dolor en la pupila", "ulcera central", "ojo derecho nublado", "visión tapada", "infección corneal central"]'),
('H16.012', 'Úlcera corneal central, ojo izquierdo', 'Sin especificar', '["mancha en el centro del ojo", "punto blanco en el ojo", "dolor en la pupila", "ulcera central", "ojo izquierdo nublado", "visión tapada", "infección corneal central"]'),
('H16.013', 'Úlcera corneal central, bilateral', 'Sin especificar', '["manchas blancas en los ojos", "dolor central en ambos ojos", "visión central borrosa", "ulceras corneales centrales", "problema visual central"]'),
('H16.019', 'Úlcera corneal central, ojo no especificado', 'Sin especificar', '["mancha central en el ojo", "punto en la córnea", "dolor al mirar al frente", "ulcera corneal focal"]'),
('H16.021', 'Úlcera corneal en anillo, ojo derecho', 'Sin especificar', '["anillo blanco en el ojo", "ulcera circular ojo derecho", "cerco en la córnea", "infección corneal anular"]'),
('H16.022', 'Úlcera corneal en anillo, ojo izquierdo', 'Sin especificar', '["anillo blanco en el ojo", "ulcera circular ojo izquierdo", "cerco en la córnea", "infección corneal anular"]'),
('H16.023', 'Úlcera corneal en anillo, bilateral', 'Sin especificar', '["anillos en ambos ojos", "ulceras circulares", "cerco corneal bilateral", "infección ocular en anillo"]'),
('H16.029', 'Úlcera corneal en anillo, ojo no especificado', 'Sin especificar', '["anillo en la córnea", "ulcera corneal circular", "cerco blanco en el ojo"]'),
('H16.031', 'Úlcera corneal con hipopión, ojo derecho', 'Sin especificar', '["pus en el ojo", "nivel de pus en el ojo", "ojo derecho con material blanco", "infección grave ojo derecho", "ulceración con pus"]'),
('H16.032', 'Úlcera corneal con hipopión, ojo izquierdo', 'Sin especificar', '["pus en el ojo", "nivel de pus en el ojo", "ojo izquierdo con material blanco", "infección grave ojo izquierdo", "ulceración con pus"]'),
('H16.033', 'Úlcera corneal con hipopión, bilateral', 'Sin especificar', '["pus en ambos ojos", "niveles de pus ocular", "infección severa bilateral", "ulceras corneales purulentas"]'),
('H16.039', 'Úlcera corneal con hipopión, ojo no especificado', 'Sin especificar', '["pus en la cámara anterior", "infección corneal con pus", "ojo infectado con secreción"]'),
('H16.041', 'Úlcera corneal marginal, ojo derecho', 'Sin especificar', '["ulcera en borde del ojo", "infección corneal lateral", "ojo rojo marginal", "dolor en la periferia del ojo derecho"]'),
('H16.042', 'Úlcera corneal marginal, ojo izquierdo', 'Sin especificar', '["ulcera en borde del ojo", "infección corneal lateral", "ojo rojo marginal", "dolor en la periferia del ojo izquierdo"]'),
('H16.043', 'Úlcera corneal marginal, bilateral', 'Sin especificar', '["ulceras en bordes oculares", "irritación marginal bilateral", "dolor periférico en ojos"]'),
('H16.049', 'Úlcera corneal marginal, ojo no especificado', 'Sin especificar', '["ulcera periférica", "infección en borde de córnea", "ojo irritado lateralmente"]'),
('H16.051', 'Úlcera corneal de Mooren, ojo derecho', 'Sin especificar', '["ulcera de Mooren", "erosión corneal crónica", "enfermedad autoinmune ojo derecho", "ulcera periférica progresiva"]'),
('H16.052', 'Úlcera corneal de Mooren, ojo izquierdo', 'Sin especificar', '["ulcera de Mooren", "erosión corneal crónica", "enfermedad autoinmune ojo izquierdo", "ulcera periférica progresiva"]'),
('H16.053', 'Úlcera corneal de Mooren, bilateral', 'Sin especificar', '["ulceras de Mooren ambos ojos", "erosión corneal autoinmune", "daño corneal progresivo"]'),
('H16.059', 'Úlcera corneal de Mooren, ojo no especificado', 'Sin especificar', '["ulcera de Mooren", "ulcera ocular autoinmune", "degradación corneal"]'),
('H16.061', 'Úlcera corneal micótica, ojo derecho', 'Sin especificar', '["hongos en el ojo", "infección por hongos córnea", "ojo derecho micótico", "ulcera por vegetación", "infección fúngica ocular"]'),
('H16.062', 'Úlcera corneal micótica, ojo izquierdo', 'Sin especificar', '["hongos en el ojo", "infección por hongos córnea", "ojo izquierdo micótico", "ulcera por vegetación", "infección fúngica ocular"]'),
('H16.063', 'Úlcera corneal micótica, bilateral', 'Sin especificar', '["hongos en ambos ojos", "infección fúngica corneal bilateral", "ulceras por hongos en ojos"]'),
('H16.069', 'Úlcera corneal micótica, ojo no especificado', 'Sin especificar', '["infección micótica ocular", "hongos en la córnea", "ulcera corneal infecciosa"]'),
('H16.071', 'Úlcera corneal perforada, ojo derecho', 'Sin especificar', '["agujero en el ojo", "córnea perforada", "ojo derecho roto", "herida abierta en córnea", "fuga de humor acuoso"]'),
('H16.072', 'Úlcera corneal perforada, ojo izquierdo', 'Sin especificar', '["agujero en el ojo", "córnea perforada", "ojo izquierdo roto", "herida abierta en córnea", "fuga de humor acuoso"]'),
('H16.073', 'Úlcera corneal perforada, bilateral', 'Sin especificar', '["perforaciones oculares", "córneas abiertas", "ruptura corneal bilateral", "emergencia oftalmológica"]'),
('H16.079', 'Úlcera corneal perforada, ojo no especificado', 'Sin especificar', '["perforación de córnea", "ojo perforado", "ulcera profunda con apertura"]'),
('H16.101', 'Queratitis superficial no especificada, ojo derecho', 'Sin especificar', '["irritación corneal", "ojo derecho rayado", "inflamación superficie ojo", "queratitis derecha", "ojo arenoso"]'),
('H16.102', 'Queratitis superficial no especificada, ojo izquierdo', 'Sin especificar', '["irritación corneal", "ojo izquierdo rayado", "inflamación superficie ojo", "queratitis izquierda", "ojo arenoso"]'),
('H16.103', 'Queratitis superficial no especificada, bilateral', 'Sin especificar', '["queratitis en ambos ojos", "irritación ocular superficial", "ojos inflamados", "inflamación de la córnea"]'),
('H16.109', 'Queratitis superficial no especificada, ojo no especificado', 'Sin especificar', '["inflamación corneal", "queratitis", "ojo con arenilla", "superficie ocular dañada"]'),
('H16.111', 'Queratitis macular, ojo derecho', 'Sin especificar', '["mancha en la córnea", "queratitis con manchas", "opacidad corneal ojo derecho", "ojo nublado"]'),
('H16.112', 'Queratitis macular, ojo izquierdo', 'Sin especificar', '["mancha en la córnea", "queratitis con manchas", "opacidad corneal ojo izquierdo", "ojo nublado"]'),
('H16.113', 'Queratitis macular, bilateral', 'Sin especificar', '["manchas en córneas", "queratitis macular bilateral", "ojos con manchas opacas"]'),
('H16.119', 'Queratitis macular, ojo no especificado', 'Sin especificar', '["queratitis por manchas", "opacidad en el ojo", "mancha corneal"]'),
('H16.121', 'Queratitis filamentosa, ojo derecho', 'Sin especificar', '["hilos en el ojo", "cuerdas en la córnea", "ojo derecho con filamentos", "queratitis por sequedad"]'),
('H16.122', 'Queratitis filamentosa, ojo izquierdo', 'Sin especificar', '["hilos en el ojo", "cuerdas en la córnea", "ojo izquierdo con filamentos", "queratitis por sequedad"]'),
('H16.123', 'Queratitis filamentosa, bilateral', 'Sin especificar', '["filamentos en ambos ojos", "ojos con hilos", "sequedad ocular con filamentos"]'),
('H16.129', 'Queratitis filamentosa, ojo no especificado', 'Sin especificar', '["queratitis con filamentos", "ojo con mucosidad pegada", "sequedad extrema con hilos"]'),
('H16.131', 'Fotoqueratitis, ojo derecho', 'Sin especificar', '["ojo quemado por sol", "queratitis por soldadura", "ojo derecho quemado", "quemadura solar ojo", "ojo quemado por reflejo"]'),
('H16.132', 'Fotoqueratitis, ojo izquierdo', 'Sin especificar', '["ojo quemado por sol", "queratitis por soldadura", "ojo izquierdo quemado", "quemadura solar ojo", "ojo quemado por reflejo"]'),
('H16.133', 'Fotoqueratitis, bilateral', 'Sin especificar', '["ojos quemados por luz", "quemadura por soldadura en ambos ojos", "ceguera temporal por luz", "fotoqueratitis bilateral"]'),
('H16.139', 'Fotoqueratitis, ojo no especificado', 'Sin especificar', '["ojo quemado por luz", "lesión ocular por rayos UV", "quemadura corneal"]'),
('H16.141', 'Queratitis punteada, ojo derecho', 'Sin especificar', '["puntitos en el ojo", "queratitis con puntos", "ojo derecho picado", "irritación con puntos oculares"]'),
('H16.142', 'Queratitis punteada, ojo izquierdo', 'Sin especificar', '["puntitos en el ojo", "queratitis con puntos", "ojo izquierdo picado", "irritación con puntos oculares"]'),
('H16.143', 'Queratitis punteada, bilateral', 'Sin especificar', '["puntos en ambos ojos", "queratitis punteada bilateral", "ojos con irritación punteada"]'),
('H16.149', 'Queratitis punteada, ojo no especificado', 'Sin especificar', '["queratitis con puntilleo", "puntos en la córnea", "ojo irritado por puntos"]'),
('H16.201', 'Queratoconjuntivitis no especificada, ojo derecho', 'Sin especificar', '["ojo rojo e irritado", "infección conjuntiva y córnea", "ojo derecho pegajoso", "inflamación ojo derecho", "conjuntivitis y queratitis"]'),
('H16.202', 'Queratoconjuntivitis no especificada, ojo izquierdo', 'Sin especificar', '["ojo rojo e irritado", "infección conjuntiva y córnea", "ojo izquierdo pegajoso", "inflamación ojo izquierdo", "conjuntivitis y queratitis"]'),
('H16.203', 'Queratoconjuntivitis no especificada, bilateral', 'Sin especificar', '["ojos rojos e irritados", "infección ocular doble", "ojos pegajosos", "inflamación bilateral"]'),
('H16.209', 'Queratoconjuntivitis no especificada, ojo no especificado', 'Sin especificar', '["inflamación de ojo y párpados", "ojo rojo", "infección superficial ocular"]'),
('H16.211', 'Queratoconjuntivitis por exposición, ojo derecho', 'Sin especificar', '["ojo seco por no cerrar", "ojo expuesto al aire", "parálisis facial ojo", "ojo derecho abierto", "queratitis por exposición"]'),
('H16.212', 'Queratoconjuntivitis por exposición, ojo izquierdo', 'Sin especificar', '["ojo seco por no cerrar", "ojo expuesto al aire", "parálisis facial ojo", "ojo izquierdo abierto", "queratitis por exposición"]'),
('H16.213', 'Queratoconjuntivitis por exposición, bilateral', 'Sin especificar', '["ojos expuestos", "ojos que no cierran bien", "sequedad por exposición bilateral"]'),
('H16.219', 'Queratoconjuntivitis por exposición, ojo no especificado', 'Sin especificar', '["ojo reseco por exposición", "córnea seca por párpados abiertos", "exposición ocular"]'),
('H16.221', 'Queratoconjuntivitis seca, no especificada como de Sjögren, ojo derecho', 'Sin especificar', '["ojo seco", "falta de lágrimas", "arenilla en el ojo derecho", "ojo derecho irritado por sequedad", "ardor ocular derecho"]'),
('H16.222', 'Queratoconjuntivitis seca, no especificada como de Sjögren, ojo izquierdo', 'Sin especificar', '["ojo seco", "falta de lágrimas", "arenilla en el ojo izquierdo", "ojo izquierdo irritado por sequedad", "ardor ocular izquierdo"]'),
('H16.223', 'Queratoconjuntivitis seca, no especificada como de Sjögren, bilateral', 'Sin especificar', '["ojos secos", "ojos sin lágrimas", "ojo seco bilateral", "ardor en ambos ojos", "sequedad crónica ocular"]'),
('H16.229', 'Queratoconjuntivitis seca, no especificada como de Sjögren, ojo no especificado', 'Sin especificar', '["sequedad de ojos", "ojos irritados por sequedad", "falta de lubricación ocular"]'),
('H16.231', 'Queratoconjuntivitis neurotrófica, ojo derecho', 'Sin especificar', '["ojo sin sensibilidad", "córnea insensible", "daño corneal por falta de nervio", "ojo derecho sin dolor pero dañado"]'),
('H16.232', 'Queratoconjuntivitis neurotrófica, ojo izquierdo', 'Sin especificar', '["ojo sin sensibilidad", "córnea insensible", "daño corneal por falta de nervio", "ojo izquierdo sin dolor pero dañado"]'),
('H16.233', 'Queratoconjuntivitis neurotrófica, bilateral', 'Sin especificar', '["ojos insensibles", "daño corneal bilateral por nervios", "queratitis sin dolor"]'),
('H16.239', 'Queratoconjuntivitis neurotrófica, ojo no especificado', 'Sin especificar', '["córnea anestesiada", "queratitis neurotrófica", "falta de sensibilidad ocular"]'),
('H16.241', 'Oftalmía nodosa, ojo derecho', 'Sin especificar', '["bultos en el ojo", "pelos en el ojo", "reacción a pelos de oruga", "nódulos oculares ojo derecho"]'),
('H16.242', 'Oftalmía nodosa, ojo izquierdo', 'Sin especificar', '["bultos en el ojo", "pelos en el ojo", "reacción a pelos de oruga", "nódulos oculares ojo izquierdo"]'),
('H16.243', 'Oftalmía nodosa, bilateral', 'Sin especificar', '["bultos en ambos ojos", "reacción a cuerpos extraños", "oftalmía nodosa bilateral"]'),
('H16.249', 'Oftalmía nodosa, ojo no especificado', 'Sin especificar', '["nódulos por cuerpo extraño", "reacción inflamatoria nodular ocular"]'),
('H16.251', 'Queratoconjuntivitis flictenular, ojo derecho', 'Sin especificar', '["ampollas en el ojo", "bultitos oculares", "alergia ocular ojo derecho", "flictenas en la córnea"]'),
('H16.252', 'Queratoconjuntivitis flictenular, ojo izquierdo', 'Sin especificar', '["ampollas en el ojo", "bultitos oculares", "alergia ocular ojo izquierdo", "flictenas en la córnea"]'),
('H16.253', 'Queratoconjuntivitis flictenular, bilateral', 'Sin especificar', '["ampollas en ambos ojos", "reacción alérgica ocular", "nódulos flictenulares"]'),
('H16.259', 'Queratoconjuntivitis flictenular, ojo no especificado', 'Sin especificar', '["queratitis alérgica", "flictenas oculares", "bultos en la conjuntiva"]'),
('H16.261', 'Queratoconjuntivitis vernal, con afectación de limbo y córnea, ojo derecho', 'Sin especificar', '["alergia ocular severa", "picazón de ojos primavera", "ojo derecho alérgico", "vernal ocular derecho"]'),
('H16.262', 'Queratoconjuntivitis vernal, con afectación de limbo y córnea, ojo izquierdo', 'Sin especificar', '["alergia ocular severa", "picazón de ojos primavera", "ojo izquierdo alérgico", "vernal ocular izquierdo"]'),
('H16.263', 'Queratoconjuntivitis vernal, con afectación de limbo y córnea, bilateral', 'Sin especificar', '["ojos alérgicos primaverales", "alergia ocular crónica", "queratoconjuntivitis vernal bilateral"]'),
('H16.269', 'Queratoconjuntivitis vernal, con afectación de limbo y córnea, ojo no especificado', 'Sin especificar', '["alergia ocular estacional", "queratoconjuntivitis vernal"]'),
('H16.291', 'Otras queratoconjuntivitis, ojo derecho', 'Sin especificar', '["inflamación combinada ojo derecho", "infección de ojo y párpados derecho"]'),
('H16.292', 'Otras queratoconjuntivitis, ojo izquierdo', 'Sin especificar', '["inflamación combinada ojo izquierdo", "infección de ojo y párpados izquierdo"]'),
('H16.293', 'Otras queratoconjuntivitis, bilateral', 'Sin especificar', '["inflamación combinada ambos ojos", "conjuntivitis y queratitis mixta"]'),
('H16.299', 'Otras queratoconjuntivitis, ojo no especificado', 'Sin especificar', '["inflamación ocular mixta", "queratoconjuntivitis otra"]'),
('H16.301', 'Queratitis intersticial no especificada, ojo derecho', 'Sin especificar', '["inflamación profunda ojo derecho", "queratitis profunda", "ojo nublado por dentro"]'),
('H16.302', 'Queratitis intersticial no especificada, ojo izquierdo', 'Sin especificar', '["inflamación profunda ojo izquierdo", "queratitis profunda", "ojo nublado por dentro"]'),
('H16.303', 'Queratitis intersticial no especificada, bilateral', 'Sin especificar', '["queratitis profunda ambos ojos", "inflamación corneal interna bilateral"]'),
('H16.309', 'Queratitis intersticial no especificada, ojo no especificado', 'Sin especificar', '["queratitis intersticial", "inflamación estromal"]'),
('H16.311', 'Absceso de córnea, ojo derecho', 'Sin especificar', '["infección con pus ojo derecho", "absceso ocular", "mancha amarilla en el ojo"]'),
('H16.312', 'Absceso de córnea, ojo izquierdo', 'Sin especificar', '["infección con pus ojo izquierdo", "absceso ocular", "mancha amarilla en el ojo"]'),
('H16.313', 'Absceso de córnea, bilateral', 'Sin especificar', '["abscesos en ambos ojos", "infecciones purulentas oculares"]'),
('H16.319', 'Absceso de córnea, ojo no especificado', 'Sin especificar', '["absceso en la córnea", "infección profunda ocular"]'),
('H16.321', 'Queratitis intersticial difusa, ojo derecho', 'Sin especificar', '["queratitis difusa ojo derecho", "inflamación extendida córnea"]'),
('H16.322', 'Queratitis intersticial difusa, ojo izquierdo', 'Sin especificar', '["queratitis difusa ojo izquierdo", "inflamación extendida córnea"]'),
('H16.323', 'Queratitis intersticial difusa, bilateral', 'Sin especificar', '["inflamación corneal extendida", "queratitis intersticial bilateral"]'),
('H16.329', 'Queratitis intersticial difusa, ojo no especificado', 'Sin especificar', '["queratitis profunda diseminada", "córnea inflamada difusamente"]'),
('H16.331', 'Queratitis esclerosante, ojo derecho', 'Sin especificar', '["córnea blanca ojo derecho", "esclerotización corneal", "ojo que se pone blanco"]'),
('H16.332', 'Queratitis esclerosante, ojo izquierdo', 'Sin especificar', '["córnea blanca ojo izquierdo", "esclerotización corneal", "ojo que se pone blanco"]'),
('H16.333', 'Queratitis esclerosante, bilateral', 'Sin especificar', '["córneas esclerosadas", "endurecimiento corneal bilateral"]'),
('H16.339', 'Queratitis esclerosante, ojo no especificado', 'Sin especificar', '["queratitis que blanquea la córnea", "esclerosis corneal"]'),
('H16.391', 'Otros tipos de queratitis intersticial y profunda, ojo derecho', 'Sin especificar', '["queratitis profunda ojo derecho", "infección interna córnea derecha"]'),
('H16.392', 'Otros tipos de queratitis intersticial y profunda, ojo izquierdo', 'Sin especificar', '["queratitis profunda ojo izquierdo", "infección interna córnea izquierda"]'),
('H16.393', 'Otros tipos de queratitis intersticial y profunda, bilateral', 'Sin especificar', '["queratitis profundas", "inflamación interna ocular"]'),
('H16.399', 'Otros tipos de queratitis intersticial y profunda, ojo no especificado', 'Sin especificar', '["queratitis interna", "inflamación estromal corneal"]'),
('H16.401', 'Neovascularización corneal no especificada, ojo derecho', 'Sin especificar', '["venas en el ojo derecho", "vasos sanguíneos en córnea", "ojo con venitas rojas"]'),
('H16.402', 'Neovascularización corneal no especificada, ojo izquierdo', 'Sin especificar', '["venas en el ojo izquierdo", "vasos sanguíneos en córnea", "ojo con venitas rojas"]'),
('H16.403', 'Neovascularización corneal no especificada, bilateral', 'Sin especificar', '["vasos sanguíneos en ambos ojos", "venas creciendo en la córnea"]'),
('H16.409', 'Neovascularización corneal no especificada, ojo no especificado', 'Sin especificar', '["vascularización corneal", "vasos en la córnea"]'),
('H16.411', 'Vasos fantasma (corneales), ojo derecho', 'Sin especificar', '["venas viejas en ojo derecho", "vasos invisibles córnea", "rastro de vasos en ojo"]'),
('H16.412', 'Vasos fantasma (corneales), ojo izquierdo', 'Sin especificar', '["venas viejas en ojo izquierdo", "vasos invisibles córnea", "rastro de vasos en ojo"]'),
('H16.413', 'Vasos fantasma (corneales), bilateral', 'Sin especificar', '["vasos fantasma", "marcas vasculares antiguas córnea"]'),
('H16.419', 'Vasos fantasma (corneales), ojo no especificado', 'Sin especificar', '["vasos corneales atróficos", "huellas de vasos en ojo"]'),
('H16.421', 'Pannus (corneal), ojo derecho', 'Sin especificar', '["telita en el ojo derecho", "pannus corneal", "tejido sobre el ojo"]'),
('H16.422', 'Pannus (corneal), ojo izquierdo', 'Sin especificar', '["telita en el ojo izquierdo", "pannus corneal", "tejido sobre el ojo"]'),
('H16.423', 'Pannus (corneal), bilateral', 'Sin especificar', '["pannus en ambos ojos", "tejido sobre las córneas"]'),
('H16.429', 'Pannus (corneal), ojo no especificado', 'Sin especificar', '["pannus", "crecimiento de tejido corneal"]'),
('H16.431', 'Vascularización localizada de córnea, ojo derecho', 'Sin especificar', '["vasos en un punto del ojo", "venas locales córnea derecha"]'),
('H16.432', 'Vascularización localizada de córnea, ojo izquierdo', 'Sin especificar', '["vasos en un punto del ojo", "venas locales córnea izquierda"]'),
('H16.433', 'Vascularización localizada de córnea, bilateral', 'Sin especificar', '["vasos localizados ambos ojos", "venas puntuales córnea"]'),
('H16.439', 'Vascularización localizada de córnea, ojo no especificado', 'Sin especificar', '["venas en parte de la córnea", "vascularización corneal focal"]'),
('H16.441', 'Vascularización profunda de córnea, ojo derecho', 'Sin especificar', '["venas profundas córnea derecha", "vascularización estromal ojo"]'),
('H16.442', 'Vascularización profunda de córnea, ojo izquierdo', 'Sin especificar', '["venas profundas córnea izquierda", "vascularización estromal ojo"]'),
('H16.443', 'Vascularización profunda de córnea, bilateral', 'Sin especificar', '["vasos profundos córneas", "vascularización estromal bilateral"]'),
('H16.449', 'Vascularización profunda de córnea, ojo no especificado', 'Sin especificar', '["vascularización profunda", "venas profundas en el ojo"]'),
('H16.8', 'Otras queratitis', 'Sin especificar', '["inflamación corneal", "problema en córnea", "queratitis", "ojo irritado y nublado"]'),
('H16.9', 'Queratitis no especificada', 'Sin especificar', '["queratitis", "inflamación de la córnea", "ojo dolorido y nublado", "dolor corneal"]');
