INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K75.0', 'Absceso de hígado', 'Sin especificar', '["absceso hepático", "pus en el hígado", "infección en el hígado", "quiste infectado hígado", "dolor en el cuadrante superior derecho", "fiebre alta hígado", "hígado inflamado", "hinchazón abdominal", "dolor en la panza", "dolor en la guata", "dolor en la barriga", "dolor bajo las costillas", "hígado con pus", "amebiasis hepática", "absceso piógeno"]'),
('K75.1', 'Flebitis de vena porta', 'Sin especificar', '["piletitis", "inflamación vena porta", "trombosis venosa portal", "vena del hígado tapada", "dolor abdominal intenso", "infección sistema porta", "problemas de circulación hígado", "dolor en la guata", "dolor en la panza", "hipertensión portal", "ictericia", "fiebre y escalofríos", "dolor visceral", "problemas de venas hígado", "obstrucción portal"]'),
('K75.2', 'Hepatitis reactiva inespecífica', 'Sin especificar', '["hígado inflamado", "hepatitis leve", "hígado irritado", "elevación transaminasas", "dolor en el hipocondrio derecho", "malestar general", "hígado sensible", "inflamación hepática", "hígado con reacción", "dolor en la panza", "dolor en el abdomen", "fatiga hepática", "problemas hepáticos inespecíficos", "hígado resentido", "ictericia leve"]'),
('K75.3', 'Hepatitis granulomatosa, no clasificada bajo otro concepto', 'Sin especificar', '["inflamación granulomatosa hígado", "bolitas en el hígado", "nódulos en el hígado", "hígado inflamado", "hepatitis crónica", "hígado con granulomas", "dolor abdominal persistente", "fatiga crónica", "problemas hepáticos", "dolor bajo las costillas", "hígado endurecido", "malestar abdominal", "estudio de hígado", "hepatitis poco común", "inflamación sistémica hígado"]'),
('K75.4', 'Hepatitis autoinmune', 'Sin especificar', '["mis defensas atacan el hígado", "hepatitis autoinmune", "inflamación autoinmune hígado", "hígado atacado por sistema inmune", "hígado inflamado", "fatiga extrema", "dolor en la panza", "ictericia", "piel amarilla", "ojos amarillos", "hígado crónico", "enfermedad autoinmune hígado", "dolor en la guata", "malestar hepático", "transaminasas altas"]'),
('K75.81', 'Esteatohepatitis no alcohólica (EHNA)', 'Sin especificar', '["hígado graso no alcohólico", "hígado con grasa", "hígado inflamado por grasa", "esteatosis hepática", "grasa en el hígado", "hígado pesado", "dolor en la panza", "dolor en la guata", "metabolismo hepático", "obesidad y hígado", "resistencia a la insulina hígado", "hígado agrandado", "hígado con cicatrices", "esteatohepatitis", "cirrosis por grasa"]'),
('K75.89', 'Otras enfermedades inflamatorias especificadas del hígado', 'Sin especificar', '["inflamación del hígado", "hígado irritado", "dolor abdominal superior", "problemas hepáticos", "malestar en la panza", "dolor en la guata", "hígado agrandado", "hinchazón en la barriga", "hígado delicado", "fatiga hepática", "molestia bajo las costillas", "ictericia", "transaminasas elevadas", "problemas de hígado", "dolor hepático"]'),
('K75.9', 'Enfermedad inflamatoria de hígado, no especificada', 'Sin especificar', '["hígado inflamado", "hepatitis inespecífica", "hígado irritado", "dolor en el cuadrante superior derecho", "dolor en la panza", "dolor en la guata", "dolor en la barriga", "hígado resentido", "hinchazón abdominal", "malestar en el hígado", "hígado con dolor", "problemas hepáticos", "molestia hepática", "inflamación en el vientre", "transaminasas altas"]');
