INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K63.0', 'Absceso de intestino', 'Sin especificar', '["pus en la panza", "infección intestinal profunda", "absceso abdominal", "bulto doloroso en el vientre", "flemón intestinal", "dolor abdominal intenso", "fiebre por infección de tripas", "infección en el intestino", "inflamación con pus", "absceso perirrectal", "dolor de guata con fiebre", "abdomen agudo", "tumoración dolorosa intestinal"]'),
('K63.1', 'Perforación de intestino (no traumática)', 'Sin especificar', '["intestino roto", "agujero en el intestino", "perforación intestinal", "tripas perforadas", "peritonitis", "dolor de barriga insoportable", "abdomen tabla", "dolor agudo abdominal", "emergencia intestinal", "perforación espontánea", "sepsis abdominal", "tripas rotas", "dolor de panza grave"]'),
('K63.2', 'Fístula de intestino', 'Sin especificar', '["fístula intestinal", "hueco en el intestino", "conexión anormal de tripas", "drenaje intestinal", "fístula anal", "fístula enterocutánea", "secreción por la panza", "comunicación intestinal", "fístula de guata", "úlcera con fístula", "orificio en el intestino", "herida que no cierra en el abdomen"]'),
('K63.3', 'Úlcera de intestino', 'Sin especificar', '["llaga en el intestino", "úlcera intestinal", "herida en las tripas", "dolor ardiente en la guata", "ardor en la panza", "úlcera de colon", "hemorragia intestinal", "dolor crónico de estómago", "sangrado de tripas", "úlcera digestiva", "acidez intestinal", "dolor en la guata por úlcera"]'),
('K63.4', 'Enteroptosis', 'Sin especificar', '["intestino caído", "tripas descendidas", "ptosis intestinal", "caída de las vísceras", "abdomen caído", "pesadez en la panza", "sensación de vacío en el vientre", "vientre bajo caído", "distensión abdominal", "intestino relajado", "descolgamiento visceral", "mala digestión por caída de órganos"]'),
('K63.5', 'Pólipo de colon', 'Sin especificar', '["pólipos en el colon", "bultitos en el intestino", "crecimiento en el colon", "verrugas en el intestino", "sangre en la caca", "tumor benigno intestinal", "pólipo intestinal", "crecimiento anormal en colon", "verruga en el recto", "sangrado al ir al baño", "tamizaje de colon", "excrecencia en el intestino"]'),
('K63.81', 'Lesión de Dieulafoy de intestino', 'Sin especificar', '["sangrado intestinal inexplicable", "vaso sanguíneo roto en intestino", "hemorragia digestiva alta", "sangrado de Dieulafoy", "lesión vascular intestinal", "sangrado severo de tripas", "úlcera vascular", "hemorragia por arteria dilatada", "sangrado intestinal grave", "lesión sangrante de colon", "aneurisma intestinal roto"]'),
('K63.8211', 'Sobrecrecimiento bacteriano en intestino delgado, subtipo hidrógeno', 'Sin especificar', '["SIBO hidrógeno", "hinchazón por SIBO", "gases excesivos", "barriga inflada", "panza de embarazada por gases", "fermentación intestinal", "exceso de bacterias", "sobrecrecimiento bacteriano", "gases por hidrógeno", "intestino gaseoso", "distensión abdominal extrema", "mala digestión crónica"]'),
('K63.8212', 'Sobrecrecimiento bacteriano en intestino delgado, subtipo sulfuro de hidrógeno', 'Sin especificar', '["SIBO sulfuro", "gases con olor a huevo podrido", "flatulencias fétidas", "sobrecrecimiento bacteriano sulfuro", "SIBO maloliente", "gases con azufre", "dolor abdominal por gases", "diarrea por SIBO", "hinchazón abdominal", "tripas con mal olor", "sulfuro de hidrógeno intestinal"]'),
('K63.8219', 'Sobrecrecimiento bacteriano en intestino delgado, no especificado', 'Sin especificar', '["SIBO", "sobrecrecimiento bacteriano", "bacterias en intestino delgado", "hinchazón constante", "gases persistentes", "mala absorción", "intestino irritado por bacterias", "siempre inflamado", "diarreas por SIBO", "problemas de flora intestinal", "infección bacteriana intestinal", "disbiosis intestinal"]'),
('K63.822', 'Sobrecrecimiento fúngico en intestino delgado', 'Sin especificar', '["hongos en el intestino", "cándida intestinal", "sobrecrecimiento de hongos", "micosis intestinal", "infección por hongos en tripas", "gas por hongos", "hinchazón por cándida", "disbiosis fúngica", "picazón rectal por hongos", "hinchazón de guata por levaduras", "infección micótica de colon"]'),
('K63.829', 'Sobrecrecimiento de metanógeno intestinal, no especificado', 'Sin especificar', '["IMO", "estreñimiento por metano", "metano intestinal", "estreñimiento crónico por bacterias", "gases por metano", "intestino lento", "disbiosis metanogénica", "hinchazón de vientre", "estreñimiento pertinaz", "bacterias productoras de gas", "sobrecrecimiento arqueas", "dificultad para ir al baño"]'),
('K63.89', 'Otras enfermedades especificadas de intestino', 'Sin especificar', '["problemas raros de intestino", "enfermedad intestinal rara", "dolencia intestinal sin nombre", "complicación de tripas", "afección intestinal compleja", "trastorno del colon", "problema en el intestino delgado", "dolor crónico de barriga", "enfermedad de las tripas", "malestar intestinal general"]'),
('K63.9', 'Enfermedad de intestino, no especificada', 'Sin especificar', '["problema intestinal", "dolor de tripas", "me duele la guata", "dolor de panza", "malestar en el vientre", "enfermedad de las tripas", "dolor abdominal", "no sé qué tengo en la guata", "problema en el colon", "indigestión grave", "dolor intestinal desconocido"]');
