INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L90.0', 'Liquen escleroso y atrófico', 'Sin especificar', '["manchas blancas en la piel", "piel arrugada", "picazón genital", "liquen", "manchas blanquecinas", "atrofia vulvar", "atrofia balánica", "piel fina", "picor íntimo", "manchas en la zona genital", "piel apergaminada", "adelgazamiento de la piel", "liquen escleroso", "lesiones blancas", "irritación genital"]'),
('L90.1', 'Anetodermia de Schweninger-Buzzi', 'Sin especificar', '["piel floja", "bultos blandos en la piel", "puntos de piel hundidos", "hernias cutáneas", "piel flácida", "nódulos blandos", "atrofia dérmica", "lesiones cutáneas blandas", "piel de aspecto elástico", "depresiones en la piel", "anodermia", "hundimientos cutáneos", "piel que se hunde", "manchas blandas", "puntos atróficos"]'),
('L90.2', 'Anetodermia de Jadassohn-Pellizzari', 'Sin especificar', '["bolsas en la piel", "puntos blandos", "piel que parece un saco", "atrofia localizada", "lesiones tipo hernia", "piel flácida en el cuerpo", "puntos hundidos", "anodermatitis", "piel delgada y blanda", "manchas depresibles", "tejido subcutáneo débil", "lesiones cutáneas circulares", "blandura en la piel", "atrofia focal", "puntos de laxitud"]'),
('L90.3', 'Atrofoderma de Pasini y Pierini', 'Sin especificar', '["manchas oscuras hundidas", "piel deprimida", "manchas marrones atróficas", "lesiones en la espalda", "piel como si faltara tejido", "manchas en el tronco", "atrofia en parches", "hundimientos en la piel", "lesiones pigmentadas hundidas", "adelgazamiento cutáneo focal", "manchas deprimidas", "atrofodermia", "piel hundida", "lesiones asintomáticas", "manchas que parecen huellas"]'),
('L90.4', 'Acrodermatitis crónica atrófica', 'Sin especificar', '["piel fina en las manos", "manos adelgazadas", "piel de papel", "atrofia en extremidades", "enrojecimiento y atrofia", "piel brillante y delgada", "manos y pies con piel fina", "atrofia cutánea crónica", "enfermedad de piel en manos", "piel que se transparenta", "adelgazamiento de la piel en extremidades", "piel arrugada en las extremidades", "atrofia por picadura", "lesiones atróficas en piernas", "piel sensible y fina"]'),
('L90.5', 'Afecciones cicatriciales y fibrosis de la piel', 'Sin especificar', '["cicatrices", "queloide", "piel dura", "cicatrices gruesas", "fibrosis cutánea", "marcas en la piel", "piel endurecida", "cicatrización anormal", "piel acartonada", "cicatriz queloidea", "cicatriz hipertrófica", "tejido cicatricial", "piel tiesa", "durezas en la piel", "cicatrices feas"]'),
('L90.6', 'Estrías atróficas', 'Sin especificar', '["estrías", "rayas en la panza", "estrías en el cuerpo", "piel rota", "marcas de estiramiento", "estrías blancas", "estrías rojas", "piel rajada", "estrías de embarazo", "marcas en la piel por crecimiento", "estrías en las piernas", "estrías en los pechos", "estrías en la espalda", "piel estirada", "estrías atróficas"]'),
('L90.8', 'Otros tipos de trastornos atróficos de la piel', 'Sin especificar', '["piel delgada", "piel atrófica", "desgaste de piel", "piel que se rompe fácil", "piel de papel", "fragilidad cutánea", "atrofia de la piel", "piel fina como cebolla", "adelgazamiento dérmico", "problemas de atrofia", "piel frágil", "piel que se ve rara", "manchas de atrofia", "daño en la piel", "desnutrición de la piel"]'),
('L90.9', 'Trastorno atrófico de la piel, no especificado', 'Sin especificar', '["problema en la piel", "piel dañada", "atrofia cutánea", "piel rara", "manchas y atrofia", "desconocido en la piel", "piel que cambia", "adelgazamiento inexplicable", "lesión atrófica", "cambio en la textura de la piel", "afección de la piel", "piel débil", "atrofia sin diagnóstico", "trastorno dérmico", "problemas de piel no definidos"]');
