INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J35.01', 'Amigdalitis crónica', 'Sin especificar', '["amigdalitis", "anginas", "dolor de garganta", "infección en las amígdalas", "anginas inflamadas", "garganta inflamada", "bolitas en la garganta", "fuegos en la garganta", "placas en la garganta", "amigdalitis recurrente", "amígdalas con pus", "carachas", "amigdalitis crónica", "inflamación de anginas", "dolor al tragar"]'),
('J35.02', 'Adenoiditis crónica', 'Sin especificar', '["adenoiditis", "adenoides inflamadas", "vegetaciones", "nariz tapada", "respirar por la boca", "ronquidos niños", "voz gangosa", "moco constante", "nariz congestionada", "adenoiditis persistente", "problemas de adenoides", "inflamación de vegetaciones", "nariz trancada", "respiración ruidosa", "ojeras por mala respiración"]'),
('J35.03', 'Amigdalitis y adenoiditis crónica', 'Sin especificar', '["amígdalas y adenoides inflamadas", "problemas de anginas y adenoides", "vegetaciones y amigdalitis", "inflamación crónica de garganta y nariz", "respiración bucal y dolor de garganta", "infección de anginas y vegetaciones", "ronquidos y dolor de garganta", "amigdalitis y adenoiditis", "infección recurrente garganta nariz", "amígdalas grandes y adenoides", "garganta cerrada y nariz tapada"]'),
('J35.1', 'Hipertrofia de las amígdalas', 'Sin especificar', '["amígdalas grandes", "anginas grandes", "amígdalas inflamadas", "anginas que se tocan", "amígdalas hipertróficas", "amígdalas gigantes", "problemas para tragar", "anginas que obstruyen", "amígdalas grado 3", "hipertrofia amigdalar", "amígdalas que molestan", "amígdalas obstruyendo la garganta", "anginas muy grandes"]'),
('J35.2', 'Hipertrofia de las adenoides', 'Sin especificar', '["adenoides grandes", "vegetaciones grandes", "adenoides hipertróficas", "adenoides crecidas", "cara adenoidea", "respirar mal por la nariz", "obstrucción nasal adenoides", "adenoides que tapan la nariz", "hipertrofia adenoidea", "nariz bloqueada por adenoides", "problemas para respirar por adenoides", "vegetaciones hipertróficas"]'),
('J35.3', 'Hipertrofia de las amígdalas con hipertrofia de las adenoides', 'Sin especificar', '["amígdalas y adenoides muy grandes", "amígdalas y vegetaciones crecidas", "hipertrofia amigdaloadenoidea", "anginas y adenoides gigantes", "obstrucción respiratoria alta", "amígdalas y adenoides obstruyendo", "problemas severos de anginas y adenoides", "hipertrofia de amígdalas y vegetaciones", "anginas y adenoides hipertróficas", "respiración difícil amígdalas y adenoides"]'),
('J35.8', 'Otras enfermedades crónicas de las amígdalas y de las adenoides', 'Sin especificar', '["cálculos amigdalinos", "caseum", "piedras en las amígdalas", "piedritas en la garganta", "mal aliento por amígdalas", "absceso amigdalino recurrente", "quistes en amígdalas", "patología amigdalina", "enfermedad de anginas", "problemas de garganta persistentes", "dolor recurrente de anginas", "piedras blancas garganta"]'),
('J35.9', 'Enfermedad crónica de las amígdalas y de las adenoides, no especificada', 'Sin especificar', '["problema en las anginas", "dolencia de amígdalas", "afección de adenoides", "molestia crónica garganta", "problema en garganta y nariz", "enfermedad amigdalar no especificada", "dolor constante anginas", "molestia en la garganta", "infección persistente anginas adenoides", "problemas de garganta crónicos"]');
