INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z99.0', 'Dependencia de aspirador', 'Sin especificar', '["aspirador de secreciones", "succión de flemas", "máquina de succionar", "aspirar garganta", "limpieza de vías aéreas", "equipo de aspiración", "uso de aspirador", "aspiración pulmonar", "dispositivo de succión", "aspirar mucosidad", "equipo médico de succión", "aspirador de fluidos"]'),
('Z99.11', 'Estado de dependencia de respirador [ventilador]', 'Sin especificar', '["dependiente de ventilador", "respirador artificial", "soporte ventilatorio", "paciente intubado", "traqueostomía", "ventilación mecánica", "estar conectado a una máquina", "pulmón artificial", "ayuda para respirar", "asistencia respiratoria", "equipo de ventilación", "vía aérea artificial", "ventilador de terapia intensiva"]'),
('Z99.12', 'Contacto por dependencia de respirador [ventilador] durante falta de electricidad', 'Sin especificar', '["sin luz con respirador", "falla eléctrica ventilador", "corte de energía respirador", "emergencia sin luz", "batería de respirador", "apagon y ventilación", "riesgo por falta de luz", "respirador sin corriente", "fallo de red eléctrica", "autonomía de ventilador", "crisis por corte eléctrico", "equipo médico sin luz"]'),
('Z99.2', 'Dependencia de diálisis renal', 'Sin especificar', '["paciente renal", "hacerse diálisis", "hemodiálisis", "falla de riñones", "riñones dañados", "limpiar la sangre", "diálisis peritoneal", "máquina de diálisis", "conectado a la máquina", "insuficiencia renal crónica", "tratamiento de riñones", "tengo que ir a diálisis", "depuración renal", "catéter de diálisis"]'),
('Z99.3', 'Dependencia a silla de ruedas', 'Sin especificar', '["uso silla de ruedas", "andador", "no puedo caminar", "discapacidad motriz", "movilidad reducida", "en silla", "aparato para moverse", "silla para inválidos", "problemas para caminar", "depender de una silla", "postrado en silla", "fuerza en piernas", "movimiento limitado", "carrito para personas"]'),
('Z99.81', 'Dependencia de oxígeno suplementario', 'Sin especificar', '["tanque de oxígeno", "balón de oxígeno", "concentrador de oxígeno", "máscara de oxígeno", "oxígeno en casa", "me falta el aire", "dependo del oxígeno", "apoyo respiratorio", "puntas nasales", "chico del oxígeno", "problemas pulmonares", "botellón de oxígeno", "ayuda para oxigenar", "terapia de oxígeno"]'),
('Z99.89', 'Dependencia de otras máquinas y dispositivos de apoyo', 'Sin especificar', '["aparatos médicos", "dispositivo de soporte", "maquinaria de salud", "equipo de asistencia", "ayudas técnicas", "instrumental médico", "cuidado con máquinas", "vida asistida por máquinas", "tecnología médica", "dispositivos para vivir", "soporte vital", "aparatos de ayuda"]');
