INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q04.0', 'Malformaciones congénitas del cuerpo calloso', 'Sin especificar', '["agenesia del cuerpo calloso", "falta de cuerpo calloso", "disgenesia callosa", "malformación cerebral congénita", "defecto cerebral de nacimiento", "cerebro incompleto", "hipoplasia del cuerpo calloso", "anomalía en la conexión cerebral", "problemas de desarrollo cerebral", "cuerpo calloso ausente", "malformaciones neurológicas infantiles", "desarrollo neurológico atípico", "cerebro con malformaciones", "fallas en el desarrollo del cerebro", "anomalía congénita del encéfalo"]'),
('Q04.1', 'Arrinencefalia', 'Sin especificar', '["ausencia de bulbos olfatorios", "arrinencefalia", "falta de olfato congénita", "malformación del lóbulo frontal", "defecto de desarrollo cerebral", "anomalía cerebral congénita", "desarrollo incompleto del encéfalo", "problemas del sistema olfativo central", "malformaciones del prosencéfalo", "trastorno del desarrollo encefálico", "anomalía craneal al nacer", "malformación del sistema nervioso central", "ausencia de estructuras olfativas", "defecto de formación del cerebro", "afección neurológica rara"]'),
('Q04.2', 'Holoprosencefalia', 'Sin especificar', '["holoprosencefalia", "malformación prosencefálica", "cerebro no dividido", "defectos del desarrollo del cerebro anterior", "anomalía cerebral severa", "problemas en la división del cerebro", "disfunción cerebral al nacer", "malformación congénita del encéfalo", "anomalía craneofacial congénita", "trastorno del desarrollo neurológico", "cerebro único", "fallo en la separación cerebral", "malformación congénita grave", "anomalía morfológica cerebral", "defecto de línea media"]'),
('Q04.3', 'Otras deformidades por reducción del cerebro', 'Sin especificar', '["atrofia cerebral congénita", "cerebro pequeño de nacimiento", "microencefalia", "reducción de masa cerebral", "malformación reductiva cerebral", "hipoplasia cerebral", "desarrollo cerebral disminuido", "defectos de tamaño del cerebro", "cerebro subdesarrollado", "anomalía por falta de tejido cerebral", "trastorno congénito del tamaño cerebral", "reducción de lóbulos cerebrales", "falla en el crecimiento cerebral", "malformaciones cerebrales inespecíficas", "encéfalo reducido"]'),
('Q04.4', 'Displasia del septo óptico del cerebro', 'Sin especificar', '["displasia septo-óptica", "síndrome de de Morsier", "anomalía del nervio óptico y cerebro", "hipoplasia del nervio óptico", "problemas de visión congénitos", "malformación del tabique cerebral", "defectos en el desarrollo hipotalámico", "trastorno del eje hipotálamo-hipofisario", "anomalía estructural de la línea media", "problemas hormonales congénitos", "falta de desarrollo del septo", "malformación cerebral y visual", "displasia del sistema nervioso central", "anomalía septal", "ceguera congénita cerebral"]'),
('Q04.5', 'Megalencefalia', 'Sin especificar', '["megalencefalia", "macrocéfalo", "cerebro grande", "cabeza grande al nacer", "macrocefalia congénita", "crecimiento excesivo del cerebro", "aumento de volumen cerebral", "malformación cerebral por sobrecrecimiento", "anomalía del desarrollo encefálico", "trastorno de tamaño cerebral", "hiperplasia cerebral congénita", "cabeza inusualmente grande", "problemas de desarrollo por cerebro grande", "macroencefalia", "aumento del tamaño del encéfalo"]'),
('Q04.6', 'Quistes cerebrales congénitos', 'Sin especificar', '["quiste cerebral congénito", "bolsa de líquido en el cerebro", "quiste aracnoideo", "quistes en la cabeza al nacer", "malformación quística cerebral", "quiste encefálico", "líquido en el cerebro del bebé", "anomalía quística cerebral", "quistes congénitos del sistema nervioso", "lesión quística cerebral al nacer", "quiste congénito", "cavidad quística en el encéfalo", "quistes cerebrales infantiles", "problemas con líquido cerebral", "formación quística congénita"]'),
('Q04.8', 'Otras malformaciones congénitas especificadas del cerebro', 'Sin especificar', '["otras malformaciones cerebrales", "anomalías congénitas del encéfalo", "defectos cerebrales raros", "malformación compleja del cerebro", "problemas congénitos del sistema nervioso", "trastornos del desarrollo cerebral", "anomalías de estructura cerebral", "deformidades congénitas del encéfalo", "alteraciones del desarrollo cerebral", "malformaciones neurológicas específicas", "defectos anatómicos del cerebro", "trastornos anatómicos cerebrales", "anomalía congénita cerebral especificada", "error de desarrollo del encéfalo", "problemas cerebrales de nacimiento"]'),
('Q04.9', 'Malformación congénita del cerebro, no especificada', 'Sin especificar', '["malformación cerebral inespecífica", "defecto cerebral al nacer", "problemas del cerebro congénitos", "anomalía cerebral no definida", "problemas neurológicos al nacer", "trastorno cerebral congénito", "enfermedad cerebral de nacimiento", "anomalía del desarrollo cerebral", "defecto en la formación del cerebro", "malformación congénita del encéfalo", "problema en el desarrollo cerebral", "falla neurológica congénita", "anomalía estructural cerebral", "trastorno cerebral inespecífico", "daño cerebral congénito"]');
