INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L60.0', 'Uña encarnada', 'Sin especificar', '["uña encarnada", "uña enterrada", "uña encarnada del pie", "uña enterrada en el dedo", "uña que se clava", "paroniquia", "inflamación de la uña", "uñero", "uña con pus", "uña mal cortada", "dolor en el dedo del pie", "uña enterrada carne", "uñero infectado", "uñero inflamado", "uña encarnada tratamiento", "uña encarnada dolor"]'),
('L60.1', 'Onicolisis', 'Sin especificar', '["onicolisis", "separación de la uña", "uña que se desprende", "uña levantada", "uña hueca", "uña se despega de la piel", "desprendimiento de la uña", "uña blanca al final", "uña floja", "uña que se cae", "trauma en la uña", "uña despegada", "onicolisis tratamiento", "mancha blanca bajo la uña", "despego de la placa ungueal"]'),
('L60.2', 'Onicogrifosis', 'Sin especificar', '["onicogrifosis", "uña en garra", "uña de carnero", "uña muy gruesa", "uña engrosada", "uña deforme", "uña hipertrófica", "uñas como cuernos", "engrosamiento ungueal", "uña dura", "uña difícil de cortar", "uñas de anciano", "uña retorcida", "uñas feas", "deformidad en las uñas"]'),
('L60.3', 'Distrofia ungueal', 'Sin especificar', '["distrofia ungueal", "uñas quebradizas", "uñas feas", "uñas deformadas", "uñas estriadas", "uñas que se rompen", "mala calidad de la uña", "uñas débiles", "uñas raras", "uñas descamadas", "deterioro de la uña", "uñas enfermas", "anormalidad en las uñas", "uñas que no crecen bien", "uñas con surcos"]'),
('L60.4', 'Líneas de Beau', 'Sin especificar', '["líneas de Beau", "surcos en la uña", "rayas horizontales en la uña", "uñas con canaletas", "hundimientos en la uña", "líneas transversales en las uñas", "hendiduras en las uñas", "surcos profundos en la uña", "uñas con surcos horizontales", "marcas en la uña", "uñas con depresiones", "uñas rayadas", "líneas después de enfermedad", "surcos ungueales"]'),
('L60.5', 'Síndrome de la uña amarilla', 'Sin especificar', '["síndrome de la uña amarilla", "uñas amarillas", "uñas amarillentas", "coloración amarilla en las uñas", "uñas que se vuelven amarillas", "uña sin brillo", "uñas amarillas y engrosadas", "uñas amarillentas y lentas", "decoloración de la uña", "uñas con falta de crecimiento", "uñas amarillas y enfermedades pulmonares", "uña amarilla y linfedema", "uña amarillenta persistente"]'),
('L60.8', 'Otros trastornos de las uñas', 'Sin especificar', '["problemas de uñas", "enfermedad en las uñas", "uñas enfermas", "dolor en uñas", "manchas en las uñas", "uñas con hongos", "uñas raras", "uñas que cambian de color", "uñas que sangran", "uñas con puntos blancos", "uñas que duelen", "alteraciones ungueales", "infección en las uñas", "uñas con mal olor", "uñas comidas"]'),
('L60.9', 'Trastorno de la uña, no especificado', 'Sin especificar', '["daño en la uña", "problema en la uña", "uñas raras", "algo raro en la uña", "uña con mal aspecto", "qué le pasa a mi uña", "dolor en uña", "uña que se puso negra", "mancha bajo la uña", "uñas débiles", "uña que no es normal", "alteración de la uña", "infección ungueal", "lesión en la uña"]');
