INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D12.0', 'Neoplasia benigna de ciego', 'Sin especificar', '["bolita en el ciego", "tumor benigno intestino grueso", "crecimiento ciego", "dolor abdominal bajo derecho", "inflamación en la panza", "masa abdominal", "polipo en el ciego", "dolor en la guata", "hinchazón abdominal", "molestia en el costado derecho", "problemas digestivos", "tumor que no es cáncer", "neoplasia no maligna ciego", "bulto en el abdomen"]'),
('D12.1', 'Neoplasia benigna de apéndice', 'Sin especificar', '["tumor benigno apéndice", "bolita en el apéndice", "masa en la zona del apéndice", "dolor en la fosa ilíaca derecha", "apendicitis crónica leve", "crecimiento anormal apéndice", "polipo apendicular", "molestia al lado de la panza", "dolor de guata agudo", "tumor no canceroso apéndice", "bulto cerca del apéndice", "inflamación apendicular", "neoplasia apéndice no maligna", "dolor abdominal persistente"]'),
('D12.2', 'Neoplasia benigna de colon ascendente', 'Sin especificar', '["tumor benigno colon derecho", "polipo en el colon ascendente", "bolita en el intestino", "dolor de panza lado derecho", "masa en el colon", "crecimiento en el intestino grueso", "problemas para ir al baño", "estreñimiento por tumor", "dolor abdominal crónico", "neoplasia no maligna colon ascendente", "hinchazón abdominal constante", "bulto en el abdomen superior derecho", "tumorcito en el colon", "sangrado rectal leve"]'),
('D12.3', 'Neoplasia benigna de colon transverso', 'Sin especificar', '["tumor benigno intestino medio", "masa en el abdomen superior", "polipo en colon transverso", "dolor en la boca del estómago", "molestia abdominal central", "hinchazón después de comer", "problemas digestivos frecuentes", "bolita en la guata", "crecimiento benigno intestino", "dolor tipo cólico", "neoplasia no cancerosa colon", "bulto en la parte media de la panza", "sensación de pesadez abdominal", "estreñimiento intermitente"]'),
('D12.4', 'Neoplasia benigna de colon descendente', 'Sin especificar', '["tumor benigno colon izquierdo", "polipo en el colon descendente", "dolor abdominal lado izquierdo", "molestia en la panza baja", "masa en el lado izquierdo", "estreñimiento crónico", "problemas de evacuación", "bolita en el intestino", "dolor al ir al baño", "neoplasia no maligna intestino", "hinchazón lateral izquierda", "bulto en el costado izquierdo", "sangrado al defecar", "obstrucción intestinal leve"]'),
('D12.5', 'Neoplasia benigna de colon sigmoide', 'Sin especificar', '["tumor en el sigmoide", "polipo sigmoideo", "bolita en el intestino bajo", "dolor de panza lado izquierdo bajo", "masa pélvica benigna", "dolor al defecar", "estreñimiento fuerte", "neoplasia benigna sigmoides", "dolor tipo cólico bajo", "bulto en el bajo vientre", "sangre en las heces", "molestia en la zona rectal", "tumor no canceroso sigmoides", "hinchazón del abdomen inferior"]'),
('D12.6', 'Neoplasia benigna de colon, no especificada', 'Sin especificar', '["tumor en el intestino grueso", "polipos en el colon", "bolitas en el colon", "dolor abdominal inespecífico", "problemas digestivos crónicos", "neoplasia intestinal no maligna", "crecimiento anormal en el colon", "masa abdominal", "hinchazón constante", "cambios en el ritmo intestinal", "dolor de barriga", "molestia en la guata", "tumor no canceroso intestino", "bulto intestinal"]'),
('D12.7', 'Neoplasia benigna de unión rectosigmoidea', 'Sin especificar', '["tumor en la unión recto-colon", "bolita entre el recto y colon", "masa en la parte baja", "dolor rectal bajo", "molestia al evacuar", "sangrado anal leve", "sensación de cuerpo extraño en el recto", "polipo recto-sigmoide", "neoplasia benigna unión rectosigmoidea", "dolor tipo puntada rectal", "dificultad para defecar", "inflamación pélvica", "tumor no maligno zona rectal", "bulto en la zona del ano"]'),
('D12.8', 'Neoplasia benigna de recto', 'Sin especificar', '["tumor en el recto", "polipo rectal", "bolita en el recto", "dolor en el ano", "sangrado anal", "molestia al sentarse", "sensación de no haber vaciado el recto", "tenesmo rectal", "neoplasia no maligna del recto", "bulto cerca del ano", "tumor no canceroso anal", "dolor punzante en el recto", "hinchazón anal", "picazón o molestia rectal"]'),
('D12.9', 'Neoplasia benigna de ano y canal anal', 'Sin especificar', '["tumor en el ano", "verruga anal gigante", "bolita en el borde del ano", "masa en el canal anal", "polipo anal", "dolor anal persistente", "sangre en el papel higiénico", "molestia al ir al baño", "neoplasia benigna del ano", "bulto en el orificio anal", "picazón anal intensa", "tumor no maligno canal anal", "dolor al defecar", "inflamación en la zona del ano"]');
