INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D35.00', 'Neoplasia benigna de glándula suprarrenal no especificada', 'Sin especificar', '["tumor adrenal", "bolita en la suprarrenal", "masa benigna adrenal", "adenoma suprarrenal", "problema en las adrenales", "crecimiento en glándula suprarrenal", "hiperplasia suprarrenal benigna", "nódulo adrenal", "tumor no canceroso suprarrenal", "dolor lumbar adrenal", "afección glándulas arriba del riñón", "adenoma de corteza suprarrenal", "neoplasia endocrina", "quiste suprarrenal"]'),
('D35.01', 'Neoplasia benigna de glándula suprarrenal derecha', 'Sin especificar', '["tumor adrenal derecho", "adenoma suprarrenal derecho", "masa en la suprarrenal derecha", "bolita lado derecho arriba del riñón", "nódulo suprarrenal derecho", "neoplasia benigna adrenal derecha", "crecimiento benigno glándula derecha", "adenoma cortical derecho", "dolor costado derecho superior", "afección endocrina derecha", "tumor benigno adrenal derecha"]'),
('D35.02', 'Neoplasia benigna de glándula suprarrenal izquierda', 'Sin especificar', '["tumor adrenal izquierdo", "adenoma suprarrenal izquierdo", "masa en la suprarrenal izquierda", "bolita lado izquierdo arriba del riñón", "nódulo suprarrenal izquierdo", "neoplasia benigna adrenal izquierda", "crecimiento benigno glándula izquierda", "adenoma cortical izquierdo", "dolor costado izquierdo superior", "afección endocrina izquierda", "tumor benigno adrenal izquierda"]'),
('D35.1', 'Neoplasia benigna de glándula paratiroides', 'Sin especificar', '["tumor paratiroideo", "adenoma paratiroideo", "bolita en el cuello", "problema de calcio y paratiroides", "hiperparatiroidismo benigno", "masa en glándula paratiroides", "tumor cuello calcio", "nódulo paratiroideo", "adenoma de paratiroides", "quiste paratiroideo", "crecimiento benigno cuello", "trastorno glandular cuello"]'),
('D35.2', 'Neoplasia benigna de hipófisis', 'Sin especificar', '["adenoma hipofisario", "tumor en la hipófisis", "tumor en la glándula pituitaria", "bolita en la cabeza hipófisis", "microadenoma hipofisario", "macroadenoma pituitario", "problemas de hormonas cerebro", "crecimiento benigno base del cráneo", "masa hipofisaria", "tumor endocrino cerebral", "nódulo pituitario", "adenoma productor de hormonas"]'),
('D35.3', 'Neoplasia benigna de conducto craneofaríngeo', 'Sin especificar', '["craneofaringioma benigno", "tumor en el conducto craneofaríngeo", "masa base del cráneo", "tumor hipofisario tipo craneofaringioma", "crecimiento benigno cerca de la hipófisis", "quiste craneofaríngeo", "tumor quístico cerebral", "problemas de visión y cabeza", "neoplasia conducto craneal", "tumor benigno infantil base cráneo", "lesión craneofaríngea"]'),
('D35.4', 'Neoplasia benigna de glándula pineal', 'Sin especificar', '["tumor glándula pineal", "pineocitoma benigno", "masa en el centro del cerebro", "bolita en la pineal", "tumor cerebral pineal", "crecimiento pineal benigno", "quiste de la glándula pineal", "problemas de melatonina", "nódulo en la pineal", "tumor pineal no canceroso", "afección glándula pineal", "lesión benigna pineal"]'),
('D35.5', 'Neoplasia benigna de cuerpo carotídeo', 'Sin especificar', '["tumor cuerpo carotídeo", "paraganglioma carotídeo", "bolita en el cuello arteria", "masa carótida", "tumor benigno arteria cuello", "quemodectoma", "crecimiento en bifurcación carótida", "tumor vascular cuello", "nódulo carotídeo", "masa pulsátil cuello", "tumor benigno cuello", "neoplasia para-ganglionar"]'),
('D35.6', 'Neoplasia benigna de cuerpo aórtico y otros paraganglios', 'Sin especificar', '["paraganglioma aórtico", "tumor de cuerpo aórtico", "tumor glómico", "masa en la aorta", "tumor para-ganglionar", "crecimiento benigno paraganglios", "nódulo aórtico", "tumor benigno sistema nervioso simpático", "feocromocitoma extra-adrenal benigno", "masa vascular torácica", "neoplasia benigna paraganglionar"]'),
('D35.7', 'Neoplasia benigna de otras glándulas endocrinas especificadas', 'Sin especificar', '["tumor glándula endocrina", "masa endocrina benigna", "crecimiento benigno sistema hormonal", "adenoma endocrino", "nódulo endocrino", "tumor en glándula específica", "neoplasia glándula no identificada", "problemas hormonales tumor", "quiste glandular", "lesión benigna endocrina", "tumor glándula rara"]'),
('D35.9', 'Neoplasia benigna de glándula endocrina, no especificada', 'Sin especificar', '["tumor endocrino benigno", "masa en glándula", "crecimiento benigno hormonal", "bolita glandular", "problemas en glándulas", "tumor benigno no especificado", "nódulo en glándula", "neoplasia endocrina desconocida", "adenoma general", "tumor del sistema endocrino", "quiste glandular benigno", "afección de glándulas"]');
