INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A20.0', 'Peste bubónica', 'Sin especificar', '["peste negra", "bubones", "ganglios inflamados", "bultos en la ingle", "inflamación de ganglios", "peste de las ratas", "muerte negra", "chichones en el cuello", "dolor en las axilas", "infección por picadura de pulga", "pestilencia", "bubón axilar", "ganglios duros", "fiebre y bubones", "infección bacteriana grave"]'),
('A20.1', 'Peste celulocutánea', 'Sin especificar', '["peste cutánea", "llagas en la piel", "necrosis cutánea", "peste en la piel", "manchas negras en la piel", "úlceras pestosas", "infección de la piel por peste", "piel gangrenada", "lesiones cutáneas por bacteria", "peste de la dermis", "pústulas negras", "heridas que no cierran", "infección dérmica", "bacterias en la piel", "síntomas cutáneos de peste"]'),
('A20.2', 'Peste neumónica', 'Sin especificar', '["peste pulmonar", "peste respiratoria", "tos con sangre", "dificultad para respirar", "neumonía pestosa", "tos y peste", "infección pulmonar grave", "peste contagiosa por aire", "flema con sangre", "dolor de pecho por peste", "ahogo", "falta de aire", "peste de los pulmones", "síntomas respiratorios peste", "tos violenta"]'),
('A20.3', 'Meningitis por peste', 'Sin especificar', '["meningitis pestosa", "inflamación de las meninges por peste", "dolor de cabeza extremo por peste", "rigidez de nuca", "fiebre y confusión", "peste en el cerebro", "infección cerebral por peste", "fotofobia por peste", "dolor de nuca intenso", "meningitis infecciosa", "peste del sistema nervioso", "fiebre alta y rigidez", "cefalalgia intensa", "delirio por peste", "complicación cerebral de peste"]'),
('A20.7', 'Peste septicémica', 'Sin especificar', '["sepsis por peste", "infección generalizada", "peste en la sangre", "sangre envenenada", "choque séptico por peste", "gangrena en dedos", "necrosis de extremidades", "dedos negros", "fiebre hemorrágica", "sangrado bajo la piel", "falla multiorgánica", "septicemia bacteriana", "manchas moradas en el cuerpo", "peste sistémica", "bacteriemia grave"]'),
('A20.8', 'Otras formas de peste', 'Sin especificar', '["formas raras de peste", "peste atípica", "complicaciones de la peste", "peste inusual", "variantes de la yersinia pestis", "otros tipos de peste", "peste extragenital", "cuadros clínicos de peste", "manifestaciones pestosas", "peste poco común", "casos atípicos de peste", "peste no clasificada", "cuadro sistémico de peste", "infección por yersinia", "peste compleja"]'),
('A20.9', 'Peste, no especificada', 'Sin especificar', '["peste", "enfermedad de la peste", "la peste", "infección por pulgas", "bacteria de la peste", "fiebre pestilente", "epidemia antigua", "muerte negra", "yersiniosis", "peste bubónica general", "enfermedad infecciosa grave", "peste sin especificar", "sospecha de peste", "peste bacteriana", "mal de los roedores"]');
