INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J38.00', 'Parálisis de las cuerdas vocales y de la laringe, no especificada', 'Sin especificar', '["voz ronca", "disfonía", "quedarse sin voz", "afonía", "garganta trabada", "voz soplada", "problemas para hablar", "parálisis laríngea", "voz apagada", "no me sale la voz", "cuerdas vocales paralizadas", "ronquera constante", "voz forzada", "disfonía funcional"]'),
('J38.01', 'Parálisis de las cuerdas vocales y de la laringe, unilateral', 'Sin especificar', '["parálisis de una cuerda vocal", "voz entrecortada", "voz quebrada", "ronquera de un lado", "voz de soplido", "cuerda vocal inmóvil", "problemas de voz unilateral", "disfonía persistente", "voz débil", "fatiga al hablar", "cuerda vocal bloqueada", "aire al hablar", "parálisis laringe un lado"]'),
('J38.02', 'Parálisis de las cuerdas vocales y de la laringe, bilateral', 'Sin especificar', '["parálisis de ambas cuerdas vocales", "dificultad para respirar", "voz apenas audible", "asfixia leve", "estridor", "ruido al respirar", "falta de aire al hablar", "cuerdas vocales pegadas", "cierre de la laringe", "emergencia de voz", "voz susurrada permanentemente", "inmovilidad laríngea bilateral", "ahogo al hablar"]'),
('J38.1', 'Pólipos de las cuerdas vocales y de la laringe', 'Sin especificar', '["polipos en la garganta", "bulto en la cuerda vocal", "bolita en la garganta", "voz ronca por polipos", "carnosidad en la laringe", "voz rasposa", "molestia al tragar", "cuerpo extraño en la garganta", "polipos laringeos", "voz grave súbita", "crescimiento en las cuerdas", "voz soplada crónica"]'),
('J38.2', 'Nódulos de las cuerdas vocales', 'Sin especificar', '["nódulos en la garganta", "callos en las cuerdas vocales", "voz de cantante dañada", "nódulos del gritón", "voz ronca por hablar mucho", "bolitas en las cuerdas", "esfuerzo vocal", "garganta cansada", "disfonía del profesor", "nódulos laríngeos", "voz con carraspera", "inflamación de cuerdas vocales"]'),
('J38.3', 'Otras enfermedades de las cuerdas vocales', 'Sin especificar', '["quistes en cuerdas vocales", "úlceras de contacto", "leucoplasia laringea", "garganta irritada", "carraspera crónica", "voz que se corta", "problemas de voz", "daño en cuerdas vocales", "enfermedad de la laringe", "voz áspera", "dolor al usar la voz", "fatiga vocal"]'),
('J38.4', 'Edema de la laringe', 'Sin especificar', '["hinchazón de garganta", "laringe inflamada", "garganta cerrada", "edema laríngeo", "inflamación de la laringe", "dificultad para tragar", "sensación de cuello apretado", "inflamación de glotis", "garganta roja", "ahogo", "sensación de cuerpo extraño", "obstrucción de garganta"]'),
('J38.5', 'Espasmo de la laringe', 'Sin especificar', '["laringoespasmo", "garganta cerrada de golpe", "nudo en la garganta", "ataque de ahogo", "cierre de la laringe", "sensación de asfixia", "garganta que se traba", "espasmo en el cuello", "falta de aire súbita", "tos de perro", "garganta contraída", "chillido al respirar"]'),
('J38.6', 'Estenosis de la laringe', 'Sin especificar', '["estrechamiento de la garganta", "laringe estrecha", "dificultad respiratoria", "aire que no pasa", "estenosis laríngea", "cicatriz en la garganta", "garganta reducida", "respiración ruidosa", "estridor constante", "dificultad para respirar al hacer ejercicio", "obstrucción de la vía aérea", "falta de aire"]'),
('J38.7', 'Otras enfermedades de la laringe', 'Sin especificar', '["problemas de garganta", "molestias en la laringe", "enfermedad laríngea", "garganta afectada", "patología de la laringe", "dolor en la nuez", "inflamación laríngea", "infección en la garganta", "molestia al pasar saliva", "sensación de quemazón en la garganta", "afectación de cuerdas"]');
