INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('O36.0110', 'Atención materna por los anticuerpos anti-D [RH], primer trimestre, no aplicable o no especificado', 'Sin especificar', '["incompatibilidad RH", "madre RH negativo", "anticuerpos anti D", "isoinmunización", "sangre RH", "embarazo RH negativo", "riesgo inmunológico feto", "sensibilización RH", "vacuna anti D", "anemia fetal", "control prenatal RH", "factor sanguíneo", "anticuerpos en embarazo"]'),
('O36.0111', 'Atención materna por los anticuerpos anti-D [RH], primer trimestre, feto 1', 'Sin especificar', '["incompatibilidad RH feto 1", "control embarazo anti D", "primer trimestre RH", "riesgo isoinmunización feto único", "seguimiento feto 1"]'),
('O36.0112', 'Atención materna por los anticuerpos anti-D [RH], primer trimestre, feto 2', 'Sin especificar', '["embarazo gemelar RH", "incompatibilidad RH feto 2", "control anticuerpos feto 2", "seguimiento isoinmunización feto 2"]'),
('O36.0113', 'Atención materna por los anticuerpos anti-D [RH], primer trimestre, feto 3', 'Sin especificar', '["embarazo triple RH", "incompatibilidad RH feto 3", "control embarazo múltiple RH"]'),
('O36.0114', 'Atención materna por los anticuerpos anti-D [RH], primer trimestre, feto 4', 'Sin especificar', '["embarazo múltiple RH", "feto 4 incompatibilidad RH"]'),
('O36.0115', 'Atención materna por los anticuerpos anti-D [RH], primer trimestre, feto 5', 'Sin especificar', '["gestación múltiple RH", "feto 5 incompatibilidad RH"]'),
('O36.0119', 'Atención materna por los anticuerpos anti-D [RH], primer trimestre, otro feto', 'Sin especificar', '["embarazo múltiple RH", "feto adicional RH"]'),
('O36.0120', 'Atención materna por los anticuerpos anti-D [RH], segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["incompatibilidad RH segundo trimestre", "anticuerpos anti D control", "riesgo fetal RH", "isoinmunización semanas 14-26"]'),
('O36.0121', 'Atención materna por los anticuerpos anti-D [RH], segundo trimestre, feto 1', 'Sin especificar', '["control feto único RH segundo trimestre", "riesgo isoinmunización feto 1"]'),
('O36.0122', 'Atención materna por los anticuerpos anti-D [RH], segundo trimestre, feto 2', 'Sin especificar', '["control feto 2 RH segundo trimestre", "gemelar RH segundo trimestre"]'),
('O36.0123', 'Atención materna por los anticuerpos anti-D [RH], segundo trimestre, feto 3', 'Sin especificar', '["trillizos RH segundo trimestre", "feto 3 RH"]'),
('O36.0124', 'Atención materna por los anticuerpos anti-D [RH], segundo trimestre, feto 4', 'Sin especificar', '["embarazo múltiple RH feto 4"]'),
('O36.0125', 'Atención materna por los anticuerpos anti-D [RH], segundo trimestre, feto 5', 'Sin especificar', '["embarazo múltiple RH feto 5"]'),
('O36.0129', 'Atención materna por los anticuerpos anti-D [RH], segundo trimestre, otro feto', 'Sin especificar', '["otro feto RH segundo trimestre"]'),
('O36.0130', 'Atención materna por los anticuerpos anti-D [RH], tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["incompatibilidad RH tercer trimestre", "riesgo final embarazo RH", "monitoreo anticuerpos antes del parto"]'),
('O36.0131', 'Atención materna por los anticuerpos anti-D [RH], tercer trimestre, feto 1', 'Sin especificar', '["control feto 1 tercer trimestre RH"]'),
('O36.0132', 'Atención materna por los anticuerpos anti-D [RH], tercer trimestre, feto 2', 'Sin especificar', '["control feto 2 tercer trimestre RH"]'),
('O36.0133', 'Atención materna por los anticuerpos anti-D [RH], tercer trimestre, feto 3', 'Sin especificar', '["control feto 3 tercer trimestre RH"]'),
('O36.0134', 'Atención materna por los anticuerpos anti-D [RH], tercer trimestre, feto 4', 'Sin especificar', '["control feto 4 tercer trimestre RH"]'),
('O36.0135', 'Atención materna por los anticuerpos anti-D [RH], tercer trimestre, feto 5', 'Sin especificar', '["control feto 5 tercer trimestre RH"]'),
('O36.0139', 'Atención materna por los anticuerpos anti-D [RH], tercer trimestre, otro feto', 'Sin especificar', '["control otro feto tercer trimestre RH"]'),
('O36.0190', 'Atención materna por los anticuerpos anti-D [RH], trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["control RH embarazo general", "anticuerpos anti D seguimiento"]'),
('O36.0191', 'Atención materna por los anticuerpos anti-D [RH], trimestre no especificado, feto 1', 'Sin especificar', '["seguimiento feto 1 RH"]'),
('O36.0192', 'Atención materna por los anticuerpos anti-D [RH], trimestre no especificado, feto 2', 'Sin especificar', '["seguimiento feto 2 RH"]'),
('O36.0193', 'Atención materna por los anticuerpos anti-D [RH], trimestre no especificado, feto 3', 'Sin especificar', '["seguimiento feto 3 RH"]'),
('O36.0194', 'Atención materna por los anticuerpos anti-D [RH], trimestre no especificado, feto 4', 'Sin especificar', '["seguimiento feto 4 RH"]'),
('O36.0195', 'Atención materna por los anticuerpos anti-D [RH], trimestre no especificado, feto 5', 'Sin especificar', '["seguimiento feto 5 RH"]'),
('O36.0199', 'Atención materna por los anticuerpos anti-D [RH], trimestre no especificado, otro feto', 'Sin especificar', '["seguimiento feto adicional RH"]'),
('O36.0910', 'Atención materna por otra isoinmunización Rhesus, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["isoinmunización rhesus", "problemas factor RH", "aloinmunización materna", "anticuerpos grupo sanguíneo", "anemia hemolítica neonatal", "riesgo RH primer trimestre"]'),
('O36.0911', 'Atención materna por otra isoinmunización Rhesus, primer trimestre, feto 1', 'Sin especificar', '["isoinmunización feto 1"]'),
('O36.0912', 'Atención materna por otra isoinmunización Rhesus, primer trimestre, feto 2', 'Sin especificar', '["isoinmunización feto 2"]'),
('O36.0913', 'Atención materna por otra isoinmunización Rhesus, primer trimestre, feto 3', 'Sin especificar', '["isoinmunización feto 3"]'),
('O36.0914', 'Atención materna por otra isoinmunización Rhesus, primer trimestre, feto 4', 'Sin especificar', '["isoinmunización feto 4"]'),
('O36.0915', 'Atención materna por otra isoinmunización Rhesus, primer trimestre, feto 5', 'Sin especificar', '["isoinmunización feto 5"]'),
('O36.0919', 'Atención materna por otra isoinmunización Rhesus, primer trimestre, otro feto', 'Sin especificar', '["isoinmunización otro feto"]'),
('O36.0920', 'Atención materna por otra isoinmunización Rhesus, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["control isoinmunización Rhesus", "seguimiento rhesus 2do trimestre"]'),
('O36.0921', 'Atención materna por otra isoinmunización Rhesus, segundo trimestre, feto 1', 'Sin especificar', '["control isoinmunización feto 1"]'),
('O36.0922', 'Atención materna por otra isoinmunización Rhesus, segundo trimestre, feto 2', 'Sin especificar', '["control isoinmunización feto 2"]'),
('O36.0923', 'Atención materna por otra isoinmunización Rhesus, segundo trimestre, feto 3', 'Sin especificar', '["control isoinmunización feto 3"]'),
('O36.0924', 'Atención materna por otra isoinmunización Rhesus, segundo trimestre, feto 4', 'Sin especificar', '["control isoinmunización feto 4"]'),
('O36.0925', 'Atención materna por otra isoinmunización Rhesus, segundo trimestre, feto 5', 'Sin especificar', '["control isoinmunización feto 5"]'),
('O36.0929', 'Atención materna por otra isoinmunización Rhesus, segundo trimestre, otro feto', 'Sin especificar', '["control isoinmunización otro feto"]'),
('O36.0930', 'Atención materna por otra isoinmunización Rhesus, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["monitoreo isoinmunización Rhesus", "riesgo rhesus final embarazo"]'),
('O36.0931', 'Atención materna por otra isoinmunización Rhesus, tercer trimestre, feto 1', 'Sin especificar', '["seguimiento feto 1 Rhesus"]'),
('O36.0932', 'Atención materna por otra isoinmunización Rhesus, tercer trimestre, feto 2', 'Sin especificar', '["seguimiento feto 2 Rhesus"]'),
('O36.0933', 'Atención materna por otra isoinmunización Rhesus, tercer trimestre, feto 3', 'Sin especificar', '["seguimiento feto 3 Rhesus"]'),
('O36.0934', 'Atención materna por otra isoinmunización Rhesus, tercer trimestre, feto 4', 'Sin especificar', '["seguimiento feto 4 Rhesus"]'),
('O36.0935', 'Atención materna por otra isoinmunización Rhesus, tercer trimestre, feto 5', 'Sin especificar', '["seguimiento feto 5 Rhesus"]'),
('O36.0939', 'Atención materna por otra isoinmunización Rhesus, tercer trimestre, otro feto', 'Sin especificar', '["seguimiento otro feto Rhesus"]'),
('O36.0990', 'Atención materna por otra isoinmunización Rhesus, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["isoinmunización rhesus general"]'),
('O36.0991', 'Atención materna por otra isoinmunización Rhesus, trimestre no especificado, feto 1', 'Sin especificar', '["isoinmunización Rhesus feto 1"]'),
('O36.0992', 'Atención materna por otra isoinmunización Rhesus, trimestre no especificado, feto 2', 'Sin especificar', '["isoinmunización Rhesus feto 2"]'),
('O36.0993', 'Atención materna por otra isoinmunización Rhesus, trimestre no especificado, feto 3', 'Sin especificar', '["isoinmunización Rhesus feto 3"]'),
('O36.0994', 'Atención materna por otra isoinmunización Rhesus, trimestre no especificado, feto 4', 'Sin especificar', '["isoinmunización Rhesus feto 4"]'),
('O36.0995', 'Atención materna por otra isoinmunización Rhesus, trimestre no especificado, feto 5', 'Sin especificar', '["isoinmunización Rhesus feto 5"]'),
('O36.0999', 'Atención materna por otra isoinmunización Rhesus, trimestre no especificado, otro feto', 'Sin especificar', '["isoinmunización Rhesus otro feto"]'),
('O36.1110', 'Atención materna por sensibilización anti-A, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["incompatibilidad grupo sanguíneo", "sensibilización anti A", "incompatibilidad ABO", "riesgo feto grupo sanguíneo", "hemólisis neonatal", "anticuerpos grupo A", "embarazo incompatible", "anemia en el bebé"]'),
('O36.1111', 'Atención materna por sensibilización anti-A, primer trimestre, feto 1', 'Sin especificar', '["sensibilización anti A feto 1"]'),
('O36.1112', 'Atención materna por sensibilización anti-A, primer trimestre, feto 2', 'Sin especificar', '["sensibilización anti A feto 2"]'),
('O36.1113', 'Atención materna por sensibilización anti-A, primer trimestre, feto 3', 'Sin especificar', '["sensibilización anti A feto 3"]'),
('O36.1114', 'Atención materna por sensibilización anti-A, primer trimestre, feto 4', 'Sin especificar', '["sensibilización anti A feto 4"]'),
('O36.1115', 'Atención materna por sensibilización anti-A, primer trimestre, feto 5', 'Sin especificar', '["sensibilización anti A feto 5"]'),
('O36.1119', 'Atención materna por sensibilización anti-A, primer trimestre, otro feto', 'Sin especificar', '["sensibilización anti A otro feto"]'),
('O36.1120', 'Atención materna por sensibilización anti-A, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["control sensibilización anti A", "incompatibilidad grupo 2do trimestre"]'),
('O36.1121', 'Atención materna por sensibilización anti-A, segundo trimestre, feto 1', 'Sin especificar', '["control anti A feto 1"]'),
('O36.1122', 'Atención materna por sensibilización anti-A, segundo trimestre, feto 2', 'Sin especificar', '["control anti A feto 2"]'),
('O36.1123', 'Atención materna por sensibilización anti-A, segundo trimestre, feto 3', 'Sin especificar', '["control anti A feto 3"]'),
('O36.1124', 'Atención materna por sensibilización anti-A, segundo trimestre, feto 4', 'Sin especificar', '["control anti A feto 4"]'),
('O36.1125', 'Atención materna por sensibilización anti-A, segundo trimestre, feto 5', 'Sin especificar', '["control anti A feto 5"]'),
('O36.1129', 'Atención materna por sensibilización anti-A, segundo trimestre, otro feto', 'Sin especificar', '["control anti A otro feto"]'),
('O36.1130', 'Atención materna por sensibilización anti-A, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["incompatibilidad ABO tercer trimestre", "alerta anti A"]'),
('O36.1131', 'Atención materna por sensibilización anti-A, tercer trimestre, feto 1', 'Sin especificar', '["monitoreo anti A feto 1"]'),
('O36.1132', 'Atención materna por sensibilización anti-A, tercer trimestre, feto 2', 'Sin especificar', '["monitoreo anti A feto 2"]'),
('O36.1133', 'Atención materna por sensibilización anti-A, tercer trimestre, feto 3', 'Sin especificar', '["monitoreo anti A feto 3"]'),
('O36.1134', 'Atención materna por sensibilización anti-A, tercer trimestre, feto 4', 'Sin especificar', '["monitoreo anti A feto 4"]'),
('O36.1135', 'Atención materna por sensibilización anti-A, tercer trimestre, feto 5', 'Sin especificar', '["monitoreo anti A feto 5"]'),
('O36.1139', 'Atención materna por sensibilización anti-A, tercer trimestre, otro feto', 'Sin especificar', '["monitoreo anti A otro feto"]'),
('O36.1190', 'Atención materna por sensibilización anti-A, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["problema grupo sanguíneo A", "sensibilización ABO"]'),
('O36.1191', 'Atención materna por sensibilización anti-A, trimestre no especificado, feto 1', 'Sin especificar', '["seguimiento sensibilización anti A feto 1"]'),
('O36.1192', 'Atención materna por sensibilización anti-A, trimestre no especificado, feto 2', 'Sin especificar', '["seguimiento sensibilización anti A feto 2"]'),
('O36.1193', 'Atención materna por sensibilización anti-A, trimestre no especificado, feto 3', 'Sin especificar', '["seguimiento sensibilización anti A feto 3"]'),
('O36.1194', 'Atención materna por sensibilización anti-A, trimestre no especificado, feto 4', 'Sin especificar', '["seguimiento sensibilización anti A feto 4"]'),
('O36.1195', 'Atención materna por sensibilización anti-A, trimestre no especificado, feto 5', 'Sin especificar', '["seguimiento sensibilización anti A feto 5"]'),
('O36.1199', 'Atención materna por sensibilización anti-A, trimestre no especificado, otro feto', 'Sin especificar', '["seguimiento sensibilización anti A otro feto"]'),
('O36.1910', 'Atención materna por otra isoinmunización, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["isoinmunización otros anticuerpos", "riesgo inmunológico feto", "aloinmunización", "incompatibilidad grupos sanguíneos menores", "anemia fetal por anticuerpos", "control inmunológico", "embarazo de riesgo por sangre", "anticuerpos irregulares"]'),
('O36.1911', 'Atención materna por otra isoinmunización, primer trimestre, feto 1', 'Sin especificar', '["otros anticuerpos feto 1"]'),
('O36.1912', 'Atención materna por otra isoinmunización, primer trimestre, feto 2', 'Sin especificar', '["otros anticuerpos feto 2"]'),
('O36.1913', 'Atención materna por otra isoinmunización, primer trimestre, feto 3', 'Sin especificar', '["otros anticuerpos feto 3"]'),
('O36.1914', 'Atención materna por otra isoinmunización, primer trimestre, feto 4', 'Sin especificar', '["otros anticuerpos feto 4"]'),
('O36.1915', 'Atención materna por otra isoinmunización, primer trimestre, feto 5', 'Sin especificar', '["otros anticuerpos feto 5"]'),
('O36.1919', 'Atención materna por otra isoinmunización, primer trimestre, otro feto', 'Sin especificar', '["otros anticuerpos otro feto"]'),
('O36.1920', 'Atención materna por otra isoinmunización, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["monitoreo isoinmunización 2do trimestre"]'),
('O36.1921', 'Atención materna por otra isoinmunización, segundo trimestre, feto 1', 'Sin especificar', '["seguimiento feto 1 isoinmunización"]'),
('O36.1922', 'Atención materna por otra isoinmunización, segundo trimestre, feto 2', 'Sin especificar', '["seguimiento feto 2 isoinmunización"]'),
('O36.1923', 'Atención materna por otra isoinmunización, segundo trimestre, feto 3', 'Sin especificar', '["seguimiento feto 3 isoinmunización"]'),
('O36.1924', 'Atención materna por otra isoinmunización, segundo trimestre, feto 4', 'Sin especificar', '["seguimiento feto 4 isoinmunización"]'),
('O36.1925', 'Atención materna por otra isoinmunización, segundo trimestre, feto 5', 'Sin especificar', '["seguimiento feto 5 isoinmunización"]'),
('O36.1929', 'Atención materna por otra isoinmunización, segundo trimestre, otro feto', 'Sin especificar', '["seguimiento otro feto isoinmunización"]'),
('O36.1930', 'Atención materna por otra isoinmunización, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["monitoreo isoinmunización 3er trimestre"]'),
('O36.1931', 'Atención materna por otra isoinmunización, tercer trimestre, feto 1', 'Sin especificar', '["seguimiento tercer trimestre feto 1"]'),
('O36.1932', 'Atención materna por otra isoinmunización, tercer trimestre, feto 2', 'Sin especificar', '["seguimiento tercer trimestre feto 2"]'),
('O36.1933', 'Atención materna por otra isoinmunización, tercer trimestre, feto 3', 'Sin especificar', '["seguimiento tercer trimestre feto 3"]'),
('O36.1934', 'Atención materna por otra isoinmunización, tercer trimestre, feto 4', 'Sin especificar', '["seguimiento tercer trimestre feto 4"]'),
('O36.1935', 'Atención materna por otra isoinmunización, tercer trimestre, feto 5', 'Sin especificar', '["seguimiento tercer trimestre feto 5"]'),
('O36.1939', 'Atención materna por otra isoinmunización, tercer trimestre, otro feto', 'Sin especificar', '["seguimiento tercer trimestre otro feto"]'),
('O36.1990', 'Atención materna por otra isoinmunización, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["isoinmunización general"]'),
('O36.1991', 'Atención materna por otra isoinmunización, trimestre no especificado, feto 1', 'Sin especificar', '["seguimiento general feto 1"]'),
('O36.1992', 'Atención materna por otra isoinmunización, trimestre no especificado, feto 2', 'Sin especificar', '["seguimiento general feto 2"]'),
('O36.1993', 'Atención materna por otra isoinmunización, trimestre no especificado, feto 3', 'Sin especificar', '["seguimiento general feto 3"]'),
('O36.1994', 'Atención materna por otra isoinmunización, trimestre no especificado, feto 4', 'Sin especificar', '["seguimiento general feto 4"]'),
('O36.1995', 'Atención materna por otra isoinmunización, trimestre no especificado, feto 5', 'Sin especificar', '["seguimiento general feto 5"]'),
('O36.1999', 'Atención materna por otra isoinmunización, trimestre no especificado, otro feto', 'Sin especificar', '["seguimiento general otro feto"]'),
('O36.20X0', 'Atención materna por hidropesía fetal, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["hidropesía fetal", "bebé hinchado en el útero", "edema fetal", "líquido en el cuerpo del bebé", "hidrops fetal", "feto con líquido", "anemia grave del bebé", "insuficiencia cardíaca fetal", "hinchazón abdominal del feto", "hidropesía"]'),
('O36.20X1', 'Atención materna por hidropesía fetal, trimestre no especificado, feto 1', 'Sin especificar', '["hidropesía feto 1"]'),
('O36.20X2', 'Atención materna por hidropesía fetal, trimestre no especificado, feto 2', 'Sin especificar', '["hidropesía feto 2"]'),
('O36.20X3', 'Atención materna por hidropesía fetal, trimestre no especificado, feto 3', 'Sin especificar', '["hidropesía feto 3"]'),
('O36.20X4', 'Atención materna por hidropesía fetal, trimestre no especificado, feto 4', 'Sin especificar', '["hidropesía feto 4"]'),
('O36.20X5', 'Atención materna por hidropesía fetal, trimestre no especificado, feto 5', 'Sin especificar', '["hidropesía feto 5"]'),
('O36.20X9', 'Atención materna por hidropesía fetal, trimestre no especificado, otro feto', 'Sin especificar', '["hidropesía otro feto"]'),
('O36.21X0', 'Atención materna por hidropesía fetal, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["hidropesía primer trimestre"]'),
('O36.21X1', 'Atención materna por hidropesía fetal, primer trimestre, feto 1', 'Sin especificar', '["hidropesía feto 1 primer trimestre"]'),
('O36.21X2', 'Atención materna por hidropesía fetal, primer trimestre, feto 2', 'Sin especificar', '["hidropesía feto 2 primer trimestre"]'),
('O36.21X3', 'Atención materna por hidropesía fetal, primer trimestre, feto 3', 'Sin especificar', '["hidropesía feto 3 primer trimestre"]'),
('O36.21X4', 'Atención materna por hidropesía fetal, primer trimestre, feto 4', 'Sin especificar', '["hidropesía feto 4 primer trimestre"]'),
('O36.21X5', 'Atención materna por hidropesía fetal, primer trimestre, feto 5', 'Sin especificar', '["hidropesía feto 5 primer trimestre"]'),
('O36.21X9', 'Atención materna por hidropesía fetal, primer trimestre, otro feto', 'Sin especificar', '["hidropesía otro feto primer trimestre"]'),
('O36.22X0', 'Atención materna por hidropesía fetal, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["hidropesía segundo trimestre"]'),
('O36.22X1', 'Atención materna por hidropesía fetal, segundo trimestre, feto 1', 'Sin especificar', '["hidropesía feto 1 segundo trimestre"]'),
('O36.22X2', 'Atención materna por hidropesía fetal, segundo trimestre, feto 2', 'Sin especificar', '["hidropesía feto 2 segundo trimestre"]'),
('O36.22X3', 'Atención materna por hidropesía fetal, segundo trimestre, feto 3', 'Sin especificar', '["hidropesía feto 3 segundo trimestre"]'),
('O36.22X4', 'Atención materna por hidropesía fetal, segundo trimestre, feto 4', 'Sin especificar', '["hidropesía feto 4 segundo trimestre"]'),
('O36.22X5', 'Atención materna por hidropesía fetal, segundo trimestre, feto 5', 'Sin especificar', '["hidropesía feto 5 segundo trimestre"]'),
('O36.22X9', 'Atención materna por hidropesía fetal, segundo trimestre, otro feto', 'Sin especificar', '["hidropesía otro feto segundo trimestre"]'),
('O36.23X0', 'Atención materna por hidropesía fetal, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["hidropesía tercer trimestre"]'),
('O36.23X1', 'Atención materna por hidropesía fetal, tercer trimestre, feto 1', 'Sin especificar', '["hidropesía feto 1 tercer trimestre"]'),
('O36.23X2', 'Atención materna por hidropesía fetal, tercer trimestre, feto 2', 'Sin especificar', '["hidropesía feto 2 tercer trimestre"]'),
('O36.23X3', 'Atención materna por hidropesía fetal, tercer trimestre, feto 3', 'Sin especificar', '["hidropesía feto 3 tercer trimestre"]'),
('O36.23X4', 'Atención materna por hidropesía fetal, tercer trimestre, feto 4', 'Sin especificar', '["hidropesía feto 4 tercer trimestre"]'),
('O36.23X5', 'Atención materna por hidropesía fetal, tercer trimestre, feto 5', 'Sin especificar', '["hidropesía feto 5 tercer trimestre"]'),
('O36.23X9', 'Atención materna por hidropesía fetal, tercer trimestre, otro feto', 'Sin especificar', '["hidropesía otro feto tercer trimestre"]'),
('O36.4XX0', 'Atención materna por muerte intrauterina, no aplicable o no especificado', 'Sin especificar', '["muerte fetal", "bebé muerto en el vientre", "óbito fetal", "pérdida de embarazo", "muerte dentro del útero", "aborto diferido", "feto sin latido", "embarazo interrumpido", "duelo gestacional"]'),
('O36.4XX1', 'Atención materna por muerte intrauterina, feto 1', 'Sin especificar', '["muerte intrauterina feto 1"]'),
('O36.4XX2', 'Atención materna por muerte intrauterina, feto 2', 'Sin especificar', '["muerte intrauterina feto 2"]'),
('O36.4XX3', 'Atención materna por muerte intrauterina, feto 3', 'Sin especificar', '["muerte intrauterina feto 3"]'),
('O36.4XX4', 'Atención materna por muerte intrauterina, feto 4', 'Sin especificar', '["muerte intrauterina feto 4"]'),
('O36.4XX5', 'Atención materna por muerte intrauterina, feto 5', 'Sin especificar', '["muerte intrauterina feto 5"]'),
('O36.4XX9', 'Atención materna por muerte intrauterina, otro feto', 'Sin especificar', '["muerte intrauterina otro feto"]'),
('O36.5110', 'Atención materna por insuficiencia placentaria, conocida o sospechada, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["insuficiencia placentaria", "mala alimentación del bebé", "placenta que no funciona", "problemas de placenta", "crecimiento lento feto", "placenta envejecida", "flujo umbilical pobre", "nutrición fetal insuficiente", "placenta deficiente", "bebé pequeño"]'),
('O36.5111', 'Atención materna por insuficiencia placentaria, conocida o sospechada, primer trimestre, feto 1', 'Sin especificar', '["insuficiencia placentaria feto 1"]'),
('O36.5112', 'Atención materna por insuficiencia placentaria, conocida o sospechada, primer trimestre, feto 2', 'Sin especificar', '["insuficiencia placentaria feto 2"]'),
('O36.5113', 'Atención materna por insuficiencia placentaria, conocida o sospechada, primer trimestre, feto 3', 'Sin especificar', '["insuficiencia placentaria feto 3"]'),
('O36.5114', 'Atención materna por insuficiencia placentaria, conocida o sospechada, primer trimestre, feto 4', 'Sin especificar', '["insuficiencia placentaria feto 4"]'),
('O36.5115', 'Atención materna por insuficiencia placentaria, conocida o sospechada, primer trimestre, feto 5', 'Sin especificar', '["insuficiencia placentaria feto 5"]'),
('O36.5119', 'Atención materna por insuficiencia placentaria, conocida o sospechada, primer trimestre, otro feto', 'Sin especificar', '["insuficiencia placentaria otro feto"]'),
('O36.5120', 'Atención materna por insuficiencia placentaria, conocida o sospechada, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["insuficiencia placentaria 2do trimestre"]'),
('O36.5121', 'Atención materna por insuficiencia placentaria, conocida o sospechada, segundo trimestre, feto 1', 'Sin especificar', '["insuficiencia placentaria feto 1 2do trimestre"]'),
('O36.5122', 'Atención materna por insuficiencia placentaria, conocida o sospechada, segundo trimestre, feto 2', 'Sin especificar', '["insuficiencia placentaria feto 2 2do trimestre"]'),
('O36.5123', 'Atención materna por insuficiencia placentaria, conocida o sospechada, segundo trimestre, feto 3', 'Sin especificar', '["insuficiencia placentaria feto 3 2do trimestre"]'),
('O36.5124', 'Atención materna por insuficiencia placentaria, conocida o sospechada, segundo trimestre, feto 4', 'Sin especificar', '["insuficiencia placentaria feto 4 2do trimestre"]'),
('O36.5125', 'Atención materna por insuficiencia placentaria, conocida o sospechada, segundo trimestre, feto 5', 'Sin especificar', '["insuficiencia placentaria feto 5 2do trimestre"]'),
('O36.5129', 'Atención materna por insuficiencia placentaria, conocida o sospechada, segundo trimestre, otro feto', 'Sin especificar', '["insuficiencia placentaria otro feto 2do trimestre"]'),
('O36.5130', 'Atención materna por insuficiencia placentaria, conocida o sospechada, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["insuficiencia placentaria 3er trimestre"]'),
('O36.5131', 'Atención materna por insuficiencia placentaria, conocida o sospechada, tercer trimestre, feto 1', 'Sin especificar', '["insuficiencia placentaria feto 1 3er trimestre"]'),
('O36.5132', 'Atención materna por insuficiencia placentaria, conocida o sospechada, tercer trimestre, feto 2', 'Sin especificar', '["insuficiencia placentaria feto 2 3er trimestre"]'),
('O36.5133', 'Atención materna por insuficiencia placentaria, conocida o sospechada, tercer trimestre, feto 3', 'Sin especificar', '["insuficiencia placentaria feto 3 3er trimestre"]'),
('O36.5134', 'Atención materna por insuficiencia placentaria, conocida o sospechada, tercer trimestre, feto 4', 'Sin especificar', '["insuficiencia placentaria feto 4 3er trimestre"]'),
('O36.5135', 'Atención materna por insuficiencia placentaria, conocida o sospechada, tercer trimestre, feto 5', 'Sin especificar', '["insuficiencia placentaria feto 5 3er trimestre"]'),
('O36.5139', 'Atención materna por insuficiencia placentaria, conocida o sospechada, tercer trimestre, otro feto', 'Sin especificar', '["insuficiencia placentaria otro feto 3er trimestre"]'),
('O36.5190', 'Atención materna por insuficiencia placentaria, conocida o sospechada, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["insuficiencia placentaria general"]'),
('O36.5191', 'Atención materna por insuficiencia placentaria, conocida o sospechada, trimestre no especificado, feto 1', 'Sin especificar', '["insuficiencia placentaria feto 1 general"]'),
('O36.5192', 'Atención materna por insuficiencia placentaria, conocida o sospechada, trimestre no especificado, feto 2', 'Sin especificar', '["insuficiencia placentaria feto 2 general"]'),
('O36.5193', 'Atención materna por insuficiencia placentaria, conocida o sospechada, trimestre no especificado, feto 3', 'Sin especificar', '["insuficiencia placentaria feto 3 general"]'),
('O36.5194', 'Atención materna por insuficiencia placentaria, conocida o sospechada, trimestre no especificado, feto 4', 'Sin especificar', '["insuficiencia placentaria feto 4 general"]'),
('O36.5195', 'Atención materna por insuficiencia placentaria, conocida o sospechada, trimestre no especificado, feto 5', 'Sin especificar', '["insuficiencia placentaria feto 5 general"]'),
('O36.5199', 'Atención materna por insuficiencia placentaria, conocida o sospechada, trimestre no especificado, otro feto', 'Sin especificar', '["insuficiencia placentaria otro feto general"]'),
('O36.5910', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["crecimiento restringido intrauterino", "bebé pequeño para edad gestacional", "feto que no crece", "RCIU", "retraso crecimiento fetal", "peso bajo del bebé", "desnutrición fetal", "problemas de tamaño feto", "bajo peso gestacional", "feto hipocrecido"]'),
('O36.5911', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, primer trimestre, feto 1', 'Sin especificar', '["crecimiento insuficiente feto 1"]'),
('O36.5912', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, primer trimestre, feto 2', 'Sin especificar', '["crecimiento insuficiente feto 2"]'),
('O36.5913', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, primer trimestre, feto 3', 'Sin especificar', '["crecimiento insuficiente feto 3"]'),
('O36.5914', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, primer trimestre, feto 4', 'Sin especificar', '["crecimiento insuficiente feto 4"]'),
('O36.5915', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, primer trimestre, feto 5', 'Sin especificar', '["crecimiento insuficiente feto 5"]'),
('O36.5919', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, primer trimestre, otro feto', 'Sin especificar', '["crecimiento insuficiente otro feto"]'),
('O36.5920', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["crecimiento insuficiente 2do trimestre"]'),
('O36.5921', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, segundo trimestre, feto 1', 'Sin especificar', '["crecimiento insuficiente feto 1 2do trimestre"]'),
('O36.5922', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, segundo trimestre, feto 2', 'Sin especificar', '["crecimiento insuficiente feto 2 2do trimestre"]'),
('O36.5923', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, segundo trimestre, feto 3', 'Sin especificar', '["crecimiento insuficiente feto 3 2do trimestre"]'),
('O36.5924', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, segundo trimestre, feto 4', 'Sin especificar', '["crecimiento insuficiente feto 4 2do trimestre"]'),
('O36.5925', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, segundo trimestre, feto 5', 'Sin especificar', '["crecimiento insuficiente feto 5 2do trimestre"]'),
('O36.5929', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, segundo trimestre, otro feto', 'Sin especificar', '["crecimiento insuficiente otro feto 2do trimestre"]'),
('O36.5930', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["crecimiento insuficiente 3er trimestre"]'),
('O36.5931', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, tercer trimestre, feto 1', 'Sin especificar', '["crecimiento insuficiente feto 1 3er trimestre"]'),
('O36.5932', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, tercer trimestre, feto 2', 'Sin especificar', '["crecimiento insuficiente feto 2 3er trimestre"]'),
('O36.5933', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, tercer trimestre, feto 3', 'Sin especificar', '["crecimiento insuficiente feto 3 3er trimestre"]'),
('O36.5934', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, tercer trimestre, feto 4', 'Sin especificar', '["crecimiento insuficiente feto 4 3er trimestre"]'),
('O36.5935', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, tercer trimestre, feto 5', 'Sin especificar', '["crecimiento insuficiente feto 5 3er trimestre"]'),
('O36.5939', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, tercer trimestre, otro feto', 'Sin especificar', '["crecimiento insuficiente otro feto 3er trimestre"]'),
('O36.5990', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["crecimiento insuficiente feto general"]'),
('O36.5991', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, trimestre no especificado, feto 1', 'Sin especificar', '["crecimiento insuficiente feto 1 general"]'),
('O36.5992', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, trimestre no especificado, feto 2', 'Sin especificar', '["crecimiento insuficiente feto 2 general"]'),
('O36.5993', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, trimestre no especificado, feto 3', 'Sin especificar', '["crecimiento insuficiente feto 3 general"]'),
('O36.5994', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, trimestre no especificado, feto 4', 'Sin especificar', '["crecimiento insuficiente feto 4 general"]'),
('O36.5995', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, trimestre no especificado, feto 5', 'Sin especificar', '["crecimiento insuficiente feto 5 general"]'),
('O36.5999', 'Atención materna por otro tipo de crecimiento fetal insuficiente, conocido o sospechado, trimestre no especificado, otro feto', 'Sin especificar', '["crecimiento insuficiente otro feto general"]'),
('O36.60X0', 'Atención materna por crecimiento fetal excesivo, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["bebé muy grande", "macrosomía fetal", "feto grande", "exceso de crecimiento feto", "bebé macrosómico", "peso elevado al nacer", "feto gigante", "diabetes gestacional bebé grande", "bebé pesado", "crecimiento fetal rápido"]'),
('O36.60X1', 'Atención materna por crecimiento fetal excesivo, trimestre no especificado, feto 1', 'Sin especificar', '["crecimiento excesivo feto 1"]'),
('O36.60X2', 'Atención materna por crecimiento fetal excesivo, trimestre no especificado, feto 2', 'Sin especificar', '["crecimiento excesivo feto 2"]'),
('O36.60X3', 'Atención materna por crecimiento fetal excesivo, trimestre no especificado, feto 3', 'Sin especificar', '["crecimiento excesivo feto 3"]'),
('O36.60X4', 'Atención materna por crecimiento fetal excesivo, trimestre no especificado, feto 4', 'Sin especificar', '["crecimiento excesivo feto 4"]'),
('O36.60X5', 'Atención materna por crecimiento fetal excesivo, trimestre no especificado, feto 5', 'Sin especificar', '["crecimiento excesivo feto 5"]'),
('O36.60X9', 'Atención materna por crecimiento fetal excesivo, trimestre no especificado, otro feto', 'Sin especificar', '["crecimiento excesivo otro feto"]'),
('O36.61X0', 'Atención materna por crecimiento fetal excesivo, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["crecimiento excesivo primer trimestre"]'),
('O36.61X1', 'Atención materna por crecimiento fetal excesivo, primer trimestre, feto 1', 'Sin especificar', '["crecimiento excesivo feto 1 primer trimestre"]'),
('O36.61X2', 'Atención materna por crecimiento fetal excesivo, primer trimestre, feto 2', 'Sin especificar', '["crecimiento excesivo feto 2 primer trimestre"]'),
('O36.61X3', 'Atención materna por crecimiento fetal excesivo, primer trimestre, feto 3', 'Sin especificar', '["crecimiento excesivo feto 3 primer trimestre"]'),
('O36.61X4', 'Atención materna por crecimiento fetal excesivo, primer trimestre, feto 4', 'Sin especificar', '["crecimiento excesivo feto 4 primer trimestre"]'),
('O36.61X5', 'Atención materna por crecimiento fetal excesivo, primer trimestre, feto 5', 'Sin especificar', '["crecimiento excesivo feto 5 primer trimestre"]'),
('O36.61X9', 'Atención materna por crecimiento fetal excesivo, primer trimestre, otro feto', 'Sin especificar', '["crecimiento excesivo otro feto primer trimestre"]'),
('O36.62X0', 'Atención materna por crecimiento fetal excesivo, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["crecimiento excesivo segundo trimestre"]'),
('O36.62X1', 'Atención materna por crecimiento fetal excesivo, segundo trimestre, feto 1', 'Sin especificar', '["crecimiento excesivo feto 1 segundo trimestre"]'),
('O36.62X2', 'Atención materna por crecimiento fetal excesivo, segundo trimestre, feto 2', 'Sin especificar', '["crecimiento excesivo feto 2 segundo trimestre"]'),
('O36.62X3', 'Atención materna por crecimiento fetal excesivo, segundo trimestre, feto 3', 'Sin especificar', '["crecimiento excesivo feto 3 segundo trimestre"]'),
('O36.62X4', 'Atención materna por crecimiento fetal excesivo, segundo trimestre, feto 4', 'Sin especificar', '["crecimiento excesivo feto 4 segundo trimestre"]'),
('O36.62X5', 'Atención materna por crecimiento fetal excesivo, segundo trimestre, feto 5', 'Sin especificar', '["crecimiento excesivo feto 5 segundo trimestre"]'),
('O36.62X9', 'Atención materna por crecimiento fetal excesivo, segundo trimestre, otro feto', 'Sin especificar', '["crecimiento excesivo otro feto segundo trimestre"]'),
('O36.63X0', 'Atención materna por crecimiento fetal excesivo, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["crecimiento excesivo tercer trimestre"]'),
('O36.63X1', 'Atención materna por crecimiento fetal excesivo, tercer trimestre, feto 1', 'Sin especificar', '["crecimiento excesivo feto 1 tercer trimestre"]'),
('O36.63X2', 'Atención materna por crecimiento fetal excesivo, tercer trimestre, feto 2', 'Sin especificar', '["crecimiento excesivo feto 2 tercer trimestre"]'),
('O36.63X3', 'Atención materna por crecimiento fetal excesivo, tercer trimestre, feto 3', 'Sin especificar', '["crecimiento excesivo feto 3 tercer trimestre"]'),
('O36.63X4', 'Atención materna por crecimiento fetal excesivo, tercer trimestre, feto 4', 'Sin especificar', '["crecimiento excesivo feto 4 tercer trimestre"]'),
('O36.63X5', 'Atención materna por crecimiento fetal excesivo, tercer trimestre, feto 5', 'Sin especificar', '["crecimiento excesivo feto 5 tercer trimestre"]'),
('O36.63X9', 'Atención materna por crecimiento fetal excesivo, tercer trimestre, otro feto', 'Sin especificar', '["crecimiento excesivo otro feto tercer trimestre"]'),
('O36.70X0', 'Atención materna por feto viable en embarazo abdominal, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["embarazo abdominal", "embarazo extrauterino avanzado", "feto fuera del útero", "gestación abdominal", "bebé en la cavidad abdominal", "embarazo ectópico tardío", "feto viable en abdomen", "complicación de embarazo extrauterino", "embarazo fuera del útero"]'),
('O36.70X1', 'Atención materna por feto viable en embarazo abdominal, trimestre no especificado, feto 1', 'Sin especificar', '["embarazo abdominal feto 1"]'),
('O36.70X2', 'Atención materna por feto viable en embarazo abdominal, trimestre no especificado, feto 2', 'Sin especificar', '["embarazo abdominal feto 2"]'),
('O36.70X3', 'Atención materna por feto viable en embarazo abdominal, trimestre no especificado, feto 3', 'Sin especificar', '["embarazo abdominal feto 3"]'),
('O36.70X4', 'Atención materna por feto viable en embarazo abdominal, trimestre no especificado, feto 4', 'Sin especificar', '["embarazo abdominal feto 4"]'),
('O36.70X5', 'Atención materna por feto viable en embarazo abdominal, trimestre no especificado, feto 5', 'Sin especificar', '["embarazo abdominal feto 5"]'),
('O36.70X9', 'Atención materna por feto viable en embarazo abdominal, trimestre no especificado, otro feto', 'Sin especificar', '["embarazo abdominal otro feto"]'),
('O36.71X0', 'Atención materna por feto viable en embarazo abdominal, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["embarazo abdominal primer trimestre"]'),
('O36.71X1', 'Atención materna por feto viable en embarazo abdominal, primer trimestre, feto 1', 'Sin especificar', '["embarazo abdominal feto 1 primer trimestre"]'),
('O36.71X2', 'Atención materna por feto viable en embarazo abdominal, primer trimestre, feto 2', 'Sin especificar', '["embarazo abdominal feto 2 primer trimestre"]'),
('O36.71X3', 'Atención materna por feto viable en embarazo abdominal, primer trimestre, feto 3', 'Sin especificar', '["embarazo abdominal feto 3 primer trimestre"]'),
('O36.71X4', 'Atención materna por feto viable en embarazo abdominal, primer trimestre, feto 4', 'Sin especificar', '["embarazo abdominal feto 4 primer trimestre"]'),
('O36.71X5', 'Atención materna por feto viable en embarazo abdominal, primer trimestre, feto 5', 'Sin especificar', '["embarazo abdominal feto 5 primer trimestre"]'),
('O36.71X9', 'Atención materna por feto viable en embarazo abdominal, primer trimestre, otro feto', 'Sin especificar', '["embarazo abdominal otro feto primer trimestre"]'),
('O36.72X0', 'Atención materna por feto viable en embarazo abdominal, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["embarazo abdominal segundo trimestre"]'),
('O36.72X1', 'Atención materna por feto viable en embarazo abdominal, segundo trimestre, feto 1', 'Sin especificar', '["embarazo abdominal feto 1 segundo trimestre"]'),
('O36.72X2', 'Atención materna por feto viable en embarazo abdominal, segundo trimestre, feto 2', 'Sin especificar', '["embarazo abdominal feto 2 segundo trimestre"]'),
('O36.72X3', 'Atención materna por feto viable en embarazo abdominal, segundo trimestre, feto 3', 'Sin especificar', '["embarazo abdominal feto 3 segundo trimestre"]'),
('O36.72X4', 'Atención materna por feto viable en embarazo abdominal, segundo trimestre, feto 4', 'Sin especificar', '["embarazo abdominal feto 4 segundo trimestre"]'),
('O36.72X5', 'Atención materna por feto viable en embarazo abdominal, segundo trimestre, feto 5', 'Sin especificar', '["embarazo abdominal feto 5 segundo trimestre"]'),
('O36.72X9', 'Atención materna por feto viable en embarazo abdominal, segundo trimestre, otro feto', 'Sin especificar', '["embarazo abdominal otro feto segundo trimestre"]'),
('O36.73X0', 'Atención materna por feto viable en embarazo abdominal, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["embarazo abdominal tercer trimestre"]'),
('O36.73X1', 'Atención materna por feto viable en embarazo abdominal, tercer trimestre, feto 1', 'Sin especificar', '["embarazo abdominal feto 1 tercer trimestre"]'),
('O36.73X2', 'Atención materna por feto viable en embarazo abdominal, tercer trimestre, feto 2', 'Sin especificar', '["embarazo abdominal feto 2 tercer trimestre"]'),
('O36.73X3', 'Atención materna por feto viable en embarazo abdominal, tercer trimestre, feto 3', 'Sin especificar', '["embarazo abdominal feto 3 tercer trimestre"]'),
('O36.73X4', 'Atención materna por feto viable en embarazo abdominal, tercer trimestre, feto 4', 'Sin especificar', '["embarazo abdominal feto 4 tercer trimestre"]'),
('O36.73X5', 'Atención materna por feto viable en embarazo abdominal, tercer trimestre, feto 5', 'Sin especificar', '["embarazo abdominal feto 5 tercer trimestre"]'),
('O36.73X9', 'Atención materna por feto viable en embarazo abdominal, tercer trimestre, otro feto', 'Sin especificar', '["embarazo abdominal otro feto tercer trimestre"]'),
('O36.80X0', 'Embarazo con viabilidad fetal no concluyente, no aplicable o no especificado', 'Sin especificar', '["viabilidad fetal dudosa", "no se escucha latido", "embarazo en duda", "monitoreo feto no concluyente", "viabilidad feto incierta", "control latido fetal", "latido fetal difícil", "embarazo con riesgo", "feto con signos inciertos"]'),
('O36.80X1', 'Embarazo con viabilidad fetal no concluyente, feto 1', 'Sin especificar', '["viabilidad dudosa feto 1"]'),
('O36.80X2', 'Embarazo con viabilidad fetal no concluyente, feto 2', 'Sin especificar', '["viabilidad dudosa feto 2"]'),
('O36.80X3', 'Embarazo con viabilidad fetal no concluyente, feto 3', 'Sin especificar', '["viabilidad dudosa feto 3"]'),
('O36.80X4', 'Embarazo con viabilidad fetal no concluyente, feto 4', 'Sin especificar', '["viabilidad dudosa feto 4"]'),
('O36.80X5', 'Embarazo con viabilidad fetal no concluyente, feto 5', 'Sin especificar', '["viabilidad dudosa feto 5"]'),
('O36.80X9', 'Embarazo con viabilidad fetal no concluyente, otro feto', 'Sin especificar', '["viabilidad dudosa otro feto"]'),
('O36.8120', 'Disminución de los movimientos fetales, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["feto no se mueve", "el bebé se mueve poco", "disminución movimientos bebé", "se mueve menos el bebé", "bebé quieto", "falta de movimiento fetal", "poco movimiento intrauterino", "estoy preocupada no siento al bebé", "feto lento"]'),
('O36.8121', 'Disminución de los movimientos fetales, segundo trimestre, feto 1', 'Sin especificar', '["pocos movimientos feto 1"]'),
('O36.8122', 'Disminución de los movimientos fetales, segundo trimestre, feto 2', 'Sin especificar', '["pocos movimientos feto 2"]'),
('O36.8123', 'Disminución de los movimientos fetales, segundo trimestre, feto 3', 'Sin especificar', '["pocos movimientos feto 3"]'),
('O36.8124', 'Disminución de los movimientos fetales, segundo trimestre, feto 4', 'Sin especificar', '["pocos movimientos feto 4"]'),
('O36.8125', 'Disminución de los movimientos fetales, segundo trimestre, feto 5', 'Sin especificar', '["pocos movimientos feto 5"]'),
('O36.8129', 'Disminución de los movimientos fetales, segundo trimestre, otro feto', 'Sin especificar', '["pocos movimientos otro feto"]'),
('O36.8130', 'Disminución de los movimientos fetales, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["pocos movimientos tercer trimestre"]'),
('O36.8131', 'Disminución de los movimientos fetales, tercer trimestre, feto 1', 'Sin especificar', '["pocos movimientos feto 1 tercer trimestre"]'),
('O36.8132', 'Disminución de los movimientos fetales, tercer trimestre, feto 2', 'Sin especificar', '["pocos movimientos feto 2 tercer trimestre"]'),
('O36.8133', 'Disminución de los movimientos fetales, tercer trimestre, feto 3', 'Sin especificar', '["pocos movimientos feto 3 tercer trimestre"]'),
('O36.8134', 'Disminución de los movimientos fetales, tercer trimestre, feto 4', 'Sin especificar', '["pocos movimientos feto 4 tercer trimestre"]'),
('O36.8135', 'Disminución de los movimientos fetales, tercer trimestre, feto 5', 'Sin especificar', '["pocos movimientos feto 5 tercer trimestre"]'),
('O36.8139', 'Disminución de los movimientos fetales, tercer trimestre, otro feto', 'Sin especificar', '["pocos movimientos otro feto tercer trimestre"]'),
('O36.8190', 'Disminución de los movimientos fetales, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["movimientos fetales disminuidos"]'),
('O36.8191', 'Disminución de los movimientos fetales, trimestre no especificado, feto 1', 'Sin especificar', '["movimientos fetales disminuidos feto 1"]'),
('O36.8192', 'Disminución de los movimientos fetales, trimestre no especificado, feto 2', 'Sin especificar', '["movimientos fetales disminuidos feto 2"]'),
('O36.8193', 'Disminución de los movimientos fetales, trimestre no especificado, feto 3', 'Sin especificar', '["movimientos fetales disminuidos feto 3"]'),
('O36.8194', 'Disminución de los movimientos fetales, trimestre no especificado, feto 4', 'Sin especificar', '["movimientos fetales disminuidos feto 4"]'),
('O36.8195', 'Disminución de los movimientos fetales, trimestre no especificado, feto 5', 'Sin especificar', '["movimientos fetales disminuidos feto 5"]'),
('O36.8199', 'Disminución de los movimientos fetales, trimestre no especificado, otro feto', 'Sin especificar', '["movimientos fetales disminuidos otro feto"]'),
('O36.8210', 'Anemia y trombocitopenia fetal, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["anemia del bebé", "bebé sin sangre", "plaquetas bajas feto", "anemia fetal", "trombocitopenia feto", "problemas de sangre feto", "anemia intrauterina", "plaquetas bajas en el feto", "riesgo sanguíneo feto", "sangre fetal"]'),
('O36.8211', 'Anemia y trombocitopenia fetal, primer trimestre, feto 1', 'Sin especificar', '["anemia feto 1"]'),
('O36.8212', 'Anemia y trombocitopenia fetal, primer trimestre, feto 2', 'Sin especificar', '["anemia feto 2"]'),
('O36.8213', 'Anemia y trombocitopenia fetal, primer trimestre, feto 3', 'Sin especificar', '["anemia feto 3"]'),
('O36.8214', 'Anemia y trombocitopenia fetal, primer trimestre, feto 4', 'Sin especificar', '["anemia feto 4"]'),
('O36.8215', 'Anemia y trombocitopenia fetal, primer trimestre, feto 5', 'Sin especificar', '["anemia feto 5"]'),
('O36.8219', 'Anemia y trombocitopenia fetal, primer trimestre, otro feto', 'Sin especificar', '["anemia otro feto"]'),
('O36.8220', 'Anemia y trombocitopenia fetal, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["anemia segundo trimestre"]'),
('O36.8221', 'Anemia y trombocitopenia fetal, segundo trimestre, feto 1', 'Sin especificar', '["anemia feto 1 segundo trimestre"]'),
('O36.8222', 'Anemia y trombocitopenia fetal, segundo trimestre, feto 2', 'Sin especificar', '["anemia feto 2 segundo trimestre"]'),
('O36.8223', 'Anemia y trombocitopenia fetal, segundo trimestre, feto 3', 'Sin especificar', '["anemia feto 3 segundo trimestre"]'),
('O36.8224', 'Anemia y trombocitopenia fetal, segundo trimestre, feto 4', 'Sin especificar', '["anemia feto 4 segundo trimestre"]'),
('O36.8225', 'Anemia y trombocitopenia fetal, segundo trimestre, feto 5', 'Sin especificar', '["anemia feto 5 segundo trimestre"]'),
('O36.8229', 'Anemia y trombocitopenia fetal, segundo trimestre, otro feto', 'Sin especificar', '["anemia otro feto segundo trimestre"]'),
('O36.8230', 'Anemia y trombocitopenia fetal, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["anemia tercer trimestre"]'),
('O36.8231', 'Anemia y trombocitopenia fetal, tercer trimestre, feto 1', 'Sin especificar', '["anemia feto 1 tercer trimestre"]'),
('O36.8232', 'Anemia y trombocitopenia fetal, tercer trimestre, feto 2', 'Sin especificar', '["anemia feto 2 tercer trimestre"]'),
('O36.8233', 'Anemia y trombocitopenia fetal, tercer trimestre, feto 3', 'Sin especificar', '["anemia feto 3 tercer trimestre"]'),
('O36.8234', 'Anemia y trombocitopenia fetal, tercer trimestre, feto 4', 'Sin especificar', '["anemia feto 4 tercer trimestre"]'),
('O36.8235', 'Anemia y trombocitopenia fetal, tercer trimestre, feto 5', 'Sin especificar', '["anemia feto 5 tercer trimestre"]'),
('O36.8239', 'Anemia y trombocitopenia fetal, tercer trimestre, otro feto', 'Sin especificar', '["anemia otro feto tercer trimestre"]'),
('O36.8290', 'Anemia y trombocitopenia fetal, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["anemia feto general"]'),
('O36.8291', 'Anemia y trombocitopenia fetal, trimestre no especificado, feto 1', 'Sin especificar', '["anemia feto 1 general"]'),
('O36.8292', 'Anemia y trombocitopenia fetal, trimestre no especificado, feto 2', 'Sin especificar', '["anemia feto 2 general"]'),
('O36.8293', 'Anemia y trombocitopenia fetal, trimestre no especificado, feto 3', 'Sin especificar', '["anemia feto 3 general"]'),
('O36.8294', 'Anemia y trombocitopenia fetal, trimestre no especificado, feto 4', 'Sin especificar', '["anemia feto 4 general"]'),
('O36.8295', 'Anemia y trombocitopenia fetal, trimestre no especificado, feto 5', 'Sin especificar', '["anemia feto 5 general"]'),
('O36.8299', 'Anemia y trombocitopenia fetal, trimestre no especificado, otro feto', 'Sin especificar', '["anemia otro feto general"]'),
('O36.8310', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["corazón del bebé acelerado", "ritmo cardíaco feto irregular", "latido bebé lento", "arritmia feto", "problemas corazón feto", "taquicardia fetal", "bradicardia feto", "latidos cardíacos extraños", "corazón bebé", "monitoreo cardíaco feto"]'),
('O36.8311', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, primer trimestre, feto 1', 'Sin especificar', '["ritmo cardíaco feto 1"]'),
('O36.8312', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, primer trimestre, feto 2', 'Sin especificar', '["ritmo cardíaco feto 2"]'),
('O36.8313', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, primer trimestre, feto 3', 'Sin especificar', '["ritmo cardíaco feto 3"]'),
('O36.8314', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, primer trimestre, feto 4', 'Sin especificar', '["ritmo cardíaco feto 4"]'),
('O36.8315', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, primer trimestre, feto 5', 'Sin especificar', '["ritmo cardíaco feto 5"]'),
('O36.8319', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, primer trimestre, otro feto', 'Sin especificar', '["ritmo cardíaco otro feto"]'),
('O36.8320', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["arritmia segundo trimestre"]'),
('O36.8321', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, segundo trimestre, feto 1', 'Sin especificar', '["arritmia feto 1 segundo trimestre"]'),
('O36.8322', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, segundo trimestre, feto 2', 'Sin especificar', '["arritmia feto 2 segundo trimestre"]'),
('O36.8323', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, segundo trimestre, feto 3', 'Sin especificar', '["arritmia feto 3 segundo trimestre"]'),
('O36.8324', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, segundo trimestre, feto 4', 'Sin especificar', '["arritmia feto 4 segundo trimestre"]'),
('O36.8325', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, segundo trimestre, feto 5', 'Sin especificar', '["arritmia feto 5 segundo trimestre"]'),
('O36.8329', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, segundo trimestre, otro feto', 'Sin especificar', '["arritmia otro feto segundo trimestre"]'),
('O36.8330', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["arritmia tercer trimestre"]'),
('O36.8331', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, tercer trimestre, feto 1', 'Sin especificar', '["arritmia feto 1 tercer trimestre"]'),
('O36.8332', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, tercer trimestre, feto 2', 'Sin especificar', '["arritmia feto 2 tercer trimestre"]'),
('O36.8333', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, tercer trimestre, feto 3', 'Sin especificar', '["arritmia feto 3 tercer trimestre"]'),
('O36.8334', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, tercer trimestre, feto 4', 'Sin especificar', '["arritmia feto 4 tercer trimestre"]'),
('O36.8335', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, tercer trimestre, feto 5', 'Sin especificar', '["arritmia feto 5 tercer trimestre"]'),
('O36.8339', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, tercer trimestre, otro feto', 'Sin especificar', '["arritmia otro feto tercer trimestre"]'),
('O36.8390', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["arritmia general"]'),
('O36.8391', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, trimestre no especificado, feto 1', 'Sin especificar', '["arritmia feto 1 general"]'),
('O36.8392', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, trimestre no especificado, feto 2', 'Sin especificar', '["arritmia feto 2 general"]'),
('O36.8393', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, trimestre no especificado, feto 3', 'Sin especificar', '["arritmia feto 3 general"]'),
('O36.8394', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, trimestre no especificado, feto 4', 'Sin especificar', '["arritmia feto 4 general"]'),
('O36.8395', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, trimestre no especificado, feto 5', 'Sin especificar', '["arritmia feto 5 general"]'),
('O36.8399', 'Atención materna por anomalías de la frecuencia o ritmo cardíacos fetales, trimestre no especificado, otro feto', 'Sin especificar', '["arritmia otro feto general"]'),
('O36.8910', 'Atención materna por otros problemas fetales especificados, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["problema feto", "complicación feto", "feto en riesgo", "salud fetal preocupante", "problema en el bebé", "monitoreo feto", "riesgo gestacional", "feto especial", "control embarazo difícil", "problemas desarrollo fetal"]'),
('O36.8911', 'Atención materna por otros problemas fetales especificados, primer trimestre, feto 1', 'Sin especificar', '["problema feto 1"]'),
('O36.8912', 'Atención materna por otros problemas fetales especificados, primer trimestre, feto 2', 'Sin especificar', '["problema feto 2"]'),
('O36.8913', 'Atención materna por otros problemas fetales especificados, primer trimestre, feto 3', 'Sin especificar', '["problema feto 3"]'),
('O36.8914', 'Atención materna por otros problemas fetales especificados, primer trimestre, feto 4', 'Sin especificar', '["problema feto 4"]'),
('O36.8915', 'Atención materna por otros problemas fetales especificados, primer trimestre, feto 5', 'Sin especificar', '["problema feto 5"]'),
('O36.8919', 'Atención materna por otros problemas fetales especificados, primer trimestre, otro feto', 'Sin especificar', '["problema otro feto"]'),
('O36.8920', 'Atención materna por otros problemas fetales especificados, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["problema feto segundo trimestre"]'),
('O36.8921', 'Atención materna por otros problemas fetales especificados, segundo trimestre, feto 1', 'Sin especificar', '["problema feto 1 segundo trimestre"]'),
('O36.8922', 'Atención materna por otros problemas fetales especificados, segundo trimestre, feto 2', 'Sin especificar', '["problema feto 2 segundo trimestre"]'),
('O36.8923', 'Atención materna por otros problemas fetales especificados, segundo trimestre, feto 3', 'Sin especificar', '["problema feto 3 segundo trimestre"]'),
('O36.8924', 'Atención materna por otros problemas fetales especificados, segundo trimestre, feto 4', 'Sin especificar', '["problema feto 4 segundo trimestre"]'),
('O36.8925', 'Atención materna por otros problemas fetales especificados, segundo trimestre, feto 5', 'Sin especificar', '["problema feto 5 segundo trimestre"]'),
('O36.8929', 'Atención materna por otros problemas fetales especificados, segundo trimestre, otro feto', 'Sin especificar', '["problema otro feto segundo trimestre"]'),
('O36.8930', 'Atención materna por otros problemas fetales especificados, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["problema feto tercer trimestre"]'),
('O36.8931', 'Atención materna por otros problemas fetales especificados, tercer trimestre, feto 1', 'Sin especificar', '["problema feto 1 tercer trimestre"]'),
('O36.8932', 'Atención materna por otros problemas fetales especificados, tercer trimestre, feto 2', 'Sin especificar', '["problema feto 2 tercer trimestre"]'),
('O36.8933', 'Atención materna por otros problemas fetales especificados, tercer trimestre, feto 3', 'Sin especificar', '["problema feto 3 tercer trimestre"]'),
('O36.8934', 'Atención materna por otros problemas fetales especificados, tercer trimestre, feto 4', 'Sin especificar', '["problema feto 4 tercer trimestre"]'),
('O36.8935', 'Atención materna por otros problemas fetales especificados, tercer trimestre, feto 5', 'Sin especificar', '["problema feto 5 tercer trimestre"]'),
('O36.8939', 'Atención materna por otros problemas fetales especificados, tercer trimestre, otro feto', 'Sin especificar', '["problema otro feto tercer trimestre"]'),
('O36.8990', 'Atención materna por otros problemas fetales especificados, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["problema feto general"]'),
('O36.8991', 'Atención materna por otros problemas fetales especificados, trimestre no especificado, feto 1', 'Sin especificar', '["problema feto 1 general"]'),
('O36.8992', 'Atención materna por otros problemas fetales especificados, trimestre no especificado, feto 2', 'Sin especificar', '["problema feto 2 general"]'),
('O36.8993', 'Atención materna por otros problemas fetales especificados, trimestre no especificado, feto 3', 'Sin especificar', '["problema feto 3 general"]'),
('O36.8994', 'Atención materna por otros problemas fetales especificados, trimestre no especificado, feto 4', 'Sin especificar', '["problema feto 4 general"]'),
('O36.8995', 'Atención materna por otros problemas fetales especificados, trimestre no especificado, feto 5', 'Sin especificar', '["problema feto 5 general"]'),
('O36.8999', 'Atención materna por otros problemas fetales especificados, trimestre no especificado, otro feto', 'Sin especificar', '["problema otro feto general"]'),
('O36.90X0', 'Atención materna por problema fetal, no especificado, trimestre no especificado, no aplicable o no especificado', 'Sin especificar', '["embarazo con complicaciones", "problema en el embarazo no definido", "feto riesgo", "embarazo control especial", "bebé no está bien", "problemas fetales", "monitoreo feto"]'),
('O36.90X1', 'Atención materna por problema fetal, no especificado, trimestre no especificado, feto 1', 'Sin especificar', '["problema fetal feto 1"]'),
('O36.90X2', 'Atención materna por problema fetal, no especificado, trimestre no especificado, feto 2', 'Sin especificar', '["problema fetal feto 2"]'),
('O36.90X3', 'Atención materna por problema fetal, no especificado, trimestre no especificado, feto 3', 'Sin especificar', '["problema fetal feto 3"]'),
('O36.90X4', 'Atención materna por problema fetal, no especificado, trimestre no especificado, feto 4', 'Sin especificar', '["problema fetal feto 4"]'),
('O36.90X5', 'Atención materna por problema fetal, no especificado, trimestre no especificado, feto 5', 'Sin especificar', '["problema fetal feto 5"]'),
('O36.90X9', 'Atención materna por problema fetal, no especificado, trimestre no especificado, otro feto', 'Sin especificar', '["problema fetal otro feto"]'),
('O36.91X0', 'Atención materna por problema fetal, no especificado, primer trimestre, no aplicable o no especificado', 'Sin especificar', '["problema fetal primer trimestre"]'),
('O36.91X1', 'Atención materna por problema fetal, no especificado, primer trimestre, feto 1', 'Sin especificar', '["problema fetal feto 1 primer trimestre"]'),
('O36.91X2', 'Atención materna por problema fetal, no especificado, primer trimestre, feto 2', 'Sin especificar', '["problema fetal feto 2 primer trimestre"]'),
('O36.91X3', 'Atención materna por problema fetal, no especificado, primer trimestre, feto 3', 'Sin especificar', '["problema fetal feto 3 primer trimestre"]'),
('O36.91X4', 'Atención materna por problema fetal, no especificado, primer trimestre, feto 4', 'Sin especificar', '["problema fetal feto 4 primer trimestre"]'),
('O36.91X5', 'Atención materna por problema fetal, no especificado, primer trimestre, feto 5', 'Sin especificar', '["problema fetal feto 5 primer trimestre"]'),
('O36.91X9', 'Atención materna por problema fetal, no especificado, primer trimestre, otro feto', 'Sin especificar', '["problema fetal otro feto primer trimestre"]'),
('O36.92X0', 'Atención materna por problema fetal, no especificado, segundo trimestre, no aplicable o no especificado', 'Sin especificar', '["problema fetal segundo trimestre"]'),
('O36.92X1', 'Atención materna por problema fetal, no especificado, segundo trimestre, feto 1', 'Sin especificar', '["problema fetal feto 1 segundo trimestre"]'),
('O36.92X2', 'Atención materna por problema fetal, no especificado, segundo trimestre, feto 2', 'Sin especificar', '["problema fetal feto 2 segundo trimestre"]'),
('O36.92X3', 'Atención materna por problema fetal, no especificado, segundo trimestre, feto 3', 'Sin especificar', '["problema fetal feto 3 segundo trimestre"]'),
('O36.92X4', 'Atención materna por problema fetal, no especificado, segundo trimestre, feto 4', 'Sin especificar', '["problema fetal feto 4 segundo trimestre"]'),
('O36.92X5', 'Atención materna por problema fetal, no especificado, segundo trimestre, feto 5', 'Sin especificar', '["problema fetal feto 5 segundo trimestre"]'),
('O36.92X9', 'Atención materna por problema fetal, no especificado, segundo trimestre, otro feto', 'Sin especificar', '["problema fetal otro feto segundo trimestre"]'),
('O36.93X0', 'Atención materna por problema fetal, no especificado, tercer trimestre, no aplicable o no especificado', 'Sin especificar', '["problema fetal tercer trimestre"]'),
('O36.93X1', 'Atención materna por problema fetal, no especificado, tercer trimestre, feto 1', 'Sin especificar', '["problema fetal feto 1 tercer trimestre"]'),
('O36.93X2', 'Atención materna por problema fetal, no especificado, tercer trimestre, feto 2', 'Sin especificar', '["problema fetal feto 2 tercer trimestre"]'),
('O36.93X3', 'Atención materna por problema fetal, no especificado, tercer trimestre, feto 3', 'Sin especificar', '["problema fetal feto 3 tercer trimestre"]'),
('O36.93X4', 'Atención materna por problema fetal, no especificado, tercer trimestre, feto 4', 'Sin especificar', '["problema fetal feto 4 tercer trimestre"]'),
('O36.93X5', 'Atención materna por problema fetal, no especificado, tercer trimestre, feto 5', 'Sin especificar', '["problema fetal feto 5 tercer trimestre"]'),
('O36.93X9', 'Atención materna por problema fetal, no especificado, tercer trimestre, otro feto', 'Sin especificar', '["problema fetal otro feto tercer trimestre"]');
