INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('E31.0', 'Insuficiencia poliglandular autoinmune', 'Sin especificar', '["ataque a las glándulas", "enfermedad autoinmune endocrina", "fallo de glándulas", "desequilibrio hormonal autoinmune", "tiroides y páncreas fallando", "síndrome poliglandular", "fallo multiorgánico endocrino", "ataque de defensas a las hormonas", "problemas hormonales múltiples", "cuerpo atacando sus glándulas", "insuficiencia de glándulas", "autoanticuerpos endocrinos", "fallo endocrino autoinmune", "problemas de glándulas en cadena", "desajuste glandular severo"]'),
('E31.1', 'Hiperfunción poliglandular', 'Sin especificar', '["glándulas hiperactivas", "exceso de hormonas", "hiperactividad glandular", "hormonas disparadas", "hiperfunción de glándulas", "glándulas trabajando de más", "sobreproducción hormonal", "aceleración endocrina", "glándulas locas", "metabolismo acelerado por glándulas", "exceso de secreción glandular", "hiperactividad endocrina múltiple", "sobrecarga hormonal", "exceso de actividad en glándulas", "hiperestimulación glandular"]'),
('E31.20', 'Síndrome de neoplasia endocrina múltiple [NEM] [MEN], no especificado', 'Sin especificar', '["tumores en glándulas", "cáncer endocrino múltiple", "MEN", "NEM", "nódulos en glándulas", "neoplasia múltiple", "tumores hormonales", "crecimiento en varias glándulas", "síndrome endocrino tumoral", "bolitas en las glándulas", "alteración endocrina hereditaria", "adenomas múltiples", "neoplasia endocrina", "tumores glandulares múltiples", "problema de glándulas y tumores"]'),
('E31.21', 'Neoplasia endocrina múltiple [NEM] [MEN] tipo I', 'Sin especificar', '["MEN tipo 1", "NEM 1", "síndrome de Wermer", "tumores en páncreas y tiroides", "neoplasia endocrina tipo 1", "adenomatosis endocrina múltiple", "tumores múltiples endocrinos", "hiperparatiroidismo y tumores", "problema hormonal heredado", "neoplasia tipo uno", "nódulos endocrinos", "tumores neuroendocrinos múltiples", "adenomas múltiples", "genética y glándulas", "cáncer endocrino tipo 1"]'),
('E31.22', 'Neoplasia endocrina múltiple [NEM] [MEN] tipo II A', 'Sin especificar', '["MEN 2A", "NEM 2A", "síndrome de Sipple", "cáncer de tiroides y glándulas", "neoplasia endocrina tipo 2A", "feocromocitoma y tiroides", "tumores endocrinos tipo 2A", "neoplasia familiar endocrina", "tumores en glándulas suprarrenales", "carcinoma medular de tiroides", "problemas glandulares hereditarios", "men tipo dos a", "hiperplasia glandular múltiple", "tumoración endocrina hereditaria", "mutación endocrina múltiple"]'),
('E31.23', 'Neoplasia endocrina múltiple [NEM] [MEN] tipo II B', 'Sin especificar', '["MEN 2B", "NEM 2B", "neoplasia endocrina múltiple 2B", "tumores endocrinos agresivos", "síndrome de neoplasia tipo 2B", "carcinoma medular tiroideo tipo 2B", "alteración hormonal múltiple", "feocromocitoma tipo 2B", "neuromas y tumores endocrinos", "men tipo dos b", "genética de glándulas", "tumores múltiples graves", "neoplasia endocrina hereditaria", "problemas de secreción hormonal", "cáncer tiroideo familiar"]'),
('E31.8', 'Otros tipos de disfunción poliglandular', 'Sin especificar', '["otros problemas de glándulas", "fallo hormonal múltiple", "desorden de varias glándulas", "problemas endocrinos variados", "desequilibrio de hormonas", "glándulas que no funcionan bien", "falla glandular mixta", "dificultad endocrina", "problemas en el sistema endocrino", "desajuste multiorgánico", "disfunción de glándulas varias", "problemas metabólicos y glandulares", "fallo en cadena endocrina", "desregulación hormonal", "caos glandular"]'),
('E31.9', 'Disfunción poliglandular, no especificada', 'Sin especificar', '["problema de glándulas no identificado", "falla glandular inespecífica", "desequilibrio hormonal", "fallo del sistema endocrino", "hormonas locas", "problemas con las hormonas", "glándulas fallando", "disfunción endocrina", "desorden glandular", "problema endocrino raro", "desajuste hormonal", "falla en el sistema de glándulas", "desequilibrio endocrino", "problemas de tiroides y otras glándulas", "sin diagnóstico endocrino claro"]');
