INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D33.0', 'Neoplasia benigna de cerebro, supratentorial', 'Sin especificar', '["tumor en la cabeza", "bolita en el cerebro", "masa cerebral", "bulto en el coco", "tumor benigno supratentorial", "crecimiento en el cerebro", "nódulo cerebral", "dolor de cabeza constante", "mareos", "problemas de visión", "crisis convulsivas", "tumor no cancerígeno", "masa en la parte superior del cerebro", "tumor de encéfalo", "cefalea persistente"]'),
('D33.1', 'Neoplasia benigna de cerebro, infratentorial', 'Sin especificar', '["tumor en la base del cráneo", "tumor cerebeloso", "masa en el tronco encefálico", "tumor de fosa posterior", "problemas de equilibrio", "inestabilidad al caminar", "mareo constante", "vértigo", "bulto benigno cerebral", "tumor no maligno infratentorial", "problemas de coordinación", "náuseas matutinas", "vómitos frecuentes", "tumor en la nuca", "masa infratentorial"]'),
('D33.2', 'Neoplasia benigna de cerebro, no especificada', 'Sin especificar', '["tumor cerebral benigno", "bulto en el cerebro", "masa intracraneal", "tumor en la cabeza", "bolita en la cabeza", "tumor no maligno", "crecimiento anormal en cerebro", "lesión ocupante de espacio", "diagnóstico de tumor cerebral", "quiste o tumor cerebral", "masa en la testa", "neoplasia en el cerebro", "tumor sin especificar", "bulto en el mate", "problemas neurológicos"]'),
('D33.3', 'Neoplasia benigna de nervios craneales', 'Sin especificar', '["tumor en el nervio", "neuroma benigno", "tumor en el nervio auditivo", "schwannoma", "bulto en la cara", "problemas faciales por tumor", "parálisis facial benigna", "pérdida de audición progresiva", "tumor en nervio craneal", "masa nerviosa benigna", "dolor facial", "hormigueo en la cara", "tumor del nervio vestibular", "neoplasia de nervios", "bulto en la cabeza por nervios"]'),
('D33.4', 'Neoplasia benigna de médula espinal', 'Sin especificar', '["tumor en la espalda", "masa en la columna", "bulto en la médula", "tumor espinal benigno", "dolor de espalda constante", "adormecimiento de piernas", "debilidad en brazos o piernas", "tumor medular no cancerígeno", "bolita en la columna", "problemas de movilidad", "hormigueo en extremidades", "tumor benigno en la columna vertebral", "neoplasia espinal", "masa en la médula", "dolor en la columna"]'),
('D33.7', 'Neoplasia benigna de otras localizaciones especificadas de sistema nervioso central', 'Sin especificar', '["tumor en el sistema nervioso", "masa en el SNC", "tumor en meninges", "tumor de otras zonas cerebrales", "crecimiento benigno en el sistema nervioso", "lesión en el sistema nervioso central", "tumor benigno especificado", "bulto en áreas del cerebro", "masa benigna en SNC", "neoplasia de sistema nervioso", "problemas neurológicos benignos", "tumor en tejidos del sistema nervioso", "crecimiento anormal en SNC", "afección nerviosa benigna", "tumor benigno no clasificado"]'),
('D33.9', 'Neoplasia benigna de sistema nervioso central, no especificada', 'Sin especificar', '["tumor del sistema nervioso", "bulto en el sistema nervioso central", "masa benigna en cerebro o médula", "problemas de nervios", "tumor benigno no especificado", "enfermedad del sistema nervioso central", "crecimiento no maligno en SNC", "neoplasia de SNC", "bulto en la médula o cerebro", "masa en el sistema nervioso", "lesión benigna en SNC", "tumor de origen nervioso", "dolor neurológico", "afección en el sistema nervioso", "tumor cerebral o espinal sin definir"]');
