INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D44.0', 'Neoplasia de comportamiento incierto de glándula tiroides', 'Sin especificar', '["bocio", "bolita en el cuello", "nódulo tiroideo", "tumor tiroides", "problemas de tiroides", "tiroides inflamada", "crecimiento en la garganta", "bulto en el cuello", "hipertiroidismo", "hipotiroidismo", "quiste tiroideo", "tumoración tiroidea", "anormalidad en tiroides", "bulto al tragar", "hiperplasia tiroidea"]'),
('D44.10', 'Neoplasia de comportamiento incierto de glándula suprarrenal no especificada', 'Sin especificar', '["tumor suprarrenal", "bulto en glándula adrenal", "problema de adrenales", "nódulo adrenal", "tumor en el riñón", "crecimiento suprarrenal", "masa en la suprarrenal", "afección de glándulas adrenales", "tumor endocrino", "hiperplasia suprarrenal", "dolor de costado", "problemas hormonales", "incidentaloma adrenal", "tumor abdominal", "masa abdominal"]'),
('D44.11', 'Neoplasia de comportamiento incierto de glándula suprarrenal derecha', 'Sin especificar', '["tumor adrenal derecho", "bulto en suprarrenal derecha", "masa derecha del riñón", "adenoma suprarrenal derecho", "nódulo en adrenal derecha", "crecimiento lado derecho", "problema adrenal derecho", "tumoración derecha", "dolor lado derecho", "masa en flanco derecho", "anormalidad adrenal derecha", "quiste suprarrenal derecho", "tumor renal derecho", "patología suprarrenal derecha"]'),
('D44.12', 'Neoplasia de comportamiento incierto de glándula suprarrenal izquierda', 'Sin especificar', '["tumor adrenal izquierdo", "bulto en suprarrenal izquierda", "masa izquierda del riñón", "adenoma suprarrenal izquierdo", "nódulo en adrenal izquierda", "crecimiento lado izquierdo", "problema adrenal izquierdo", "tumoración izquierda", "dolor lado izquierdo", "masa en flanco izquierdo", "anormalidad adrenal izquierda", "quiste suprarrenal izquierdo", "tumor renal izquierdo", "patología suprarrenal izquierda"]'),
('D44.2', 'Neoplasia de comportamiento incierto de glándula paratiroides', 'Sin especificar', '["adenoma paratiroideo", "problema de paratiroides", "calcio alto en sangre", "tumor de paratiroides", "hiperparatiroidismo", "nódulo paratiroideo", "hipercalcemia", "bulto en el cuello", "glándulas del calcio", "masa paratiroidea", "problemas de huesos", "cálculos renales", "crecimiento paratiroideo", "tumor endocrino cuello", "anormalidad paratiroidea"]'),
('D44.3', 'Neoplasia de comportamiento incierto de hipófisis', 'Sin especificar', '["tumor hipofisario", "adenoma de hipófisis", "tumor en la cabeza", "problemas de hormonas", "tumor en la silla turca", "tumor de la pituitaria", "dolor de cabeza persistente", "problemas de visión", "crecimiento en el cerebro", "masa en hipófisis", "problemas de crecimiento", "prolactinoma", "tumor cerebral benigno", "anormalidad pituitaria", "hormonas descontroladas"]'),
('D44.4', 'Neoplasia de comportamiento incierto de conducto craneofaríngeo', 'Sin especificar', '["craneofaringioma", "tumor cerebral", "tumor base del cráneo", "problemas de visión", "masa craneofaríngea", "tumor en el cerebro", "dolor de cabeza intenso", "problemas hormonales", "quiste en la cabeza", "tumor en niños", "anormalidad cerebral", "tumor de la silla turca", "problemas hipofisarios", "crecimiento cerca del cerebro", "masa en base del cráneo"]'),
('D44.5', 'Neoplasia de comportamiento incierto de glándula pineal', 'Sin especificar', '["tumor de la glándula pineal", "tumor cerebral", "problemas del sueño", "masa pineal", "crecimiento en el centro del cerebro", "dolor de cabeza", "presión intracraneal", "anormalidad de la pineal", "quiste pineal", "problemas de melatonina", "tumor en la cabeza", "masa en el cerebro", "problemas de equilibrio", "náuseas por tumor", "tumor pineal"]'),
('D44.6', 'Neoplasia de comportamiento incierto de cuerpo carotídeo', 'Sin especificar', '["tumor del cuerpo carotídeo", "paraganglioma carotídeo", "bolita en el cuello", "bulto cerca de la carótida", "masa en el cuello", "tumor en la arteria", "nódulo en el cuello", "tumor cervical", "crecimiento en la garganta", "afección vascular cuello", "tumor pulsátil", "bulto que late", "anormalidad carotídea", "masa lateral cuello", "tumor paraganglionar"]'),
('D44.7', 'Neoplasia de comportamiento incierto de cuerpo aórtico y otros paraganglios', 'Sin especificar', '["paraganglioma", "tumor paraganglionar", "tumor en el tórax", "masa en la aorta", "tumor torácico", "bulto en el pecho", "problemas endocrinos", "tumor neuroendocrino", "masa en paraganglios", "anormalidad en el tórax", "tumor aórtico", "crecimiento retroperitoneal", "problemas de presión arterial", "sudoración excesiva", "palpitaciones"]'),
('D44.9', 'Neoplasia de comportamiento incierto de glándula endocrina no especificada', 'Sin especificar', '["tumor endocrino", "problemas de hormonas", "bulto en glándula", "masa endocrina", "tumor no identificado", "anormalidad en glándula", "enfermedad de las glándulas", "nódulo endocrino", "descontrol hormonal", "problemas metabólicos", "tumor de origen desconocido", "masa glandular", "crecimiento hormonal", "afección endocrina", "quiste en glándula"]');
