INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P71.0', 'Hipocalcemia neonatal por leche de vaca', 'Sin especificar', '["falta de calcio bebé", "calcio bajo recién nacido", "leche de vaca bebé convulsiones", "hipocalcemia láctea", "calcio en sangre bajo", "tetania del lactante", "bebé con espasmos por leche", "calcio bajo por fórmula", "desequilibrio de minerales recién nacido", "deficiencia de calcio neonatal", "temblor recién nacido por leche", "exceso de fosfato leche vaca", "problemas de calcio en bebés", "calcio bajo alimentación artificial", "tetania hipocalcémica"]'),
('P71.1', 'Otros tipos de hipocalcemia neonatal', 'Sin especificar', '["calcio bajo en el recién nacido", "hipocalcemia del neonato", "niveles de calcio bajitos bebé", "calcio en sangre insuficiente", "falta de calcio al nacer", "temblores por falta de calcio", "espasmos neonatales por calcio", "hipocalcemia tardía neonatal", "hipocalcemia temprana", "calcio sérico bajo bebé", "convulsiones por calcio bajo", "irritabilidad neonatal calcio", "deficiencia mineral recién nacido", "alteración niveles calcio bebé", "problemas óseos neonatales iniciales"]'),
('P71.2', 'Hipomagnesemia neonatal', 'Sin especificar', '["magnesio bajo bebé", "falta de magnesio recién nacido", "hipomagnesemia del recién nacido", "magnesio en sangre insuficiente", "niveles bajos de magnesio", "temblores neonatales magnesio", "convulsiones por falta de magnesio", "deficiencia de magnesio neonatal", "espasmos por poco magnesio", "hipomagnesemia e hipocalcemia", "trastorno electrolítico bebé", "problemas de minerales en neonato", "magnesio sérico bajo", "tetania por falta de magnesio", "bebés con poco magnesio"]'),
('P71.3', 'Tetania neonatal sin déficit de calcio ni magnesio', 'Sin especificar', '["tetania del recién nacido", "espasmos musculares neonatales", "convulsiones bebé sin causa mineral", "rigidez muscular recién nacido", "tetania idiopática neonatal", "espasmo carpopedal bebé", "contracciones musculares bebé", "tetania sin hipocalcemia", "tetania sin hipomagnesemia", "espasmos involuntarios recién nacido", "calambres intensos bebé", "crisis convulsiva neonatal", "rigidez en manos y pies bebé", "temblor persistente recién nacido", "distonía neonatal transitoria"]'),
('P71.4', 'Hipoparatiroidismo neonatal transitorio', 'Sin especificar', '["tiroides bebé calcio bajo", "problema de paratiroides recién nacido", "hipoparatiroidismo temporal", "calcio bajo por tiroides bebé", "falta de hormona paratiroidea", "problema glándulas paratiroides bebé", "hipocalcemia por paratiroides", "deficiencia paratiroidea transitoria", "regulación calcio recién nacido", "glándulas paratiroides inmaduras", "desequilibrio hormonal calcio bebé", "disfunción paratiroidea neonatal", "calcio y fósforo desequilibrado", "hipocalcemia neonatal transitoria", "problemas endocrinos recién nacido"]'),
('P71.8', 'Otros trastornos neonatales transitorios del metabolismo del calcio y del magnesio', 'Sin especificar', '["problemas de minerales recién nacido", "desorden electrolitos neonatal", "metabolismo calcio y magnesio bebé", "calcio y magnesio fuera de rango", "desequilibrio mineral temporal", "problemas de electrolitos bebé", "alteración fósforo recién nacido", "metabolismo mineral inmaduro", "hipocalcemia magnesemia neonatal", "trastornos electrolíticos transitorios", "calcio alto bajo recién nacido", "magnesio alto bajo bebé", "desequilibrio fosfocálcico neonatal", "dificultad regulación minerales bebé", "problemas metabólicos pasajeros"]'),
('P71.9', 'Trastorno neonatal transitorio del metabolismo del calcio y del magnesio, no especificado', 'Sin especificar', '["problemas de calcio y magnesio no clasificados", "desequilibrio electrolítico bebé", "alteración mineral recién nacido", "problemas metabólicos calcio magnesio", "trastorno de minerales al nacer", "inestabilidad minerales bebé", "calcio y magnesio anormal", "problemas electrolitos no definidos", "trastorno metabólico transitorio bebé", "desajuste mineral recién nacido", "calcio magnesio inestable", "problemas sangre recién nacido", "desequilibrio mineral sin especificar", "crisis mineral neonatal", "problemas de electrolitos neonato"]');
