INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Q54.0', 'Hipospadias del glande', 'Sin especificar', '["pene malformado", "orificio urinario desviado", "meato uretral desplazado", "pipi chueca", "malformación genital bebé", "orificio en la cabeza del pene", "chorrito desviado", "pene con orificio abajo", "anomalía uretral distal", "hipospadias glandular", "orificio fuera de lugar", "defecto al nacer pene", "pene curvo", "pipí por debajo del glande"]'),
('Q54.1', 'Hipospadias peneano', 'Sin especificar', '["orificio uretral en el cuerpo del pene", "meato uretral bajo", "malformación peneana", "uretra corta", "problemas al orinar niño", "pipí por el cuerpo del pene", "pene deforme", "defecto congénito uretral", "hipospadias del cuerpo peneano", "chorrito hacia abajo", "orificio en el tronco del pene", "anomalía peneana", "cirugía de uretra bebé", "pipi mal ubicada"]'),
('Q54.2', 'Hipospadias penescrotal', 'Sin especificar', '["orificio entre pene y escroto", "hipospadias unión escrotal", "malformación genital severa", "orificio cerca de los huevos", "pipi saliendo entre el pene y las bolas", "defecto uretral penescrotal", "anomalía genital masculina", "uretra en la base del pene", "genitales ambiguos", "orificio en la raíz del pene", "malformación de nacimiento", "problema de uretra grave", "pene enterrado", "chorrito en la base"]'),
('Q54.3', 'Hipospadias perineal', 'Sin especificar', '["hipospadias grave", "orificio urinario en el perineo", "malformación urogenital severa", "pipi desde atrás de los testículos", "orificio entre el ano y el escroto", "uretra perineal", "defecto genital complejo", "problemas para orinar de pie", "genitales mal formados", "hipospadias tipo perineal", "anomalía congénita uretra", "pene muy pequeño y desviado", "malformación de uretra", "urgencia urológica bebé"]'),
('Q54.4', 'Encordamiento congénito del pene', 'Sin especificar', '["pene curvado hacia abajo", "cuerda en el pene", "pene con curvatura congénita", "chordee", "pene torcido al nacer", "pene arqueado", "dificultad para erección", "deformidad peneana", "pene que se dobla", "fibrosis congénita pene", "curvatura peniana infantil", "pene encorvado", "problemas de desarrollo genital", "pene en gancho"]'),
('Q54.8', 'Otras hipospadias', 'Sin especificar', '["variantes de hipospadias", "malformación rara de uretra", "defecto uretral atípico", "problemas al orinar congénitos", "anomalías del pene no especificadas", "uretra mal ubicada", "complicaciones de hipospadias", "trastornos del desarrollo genital", "meato uretral ectópico", "malformaciones peneanas", "pipi desviada", "defecto de nacimiento uretra", "anomalía de nacimiento genital"]'),
('Q54.9', 'Hipospadias, no especificado', 'Sin especificar', '["pipi mal ubicada", "problema al orinar congénito", "orificio del pene en otro lado", "malformación en el pito", "defecto de nacimiento del pene", "niño con hipospadias", "uretra mal colocada", "anomalía al nacer", "pene con orificio anormal", "meato uretral fuera de lugar", "problema urológico del bebé", "pene de niño con malformación", "defecto congénito genital", "orificio urinario mal puesto"]');
