INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P70.0', 'Síndrome del hijo de madre con diabetes gestacional', 'Sin especificar', '["bebé de mamá diabética", "azúcar alta en el embarazo", "bebé grande", "macrosomía fetal", "riesgo metabólico recién nacido", "hiperinsulinismo neonatal", "hijo de diabética", "azúcar en la sangre del bebé", "problemas de azúcar al nacer", "bebé gordito al nacer", "diabetes en el embarazo", "complicaciones del embarazo", "control glucémico gestacional", "bebé con sobrepeso al nacer"]'),
('P70.1', 'Síndrome del recién nacido hijo de madre diabética', 'Sin especificar', '["recién nacido de madre diabética", "bebé con hipoglucemia", "bebé con azúcar baja", "problemas metabólicos del bebé", "hijo de madre con azúcar", "recién nacido con descontrol glucémico", "bebé macrosómico", "bebé con insulina alta", "hiperinsulinemia neonatal", "asfixia neonatal", "ictericia neonatal", "bebé edematizado", "bebé hinchado", "complicaciones al nacer por diabetes"]'),
('P70.2', 'Diabetes mellitus neonatal', 'Sin especificar', '["diabetes de bebé", "diabetes en neonatos", "azúcar alta en recién nacidos", "diabetes congénita", "hiperglucemia del recién nacido", "bebé con diabetes", "diabetes tipo 1 neonatal", "diabetes transitoria", "diabetes permanente", "fallo pancreático neonatal", "problema de páncreas del bebé", "poliuria neonatal", "deshidratación en recién nacidos", "niño nacido diabético"]'),
('P70.3', 'Hipoglucemia neonatal iatrogénica', 'Sin especificar', '["azúcar baja por medicamentos", "hipoglucemia inducida", "bajón de azúcar médico", "error de dosis insulina bebé", "efecto secundario médico", "bajo nivel de glucosa en sangre", "temblores en recién nacido", "sudoración fría bebé", "irritabilidad neonatal", "hipoglucemia hospitalaria", "mal manejo clínico", "crisis hipoglucémica", "letargo en recién nacido", "convulsiones por falta de azúcar"]'),
('P70.4', 'Otros tipos de hipoglucemia neonatal', 'Sin especificar', '["azúcar baja en el recién nacido", "hipoglucemia del bebé", "bajón de glucosa", "ataque de hipoglucemia", "bebé pálido", "bebé que no se despierta", "bebé con frío", "desmayo del bebé", "hipoglucemia hiperinsulinémica", "deficiencia de glucosa", "debilidad neonatal", "falta de azúcar al nacer", "problemas de alimentación del bebé", "temblor de barbilla"]'),
('P70.8', 'Otros trastornos neonatales transitorios del metabolismo de los hidratos de carbono', 'Sin especificar', '["problemas de azúcar bebé", "desorden metabólico transitorio", "metabolismo del bebé", "trastorno del azúcar en sangre", "hiperglucemia transitoria", "problemas de carbohidratos", "desequilibrio metabólico", "anomalía glucémica neonatal", "adaptación metabólica al nacer", "dificultad para procesar azúcares", "bebé con glucosa inestable", "trastorno metabólico temporal", "falla transitoria páncreas"]'),
('P70.9', 'Trastorno neonatal transitorio del metabolismo de los hidratos de carbono, no especificado', 'Sin especificar', '["problema metabólico del recién nacido", "fallo de azúcar no especificado", "metabolismo alterado bebé", "indefinido metabólico neonatal", "desorden transitorio desconocido", "inestabilidad glucémica", "bebé con azúcar no controlada", "enfermedad metabólica del recién nacido", "problema no claro en recién nacido", "alteración bioquímica neonatal", "trastorno metabólico agudo", "incertidumbre metabólica", "dificultad metabólica al nacer"]');
