INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z84.0', 'Historia familiar de enfermedades de piel y del tejido subcutáneo', 'Sin especificar', '["antecedentes de piel", "herencia dermatológica", "problemas de la piel en la familia", "eccema hereditario", "psoriasis familiar", "manchas en la piel genéticas", "alergias cutáneas hereditarias", "herencia de dermatitis", "piel sensible heredada", "lunares peligrosos familia", "cáncer de piel antecedentes", "historial de ronchas familiares", "antecedentes de sarpullido", "genética de la piel", "afecciones cutáneas heredadas"]'),
('Z84.1', 'Historia familiar de trastornos del riñón y del uréter', 'Sin especificar', '["problemas de riñón hereditarios", "antecedentes de cálculos renales", "piedras en el riñón familia", "herencia de insuficiencia renal", "historial familiar de nefritis", "enfermedad poliquística renal", "familia con fallas renales", "problemas urinarios hereditarios", "antecedentes de mal de orín familiar", "piedras en la vejiga herencia", "herencia de cólico renal", "insuficiencia de riñones antecedentes", "fallo renal en la familia", "problemas en las vías urinarias hereditarios"]'),
('Z84.2', 'Historia familiar de otras enfermedades del aparato genitourinario', 'Sin especificar', '["herencia de problemas genitales", "antecedentes de enfermedades de transmisión familiar", "historial de problemas urinarios", "problemas reproductivos familiares", "genética de enfermedades genitales", "antecedentes de infecciones urinarias recurrentes", "herencia de vejiga caída", "problemas prostáticos hereditarios", "historia familiar de quistes genitales", "incontinencia familiar", "anomalías genitourinarias heredadas", "antecedentes de problemas de útero hereditarios", "herencia de malformaciones genitourinarias"]'),
('Z84.3', 'Historia familiar de consanguinidad', 'Sin especificar', '["familia entre primos", "casarse entre parientes", "matrimonio entre familiares", "consanguíneos", "hijos de primos", "endogamia", "parentesco cercano en la pareja", "padres primos", "unión de parientes cercanos", "herencia por consanguinidad", "riesgos genéticos por parentesco", "matrimonio consanguíneo", "familia emparentada"]'),
('Z84.81', 'Historia familiar de portador de enfermedad genética', 'Sin especificar', '["portador de genes", "enfermedad hereditaria en la familia", "genética familiar", "antecedentes de enfermedades raras", "gen defectuoso familiar", "historial de carga genética", "portador de enfermedades", "herencia genética", "mutación genética familiar", "genealogía de enfermedades", "transmisión de enfermedades familia", "genética heredada", "antecedente de síndrome genético", "portador de alteraciones cromosómicas"]'),
('Z84.82', 'Historia familiar de síndrome de muerte súbita del lactante (SMSL)', 'Sin especificar', '["muerte de cuna familiar", "muerte súbita de bebé", "antecedente de muerte en la cuna", "muerte inexplicable del lactante", "SMSL familiar", "bebés fallecidos sin causa", "historial de muerte súbita", "herencia de muerte de cuna", "riesgo de muerte súbita bebé", "bebé que murió durmiendo familiar", "antecedente de fallecimiento infantil", "síndrome de la muerte súbita", "fallecimiento repentino de bebé"]'),
('Z84.89', 'Historia familiar de otra afección especificada', 'Sin especificar', '["otros antecedentes familiares", "historia de enfermedades raras familiares", "antecedentes médicos de la familia", "herencias patológicas", "historial de problemas de salud familiares", "enfermedades que corren en la familia", "antecedentes de enfermedades crónicas", "carga genética familiar", "historia de padecimientos heredados", "familia con antecedentes médicos", "genealogía de salud", "rastreo de enfermedades familiares", "padecimientos genéticos familiares"]');
