INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('X10.0XXA', 'Contacto con bebidas calientes, contacto inicial', 'Sin especificar', '["quemadura con café", "quemada con té", "bebió algo hirviendo", "quemadura de lengua", "quemadura de paladar", "bebida ardiendo", "escaldadura con café", "quemadura en boca", "tomar algo muy caliente", "quemadura reciente con líquido", "quemazón de garganta", "líquido hirviendo", "café muy caliente", "té quemando", "quemadura externa por bebida"]'),
('X10.0XXD', 'Contacto con bebidas calientes, contacto sucesivo', 'Sin especificar', '["seguimiento de quemadura", "cura de quemadura", "quemadura en proceso", "revisión de quemada", "tratamiento de escaldadura", "quemadura que no sana", "curación de herida por calor", "lesión por bebida caliente", "cuidado de quemadura recurrente", "revisión médica por quemazón", "control de quemadura", "quemadura segunda visita", "herida por café en proceso", "dolor persistente por quemadura"]'),
('X10.0XXS', 'Contacto con bebidas calientes, secuela', 'Sin especificar', '["cicatriz por quemadura", "marca de quemada", "mancha por quemadura", "secuela de quemadura", "tejido cicatricial", "problema crónico por quemadura", "queloides por quemadura", "efectos a largo plazo de quemadura", "fibrosis por quemadura", "quemadura antigua", "dolor residual de quemadura", "rehabilitación tras quemadura", "cicatriz queloide en boca", "daño tisular persistente"]'),
('X10.1XXA', 'Contacto con alimentos calientes, contacto inicial', 'Sin especificar', '["quemada con comida", "quemarse con sopa", "quemadura con alimento", "quemazón por comida caliente", "quemarse el paladar", "quemadura al comer", "comida ardiendo", "escaldadura por alimento", "quemadura bucal por comida", "quemadura al ingerir", "quemadura con puré caliente", "quemarse la lengua con comida", "alimento hirviendo", "quemadura inmediata por comida"]'),
('X10.1XXD', 'Contacto con alimentos calientes, contacto sucesivo', 'Sin especificar', '["seguimiento quemadura comida", "curación herida bucal", "revisión quemadura paladar", "tratamiento tras quemadura", "control de lesión oral", "quemadura bucal infectada", "cura de quemazón por comida", "evolución de quemadura", "visita de control quemadura", "quemadura que sigue doliendo", "revisión de lesión por comida", "cuidado post-quemadura"]'),
('X10.1XXS', 'Contacto con alimentos calientes, secuela', 'Sin especificar', '["secuela por quemadura", "cicatriz en la lengua", "marca de quemadura", "daño permanente en boca", "cicatriz paladar", "fibrosis oral", "problemas de sensibilidad oral", "quemadura antigua en boca", "tejido con marca", "queloides bucales", "lesión crónica por quemadura", "efectos secundarios de quemadura"]'),
('X10.2XXA', 'Contacto con grasas y aceites de cocina, contacto inicial', 'Sin especificar', '["quemadura con aceite", "salpicadura de aceite", "quemada con manteca", "quemadura por fritura", "aceite hirviendo", "quemada cocinando", "quemadura con grasa caliente", "salpicón de aceite", "quemada con sartén", "aceite saltando", "quemadura grave por aceite", "quemadura reciente con grasa", "accidente con aceite", "quemazón con aceite"]'),
('X10.2XXD', 'Contacto con grasas y aceites de cocina, contacto sucesivo', 'Sin especificar', '["cura de quemadura aceite", "revisión quemadura grasa", "curación quemada aceite", "tratamiento herida por aceite", "seguimiento quemadura piel", "quemadura infectada por aceite", "control de quemadura grave", "evolución de quemada por grasa", "revisión de piel quemada", "curación de segunda etapa", "cuidado de ampolla por aceite", "seguimiento médico quemadura"]'),
('X10.2XXS', 'Contacto con grasas y aceites de cocina, secuela', 'Sin especificar', '["cicatriz por aceite", "marca de quemadura aceite", "quemadura queloide", "secuela de quemadura grasa", "fibrosis cutánea", "cicatriz retráctil", "mancha por quemadura", "daño profundo por aceite", "quemadura mal curada", "secuela estética por quemadura", "tejido cicatrizal por aceite", "problema crónico de piel", "cicatriz permanente"]');
