INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('R23.0', 'Cianosis', 'Sin especificar', '["uñas moradas", "labios azules", "piel morada", "falta de oxigeno", "dedos morados", "se me puso azul", "coloracion azulada", "cianosis", "hipoxia", "piel cianotica", "labios morados", "dedos de color oscuro", "piel amoratada", "mala circulacion", "asfixia leve", "dedos frios y morados", "coloracion violacea"]'),
('R23.1', 'Palidez', 'Sin especificar', '["estar palido", "cara blanca", "descolorido", "anemia", "baja de tension", "bajon de presion", "estar descolorido", "cara de susto", "palidez extrema", "sin color en la cara", "anemico", "blanco como el papel", "se me fue el color", "sentirse desmayado", "mareo", "baja de hemoglobina", "blanquecino"]'),
('R23.2', 'Rubor', 'Sin especificar', '["cara roja", "bochorno", "sonrojo", "estar colorado", "ponerse rojo", "calorones", "sofoco", "cara encendida", "me arde la cara", "me puse tomate", "chapetas", "sofocacion", "chapa", "me subio la sangre a la cabeza", "bochorno repentino", "piel roja"]'),
('R23.3', 'Equimosis espontánea', 'Sin especificar', '["moretones sin causa", "manchas moradas", "cardenales", "hematomas espontaneos", "se me hacen morados solos", "moretones de la nada", "equimosis", "manchas en la piel", "sangrado debajo de la piel", "manchas de sangre", "moretones faciles", "pecas de sangre", "manchas violaceas", "problemas de coagulacion", "manchas de color sangre", "morados raros"]'),
('R23.4', 'Alteraciones de la textura de la piel', 'Sin especificar', '["piel rugosa", "piel escamosa", "piel seca", "piel con textura rara", "aspereza", "piel de lija", "piel acartonada", "piel dura", "piel engrosada", "dermatitis", "piel con bultos", "piel descamada", "piel con parches", "piel cuarteada", "piel rasposa", "textura de la piel", "piel con relieve"]'),
('R23.8', 'Otras alteraciones cutáneas', 'Sin especificar', '["ronchas", "manchas en la piel", "erupciones", "brotes", "granitos raros", "picazon", "irritacion", "piel marcada", "cambios en la piel", "lesiones en la piel", "manchas raras", "erupcion cutanea", "alergia en la piel", "piel sensible", "problemas de la piel", "parches en la piel"]'),
('R23.9', 'Alteraciones cutáneas no especificadas', 'Sin especificar', '["algo en la piel", "problema en la piel", "cosa rara en la piel", "marca en la piel", "sarpullido", "afeccion cutanea", "cambio en la dermis", "mancha rara", "roncha rara", "no se que es esto en la piel", "problema dermatologico", "alteracion de la piel", "señal en la piel", "lesion dermatologica"]');
