INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P13.0', 'Fractura de cráneo debida a traumatismo del nacimiento', 'Sin especificar', '["fractura craneal recién nacido", "hueso de la cabeza roto parto", "golpe en la cabeza al nacer", "trauma de cráneo neonato", "fisura de cráneo bebé", "cráneo hundido parto", "lesión ósea cabeza bebé", "fractura de bóveda craneal", "traumatismo obstétrico cabeza", "parto difícil fractura", "bebé con chichón duro", "lesión al nacer cráneo", "fractura de fontanela", "hueso de la mollera roto", "trauma por fórceps cabeza"]'),
('P13.1', 'Otros traumatismos de cráneo al nacimiento', 'Sin especificar', '["lesión cabeza bebé parto", "golpe al nacer", "hematoma craneal recién nacido", "traumatismo obstétrico cabeza", "daño cerebral por parto", "lesión en la mollera", "trauma neonatal", "chichón del bebé al nacer", "inflamación cabeza parto", "trauma por ventosa", "lesión cráneo-facial parto", "daño tejido blando cabeza", "parto traumático", "equimosis cabeza bebé", "lesión del cuero cabelludo parto"]'),
('P13.2', 'Traumatismo del nacimiento de fémur', 'Sin especificar', '["fractura de fémur bebé", "hueso de la pierna roto al nacer", "trauma de muslo parto", "fractura de pierna recién nacido", "lesión ósea parto", "fémur roto parto difícil", "fractura diafisaria fémur bebé", "daño en la patita del bebé", "hueso del muslo lastimado", "traumatismo óseo neonatal", "fractura obstétrica pierna", "lesión por tracción en parto", "fémur quebrado al nacer", "parto complicado pierna", "problema de hueso de pierna recién nacido"]'),
('P13.3', 'Traumatismo del nacimiento de otros huesos largos', 'Sin especificar', '["fractura brazo bebé", "hueso roto brazo recién nacido", "lesión húmero parto", "trauma huesos largos neonato", "fractura de radio o cúbito", "fractura de brazo al nacer", "lesión brazo parto complicado", "hueso del miembro superior roto", "traumatismo óseo al nacer", "fractura obstétrica brazo", "daño brazo recién nacido", "fractura de tibia recién nacido", "hueso largo quebrado parto", "lesión por parto difícil brazos", "trauma esquelético bebé"]'),
('P13.4', 'Fractura de clavícula debida a traumatismo del nacimiento', 'Sin especificar', '["clavícula rota bebé", "hueso del hombro roto recién nacido", "fractura de hombro parto", "hueso del cuello roto", "clavícula quebrada al nacer", "lesión de clavícula parto", "trauma hombro bebé", "fractura obstétrica clavícula", "hueso de la clavícula saltado", "clic en el hombro bebé", "dolor al mover brazo bebé", "fractura por distocia de hombros", "lesión al nacer clavícula", "hueso de arriba del pecho roto", "clavícula de bebé lastimada"]'),
('P13.8', 'Traumatismo del nacimiento de otras partes del esqueleto', 'Sin especificar', '["lesión ósea bebé al nacer", "trauma esqueleto recién nacido", "fractura costilla parto", "lesión columna recién nacido", "hueso roto parto", "traumatismo óseo múltiple", "lesión del esqueleto neonatal", "daño al nacer huesos", "fractura de mano o pie bebé", "trauma de columna al nacer", "lesión de cadera parto", "fractura de vértebra bebé", "trauma esquelético diverso", "hueso dañado en el parto", "lesión obstétrica ósea"]'),
('P13.9', 'Traumatismo del nacimiento del esqueleto, no especificada', 'Sin especificar', '["lesión bebé parto", "daño huesos recién nacido", "problema óseo al nacer", "trauma por parto", "lesión traumática neonatal", "fractura de bebé no especificada", "traumatismo al nacer", "lesión física parto", "problema en el esqueleto bebé", "daño al nacer", "trauma médico al nacer", "lesión del recién nacido", "golpe o fractura parto", "complicación ósea al nacer", "traumatismo obstétrico general"]');
