INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D47.01', 'Mastocitosis cutánea', 'Sin especificar', '["manchas en la piel", "ronchas constantes", "picazón piel", "reacción alérgica piel", "erupciones cutáneas", "urticaria pigmentosa", "mastocitos en piel", "manchas café con leche", "picazón crónica", "problemas de dermis", "manchas que pican", "alergia dermatológica", "inflamación de la piel", "manchas rojizas", "sensibilidad cutánea", "lesiones cutáneas"]'),
('D47.02', 'Mastocitosis sistémica', 'Sin especificar', '["mastocitosis generalizada", "fallo de mastocitos", "células inmunes alteradas", "reacciones alérgicas severas", "shock anafiláctico frecuente", "dolor abdominal crónico", "fatiga extrema", "problemas de órganos internos", "mastocitos descontrolados", "enfermedad inmunológica", "síntomas sistémicos", "dolor de huesos", "pérdida de peso inexplicada", "reacción a alimentos", "problemas digestivos", "anafilaxia"]'),
('D47.09', 'Otras neoplasias de mastocitos de comportamiento incierto', 'Sin especificar', '["tumor mastocitario", "crecimiento anormal células", "neoplasia inespecífica", "masa sospechosa", "nódulos en el cuerpo", "proliferación celular", "problemas hematológicos", "tumor de comportamiento dudoso", "células malignas o benignas", "crecimiento tisular", "anomalía en sangre", "nódulos linfáticos", "descontrol celular", "enfermedad rara hematológica", "diagnóstico incierto", "tumor incierto"]'),
('D47.1', 'Enfermedad mieloproliferativa crónica', 'Sin especificar', '["sangre espesa", "exceso de células sanguíneas", "médula ósea sobreactiva", "problemas de médula", "cáncer de sangre crónico", "glóbulos altos", "plaquetas elevadas", "problemas hematológicos crónicos", "cansancio crónico por sangre", "esplenomegalia", "dolor en el bazo", "anemia crónica", "hiperplasia medular", "enfermedad de la sangre", "formación excesiva de células"]'),
('D47.2', 'Gammapatía monoclonal', 'Sin especificar', '["proteínas en sangre", "anomalía de proteínas", "mieloma en observación", "picos en electroforesis", "proteína M", "gammapatía de significado incierto", "problemas de defensas", "inmunoglobulinas alteradas", "riesgo de mieloma", "sangre alterada", "anomalía proteica", "problemas de médula ósea", "exceso de anticuerpos", "control de proteínas", "estudio hematológico"]'),
('D47.3', 'Trombocitemia esencial (hemorrágica)', 'Sin especificar', '["plaquetas altas", "exceso de plaquetas", "sangre muy espesa", "trombosis frecuentes", "riesgo de coágulos", "sangrados frecuentes", "problemas de coagulación", "plaquetas disparadas", "dolor de cabeza por plaquetas", "mareos por sangre espesa", "trombocitosis", "problemas circulatorios", "riesgo de infarto", "células sanguíneas elevadas", "espesor sanguíneo", "coágulos arteriales"]'),
('D47.4', 'Osteomielofibrosis', 'Sin especificar', '["médula ósea cicatrizada", "fibrosis medular", "bazo grande", "esplenomegalia severa", "anemia severa", "cansancio extremo", "huesos que no producen sangre", "médula fibrosa", "dolor abdominal superior", "pérdida de fuerza", "problemas de producción sanguínea", "insuficiencia medular", "células madre alteradas", "metaplasia mieloide", "anemia mieloide", "problemas hematopoyéticos"]'),
('D47.Z1', 'Trastorno linfoproliferativo postrasplante (TLPT)', 'Sin especificar', '["rechazo trasplante", "linfoma postrasplante", "proliferación linfocitaria", "problemas tras cirugía de órgano", "cáncer tras trasplante", "bajada de defensas", "linfocitos descontrolados", "infección postrasplante", "masa linfática", "complicación postrasplante", "linfoproliferación", "enfermedad inmunosupresora", "crecimiento de ganglios", "riesgo post-cirugía", "linfoma inducido"]'),
('D47.Z2', 'Enfermedad de Castleman', 'Sin especificar', '["ganglios inflamados", "tumor de ganglios linfáticos", "adenopatías gigantes", "ganglios que no bajan", "inflamación linfática crónica", "problemas del sistema inmune", "fiebre y ganglios", "masa linfática interna", "adenopatía persistente", "dolor de cuello por ganglios", "ganglios en axila", "linfadenopatía", "hiperplasia linfática", "enfermedad inflamatoria ganglios", "crecimiento de nódulos", "nódulos linfáticos agrandados"]'),
('D47.Z9', 'Otros tumores especificados de comportamiento incierto de tejido linfático, hemopoyético y relacionados', 'Sin especificar', '["masa en ganglios", "tumor de sangre incierto", "crecimiento anormal linfático", "problema en sistema linfático", "tumor dudoso", "nódulos sospechosos", "anomalía hematopoyética", "neoplasia inespecífica", "tejido linfático alterado", "tumor no clasificado", "bultos en el cuerpo", "crecimiento tisular extraño", "diagnóstico hemático incierto", "tumor linfático", "linfoma sospechado"]'),
('D47.9', 'Neoplasia de comportamiento incierto de tejido linfático, hemopoyético y relacionados, no especificada', 'Sin especificar', '["enfermedad de la sangre sin nombre", "cáncer de sangre incierto", "tumor inespecífico", "problema de médula o ganglios", "masa de origen incierto", "anomalía en sistema hemático", "diagnóstico hematológico pendiente", "crecimiento celular desconocido", "neoplasia sin clasificar", "problemas linfáticos raros", "células extrañas en sangre", "tumor de origen desconocido", "enfermedad rara de la sangre", "patología hematológica", "masa corporal indefinida"]');
