INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('M32.0', 'Lupus eritematoso sistémico, inducido por fármacos', 'Sin especificar', '["lupus por pastillas", "lupus medicamentoso", "reacción a medicamentos", "lupus inducido por drogas", "manchas por medicinas", "lupus farmacéutico", "efectos secundarios medicamentos", "enfermedad autoinmune fármacos", "erupción cutánea medicación", "dolor articular por pastillas", "lupus secundario", "problemas de piel por fármacos", "lupus iatrogénico", "autoinmunidad por medicamentos"]'),
('M32.10', 'Lupus eritematoso sistémico, afectación de órgano o sistema no especificado', 'Sin especificar', '["lupus generalizado", "enfermedad del lupus", "lupus sistémico", "dolores por lupus", "cansancio extremo lupus", "fiebre y lupus", "lupus en el cuerpo", "diagnóstico de lupus", "autoinmune sistémico", "problemas órganos lupus", "erupción en mariposa", "lupus activo", "brotes de lupus", "inflamación sistémica", "fatiga crónica lupus"]'),
('M32.11', 'Endocarditis en lupus eritematoso sistémico', 'Sin especificar', '["lupus en el corazón", "endocarditis lúpica", "infección válvulas lupus", "dolor en el pecho lupus", "inflamación del corazón lupus", "problemas cardíacos lupus", "lupus y endocarditis", "vegetaciones cardíacas lupus", "soplos cardíacos lupus", "taquicardia por lupus", "miocarditis lúpica", "daño al corazón autoinmune", "dolor torácico sistémico"]'),
('M32.12', 'Pericarditis en lupus eritematoso sistémico', 'Sin especificar', '["pericarditis por lupus", "dolor de pecho por lupus", "inflamación alrededor del corazón", "líquido en el corazón lupus", "pinchazos en el pecho lúpico", "problemas membrana corazón", "lupus cardíaco", "dolor punzante pecho autoinmune", "lupus dolor pecho", "saco cardíaco inflamado", "derrame pericárdico lúpico"]'),
('M32.13', 'Afectación de pulmón en lupus eritematoso sistémico', 'Sin especificar', '["lupus en los pulmones", "pleuritis lúpica", "falta de aire lupus", "tos por lupus", "dolor al respirar lupus", "lupus pulmonar", "inflamación pulmones lupus", "fibrosis pulmonar lupus", "dificultad para respirar autoinmune", "líquido en pulmones lupus", "lupus y asma", "disnea lúpica"]'),
('M32.14', 'Enfermedad glomerular en lupus eritematoso sistémico', 'Sin especificar', '["nefritis lúpica", "lupus en los riñones", "problemas de riñón por lupus", "insuficiencia renal lupus", "daño renal autoinmune", "glomérulos dañados lupus", "orina con espuma lupus", "hinchazón por riñones lupus", "falla renal sistémica", "proteína en la orina lupus", "nefropatía por lupus", "enfermedad del riñón lupus"]'),
('M32.15', 'Nefropatía túbulointersticial en lupus eritematoso sistémico', 'Sin especificar', '["daño túbulos renales lupus", "nefropatía lúpica", "inflamación riñón lupus", "lupus y riñones", "problemas de filtrado renal lupus", "nefritis intersticial lúpica", "dolor lumbar lupus", "orina anormal lupus", "fallo renal lúpico", "lesión túbulo intersticial lupus", "lupus nefropatía"]'),
('M32.19', 'Afectación de otro órgano o sistema en lupus eritematoso sistémico', 'Sin especificar', '["lupus en otros órganos", "lupus multisistémico", "lupus afectación órganos", "complicaciones lupus", "lupus fuera del control", "lupus multiorgánico", "daño sistémico lúpico", "ataque del lupus a órganos", "síntomas raros de lupus", "lupus severo", "lupus visceral"]'),
('M32.8', 'Otras formas de lupus eritematoso sistémico', 'Sin especificar', '["variantes de lupus", "tipos poco comunes de lupus", "lupus atípico", "otras manifestaciones de lupus", "lupus sistémico especial", "clasificaciones de lupus", "formas raras lupus", "lupus variante", "lupus sistémico específico"]'),
('M32.9', 'Lupus eritematoso sistémico no especificado', 'Sin especificar', '["tengo lupus", "enfermedad lupus", "lupus crónico", "manchas en la cara lupus", "autoinmune sistémico", "la enfermedad de la mariposa", "lupus eritematoso", "problemas inmunológicos", "ataque de lupus", "diagnóstico lupus", "síntomas de lupus", "lupus sin especificar", "lupus no definido"]');
