INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('X39.01XA', 'Exposición al radón, contacto inicial', 'Sin especificar', '["radón", "gas radón", "radiación en casa", "intoxicación por radón", "exposición a gas radioactivo", "cáncer de pulmón por radón", "partículas radiactivas", "contaminación por radón", "aire radioactivo", "gases del subsuelo", "emanaciones del suelo", "riesgo de radón", "medición de radón", "envenenamiento por radiación", "exposición inicial a gas"]'),
('X39.01XD', 'Exposición al radón, contacto sucesivo', 'Sin especificar', '["radón persistente", "exposición prolongada a radón", "contacto continuo con radón", "seguimiento por gas radón", "radiación acumulada", "reexposición a radón", "exposición crónica a gases", "chequeo por radón", "daño por radón repetido", "riesgo radioactivo continuo", "exposición recurrente", "control de radón", "secuelas de exposición a gas", "problemas por radón constante", "inhalación de radón a largo plazo"]'),
('X39.01XS', 'Exposición al radón, secuela', 'Sin especificar', '["efectos secundarios del radón", "secuelas del gas radón", "problemas de salud por radón", "daños por radiación pasada", "complicaciones por radón", "consecuencias de inhalar radón", "patología por exposición previa", "daño pulmonar por radón", "enfermedad post-exposición", "efecto retardado de radiación", "lesiones por radón antiguo", "secuela radioactiva", "historial de exposición al radón", "efectos a largo plazo del gas"]'),
('X39.08XA', 'Exposición a otra radiación natural, contacto inicial', 'Sin especificar', '["radiación natural", "exposición a rayos cósmicos", "radiación de fondo", "radiación telúrica", "contacto con radiación ambiental", "radiación solar extrema", "exposición a radioactividad natural", "fuerzas naturales radioactivas", "radiación del ambiente", "contacto con isótopos naturales", "energía natural radioactiva", "radiación de la tierra", "exposición a radiación del entorno", "primer contacto con radiación", "riesgos radioactivos naturales"]'),
('X39.08XD', 'Exposición a otra radiación natural, contacto sucesivo', 'Sin especificar', '["radiación natural continua", "exposición repetida a radiación", "radiación ambiental recurrente", "seguimiento de radiación natural", "contacto sucesivo a rayos", "radiación de fondo constante", "exposición prolongada a radiación natural", "efectos acumulativos de radiación", "chequeo de radiación ambiental", "exposición persistente a energía natural", "radiación recurrente del entorno", "control de dosis de radiación", "exposición prolongada", "contacto crónico con radiación"]'),
('X39.08XS', 'Exposición a otra radiación natural, secuela', 'Sin especificar', '["secuelas de radiación natural", "daños por radiación ambiental", "efectos de radiación de fondo", "consecuencias de exposición radioactiva", "patología post-radiación", "problemas de salud por exposición natural", "lesiones por radiación telúrica", "efectos tardíos de la radiación", "complicaciones por radiación natural", "secuela de rayos cósmicos", "efecto residual de radioactividad", "consecuencia de contacto anterior", "problemas médicos por radiación pasada"]'),
('X39.8XXA', 'Otras exposiciones a las fuerzas de la naturaleza, contacto inicial', 'Sin especificar', '["desastre natural", "cataclismo", "fuerzas de la naturaleza", "contacto con desastre", "accidente por fuerza natural", "fenómeno meteorológico extremo", "golpe de fuerza natural", "peligro natural", "exposición a tormenta", "exposición a inundación", "contacto inicial con desastre", "impacto de la naturaleza", "emergencia natural", "fuerzas incontrolables", "riesgo de la naturaleza"]'),
('X39.8XXD', 'Otras exposiciones a las fuerzas de la naturaleza, contacto sucesivo', 'Sin especificar', '["seguimiento post-desastre", "exposición persistente a fuerzas naturales", "continuación de desastre natural", "efectos sucesivos de fenómeno natural", "contacto recurrente con desastre", "emergencia natural en curso", "secuelas de desastre", "chequeo post-evento natural", "atención tras desastre", "exposición prolongada a la naturaleza", "problemas tras catástrofe", "situación de emergencia continuada", "efecto acumulativo de desastre"]'),
('X39.8XXS', 'Otras exposiciones a las fuerzas de la naturaleza, secuela', 'Sin especificar', '["secuelas de desastre natural", "efectos a largo plazo de desastre", "consecuencias de cataclismo", "trauma por fenómeno natural", "secuelas tras inundación", "problemas post-desastre", "efectos tardíos de la naturaleza", "patología post-catástrofe", "lesiones tras fuerza natural", "complicaciones post-evento", "daños derivados de la naturaleza", "secuelas de emergencia natural", "historial de desastre natural"]');
