INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('C71.0', 'Neoplasia maligna de cerebro, excepto lóbulos y ventrículos', 'Sin especificar', '["tumor cerebral", "cáncer en la cabeza", "bolita en el cerebro", "masa cerebral", "cabeza con tumor", "neoplasia craneal", "crecimiento maligno cerebro", "lesión cerebral", "cáncer de coco", "tumor en la matadura", "masa en la choya", "cáncer en la bocha", "tumor intracraneal", "malignidad cerebral", "bulto en la cabeza"]'),
('C71.1', 'Neoplasia maligna de lóbulo frontal', 'Sin especificar', '["tumor lóbulo frontal", "cáncer frente", "tumor parte frontal cerebro", "masa frontal", "cáncer lóbulo frontal", "lesión frente cerebro", "neoplasia lóbulo frontal", "tumor zona frontal", "cáncer en la frente", "problemas cognitivos lóbulo frontal", "malignidad lóbulo frontal", "crecimiento lóbulo frontal", "tumor frontal", "masa en la frente"]'),
('C71.2', 'Neoplasia maligna de lóbulo temporal', 'Sin especificar', '["tumor lóbulo temporal", "cáncer sienes", "masa temporal cerebro", "tumor zona temporal", "cáncer lóbulo temporal", "lesión temporal", "neoplasia lóbulo temporal", "crecimiento temporal", "malignidad temporal", "dolor en la sien tumor", "tumor lateral cabeza", "masa al costado del cerebro", "cáncer lóbulo temporal", "tumor auditivo-temporal"]'),
('C71.3', 'Neoplasia maligna de lóbulo parietal', 'Sin especificar', '["tumor lóbulo parietal", "cáncer parte superior cabeza", "masa parietal", "tumor parietal", "cáncer lóbulo parietal", "lesión parietal", "neoplasia lóbulo parietal", "malignidad parietal", "crecimiento parietal", "tumor corona de la cabeza", "masa parietal cerebro", "problemas sensoriales cerebro parietal"]'),
('C71.4', 'Neoplasia maligna de lóbulo occipital', 'Sin especificar', '["tumor lóbulo occipital", "cáncer nuca", "masa occipital", "tumor occipital", "cáncer lóbulo occipital", "lesión occipital", "neoplasia lóbulo occipital", "malignidad occipital", "crecimiento occipital", "tumor parte trasera cabeza", "masa nuca cerebro", "problemas visión tumor cerebral", "tumor zona occipital"]'),
('C71.5', 'Neoplasia maligna de ventrículo cerebral', 'Sin especificar', '["tumor ventrículos cerebrales", "cáncer ventrículo", "masa en ventrículos", "tumor intraventricular", "cáncer sistema ventricular", "lesión ventricular", "neoplasia ventricular", "malignidad ventricular", "crecimiento ventrículo cerebral", "tumor cavidad cerebral", "hidrocefalia por tumor", "obstrucción ventricular tumor"]'),
('C71.6', 'Neoplasia maligna de cerebelo', 'Sin especificar', '["tumor cerebelo", "cáncer cerebeloso", "masa en el cerebelo", "tumor equilibrio", "cáncer de cerebelo", "lesión cerebelar", "neoplasia cerebelosa", "malignidad cerebelo", "crecimiento cerebelo", "tumor parte baja cerebro", "mareos tumor cerebelo", "problemas de marcha tumor", "tumor fosa posterior"]'),
('C71.7', 'Neoplasia maligna de tronco cerebral', 'Sin especificar', '["tumor tronco encefálico", "cáncer tronco cerebral", "masa tronco cerebral", "tumor tallo cerebral", "cáncer tallo encefálico", "lesión tronco cerebral", "neoplasia tronco encefálico", "malignidad tallo cerebral", "crecimiento tronco cerebral", "tumor base del cerebro", "cáncer tallo cerebral", "dificultad respiratoria tumor cerebral", "tumor tronco"]'),
('C71.8', 'Neoplasia maligna de localizaciones contiguas de cerebro', 'Sin especificar', '["tumor cerebral múltiple", "cáncer cerebral extenso", "tumor zonas contiguas", "masa cerebral difusa", "cáncer cerebral multifocal", "lesiones cerebrales múltiples", "neoplasia cerebro superpuesta", "malignidad cerebral extendida", "crecimiento cerebral múltiple", "tumor que afecta varias partes cerebro", "cáncer cerebral complejo"]'),
('C71.9', 'Neoplasia maligna de cerebro, no especificada', 'Sin especificar', '["tumor en la cabeza", "cáncer cerebral", "masa maligna en el cerebro", "tumor maligno", "cáncer de coco", "bolita en la cabeza", "neoplasia cerebral", "tumor cerebral no especificado", "cáncer de sesos", "lesión cerebral maligna", "crecimiento maligno en la cabeza", "cáncer en la choya", "tumor de la cabeza", "enfermedad maligna cerebral"]');
