INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D07.0', 'Carcinoma in situ de endometrio', 'Sin especificar', '["cáncer de útero", "sangrado uterino", "tumor en la matriz", "cáncer de matriz", "metrorragia", "células anormales útero", "neoplasia intraepitelial endometrial", "dolor pélvico", "cáncer endometrio", "manchado postmenopáusico", "células cancerosas útero", "pre-cáncer útero", "cáncer de endometrio etapa inicial", "tumor endometrio"]'),
('D07.1', 'Carcinoma in situ de vulva', 'Sin especificar', '["cáncer de vulva", "picazón en la zona íntima", "ardor vulvar", "lesión en labios vaginales", "células cancerosas vulva", "cáncer de partes íntimas", "tumor en la vulva", "mancha blanca vulva", "VIN", "lesión premaligna vulva", "neoplasia intraepitelial vulvar", "picor vaginal", "dolor vulvar", "cáncer vulvar in situ"]'),
('D07.2', 'Carcinoma in situ de vagina', 'Sin especificar', '["cáncer de vagina", "tumor vaginal", "células anormales vagina", "VAIN", "lesión pre-cáncer vaginal", "sangrado vaginal anormal", "dolor al tener relaciones", "cáncer vaginal inicial", "displasia vaginal", "lesión precancerosa zona íntima", "neoplasia intraepitelial vaginal"]'),
('D07.30', 'Carcinoma in situ de órganos genitales femeninos no especificados', 'Sin especificar', '["cáncer ginecológico inicial", "tumor zona íntima mujer", "células cancerosas zona genital", "pre-cáncer ginecológico", "afección maligna inicial aparato reproductor", "problemas ginecológicos graves", "neoplasia in situ ginecológica", "cáncer femenino no especificado", "lesión extraña en partes íntimas"]'),
('D07.39', 'Carcinoma in situ de otros órganos genitales femeninos', 'Sin especificar', '["cáncer ginecológico raro", "tumor en trompas de falopio", "cáncer de ovarios inicial", "lesión precancerosa genital", "neoplasia intraepitelial en otros órganos genitales", "células atípicas genitales", "tumor ginecológico incipiente"]'),
('D07.4', 'Carcinoma in situ de pene', 'Sin especificar', '["cáncer de pene", "lesión en el miembro", "tumor en el pito", "cáncer de miembro viril", "neoplasia intraepitelial peneana", "PIN", "mancha en el glande", "pre-cáncer pene", "dolor en el pene", "células cancerosas en el pene", "tumor en el pene"]'),
('D07.5', 'Carcinoma in situ de próstata', 'Sin especificar', '["cáncer de próstata inicial", "tumor de próstata", "problemas de orina", "dolor al orinar", "células cancerosas próstata", "neoplasia intraepitelial prostática", "PIN prostático", "examen de próstata anormal", "dificultad para orinar", "cáncer de próstata no invasivo"]'),
('D07.60', 'Carcinoma in situ de órganos genitales masculinos no especificados', 'Sin especificar', '["cáncer genital masculino", "tumor en zona genital hombre", "células anormales genitales", "pre-cáncer masculino", "lesión zona íntima hombre", "cáncer varón inicial", "problemas genitales masculinos", "tumor aparato reproductor masculino"]'),
('D07.61', 'Carcinoma in situ de escroto', 'Sin especificar', '["cáncer de escroto", "tumor en los testículos", "bulto en la bolsa escrotal", "lesión en el escroto", "pre-cáncer escrotal", "enfermedad de Paget escrotal", "cáncer de huevos", "dolor en escroto", "células atípicas bolsa escrotal"]'),
('D07.69', 'Carcinoma in situ de otros órganos genitales masculinos', 'Sin especificar', '["cáncer de conductos genitales", "tumor en glándulas masculinas", "cáncer vesículas seminales", "neoplasia genital masculina", "pre-cáncer aparato reproductor masculino", "células cancerosas genitales", "lesión interna genital"]');
