INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S68.011A', 'Amputación traumática metacarpofalángica completa de pulgar derecho, contacto inicial', 'Sin especificar', '["pulgar cercenado", "dedo gordo cortado", "accidente pulgar", "dedo volado", "dedo amputado", "traumatismo mano", "pérdida de dedo", "dedo derecho perdido", "accidente laboral dedo", "urgencia dedo amputado"]'),
('S68.011D', 'Amputación traumática metacarpofalángica completa de pulgar derecho, contacto sucesivo', 'Sin especificar', '["seguimiento amputación dedo", "control dedo pulgar", "cura amputación pulgar", "revisión dedo cortado", "curación dedo gordo", "post operatorio pulgar", "seguimiento accidente mano"]'),
('S68.011S', 'Amputación traumática metacarpofalángica completa de pulgar derecho, secuela', 'Sin especificar', '["cicatriz amputación", "problemas dedo pulgar", "dolor muñón", "secuelas dedo perdido", "falta de dedo", "incapacidad dedo pulgar", "estética dedo amputado"]'),
('S68.012A', 'Amputación traumática metacarpofalángica completa de pulgar izquierdo, contacto inicial', 'Sin especificar', '["dedo gordo izquierdo cortado", "pulgar izquierdo cercenado", "accidente dedo izquierdo", "dedo amputado urgencia", "pérdida pulgar izquierdo", "trauma en mano izquierda"]'),
('S68.012D', 'Amputación traumática metacarpofalángica completa de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["control dedo pulgar izquierdo", "seguimiento amputación", "curación mano izquierda", "revisión herida dedo", "post-amputación pulgar"]'),
('S68.012S', 'Amputación traumática metacarpofalángica completa de pulgar izquierdo, secuela', 'Sin especificar', '["secuela dedo amputado", "dolor fantasma pulgar", "problemas motricidad pulgar", "cicatriz mano izquierda", "secuelas traumáticas mano"]'),
('S68.019A', 'Amputación traumática metacarpofalángica completa de pulgar no especificado, contacto inicial', 'Sin especificar', '["dedo gordo cortado", "accidente de pulgar", "dedo amputado", "cercenamiento pulgar", "urgencia mano", "dedo volado"]'),
('S68.019D', 'Amputación traumática metacarpofalángica completa de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["revisión de muñón", "cura de dedo", "seguimiento amputación", "control médico dedo", "post quirúrgico mano"]'),
('S68.019S', 'Amputación traumática metacarpofalángica completa de pulgar no especificado, secuela', 'Sin especificar', '["muñón doloroso", "secuela de dedo", "pérdida funcional dedo", "cicatriz problemática", "dolor en mano"]'),
('S68.021A', 'Amputación traumática metacarpofalángica parcial de pulgar derecho, contacto inicial', 'Sin especificar', '["pulgar derecho mutilado", "dedo gordo herido grave", "amputación parcial pulgar", "dedo roto traumático", "accidente dedo mano"]'),
('S68.021D', 'Amputación traumática metacarpofalángica parcial de pulgar derecho, contacto sucesivo', 'Sin especificar', '["control amputación parcial", "curación dedo pulgar", "seguimiento herida pulgar", "evolución muñón dedo"]'),
('S68.021S', 'Amputación traumática metacarpofalángica parcial de pulgar derecho, secuela', 'Sin especificar', '["deformidad pulgar", "secuela amputación parcial", "cicatriz dedo", "limitación funcional dedo"]'),
('S68.022A', 'Amputación traumática metacarpofalángica parcial de pulgar izquierdo, contacto inicial', 'Sin especificar', '["pulgar izquierdo mutilado", "dedo gordo parcial", "accidente pulgar izquierdo", "corte grave pulgar"]'),
('S68.022D', 'Amputación traumática metacarpofalángica parcial de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["curación pulgar izquierdo", "revisión herida", "control amputación", "seguimiento post operatorio"]'),
('S68.022S', 'Amputación traumática metacarpofalángica parcial de pulgar izquierdo, secuela', 'Sin especificar', '["secuela mano izquierda", "muñón sensible", "deformación dedo", "dolor crónico pulgar"]'),
('S68.029A', 'Amputación traumática metacarpofalángica parcial de pulgar no especificado, contacto inicial', 'Sin especificar', '["dedo gordo cortado", "amputación parcial", "trauma pulgar", "herida grave mano"]'),
('S68.029D', 'Amputación traumática metacarpofalángica parcial de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["curación dedo", "control médico", "seguimiento herida", "post operatorio"]'),
('S68.029S', 'Amputación traumática metacarpofalángica parcial de pulgar no especificado, secuela', 'Sin especificar', '["secuelas traumáticas", "cicatriz", "dolor", "discapacidad dedo"]'),
('S68.110A', 'Amputación traumática metacarpofalángica completa de dedo índice derecho, contacto inicial', 'Sin especificar', '["dedo índice cortado", "índice cercenado", "accidente índice derecho", "dedo perdido mano derecha", "traumatismo índice"]'),
('S68.110D', 'Amputación traumática metacarpofalángica completa de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["revisión índice derecho", "cura dedo índice", "seguimiento amputación", "control médico mano"]'),
('S68.110S', 'Amputación traumática metacarpofalángica completa de dedo índice derecho, secuela', 'Sin especificar', '["secuela índice", "muñón dedo índice", "cicatriz mano", "falta dedo índice"]'),
('S68.111A', 'Amputación traumática metacarpofalángica completa de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["dedo índice izquierdo cortado", "índice izquierdo perdido", "accidente índice", "amputación dedo mano izquierda"]'),
('S68.111D', 'Amputación traumática metacarpofalángica completa de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["curación índice izquierdo", "seguimiento mano", "revisión dedo", "control post operatorio"]'),
('S68.111S', 'Amputación traumática metacarpofalángica completa de dedo índice izquierdo, secuela', 'Sin especificar', '["secuela amputación índice", "muñón índice", "dolor fantasma", "problemas mano"]'),
('S68.112A', 'Amputación traumática metacarpofalángica completa de dedo medio derecho, contacto inicial', 'Sin especificar', '["dedo corazón cortado", "dedo medio amputado", "accidente dedo medio", "dedo perdido", "trauma mano"]'),
('S68.112D', 'Amputación traumática metacarpofalángica completa de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["curación dedo medio", "control amputación", "seguimiento dedo", "revisión médica"]'),
('S68.112S', 'Amputación traumática metacarpofalángica completa de dedo medio derecho, secuela', 'Sin especificar', '["secuela dedo medio", "cicatriz mano", "problemas dedo", "dolor muñón"]'),
('S68.113A', 'Amputación traumática metacarpofalángica completa de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["dedo corazón izquierdo", "medio izquierdo amputado", "dedo cortado mano izquierda", "accidente mano"]'),
('S68.113D', 'Amputación traumática metacarpofalángica completa de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["revisión dedo medio", "cura herida", "control post amputación", "seguimiento dedo"]'),
('S68.113S', 'Amputación traumática metacarpofalángica completa de dedo medio izquierdo, secuela', 'Sin especificar', '["secuela dedo medio", "muñón", "cicatriz", "discapacidad mano"]'),
('S68.114A', 'Amputación traumática metacarpofalángica completa de dedo anular derecho, contacto inicial', 'Sin especificar', '["dedo anular cortado", "amputación anular derecho", "dedo perdido", "accidente mano", "corte dedo anular"]'),
('S68.114D', 'Amputación traumática metacarpofalángica completa de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["curación anular derecho", "seguimiento amputación", "control dedo", "revisión muñón"]'),
('S68.114S', 'Amputación traumática metacarpofalángica completa de dedo anular derecho, secuela', 'Sin especificar', '["secuela anular", "cicatriz dedo", "dolor", "problema anular"]'),
('S68.115A', 'Amputación traumática metacarpofalángica completa de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["anular izquierdo cortado", "amputación anular", "accidente anular izquierdo", "dedo volado"]'),
('S68.115D', 'Amputación traumática metacarpofalángica completa de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["control anular izquierdo", "cura dedo", "seguimiento post operado", "revisión mano"]'),
('S68.115S', 'Amputación traumática metacarpofalángica completa de dedo anular izquierdo, secuela', 'Sin especificar', '["secuela dedo anular", "muñón", "cicatriz", "dolor crónico"]'),
('S68.116A', 'Amputación traumática metacarpofalángica completa de dedo meñique derecho, contacto inicial', 'Sin especificar', '["dedo meñique cortado", "meñique derecho amputado", "accidente meñique", "dedo pequeño cortado"]'),
('S68.116D', 'Amputación traumática metacarpofalángica completa de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["cura meñique derecho", "control médico", "seguimiento amputación", "revisión muñón"]'),
('S68.116S', 'Amputación traumática metacarpofalángica completa de dedo meñique derecho, secuela', 'Sin especificar', '["secuela meñique", "muñón meñique", "cicatriz", "falta dedo pequeño"]'),
('S68.117A', 'Amputación traumática metacarpofalángica completa de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["meñique izquierdo cortado", "dedo pequeño izquierdo", "accidente meñique", "cercenamiento dedo"]'),
('S68.117D', 'Amputación traumática metacarpofalángica completa de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["curación meñique izquierdo", "control dedo", "seguimiento herida", "revisión"]'),
('S68.117S', 'Amputación traumática metacarpofalángica completa de dedo meñique izquierdo, secuela', 'Sin especificar', '["secuela meñique", "muñón", "dolor", "cicatriz"]'),
('S68.118A', 'Amputación traumática metacarpofalángica completa de otro dedo de mano, contacto inicial', 'Sin especificar', '["dedo cortado", "amputación dedo", "accidente mano", "trauma dedo"]'),
('S68.118D', 'Amputación traumática metacarpofalángica completa de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "control post operatorio", "revisión muñón"]'),
('S68.118S', 'Amputación traumática metacarpofalángica completa de otro dedo de mano, secuela', 'Sin especificar', '["secuela dedo", "muñón", "dolor", "cicatriz"]'),
('S68.119A', 'Amputación traumática metacarpofalángica completa de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["dedo cercenado", "amputación dedo", "accidente", "dedo volado"]'),
('S68.119D', 'Amputación traumática metacarpofalángica completa de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "control médico", "revisión"]'),
('S68.119S', 'Amputación traumática metacarpofalángica completa de dedo de mano no especificado, secuela', 'Sin especificar', '["secuelas", "muñón", "cicatriz", "dolor"]'),
('S68.120A', 'Amputación traumática metacarpofalángica parcial de dedo índice derecho, contacto inicial', 'Sin especificar', '["índice derecho herido", "corte parcial índice", "amputación parcial", "trauma dedo índice"]'),
('S68.120D', 'Amputación traumática metacarpofalángica parcial de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["cura índice derecho", "seguimiento herida", "revisión", "control post operado"]'),
('S68.120S', 'Amputación traumática metacarpofalángica parcial de dedo índice derecho, secuela', 'Sin especificar', '["secuela índice", "cicatriz índice", "dolor dedo", "deformidad índice"]'),
('S68.121A', 'Amputación traumática metacarpofalángica parcial de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["índice izquierdo herido", "corte parcial índice", "accidente índice izquierdo", "amputación parcial"]'),
('S68.121D', 'Amputación traumática metacarpofalángica parcial de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["cura índice izquierdo", "seguimiento", "revisión", "control"]'),
('S68.121S', 'Amputación traumática metacarpofalángica parcial de dedo índice izquierdo, secuela', 'Sin especificar', '["secuela índice", "cicatriz", "dolor dedo", "deformidad"]'),
('S68.122A', 'Amputación traumática metacarpofalángica parcial de dedo medio derecho, contacto inicial', 'Sin especificar', '["medio derecho herido", "corte parcial medio", "amputación parcial", "accidente dedo"]'),
('S68.122D', 'Amputación traumática metacarpofalángica parcial de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["cura dedo medio", "seguimiento", "revisión", "control"]'),
('S68.122S', 'Amputación traumática metacarpofalángica parcial de dedo medio derecho, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.123A', 'Amputación traumática metacarpofalángica parcial de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["medio izquierdo herido", "corte parcial medio", "amputación parcial", "accidente dedo"]'),
('S68.123D', 'Amputación traumática metacarpofalángica parcial de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["cura dedo medio izquierdo", "seguimiento", "revisión", "control"]'),
('S68.123S', 'Amputación traumática metacarpofalángica parcial de dedo medio izquierdo, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.124A', 'Amputación traumática metacarpofalángica parcial de dedo anular derecho, contacto inicial', 'Sin especificar', '["anular derecho herido", "corte parcial anular", "amputación parcial", "accidente dedo"]'),
('S68.124D', 'Amputación traumática metacarpofalángica parcial de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["cura anular derecho", "seguimiento", "revisión", "control"]'),
('S68.124S', 'Amputación traumática metacarpofalángica parcial de dedo anular derecho, secuela', 'Sin especificar', '["secuela anular", "cicatriz", "dolor", "deformidad"]'),
('S68.125A', 'Amputación traumática metacarpofalángica parcial de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["anular izquierdo herido", "corte parcial anular", "amputación parcial", "accidente dedo"]'),
('S68.125D', 'Amputación traumática metacarpofalángica parcial de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["cura anular izquierdo", "seguimiento", "revisión", "control"]'),
('S68.125S', 'Amputación traumática metacarpofalángica parcial de dedo anular izquierdo, secuela', 'Sin especificar', '["secuela anular", "cicatriz", "dolor", "deformidad"]'),
('S68.126A', 'Amputación traumática metacarpofalángica parcial de dedo meñique derecho, contacto inicial', 'Sin especificar', '["meñique derecho herido", "corte parcial meñique", "amputación parcial", "accidente dedo"]'),
('S68.126D', 'Amputación traumática metacarpofalángica parcial de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["cura meñique derecho", "seguimiento", "revisión", "control"]'),
('S68.126S', 'Amputación traumática metacarpofalángica parcial de dedo meñique derecho, secuela', 'Sin especificar', '["secuela meñique", "cicatriz", "dolor", "deformidad"]'),
('S68.127A', 'Amputación traumática metacarpofalángica parcial de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["meñique izquierdo herido", "corte parcial meñique", "amputación parcial", "accidente dedo"]'),
('S68.127D', 'Amputación traumática metacarpofalángica parcial de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["cura meñique izquierdo", "seguimiento", "revisión", "control"]'),
('S68.127S', 'Amputación traumática metacarpofalángica parcial de dedo meñique izquierdo, secuela', 'Sin especificar', '["secuela meñique", "cicatriz", "dolor", "deformidad"]'),
('S68.128A', 'Amputación traumática metacarpofalángica parcial de otro dedo de mano, contacto inicial', 'Sin especificar', '["dedo herido", "corte parcial", "amputación parcial", "accidente dedo"]'),
('S68.128D', 'Amputación traumática metacarpofalángica parcial de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.128S', 'Amputación traumática metacarpofalángica parcial de otro dedo de mano, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.129A', 'Amputación traumática metacarpofalángica parcial de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["dedo herido", "corte parcial", "amputación parcial", "accidente"]'),
('S68.129D', 'Amputación traumática metacarpofalángica parcial de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.129S', 'Amputación traumática metacarpofalángica parcial de dedo de mano no especificado, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.411A', 'Amputación mano derecha', 'Sin especificar', '["mano cortada", "pérdida mano derecha", "accidente muñeca", "amputación muñeca", "trauma mano", "urgencia amputación"]'),
('S68.411D', 'Amputación traumática completa de mano derecha a nivel de muñeca, contacto sucesivo', 'Sin especificar', '["cura muñeca", "seguimiento amputación", "revisión mano", "control post operatorio"]'),
('S68.411S', 'Amputación traumática completa de mano derecha a nivel de muñeca, secuela', 'Sin especificar', '["secuela amputación", "muñón mano", "cicatriz mano", "dolor fantasma", "discapacidad"]'),
('S68.412A', 'Amputación traumática completa de mano izquierda a nivel de muñeca, contacto inicial', 'Sin especificar', '["mano izquierda cortada", "pérdida mano izquierda", "accidente muñeca", "amputación muñeca", "urgencia"]'),
('S68.412D', 'Amputación traumática completa de mano izquierda a nivel de muñeca, contacto sucesivo', 'Sin especificar', '["cura muñeca izquierda", "seguimiento", "revisión", "control"]'),
('S68.412S', 'Amputación traumática completa de mano izquierda a nivel de muñeca, secuela', 'Sin especificar', '["secuela amputación", "muñón mano", "cicatriz", "dolor fantasma"]'),
('S68.419A', 'Amputación traumática completa de mano no especificada a nivel de muñeca, contacto inicial', 'Sin especificar', '["mano cortada", "amputación muñeca", "trauma mano", "accidente"]'),
('S68.419D', 'Amputación traumática completa de mano no especificada a nivel de muñeca, contacto sucesivo', 'Sin especificar', '["cura muñeca", "seguimiento", "revisión", "control"]'),
('S68.419S', 'Amputación traumática completa de mano no especificada a nivel de muñeca, secuela', 'Sin especificar', '["secuela amputación", "muñón", "cicatriz", "dolor"]'),
('S68.421A', 'Amputación traumática parcial de mano derecha a nivel de muñeca, contacto inicial', 'Sin especificar', '["mano derecha herida", "amputación parcial mano", "accidente muñeca", "trauma mano"]'),
('S68.421D', 'Amputación traumática parcial de mano derecha a nivel de muñeca, contacto sucesivo', 'Sin especificar', '["cura mano", "seguimiento", "revisión", "control"]'),
('S68.421S', 'Amputación traumática parcial de mano derecha a nivel de muñeca, secuela', 'Sin especificar', '["secuela mano", "cicatriz", "dolor", "discapacidad"]'),
('S68.422A', 'Amputación traumática parcial de mano izquierda a nivel de muñeca, contacto inicial', 'Sin especificar', '["mano izquierda herida", "amputación parcial mano", "accidente muñeca", "trauma mano"]'),
('S68.422D', 'Amputación traumática parcial de mano izquierda a nivel de muñeca, contacto sucesivo', 'Sin especificar', '["cura mano", "seguimiento", "revisión", "control"]'),
('S68.422S', 'Amputación traumática parcial de mano izquierda a nivel de muñeca, secuela', 'Sin especificar', '["secuela mano", "cicatriz", "dolor", "discapacidad"]'),
('S68.429A', 'Amputación traumática parcial de mano no especificada a nivel de muñeca, contacto inicial', 'Sin especificar', '["mano herida", "amputación parcial", "trauma mano", "accidente"]'),
('S68.429D', 'Amputación traumática parcial de mano no especificada a nivel de muñeca, contacto sucesivo', 'Sin especificar', '["cura mano", "seguimiento", "revisión", "control"]'),
('S68.429S', 'Amputación traumática parcial de mano no especificada a nivel de muñeca, secuela', 'Sin especificar', '["secuela mano", "cicatriz", "dolor", "discapacidad"]'),
('S68.511A', 'Amputación traumática transfalángica completa de pulgar derecho, contacto inicial', 'Sin especificar', '["pulgar derecho cercenado", "amputación dedo gordo", "accidente pulgar", "dedo cortado", "trauma falange"]'),
('S68.511D', 'Amputación traumática transfalángica completa de pulgar derecho, contacto sucesivo', 'Sin especificar', '["cura pulgar", "seguimiento", "revisión", "control"]'),
('S68.511S', 'Amputación traumática transfalángica completa de pulgar derecho, secuela', 'Sin especificar', '["secuela pulgar", "muñón", "dolor", "cicatriz"]'),
('S68.512A', 'Amputación traumática transfalángica completa de pulgar izquierdo, contacto inicial', 'Sin especificar', '["pulgar izquierdo cercenado", "amputación dedo gordo", "accidente pulgar", "dedo cortado"]'),
('S68.512D', 'Amputación traumática transfalángica completa de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["cura pulgar", "seguimiento", "revisión", "control"]'),
('S68.512S', 'Amputación traumática transfalángica completa de pulgar izquierdo, secuela', 'Sin especificar', '["secuela pulgar", "muñón", "dolor", "cicatriz"]'),
('S68.519A', 'Amputación traumática transfalángica completa de pulgar no especificado, contacto inicial', 'Sin especificar', '["pulgar cercenado", "amputación dedo gordo", "accidente pulgar", "dedo cortado"]'),
('S68.519D', 'Amputación traumática transfalángica completa de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["cura pulgar", "seguimiento", "revisión", "control"]'),
('S68.519S', 'Amputación traumática transfalángica completa de pulgar no especificado, secuela', 'Sin especificar', '["secuela pulgar", "muñón", "dolor", "cicatriz"]'),
('S68.521A', 'Amputación traumática transfalángica parcial de pulgar derecho, contacto inicial', 'Sin especificar', '["pulgar derecho herido", "corte parcial falange", "accidente pulgar", "dedo dañado"]'),
('S68.521D', 'Amputación traumática transfalángica parcial de pulgar derecho, contacto sucesivo', 'Sin especificar', '["cura pulgar", "seguimiento", "revisión", "control"]'),
('S68.521S', 'Amputación traumática transfalángica parcial de pulgar derecho, secuela', 'Sin especificar', '["secuela pulgar", "cicatriz", "dolor", "deformidad"]'),
('S68.522A', 'Amputación traumática transfalángica parcial de pulgar izquierdo, contacto inicial', 'Sin especificar', '["pulgar izquierdo herido", "corte parcial falange", "accidente pulgar", "dedo dañado"]'),
('S68.522D', 'Amputación traumática transfalángica parcial de pulgar izquierdo, contacto sucesivo', 'Sin especificar', '["cura pulgar", "seguimiento", "revisión", "control"]'),
('S68.522S', 'Amputación traumática transfalángica parcial de pulgar izquierdo, secuela', 'Sin especificar', '["secuela pulgar", "cicatriz", "dolor", "deformidad"]'),
('S68.529A', 'Amputación traumática transfalángica parcial de pulgar no especificado, contacto inicial', 'Sin especificar', '["pulgar herido", "corte parcial falange", "accidente pulgar", "dedo dañado"]'),
('S68.529D', 'Amputación traumática transfalángica parcial de pulgar no especificado, contacto sucesivo', 'Sin especificar', '["cura pulgar", "seguimiento", "revisión", "control"]'),
('S68.529S', 'Amputación traumática transfalángica parcial de pulgar no especificado, secuela', 'Sin especificar', '["secuela pulgar", "cicatriz", "dolor", "deformidad"]'),
('S68.610A', 'Amputación traumática transfalángica completa de dedo índice derecho, contacto inicial', 'Sin especificar', '["índice derecho cercenado", "falange cortada", "accidente índice", "dedo índice perdido"]'),
('S68.610D', 'Amputación traumática transfalángica completa de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["cura índice", "seguimiento", "revisión", "control"]'),
('S68.610S', 'Amputación traumática transfalángica completa de dedo índice derecho, secuela', 'Sin especificar', '["secuela índice", "muñón", "dolor", "cicatriz"]'),
('S68.611A', 'Amputación traumática transfalángica completa de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["índice izquierdo cercenado", "falange cortada", "accidente índice", "dedo índice perdido"]'),
('S68.611D', 'Amputación traumática transfalángica completa de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["cura índice", "seguimiento", "revisión", "control"]'),
('S68.611S', 'Amputación traumática transfalángica completa de dedo índice izquierdo, secuela', 'Sin especificar', '["secuela índice", "muñón", "dolor", "cicatriz"]'),
('S68.612A', 'Amputación traumática transfalángica completa de dedo medio derecho, contacto inicial', 'Sin especificar', '["medio derecho cercenado", "falange cortada", "accidente dedo", "dedo medio perdido"]'),
('S68.612D', 'Amputación traumática transfalángica completa de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.612S', 'Amputación traumática transfalángica completa de dedo medio derecho, secuela', 'Sin especificar', '["secuela dedo", "muñón", "dolor", "cicatriz"]'),
('S68.613A', 'Amputación traumática transfalángica completa de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["medio izquierdo cercenado", "falange cortada", "accidente dedo", "dedo medio perdido"]'),
('S68.613D', 'Amputación traumática transfalángica completa de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.613S', 'Amputación traumática transfalángica completa de dedo medio izquierdo, secuela', 'Sin especificar', '["secuela dedo", "muñón", "dolor", "cicatriz"]'),
('S68.614A', 'Amputación traumática transfalángica completa de dedo anular derecho, contacto inicial', 'Sin especificar', '["anular derecho cercenado", "falange cortada", "accidente dedo", "dedo anular perdido"]'),
('S68.614D', 'Amputación traumática transfalángica completa de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.614S', 'Amputación traumática transfalángica completa de dedo anular derecho, secuela', 'Sin especificar', '["secuela dedo", "muñón", "dolor", "cicatriz"]'),
('S68.615A', 'Amputación traumática transfalángica completa de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["anular izquierdo cercenado", "falange cortada", "accidente dedo", "dedo anular perdido"]'),
('S68.615D', 'Amputación traumática transfalángica completa de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.615S', 'Amputación traumática transfalángica completa de dedo anular izquierdo, secuela', 'Sin especificar', '["secuela dedo", "muñón", "dolor", "cicatriz"]'),
('S68.616A', 'Amputación traumática transfalángica completa de dedo meñique derecho, contacto inicial', 'Sin especificar', '["meñique derecho cercenado", "falange cortada", "accidente dedo", "dedo meñique perdido"]'),
('S68.616D', 'Amputación traumática transfalángica completa de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.616S', 'Amputación traumática transfalángica completa de dedo meñique derecho, secuela', 'Sin especificar', '["secuela dedo", "muñón", "dolor", "cicatriz"]'),
('S68.617A', 'Amputación traumática transfalángica completa de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["meñique izquierdo cercenado", "falange cortada", "accidente dedo", "dedo meñique perdido"]'),
('S68.617D', 'Amputación traumática transfalángica completa de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.617S', 'Amputación traumática transfalángica completa de dedo meñique izquierdo, secuela', 'Sin especificar', '["secuela dedo", "muñón", "dolor", "cicatriz"]'),
('S68.618A', 'Amputación traumática transfalángica completa de otro dedo de mano, contacto inicial', 'Sin especificar', '["dedo cercenado", "falange cortada", "accidente dedo"]'),
('S68.618D', 'Amputación traumática transfalángica completa de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.618S', 'Amputación traumática transfalángica completa de otro dedo de mano, secuela', 'Sin especificar', '["secuela dedo", "muñón", "dolor", "cicatriz"]'),
('S68.619A', 'Amputación traumática transfalángica completa de dedo no especificado, contacto inicial', 'Sin especificar', '["dedo cercenado", "falange cortada", "accidente dedo"]'),
('S68.619D', 'Amputación traumática transfalángica completa de dedo no especificado, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.619S', 'Amputación traumática transfalángica completa de dedo no especificado, secuela', 'Sin especificar', '["secuela dedo", "muñón", "dolor", "cicatriz"]'),
('S68.620A', 'Amputación traumática transfalángica parcial de dedo índice derecho, contacto inicial', 'Sin especificar', '["índice derecho herido", "corte parcial falange", "accidente dedo"]'),
('S68.620D', 'Amputación traumática transfalángica parcial de dedo índice derecho, contacto sucesivo', 'Sin especificar', '["cura índice", "seguimiento", "revisión", "control"]'),
('S68.620S', 'Amputación traumática transfalángica parcial de dedo índice derecho, secuela', 'Sin especificar', '["secuela índice", "cicatriz", "dolor", "deformidad"]'),
('S68.621A', 'Amputación traumática transfalángica parcial de dedo índice izquierdo, contacto inicial', 'Sin especificar', '["índice izquierdo herido", "corte parcial falange", "accidente dedo"]'),
('S68.621D', 'Amputación traumática transfalángica parcial de dedo índice izquierdo, contacto sucesivo', 'Sin especificar', '["cura índice", "seguimiento", "revisión", "control"]'),
('S68.621S', 'Amputación traumática transfalángica parcial de dedo índice izquierdo, secuela', 'Sin especificar', '["secuela índice", "cicatriz", "dolor", "deformidad"]'),
('S68.622A', 'Amputación traumática transfalángica parcial de dedo medio derecho, contacto inicial', 'Sin especificar', '["medio derecho herido", "corte parcial falange", "accidente dedo"]'),
('S68.622D', 'Amputación traumática transfalángica parcial de dedo medio derecho, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.622S', 'Amputación traumática transfalángica parcial de dedo medio derecho, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.623A', 'Amputación traumática transfalángica parcial de dedo medio izquierdo, contacto inicial', 'Sin especificar', '["medio izquierdo herido", "corte parcial falange", "accidente dedo"]'),
('S68.623D', 'Amputación traumática transfalángica parcial de dedo medio izquierdo, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.623S', 'Amputación traumática transfalángica parcial de dedo medio izquierdo, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.624A', 'Amputación traumática transfalángica parcial de dedo anular derecho, contacto inicial', 'Sin especificar', '["anular derecho herido", "corte parcial falange", "accidente dedo"]'),
('S68.624D', 'Amputación traumática transfalángica parcial de dedo anular derecho, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.624S', 'Amputación traumática transfalángica parcial de dedo anular derecho, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.625A', 'Amputación traumática transfalángica parcial de dedo anular izquierdo, contacto inicial', 'Sin especificar', '["anular izquierdo herido", "corte parcial falange", "accidente dedo"]'),
('S68.625D', 'Amputación traumática transfalángica parcial de dedo anular izquierdo, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.625S', 'Amputación traumática transfalángica parcial de dedo anular izquierdo, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.626A', 'Amputación traumática transfalángica parcial de dedo meñique derecho, contacto inicial', 'Sin especificar', '["meñique derecho herido", "corte parcial falange", "accidente dedo"]'),
('S68.626D', 'Amputación traumática transfalángica parcial de dedo meñique derecho, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.626S', 'Amputación traumática transfalángica parcial de dedo meñique derecho, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.627A', 'Amputación traumática transfalángica parcial de dedo meñique izquierdo, contacto inicial', 'Sin especificar', '["meñique izquierdo herido", "corte parcial falange", "accidente dedo"]'),
('S68.627D', 'Amputación traumática transfalángica parcial de dedo meñique izquierdo, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.627S', 'Amputación traumática transfalángica parcial de dedo meñique izquierdo, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.628A', 'Amputación traumática transfalángica parcial de otro dedo de mano, contacto inicial', 'Sin especificar', '["dedo herido", "corte parcial falange", "accidente dedo"]'),
('S68.628D', 'Amputación traumática transfalángica parcial de otro dedo de mano, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.628S', 'Amputación traumática transfalángica parcial de otro dedo de mano, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.629A', 'Amputación traumática transfalángica parcial de dedo de mano no especificado, contacto inicial', 'Sin especificar', '["dedo herido", "corte parcial falange", "accidente"]'),
('S68.629D', 'Amputación traumática transfalángica parcial de dedo de mano no especificado, contacto sucesivo', 'Sin especificar', '["cura dedo", "seguimiento", "revisión", "control"]'),
('S68.629S', 'Amputación traumática transfalángica parcial de dedo de mano no especificado, secuela', 'Sin especificar', '["secuela dedo", "cicatriz", "dolor", "deformidad"]'),
('S68.711A', 'Amputación traumática transmetacarpiana completa de mano derecha, contacto inicial', 'Sin especificar', '["mano derecha cercenada", "amputación mano", "accidente mano", "corte transmetacarpiano"]'),
('S68.711D', 'Amputación traumática transmetacarpiana completa de mano derecha, contacto sucesivo', 'Sin especificar', '["cura mano", "seguimiento", "revisión", "control"]'),
('S68.711S', 'Amputación traumática transmetacarpiana completa de mano derecha, secuela', 'Sin especificar', '["secuela mano", "cicatriz", "dolor", "discapacidad"]'),
('S68.712A', 'Amputación traumática transmetacarpiana completa de mano izquierda, contacto inicial', 'Sin especificar', '["mano izquierda cercenada", "amputación mano", "accidente mano", "corte transmetacarpiano"]'),
('S68.712D', 'Amputación traumática transmetacarpiana completa de mano izquierda, contacto sucesivo', 'Sin especificar', '["cura mano", "seguimiento", "revisión", "control"]'),
('S68.712S', 'Amputación traumática transmetacarpiana completa de mano izquierda, secuela', 'Sin especificar', '["secuela mano", "cicatriz", "dolor", "discapacidad"]'),
('S68.719A', 'Amputación traumática transmetacarpiana completa de mano no especificada, contacto inicial', 'Sin especificar', '["mano cercenada", "amputación mano", "accidente mano", "corte"]'),
('S68.719D', 'Amputación traumática transmetacarpiana completa de mano no especificada, contacto sucesivo', 'Sin especificar', '["cura mano", "seguimiento", "revisión", "control"]'),
('S68.719S', 'Amputación traumática transmetacarpiana completa de mano no especificada, secuela', 'Sin especificar', '["secuela mano", "cicatriz", "dolor", "discapacidad"]'),
('S68.721A', 'Amputación traumática transmetacarpiana parcial de mano derecha, contacto inicial', 'Sin especificar', '["mano derecha herida", "amputación parcial mano", "accidente", "corte"]'),
('S68.721D', 'Amputación traumática transmetacarpiana parcial de mano derecha, contacto sucesivo', 'Sin especificar', '["cura mano", "seguimiento", "revisión", "control"]'),
('S68.721S', 'Amputación traumática transmetacarpiana parcial de mano derecha, secuela', 'Sin especificar', '["secuela mano", "cicatriz", "dolor", "discapacidad"]'),
('S68.722A', 'Amputación traumática transmetacarpiana parcial de mano izquierda, contacto inicial', 'Sin especificar', '["mano izquierda herida", "amputación parcial mano", "accidente", "corte"]'),
('S68.722D', 'Amputación traumática transmetacarpiana parcial de mano izquierda, contacto sucesivo', 'Sin especificar', '["cura mano", "seguimiento", "revisión", "control"]'),
('S68.722S', 'Amputación traumática transmetacarpiana parcial de mano izquierda, secuela', 'Sin especificar', '["secuela mano", "cicatriz", "dolor", "discapacidad"]'),
('S68.729A', 'Amputación traumática transmetacarpiana parcial de mano no especificada, contacto inicial', 'Sin especificar', '["mano herida", "amputación parcial", "accidente", "corte"]'),
('S68.729D', 'Amputación traumática transmetacarpiana parcial de mano no especificada, contacto sucesivo', 'Sin especificar', '["cura mano", "seguimiento", "revisión", "control"]'),
('S68.729S', 'Amputación traumática transmetacarpiana parcial de mano no especificada, secuela', 'Sin especificar', '["secuela mano", "cicatriz", "dolor", "discapacidad"]');
