INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('S81.001A', 'Herida abierta no especificada de rodilla derecha, contacto inicial', 'Sin especificar', '["corte en la rodilla", "rodilla rota", "tajo en la rodilla", "raja en la rodilla", "herida sangrante", "rodilla abierta", "me corté la rodilla", "accidente de rodilla", "rasguño profundo rodilla", "rodilla derecha lastimada", "golpe con corte rodilla", "emergencia rodilla", "sangre en la rodilla", "traumatismo rodilla", "corte reciente"]'),
('S81.001D', 'Herida abierta no especificada de rodilla derecha, contacto sucesivo', 'Sin especificar', '["curación de rodilla", "seguimiento herida rodilla", "revisión corte rodilla", "punto de sutura rodilla", "limpieza de herida", "curación infectada rodilla", "control médico rodilla", "revisión médica corte", "seguimiento herida", "tratamiento rodilla derecha", "cambio de vendaje rodilla", "curación sucesiva"]'),
('S81.001S', 'Herida abierta no especificada de rodilla derecha, secuela', 'Sin especificar', '["cicatriz rodilla", "problemas tras corte rodilla", "dolor crónico rodilla", "secuela de herida", "mala cicatrización rodilla", "rigidez por cicatriz", "complicación herida vieja", "herida que no cierra", "rehabilitación tras corte", "secuela cicatriz"]'),
('S81.002A', 'Herida abierta no especificada de rodilla izquierda, contacto inicial', 'Sin especificar', '["corte en la rodilla izquierda", "rodilla izquierda abierta", "tajo rodilla izquierda", "sangre en la rodilla izquierda", "herida recién hecha rodilla", "accidente rodilla izquierda", "rasguño rodilla", "lesión rodilla izquierda", "golpe y corte rodilla"]'),
('S81.002D', 'Herida abierta no especificada de rodilla izquierda, contacto sucesivo', 'Sin especificar', '["curación rodilla izquierda", "control herida izquierda", "seguimiento herida abierta", "revisión puntos rodilla izquierda", "limpieza de herida infectada", "cura de rodilla", "revisión médica rodilla izquierda", "cambio de curas", "tratamiento posterior corte"]'),
('S81.002S', 'Herida abierta no especificada de rodilla izquierda, secuela', 'Sin especificar', '["cicatriz rodilla izquierda", "molestias por herida antigua", "dolor rodilla izquierda cicatriz", "secuelas de corte rodilla", "queloide rodilla", "mala cicatriz rodilla", "rehabilitación cicatriz", "problemas post herida"]'),
('S81.009A', 'Herida abierta no especificada de rodilla no especificada, contacto inicial', 'Sin especificar', '["corte en la rodilla", "herida rodilla", "tajo rodilla", "rodilla sangrando", "me hice una rajada en la rodilla", "golpe con herida rodilla", "emergencia herida rodilla"]'),
('S81.009D', 'Herida abierta no especificada de rodilla no especificada, contacto sucesivo', 'Sin especificar', '["curación de rodilla", "revisión herida", "control de sutura", "seguimiento herida rodilla", "cura de herida", "curar rodilla", "limpieza de rodilla"]'),
('S81.009S', 'Herida abierta no especificada de rodilla no especificada, secuela', 'Sin especificar', '["secuela cicatriz rodilla", "cicatriz que molesta", "dolor por vieja herida", "problemas de cicatrización", "rehabilitación cicatriz"]'),
('S81.011A', 'Desgarro sin cuerpo extraño de rodilla derecha, contacto inicial', 'Sin especificar', '["desgarro piel rodilla", "rodilla rasgada", "piel abierta rodilla", "herida por desgarro", "despellejado rodilla derecha", "rodilla derecha abierta por accidente", "piel desprendida rodilla"]'),
('S81.011D', 'Desgarro sin cuerpo extraño de rodilla derecha, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro rodilla", "curación desgarro piel", "revisión herida desgarro", "control cicatrización rodilla", "limpieza herida desgarro"]'),
('S81.011S', 'Desgarro sin cuerpo extraño de rodilla derecha, secuela', 'Sin especificar', '["secuela desgarro rodilla", "cicatriz de desgarro", "piel tirante rodilla", "mala cicatrización desgarro"]'),
('S81.012A', 'Desgarro sin cuerpo extraño de rodilla izquierda, contacto inicial', 'Sin especificar', '["desgarro rodilla izquierda", "piel abierta rodilla izquierda", "despellejada rodilla", "rasgón rodilla izquierda", "herida desgarro pierna"]'),
('S81.012D', 'Desgarro sin cuerpo extraño de rodilla izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro izquierda", "curación desgarro piel", "control cicatrización izquierda", "revisión médica rodilla"]'),
('S81.012S', 'Desgarro sin cuerpo extraño de rodilla izquierda, secuela', 'Sin especificar', '["cicatriz desgarro rodilla", "secuela cutánea rodilla", "piel que no estira bien"]'),
('S81.019A', 'Desgarro sin cuerpo extraño de rodilla no especificada, contacto inicial', 'Sin especificar', '["desgarro piel rodilla", "piel abierta", "despellejada rodilla", "herida profunda piel rodilla"]'),
('S81.019D', 'Desgarro sin cuerpo extraño de rodilla no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro", "curar desgarro", "revisión piel rodilla"]'),
('S81.019S', 'Desgarro sin cuerpo extraño de rodilla no especificada, secuela', 'Sin especificar', '["cicatriz desgarro", "secuela herida piel", "piel dura rodilla"]'),
('S81.021A', 'Desgarro con cuerpo extraño de rodilla derecha, contacto inicial', 'Sin especificar', '["desgarro con astilla", "vidrio en la rodilla", "tierra en la herida", "algo clavado en la rodilla", "desgarro con basura en la herida", "rodilla sucia abierta"]'),
('S81.021D', 'Desgarro con cuerpo extraño de rodilla derecha, contacto sucesivo', 'Sin especificar', '["limpieza de herida contaminada", "quitar restos de herida", "curación tras extracción cuerpo extraño", "control infección rodilla"]'),
('S81.021S', 'Desgarro con cuerpo extraño de rodilla derecha, secuela', 'Sin especificar', '["cicatriz sucia", "infección residual", "secuela cuerpo extraño", "molestias por cicatriz interna"]'),
('S81.022A', 'Desgarro con cuerpo extraño de rodilla izquierda, contacto inicial', 'Sin especificar', '["desgarro con suciedad", "cristales en rodilla izquierda", "objeto en la rodilla", "herida contaminada rodilla"]'),
('S81.022D', 'Desgarro con cuerpo extraño de rodilla izquierda, contacto sucesivo', 'Sin especificar', '["lavado de herida", "quitar restos", "revisión herida abierta", "curación rodilla izquierda"]'),
('S81.022S', 'Desgarro con cuerpo extraño de rodilla izquierda, secuela', 'Sin especificar', '["cicatriz con mancha", "secuela herida contaminada", "dolor residual cuerpo extraño"]'),
('S81.029A', 'Desgarro con cuerpo extraño de rodilla no especificada, contacto inicial', 'Sin especificar', '["herida con objeto extraño", "rodilla deshecha con suciedad", "astilla en la rodilla", "vidrio en la piel"]'),
('S81.029D', 'Desgarro con cuerpo extraño de rodilla no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento herida sucia", "curación de restos", "revisión rodilla"]'),
('S81.029S', 'Desgarro con cuerpo extraño de rodilla no especificada, secuela', 'Sin especificar', '["secuela desgarro sucio", "cicatriz con restos", "problemas post desgarro"]'),
('S81.031A', 'Herida punzante sin cuerpo extraño de rodilla derecha, contacto inicial', 'Sin especificar', '["pinchazo en la rodilla", "perforación rodilla", "agujero en la rodilla", "herida de clavo rodilla", "rodilla pinchada"]'),
('S81.031D', 'Herida punzante sin cuerpo extraño de rodilla derecha, contacto sucesivo', 'Sin especificar', '["curar pinchazo rodilla", "seguimiento herida punzante", "control infección rodilla"]'),
('S81.031S', 'Herida punzante sin cuerpo extraño de rodilla derecha, secuela', 'Sin especificar', '["marca de pinchazo", "cicatriz punzante", "dolor crónico rodilla"]'),
('S81.032A', 'Herida punzante sin cuerpo extraño de rodilla izquierda, contacto inicial', 'Sin especificar', '["pinchazo rodilla izquierda", "agujero rodilla", "lesión punzante rodilla", "me piqué la rodilla"]'),
('S81.032D', 'Herida punzante sin cuerpo extraño de rodilla izquierda, contacto sucesivo', 'Sin especificar', '["curación pinchazo", "seguimiento herida perforante", "revisión punzada"]'),
('S81.032S', 'Herida punzante sin cuerpo extraño de rodilla izquierda, secuela', 'Sin especificar', '["cicatriz punto", "molestias por punzada", "secuela lesión rodilla"]'),
('S81.039A', 'Herida punzante sin cuerpo extraño de rodilla no especificada, contacto inicial', 'Sin especificar', '["pinchazo rodilla", "herida profunda rodilla", "punzada rodilla"]'),
('S81.039D', 'Herida punzante sin cuerpo extraño de rodilla no especificada, contacto sucesivo', 'Sin especificar', '["cura pinchazo", "seguimiento herida", "revisión médica"]'),
('S81.039S', 'Herida punzante sin cuerpo extraño de rodilla no especificada, secuela', 'Sin especificar', '["cicatriz puntada", "dolor secuela"]'),
('S81.041A', 'Herida punzante con cuerpo extraño de rodilla derecha, contacto inicial', 'Sin especificar', '["clavo en la rodilla", "objeto clavado rodilla", "astilla profunda rodilla", "rodilla atravesada"]'),
('S81.041D', 'Herida punzante con cuerpo extraño de rodilla derecha, contacto sucesivo', 'Sin especificar', '["retiro de objeto rodilla", "limpieza profunda rodilla", "seguimiento herida compleja"]'),
('S81.041S', 'Herida punzante con cuerpo extraño de rodilla derecha, secuela', 'Sin especificar', '["secuela herida profunda", "cicatriz compleja", "dolor persistente"]'),
('S81.042A', 'Herida punzante con cuerpo extraño de rodilla izquierda, contacto inicial', 'Sin especificar', '["algo clavado en la rodilla", "punzada con objeto", "rodilla herida profundo"]'),
('S81.042D', 'Herida punzante con cuerpo extraño de rodilla izquierda, contacto sucesivo', 'Sin especificar', '["curar punzada profunda", "revisión de herida", "limpieza rodilla"]'),
('S81.042S', 'Herida punzante con cuerpo extraño de rodilla izquierda, secuela', 'Sin especificar', '["cicatriz profunda", "daño residual rodilla"]'),
('S81.049A', 'Herida punzante con cuerpo extraño de rodilla no especificada, contacto inicial', 'Sin especificar', '["herida con clavo", "objeto clavado", "punzada con suciedad"]'),
('S81.049D', 'Herida punzante con cuerpo extraño de rodilla no especificada, contacto sucesivo', 'Sin especificar', '["limpieza de objeto", "seguimiento herida", "control médico"]'),
('S81.049S', 'Herida punzante con cuerpo extraño de rodilla no especificada, secuela', 'Sin especificar', '["cicatriz de punzada", "secuela de lesión"]'),
('S81.051A', 'Mordedura abierta en rodilla derecha, contacto inicial', 'Sin especificar', '["mordida en la rodilla", "perro me mordió la rodilla", "mordedura animal rodilla", "herida por mordida"]'),
('S81.051D', 'Mordedura abierta en rodilla derecha, contacto sucesivo', 'Sin especificar', '["curar mordedura rodilla", "seguimiento mordida perro", "prevención rabia rodilla", "limpieza herida mordida"]'),
('S81.051S', 'Mordedura abierta en rodilla derecha, secuela', 'Sin especificar', '["cicatriz mordida", "marca de mordedura", "infección secundaria mordida"]'),
('S81.052A', 'Mordedura abierta en rodilla izquierda, contacto inicial', 'Sin especificar', '["mordida rodilla izquierda", "me mordió un perro rodilla", "herida por dientes rodilla"]'),
('S81.052D', 'Mordedura abierta en rodilla izquierda, contacto sucesivo', 'Sin especificar', '["curación mordedura", "control herida mordida", "limpieza infección"]'),
('S81.052S', 'Mordedura abierta en rodilla izquierda, secuela', 'Sin especificar', '["cicatriz por mordida", "daño tisular mordida"]'),
('S81.059A', 'Mordedura abierta en rodilla no especificada, contacto inicial', 'Sin especificar', '["mordedura en rodilla", "me mordieron la rodilla", "herida animal"]'),
('S81.059D', 'Mordedura abierta en rodilla no especificada, contacto sucesivo', 'Sin especificar', '["curación mordedura", "seguimiento herida animal", "control"]'),
('S81.059S', 'Mordedura abierta en rodilla no especificada, secuela', 'Sin especificar', '["cicatriz mordedura", "secuela herida"]'),
('S81.801A', 'Herida abierta no especificada de pierna derecha, contacto inicial', 'Sin especificar', '["corte en la pierna", "herida en la canilla", "raja en la pierna", "sangre pierna derecha", "tajo pierna"]'),
('S81.801D', 'Herida abierta no especificada de pierna derecha, contacto sucesivo', 'Sin especificar', '["cura de pierna", "seguimiento corte pierna", "revisión sutura pierna", "limpieza herida"]'),
('S81.801S', 'Herida abierta no especificada de pierna derecha, secuela', 'Sin especificar', '["cicatriz en la pierna", "secuela de corte", "dolor pierna cicatriz"]'),
('S81.802A', 'Herida abierta no especificada de pierna izquierda, contacto inicial', 'Sin especificar', '["corte pierna izquierda", "herida en la pata", "tajo pierna", "rasguño profundo"]'),
('S81.802D', 'Herida abierta no especificada de pierna izquierda, contacto sucesivo', 'Sin especificar', '["seguimiento herida pierna", "curación pierna", "control sutura"]'),
('S81.802S', 'Herida abierta no especificada de pierna izquierda, secuela', 'Sin especificar', '["cicatriz pierna izquierda", "marca corte", "secuela piel"]'),
('S81.809A', 'Herida abierta no especificada de pierna no especificada, contacto inicial', 'Sin especificar', '["corte en la pierna", "herida pierna", "tajo", "me corté la pierna"]'),
('S81.809D', 'Herida abierta no especificada de pierna no especificada, contacto sucesivo', 'Sin especificar', '["cura herida", "seguimiento", "revisión"]'),
('S81.809S', 'Herida abierta no especificada de pierna no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela herida"]'),
('S81.811A', 'Desgarro sin cuerpo extraño de pierna derecha, contacto inicial', 'Sin especificar', '["desgarro piel pierna", "piel abierta pierna", "despellejada", "rasgón"]'),
('S81.811D', 'Desgarro sin cuerpo extraño de pierna derecha, contacto sucesivo', 'Sin especificar', '["seguimiento desgarro", "curación piel", "revisión"]'),
('S81.811S', 'Desgarro sin cuerpo extraño de pierna derecha, secuela', 'Sin especificar', '["cicatriz desgarro", "secuela piel"]'),
('S81.812A', 'Desgarro sin cuerpo extraño de pierna izquierda, contacto inicial', 'Sin especificar', '["desgarro piel pierna izquierda", "herida piel", "despellejada"]'),
('S81.812D', 'Desgarro sin cuerpo extraño de pierna izquierda, contacto sucesivo', 'Sin especificar', '["cura desgarro", "seguimiento", "control"]'),
('S81.812S', 'Desgarro sin cuerpo extraño de pierna izquierda, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S81.819A', 'Desgarro sin cuerpo extraño de pierna no especificada, contacto inicial', 'Sin especificar', '["desgarro piel", "herida abierta", "piel levantada"]'),
('S81.819D', 'Desgarro sin cuerpo extraño de pierna no especificada, contacto sucesivo', 'Sin especificar', '["seguimiento", "curar", "limpiar"]'),
('S81.819S', 'Desgarro sin cuerpo extraño de pierna no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S81.821A', 'Desgarro con cuerpo extraño de pierna derecha, contacto inicial', 'Sin especificar', '["desgarro con astilla pierna", "vidrio en la piel", "tierra en la herida", "objeto en pierna"]'),
('S81.821D', 'Desgarro con cuerpo extraño de pierna derecha, contacto sucesivo', 'Sin especificar', '["limpieza herida con restos", "retiro cuerpo extraño", "seguimiento"]'),
('S81.821S', 'Desgarro con cuerpo extraño de pierna derecha, secuela', 'Sin especificar', '["cicatriz con restos", "infección residual", "secuela"]'),
('S81.822A', 'Desgarro con cuerpo extraño de pierna izquierda, contacto inicial', 'Sin especificar', '["desgarro con suciedad", "cristales en la pierna", "objeto extraño"]'),
('S81.822D', 'Desgarro con cuerpo extraño de pierna izquierda, contacto sucesivo', 'Sin especificar', '["lavado herida", "curación pierna", "revisión"]'),
('S81.822S', 'Desgarro con cuerpo extraño de pierna izquierda, secuela', 'Sin especificar', '["cicatriz manchada", "secuela cuerpo extraño"]'),
('S81.829A', 'Desgarro con cuerpo extraño de pierna no especificada, contacto inicial', 'Sin especificar', '["herida con objeto", "pierna deshecha con suciedad", "astilla"]'),
('S81.829D', 'Desgarro con cuerpo extraño de pierna no especificada, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "limpieza"]'),
('S81.829S', 'Desgarro con cuerpo extraño de pierna no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S81.831A', 'Herida punzante sin cuerpo extraño de pierna derecha, contacto inicial', 'Sin especificar', '["pinchazo en la pierna", "perforación pierna", "agujero pierna", "herida clavo"]'),
('S81.831D', 'Herida punzante sin cuerpo extraño de pierna derecha, contacto sucesivo', 'Sin especificar', '["curar pinchazo", "seguimiento herida", "control"]'),
('S81.831S', 'Herida punzante sin cuerpo extraño de pierna derecha, secuela', 'Sin especificar', '["marca pinchazo", "cicatriz", "dolor"]'),
('S81.832A', 'Herida punzante sin cuerpo extraño de pierna izquierda, contacto inicial', 'Sin especificar', '["pinchazo pierna izquierda", "agujero", "lesión punzante"]'),
('S81.832D', 'Herida punzante sin cuerpo extraño de pierna izquierda, contacto sucesivo', 'Sin especificar', '["cura pinchazo", "seguimiento", "revisión"]'),
('S81.832S', 'Herida punzante sin cuerpo extraño de pierna izquierda, secuela', 'Sin especificar', '["cicatriz", "molestias"]'),
('S81.839A', 'Herida punzante sin cuerpo extraño de pierna no especificada, contacto inicial', 'Sin especificar', '["pinchazo pierna", "herida profunda", "punzada"]'),
('S81.839D', 'Herida punzante sin cuerpo extraño de pierna no especificada, contacto sucesivo', 'Sin especificar', '["cura", "seguimiento", "revisión"]'),
('S81.839S', 'Herida punzante sin cuerpo extraño de pierna no especificada, secuela', 'Sin especificar', '["cicatriz", "dolor"]'),
('S81.841A', 'Herida punzante con cuerpo extraño de pierna derecha, contacto inicial', 'Sin especificar', '["clavo en la pierna", "objeto clavado", "astilla profunda", "pierna atravesada"]'),
('S81.841D', 'Herida punzante con cuerpo extraño de pierna derecha, contacto sucesivo', 'Sin especificar', '["retiro objeto", "limpieza profunda", "seguimiento"]'),
('S81.841S', 'Herida punzante con cuerpo extraño de pierna derecha, secuela', 'Sin especificar', '["secuela", "cicatriz", "dolor"]'),
('S81.842A', 'Herida punzante con cuerpo extraño de pierna izquierda, contacto inicial', 'Sin especificar', '["objeto en pierna", "punzada con objeto", "herida profundo"]'),
('S81.842D', 'Herida punzante con cuerpo extraño de pierna izquierda, contacto sucesivo', 'Sin especificar', '["curar punzada", "revisión", "limpieza"]'),
('S81.842S', 'Herida punzante con cuerpo extraño de pierna izquierda, secuela', 'Sin especificar', '["cicatriz", "daño residual"]'),
('S81.849A', 'Herida punzante con cuerpo extraño de pierna no especificada, contacto inicial', 'Sin especificar', '["herida con clavo", "objeto clavado", "punzada sucia"]'),
('S81.849D', 'Herida punzante con cuerpo extraño de pierna no especificada, contacto sucesivo', 'Sin especificar', '["limpieza", "seguimiento", "control"]'),
('S81.849S', 'Herida punzante con cuerpo extraño de pierna no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]'),
('S81.851A', 'Mordedura abierta en pierna derecha, contacto inicial', 'Sin especificar', '["mordida en la pierna", "perro me mordió", "mordedura animal pierna", "herida por dientes"]'),
('S81.851D', 'Mordedura abierta en pierna derecha, contacto sucesivo', 'Sin especificar', '["curar mordida pierna", "seguimiento mordida", "limpieza"]'),
('S81.851S', 'Mordedura abierta en pierna derecha, secuela', 'Sin especificar', '["cicatriz mordida", "marca", "infección"]'),
('S81.852A', 'Mordedura abierta en pierna izquierda, contacto inicial', 'Sin especificar', '["mordida pierna izquierda", "mordida animal", "herida dientes"]'),
('S81.852D', 'Mordedura abierta en pierna izquierda, contacto sucesivo', 'Sin especificar', '["curación", "control herida", "limpieza"]'),
('S81.852S', 'Mordedura abierta en pierna izquierda, secuela', 'Sin especificar', '["cicatriz", "daño"]'),
('S81.859A', 'Mordedura abierta en pierna no especificada, contacto inicial', 'Sin especificar', '["mordedura pierna", "me mordieron", "herida animal"]'),
('S81.859D', 'Mordedura abierta en pierna no especificada, contacto sucesivo', 'Sin especificar', '["curación", "seguimiento", "control"]'),
('S81.859S', 'Mordedura abierta en pierna no especificada, secuela', 'Sin especificar', '["cicatriz", "secuela"]');
