INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('L23.0', 'Dermatitis alérgica de contacto debida a metales', 'Sin especificar', '["alergia a metales", "picazón por reloj", "alergia a la bisutería", "dermatitis por hebilla", "ronchas por anillos", "irritación por níquel", "piel roja por aros", "eccema por metales", "picor en la piel", "reacción alérgica al metal", "dermatitis de contacto", "sarpullido por cadenas", "piel irritada por metales", "alergia a pendientes", "erupción cutánea", "alergia a pulseras"]'),
('L23.1', 'Dermatitis alérgica de contacto debida a adhesivos', 'Sin especificar', '["alergia a curitas", "irritación por cintas", "alergia al pegamento", "ronchas por vendajes", "dermatitis por apósitos", "piel irritada por adhesivo", "picazón por esparadrapo", "alergia a cintas médicas", "reacción a parches", "dermatitis por pegamento", "eccema por adhesivos", "sarpullido por parches", "piel roja por cinta", "alergia a adhesivos de pestañas", "erupción por pegamento"]'),
('L23.2', 'Dermatitis alérgica de contacto debida a cosméticos', 'Sin especificar', '["alergia al maquillaje", "reacción a cremas", "piel irritada por labial", "picazón por sombras", "ronchas por cosméticos", "dermatitis por loción", "alergia a perfumes", "sarpullido por base de maquillaje", "piel roja por crema", "eccema por maquillaje", "dermatitis de contacto facial", "reacción a serums", "irritación por delineador", "alergia a productos de belleza", "erupción por cosméticos"]'),
('L23.3', 'Dermatitis alérgica de contacto debida a drogas en contacto con piel', 'Sin especificar', '["alergia a pomadas", "reacción a ungüentos", "irritación por cremas medicinales", "picazón por medicamentos tópicos", "dermatitis por medicación", "piel roja por pomada", "ronchas por cremas", "sarpullido por fármacos", "alergia a antibióticos tópicos", "erupción por medicamentos", "eccema por cremas", "dermatitis farmacológica", "reacción cutánea a medicamentos", "piel irritada por ungüentos", "alergia al contacto con medicinas"]'),
('L23.4', 'Dermatitis alérgica de contacto debida a colorantes', 'Sin especificar', '["alergia a tintes", "reacción a colorantes de ropa", "picazón por ropa nueva", "dermatitis por tintes textiles", "irritación por colorantes", "ronchas por teñido", "piel roja por ropa", "eccema por tintes", "sarpullido por telas", "alergia a la ropa", "erupción por pigmentos", "dermatitis por colorantes", "irritación por colorante de cabello", "alergia a cueros teñidos", "picor por colorantes"]'),
('L23.5', 'Dermatitis alérgica de contacto debida a otros productos químicos', 'Sin especificar', '["alergia a químicos", "irritación por productos de limpieza", "picazón por detergentes", "dermatitis por solventes", "reacción a químicos industriales", "piel roja por desinfectantes", "ronchas por productos de aseo", "eccema por químicos", "sarpullido por sustancias", "alergia a jabones fuertes", "erupción por contacto químico", "dermatitis química", "quemazón por químicos", "irritación por lejía", "alergia laboral a químicos"]'),
('L23.6', 'Dermatitis alérgica de contacto debida a alimentos en contacto con la piel', 'Sin especificar', '["alergia a alimentos en la piel", "reacción a frutas", "picazón al pelar verduras", "dermatitis por contacto alimentario", "irritación por cítricos", "ronchas por comida", "piel roja por manipular alimentos", "sarpullido por vegetales", "eccema por contacto con alimentos", "alergia a especias en la piel", "erupción por zumos de frutas", "alergia al látex de frutas", "picor por manipulación de comida", "dermatitis por manipulación de hortalizas", "reacción a alimentos"]'),
('L23.7', 'Dermatitis alérgica de contacto debida a plantas, excepto las alimenticias', 'Sin especificar', '["alergia a plantas", "picazón por hiedra", "sarpullido por plantas", "ronchas por hierbas", "dermatitis por maleza", "irritación por plantas silvestres", "reacción a polen de plantas", "piel roja por contacto con hojas", "eccema por plantas", "erupción por flores", "alergia al contacto con flores", "picor por plantas de jardín", "dermatitis por savia", "reacción alérgica a arbustos", "erupción cutánea por naturaleza"]'),
('L23.81', 'Dermatitis alérgica de contacto por caspa de animales (gato) (perro)', 'Sin especificar', '["alergia a perros", "alergia a gatos", "picazón por mascotas", "reacción al pelaje", "dermatitis por caspa animal", "ronchas por tocar animales", "piel roja por animales", "sarpullido por mascota", "eccema por caspa de perro", "alergia a animales", "erupción por contacto con gato", "picor por animales", "dermatitis por pelo de mascota", "reacción alérgica a caspa", "irritación al acariciar animales"]'),
('L23.89', 'Dermatitis alérgica de contacto debida a otros agentes', 'Sin especificar', '["dermatitis alérgica", "alergia cutánea", "sarpullido desconocido", "irritación misteriosa", "ronchas por contacto", "eccema de contacto", "picazón intensa", "piel irritada", "erupción cutánea inespecífica", "reacción alérgica en piel", "dermatitis inespecífica", "picor corporal", "piel roja irritada", "alergia de piel", "dermatitis no clasificada"]'),
('L23.9', 'Dermatitis alérgica de contacto, de causa no especificada', 'Sin especificar', '["dermatitis alérgica", "alergia cutánea sin causa", "picor repentino", "sarpullido de contacto", "ronchas sin explicación", "eccema por causa desconocida", "irritación dermatológica", "alergia de piel por contacto", "erupción de causa incierta", "dermatitis de origen desconocido", "piel irritada sin motivo", "picazón por contacto", "alergia inexplicable", "dermatitis por agente no identificado", "reacción alérgica de contacto"]');
