INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('M99.00', 'Disfunción segmentaria y somática, región de la cabeza', 'Sin especificar', '["dolor de cabeza", "jaqueca", "migraña", "tensión craneal", "dolor en la nuca", "cabeza pesada", "vértigo por tensión", "punzadas en la cabeza", "dolor de cráneo", "presión en la cabeza", "contractura cervical alta", "dolor de casco", "rigidez de cuello"]'),
('M99.01', 'Disfunción segmentaria y somática, región cervical', 'Sin especificar', '["dolor de cuello", "cuello tieso", "tortícolis", "cervicalgia", "dolor de nuca", "cuello trabado", "pesadez de cuello", "tensión cervical", "cuello duro", "molestias en las vértebras del cuello", "dolor de espalda alta", "cuello engarrotado"]'),
('M99.02', 'Disfunción segmentaria y somática, región dorsal', 'Sin especificar', '["dolor de espalda alta", "dolor entre los omóplatos", "espalda trabada", "dolor dorsal", "nudos en la espalda", "tensión en la parte media", "dolor interescapular", "espalda rígida", "pinchazos en la espalda", "dolor de columna dorsal", "espalda cansada"]'),
('M99.03', 'Disfunción segmentaria y somática, región lumbar', 'Sin especificar', '["dolor de cintura", "lumbalgia", "riñones afectados", "dolor en la rabadilla", "espalda baja trabada", "lumbago", "ciática", "dolor de cadera", "tirón en la cintura", "espalda baja rígida", "pinchazo en la cintura", "dolor sacro"]'),
('M99.04', 'Disfunción segmentaria y somática, región sacra', 'Sin especificar', '["dolor de coxis", "dolor en el sacro", "dolor de rabadilla", "molestia en la base de la columna", "dolor al sentarse", "dolor en el traste", "sacralgia", "lesión en la rabadilla", "dolor bajo de espalda"]'),
('M99.05', 'Disfunción segmentaria y somática, región pélvica', 'Sin especificar', '["dolor de cadera", "dolor pélvico", "molestia en la ingle", "dolor de pelvis", "caderas trabadas", "disfunción de cadera", "dolor al caminar", "pinchazo en la pelvis", "cadera encajada"]'),
('M99.06', 'Disfunción segmentaria y somática, extremidad inferior', 'Sin especificar', '["dolor de pierna", "pierna trabada", "dolor de rodilla", "dolor de tobillo", "dolor en el muslo", "molestia en la pierna", "cojera", "pierna rígida", "problemas articulares pierna", "dolor en pie"]'),
('M99.07', 'Disfunción segmentaria y somática, extremidad superior', 'Sin especificar', '["dolor de brazo", "dolor de hombro", "dolor de codo", "dolor de muñeca", "brazo entumecido", "hombro trabado", "dolor en la mano", "brazo rígido", "molestia articular brazo"]'),
('M99.08', 'Disfunción segmentaria y somática, caja torácica', 'Sin especificar', '["dolor en el pecho", "costillas trabadas", "dolor al respirar", "opresión torácica", "dolor intercostal", "pinchazo en las costillas", "pecho rígido", "dolor de costado"]'),
('M99.09', 'Disfunción segmentaria y somática, abdomen y otras regiones', 'Sin especificar', '["dolor abdominal", "dolor de panza", "dolor de guata", "dolor de barriga", "indigestión muscular", "tensión abdominal", "dolor de vientre", "espasmo muscular abdomen"]'),
('M99.10', 'Complejo de subluxación (vertebral) de región de cabeza', 'Sin especificar', '["vértebra movida", "hueso fuera de lugar cabeza", "subluxación cabeza", "vértebra desajustada", "desalineación cervical alta", "columna movida"]'),
('M99.11', 'Complejo de subluxación (vertebral) de región cervical', 'Sin especificar', '["vértebra cervical movida", "cuello desalineado", "subluxación de cuello", "hueso del cuello fuera de sitio", "vértebra trabada cuello", "cervicales movidas"]'),
('M99.12', 'Complejo de subluxación (vertebral) de región dorsal', 'Sin especificar', '["vértebra dorsal movida", "subluxación de espalda", "columna desajustada dorsal", "hueso de la espalda fuera de lugar", "vértebra dorsal encajada"]'),
('M99.13', 'Complejo de subluxación (vertebral) de región lumbar', 'Sin especificar', '["vértebra lumbar movida", "subluxación lumbar", "desajuste de cintura", "vértebra de la cintura movida", "columna lumbar desalineada", "hueso de la cintura fuera de sitio"]'),
('M99.14', 'Complejo de subluxación (vertebral) de región sacra', 'Sin especificar', '["subluxación sacra", "hueso sacro movido", "desalineación de rabadilla", "vértebra sacra fuera de lugar"]'),
('M99.15', 'Complejo de subluxación (vertebral) de región pélvica', 'Sin especificar', '["cadera movida", "subluxación pélvica", "pelvis desalineada", "cadera fuera de sitio", "hueso de la cadera movido"]'),
('M99.16', 'Complejo de subluxación (vertebral) de extremidad inferior', 'Sin especificar', '["articulación movida pierna", "subluxación rodilla", "hueso fuera de lugar pierna", "tobillo desajustado"]'),
('M99.17', 'Complejo de subluxación (vertebral) de extremidad superior', 'Sin especificar', '["subluxación hombro", "articulación brazo movida", "hueso del hombro fuera de sitio", "muñeca desajustada"]'),
('M99.18', 'Complejo de subluxación (vertebral) de caja torácica', 'Sin especificar', '["costilla movida", "subluxación costal", "costilla fuera de lugar", "vértebra torácica desalineada"]'),
('M99.19', 'Complejo de subluxación (vertebral) de abdomen y otras regiones', 'Sin especificar', '["subluxación abdominal", "desajuste vertebral abdomen", "vértebra movida abdomen"]'),
('M99.20', 'Estenosis por subluxación del conducto vertebral, región de la cabeza', 'Sin especificar', '["conducto estrecho cabeza", "nervio pinzado cabeza", "canal estrecho cervical alto", "compresión nerviosa cabeza"]'),
('M99.21', 'Estenosis por subluxación del conducto vertebral, región cervical', 'Sin especificar', '["canal estrecho cervical", "nervio apretado cuello", "estenosis de cuello", "compresión de médula cuello", "hormigueo en brazos por cuello"]'),
('M99.22', 'Estenosis por subluxación del conducto vertebral, región dorsal', 'Sin especificar', '["canal estrecho dorsal", "nervio pinzado espalda alta", "estenosis de espalda", "compresión de espalda"]'),
('M99.23', 'Estenosis por subluxación del conducto vertebral, región lumbar', 'Sin especificar', '["canal estrecho lumbar", "nervio ciático apretado", "estenosis lumbar", "compresión nerviosa cintura", "dolor de ciática por canal estrecho"]'),
('M99.24', 'Estenosis por subluxación del conducto vertebral, región sacra', 'Sin especificar', '["canal estrecho sacro", "estenosis sacra", "nervio presionado sacro"]'),
('M99.25', 'Estenosis por subluxación del conducto vertebral, región pélvica', 'Sin especificar', '["estrechez de canal pélvico", "compresión nerviosa pelvis"]'),
('M99.26', 'Estenosis por subluxación del conducto vertebral, extremidad inferior', 'Sin especificar', '["nervio pinzado pierna", "compresión nerviosa pierna", "canal estrecho pierna"]'),
('M99.27', 'Estenosis por subluxación del conducto vertebral, extremidad superior', 'Sin especificar', '["nervio pinzado brazo", "compresión nerviosa brazo", "canal estrecho brazo"]'),
('M99.28', 'Estenosis por subluxación del conducto vertebral, caja torácica', 'Sin especificar', '["estrechez torácica", "nervio pinzado tórax", "canal estrecho tórax"]'),
('M99.29', 'Estenosis por subluxación del conducto vertebral, abdomen y otras regiones', 'Sin especificar', '["estrechez abdominal", "nervio pinzado abdomen"]'),
('M99.30', 'Estenosis ósea del conducto vertebral, región de la cabeza', 'Sin especificar', '["hueso crecido cabeza", "estenosis ósea craneal", "espolón óseo cabeza"]'),
('M99.31', 'Estenosis ósea del conducto vertebral, región cervical', 'Sin especificar', '["espolones en el cuello", "huesos del cuello crecidos", "estenosis ósea cervical", "artrosis cervical severa"]'),
('M99.32', 'Estenosis ósea del conducto vertebral, región dorsal', 'Sin especificar', '["huesos crecidos espalda alta", "estenosis ósea dorsal", "espolón dorsal"]'),
('M99.33', 'Estenosis ósea del conducto vertebral, región lumbar', 'Sin especificar', '["huesos crecidos cintura", "estenosis ósea lumbar", "espolones lumbares", "desgaste óseo lumbar"]'),
('M99.34', 'Estenosis ósea del conducto vertebral, región sacra', 'Sin especificar', '["huesos crecidos sacro", "estenosis ósea sacra", "espolón sacro"]'),
('M99.35', 'Estenosis ósea del conducto vertebral, región pélvica', 'Sin especificar', '["huesos crecidos pelvis", "estenosis ósea pélvica"]'),
('M99.36', 'Estenosis ósea del conducto vertebral, extremidad inferior', 'Sin especificar', '["huesos crecidos pierna", "espolón óseo pierna", "estenosis ósea pierna"]'),
('M99.37', 'Estenosis ósea del conducto vertebral, extremidad superior', 'Sin especificar', '["huesos crecidos brazo", "espolón óseo brazo", "estenosis ósea brazo"]'),
('M99.38', 'Estenosis ósea del conducto vertebral, caja torácica', 'Sin especificar', '["huesos crecidos tórax", "estenosis ósea torácica"]'),
('M99.39', 'Estenosis ósea del conducto vertebral, abdomen y otras regiones', 'Sin especificar', '["estenosis ósea abdominal", "crecimiento óseo abdomen"]'),
('M99.40', 'Estenosis por tejido conjuntivo del conducto vertebral, región de la cabeza', 'Sin especificar', '["tejido fibroso cabeza", "estrechez por tejido cabeza"]'),
('M99.41', 'Estenosis por tejido conjuntivo del conducto vertebral, región cervical', 'Sin especificar', '["fibrosis cervical", "tejido apretando cuello", "estenosis por tejido cuello"]'),
('M99.42', 'Estenosis por tejido conjuntivo del conducto vertebral, región dorsal', 'Sin especificar', '["fibrosis dorsal", "tejido apretando espalda alta"]'),
('M99.43', 'Estenosis por tejido conjuntivo del conducto vertebral, región lumbar', 'Sin especificar', '["fibrosis lumbar", "tejido apretando cintura", "estenosis por tejido lumbar"]'),
('M99.44', 'Estenosis por tejido conjuntivo del conducto vertebral, región sacra', 'Sin especificar', '["fibrosis sacra", "tejido apretando sacro"]'),
('M99.45', 'Estenosis por tejido conjuntivo del conducto vertebral, región pélvica', 'Sin especificar', '["fibrosis pélvica", "tejido apretando pelvis"]'),
('M99.46', 'Estenosis por tejido conjuntivo del conducto vertebral, extremidad inferior', 'Sin especificar', '["fibrosis pierna", "tejido apretando pierna"]'),
('M99.47', 'Estenosis por tejido conjuntivo del conducto vertebral, extremidad superior', 'Sin especificar', '["fibrosis brazo", "tejido apretando brazo"]'),
('M99.48', 'Estenosis por tejido conjuntivo del conducto vertebral, caja torácica', 'Sin especificar', '["fibrosis torácica", "tejido apretando tórax"]'),
('M99.49', 'Estenosis por tejido conjuntivo del conducto vertebral, abdomen y otras regiones', 'Sin especificar', '["fibrosis abdominal", "tejido apretando abdomen"]'),
('M99.50', 'Estenosis por disco intervertebral del conducto vertebral, región de la cabeza', 'Sin especificar', '["disco movido cabeza", "hernia discal alta"]'),
('M99.51', 'Estenosis por disco intervertebral del conducto vertebral, región cervical', 'Sin especificar', '["hernia cervical", "disco herniado cuello", "disco que aprieta cuello", "dolor de brazo por hernia"]'),
('M99.52', 'Estenosis por disco intervertebral del conducto vertebral, región dorsal', 'Sin especificar', '["hernia dorsal", "disco herniado espalda alta"]'),
('M99.53', 'Estenosis por disco intervertebral del conducto vertebral, región lumbar', 'Sin especificar', '["hernia discal", "disco herniado cintura", "hernia lumbar", "dolor de pierna por hernia", "ciática por disco"]'),
('M99.54', 'Estenosis por disco intervertebral del conducto vertebral, región sacra', 'Sin especificar', '["hernia sacra", "disco herniado sacro"]'),
('M99.55', 'Estenosis por disco intervertebral del conducto vertebral, región pélvica', 'Sin especificar', '["hernia pélvica", "problema de disco pelvis"]'),
('M99.56', 'Estenosis por disco intervertebral del conducto vertebral, extremidad inferior', 'Sin especificar', '["hernia pierna", "disco herniado pierna"]'),
('M99.57', 'Estenosis por disco intervertebral del conducto vertebral, extremidad superior', 'Sin especificar', '["hernia brazo", "disco herniado brazo"]'),
('M99.58', 'Estenosis por disco intervertebral del conducto vertebral, caja torácica', 'Sin especificar', '["hernia tórax", "disco herniado tórax"]'),
('M99.59', 'Estenosis por disco intervertebral del conducto vertebral, abdomen y otras regiones', 'Sin especificar', '["hernia abdominal", "disco herniado abdomen"]'),
('M99.60', 'Estenosis ósea y por subluxación de agujeros intervertebrales, región de la cabeza', 'Sin especificar', '["agujero apretado cabeza", "nervio aplastado cabeza", "estenosis de agujeros"]'),
('M99.61', 'Estenosis ósea y por subluxación de agujeros intervertebrales, región cervical', 'Sin especificar', '["agujero de conjunción estrecho", "nervio aprisionado cuello", "agujero intervertebral bloqueado"]'),
('M99.62', 'Estenosis ósea y por subluxación de agujeros intervertebrales, región dorsal', 'Sin especificar', '["agujero de conjunción bloqueado dorsal", "nervio atrapado espalda"]'),
('M99.63', 'Estenosis ósea y por subluxación de agujeros intervertebrales, región lumbar', 'Sin especificar', '["agujero de conjunción estrecho lumbar", "nervio apretado espalda baja"]'),
('M99.64', 'Estenosis ósea y por subluxación de los agujeros intervertebrales, región sacra', 'Sin especificar', '["agujero sacro estrecho", "nervio bloqueado sacro"]'),
('M99.65', 'Estenosis ósea y por subluxación de los agujeros intervertebrales, región pélvica', 'Sin especificar', '["agujero pélvico bloqueado", "compresión nerviosa pelvis"]'),
('M99.66', 'Estenosis ósea y por subluxación de los agujeros intervertebrales, extremidad inferior', 'Sin especificar', '["agujero bloqueado pierna", "nervio atrapado pierna"]'),
('M99.67', 'Estenosis ósea y por subluxación de los agujeros intervertebrales, extremidad superior', 'Sin especificar', '["agujero bloqueado brazo", "nervio atrapado brazo"]'),
('M99.68', 'Estenosis ósea y por subluxación de los agujeros intervertebrales, caja torácica', 'Sin especificar', '["agujero tórax bloqueado", "nervio apretado tórax"]'),
('M99.69', 'Estenosis ósea y por subluxación de los agujeros intervertebrales, abdomen y otras regiones', 'Sin especificar', '["agujero abdomen bloqueado", "nervio atrapado abdomen"]'),
('M99.70', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de región de la cabeza', 'Sin especificar', '["disco y tejido tapando agujero cabeza", "compresión nerviosa cabeza"]'),
('M99.71', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de región cervical', 'Sin especificar', '["nervio pinzado por disco cuello", "agujero cervical tapado"]'),
('M99.72', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de región dorsal', 'Sin especificar', '["nervio pinzado por disco dorsal", "agujero dorsal tapado"]'),
('M99.73', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de región lumbar', 'Sin especificar', '["nervio pinzado por disco lumbar", "agujero lumbar tapado"]'),
('M99.74', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de región sacra', 'Sin especificar', '["nervio pinzado por disco sacro", "agujero sacro tapado"]'),
('M99.75', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de región pélvica', 'Sin especificar', '["nervio pinzado por tejido pelvis", "agujero pélvico tapado"]'),
('M99.76', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de extremidad inferior', 'Sin especificar', '["agujero pierna tapado", "nervio atrapado pierna"]'),
('M99.77', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de extremidad superior', 'Sin especificar', '["agujero brazo tapado", "nervio atrapado brazo"]'),
('M99.78', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de caja torácica', 'Sin especificar', '["agujero tórax tapado", "nervio apretado tórax"]'),
('M99.79', 'Estenosis de los agujeros intervertebrales por tejido conjuntivo o por disco intervertebral de abdomen y otras regiones', 'Sin especificar', '["agujero abdomen tapado", "nervio atrapado abdomen"]'),
('M99.80', 'Otras lesiones biomecánicas de la región de cabeza', 'Sin especificar', '["lesión cabeza", "golpe cabeza", "problema mecánico cabeza", "traumatismo menor cabeza"]'),
('M99.81', 'Otras lesiones biomecánicas de la región cervical', 'Sin especificar', '["lesión cuello", "latigazo cervical", "problema mecánico cuello", "tensión cuello"]'),
('M99.82', 'Otras lesiones biomecánicas de la región torácica', 'Sin especificar', '["lesión espalda alta", "problema mecánico dorsal", "golpe espalda"]'),
('M99.83', 'Otras lesiones biomecánicas de la región lumbar', 'Sin especificar', '["lesión lumbar", "problema mecánico cintura", "tensión espalda baja"]'),
('M99.84', 'Otras lesiones biomecánicas de la región sacra', 'Sin especificar', '["lesión sacra", "problema mecánico rabadilla"]'),
('M99.85', 'Otras lesiones biomecánicas de la región pélvica', 'Sin especificar', '["lesión pélvica", "problema mecánico cadera"]'),
('M99.86', 'Otras lesiones biomecánicas de extremidades inferiores', 'Sin especificar', '["lesión pierna", "esguince pierna", "problema articular pierna"]'),
('M99.87', 'Otras lesiones biomecánicas de extremidades superiores', 'Sin especificar', '["lesión brazo", "esguince brazo", "problema articular brazo"]'),
('M99.88', 'Otras lesiones biomecánicas de caja torácica', 'Sin especificar', '["lesión costillas", "golpe tórax", "problema mecánico costillas"]'),
('M99.89', 'Otras lesiones biomecánicas del abdomen y de otras regiones', 'Sin especificar', '["lesión abdominal", "golpe vientre", "problema mecánico abdomen"]'),
('M99.9', 'Lesión biomecánica, no especificada', 'Sin especificar', '["lesión desconocida", "golpe no especificado", "dolor sin causa clara", "molestia corporal general", "problema óseo no definido"]');
