INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('W61.01XA', 'Mordido por loro, contacto inicial', 'Sin especificar', '["mordida de loro", "mi loro me mordió", "dedo mordido por loro", "herida por loro", "ataque de loro", "loro agresivo", "me picó el loro", "picotazo de loro", "sangre por loro", "urgencias por loro", "accidente con loro", "lesión por ave", "mordida de cotorra", "loro me rompió la piel"]'),
('W61.01XD', 'Mordido por loro, contacto sucesivo', 'Sin especificar', '["cura de mordida de loro", "seguimiento mordida loro", "herida de loro infectada", "curación por picotazo loro", "revisión herida loro", "control mordedura loro", "dolor persistente por loro", "infección por mordida de ave", "limpieza de herida por loro", "punto por loro"]'),
('W61.01XS', 'Mordido por loro, secuela', 'Sin especificar', '["cicatriz de mordida de loro", "secuelas de picotazo", "dolor crónico por loro", "deformidad por picotazo", "problema articular por mordida", "rigidez tras mordida de loro", "cicatriz queloide por ave", "dificultad movimiento por loro"]'),
('W61.02XA', 'Golpeado por loro, contacto inicial', 'Sin especificar', '["golpe de loro", "loro me pegó", "ala de loro golpe", "trompazo de loro", "lorazo", "traumatismo por loro", "loro me dio un aletazo", "contusión por ave", "golpe con pico de loro", "moretón por loro"]'),
('W61.02XD', 'Golpeado por loro, contacto sucesivo', 'Sin especificar', '["revisión golpe loro", "seguimiento contusión loro", "dolor post golpe ave", "revisión aletazo loro", "control traumatismo loro", "revisión moretón por loro"]'),
('W61.02XS', 'Golpeado por loro, secuela', 'Sin especificar', '["secuela golpe loro", "dolor residual aletazo", "lesión antigua por loro", "molestia crónica por golpe de ave", "fibrosis por golpe de loro"]'),
('W61.09XA', 'Otro contacto con loro, contacto inicial', 'Sin especificar', '["rasguño de loro", "garra de loro", "arañazo de loro", "frotamiento con loro", "contacto con plumas loro", "alergia por contacto loro", "picada de loro", "accidente doméstico con loro"]'),
('W61.09XD', 'Otro contacto con loro, contacto sucesivo', 'Sin especificar', '["seguimiento raspadura loro", "revisión rasguño loro", "cura arañazo loro", "control dermatológico loro"]'),
('W61.09XS', 'Otro contacto con loro, secuela', 'Sin especificar', '["cicatriz por garra loro", "secuela rasguño loro", "piel irritada por ave", "problema dermatológico persistente loro"]'),
('W61.11XA', 'Mordido por guacamayo, contacto inicial', 'Sin especificar', '["mordida de guacamayo", "mordida de papagayo", "picotazo guacamayo", "dedo partido por guacamayo", "herida por guacamayo", "ataque de guacamaya", "me mordió una guacamaya"]'),
('W61.11XD', 'Mordido por guacamayo, contacto sucesivo', 'Sin especificar', '["seguimiento mordida guacamayo", "curación herida guacamaya", "control infección guacamayo", "revisión mordedura grande"]'),
('W61.11XS', 'Mordido por guacamayo, secuela', 'Sin especificar', '["cicatriz guacamayo", "daño nervioso por guacamayo", "secuela mordida grande", "fibrosis por picotazo fuerte"]'),
('W61.12XA', 'Golpeado por guacamayo, contacto inicial', 'Sin especificar', '["golpe de guacamaya", "aletazo de guacamayo", "trompazo de guacamaya", "traumatismo guacamayo", "contusión por ave grande"]'),
('W61.12XD', 'Golpeado por guacamayo, contacto sucesivo', 'Sin especificar', '["revisión contusión guacamayo", "seguimiento golpe ala", "control dolor guacamayo"]'),
('W61.12XS', 'Golpeado por guacamayo, secuela', 'Sin especificar', '["secuela golpe guacamaya", "dolor crónico aletazo", "lesión ósea por guacamayo"]'),
('W61.19XA', 'Otro contacto con guacamayo, contacto inicial', 'Sin especificar', '["arañazo guacamaya", "garra de guacamayo", "rasguño guacamaya", "accidente con guacamayo", "contacto agresivo guacamaya"]'),
('W61.19XD', 'Otro contacto con guacamayo, contacto sucesivo', 'Sin especificar', '["curación rasguño guacamaya", "control arañazo", "revisión dermatológica ave"]'),
('W61.19XS', 'Otro contacto con guacamayo, secuela', 'Sin especificar', '["cicatriz arañazo guacamayo", "secuela contacto ave grande", "lesión piel guacamaya"]'),
('W61.21XA', 'Mordido por otros psitácidos, contacto inicial', 'Sin especificar', '["mordida de periquito", "picotazo de cotorra", "mordida de cacatúa", "mordida de agaporni", "picoteo de ninfa", "mordedura ave psitácida", "me mordió el perico"]'),
('W61.21XD', 'Mordido por otros psitácidos, contacto sucesivo', 'Sin especificar', '["curación mordida perico", "seguimiento picotazo psitácida", "control infección cotorra", "revisión mordida cacatúa"]'),
('W61.21XS', 'Mordido por otros psitácidos, secuela', 'Sin especificar', '["secuela mordida perico", "cicatriz picotazo ave", "lesión persistente psitácida"]'),
('W61.22XA', 'Golpeado por otros psitácidos, contacto inicial', 'Sin especificar', '["golpe de perico", "golpe de cacatúa", "aletazo periquito", "contusión ave exótica", "golpe cotorra"]'),
('W61.22XD', 'Golpeado por otros psitácidos, contacto sucesivo', 'Sin especificar', '["revisión golpe periquito", "control contusión cacatúa", "seguimiento aletazo"]'),
('W61.22XS', 'Golpeado por otros psitácidos, secuela', 'Sin especificar', '["secuela golpe ave pequeña", "dolor residual aletazo perico"]'),
('W61.29XA', 'Otro contacto con otros psitácidos, contacto inicial', 'Sin especificar', '["arañazo perico", "garra de cacatúa", "picada psitácida", "contacto ave exótica"]'),
('W61.29XD', 'Otro contacto con otros psitácidos, contacto sucesivo', 'Sin especificar', '["control herida perico", "seguimiento arañazo psitácida"]'),
('W61.29XS', 'Otro contacto con otros psitácidos, secuela', 'Sin especificar', '["cicatriz garra periquito", "secuela contacto psitácida"]'),
('W61.32XA', 'Golpeado por pollo, contacto inicial', 'Sin especificar', '["golpe de pollo", "aletazo de gallina", "gallinazo", "golpeado por gallo", "contusión gallo", "traumatismo por aves corral"]'),
('W61.32XD', 'Golpeado por pollo, contacto sucesivo', 'Sin especificar', '["revisión golpe gallina", "control aletazo gallo", "seguimiento hematoma pollo"]'),
('W61.32XS', 'Golpeado por pollo, secuela', 'Sin especificar', '["secuela golpe gallináceo", "lesión residual pollo", "dolor crónico ave corral"]'),
('W61.33XA', 'Picoteado por pollo, contacto inicial', 'Sin especificar', '["picotazo de gallina", "picoteado por gallo", "herida por pico de pollo", "me picó el gallo", "picada de gallina"]'),
('W61.33XD', 'Picoteado por pollo, contacto sucesivo', 'Sin especificar', '["curación picotazo gallo", "control herida gallina", "infección por picotazo pollo", "revisión herida corral"]'),
('W61.33XS', 'Picoteado por pollo, secuela', 'Sin especificar', '["cicatriz picotazo gallina", "secuela herida gallo", "fibrosis por pico ave"]'),
('W61.39XA', 'Otro contacto con pollo, contacto inicial', 'Sin especificar', '["arañazo de gallina", "garra de pollo", "espuela de gallo", "accidente con gallo", "contacto gallináceo"]'),
('W61.39XD', 'Otro contacto con pollo, contacto sucesivo', 'Sin especificar', '["revisión rasguño gallina", "control espuela gallo", "seguimiento herida corral"]'),
('W61.39XS', 'Otro contacto con pollo, secuela', 'Sin especificar', '["cicatriz espuela gallo", "secuela arañazo gallina", "lesión persistente gallinácea"]'),
('W61.42XA', 'Golpeado por pavo, contacto inicial', 'Sin especificar', '["golpe de pavo", "aletazo de guajolote", "golpe guajolote", "contusión por pavo", "traumatismo ave grande"]'),
('W61.42XD', 'Golpeado por pavo, contacto sucesivo', 'Sin especificar', '["revisión golpe pavo", "seguimiento contusión guajolote", "control dolor aletazo"]'),
('W61.42XS', 'Golpeado por pavo, secuela', 'Sin especificar', '["secuela golpe pavo", "dolor crónico guajolote", "lesión residual pavo"]'),
('W61.43XA', 'Picoteado por pavo, contacto inicial', 'Sin especificar', '["picotazo de pavo", "picotazo de guajolote", "herida por pico de pavo", "pavo agresivo", "me picó el guajolote"]'),
('W61.43XD', 'Picoteado por pavo, contacto sucesivo', 'Sin especificar', '["curación picotazo pavo", "control herida guajolote", "revisión picadura pavo"]'),
('W61.43XS', 'Picoteado por pavo, secuela', 'Sin especificar', '["cicatriz picotazo pavo", "secuela herida guajolote", "fibrosis pico pavo"]'),
('W61.49XA', 'Otro contacto con pavo, contacto inicial', 'Sin especificar', '["arañazo de pavo", "garra de guajolote", "accidente con guajolote", "contacto agresivo pavo"]'),
('W61.49XD', 'Otro contacto con pavo, contacto sucesivo', 'Sin especificar', '["revisión arañazo pavo", "control herida guajolote", "seguimiento dermatológico pavo"]'),
('W61.49XS', 'Otro contacto con pavo, secuela', 'Sin especificar', '["cicatriz garra pavo", "secuela contacto guajolote", "lesión persistente pavo"]'),
('W61.51XA', 'Mordido por ganso, contacto inicial', 'Sin especificar', '["mordida de ganso", "picotazo de ganso", "ganso agresivo", "me mordió un ganso", "ataque de ganso", "herida ganso"]'),
('W61.51XD', 'Mordido por ganso, contacto sucesivo', 'Sin especificar', '["curación mordida ganso", "control herida ganso", "revisión picotazo ganso"]'),
('W61.51XS', 'Mordido por ganso, secuela', 'Sin especificar', '["cicatriz mordida ganso", "secuela herida ganso", "fibrosis ganso"]'),
('W61.52XA', 'Golpeado por ganso, contacto inicial', 'Sin especificar', '["golpe de ganso", "aletazo de ganso", "traumatismo ganso", "golpe gansos"]'),
('W61.52XD', 'Golpeado por ganso, contacto sucesivo', 'Sin especificar', '["revisión golpe ganso", "seguimiento contusión ganso"]'),
('W61.52XS', 'Golpeado por ganso, secuela', 'Sin especificar', '["secuela golpe ganso", "dolor crónico ganso"]'),
('W61.59XA', 'Otro contacto con ganso, contacto inicial', 'Sin especificar', '["arañazo ganso", "garra ganso", "contacto agresivo ganso"]'),
('W61.59XD', 'Otro contacto con ganso, contacto sucesivo', 'Sin especificar', '["revisión arañazo ganso", "seguimiento piel ganso"]'),
('W61.59XS', 'Otro contacto con ganso, secuela', 'Sin especificar', '["cicatriz ganso", "lesión piel ganso"]'),
('W61.61XA', 'Mordido por pato, contacto inicial', 'Sin especificar', '["mordida de pato", "picotazo pato", "pato agresivo", "herida por pato", "me picó el pato"]'),
('W61.61XD', 'Mordido por pato, contacto sucesivo', 'Sin especificar', '["curación mordida pato", "control herida pato", "revisión picotazo pato"]'),
('W61.61XS', 'Mordido por pato, secuela', 'Sin especificar', '["cicatriz mordida pato", "secuela herida pato"]'),
('W61.62XA', 'Golpeado por pato, contacto inicial', 'Sin especificar', '["golpe de pato", "aletazo pato", "contusión pato", "traumatismo pato"]'),
('W61.62XD', 'Golpeado por pato, contacto sucesivo', 'Sin especificar', '["revisión golpe pato", "seguimiento contusión pato"]'),
('W61.62XS', 'Golpeado por pato, secuela', 'Sin especificar', '["secuela golpe pato", "dolor pato"]'),
('W61.69XA', 'Otro contacto con pato, contacto inicial', 'Sin especificar', '["arañazo pato", "contacto pato", "garra pato"]'),
('W61.69XD', 'Otro contacto con pato, contacto sucesivo', 'Sin especificar', '["control piel pato", "seguimiento arañazo pato"]'),
('W61.69XS', 'Otro contacto con pato, secuela', 'Sin especificar', '["cicatriz pato", "lesión persistente pato"]'),
('W61.91XA', 'Mordido por otras aves, contacto inicial', 'Sin especificar', '["picotazo ave", "mordida ave", "picada ave silvestre", "mordida de pájaro", "pájaro me mordió", "herida pájaro"]'),
('W61.91XD', 'Mordido por otras aves, contacto sucesivo', 'Sin especificar', '["cura picotazo pájaro", "seguimiento herida ave", "control mordida pájaro"]'),
('W61.91XS', 'Mordido por otras aves, secuela', 'Sin especificar', '["cicatriz picotazo pájaro", "secuela herida ave", "fibrosis ave"]'),
('W61.92XA', 'Golpeado por otras aves, contacto inicial', 'Sin especificar', '["golpe ave", "aletazo pájaro", "golpeado por pájaro", "traumatismo ave", "golpe contusión ave"]'),
('W61.92XD', 'Golpeado por otras aves, contacto sucesivo', 'Sin especificar', '["revisión golpe ave", "seguimiento aletazo pájaro", "control contusión ave"]'),
('W61.92XS', 'Golpeado por otras aves, secuela', 'Sin especificar', '["secuela golpe pájaro", "dolor crónico ave"]'),
('W61.99XA', 'Otro contacto con otras aves, contacto inicial', 'Sin especificar', '["arañazo ave", "contacto pájaro", "garra pájaro", "accidente con pájaro", "arañado por ave"]'),
('W61.99XD', 'Otro contacto con otras aves, contacto sucesivo', 'Sin especificar', '["revisión arañazo pájaro", "control piel ave", "seguimiento contacto ave"]'),
('W61.99XS', 'Otro contacto con otras aves, secuela', 'Sin especificar', '["cicatriz pájaro", "lesión piel ave", "secuela contacto ave"]');
