INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('B42.0', 'Esporotricosis pulmonar', 'Sin especificar', '["infección por hongos en los pulmones", "hongo del jardinero en el pulmón", "micosis pulmonar", "tos con hongos", "esporotricosis de los pulmones", "neumonía fúngica", "infección pulmonar por esporotrix", "tos persistente por hongos", "dolor de pecho por micosis", "esporas en los pulmones", "enfermedad del cultivador de rosas pulmonar", "dificultad para respirar por hongo", "micosis profunda pulmonar", "infección de los pulmones por espinas", "esporotricosis sistémica pulmonar"]'),
('B42.1', 'Esporotricosis linfocutánea', 'Sin especificar', '["hongo del jardinero", "enfermedad de la rosa", "llagas por espinas", "bultos en el brazo por hongo", "micosis cutánea", "úlceras por esporotrix", "nódulos en la piel", "infección por jardinería", "rayitas de bultos en la piel", "heridas que no cierran", "esporotricosis de la piel", "hongos en el cuerpo por plantas", "esporotricosis nodular", "infección por manipular rosales", "granos con pus por hongo", "lesiones linfáticas cutáneas"]'),
('B42.7', 'Esporotricosis diseminada', 'Sin especificar', '["esporotricosis generalizada", "infección por hongos por todo el cuerpo", "micosis sistémica", "hongos en la sangre", "esporotricosis grave", "hongo que se extiende", "esporotrix en varios órganos", "infección diseminada por esporas", "micosis diseminada", "esporotricosis multiorgánica", "infección fúngica avanzada", "compromiso sistémico por esporotricosis", "hongos diseminados", "complicaciones de esporotricosis", "infección fúngica sistémica crónica"]'),
('B42.81', 'Esporotricosis cerebral', 'Sin especificar', '["hongo en el cerebro", "micosis cerebral", "meningitis por hongos", "infección fúngica en la cabeza", "esporotricosis del sistema nervioso", "inflamación cerebral por esporotrix", "infección del sistema nervioso central", "esporotricosis meníngea", "dolor de cabeza por hongo", "confusión por micosis", "infección cerebral rara", "micosis del sistema nervioso", "esporas en el cerebro", "complicación cerebral de esporotricosis", "absceso cerebral micótico"]'),
('B42.82', 'Artritis por esporotricosis', 'Sin especificar', '["hongo en las articulaciones", "dolor articular por hongos", "artritis micótica", "inflamación de rodilla por hongo", "esporotricosis articular", "dolor en los huesos por micosis", "infección en las coyunturas", "artritis de origen fúngico", "reuma por esporotrix", "hinchazón de articulaciones por hongo", "sinovitis por esporotricosis", "dolor en las manos por hongo", "esporotricosis ósea y articular", "infección articular por jardinería", "dificultad para mover las articulaciones"]'),
('B42.89', 'Otras formas de esporotricosis', 'Sin especificar', '["esporotricosis atípica", "infecciones raras por esporotrix", "esporotricosis ocular", "infección de órganos internos por hongo", "micosis inusual", "esporotricosis visceral", "otras manifestaciones de esporotricosis", "hongo raro", "variantes de esporotricosis", "esporotricosis extracutánea", "complicaciones raras por esporotrix", "enfermedad fúngica poco común", "esporotricosis de otros tejidos", "formas raras de micosis"]'),
('B42.9', 'Esporotricosis, no especificada', 'Sin especificar', '["infección por esporotrix", "hongo del rosal", "micosis cutánea o profunda", "enfermedad por hongo no clasificada", "sospecha de esporotricosis", "infección por esporas no definida", "hongos en la piel o cuerpo", "esporotricosis sin especificar", "dermatitis micótica", "diagnóstico de esporotricosis", "infección por contacto con plantas", "micosis general", "hongo de jardín", "problema de la piel por hongo", "esporotricosis sospechosa"]');
