INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('R09.01', 'Asfixia', 'Sin especificar', '["ahogo", "falta de aire", "me ahogo", "no puedo respirar", "sofoco", "asfixiarse", "ahogamiento", "aprieto en el pecho", "falta de oxígeno", "asfixia mecánica", "ahorque", "quedarse sin aire", "ahogado", "estrangulamiento", "atragantamiento"]'),
('R09.02', 'Hipoxemia', 'Sin especificar', '["baja oxigenación", "falta de oxigeno en sangre", "saturación baja", "cianosis", "dedos morados", "labios azules", "hipoxia", "niveles bajos de oxígeno", "dificultad para oxigenar", "oxigenación deficiente", "baja saturación", "mal de altura", "falta de aire en la sangre"]'),
('R09.1', 'Pleuritis', 'Sin especificar', '["dolor al respirar", "puntada en el costado", "pleuresía", "dolor pleurítico", "inflamación de la pleura", "dolor en el pecho al inhalar", "pinchazo en el pulmón", "pulmón inflamado", "pinchazo al respirar", "dolor torácico", "dolor de pleura"]'),
('R09.2', 'Paro respiratorio', 'Sin especificar', '["dejar de respirar", "parada respiratoria", "insuficiencia respiratoria aguda", "apnea", "respiración detenida", "colapso respiratorio", "no respira", "paro cardiorrespiratorio", "cese de la respiración", "falla pulmonar aguda"]'),
('R09.3', 'Esputo anómalo', 'Sin especificar', '["flemas", "gargajos", "catarro", "escupir sangre", "hemoptisis", "moco con sangre", "esputo verde", "flemas amarillas", "escupitajo", "flema con sangre", "toser flemas", "expectoración", "tos con moco", "flema pegajosa"]'),
('R09.81', 'Congestión nasal', 'Sin especificar', '["nariz tapada", "nariz obstruida", "nariz tupida", "nariz atrancada", "no puedo respirar por la nariz", "mocos", "nariz trancada", "catarro nasal", "nariz congestionada", "tapón en la nariz", "nariz bloqueda", "resfriado"]'),
('R09.82', 'Goteo posnasal', 'Sin especificar', '["goteo retronasal", "moco en la garganta", "flema que baja por la garganta", "carraspera", "aclarar la garganta", "mucosidad posterior", "sensación de moco en la garganta", "goteo hacia adentro", "goteo nasal posterior", "escurrimiento nasal interno"]'),
('R09.89', 'Otros síntomas y signos especificados que afectan a los aparatos circulatorio y respiratorio', 'Sin especificar', '["dolor de pecho", "palpitaciones", "taquicardia", "opresión en el pecho", "falta de aliento", "ahogos", "dolor precordial", "latidos raros", "molestia al respirar", "sensación de desmayo", "mareo", "cansancio al respirar", "sofocación"]'),
('R09.A0', 'Sensación de cuerpo extraño, sin especificar', 'Sin especificar', '["algo atravesado", "objeto extraño", "sensación de tener algo atorado", "sentir algo adentro", "cuerpo extraño", "objeto atascado", "algo clavado", "sentir algo que no está", "obstrucción"]'),
('R09.A1', 'Sensación de cuerpo extraño, nariz', 'Sin especificar', '["algo en la nariz", "objeto en la nariz", "nariz obstruida por objeto", "me metí algo en la nariz", "sentir algo en la fosa nasal", "nariz atascada", "objeto nasal", "cuerpo extraño en nariz"]'),
('R09.A2', 'Sensación de cuerpo extraño, garganta', 'Sin especificar', '["espina clavada", "algo atorado en la garganta", "bola en la garganta", "sensación de nudo en la garganta", "objeto en la faringe", "comida atascada", "algo clavado en la garganta", "ahogo por cuerpo extraño", "garganta cerrada", "sentir una espina"]'),
('R09.A9', 'Sensación de cuerpo extraño, otra localización', 'Sin especificar', '["objeto extraño en otra parte", "algo metido en la piel", "sentir algo en el oído", "cuerpo extraño en cavidad", "objeto en cavidad corporal", "sensación de objeto ajeno", "algo clavado en algún lugar"]');
