INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('A32.0', 'Listeriosis cutánea', 'Sin especificar', '["infección en la piel por listeria", "ronchas por listeria", "granitos por bacteria", "erupción cutánea bacteriana", "listeriosis de la piel", "manchas en la piel por comida contaminada", "infección dérmica listeria", "llagas por listeria", "bultos en la piel por bacteria", "picazón por listeria", "infección en manos por listeria", "listeriosis cutánea síntomas", "lesión cutánea por bacteria"]'),
('A32.11', 'Meningitis por Listeria', 'Sin especificar', '["meningitis bacteriana", "infección en las meninges", "inflamación del cerebro por listeria", "fiebre y dolor de nuca", "rigidez de cuello por bacteria", "dolor de cabeza fuerte por listeria", "listeria en el sistema nervioso", "meningitis por comida en mal estado", "dolor de nuca", "fotofobia por listeria", "infección cerebral grave", "vómitos y rigidez de nuca", "infección de las meninges por bacteria"]'),
('A32.12', 'Meningoencefalitis por Listeria', 'Sin especificar', '["inflamación de cerebro y meninges", "encefalitis por listeria", "confusión mental por infección", "listeria en el cerebro", "infección del sistema nervioso central", "meningoencefalitis bacteriana", "desorientación por listeria", "fiebre y convulsiones por listeria", "ataque al cerebro por bacteria", "listeriosis neurológica", "inflamación cerebral grave", "problemas de habla por listeria", "estado alterado de conciencia por bacteria"]'),
('A32.7', 'Sepsis por Listeria', 'Sin especificar', '["septicemia por listeria", "infección generalizada por bacteria", "infección en la sangre por listeria", "sepsis bacteriana", "listeria en la sangre", "choque séptico por listeria", "infección grave de todo el cuerpo", "bacteria en el torrente sanguíneo", "fiebre alta por infección general", "intoxicación por listeria grave", "fallo multiorgánico por listeria", "infección sistémica por bacteria", "peligro de muerte por listeria"]'),
('A32.81', 'Listeriosis oculoglandular', 'Sin especificar', '["infección en los ojos por listeria", "ojos rojos e hinchados por bacteria", "listeria conjuntival", "inflamación de ganglios por listeria", "glándulas inflamadas y ojos rojos", "infección ocular bacteriana", "dolor en los ojos y ganglios inflamados", "conjuntivitis por listeria", "ganglios del cuello hinchados por bacteria", "secreción ocular por listeria", "infección glandular por listeria", "ojos lagrimosos e hinchados", "problemas en los ojos y cuello inflamado"]'),
('A32.82', 'Endocarditis por Listeria', 'Sin especificar', '["infección del corazón por listeria", "listeria en las válvulas cardiacas", "endocarditis bacteriana", "inflamación del revestimiento del corazón", "bacteria en el corazón", "dolor en el pecho por listeria", "infección cardiaca", "soplo cardiaco por listeria", "insuficiencia cardiaca por bacteria", "fiebre prolongada y problemas cardiacos", "infección de las válvulas del corazón", "listeriosis cardiaca", "endocarditis por comida contaminada"]'),
('A32.89', 'Otras formas de listeriosis', 'Sin especificar', '["infección rara por listeria", "otras complicaciones por listeria", "formas atípicas de listeriosis", "listeria en otros órganos", "listeriosis diseminada", "infección bacteriana rara", "bacterias en el cuerpo listeria", "complicaciones listeria", "listeriosis no especificada", "enfermedad rara por listeria", "infección de tejidos profundos por listeria", "listeria en los huesos", "infección por listeria extraña"]'),
('A32.9', 'Listeriosis, no especificada', 'Sin especificar', '["tengo listeria", "infección por listeria", "intoxicación por listeria", "bacterias en los alimentos", "diarrea y fiebre por comida", "comí algo contaminado con listeria", "listeriosis", "síntomas de listeria", "infección bacteriana por quesos", "bacteria de la leche cruda", "listeriosis general", "malestar por bacteria en la comida", "infección por alimentos en mal estado"]');
