INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('E78.00', 'Hipercolesterolemia pura, no especificada', 'Sin especificar', '["colesterol alto", "grasa en la sangre", "colesterol elevado", "colesterol malo", "dislipidemia", "niveles altos de colesterol", "grasas en sangre", "hipercolesterolemia", "chequeo colesterol", "problemas de grasas", "colesterol LDL alto", "tengo el colesterol por las nubes", "grasa en las venas", "exceso de colesterol"]'),
('E78.01', 'Hipercolesterolemia familiar', 'Sin especificar', '["colesterol hereditario", "colesterol genético", "colesterol de familia", "hipercolesterolemia genética", "colesterol alto heredado", "problema genético de grasas", "colesterol familiar", "herencia de colesterol alto", "dislipidemia familiar", "riesgo cardíaco familiar", "colesterol que viene de familia"]'),
('E78.1', 'Hiperpergliceridemia pura', 'Sin especificar', '["triglicéridos altos", "triglicéridos elevados", "grasas en sangre", "triglicéridos disparados", "niveles altos de triglicéridos", "exceso de triglicéridos", "problemas de triglicéridos", "grasa en sangre alta", "hipertrigliceridemia", "tengo los triglicéridos altos", "análisis de triglicéridos"]'),
('E78.2', 'Hiperlipidemia mixta', 'Sin especificar', '["colesterol y triglicéridos altos", "dislipidemia mixta", "grasas altas en sangre", "triglicéridos y colesterol elevado", "perfil lipídico alterado", "hiperlipidemia combinada", "grasa total alta", "problemas de lípidos", "colesterol y triglicéridos descontrolados", "análisis de grasas alto"]'),
('E78.3', 'Hiperquilomicronemia', 'Sin especificar', '["exceso de quilomicrones", "quilomicronemia", "grasas muy altas en sangre", "síndrome de quilomicrones altos", "problema de grasas tras comer", "hiperlipidemia severa", "grasa lechosa en sangre", "trastorno lipídico raro", "niveles extremos de lípidos", "pancreatitis por grasas"]'),
('E78.41', 'Elevación de lipoproteína(a)', 'Sin especificar', '["lipoproteína a alta", "LP(a) elevada", "riesgo cardíaco por lipoproteína a", "colesterol genético", "lipoproteína a aumentada", "factor de riesgo cardiovascular", "elevación de LP pequeña a", "problema de lipoproteínas", "estudio de LP(a)"]'),
('E78.49', 'Otros tipos de hiperlipidemia', 'Sin especificar', '["problemas de lípidos raros", "otras dislipidemias", "desordenes metabólicos de grasas", "problemas de colesterol y grasas", "alteraciones lipídicas", "grasa en sangre alta no especificada", "síndromes de exceso de lípidos", "desequilibrio metabólico de grasas"]'),
('E78.5', 'Hiperlipidemia, no especificada', 'Sin especificar', '["grasas altas", "niveles de lípidos altos", "sangre grasa", "perfil lipídico alto", "tengo la sangre cargada de grasa", "exceso de lípidos", "colesterol y triglicéridos", "problemas de grasas en sangre", "dislipidemia", "análisis de lípidos malo"]'),
('E78.6', 'Carencia de lipoproteínas', 'Sin especificar', '["falta de lipoproteínas", "déficit de grasas en sangre", "hipolipidemia", "carencia de lípidos", "trastorno metabólico de grasas", "bajos niveles de lípidos", "problemas por falta de colesterol", "malabsorción de grasas", "deficiencia de lipoproteínas"]'),
('E78.70', 'Trastorno de metabolismo de ácidos biliares y colesterol, no especificado', 'Sin especificar', '["problemas de bilis y colesterol", "metabolismo de colesterol alterado", "problema biliar", "mala digestión de grasas", "trastorno de ácidos biliares", "fallo en procesamiento de colesterol", "digestión pesada por bilis", "problema metabólico biliar"]'),
('E78.71', 'Síndrome de Barth', 'Sin especificar', '["síndrome de Barth", "enfermedad mitocondrial de Barth", "debilidad muscular y corazón", "cardiomiopatía de Barth", "enfermedad genética de Barth", "deficiencia de cardiolipina", "problema de crecimiento infantil", "trastorno genético metabólico"]'),
('E78.72', 'Síndrome de Smith-Lemli-Opitz', 'Sin especificar', '["síndrome de Smith-Lemli-Opitz", "SLOS", "defecto de síntesis de colesterol", "problema genético de metabolismo", "trastorno congénito del colesterol", "retraso en el desarrollo infantil", "malformaciones por falta de colesterol", "mutación de enzima DHCR7"]'),
('E78.79', 'Otros trastornos del metabolismo de ácidos biliares y colesterol', 'Sin especificar', '["trastornos biliares metabólicos", "problemas del colesterol y bilis", "alteración ácidos biliares", "metabolismo hepático alterado", "enfermedades del metabolismo del colesterol", "fallo metabólico biliar"]'),
('E78.81', 'Dermatoartritis lipoidea', 'Sin especificar', '["dermatoartritis lipoidea", "nódulos en piel y articulaciones", "artritis por lípidos", "problemas de piel y grasa", "hinchazón de articulaciones por grasas", "lipidosis cutánea", "dolor articular con depósitos de grasa"]'),
('E78.89', 'Otros trastornos del metabolismo de lipoproteínas', 'Sin especificar', '["trastornos lipídicos raros", "otros problemas de lipoproteínas", "desorden metabólico de grasas", "alteraciones en transporte de lípidos", "enfermedades metabólicas de grasas"]'),
('E78.9', 'Trastorno del metabolismo de las lipoproteínas, no especificado', 'Sin especificar', '["problema metabólico de grasas", "desorden de grasas en sangre", "trastorno de lípidos", "fallo en el metabolismo lipídico", "problemas al procesar grasas", "enfermedad metabólica de lípidos", "análisis de lípidos alterado"]');
