INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('P01.0', 'Recién nacido afectado por incompetencia del cuello uterino', 'Sin especificar', '["cuello uterino corto", "insuficiencia cervical", "cérvix incompetente", "parto prematuro por cuello", "problemas en el útero al nacer", "bebé prematuro cérvix", "cuello del útero débil", "aborto espontáneo previo", "cerclaje fallido", "amenaza de parto", "bebé de alto riesgo", "complicación al nacer", "parto antes de tiempo"]'),
('P01.1', 'Recién nacido afectado por rotura prematura de membranas', 'Sin especificar', '["se rompió la fuente antes", "bolsa rota", "ruptura de aguas", "bebé con bolsa rota", "fuga de líquido amniótico", "parto seco", "membranas rotas", "fuente seca", "se salió el líquido", "parto prematuro fuente", "infección por bolsa rota", "bebé con pérdida de líquido"]'),
('P01.2', 'Recién nacido afectado por oligoamnios', 'Sin especificar', '["poco líquido amniótico", "escasez de líquido", "oligoamnios", "bebé con falta de líquido", "deshidratación fetal", "volumen amniótico bajo", "líquido amniótico disminuido", "poco líquido en la panza", "problemas de riñón bebé", "restricción de crecimiento", "parto con poco líquido"]'),
('P01.3', 'Recién nacido afectado por polihidramnios', 'Sin especificar', '["mucho líquido amniótico", "exceso de líquido amniótico", "polihidramnios", "hidramnios", "panza muy grande", "bebé flota mucho", "exceso de líquido en embarazo", "panza de más", "volumen amniótico alto", "distensión uterina", "bebé con mucho espacio"]'),
('P01.4', 'Recién nacido afectado por embarazo ectópico', 'Sin especificar', '["embarazo fuera de lugar", "embarazo en las trompas", "ectópico", "embarazo extrauterino", "bebé fuera del útero", "trompa rota", "embarazo tubárico", "cirugía por embarazo ectópico", "masa pélvica", "dolor fuerte embarazo", "sangrado embarazo temprano"]'),
('P01.5', 'Recién nacido afectado por embarazo múltiple', 'Sin especificar', '["gemelos", "mellizos", "trillizos", "embarazo doble", "embarazo múltiple", "cuates", "gemelares", "bebé de parto múltiple", "varios bebés en la panza", "parto de alto riesgo", "parto prematuro múltiple", "embarazo de gemelos"]'),
('P01.6', 'Recién nacido afectado por muerte materna', 'Sin especificar', '["muerte de la madre", "madre fallecida al nacer", "orfandad materna", "bebé huérfano al nacer", "bebé post-mortem", "fallecimiento de la mamá", "madre murió en parto", "duelo al nacer", "bebé sin madre", "complicaciones graves parto", "fallecimiento materno"]'),
('P01.7', 'Recién nacido afectado por mala presentación antes del trabajo de parto', 'Sin especificar', '["bebé mal acomodado", "bebé sentado", "bebé de nalgas", "bebé cruzado", "posición podálica", "bebé atravesado", "parto difícil mala posición", "bebé no se encajó", "mal presentación fetal", "parto de nalgas", "cesárea por mala posición"]'),
('P01.8', 'Recién nacido afectado por otras complicaciones maternas del embarazo', 'Sin especificar', '["complicaciones embarazo", "problemas de salud de la madre", "enfermedad materna", "bebé afectado por mamá", "embarazo de riesgo", "toxemia", "diabetes gestacional bebé", "hipertensión embarazo", "anemia en embarazo", "complicaciones del parto", "salud materna", "afectación por mamá"]'),
('P01.9', 'Recién nacido afectado por complicaciones maternas del embarazo, no especificadas', 'Sin especificar', '["problema en el parto", "complicación al nacer", "algo salió mal en el embarazo", "bebé afectado por la madre", "parto complicado", "problemas durante la gestación", "embarazo difícil", "causas maternas", "afectación fetal no clara", "bebé con problemas al nacer", "riesgo al nacer"]');
