INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('D39.0', 'Neoplasia de comportamiento incierto de útero', 'Sin especificar', '["matriz", "útero", "tumor en la matriz", "bolitas en la matriz", "sangrado anormal", "dolor de vientre", "mioma sospechoso", "neoplasia uterina", "dolor bajo", "cáncer de matriz", "masa en útero", "problemas de matriz", "flujo anormal", "cervix", "histerectomía", "células extrañas", "sangrado entre periodos"]'),
('D39.10', 'Neoplasia de comportamiento incierto de ovario no especificado', 'Sin especificar', '["ovarios", "quiste complejo", "tumor ovárico", "dolor de ovarios", "bolitas en los ovarios", "dolor pélvico", "masa pélvica", "neoplasia ovárica", "inflamación de ovarios", "dolor de ovarios", "problemas reproductivos", "quiste sospechoso", "dolor abdominal bajo", "hinchazón de vientre", "irregularidad menstrual", "células anormales en ovario"]'),
('D39.11', 'Neoplasia de comportamiento incierto de ovario derecho', 'Sin especificar', '["ovario derecho", "dolor en el lado derecho", "pinchazos en el ovario", "masa en el lado derecho", "quiste en ovario derecho", "dolor abdominal lado derecho", "neoplasia lado derecho", "ovario derecho inflamado", "molestia pélvica derecha", "células raras ovario derecho", "punzadas lado derecho", "tumor derecho", "dolor bajo vientre derecho", "ovario derecho agrandado"]'),
('D39.12', 'Neoplasia de comportamiento incierto de ovario izquierdo', 'Sin especificar', '["ovario izquierdo", "dolor en el lado izquierdo", "pinchazos en el ovario izquierdo", "masa en el lado izquierdo", "quiste en ovario izquierdo", "dolor abdominal lado izquierdo", "neoplasia lado izquierdo", "ovario izquierdo inflamado", "molestia pélvica izquierda", "células raras ovario izquierdo", "punzadas lado izquierdo", "tumor izquierdo", "dolor bajo vientre izquierdo", "ovario izquierdo agrandado"]'),
('D39.2', 'Neoplasia de comportamiento incierto de placenta', 'Sin especificar', '["placenta", "problemas en la placenta", "embarazo", "tumor en la placenta", "masa placentaria", "neoplasia de placenta", "complicaciones del embarazo", "células anormales placenta", "tejido placentario", "placenta previa", "anomalía de placenta", "placenta enferma", "riesgo en gestación", "crecimiento anormal placenta"]'),
('D39.8', 'Neoplasia de comportamiento incierto de otros órganos genitales femeninos especificados', 'Sin especificar', '["genitales femeninos", "vulva", "vagina", "trompas de falopio", "neoplasia genital", "tumor en zona íntima", "lesión genital", "bolitas en la vagina", "dolor en genitales", "infecciones recurrentes", "masa en vulva", "células raras genitales", "problemas de zona íntima", "neoplasia de trompas", "dolor en la entrepierna"]'),
('D39.9', 'Neoplasia de comportamiento incierto de órgano genital femenino, localización no especificada', 'Sin especificar', '["zona íntima", "partes íntimas", "aparato reproductor femenino", "masa abdominal baja", "dolor pélvico desconocido", "tumor en zona baja", "neoplasia ginecológica", "células anormales zona femenina", "problemas ginecológicos", "dolor en el aparato reproductor", "tumor femenino", "molestia en la zona baja", "neoplasia de origen desconocido femenino"]');
