INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('K62.0', 'Pólipo anal', 'Sin especificar', '["bolita en el ano", "bulto anal", "carne salida", "protuberancia en el culo", "crecimiento anal", "tumor benigno ano", "verruga anal", "bultito al limpiarse", "masa en el esfínter", "sangrado anal", "picazón anal", "dolor al defecar", "inflamación anal", "pólipo en el hoyo", "hemorroide confundida"]'),
('K62.1', 'Pólipo rectal', 'Sin especificar', '["pólipo en el recto", "bulto interno ano", "tumor en el intestino final", "sangre al obrar", "sangre al cagar", "moco en las heces", "sangre roja en papel", "masa en el recto", "dolor rectal", "tenesmo", "ganas constantes de ir al baño", "pólipo intestinal bajo", "pólipo de colon distal", "sangrado rectal", "protrusión rectal"]'),
('K62.2', 'Prolapso anal', 'Sin especificar', '["se me sale el ano", "se me salió la tripa", "ano afuera", "prolapso de esfínter", "tejido saliendo del ano", "cuerpo extraño en el ano", "se me salió el recto", "bulto rojo en el ano", "ano invertido", "dolor al sentarse", "esfínter relajado", "prolapso mucoso", "ano caído", "descolgamiento anal", "hernia anal"]'),
('K62.3', 'Prolapso rectal', 'Sin especificar', '["se me salió el intestino", "recto afuera", "prolapso intestinal", "se me salió el budín", "tripa afuera", "se me salió el recto", "protrusión rectal total", "ano que se voltea", "intestino asomándose", "prolapso de mucosa rectal", "dolor pélvico rectal", "evacuación difícil", "masa rectal", "sensación de pesadez anal", "rectocele"]'),
('K62.4', 'Estenosis de ano y recto', 'Sin especificar', '["ano cerrado", "ano estrecho", "dificultad para obrar", "no puedo cagar", "ano muy apretado", "heces delgadas", "heces en cinta", "estrechez anal", "estrechez rectal", "obstrucción anal", "dolor al evacuar", "esfínter contraído", "ano estrechado", "constipación crónica", "ano cicatrizado"]'),
('K62.5', 'Hemorragia de ano y recto', 'Sin especificar', '["sangre al ir al baño", "sangre en el inodoro", "sangrado rectal", "cagar sangre", "sangre en el papel", "rectorragia", "sangrado anal", "sangre en la caca", "hemorragia rectal", "heces negras", "sangre roja viva", "manchas de sangre en ropa interior", "evacuación sangrienta", "sangrado por el culo", "sangrado de almorranas"]'),
('K62.6', 'Úlcera de ano y de recto', 'Sin especificar', '["llaga en el ano", "herida en el recto", "úlcera rectal", "fisura anal que no cura", "dolor al ir al baño", "ardor en el ano", "picor rectal", "herida sangrante ano", "úlcera solitaria del recto", "escoriación anal", "dolor anal punzante", "sangre y pus en el ano", "irritación rectal", "úlcera anal", "dolor al defecar"]'),
('K62.7', 'Proctitis por radiación', 'Sin especificar', '["inflamación rectal por radioterapia", "daño por rayos en el recto", "dolor anal post radiación", "sangrado rectal por radio", "proctitis radiogénica", "ardor al evacuar radioterapia", "irritación del recto", "escurrimiento mucoso anal", "urgencia para obrar", "tenesmo rectal", "colitis por radiación", "recto irritado", "sangre en heces por radiación", "dolor de ano constante", "daño intestinal por radioterapia"]'),
('K62.81', 'Desgarro de esfínter anal (antiguo) (curado) (no traumático)', 'Sin especificar', '["esfínter roto", "ano rasgado viejo", "incontinencia anal", "desgarro esfínter antiguo", "ano dañado", "cicatriz en el ano", "falta de control anal", "se me escapan los gases", "esfínter debilitado", "desgarro anal de parto", "daño muscular anal", "esfínter insuficiente", "ano que no cierra bien", "lesión esfinteriana antigua", "incontinencia fecal"]'),
('K62.82', 'Displasia de ano', 'Sin especificar', '["lesiones precancerosas ano", "verrugas anales", "VPH ano", "células anormales ano", "displasia anal", "lesión anal por virus", "manchas en el ano", "inflamación persistente ano", "biopsia anal anormal", "precáncer anal", "infección ano VPH", "condilomas anales", "crecimiento celular anal", "lesiones anales sospechosas", "cambios celulares ano"]'),
('K62.89', 'Otras enfermedades especificadas de ano y recto', 'Sin especificar', '["problemas del ano", "dolencia rectal", "mal del recto", "enfermedad ano", "molestias anales", "cuerpo extraño en el recto", "inflamación ano", "dolor rectal inexplicable", "afección anal rara", "padecimientos del ano", "problemas de recto", "irritación anal", "bultos anales", "comezón anal crónica", "recto irritado"]'),
('K62.9', 'Enfermedad de ano y recto, no especificada', 'Sin especificar', '["mal del culo", "dolor en el ano", "molestia en el recto", "problemas para obrar", "dolor anal", "irritación en el hoyo", "urgencia rectal", "pesadez en el recto", "picazón en el ano", "dolor al sentarse", "molestias en el esfínter", "incomodidad anal", "afección rectal", "no sé qué tengo en el ano", "problema de ano"]');
