INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('G82.20', 'Paraplejia, no especificada', 'Sin especificar', '["paraplejia", "piernas paralizadas", "no puedo mover las piernas", "parálisis de cintura para abajo", "inmovilidad de miembros inferiores", "falta de movilidad piernas", "pérdida de sensibilidad en piernas", "medula lesionada piernas", "paralítico", "incapacidad de caminar", "piernas muertas", "no siento las piernas", "lesión medular", "parapléjico", "problemas de movilidad inferior"]'),
('G82.21', 'Paraplejia completa', 'Sin especificar', '["paraplejia total", "parálisis total miembros inferiores", "cero movilidad piernas", "paraplejia completa", "lesión medular total", "no muevo nada de la cintura para abajo", "parapléjico completo", "pérdida absoluta de movimiento piernas", "parálisis motora irreversible", "sin respuesta en las piernas", "bloqueo motor inferior", "invalidez de piernas", "paraplejia grado completo", "lesión medular definitiva"]'),
('G82.22', 'Paraplejia incompleta', 'Sin especificar', '["paraplejia parcial", "poca movilidad en las piernas", "parálisis incompleta", "puedo mover un poco las piernas", "paraplejia leve", "sensibilidad parcial en piernas", "movimiento limitado miembros inferiores", "lesión medular incompleta", "parapléjico con algo de respuesta", "recuperación parcial piernas", "parálisis no total de piernas", "debilidad extrema en piernas", "paraplejia grado incompleto"]'),
('G82.50', 'Tetraplejia, no especificada', 'Sin especificar', '["tetraplejia", "cuadriplejia", "parálisis de los cuatro miembros", "no puedo mover brazos ni piernas", "cuerpo paralizado", "parálisis de cuello para abajo", "tetrapléjico", "cuadripléjico", "sin movimiento en cuerpo", "inmovilidad total corporal", "lesión cervical", "no muevo extremidades", "problemas de movilidad general", "parálisis total"]'),
('G82.51', 'Tetraplejia, C1-C4 completa', 'Sin especificar', '["tetraplejia cervical alta", "lesión C1 C4 completa", "parálisis total cuello cabeza brazos piernas", "tetraplejia severa", "cuadriplejia completa alta", "parálisis de cuello hacia abajo", "inmovilidad absoluta", "lesión medular alta", "tetrapléjico dependiente total", "sin movilidad nivel cervical", "bloqueo motor cuello a pies", "cuadripléjico nivel C1 C4"]'),
('G82.52', 'Tetraplejia, C1-C4 incompleta', 'Sin especificar', '["tetraplejia cervical incompleta", "lesión C1 C4 parcial", "algo de movimiento en brazos", "tetraplejia con sensibilidad residual", "cuadriplejia parcial", "lesión medular alta incompleta", "parálisis parcial cuello abajo", "movimiento limitado manos brazos", "tetrapléjico con poca respuesta", "mejora post lesión cervical", "cuadripléjico nivel C1 C4 incompleto"]'),
('G82.53', 'Tetraplejia, C5-C7 completa', 'Sin especificar', '["tetraplejia cervical baja", "lesión C5 C7 completa", "parálisis de cuello a pies", "cuadriplejia nivel C5 C7", "tetrapléjico completo brazos y piernas", "parálisis total bajo nivel cervical", "inmovilidad desde el pecho", "lesión medular media", "bloqueo motriz total extremidades", "cuadripléjico severo C5 C7", "sin respuesta brazos piernas"]'),
('G82.54', 'Tetraplejia, C5-C7 incompleta', 'Sin especificar', '["tetraplejia cervical baja incompleta", "lesión C5 C7 incompleta", "puedo mover algo los brazos", "cuadriplejia parcial C5 C7", "tetraplejia con algo de fuerza en manos", "lesión medular media parcial", "recuperación parcial tras tetraplejia", "tetrapléjico con sensibilidad restos", "movilidad limitada brazos y piernas", "parálisis incompleta nivel cervical bajo"]');
