INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('Z94.0', 'Estado de trasplante renal', 'Sin especificar', '["trasplante de riñón", "riñón nuevo", "operación de riñón", "donante de riñón", "insuficiencia renal trasplante", "post-trasplante renal", "falla renal operada", "riñón trasplantado", "cirugía de riñón", "diálisis superada", "seguimiento trasplante renal", "donación de riñón", "paciente renal trasplantado", "inmunosupresión renal", "rejunte de riñón"]'),
('Z94.1', 'Estado de trasplante de corazón', 'Sin especificar', '["trasplante de corazón", "corazón nuevo", "operación de corazón", "corazón trasplantado", "donante de corazón", "post-trasplante cardíaco", "cirugía de trasplante cardíaco", "falla cardíaca operada", "corazón cambiado", "seguimiento cardiológico", "donación cardíaca", "paciente con trasplante", "inmunosupresión cardíaca", "trasplantado del corazón", "trasplante de órgano vital"]'),
('Z94.2', 'Estado de trasplante de pulmón', 'Sin especificar', '["trasplante de pulmón", "pulmón nuevo", "operación de pulmón", "donante pulmonar", "post-trasplante pulmonar", "cirugía de pulmón", "pulmones trasplantados", "falla respiratoria trasplante", "donación de pulmón", "trasplantado de pulmón", "inmunosupresión pulmonar", "seguimiento respiratorio", "pulmón cambiado", "operación de tórax", "paciente trasplantado pulmón"]'),
('Z94.3', 'Estado de trasplante de corazón y pulmones', 'Sin especificar', '["trasplante cardiopulmonar", "doble trasplante", "corazón y pulmones nuevos", "operación de pecho", "cirugía mayor trasplante", "donación múltiple", "post-trasplante conjunto", "trasplantado de corazón y pulmón", "falla multiorgánica torácica", "seguimiento complejo", "inmunosupresión doble", "corazón y pulmones trasplantados", "trasplante combinado", "operación de trasplante doble", "donantes de órganos torácicos"]'),
('Z94.4', 'Estado de trasplante de hígado', 'Sin especificar', '["trasplante de hígado", "hígado nuevo", "operación de hígado", "trasplante hepático", "donante hepático", "post-trasplante hepático", "cirugía de hígado", "hígado trasplantado", "fallo hepático trasplante", "donación de hígado", "paciente hepático", "inmunosupresión hepática", "hígado cambiado", "trasplantado del hígado", "seguimiento hepatológico"]'),
('Z94.5', 'Estado de trasplante de piel', 'Sin especificar', '["trasplante de piel", "injerto de piel", "operación de piel", "autoinjerto", "aloingerto piel", "post-trasplante cutáneo", "quemaduras trasplante", "cirugía reconstructiva piel", "piel nueva", "reconstrucción cutánea", "donación de piel", "banco de piel", "inmunosupresión injerto", "piel trasplantada", "tratamiento de quemaduras"]'),
('Z94.6', 'Estado de trasplante de hueso', 'Sin especificar', '["trasplante de hueso", "injerto óseo", "operación de huesos", "implante óseo", "donante de hueso", "post-trasplante óseo", "cirugía ortopédica", "hueso trasplantado", "reconstrucción ósea", "banco de huesos", "donación ósea", "injerto de tejido óseo", "cirugía de injerto", "fijación ósea", "regeneración ósea"]'),
('Z94.7', 'Estado de trasplante de córnea', 'Sin especificar', '["trasplante de córnea", "operación de ojos", "córnea nueva", "queratoplastia", "trasplante corneal", "donante de córnea", "post-trasplante de ojo", "cirugía ocular", "donación de ojos", "córnea trasplantada", "operación de vista", "trasplantado de córnea", "banco de ojos", "reparación corneal", "ojo operado"]'),
('Z94.81', 'Estado de trasplante de médula ósea', 'Sin especificar', '["trasplante de médula", "médula ósea trasplantada", "trasplante hematopoyético", "donante de médula", "operación de sangre", "leucemia trasplante", "post-trasplante médula", "médula nueva", "células madre trasplante", "donación de médula", "inmunosupresión médula", "trasplantado de médula", "procedimiento hematológico", "trasplante autólogo", "trasplante alogénico"]'),
('Z94.82', 'Estado de trasplante de intestino', 'Sin especificar', '["trasplante de intestino", "trasplante intestinal", "operación de tripas", "donante intestinal", "intestino trasplantado", "post-trasplante intestinal", "cirugía digestiva mayor", "falla intestinal trasplante", "donación de intestino", "trasplantado intestinal", "inmunosupresión intestinal", "seguimiento digestivo", "intestino nuevo", "operación abdominal trasplante", "problemas de absorción trasplante"]'),
('Z94.83', 'Estado de trasplante de páncreas', 'Sin especificar', '["trasplante de páncreas", "páncreas nuevo", "operación de páncreas", "trasplante pancreático", "donante pancreático", "post-trasplante páncreas", "diabetes trasplante", "páncreas trasplantado", "cirugía de páncreas", "donación de páncreas", "inmunosupresión pancreática", "trasplantado de páncreas", "seguimiento diabético", "falla pancreática", "operación páncreas riñón"]'),
('Z94.84', 'Estado de trasplante de células madre', 'Sin especificar', '["trasplante de células madre", "terapia células madre", "células progenitoras", "inyección células madre", "regeneración celular", "trasplante stem cells", "post-trasplante células", "tratamiento celular", "trasplantado de células", "donación células madre", "inmunosupresión celular", "infusión de células madre", "medicina regenerativa", "trasplante hematopoyético", "procedimiento células madre"]'),
('Z94.89', 'Estado de trasplante de otros órganos y tejidos trasplantados', 'Sin especificar', '["trasplante de otros órganos", "trasplante tejido variado", "cirugía de implante", "trasplante de mano", "trasplante de cara", "trasplante de útero", "donación de tejidos", "operación de tejido", "trasplantado complejo", "post-trasplante otros", "órgano trasplantado raro", "inmunosupresión tejido", "seguimiento quirúrgico", "cirugía reconstructiva", "tejido nuevo"]'),
('Z94.9', 'Estado de órgano y tejido trasplantado, no especificado', 'Sin especificar', '["trasplante general", "persona trasplantada", "operado de trasplante", "paciente con órgano nuevo", "post-cirugía trasplante", "seguimiento de trasplante", "inmunosupresión general", "donación de órgano", "trasplantado desconocido", "historial de trasplante", "medicación post-trasplante", "vida tras el trasplante", "estado de trasplantado", "cirugía de trasplante", "paciente receptor"]');
