INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('J34.0', 'Absceso, forúnculo y carbunco de la nariz', 'Sin especificar', '["grano en la nariz", "espinilla infectada", "nacido en la nariz", "furúnculo nasal", "infección en la nariz", "absceso nasal", "bolita con pus", "flemón en la nariz", "grano enterrado", "carbunco nasal", "nariz hinchada", "dolor en la punta de la nariz", "infección folicular", "grano doloroso", "inflamación nasal"]'),
('J34.1', 'Quiste y mucocele de la nariz y de los senos nasales', 'Sin especificar', '["quiste nasal", "bolita en la nariz", "mucocele", "quiste en los senos paranasales", "bulto en la nariz", "acumulación de moco", "quiste de retención", "quiste sinusal", "nariz tapada por bulto", "protuberancia interna", "sinusitis quística", "bolita en el tabique", "bulto en el seno maxilar", "tumor benigno nariz", "obstrucción por quiste"]'),
('J34.2', 'Tabique nasal desviado', 'Sin especificar', '["tabique chueco", "nariz torcida", "desviación del tabique", "tabique desviado", "nariz tabicada", "no puedo respirar por un lado", "tabique roto", "tabique desviado congénito", "septum desviado", "nariz operada", "problemas para respirar", "nariz obstruida", "tabique nasal asimétrico", "ronquidos por nariz", "caballete desviado"]'),
('J34.3', 'Hipertrofia de los cornetes nasales', 'Sin especificar', '["cornetes inflamados", "cornetes grandes", "nariz tapada", "hipertrofia de cornetes", "cornetes hipertróficos", "obstrucción nasal crónica", "nariz congestionada siempre", "problemas de cornetes", "respiración difícil", "rinitis persistente", "nariz obstruida por carnosidades", "inflamación de los cornetes", "turbinatos grandes", "no entra aire por la nariz", "carnosidades en la nariz"]'),
('J34.81', 'Mucositis nasal (ulcerosa)', 'Sin especificar', '["llagas en la nariz", "heridas en la nariz", "nariz irritada", "úlceras nasales", "costras en la nariz", "mucositis ulcerativa", "nariz con sangre", "dolor al respirar", "resequedad extrema nariz", "quemazón en la nariz", "heridas internas en la nariz", "nariz lastimada", "inflamación de la mucosa nasal", "úlcera del tabique", "nariz erosionada"]'),
('J34.8200', 'Colapso de válvula nasal interna, no especificado', 'Sin especificar', '["colapso nasal", "nariz que se cierra", "problemas de válvula nasal", "no puedo respirar al inhalar", "obstrucción valvular", "nariz colapsada", "dificultad al inspirar", "obstrucción nasal interna", "colapso de la válvula", "nariz que se chupa al respirar", "insuficiencia valvular nasal", "mala entrada de aire", "nariz estrecha", "problema funcional de nariz", "obstrucción de válvula"]'),
('J34.8201', 'Colapso de válvula nasal interna, estático', 'Sin especificar', '["nariz estrecha constante", "colapso valvular fijo", "obstrucción nasal estática", "válvula nasal estrecha", "nariz sin fuerza para respirar", "colapso interno permanente", "estrechez nasal", "válvula nasal rígida", "obstrucción por falta de soporte", "colapso nasal mecánico", "bloqueo de aire nasal", "problema estructural de nariz", "insuficiencia respiratoria nasal", "tabique estrecho", "colapso de válvula fija"]'),
('J34.8202', 'Colapso de válvula nasal interna, dinámico', 'Sin especificar', '["nariz que se cierra al respirar", "colapso al inhalar", "válvula nasal débil", "colapso dinámico de nariz", "nariz que se colapsa con la respiración", "obstrucción inspiratoria", "nariz que se contrae al inhalar", "insuficiencia valvular al respirar", "colapso nasal funcional", "se me cierra la nariz al inspirar", "problema de pared nasal", "flacidez nasal", "colapso al hacer ejercicio", "obstrucción por aspiración", "debilidad de la válvula"]'),
('J34.8210', 'Colapso de válvula nasal externa, no especificado', 'Sin especificar', '["colapso alar", "nariz que se colapsa", "aletas nasales débiles", "colapso externo nasal", "obstrucción por aletas nasales", "nariz débil", "aletas que se pegan al respirar", "colapso nasal", "problema de aletas de la nariz", "insuficiencia valvular externa", "obstrucción externa", "nariz que no abre al respirar", "debilidad alar", "nariz que se chupa", "colapso de aleta nasal"]'),
('J34.8211', 'Colapso de válvula nasal externa, estático', 'Sin especificar', '["aletas nasales cerradas", "colapso alar fijo", "nariz estrecha externa", "obstrucción nasal externa permanente", "aletas nasales rígidas y estrechas", "estrechez de la fosa nasal", "colapso nasal estático", "falta de apertura nasal", "obstrucción fija", "nariz con poca entrada de aire", "malformación valvular externa", "aletas sin soporte", "colapso estructural externo", "obstrucción de válvula externa", "nariz pequeña y tapada"]'),
('J34.8212', 'Colapso de válvula nasal externa, dinámico', 'Sin especificar', '["aletas que se cierran al inhalar", "colapso alar al respirar", "nariz que se chupa al inspirar", "obstrucción dinámica externa", "debilidad de aletas nasales", "aletas nasales que se colapsan", "colapso al hacer fuerza", "insuficiencia inspiratoria", "se me cierran los huecos de la nariz", "colapso nasal por respiración", "aletas nasales flácidas", "obstrucción al inhalar fuerte", "colapso externo funcional", "nariz que se contrae", "problema alar dinámico"]'),
('J34.829', 'Colapso de válvula nasal, sin especificar', 'Sin especificar', '["nariz colapsada", "no puedo respirar bien", "problema de válvulas nasales", "colapso nasal", "obstrucción al respirar", "problemas de respiración nasal", "nariz que se cierra", "válvulas nasales débiles", "insuficiencia nasal", "se me tapa la nariz al respirar", "nariz que falla", "obstrucción de la vía aérea", "problema valvular", "nariz obstruida", "colapso de la vía aérea nasal"]'),
('J34.89', 'Otras enfermedades especificadas de la nariz y de los senos nasales', 'Sin especificar', '["problemas nasales", "enfermedades de la nariz", "molestias en los senos paranasales", "problemas de los senos", "dolor nasal", "infección nasal", "nariz irritada", "problemas de mucosa", "obstrucción nasal", "inflamación de senos nasales", "problemas de nariz y senos", "dolor de cara por nariz", "malestar en la nariz", "nariz inflamada", "problemas sinusal"]'),
('J34.9', 'Enfermedades no especificadas de la nariz y de los senos nasales', 'Sin especificar', '["problema de nariz", "malestar en la nariz", "nariz tapada", "dolor de nariz", "enfermedad nasal no diagnosticada", "qué tengo en la nariz", "molestia en los senos", "problema sinusal", "nariz congestionada", "dificultad al respirar por nariz", "nariz rara", "dolor en la nariz inexplicable", "problema desconocido nariz", "nariz inflamada sin razón", "incomodidad nasal"]');
