INSERT INTO catalogo_cie10 (codigo_cie10, termino_medico, capitulo, keywords)
VALUES 
('H94.00', 'Neuritis acústica en enfermedades infecciosas y parasitarias clasificadas bajo otro concepto, oído no especificado', 'Sin especificar', '["zumbido en los oídos", "pitido en el oído", "tinnitus", "dolor de oído", "inflamación del nervio auditivo", "oído tapado", "sordera repentina", "pérdida auditiva", "ruido en la cabeza", "infección en el oído", "vértigo", "mareos", "problemas de audición", "acúfenos", "nervio auditivo inflamado", "pinchazos en el oído"]'),
('H94.01', 'Neuritis acústica en enfermedades infecciosas y parasitarias clasificadas bajo otro concepto, oído derecho', 'Sin especificar', '["dolor en oído derecho", "zumbido lado derecho", "pitido oído derecho", "inflamación nervio auditivo derecho", "oído derecho tapado", "sordera oído derecho", "tinnitus derecho", "acúfeno derecho", "mareo por oído derecho", "infección oído derecho", "ruido en el lado derecho de la cabeza", "pinchazos en el oído derecho", "problema auditivo derecho", "oído derecho adolorido"]'),
('H94.02', 'Neuritis acústica en enfermedades infecciosas y parasitarias clasificadas bajo otro concepto, oído izquierdo', 'Sin especificar', '["dolor en oído izquierdo", "zumbido lado izquierdo", "pitido oído izquierdo", "inflamación nervio auditivo izquierdo", "oído izquierdo tapado", "sordera oído izquierdo", "tinnitus izquierdo", "acúfeno izquierdo", "mareo por oído izquierdo", "infección oído izquierdo", "ruido en el lado izquierdo de la cabeza", "pinchazos en el oído izquierdo", "problema auditivo izquierdo", "oído izquierdo adolorido"]'),
('H94.03', 'Neuritis acústica en enfermedades infecciosas y parasitarias clasificadas bajo otro concepto, bilateral', 'Sin especificar', '["zumbidos en ambos oídos", "pitidos en los dos oídos", "sordera bilateral", "dolor de oídos", "tinnitus en ambos lados", "problemas de audición graves", "acúfenos bilaterales", "mareos fuertes", "vértigos constantes", "infección auditiva doble", "inflamación de nervios auditivos", "ruido constante en la cabeza", "oídos tapados", "pinchazos en ambos oídos"]'),
('H94.80', 'Otros trastornos especificados del oído en enfermedades clasificadas bajo otro concepto, oído no especificado', 'Sin especificar', '["molestias en el oído", "dolor de oído", "oído inflamado", "picazón en el oído", "sensación de oído tapado", "cerumen", "tapón de cera", "secreción en el oído", "supuración del oído", "oído con agua", "infección auditiva", "oído lastimado", "oído irritado", "problemas de oído", "dolor al tocarse el oído"]'),
('H94.81', 'Otros trastornos especificados del oído en enfermedades clasificadas bajo otro concepto, oído derecho', 'Sin especificar', '["dolor en el oído derecho", "oído derecho tapado", "picazón oído derecho", "infección en oído derecho", "secreción oído derecho", "oído derecho con agua", "oído derecho irritado", "problema en oído derecho", "cerilla en oído derecho", "oído derecho lastimado", "dolor al acostarse sobre lado derecho", "pinchazo en oído derecho", "oído derecho hinchado"]'),
('H94.82', 'Otros trastornos especificados del oído en enfermedades clasificadas bajo otro concepto, oído izquierdo', 'Sin especificar', '["dolor en el oído izquierdo", "oído izquierdo tapado", "picazón oído izquierdo", "infección en oído izquierdo", "secreción oído izquierdo", "oído izquierdo con agua", "oído izquierdo irritado", "problema en oído izquierdo", "cerilla en oído izquierdo", "oído izquierdo lastimado", "dolor al acostarse sobre lado izquierdo", "pinchazo en oído izquierdo", "oído izquierdo hinchado"]'),
('H94.83', 'Otros trastornos especificados del oído en enfermedades clasificadas bajo otro concepto, bilateral', 'Sin especificar', '["dolor en los dos oídos", "ambos oídos tapados", "infección en ambos oídos", "oídos con agua", "picazón en ambos oídos", "problemas auditivos generales", "oídos irritados", "secreción en los oídos", "cerumen excesivo", "oídos lastimados", "dolor punzante en ambos oídos", "molestias auditivas bilaterales", "oídos hinchados"]');
